"""Shape: intake_img_cr —
    IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor.

User uploads a reference image (character / setting) + asks for a full mini-drama built around it. No audio overlay. (Path B alignment with v3 eval — opt-in audio: chain has Music/Ambience/AudioMix iff user_goal explicitly mentions audio.)
"""
from __future__ import annotations

SAMPLES: list[dict] = [
    {
        "user_goal": "Using this uploaded character portrait, produce an epic cultivation-fantasy mini-drama where the protagonist awakens an ancient bloodline.",
        "rationale": "User uploaded a character reference image + asks for a cultivation-fantasy mini-drama. IntakeImageAgent ingests the portrait. StoryAgent writes a story around the character. ScreenplayAgent breaks it into scenes. KeyFrameAgent designs key frames. VideoAgent renders motion clips. baked-in audio. CompositorAgent assembles the final film. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded character portrait into the workspace as the visual reference.",
            "Enrich the character brief combining the image features with the cultivation-fantasy concept.",
            "Write a cultivation-fantasy story where the protagonist awakens an ancient bloodline.",
            "Break the story into cinematic scenes with beats and dialogue.",
            "Design key frames for each scene matching the uploaded character's likeness.",
            "Render motion-video clips from the key frames preserving the character's continuity.",
            "Compose the final cultivation-fantasy mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded seaside photo, make a tragic costume-drama mini-drama where the female lead sacrifices herself under the sea for the male lead.",
        "rationale": "Seaside photo reference + tragic costume drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded seaside photo into the workspace as the visual reference.",
            "Enrich the setting brief combining the seaside atmosphere with the costume-drama concept.",
            "Write a tragic costume-drama story where the female lead sacrifices herself for the male lead.",
            "Break the story into scenes emphasizing the seaside sacrifice climax.",
            "Design key frames for each scene matching the uploaded seaside setting.",
            "Render motion-video clips preserving the seaside environment.",
            "Compose the final costume-drama mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Use the character from this uploaded image as the hero of a one-minute cyberpunk hacker mini-drama.",
        "rationale": "Character image + cyberpunk hacker drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded character image into the workspace as the visual reference.",
            "Enrich the character brief combining the image features with the cyberpunk-hacker concept.",
            "Write a one-minute cyberpunk hacker story around the uploaded character.",
            "Break the story into taut hacker-drama scenes with beats.",
            "Design key frames for each scene matching the uploaded character's cyberpunk look.",
            "Render motion-video clips preserving the cyberpunk character continuity.",
            "Compose the final cyberpunk mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded photo of an old mansion, make a haunted-house mystery mini-drama where a new tenant discovers a ghost.",
        "rationale": "Old-mansion photo + haunted-house mystery. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded old-mansion photo into the workspace as the visual reference.",
            "Enrich the setting brief combining the mansion atmosphere with the haunted-house concept.",
            "Write a haunted-house mystery story where a new tenant discovers a ghost.",
            "Break the story into scenes emphasizing the mansion's haunted atmosphere.",
            "Design key frames matching the uploaded mansion architecture.",
            "Render motion-video clips preserving the mansion's visual identity.",
            "Compose the final haunted-house mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Take the person in this uploaded photo as the protagonist and make a rebirth-themed mini-drama about her waking up ten years before her lover's death.",
        "rationale": "Person photo + rebirth drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded person photo into the workspace as the visual reference.",
            "Enrich the character brief combining the person's features with the rebirth concept.",
            "Write a rebirth mini-drama where the protagonist wakes up ten years before her lover's death.",
            "Break the story into rebirth-drama scenes with emotional beats.",
            "Design key frames for each scene matching the uploaded person's likeness.",
            "Render motion-video clips preserving the protagonist's continuity.",
            "Compose the final rebirth mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a forest, make a mystical druid mini-drama where an ancient guardian awakens.",
        "rationale": "Forest image + mystical druid drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded forest image into the workspace as the visual reference.",
            "Enrich the setting brief combining the forest atmosphere with the druid concept.",
            "Write a mystical druid mini-drama where an ancient guardian awakens in the forest.",
            "Break the story into druid-drama scenes with mystical beats.",
            "Design key frames matching the uploaded forest setting.",
            "Render motion-video clips preserving the forest's visual identity.",
            "Compose the final druid mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this character portrait of a detective, make a noir-style mystery mini-drama about solving a cold case.",
        "rationale": "Detective portrait + noir mystery. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded detective portrait into the workspace as the visual reference.",
            "Enrich the character brief combining the detective's features with the noir concept.",
            "Write a noir-style cold-case mystery mini-drama around the uploaded detective.",
            "Break the story into noir-mystery scenes with investigative beats.",
            "Design key frames for each scene matching the uploaded detective's likeness.",
            "Render motion-video clips preserving the detective's continuity.",
            "Compose the final noir mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded castle photo, make a fantasy princess mini-drama where she escapes an arranged marriage.",
        "rationale": "Castle photo + fantasy princess drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded castle photo into the workspace as the visual reference.",
            "Enrich the setting brief combining the castle atmosphere with the princess-escape concept.",
            "Write a fantasy princess mini-drama where she escapes an arranged marriage.",
            "Break the story into princess-escape scenes inside the castle.",
            "Design key frames matching the uploaded castle architecture.",
            "Render motion-video clips preserving the castle's visual identity.",
            "Compose the final princess mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded portrait of a samurai, make a sengoku-era revenge mini-drama.",
        "rationale": "Samurai portrait + sengoku revenge drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded samurai portrait into the workspace as the visual reference.",
            "Enrich the character brief combining the samurai's features with the sengoku-revenge concept.",
            "Write a sengoku-era revenge mini-drama around the uploaded samurai.",
            "Break the story into sengoku-drama scenes with revenge beats.",
            "Design key frames for each scene matching the uploaded samurai's likeness.",
            "Render motion-video clips preserving the samurai character continuity.",
            "Compose the final sengoku mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded photo of a desert landscape, make a post-apocalyptic survivor mini-drama.",
        "rationale": "Desert landscape photo + post-apocalyptic drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded desert-landscape photo into the workspace as the visual reference.",
            "Enrich the setting brief combining the desert atmosphere with the post-apocalyptic concept.",
            "Write a post-apocalyptic survivor mini-drama set in the uploaded desert landscape.",
            "Break the story into survivor-drama scenes across the wasteland.",
            "Design key frames matching the uploaded desert setting.",
            "Render motion-video clips preserving the desert's visual identity.",
            "Compose the final post-apocalyptic mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Victorian parlor, make a Gothic-romance mini-drama about a cursed family heirloom.",
        "rationale": "Victorian-parlor image + Gothic romance. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Victorian-parlor image into the workspace as the visual reference.",
            "Enrich the setting brief combining the parlor atmosphere with the Gothic-romance concept.",
            "Write a Gothic-romance mini-drama about a cursed family heirloom.",
            "Break the story into Gothic-romance scenes inside the Victorian parlor.",
            "Design key frames matching the uploaded parlor decor.",
            "Render motion-video clips preserving the parlor's visual identity.",
            "Compose the final Gothic mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded photo of a mountain monastery, make a wuxia mini-drama about a disciple's vengeance.",
        "rationale": "Mountain-monastery photo + wuxia vengeance drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded mountain-monastery photo into the workspace as the visual reference.",
            "Enrich the setting brief combining the monastery with the wuxia-vengeance concept.",
            "Write a wuxia mini-drama about a disciple's vengeance set at the monastery.",
            "Break the story into wuxia scenes inside and around the monastery.",
            "Design key frames matching the uploaded monastery architecture.",
            "Render motion-video clips preserving the monastery's visual identity.",
            "Compose the final wuxia mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded portrait of a scientist, make a near-future AI-emerges mini-drama.",
        "rationale": "Scientist portrait + AI-emerges drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded scientist portrait into the workspace as the visual reference.",
            "Enrich the character brief combining the scientist's features with the AI-emerges concept.",
            "Write a near-future AI-emerges mini-drama around the uploaded scientist.",
            "Break the story into sci-fi scenes emphasizing the AI awakening moment.",
            "Design key frames for each scene matching the uploaded scientist's likeness.",
            "Render motion-video clips preserving the scientist's continuity.",
            "Compose the final AI-emerges mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a pirate ship deck, make a pirate-adventure mini-drama about a hidden treasure.",
        "rationale": "Pirate-ship-deck image + pirate-adventure drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded pirate-ship-deck image into the workspace as the visual reference.",
            "Enrich the setting brief combining the pirate-ship atmosphere with the adventure concept.",
            "Write a pirate-adventure mini-drama about a hidden treasure.",
            "Break the story into pirate-adventure scenes on the deck.",
            "Design key frames matching the uploaded pirate-ship architecture.",
            "Render motion-video clips preserving the pirate-ship's visual identity.",
            "Compose the final pirate mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a snowy village, make a heartwarming Christmas miracle mini-drama.",
        "rationale": "Snowy-village image + Christmas miracle drama + gentle holiday-bells. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded snowy-village image into the workspace as the visual reference.",
            "Enrich the setting brief combining the snowy-village atmosphere with the Christmas-miracle concept.",
            "Write a heartwarming Christmas-miracle mini-drama set in the uploaded snowy village.",
            "Break the story into holiday-drama scenes around the village.",
            "Design key frames matching the uploaded snowy-village setting.",
            "Render motion-video clips preserving the village's visual identity.",
            "Compose the final Christmas mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Parisian café, make a romantic mini-drama where two old friends reconnect.",
        "rationale": "Parisian-café image + romantic reconnection drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Parisian-café image into the workspace as the visual reference.",
            "Enrich the setting brief combining the café atmosphere with the reconnection concept.",
            "Write a romantic mini-drama where two old friends reconnect at the café.",
            "Break the story into romantic-reconnection scenes inside and around the café.",
            "Design key frames matching the uploaded Parisian-café decor.",
            "Render motion-video clips preserving the café's visual identity.",
            "Compose the final romantic mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded photo of a Japanese garden, make a contemplative monk-apprentice mini-drama.",
        "rationale": "Japanese-garden photo + monk-apprentice drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Japanese-garden photo into the workspace as the visual reference.",
            "Enrich the setting brief combining the garden atmosphere with the monk-apprentice concept.",
            "Write a contemplative monk-apprentice mini-drama set in the garden.",
            "Break the story into contemplative scenes in the garden.",
            "Design key frames matching the uploaded Japanese-garden layout.",
            "Render motion-video clips preserving the garden's visual identity.",
            "Compose the final monk mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a space-station interior, make a sci-fi first-contact mini-drama.",
        "rationale": "Space-station-interior image + sci-fi first-contact drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded space-station-interior image into the workspace as the visual reference.",
            "Enrich the setting brief combining the space-station atmosphere with the first-contact concept.",
            "Write a sci-fi first-contact mini-drama set in the uploaded space station.",
            "Break the story into first-contact scenes on the station.",
            "Design key frames matching the uploaded space-station architecture.",
            "Render motion-video clips preserving the station's visual identity.",
            "Compose the final first-contact mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a small fishing village, make a seaside romance mini-drama.",
        "rationale": "Fishing-village image + seaside romance drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded fishing-village image into the workspace as the visual reference.",
            "Enrich the setting brief combining the village atmosphere with the seaside-romance concept.",
            "Write a seaside romance mini-drama set in the uploaded fishing village.",
            "Break the story into seaside-romance scenes in and around the village.",
            "Design key frames matching the uploaded fishing-village setting.",
            "Render motion-video clips preserving the village's visual identity.",
            "Compose the final seaside romance mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a medieval tavern, make a fantasy heist mini-drama where a thief recruits allies.",
        "rationale": "Medieval-tavern image + fantasy heist drama + rollicking Celtic-fiddle. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded medieval-tavern image into the workspace as the visual reference.",
            "Enrich the setting brief combining the tavern atmosphere with the heist concept.",
            "Write a fantasy heist mini-drama where a thief recruits allies at the tavern.",
            "Break the story into heist-recruitment scenes inside the tavern.",
            "Design key frames matching the uploaded tavern decor.",
            "Render motion-video clips preserving the tavern's visual identity.",
            "Compose the final fantasy heist mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded photo of a train station, make a wartime farewell mini-drama.",
        "rationale": "Train-station photo + wartime farewell drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded train-station photo into the workspace as the visual reference.",
            "Enrich the setting brief combining the train-station atmosphere with the wartime-farewell concept.",
            "Write a wartime farewell mini-drama set at the train station.",
            "Break the story into wartime-farewell scenes around the station.",
            "Design key frames matching the uploaded station architecture.",
            "Render motion-video clips preserving the station's visual identity.",
            "Compose the final wartime mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a mountain lake at dawn, make a zen quiet-morning mini-drama about a hermit's last day.",
        "rationale": "Mountain-lake-at-dawn image + zen quiet-morning drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded mountain-lake-at-dawn image into the workspace as the visual reference.",
            "Enrich the setting brief combining the dawn-lake atmosphere with the hermit concept.",
            "Write a zen quiet-morning mini-drama about a hermit's last day at the lake.",
            "Break the story into contemplative dawn scenes around the lake.",
            "Design key frames matching the uploaded lake-at-dawn setting.",
            "Render motion-video clips preserving the lake's dawn lighting.",
            "Compose the final zen mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": ".",
        "rationale": "Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded jazz-club image into the workspace as the visual reference.",
            "Enrich the setting brief combining the jazz-club atmosphere with the trumpeter concept.",
            "Write a 1950s-noir musician mini-drama about a trumpeter chasing fame.",
            "Break the story into noir-musician scenes inside the jazz club.",
            "Design key frames matching the uploaded jazz-club decor.",
            "Render motion-video clips preserving the jazz-club's visual identity.",
            "Compose the final 1950s-noir mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of an ancient library, make a young-scholar-finds-a-secret-book mini-drama.",
        "rationale": "Ancient-library image + young-scholar-finds-secret-book drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded ancient-library image into the workspace as the visual reference.",
            "Enrich the setting brief combining the library atmosphere with the secret-book concept.",
            "Write a young-scholar-finds-a-secret-book mini-drama set in the uploaded library.",
            "Break the story into discovery scenes inside the library.",
            "Design key frames matching the uploaded library's shelves and decor.",
            "Render motion-video clips preserving the library's visual identity.",
            "Compose the final scholar mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a bustling market, make a street-vendor romance mini-drama.",
        "rationale": "Bustling-market image + street-vendor romance drama + uplifting brass-band. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded bustling-market image into the workspace as the visual reference.",
            "Enrich the setting brief combining the market atmosphere with the street-vendor-romance concept.",
            "Write a street-vendor romance mini-drama set in the uploaded market.",
            "Break the story into romance scenes across the bustling market.",
            "Design key frames matching the uploaded market layout.",
            "Render motion-video clips preserving the market's visual identity.",
            "Compose the final market-romance mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of an alpine chalet, make a cozy winter-holiday mini-drama about a snowed-in family.",
        "rationale": "Alpine-chalet image + cozy winter-family drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded alpine-chalet image into the workspace as the visual reference.",
            "Enrich the setting brief combining the chalet atmosphere with the winter-family concept.",
            "Write a cozy winter-holiday mini-drama about a snowed-in family at the chalet.",
            "Break the story into cozy family scenes inside and around the chalet.",
            "Design key frames matching the uploaded chalet architecture.",
            "Render motion-video clips preserving the chalet's visual identity.",
            "Compose the final winter-family mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a downtown rooftop, make an urban-stargazer romance mini-drama.",
        "rationale": "Downtown-rooftop image + urban-stargazer romance drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded downtown-rooftop image into the workspace as the visual reference.",
            "Enrich the setting brief combining the rooftop atmosphere with the stargazer-romance concept.",
            "Write an urban-stargazer romance mini-drama set on the rooftop.",
            "Break the story into romance scenes under the stars.",
            "Design key frames matching the uploaded rooftop setting.",
            "Render motion-video clips preserving the rooftop's visual identity.",
            "Compose the final rooftop mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a steampunk workshop, make an inventor mini-drama about a prototype flying machine.",
        "rationale": "Steampunk-workshop image + inventor drama + steampunk brass-clockwork. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded steampunk-workshop image into the workspace as the visual reference.",
            "Enrich the setting brief combining the workshop atmosphere with the inventor concept.",
            "Write an inventor mini-drama about a prototype flying machine in the workshop.",
            "Break the story into inventor-drama scenes across the workshop.",
            "Design key frames matching the uploaded steampunk workshop layout.",
            "Render motion-video clips preserving the workshop's visual identity.",
            "Compose the final steampunk inventor mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a farmhouse at sunrise, make a family-farewell mini-drama about a son leaving for war.",
        "rationale": "Farmhouse-at-sunrise image + family-farewell drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded farmhouse-at-sunrise image into the workspace as the visual reference.",
            "Enrich the setting brief combining the farm atmosphere with the family-farewell concept.",
            "Write a family-farewell mini-drama about a son leaving for war at the farm.",
            "Break the story into farewell scenes across the farmhouse and fields.",
            "Design key frames matching the uploaded farmhouse setting.",
            "Render motion-video clips preserving the farm's sunrise lighting.",
            "Compose the final farewell mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "make a harvest-day family mini-drama.",
        "rationale": "harvest-day family drama + lilting Italian-mandolin. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Tuscan-vineyard image into the workspace as the visual reference.",
            "Enrich the setting brief combining the vineyard atmosphere with the harvest-family concept.",
            "Write a harvest-day family mini-drama set in the Tuscan vineyard.",
            "Break the story into harvest-day scenes across the vineyard.",
            "Design key frames matching the uploaded vineyard layout.",
            "Render motion-video clips preserving the vineyard's visual identity.",
            "Compose the final Tuscan mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Moroccan souk, make an exotic spice-trader mini-drama.",
        "rationale": "Moroccan-souk image + spice-trader drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Moroccan-souk image into the workspace as the visual reference.",
            "Enrich the setting brief combining the souk atmosphere with the spice-trader concept.",
            "Write an exotic spice-trader mini-drama set in the uploaded Moroccan souk.",
            "Break the story into spice-trader scenes across the market.",
            "Design key frames matching the uploaded souk layout.",
            "Render motion-video clips preserving the souk's visual identity.",
            "Compose the final Moroccan mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of an Arctic research base, make a survival thriller mini-drama about a mysterious radio signal.",
        "rationale": "Arctic-research-base image + survival thriller drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Arctic-research-base image into the workspace as the visual reference.",
            "Enrich the setting brief combining the base atmosphere with the radio-signal thriller concept.",
            "Write a survival thriller mini-drama about a mysterious radio signal at the Arctic base.",
            "Break the story into thriller scenes inside and around the base.",
            "Design key frames matching the uploaded Arctic-base setting.",
            "Render motion-video clips preserving the base's visual identity.",
            "Compose the final Arctic thriller mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Brazilian carnival street, make a carnival-dancer mini-drama.",
        "rationale": "Brazilian-carnival image + carnival-dancer drama + lively samba. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Brazilian-carnival-street image into the workspace as the visual reference.",
            "Enrich the setting brief combining the carnival atmosphere with the dancer concept.",
            "Write a carnival-dancer mini-drama set in the uploaded Brazilian carnival.",
            "Break the story into carnival-dancer scenes across the street.",
            "Design key frames matching the uploaded carnival scene.",
            "Render motion-video clips preserving the carnival's visual identity.",
            "Compose the final carnival mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a haunted forest clearing, make a fairy-tale ghost-encounter mini-drama.",
        "rationale": "Haunted-forest-clearing image + fairy-tale ghost drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded haunted-forest-clearing image into the workspace as the visual reference.",
            "Enrich the setting brief combining the clearing atmosphere with the ghost-encounter concept.",
            "Write a fairy-tale ghost-encounter mini-drama set in the clearing.",
            "Break the story into ghost-encounter scenes in the forest.",
            "Design key frames matching the uploaded haunted-forest setting.",
            "Render motion-video clips preserving the forest's visual identity.",
            "Compose the final fairy-tale mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a high-school gymnasium, make a sports-comeback mini-drama about a basketball captain's last game.",
        "rationale": "High-school-gym image + sports-comeback drama + anthemic rock. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded high-school-gym image into the workspace as the visual reference.",
            "Enrich the setting brief combining the gym atmosphere with the sports-comeback concept.",
            "Write a sports-comeback mini-drama about a basketball captain's last game.",
            "Break the story into sports-drama scenes across the gym.",
            "Design key frames matching the uploaded gym layout.",
            "Render motion-video clips preserving the gym's visual identity.",
            "Compose the final sports mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a submarine bridge, make a deep-sea-mission mini-drama about contacting an unknown species.",
        "rationale": "Submarine-bridge image + deep-sea-mission drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded submarine-bridge image into the workspace as the visual reference.",
            "Enrich the setting brief combining the submarine atmosphere with the deep-sea-mission concept.",
            "Write a deep-sea-mission mini-drama about contacting an unknown species.",
            "Break the story into mission scenes on the submarine bridge.",
            "Design key frames matching the uploaded submarine layout.",
            "Render motion-video clips preserving the submarine's visual identity.",
            "Compose the final submarine mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a temple in the jungle, make an adventurous explorer mini-drama about discovering a lost civilization.",
        "rationale": "Jungle-temple image + explorer drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded jungle-temple image into the workspace as the visual reference.",
            "Enrich the setting brief combining the temple atmosphere with the explorer concept.",
            "Write an explorer mini-drama about discovering a lost civilization at the temple.",
            "Break the story into explorer-adventure scenes at the temple.",
            "Design key frames matching the uploaded jungle-temple setting.",
            "Render motion-video clips preserving the temple's visual identity.",
            "Compose the final explorer mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a New York speakeasy, make a 1920s bootlegger mini-drama.",
        "rationale": "New-York-speakeasy image + 1920s bootlegger drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded NY-speakeasy image into the workspace as the visual reference.",
            "Enrich the setting brief combining the speakeasy atmosphere with the bootlegger concept.",
            "Write a 1920s bootlegger mini-drama set in the speakeasy.",
            "Break the story into bootlegger-drama scenes inside the speakeasy.",
            "Design key frames matching the uploaded speakeasy decor.",
            "Render motion-video clips preserving the speakeasy's visual identity.",
            "Compose the final 1920s mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Cornish seaside cottage, make a ghost-romance mini-drama about a woman meeting her dead husband's ghost.",
        "rationale": "Cornish-cottage image + ghost-romance drama + melancholic string-quartet. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Cornish-cottage image into the workspace as the visual reference.",
            "Enrich the setting brief combining the cottage atmosphere with the ghost-romance concept.",
            "Write a ghost-romance mini-drama about a woman meeting her dead husband's ghost.",
            "Break the story into ghost-romance scenes inside and around the cottage.",
            "Design key frames matching the uploaded cottage decor.",
            "Render motion-video clips preserving the cottage's visual identity.",
            "Compose the final ghost-romance mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Korean hanok village, make a palace-era romance mini-drama.",
        "rationale": "Korean-hanok-village image + palace-era romance drama + gentle gayageum. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Korean-hanok-village image into the workspace as the visual reference.",
            "Enrich the setting brief combining the hanok atmosphere with the palace-romance concept.",
            "Write a palace-era romance mini-drama set in the uploaded hanok village.",
            "Break the story into palace-romance scenes in the village.",
            "Design key frames matching the uploaded hanok architecture.",
            "Render motion-video clips preserving the village's visual identity.",
            "Compose the final palace-era mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Hollywood back-lot, make a 1950s-starlet-behind-the-scenes mini-drama.",
        "rationale": "Hollywood-backlot image + 1950s-starlet drama + brassy big-band. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Hollywood-back-lot image into the workspace as the visual reference.",
            "Enrich the setting brief combining the back-lot atmosphere with the 1950s-starlet concept.",
            "Write a 1950s-starlet-behind-the-scenes mini-drama set at the back-lot.",
            "Break the story into starlet scenes across the studio.",
            "Design key frames matching the uploaded back-lot layout.",
            "Render motion-video clips preserving the back-lot's visual identity.",
            "Compose the final 1950s starlet mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Spanish flamenco stage, make a passion-and-rivalry dancer mini-drama.",
        "rationale": "Flamenco-stage image + passion-and-rivalry dancer drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded flamenco-stage image into the workspace as the visual reference.",
            "Enrich the setting brief combining the stage atmosphere with the dancer-rivalry concept.",
            "Write a passion-and-rivalry dancer mini-drama set at the flamenco stage.",
            "Break the story into dancer-rivalry scenes on the stage.",
            "Design key frames matching the uploaded flamenco-stage layout.",
            "Render motion-video clips preserving the stage's visual identity.",
            "Compose the final flamenco mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of an Indian palace, make a Rajput princess mini-drama about defying a forced alliance.",
        "rationale": "Indian-palace image + Rajput princess drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Indian-palace image into the workspace as the visual reference.",
            "Enrich the setting brief combining the palace atmosphere with the Rajput-princess concept.",
            "Write a Rajput princess mini-drama about defying a forced alliance.",
            "Break the story into princess-drama scenes across the palace.",
            "Design key frames matching the uploaded palace architecture.",
            "Render motion-video clips preserving the palace's visual identity.",
            "Compose the final Rajput mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "make a winemaker-family-succession mini-drama.",
        "rationale": "winemaker succession drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded California-vineyard-at-golden-hour image into the workspace as the visual reference.",
            "Enrich the setting brief combining the vineyard atmosphere with the succession concept.",
            "Write a winemaker-family-succession mini-drama set in the vineyard.",
            "Break the story into succession-drama scenes across the vineyard.",
            "Design key frames matching the uploaded vineyard's golden-hour lighting.",
            "Render motion-video clips preserving the vineyard's visual identity.",
            "Compose the final winemaker mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a snow-covered lighthouse, make a keeper's-last-winter mini-drama.",
        "rationale": "Snow-covered-lighthouse image + keeper's-last-winter drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded snow-covered-lighthouse image into the workspace as the visual reference.",
            "Enrich the setting brief combining the lighthouse atmosphere with the keeper concept.",
            "Write a keeper's-last-winter mini-drama set at the lighthouse.",
            "Break the story into keeper-drama scenes inside and around the lighthouse.",
            "Design key frames matching the uploaded lighthouse architecture.",
            "Render motion-video clips preserving the lighthouse's visual identity.",
            "Compose the final keeper mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Venice canal, make a 18th-century mask-ball romance mini-drama.",
        "rationale": "Venice-canal image + 18th-century mask-ball romance. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Venice-canal image into the workspace as the visual reference.",
            "Enrich the setting brief combining the canal atmosphere with the mask-ball-romance concept.",
            "Write an 18th-century mask-ball romance mini-drama set on the Venice canal.",
            "Break the story into mask-ball scenes along the canal.",
            "Design key frames matching the uploaded Venice architecture.",
            "Render motion-video clips preserving the canal's visual identity.",
            "Compose the final Venice mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Brooklyn brownstone stoop, make a teenage-summer coming-of-age mini-drama.",
        "rationale": "Brooklyn-brownstone-stoop image + teenage summer coming-of-age + indie-folk acoustic. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Brooklyn-brownstone-stoop image into the workspace as the visual reference.",
            "Enrich the setting brief combining the stoop atmosphere with the coming-of-age concept.",
            "Write a teenage-summer coming-of-age mini-drama set on the stoop.",
            "Break the story into coming-of-age scenes across the stoop and block.",
            "Design key frames matching the uploaded brownstone setting.",
            "Render motion-video clips preserving the brownstone's visual identity.",
            "Compose the final coming-of-age mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Bavarian Christmas market, make a holiday-miracle mini-drama about lost siblings reuniting.",
        "rationale": "Bavarian-Christmas-market image + holiday-miracle drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Bavarian-Christmas-market image into the workspace as the visual reference.",
            "Enrich the setting brief combining the market atmosphere with the holiday-miracle concept.",
            "Write a holiday-miracle mini-drama about lost siblings reuniting at the market.",
            "Break the story into holiday-reunion scenes across the market.",
            "Design key frames matching the uploaded Christmas-market layout.",
            "Render motion-video clips preserving the market's festive visual identity.",
            "Compose the final holiday mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a volcanic island, make a scientist-reluctant-hero mini-drama racing to warn of an eruption.",
        "rationale": "Volcanic-island image + scientist-hero drama + tense cinematic. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded volcanic-island image into the workspace as the visual reference.",
            "Enrich the setting brief combining the island atmosphere with the scientist-hero concept.",
            "Write a scientist-reluctant-hero mini-drama about warning of an eruption.",
            "Break the story into thriller scenes across the volcanic island.",
            "Design key frames matching the uploaded island topography.",
            "Render motion-video clips preserving the volcanic-island's visual identity.",
            "Compose the final volcano mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Tibetan monastery at dusk, make a pilgrim-child mini-drama about finding an unexpected teacher.",
        "rationale": "Tibetan-monastery-at-dusk image + pilgrim-child drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Tibetan-monastery-at-dusk image into the workspace as the visual reference.",
            "Enrich the setting brief combining the monastery atmosphere with the pilgrim-child concept.",
            "Write a pilgrim-child mini-drama about finding an unexpected teacher at the monastery.",
            "Break the story into pilgrim scenes at the monastery.",
            "Design key frames matching the uploaded monastery architecture.",
            "Render motion-video clips preserving the monastery's dusk lighting.",
            "Compose the final pilgrim mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Caribbean beach bar, make a sunset-romance mini-drama about two strangers finding each other on vacation.",
        "rationale": "Caribbean-beach-bar image + sunset-romance drama. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded Caribbean-beach-bar image into the workspace as the visual reference.",
            "Enrich the setting brief combining the beach-bar atmosphere with the sunset-romance concept.",
            "Write a sunset-romance mini-drama about two strangers finding each other on vacation.",
            "Break the story into beach-bar romance scenes at sunset.",
            "Design key frames matching the uploaded beach-bar setting.",
            "Render motion-video clips preserving the beach-bar's visual identity.",
            "Compose the final Caribbean romance mini-drama with all layers assembled.",
        ],
    },
]
