"""Shape: vid_analysis_cr —
    IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor.

Video-analysis-referenced cinematic remake, no audio overlay. (Path B alignment with v3 eval — opt-in audio: chain has Music/Ambience/AudioMix iff user_goal explicitly mentions audio.)
"""
from __future__ import annotations

SAMPLES: list[dict] = [
    {
        "user_goal": "Analyze this short clip of my travel vlog, and use it as inspiration to make a cinematic mini-drama about a solo wanderer finding herself.",
        "rationale": "User uploaded a reference travel vlog + asks for a cinematic remake inspired by it. IntakeVideoAgent ingests the vlog. VideoAnalysisAgent parses themes / settings from the vlog. StoryAgent writes a new story inspired by it. ScreenplayAgent breaks into scenes. KeyFrameAgent designs key frames. VideoAgent renders motion clips. baked audio. CompositorAgent assembles the final remake. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the uploaded travel-vlog clip into the workspace as the reference.",
            "Analyze the vlog to extract travel themes, landscapes, and narrative tone.",
            "Write a cinematic solo-wanderer story inspired by the vlog's themes.",
            "Break the story into wanderer-drama scenes across the analyzed landscapes.",
            "Design key frames inspired by the vlog's settings for each scene.",
            "Render motion-video clips from the key frames.",
            "Compose the final wanderer mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this clip of a street-food vendor and use it as inspiration for a heartwarming urban-drama about a young cook's dream.",
        "rationale": "Street-food vendor clip as reference + urban-drama remake. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the street-food vendor clip into the workspace as the reference.",
            "Analyze the clip to extract the vendor's craft, bustle, and urban mood.",
            "Write a heartwarming urban drama about a young cook's dream inspired by the clip.",
            "Break the story into young-cook scenes across a bustling market.",
            "Design key frames inspired by the vendor clip's settings for each scene.",
            "Render motion-video clips preserving the market flavor.",
            "Compose the final urban mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this surf competition clip and make a cinematic coming-of-age mini-drama about a young surfer chasing her first title.",
        "rationale": "Surf competition clip reference + coming-of-age surf drama + energetic indie-rock. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the surf-competition clip into the workspace as the reference.",
            "Analyze the clip to extract surfing tricks, energy, and youth culture vibe.",
            "Write a coming-of-age story about a young surfer chasing her first title.",
            "Break the story into surfer-drama scenes at the beach and competition.",
            "Design key frames inspired by the surf clip's settings.",
            "Render motion-video clips preserving the surf-energy.",
            "Compose the final coming-of-age mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this dance-rehearsal clip and use it as inspiration for a drama about a ballerina's injury comeback.",
        "rationale": "Dance-rehearsal clip reference + ballerina-injury drama. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the dance-rehearsal clip into the workspace as the reference.",
            "Analyze the clip to extract rehearsal atmosphere and dancer motion.",
            "Write a ballerina-injury-comeback mini-drama inspired by the rehearsal clip.",
            "Break the story into comeback-drama scenes in the rehearsal studio.",
            "Design key frames inspired by the rehearsal clip's staging.",
            "Render motion-video clips preserving the rehearsal mood.",
            "Compose the final ballerina mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this Japanese-market clip and use it as inspiration for a ghost-encounter period drama.",
        "rationale": "Japanese-market clip reference + ghost-encounter period drama. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the Japanese-market clip into the workspace as the reference.",
            "Analyze the clip to extract market architecture and atmosphere.",
            "Write a ghost-encounter period drama inspired by the market clip.",
            "Break the story into period-drama scenes in the market.",
            "Design key frames inspired by the market clip's lanterns and stalls.",
            "Render motion-video clips preserving the Japanese-market mood.",
            "Compose the final period ghost mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this clip of a winter mountain ski-resort and make a love-at-first-sight mini-drama between two skiers.",
        "rationale": "Ski-resort clip reference + love-at-first-sight drama. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the ski-resort clip into the workspace as the reference.",
            "Analyze the clip to extract resort landscape and skier motion.",
            "Write a love-at-first-sight mini-drama between two skiers inspired by the clip.",
            "Break the story into romance scenes at the resort and slopes.",
            "Design key frames inspired by the ski-resort setting.",
            "Render motion-video clips preserving the alpine mood.",
            "Compose the final romance mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this clip of an abandoned warehouse and make a noir-style detective mini-drama chasing a killer.",
        "rationale": "Abandoned-warehouse clip reference + noir detective drama. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the abandoned-warehouse clip into the workspace as the reference.",
            "Analyze the clip to extract the warehouse's decay and atmosphere.",
            "Write a noir-detective mini-drama about chasing a killer in the warehouse.",
            "Break the story into noir-detective scenes across the warehouse.",
            "Design key frames inspired by the warehouse clip's architecture.",
            "Render motion-video clips preserving the noir warehouse mood.",
            "Compose the final noir mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this city-rooftop clip and make a sci-fi chase mini-drama about a messenger dodging drones.",
        "rationale": "City-rooftop clip reference + sci-fi chase drama. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the city-rooftop clip into the workspace as the reference.",
            "Analyze the clip to extract rooftop geometry and city scale.",
            "Write a sci-fi chase mini-drama about a messenger dodging drones.",
            "Break the story into chase scenes across city rooftops.",
            "Design key frames inspired by the rooftop clip's architecture.",
            "Render motion-video clips preserving the city-rooftop scale.",
            "Compose the final chase mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this clip of a pottery studio and make a master-and-apprentice mini-drama about a life-changing lesson.",
        "rationale": "Pottery-studio clip reference + master-apprentice drama. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the pottery-studio clip into the workspace as the reference.",
            "Analyze the clip to extract studio atmosphere and craft details.",
            "Write a master-and-apprentice mini-drama about a life-changing lesson.",
            "Break the story into master-apprentice scenes in the studio.",
            "Design key frames inspired by the studio clip's layout and decor.",
            "Render motion-video clips preserving the pottery-studio mood.",
            "Compose the final apprentice mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this clip of a bustling street festival and make a love-across-cultures mini-drama.",
        "rationale": "Street-festival clip reference + love-across-cultures drama + joyful world-fusion. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the street-festival clip into the workspace as the reference.",
            "Analyze the clip to extract festival atmosphere and cultural elements.",
            "Write a love-across-cultures mini-drama inspired by the festival clip.",
            "Break the story into romance scenes across the festival.",
            "Design key frames inspired by the festival's visual identity.",
            "Render motion-video clips preserving the festival's vibrant mood.",
            "Compose the final love-across-cultures mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this clip of a small-town diner and make a heartwarming found-family mini-drama.",
        "rationale": "Small-town diner clip reference + found-family drama. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the small-town diner clip into the workspace as the reference.",
            "Analyze the clip to extract diner atmosphere and small-town charm.",
            "Write a heartwarming found-family mini-drama inspired by the diner clip.",
            "Break the story into found-family scenes in the diner.",
            "Design key frames inspired by the diner clip's booths and decor.",
            "Render motion-video clips preserving the diner's cozy mood.",
            "Compose the final found-family mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": ".",
        "rationale": "Classical concert clip reference. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the classical-music concert clip into the workspace as the reference.",
            "Analyze the clip to extract concert atmosphere and musical gravitas.",
            "Write a musician-grief mini-drama about finishing a mentor's last composition.",
            "Break the story into grief-drama scenes across concert halls and practice rooms.",
            "Design key frames inspired by the concert clip's staging.",
            "Render motion-video clips preserving the classical mood.",
            "Compose the final musician mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this dog-shelter volunteer clip and make a tearjerker adoption mini-drama about a rescue dog finding a home.",
        "rationale": "Dog-shelter clip reference + rescue-adoption drama. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the dog-shelter volunteer clip into the workspace as the reference.",
            "Analyze the clip to extract shelter atmosphere and dog behavior.",
            "Write a tearjerker rescue-dog adoption mini-drama.",
            "Break the story into adoption scenes at the shelter and new home.",
            "Design key frames inspired by the shelter clip's layout.",
            "Render motion-video clips preserving the shelter mood.",
            "Compose the final adoption mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this clip of a summer-camp lake and make a coming-of-age mini-drama about first love at camp.",
        "rationale": "Summer-camp lake clip + coming-of-age first-love drama. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the summer-camp lake clip into the workspace as the reference.",
            "Analyze the clip to extract camp atmosphere and lakeside vibe.",
            "Write a coming-of-age first-love mini-drama at the camp.",
            "Break the story into coming-of-age scenes across the camp and lake.",
            "Design key frames inspired by the camp clip's settings.",
            "Render motion-video clips preserving the camp mood.",
            "Compose the final coming-of-age mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this farming clip and make a generational family-saga mini-drama about passing down the land.",
        "rationale": "Farming clip reference + generational family-saga drama + stirring Americana-folk. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the farming clip into the workspace as the reference.",
            "Analyze the clip to extract farm atmosphere and multigenerational feel.",
            "Write a generational family-saga mini-drama about passing down the land.",
            "Break the story into saga scenes across seasons of farm life.",
            "Design key frames inspired by the farming clip's landscape.",
            "Render motion-video clips preserving the farm mood.",
            "Compose the final farm mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this clip of a bus-station goodbye and make a long-distance-love mini-drama about a letter-writing romance.",
        "rationale": "Bus-station clip reference + long-distance-love drama + bittersweet strings. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the bus-station goodbye clip into the workspace as the reference.",
            "Analyze the clip to extract farewell atmosphere and station geometry.",
            "Write a long-distance-love letter-writing romance mini-drama.",
            "Break the story into letter-writing romance scenes across cities.",
            "Design key frames inspired by the bus-station clip's layout.",
            "Render motion-video clips preserving the goodbye mood.",
            "Compose the final long-distance-love mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this clip of a flower-shop owner and make a feel-good small-business mini-drama about saving her shop.",
        "rationale": "Flower-shop clip reference + small-business feel-good drama + whimsical indie-folk. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the flower-shop clip into the workspace as the reference.",
            "Analyze the clip to extract shop atmosphere and owner's craft.",
            "Write a feel-good small-business mini-drama about saving the shop.",
            "Break the story into small-business scenes across the flower-shop.",
            "Design key frames inspired by the flower-shop clip's interior.",
            "Render motion-video clips preserving the shop mood.",
            "Compose the final small-business mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this clip of a mountain-lake fisher and make an old-man-and-the-lake contemplation mini-drama.",
        "rationale": "Mountain-lake fisher clip + contemplative drama. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the mountain-lake fisher clip into the workspace as the reference.",
            "Analyze the clip to extract lake atmosphere and fisher's solitude.",
            "Write an old-man-and-the-lake contemplative mini-drama.",
            "Break the story into contemplative scenes across the lake's seasons.",
            "Design key frames inspired by the fisher clip's landscape.",
            "Render motion-video clips preserving the mountain-lake mood.",
            "Compose the final contemplative mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this clip of a bookshop cat and make a cozy bookstore-romance mini-drama.",
        "rationale": "Bookshop cat clip + cozy bookstore-romance. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the bookshop cat clip into the workspace as the reference.",
            "Analyze the clip to extract bookstore atmosphere and cat's quiet presence.",
            "Write a cozy bookstore-romance mini-drama inspired by the clip.",
            "Break the story into bookstore-romance scenes around the shelves.",
            "Design key frames inspired by the bookshop clip's layout.",
            "Render motion-video clips preserving the cozy bookstore mood.",
            "Compose the final bookstore mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Analyze this clip of a mountain-rescue helicopter and make an action-thriller mini-drama about saving a stranded climber.",
        "rationale": "Mountain-rescue helicopter clip + action-thriller drama. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor → done.",
        "intents": [
            "Ingest the mountain-rescue helicopter clip into the workspace as the reference.",
            "Analyze the clip to extract mountain terrain and rescue-operation dynamics.",
            "Write an action-thriller mini-drama about saving a stranded climber.",
            "Break the story into thriller scenes across mountain and helicopter.",
            "Design key frames inspired by the rescue clip's aerial angles.",
            "Render motion-video clips preserving the rescue intensity.",
            "Compose the final action-thriller mini-drama with all layers assembled.",
        ],
    },
]
