"""Shape: cr_subtitle —
    Story → Screenplay → KeyFrame → Video → Transcription → Compositor.

Cinematic mini-drama with monolingual subtitles, no audio overlay. (Path B alignment with v3 eval — opt-in audio: chain has Music/Ambience/AudioMix iff user_goal explicitly mentions audio.)
"""
from __future__ import annotations

SAMPLES: list[dict] = [
    {
        "user_goal": "Make an English-subtitled campus sweet-romance mini-drama where the top-student class president and a transferred-in delinquent girl redeem each other.",
        "rationale": "Campus sweet-romance drama + English subtitles. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done. Reject Translation (monolingual only).",
        "intents": [
            "Write the campus sweet-romance story of the class president and delinquent girl.",
            "Break the story into campus-romance scenes.",
            "Design key frames for the campus and character dynamics.",
            "Render motion-video clips preserving campus-romance continuity.",
            "Transcribe the English dialogue across the scenes into timestamped SRT.",
            "Compose the final campus mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a subtitled costume-drama culinary animated drama where a junior imperial-kitchen maid rises through her cooking skills.",
        "rationale": "Imperial-kitchen maid rise drama + monolingual subtitles. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the imperial-kitchen maid's rise story.",
            "Break the story into palace-kitchen scenes.",
            "Design key frames for the imperial kitchen.",
            "Render motion-video clips preserving the imperial-kitchen continuity.",
            "Transcribe the palace-kitchen dialogue into timestamped SRT.",
            "Compose the final imperial-kitchen mini-drama with subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Create a mini-drama with English subtitles about a rebirth-revenge story set in modern Shanghai.",
        "rationale": "Modern Shanghai rebirth-revenge drama + English subtitles. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Shanghai rebirth-revenge story.",
            "Break the story into modern-Shanghai revenge scenes.",
            "Design key frames for the Shanghai skyline and revenge climax.",
            "Render motion-video clips preserving the Shanghai-drama continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final Shanghai mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled cyberpunk hacker mini-drama.",
        "rationale": "Cyberpunk hacker drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the cyberpunk-hacker story.",
            "Break the story into cyberpunk-hacker scenes.",
            "Design key frames for the neon cyberpunk city.",
            "Render motion-video clips preserving cyberpunk continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final cyberpunk mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled underdog-boxing mini-drama about a single mom fighting her way to the title.",
        "rationale": "Single-mom underdog-boxing drama + English subs + anthemic rock. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the single-mom underdog-boxing story.",
            "Break the story into boxing-training and fight scenes.",
            "Design key frames for the gym and boxing arena.",
            "Render motion-video clips preserving boxing-drama continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final boxing mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a French-subtitled Parisian-café mini-drama about a writer struggling with her second novel.",
        "rationale": "Parisian-writer second-novel drama + French subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Parisian-writer second-novel story.",
            "Break the story into Parisian-writing scenes.",
            "Design key frames for the Parisian café and writer's struggle.",
            "Render motion-video clips preserving the Parisian-writer continuity.",
            "Transcribe the French dialogue into timestamped SRT.",
            "Compose the final Parisian mini-drama with French captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a Japanese-subtitled Meiji-era samurai drama about a masterless swordsman taking a bodyguard job.",
        "rationale": "Meiji-era masterless-swordsman drama + Japanese subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Meiji masterless-swordsman story.",
            "Break the story into Meiji swordsman scenes.",
            "Design key frames for Meiji streets and sword encounters.",
            "Render motion-video clips preserving Meiji-period continuity.",
            "Transcribe the Japanese dialogue into timestamped SRT.",
            "Compose the final Meiji mini-drama with Japanese captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled period drama about a 1950s NASA female computer whose calculations save a mission.",
        "rationale": "1950s NASA female-computer drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the 1950s NASA female-computer story.",
            "Break the story into NASA-mission scenes.",
            "Design key frames for 1950s NASA facilities and the computer room.",
            "Render motion-video clips preserving 1950s NASA continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final NASA mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mountain-climber-survival mini-drama about a woman trapped on K2 during a storm.",
        "rationale": "K2-climber storm-survival drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the K2 storm-survival story.",
            "Break the story into K2-survival scenes.",
            "Design key frames for the K2 storm and climber's ordeal.",
            "Render motion-video clips preserving the K2-survival continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final K2 mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a Chinese-subtitled wuxia mini-drama about a blind swordswoman seeking her master's killer.",
        "rationale": "Wuxia blind-swordswoman drama + Chinese subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the wuxia blind-swordswoman story.",
            "Break the story into wuxia-swordswoman scenes.",
            "Design key frames for the wuxia courtyard and combat.",
            "Render motion-video clips preserving wuxia continuity.",
            "Transcribe the Chinese dialogue into timestamped SRT.",
            "Compose the final wuxia mini-drama with Chinese captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a Spanish-subtitled flamenco-dancer mini-drama about a young dancer competing for a coveted award.",
        "rationale": "Flamenco-dancer competition drama + Spanish subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the flamenco-dancer competition story.",
            "Break the story into flamenco-rehearsal and competition scenes.",
            "Design key frames for the flamenco venue and dancer.",
            "Render motion-video clips preserving flamenco continuity.",
            "Transcribe the Spanish dialogue into timestamped SRT.",
            "Compose the final flamenco mini-drama with Spanish captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a German-subtitled Berlin-1990s underground-club mini-drama about a DJ making her first track.",
        "rationale": "1990s Berlin DJ first-track drama + German subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the 1990s Berlin DJ story.",
            "Break the story into club-DJ scenes.",
            "Design key frames for the Berlin underground club.",
            "Render motion-video clips preserving the 1990s Berlin continuity.",
            "Transcribe the German dialogue into timestamped SRT.",
            "Compose the final Berlin mini-drama with German captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a Portuguese-subtitled Rio-favela mini-drama about a young soccer prodigy trying to escape poverty.",
        "rationale": "Rio-favela soccer-prodigy drama + Portuguese subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Rio-favela soccer-prodigy story.",
            "Break the story into favela soccer scenes.",
            "Design key frames for the Rio favela and soccer fields.",
            "Render motion-video clips preserving favela continuity.",
            "Transcribe the Portuguese dialogue into timestamped SRT.",
            "Compose the final favela mini-drama with Portuguese captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a Korean-subtitled K-drama mini-drama about a second-chance romance between ex-lovers reuniting in Seoul.",
        "rationale": "Seoul second-chance K-drama + Korean subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Seoul second-chance K-drama story.",
            "Break the story into Seoul-romance scenes.",
            "Design key frames for Seoul landmarks and ex-lover reunion.",
            "Render motion-video clips preserving K-drama continuity.",
            "Transcribe the Korean dialogue into timestamped SRT.",
            "Compose the final Seoul mini-drama with Korean captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an Italian-subtitled Sicilian mafia-drama about a young woman seeking the don's protection for her brother.",
        "rationale": "Sicilian mafia drama + Italian subs + baroque-strings. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Sicilian-mafia brother-protection story.",
            "Break the story into Sicilian mafia scenes.",
            "Design key frames for the Sicilian villa and don's court.",
            "Render motion-video clips preserving Sicilian mafia continuity.",
            "Transcribe the Italian dialogue into timestamped SRT.",
            "Compose the final Sicilian mini-drama with Italian captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a Russian-subtitled ballet mini-drama about a young Bolshoi dancer auditioning for the Paris Opera.",
        "rationale": "Bolshoi-to-Paris ballet drama + Russian subs + Tchaikovsky-style. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Bolshoi-to-Paris ballet story.",
            "Break the story into ballet-audition scenes.",
            "Design key frames for the Bolshoi and Paris Opera.",
            "Render motion-video clips preserving ballet continuity.",
            "Transcribe the Russian dialogue into timestamped SRT.",
            "Compose the final ballet mini-drama with Russian captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an Arabic-subtitled Bedouin desert-drama about a young woman saving her tribe from a rival.",
        "rationale": "Bedouin desert-heroine drama + Arabic subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Bedouin desert-heroine story.",
            "Break the story into Bedouin-desert scenes.",
            "Design key frames for the Bedouin desert camp and heroine.",
            "Render motion-video clips preserving the Bedouin-drama continuity.",
            "Transcribe the Arabic dialogue into timestamped SRT.",
            "Compose the final Bedouin mini-drama with Arabic captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a Hindi-subtitled village-to-city mini-drama about a young girl from rural Rajasthan moving to Mumbai for IIT.",
        "rationale": "Rajasthan-to-Mumbai village-to-city drama + Hindi subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the rural-Rajasthan-to-Mumbai story.",
            "Break the story into village-to-city transition scenes.",
            "Design key frames for the rural village and Mumbai.",
            "Render motion-video clips preserving the village-to-city continuity.",
            "Transcribe the Hindi dialogue into timestamped SRT.",
            "Compose the final village-to-city mini-drama with Hindi captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a Thai-subtitled Muay-Thai orphan mini-drama about a boy training to become the next champion.",
        "rationale": "Muay-Thai orphan champion drama + Thai subs + traditional piphat. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Muay-Thai orphan champion story.",
            "Break the story into Muay-Thai training scenes.",
            "Design key frames for the Muay-Thai gym and orphan's rise.",
            "Render motion-video clips preserving Muay-Thai continuity.",
            "Transcribe the Thai dialogue into timestamped SRT.",
            "Compose the final Muay-Thai mini-drama with Thai captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a Vietnamese-subtitled Saigon-1970s war-drama about a young photographer documenting the fall.",
        "rationale": "1970s Saigon photographer war-drama + Vietnamese subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the 1970s Saigon photographer story of documenting the fall.",
            "Break the story into photographer-war scenes.",
            "Design key frames for 1970s Saigon streets and fall.",
            "Render motion-video clips preserving the Saigon-war continuity.",
            "Transcribe the Vietnamese dialogue into timestamped SRT.",
            "Compose the final Saigon mini-drama with Vietnamese captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a Dutch-subtitled 17th-century Rembrandt-apprentice mini-drama about a young woman disguising herself as a man to study painting.",
        "rationale": "17th-century Rembrandt apprentice drama + Dutch subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Rembrandt-apprentice disguise story.",
            "Break the story into Amsterdam apprentice scenes.",
            "Design key frames for the 17th-century studio and Amsterdam streets.",
            "Render motion-video clips preserving 17th-century continuity.",
            "Transcribe the Dutch dialogue into timestamped SRT.",
            "Compose the final Rembrandt mini-drama with Dutch captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a Turkish-subtitled Istanbul-bazaar mini-drama about a rug-weaver's daughter uncovering a family secret.",
        "rationale": "Istanbul rug-weaver's-daughter secret drama + Turkish subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Istanbul rug-weaver's-daughter story.",
            "Break the story into Istanbul-bazaar family-secret scenes.",
            "Design key frames for the Istanbul bazaar and rug shop.",
            "Render motion-video clips preserving Istanbul-bazaar continuity.",
            "Transcribe the Turkish dialogue into timestamped SRT.",
            "Compose the final Istanbul mini-drama with Turkish captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a Greek-subtitled Santorini mini-drama about a young fisherman's daughter restoring her grandmother's abandoned taverna.",
        "rationale": "Santorini fisherman's-daughter taverna drama + Greek subs + warm bouzouki. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Santorini fisherman's-daughter taverna story.",
            "Break the story into Santorini-taverna scenes.",
            "Design key frames for Santorini and the taverna restoration.",
            "Render motion-video clips preserving the Santorini continuity.",
            "Transcribe the Greek dialogue into timestamped SRT.",
            "Compose the final Santorini mini-drama with Greek captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make a Polish-subtitled Krakow mini-drama about a young Jewish cellist surviving WWII in the underground.",
        "rationale": "WWII Krakow Jewish cellist drama + Polish subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the WWII Krakow Jewish cellist survival story.",
            "Break the story into wartime-Krakow scenes.",
            "Design key frames for wartime Krakow and the cellist's hiding.",
            "Render motion-video clips preserving wartime-Krakow continuity.",
            "Transcribe the Polish dialogue into timestamped SRT.",
            "Compose the final Krakow mini-drama with Polish captions and mixed audio.",
        ],
    },
    {
        "user_goal": ".",
        "rationale": "High-school theater-kid drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the high-school theater-kid audition story.",
            "Break the story into school-theater scenes.",
            "Design key frames for the school theater and audition moments.",
            "Render motion-video clips preserving school-theater continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final theater mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled contemporary mini-drama about a grief counselor who discovers her newest client is her own estranged brother.",
        "rationale": "Grief-counselor estranged-brother drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the grief-counselor estranged-brother story.",
            "Break the story into counselor-office scenes.",
            "Design key frames for the counseling office and brother's arrival.",
            "Render motion-video clips preserving the counselor-drama continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final counselor mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled small-town mini-drama about a widow inheriting her late husband's bait-and-tackle shop and befriending the regulars.",
        "rationale": "Widow bait-shop drama + English subs + warm Americana. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the widow's bait-shop story.",
            "Break the story into bait-shop scenes.",
            "Design key frames for the bait-and-tackle shop and regulars.",
            "Render motion-video clips preserving the small-town continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final bait-shop mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled coming-of-age mini-drama about a first-generation college student returning home for the holidays to navigate changed family dynamics.",
        "rationale": "First-gen college student holiday-return drama + English subs + indie-folk. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the first-gen college student's holiday-return story.",
            "Break the story into holiday-home scenes.",
            "Design key frames for the family home and returning student.",
            "Render motion-video clips preserving the coming-of-age continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final holiday mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled thriller mini-drama about a whistleblower software engineer meeting an anonymous contact in a parking garage.",
        "rationale": "Whistleblower engineer parking-garage drama + English subs + pulsing tension. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the whistleblower engineer meeting story.",
            "Break the story into thriller-meeting scenes.",
            "Design key frames for the parking garage and whistleblower's tension.",
            "Render motion-video clips preserving the thriller continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final whistleblower mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled period mini-drama about a WWII Bletchley-Park codebreaker breaking a key Enigma cipher.",
        "rationale": "WWII Bletchley-Park codebreaker drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Bletchley-Park codebreaker's breakthrough story.",
            "Break the story into Bletchley-Park scenes.",
            "Design key frames for the Bletchley-Park hut and the codebreaker.",
            "Render motion-video clips preserving WWII Bletchley continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final Bletchley mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled romance mini-drama about a retired ballet dancer teaching her first class at a community center.",
        "rationale": "Retired ballet-teacher community-class drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the retired-ballerina community-class story.",
            "Break the story into ballet-teaching scenes.",
            "Design key frames for the community center ballet class.",
            "Render motion-video clips preserving the ballet-teacher continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final ballet-teacher mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled horror mini-drama about a night-shift nurse handling strange events at a century-old psychiatric ward.",
        "rationale": "Psychiatric-ward night-nurse horror + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the psychiatric-ward night-nurse horror story.",
            "Break the story into night-shift horror scenes.",
            "Design key frames for the psychiatric ward corridors and strange events.",
            "Render motion-video clips preserving the horror tone.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final psychiatric-horror mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled adventure mini-drama about a female cave-diver mapping a previously unexplored Yucatán cenote.",
        "rationale": "Female cave-diver Yucatán cenote drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the female cave-diver's Yucatán cenote story.",
            "Break the story into cenote-exploration scenes.",
            "Design key frames for the cenote and diver's navigation.",
            "Render motion-video clips preserving cenote-adventure continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final cenote mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled drama about a young pianist returning to the Juilliard stage after a five-year hiatus.",
        "rationale": "Pianist post-hiatus Juilliard return drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the pianist's Juilliard-return story.",
            "Break the story into Juilliard-return scenes.",
            "Design key frames for the Juilliard stage and pianist.",
            "Render motion-video clips preserving the pianist-return continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final pianist mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mini-drama about a foster-care social worker navigating one especially difficult case.",
        "rationale": "Foster-care social-worker drama + English subs + heartfelt acoustic. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the foster-care social-worker story.",
            "Break the story into foster-care scenes.",
            "Design key frames for the social worker's office and case family.",
            "Render motion-video clips preserving the social-worker continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final foster-care mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled sci-fi mini-drama about a xenobiologist on a first-contact mission cataloging a sentient plant species.",
        "rationale": "Xenobiologist sentient-plants first-contact drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the xenobiologist's first-contact-with-plants story.",
            "Break the story into alien-jungle scenes.",
            "Design key frames for the alien jungle and sentient plants.",
            "Render motion-video clips preserving the sci-fi-first-contact tone.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final xenobiology mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mini-drama about a retired sailor teaching her estranged granddaughter to sail solo.",
        "rationale": "Retired sailor estranged-granddaughter sail-teaching drama + English subs + sea-shanty-quartet. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the sailor-grandmother-granddaughter sailing story.",
            "Break the story into sailing-teaching scenes.",
            "Design key frames for the sailboat and grandmother-granddaughter dynamics.",
            "Render motion-video clips preserving the sailing continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final sailing mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mini-drama about a young cartographer charting a new trail through an uncharted Nordic mountain range.",
        "rationale": "Young cartographer Nordic-mountain drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the young-cartographer's Nordic-mountain story.",
            "Break the story into Nordic-cartography scenes.",
            "Design key frames for the Nordic peaks and cartographer.",
            "Render motion-video clips preserving the Nordic-cartography continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final Nordic mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mini-drama about a young Alaskan fisherwoman captaining her first solo salmon run.",
        "rationale": "Alaskan fisherwoman solo-salmon drama + English subs + stirring Americana-strings. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Alaskan fisherwoman solo-salmon story.",
            "Break the story into solo-salmon scenes.",
            "Design key frames for the Alaskan waters and fishing boat.",
            "Render motion-video clips preserving the Alaskan-fishing continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final Alaskan mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mini-drama about a young physiotherapist helping a concussed athlete through a slow recovery.",
        "rationale": "Physiotherapist concussed-athlete drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the physiotherapist-and-athlete recovery story.",
            "Break the story into physiotherapy scenes.",
            "Design key frames for the clinic and rehabilitation.",
            "Render motion-video clips preserving the rehab continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final rehab mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mini-drama about a young Texan astronaut preparing for a lunar gateway mission.",
        "rationale": "Texan-astronaut lunar-mission drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Texan-astronaut's lunar-mission preparation story.",
            "Break the story into lunar-mission prep scenes.",
            "Design key frames for Houston mission control and astronaut training.",
            "Render motion-video clips preserving the lunar-mission continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final lunar mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mini-drama about a Florida wildlife-rehabilitator nursing an injured panther back to health.",
        "rationale": "Wildlife-rehabilitator panther drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the Florida wildlife-rehabilitator-and-panther story.",
            "Break the story into panther-rehabilitation scenes.",
            "Design key frames for the wildlife reserve and panther.",
            "Render motion-video clips preserving the wildlife continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final wildlife mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mini-drama about a young marine salvage diver recovering a WWII plane from the Pacific.",
        "rationale": "Marine salvage WWII-plane drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the marine salvage WWII-plane recovery story.",
            "Break the story into deep-Pacific salvage scenes.",
            "Design key frames for the deep-Pacific dive and WWII plane.",
            "Render motion-video clips preserving the salvage continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final salvage mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mini-drama about a museum-curator discovering a forgery at her own exhibition opening night.",
        "rationale": "Museum-curator forgery-discovery drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the museum-curator forgery-discovery story.",
            "Break the story into opening-night discovery scenes.",
            "Design key frames for the museum exhibition and curator.",
            "Render motion-video clips preserving the museum-mystery continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final museum mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mini-drama about a young forest ranger mentoring a troubled teen through wildfire-prevention training.",
        "rationale": "Forest-ranger mentorship drama + English subs + warm Americana-folk. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the forest-ranger-and-troubled-teen mentorship story.",
            "Break the story into ranger-training scenes.",
            "Design key frames for the ranger station and wildfire-prevention drills.",
            "Render motion-video clips preserving the ranger-mentorship continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final ranger mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mini-drama about a young oceanographer tracking whale-song migration patterns alone on a research catamaran.",
        "rationale": "Young oceanographer whale-song drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the young-oceanographer whale-song story.",
            "Break the story into oceanographic-research scenes.",
            "Design key frames for the catamaran and whale encounters.",
            "Render motion-video clips preserving the oceanographic continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final oceanographer mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mini-drama about a retired fire-chief mentoring a rookie through her first major warehouse fire.",
        "rationale": "Retired fire-chief rookie-mentorship drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the fire-chief rookie-mentorship story.",
            "Break the story into warehouse-fire scenes.",
            "Design key frames for the warehouse fire and firefighters.",
            "Render motion-video clips preserving the firefighter continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final firefighter mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mini-drama about a young tribal-language teacher preserving her grandmother's dialect through recordings.",
        "rationale": "Tribal-language teacher preservation drama + English subs + reverent folk. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the tribal-language teacher's preservation story.",
            "Break the story into language-preservation scenes.",
            "Design key frames for the tribal village and teacher-grandmother dynamic.",
            "Render motion-video clips preserving the tribal-village continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final language mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mini-drama about a refugee doctor recertifying in her new country while running an underground clinic.",
        "rationale": "Refugee-doctor recertification drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the refugee-doctor underground-clinic story.",
            "Break the story into clinic and study scenes.",
            "Design key frames for the underground clinic and doctor's perseverance.",
            "Render motion-video clips preserving the refugee-doctor continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final clinic mini-drama with English captions and mixed audio.",
        ],
    },
    {
        "user_goal": "Make an English-subtitled mini-drama about a young conservation-ecologist racing to save the last wild jaguar cubs in a threatened habitat.",
        "rationale": "Jaguar-cub conservation drama + English subs. Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Write the conservation-ecologist jaguar-cub story.",
            "Break the story into jaguar-conservation scenes.",
            "Design key frames for the jungle habitat and jaguar cubs.",
            "Render motion-video clips preserving the conservation continuity.",
            "Transcribe the English dialogue into timestamped SRT.",
            "Compose the final conservation mini-drama with English captions and mixed audio.",
        ],
    },
]
