"""Shape: intake_img_cr_bilingual —
    IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor.

Image-referenced mini-drama with bilingual subtitles, no audio overlay. (Path B alignment with v3 eval — opt-in audio: chain has Music/Ambience/AudioMix iff user_goal explicitly mentions audio.)
"""
from __future__ import annotations

SAMPLES: list[dict] = [
    {
        "user_goal": "Using this uploaded portrait of a cultivation-fantasy protagonist, make a mini-drama with Chinese+English bilingual subtitles.",
        "rationale": "Image-referenced cultivation-fantasy + Chinese+English bilingual. Longest cinematic chain. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded cultivation-fantasy portrait as the visual reference.",
            "Enrich the character brief combining image features with the cultivation concept.",
            "Write a cultivation-fantasy story around the uploaded character.",
            "Break the story into cultivation scenes with bloodline-awakening beats.",
            "Design key frames for the sect halls and cultivation combat matching the portrait.",
            "Render motion-video clips preserving cultivation-character continuity.",
            "Transcribe the Chinese cultivation dialogue into timestamped SRT.",
            "Translate the Chinese SRT into English subtitles.",
            "Compose the cultivation mini-drama with bilingual Chinese-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded photo of a Parisian café, make a romantic mini-drama about two old friends reconnecting, with French+English bilingual subtitles.",
        "rationale": "Image-referenced Parisian café reconnection + French+English bilingual. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Parisian café photo as the visual reference.",
            "Enrich the setting brief combining café atmosphere with reconnection concept.",
            "Write a romantic reconnection story at the café.",
            "Break the story into reconnection scenes.",
            "Design key frames matching the uploaded café decor.",
            "Render motion-video clips preserving the Parisian continuity.",
            "Transcribe the French dialogue into timestamped SRT.",
            "Translate the French SRT into English subtitles.",
            "Compose the Parisian mini-drama with bilingual French-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded Japanese garden photo, make a contemplative monk-apprentice mini-drama, with Japanese+English bilingual subtitles.",
        "rationale": "Image-referenced Japanese-garden monk-apprentice + Japanese+English bilingual. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Japanese garden photo as the visual reference.",
            "Enrich the setting brief combining the garden with the monk-apprentice concept.",
            "Write a contemplative monk-apprentice story in the garden.",
            "Break the story into contemplative garden scenes.",
            "Design key frames matching the uploaded garden layout.",
            "Render motion-video clips preserving the Japanese garden continuity.",
            "Transcribe the Japanese dialogue into timestamped SRT.",
            "Translate the Japanese SRT into English subtitles.",
            "Compose the monk mini-drama with bilingual Japanese-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Korean hanok village, make a palace-era forbidden-love drama with Korean+English bilingual subs.",
        "rationale": "Image-referenced hanok-village forbidden-love + Korean+English bilingual + gayageum. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Korean hanok-village image as the visual reference.",
            "Enrich the setting brief combining hanok atmosphere with forbidden-love concept.",
            "Write a palace-era forbidden-love story in the hanok village.",
            "Break the story into forbidden-love scenes across the village.",
            "Design key frames matching the uploaded hanok architecture.",
            "Render motion-video clips preserving hanok continuity.",
            "Transcribe the Korean dialogue into timestamped SRT.",
            "Translate the Korean SRT into English subtitles.",
            "Compose the palace-era mini-drama with bilingual Korean-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded Moroccan souk photo, make an exotic spice-trader mini-drama with Arabic+English bilingual subs.",
        "rationale": "Image-referenced Moroccan-souk spice-trader + Arabic+English bilingual. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Moroccan souk photo as the visual reference.",
            "Enrich the setting brief combining the souk with the spice-trader concept.",
            "Write the exotic spice-trader story set in the souk.",
            "Break the story into spice-trader scenes across the market.",
            "Design key frames matching the uploaded souk layout.",
            "Render motion-video clips preserving the souk's visual identity.",
            "Transcribe the Arabic dialogue into timestamped SRT.",
            "Translate the Arabic SRT into English subtitles.",
            "Compose the souk mini-drama with bilingual Arabic-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "make a winemaker-succession mini-drama with Italian+English bilingual subs.",
        "rationale": "Italian+English bilingual + mandolin. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Tuscan vineyard image as the visual reference.",
            "Enrich the setting brief combining vineyard atmosphere with succession concept.",
            "Write the winemaker-family-succession story set in the vineyard.",
            "Break the story into succession-drama scenes.",
            "Design key frames matching the uploaded vineyard layout.",
            "Render motion-video clips preserving the Tuscan continuity.",
            "Transcribe the Italian dialogue into timestamped SRT.",
            "Translate the Italian SRT into English subtitles.",
            "Compose the Tuscan mini-drama with bilingual Italian-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a snow-covered lighthouse, make a keeper's-last-winter drama with Icelandic+English bilingual subs.",
        "rationale": "Image-referenced snow-lighthouse keeper-winter + Icelandic+English bilingual. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded snow-lighthouse image as the visual reference.",
            "Enrich the setting brief combining lighthouse atmosphere with keeper-winter concept.",
            "Write the keeper's-last-winter story at the lighthouse.",
            "Break the story into keeper-drama scenes.",
            "Design key frames matching the uploaded lighthouse architecture.",
            "Render motion-video clips preserving the lighthouse continuity.",
            "Transcribe the Icelandic dialogue into timestamped SRT.",
            "Translate the Icelandic SRT into English subtitles.",
            "Compose the keeper mini-drama with bilingual Icelandic-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Venice canal, make an 18th-century mask-ball romance mini-drama with Italian+English bilingual subs.",
        "rationale": "Image-referenced Venice canal mask-ball + Italian+English bilingual. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Venice canal image as the visual reference.",
            "Enrich the setting brief combining canal atmosphere with mask-ball concept.",
            "Write the 18th-century mask-ball romance story set on the canal.",
            "Break the story into mask-ball canal scenes.",
            "Design key frames matching the uploaded Venice architecture.",
            "Render motion-video clips preserving the canal's visual identity.",
            "Transcribe the Italian dialogue into timestamped SRT.",
            "Translate the Italian SRT into English subtitles.",
            "Compose the Venice mini-drama with bilingual Italian-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a medieval tavern, make a fantasy heist mini-drama where a thief recruits allies, with Gaelic+English bilingual subs.",
        "rationale": "Image-referenced medieval-tavern heist + Gaelic+English bilingual + Celtic-fiddle. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded medieval tavern image as the visual reference.",
            "Enrich the setting brief combining tavern atmosphere with heist concept.",
            "Write the fantasy heist story at the tavern.",
            "Break the story into heist-recruitment scenes.",
            "Design key frames matching the uploaded tavern decor.",
            "Render motion-video clips preserving the tavern's visual identity.",
            "Transcribe the Gaelic dialogue into timestamped SRT.",
            "Translate the Gaelic SRT into English subtitles.",
            "Compose the fantasy heist mini-drama with bilingual Gaelic-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Balinese temple, make a dancer-temple-priestess drama with Indonesian+English bilingual subs.",
        "rationale": "Image-referenced Balinese-temple priestess-dancer + Indonesian+English bilingual + gamelan. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Balinese temple image as the visual reference.",
            "Enrich the setting brief combining temple atmosphere with priestess-dancer concept.",
            "Write the dancer-temple-priestess story at the temple.",
            "Break the story into temple-priestess scenes.",
            "Design key frames matching the uploaded temple architecture.",
            "Render motion-video clips preserving the Balinese-temple continuity.",
            "Transcribe the Indonesian dialogue into timestamped SRT.",
            "Translate the Indonesian SRT into English subtitles.",
            "Compose the Balinese mini-drama with bilingual Indonesian-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Rajasthani palace, make a desert-princess mini-drama with Hindi+English bilingual subs.",
        "rationale": "Image-referenced Rajasthani-palace princess + Hindi+English bilingual. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Rajasthani palace image as the visual reference.",
            "Enrich the setting brief combining palace atmosphere with desert-princess concept.",
            "Write the desert-princess story at the Rajasthani palace.",
            "Break the story into princess-drama scenes.",
            "Design key frames matching the uploaded palace architecture.",
            "Render motion-video clips preserving the Rajasthani continuity.",
            "Transcribe the Hindi dialogue into timestamped SRT.",
            "Translate the Hindi SRT into English subtitles.",
            "Compose the Rajasthani mini-drama with bilingual Hindi-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Caribbean beach bar, make a sunset-romance mini-drama with Spanish+English bilingual subs.",
        "rationale": "Image-referenced Caribbean-beach-bar romance + Spanish+English bilingual. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Caribbean beach-bar image as the visual reference.",
            "Enrich the setting brief combining beach-bar atmosphere with sunset-romance concept.",
            "Write the sunset-romance story at the beach bar.",
            "Break the story into beach-bar romance scenes at sunset.",
            "Design key frames matching the uploaded beach-bar setting.",
            "Render motion-video clips preserving the beach-bar continuity.",
            "Transcribe the Spanish dialogue into timestamped SRT.",
            "Translate the Spanish SRT into English subtitles.",
            "Compose the Caribbean mini-drama with bilingual Spanish-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of an ancient Greek theater, make a classical tragedy mini-drama with Greek+English bilingual subs.",
        "rationale": "Image-referenced Greek-theater tragedy + Greek+English bilingual + lyre-and-aulos. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded ancient Greek theater image as the visual reference.",
            "Enrich the setting brief combining theater atmosphere with classical-tragedy concept.",
            "Write the classical tragedy at the Greek theater.",
            "Break the story into tragedy acts.",
            "Design key frames matching the uploaded theater architecture.",
            "Render motion-video clips preserving the Greek-theater continuity.",
            "Transcribe the Greek dialogue into timestamped SRT.",
            "Translate the Greek SRT into English subtitles.",
            "Compose the Greek tragedy mini-drama with bilingual Greek-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Kyoto tea house, make a tea-ceremony-master drama with Japanese+English bilingual subs.",
        "rationale": "Image-referenced Kyoto tea-house tea-master + Japanese+English bilingual. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Kyoto tea-house image as the visual reference.",
            "Enrich the setting brief combining tea-house atmosphere with tea-master concept.",
            "Write the tea-ceremony-master story.",
            "Break the story into tea-ceremony scenes.",
            "Design key frames matching the uploaded tea-house layout.",
            "Render motion-video clips preserving the Kyoto tea-house continuity.",
            "Transcribe the Japanese dialogue into timestamped SRT.",
            "Translate the Japanese SRT into English subtitles.",
            "Compose the tea-ceremony mini-drama with bilingual Japanese-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Peruvian Inca ruin, make an archaeologist-discovery drama with Quechua+English bilingual subs.",
        "rationale": "Image-referenced Inca-ruin archaeologist + Quechua+English bilingual. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Inca-ruin image as the visual reference.",
            "Enrich the setting brief combining ruin atmosphere with archaeologist concept.",
            "Write the archaeologist-discovery story at the Inca ruin.",
            "Break the story into discovery scenes.",
            "Design key frames matching the uploaded ruin architecture.",
            "Render motion-video clips preserving the Inca-ruin continuity.",
            "Transcribe the Quechua dialogue into timestamped SRT.",
            "Translate the Quechua SRT into English subtitles.",
            "Compose the Inca mini-drama with bilingual Quechua-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Russian Siberian tundra, make a reindeer-herder mini-drama with Russian+English bilingual subs.",
        "rationale": "Image-referenced Siberian tundra reindeer-herder + Russian+English bilingual + balalaika. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Siberian tundra image as the visual reference.",
            "Enrich the setting brief combining tundra atmosphere with reindeer-herder concept.",
            "Write the reindeer-herder story on the tundra.",
            "Break the story into tundra-herder scenes.",
            "Design key frames matching the uploaded tundra landscape.",
            "Render motion-video clips preserving the tundra continuity.",
            "Transcribe the Russian dialogue into timestamped SRT.",
            "Translate the Russian SRT into English subtitles.",
            "Compose the Siberian mini-drama with bilingual Russian-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of an Amsterdam canal at night, make a 17th-century-merchant drama with Dutch+English bilingual subs.",
        "rationale": "Image-referenced Amsterdam-canal 17th-merchant + Dutch+English bilingual + baroque-chamber. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Amsterdam canal image as the visual reference.",
            "Enrich the setting brief combining canal atmosphere with 17th-merchant concept.",
            "Write the 17th-century-merchant story on the Amsterdam canal.",
            "Break the story into merchant scenes.",
            "Design key frames matching the uploaded Amsterdam architecture.",
            "Render motion-video clips preserving the 17th-Amsterdam continuity.",
            "Transcribe the Dutch dialogue into timestamped SRT.",
            "Translate the Dutch SRT into English subtitles.",
            "Compose the merchant mini-drama with bilingual Dutch-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Nairobi rooftop, make a young-entrepreneur mini-drama with Swahili+English bilingual subs.",
        "rationale": "Image-referenced Nairobi-rooftop entrepreneur + Swahili+English bilingual + Afrobeats. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Nairobi-rooftop image as the visual reference.",
            "Enrich the setting brief combining rooftop atmosphere with entrepreneur concept.",
            "Write the young-entrepreneur story at the Nairobi rooftop.",
            "Break the story into entrepreneur scenes.",
            "Design key frames matching the uploaded Nairobi-rooftop view.",
            "Render motion-video clips preserving the Nairobi continuity.",
            "Transcribe the Swahili dialogue into timestamped SRT.",
            "Translate the Swahili SRT into English subtitles.",
            "Compose the Nairobi mini-drama with bilingual Swahili-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Havana street.",
        "rationale": "Spanish+English bilingual + salsa. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Havana street image as the visual reference.",
            "Enrich the setting brief combining Havana atmosphere with Cuban-musician concept.",
            "Write the Cuban-musician story set on the Havana street.",
            "Break the story into Havana-musician scenes.",
            "Design key frames matching the uploaded Havana streetscape.",
            "Render motion-video clips preserving the Havana continuity.",
            "Transcribe the Spanish dialogue into timestamped SRT.",
            "Translate the Spanish SRT into English subtitles.",
            "Compose the Havana mini-drama with bilingual Spanish-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of an Andalusian patio, make a young-flamenco-singer mini-drama with Spanish+English bilingual subs.",
        "rationale": "Image-referenced Andalusian-patio flamenco-singer + Spanish+English bilingual + cante-jondo. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Andalusian patio image as the visual reference.",
            "Enrich the setting brief combining patio atmosphere with flamenco-singer concept.",
            "Write the young-flamenco-singer story in the patio.",
            "Break the story into flamenco-singer scenes.",
            "Design key frames matching the uploaded patio decor.",
            "Render motion-video clips preserving the Andalusian continuity.",
            "Transcribe the Spanish dialogue into timestamped SRT.",
            "Translate the Spanish SRT into English subtitles.",
            "Compose the Andalusian mini-drama with bilingual Spanish-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Ukrainian wheat field, make a young-farmer-at-harvest mini-drama with Ukrainian+English bilingual subs.",
        "rationale": "Image-referenced Ukrainian wheat-field farmer + Ukrainian+English bilingual + Ukrainian-folk. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Ukrainian wheat-field image as the visual reference.",
            "Enrich the setting brief combining wheat-field atmosphere with farmer concept.",
            "Write the young-farmer-at-harvest story.",
            "Break the story into harvest-farmer scenes.",
            "Design key frames matching the uploaded wheat-field landscape.",
            "Render motion-video clips preserving the Ukrainian continuity.",
            "Transcribe the Ukrainian dialogue into timestamped SRT.",
            "Translate the Ukrainian SRT into English subtitles.",
            "Compose the Ukrainian mini-drama with bilingual Ukrainian-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Thai floating market, make a boat-vendor-romance mini-drama with Thai+English bilingual subs.",
        "rationale": "Image-referenced Thai floating-market romance + Thai+English bilingual + khene. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Thai floating-market image as the visual reference.",
            "Enrich the setting brief combining market atmosphere with boat-vendor-romance concept.",
            "Write the boat-vendor-romance story.",
            "Break the story into boat-vendor romance scenes.",
            "Design key frames matching the uploaded floating-market layout.",
            "Render motion-video clips preserving the floating-market continuity.",
            "Transcribe the Thai dialogue into timestamped SRT.",
            "Translate the Thai SRT into English subtitles.",
            "Compose the Thai mini-drama with bilingual Thai-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a snowy Mongolian ger, make a winter-herder-family mini-drama with Mongolian+English bilingual subs.",
        "rationale": "Image-referenced Mongolian ger winter-herder + Mongolian+English bilingual + throat-singing. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Mongolian ger image as the visual reference.",
            "Enrich the setting brief combining ger atmosphere with winter-herder concept.",
            "Write the winter-herder-family story in the ger.",
            "Break the story into winter-herder scenes.",
            "Design key frames matching the uploaded ger decor.",
            "Render motion-video clips preserving the Mongolian continuity.",
            "Transcribe the Mongolian dialogue into timestamped SRT.",
            "Translate the Mongolian SRT into English subtitles.",
            "Compose the Mongolian mini-drama with bilingual Mongolian-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Buenos Aires tango salon, make a young-tango-dancer mini-drama with Spanish+English bilingual subs.",
        "rationale": "Image-referenced Buenos Aires tango salon + Spanish+English bilingual + tango. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Buenos Aires tango salon image as the visual reference.",
            "Enrich the setting brief combining salon atmosphere with tango-dancer concept.",
            "Write the young-tango-dancer story at the salon.",
            "Break the story into tango-dancer scenes.",
            "Design key frames matching the uploaded tango salon layout.",
            "Render motion-video clips preserving the Buenos Aires continuity.",
            "Transcribe the Spanish dialogue into timestamped SRT.",
            "Translate the Spanish SRT into English subtitles.",
            "Compose the Buenos Aires mini-drama with bilingual Spanish-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Himalayan monastery, make a young-nun's-first-initiation mini-drama with Tibetan+English bilingual subs.",
        "rationale": "Image-referenced Himalayan monastery initiation + Tibetan+English bilingual + Tibetan-bowls. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Himalayan monastery image as the visual reference.",
            "Enrich the setting brief combining monastery atmosphere with initiation concept.",
            "Write the young-nun's first-initiation story at the monastery.",
            "Break the story into initiation scenes.",
            "Design key frames matching the uploaded monastery architecture.",
            "Render motion-video clips preserving the Himalayan continuity.",
            "Transcribe the Tibetan dialogue into timestamped SRT.",
            "Translate the Tibetan SRT into English subtitles.",
            "Compose the Himalayan mini-drama with bilingual Tibetan-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Dublin pub, make a young-poet-first-reading mini-drama with Irish+English bilingual subs.",
        "rationale": "Image-referenced Dublin-pub poet + Irish+English bilingual + Celtic-folk. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Dublin pub image as the visual reference.",
            "Enrich the setting brief combining pub atmosphere with poet-first-reading concept.",
            "Write the young-poet-first-reading story at the pub.",
            "Break the story into poet-reading scenes.",
            "Design key frames matching the uploaded Dublin pub decor.",
            "Render motion-video clips preserving the Dublin continuity.",
            "Transcribe the Irish dialogue into timestamped SRT.",
            "Translate the Irish SRT into English subtitles.",
            "Compose the Dublin mini-drama with bilingual Irish-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Chinese junk-boat at sunset, make a fisherman's-daughter mini-drama with Chinese+English bilingual subs.",
        "rationale": "Image-referenced Chinese junk-boat fisherman's daughter + Chinese+English bilingual. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Chinese junk-boat image as the visual reference.",
            "Enrich the setting brief combining junk-boat atmosphere with fisherman's-daughter concept.",
            "Write the fisherman's-daughter story on the junk-boat.",
            "Break the story into junk-boat scenes.",
            "Design key frames matching the uploaded junk-boat design.",
            "Render motion-video clips preserving the junk-boat continuity.",
            "Transcribe the Chinese dialogue into timestamped SRT.",
            "Translate the Chinese SRT into English subtitles.",
            "Compose the junk-boat mini-drama with bilingual Chinese-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Bavarian mountain village, make a coming-of-age woodworker mini-drama with German+English bilingual subs.",
        "rationale": "Image-referenced Bavarian-village coming-of-age woodworker + German+English bilingual + zither. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Bavarian village image as the visual reference.",
            "Enrich the setting brief combining village atmosphere with woodworker concept.",
            "Write the coming-of-age woodworker story.",
            "Break the story into woodworker scenes.",
            "Design key frames matching the uploaded Bavarian village layout.",
            "Render motion-video clips preserving the Bavarian continuity.",
            "Transcribe the German dialogue into timestamped SRT.",
            "Translate the German SRT into English subtitles.",
            "Compose the Bavarian mini-drama with bilingual German-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Jordanian Petra ruin, make an archaeologist-Bedouin-guide drama with Arabic+English bilingual subs.",
        "rationale": "Image-referenced Petra-ruin archaeologist-Bedouin + Arabic+English bilingual. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Petra-ruin image as the visual reference.",
            "Enrich the setting brief combining Petra atmosphere with archaeologist-Bedouin-guide concept.",
            "Write the archaeologist-Bedouin-guide story at Petra.",
            "Break the story into Petra-exploration scenes.",
            "Design key frames matching the uploaded Petra landscape.",
            "Render motion-video clips preserving the Petra continuity.",
            "Transcribe the Arabic dialogue into timestamped SRT.",
            "Translate the Arabic SRT into English subtitles.",
            "Compose the Petra mini-drama with bilingual Arabic-English captions and all audio layers.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Southwest American desert reservation, make a young-silversmith mini-drama with Navajo+English bilingual subs.",
        "rationale": "Image-referenced Southwest reservation silversmith + Navajo+English bilingual. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → Transcription → Translation → Compositor → done.",
        "intents": [
            "Ingest the uploaded Southwest reservation image as the visual reference.",
            "Enrich the setting brief combining reservation atmosphere with silversmith concept.",
            "Write the young-silversmith story at the reservation.",
            "Break the story into silversmith scenes.",
            "Design key frames matching the uploaded reservation landscape.",
            "Render motion-video clips preserving the reservation continuity.",
            "Transcribe the Navajo dialogue into timestamped SRT.",
            "Translate the Navajo SRT into English subtitles.",
            "Compose the silversmith mini-drama with bilingual Navajo-English captions and all audio layers.",
        ],
    },
]
