"""Shape: vid_analysis_cr_subtitle —
    IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor.

Video-analysis-referenced cinematic remake with monolingual subtitles, no audio overlay. (Path B alignment with v3 eval — opt-in audio: chain has Music/Ambience/AudioMix iff user_goal explicitly mentions audio.)
"""
from __future__ import annotations

SAMPLES: list[dict] = [
    {
        "user_goal": "Analyze this travel-vlog clip and make a cinematic solo-wanderer mini-drama inspired by it, and English subtitles.",
        "rationale": "User uploaded a travel-vlog as reference + cinematic remake + English subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the uploaded travel-vlog clip into the workspace as the reference.",
            "Analyze the vlog to extract travel themes, landscapes, and narrative tone.",
            "Write a cinematic solo-wanderer story inspired by the vlog's themes.",
            "Break the story into wanderer-drama scenes across the analyzed landscapes.",
            "Design key frames inspired by the vlog's settings for each scene.",
            "Render motion-video clips from the key frames preserving the wanderer's journey.",
            "Transcribe the English dialogue across the scenes into timestamped SRT.",
            "Compose the final wanderer mini-drama with English subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this street-food clip and make a cinematic cooking-dream mini-drama, and Chinese subtitles.",
        "rationale": "Street-food clip reference + cooking-dream remake + Chinese subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the street-food vendor clip into the workspace as the reference.",
            "Analyze the clip to extract the vendor's craft, bustle, and urban mood.",
            "Write a cooking-dream mini-drama about a young cook's journey.",
            "Break the story into young-cook scenes across a bustling market.",
            "Design key frames inspired by the vendor clip's settings.",
            "Render motion-video clips preserving the market flavor.",
            "Transcribe the Chinese dialogue across the scenes into timestamped SRT.",
            "Compose the final cooking mini-drama with Chinese subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this dance-rehearsal clip and make a ballerina-comeback mini-drama, and English subtitles.",
        "rationale": "Dance-rehearsal reference + ballerina-comeback remake + English subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the dance-rehearsal clip into the workspace as the reference.",
            "Analyze the clip to extract rehearsal atmosphere and dancer motion.",
            "Write a ballerina-injury-comeback mini-drama inspired by the rehearsal clip.",
            "Break the story into comeback-drama scenes in the rehearsal studio.",
            "Design key frames inspired by the rehearsal clip's staging.",
            "Render motion-video clips preserving the rehearsal mood.",
            "Transcribe the English dialogue across the scenes into timestamped SRT.",
            "Compose the final ballerina mini-drama with English subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this abandoned-warehouse clip and make a noir-detective cat-and-mouse mini-drama, and Japanese subtitles.",
        "rationale": "Abandoned-warehouse reference + noir-detective remake + Japanese subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the abandoned-warehouse clip into the workspace as the reference.",
            "Analyze the clip to extract the warehouse's decay and atmosphere.",
            "Write a noir-detective mini-drama about chasing a killer in the warehouse.",
            "Break the story into noir-detective scenes across the warehouse.",
            "Design key frames inspired by the warehouse clip's architecture.",
            "Render motion-video clips preserving the noir warehouse mood.",
            "Transcribe the Japanese detective dialogue across the scenes into timestamped SRT.",
            "Compose the final noir mini-drama with Japanese subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this volcano-island drone clip and make a scientist-racing-against-time thriller, and Spanish subtitles.",
        "rationale": "Volcano-island drone reference + scientist-thriller remake + tense cinematic + Spanish subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the volcano-island drone clip into the workspace as the reference.",
            "Analyze the clip to extract island terrain and volcanic activity.",
            "Write a scientist-racing-against-time thriller about predicting the eruption.",
            "Break the story into thriller scenes across the volcanic island.",
            "Design key frames inspired by the drone clip's aerial perspective.",
            "Render motion-video clips preserving the volcanic-island mood.",
            "Transcribe the Spanish dialogue across the scenes into timestamped SRT.",
            "Compose the final thriller with Spanish subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this Japanese market clip and make a ghost-encounter period drama, and Japanese subtitles.",
        "rationale": "Japanese market reference + ghost-encounter period remake + Japanese subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the Japanese market clip into the workspace as the reference.",
            "Analyze the clip to extract market architecture and atmosphere.",
            "Write a ghost-encounter period drama inspired by the market clip.",
            "Break the story into period-drama scenes in the market.",
            "Design key frames inspired by the market clip's lanterns and stalls.",
            "Render motion-video clips preserving the Japanese-market mood.",
            "Transcribe the Japanese dialogue across the scenes into timestamped SRT.",
            "Compose the final period ghost mini-drama with Japanese subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this Caribbean beach clip and make a sunset-romance mini-drama about two strangers, and English subtitles.",
        "rationale": "Caribbean beach reference + sunset-romance remake + English subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the Caribbean-beach clip into the workspace as the reference.",
            "Analyze the clip to extract beach-bar atmosphere and sunset lighting.",
            "Write a sunset-romance mini-drama about two strangers on vacation.",
            "Break the story into beach-bar romance scenes at sunset.",
            "Design key frames inspired by the beach-bar setting.",
            "Render motion-video clips preserving the beach-bar mood.",
            "Transcribe the English dialogue across the scenes into timestamped SRT.",
            "Compose the final Caribbean romance mini-drama with English subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this Parisian café clip and make a rekindled-romance mini-drama, and French subtitles.",
        "rationale": "Parisian café reference + rekindled-romance remake + French subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the Parisian-café clip into the workspace as the reference.",
            "Analyze the clip to extract café atmosphere and Parisian character.",
            "Write a rekindled-romance mini-drama set at the café.",
            "Break the story into rekindled-romance scenes at and around the café.",
            "Design key frames inspired by the café's decor.",
            "Render motion-video clips preserving the Parisian mood.",
            "Transcribe the French dialogue across the scenes into timestamped SRT.",
            "Compose the final café mini-drama with French subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this Korean hanok-village clip and make a palace-era forbidden-love drama, with gentle gayageum, and Korean subtitles.",
        "rationale": "Korean hanok reference + palace-era forbidden-love remake + gentle gayageum + Korean subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the Korean hanok-village clip into the workspace as the reference.",
            "Analyze the clip to extract hanok architecture and period atmosphere.",
            "Write a palace-era forbidden-love drama in the hanok village.",
            "Break the story into forbidden-love scenes across the village.",
            "Design key frames inspired by the hanok architecture.",
            "Render motion-video clips preserving the village's period identity.",
            "Transcribe the Korean dialogue across the scenes into timestamped SRT.",
            "Compose the final palace-era mini-drama with Korean subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this Moroccan souk clip and make an exotic spice-trader mini-drama, and Arabic subtitles.",
        "rationale": "Moroccan souk reference + spice-trader remake + Arabic subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the Moroccan-souk clip into the workspace as the reference.",
            "Analyze the clip to extract souk atmosphere and market layout.",
            "Write an exotic spice-trader mini-drama set in the souk.",
            "Break the story into spice-trader scenes across the market.",
            "Design key frames inspired by the souk layout.",
            "Render motion-video clips preserving the souk's visual identity.",
            "Transcribe the Arabic dialogue across the scenes into timestamped SRT.",
            "Compose the final souk mini-drama with Arabic subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this Indian palace clip and make a Rajput princess drama about defying forced marriage, and Hindi subtitles.",
        "rationale": "Indian palace reference + Rajput princess remake + Hindi subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the Indian-palace clip into the workspace as the reference.",
            "Analyze the clip to extract palace architecture and period atmosphere.",
            "Write a Rajput princess mini-drama about defying a forced marriage.",
            "Break the story into princess-drama scenes across the palace.",
            "Design key frames inspired by the palace architecture.",
            "Render motion-video clips preserving the palace's period identity.",
            "Transcribe the Hindi dialogue across the scenes into timestamped SRT.",
            "Compose the final Rajput mini-drama with Hindi subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "and English subtitles.",
        "rationale": "winemaker-family succession + English subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the California-vineyard clip into the workspace as the reference.",
            "Analyze the clip to extract vineyard atmosphere and evening lighting.",
            "Write a winemaker-family-succession mini-drama at the vineyard.",
            "Break the story into succession-drama scenes across the vineyard.",
            "Design key frames inspired by the vineyard's golden-hour lighting.",
            "Render motion-video clips preserving the vineyard's visual identity.",
            "Transcribe the English dialogue across the scenes into timestamped SRT.",
            "Compose the final winemaker mini-drama with English subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this snow-covered lighthouse clip and make a keeper's-last-winter drama, and English subtitles.",
        "rationale": "Snow-covered lighthouse reference + keeper's-last-winter remake + English subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the snow-covered lighthouse clip into the workspace as the reference.",
            "Analyze the clip to extract lighthouse atmosphere and winter isolation.",
            "Write a keeper's-last-winter mini-drama at the lighthouse.",
            "Break the story into keeper-drama scenes inside and around the lighthouse.",
            "Design key frames inspired by the lighthouse architecture.",
            "Render motion-video clips preserving the lighthouse's visual identity.",
            "Transcribe the English dialogue across the scenes into timestamped SRT.",
            "Compose the final keeper mini-drama with English subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this Venice canal clip and make an 18th-century mask-ball romance mini-drama, and Italian subtitles.",
        "rationale": "Venice canal reference + 18th-century mask-ball romance + Italian subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the Venice-canal clip into the workspace as the reference.",
            "Analyze the clip to extract Venice architecture and period atmosphere.",
            "Write an 18th-century mask-ball romance mini-drama on the Venice canal.",
            "Break the story into mask-ball scenes along the canal.",
            "Design key frames inspired by Venice architecture.",
            "Render motion-video clips preserving the canal's visual identity.",
            "Transcribe the Italian dialogue across the scenes into timestamped SRT.",
            "Compose the final Venice mini-drama with Italian subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this Brooklyn brownstone clip and make a teenage-summer coming-of-age drama, with indie-folk acoustic, and English subtitles.",
        "rationale": "Brooklyn brownstone reference + coming-of-age remake + indie-folk + English subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the Brooklyn-brownstone clip into the workspace as the reference.",
            "Analyze the clip to extract brownstone atmosphere and summer mood.",
            "Write a teenage-summer coming-of-age mini-drama on the brownstone stoop.",
            "Break the story into coming-of-age scenes across the stoop and block.",
            "Design key frames inspired by the brownstone setting.",
            "Render motion-video clips preserving the brownstone's visual identity.",
            "Transcribe the English dialogue across the scenes into timestamped SRT.",
            "Compose the final coming-of-age mini-drama with English subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this Tibetan monastery clip and make a pilgrim-child mini-drama, and Tibetan subtitles.",
        "rationale": "Tibetan monastery reference + pilgrim-child remake + Tibetan subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the Tibetan-monastery clip into the workspace as the reference.",
            "Analyze the clip to extract monastery atmosphere and dusk lighting.",
            "Write a pilgrim-child mini-drama at the monastery.",
            "Break the story into pilgrim scenes around the monastery.",
            "Design key frames inspired by the monastery architecture.",
            "Render motion-video clips preserving the monastery's dusk mood.",
            "Transcribe the Tibetan dialogue across the scenes into timestamped SRT.",
            "Compose the final pilgrim mini-drama with Tibetan subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this Bavarian Christmas-market clip and make a holiday-miracle mini-drama about siblings reuniting, and German subtitles.",
        "rationale": "Bavarian Christmas market reference + holiday-miracle remake + German subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the Bavarian Christmas-market clip into the workspace as the reference.",
            "Analyze the clip to extract market atmosphere and festive mood.",
            "Write a holiday-miracle reunion mini-drama at the market.",
            "Break the story into reunion scenes across the market.",
            "Design key frames inspired by the Christmas-market layout.",
            "Render motion-video clips preserving the market's festive identity.",
            "Transcribe the German dialogue across the scenes into timestamped SRT.",
            "Compose the final holiday mini-drama with German subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this deep-sea submarine clip and make a first-contact mini-drama, and English subtitles.",
        "rationale": "Deep-sea submarine reference + first-contact remake + English subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the submarine clip into the workspace as the reference.",
            "Analyze the clip to extract submarine atmosphere and depth.",
            "Write a deep-sea first-contact mini-drama on the submarine.",
            "Break the story into first-contact scenes on the submarine bridge.",
            "Design key frames inspired by the submarine interior.",
            "Render motion-video clips preserving the submarine's tension.",
            "Transcribe the English dialogue across the scenes into timestamped SRT.",
            "Compose the final first-contact mini-drama with English subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this jungle-temple clip and make a lost-civilization explorer drama, and English subtitles.",
        "rationale": "Jungle-temple reference + lost-civilization explorer remake + sweeping adventure + English subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the jungle-temple clip into the workspace as the reference.",
            "Analyze the clip to extract temple atmosphere and jungle surroundings.",
            "Write an explorer mini-drama about discovering a lost civilization at the temple.",
            "Break the story into explorer-adventure scenes at the temple.",
            "Design key frames inspired by the jungle-temple setting.",
            "Render motion-video clips preserving the temple's mystery.",
            "Transcribe the English dialogue across the scenes into timestamped SRT.",
            "Compose the final explorer mini-drama with English subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this circus big-top clip and make a trapeze-artist family mini-drama, and English subtitles.",
        "rationale": "Circus big-top reference + trapeze-artist family remake + English subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the circus big-top clip into the workspace as the reference.",
            "Analyze the clip to extract circus atmosphere and trapeze dynamics.",
            "Write a trapeze-artist family mini-drama at the circus.",
            "Break the story into circus-family scenes in the big top.",
            "Design key frames inspired by the big-top staging.",
            "Render motion-video clips preserving the circus visual identity.",
            "Transcribe the English dialogue across the scenes into timestamped SRT.",
            "Compose the final circus mini-drama with English subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this mountain-rescue clip and make an action-thriller mini-drama about saving a climber, and English subtitles.",
        "rationale": "Mountain-rescue reference + action-thriller remake + English subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the mountain-rescue clip into the workspace as the reference.",
            "Analyze the clip to extract mountain terrain and rescue operation dynamics.",
            "Write an action-thriller about saving a stranded climber.",
            "Break the story into thriller scenes across mountain and helicopter.",
            "Design key frames inspired by the rescue clip.",
            "Render motion-video clips preserving the rescue intensity.",
            "Transcribe the English dialogue across the scenes into timestamped SRT.",
            "Compose the final action-thriller mini-drama with English subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this Moroccan medina clip and make a lost-tourist romance mini-drama, and Arabic subtitles.",
        "rationale": "Moroccan medina reference + lost-tourist romance remake + Arabic subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the Moroccan-medina clip into the workspace as the reference.",
            "Analyze the clip to extract medina atmosphere and alley layout.",
            "Write a lost-tourist romance mini-drama in the medina.",
            "Break the story into medina-romance scenes across the alleys.",
            "Design key frames inspired by the medina layout.",
            "Render motion-video clips preserving the medina's visual identity.",
            "Transcribe the Arabic dialogue across the scenes into timestamped SRT.",
            "Compose the final medina mini-drama with Arabic subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this deserted-motel clip and make a 1970s-noir road-trip mini-drama, with slow blues, and English subtitles.",
        "rationale": "Deserted-motel reference + 1970s-noir road-trip remake + slow blues + English subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the deserted-motel clip into the workspace as the reference.",
            "Analyze the clip to extract motel decay and 1970s period feel.",
            "Write a 1970s-noir road-trip mini-drama at the motel.",
            "Break the story into road-trip noir scenes.",
            "Design key frames inspired by the motel atmosphere.",
            "Render motion-video clips preserving the 1970s mood.",
            "Transcribe the English dialogue across the scenes into timestamped SRT.",
            "Compose the final 1970s-noir mini-drama with English subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "with Italian mandolin, and Italian subtitles.",
        "rationale": "family drama remake + mandolin + Italian subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the Tuscan-vineyard clip into the workspace as the reference.",
            "Analyze the clip to extract vineyard atmosphere and harvest season.",
            "Write a Tuscan family harvest drama mini-drama.",
            "Break the story into harvest-family scenes across the vineyard.",
            "Design key frames inspired by the vineyard layout.",
            "Render motion-video clips preserving the Tuscan mood.",
            "Transcribe the Italian dialogue across the scenes into timestamped SRT.",
            "Compose the final Tuscan mini-drama with Italian subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this forest-cabin clip and make a cabin-recluse-meets-stranger mini-drama, and English subtitles.",
        "rationale": "Forest-cabin reference + recluse-meets-stranger remake + English subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the forest-cabin clip into the workspace as the reference.",
            "Analyze the clip to extract cabin atmosphere and forest isolation.",
            "Write a cabin-recluse-meets-stranger mini-drama at the cabin.",
            "Break the story into cabin-intrigue scenes.",
            "Design key frames inspired by the cabin's interior and forest.",
            "Render motion-video clips preserving the cabin's visual identity.",
            "Transcribe the English dialogue across the scenes into timestamped SRT.",
            "Compose the final cabin mini-drama with English subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this pottery-studio clip and make a master-and-apprentice drama, and Japanese subtitles.",
        "rationale": "Pottery-studio reference + master-apprentice remake + Japanese subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the pottery-studio clip into the workspace as the reference.",
            "Analyze the clip to extract studio atmosphere and craft details.",
            "Write a master-and-apprentice mini-drama at the pottery studio.",
            "Break the story into master-apprentice scenes in the studio.",
            "Design key frames inspired by the studio clip's layout.",
            "Render motion-video clips preserving the pottery-studio mood.",
            "Transcribe the Japanese dialogue across the scenes into timestamped SRT.",
            "Compose the final apprentice mini-drama with Japanese subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this fishing-village clip and make a seaside romance mini-drama, and Portuguese subtitles.",
        "rationale": "Fishing-village reference + seaside romance remake + Portuguese subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the fishing-village clip into the workspace as the reference.",
            "Analyze the clip to extract village atmosphere and seaside life.",
            "Write a seaside romance mini-drama set in the fishing village.",
            "Break the story into seaside-romance scenes in and around the village.",
            "Design key frames inspired by the village setting.",
            "Render motion-video clips preserving the village's visual identity.",
            "Transcribe the Portuguese dialogue across the scenes into timestamped SRT.",
            "Compose the final fishing-village mini-drama with Portuguese subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this steampunk-workshop clip and make an inventor-and-rival mini-drama, with steampunk brass-clockwork, and English subtitles.",
        "rationale": "Steampunk-workshop reference + inventor-and-rival remake + steampunk brass-clockwork + English subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the steampunk-workshop clip into the workspace as the reference.",
            "Analyze the clip to extract workshop atmosphere and inventor's craft.",
            "Write an inventor-and-rival mini-drama in the workshop.",
            "Break the story into inventor-rivalry scenes across the workshop.",
            "Design key frames inspired by the steampunk workshop layout.",
            "Render motion-video clips preserving the workshop's visual identity.",
            "Transcribe the English dialogue across the scenes into timestamped SRT.",
            "Compose the final steampunk mini-drama with English subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this library clip and make a young-scholar-finds-a-secret-book mini-drama, and English subtitles.",
        "rationale": "Library reference + young-scholar remake + English subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the library clip into the workspace as the reference.",
            "Analyze the clip to extract library atmosphere and shelving layout.",
            "Write a young-scholar-finds-a-secret-book mini-drama in the library.",
            "Break the story into discovery scenes inside the library.",
            "Design key frames inspired by the library's shelves and decor.",
            "Render motion-video clips preserving the library's visual identity.",
            "Transcribe the English dialogue across the scenes into timestamped SRT.",
            "Compose the final scholar mini-drama with English subtitles and mixed audio.",
        ],
    },
    {
        "user_goal": "Analyze this wine-cellar clip and make a family-secret mini-drama about a hidden will, with melancholic string-quartet, and French subtitles.",
        "rationale": "Wine-cellar reference + family-secret remake + melancholic string-quartet + French subtitles. Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Ingest the wine-cellar clip into the workspace as the reference.",
            "Analyze the clip to extract cellar atmosphere and family history feel.",
            "Write a family-secret mini-drama about a hidden will in the wine cellar.",
            "Break the story into family-secret scenes in the cellar.",
            "Design key frames inspired by the wine-cellar layout.",
            "Render motion-video clips preserving the cellar's visual identity.",
            "Transcribe the French dialogue across the scenes into timestamped SRT.",
            "Compose the final family-secret mini-drama with French subtitles and mixed audio.",
        ],
    },
]
