"""Shape: intake_img_cr_extend —
    IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor.

Image-referenced mini-drama, extended beyond default duration, no audio overlay. (Path B alignment with v3 eval — opt-in audio: chain has Music/Ambience/AudioMix iff user_goal explicitly mentions audio.)
"""
from __future__ import annotations

SAMPLES: list[dict] = [
    {
        "user_goal": "Using this uploaded character portrait, make an extended-length wuxia mini-drama about a disciple's revenge.",
        "rationale": "Image-referenced wuxia revenge, extended duration. Chain extends the base creative clip before audio layering. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded wuxia character portrait as the visual reference.",
            "Enrich the character brief combining image features with the wuxia-revenge concept.",
            "Write the wuxia disciple-revenge story.",
            "Break the story into wuxia-revenge scenes.",
            "Design key frames matching the uploaded character's likeness.",
            "Render motion-video clips preserving the wuxia character continuity.",
            "Extend the wuxia-video clips to the requested longer runtime.",
            "Compose the extended wuxia mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded photo of a coastal cliff, make an extended-length pirate-adventure mini-drama.",
        "rationale": "Image-referenced pirate-adventure extended. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded coastal-cliff photo as the visual reference.",
            "Enrich the setting brief combining cliff atmosphere with pirate-adventure concept.",
            "Write the pirate-adventure story at the coastal cliff.",
            "Break the story into pirate-adventure scenes.",
            "Design key frames matching the uploaded cliff landscape.",
            "Render motion-video clips preserving the pirate-adventure continuity.",
            "Extend the clips to the requested longer runtime.",
            "Compose the extended pirate mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a haunted Victorian mansion, make an extended-length gothic-ghost mini-drama.",
        "rationale": "Image-referenced haunted-mansion gothic-ghost extended + haunting pipe-organ. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Victorian-mansion photo as the visual reference.",
            "Enrich the setting brief combining mansion atmosphere with gothic-ghost concept.",
            "Write the gothic-ghost story at the mansion.",
            "Break the story into gothic-ghost mansion scenes.",
            "Design key frames matching the uploaded mansion architecture.",
            "Render motion-video clips preserving the gothic mansion continuity.",
            "Extend the gothic clips to the longer requested runtime.",
            "Compose the extended gothic mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded cyberpunk-city image, make an extended hacker mini-drama.",
        "rationale": "Image-referenced cyberpunk hacker extended. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded cyberpunk-city image as the visual reference.",
            "Enrich the setting brief combining cyberpunk city with hacker concept.",
            "Write the cyberpunk hacker story.",
            "Break the story into cyberpunk hacker scenes.",
            "Design key frames matching the uploaded cyberpunk cityscape.",
            "Render motion-video clips preserving cyberpunk continuity.",
            "Extend the cyberpunk clips to the longer requested runtime.",
            "Compose the extended cyberpunk mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a volcanic island, make an extended scientist-racing-against-eruption mini-drama.",
        "rationale": "Image-referenced volcanic-island scientist-thriller extended + tense cinematic. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded volcanic-island image as the visual reference.",
            "Enrich the setting brief combining island atmosphere with scientist-eruption concept.",
            "Write the scientist-racing-eruption story.",
            "Break the story into eruption thriller scenes.",
            "Design key frames matching the uploaded island topology.",
            "Render motion-video clips preserving the volcanic-island continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended volcanic mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Siberian tundra, make an extended reindeer-herder mini-drama.",
        "rationale": "Image-referenced Siberian-tundra herder extended + haunting Nordic-strings. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Siberian-tundra image as the visual reference.",
            "Enrich the setting brief combining tundra atmosphere with reindeer-herder concept.",
            "Write the reindeer-herder story on the tundra.",
            "Break the story into tundra-herder scenes.",
            "Design key frames matching the uploaded tundra landscape.",
            "Render motion-video clips preserving the tundra continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended Siberian mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a desert oasis, make an extended-length nomad-princess mini-drama.",
        "rationale": "Image-referenced desert-oasis nomad-princess extended + Middle-Eastern-fusion. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded desert-oasis image as the visual reference.",
            "Enrich the setting brief combining oasis atmosphere with nomad-princess concept.",
            "Write the nomad-princess story at the oasis.",
            "Break the story into nomad-princess scenes.",
            "Design key frames matching the uploaded oasis layout.",
            "Render motion-video clips preserving the oasis continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended nomad mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Scottish Highland estate, make an extended heir-reclaim mini-drama.",
        "rationale": "Image-referenced Scottish-Highland heir-reclaim extended + bagpipe. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Scottish-Highland estate image as the visual reference.",
            "Enrich the setting brief combining Highland atmosphere with heir-reclaim concept.",
            "Write the heir-reclaim story at the Highland estate.",
            "Break the story into heir-reclaim scenes.",
            "Design key frames matching the uploaded Highland estate.",
            "Render motion-video clips preserving the Highland continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended Highland mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a dragon-nest mountain peak, make an extended-length dragon-rider mini-drama.",
        "rationale": "Image-referenced dragon-nest mountain dragon-rider extended + cinematic fantasy. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded dragon-nest mountain-peak image as the visual reference.",
            "Enrich the setting brief combining mountain atmosphere with dragon-rider concept.",
            "Write the dragon-rider story at the mountain peak.",
            "Break the story into dragon-rider scenes.",
            "Design key frames matching the uploaded mountain-peak landscape.",
            "Render motion-video clips preserving the dragon-rider continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended dragon mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a foggy English moor, make an extended-length Brontë-style romance drama.",
        "rationale": "Image-referenced English-moor Brontë-romance extended + lush period-strings. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded foggy English-moor image as the visual reference.",
            "Enrich the setting brief combining moor atmosphere with Brontë-romance concept.",
            "Write the Brontë-style romance story on the moor.",
            "Break the story into Brontë-moor romance scenes.",
            "Design key frames matching the uploaded moor landscape.",
            "Render motion-video clips preserving the moor continuity.",
            "Extend the moor-romance clips to the longer requested runtime.",
            "Compose the extended Brontë mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a stormy Scottish castle, make an extended-length haunted-castle mini-drama.",
        "rationale": "Image-referenced Scottish-castle haunted-castle extended + gothic pipe-organ. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded stormy Scottish-castle image as the visual reference.",
            "Enrich the setting brief combining castle atmosphere with haunted-castle concept.",
            "Write the haunted-castle story at the storm-bound castle.",
            "Break the story into haunted-castle scenes.",
            "Design key frames matching the uploaded castle architecture.",
            "Render motion-video clips preserving the castle continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended castle mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a sprawling Silk Road caravanserai, make an extended-length merchant-adventure mini-drama.",
        "rationale": "Image-referenced Silk-Road caravanserai merchant-adventure extended. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Silk Road caravanserai image as the visual reference.",
            "Enrich the setting brief combining caravanserai atmosphere with merchant-adventure concept.",
            "Write the merchant-adventure story at the caravanserai.",
            "Break the story into merchant-adventure scenes.",
            "Design key frames matching the uploaded caravanserai architecture.",
            "Render motion-video clips preserving the caravanserai continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended merchant mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a deep-jungle temple, make an extended lost-civilization explorer mini-drama.",
        "rationale": "Image-referenced jungle-temple explorer extended. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded jungle-temple image as the visual reference.",
            "Enrich the setting brief combining temple atmosphere with explorer concept.",
            "Write the lost-civilization explorer story at the temple.",
            "Break the story into explorer-adventure scenes.",
            "Design key frames matching the uploaded temple architecture.",
            "Render motion-video clips preserving the temple continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended explorer mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of an ancient Egyptian tomb, make an extended-length Egyptologist mini-drama.",
        "rationale": "Image-referenced Egyptian-tomb Egyptologist extended. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Egyptian-tomb image as the visual reference.",
            "Enrich the setting brief combining tomb atmosphere with Egyptologist concept.",
            "Write the Egyptologist story at the tomb.",
            "Break the story into tomb-discovery scenes.",
            "Design key frames matching the uploaded tomb architecture.",
            "Render motion-video clips preserving the Egyptologist continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended Egyptology mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a submerged shipwreck, make an extended-length salvage-diver mini-drama.",
        "rationale": "Image-referenced shipwreck salvage-diver extended. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded submerged-shipwreck image as the visual reference.",
            "Enrich the setting brief combining shipwreck atmosphere with salvage-diver concept.",
            "Write the salvage-diver story at the wreck.",
            "Break the story into salvage-diver scenes.",
            "Design key frames matching the uploaded shipwreck angle.",
            "Render motion-video clips preserving the deep-sea salvage continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended salvage mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Himalayan glacier, make an extended mountaineer mini-drama.",
        "rationale": "Image-referenced Himalayan-glacier mountaineer extended. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Himalayan-glacier image as the visual reference.",
            "Enrich the setting brief combining glacier atmosphere with mountaineer concept.",
            "Write the mountaineer story on the glacier.",
            "Break the story into mountaineer scenes.",
            "Design key frames matching the uploaded glacier landscape.",
            "Render motion-video clips preserving the glacier continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended mountaineer mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Parisian rooftop, make an extended-length rooftop-artist mini-drama.",
        "rationale": "Image-referenced Parisian-rooftop artist extended. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Parisian rooftop image as the visual reference.",
            "Enrich the setting brief combining rooftop atmosphere with rooftop-artist concept.",
            "Write the rooftop-artist story in Paris.",
            "Break the story into rooftop-artist scenes.",
            "Design key frames matching the uploaded rooftop view.",
            "Render motion-video clips preserving the rooftop continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended Parisian mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Victorian railway station, make an extended-length wartime-farewell mini-drama.",
        "rationale": "Image-referenced Victorian-railway wartime-farewell extended + bittersweet quartet. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Victorian-railway-station image as the visual reference.",
            "Enrich the setting brief combining station atmosphere with wartime-farewell concept.",
            "Write the wartime-farewell story at the station.",
            "Break the story into wartime-farewell scenes.",
            "Design key frames matching the uploaded station architecture.",
            "Render motion-video clips preserving the Victorian-station continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended wartime mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Navajo desert canyon, make an extended-length coming-of-age mini-drama.",
        "rationale": "Image-referenced Navajo-canyon coming-of-age extended. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Navajo-desert canyon image as the visual reference.",
            "Enrich the setting brief combining canyon atmosphere with coming-of-age concept.",
            "Write the coming-of-age story in the canyon.",
            "Break the story into coming-of-age canyon scenes.",
            "Design key frames matching the uploaded canyon landscape.",
            "Render motion-video clips preserving the canyon continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended canyon mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Mediterranean harbor, make an extended fisherman-to-mayor mini-drama.",
        "rationale": "Image-referenced Mediterranean-harbor fisherman-mayor extended + Mediterranean-folk. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Mediterranean-harbor image as the visual reference.",
            "Enrich the setting brief combining harbor atmosphere with fisherman-to-mayor concept.",
            "Write the fisherman-to-mayor story at the harbor.",
            "Break the story into fisherman-turned-mayor scenes.",
            "Design key frames matching the uploaded harbor view.",
            "Render motion-video clips preserving the harbor continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended harbor mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Nordic fjord, make an extended sailing mini-drama.",
        "rationale": "Image-referenced Nordic-fjord sailing extended. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Nordic-fjord image as the visual reference.",
            "Enrich the setting brief combining fjord atmosphere with sailing concept.",
            "Write the Nordic sailing story.",
            "Break the story into fjord-sailing scenes.",
            "Design key frames matching the uploaded fjord landscape.",
            "Render motion-video clips preserving the fjord continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended Nordic mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Moroccan riad, make an extended riad-keeper mini-drama.",
        "rationale": "Image-referenced Moroccan-riad keeper extended + Arabic-andalusian fusion. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Moroccan-riad image as the visual reference.",
            "Enrich the setting brief combining riad atmosphere with riad-keeper concept.",
            "Write the riad-keeper story.",
            "Break the story into riad-keeper scenes.",
            "Design key frames matching the uploaded riad architecture.",
            "Render motion-video clips preserving the riad continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended riad mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a cherry-blossom-filled Tokyo park, make an extended young-park-gardener mini-drama.",
        "rationale": "Image-referenced Tokyo cherry-blossom park gardener extended. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded cherry-blossom Tokyo-park image as the visual reference.",
            "Enrich the setting brief combining park atmosphere with park-gardener concept.",
            "Write the young-park-gardener story.",
            "Break the story into park-gardener scenes.",
            "Design key frames matching the uploaded cherry-blossom park.",
            "Render motion-video clips preserving the Tokyo-park continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended Tokyo-park mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Gulf of Mexico oil rig, make an extended rig-worker thriller mini-drama.",
        "rationale": "Image-referenced Gulf oil-rig thriller extended. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Gulf oil-rig image as the visual reference.",
            "Enrich the setting brief combining rig atmosphere with rig-worker-thriller concept.",
            "Write the rig-worker thriller story.",
            "Break the story into rig-thriller scenes.",
            "Design key frames matching the uploaded rig architecture.",
            "Render motion-video clips preserving the rig continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended rig mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Galápagos beach, make an extended-length young-biologist mini-drama.",
        "rationale": "Image-referenced Galápagos-beach biologist extended. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Galápagos-beach image as the visual reference.",
            "Enrich the setting brief combining beach atmosphere with young-biologist concept.",
            "Write the young-biologist story on the Galápagos.",
            "Break the story into biologist-field scenes.",
            "Design key frames matching the uploaded beach landscape.",
            "Render motion-video clips preserving the Galápagos continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended Galápagos mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Tokyo shoutengai street, make an extended-length ramen-shop-daughter mini-drama.",
        "rationale": "Image-referenced Tokyo-shoutengai ramen-shop daughter extended + bossa-nova-japan-fusion. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Tokyo shoutengai image as the visual reference.",
            "Enrich the setting brief combining shoutengai atmosphere with ramen-shop-daughter concept.",
            "Write the ramen-shop-daughter story.",
            "Break the story into ramen-shop scenes.",
            "Design key frames matching the uploaded shoutengai street.",
            "Render motion-video clips preserving the shoutengai continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended shoutengai mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Rio favela, make an extended young-capoeirista mini-drama.",
        "rationale": "Image-referenced Rio-favela capoeirista extended + berimbau. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Rio-favela image as the visual reference.",
            "Enrich the setting brief combining favela atmosphere with capoeirista concept.",
            "Write the young-capoeirista story in the favela.",
            "Break the story into capoeirista scenes.",
            "Design key frames matching the uploaded favela layout.",
            "Render motion-video clips preserving the favela continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended favela mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Himalayan salt mine, make an extended-length salt-miner mini-drama.",
        "rationale": "Image-referenced Himalayan-salt-mine miner extended + Tibetan-chant. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Himalayan-salt-mine image as the visual reference.",
            "Enrich the setting brief combining salt-mine atmosphere with salt-miner concept.",
            "Write the salt-miner story in the Himalayan mine.",
            "Break the story into salt-miner scenes.",
            "Design key frames matching the uploaded mine interior.",
            "Render motion-video clips preserving the mine continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended salt-mine mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Venetian glass-blower's workshop, make an extended-length young-glassblower mini-drama.",
        "rationale": "Image-referenced Venetian-glassblower extended + Italian-baroque. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Venetian-glassblower workshop image as the visual reference.",
            "Enrich the setting brief combining workshop atmosphere with young-glassblower concept.",
            "Write the young-glassblower story in the workshop.",
            "Break the story into glassblower scenes.",
            "Design key frames matching the uploaded workshop layout.",
            "Render motion-video clips preserving the Venetian continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended Venetian mini-drama with all layers assembled.",
        ],
    },
    {
        "user_goal": "Using this uploaded image of a Saharan dune caravan, make an extended-length desert-caravan mini-drama.",
        "rationale": "Image-referenced Sahara-caravan extended + Middle-Eastern-fusion. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Ingest the uploaded Saharan-dune caravan image as the visual reference.",
            "Enrich the setting brief combining caravan atmosphere with desert-caravan concept.",
            "Write the desert-caravan story across the Sahara.",
            "Break the story into caravan scenes.",
            "Design key frames matching the uploaded caravan landscape.",
            "Render motion-video clips preserving the Saharan continuity.",
            "Extend the clips to the longer requested runtime.",
            "Compose the extended caravan mini-drama with all layers assembled.",
        ],
    },
]
