"""x15 story_music_bilingual SFT.
Chain: Narration → Illustration → Narrator → Music → AudioMix → Translation → Compositor.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Tell me a children's audiobook in Spanish about a young dragon, with soft-piano BGM and English subtitles.",
    "I want an illustrated audiobook in French about a young witch and her cat, with whimsical-flute BGM and English subtitles.",
    "Make me a bedtime audiobook in Mandarin about a moon rabbit, with classical-guzheng BGM and English subtitles.",
    "Create a picture-book audiobook in Korean about a tiger and a persimmon tree, with traditional-haegeum BGM and English subtitles.",
    "Produce an illustrated children's tale in Japanese about a paper crane, with shamisen BGM and English subtitles.",
    "Generate a kids' audiobook in German about a young owl learning to fly, with classical-strings BGM and English subtitles.",
    "Build a narrated picture-book in Italian about a curious mouse, with Italian-mandolin BGM and English subtitles.",
    "Render a children's audiobook in Portuguese about a young toucan, with Brazilian-cuíca BGM and English subtitles.",
    "I'd like a bedtime audiobook in Russian about a young bear cub, with balalaika BGM and English subtitles.",
    "Tell me a children's audiobook in Polish about a young fox, with Polish-folk-fiddle BGM and English subtitles.",
    "Make a soft picture-book audiobook in Swedish about a young reindeer, with Swedish-folk-fiddle BGM and English subtitles.",
    "Cook up a children's audiobook in Norwegian about a young troll, with Norwegian-fiddle BGM and English subtitles.",
    "Generate a narrated picture-book in Finnish about a young white wolf, with Finnish-folk BGM and English subtitles.",
    "Produce a children's audiobook in Greek about a young sea-turtle, with Greek-bouzouki BGM and English subtitles.",
    "Build a bedtime audiobook in Turkish about a young hedgehog, with Turkish-saz BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Hebrew about a baby owl, with Hebrew-folk BGM and English subtitles.",
    "Make me a picture-book audiobook in Arabic about a young desert fox, with oud BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Persian about a young nightingale, with Persian-santur BGM and English subtitles.",
    "Generate a children's bedtime audiobook in Hindi about a young peacock, with bansuri BGM and English subtitles.",
    "Produce a kids' picture-book audiobook in Tamil about a young elephant, with Indian-classical BGM and English subtitles.",
    "Build an illustrated children's audiobook in Bengali about a young tiger cub, with Indian-folk BGM and English subtitles.",
    "Tell me a children's audiobook in Vietnamese about a young water buffalo, with Vietnamese-dan-bau BGM and English subtitles.",
    "Make a narrated picture-book audiobook in Thai about a young monkey, with Thai-classical BGM and English subtitles.",
    "Render a children's audiobook in Khmer about a young temple cat, with Khmer-flute BGM and English subtitles.",
    "I'd like a bedtime audiobook in Indonesian about a young komodo dragon, with gamelan BGM and English subtitles.",
    "Cook up a children's audiobook in Tagalog about a young carabao, with Tagalog-folk BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Malay about a young pangolin, with Malay-folk BGM and English subtitles.",
    "Produce a narrated children's audiobook in Swahili about a young giraffe, with Swahili-taarab BGM and English subtitles.",
    "Build a bedtime audiobook in Yoruba about a young leopard cub, with Yoruba-juju BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Zulu about a young rhino, with Zulu-isicathamiya BGM and English subtitles.",
    "Make me a picture-book audiobook in Amharic about a young hyena cub, with Ethiopian-azmari BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Quechua about a young llama, with Andean-quena BGM and Spanish subtitles.",
    "Generate a children's bedtime audiobook in Aymara about a young vicuña, with Andean-pan-flute BGM and Spanish subtitles.",
    "Produce a kids' picture-book audiobook in Nahuatl about a young hummingbird, with Mexican-folk BGM and Spanish subtitles.",
    "Build an illustrated children's audiobook in Mapudungun about a young condor, with Mapuche-trutruka BGM and Spanish subtitles.",
    # ── more illustrated children's audiobooks with BGM and bilingual subtitles (50)
    "Tell me a children's audiobook in Dutch about a young hare on the dunes, with Dutch-folk BGM and English subtitles.",
    "Make me an illustrated audiobook in Danish about a young Copenhagen swan, with Danish-folk BGM and English subtitles.",
    "Cook up a bedtime audiobook in Hungarian about a young Puszta horse, with Hungarian-csárdás BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Romanian about a young Carpathian wolf cub, with Romanian-fiddle BGM and English subtitles.",
    "Produce a children's audiobook in Bulgarian about a young Rhodope lamb, with Bulgarian-gaida BGM and English subtitles.",
    "Build a narrated picture-book audiobook in Slovak about a young High-Tatra chamois, with Slovak-fujara BGM and English subtitles.",
    "Render a children's audiobook in Slovenian about a young Triglav ibex, with Slovenian-folk BGM and English subtitles.",
    "I'd like a bedtime audiobook in Croatian about a young Adriatic dolphin, with klapa-vocals BGM and English subtitles.",
    "Tell me a children's audiobook in Serbian about a young Tara wolf, with Serbian-trumpet BGM and English subtitles.",
    "Make a picture-book audiobook in Bosnian about a young Bjelašnica horse, with sevdah-strings BGM and English subtitles.",
    "Cook up a children's audiobook in Albanian about a young Accursed-Mountains eagle, with Albanian-iso-polyphonic BGM and English subtitles.",
    "Generate a narrated picture-book in Ukrainian about a young steppe wolf, with Ukrainian-bandura BGM and English subtitles.",
    "Produce a children's audiobook in Belarusian about a young Białowieża bison, with Belarusian-folk BGM and English subtitles.",
    "Build a bedtime audiobook in Lithuanian about a young Curonian seal, with Lithuanian-kanklės BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Latvian about a young Gauja deer, with Latvian-folk-fiddle BGM and English subtitles.",
    "Make me a picture-book audiobook in Estonian about a young Lahemaa moose, with Estonian-regilaul BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Catalan about a young Pyrenean brown bear, with Catalan-folk BGM and Spanish subtitles.",
    "Generate a children's bedtime audiobook in Galician about a young Atlantic puffin, with Galician-gaita BGM and Spanish subtitles.",
    "Produce a kids' picture-book audiobook in Basque about a young Pyrenean lammergeier, with Basque-txistu BGM and Spanish subtitles.",
    "Build an illustrated children's audiobook in Welsh about a young Snowdonia mountain pony, with Welsh-folk BGM and English subtitles.",
    "Tell me a children's audiobook in Irish-Gaelic about a young Connemara pony, with Irish-fiddle BGM and English subtitles.",
    "Make a narrated picture-book audiobook in Scottish-Gaelic about a young Highland-cow calf, with bagpipe BGM and English subtitles.",
    "Render a children's audiobook in Cornish about a young Cornish chough, with Cornish-bagpipe BGM and English subtitles.",
    "I'd like a bedtime audiobook in Manx about a young Manx-cat kitten, with Manx-fiddle BGM and English subtitles.",
    "Cook up a children's audiobook in Breton about a young Crozon dolphin, with Breton-bombarde BGM and French subtitles.",
    "Generate a kids' picture-book audiobook in Faroese about a young Faroese pony, with Faroese-kvæði BGM and Danish subtitles.",
    "Produce a narrated children's audiobook in Icelandic about a young Icelandic horse, with Icelandic-folk BGM and English subtitles.",
    "Build a bedtime audiobook in Lao about a young Mekong elephant, with Lao-khaen BGM and Thai subtitles.",
    "Tell me an illustrated children's audiobook in Burmese about a young Irrawaddy dolphin, with Burmese-saung BGM and English subtitles.",
    "Make me a picture-book audiobook in Hmong about a young Sapa village calf, with Hmong-qeej BGM and Vietnamese subtitles.",
    "Cook up a narrated children's audiobook in Javanese about a young Wayang shadow puppet, with Javanese-gamelan BGM and Indonesian subtitles.",
    "Generate a children's bedtime audiobook in Sundanese about a young Sundanese cassowary, with Sundanese-angklung BGM and Indonesian subtitles.",
    "Produce a kids' picture-book audiobook in Balinese about a young Bali starling, with Balinese-gamelan BGM and Indonesian subtitles.",
    "Build an illustrated children's audiobook in Cebuano about a young tarsier, with Cebuano-rondalla BGM and Tagalog subtitles.",
    "Tell me a children's audiobook in Punjabi about a young Punjabi sparrow, with Punjabi-dhol BGM and Hindi subtitles.",
    "Make a narrated picture-book audiobook in Marathi about a young Pune peacock, with Marathi-folk BGM and Hindi subtitles.",
    "Render a children's audiobook in Gujarati about a young Asiatic lion cub, with Gujarati-garba BGM and Hindi subtitles.",
    "I'd like a bedtime audiobook in Telugu about a young Hyderabad parrot, with Telugu-classical BGM and English subtitles.",
    "Cook up a children's audiobook in Malayalam about a young Kerala elephant, with Kerala-chenda BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Sinhalese about a young Sri-Lankan leopard cub, with Sri-Lankan-percussion BGM and Tamil subtitles.",
    "Produce a narrated children's audiobook in Nepali about a young Himalayan snow leopard, with Nepali-madal BGM and English subtitles.",
    "Build a bedtime audiobook in Dzongkha about a young Bhutanese takin, with Bhutanese-flute BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Tibetan about a young Tibetan antelope, with Tibetan-singing-bowl BGM and Mandarin subtitles.",
    "Make me a picture-book audiobook in Mongolian about a young Bactrian camel, with Mongolian-throat-singing BGM and Russian subtitles.",
    "Cook up a narrated children's audiobook in Pashto about a young Hindu-Kush ibex, with Afghan-rubab BGM and Dari subtitles.",
    "Generate a children's bedtime audiobook in Urdu about a young Pakistani markhor, with Pakistani-tabla BGM and English subtitles.",
    "Produce a kids' picture-book audiobook in Kazakh about a young steppe falcon, with Kazakh-dombra BGM and Russian subtitles.",
    "Build an illustrated children's audiobook in Uzbek about a young Aral-Sea fox, with Uzbek-doira BGM and Russian subtitles.",
    "Tell me a children's audiobook in Kyrgyz about a young Tian-Shan eagle, with Kyrgyz-komuz BGM and Russian subtitles.",
    "Make a narrated picture-book audiobook in Tajik about a young Pamir snow leopard, with Tajik-rubab BGM and Russian subtitles.",
    # ── more illustrated children's audiobooks with BGM and bilingual subtitles (50)
    "Tell me a children's audiobook in Haitian-Kreyòl about a young Caribbean parrot, with Haitian-Kompa BGM and French subtitles.",
    "Make me an illustrated audiobook in Jamaican-Patois about a young tropical mongoose, with reggae BGM and English subtitles.",
    "Cook up a bedtime audiobook in Trinidadian-Creole about a young Trinidad iguana, with soca BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Bahamian-Creole about a young Caribbean flamingo, with goombay BGM and English subtitles.",
    "Produce a children's audiobook in Saint-Lucian-Kwéyòl about a young Saint-Lucian parrot, with Saint-Lucian-folk BGM and English subtitles.",
    "Build a narrated picture-book audiobook in Papiamento about a young Curaçao iguana, with tambú BGM and Dutch subtitles.",
    "Render a children's audiobook in Sranan-Tongo about a young Surinamese tapir, with kaseko BGM and Dutch subtitles.",
    "I'd like a bedtime audiobook in Rapa-Nui about a young Easter-Island bird, with Polynesian-drum BGM and Spanish subtitles.",
    "Tell me a children's audiobook in Hokkien about a young Singapore long-tailed macaque, with Hokkien-getai BGM and Mandarin subtitles.",
    "Make a picture-book audiobook in Hakka about a young Taiwan pangolin, with Hakka-folk BGM and Mandarin subtitles.",
    "Cook up a children's audiobook in Teochew about a young river fish, with Teochew-folk BGM and Mandarin subtitles.",
    "Generate a narrated picture-book in Cantonese about a young Hong-Kong parrot, with Cantonese-folk BGM and English subtitles.",
    "Produce a children's audiobook in Min-Nan about a young Fujian deer, with Min-Nan-bei-guan BGM and Mandarin subtitles.",
    "Build a bedtime audiobook in Shanghainese about a young Yangtze finless-porpoise, with Shanghai-pop BGM and Mandarin subtitles.",
    "Tell me an illustrated children's audiobook in Wu about a young Suzhou egret, with Suzhou-opera BGM and Mandarin subtitles.",
    "Make me a picture-book audiobook in Macanese-Patuá about a young Macau cat, with Macanese-fado BGM and Portuguese subtitles.",
    "Cook up a narrated children's audiobook in Tagalog about a young Philippine eagle, with Filipino-rondalla BGM and English subtitles.",
    "Generate a children's bedtime audiobook in Ilocano about a young Luzon mountain mouse, with Ilocano-folk BGM and Tagalog subtitles.",
    "Produce a kids' picture-book audiobook in Hiligaynon about a young Visayan warty pig, with Hiligaynon-folk BGM and Tagalog subtitles.",
    "Build an illustrated children's audiobook in Maranao about a young Mindanao civet, with Maranao-kulintang BGM and Tagalog subtitles.",
    "Tell me a children's audiobook in Tausug about a young Sulu hornbill, with Tausug-kulintang BGM and Tagalog subtitles.",
    "Make a narrated picture-book audiobook in Acehnese about a young Sumatran orangutan, with Acehnese-rapai BGM and Indonesian subtitles.",
    "Render a children's audiobook in Toraja about a young water-buffalo, with Toraja-pa'pompang BGM and Indonesian subtitles.",
    "I'd like a bedtime audiobook in Batak about a young Lake-Toba fish, with Batak-gondang BGM and Indonesian subtitles.",
    "Cook up a children's audiobook in Minangkabau about a young Sumatran rhino, with Minangkabau-talempong BGM and Indonesian subtitles.",
    "Generate a kids' picture-book audiobook in Sasak about a young Lombok deer, with Sasak-gendang BGM and Indonesian subtitles.",
    "Produce a narrated children's audiobook in Buginese about a young Sulawesi anoa, with Buginese-kecapi BGM and Indonesian subtitles.",
    "Build a bedtime audiobook in Dayak about a young Borneo elephant, with Dayak-sape BGM and Indonesian subtitles.",
    "Tell me an illustrated children's audiobook in Iban about a young Borneo hornbill, with Iban-sape BGM and Malay subtitles.",
    "Make me a picture-book audiobook in Bidayuh about a young Borneo Sun-bear, with Bidayuh-pratuokng BGM and Malay subtitles.",
    "Cook up a narrated children's audiobook in Igorot about a young Cordillera cloud-rat, with Igorot-gangsa BGM and Tagalog subtitles.",
    "Generate a children's bedtime audiobook in Hmong about a young Sapa water-buffalo, with Hmong-qeej BGM and Lao subtitles.",
    "Produce a kids' picture-book audiobook in Lao about a young Mekong Irrawaddy-dolphin, with Lao-khaen BGM and Thai subtitles.",
    "Build an illustrated children's audiobook in Karen about a young elephant, with Karen-tlow BGM and Thai subtitles.",
    "Tell me a children's audiobook in Mon about a young Gulf-of-Martaban fishing-cat, with Mon-saung BGM and Burmese subtitles.",
    "Make a narrated picture-book audiobook in Shan about a young Tai-Yai forest-pig, with Shan-folk BGM and Burmese subtitles.",
    "Render a children's audiobook in Karenni about a young hornbill, with Karenni-folk BGM and Burmese subtitles.",
    "I'd like a bedtime audiobook in Kachin about a young red panda, with Kachin-mahkawn BGM and Burmese subtitles.",
    "Cook up a children's audiobook in Chin about a young Mizoram serow, with Chin-folk BGM and Burmese subtitles.",
    "Generate a kids' picture-book audiobook in Naga about a young Hornbill, with Naga-folk BGM and English subtitles.",
    "Produce a narrated children's audiobook in Mizo about a young bamboo-flowering rat, with Mizo-folk BGM and English subtitles.",
    "Build a bedtime audiobook in Khasi about a young pitcher-plant guardian frog, with Khasi-tangmuri BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Garo about a young clouded-leopard, with Garo-dama BGM and English subtitles.",
    "Make me a picture-book audiobook in Bodo about a young Brahmaputra dolphin, with Bodo-folk BGM and Bengali subtitles.",
    "Cook up a narrated children's audiobook in Manipuri about a young Sangai deer, with Manipuri-pung BGM and Bengali subtitles.",
    "Generate a children's bedtime audiobook in Assamese about a young one-horned rhino, with Assamese-bihu BGM and Bengali subtitles.",
    "Produce a kids' picture-book audiobook in Maithili about a young Bagmati-river fish, with Maithili-folk BGM and Hindi subtitles.",
    "Build an illustrated children's audiobook in Bhojpuri about a young Gangetic dolphin, with Bhojpuri-folk BGM and Hindi subtitles.",
    "Tell me a children's audiobook in Gond about a young Gondwana tiger, with Gond-folk BGM and Hindi subtitles.",
    "Make a narrated picture-book audiobook in Santali about a young Hazaribagh elephant, with Santali-folk BGM and Bengali subtitles.",
    # ── more major-language folk-tales + BGM + subtitles (50) ──
    "Render a children's audiobook in Russian about Baba-Yaga's hut on chicken legs, with Russian-balalaika BGM and English subtitles.",
    "I'd like a bedtime audiobook in Russian about a young Firebird gleaming in the forest, with Russian-orchestral BGM and French subtitles.",
    "Cook up a children's audiobook in Russian about Vasilisa-the-Wise weaving cloth, with Russian-folk-strings BGM and German subtitles.",
    "Generate a kids' picture-book audiobook in Russian about Snegurochka's first spring, with Russian-orchestral-2 BGM and English subtitles.",
    "Produce a narrated children's audiobook in Russian about Ivan-Tsarevich and the Grey Wolf, with Russian-orchestral-3 BGM and English subtitles.",
    "Build a bedtime audiobook in Polish about Smok-Wawelski guarding Kraków, with Polish-mazurka BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Polish about a Pan-Twardowski ride on the moon, with Polish-folk BGM and German subtitles.",
    "Make me a picture-book audiobook in Czech about Krakonoš walking the Krkonoše mountains, with Czech-folk BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Czech about a Golem of Prague, with Czech-Hassidic BGM and German subtitles.",
    "Generate a children's bedtime audiobook in Slovak about Jánošík sliding down a Tatra slope, with Slovak-folk BGM and English subtitles.",
    "Produce a kids' picture-book audiobook in Hungarian about Toldi-Miklós lifting a stone, with Hungarian-csárdás BGM and English subtitles.",
    "Build an illustrated children's audiobook in Romanian about a Mioriță lamb on a mountainside, with Romanian-doina BGM and French subtitles.",
    "Tell me a children's audiobook in Bulgarian about a Krali-Marko sword, with Bulgarian-gaida BGM and English subtitles.",
    "Make a narrated picture-book audiobook in Greek about young Theseus and a labyrinth thread, with Greek-bouzouki BGM and English subtitles.",
    "Render a children's audiobook in Albanian about a young Skanderbeg, with Albanian-çifteli BGM and Italian subtitles.",
    "I'd like a bedtime audiobook in Croatian about a young Knez-Branimir, with Croatian-tamburica BGM and Italian subtitles.",
    "Cook up a children's audiobook in Slovene about a Lake-Bled-bell legend, with Slovene-folk BGM and German subtitles.",
    "Generate a kids' picture-book audiobook in Serbian about a young Marko-Kraljević, with Serbian-frula BGM and English subtitles.",
    "Produce a narrated children's audiobook in Macedonian about a young eagle of Skopje, with Macedonian-zurna BGM and English subtitles.",
    "Build a bedtime audiobook in Italian about a young Pinocchio in Tuscany, with Italian-mandolin BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Italian about a young Cinderella in Naples, with Neapolitan-tarantella BGM and Spanish subtitles.",
    "Make me a picture-book audiobook in Italian about a young Pulcinella in Naples, with Italian-folk BGM and French subtitles.",
    "Cook up a narrated children's audiobook in Sicilian about a young swordfish boy, with Sicilian-tarantella BGM and Italian subtitles.",
    "Generate a children's bedtime audiobook in Sardinian about a Janas fairy, with Sardinian-launeddas BGM and Italian subtitles.",
    "Produce a kids' picture-book audiobook in Spanish about a young Don-Quixote on a windmill chase, with Spanish-classical-guitar BGM and English subtitles.",
    "Build an illustrated children's audiobook in Catalan about a young Sant-Jordi taming a dragon, with Catalan-sardana BGM and Spanish subtitles.",
    "Tell me a children's audiobook in Basque about a young Mari of the mountains, with Basque-txistu BGM and Spanish subtitles.",
    "Make a narrated picture-book audiobook in Galician about a young Castro warrior, with Galician-gaita BGM and Spanish subtitles.",
    "Render a children's audiobook in Portuguese about a young Princess-Iguassu, with Portuguese-fado BGM and Spanish subtitles.",
    "I'd like a bedtime audiobook in French about a young Petit Prince on his planet, with French-musette BGM and English subtitles.",
    "Cook up a children's audiobook in French about a young Tintin in Tibet, with French-orchestral BGM and Dutch subtitles.",
    "Generate a kids' picture-book audiobook in French about a young Asterix in Gaul, with Gallic-bagpipe BGM and German subtitles.",
    "Produce a narrated children's audiobook in Breton about a young Ankou wandering moors, with Breton-bombarde BGM and French subtitles.",
    "Build a bedtime audiobook in Welsh about a young Pwyll riding a magical horse, with Welsh-harp BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Irish about a young Cúchulainn taming a hound, with Irish-uilleann-pipe BGM and English subtitles.",
    "Make me a picture-book audiobook in Scottish-Gaelic about a young selkie on Skye, with Scottish-fiddle BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Norwegian about a young troll on a snowy ridge, with Norwegian-Hardanger-fiddle BGM and Swedish subtitles.",
    "Generate a children's bedtime audiobook in Swedish about a young Pippi-Longstocking, with Swedish-folk-fiddle BGM and English subtitles.",
    "Produce a kids' picture-book audiobook in Danish about a young Little-Mermaid, with Danish-spillemand BGM and English subtitles.",
    "Build an illustrated children's audiobook in Finnish about a young Moomintroll in Moominvalley, with Finnish-kantele BGM and English subtitles.",
    "Tell me a children's audiobook in Estonian about a young Kalevipoeg lifting a boulder, with Estonian-folk BGM and Russian subtitles.",
    "Make a narrated picture-book audiobook in Latvian about a young Lāčplēsis taming a bear, with Latvian-folk BGM and Russian subtitles.",
    "Render a children's audiobook in Lithuanian about a young Eglė queen of grass-snakes, with Lithuanian-folk BGM and Russian subtitles.",
    "I'd like a bedtime audiobook in Icelandic about a young Saga-explorer at sea, with Icelandic-rímur BGM and English subtitles.",
    "Cook up a children's audiobook in Faroese about a young puffin chick on a sea-cliff, with Faroese-folk BGM and Danish subtitles.",
    "Generate a kids' picture-book audiobook in German about a young Hänsel and Gretel in a Black-Forest cottage, with German-folk-zither BGM and English subtitles.",
    "Produce a narrated children's audiobook in Yiddish about a young Hershele Ostropoler, with Yiddish-klezmer BGM and English subtitles.",
    "Build a bedtime audiobook in Turkish about a young Nasreddin-Hodja and his donkey, with Turkish-saz BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Persian about a young Rostam in the mountains, with Persian-tar BGM and English subtitles.",
    "Make a narrated picture-book audiobook in Arabic about a young Aladdin's lamp, with Arabic-oud BGM and English subtitles.",
    # ── more African / Middle-Eastern / South-Asian folk-tales + regional BGM + bilingual (50) ──
    "Render a children's audiobook in Swahili about young Anansi crossing the savanna, with Swahili-taarab-2 BGM and English subtitles.",
    "I'd like a bedtime audiobook in Yoruba about young Ijapa-the-tortoise tricking the elephant, with Yoruba-talking-drum BGM and English subtitles.",
    "Cook up a children's audiobook in Zulu about young Inkosazana-Yasezulwini guarding the sky, with Zulu-folk BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Xhosa about young Nyangakazi healer, with Xhosa-uhadi BGM and Afrikaans subtitles.",
    "Produce a narrated children's audiobook in Wolof about young Leuk-le-lièvre and the sea, with Wolof-sabar BGM and French subtitles.",
    "Build a bedtime audiobook in Bambara about young Sundiata-Keita walking, with Bambara-kora BGM and French subtitles.",
    "Tell me an illustrated children's audiobook in Mandinka about young Wangrin trickster, with Mandinka-kora BGM and English subtitles.",
    "Make me a picture-book audiobook in Hausa about young Gizo the spider trickster, with Hausa-goje BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Igbo about young Ekwensu's-trickery, with Igbo-udu-drum BGM and English subtitles.",
    "Generate a children's bedtime audiobook in Akan about young Akye trickster, with Akan-atumpan BGM and English subtitles.",
    "Produce a kids' picture-book audiobook in Twi about young Anansi-the-trickster spinning a tale, with Twi-kete BGM and English subtitles.",
    "Build an illustrated children's audiobook in Ewe about young Yevi-the-spider weaving, with Ewe-agbadza BGM and French subtitles.",
    "Tell me a children's audiobook in Fon about young Aziza-fairy in the forest, with Fon-vodun-drum BGM and French subtitles.",
    "Make a narrated picture-book audiobook in Lingala about young Bunga-the-river-spirit, with Lingala-rumba BGM and French subtitles.",
    "Render a children's audiobook in Kikuyu about young Mugumo-tree-elder, with Kikuyu-folk BGM and English subtitles.",
    "I'd like a bedtime audiobook in Luganda about young Walumbe-the-tiny-trickster, with Luganda-kadongo-kamu BGM and English subtitles.",
    "Cook up a children's audiobook in Kinyarwanda about young Sebgugugu-the-foolish, with Kinyarwanda-inanga BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Amharic about young Aleka-Gebrehana, with Amharic-krar BGM and English subtitles.",
    "Produce a narrated children's audiobook in Tigrinya about young Hamzia-the-clever, with Tigrinya-krar BGM and Amharic subtitles.",
    "Build a bedtime audiobook in Somali about young Wiil-Waal the cunning, with Somali-banaadiri BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Oromo about young Nay-Bahile-the-brave, with Oromo-folk BGM and Amharic subtitles.",
    "Make me a picture-book audiobook in Hebrew about young King-David tending sheep, with Hebrew-cantor BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Yiddish about young Chelm-fool's-quest, with Yiddish-klezmer-2 BGM and English subtitles.",
    "Generate a children's bedtime audiobook in Ladino about young Djoha-the-trickster, with Ladino-romance BGM and Spanish subtitles.",
    "Produce a kids' picture-book audiobook in Aramaic about young Esther-of-Susa, with Aramaic-piyut BGM and Hebrew subtitles.",
    "Build an illustrated children's audiobook in Coptic about young Saint-Mark of Alexandria, with Coptic-chant BGM and Arabic subtitles.",
    "Tell me a children's audiobook in Pashto about young Khushal-Khan the warrior-poet, with Pashto-rabab BGM and Urdu subtitles.",
    "Make a narrated picture-book audiobook in Dari about young Rabia-Balkhi the poet, with Dari-rubab BGM and Persian subtitles.",
    "Render a children's audiobook in Kurdish about young Mem-and-Zin lovers, with Kurdish-tembûr BGM and Arabic subtitles.",
    "I'd like a bedtime audiobook in Azerbaijani about young Koroğlu-the-brave, with Azerbaijani-saz BGM and Turkish subtitles.",
    "Cook up a children's audiobook in Uzbek about young Hodja-Nasreddin and his donkey, with Uzbek-doira BGM and Russian subtitles.",
    "Generate a kids' picture-book audiobook in Kazakh about young Aldar-Köse the trickster, with Kazakh-dombra BGM and Russian subtitles.",
    "Produce a narrated children's audiobook in Kyrgyz about young Manas-the-hero, with Kyrgyz-komuz BGM and Russian subtitles.",
    "Build a bedtime audiobook in Tajik about young Roudaki the poet, with Tajik-falak BGM and Persian subtitles.",
    "Tell me an illustrated children's audiobook in Mongolian about young Geser-Khan, with Mongolian-morin-khuur BGM and Tibetan subtitles.",
    "Make me a picture-book audiobook in Tibetan about young Milarepa singing on the mountain, with Tibetan-monastic-chant BGM and Sanskrit subtitles.",
    "Cook up a narrated children's audiobook in Bengali about young Tagore reading by the lamplight, with Rabindra-sangeet-2 BGM and English subtitles.",
    "Generate a children's bedtime audiobook in Hindi about young Birbal of Akbar's court, with Mughal-darbar BGM and Urdu subtitles.",
    "Produce a kids' picture-book audiobook in Marathi about young Shivaji of the Sahyadri, with Marathi-povada BGM and Hindi subtitles.",
    "Build an illustrated children's audiobook in Gujarati about young Krishna-of-Dwarka, with Gujarati-garba BGM and Sanskrit subtitles.",
    "Tell me a children's audiobook in Punjabi about young Heer-and-Ranjha, with Punjabi-folk BGM and Urdu subtitles.",
    "Make a narrated picture-book audiobook in Tamil about young Thiruvalluvar by the sea, with Tamil-Carnatic BGM and Sanskrit subtitles.",
    "Render a children's audiobook in Telugu about young Krishnadeva-Raya in his court, with Telugu-Carnatic BGM and Sanskrit subtitles.",
    "I'd like a bedtime audiobook in Kannada about young Akka-Mahadevi the saint-poet, with Kannada-Carnatic BGM and Sanskrit subtitles.",
    "Cook up a children's audiobook in Malayalam about young Vamanan-the-dwarf, with Malayalam-sopanam BGM and Sanskrit subtitles.",
    "Generate a kids' picture-book audiobook in Sinhala about young Vijaya landing in Lanka, with Sinhala-baila BGM and Pali subtitles.",
    "Produce a narrated children's audiobook in Burmese about young Min-Thuwun the poet, with Burmese-saung-gauk-2 BGM and Pali subtitles.",
    "Build a bedtime audiobook in Khmer about young Preah-Ko on the Mekong, with Khmer-pinpeat-2 BGM and Sanskrit subtitles.",
    "Tell me an illustrated children's audiobook in Lao about young Khun-Borom uniting the kingdoms, with Lao-classical BGM and Pali subtitles.",
    "Make me a picture-book audiobook in Thai about young Phra-Ruang the boy-king, with Thai-classical BGM and Sanskrit subtitles.",
    # ── more legendary-heroine folk tales + BGM + bilingual subtitles (50) ──
    "Tell me a children's audiobook in French about young Joan-of-Arc hearing voices at Domrémy, with medieval-French-chant BGM and Latin subtitles.",
    "Make a narrated picture-book audiobook in English about young Boudica leading the Iceni, with Celtic-bagpipe-strings BGM and Welsh subtitles.",
    "Render a children's audiobook in Greek about young Antigone burying her brother, with ancient-Greek-aulos BGM and Latin subtitles.",
    "I'd like a bedtime audiobook in Italian about young Beatrice in the Florentine garden, with Italian-Renaissance-lute BGM and Latin subtitles.",
    "Cook up a children's audiobook in Spanish about young La-Malinche translating in Tenochtitlán, with Aztec-flute BGM and Nahuatl subtitles.",
    "Generate a kids' picture-book audiobook in Quechua about young Cura-Ocllo on the Sacred-Valley, with Quechua-quena-2 BGM and Spanish subtitles.",
    "Produce a narrated children's audiobook in Mapudungun about young Janequeo on the Araucanía, with Mapuche-trutruka-3 BGM and Spanish subtitles.",
    "Build a bedtime audiobook in Portuguese about young Anita-Garibaldi at sea, with Brazilian-modinha BGM and Italian subtitles.",
    "Tell me an illustrated children's audiobook in Spanish about young Manuela-Sáenz with Bolívar, with Andean-charango-3 BGM and Quechua subtitles.",
    "Make me a picture-book audiobook in Spanish about young Juana-Azurduy on the Andes, with Bolivian-folk-2 BGM and Aymara subtitles.",
    "Cook up a narrated children's audiobook in Russian about young Princess-Olga at Kiev, with Russian-Slavic-folk BGM and Old-Norse subtitles.",
    "Generate a children's bedtime audiobook in Russian about young Marfa-Posadnitsa of Novgorod, with Russian-folk-strings BGM and Old-East-Slavic subtitles.",
    "Produce a kids' picture-book audiobook in Polish about young Wanda jumping into the Vistula, with Polish-mazurka-2 BGM and Latin subtitles.",
    "Build an illustrated children's audiobook in Czech about young Libuše prophesying Prague, with Czech-folk-2 BGM and Old-Slavic subtitles.",
    "Tell me a children's audiobook in Hungarian about young Saint-Elizabeth-of-Hungary, with Hungarian-folk-2 BGM and Latin subtitles.",
    "Make a narrated picture-book audiobook in Romanian about young Domnita-Anastasia on the Carpathians, with Romanian-folk-2 BGM and Latin subtitles.",
    "Render a children's audiobook in Bulgarian about young Tsaritsa-Theodora at Tarnovo, with Bulgarian-gaida-2 BGM and Old-Bulgarian subtitles.",
    "I'd like a bedtime audiobook in Macedonian about young Tsaritsa-Helena of the Komnenos, with Byzantine-chant-3 BGM and Greek subtitles.",
    "Cook up a children's audiobook in Albanian about young Mother-Teresa-of-Skopje, with Albanian-folk BGM and Italian subtitles.",
    "Generate a kids' picture-book audiobook in Croatian about young Princess-Katarina-Zrinski, with Croatian-tamburica-2 BGM and Latin subtitles.",
    "Produce a narrated children's audiobook in Slovene about young Veronika-of-Desenice, with Slovene-folk BGM and German subtitles.",
    "Build a bedtime audiobook in Serbian about young Princess-Milica at Kosovo, with Serbian-frula-2 BGM and Old-Serbian subtitles.",
    "Tell me an illustrated children's audiobook in Greek about young Empress-Theodora at Constantinople, with Byzantine-chant-4 BGM and Latin subtitles.",
    "Make me a picture-book audiobook in Greek about young Bouboulina at Spetses, with Greek-folk-2 BGM and Italian subtitles.",
    "Cook up a narrated children's audiobook in Turkish about young Hürrem-Sultan at Topkapı, with Ottoman-makam-2 BGM and Persian subtitles.",
    "Generate a children's bedtime audiobook in Arabic about young Zenobia of Palmyra, with Levantine-oud-2 BGM and Aramaic subtitles.",
    "Produce a kids' picture-book audiobook in Persian about young Pourandokht the Sassanid queen, with Sassanid-tar BGM and Aramaic subtitles.",
    "Build an illustrated children's audiobook in Persian about young Razia-Sultan riding a horse, with Persian-radif-3 BGM and Urdu subtitles.",
    "Tell me a children's audiobook in Urdu about young Begum-Hazrat-Mahal, with Indo-Persian-tabla BGM and Hindi subtitles.",
    "Make a narrated picture-book audiobook in Hindi about young Rani-Lakshmibai of Jhansi, with Hindustani-classical-4 BGM and Marathi subtitles.",
    "Render a children's audiobook in Marathi about young Tarabai of the Marathas, with Marathi-povada-2 BGM and Hindi subtitles.",
    "I'd like a bedtime audiobook in Bengali about young Rani-Bhabani, with Rabindra-sangeet-3 BGM and Sanskrit subtitles.",
    "Cook up a children's audiobook in Tamil about young Velu-Nachiyar of Sivagangai, with Tamil-Carnatic-2 BGM and Sanskrit subtitles.",
    "Generate a kids' picture-book audiobook in Telugu about young Rudramadevi of Warangal, with Telugu-Carnatic-2 BGM and Sanskrit subtitles.",
    "Produce a narrated children's audiobook in Kannada about young Kittur-Rani-Chennamma, with Kannada-Carnatic-2 BGM and Marathi subtitles.",
    "Build a bedtime audiobook in Malayalam about young Unniyarcha-of-Vadakkan-Pattukal, with Malayalam-sopanam-2 BGM and Sanskrit subtitles.",
    "Tell me an illustrated children's audiobook in Tibetan about young Princess-Wencheng entering Lhasa, with Tibetan-monastic-chant-2 BGM and Mandarin subtitles.",
    "Make me a picture-book audiobook in Mongolian about young Khutulun wrestling at the Khan's court, with Mongolian-morin-khuur-3 BGM and Mandarin subtitles.",
    "Cook up a narrated children's audiobook in Mandarin about young Mulan riding to war, with Chinese-erhu-3 BGM and Old-Chinese subtitles.",
    "Generate a children's bedtime audiobook in Mandarin about young Hua-Mu-Lan in disguise, with Chinese-classical-4 BGM and Mongolian subtitles.",
    "Produce a kids' picture-book audiobook in Cantonese about young Mui-Tsai serving in Hong-Kong, with Cantonese-opera-3 BGM and English subtitles.",
    "Build an illustrated children's audiobook in Mandarin about young Fu-Hao the Shang-warrior-priestess, with Shang-bronze-bell BGM and Old-Chinese subtitles.",
    "Tell me a children's audiobook in Korean about young Princess-Pyeonggang of Goguryeo, with Goguryeo-folk BGM and Mandarin subtitles.",
    "Make a narrated picture-book audiobook in Korean about young Queen-Seondeok of Silla, with Silla-court-music BGM and Sanskrit subtitles.",
    "Render a children's audiobook in Japanese about young Empress-Suiko at Asuka, with Japanese-gagaku BGM and Old-Korean subtitles.",
    "I'd like a bedtime audiobook in Japanese about young Tomoe-Gozen at Awazu, with Heian-biwa BGM and Old-Japanese subtitles.",
    "Cook up a children's audiobook in Japanese about young Princess-Kazu-no-miya, with Japanese-koto BGM and Old-Japanese subtitles.",
    "Generate a kids' picture-book audiobook in Vietnamese about young Trưng-Trắc at the river, with Vietnamese-đàn-tranh BGM and Old-Chinese subtitles.",
    "Produce a narrated children's audiobook in Vietnamese about young Trưng-Nhị riding into battle, with Vietnamese-trống BGM and Old-Chinese subtitles.",
    "Build a bedtime audiobook in Khmer about young Princess-Yasodharā by the river, with Khmer-pinpeat-3 BGM and Sanskrit subtitles.",
    # ── more classic mythology heroes (Greek / Norse / Hindu / Chinese) + BGM (50) ──
    "Tell me a children's audiobook in Greek about young Heracles wrestling the Nemean lion, with Greek-lyre BGM and English subtitles.",
    "I want an illustrated audiobook in Greek about young Theseus in the Cretan-Labyrinth, with Cretan-lyra BGM and English subtitles.",
    "Make me a bedtime audiobook in Greek about young Perseus and Medusa-Argive-shore, with Greek-aulos-2 BGM and English subtitles.",
    "Create a picture-book audiobook in Greek about young Odysseus on the Ithaca-shore, with Aegean-folk BGM and English subtitles.",
    "Produce an illustrated children's tale in Greek about young Achilles at Phthia-river, with Greek-phorminx BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Greek about young Jason on the Argo, with Greek-syrinx BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about young Bellerophon riding Pegasus, with Greek-kithara BGM and English subtitles.",
    "Build a bedtime audiobook in Greek about young Atalanta racing in Arcadia, with Arcadian-pan-pipes BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about young Orpheus playing the lyre, with Orphic-lyre BGM and English subtitles.",
    "Make me a picture-book audiobook in Greek about young Antigone at Thebes, with Theban-aulos-2 BGM and English subtitles.",
    "Cook up a children's audiobook in Old-Norse about young Sigurd at the dragon-cave, with Norse-tagelharpa BGM and English subtitles.",
    "Produce a narrated children's audiobook in Old-Norse about young Brynhild on the flame-girt mountain, with Old-Norse-langeleik BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Norse about young Beowulf at Heorot-mead-hall, with Anglo-Saxon-lyre BGM and English subtitles.",
    "Build a bedtime audiobook in Old-Norse about young Freyja in Sessrúmnir, with Norse-wooden-flute BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Old-Norse about young Loki at Asgard, with Norse-frame-drum BGM and English subtitles.",
    "Make me a picture-book audiobook in Old-Norse about young Ragnar Lodbrok at Uppsala, with Norse-bone-flute BGM and English subtitles.",
    "Cook up a children's audiobook in Old-Norse about young Lagertha at Hladir, with Norse-jouhikko BGM and English subtitles.",
    "Produce a narrated children's audiobook in Old-Norse about young Egil-Skallagrímsson at Borgarfjörður, with Icelandic-langspil BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Norse about young Grettir-the-Strong on Drangey, with Icelandic-fidla BGM and English subtitles.",
    "Build a bedtime audiobook in Old-Norse about young Gudrun-Ósvífursdóttir at Laugar, with Old-Norse-kantele BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Sanskrit about young Rama-of-Ayodhya, with Indian-rudra-veena BGM and English subtitles.",
    "Make me a picture-book audiobook in Sanskrit about young Krishna in Vrindavan, with Indian-bansuri BGM and English subtitles.",
    "Cook up a children's audiobook in Sanskrit about young Arjuna at Kurukshetra, with Indian-shankha-conch BGM and English subtitles.",
    "Produce a narrated children's audiobook in Sanskrit about young Bhima at Hidimba's-forest, with Indian-mridangam BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Sanskrit about young Hanuman leaping to Lanka, with Indian-conch-shell BGM and English subtitles.",
    "Build a bedtime audiobook in Sanskrit about young Sita in Mithila, with Indian-veena BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Sanskrit about young Draupadi at Panchala, with Indian-sarangi BGM and English subtitles.",
    "Make me a picture-book audiobook in Sanskrit about young Karna at Anga, with Indian-pakhawaj BGM and English subtitles.",
    "Cook up a children's audiobook in Sanskrit about young Ekalavya in the forest-archery hut, with Indian-tribal-flute BGM and English subtitles.",
    "Produce a narrated children's audiobook in Sanskrit about young Abhimanyu in the Chakravyuha, with Indian-nadaswaram BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Tamil about young Kannagi in Madurai, with Tamil-yazh BGM and English subtitles.",
    "Build a bedtime audiobook in Old-Tamil about young Kovalan in Puhar, with Tamil-thavil BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Old-Chinese about young Sun-Wukong on Huaguo-Mountain, with Chinese-erhu BGM and Modern-Chinese subtitles.",
    "Make me a picture-book audiobook in Old-Chinese about young Nezha at Chentangguan, with Chinese-pipa BGM and Modern-Chinese subtitles.",
    "Cook up a children's audiobook in Old-Chinese about young Mulan at the loom, with Chinese-guzheng-2 BGM and Modern-Chinese subtitles.",
    "Produce a narrated children's audiobook in Old-Chinese about young Yang-Jian at Sangu-Mountain, with Chinese-suona BGM and Modern-Chinese subtitles.",
    "Generate a kids' picture-book audiobook in Old-Chinese about young Houyi shooting the suns, with Chinese-dizi BGM and Modern-Chinese subtitles.",
    "Build a bedtime audiobook in Old-Chinese about young Chang'e at the Moon Palace, with Chinese-xiao BGM and Modern-Chinese subtitles.",
    "Tell me an illustrated children's audiobook in Old-Chinese about young Niulang and Zhinü, with Chinese-guqin BGM and Modern-Chinese subtitles.",
    "Make me a picture-book audiobook in Old-Chinese about young Bai-Suzhen at West-Lake, with West-Lake-Jiangnan-folk BGM and Modern-Chinese subtitles.",
    "Cook up a children's audiobook in Old-Chinese about young Madame-White-Snake-Xiaoqing at West-Lake-2, with Jiangnan-sizhu BGM and Modern-Chinese subtitles.",
    "Produce a narrated children's audiobook in Old-Chinese about young Liang-Shanbo and Zhu-Yingtai, with Yueyu-erhu BGM and Modern-Chinese subtitles.",
    "Generate a kids' picture-book audiobook in Old-Chinese about young Hua-Mulan riding north, with Chinese-bawu BGM and Modern-Chinese subtitles.",
    "Build a bedtime audiobook in Hebrew about young David facing Goliath at Elah, with Hebrew-kinnor BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Hebrew about young Samson at Timnah, with Hebrew-shofar BGM and English subtitles.",
    "Make me a picture-book audiobook in Hebrew about young Esther at Susa-palace, with Persian-Jewish-tar BGM and English subtitles.",
    "Cook up a children's audiobook in Hebrew about young Ruth in the Bethlehem-fields, with Hebrew-nevel BGM and English subtitles.",
    "Produce a narrated children's audiobook in Hebrew about young Deborah at the Mt-Tabor-judgment-tree, with Hebrew-tof BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Akkadian about young Gilgamesh at Uruk-Ramparts, with Sumerian-lyre-of-Ur BGM and English subtitles.",
    "Build a bedtime audiobook in Akkadian about young Enkidu in the steppe, with Akkadian-arched-harp BGM and English subtitles.",
    # ── more Aesop / La-Fontaine / Panchatantra animal fables + BGM (50) ──
    "Tell me a children's audiobook in Greek about Aesop's-Tortoise-and-the-Hare, with Greek-lyre-2 BGM and English subtitles.",
    "I want an illustrated audiobook in Greek about Aesop's-Lion-and-the-Mouse, with Greek-aulos-3 BGM and English subtitles.",
    "Make me a bedtime audiobook in Greek about Aesop's-Boy-Who-Cried-Wolf, with Greek-syrinx-2 BGM and English subtitles.",
    "Create a picture-book audiobook in Greek about Aesop's-Fox-and-the-Crow, with Greek-kithara-2 BGM and English subtitles.",
    "Produce an illustrated children's tale in Greek about Aesop's-Ant-and-the-Grasshopper, with Aegean-lyre BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Greek about Aesop's-Dog-and-its-Reflection, with Greek-bouzouki BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Aesop's-North-Wind-and-the-Sun, with Greek-pan-pipes BGM and English subtitles.",
    "Build a bedtime audiobook in Greek about Aesop's-Goose-with-Golden-Eggs, with Greek-Orphic-lyre BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Aesop's-Wolf-in-Sheep's-Clothing, with Greek-flute BGM and English subtitles.",
    "Make me a picture-book audiobook in Greek about Aesop's-Town-Mouse-and-Country-Mouse, with Greek-baglama BGM and English subtitles.",
    "Cook up a children's audiobook in French about La-Fontaine's-La-Cigale-et-la-Fourmi, with French-Baroque-recorder-2 BGM and English subtitles.",
    "Produce a narrated children's audiobook in French about La-Fontaine's-Le-Corbeau-et-le-Renard, with French-Baroque-clavichord BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in French about La-Fontaine's-Le-Loup-et-l'Agneau, with French-Baroque-viola-da-gamba-2 BGM and English subtitles.",
    "Build a bedtime audiobook in French about La-Fontaine's-Le-Lièvre-et-la-Tortue, with French-Baroque-harpsichord-2 BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in French about La-Fontaine's-Le-Chêne-et-le-Roseau, with French-Baroque-theorbo-2 BGM and English subtitles.",
    "Make me a picture-book audiobook in French about La-Fontaine's-Le-Lion-et-le-Rat, with French-Renaissance-lute-2 BGM and English subtitles.",
    "Cook up a children's audiobook in French about La-Fontaine's-La-Grenouille-qui-veut-se-faire-aussi-grosse-que-le-Bœuf, with French-Baroque-musette BGM and English subtitles.",
    "Produce a narrated children's audiobook in French about La-Fontaine's-Le-Renard-et-les-Raisins, with French-Renaissance-vielle BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in French about La-Fontaine's-Le-Chat-et-les-Souris, with French-Baroque-bassoon BGM and English subtitles.",
    "Build a bedtime audiobook in French about La-Fontaine's-La-Laitière-et-le-Pot-au-Lait, with French-pastoral-folk BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Sanskrit about Panchatantra's-Lion-and-the-Hare, with Indian-rudra-veena-2 BGM and English subtitles.",
    "Make me a picture-book audiobook in Sanskrit about Panchatantra's-Crow-and-the-Cobra, with Indian-bansuri-2 BGM and English subtitles.",
    "Cook up a children's audiobook in Sanskrit about Panchatantra's-Monkey-and-the-Crocodile, with Indian-sitar BGM and English subtitles.",
    "Produce a narrated children's audiobook in Sanskrit about Panchatantra's-Brahmin-and-the-Mongoose, with Indian-tabla BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Sanskrit about Panchatantra's-Blue-Jackal, with Indian-sarod BGM and English subtitles.",
    "Build a bedtime audiobook in Sanskrit about Panchatantra's-Tortoise-and-the-Geese, with Indian-tanpura BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Sanskrit about Panchatantra's-Mice-that-Ate-Iron, with Indian-shehnai BGM and English subtitles.",
    "Make me a picture-book audiobook in Sanskrit about Panchatantra's-Doves-and-the-Hunter, with Indian-veena-2 BGM and English subtitles.",
    "Cook up a children's audiobook in Sanskrit about Hitopadesha's-Tiger-and-the-Traveller, with Indian-flute-shehnai BGM and English subtitles.",
    "Produce a narrated children's audiobook in Sanskrit about Hitopadesha's-Foolish-Lion-and-Clever-Rabbit, with Indian-mridangam-2 BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Chinese about Liji's-Crane-and-Tortoise, with Chinese-erhu-2 BGM and Modern-Chinese subtitles.",
    "Build a bedtime audiobook in Old-Chinese about Zhuangzi's-Butterfly-Dream, with Chinese-pipa-2 BGM and Modern-Chinese subtitles.",
    "Tell me an illustrated children's audiobook in Old-Chinese about Mencius's-Wei-Bian-San-Jue-three-bamboo-slip-fable, with Chinese-guqin-2 BGM and Modern-Chinese subtitles.",
    "Make me a picture-book audiobook in Old-Chinese about Han-Fei's-Shou-Zhu-Dai-Tu-fox-stump fable, with Chinese-dizi-2 BGM and Modern-Chinese subtitles.",
    "Cook up a children's audiobook in Old-Chinese about Yu-Gong-Yi-Shan-Yu-Gong-moves-the-mountain, with Chinese-xiao-2 BGM and Modern-Chinese subtitles.",
    "Produce a narrated children's audiobook in Old-Chinese about Sai-Weng-Shi-Ma-Sai-Weng-loses-his-horse fable, with Chinese-suona-2 BGM and Modern-Chinese subtitles.",
    "Generate a kids' picture-book audiobook in Old-Chinese about Hua-She-Tian-Zu-painting-snake-adding-feet, with Chinese-bawu-2 BGM and Modern-Chinese subtitles.",
    "Build a bedtime audiobook in Old-Japanese about Kachi-kachi-Yama-Mt-Crackle-Crackle, with Japanese-shamisen-2 BGM and Modern-Japanese subtitles.",
    "Tell me an illustrated children's audiobook in Old-Japanese about Bunbuku-Chagama-tea-kettle-tanuki, with Japanese-koto-2 BGM and Modern-Japanese subtitles.",
    "Make me a picture-book audiobook in Old-Japanese about Saru-Kani-Kassen-monkey-crab-battle, with Japanese-shakuhachi-2 BGM and Modern-Japanese subtitles.",
    "Cook up a children's audiobook in Old-Japanese about Tanuki-no-Hara-Tsuzumi-tanuki-belly-drum, with Japanese-tsuzumi BGM and Modern-Japanese subtitles.",
    "Produce a narrated children's audiobook in Korean about Heungbu-and-Nolbu-swallow-pumpkin, with Korean-gayageum-2 BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Korean about Tiger-and-Persimmon-fable, with Korean-haegeum-2 BGM and English subtitles.",
    "Build a bedtime audiobook in Korean about Tortoise-and-Rabbit-Korean-fable, with Korean-pansori-2 BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Vietnamese about Tấm-Cám-Cinderella-fish-fable, with Vietnamese-đàn-tranh-2 BGM and English subtitles.",
    "Make me a picture-book audiobook in Vietnamese about Sơn-Tinh-Thủy-Tinh-mountain-water-spirits, with Vietnamese-trống-2 BGM and English subtitles.",
    "Cook up a children's audiobook in Thai about Cock-and-the-Crab-Thai-folk-fable, with Thai-piphat-2 BGM and English subtitles.",
    "Produce a narrated children's audiobook in Thai about Phra-Aphai-Mani-mermaid-tale, with Thai-classical-piphat-2 BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Burmese about Nga-Mani-Galay-fable, with Burmese-saung-4 BGM and English subtitles.",
    "Build a bedtime audiobook in Khmer about Reamker-monkey-king-Khmer-Ramayana, with Khmer-pinpeat-5 BGM and English subtitles.",
    # ── more Arabian Nights / Persian Shahnameh / Sufi-tale retellings + BGM (50) ──
    "Tell me a children's audiobook in Classical-Arabic about Aladdin-and-the-Magic-Lamp, with Arabian-Nights-oud BGM and English subtitles.",
    "I want an illustrated audiobook in Classical-Arabic about Ali-Baba-and-the-Forty-Thieves, with Arabian-Nights-qanun BGM and English subtitles.",
    "Make me a bedtime audiobook in Classical-Arabic about Sinbad-the-Sailor's-First-Voyage, with Arabian-Nights-ney BGM and English subtitles.",
    "Create a picture-book audiobook in Classical-Arabic about Sinbad-the-Sailor's-Second-Voyage-Roc, with Arabian-Nights-darbuka BGM and English subtitles.",
    "Produce an illustrated children's tale in Classical-Arabic about Sinbad-the-Sailor's-Sixth-Voyage-Mountain-of-Light, with Arabian-Nights-tar BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Classical-Arabic about Scheherazade-1001-Nights-frame, with Scheherazade-symphonic-Rimsky BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Classical-Arabic about The-Fisherman-and-the-Jinni, with Arabian-Nights-mawwal BGM and English subtitles.",
    "Build a bedtime audiobook in Classical-Arabic about The-Three-Apples-Mystery, with Arabian-Nights-takht BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Classical-Arabic about The-Hunchback's-Tale-Baghdad, with Baghdad-takht BGM and English subtitles.",
    "Make me a picture-book audiobook in Classical-Arabic about The-Tale-of-Nur-al-Din-and-Anis-al-Jalis, with Arabian-Nights-muwashshah BGM and English subtitles.",
    "Cook up a children's audiobook in Classical-Arabic about The-Ebony-Horse-flying-machine, with Arabian-Nights-qanun-2 BGM and English subtitles.",
    "Produce a narrated children's audiobook in Classical-Arabic about The-City-of-Brass, with Arabian-Nights-symphonic BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Classical-Arabic about The-Tale-of-the-Three-Kings-of-Persia, with Arabian-Nights-zummara BGM and English subtitles.",
    "Build a bedtime audiobook in Classical-Arabic about The-Story-of-Princess-Parizade, with Arabian-Nights-canun-arabe BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Classical-Arabic about Prince-Ahmed-and-the-Fairy-Pari-Banu, with Arabian-Nights-rebab BGM and English subtitles.",
    "Make me a picture-book audiobook in Classical-Arabic about The-Enchanted-Horse-Persian-prince, with Persian-Arabian-Nights-tar BGM and English subtitles.",
    "Cook up a children's audiobook in Persian about Rostam-and-Sohrab-Shahnameh, with Persian-tar-Shahnameh BGM and English subtitles.",
    "Produce a narrated children's audiobook in Persian about Rostam-and-the-Seven-Trials-Haft-Khan, with Persian-setar-Shahnameh BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Persian about Rostam-and-Esfandiyar-Shahnameh, with Persian-tonbak-Shahnameh BGM and English subtitles.",
    "Build a bedtime audiobook in Persian about Zal-and-Rudaba-Shahnameh, with Persian-santur-Shahnameh BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Persian about Bizhan-and-Manijeh-Shahnameh, with Persian-kamancheh-Shahnameh BGM and English subtitles.",
    "Make me a picture-book audiobook in Persian about Siyâvash-and-the-Trial-by-Fire, with Persian-radif-vocal BGM and English subtitles.",
    "Cook up a children's audiobook in Persian about Kay-Khosrow-and-the-Holy-Grail, with Persian-classical-radif BGM and English subtitles.",
    "Produce a narrated children's audiobook in Persian about Jamshid-the-First-King, with Persian-Shahnameh-orchestral BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Persian about Faridun-and-Zahhak-Shahnameh, with Persian-Sassanid-orchestral BGM and English subtitles.",
    "Build a bedtime audiobook in Persian about Kaveh-the-Blacksmith-Shahnameh, with Persian-Kaveh-anvil-percussion BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Persian about Yusuf-and-Zulaykha-Sufi-romance, with Persian-Sufi-ney BGM and English subtitles.",
    "Make me a picture-book audiobook in Persian about Layla-and-Majnun-Sufi-romance, with Persian-Sufi-rubab BGM and English subtitles.",
    "Cook up a children's audiobook in Persian about Rumi-Mathnawi-Reed-Flute, with Persian-Mevlevi-ney BGM and English subtitles.",
    "Produce a narrated children's audiobook in Persian about Rumi-Conference-of-the-Birds-Attar, with Persian-Attar-rebab BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Persian about Hafez-Diwan-tale, with Persian-Hafez-tar BGM and English subtitles.",
    "Build a bedtime audiobook in Persian about Saadi-Gulistan-Rose-Garden, with Persian-Saadi-setar BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Persian about Saadi-Bustan-Orchard-tale, with Persian-Bustan-tar BGM and English subtitles.",
    "Make me a picture-book audiobook in Persian about Khaqani-Shirvan-poem, with Persian-Shirvan-tar BGM and English subtitles.",
    "Cook up a children's audiobook in Persian about Nizami-Khamsa-Five-Treasures, with Persian-Nizami-orchestral BGM and English subtitles.",
    "Produce a narrated children's audiobook in Persian about Khusrau-and-Shirin-Nizami, with Persian-Khusrau-Shirin-tar BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Persian about Nizami-Seven-Beauties-Haft-Paykar, with Persian-Haft-Paykar-orchestral BGM and English subtitles.",
    "Build a bedtime audiobook in Persian about Sheikh-Sanan-Attar-tale, with Persian-Attar-ney BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Persian about Mansur-Hallaj-Sufi-tale, with Persian-Sufi-ana-l-Haqq BGM and English subtitles.",
    "Make me a picture-book audiobook in Persian about Bayazid-Bistami-Sufi-tale, with Persian-Sufi-Bistami BGM and English subtitles.",
    "Cook up a children's audiobook in Old-Turkish about Dede-Korkut-Oghuz-tales, with Turkic-kobyz BGM and English subtitles.",
    "Produce a narrated children's audiobook in Turkish about Nasreddin-Hoca-tales, with Turkish-saz-Hoca BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Turkish about Karagöz-and-Hacivat-shadow-puppets, with Turkish-shadow-zurna BGM and English subtitles.",
    "Build a bedtime audiobook in Uzbek about Alpamysh-Karakalpak-epic, with Karakalpak-dombra BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Uzbek about Hodja-Nasreddin-Bukhara, with Uzbek-shashmaqom-Bukhara BGM and English subtitles.",
    "Make me a picture-book audiobook in Tajik about Mevlana-Jalaluddin-Balkh, with Tajik-falak-Balkh BGM and English subtitles.",
    "Cook up a children's audiobook in Pashto about Khushal-Khan-Khattak-Pashto-poet, with Pashto-rabab-Khushal BGM and English subtitles.",
    "Produce a narrated children's audiobook in Urdu about Iqbal's-Shaheen-tale, with Urdu-Iqbal-classical BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Urdu about Mir-Taqi-Mir-Diwan-tale, with Urdu-Mir-Taqi-classical BGM and English subtitles.",
    "Build a bedtime audiobook in Urdu about Ghalib's-Diwan-tale, with Urdu-Ghalib-classical BGM and English subtitles.",
    # ── more Greek myths + BGM (50) ──
    "Tell me an illustrated children's audiobook in Greek about Perseus-and-Medusa, with Greek-bouzouki-Perseus BGM and English subtitles.",
    "Make me a picture-book audiobook in Greek about Theseus-and-the-Minotaur, with Greek-bouzouki-Theseus BGM and English subtitles.",
    "Cook up a children's audiobook in Greek about Heracles-Twelve-Labours, with Greek-lyra-Heracles BGM and English subtitles.",
    "Produce a narrated children's audiobook in Greek about Jason-and-the-Argonauts, with Greek-lyra-Jason BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Odysseus-and-the-Cyclops, with Greek-lyre-Odysseus BGM and English subtitles.",
    "Build a bedtime audiobook in Greek about Pandora's-Box, with Greek-aulos-Pandora BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Prometheus-bringing-fire-to-man, with Greek-lyre-Prometheus BGM and English subtitles.",
    "Make me a picture-book audiobook in Greek about Icarus-and-Daedalus, with Greek-aulos-Icarus BGM and English subtitles.",
    "Cook up a children's audiobook in Greek about Orpheus-and-Eurydice, with Greek-lyre-Orpheus BGM and English subtitles.",
    "Produce a narrated children's audiobook in Greek about Cupid-and-Psyche, with Greek-aulos-Eros BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Atalanta-and-the-Calydonian-Boar, with Greek-aulos-Atalanta BGM and English subtitles.",
    "Build a bedtime audiobook in Greek about Bellerophon-and-Pegasus, with Greek-lyre-Bellerophon BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Persephone-and-Hades, with Greek-aulos-Persephone BGM and English subtitles.",
    "Make me a picture-book audiobook in Greek about Demeter-and-the-Eleusinian-Mysteries, with Greek-aulos-Demeter BGM and English subtitles.",
    "Cook up a children's audiobook in Greek about Apollo-and-Daphne, with Greek-lyre-Apollo BGM and English subtitles.",
    "Produce a narrated children's audiobook in Greek about Artemis-and-Actaeon, with Greek-aulos-Artemis BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Athena-and-Arachne, with Greek-lyre-Athena BGM and English subtitles.",
    "Build a bedtime audiobook in Greek about Hephaestus-and-the-Golden-Throne, with Greek-aulos-Hephaestus BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Hermes-and-the-cattle-of-Apollo, with Greek-syrinx-Hermes BGM and English subtitles.",
    "Make me a picture-book audiobook in Greek about Dionysus-and-the-pirates, with Greek-aulos-Dionysus BGM and English subtitles.",
    "Cook up a children's audiobook in Greek about Narcissus-and-Echo, with Greek-aulos-Narcissus BGM and English subtitles.",
    "Produce a narrated children's audiobook in Greek about Pyramus-and-Thisbe, with Greek-aulos-Pyramus BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Cadmus-and-the-founding-of-Thebes, with Greek-lyre-Cadmus BGM and English subtitles.",
    "Build a bedtime audiobook in Greek about Oedipus-and-the-Sphinx, with Greek-aulos-Oedipus BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Antigone-and-Creon, with Greek-aulos-Antigone BGM and English subtitles.",
    "Make me a picture-book audiobook in Greek about Electra-and-Orestes, with Greek-aulos-Electra BGM and English subtitles.",
    "Cook up a children's audiobook in Greek about Achilles-and-Patroclus-at-Troy, with Greek-aulos-Achilles BGM and English subtitles.",
    "Produce a narrated children's audiobook in Greek about Helen-of-Troy-and-Paris, with Greek-aulos-Helen BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Hector-and-Andromache, with Greek-aulos-Hector BGM and English subtitles.",
    "Build a bedtime audiobook in Greek about Aeneas-fleeing-Troy, with Greek-aulos-Aeneas BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Sisyphus-and-the-boulder, with Greek-aulos-Sisyphus BGM and English subtitles.",
    "Make me a picture-book audiobook in Greek about Tantalus-and-the-fruit-tree, with Greek-aulos-Tantalus BGM and English subtitles.",
    "Cook up a children's audiobook in Greek about Midas-and-the-golden-touch, with Greek-syrinx-Midas BGM and English subtitles.",
    "Produce a narrated children's audiobook in Greek about Phaethon-and-the-Sun-Chariot, with Greek-aulos-Phaethon BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Arion-and-the-dolphin, with Greek-aulos-Arion BGM and English subtitles.",
    "Build a bedtime audiobook in Greek about Philemon-and-Baucis, with Greek-aulos-Philemon BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Galatea-and-Pygmalion, with Greek-aulos-Galatea BGM and English subtitles.",
    "Make me a picture-book audiobook in Greek about Andromeda-and-the-sea-monster, with Greek-aulos-Andromeda BGM and English subtitles.",
    "Cook up a children's audiobook in Greek about Atlas-holding-up-the-sky, with Greek-aulos-Atlas BGM and English subtitles.",
    "Produce a narrated children's audiobook in Greek about Castor-and-Pollux-Dioscuri, with Greek-aulos-Dioscuri BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Meleager-and-the-Calydonian-hunt, with Greek-aulos-Meleager BGM and English subtitles.",
    "Build a bedtime audiobook in Greek about Hippolytus-and-Phaedra, with Greek-aulos-Hippolytus BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Procne-and-Philomela, with Greek-aulos-Procne BGM and English subtitles.",
    "Make me a picture-book audiobook in Greek about Hyacinthus-and-Apollo, with Greek-aulos-Hyacinthus BGM and English subtitles.",
    "Cook up a children's audiobook in Greek about Adonis-and-Aphrodite, with Greek-aulos-Adonis BGM and English subtitles.",
    "Produce a narrated children's audiobook in Greek about Eros-bringing-life-to-Pandora, with Greek-aulos-Eros-2 BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Selene-and-Endymion, with Greek-aulos-Selene BGM and English subtitles.",
    "Build a bedtime audiobook in Greek about Calypso-and-Odysseus, with Greek-lyre-Calypso BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Circe-and-the-pigs, with Greek-lyre-Circe BGM and English subtitles.",
    "Make me a picture-book audiobook in Greek about Polyphemus-and-Galatea-and-Acis, with Greek-syrinx-Polyphemus BGM and English subtitles.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
