"""x15 story_bilingual SFT.
Chain: Narration → Illustration → Narrator → Translation → Compositor.
Trigger: illustrated audiobook + bilingual subtitles (no music, no ambience).
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Tell me a children's audiobook in Spanish about a young dragon, with English subtitles overlaid.",
    "I want an illustrated audiobook in French about a young witch and her cat, with English subtitles.",
    "Make me a bedtime audiobook in Mandarin about a moon rabbit, with English subtitles.",
    "Create a picture-book audiobook in Korean about a tiger and a persimmon tree, with English subtitles.",
    "Produce an illustrated children's tale in Japanese about a paper crane, with English subtitles.",
    "Generate a kids' audiobook in German about a young owl learning to fly, with English subtitles.",
    "Build a narrated picture-book in Italian about a curious mouse, with English subtitles.",
    "Render a children's audiobook in Portuguese about a young toucan, with English subtitles.",
    "I'd like a bedtime audiobook in Russian about a young bear cub, with English subtitles.",
    "Tell me a children's audiobook in Polish about a young fox, with English subtitles.",
    "Make a soft picture-book audiobook in Swedish about a young reindeer, with English subtitles.",
    "Cook up a children's audiobook in Norwegian about a young troll, with English subtitles.",
    "Generate a narrated picture-book in Finnish about a young white wolf, with English subtitles.",
    "Produce a children's audiobook in Greek about a young sea-turtle, with English subtitles.",
    "Build a bedtime audiobook in Turkish about a young hedgehog, with English subtitles.",
    "Tell me an illustrated children's audiobook in Hebrew about a baby owl, with English subtitles.",
    "Make me a picture-book audiobook in Arabic about a young desert fox, with English subtitles.",
    "Cook up a narrated children's audiobook in Persian about a young nightingale, with English subtitles.",
    "Generate a children's bedtime audiobook in Hindi about a young peacock, with English subtitles.",
    "Produce a kids' picture-book audiobook in Tamil about a young elephant, with English subtitles.",
    "Build an illustrated children's audiobook in Bengali about a young tiger cub, with English subtitles.",
    "Tell me a children's audiobook in Vietnamese about a young water buffalo, with English subtitles.",
    "Make a narrated picture-book audiobook in Thai about a young monkey, with English subtitles.",
    "Render a children's audiobook in Khmer about a young temple cat, with English subtitles.",
    "I'd like a bedtime audiobook in Indonesian about a young komodo dragon, with English subtitles.",
    "Cook up a children's audiobook in Tagalog about a young carabao, with English subtitles.",
    "Generate a kids' picture-book audiobook in Malay about a young pangolin, with English subtitles.",
    "Produce a narrated children's audiobook in Swahili about a young giraffe, with English subtitles.",
    "Build a bedtime audiobook in Yoruba about a young leopard cub, with English subtitles.",
    "Tell me an illustrated children's audiobook in Zulu about a young rhino, with English subtitles.",
    "Make me a picture-book audiobook in Amharic about a young hyena cub, with English subtitles.",
    "Cook up a narrated children's audiobook in Quechua about a young llama, with Spanish subtitles.",
    "Generate a children's bedtime audiobook in Aymara about a young vicuña, with Spanish subtitles.",
    "Produce a kids' picture-book audiobook in Nahuatl about a young hummingbird, with Spanish subtitles.",
    "Build an illustrated children's audiobook in Mapudungun about a young condor, with Spanish subtitles.",
    # ── more illustrated children's audiobooks with bilingual subtitles (50)
    "Tell me a children's audiobook in Dutch about a young hare on the dunes, with English subtitles.",
    "Make me an illustrated audiobook in Danish about a young Copenhagen swan, with English subtitles.",
    "Cook up a bedtime audiobook in Hungarian about a young Puszta horse, with English subtitles.",
    "Generate a kids' picture-book audiobook in Romanian about a young Carpathian wolf cub, with English subtitles.",
    "Produce a children's audiobook in Bulgarian about a young Rhodope lamb, with English subtitles.",
    "Build a narrated picture-book audiobook in Slovak about a young High-Tatra chamois, with English subtitles.",
    "Render a children's audiobook in Slovenian about a young Triglav ibex, with English subtitles.",
    "I'd like a bedtime audiobook in Croatian about a young Adriatic dolphin, with English subtitles.",
    "Tell me a children's audiobook in Serbian about a young Tara wolf, with English subtitles.",
    "Make a picture-book audiobook in Bosnian about a young Bjelašnica horse, with English subtitles.",
    "Cook up a children's audiobook in Albanian about a young Accursed-Mountains eagle, with English subtitles.",
    "Generate a narrated picture-book in Ukrainian about a young steppe wolf, with English subtitles.",
    "Produce a children's audiobook in Belarusian about a young Białowieża bison, with English subtitles.",
    "Build a bedtime audiobook in Lithuanian about a young Curonian seal, with English subtitles.",
    "Tell me an illustrated children's audiobook in Latvian about a young Gauja deer, with English subtitles.",
    "Make me a picture-book audiobook in Estonian about a young Lahemaa moose, with English subtitles.",
    "Cook up a narrated children's audiobook in Catalan about a young Pyrenean brown bear, with Spanish subtitles.",
    "Generate a children's bedtime audiobook in Galician about a young Atlantic puffin, with Spanish subtitles.",
    "Produce a kids' picture-book audiobook in Basque about a young Pyrenean lammergeier, with Spanish subtitles.",
    "Build an illustrated children's audiobook in Welsh about a young Snowdonia mountain pony, with English subtitles.",
    "Tell me a children's audiobook in Irish-Gaelic about a young Connemara pony, with English subtitles.",
    "Make a narrated picture-book audiobook in Scottish-Gaelic about a young Highland-cow calf, with English subtitles.",
    "Render a children's audiobook in Cornish about a young Cornish chough, with English subtitles.",
    "I'd like a bedtime audiobook in Manx about a young Manx-cat kitten, with English subtitles.",
    "Cook up a children's audiobook in Breton about a young Crozon dolphin, with French subtitles.",
    "Generate a kids' picture-book audiobook in Faroese about a young Faroese pony, with Danish subtitles.",
    "Produce a narrated children's audiobook in Icelandic about a young Icelandic horse, with English subtitles.",
    "Build a bedtime audiobook in Lao about a young Mekong elephant, with Thai subtitles.",
    "Tell me an illustrated children's audiobook in Burmese about a young Irrawaddy dolphin, with English subtitles.",
    "Make me a picture-book audiobook in Hmong about a young Sapa village calf, with Vietnamese subtitles.",
    "Cook up a narrated children's audiobook in Javanese about a young Wayang shadow puppet, with Indonesian subtitles.",
    "Generate a children's bedtime audiobook in Sundanese about a young Sundanese cassowary, with Indonesian subtitles.",
    "Produce a kids' picture-book audiobook in Balinese about a young Bali starling, with Indonesian subtitles.",
    "Build an illustrated children's audiobook in Cebuano about a young tarsier, with Tagalog subtitles.",
    "Tell me a children's audiobook in Punjabi about a young Punjabi sparrow, with Hindi subtitles.",
    "Make a narrated picture-book audiobook in Marathi about a young Pune peacock, with Hindi subtitles.",
    "Render a children's audiobook in Gujarati about a young Asiatic lion cub, with Hindi subtitles.",
    "I'd like a bedtime audiobook in Telugu about a young Hyderabad parrot, with English subtitles.",
    "Cook up a children's audiobook in Malayalam about a young Kerala elephant, with English subtitles.",
    "Generate a kids' picture-book audiobook in Sinhalese about a young Sri-Lankan leopard cub, with Tamil subtitles.",
    "Produce a narrated children's audiobook in Nepali about a young Himalayan snow leopard, with English subtitles.",
    "Build a bedtime audiobook in Dzongkha about a young Bhutanese takin, with English subtitles.",
    "Tell me an illustrated children's audiobook in Tibetan about a young Tibetan antelope, with Mandarin subtitles.",
    "Make me a picture-book audiobook in Mongolian about a young Bactrian camel, with Russian subtitles.",
    "Cook up a narrated children's audiobook in Pashto about a young Hindu-Kush ibex, with Dari subtitles.",
    "Generate a children's bedtime audiobook in Urdu about a young Pakistani markhor, with English subtitles.",
    "Produce a kids' picture-book audiobook in Kazakh about a young steppe falcon, with Russian subtitles.",
    "Build an illustrated children's audiobook in Uzbek about a young Aral-Sea fox, with Russian subtitles.",
    "Tell me a children's audiobook in Kyrgyz about a young Tian-Shan eagle, with Russian subtitles.",
    "Make a narrated picture-book audiobook in Tajik about a young Pamir snow leopard, with Russian subtitles.",
    # ── more illustrated children's audiobooks with bilingual subtitles (50)
    "Tell me a children's audiobook in Haitian-Kreyòl about a young Caribbean parrot, with French subtitles.",
    "Make me an illustrated audiobook in Jamaican-Patois about a young tropical mongoose, with English subtitles.",
    "Cook up a bedtime audiobook in Trinidadian-Creole about a young Trinidad iguana, with English subtitles.",
    "Generate a kids' picture-book audiobook in Bahamian-Creole about a young Caribbean flamingo, with English subtitles.",
    "Produce a children's audiobook in Saint-Lucian-Kwéyòl about a young Saint-Lucian parrot, with English subtitles.",
    "Build a narrated picture-book audiobook in Papiamento about a young Curaçao iguana, with Dutch subtitles.",
    "Render a children's audiobook in Sranan-Tongo about a young Surinamese tapir, with Dutch subtitles.",
    "I'd like a bedtime audiobook in Rapa-Nui about a young Easter-Island bird, with Spanish subtitles.",
    "Tell me a children's audiobook in Hokkien about a young Singapore long-tailed macaque, with Mandarin subtitles.",
    "Make a picture-book audiobook in Hakka about a young Taiwan pangolin, with Mandarin subtitles.",
    "Cook up a children's audiobook in Teochew about a young river fish, with Mandarin subtitles.",
    "Generate a narrated picture-book in Cantonese about a young Hong-Kong parrot, with English subtitles.",
    "Produce a children's audiobook in Min-Nan about a young Fujian deer, with Mandarin subtitles.",
    "Build a bedtime audiobook in Shanghainese about a young Yangtze finless-porpoise, with Mandarin subtitles.",
    "Tell me an illustrated children's audiobook in Wu about a young Suzhou egret, with Mandarin subtitles.",
    "Make me a picture-book audiobook in Macanese-Patuá about a young Macau cat, with Portuguese subtitles.",
    "Cook up a narrated children's audiobook in Tagalog about a young Philippine eagle, with English subtitles.",
    "Generate a children's bedtime audiobook in Ilocano about a young Luzon mountain mouse, with Tagalog subtitles.",
    "Produce a kids' picture-book audiobook in Hiligaynon about a young Visayan warty pig, with Tagalog subtitles.",
    "Build an illustrated children's audiobook in Maranao about a young Mindanao civet, with Tagalog subtitles.",
    "Tell me a children's audiobook in Tausug about a young Sulu hornbill, with Tagalog subtitles.",
    "Make a narrated picture-book audiobook in Acehnese about a young Sumatran orangutan, with Indonesian subtitles.",
    "Render a children's audiobook in Toraja about a young water-buffalo, with Indonesian subtitles.",
    "I'd like a bedtime audiobook in Batak about a young Lake-Toba fish, with Indonesian subtitles.",
    "Cook up a children's audiobook in Minangkabau about a young Sumatran rhino, with Indonesian subtitles.",
    "Generate a kids' picture-book audiobook in Sasak about a young Lombok deer, with Indonesian subtitles.",
    "Produce a narrated children's audiobook in Buginese about a young Sulawesi anoa, with Indonesian subtitles.",
    "Build a bedtime audiobook in Dayak about a young Borneo elephant, with Indonesian subtitles.",
    "Tell me an illustrated children's audiobook in Iban about a young Borneo hornbill, with Malay subtitles.",
    "Make me a picture-book audiobook in Bidayuh about a young Borneo Sun-bear, with Malay subtitles.",
    "Cook up a narrated children's audiobook in Igorot about a young Cordillera cloud-rat, with Tagalog subtitles.",
    "Generate a children's bedtime audiobook in Hmong about a young Sapa water-buffalo, with Lao subtitles.",
    "Produce a kids' picture-book audiobook in Lao about a young Mekong Irrawaddy-dolphin, with Thai subtitles.",
    "Build an illustrated children's audiobook in Karen about a young elephant, with Thai subtitles.",
    "Tell me a children's audiobook in Mon about a young Gulf-of-Martaban fishing-cat, with Burmese subtitles.",
    "Make a narrated picture-book audiobook in Shan about a young Tai-Yai forest-pig, with Burmese subtitles.",
    "Render a children's audiobook in Karenni about a young hornbill, with Burmese subtitles.",
    "I'd like a bedtime audiobook in Kachin about a young red panda, with Burmese subtitles.",
    "Cook up a children's audiobook in Chin about a young Mizoram serow, with Burmese subtitles.",
    "Generate a kids' picture-book audiobook in Naga about a young Hornbill, with English subtitles.",
    "Produce a narrated children's audiobook in Mizo about a young bamboo-flowering rat, with English subtitles.",
    "Build a bedtime audiobook in Khasi about a young pitcher-plant guardian frog, with English subtitles.",
    "Tell me an illustrated children's audiobook in Garo about a young clouded-leopard, with English subtitles.",
    "Make me a picture-book audiobook in Bodo about a young Brahmaputra dolphin, with Bengali subtitles.",
    "Cook up a narrated children's audiobook in Manipuri about a young Sangai deer, with Bengali subtitles.",
    "Generate a children's bedtime audiobook in Assamese about a young one-horned rhino, with Bengali subtitles.",
    "Produce a kids' picture-book audiobook in Maithili about a young Bagmati-river fish, with Hindi subtitles.",
    "Build an illustrated children's audiobook in Bhojpuri about a young Gangetic dolphin, with Hindi subtitles.",
    "Tell me a children's audiobook in Gond about a young Gondwana tiger, with Hindi subtitles.",
    "Make a narrated picture-book audiobook in Santali about a young Hazaribagh elephant, with Bengali subtitles.",
    # ── more major-language folk-tale audiobooks (50) ──
    "Render a children's audiobook in Russian about Baba-Yaga's hut on chicken legs, with English subtitles.",
    "I'd like a bedtime audiobook in Russian about a young Firebird gleaming in the forest, with French subtitles.",
    "Cook up a children's audiobook in Russian about Vasilisa-the-Wise weaving cloth, with German subtitles.",
    "Generate a kids' picture-book audiobook in Russian about Snegurochka's first spring, with English subtitles.",
    "Produce a narrated children's audiobook in Russian about Ivan-Tsarevich and the Grey Wolf, with English subtitles.",
    "Build a bedtime audiobook in Polish about Smok-Wawelski guarding Kraków, with English subtitles.",
    "Tell me an illustrated children's audiobook in Polish about a Pan-Twardowski ride on the moon, with German subtitles.",
    "Make me a picture-book audiobook in Czech about Krakonoš walking the Krkonoše mountains, with English subtitles.",
    "Cook up a narrated children's audiobook in Czech about a Golem of Prague, with German subtitles.",
    "Generate a children's bedtime audiobook in Slovak about Jánošík sliding down a Tatra slope, with English subtitles.",
    "Produce a kids' picture-book audiobook in Hungarian about Toldi-Miklós lifting a stone, with English subtitles.",
    "Build an illustrated children's audiobook in Romanian about a Mioriță lamb on a mountainside, with French subtitles.",
    "Tell me a children's audiobook in Bulgarian about a Krali-Marko sword, with English subtitles.",
    "Make a narrated picture-book audiobook in Greek about young Theseus and a labyrinth thread, with English subtitles.",
    "Render a children's audiobook in Albanian about a young Skanderbeg, with Italian subtitles.",
    "I'd like a bedtime audiobook in Croatian about a young Knez-Branimir, with Italian subtitles.",
    "Cook up a children's audiobook in Slovene about a Lake-Bled-bell legend, with German subtitles.",
    "Generate a kids' picture-book audiobook in Serbian about a young Marko-Kraljević, with English subtitles.",
    "Produce a narrated children's audiobook in Macedonian about a young eagle of Skopje, with English subtitles.",
    "Build a bedtime audiobook in Italian about a young Pinocchio in Tuscany, with English subtitles.",
    "Tell me an illustrated children's audiobook in Italian about a young Cinderella in Naples, with Spanish subtitles.",
    "Make me a picture-book audiobook in Italian about a young Pulcinella in Naples, with French subtitles.",
    "Cook up a narrated children's audiobook in Sicilian about a young swordfish boy, with Italian subtitles.",
    "Generate a children's bedtime audiobook in Sardinian about a Janas fairy, with Italian subtitles.",
    "Produce a kids' picture-book audiobook in Spanish about a young Don-Quixote on a windmill chase, with English subtitles.",
    "Build an illustrated children's audiobook in Catalan about a young Sant-Jordi taming a dragon, with Spanish subtitles.",
    "Tell me a children's audiobook in Basque about a young Mari of the mountains, with Spanish subtitles.",
    "Make a narrated picture-book audiobook in Galician about a young Castro warrior, with Spanish subtitles.",
    "Render a children's audiobook in Portuguese about a young Princess-Iguassu, with Spanish subtitles.",
    "I'd like a bedtime audiobook in French about a young Petit Prince on his planet, with English subtitles.",
    "Cook up a children's audiobook in French about a young Tintin in Tibet, with Dutch subtitles.",
    "Generate a kids' picture-book audiobook in French about a young Asterix in Gaul, with German subtitles.",
    "Produce a narrated children's audiobook in Breton about a young Ankou wandering moors, with French subtitles.",
    "Build a bedtime audiobook in Welsh about a young Pwyll riding a magical horse, with English subtitles.",
    "Tell me an illustrated children's audiobook in Irish about a young Cúchulainn taming a hound, with English subtitles.",
    "Make me a picture-book audiobook in Scottish-Gaelic about a young selkie on Skye, with English subtitles.",
    "Cook up a narrated children's audiobook in Norwegian about a young troll on a snowy ridge, with Swedish subtitles.",
    "Generate a children's bedtime audiobook in Swedish about a young Pippi-Longstocking, with English subtitles.",
    "Produce a kids' picture-book audiobook in Danish about a young Little-Mermaid, with English subtitles.",
    "Build an illustrated children's audiobook in Finnish about a young Moomintroll in Moominvalley, with English subtitles.",
    "Tell me a children's audiobook in Estonian about a young Kalevipoeg lifting a boulder, with Russian subtitles.",
    "Make a narrated picture-book audiobook in Latvian about a young Lāčplēsis taming a bear, with Russian subtitles.",
    "Render a children's audiobook in Lithuanian about a young Eglė queen of grass-snakes, with Russian subtitles.",
    "I'd like a bedtime audiobook in Icelandic about a young Saga-explorer at sea, with English subtitles.",
    "Cook up a children's audiobook in Faroese about a young puffin chick on a sea-cliff, with Danish subtitles.",
    "Generate a kids' picture-book audiobook in German about a young Hänsel and Gretel in a Black-Forest cottage, with English subtitles.",
    "Produce a narrated children's audiobook in Yiddish about a young Hershele Ostropoler, with English subtitles.",
    "Build a bedtime audiobook in Turkish about a young Nasreddin-Hodja and his donkey, with English subtitles.",
    "Tell me an illustrated children's audiobook in Persian about a young Rostam in the mountains, with English subtitles.",
    "Make a narrated picture-book audiobook in Arabic about a young Aladdin's lamp, with English subtitles.",
    # ── more African / Middle-Eastern / South-Asian folk tales (50) ──
    "Render a children's audiobook in Swahili about young Anansi crossing the savanna, with English subtitles.",
    "I'd like a bedtime audiobook in Yoruba about young Ijapa-the-tortoise tricking the elephant, with English subtitles.",
    "Cook up a children's audiobook in Zulu about young Inkosazana-Yasezulwini guarding the sky, with English subtitles.",
    "Generate a kids' picture-book audiobook in Xhosa about young Nyangakazi healer, with Afrikaans subtitles.",
    "Produce a narrated children's audiobook in Wolof about young Leuk-le-lièvre and the sea, with French subtitles.",
    "Build a bedtime audiobook in Bambara about young Sundiata-Keita walking, with French subtitles.",
    "Tell me an illustrated children's audiobook in Mandinka about young Wangrin trickster, with English subtitles.",
    "Make me a picture-book audiobook in Hausa about young Gizo the spider trickster, with English subtitles.",
    "Cook up a narrated children's audiobook in Igbo about young Ekwensu's-trickery, with English subtitles.",
    "Generate a children's bedtime audiobook in Akan about young Akye trickster, with English subtitles.",
    "Produce a kids' picture-book audiobook in Twi about young Anansi-the-trickster spinning a tale, with English subtitles.",
    "Build an illustrated children's audiobook in Ewe about young Yevi-the-spider weaving, with French subtitles.",
    "Tell me a children's audiobook in Fon about young Aziza-fairy in the forest, with French subtitles.",
    "Make a narrated picture-book audiobook in Lingala about young Bunga-the-river-spirit, with French subtitles.",
    "Render a children's audiobook in Kikuyu about young Mugumo-tree-elder, with English subtitles.",
    "I'd like a bedtime audiobook in Luganda about young Walumbe-the-tiny-trickster, with English subtitles.",
    "Cook up a children's audiobook in Kinyarwanda about young Sebgugugu-the-foolish, with English subtitles.",
    "Generate a kids' picture-book audiobook in Amharic about young Aleka-Gebrehana, with English subtitles.",
    "Produce a narrated children's audiobook in Tigrinya about young Hamzia-the-clever, with Amharic subtitles.",
    "Build a bedtime audiobook in Somali about young Wiil-Waal the cunning, with English subtitles.",
    "Tell me an illustrated children's audiobook in Oromo about young Nay-Bahile-the-brave, with Amharic subtitles.",
    "Make me a picture-book audiobook in Hebrew about young King-David tending sheep, with English subtitles.",
    "Cook up a narrated children's audiobook in Yiddish about young Chelm-fool's-quest, with English subtitles.",
    "Generate a children's bedtime audiobook in Ladino about young Djoha-the-trickster, with Spanish subtitles.",
    "Produce a kids' picture-book audiobook in Aramaic about young Esther-of-Susa, with Hebrew subtitles.",
    "Build an illustrated children's audiobook in Coptic about young Saint-Mark of Alexandria, with Arabic subtitles.",
    "Tell me a children's audiobook in Pashto about young Khushal-Khan the warrior-poet, with Urdu subtitles.",
    "Make a narrated picture-book audiobook in Dari about young Rabia-Balkhi the poet, with Persian subtitles.",
    "Render a children's audiobook in Kurdish about young Mem-and-Zin lovers, with Arabic subtitles.",
    "I'd like a bedtime audiobook in Azerbaijani about young Koroğlu-the-brave, with Turkish subtitles.",
    "Cook up a children's audiobook in Uzbek about young Hodja-Nasreddin and his donkey, with Russian subtitles.",
    "Generate a kids' picture-book audiobook in Kazakh about young Aldar-Köse the trickster, with Russian subtitles.",
    "Produce a narrated children's audiobook in Kyrgyz about young Manas-the-hero, with Russian subtitles.",
    "Build a bedtime audiobook in Tajik about young Roudaki the poet, with Persian subtitles.",
    "Tell me an illustrated children's audiobook in Mongolian about young Geser-Khan, with Tibetan subtitles.",
    "Make me a picture-book audiobook in Tibetan about young Milarepa singing on the mountain, with Sanskrit subtitles.",
    "Cook up a narrated children's audiobook in Bengali about young Tagore reading by the lamplight, with English subtitles.",
    "Generate a children's bedtime audiobook in Hindi about young Birbal of Akbar's court, with Urdu subtitles.",
    "Produce a kids' picture-book audiobook in Marathi about young Shivaji of the Sahyadri, with Hindi subtitles.",
    "Build an illustrated children's audiobook in Gujarati about young Krishna-of-Dwarka, with Sanskrit subtitles.",
    "Tell me a children's audiobook in Punjabi about young Heer-and-Ranjha, with Urdu subtitles.",
    "Make a narrated picture-book audiobook in Tamil about young Thiruvalluvar by the sea, with Sanskrit subtitles.",
    "Render a children's audiobook in Telugu about young Krishnadeva-Raya in his court, with Sanskrit subtitles.",
    "I'd like a bedtime audiobook in Kannada about young Akka-Mahadevi the saint-poet, with Sanskrit subtitles.",
    "Cook up a children's audiobook in Malayalam about young Vamanan-the-dwarf, with Sanskrit subtitles.",
    "Generate a kids' picture-book audiobook in Sinhala about young Vijaya landing in Lanka, with Pali subtitles.",
    "Produce a narrated children's audiobook in Burmese about young Min-Thuwun the poet, with Pali subtitles.",
    "Build a bedtime audiobook in Khmer about young Preah-Ko on the Mekong, with Sanskrit subtitles.",
    "Tell me an illustrated children's audiobook in Lao about young Khun-Borom uniting the kingdoms, with Pali subtitles.",
    "Make me a picture-book audiobook in Thai about young Phra-Ruang the boy-king, with Sanskrit subtitles.",
    # ── more legendary-heroine folk tales (50) ──
    "Tell me a children's audiobook in French about young Joan-of-Arc hearing voices at Domrémy, with Latin subtitles.",
    "Make a narrated picture-book audiobook in English about young Boudica leading the Iceni, with Welsh subtitles.",
    "Render a children's audiobook in Greek about young Antigone burying her brother, with Latin subtitles.",
    "I'd like a bedtime audiobook in Italian about young Beatrice in the Florentine garden, with Latin subtitles.",
    "Cook up a children's audiobook in Spanish about young La-Malinche translating in Tenochtitlán, with Nahuatl subtitles.",
    "Generate a kids' picture-book audiobook in Quechua about young Cura-Ocllo on the Sacred-Valley, with Spanish subtitles.",
    "Produce a narrated children's audiobook in Mapudungun about young Janequeo on the Araucanía, with Spanish subtitles.",
    "Build a bedtime audiobook in Portuguese about young Anita-Garibaldi at sea, with Italian subtitles.",
    "Tell me an illustrated children's audiobook in Spanish about young Manuela-Sáenz with Bolívar, with Quechua subtitles.",
    "Make me a picture-book audiobook in Spanish about young Juana-Azurduy on the Andes, with Aymara subtitles.",
    "Cook up a narrated children's audiobook in Russian about young Princess-Olga at Kiev, with Old-Norse subtitles.",
    "Generate a children's bedtime audiobook in Russian about young Marfa-Posadnitsa of Novgorod, with Old-East-Slavic subtitles.",
    "Produce a kids' picture-book audiobook in Polish about young Wanda jumping into the Vistula, with Latin subtitles.",
    "Build an illustrated children's audiobook in Czech about young Libuše prophesying Prague, with Old-Slavic subtitles.",
    "Tell me a children's audiobook in Hungarian about young Saint-Elizabeth-of-Hungary, with Latin subtitles.",
    "Make a narrated picture-book audiobook in Romanian about young Domnita-Anastasia on the Carpathians, with Latin subtitles.",
    "Render a children's audiobook in Bulgarian about young Tsaritsa-Theodora at Tarnovo, with Old-Bulgarian subtitles.",
    "I'd like a bedtime audiobook in Macedonian about young Tsaritsa-Helena of the Komnenos, with Greek subtitles.",
    "Cook up a children's audiobook in Albanian about young Mother-Teresa-of-Skopje, with Italian subtitles.",
    "Generate a kids' picture-book audiobook in Croatian about young Princess-Katarina-Zrinski, with Latin subtitles.",
    "Produce a narrated children's audiobook in Slovene about young Veronika-of-Desenice, with German subtitles.",
    "Build a bedtime audiobook in Serbian about young Princess-Milica at Kosovo, with Old-Serbian subtitles.",
    "Tell me an illustrated children's audiobook in Greek about young Empress-Theodora at Constantinople, with Latin subtitles.",
    "Make me a picture-book audiobook in Greek about young Bouboulina at Spetses, with Italian subtitles.",
    "Cook up a narrated children's audiobook in Turkish about young Hürrem-Sultan at Topkapı, with Persian subtitles.",
    "Generate a children's bedtime audiobook in Arabic about young Zenobia of Palmyra, with Aramaic subtitles.",
    "Produce a kids' picture-book audiobook in Persian about young Pourandokht the Sassanid queen, with Aramaic subtitles.",
    "Build an illustrated children's audiobook in Persian about young Razia-Sultan riding a horse, with Urdu subtitles.",
    "Tell me a children's audiobook in Urdu about young Begum-Hazrat-Mahal, with Hindi subtitles.",
    "Make a narrated picture-book audiobook in Hindi about young Rani-Lakshmibai of Jhansi, with Marathi subtitles.",
    "Render a children's audiobook in Marathi about young Tarabai of the Marathas, with Hindi subtitles.",
    "I'd like a bedtime audiobook in Bengali about young Rani-Bhabani, with Sanskrit subtitles.",
    "Cook up a children's audiobook in Tamil about young Velu-Nachiyar of Sivagangai, with Sanskrit subtitles.",
    "Generate a kids' picture-book audiobook in Telugu about young Rudramadevi of Warangal, with Sanskrit subtitles.",
    "Produce a narrated children's audiobook in Kannada about young Kittur-Rani-Chennamma, with Marathi subtitles.",
    "Build a bedtime audiobook in Malayalam about young Unniyarcha-of-Vadakkan-Pattukal, with Sanskrit subtitles.",
    "Tell me an illustrated children's audiobook in Tibetan about young Princess-Wencheng entering Lhasa, with Mandarin subtitles.",
    "Make me a picture-book audiobook in Mongolian about young Khutulun wrestling at the Khan's court, with Mandarin subtitles.",
    "Cook up a narrated children's audiobook in Mandarin about young Mulan riding to war, with Old-Chinese subtitles.",
    "Generate a children's bedtime audiobook in Mandarin about young Hua-Mu-Lan in disguise, with Mongolian subtitles.",
    "Produce a kids' picture-book audiobook in Cantonese about young Mui-Tsai serving in Hong-Kong, with English subtitles.",
    "Build an illustrated children's audiobook in Mandarin about young Fu-Hao the Shang-warrior-priestess, with Old-Chinese subtitles.",
    "Tell me a children's audiobook in Korean about young Princess-Pyeonggang of Goguryeo, with Mandarin subtitles.",
    "Make a narrated picture-book audiobook in Korean about young Queen-Seondeok of Silla, with Sanskrit subtitles.",
    "Render a children's audiobook in Japanese about young Empress-Suiko at Asuka, with Old-Korean subtitles.",
    "I'd like a bedtime audiobook in Japanese about young Tomoe-Gozen at Awazu, with Old-Japanese subtitles.",
    "Cook up a children's audiobook in Japanese about young Princess-Kazu-no-miya, with Old-Japanese subtitles.",
    "Generate a kids' picture-book audiobook in Vietnamese about young Trưng-Trắc at the river, with Old-Chinese subtitles.",
    "Produce a narrated children's audiobook in Vietnamese about young Trưng-Nhị riding into battle, with Old-Chinese subtitles.",
    "Build a bedtime audiobook in Khmer about young Princess-Yasodharā by the river, with Sanskrit subtitles.",
    # ── more classic mythology heroes (Greek / Norse / Hindu / Chinese) (50) ──
    "Tell me a children's audiobook in Greek about young Heracles wrestling the Nemean lion, with English subtitles overlaid.",
    "I want an illustrated audiobook in Greek about young Theseus in the Cretan-Labyrinth, with English subtitles.",
    "Make me a bedtime audiobook in Greek about young Perseus and Medusa-Argive-shore, with English subtitles.",
    "Create a picture-book audiobook in Greek about young Odysseus on the Ithaca-shore, with English subtitles.",
    "Produce an illustrated children's tale in Greek about young Achilles at Phthia-river, with English subtitles.",
    "Cook up a narrated children's audiobook in Greek about young Jason on the Argo, with English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about young Bellerophon riding Pegasus, with English subtitles.",
    "Build a bedtime audiobook in Greek about young Atalanta racing in Arcadia, with English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about young Orpheus playing the lyre, with English subtitles.",
    "Make me a picture-book audiobook in Greek about young Antigone at Thebes, with English subtitles.",
    "Cook up a children's audiobook in Old-Norse about young Sigurd at the dragon-cave, with English subtitles.",
    "Produce a narrated children's audiobook in Old-Norse about young Brynhild on the flame-girt mountain, with English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Norse about young Beowulf at Heorot-mead-hall, with English subtitles.",
    "Build a bedtime audiobook in Old-Norse about young Freyja in Sessrúmnir, with English subtitles.",
    "Tell me an illustrated children's audiobook in Old-Norse about young Loki at Asgard, with English subtitles.",
    "Make me a picture-book audiobook in Old-Norse about young Ragnar Lodbrok at Uppsala, with English subtitles.",
    "Cook up a children's audiobook in Old-Norse about young Lagertha at Hladir, with English subtitles.",
    "Produce a narrated children's audiobook in Old-Norse about young Egil-Skallagrímsson at Borgarfjörður, with English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Norse about young Grettir-the-Strong on Drangey, with English subtitles.",
    "Build a bedtime audiobook in Old-Norse about young Gudrun-Ósvífursdóttir at Laugar, with English subtitles.",
    "Tell me an illustrated children's audiobook in Sanskrit about young Rama-of-Ayodhya, with English subtitles.",
    "Make me a picture-book audiobook in Sanskrit about young Krishna in Vrindavan, with English subtitles.",
    "Cook up a children's audiobook in Sanskrit about young Arjuna at Kurukshetra, with English subtitles.",
    "Produce a narrated children's audiobook in Sanskrit about young Bhima at Hidimba's-forest, with English subtitles.",
    "Generate a kids' picture-book audiobook in Sanskrit about young Hanuman leaping to Lanka, with English subtitles.",
    "Build a bedtime audiobook in Sanskrit about young Sita in Mithila, with English subtitles.",
    "Tell me an illustrated children's audiobook in Sanskrit about young Draupadi at Panchala, with English subtitles.",
    "Make me a picture-book audiobook in Sanskrit about young Karna at Anga, with English subtitles.",
    "Cook up a children's audiobook in Sanskrit about young Ekalavya in the forest-archery hut, with English subtitles.",
    "Produce a narrated children's audiobook in Sanskrit about young Abhimanyu in the Chakravyuha, with English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Tamil about young Kannagi in Madurai, with English subtitles.",
    "Build a bedtime audiobook in Old-Tamil about young Kovalan in Puhar, with English subtitles.",
    "Tell me an illustrated children's audiobook in Old-Chinese about young Sun-Wukong on Huaguo-Mountain, with Modern-Chinese subtitles.",
    "Make me a picture-book audiobook in Old-Chinese about young Nezha at Chentangguan, with Modern-Chinese subtitles.",
    "Cook up a children's audiobook in Old-Chinese about young Mulan at the loom, with Modern-Chinese subtitles.",
    "Produce a narrated children's audiobook in Old-Chinese about young Yang-Jian at Sangu-Mountain, with Modern-Chinese subtitles.",
    "Generate a kids' picture-book audiobook in Old-Chinese about young Houyi shooting the suns, with Modern-Chinese subtitles.",
    "Build a bedtime audiobook in Old-Chinese about young Chang'e at the Moon Palace, with Modern-Chinese subtitles.",
    "Tell me an illustrated children's audiobook in Old-Chinese about young Niulang and Zhinü, with Modern-Chinese subtitles.",
    "Make me a picture-book audiobook in Old-Chinese about young Bai-Suzhen at West-Lake, with Modern-Chinese subtitles.",
    "Cook up a children's audiobook in Old-Chinese about young Madame-White-Snake-Xiaoqing at West-Lake-2, with Modern-Chinese subtitles.",
    "Produce a narrated children's audiobook in Old-Chinese about young Liang-Shanbo and Zhu-Yingtai, with Modern-Chinese subtitles.",
    "Generate a kids' picture-book audiobook in Old-Chinese about young Hua-Mulan riding north, with Modern-Chinese subtitles.",
    "Build a bedtime audiobook in Hebrew about young David facing Goliath at Elah, with English subtitles.",
    "Tell me an illustrated children's audiobook in Hebrew about young Samson at Timnah, with English subtitles.",
    "Make me a picture-book audiobook in Hebrew about young Esther at Susa-palace, with English subtitles.",
    "Cook up a children's audiobook in Hebrew about young Ruth in the Bethlehem-fields, with English subtitles.",
    "Produce a narrated children's audiobook in Hebrew about young Deborah at the Mt-Tabor-judgment-tree, with English subtitles.",
    "Generate a kids' picture-book audiobook in Akkadian about young Gilgamesh at Uruk-Ramparts, with English subtitles.",
    "Build a bedtime audiobook in Akkadian about young Enkidu in the steppe, with English subtitles.",
    # ── more Aesop / La-Fontaine / Panchatantra animal fables (50) ──
    "Tell me a children's audiobook in Greek about Aesop's-Tortoise-and-the-Hare, with English subtitles overlaid.",
    "I want an illustrated audiobook in Greek about Aesop's-Lion-and-the-Mouse, with English subtitles.",
    "Make me a bedtime audiobook in Greek about Aesop's-Boy-Who-Cried-Wolf, with English subtitles.",
    "Create a picture-book audiobook in Greek about Aesop's-Fox-and-the-Crow, with English subtitles.",
    "Produce an illustrated children's tale in Greek about Aesop's-Ant-and-the-Grasshopper, with English subtitles.",
    "Cook up a narrated children's audiobook in Greek about Aesop's-Dog-and-its-Reflection, with English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Aesop's-North-Wind-and-the-Sun, with English subtitles.",
    "Build a bedtime audiobook in Greek about Aesop's-Goose-with-Golden-Eggs, with English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Aesop's-Wolf-in-Sheep's-Clothing, with English subtitles.",
    "Make me a picture-book audiobook in Greek about Aesop's-Town-Mouse-and-Country-Mouse, with English subtitles.",
    "Cook up a children's audiobook in French about La-Fontaine's-La-Cigale-et-la-Fourmi, with English subtitles.",
    "Produce a narrated children's audiobook in French about La-Fontaine's-Le-Corbeau-et-le-Renard, with English subtitles.",
    "Generate a kids' picture-book audiobook in French about La-Fontaine's-Le-Loup-et-l'Agneau, with English subtitles.",
    "Build a bedtime audiobook in French about La-Fontaine's-Le-Lièvre-et-la-Tortue, with English subtitles.",
    "Tell me an illustrated children's audiobook in French about La-Fontaine's-Le-Chêne-et-le-Roseau, with English subtitles.",
    "Make me a picture-book audiobook in French about La-Fontaine's-Le-Lion-et-le-Rat, with English subtitles.",
    "Cook up a children's audiobook in French about La-Fontaine's-La-Grenouille-qui-veut-se-faire-aussi-grosse-que-le-Bœuf, with English subtitles.",
    "Produce a narrated children's audiobook in French about La-Fontaine's-Le-Renard-et-les-Raisins, with English subtitles.",
    "Generate a kids' picture-book audiobook in French about La-Fontaine's-Le-Chat-et-les-Souris, with English subtitles.",
    "Build a bedtime audiobook in French about La-Fontaine's-La-Laitière-et-le-Pot-au-Lait, with English subtitles.",
    "Tell me an illustrated children's audiobook in Sanskrit about Panchatantra's-Lion-and-the-Hare, with English subtitles.",
    "Make me a picture-book audiobook in Sanskrit about Panchatantra's-Crow-and-the-Cobra, with English subtitles.",
    "Cook up a children's audiobook in Sanskrit about Panchatantra's-Monkey-and-the-Crocodile, with English subtitles.",
    "Produce a narrated children's audiobook in Sanskrit about Panchatantra's-Brahmin-and-the-Mongoose, with English subtitles.",
    "Generate a kids' picture-book audiobook in Sanskrit about Panchatantra's-Blue-Jackal, with English subtitles.",
    "Build a bedtime audiobook in Sanskrit about Panchatantra's-Tortoise-and-the-Geese, with English subtitles.",
    "Tell me an illustrated children's audiobook in Sanskrit about Panchatantra's-Mice-that-Ate-Iron, with English subtitles.",
    "Make me a picture-book audiobook in Sanskrit about Panchatantra's-Doves-and-the-Hunter, with English subtitles.",
    "Cook up a children's audiobook in Sanskrit about Hitopadesha's-Tiger-and-the-Traveller, with English subtitles.",
    "Produce a narrated children's audiobook in Sanskrit about Hitopadesha's-Foolish-Lion-and-Clever-Rabbit, with English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Chinese about Liji's-Crane-and-Tortoise, with Modern-Chinese subtitles.",
    "Build a bedtime audiobook in Old-Chinese about Zhuangzi's-Butterfly-Dream, with Modern-Chinese subtitles.",
    "Tell me an illustrated children's audiobook in Old-Chinese about Mencius's-Wei-Bian-San-Jue-three-bamboo-slip-fable, with Modern-Chinese subtitles.",
    "Make me a picture-book audiobook in Old-Chinese about Han-Fei's-Shou-Zhu-Dai-Tu-fox-stump fable, with Modern-Chinese subtitles.",
    "Cook up a children's audiobook in Old-Chinese about Yu-Gong-Yi-Shan-Yu-Gong-moves-the-mountain, with Modern-Chinese subtitles.",
    "Produce a narrated children's audiobook in Old-Chinese about Sai-Weng-Shi-Ma-Sai-Weng-loses-his-horse fable, with Modern-Chinese subtitles.",
    "Generate a kids' picture-book audiobook in Old-Chinese about Hua-She-Tian-Zu-painting-snake-adding-feet, with Modern-Chinese subtitles.",
    "Build a bedtime audiobook in Old-Japanese about Kachi-kachi-Yama-Mt-Crackle-Crackle, with Modern-Japanese subtitles.",
    "Tell me an illustrated children's audiobook in Old-Japanese about Bunbuku-Chagama-tea-kettle-tanuki, with Modern-Japanese subtitles.",
    "Make me a picture-book audiobook in Old-Japanese about Saru-Kani-Kassen-monkey-crab-battle, with Modern-Japanese subtitles.",
    "Cook up a children's audiobook in Old-Japanese about Tanuki-no-Hara-Tsuzumi-tanuki-belly-drum, with Modern-Japanese subtitles.",
    "Produce a narrated children's audiobook in Korean about Heungbu-and-Nolbu-swallow-pumpkin, with English subtitles.",
    "Generate a kids' picture-book audiobook in Korean about Tiger-and-Persimmon-fable, with English subtitles.",
    "Build a bedtime audiobook in Korean about Tortoise-and-Rabbit-Korean-fable, with English subtitles.",
    "Tell me an illustrated children's audiobook in Vietnamese about Tấm-Cám-Cinderella-fish-fable, with English subtitles.",
    "Make me a picture-book audiobook in Vietnamese about Sơn-Tinh-Thủy-Tinh-mountain-water-spirits, with English subtitles.",
    "Cook up a children's audiobook in Thai about Cock-and-the-Crab-Thai-folk-fable, with English subtitles.",
    "Produce a narrated children's audiobook in Thai about Phra-Aphai-Mani-mermaid-tale, with English subtitles.",
    "Generate a kids' picture-book audiobook in Burmese about Nga-Mani-Galay-fable, with English subtitles.",
    "Build a bedtime audiobook in Khmer about Reamker-monkey-king-Khmer-Ramayana, with English subtitles.",
    # ── more Arabian Nights / Persian Shahnameh / Sufi-tale retellings (50) ──
    "Tell me a children's audiobook in Classical-Arabic about Aladdin-and-the-Magic-Lamp, with English subtitles overlaid.",
    "I want an illustrated audiobook in Classical-Arabic about Ali-Baba-and-the-Forty-Thieves, with English subtitles.",
    "Make me a bedtime audiobook in Classical-Arabic about Sinbad-the-Sailor's-First-Voyage, with English subtitles.",
    "Create a picture-book audiobook in Classical-Arabic about Sinbad-the-Sailor's-Second-Voyage-Roc, with English subtitles.",
    "Produce an illustrated children's tale in Classical-Arabic about Sinbad-the-Sailor's-Sixth-Voyage-Mountain-of-Light, with English subtitles.",
    "Cook up a narrated children's audiobook in Classical-Arabic about Scheherazade-1001-Nights-frame, with English subtitles.",
    "Generate a kids' picture-book audiobook in Classical-Arabic about The-Fisherman-and-the-Jinni, with English subtitles.",
    "Build a bedtime audiobook in Classical-Arabic about The-Three-Apples-Mystery, with English subtitles.",
    "Tell me an illustrated children's audiobook in Classical-Arabic about The-Hunchback's-Tale-Baghdad, with English subtitles.",
    "Make me a picture-book audiobook in Classical-Arabic about The-Tale-of-Nur-al-Din-and-Anis-al-Jalis, with English subtitles.",
    "Cook up a children's audiobook in Classical-Arabic about The-Ebony-Horse-flying-machine, with English subtitles.",
    "Produce a narrated children's audiobook in Classical-Arabic about The-City-of-Brass, with English subtitles.",
    "Generate a kids' picture-book audiobook in Classical-Arabic about The-Tale-of-the-Three-Kings-of-Persia, with English subtitles.",
    "Build a bedtime audiobook in Classical-Arabic about The-Story-of-Princess-Parizade, with English subtitles.",
    "Tell me an illustrated children's audiobook in Classical-Arabic about Prince-Ahmed-and-the-Fairy-Pari-Banu, with English subtitles.",
    "Make me a picture-book audiobook in Classical-Arabic about The-Enchanted-Horse-Persian-prince, with English subtitles.",
    "Cook up a children's audiobook in Persian about Rostam-and-Sohrab-Shahnameh, with English subtitles.",
    "Produce a narrated children's audiobook in Persian about Rostam-and-the-Seven-Trials-Haft-Khan, with English subtitles.",
    "Generate a kids' picture-book audiobook in Persian about Rostam-and-Esfandiyar-Shahnameh, with English subtitles.",
    "Build a bedtime audiobook in Persian about Zal-and-Rudaba-Shahnameh, with English subtitles.",
    "Tell me an illustrated children's audiobook in Persian about Bizhan-and-Manijeh-Shahnameh, with English subtitles.",
    "Make me a picture-book audiobook in Persian about Siyâvash-and-the-Trial-by-Fire, with English subtitles.",
    "Cook up a children's audiobook in Persian about Kay-Khosrow-and-the-Holy-Grail, with English subtitles.",
    "Produce a narrated children's audiobook in Persian about Jamshid-the-First-King, with English subtitles.",
    "Generate a kids' picture-book audiobook in Persian about Faridun-and-Zahhak-Shahnameh, with English subtitles.",
    "Build a bedtime audiobook in Persian about Kaveh-the-Blacksmith-Shahnameh, with English subtitles.",
    "Tell me an illustrated children's audiobook in Persian about Yusuf-and-Zulaykha-Sufi-romance, with English subtitles.",
    "Make me a picture-book audiobook in Persian about Layla-and-Majnun-Sufi-romance, with English subtitles.",
    "Cook up a children's audiobook in Persian about Rumi-Mathnawi-Reed-Flute, with English subtitles.",
    "Produce a narrated children's audiobook in Persian about Rumi-Conference-of-the-Birds-Attar, with English subtitles.",
    "Generate a kids' picture-book audiobook in Persian about Hafez-Diwan-tale, with English subtitles.",
    "Build a bedtime audiobook in Persian about Saadi-Gulistan-Rose-Garden, with English subtitles.",
    "Tell me an illustrated children's audiobook in Persian about Saadi-Bustan-Orchard-tale, with English subtitles.",
    "Make me a picture-book audiobook in Persian about Khaqani-Shirvan-poem, with English subtitles.",
    "Cook up a children's audiobook in Persian about Nizami-Khamsa-Five-Treasures, with English subtitles.",
    "Produce a narrated children's audiobook in Persian about Khusrau-and-Shirin-Nizami, with English subtitles.",
    "Generate a kids' picture-book audiobook in Persian about Nizami-Seven-Beauties-Haft-Paykar, with English subtitles.",
    "Build a bedtime audiobook in Persian about Sheikh-Sanan-Attar-tale, with English subtitles.",
    "Tell me an illustrated children's audiobook in Persian about Mansur-Hallaj-Sufi-tale, with English subtitles.",
    "Make me a picture-book audiobook in Persian about Bayazid-Bistami-Sufi-tale, with English subtitles.",
    "Cook up a children's audiobook in Old-Turkish about Dede-Korkut-Oghuz-tales, with English subtitles.",
    "Produce a narrated children's audiobook in Turkish about Nasreddin-Hoca-tales, with English subtitles.",
    "Generate a kids' picture-book audiobook in Turkish about Karagöz-and-Hacivat-shadow-puppets, with English subtitles.",
    "Build a bedtime audiobook in Uzbek about Alpamysh-Karakalpak-epic, with English subtitles.",
    "Tell me an illustrated children's audiobook in Uzbek about Hodja-Nasreddin-Bukhara, with English subtitles.",
    "Make me a picture-book audiobook in Tajik about Mevlana-Jalaluddin-Balkh, with English subtitles.",
    "Cook up a children's audiobook in Pashto about Khushal-Khan-Khattak-Pashto-poet, with English subtitles.",
    "Produce a narrated children's audiobook in Urdu about Iqbal's-Shaheen-tale, with English subtitles.",
    "Generate a kids' picture-book audiobook in Urdu about Mir-Taqi-Mir-Diwan-tale, with English subtitles.",
    "Build a bedtime audiobook in Urdu about Ghalib's-Diwan-tale, with English subtitles.",
    # ── more Greek myths (50) ──
    "Tell me an illustrated children's audiobook in Greek about Perseus-and-Medusa, with English subtitles.",
    "Make me a picture-book audiobook in Greek about Theseus-and-the-Minotaur, with English subtitles.",
    "Cook up a children's audiobook in Greek about Heracles-Twelve-Labours, with English subtitles.",
    "Produce a narrated children's audiobook in Greek about Jason-and-the-Argonauts, with English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Odysseus-and-the-Cyclops, with English subtitles.",
    "Build a bedtime audiobook in Greek about Pandora's-Box, with English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Prometheus-bringing-fire-to-man, with English subtitles.",
    "Make me a picture-book audiobook in Greek about Icarus-and-Daedalus, with English subtitles.",
    "Cook up a children's audiobook in Greek about Orpheus-and-Eurydice, with English subtitles.",
    "Produce a narrated children's audiobook in Greek about Cupid-and-Psyche, with English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Atalanta-and-the-Calydonian-Boar, with English subtitles.",
    "Build a bedtime audiobook in Greek about Bellerophon-and-Pegasus, with English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Persephone-and-Hades, with English subtitles.",
    "Make me a picture-book audiobook in Greek about Demeter-and-the-Eleusinian-Mysteries, with English subtitles.",
    "Cook up a children's audiobook in Greek about Apollo-and-Daphne, with English subtitles.",
    "Produce a narrated children's audiobook in Greek about Artemis-and-Actaeon, with English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Athena-and-Arachne, with English subtitles.",
    "Build a bedtime audiobook in Greek about Hephaestus-and-the-Golden-Throne, with English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Hermes-and-the-cattle-of-Apollo, with English subtitles.",
    "Make me a picture-book audiobook in Greek about Dionysus-and-the-pirates, with English subtitles.",
    "Cook up a children's audiobook in Greek about Narcissus-and-Echo, with English subtitles.",
    "Produce a narrated children's audiobook in Greek about Pyramus-and-Thisbe, with English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Cadmus-and-the-founding-of-Thebes, with English subtitles.",
    "Build a bedtime audiobook in Greek about Oedipus-and-the-Sphinx, with English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Antigone-and-Creon, with English subtitles.",
    "Make me a picture-book audiobook in Greek about Electra-and-Orestes, with English subtitles.",
    "Cook up a children's audiobook in Greek about Achilles-and-Patroclus-at-Troy, with English subtitles.",
    "Produce a narrated children's audiobook in Greek about Helen-of-Troy-and-Paris, with English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Hector-and-Andromache, with English subtitles.",
    "Build a bedtime audiobook in Greek about Aeneas-fleeing-Troy, with English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Sisyphus-and-the-boulder, with English subtitles.",
    "Make me a picture-book audiobook in Greek about Tantalus-and-the-fruit-tree, with English subtitles.",
    "Cook up a children's audiobook in Greek about Midas-and-the-golden-touch, with English subtitles.",
    "Produce a narrated children's audiobook in Greek about Phaethon-and-the-Sun-Chariot, with English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Arion-and-the-dolphin, with English subtitles.",
    "Build a bedtime audiobook in Greek about Philemon-and-Baucis, with English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Galatea-and-Pygmalion, with English subtitles.",
    "Make me a picture-book audiobook in Greek about Andromeda-and-the-sea-monster, with English subtitles.",
    "Cook up a children's audiobook in Greek about Atlas-holding-up-the-sky, with English subtitles.",
    "Produce a narrated children's audiobook in Greek about Castor-and-Pollux-Dioscuri, with English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Meleager-and-the-Calydonian-hunt, with English subtitles.",
    "Build a bedtime audiobook in Greek about Hippolytus-and-Phaedra, with English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Procne-and-Philomela, with English subtitles.",
    "Make me a picture-book audiobook in Greek about Hyacinthus-and-Apollo, with English subtitles.",
    "Cook up a children's audiobook in Greek about Adonis-and-Aphrodite, with English subtitles.",
    "Produce a narrated children's audiobook in Greek about Eros-bringing-life-to-Pandora, with English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about Selene-and-Endymion, with English subtitles.",
    "Build a bedtime audiobook in Greek about Calypso-and-Odysseus, with English subtitles.",
    "Tell me an illustrated children's audiobook in Greek about Circe-and-the-pigs, with English subtitles.",
    "Make me a picture-book audiobook in Greek about Polyphemus-and-Galatea-and-Acis, with English subtitles.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
