"""x15 story_imgref_music SFT.
Chain: IntakeImage → BriefEnricher → Narration → Illustration → Narrator → Music → AudioMix → Compositor.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a sketch of my niece — make me a children's audiobook with her as the heroine, with soft-piano BGM.",
    "Here's a portrait of my grandfather — produce a kids' picture-book audiobook of him as a young captain, with maritime-folk BGM.",
    "I'm sending you a watercolor of a friendly dragon — build an illustrated children's tale of his first flight, with adventurous-orchestral BGM.",
    "Uploading a digital painting of a young witch — make a bedtime audiobook of her broom-cycle home, with whimsical-flute BGM.",
    "Here's a sketch of a young samurai — render an illustrated children's audiobook of his teahouse training, with shakuhachi BGM.",
    "Attaching a portrait of a young Bedouin girl — produce a children's audiobook of her oasis journey, with oud BGM.",
    "Uploading a digital portrait of a young Inuit girl — make a bedtime audiobook of her ice-fishing day, with throat-singing BGM.",
    "Here's a watercolor of a young Maori girl — build an illustrated children's tale of her sea-canoe voyage, with taonga-pūoro BGM.",
    "I'd like a kids' audiobook from this sketch of a young Mongolian eagle-hunter girl, with Mongolian throat-singing BGM.",
    "Uploading a digital painting of a young Sami reindeer-herder — render a picture-book audiobook of her snow-trek, with Sami-yoik BGM.",
    "Here's a portrait of a young Hawaiian girl — produce a children's audiobook of her hula-school class, with Hawaiian-ipu-heke BGM.",
    "I have a sketch of a young Welsh shepherdess — make a bedtime audiobook of her morning at the meadow, with Welsh-folk BGM.",
    "Uploading a watercolor of a young Norse girl — build an illustrated children's tale of her longship dawn, with Norse-throat-singing BGM.",
    "Here's a digital painting of a young Andean weaver — render a picture-book audiobook of her loom afternoon, with Andean-pan-flute BGM.",
    "I'm sending you a sketch of a young Yoruba drummer — produce a children's audiobook of his courtyard rhythm, with djembe BGM.",
    "Uploading a portrait of a young Khmer dancer — make a bedtime audiobook of her Angkor-courtyard rehearsal, with Khmer-flute BGM.",
    "Here's a watercolor of a young Tibetan novice — build an illustrated children's audiobook of his monastery dawn, with singing-bowl BGM.",
    "I have a digital portrait of a young Mexican girl — render a children's audiobook of her abuela's kitchen, with mariachi-trumpet BGM.",
    "Uploading a sketch of a young Ethiopian Coptic deacon — produce a kids' audiobook of his desert-monastery walk, with masenqo-fiddle BGM.",
    "Here's a portrait of a young Russian girl — make a bedtime audiobook of her grandmother's tea-stories, with balalaika BGM.",
    "I'm sending you a watercolor of a young Greek shepherdess — build an illustrated children's tale of her Aegean morning, with bouzouki BGM.",
    "Uploading a digital painting of a young Venetian gondolier boy — render a kids' audiobook of his canal mornings, with Italian-mandolin BGM.",
    "Here's a sketch of a young Florentine apprentice — produce a children's audiobook of his sunlit workshop, with Renaissance-lute BGM.",
    "I have a portrait of a young Cuban abuelita — make a bedtime audiobook of her courtyard tales, with Cuban-tres BGM.",
    "Uploading a watercolor of a young Senegalese kora-player — build an illustrated children's tale of his street-corner concert, with kora BGM.",
    "Here's a digital portrait of a young Bhutanese archer — render a kids' audiobook of her Thimphu festival, with Bhutanese-flute BGM.",
    "I'm sending you a sketch of a young Mongolian wrestler — produce a children's audiobook of his steppe training, with Mongolian-horse-fiddle BGM.",
    "Uploading a portrait of a young Korean hanbok-clad girl — make a bedtime audiobook of her courtyard arts class, with gayageum BGM.",
    "Here's a watercolor of a young Vietnamese conical-hat girl — build an illustrated children's tale of her river morning, with dan-bau BGM.",
    "I have a digital painting of a young Tongan girl — render a kids' audiobook of her tropical-shore day, with Tongan-lali BGM.",
    "Uploading a sketch of a young Patagonian shepherd boy — produce a children's audiobook of his glacier-path walk, with Argentine-folk-fiddle BGM.",
    "Here's a portrait of a young Chilean rodeo girl — make a bedtime audiobook of her huaso-class day, with Chilean-cueca BGM.",
    "I'm sending you a watercolor of a young Argentine tango-girl — build an illustrated children's tale of her La Boca courtyard, with bandoneón BGM.",
    "Uploading a digital portrait of a young Brazilian Capoeira-girl — render a kids' audiobook of her Salvador courtyard class, with berimbau BGM.",
    "Here's a sketch of a young Colombian cumbia-girl — produce a children's audiobook of her Caribbean-village dance, with cumbia-accordion BGM.",
    # ── more reference-image audiobooks with BGM (50) ─────────────────────
    "Uploading a portrait of a young Italian-Renaissance painter — make a children's audiobook of her sun-drenched workshop morning, with Italian-Renaissance-strings BGM.",
    "Here's a sketch of a young Florentine apothecary girl — produce a kids' picture-book audiobook of her herb-grinding day, with Italian-Renaissance-lute BGM.",
    "I'm sending you a watercolor of a young Lyon silk-weaver girl — build an illustrated children's tale of her loom-room dawn, with French-musette BGM.",
    "Uploading a digital painting of a young Provence lavender-picker — make a bedtime audiobook of her summer-field afternoon, with French-folk BGM.",
    "Here's a sketch of a young Andalusian flamenco girl — render an illustrated children's audiobook of her courtyard rehearsal, with flamenco-guitar BGM.",
    "Attaching a portrait of a young Galician fisherwoman — produce a children's audiobook of her Atlantic morning, with Galician-gaita BGM.",
    "Uploading a digital portrait of a young Basque shepherd boy — make a bedtime audiobook of his Pyrenean meadow day, with Basque-txistu BGM.",
    "Here's a watercolor of a young Catalan castell girl — build an illustrated children's tale of her tower-climbing festival, with Catalan-folk BGM.",
    "I'd like a kids' audiobook from this sketch of a young Sardinian shepherd boy, with Sardinian-launeddas BGM.",
    "Uploading a digital painting of a young Sicilian fisherman boy — render a picture-book audiobook of his harbor dawn, with Sicilian-tarantella BGM.",
    "Here's a portrait of a young Beijing courtyard girl — produce a children's audiobook of her hutong morning, with Chinese-erhu BGM.",
    "I have a sketch of a young Suzhou silk-girl — make a bedtime audiobook of her loom afternoon, with Chinese-pipa BGM.",
    "Uploading a watercolor of a young Hangzhou tea-girl — build an illustrated children's tale of her West-Lake harvest, with Chinese-guzheng BGM.",
    "Here's a digital painting of a young Yunnan ethnic-minority girl — render a picture-book audiobook of her terraced-field day, with Yunnan-bamboo-flute BGM.",
    "I'm sending you a sketch of a young Tibetan plateau girl — produce a children's audiobook of her yak-herd afternoon, with Tibetan-singing-bowl BGM.",
    "Uploading a portrait of a young Sichuan panda-keeper girl — make a bedtime audiobook of her bamboo-grove morning, with Chinese-bamboo-flute BGM.",
    "Here's a watercolor of a young Kashmir saffron-picker girl — build an illustrated children's audiobook of her crocus-field dawn, with Kashmiri-rabab BGM.",
    "I have a digital portrait of a young Bangalore tech-student — render a children's audiobook of her bustling-city day, with Indian-fusion BGM.",
    "Uploading a sketch of a young Goan fisher boy — produce a kids' audiobook of his beach-shack morning, with Goan-mandolin BGM.",
    "Here's a portrait of a young Burmese saung-player — make a bedtime audiobook of his Mandalay courtyard rehearsal, with Burmese-saung BGM.",
    "I'm sending you a watercolor of a young Berber goat-herd girl — build an illustrated children's tale of her Atlas-mountain dusk, with Berber-bendir BGM.",
    "Uploading a digital painting of a young Swahili-coast fisherman boy — render a kids' audiobook of his dhow morning, with Swahili-taarab BGM.",
    "Here's a sketch of a young Hausa kakaki-trumpeter — produce a children's audiobook of his Durbar-festival arrival, with Hausa-kakaki BGM.",
    "I have a portrait of a young Maasai warrior boy — make a bedtime audiobook of his Mara plain dawn, with Maasai-chant BGM.",
    "Uploading a watercolor of a young Zulu praise-poet — build an illustrated children's tale of her village courtyard, with Zulu-percussion BGM.",
    "Here's a digital portrait of a young Akan goldsmith girl — render a kids' audiobook of her Kumasi forge-morning, with Akan-fontomfrom BGM.",
    "I'm sending you a sketch of a young Igbo mask-carver boy — produce a children's audiobook of his masquerade rehearsal, with Igbo-percussion BGM.",
    "Uploading a portrait of a young Wolof griot girl — make a bedtime audiobook of her Saint-Louis kora-evening, with Wolof-sabar BGM.",
    "Here's a watercolor of a young Tigrinya weaver girl — build an illustrated children's tale of her highland-loom morning, with Tigrinya-krar BGM.",
    "I have a digital painting of a young Madagascan lemur-friend girl — render a kids' audiobook of her baobab-grove afternoon, with Malagasy-valiha BGM.",
    "Uploading a sketch of a young Polish folk-fiddle girl — produce a children's audiobook of her Tatra-mountain festival, with Polish-folk-fiddle BGM.",
    "Here's a portrait of a young Czech glassblower boy — make a bedtime audiobook of his Bohemian-kiln morning, with Czech-cimbalom BGM.",
    "I'm sending you a watercolor of a young Slovak fujara shepherd boy — build an illustrated children's tale of his Carpathian-pasture noon, with Slovak-fujara BGM.",
    "Uploading a digital portrait of a young Hungarian csikós girl — render a kids' audiobook of her Puszta gallop, with Hungarian-csárdás BGM.",
    "Here's a sketch of a young Bulgarian rose-picker girl — produce a children's audiobook of her Rose-Valley dawn, with Bulgarian-gaida BGM.",
    "I have a portrait of a young Romanian Maramureș shepherd — make a bedtime audiobook of his alpine-meadow morning, with Romanian-fiddle BGM.",
    "Uploading a watercolor of a young Albanian iso-polyphonic singer — build an illustrated children's audiobook of her village-courtyard practice, with Albanian-iso-polyphonic BGM.",
    "Here's a digital painting of a young Faroese fisher boy — render a kids' audiobook of his stormy-harbor morning, with Faroese-kvæði BGM.",
    "I'm sending you a sketch of a young Icelandic horse-girl — produce a children's audiobook of her windy-moor ride, with Icelandic-folk BGM.",
    "Uploading a portrait of a young Estonian regilaul singer — make a bedtime audiobook of her bonfire-singing night, with Estonian-regilaul BGM.",
    "Here's a watercolor of a young Quebec maple-tapper girl — build an illustrated children's tale of her sugar-shack morning, with Quebec-folk-fiddle BGM.",
    "I have a digital portrait of a young Cajun bayou fisherman boy — render a kids' audiobook of his pirogue dawn, with Cajun-fiddle BGM.",
    "Uploading a sketch of a young Appalachian fiddler — produce a children's audiobook of his hollow-porch evening, with Appalachian-fiddle BGM.",
    "Here's a portrait of a young New-England lobsterman boy — make a bedtime audiobook of his foggy-pier morning, with New-England-folk BGM.",
    "I'm sending you a watercolor of a young Cherokee weaver girl — build an illustrated children's tale of her riverbank loom, with Cherokee-flute BGM.",
    "Uploading a digital painting of a young Lakota grandmother — render a kids' audiobook of her storytelling night, with Lakota-flute BGM.",
    "Here's a sketch of a young Yucatec Mayan dancer — produce a children's audiobook of her cenote-festival evening, with Yucatec-jarana BGM.",
    "I have a portrait of a young Quechua shepherdess — make a bedtime audiobook of her Andean morning, with Andean-pan-flute BGM.",
    "Uploading a watercolor of a young Aymara herder boy — build an illustrated children's tale of his altiplano dusk, with Aymara-zampoña BGM.",
    "Here's a digital portrait of a young Garifuna drummer girl — render a kids' audiobook of her Caribbean-shore evening, with Garifuna-drum BGM.",
    # ── more reference-image audiobooks with BGM (50) ─────────────────────
    "Uploading a portrait of a young ancient-Egyptian girl with her cat — make a children's audiobook of her papyrus-scroll workshop morning, with Egyptian-harp BGM.",
    "Here's a sketch of a young Sumerian princess — produce a kids' picture-book audiobook of her ziggurat moonrise, with Mesopotamian-lyre BGM.",
    "I'm sending you a watercolor of a young Babylonian astrologer girl — build an illustrated children's tale of her lapis-tower dusk, with Mesopotamian-lyre BGM.",
    "Uploading a digital painting of a young Phoenician sailor boy — make a bedtime audiobook of his cedar-prow dawn, with seafaring-aulos BGM.",
    "Here's a sketch of a young Carthaginian merchant girl — render an illustrated children's audiobook of her Mediterranean-port morning, with Phoenician-tambourine BGM.",
    "Attaching a portrait of a young Etruscan singer — produce a children's audiobook of her tomb-fresco rehearsal, with Etruscan-aulos BGM.",
    "Uploading a digital portrait of a young Trojan herald — make a bedtime audiobook of his wall-walk dusk, with Bronze-Age-trumpet BGM.",
    "Here's a watercolor of a young Spartan girl — build an illustrated children's tale of her agoge-training morning, with ancient-Greek-aulos BGM.",
    "I'd like a kids' audiobook from this sketch of a young Athenian philosopher's daughter at the agora at evening, with Greek-lyre BGM.",
    "Uploading a digital painting of a young Roman patrician girl — render a picture-book audiobook of her villa-courtyard afternoon, with Roman-cithara BGM.",
    "Here's a portrait of a young Pompeii girl — produce a children's audiobook of her seaside-villa morning, with Pompeian-tibia BGM.",
    "I have a sketch of a young Byzantine icon-painter — make a bedtime audiobook of her scriptorium afternoon, with Byzantine-chant BGM.",
    "Uploading a watercolor of a young Ottoman calligrapher boy — build an illustrated children's tale of his Topkapi-atelier morning, with Ottoman-ney BGM.",
    "Here's a digital painting of a young Mughal court-poet girl — render a picture-book audiobook of her Agra-balcony evening, with Mughal-sitar BGM.",
    "I'm sending you a sketch of a young Tang-dynasty courtyard girl — produce a children's audiobook of her Chang'an spring afternoon, with Tang-pipa BGM.",
    "Uploading a portrait of a young Song-dynasty artist — make a bedtime audiobook of her West-Lake studio morning, with Song-guqin BGM.",
    "Here's a watercolor of a young Yuan-dynasty cartographer — build an illustrated children's audiobook of his steppe-tent night, with Yuan-erhu BGM.",
    "I have a digital portrait of a young Ming-dynasty Forbidden-City boy — render a children's audiobook of his Imperial-garden morning, with Ming-dizi BGM.",
    "Uploading a sketch of a young Qing-dynasty kite-maker — produce a kids' audiobook of her hutong-workshop afternoon, with Qing-yueqin BGM.",
    "Here's a portrait of a young Joseon palace-girl — make a bedtime audiobook of her Gyeongbok-courtyard morning, with Korean-gayageum BGM.",
    "I'm sending you a watercolor of a young Heian-era lady-in-waiting — build an illustrated children's tale of her bamboo-screen evening, with Heian-koto BGM.",
    "Uploading a digital painting of a young Edo-era artist's apprentice — render a kids' audiobook of his ukiyo-e workshop afternoon, with Edo-shamisen BGM.",
    "Here's a sketch of a young Meiji-era schoolgirl — produce a children's audiobook of her stone-school morning, with Meiji-piano BGM.",
    "I have a portrait of a young Taisho-era flapper — make a bedtime audiobook of her Ginza-café evening, with Taisho-jazz BGM.",
    "Uploading a watercolor of a young Showa-era bookseller — build an illustrated children's tale of his Tokyo-bookshelf afternoon, with Showa-folk BGM.",
    "Here's a digital portrait of a young Edwardian-era English girl — render a kids' audiobook of her Regent-Park morning, with parlour-piano BGM.",
    "I'm sending you a sketch of a young Victorian-era English boy — produce a children's audiobook of his London-cobblestone evening, with Victorian-music-hall BGM.",
    "Uploading a portrait of a young Regency-era ballerina — make a bedtime audiobook of her King's-Theatre rehearsal, with Regency-pianoforte BGM.",
    "Here's a watercolor of a young Tudor-era seamstress — build an illustrated children's tale of her manor-loom afternoon, with Tudor-lute BGM.",
    "I have a digital painting of a young Elizabethan playwright's daughter — render a kids' audiobook of her Globe-Theatre balcony, with Elizabethan-lute BGM.",
    "Uploading a sketch of a young Stuart-era court page — produce a children's audiobook of his Hampton-Court morning, with Stuart-harpsichord BGM.",
    "Here's a portrait of a young Georgian-era kitchen girl — make a bedtime audiobook of her manor-kitchen morning, with Georgian-fiddle BGM.",
    "I'm sending you a watercolor of a young Belle-Époque Parisian girl — build an illustrated children's tale of her Tuileries afternoon, with French-cancan BGM.",
    "Uploading a digital portrait of a young fin-de-siècle Vienna girl — render a kids' audiobook of her Wiener-Café morning, with Viennese-zither BGM.",
    "Here's a sketch of a young fin-de-siècle Berlin boy — produce a children's audiobook of his Prenzlauer-Berg evening, with Berlin-cabaret BGM.",
    "I have a portrait of a young Roaring-Twenties flapper-dancer — make a bedtime audiobook of her Harlem-club evening, with Charleston-jazz BGM.",
    "Uploading a watercolor of a young Jazz-Age cornetist — build an illustrated children's tale of his New-Orleans-street evening, with Dixieland-jazz BGM.",
    "Here's a digital painting of a young Depression-Era farm-boy — render a picture-book audiobook of his Iowa-cornfield evening, with Dust-Bowl-folk BGM.",
    "I'm sending you a sketch of a young Dust-Bowl-Era Oklahoma girl — produce a children's audiobook of her wind-blown porch, with Woody-Guthrie folk BGM.",
    "Uploading a portrait of a young WW2-era London Blitz-girl — make a bedtime audiobook of her Underground-shelter night, with Vera-Lynn vocal BGM.",
    "Here's a watercolor of a young WW2-era ATA pilot girl — build an illustrated children's tale of her airfield dawn, with Glenn-Miller swing BGM.",
    "I have a digital portrait of a young 1940s Pacific-front Navy-nurse — render a kids' audiobook of her hospital-ship dawn, with Andrews-Sisters swing BGM.",
    "Uploading a sketch of a young 1940s GI-Bride — produce a children's audiobook of her ocean-liner morning, with big-band swing BGM.",
    "Here's a portrait of a young 1950s sock-hop girl — make a bedtime audiobook of her diner-jukebox evening, with doo-wop BGM.",
    "I'm sending you a watercolor of a young 1950s suburban mom — build an illustrated children's tale of her kitchen-radio morning, with cocktail-jazz BGM.",
    "Uploading a digital painting of a young 1960s flower-child — render a kids' audiobook of her Haight-Ashbury afternoon, with psychedelic-rock BGM.",
    "Here's a sketch of a young 1960s ad-agency typist — produce a children's audiobook of her Madison-Ave morning, with bossa-nova BGM.",
    "I have a portrait of a young 1970s feminist activist — make a bedtime audiobook of her march-rally afternoon, with folk-rock BGM.",
    "Uploading a watercolor of a young 1970s journalist — build an illustrated children's tale of her New-York-newsroom dusk, with disco-funk BGM.",
    "Here's a digital portrait of a young 1980s arcade-keeper — render a kids' audiobook of her neon-arcade evening, with chiptune BGM.",
    # ── more fantasy / sci-fi character portraits + BGM (50) ──
    "I'm sending you a portrait of a young apprentice wizard — produce a children's audiobook of his moonlit-tower evening, with mystical-celesta BGM.",
    "Uploading a watercolor of a young apprentice sorceress — make a bedtime audiobook of her enchanted-garden afternoon, with delicate-harp BGM.",
    "Here's a digital portrait of a young dragon-rider in training — build an illustrated children's tale of her clifftop dawn, with epic-orchestral BGM.",
    "I have a sketch of a young court-jester elf — render a kids' audiobook of his palace-courtyard afternoon, with playful-pizzicato BGM.",
    "Uploading a portrait of a young dwarf blacksmith's apprentice — produce a children's audiobook of his forge-morning, with rugged-percussion BGM.",
    "Here's a watercolor of a young troll-bridge-keeper — make a bedtime audiobook of his moonlit-bridge evening, with deep-cello BGM.",
    "I'm sending you a digital painting of a young centaur-archer — build an illustrated children's tale of her forest dawn, with woodland-flute BGM.",
    "Uploading a sketch of a young griffin-tamer — render a kids' audiobook of his mountain-aerie afternoon, with majestic-horns BGM.",
    "Here's a portrait of a young phoenix-keeper — produce a children's audiobook of his temple-evening, with sacred-strings BGM.",
    "I have a watercolor of a young mermaid scholar — make a bedtime audiobook of her coral-library afternoon, with serene-celesta BGM.",
    "Uploading a digital portrait of a young selkie minstrel — build an illustrated children's tale of her shore dawn, with Celtic-harp BGM.",
    "Here's a sketch of a young naiad fountain-tender — render a kids' audiobook of her glade afternoon, with delicate-flute BGM.",
    "I'm sending you a portrait of a young dryad-grove-warden — produce a children's audiobook of her oak-grove dawn, with woodland-harp BGM.",
    "Uploading a watercolor of a young moss-witch's apprentice — make a bedtime audiobook of her swamp-cottage evening, with eerie-celesta BGM.",
    "Here's a digital painting of a young alchemist's apprentice — build an illustrated children's tale of her workshop afternoon, with curious-strings BGM.",
    "I have a sketch of a young clockwork-tinker — render a kids' audiobook of his lantern-lit shop evening, with mechanical-pizzicato BGM.",
    "Uploading a portrait of a young airship-cabin-girl — produce a children's audiobook of her cloud-deck morning, with steampunk-march BGM.",
    "Here's a watercolor of a young steam-engine apprentice — make a bedtime audiobook of his dockyard evening, with industrial-brass BGM.",
    "I'm sending you a digital portrait of a young sky-pirate cabin-mate — build an illustrated children's tale of her airship dawn, with adventurous-shanty BGM.",
    "Uploading a sketch of a young automaton-handler — render a kids' audiobook of her workshop afternoon, with clockwork-pizzicato BGM.",
    "Here's a portrait of a young space-port mechanic — produce a children's audiobook of her hangar morning, with retro-synth BGM.",
    "I have a watercolor of a young rocket-pilot trainee — make a bedtime audiobook of her launch-pad evening, with countdown-electronic BGM.",
    "Uploading a digital painting of a young space-station gardener — build an illustrated children's tale of her hydroponic-bay morning, with serene-electronic BGM.",
    "Here's a sketch of a young moon-base researcher — render a kids' audiobook of her lunar-window evening, with cosmic-ambient BGM.",
    "I'm sending you a portrait of a young Mars-colony schoolgirl — produce a children's audiobook of her dome-school afternoon, with retro-future-orchestral BGM.",
    "Uploading a watercolor of a young asteroid-prospector — make a bedtime audiobook of his cabin-evening, with sparse-synth BGM.",
    "Here's a digital portrait of a young deep-space comm-operator — build an illustrated children's tale of her bridge dawn, with ethereal-synth BGM.",
    "I have a sketch of a young alien-language translator — render a kids' audiobook of her lab afternoon, with curious-electronic BGM.",
    "Uploading a portrait of a young xeno-botanist — produce a children's audiobook of her greenhouse morning, with curious-glass-armonica BGM.",
    "Here's a watercolor of a young terraforming engineer — make a bedtime audiobook of her glacier-dome afternoon, with hopeful-orchestral BGM.",
    "I'm sending you a digital painting of a young cyber-deck hacker — build an illustrated children's tale of her neon-bedroom evening, with synthwave BGM.",
    "Uploading a sketch of a young VR-arcade-runner — render a kids' audiobook of her arcade-pod afternoon, with chiptune-synth BGM.",
    "Here's a portrait of a young drone-courier — produce a children's audiobook of her sky-lane morning, with techno-pop BGM.",
    "I have a watercolor of a young cybernetic-sushi-chef — make a bedtime audiobook of his lantern-stall evening, with city-pop BGM.",
    "Uploading a digital portrait of a young hover-bike messenger — build an illustrated children's tale of her megacity-rooftop morning, with cyberpunk BGM.",
    "Here's a sketch of a young AI-companion-trainer — render a kids' audiobook of her studio afternoon, with ambient-electronic BGM.",
    "I'm sending you a portrait of a young hologram-busker — produce a children's audiobook of his arcade evening, with neon-synth BGM.",
    "Uploading a watercolor of a young synth-musician — make a bedtime audiobook of her studio afternoon, with synth-pop BGM.",
    "Here's a digital painting of a young neon-graffiti artist — build an illustrated children's tale of her alley dawn, with downtempo-electronic BGM.",
    "I have a sketch of a young underground-train-tagger — render a kids' audiobook of her subway evening, with breakbeat BGM.",
    "Uploading a portrait of a young post-apocalyptic-scavenger — produce a children's audiobook of her dustbowl morning, with desolate-strings BGM.",
    "Here's a watercolor of a young desert-dunes nomad — make a bedtime audiobook of her oasis evening, with desert-oud BGM.",
    "I'm sending you a digital portrait of a young ice-station traveler — build an illustrated children's tale of her glacier dawn, with arctic-ambient BGM.",
    "Uploading a sketch of a young undersea-base diver — render a kids' audiobook of his coral-dome afternoon, with underwater-ambient BGM.",
    "Here's a portrait of a young sky-island shepherd — produce a children's audiobook of his cloud-meadow morning, with pastoral-flute BGM.",
    "I have a watercolor of a young volcano-lighthouse keeper — make a bedtime audiobook of her caldera evening, with brooding-percussion BGM.",
    "Uploading a digital painting of a young aurora-watcher — build an illustrated children's tale of her tundra dawn, with shimmering-celesta BGM.",
    "Here's a sketch of a young Atlantis explorer — render a kids' audiobook of her coral-temple afternoon, with mystic-synth BGM.",
    "I'm sending you a portrait of a young storm-rider — produce a children's audiobook of her thunderhead morning, with thunderous-percussion BGM.",
    "Uploading a watercolor of a young rainbow-bridge messenger — make a bedtime audiobook of her cloud-pier evening, with celestial-strings BGM.",
    # ── more 1800s American historical portraits + Americana BGM (50) ──
    "I have a portrait of a young 1800s Lewis-and-Clark expedition member — make a bedtime audiobook of his Missouri-River dawn, with frontier-fiddle BGM.",
    "Uploading a watercolor of a young 1800s Sacagawea-companion — build an illustrated children's tale of her plains-meadow afternoon, with Plains-flute BGM.",
    "Here's a digital portrait of a young 1800s Erie-Canal-bargeman — render a kids' audiobook of his lock-house morning, with canal-shanty BGM.",
    "I'm sending you a sketch of a young 1800s Hudson-River steam-boat-deckhand — produce a children's audiobook of his Hudson-River-evening, with steamboat-banjo BGM.",
    "Uploading a portrait of a young 1800s Boston-cobbler apprentice — make a bedtime audiobook of his North-End shop evening, with Yankee-fiddle BGM.",
    "Here's a watercolor of a young 1800s Salem-witch-trial defender — build an illustrated children's tale of her Old-Burying-Point afternoon, with Puritan-psalm BGM.",
    "I have a digital portrait of a young 1800s Lowell-textile-mill girl — render a kids' audiobook of her Merrimack mill morning, with mill-girl-folk BGM.",
    "Uploading a sketch of a young 1800s Cape-Cod whaler — produce a children's audiobook of his Nantucket-quay afternoon, with whaling-shanty BGM.",
    "Here's a portrait of a young 1800s Mississippi-River-pilot — make a bedtime audiobook of his Ohio-confluence evening, with riverboat-banjo BGM.",
    "I'm sending you a watercolor of a young 1800s Natchez-cotton-merchant — build an illustrated children's tale of his Natchez-Bluff afternoon, with Delta-fiddle BGM.",
    "Uploading a digital portrait of a young 1800s New-Orleans-Creole gardener — render a kids' audiobook of her Garden-District morning, with Creole-quadrille BGM.",
    "Here's a sketch of a young 1800s St-Louis-fur-trader apprentice — produce a children's audiobook of his Mississippi-Missouri morning, with French-Creole-fiddle BGM.",
    "I have a portrait of a young 1800s Santa-Fe-Trail teamster — make a bedtime audiobook of his Cimarron-cutoff evening, with Mexican-corrido BGM.",
    "Uploading a watercolor of a young 1800s Texas-cowboy — build an illustrated children's tale of his Brazos-River afternoon, with cowboy-fiddle BGM.",
    "Here's a digital painting of a young 1800s Oregon-Trail pioneer — render a kids' audiobook of his Sweetwater-River afternoon, with pioneer-hymn BGM.",
    "I'm sending you a sketch of a young 1800s Mormon-Trail handcart-pioneer — produce a children's audiobook of his Wyoming-plain evening, with Mormon-hymn BGM.",
    "Uploading a portrait of a young 1800s California-Gold-Rush placer — make a bedtime audiobook of his Sacramento-River evening, with Gold-Rush-folk BGM.",
    "Here's a watercolor of a young 1800s Sutter's-Mill discovery boy — build an illustrated children's tale of his Coloma morning, with frontier-fiddle-2 BGM.",
    "I have a digital portrait of a young 1800s Pony-Express rider — render a kids' audiobook of her station-relay afternoon, with relay-fiddle BGM.",
    "Uploading a sketch of a young 1800s Transcontinental-Railroad track-layer — produce a children's audiobook of his Promontory-Summit afternoon, with railroad-shanty BGM.",
    "Here's a portrait of a young 1800s Comstock-silver-miner — make a bedtime audiobook of his Virginia-City evening, with Cornish-tin-mine-tune BGM.",
    "I'm sending you a watercolor of a young 1800s Klondike Gold-Rush prospector — build an illustrated children's tale of his Yukon-River morning, with Klondike-folk BGM.",
    "Uploading a digital portrait of a young 1800s Civil-War-Union-bugler — render a kids' audiobook of his Antietam camp dawn, with Union-bugle BGM.",
    "Here's a sketch of a young 1800s Civil-War-Confederate-drummer — produce a children's audiobook of his Vicksburg encampment evening, with Confederate-fife-and-drum BGM.",
    "I have a portrait of a young 1800s Underground-Railroad conductor — make a bedtime audiobook of her Ohio-River-crossing dusk, with spirituals BGM.",
    "Uploading a watercolor of a young 1800s Wendell-Phillips-orator — build an illustrated children's tale of his Faneuil-Hall afternoon, with abolitionist-hymn BGM.",
    "Here's a digital painting of a young 1800s Lyceum-circuit-lecturer — render a kids' audiobook of her village-hall evening, with parlor-piano BGM.",
    "I'm sending you a sketch of a young 1800s Brook-Farm transcendentalist — produce a children's audiobook of his utopian-orchard morning, with parlor-string-quartet BGM.",
    "Uploading a portrait of a young 1800s Walden-Pond-lover-of-nature — make a bedtime audiobook of his Concord-pond morning, with chamber-flute BGM.",
    "Here's a watercolor of a young 1800s Cape-Hatteras-lighthouse keeper — build an illustrated children's tale of his Outer-Banks evening, with sea-shanty BGM.",
    "I have a digital portrait of a young 1800s Gloucester-fisherman — render a kids' audiobook of his Cape-Ann-harbor dawn, with Gloucester-shanty BGM.",
    "Uploading a sketch of a young 1800s Newport-mansions kitchen-girl — produce a children's audiobook of her Bellevue-Avenue evening, with Gilded-Age-parlor-piano BGM.",
    "Here's a portrait of a young 1800s Saratoga-Spa-resort-bellboy — make a bedtime audiobook of his Saratoga-Hot-Springs afternoon, with Saratoga-bandstand BGM.",
    "I'm sending you a watercolor of a young 1800s Coney-Island-resort-belle — build an illustrated children's tale of her boardwalk morning, with Coney-bandstand-march BGM.",
    "Uploading a digital portrait of a young 1800s Catskill-Mountain-House porter — render a kids' audiobook of his Hudson-Valley dawn, with parlor-fiddle BGM.",
    "Here's a sketch of a young 1800s Buckeye-State-Quaker — produce a children's audiobook of her Yellow-Springs morning, with Quaker-hymn BGM.",
    "I have a portrait of a young 1800s Shaker-village-spinner — make a bedtime audiobook of her Hancock-village evening, with Shaker-hymn BGM.",
    "Uploading a watercolor of a young 1800s Cumberland-Gap settler — build an illustrated children's tale of his Daniel-Boone-trail afternoon, with Appalachian-fiddle BGM.",
    "Here's a digital painting of a young 1800s Appalachian-mountain-fiddler — render a kids' audiobook of her Blue-Ridge dusk, with Blue-Ridge-fiddle BGM.",
    "I'm sending you a sketch of a young 1800s Ozark-mountain ballad-singer — produce a children's audiobook of her cabin-porch evening, with Ozark-banjo BGM.",
    "Uploading a portrait of a young 1800s Cherokee-Trail-of-Tears walker — make a bedtime audiobook of her Hiwassee-River afternoon, with Cherokee-flute BGM.",
    "Here's a watercolor of a young 1800s Choctaw-Removal walker — build an illustrated children's tale of his Mississippi-Delta morning, with Choctaw-flute BGM.",
    "I have a digital portrait of a young 1800s Seminole-Everglades hunter — render a kids' audiobook of his sawgrass-prairie afternoon, with Seminole-stomp-dance BGM.",
    "Uploading a sketch of a young 1800s Plains-Lakota-buffalo-hunter — produce a children's audiobook of his Black-Hills morning, with Lakota-honor-song BGM.",
    "Here's a portrait of a young 1800s Apache-Sonoran-tracker — make a bedtime audiobook of his Sonoran-Desert dawn, with Apache-flute BGM.",
    "I'm sending you a watercolor of a young 1800s Navajo-Long-Walk walker — build an illustrated children's tale of her Bosque-Redondo evening, with Navajo-flute BGM.",
    "Uploading a digital portrait of a young 1800s Pueblo-pottery-maker — render a kids' audiobook of her San-Ildefonso afternoon, with Pueblo-flute BGM.",
    "Here's a sketch of a young 1800s Inuit-Nunavut whaler — produce a children's audiobook of her ice-floe-edge morning, with Inuit-throat-song BGM.",
    "I have a portrait of a young 1800s Aleut-otter-hunter — make a bedtime audiobook of his Aleutian-bay afternoon, with Aleut-drum BGM.",
    "Uploading a watercolor of a young 1800s Tlingit-totem-carver — build an illustrated children's tale of her Sitka-shore morning, with Tlingit-drum BGM.",
    # ── more 17th-c. European maritime / Age-of-Exploration + BGM (50) ──
    "I have a portrait of a young 17th-c. Dutch-East-India-Company clerk — make a bedtime audiobook of his Batavia warehouse afternoon, with Dutch-baroque-organ BGM.",
    "Uploading a watercolor of a young 17th-c. VOC-shipwright apprentice — build an illustrated children's tale of her Amsterdam-IJ shipyard, with Dutch-shanty BGM.",
    "Here's a digital portrait of a young 17th-c. Hanseatic-Bremen-merchant page — render a kids' audiobook of his Schlachte-quay morning, with Hanseatic-marching-band BGM.",
    "I'm sending you a sketch of a young 17th-c. Hamburg-fish-cooper — produce a children's audiobook of his Speicherstadt afternoon, with Low-Saxon-folk BGM.",
    "Uploading a portrait of a young 17th-c. Lübeck-marzipan apprentice — make a bedtime audiobook of his Holstentor evening, with Lübeck-organ BGM.",
    "Here's a watercolor of a young 17th-c. Stockholm-shipyard-tar boy — build an illustrated children's tale of his Skeppsholmen morning, with Swedish-folk-strings BGM.",
    "I have a digital portrait of a young 17th-c. Bergen-stockfish-trader — render a kids' audiobook of her Bryggen-warehouse afternoon, with Norwegian-Hardanger-fiddle-3 BGM.",
    "Uploading a sketch of a young 17th-c. Reykjavik-fishery elder — produce a children's audiobook of his turf-cottage morning, with Icelandic-rímur-2 BGM.",
    "Here's a portrait of a young 17th-c. Faroe-puffin-net keeper — make a bedtime audiobook of her sea-cliff afternoon, with Faroese-folk-2 BGM.",
    "I'm sending you a watercolor of a young 17th-c. London-Wapping-shipwright — build an illustrated children's tale of his Thames yard morning, with English-baroque-strings BGM.",
    "Uploading a digital portrait of a young 17th-c. Bristol-tobacco merchant — render a kids' audiobook of his Old-Vic-Quay afternoon, with Bristol-shanty BGM.",
    "Here's a sketch of a young 17th-c. Liverpool-spice-cooper apprentice — produce a children's audiobook of his Salthouse-Dock morning, with Liverpool-shanty BGM.",
    "I have a portrait of a young 17th-c. Plymouth-Pilgrim-bound Mayflower-passenger — make a bedtime audiobook of her dock evening, with English-psalm BGM.",
    "Uploading a watercolor of a young 17th-c. Boston-Massachusetts-Bay-Colony cooper — build an illustrated children's tale of his Long-Wharf morning, with Bay-Psalm-Book BGM.",
    "Here's a digital portrait of a young 17th-c. Salem-fishing-shallop — render a kids' audiobook of her Marblehead-quay afternoon, with English-fiddle BGM.",
    "I'm sending you a sketch of a young 17th-c. Newport-Rhode-Island Quaker-merchant — produce a children's audiobook of his Long-Wharf morning, with Quaker-silence BGM.",
    "Uploading a portrait of a young 17th-c. New-Amsterdam-trader-girl — make a bedtime audiobook of her Wall-Street palisade evening, with Dutch-Calvinist-psalm BGM.",
    "Here's a watercolor of a young 17th-c. New-Sweden-Fort-Christina settler — build an illustrated children's tale of his Delaware-River morning, with Swedish-psalm BGM.",
    "I have a digital portrait of a young 17th-c. Quebec-City-Habitant-Champlain — render a kids' audiobook of his Place-Royale afternoon, with French-Catholic-chant BGM.",
    "Uploading a sketch of a young 17th-c. Halifax-Acadian fisher — produce a children's audiobook of her Mahone-Bay quay morning, with Acadian-fiddle BGM.",
    "Here's a portrait of a young 17th-c. Tortuga-buccaneer cabin-boy — make a bedtime audiobook of his Caribbean-bay afternoon, with buccaneer-shanty BGM.",
    "I'm sending you a watercolor of a young 17th-c. Port-Royal-Jamaica privateer — build an illustrated children's tale of his Cagway-Cove evening, with English-pirate-shanty BGM.",
    "Uploading a digital portrait of a young 17th-c. Veracruz-treasure-fleet pilot — render a kids' audiobook of his San-Juan-de-Ulúa fort, with Spanish-mestizo-folk BGM.",
    "Here's a sketch of a young 17th-c. Havana-galleon-bosun — produce a children's audiobook of his Morro-Castle afternoon, with Spanish-Habanero-folk BGM.",
    "I have a portrait of a young 17th-c. Cartagena-walls galley-quartermaster — make a bedtime audiobook of his Boca-Chica evening, with Cartagena-cumbia BGM.",
    "Uploading a watercolor of a young 17th-c. Lima-Callao-treasure-galleon clerk — build an illustrated children's tale of his Callao-quay morning, with Andean-Spanish-vihuela BGM.",
    "Here's a digital painting of a young 17th-c. Manila-Galleon-chartmaker — render a kids' audiobook of his Acapulco-fortress afternoon, with Manila-galleon-folk BGM.",
    "I'm sending you a sketch of a young 17th-c. Macao-Portuguese-Jesuit clerk — produce a children's audiobook of his Senado-Square afternoon, with Portuguese-fado-baroque BGM.",
    "Uploading a portrait of a young 17th-c. Goa-Portuguese-spice-merchant — make a bedtime audiobook of his Velha-Goa evening, with Goa-mando BGM.",
    "Here's a watercolor of a young 17th-c. Cochin-pepper-clerk — build an illustrated children's tale of her Mattancherry-warehouse morning, with Cochin-Carnatic BGM.",
    "I have a digital portrait of a young 17th-c. Surat-East-India-Company factor — render a kids' audiobook of his Surat-tower-walls afternoon, with Gujarati-folk BGM.",
    "Uploading a sketch of a young 17th-c. Madras-Fort-St-George clerk — produce a children's audiobook of her Black-Town morning, with Tamil-court-Carnatic BGM.",
    "Here's a portrait of a young 17th-c. Calcutta-Old-Mission-Church merchant — make a bedtime audiobook of his Hooghly-quay evening, with Bengali-baul BGM.",
    "I'm sending you a watercolor of a young 17th-c. Bombay-Fort-clerk — build an illustrated children's tale of his Bombay-Castle morning, with Marathi-court BGM.",
    "Uploading a digital portrait of a young 17th-c. Malacca-spice-shop apprentice — render a kids' audiobook of his Stadthuys-square afternoon, with Malay-keroncong BGM.",
    "Here's a sketch of a young 17th-c. Batavia-Kasteel clerk — produce a children's audiobook of her Pasar-Ikan morning, with Sundanese-folk BGM.",
    "I have a portrait of a young 17th-c. Banten-pepper-quay-loader — make a bedtime audiobook of his Karangantu-warehouse afternoon, with Banten-rampak-bedug BGM.",
    "Uploading a watercolor of a young 17th-c. Nagasaki-Dejima-VOC factor — build an illustrated children's tale of his Dejima-fan-shape walk, with Edo-shamisen BGM.",
    "Here's a digital painting of a young 17th-c. Hirado-shogunate-port boy — render a kids' audiobook of his Hirado-castle afternoon, with Hirado-min'yō BGM.",
    "I'm sending you a sketch of a young 17th-c. Macao-Senate-clerk — produce a children's audiobook of his Largo-do-Senado morning, with Macanese-Portuguese-folk BGM.",
    "Uploading a portrait of a young 17th-c. Manila-Parián-Chinese silk-trader — make a bedtime audiobook of her Parián-quarter afternoon, with Hokkien-yue-qin BGM.",
    "Here's a watercolor of a young 17th-c. Olinda-sugar-mill quay-loader — build an illustrated children's tale of his Recife-river-quay morning, with Pernambuco-frevo-baroque BGM.",
    "I have a digital portrait of a young 17th-c. Bahia-Salvador-tobacco-merchant — render a kids' audiobook of her Pelourinho-square afternoon, with Bahian-candomblé BGM.",
    "Uploading a sketch of a young 17th-c. Rio-de-Janeiro-Misericórdia-quay porter — produce a children's audiobook of his Castelo-Hill morning, with Brazilian-baroque-viola BGM.",
    "Here's a portrait of a young 17th-c. Buenos-Aires-fortín-cooper — make a bedtime audiobook of his Cabildo-square afternoon, with Argentine-baroque-vihuela BGM.",
    "I'm sending you a watercolor of a young 17th-c. Cape-Town-VOC-Castle clerk — build an illustrated children's tale of his Castle-of-Good-Hope morning, with Cape-Dutch-folk BGM.",
    "Uploading a digital portrait of a young 17th-c. Mauritius-Dutch-fortress carpenter — render a kids' audiobook of his Frederik-Hendrik bastion afternoon, with Mauritian-folk BGM.",
    "Here's a sketch of a young 17th-c. Mocha-coffee-warehouse weighman — produce a children's audiobook of his Red-Sea-quay morning, with Yemeni-oud BGM.",
    "I have a portrait of a young 17th-c. Massawa-Eritrean Ottoman clerk — make a bedtime audiobook of his coral-stone-quay evening, with Tigré-folk-2 BGM.",
    "Uploading a watercolor of a young 17th-c. Algiers-corsair-cabin-boy — build an illustrated children's tale of his Casbah-walls morning, with Algerian-Andalusian-classical BGM.",
    # ── more ancient Egyptian / Mesopotamian / classical-antiquity figures + BGM (50) ──
    "Here's a portrait of a young Old-Kingdom Egyptian-pyramid stonemason — make me a children's audiobook of his Giza-quarry morning, with Old-Kingdom-harp BGM.",
    "Uploading a sketch of a young Middle-Kingdom Egyptian-scribe — produce a kids' picture-book audiobook of his Lahun-temple afternoon, with Middle-Kingdom-flute BGM.",
    "I'm sending you a watercolor of a young New-Kingdom Theban-temple priestess — build an illustrated children's tale of her Karnak-pylon dawn, with New-Kingdom-sistrum BGM.",
    "Uploading a digital painting of a young Amarna-period royal-court attendant — make a bedtime audiobook of her Akhetaten-palace evening, with Amarna-lyre BGM.",
    "Here's a sketch of a young Saite-period Memphis-craftsman — render an illustrated children's audiobook of his temple-workshop morning, with Saite-double-pipe BGM.",
    "I have a portrait of a young Ptolemaic-Alexandria scholar — produce a children's audiobook of his Mouseion-library afternoon, with Ptolemaic-aulos BGM.",
    "Uploading a watercolor of a young Sumerian-Uruk temple-scribe — build an illustrated children's tale of her ziggurat-courtyard dawn, with Sumerian-lyre BGM.",
    "Here's a digital portrait of a young Old-Babylonian Mari-court diplomat — make a bedtime audiobook of his palace-archive afternoon, with Old-Babylonian-harp BGM.",
    "I'm sending you a portrait of a young Middle-Assyrian Ashur-temple acolyte — produce a children's audiobook of her Tigris-shore evening, with Middle-Assyrian-tigi-drum BGM.",
    "Uploading a sketch of a young Neo-Assyrian Nineveh-palace messenger — build an illustrated children's tale of his Khorsabad-relief afternoon, with Neo-Assyrian-bull-lyre BGM.",
    "Here's a watercolor of a young Neo-Babylonian Ishtar-Gate apprentice — render a kids' audiobook of her Processional-Way morning, with Neo-Babylonian-harp BGM.",
    "I have a digital painting of a young Achaemenid-Persepolis page — produce a children's audiobook of his Apadana-stair afternoon, with Achaemenid-tonbak BGM.",
    "Uploading a portrait of a young Achaemenid-Susa royal-road courier — make a bedtime audiobook of his desert-station evening, with Susa-flute BGM.",
    "Here's a sketch of a young Achaemenid-Pasargadae garden-attendant — build an illustrated children's tale of her paradise-garden dawn, with Pasargadae-chang-harp BGM.",
    "I'm sending you a watercolor of a young Achaemenid-Babylon court-translator — render a kids' audiobook of his Etemenanki-base afternoon, with Achaemenid-Babylon-lyre BGM.",
    "Uploading a digital portrait of a young Phoenician-Tyre dye-maker — produce a children's audiobook of her purple-dye-vat morning, with Phoenician-double-pipe BGM.",
    "Here's a portrait of a young Phoenician-Sidon shipwright — make a bedtime audiobook of his harbor-shipway afternoon, with Sidonian-lyre BGM.",
    "I have a sketch of a young Carthaginian-Tophet priestess — build an illustrated children's tale of her Byrsa-acropolis evening, with Carthaginian-tympanum BGM.",
    "Uploading a watercolor of a young Hittite-Hattusa courtier — render a kids' audiobook of his Lion-Gate afternoon, with Hittite-galgalturi-cymbals BGM.",
    "Here's a digital painting of a young Mitanni-Wassukanni horse-trainer — produce a children's audiobook of his royal-stable morning, with Mitanni-flute BGM.",
    "I'm sending you a portrait of a young Urartian-Tushpa fortress-scribe — make a bedtime audiobook of his Lake-Van-citadel evening, with Urartian-cymbal BGM.",
    "Uploading a sketch of a young Lydian-Sardis goldsmith-apprentice — build an illustrated children's tale of his Pactolus-river-bench afternoon, with Lydian-magadis-harp BGM.",
    "Here's a watercolor of a young Phrygian-Gordion king's-page — render a kids' audiobook of her megaron afternoon, with Phrygian-aulos BGM.",
    "I have a digital portrait of a young Mycenaean-Pylos palace-scribe — produce a children's audiobook of his Linear-B tablet-room afternoon, with Mycenaean-phorminx BGM.",
    "Uploading a portrait of a young Minoan-Knossos fresco-painter — make a bedtime audiobook of her bull-leaping-court evening, with Minoan-triton-shell BGM.",
    "Here's a sketch of a young Archaic-Greek Corinth-vase-painter — build an illustrated children's tale of his agora-workshop morning, with Archaic-Greek-aulos BGM.",
    "I'm sending you a watercolor of a young Athens-Solon-era ephebe — render a kids' audiobook of his Acropolis-stair afternoon, with Athenian-kithara BGM.",
    "Uploading a digital painting of a young Spartan-agoge candidate — produce a children's audiobook of his Eurotas-river dawn, with Spartan-elymos-pipe BGM.",
    "Here's a portrait of a young Theban-sacred-band recruit — make a bedtime audiobook of his Cadmea-citadel evening, with Theban-aulos BGM.",
    "I have a sketch of a young Alexandrian-Mouseion librarian — build an illustrated children's tale of her Pharos-light afternoon, with Alexandrian-hydraulis-organ BGM.",
    "Uploading a watercolor of a young Pergamene-Library copyist — render a kids' audiobook of her acropolis-terrace afternoon, with Pergamene-syrinx BGM.",
    "Here's a digital portrait of a young Antiochene-court attendant — produce a children's audiobook of his Orontes-bridge evening, with Antiochene-lyre BGM.",
    "I'm sending you a portrait of a young Seleucid-Babylon astronomer-trainee — make a bedtime audiobook of his ziggurat-rooftop dawn, with Seleucid-flute BGM.",
    "Uploading a sketch of a young Arsacid-Ctesiphon court-scribe — build an illustrated children's tale of his Tigris-pavilion afternoon, with Arsacid-tonbak BGM.",
    "Here's a watercolor of a young Sassanid-Ctesiphon palace-musician — render a kids' audiobook of her Taq-Kasra-arch afternoon, with Sassanid-chang-harp BGM.",
    "I have a digital painting of a young Etruscan-Veii haruspex-apprentice — produce a children's audiobook of his sacred-grove morning, with Etruscan-trumpet BGM.",
    "Uploading a portrait of a young Roman-Republic Cato-era senator's son — make a bedtime audiobook of his Forum-Romanum afternoon, with Roman-Republic-tibia BGM.",
    "Here's a sketch of a young Roman-Imperial Trajanic-forum scribe — build an illustrated children's tale of his Trajan's-Column-base afternoon, with Roman-Imperial-cornu BGM.",
    "I'm sending you a watercolor of a young Roman-Britain Vindolanda-fort scribe — render a kids' audiobook of his Hadrian's-Wall morning, with Roman-Britain-cornu BGM.",
    "Uploading a digital portrait of a young Roman-Egypt Oxyrhynchus-papyrus copyist — produce a children's audiobook of his Nile-canal afternoon, with Roman-Egypt-double-aulos BGM.",
    "Here's a portrait of a young Roman-Syria Palmyrene-caravan trader — make a bedtime audiobook of his desert-oasis evening, with Palmyrene-lyre BGM.",
    "I have a sketch of a young Nabataean-Petra-Treasury sculptor — build an illustrated children's tale of his rose-cliff dawn, with Nabataean-double-pipe BGM.",
    "Uploading a watercolor of a young Aksumite-Aksum stelai-mason — render a kids' audiobook of her stelae-park afternoon, with Aksumite-bagana-lyre BGM.",
    "Here's a digital painting of a young Meroitic-Meroe iron-smelter — produce a children's audiobook of his pyramid-field evening, with Meroitic-zummara BGM.",
    "I'm sending you a portrait of a young Garamantian-Saharan oasis-trader — make a bedtime audiobook of his Fezzan-oasis night, with Garamantian-tindi-drum BGM.",
    "Uploading a sketch of a young Iberian-Saguntum potter — build an illustrated children's tale of her hilltop-citadel afternoon, with Iberian-bone-flute BGM.",
    "Here's a watercolor of a young Celtiberian-Numantia warrior-youth — render a kids' audiobook of his Duero-river dawn, with Celtiberian-carnyx BGM.",
    "I have a digital portrait of a young Lusitanian-Conimbriga shepherd — produce a children's audiobook of his hill-meadow morning, with Lusitanian-pipe BGM.",
    "Uploading a portrait of a young Dacian-Sarmizegetusa fortress-scribe — make a bedtime audiobook of his sun-disk-temple evening, with Dacian-buccium-horn BGM.",
    "Here's a sketch of a young Thracian-Seuthopolis horseman — build an illustrated children's tale of his Tundzha-river afternoon, with Thracian-aulos BGM.",
    # ── more medieval Islamic Golden Age figures + BGM (50) ──
    "Uploading a portrait of a young 9th-c. Baghdad-House-of-Wisdom astronomer — make me a children's audiobook of his Bayt-al-Hikma rooftop morning, with Abbasid-oud BGM.",
    "Here's a sketch of a young 9th-c. Baghdad-House-of-Wisdom translator — produce a kids' picture-book audiobook of his manuscript-room afternoon, with Abbasid-ney BGM.",
    "I'm sending you a watercolor of a young 9th-c. Baghdad-Round-City-souq calligrapher — build an illustrated children's tale of his Karkh-souq morning, with Abbasid-tar BGM.",
    "Uploading a digital painting of a young 10th-c. Cordoba-Madinat-al-Zahra court-poet — render a kids' audiobook of his Caliph's-garden afternoon, with Andalusi-classical BGM.",
    "Here's a portrait of a young 10th-c. Cordoba-Mezquita illuminator — make a bedtime audiobook of his prayer-hall dawn, with Cordoba-muwashshah BGM.",
    "I have a sketch of a young 10th-c. Cordoba-Andalusi mathematician — produce a children's audiobook of his Madinat-al-Zahra-courtyard afternoon, with Andalusi-zajal BGM.",
    "Uploading a watercolor of a young 11th-c. Cairo-Fatimid-Al-Azhar student — build an illustrated children's tale of his Al-Azhar-courtyard dawn, with Fatimid-qanun BGM.",
    "Here's a digital portrait of a young 11th-c. Cairo-Fatimid Imperial-court astronomer — render a kids' audiobook of his Mokattam-rooftop afternoon, with Fatimid-takht BGM.",
    "I'm sending you a portrait of a young 11th-c. Damascus-Umayyad-Mosque-Library scribe — produce a children's audiobook of her Salahiyah-quarter afternoon, with Damascus-muwashshah-2 BGM.",
    "Uploading a sketch of a young 11th-c. Aleppo-Ayyubid-citadel armorer — build an illustrated children's tale of his citadel-forge afternoon, with Aleppo-qudud-halabiya-2 BGM.",
    "Here's a watercolor of a young 11th-c. Bukhara-Samanid-Library binder — render a kids' audiobook of her Ismail-Samani-tomb afternoon, with Samanid-rubab BGM.",
    "I have a digital painting of a young 11th-c. Samarkand-Ulugh-Beg-precursor astronomer — produce a children's audiobook of his madrassa-rooftop dawn, with Samarkand-shashmaqam-precursor BGM.",
    "Uploading a portrait of a young 11th-c. Cairo-Geniza Karaite-scribe — make a bedtime audiobook of her Ben-Ezra-synagogue afternoon, with Cairo-Geniza-piyyut BGM.",
    "Here's a sketch of a young 11th-c. Kairouan-Aghlabid-Mosque illuminator — build an illustrated children's tale of his Kairouan-mihrab afternoon, with Kairouan-malouf BGM.",
    "I'm sending you a watercolor of a young 11th-c. Tunis-Zaytuna-Mosque student — render a kids' audiobook of his Zaytuna-courtyard morning, with Tunis-malouf BGM.",
    "Uploading a digital portrait of a young 11th-c. Marrakesh-Almoravid-court calligrapher — produce a children's audiobook of his Almoravid-Qubba afternoon, with Almoravid-andalusi BGM.",
    "Here's a portrait of a young 11th-c. Sicily-Norman-Palermo Sicilian-Arab translator — make a bedtime audiobook of her Cappella-Palatina dawn, with Sicilian-Arab-canzone BGM.",
    "I have a sketch of a young 12th-c. Toledo-School-of-Translators Mozarab-scribe — build an illustrated children's tale of his Toledo-Tagus-bridge afternoon, with Mozarabic-cantiga BGM.",
    "Uploading a watercolor of a young 12th-c. Granada-Alhambra-precursor poet — render a kids' audiobook of his Albayzín-quarter dawn, with Granada-zambra BGM.",
    "Here's a digital painting of a young 12th-c. Seville-Almohad-court astronomer — produce a children's audiobook of his Giralda-precursor-tower afternoon, with Almohad-nuba BGM.",
    "I'm sending you a portrait of a young 12th-c. Fes-Quaraouiyine-University student — make a bedtime audiobook of her Quaraouiyine-courtyard afternoon, with Fes-Andalusi-nawba BGM.",
    "Uploading a sketch of a young 12th-c. Marrakesh-Koutoubia-Mosque calligrapher — build an illustrated children's tale of his minaret-rooftop dawn, with Marrakesh-Gnawa-precursor BGM.",
    "Here's a watercolor of a young 12th-c. Damascus-Bimaristan-Nuri physician's apprentice — render a kids' audiobook of his hospital-courtyard morning, with Damascus-takht-2 BGM.",
    "I have a digital portrait of a young 12th-c. Aleppo-Citadel-throne-room courtier — produce a children's audiobook of his Ayyubid-throne-room afternoon, with Ayyubid-Aleppo-qudud BGM.",
    "Uploading a portrait of a young 12th-c. Mosul-Atabeg-court metalworker — make a bedtime audiobook of his Mosul-souq evening, with Iraqi-maqam-Mosul BGM.",
    "Here's a sketch of a young 12th-c. Konya-Seljuk-Sultan-court tile-painter — build an illustrated children's tale of his Mevlana-precursor-courtyard afternoon, with Seljuk-Konya-saz BGM.",
    "I'm sending you a watercolor of a young 12th-c. Konya-Karatay-Madrasa student — render a kids' audiobook of his Karatay-madrasa-courtyard morning, with Seljuk-ney-2 BGM.",
    "Uploading a digital painting of a young 13th-c. Baghdad-Mustansiriya-Madrasa student — produce a children's audiobook of his Tigris-quay afternoon, with Mustansiriya-maqam BGM.",
    "Here's a portrait of a young 13th-c. Granada-Madinat-al-Hamra-Alhambra fountain-engineer — make a bedtime audiobook of his Lion-Court evening, with Alhambra-nawba BGM.",
    "I have a sketch of a young 13th-c. Granada-Generalife-gardens gardener — build an illustrated children's tale of her Generalife-aqueduct afternoon, with Generalife-Andalusi BGM.",
    "Uploading a watercolor of a young 13th-c. Cairo-Mamluk-Sultan-Hassan-Madrasa student — render a kids' audiobook of his Sultan-Hassan-courtyard morning, with Mamluk-Cairo-takht BGM.",
    "Here's a digital portrait of a young 13th-c. Cairo-Mamluk-Khan-al-Khalili silver-merchant — produce a children's audiobook of his souq-stall afternoon, with Mamluk-Khan-al-Khalili-mawwal BGM.",
    "I'm sending you a portrait of a young 13th-c. Damascus-Saladin-tomb tile-mosaicist — make a bedtime audiobook of his tomb-courtyard evening, with Damascus-Saladin-muwashshah BGM.",
    "Uploading a sketch of a young 13th-c. Tabriz-Ilkhanid-court manuscript-illuminator — build an illustrated children's tale of his Rab'-i-Rashidi afternoon, with Ilkhanid-Tabriz-tar BGM.",
    "Here's a watercolor of a young 13th-c. Maragheh-Ilkhanid-Observatory star-cataloger — render a kids' audiobook of his Maragheh-Observatory rooftop dawn, with Maragheh-radif BGM.",
    "I have a digital painting of a young 13th-c. Konya-Mevlevi-lodge whirling-dervish-novice — produce a children's audiobook of his Mevlana-tomb-courtyard afternoon, with Mevlevi-sema-ney BGM.",
    "Uploading a portrait of a young 13th-c. Bursa-Ottoman-precursor tile-painter — make a bedtime audiobook of his Bursa-Green-Mosque-precursor evening, with Bursa-Ottoman-precursor-tanbur BGM.",
    "Here's a sketch of a young 13th-c. Sana'a-Yemen-Old-Walled-City Quranic-scholar — build an illustrated children's tale of his Bab-al-Yemen morning, with Yemeni-oud-2 BGM.",
    "I'm sending you a watercolor of a young 14th-c. Granada-Comares-Hall stucco-carver — render a kids' audiobook of her Comares-Hall-rooftop afternoon, with Granada-zambra-2 BGM.",
    "Uploading a digital portrait of a young 14th-c. Fes-Bou-Inania-Madrasa student — produce a children's audiobook of his Bou-Inania-courtyard morning, with Fes-Bou-Inania-Andalusi BGM.",
    "Here's a portrait of a young 14th-c. Tlemcen-Zayyanid-court calligrapher — make a bedtime audiobook of his Mansourah-mosque evening, with Tlemcen-Zayyanid-nuba BGM.",
    "I have a sketch of a young 14th-c. Cairo-Mamluk-Citadel court-poet — build an illustrated children's tale of his Citadel-stable afternoon, with Mamluk-Citadel-muwashshah BGM.",
    "Uploading a watercolor of a young 14th-c. Jerusalem-Mamluk-Aqsa tile-mosaicist — render a kids' audiobook of his Dome-of-the-Rock-precursor afternoon, with Mamluk-Jerusalem-muwashshah BGM.",
    "Here's a digital painting of a young 14th-c. Damascus-Umayyad-Mosque mosaic-restorer — produce a children's audiobook of his prayer-hall morning, with Mamluk-Damascus-takht BGM.",
    "I'm sending you a portrait of a young 14th-c. Samarkand-Bibi-Khanym-precursor mason — make a bedtime audiobook of his Bibi-Khanym-yard afternoon, with Timurid-Samarkand-shashmaqam BGM.",
    "Uploading a sketch of a young 14th-c. Bukhara-Mir-i-Arab-precursor calligrapher — build an illustrated children's tale of her madrassa-courtyard dawn, with Timurid-Bukhara-falak BGM.",
    "Here's a watercolor of a young 14th-c. Kashan-Safavid-precursor lustreware-potter — render a kids' audiobook of his kiln-yard afternoon, with Kashan-Persian-radif BGM.",
    "I have a digital portrait of a young 15th-c. Tabriz-Aq-Qoyunlu-court miniaturist — produce a children's audiobook of his royal-atelier morning, with Aq-Qoyunlu-Tabriz-tar BGM.",
    "Uploading a portrait of a young 15th-c. Herat-Timurid-court Bihzad-school-painter — make a bedtime audiobook of his madrasa-atelier afternoon, with Herat-Timurid-radif BGM.",
    "Here's a sketch of a young 15th-c. Samarkand-Ulugh-Beg-Madrasa student — build an illustrated children's tale of his Registan-courtyard morning, with Samarkand-Ulugh-Beg-shashmaqam BGM.",
    # ── more Renaissance / Baroque painter & sculptor apprentices + BGM (50) ──
    "Uploading a portrait of a young 15th-c. Florence-Verrocchio-bottega apprentice — make me a children's audiobook of his Florence-bottega-atelier afternoon, with Florentine-Renaissance-lute-3 BGM.",
    "Here's a sketch of a young 15th-c. Florence-Brunelleschi-Duomo-foreman's-son — produce a kids' picture-book audiobook of his Duomo-cupola morning, with Florentine-Duomo-organ BGM.",
    "I'm sending you a watercolor of a young 15th-c. Florence-Donatello-bottega apprentice — build an illustrated children's tale of his Cathedral-piazza afternoon, with Florentine-shawm BGM.",
    "Uploading a digital painting of a young 15th-c. Florence-Ghirlandaio-bottega apprentice — render a kids' audiobook of his Tornabuoni-Chapel morning, with Florentine-Tornabuoni-organ BGM.",
    "Here's a portrait of a young 15th-c. Florence-Botticelli-bottega apprentice — make a bedtime audiobook of his Medici-Garden-of-San-Marco afternoon, with Florentine-Medici-lute BGM.",
    "I have a sketch of a young 15th-c. Florence-Leonardo-da-Vinci-Verrocchio-pupil — produce a children's audiobook of his Verrocchio-bottega-baptism-of-Christ afternoon, with Florentine-Verrocchio-lute BGM.",
    "Uploading a watercolor of a young 15th-c. Urbino-Piero-della-Francesca-bottega apprentice — build an illustrated children's tale of his Palazzo-Ducale-Urbino-courtyard afternoon, with Urbino-Renaissance-strings BGM.",
    "Here's a digital portrait of a young 15th-c. Mantua-Mantegna-bottega apprentice — render a kids' audiobook of his Camera-degli-Sposi-fresco morning, with Mantua-Gonzaga-strings BGM.",
    "I'm sending you a portrait of a young 15th-c. Padua-Donatello-Gattamelata-foundry apprentice — produce a children's audiobook of his Padua-bronze-foundry afternoon, with Padua-foundry-percussion BGM.",
    "Uploading a sketch of a young 15th-c. Venice-Bellini-bottega apprentice — build an illustrated children's tale of his San-Marco-altar afternoon, with Venice-San-Marco-organ BGM.",
    "Here's a watercolor of a young 15th-c. Venice-Carpaccio-bottega apprentice — render a kids' audiobook of his Scuola-di-San-Giorgio afternoon, with Venice-Scuola-strings BGM.",
    "I have a digital painting of a young 15th-c. Milan-Sforza-Court-Foppa-bottega apprentice — produce a children's audiobook of his Castello-Sforzesco afternoon, with Milan-Sforza-court-strings BGM.",
    "Uploading a portrait of a young 16th-c. Florence-Michelangelo-Ghirlandaio-pupil — make a bedtime audiobook of his Settignano-quarry morning, with Florentine-quarry-stonemason BGM.",
    "Here's a sketch of a young 16th-c. Rome-Raphael-Stanze-pupil — build an illustrated children's tale of his Vatican-Stanze-fresco afternoon, with Vatican-Stanze-organ BGM.",
    "I'm sending you a watercolor of a young 16th-c. Venice-Titian-bottega apprentice — render a kids' audiobook of his San-Lio-bottega-grinding-pigment morning, with Venice-Titian-lute BGM.",
    "Uploading a digital portrait of a young 16th-c. Venice-Tintoretto-bottega apprentice — produce a children's audiobook of his Madonna-dell'Orto-altar afternoon, with Venice-Tintoretto-organ BGM.",
    "Here's a portrait of a young 16th-c. Venice-Veronese-bottega apprentice — make a bedtime audiobook of his Doge's-Palace afternoon, with Venice-Veronese-strings BGM.",
    "I have a sketch of a young 16th-c. Florence-Pontormo-bottega apprentice — build an illustrated children's tale of his Certosa-del-Galluzzo afternoon, with Florentine-Pontormo-organ BGM.",
    "Uploading a watercolor of a young 16th-c. Florence-Bronzino-bottega apprentice — render a kids' audiobook of his Palazzo-Vecchio-Eleonora-chapel afternoon, with Florentine-Eleonora-strings BGM.",
    "Here's a digital painting of a young 16th-c. Cremona-Sofonisba-Anguissola-pupil — produce a children's audiobook of her Cremona-court-painting afternoon, with Cremona-violin-precursor BGM.",
    "I'm sending you a portrait of a young 16th-c. Bologna-Carracci-Accademia apprentice — make a bedtime audiobook of his Bologna-Accademia-degli-Incamminati morning, with Bologna-Carracci-strings BGM.",
    "Uploading a sketch of a young 16th-c. Parma-Correggio-bottega apprentice — build an illustrated children's tale of his Parma-Cathedral-cupola afternoon, with Parma-Correggio-organ BGM.",
    "Here's a watercolor of a young 16th-c. Antwerp-Quentin-Matsys-bottega apprentice — render a kids' audiobook of his Antwerp-Cathedral afternoon, with Antwerp-Cathedral-organ BGM.",
    "I have a digital portrait of a young 16th-c. Antwerp-Pieter-Bruegel-the-Elder-bottega apprentice — produce a children's audiobook of his Antwerp-Coecke-van-Aelst-bottega afternoon, with Antwerp-Bruegel-lute BGM.",
    "Uploading a portrait of a young 16th-c. Nuremberg-Dürer-Werkstatt apprentice — make a bedtime audiobook of his Nuremberg-Burg-Garten afternoon, with Nuremberg-Dürer-organ BGM.",
    "Here's a sketch of a young 16th-c. Wittenberg-Cranach-bottega apprentice — build an illustrated children's tale of his Wittenberg-marketplace-shop afternoon, with Wittenberg-Cranach-organ BGM.",
    "I'm sending you a watercolor of a young 16th-c. Augsburg-Holbein-bottega apprentice — render a kids' audiobook of his Augsburg-Fugger-Chapel afternoon, with Augsburg-Holbein-organ BGM.",
    "Uploading a digital portrait of a young 16th-c. Toledo-El-Greco-bottega apprentice — produce a children's audiobook of his Santo-Tomé-Toledo afternoon, with Toledo-El-Greco-organ BGM.",
    "Here's a portrait of a young 17th-c. Rome-Caravaggio-bottega apprentice — make a bedtime audiobook of his Cerasi-Chapel afternoon, with Rome-Caravaggio-organ BGM.",
    "I have a sketch of a young 17th-c. Rome-Bernini-atelier apprentice — build an illustrated children's tale of his Piazza-Navona-fountain afternoon, with Rome-Bernini-strings BGM.",
    "Uploading a watercolor of a young 17th-c. Rome-Borromini-atelier apprentice — render a kids' audiobook of his Sant'Ivo-alla-Sapienza-cupola afternoon, with Rome-Borromini-organ BGM.",
    "Here's a digital painting of a young 17th-c. Naples-Artemisia-Gentileschi-bottega apprentice — produce a children's audiobook of her Pio-Monte-altar afternoon, with Naples-Artemisia-strings BGM.",
    "I'm sending you a portrait of a young 17th-c. Bologna-Guido-Reni-bottega apprentice — make a bedtime audiobook of his Bologna-Pinacoteca afternoon, with Bologna-Guido-Reni-organ BGM.",
    "Uploading a sketch of a young 17th-c. Antwerp-Rubens-Werkstatt apprentice — build an illustrated children's tale of his Rubenshuis-courtyard morning, with Antwerp-Rubens-organ BGM.",
    "Here's a watercolor of a young 17th-c. Antwerp-Van-Dyck-Rubens-pupil — render a kids' audiobook of his Antwerp-Cathedral afternoon, with Antwerp-Van-Dyck-organ BGM.",
    "I have a digital portrait of a young 17th-c. Antwerp-Jordaens-bottega apprentice — produce a children's audiobook of his Antwerp-Vlaeykensgang afternoon, with Antwerp-Jordaens-strings BGM.",
    "Uploading a portrait of a young 17th-c. Madrid-Velázquez-Court-bottega apprentice — make a bedtime audiobook of his Alcázar-Madrid afternoon, with Madrid-Velázquez-strings BGM.",
    "Here's a sketch of a young 17th-c. Seville-Murillo-bottega apprentice — build an illustrated children's tale of his Sevilla-Hospital-de-la-Caridad afternoon, with Sevilla-Murillo-organ BGM.",
    "I'm sending you a watercolor of a young 17th-c. Seville-Zurbarán-bottega apprentice — render a kids' audiobook of his Cartuja-de-Sevilla afternoon, with Sevilla-Zurbarán-organ BGM.",
    "Uploading a digital painting of a young 17th-c. Amsterdam-Rembrandt-Werkstatt apprentice — produce a children's audiobook of his Rembrandtshuis-Jodenbreestraat afternoon, with Amsterdam-Rembrandt-organ BGM.",
    "Here's a portrait of a young 17th-c. Delft-Vermeer-bottega-only-son — make a bedtime audiobook of his Delft-Mechelen-inn afternoon, with Delft-Vermeer-virginal BGM.",
    "I have a sketch of a young 17th-c. Delft-Carel-Fabritius-Rembrandt-pupil — build an illustrated children's tale of his Delft-Markt afternoon, with Delft-Fabritius-virginal BGM.",
    "Uploading a watercolor of a young 17th-c. Haarlem-Frans-Hals-Werkstatt apprentice — render a kids' audiobook of his Haarlem-Sint-Bavo-cathedral afternoon, with Haarlem-Frans-Hals-organ BGM.",
    "Here's a digital portrait of a young 17th-c. Haarlem-Judith-Leyster-Frans-Hals-pupil — produce a children's audiobook of her Haarlem-bottega afternoon, with Haarlem-Leyster-virginal BGM.",
    "I'm sending you a portrait of a young 17th-c. Leiden-Jan-Steen-bottega apprentice — make a bedtime audiobook of his Leiden-Pieterskerk afternoon, with Leiden-Jan-Steen-organ BGM.",
    "Uploading a sketch of a young 17th-c. Paris-Poussin-bottega apprentice — build an illustrated children's tale of his Paris-Île-de-la-Cité afternoon, with Paris-Poussin-baroque BGM.",
    "Here's a watercolor of a young 17th-c. Paris-Le-Nain-brothers-bottega apprentice — render a kids' audiobook of his Paris-Quai-d'Orléans afternoon, with Paris-Le-Nain-baroque BGM.",
    "I have a digital painting of a young 17th-c. London-Anthony-van-Dyck-court-bottega apprentice — produce a children's audiobook of his Whitehall-Banqueting-House afternoon, with London-Van-Dyck-court-strings BGM.",
    "Uploading a portrait of a young 17th-c. London-Peter-Lely-bottega apprentice — make a bedtime audiobook of his Whitehall-Royal-Apartments afternoon, with London-Lely-court-strings BGM.",
    "Here's a sketch of a young 17th-c. London-Godfrey-Kneller-bottega apprentice — build an illustrated children's tale of his Kit-Kat-Club afternoon, with London-Kneller-court-strings BGM.",
    # ── more Han dynasty scholars + BGM (50) ──
    "I have a portrait of a young Han-Chang'an-Imperial-Academy-Taixue student — produce a children's audiobook of his Chang'an-Weiyang-Palace afternoon, with Chang'an-Han-court-guqin BGM.",
    "Uploading a watercolor of a young Han-Luoyang-Eastern-Han-Imperial-Academy student — make a bedtime audiobook of his Luoyang-Lingtai-observatory afternoon, with Luoyang-Han-court-guqin BGM.",
    "Here's a digital painting of a young Han-Sima-Qian-Shiji-historian-apprentice — render a kids' audiobook of his Chang'an-Imperial-Archives afternoon, with Han-Sima-Qian-Shiji-guqin BGM.",
    "I'm sending you a portrait of a young Han-Ban-Gu-Hanshu-historian-apprentice — produce a children's audiobook of his Luoyang-Imperial-Library afternoon, with Han-Ban-Gu-Hanshu-guqin BGM.",
    "Uploading a sketch of a young Han-Cai-Lun-papermaker apprentice — build an illustrated children's tale of his Luoyang-paper-workshop afternoon, with Han-Luoyang-paper-workshop-guqin BGM.",
    "Here's a watercolor of a young Han-Zhang-Heng-astronomer apprentice — render a kids' audiobook of his Luoyang-armillary-sphere-workshop afternoon, with Han-Zhang-Heng-armillary-guqin BGM.",
    "I have a digital portrait of a young Han-Zhang-Zhongjing-physician apprentice — produce a children's audiobook of his Nanyang-medicinal-garden afternoon, with Han-Zhang-Zhongjing-Nanyang-guqin BGM.",
    "Uploading a portrait of a young Han-Hua-Tuo-surgeon apprentice — make a bedtime audiobook of his Bo-County-medical-clinic afternoon, with Han-Hua-Tuo-Bo-County-guqin BGM.",
    "Here's a sketch of a young Han-Dong-Zhongshu-Confucian-scholar apprentice — build an illustrated children's tale of his Chang'an-Confucian-academy afternoon, with Han-Dong-Zhongshu-Confucian-guqin BGM.",
    "I'm sending you a watercolor of a young Han-Liu-An-Huainanzi-philosopher apprentice — render a kids' audiobook of his Huainan-prince-court afternoon, with Han-Liu-An-Huainan-guqin BGM.",
    "Uploading a digital painting of a young Han-Wang-Chong-Lunheng-philosopher apprentice — produce a children's audiobook of his Shangyu-Kuaiji-thatched-hut afternoon, with Han-Wang-Chong-Shangyu-guqin BGM.",
    "Here's a portrait of a young Han-Yang-Xiong-Shujing-philologist apprentice — make a bedtime audiobook of his Chang'an-Imperial-Library afternoon, with Han-Yang-Xiong-Chang'an-guqin BGM.",
    "I have a sketch of a young Han-Liu-Xiang-bibliographer apprentice — build an illustrated children's tale of his Chang'an-Stone-Canal-Pavilion afternoon, with Han-Liu-Xiang-Stone-Canal-guqin BGM.",
    "Uploading a watercolor of a young Han-Zheng-Xuan-classicist-commentator apprentice — render a kids' audiobook of his Beihai-classics-school afternoon, with Han-Zheng-Xuan-Beihai-guqin BGM.",
    "Here's a digital portrait of a young Han-Xu-Shen-Shuowen-Jiezi-philologist apprentice — produce a children's audiobook of his Yancheng-philology-bureau afternoon, with Han-Xu-Shen-Yancheng-guqin BGM.",
    "I'm sending you a portrait of a young Han-Liu-Xin-bibliographer apprentice — make a bedtime audiobook of his Chang'an-Tianlu-Pavilion afternoon, with Han-Liu-Xin-Tianlu-guqin BGM.",
    "Uploading a sketch of a young Han-Sima-Xiangru-Han-fu-poet apprentice — build an illustrated children's tale of his Chengdu-Linqiong-courtyard afternoon, with Han-Sima-Xiangru-Chengdu-guqin BGM.",
    "Here's a watercolor of a young Han-Mei-Cheng-Han-fu-poet apprentice — render a kids' audiobook of his Wu-Yangzhou-grove afternoon, with Han-Mei-Cheng-Wu-Yangzhou-guqin BGM.",
    "I have a digital painting of a young Han-Zhang-Qian-envoy apprentice — produce a children's audiobook of his Chang'an-imperial-envoy-bureau afternoon, with Han-Zhang-Qian-Western-Regions-pipa BGM.",
    "Uploading a portrait of a young Han-Ban-Chao-Western-Regions-protector apprentice — make a bedtime audiobook of his Shule-frontier-garrison afternoon, with Han-Ban-Chao-Shule-pipa BGM.",
    "Here's a sketch of a young Han-Su-Wu-imperial-envoy apprentice — build an illustrated children's tale of his Chang'an-imperial-court afternoon, with Han-Su-Wu-Xiongnu-suo-na BGM.",
    "I'm sending you a portrait of a young Han-Huo-Qubing-young-general apprentice — render a kids' audiobook of his Chang'an-Wei-Qing-camp afternoon, with Han-Huo-Qubing-Wei-Qing-suona BGM.",
    "Uploading a watercolor of a young Han-Wei-Qing-young-general apprentice — produce a children's audiobook of his Hexi-Corridor-camp afternoon, with Han-Wei-Qing-Hexi-suona BGM.",
    "Here's a digital portrait of a young Han-Li-Guang-young-archer apprentice — make a bedtime audiobook of his Longxi-frontier-camp afternoon, with Han-Li-Guang-Longxi-suona BGM.",
    "I have a sketch of a young Han-Cao-Cao-young-Wei-prince scribe-boy — build an illustrated children's tale of his Xuchang-court afternoon, with Han-Cao-Cao-Xuchang-guqin BGM.",
    "Uploading a portrait of a young Han-Liu-Bei-Shu-prince scribe-boy — render a kids' audiobook of his Zhuojun-Lu-Zhi-school afternoon, with Han-Liu-Bei-Zhuojun-guqin BGM.",
    "Here's a watercolor of a young Han-Sun-Quan-Wu-prince scribe-boy — produce a children's audiobook of his Wu-Jianye-court afternoon, with Han-Sun-Quan-Jianye-guqin BGM.",
    "I'm sending you a digital painting of a young Han-Zhuge-Liang-young-strategist scribe — make a bedtime audiobook of his Nanyang-Wolong-Mountain afternoon, with Han-Zhuge-Liang-Wolong-guqin BGM.",
    "Uploading a sketch of a young Han-Pang-Tong-young-strategist scribe — build an illustrated children's tale of his Xiangyang-Lu-Zhi-school afternoon, with Han-Pang-Tong-Xiangyang-guqin BGM.",
    "Here's a portrait of a young Han-Sima-Yi-Wei-prince scribe — render a kids' audiobook of his Henei-Wenxian-courtyard afternoon, with Han-Sima-Yi-Henei-guqin BGM.",
    "I have a watercolor of a young Han-Zhou-Yu-young-general scribe — produce a children's audiobook of his Lujiang-Zhoushi-courtyard afternoon, with Han-Zhou-Yu-Lujiang-guqin BGM.",
    "Uploading a digital portrait of a young Han-Lu-Su-Wu-strategist scribe — make a bedtime audiobook of his Linhuai-Dongchengxian afternoon, with Han-Lu-Su-Linhuai-guqin BGM.",
    "Here's a sketch of a young Han-Lu-Xun-Wu-strategist scribe — build an illustrated children's tale of his Wu-Yangxian afternoon, with Han-Lu-Xun-Wu-Yangxian-guqin BGM.",
    "I'm sending you a portrait of a young Han-Guan-Yu-young-warrior scribe — render a kids' audiobook of his Hedong-Jiezhou-bottega afternoon, with Han-Guan-Yu-Hedong-suona BGM.",
    "Uploading a watercolor of a young Han-Zhang-Fei-young-warrior scribe — produce a children's audiobook of his Zhuojun-butcher-shop afternoon, with Han-Zhang-Fei-Zhuojun-suona BGM.",
    "Here's a digital painting of a young Han-Zhao-Yun-young-warrior scribe — make a bedtime audiobook of his Changshan-Zhending afternoon, with Han-Zhao-Yun-Changshan-suona BGM.",
    "I have a sketch of a young Han-Ma-Chao-young-warrior scribe — build an illustrated children's tale of his Fufeng-Maolingxian afternoon, with Han-Ma-Chao-Fufeng-suona BGM.",
    "Uploading a portrait of a young Han-Lu-Bu-young-warrior scribe — render a kids' audiobook of his Wuyuan-Jiuyuanxian afternoon, with Han-Lu-Bu-Wuyuan-suona BGM.",
    "Here's a watercolor of a young Han-Yuan-Shao-young-aristocrat scribe — produce a children's audiobook of his Runan-Yuanshi-courtyard afternoon, with Han-Yuan-Shao-Runan-guqin BGM.",
    "I'm sending you a digital portrait of a young Han-Liu-Biao-Jingzhou-governor's-son scribe — make a bedtime audiobook of his Xiangyang-court afternoon, with Han-Liu-Biao-Xiangyang-guqin BGM.",
    "Uploading a sketch of a young Han-Yuan-Shu-young-aristocrat scribe — build an illustrated children's tale of his Runan-Yuanshi-courtyard afternoon, with Han-Yuan-Shu-Runan-guqin BGM.",
    "Here's a portrait of a young Han-Cao-Pi-Wei-prince scribe — render a kids' audiobook of his Yexian-Wei-court afternoon, with Han-Cao-Pi-Yexian-guqin BGM.",
    "I have a watercolor of a young Han-Cao-Zhi-Wei-prince scribe — produce a children's audiobook of his Yexian-Wei-Tongque-Tai afternoon, with Han-Cao-Zhi-Tongque-guqin BGM.",
    "Uploading a digital painting of a young Han-Cao-Chong-Wei-prince scribe — make a bedtime audiobook of his Xuchang-Wei-court afternoon, with Han-Cao-Chong-Xuchang-guqin BGM.",
    "Here's a sketch of a young Han-Sun-Ce-Wu-young-general scribe — build an illustrated children's tale of his Lujiang-Sun-courtyard afternoon, with Han-Sun-Ce-Lujiang-guqin BGM.",
    "I'm sending you a portrait of a young Han-Sun-Shang-Xiang-Wu-princess scribe — render a kids' audiobook of her Wu-Jianye-court afternoon, with Han-Sun-Shang-Xiang-Jianye-guqin BGM.",
    "Uploading a watercolor of a young Han-Zhang-Liang-young-strategist scribe — produce a children's audiobook of his Bo-County-Yi-school afternoon, with Han-Zhang-Liang-Bo-County-guqin BGM.",
    "Here's a digital portrait of a young Han-Xiao-He-young-bureaucrat scribe — make a bedtime audiobook of his Pei-County-Xiao-court afternoon, with Han-Xiao-He-Pei-County-guqin BGM.",
    "I have a sketch of a young Han-Han-Xin-young-general scribe — build an illustrated children's tale of his Huaiyin-Han-court afternoon, with Han-Han-Xin-Huaiyin-suona BGM.",
    "Uploading a portrait of a young Han-Liu-Bang-young-village-chief scribe — render a kids' audiobook of his Pei-County-village-court afternoon, with Han-Liu-Bang-Pei-County-suona BGM.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
