"""x15 highlight_only SFT short briefs.

Chain: IntakeVideo → VideoAnalysis → Highlight (raw cut segments output).
Trigger: user uploads a LONG source video and wants the highlight clips
extracted. NO music, NO ambience, NO subtitles, NO compositor.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 90-minute youth basketball game tape — please pull the top highlight clips for me.",
    "Here's a 2-hour wedding reception video — extract the best moments as highlight clips.",
    "I've got a 3-hour fishing-tournament livestream — please pull the most exciting catches as highlights.",
    "Uploading a 45-minute high-school soccer match — extract the highlight clips.",
    "Here's a 90-minute esports tournament VOD — please pull the best clutch moments.",
    "I have a 4-hour family vacation video from Yellowstone — give me the highlight clips.",
    "Uploading a 2-hour live concert recording — please extract the standout performances.",
    "Here's a 3-hour Magic: the Gathering tournament VOD — pull the key game-winning moments.",
    "I'm sending you an 80-minute kids' birthday party video — extract the highlight moments.",
    "Uploading a 6-hour first-person mountain climb GoPro — please pull the most dramatic sections.",
    "Here's a 90-minute corporate all-hands recording — extract the highlight clips of key announcements.",
    "I have a 2.5-hour college lecture — please pull the most-quoted highlight clips.",
    "Uploading a 3-hour livestream of my Twitch playthrough — pull the best gaming moments.",
    "Here's a 4-hour endurance bike race recording — extract the highlight clips.",
    "I'm sending you a 90-minute karaoke night recording — please pull the best performance highlights.",
    "Uploading a 2-hour stand-up comedy show recording — extract the highlight bits.",
    "Here's a 5-hour wedding video — please pull the top highlight moments as clips.",
    "I have a 90-minute baseball game recording — extract the home runs and big plays.",
    "Uploading a 2-hour ice hockey tournament — pull the highlight goals as clips.",
    "Here's a 4-hour D&D campaign recording — please extract the key dramatic moments.",
    "I'm sending you a 90-minute amateur boxing match — pull the highlight knockdowns.",
    "Uploading a 2-hour open-mic poetry slam — please extract the highlight performances.",
    "Here's a 3-hour MMA cage fights compilation tape — pull the top knockout moments.",
    "I have a 4-hour kart racing event — please extract the highlight overtakes.",
    "Uploading a 90-minute jazz festival recording — pull the highlight solos.",
    "Here's a 2-hour spelling bee final — please extract the highlight word moments.",
    "I'm sending you a 3-hour cooking competition show — pull the highlight plating moments.",
    "Uploading a 5-hour livestream of my marathon swim — extract the highlight stretches.",
    "Here's a 90-minute high-school graduation ceremony — please pull the highlight speeches.",
    "I have a 2-hour soccer-team awards banquet — extract the highlight award moments.",
    "Uploading a 4-hour gymnastics meet — please pull the highlight routines.",
    "Here's a 3-hour debate-team finals — extract the highlight argument exchanges.",
    "I'm sending you a 90-minute amateur darts tournament — pull the highlight checkouts.",
    "Uploading a 2-hour surf competition livestream — extract the highlight rides.",
    "Here's a 4-hour tennis double's tournament — please pull the highlight points.",
    "I have a 2.5-hour rodeo event — extract the highlight bull rides.",
    "Uploading a 3-hour mountain bike enduro race — pull the highlight descents.",
    "Here's a 5-hour fishing-charter livestream — please extract the highlight catches.",
    "I'm sending you a 2-hour Quidditch tournament — pull the highlight Snitch moments.",
    "Uploading a 90-minute church service recording — extract the highlight worship moments.",
    "Here's a 4-hour synchronized swimming meet — please pull the highlight routines.",
    "I have a 3-hour scout-troop hike video — extract the highlight summit moments.",
    "Uploading a 90-minute kids' science fair recording — pull the highlight project demos.",
    "Here's a 2-hour kennel-club dog show — please extract the highlight breed wins.",
    "I'm sending you a 4-hour state-fair livestock judging — pull the highlight blue-ribbon awards.",
    "Uploading a 5-hour college football game tape — extract the highlight touchdowns.",
    "Here's a 3-hour high-school cheer competition — please pull the highlight stunts.",
    "I have a 90-minute ski-jumping competition — extract the highlight long jumps.",
    "Uploading a 2-hour figure skating tournament — pull the highlight programs.",
    "Here's a 4-hour kart-racing endurance event — please extract the highlight passes.",
    "I'm sending you a 90-minute pool-shark league night — pull the highlight runs.",
    "Uploading a 2-hour state-fair tractor-pull — extract the highlight pulls.",
    "Here's a 3-hour drag-racing event — please pull the highlight runs.",
    "I have a 4-hour kart-racing championship — extract the highlight finishing laps.",
    "Uploading a 90-minute community basketball pickup game — pull the highlight buckets.",
    "Here's a 2-hour Junior Olympics meet — please extract the highlight finishes.",
    "I'm sending you a 3-hour synchronized swimming nationals — pull the highlight routines.",
    "Uploading a 4-hour open-water swim event — extract the highlight finish moments.",
    "Here's a 90-minute curling tournament — please pull the highlight stones.",
    "I have a 2-hour ultimate frisbee championship — extract the highlight throws.",
    "Uploading a 3-hour disc-golf tournament livestream — pull the highlight putts.",
    "Here's a 4-hour bodybuilding competition — please extract the highlight poses.",
    "I'm sending you a 90-minute MMA amateur exhibition — pull the highlight fight finishes.",
    "Uploading a 2-hour kettlebell-sport competition — extract the highlight cleans-and-jerks.",
    "Here's a 3-hour youth chess tournament — please pull the highlight winning moves.",
    "I have a 4-hour speed-skating competition — extract the highlight finishes.",
    "Uploading a 5-hour cricket test match — pull the highlight wickets and boundary fours.",
    "Here's a 90-minute pickleball doubles tournament — please extract the highlight rallies.",
    "I'm sending you a 2-hour dressage competition — pull the highlight piaffe moments.",
    "Uploading a 4-hour archery field competition — extract the highlight bullseyes.",
    "Here's a 3-hour drone-racing championship — please pull the highlight runs.",
    "I have a 90-minute axe-throwing tournament — extract the highlight bullseyes.",
    "Uploading a 2-hour dragon-boat festival race — pull the highlight finishes.",
    "Here's a 4-hour pickleball state finals — please extract the highlight rallies.",
    "I'm sending you a 90-minute kabaddi championship — pull the highlight raids.",
    "Uploading a 3-hour cornhole national championship — extract the highlight bag-tosses.",
    "Here's a 2-hour roller-derby final — please pull the highlight jams.",
    # ── more highlight extractions (50) ───────────────────────────────────
    "Uploading a 2-hour high-school musical theater performance — please extract the highlight numbers.",
    "Here's a 3-hour state high-school speech-and-debate finals — pull the highlight argumentation moments.",
    "I have a 4-hour middle-school MUN session — please extract the highlight resolution moments.",
    "Uploading a 90-minute children's choir Christmas concert — pull the highlight harmonies.",
    "Here's a 2-hour a-capella state championship — please extract the highlight breaks.",
    "I'm sending you a 5-hour high-school marching-band finals — pull the highlight halftime shows.",
    "Uploading a 3-hour high-school dance-team competition — please extract the highlight routines.",
    "Here's a 2-hour high-school volleyball state finals — pull the highlight rallies.",
    "I have a 4-hour high-school football state finals — please extract the highlight touchdowns.",
    "Uploading a 3-hour high-school soccer state finals — pull the highlight goals.",
    "Here's a 90-minute middle-school basketball tournament — please extract the highlight buckets.",
    "I'm sending you a 2-hour middle-school wrestling tournament — pull the highlight pins.",
    "Uploading a 3-hour middle-school track-and-field meet — please extract the highlight finishes.",
    "Here's a 4-hour middle-school swim meet — pull the highlight finishes.",
    "I have a 90-minute youth gymnastics meet — please extract the highlight routines.",
    "Uploading a 2-hour youth diving meet — pull the highlight dives.",
    "Here's a 3-hour youth cheer competition — please extract the highlight stunts.",
    "I'm sending you a 4-hour youth soccer tournament — pull the highlight goals.",
    "Uploading a 2-hour youth lacrosse tournament — please extract the highlight goals.",
    "Here's a 5-hour youth ice-hockey tournament — pull the highlight goals.",
    "I have a 90-minute youth field-hockey tournament — please extract the highlight goals.",
    "Uploading a 3-hour youth water-polo tournament — pull the highlight goals.",
    "Here's a 4-hour youth track-cycling event — please extract the highlight sprints.",
    "I'm sending you a 2-hour youth diving meet — pull the highlight dives.",
    "Uploading a 3-hour youth synchronized-swimming meet — please extract the highlight routines.",
    "Here's a 4-hour youth fencing tournament — pull the highlight touches.",
    "I have a 90-minute youth tae-kwon-do tournament — please extract the highlight kicks.",
    "Uploading a 2-hour youth karate tournament — pull the highlight kata.",
    "Here's a 3-hour youth jiu-jitsu tournament — please extract the highlight submissions.",
    "I'm sending you a 4-hour youth boxing tournament — pull the highlight finishes.",
    "Uploading a 5-hour youth Muay-Thai tournament — please extract the highlight knockouts.",
    "Here's a 2-hour youth equestrian show — pull the highlight jumps.",
    "I have a 3-hour youth rodeo event — please extract the highlight rides.",
    "Uploading a 90-minute youth weightlifting meet — pull the highlight cleans-and-jerks.",
    "Here's a 4-hour youth powerlifting meet — please extract the highlight deadlifts.",
    "I'm sending you a 2-hour youth speed-cubing championship — pull the highlight sub-10-second solves.",
    "Uploading a 3-hour youth chess open — please extract the highlight winning moves.",
    "Here's a 4-hour youth Scrabble open — pull the highlight bingo plays.",
    "I have a 90-minute youth crossword puzzle race — please extract the highlight finishes.",
    "Uploading a 2-hour youth coding hackathon final — pull the highlight project demos.",
    "Here's a 3-hour youth robotics regional — please extract the highlight match clips.",
    "I'm sending you a 4-hour youth science fair — pull the highlight presentations.",
    "Uploading a 2-hour youth Maker-Faire showcase — please extract the highlight project demos.",
    "Here's a 3-hour youth FIRST-Lego-League regional — pull the highlight match clips.",
    "I have a 4-hour youth FIRST-Tech-Challenge regional — please extract the highlight matches.",
    "Uploading a 90-minute youth speech-pathology demo — pull the highlight client moments.",
    "Here's a 2-hour youth physical-therapy demo — please extract the highlight rehab moments.",
    "I'm sending you a 3-hour youth animal-assisted-therapy demo — pull the highlight client moments.",
    "Uploading a 4-hour youth occupational-therapy demo — please extract the highlight client moments.",
    "Here's a 90-minute youth vision-therapy demo — pull the highlight breakthrough moments.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
