"""x15 cr_music — 14x SFT user_goal expansion (short briefs only).

Schema: USER_GOALS: list[str].

Chain: StoryAgent → ScreenplayAgent → KeyFrameAgent → VideoAgent →
       MusicAgent → AudioMixAgent → CompositorAgent

Distinguishing trigger from cr_compositor_only: user MUST mention BGM /
score / soundtrack / music style. NO ambience (that's cr_ambience), NO
subtitles (that's cr_subtitle / cr_bilingual), NO upload.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    # ── war / military (25) ───────────────────────────────────────────────
    "Make me a 1-minute mini-drama about a young battlefield medic stitching a soldier's wound under flickering lantern light, with somber strings as the score.",
    "I want a 45-second cinematic short of a paratrooper checking her gear inside a transport plane on the morning of her first jump, scored with low brass and timpani.",
    "Create a 30-second piece about a code-breaker in a wartime Bletchley hut realizing she's cracked a key, with mounting orchestral strings.",
    "Produce a 2-minute mini-drama of a war photographer crossing a snow-covered field at dawn, with a melancholic solo cello underscore.",
    "Build a 30-second piece where a young pilot writes a letter home from her quarters, scored with an introspective piano theme.",
    "Render a 45-second cinematic clip of a sailor on a destroyer deck reading a final radio order, with a stoic French-horn motif.",
    "Cook up a 1-minute war mini-drama where a translator listens to enemy radio traffic in headphones, scored with mounting suspense strings.",
    "Generate a 30-second short about a war widow tying her husband's medal onto her son's collar, scored with a gentle solo violin.",
    "I'd like a 45-second cinematic piece about a reconnaissance scout descending a tree at first light, with quiet pizzicato strings.",
    "Make a 30-second war clip of two soldiers digging a trench in fog, with deep cellos and a distant horn.",
    "Produce a 2-minute mini-drama about a wartime artist painting an evacuation scene from a hilltop, scored with mournful piano and strings.",
    "Build a 45-second short of a young aircraft engineer chalking calculations on a hangar floor, with a determined string-section motif.",
    "Create a 30-second piece where a homefront family hangs a service flag in their window, scored with a hopeful folk melody.",
    "Render a 1-minute war mini-drama of a soldier returning to his hometown bus stop after being away three years, with quiet acoustic guitar.",
    "I want a 30-second short about a young nurse pinning her cap before a hospital shift, scored with sustained strings and harp.",
    "Cook up a 45-second war piece of a destroyer crewman raising a signal flag at dawn, with rising orchestral brass.",
    "Generate a 1-minute mini-drama of a mother knitting socks for her son's regiment, scored with a soft piano lullaby.",
    "Make me a 30-second clip about a war reporter typing a final dispatch in a Cairo hotel room, scored with a wistful clarinet.",
    "Produce a 45-second short where a young soldier removes his boots on a porch on his first night home, scored with a quiet folk theme.",
    "Build a 30-second piece of a wartime telegraph operator decoding an incoming message at midnight, with brisk strings underscoring tension.",
    "I'd like a 2-minute mini-drama of a battlefield chaplain reading a service in a ruined chapel, with a slow choral underscore.",
    "Render a 45-second war clip about a paramedic treating a wounded refugee child, scored with a hopeful string-and-piano motif.",
    "Create a 30-second piece where a wartime baker delivers bread to neighbors during a curfew, scored with a folk-violin theme.",
    "Make a 1-minute mini-drama about a captured intelligence officer slipping a coded note inside a folded letter home, with a tense string ostinato.",
    "Cook up a 45-second cinematic short of a young soldier tucking a rosary into his uniform pocket before deployment, scored with reverent strings and brass.",
    # ── exploration / adventure (20) ──────────────────────────────────────
    "I want a 1-minute mini-drama of a polar explorer raising a flag at the edge of an Antarctic ridge, with a triumphant brass-and-strings score.",
    "Make me a 45-second cinematic short about a deep-sea diver descending past a coral wall, with ethereal synth-and-string ambient music.",
    "Create a 30-second piece where a mountaineer ties off her rope on a vertical wall at sunset, with mounting orchestral percussion.",
    "Produce a 2-minute mini-drama about an Antarctic researcher carrying samples back to her station against a wind, with a slow piano-and-strings underscore.",
    "Build a 45-second short of a hot-air balloonist floating over the Serengeti at dawn, with a soaring string-and-flute theme.",
    "Render a 30-second cinematic clip of a desert archaeologist sweeping sand off a ruin's threshold, with a meditative oud-and-strings score.",
    "Cook up a 1-minute exploration mini-drama where a young geologist examines lava rock at a Hawaiian crater rim, scored with deep orchestral brass.",
    "Generate a 45-second short of a kayaker portaging across a Patagonian saddle at dusk, with a contemplative acoustic-guitar score.",
    "I'd like a 30-second cinematic piece of a free-diver surfacing through a school of fish, with rising string and harp underscoring.",
    "Make a 2-minute mini-drama about a cave explorer descending into a Bornean cavern by headlamp, with slow timpani and synth ambient.",
    "Produce a 30-second short where a research-vessel marine biologist marks a tagged whale's surface event, scored with a serene string motif.",
    "Build a 45-second cinematic piece about a desert traveler watering camels at an Empty-Quarter oasis, with a delicate flute-and-strings score.",
    "Create a 1-minute mini-drama of a glacier guide chipping ice samples from a Greenland tongue, with sustained strings and a low cello drone.",
    "Render a 30-second clip of a sub pilot turning her vessel toward an unmapped trench, scored with a tense low-brass underscore.",
    "I want a 45-second cinematic piece of a young pilot landing a bush plane on a pebble beach above the Arctic Circle, scored with a triumphant brass theme.",
    "Cook up a 1-minute mini-drama of a treasure-hunter rappelling into a Yucatán cenote with a single torch, with a tense string-and-percussion score.",
    "Generate a 30-second short about a polar climber kneeling to plant a research flag on a cracked plateau, scored with a windswept string motif.",
    "Make me a 45-second cinematic clip of a balloon expedition mapping unexplored Amazonian canopies, with an ethereal synth-and-strings score.",
    "Produce a 2-minute mini-drama about a deep-sea sub pilot powering past a giant squid silhouette, with rising suspense strings and brass.",
    "Build a 30-second piece of a research crew dropping a buoy into the Mariana Trench from a research vessel, with deep cello drones and harp.",
    # ── sports (20) ───────────────────────────────────────────────────────
    "Make me a 1-minute sports mini-drama about a young marathon runner crossing the finish line behind everyone else, scored with a triumphant string-and-brass theme.",
    "I want a 45-second cinematic short of a high-school basketball player practicing free-throws at midnight, with a quiet piano-and-soft-percussion score.",
    "Create a 30-second piece where a young gymnast lands her first standing back-tuck, scored with a soaring string crescendo.",
    "Produce a 2-minute sports mini-drama about a boxer wrapping her hands in the locker room before her first title fight, with a tense low-brass theme.",
    "Build a 45-second short of a swimmer touching the wall as a stadium scoreboard updates, scored with rising orchestral percussion.",
    "Render a 30-second cinematic clip of a goalie diving in slow motion to save a penalty kick, with a soaring string-and-horn theme.",
    "Cook up a 1-minute sports mini-drama of an Olympic figure skater tying her laces in a quiet rink before sunrise, with a meditative piano score.",
    "Generate a 45-second short of a sprinter walking out of a tunnel into stadium lights, with a percussive electronic-and-strings underscore.",
    "I'd like a 30-second cinematic piece of a fencer adjusting her mask before a championship bout, scored with rapid pizzicato strings.",
    "Make a 2-minute sports mini-drama about a coach giving a halftime speech in a high-school locker room, with a slow piano-and-cello underscore.",
    "Produce a 30-second short where a softball pitcher rehearses her windup in an empty diamond at golden hour, with a folksy guitar-and-strings score.",
    "Build a 45-second cinematic piece about a young boxer training on a heavy bag in a Brooklyn basement gym, scored with mounting low-brass and percussion.",
    "Create a 1-minute mini-drama of a cyclist climbing the final switchback of a mountain pass, with a triumphant orchestral score.",
    "Render a 30-second clip of a tennis player serving in slow motion under stadium lights, with a tense string-and-percussion underscore.",
    "I want a 45-second cinematic piece of a young surfer waxing his board at a deserted dawn beach, scored with a contemplative acoustic-guitar theme.",
    "Cook up a 1-minute sports mini-drama of a wheelchair-rugby team huddling at midcourt, with a percussive orchestral underscore.",
    "Generate a 30-second short about a junior fencer training her wrist alone in an empty gym, scored with a delicate harp-and-strings piece.",
    "Make me a 45-second cinematic clip of a hockey goalie adjusting his mask during a national-anthem moment, scored with a stoic French-horn theme.",
    "Produce a 2-minute mini-drama about a young weightlifter loading her first record-breaking bar, scored with a building string-and-brass crescendo.",
    "Build a 30-second piece of a young figure skater spinning in slow motion under the stadium lights, with a sweeping orchestral waltz.",
    # ── musician biopic / artistic (15) ───────────────────────────────────
    "Make me a 1-minute biographical mini-drama about a young jazz saxophonist practicing alone in a basement at 4 AM, with an accompanying cool-jazz score.",
    "I want a 45-second cinematic short of a young classical pianist rehearsing scales at a borrowed Steinway, scored with a delicate solo-piano piece.",
    "Create a 30-second mini-drama where a young opera singer hits her first sustained high note in a mirrored studio, with a soaring string-and-piano underscore.",
    "Produce a 2-minute mini-drama about a young violin maker varnishing his first instrument at his workbench, with a contemplative classical-strings piece.",
    "Build a 45-second short of a young blues guitarist tuning her father's old guitar on a porch, with an evocative acoustic-blues underscore.",
    "Render a 30-second cinematic clip of a young flamenco dancer practicing footwork in a Sevillian courtyard, with a flamenco-guitar-and-handclap score.",
    "Cook up a 1-minute biographical mini-drama of a young cellist auditioning for her first quartet at the Conservatoire, scored with a tense quartet motif.",
    "Generate a 45-second short of a young drummer setting up his kit in his parents' garage, with an upbeat rock-and-roll instrumental score.",
    "I'd like a 30-second cinematic piece of a young harp-maker stringing her first concert harp, scored with a delicate harp-and-strings theme.",
    "Make a 2-minute biographical mini-drama of a young Klezmer clarinetist learning a tune from her grandfather, with a Klezmer-clarinet-and-fiddle score.",
    "Produce a 30-second short where a young blues guitarist tunes his guitar on a Mississippi porch as a freight train passes, with delta-blues guitar underscoring.",
    "Build a 45-second cinematic piece about a young rock vocalist running scales backstage before her first arena show, with a rising synth-and-drums score.",
    "Create a 1-minute mini-drama of a young qin player tuning her instrument in a stone garden, with a classical-Chinese qin-and-bamboo-flute score.",
    "Render a 30-second clip of a young bagpiper rehearsing alone on a Scottish hillside at dusk, with a single bagpipe lament as the score.",
    "I want a 45-second cinematic piece of a young string-quartet leader waiting for her cue backstage, scored with a delicate quartet motif rising.",
    # ── dance (15) ────────────────────────────────────────────────────────
    "Make me a 1-minute mini-drama about a young ballet dancer practicing arabesques alone in a mirrored studio at dawn, with a delicate piano-and-strings ballet score.",
    "I want a 45-second cinematic short of a young flamenco dancer in a Sevillian courtyard, with handclaps and Spanish-guitar accompaniment.",
    "Create a 30-second piece where a young break-dancer practices windmills on cardboard in a city plaza at dusk, with a hip-hop instrumental score.",
    "Produce a 2-minute mini-drama about a Bharatanatyam dancer rehearsing in a temple courtyard, with traditional mridangam-and-flute underscore.",
    "Build a 45-second short of a young tango dancer practicing close-embrace footwork on a Buenos Aires balcony, scored with bandoneón-and-strings tango.",
    "Render a 30-second cinematic clip of a salsa dancer practicing turns at a Cuban open-air dance hall, scored with a clave-and-trumpet salsa score.",
    "Cook up a 1-minute mini-drama of an Irish step-dancer rehearsing on a wooden barn floor, with fiddle-and-bodhran reel music.",
    "Generate a 45-second short about a contemporary dancer working through a solo on a sun-warmed studio floor, scored with a piano-and-strings minimalist piece.",
    "I'd like a 30-second cinematic piece of a young ballroom dancer rehearsing alone in a hotel mirror room, scored with a sweeping string waltz.",
    "Make a 2-minute mini-drama of a Russian Cossack dancer practicing in a snowy courtyard, scored with balalaika-and-accordion folk music.",
    "Produce a 30-second short where a young hip-hop dancer practices on a New York rooftop at sunset, with a beat-and-bass underscore.",
    "Build a 45-second cinematic piece of a young Korean traditional fan-dancer rehearsing in a wooden hall, scored with a haegeum-and-janggu motif.",
    "Create a 1-minute mini-drama of a Capoeira pair practicing in an early-morning Salvador square, scored with berimbau-and-pandeiro music.",
    "Render a 30-second clip of a Cuban son dancer twirling her partner under a porch light, scored with a tres-and-bongos son piece.",
    "I want a 45-second cinematic piece of a Polynesian hula dancer rehearsing on a black-sand beach at twilight, scored with ipu-heke-and-chant music.",
    # ── romance / drama w/ score (15) ─────────────────────────────────────
    "Make me a 1-minute mini-drama about a young couple reuniting at an airport gate after a long deployment, scored with a warm string-and-piano theme.",
    "I want a 45-second cinematic short of an elderly couple slow-dancing in their kitchen on their golden anniversary, scored with a tender swing-jazz piece.",
    "Create a 30-second piece where a man waits at a Paris train station with a single bouquet, scored with a wistful accordion-and-strings musette.",
    "Produce a 2-minute mini-drama about a young woman writing a love letter at her grandmother's writing desk, scored with a delicate piano-and-cello theme.",
    "Build a 45-second short of a couple sharing an umbrella at a Tokyo crosswalk in pouring rain, scored with a delicate koto-and-strings score.",
    "Render a 30-second cinematic clip of a young couple lighting their first apartment's first candle, scored with a soft acoustic-guitar piece.",
    "Cook up a 1-minute mini-drama where two long-distance lovers open identical packages on a video call, scored with a hopeful piano-and-strings theme.",
    "Generate a 45-second short of a couple revisiting the bench of their first date on its 30th anniversary, scored with a wistful waltz.",
    "I'd like a 30-second cinematic piece of a young wife receiving her husband's first letter from overseas, scored with a soft string lament.",
    "Make a 2-minute mini-drama about a young couple proposing to each other simultaneously on a hilltop at sunset, scored with a soaring orchestral love theme.",
    "Produce a 30-second short where a young father holds his newborn for the first time in a hospital window light, scored with a hushed lullaby.",
    "Build a 45-second cinematic piece about a young couple reading their wedding vows aloud in a quiet rehearsal hall, scored with a delicate string-and-harp piece.",
    "Create a 1-minute mini-drama of a daughter dancing with her father at her wedding, scored with a sweeping classical-strings waltz.",
    "Render a 30-second clip of a young couple walking down a Parisian Pont-Neuf at dusk, scored with a quiet jazz-piano theme.",
    "I want a 45-second cinematic piece of a young husband cooking dinner for his pregnant wife in a small kitchen, scored with a soft piano-and-flute piece.",
    # ── religious / ceremonial (15) ───────────────────────────────────────
    "I want a 1-minute mini-drama of a young Buddhist monk lighting butter lamps in a Tibetan monastery at dawn, scored with low chanting and singing-bowl ambient.",
    "Make me a 45-second cinematic short of a young Greek-Orthodox priest preparing icons for a feast day, scored with a male-choir Byzantine chant.",
    "Create a 30-second piece where a young Sikh worshiper folds a chador for the Guru Granth Sahib, scored with a kirtan-style raag.",
    "Produce a 2-minute mini-drama about a young Coptic deacon walking through a desert monastery courtyard at dawn, scored with monastic chant.",
    "Build a 45-second short of a young Shinto priest sweeping the path to a shrine, scored with a koto-and-bamboo-flute piece.",
    "Render a 30-second cinematic clip of a young Bedouin elder leading evening prayers under desert stars, scored with a sustained vocal call.",
    "Cook up a 1-minute mini-drama of a young Hindu priestess threading marigolds into a temple garland, scored with a bansuri-and-sitar raag.",
    "Generate a 45-second short about a young Catholic novice taking final vows in a candlelit chapel, scored with a Gregorian-chant choir.",
    "I'd like a 30-second cinematic piece of a young yarmulke-clad cantor practicing Kol Nidre alone in an empty synagogue, scored with a solo-cantor melody.",
    "Make a 2-minute mini-drama about a young Quaker reading silently at a Meeting House before the service, scored with a single sustained organ note.",
    "Produce a 30-second short where a young Sufi practitioner whirls slowly in a lit courtyard, scored with a ney-and-drum sema piece.",
    "Build a 45-second cinematic piece about a young Maasai elder lighting a ceremonial fire at twilight, scored with a deep group chant.",
    "Create a 1-minute mini-drama of a young Druid celebrant standing before standing stones at solstice, scored with a single harp piece.",
    "Render a 30-second clip of a young Bahá'í youth lighting candles at a Naw-Rúz table, scored with a soft a-cappella melody.",
    "I want a 45-second cinematic piece of a young Vodou priestess pouring libation by candlelight, scored with traditional drumming and chant.",
    # ── disaster / storm / mystery / futurism (35 closers) ────────────────
    "Make me a 1-minute mini-drama about a coastal lighthouse keeper sounding her foghorn in a hurricane, scored with crashing orchestral strings and brass.",
    "I want a 45-second cinematic short of a young volunteer firefighter walking into wildfire glow at dawn, scored with mounting low-brass and percussion.",
    "Create a 30-second piece where a young paramedic loads survivors into an ambulance after an earthquake, scored with a tense string-and-percussion underscore.",
    "Produce a 2-minute mini-drama about a young flood-rescue boat captain navigating a flooded street, scored with a tense rising-strings score.",
    "Build a 45-second short of a tornado siren tester checking gear inside a Midwestern silo, scored with a slow building piano-and-strings underscore.",
    "Render a 30-second cinematic clip of a young farmer covering tomato vines before a hailstorm, scored with a folk-fiddle-and-strings piece.",
    "Cook up a 1-minute mini-drama where a coastal village family boards up their windows before a cyclone, scored with mounting orchestral strings.",
    "Generate a 45-second short about a young volunteer ladling soup at a flood-evacuation shelter, scored with a hopeful folk-violin piece.",
    "I'd like a 30-second cinematic piece of a snowplow driver pushing snow off a mountain pass at dawn, scored with a steady piano-and-bass piece.",
    "Make a 2-minute mini-drama about a young coastal lifeguard rescuing a stranded surfer in heavy swell, scored with a tense strings-and-percussion score.",
    "Make me a 1-minute mini-drama about a young detective decoding a cipher she found tucked in an antique book, scored with a tense piano-and-strings piece.",
    "I want a 45-second cinematic short of a young investigator opening a sealed evidence box at midnight, scored with a low rising-string suspense piece.",
    "Create a 30-second piece where a young curator notices the same stranger in three unrelated archive photos, scored with a shimmering uneasy piano theme.",
    "Produce a 2-minute mini-drama about a young librarian discovering an entire shelf of books missing overnight, scored with a tense low-string ostinato.",
    "Build a 45-second short of a young historian comparing two seemingly identical Victorian portraits, scored with a tense violin-and-piano underscore.",
    "Render a 30-second cinematic clip of a young accountant noticing identical signatures on twenty consecutive checks, scored with a percussive suspense piece.",
    "Cook up a 1-minute mystery mini-drama where a young tax officer recognizes a disappeared client's handwriting on a new file, scored with a tense piano-and-strings.",
    "Generate a 45-second short of a young clerk discovering a key inside a returned library book, scored with a rising piano-and-cello underscore.",
    "I'd like a 30-second cinematic piece of a young postmistress noticing every letter from one address has the same handwriting but different fingerprints, scored with shimmering uneasy strings.",
    "Make a 2-minute mystery mini-drama about a young restorer noticing earlier paintings hidden under a museum canvas, scored with a building chamber-orchestra piece.",
    "Make me a 1-minute futurist mini-drama about a young engineer activating the first Mars-colony water pump, scored with a synth-and-strings cinematic theme.",
    "I want a 45-second cinematic short of a young astronaut on a lunar farm watching the Earth rise, scored with a soaring orchestral score.",
    "Create a 30-second piece where a young pilot tests a hypersonic prototype on a salt-flat runway, scored with a percussive electronic-orchestra piece.",
    "Produce a 2-minute mini-drama about a young roboticist activating her first humanoid prototype in a sunlit atelier, scored with a delicate piano-and-strings piece.",
    "Build a 45-second short of a young engineer deploying a fusion-reactor coolant valve, scored with rising orchestral synth.",
    "Render a 30-second cinematic clip of a young space-elevator technician walking the cable platform at dawn, scored with an awe-struck string-and-synth theme.",
    "Cook up a 1-minute futurist mini-drama where a young settler stamps her first homestead claim on a moon-base ledger, scored with a hopeful French-horn theme.",
    "Generate a 45-second short of a young pilot testing the first solar-sail satellite from a control room, scored with a mounting electronic-orchestra piece.",
    "I'd like a 30-second cinematic piece of a young AI scientist watching her code train its first self-supervised model overnight, scored with a quiet synth-and-strings underscore.",
    "Make a 2-minute futurist mini-drama about a deep-space tugboat captain ferrying a damaged satellite back through Saturn's rings, scored with a sweeping orchestral score.",
    "Produce a 30-second short where a young exoplanet astronomer discovers her first habitable-zone candidate, scored with a soaring violin-and-synth motif.",
    "Build a 45-second cinematic piece about a young cyborg-rights advocate giving her first speech in a future Berlin parliament, scored with a determined brass-and-percussion piece.",
    "Create a 1-minute mini-drama of a young Mars-base botanist witnessing the first apple tree blossom indoors, scored with a hopeful pastoral piece.",
    "Render a 30-second clip of a young spacelift technician guiding a lunar shuttle into dock, scored with a tense orchestral-and-electronic underscore.",
    "I want a 45-second cinematic piece of a young geneticist watching her first rewilded mammoth take a step in an Arctic preserve, scored with a soaring orchestra theme.",
    # ── medical / hospital w/ score (20) ──────────────────────────────────
    "Make me a 1-minute mini-drama about a young trauma surgeon scrubbing in for a brain surgery, scored with a tense piano-and-strings piece.",
    "I want a 45-second cinematic short of a young midwife delivering her first set of twins at dawn, scored with a hopeful piano theme.",
    "Create a 30-second piece about a young oncologist sharing test results with a long-term patient, scored with a soft cello motif.",
    "Produce a 2-minute mini-drama of a young transplant surgeon waiting for the donor heart to arrive, scored with a tense low-string ostinato.",
    "Build a 45-second short of a young ER physician closing a chest after a cardiac arrest, scored with a swelling orchestral piece.",
    "Render a 30-second cinematic clip of a young pediatric nurse comforting a frightened child before chemotherapy, scored with a tender piano-and-cello duet.",
    "Cook up a 1-minute mini-drama of a young rural doctor riding a snowmobile to a remote patient, scored with a determined piano-and-fiddle piece.",
    "Generate a 45-second short of a young hospice nurse holding the hand of a dying patient, scored with a quiet harmonium-and-vocal hymn.",
    "I'd like a 30-second cinematic piece of a young anesthesiologist counting backward with a child before surgery, scored with a soft piano lullaby.",
    "Make a 30-second clip of a young battlefield medic stitching a soldier's wound under flickering lantern light, scored with a mournful violin solo.",
    "Produce a 2-minute mini-drama about a young pediatric psychiatrist meeting her first long-term patient, scored with a delicate clarinet piece.",
    "Build a 45-second short of a young veterinary surgeon performing her first cesarean on a mare, scored with a tense piano-and-strings piece.",
    "Create a 30-second piece where a young epidemiologist tracks an outbreak across a city map at midnight, scored with a tense electronic-pulse piece.",
    "Render a 1-minute mini-drama of a young dental surgeon completing a complex maxillofacial repair, scored with a quiet piano-and-strings underscore.",
    "I want a 30-second cinematic short of a young dermatologist explaining a rare diagnosis to anxious parents, scored with a soft cello-and-piano duet.",
    "Cook up a 45-second piece of a young infectious-disease doctor donning a hazmat suit before entering an isolation ward, scored with a tense low-brass piece.",
    "Generate a 1-minute mini-drama of a young trauma nurse stabilizing a patient as the chopper lifts off, scored with a swelling orchestral piece.",
    "Make me a 30-second clip of a young burn-unit physician dressing a patient's bandages, scored with a tender piano-and-cello duet.",
    "Produce a 45-second short of a young palliative-care physician sitting with a family at a bedside, scored with a quiet harmonium-and-vocal hymn.",
    "Build a 30-second piece of a young chief resident handing off her last patient before retirement, scored with a tender piano-and-strings duet.",
    # ── tech / startup / hacker w/ score (15) ─────────────────────────────
    "Make me a 1-minute mini-drama about a young coder pulling an all-nighter the night before her startup's product launch, scored with a tense electronic-pulse piece.",
    "I want a 45-second cinematic short of a young hacker tracing a security breach across global subnets, scored with a tense electronic-orchestra piece.",
    "Create a 30-second piece about a young engineer writing her resignation letter at midnight, scored with a soft piano-and-cello duet.",
    "Produce a 2-minute mini-drama of a young AI researcher watching her model achieve a breakthrough overnight, scored with a swelling synth-and-strings piece.",
    "Build a 45-second short of a young chip designer running her first foundry tape-out, scored with a determined electronic-pulse piece.",
    "Render a 30-second cinematic clip of a young blockchain architect pushing her first commit to a public protocol, scored with a tense electronic-pulse piece.",
    "Cook up a 1-minute mini-drama of a young cybersecurity analyst defending against a live nation-state attack, scored with a tense electronic-orchestra piece.",
    "Generate a 45-second short of a young VR designer testing her first immersive simulation, scored with an awe-struck synth-and-strings piece.",
    "I'd like a 30-second cinematic piece of a young app developer presenting at her first hackathon final, scored with an upbeat electronic-pulse piece.",
    "Make a 30-second clip of a young data scientist running her first machine-learning pipeline at scale, scored with a determined synth-and-strings piece.",
    "Produce a 2-minute mini-drama about a young CTO explaining a system architecture to her board of directors, scored with a corporate-uplift piece.",
    "Build a 45-second short of a young privacy advocate testifying before a Senate committee, scored with a determined low-brass-and-strings piece.",
    "Create a 30-second piece where a young UX researcher debriefs a usability study with her team, scored with a soft acoustic-piano piece.",
    "Render a 1-minute mini-drama of a young open-source maintainer accepting her first major code contribution, scored with a hopeful piano-and-strings piece.",
    "I want a 45-second cinematic piece of a young chip-fab engineer overseeing her first wafer-yield run, scored with a determined synth-and-strings piece.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
