"""x15 extend_style_subtitle SFT.
Chain: IntakeVideo → VideoExtend → StyleTransfer → Transcription → Compositor.
Trigger: upload + extend + style + monolingual subtitle.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 30-second talking-head clip — extend to 90 seconds, convert to anime style, and add English subtitles.",
    "Here's a 45-second tutorial — extend to 2 minutes, render as watercolor, and overlay English captions.",
    "I have a 1-minute lecture clip — extend to 3 minutes, style as oil painting, and add English subtitles.",
    "Uploading a 30-second product demo — extend to 90 seconds, convert to cel-shaded style, and overlay English captions.",
    "Here's a 45-second cooking tutorial — extend to 2 minutes, style as Studio Ghibli, and add English subtitles.",
    "I'm sending you a 30-second yoga demo — extend to 90 seconds, render as charcoal sketch, and overlay English captions.",
    "Uploading a 1-minute meditation guide — extend to 3 minutes, style as Tibetan thangka, and add English subtitles.",
    "Here's a 45-second TED-talk excerpt — extend to 2 minutes, convert to a 1960s Saul Bass title-card, and overlay English captions.",
    "I have a 30-second motivational speech — extend to 90 seconds, style as Russian Constructivist poster, and add English subtitles.",
    "Uploading a 1-minute museum-curator tour — extend to 3 minutes, render as Vermeer interior, and overlay English captions.",
    "Here's a 30-second author interview — extend to 90 seconds, style as Klimt golden-portrait, and add English subtitles.",
    "I'm sending you a 45-second classroom lesson — extend to 2 minutes, convert to chalkboard hand-drawing, and overlay English captions.",
    "Uploading a 1-minute corporate-training video — extend to 3 minutes, style as 1970s 16mm film, and add English subtitles.",
    "Here's a 30-second documentary clip — extend to 90 seconds, render as 1940s newsreel, and overlay English captions.",
    "I have a 45-second history podcast clip — extend to 2 minutes, style as 1900s sepia film, and add English subtitles.",
    "Uploading a 1-minute museum tour — extend to 3 minutes, convert to Persian miniature, and overlay English captions.",
    "Here's a 30-second science explainer — extend to 90 seconds, style as 1980s VHS aesthetic, and add English subtitles.",
    "I'm sending you a 45-second philosophy monologue — extend to 2 minutes, render as Victorian etching, and overlay English captions.",
    "Uploading a 1-minute motivational speech — extend to 3 minutes, style as Art Deco poster, and add English subtitles.",
    "Here's a 30-second author interview — extend to 90 seconds, convert to anime cel-shading, and overlay English captions.",
    "I have a 45-second celebrity interview — extend to 2 minutes, style as Wong-Kar-wai cinematic look, and add English subtitles.",
    "Uploading a 1-minute fitness demo — extend to 3 minutes, render as Pixar 3D animation, and overlay English captions.",
    "Here's a 30-second classroom recording — extend to 90 seconds, style as 1990s Saturday-morning cartoon, and add English subtitles.",
    "I'm sending you a 45-second TED-talk excerpt — extend to 2 minutes, convert to French Nouvelle-Vague film, and overlay English captions.",
    "Uploading a 1-minute life-coach monologue — extend to 3 minutes, style as Bharatanatyam-style miniature, and add English subtitles.",
    "Here's a 30-second museum-docent tour — extend to 90 seconds, render as Vermeer interior, and overlay English captions.",
    "I have a 45-second yoga-flow demo — extend to 2 minutes, style as Mid-century-modern poster, and add English subtitles.",
    "Uploading a 1-minute career-coach clip — extend to 3 minutes, convert to 1950s magazine illustration, and overlay English captions.",
    "Here's a 30-second podcast video — extend to 90 seconds, style as Bauhaus poster, and add English subtitles.",
    "I'm sending you a 45-second science-news monologue — extend to 2 minutes, render as Studio Ghibli aesthetic, and overlay English captions.",
    "Uploading a 1-minute therapy-channel clip — extend to 3 minutes, style as watercolor children's-book, and add English subtitles.",
    "Here's a 30-second cooking-show monologue — extend to 90 seconds, convert to Norman Rockwell illustration, and overlay English captions.",
    "I have a 45-second tax-tips video — extend to 2 minutes, style as 1960s magazine cover, and add English subtitles.",
    "Uploading a 1-minute gardening tutorial — extend to 3 minutes, render as William Morris pattern, and overlay English captions.",
    "Here's a 30-second physics explainer — extend to 90 seconds, style as Caspar David Friedrich painting, and add English subtitles.",
    # ── more upload + extend + style + subtitle requests (50) ──────────────
    "Uploading a 30-second keynote-address clip — extend to 90 seconds, convert to cyberpunk-neon, and add English subtitles.",
    "Here's a 45-second product-launch reel — extend to 2 minutes, render as dieselpunk-1940s, and overlay English captions.",
    "I have a 1-minute design-review session — extend to 3 minutes, style as atompunk-1950s-retro-future, and add English subtitles.",
    "Uploading a 30-second code-review clip — extend to 90 seconds, convert to solarpunk-bright-eco, and overlay English captions.",
    "Here's a 45-second whiteboard-session clip — extend to 2 minutes, style as steampunk-Victorian, and add English subtitles.",
    "I'm sending you a 30-second mock-interview reel — extend to 90 seconds, render as clockpunk-gilded-gears, and overlay English captions.",
    "Uploading a 1-minute panel-discussion excerpt — extend to 3 minutes, convert to low-poly PS1 aesthetic, and add English subtitles.",
    "Here's a 45-second skill-share class clip — extend to 2 minutes, style as 16-bit pixel art, and overlay English captions.",
    "I have a 30-second art-history lecture clip — extend to 90 seconds, render as ASCII-art monochrome, and add English subtitles.",
    "Uploading a 1-minute music-theory class — extend to 3 minutes, convert to blueprint CAD style, and overlay English captions.",
    "Here's a 30-second composition lesson — extend to 90 seconds, style as wireframe 3D, and add English subtitles.",
    "I'm sending you a 45-second piano masterclass clip — extend to 2 minutes, render as Hergé Tintin ligne-claire, and overlay English captions.",
    "Uploading a 1-minute conducting class — extend to 3 minutes, convert to Asterix Goscinny-Uderzo style, and add English subtitles.",
    "Here's a 30-second improv-class clip — extend to 90 seconds, style as Soviet propaganda poster, and overlay English captions.",
    "I have a 45-second standup-routine clip — extend to 2 minutes, render as WPA New-Deal poster, and add English subtitles.",
    "Uploading a 1-minute comedy-special excerpt — extend to 3 minutes, convert to NPS National-Parks poster, and overlay English captions.",
    "Here's a 30-second book-club discussion — extend to 90 seconds, style as Russian icon painting, and add English subtitles.",
    "I'm sending you a 45-second writing-workshop clip — extend to 2 minutes, render as Byzantine mosaic, and overlay English captions.",
    "Uploading a 1-minute poetry-reading excerpt — extend to 3 minutes, convert to Roman fresco, and add English subtitles.",
    "Here's a 30-second chef-demo clip — extend to 90 seconds, style as Egyptian tomb painting, and overlay English captions.",
    "I have a 45-second mixology-tutorial clip — extend to 2 minutes, render as Greek-vase red-figure, and add English subtitles.",
    "Uploading a 1-minute watercolor class — extend to 3 minutes, convert to Aztec codex illustration, and overlay English captions.",
    "Here's a 30-second pottery class — extend to 90 seconds, style as Maya glyph carving, and add English subtitles.",
    "I'm sending you a 45-second knitting class — extend to 2 minutes, render as Polynesian tapa cloth, and overlay English captions.",
    "Uploading a 1-minute woodworking tutorial — extend to 3 minutes, convert to Aboriginal dot painting, and add English subtitles.",
    "Here's a 30-second photography tutorial — extend to 90 seconds, style as African mask, and overlay English captions.",
    "I have a 45-second video-editing tutorial — extend to 2 minutes, render as Ethiopian icon, and add English subtitles.",
    "Uploading a 1-minute 3D-modeling tutorial — extend to 3 minutes, convert to Coptic icon, and overlay English captions.",
    "Here's a 30-second web-dev tutorial — extend to 90 seconds, style as Russian lubok print, and add English subtitles.",
    "I'm sending you a 45-second data-science lecture — extend to 2 minutes, render as Polish-poster-school graphic, and overlay English captions.",
    "Uploading a 1-minute chess-strategy lesson — extend to 3 minutes, convert to Japanese Sumi-e ink-wash, and add English subtitles.",
    "Here's a 30-second poker-strategy clip — extend to 90 seconds, style as Korean Minhwa folk, and overlay English captions.",
    "I have a 45-second backgammon lesson — extend to 2 minutes, render as Chinese shanshui ink, and add English subtitles.",
    "Uploading a 1-minute Rubik's-cube tutorial — extend to 3 minutes, convert to Thai temple mural, and overlay English captions.",
    "Here's a 30-second juggling lesson — extend to 90 seconds, style as Burmese lacquer painting, and add English subtitles.",
    "I'm sending you a 45-second magic-trick reveal — extend to 2 minutes, render as Vietnamese silk painting, and overlay English captions.",
    "Uploading a 1-minute card-trick tutorial — extend to 3 minutes, convert to Mongol horse painting, and add English subtitles.",
    "Here's a 30-second dance-class reel — extend to 90 seconds, style as Aboriginal rock art, and overlay English captions.",
    "I have a 45-second Pilates class — extend to 2 minutes, render as Inuit soapstone carving, and add English subtitles.",
    "Uploading a 1-minute CrossFit demo — extend to 3 minutes, convert to Native-American ledger art, and overlay English captions.",
    "Here's a 30-second nutrition lecture — extend to 90 seconds, style as Brutalist concrete graphic, and add English subtitles.",
    "I'm sending you a 45-second wine-tasting clip — extend to 2 minutes, render as Memphis 1980s design, and overlay English captions.",
    "Uploading a 1-minute cocktail class — extend to 3 minutes, convert to De-Stijl Mondrian, and add English subtitles.",
    "Here's a 30-second cooking-show excerpt — extend to 90 seconds, style as Frank-Miller noir comic, and overlay English captions.",
    "I have a 45-second baking-show clip — extend to 2 minutes, render as Atelier-Populaire May-1968 poster, and add English subtitles.",
    "Uploading a 1-minute pastry class — extend to 3 minutes, convert to Push-Pin-Studios poster, and overlay English captions.",
    "Here's a 30-second coffee-brewing class — extend to 90 seconds, style as Reid-Miles Blue-Note jazz cover, and add English subtitles.",
    "I'm sending you a 45-second tea-ceremony lesson — extend to 2 minutes, render as Eames Powers-of-Ten infographic, and overlay English captions.",
    "Uploading a 1-minute calligraphy class — extend to 3 minutes, convert to Milton-Glaser graphic, and add English subtitles.",
    "Here's a 30-second typography lesson — extend to 90 seconds, style as Paula-Scher type-poster, and overlay English captions.",
    # ── more upload + extend + style + subtitle requests (50) ──────────────
    "Uploading a 30-second red-carpet interview — extend to 90 seconds, convert to Hollywood-Walk poster, and add English subtitles.",
    "Here's a 45-second press-conference walkthrough — extend to 2 minutes, render as news-broadcast aesthetic, and overlay English captions.",
    "I have a 1-minute game-night recap — extend to 3 minutes, style as Monopoly-board illustration, and add English subtitles.",
    "Uploading a 30-second board-game tournament clip — extend to 90 seconds, convert to Settlers-of-Catan illustration, and overlay English captions.",
    "Here's a 45-second Dungeons-Dragons session — extend to 2 minutes, style as medieval illuminated manuscript, and add English subtitles.",
    "I'm sending you a 30-second tabletop-RPG meetup clip — extend to 90 seconds, render as Frank-Frazetta fantasy, and overlay English captions.",
    "Uploading a 1-minute cosplay-meetup reel — extend to 3 minutes, convert to Akira-Toriyama anime, and add English subtitles.",
    "Here's a 45-second anime-convention panel — extend to 2 minutes, style as Hayao-Miyazaki, and overlay English captions.",
    "I have a 30-second comic-book signing reel — extend to 90 seconds, render as Jack-Kirby Marvel comics, and add English subtitles.",
    "Uploading a 1-minute zine-fair browse reel — extend to 3 minutes, convert to R.-Crumb underground comix, and overlay English captions.",
    "Here's a 30-second art-fair walkthrough — extend to 90 seconds, style as Banksy stencil graffiti, and add English subtitles.",
    "I'm sending you a 45-second NFT-gallery walkthrough — extend to 2 minutes, render as glitch-art, and overlay English captions.",
    "Uploading a 1-minute metaverse-showroom reel — extend to 3 minutes, convert to low-poly PS1 aesthetic, and add English subtitles.",
    "Here's a 30-second crypto-conference reel — extend to 90 seconds, style as cyberpunk-neon, and overlay English captions.",
    "I have a 45-second AR-headset demo — extend to 2 minutes, render as wireframe HUD, and add English subtitles.",
    "Uploading a 1-minute VR-arcade reel — extend to 3 minutes, convert to neon-grid Tron, and overlay English captions.",
    "Here's a 30-second drone-show recap — extend to 90 seconds, style as algorithmic generative art, and add English subtitles.",
    "I'm sending you a 45-second fireworks-display reel — extend to 2 minutes, render as James-Whistler nocturne, and overlay English captions.",
    "Uploading a 1-minute New-Year celebration reel — extend to 3 minutes, convert to Mary-Cassatt impressionist, and add English subtitles.",
    "Here's a 30-second Lunar-New-Year parade — extend to 90 seconds, style as Wu-Guanzhong, and overlay English captions.",
    "I have a 45-second Diwali celebration reel — extend to 2 minutes, render as Mughal miniature, and add English subtitles.",
    "Uploading a 1-minute Holi-festival reel — extend to 3 minutes, convert to Bhupen-Khakhar, and overlay English captions.",
    "Here's a 30-second Eid celebration reel — extend to 90 seconds, style as Iznik tile, and add English subtitles.",
    "I'm sending you a 45-second Hanukkah celebration reel — extend to 2 minutes, render as Yiddish theater poster, and overlay English captions.",
    "Uploading a 1-minute Easter Sunday reel — extend to 3 minutes, convert to Pre-Raphaelite Brotherhood, and add English subtitles.",
    "Here's a 30-second Christmas-Eve reel — extend to 90 seconds, style as Saul-Steinberg, and overlay English captions.",
    "I have a 45-second Halloween trick-or-treat reel — extend to 2 minutes, render as Edward-Gorey, and add English subtitles.",
    "Uploading a 1-minute Thanksgiving dinner reel — extend to 3 minutes, convert to James-Audubon ornithological plate, and overlay English captions.",
    "Here's a 30-second Sukkot meal reel — extend to 90 seconds, style as Maira-Kalman illustration, and add English subtitles.",
    "I'm sending you a 45-second Mid-Autumn festival reel — extend to 2 minutes, render as Qi-Baishi ink, and overlay English captions.",
    "Uploading a 1-minute Day-of-the-Dead reel — extend to 3 minutes, convert to José-Posada cordel, and add English subtitles.",
    "Here's a 30-second Carnival-Rio reel — extend to 90 seconds, style as Hélio-Oiticica, and overlay English captions.",
    "I have a 45-second Mardi-Gras reel — extend to 2 minutes, render as George-Rodrigue Blue-Dog, and add English subtitles.",
    "Uploading a 1-minute Oktoberfest reel — extend to 3 minutes, convert to Bavarian folk-illustration, and overlay English captions.",
    "Here's a 30-second Bastille-Day reel — extend to 90 seconds, style as Daumier caricature, and add English subtitles.",
    "I'm sending you a 45-second St-Patrick's-Day reel — extend to 2 minutes, render as Jim-Fitzpatrick Celtic, and overlay English captions.",
    "Uploading a 1-minute Cinco-de-Mayo reel — extend to 3 minutes, convert to José-Posada cordel, and add English subtitles.",
    "Here's a 30-second Independence-Day fireworks reel — extend to 90 seconds, style as Hopper Independence-Day, and overlay English captions.",
    "I have a 45-second Veterans-Day parade reel — extend to 2 minutes, render as Joe-Rosenthal photographic, and add English subtitles.",
    "Uploading a 1-minute Memorial-Day cemetery reel — extend to 3 minutes, convert to Ansel-Adams photograph, and overlay English captions.",
    "Here's a 30-second New-Year-Eve Times-Square reel — extend to 90 seconds, style as Edward-Hopper night, and add English subtitles.",
    "I'm sending you a 45-second Songkran-festival reel — extend to 2 minutes, render as Persian miniature, and overlay English captions.",
    "Uploading a 1-minute Vesak-festival reel — extend to 3 minutes, convert to Cambodian Angkor bas-relief, and add English subtitles.",
    "Here's a 30-second Pongal-festival reel — extend to 90 seconds, style as kolam rangoli pattern, and overlay English captions.",
    "I have a 45-second Onam-festival reel — extend to 2 minutes, render as Kerala-mural temple, and add English subtitles.",
    "Uploading a 1-minute Janmashtami reel — extend to 3 minutes, convert to Mithila Madhubani, and overlay English captions.",
    "Here's a 30-second Navaratri reel — extend to 90 seconds, style as Ravi-Varma, and add English subtitles.",
    "I'm sending you a 45-second Sankranti reel — extend to 2 minutes, render as Mughal miniature, and overlay English captions.",
    "Uploading a 1-minute Karva-Chauth reel — extend to 3 minutes, convert to Pahari Kangra miniature, and add English subtitles.",
    "Here's a 30-second Lohri reel — extend to 90 seconds, style as Punjabi folk-art, and overlay English captions.",
    # ── more upload + extend + style + subtitle requests (50) ──────────────
    "Uploading a 30-second tech-product-launch keynote — extend to 90 seconds, convert to cyberpunk-neon, and add English subtitles.",
    "Here's a 45-second e-commerce-haul reel — extend to 2 minutes, render as Andy-Warhol screenprint, and overlay English captions.",
    "I have a 1-minute fashion-haul reel — extend to 3 minutes, style as Jacqueline-Casey graphic, and add English subtitles.",
    "Uploading a 30-second holiday-haul reel — extend to 90 seconds, convert to Norman-Rockwell, and overlay English captions.",
    "Here's a 45-second unboxing reel — extend to 2 minutes, style as Eduardo-Paolozzi pop, and add English subtitles.",
    "I'm sending you a 30-second apartment-tour reel — extend to 90 seconds, render as Dutch-Golden-Age interior, and overlay English captions.",
    "Uploading a 1-minute tiny-house-tour reel — extend to 3 minutes, convert to Carl-Larsson watercolor, and add English subtitles.",
    "Here's a 45-second RV-tour reel — extend to 2 minutes, style as WPA National-Parks poster, and overlay English captions.",
    "I have a 30-second car-collection-tour reel — extend to 90 seconds, render as LeRoy-Neiman, and add English subtitles.",
    "Uploading a 1-minute wardrobe-tour reel — extend to 3 minutes, convert to Mucha Art-Nouveau, and overlay English captions.",
    "Here's a 30-second closet-tour reel — extend to 90 seconds, style as Pierre-Cardin sketch, and add English subtitles.",
    "I'm sending you a 45-second shoe-collection reel — extend to 2 minutes, render as Ed-Ruscha, and overlay English captions.",
    "Uploading a 1-minute handbag-collection reel — extend to 3 minutes, convert to Roy-Lichtenstein dot, and add English subtitles.",
    "Here's a 30-second watch-collection reel — extend to 90 seconds, style as Vermeer interior, and overlay English captions.",
    "I have a 45-second jewelry-collection reel — extend to 2 minutes, render as Klimt gold-leaf, and add English subtitles.",
    "Uploading a 1-minute kitchen-tour reel — extend to 3 minutes, convert to Vermeer interior, and overlay English captions.",
    "Here's a 30-second bathroom-tour reel — extend to 90 seconds, style as Hammershøi, and add English subtitles.",
    "I'm sending you a 45-second workout-room reel — extend to 2 minutes, render as Lichtenstein dot, and overlay English captions.",
    "Uploading a 1-minute home-theater reel — extend to 3 minutes, convert to Saul-Bass title, and add English subtitles.",
    "Here's a 30-second game-room reel — extend to 90 seconds, style as chiptune-pixel, and overlay English captions.",
    "I have a 45-second office-tour reel — extend to 2 minutes, render as Mondrian grid, and add English subtitles.",
    "Uploading a 1-minute workshop-tour reel — extend to 3 minutes, convert to Mary-Cassatt impressionist, and overlay English captions.",
    "Here's a 30-second studio-tour reel — extend to 90 seconds, style as Pollock action-painting, and add English subtitles.",
    "I'm sending you a 45-second atelier-tour reel — extend to 2 minutes, render as Vermeer atelier, and overlay English captions.",
    "Uploading a 1-minute bookstore-tour reel — extend to 3 minutes, convert to Saul-Steinberg, and add English subtitles.",
    "Here's a 30-second record-store-tour reel — extend to 90 seconds, style as Reid-Miles Blue-Note, and overlay English captions.",
    "I have a 45-second comic-shop-tour reel — extend to 2 minutes, render as Frank-Miller noir, and add English subtitles.",
    "Uploading a 1-minute toy-shop-tour reel — extend to 3 minutes, convert to Mary-Blair concept-art, and overlay English captions.",
    "Here's a 30-second candy-shop-tour reel — extend to 90 seconds, style as Wayne-Thiebaud cake-pop, and add English subtitles.",
    "I'm sending you a 45-second coffee-shop-tour reel — extend to 2 minutes, render as Hopper urban-loneliness, and overlay English captions.",
    "Uploading a 1-minute bakery-tour reel — extend to 3 minutes, convert to Renoir Boating-Party, and add English subtitles.",
    "Here's a 30-second flower-shop-tour reel — extend to 90 seconds, style as Berthe-Morisot impressionist, and overlay English captions.",
    "I have a 45-second plant-shop-tour reel — extend to 2 minutes, render as Henri-Rousseau jungle, and add English subtitles.",
    "Uploading a 1-minute pet-shop-tour reel — extend to 3 minutes, convert to Beatrix-Potter watercolor, and overlay English captions.",
    "Here's a 30-second aquarium-tour reel — extend to 90 seconds, style as Yves-Klein blue, and add English subtitles.",
    "I'm sending you a 45-second wax-museum reel — extend to 2 minutes, render as Madame-Tussaud illustration, and overlay English captions.",
    "Uploading a 1-minute art-gallery reel — extend to 3 minutes, convert to Rembrandt portrait, and add English subtitles.",
    "Here's a 30-second modern-art-museum reel — extend to 90 seconds, style as Rothko color-field, and overlay English captions.",
    "I have a 45-second natural-history-museum reel — extend to 2 minutes, render as Audubon ornithological plate, and add English subtitles.",
    "Uploading a 1-minute science-museum reel — extend to 3 minutes, convert to Eames Powers-of-Ten, and overlay English captions.",
    "Here's a 30-second transportation-museum reel — extend to 90 seconds, style as Stuart-Davis, and add English subtitles.",
    "I'm sending you a 45-second children's-museum reel — extend to 2 minutes, render as Eric-Carle collage, and overlay English captions.",
    "Uploading a 1-minute planetarium reel — extend to 3 minutes, convert to astronomical illumination, and add English subtitles.",
    "Here's a 30-second observatory reel — extend to 90 seconds, style as astronomical illumination, and overlay English captions.",
    "I have a 45-second zoo-tour reel — extend to 2 minutes, render as James-Audubon plate, and add English subtitles.",
    "Uploading a 1-minute botanical-garden reel — extend to 3 minutes, convert to Maria-Sibylla-Merian botanical, and overlay English captions.",
    "Here's a 30-second greenhouse-tour reel — extend to 90 seconds, style as Jan-Brueghel still-life, and add English subtitles.",
    "I'm sending you a 45-second butterfly-house reel — extend to 2 minutes, render as Damien-Hirst spot-painting, and overlay English captions.",
    "Uploading a 1-minute bird-sanctuary reel — extend to 3 minutes, convert to Charley-Harper, and add English subtitles.",
    "Here's a 30-second reptile-house reel — extend to 90 seconds, style as Maurice-Sendak storybook, and overlay English captions.",
    # ── more outdoor-sports / nature-doc + naturalist art-style + subtitle (50) ──
    "I'm sending you a 30-second mountain-summit reel — extend to 90 seconds, style as Caspar-David-Friedrich, and add English subtitles.",
    "Uploading a 45-second alpine-glacier reel — extend to 2 minutes, render as Albert-Bierstadt sublime, and overlay English captions.",
    "Here's a 1-minute fjord-kayak reel — extend to 3 minutes, convert to Edvard-Munch Norwegian, and add English subtitles.",
    "I have a 30-second savanna-safari reel — extend to 90 seconds, style as Jamini-Roy folk, and overlay English captions.",
    "Uploading a 45-second jungle-trek reel — extend to 2 minutes, render as Henri-Rousseau jungle, and add English subtitles.",
    "Here's a 1-minute coral-reef-dive reel — extend to 3 minutes, convert to Ernst-Haeckel Kunstformen, and overlay English captions.",
    "I'm sending you a 30-second whale-watching reel — extend to 90 seconds, style as Hokusai sea-wave, and add English subtitles.",
    "Uploading a 45-second polar-bear reel — extend to 2 minutes, render as Karel-Appel CoBrA, and overlay English captions.",
    "Here's a 1-minute Arctic-tundra reel — extend to 3 minutes, convert to Lawren-Harris Group-of-Seven, and add English subtitles.",
    "I have a 30-second Antarctic-emperor-penguin reel — extend to 90 seconds, style as Frederic-Edwin-Church polar, and overlay English captions.",
    "Uploading a 45-second redwood-forest reel — extend to 2 minutes, render as Maxfield-Parrish luminous, and add English subtitles.",
    "Here's a 1-minute desert-dune reel — extend to 3 minutes, convert to Georgia-O'Keeffe Southwestern, and overlay English captions.",
    "I'm sending you a 30-second canyon-vista reel — extend to 90 seconds, style as Thomas-Moran Yellowstone, and add English subtitles.",
    "Uploading a 45-second waterfall-Kauai reel — extend to 2 minutes, render as Frederic-Edwin-Church Andes, and overlay English captions.",
    "Here's a 1-minute Iguazu-falls reel — extend to 3 minutes, convert to Tarsila-do-Amaral modernist, and add English subtitles.",
    "I have a 30-second coral-spawning reel — extend to 90 seconds, style as Ernst-Haeckel marine, and overlay English captions.",
    "Uploading a 45-second deep-sea reel — extend to 2 minutes, render as J.M.W.-Turner sea-mist, and add English subtitles.",
    "Here's a 1-minute kelp-forest reel — extend to 3 minutes, convert to Anna-Atkins cyanotype, and overlay English captions.",
    "I'm sending you a 30-second tide-pool reel — extend to 90 seconds, style as Beatrix-Potter naturalist, and add English subtitles.",
    "Uploading a 45-second bird-migration reel — extend to 2 minutes, render as Charley-Harper minimal, and overlay English captions.",
    "Here's a 1-minute meadow-flowers reel — extend to 3 minutes, convert to Pierre-Joseph-Redouté botanical, and add English subtitles.",
    "I have a 30-second alpine-meadow reel — extend to 90 seconds, style as Ferdinand-Hodler Swiss, and overlay English captions.",
    "Uploading a 45-second lavender-field reel — extend to 2 minutes, render as Vincent-van-Gogh Provençal, and add English subtitles.",
    "Here's a 1-minute sunflower-field reel — extend to 3 minutes, convert to Vincent-van-Gogh Arles, and overlay English captions.",
    "I'm sending you a 30-second cherry-blossom reel — extend to 90 seconds, style as Hiroshige meisho-e, and add English subtitles.",
    "Uploading a 45-second tulip-field reel — extend to 2 minutes, render as Jan-Brueghel-the-Elder still-life, and overlay English captions.",
    "Here's a 1-minute autumn-foliage reel — extend to 3 minutes, convert to Tom-Thomson Algonquin, and add English subtitles.",
    "I have a 30-second salmon-run reel — extend to 90 seconds, style as Bill-Reid Haida, and overlay English captions.",
    "Uploading a 45-second eagle-nesting reel — extend to 2 minutes, render as Louis-Agassiz-Fuertes ornithological, and add English subtitles.",
    "Here's a 1-minute rock-climbing reel — extend to 3 minutes, convert to Maxfield-Parrish illustration, and overlay English captions.",
    "I'm sending you a 30-second mountain-biking reel — extend to 90 seconds, style as Charles-Russell Western, and add English subtitles.",
    "Uploading a 45-second trail-running reel — extend to 2 minutes, render as N.C.-Wyeth illustration, and overlay English captions.",
    "Here's a 1-minute ice-climbing reel — extend to 3 minutes, convert to Arnold-Böcklin symbolist, and add English subtitles.",
    "I have a 30-second base-jumping reel — extend to 90 seconds, style as Anne-Brigman pictorialist, and overlay English captions.",
    "Uploading a 45-second wing-suit reel — extend to 2 minutes, render as F.T.-Marinetti Futurist, and add English subtitles.",
    "Here's a 1-minute paragliding reel — extend to 3 minutes, convert to Marc-Chagall lyrical, and overlay English captions.",
    "I'm sending you a 30-second hot-air-balloon reel — extend to 90 seconds, style as Eugène-Boudin sky, and add English subtitles.",
    "Uploading a 45-second sky-diving reel — extend to 2 minutes, render as Robert-Delaunay rhythm, and overlay English captions.",
    "Here's a 1-minute surfing reel — extend to 3 minutes, convert to John-Severson Surfer-magazine, and add English subtitles.",
    "I have a 30-second wind-surfing reel — extend to 90 seconds, style as Raoul-Dufy regatta, and overlay English captions.",
    "Uploading a 45-second kite-surfing reel — extend to 2 minutes, render as Joaquín-Sorolla beach, and add English subtitles.",
    "Here's a 1-minute kayaking-rapids reel — extend to 3 minutes, convert to Winslow-Homer canoe, and overlay English captions.",
    "I'm sending you a 30-second white-water-rafting reel — extend to 90 seconds, style as George-Catlin Western, and add English subtitles.",
    "Uploading a 45-second standup-paddleboard reel — extend to 2 minutes, render as Childe-Hassam impressionist, and overlay English captions.",
    "Here's a 1-minute open-water-swim reel — extend to 3 minutes, convert to Eakins athletic-realism, and add English subtitles.",
    "I have a 30-second free-diving reel — extend to 90 seconds, style as Henri-Matisse swimming-pool, and overlay English captions.",
    "Uploading a 45-second snorkel-tour reel — extend to 2 minutes, render as Audubon Birds-of-America, and add English subtitles.",
    "Here's a 1-minute scuba-diving reel — extend to 3 minutes, convert to Yves-Tanguy biomorphic, and overlay English captions.",
    "I'm sending you a 30-second cave-diving reel — extend to 90 seconds, style as Odilon-Redon noirs, and add English subtitles.",
    "Uploading a 45-second cenote-dive reel — extend to 2 minutes, render as Diego-Rivera mural, and overlay English captions.",
    # ── more workshop / craft / artisan demo reels + craft-art-style + subtitle (50) ──
    "I have a 30-second pottery-wheel-throwing reel — extend to 90 seconds, style as Greek-black-figure, and add English subtitles.",
    "Uploading a 45-second hand-built-coil-pot reel — extend to 2 minutes, render as Maria-Martinez-pueblo, and overlay English captions.",
    "Here's a 1-minute kintsugi-gold-mend reel — extend to 3 minutes, convert to Japanese-Edo-woodblock, and add English subtitles.",
    "I'm sending you a 30-second wood-lathe-turning reel — extend to 90 seconds, style as Shaker-furniture-print, and overlay English captions.",
    "Uploading a 45-second Windsor-chair-bodging reel — extend to 2 minutes, render as Eric-Sloane Americana, and add English subtitles.",
    "Here's a 1-minute Japanese-joinery reel — extend to 3 minutes, convert to Hokusai-Manga-folio, and overlay English captions.",
    "I have a 30-second timber-frame-raising reel — extend to 90 seconds, style as Currier-Ives American, and add English subtitles.",
    "Uploading a 45-second blacksmith-forge-weld reel — extend to 2 minutes, render as American-Realist-Bellows, and overlay English captions.",
    "Here's a 1-minute farrier-horseshoe reel — extend to 3 minutes, convert to George-Stubbs-equine-plate, and add English subtitles.",
    "I'm sending you a 30-second copper-repoussé reel — extend to 90 seconds, style as Persian-Safavid-metal-plate, and overlay English captions.",
    "Uploading a 45-second silver-filigree reel — extend to 2 minutes, render as Mughal-darbar miniature, and add English subtitles.",
    "Here's a 1-minute gold-leaf-gilding reel — extend to 3 minutes, convert to Byzantine-icon-gold-leaf, and overlay English captions.",
    "I have a 30-second silk-screen-printing reel — extend to 90 seconds, style as Andy-Warhol-screen, and add English subtitles.",
    "Uploading a 45-second linocut-block-printing reel — extend to 2 minutes, render as German-Expressionist-Kirchner, and overlay English captions.",
    "Here's a 1-minute woodblock-printing reel — extend to 3 minutes, convert to Hokusai-ukiyoe-2, and add English subtitles.",
    "I'm sending you a 30-second copper-etching reel — extend to 90 seconds, style as Rembrandt-etching, and overlay English captions.",
    "Uploading a 45-second mezzotint-printing reel — extend to 2 minutes, render as English-Country-mezzotint, and add English subtitles.",
    "Here's a 1-minute lithography-stone-pull reel — extend to 3 minutes, convert to Honoré-Daumier-political, and overlay English captions.",
    "I have a 30-second letterpress-printing reel — extend to 90 seconds, style as Eric-Gill-Perpetua-type, and add English subtitles.",
    "Uploading a 45-second moveable-type-setting reel — extend to 2 minutes, render as Aldus-Manutius-page, and overlay English captions.",
    "Here's a 1-minute bookbinding-Coptic-stitch reel — extend to 3 minutes, convert to Coptic-illumination, and add English subtitles.",
    "I'm sending you a 30-second leather-tooling reel — extend to 90 seconds, style as Spanish-Moorish-leather, and overlay English captions.",
    "Uploading a 45-second saddle-stitch-leather reel — extend to 2 minutes, render as Western-leather-stamp, and add English subtitles.",
    "Here's a 1-minute glass-blowing-cane reel — extend to 3 minutes, convert to Murano-Venetian-glass, and overlay English captions.",
    "I have a 30-second stained-glass-soldering reel — extend to 90 seconds, style as Chartres-cathedral-window, and add English subtitles.",
    "Uploading a 45-second flame-worked-bead reel — extend to 2 minutes, render as Egyptian-faience-bead, and overlay English captions.",
    "Here's a 1-minute lapidary-cabbing reel — extend to 3 minutes, convert to Mughal-jeweled-portrait, and add English subtitles.",
    "I'm sending you a 30-second filigree-enamel reel — extend to 90 seconds, style as Russian-Fabergé-enamel, and overlay English captions.",
    "Uploading a 45-second cloisonné-enamel reel — extend to 2 minutes, render as Chinese-Cloisonné-Ming, and add English subtitles.",
    "Here's a 1-minute champlevé-enamel reel — extend to 3 minutes, convert to Limoges-Romanesque-enamel, and overlay English captions.",
    "I have a 30-second floor-loom-weaving reel — extend to 90 seconds, style as Navajo-rug-textile, and add English subtitles.",
    "Uploading a 45-second backstrap-loom reel — extend to 2 minutes, render as Andean-textile-pre-Columbian, and overlay English captions.",
    "Here's a 1-minute tapestry-weaving reel — extend to 3 minutes, convert to Bayeux-tapestry, and add English subtitles.",
    "I'm sending you a 30-second basket-weaving reel — extend to 90 seconds, style as Cherokee-river-cane-basket, and overlay English captions.",
    "Uploading a 45-second rope-twisting reel — extend to 2 minutes, render as nautical-rope-chart, and add English subtitles.",
    "Here's a 1-minute cordage-making reel — extend to 3 minutes, convert to Maori-flax-textile, and overlay English captions.",
    "I have a 30-second felt-making reel — extend to 90 seconds, style as Mongolian-felt-yurt, and add English subtitles.",
    "Uploading a 45-second indigo-dyeing reel — extend to 2 minutes, render as Japanese-aizome-indigo, and overlay English captions.",
    "Here's a 1-minute batik-wax-resist reel — extend to 3 minutes, convert to Javanese-batik-classical, and add English subtitles.",
    "I'm sending you a 30-second tie-dye-shibori reel — extend to 90 seconds, style as Japanese-shibori, and overlay English captions.",
    "Uploading a 45-second mokume-gane reel — extend to 2 minutes, render as Japanese-tsuba-mokume, and add English subtitles.",
    "Here's a 1-minute damascus-steel-folding reel — extend to 3 minutes, convert to Persian-Safavid-shamshir, and overlay English captions.",
    "I have a 30-second sword-polishing reel — extend to 90 seconds, style as Japanese-sword-polishing-print, and add English subtitles.",
    "Uploading a 45-second knife-grinding reel — extend to 2 minutes, render as Sheffield-cutlery, and overlay English captions.",
    "Here's a 1-minute violin-luthier-bench reel — extend to 3 minutes, convert to Cremona-luthier, and add English subtitles.",
    "I'm sending you a 30-second piano-tuning reel — extend to 90 seconds, style as Bösendorfer-blueprint, and overlay English captions.",
    "Uploading a 45-second harpsichord-quill reel — extend to 2 minutes, render as Flemish-harpsichord-page, and add English subtitles.",
    "Here's a 1-minute organ-pipe-voicing reel — extend to 3 minutes, convert to Schnitger-Baroque-organ, and overlay English captions.",
    "I have a 30-second mandolin-fretting reel — extend to 90 seconds, style as Neapolitan-mandolin-poster, and add English subtitles.",
    "Uploading a 45-second fiddle-bow-rehairing reel — extend to 2 minutes, render as Appalachian-fiddle-print, and overlay English captions.",
    # ── more textile / weaving / knitting demos + folk-art styles (50) ──
    "Uploading a 30-second Navajo-rug-weaving reel — extend to 90 seconds, convert to Navajo-Two-Grey-Hills-pattern, and add English subtitles.",
    "Here's a 45-second Pendleton-blanket-weaving reel — extend to 2 minutes, render as Pendleton-trade-blanket-print, and overlay English captions.",
    "I have a 1-minute Saori-loom-Japan reel — extend to 3 minutes, style as Saori-freeform-print, and add English subtitles.",
    "Uploading a 30-second Tibetan-thangka-embroidery reel — extend to 90 seconds, convert to Tibetan-thangka-style, and overlay English captions.",
    "Here's a 45-second Bhutanese-kira-weaving reel — extend to 2 minutes, render as Bhutanese-textile-print, and add English subtitles.",
    "I'm sending you a 1-minute Naga-shawl-weaving reel — extend to 3 minutes, style as Naga-warrior-shawl-print, and overlay English captions.",
    "Uploading a 30-second Banaras-silk-brocade reel — extend to 90 seconds, convert to Banarasi-silk-pattern, and add English subtitles.",
    "Here's a 45-second Kanchipuram-silk-weaving reel — extend to 2 minutes, render as Kanchipuram-silk-print, and overlay English captions.",
    "I have a 1-minute Pashmina-shawl-Kashmir reel — extend to 3 minutes, style as Kashmiri-jamawar-print, and add English subtitles.",
    "Uploading a 30-second Bhujodi-shawl-weaving reel — extend to 90 seconds, convert to Kachchhi-Rabari-print, and overlay English captions.",
    "Here's a 45-second Patola-silk-double-ikat reel — extend to 2 minutes, render as Patan-Patola-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Kalamkari-block-print reel — extend to 3 minutes, style as Andhra-Kalamkari-print, and overlay English captions.",
    "Uploading a 30-second Ajrakh-block-print reel — extend to 90 seconds, convert to Sindhi-Ajrakh-pattern, and add English subtitles.",
    "Here's a 45-second Bagru-block-print reel — extend to 2 minutes, render as Rajasthan-Bagru-print, and overlay English captions.",
    "I have a 1-minute Sanganeri-block-print reel — extend to 3 minutes, style as Sanganeri-floral-print, and add English subtitles.",
    "Uploading a 30-second Madhubani-painting reel — extend to 90 seconds, convert to Mithila-Madhubani-style, and overlay English captions.",
    "Here's a 45-second Warli-painting reel — extend to 2 minutes, render as Maharashtra-Warli-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Pattachitra-Odisha reel — extend to 3 minutes, style as Pattachitra-palm-leaf, and overlay English captions.",
    "Uploading a 30-second Gond-tribal-painting reel — extend to 90 seconds, convert to Gond-Madhya-Pradesh-pattern, and add English subtitles.",
    "Here's a 45-second Phulkari-embroidery reel — extend to 2 minutes, render as Punjabi-Phulkari-pattern, and overlay English captions.",
    "I have a 1-minute Chikankari-Lucknow reel — extend to 3 minutes, style as Awadhi-Chikankari-print, and add English subtitles.",
    "Uploading a 30-second Persian-rug-knotting-Tabriz reel — extend to 90 seconds, convert to Tabriz-medallion-pattern, and overlay English captions.",
    "Here's a 45-second Persian-rug-knotting-Isfahan reel — extend to 2 minutes, render as Isfahan-floral-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Persian-rug-knotting-Kashan reel — extend to 3 minutes, style as Kashan-medallion-pattern, and overlay English captions.",
    "Uploading a 30-second Persian-rug-knotting-Qom reel — extend to 90 seconds, convert to Qom-silk-pattern, and add English subtitles.",
    "Here's a 45-second Turkish-kilim-Konya reel — extend to 2 minutes, render as Anatolian-kilim-pattern, and overlay English captions.",
    "I have a 1-minute Turkmen-rug-knotting-Tekke reel — extend to 3 minutes, style as Turkmen-Tekke-gul-pattern, and add English subtitles.",
    "Uploading a 30-second Caucasian-rug-Shirvan reel — extend to 90 seconds, convert to Shirvan-prayer-rug-pattern, and overlay English captions.",
    "Here's a 45-second Berber-rug-Beni-Ourain reel — extend to 2 minutes, render as Beni-Ourain-Atlas-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Berber-rug-Boucherouite reel — extend to 3 minutes, style as Boucherouite-recycled-pattern, and overlay English captions.",
    "Uploading a 30-second Egyptian-cotton-weaving reel — extend to 90 seconds, convert to Tally-Egyptian-print, and add English subtitles.",
    "Here's a 45-second Coptic-tapestry-weaving reel — extend to 2 minutes, render as Coptic-textile-print, and overlay English captions.",
    "I have a 1-minute Ethiopian-shamma-weaving reel — extend to 3 minutes, style as Habesha-shamma-print, and add English subtitles.",
    "Uploading a 30-second Ndebele-beadwork reel — extend to 90 seconds, convert to Ndebele-house-pattern, and overlay English captions.",
    "Here's a 45-second Zulu-beadwork reel — extend to 2 minutes, render as Zulu-isishunka-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Yoruba-adire-indigo reel — extend to 3 minutes, style as Yoruba-adire-pattern, and overlay English captions.",
    "Uploading a 30-second Akan-kente-weaving reel — extend to 90 seconds, convert to Asante-kente-pattern, and add English subtitles.",
    "Here's a 45-second Ewe-kente-weaving reel — extend to 2 minutes, render as Ewe-kente-pattern, and overlay English captions.",
    "I have a 1-minute Bogolan-mud-cloth reel — extend to 3 minutes, style as Bamana-bogolan-pattern, and add English subtitles.",
    "Uploading a 30-second Maya-backstrap-loom reel — extend to 90 seconds, convert to Tzotzil-Chiapas-pattern, and overlay English captions.",
    "Here's a 45-second Otomi-embroidery reel — extend to 2 minutes, render as Tenango-Otomi-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Zapotec-rug-Teotitlan reel — extend to 3 minutes, style as Zapotec-Teotitlan-pattern, and overlay English captions.",
    "Uploading a 30-second Quechua-aguayo-weaving reel — extend to 90 seconds, convert to Quechua-aguayo-pattern, and add English subtitles.",
    "Here's a 45-second Aymara-textile-weaving reel — extend to 2 minutes, render as Aymara-Bolivia-pattern, and overlay English captions.",
    "I have a 1-minute Mapuche-witral-weaving reel — extend to 3 minutes, style as Mapuche-witral-pattern, and add English subtitles.",
    "Uploading a 30-second Andean-chullo-knitting reel — extend to 90 seconds, convert to Taquile-Island-pattern, and overlay English captions.",
    "Here's a 45-second Sami-Lapland-weaving reel — extend to 2 minutes, render as Sami-grene-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Faroese-knitting reel — extend to 3 minutes, style as Faroese-yoke-pattern, and overlay English captions.",
    "Uploading a 30-second Aran-knitting-Ireland reel — extend to 90 seconds, convert to Aran-Cabling-pattern, and add English subtitles.",
    "Here's a 45-second Fair-Isle-knitting reel — extend to 2 minutes, render as Fair-Isle-pattern, and overlay English captions.",
    # ── more woodworking / luthier / leatherwork demos + folk-art / Arts-and-Crafts styles (50) ──
    "Uploading a 30-second Shaker-table-mortise reel — extend to 90 seconds, convert to Shaker-furniture-print, and add English subtitles.",
    "Here's a 45-second Pennsylvania-Dutch-dough-box reel — extend to 2 minutes, render as Pennsylvania-Dutch-fraktur, and overlay English captions.",
    "I have a 1-minute Adirondack-twig-rocker reel — extend to 3 minutes, style as Adirondack-rustic-print, and add English subtitles.",
    "Uploading a 30-second Windsor-chair-spindle reel — extend to 90 seconds, convert to Windsor-chair-print, and overlay English captions.",
    "Here's a 45-second Greene-and-Greene-bungalow-joinery reel — extend to 2 minutes, render as Greene-and-Greene-bungalow-print, and add English subtitles.",
    "I'm sending you a 1-minute Stickley-Mission-mortise reel — extend to 3 minutes, style as Stickley-Mission-print, and overlay English captions.",
    "Uploading a 30-second Roycroft-bookbinding reel — extend to 90 seconds, convert to Roycroft-Arts-and-Crafts, and add English subtitles.",
    "Here's a 45-second Nakashima-walnut-slab reel — extend to 2 minutes, render as Nakashima-Conoid-print, and overlay English captions.",
    "I have a 1-minute Maloof-rocker-shaping reel — extend to 3 minutes, style as Maloof-rocker-print, and add English subtitles.",
    "Uploading a 30-second Krenov-cabinet-dovetail reel — extend to 90 seconds, convert to Krenov-cabinet-print, and overlay English captions.",
    "Here's a 45-second Welsh-spoon-carving reel — extend to 2 minutes, render as Welsh-love-spoon-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Norwegian-acanthus-carving reel — extend to 3 minutes, style as Norwegian-akantus-print, and overlay English captions.",
    "Uploading a 30-second Russian-khokhloma-bowl-painting reel — extend to 90 seconds, convert to Khokhloma-pattern, and add English subtitles.",
    "Here's a 45-second Russian-matryoshka-painting reel — extend to 2 minutes, render as Sergiev-Posad-pattern, and overlay English captions.",
    "I have a 1-minute Russian-Palekh-lacquer-box reel — extend to 3 minutes, style as Palekh-miniature-pattern, and add English subtitles.",
    "Uploading a 30-second Russian-Gzhel-blue-pottery reel — extend to 90 seconds, convert to Gzhel-pattern, and overlay English captions.",
    "Here's a 45-second Tibetan-thangka-pigment-grinding reel — extend to 2 minutes, render as Tibetan-thangka-print-2, and add English subtitles.",
    "I'm sending you a 1-minute Bhutanese-thanka-mineral-paint reel — extend to 3 minutes, style as Bhutanese-thanka-print, and overlay English captions.",
    "Uploading a 30-second Mongolian-felt-yurt reel — extend to 90 seconds, convert to Mongolian-felt-pattern, and add English subtitles.",
    "Here's a 45-second Kyrgyz-shyrdak-felt reel — extend to 2 minutes, render as Kyrgyz-shyrdak-pattern, and overlay English captions.",
    "I have a 1-minute Uzbek-suzani-embroidery reel — extend to 3 minutes, style as Uzbek-suzani-pattern, and add English subtitles.",
    "Uploading a 30-second Persian-miniature-illumination reel — extend to 90 seconds, convert to Safavid-miniature-pattern, and overlay English captions.",
    "Here's a 45-second Turkish-iznik-tile-painting reel — extend to 2 minutes, render as Iznik-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Moroccan-zellige-tilework reel — extend to 3 minutes, style as Moroccan-zellige-pattern, and overlay English captions.",
    "Uploading a 30-second Andalusian-azulejo-tile reel — extend to 90 seconds, convert to Andalusian-azulejo-pattern, and add English subtitles.",
    "Here's a 45-second Portuguese-azulejo-painting reel — extend to 2 minutes, render as Portuguese-azulejo-pattern, and overlay English captions.",
    "I have a 1-minute Talavera-Puebla-pottery reel — extend to 3 minutes, style as Talavera-Puebla-pattern, and add English subtitles.",
    "Uploading a 30-second Mata-Ortiz-pottery reel — extend to 90 seconds, convert to Mata-Ortiz-pattern, and overlay English captions.",
    "Here's a 45-second Pueblo-pottery-coiling reel — extend to 2 minutes, render as Acoma-Pueblo-pattern, and add English subtitles.",
    "I'm sending you a 1-minute San-Ildefonso-blackware reel — extend to 3 minutes, style as San-Ildefonso-blackware-pattern, and overlay English captions.",
    "Uploading a 30-second Maria-Martinez-blackware reel — extend to 90 seconds, convert to Maria-Martinez-pattern, and add English subtitles.",
    "Here's a 45-second Hopi-katsina-doll-carving reel — extend to 2 minutes, render as Hopi-katsina-pattern, and overlay English captions.",
    "I have a 1-minute Zuni-fetish-carving reel — extend to 3 minutes, style as Zuni-fetish-pattern, and add English subtitles.",
    "Uploading a 30-second Inuit-soapstone-carving reel — extend to 90 seconds, convert to Inuit-soapstone-print, and overlay English captions.",
    "Here's a 45-second Northwest-Coast-totem-carving reel — extend to 2 minutes, render as Haida-totem-print, and add English subtitles.",
    "I'm sending you a 1-minute Tlingit-Chilkat-blanket-weaving reel — extend to 3 minutes, style as Chilkat-pattern, and overlay English captions.",
    "Uploading a 30-second Haida-argillite-carving reel — extend to 90 seconds, convert to Haida-argillite-pattern, and add English subtitles.",
    "Here's a 45-second Sámi-knife-handle-carving reel — extend to 2 minutes, render as Sámi-duodji-print, and overlay English captions.",
    "I have a 1-minute Rosemaling-Norwegian-painting reel — extend to 3 minutes, style as Rosemaling-pattern, and add English subtitles.",
    "Uploading a 30-second Dalecarlian-horse-painting reel — extend to 90 seconds, convert to Dala-horse-pattern, and overlay English captions.",
    "Here's a 45-second Kurbits-Swedish-folk-painting reel — extend to 2 minutes, render as Kurbits-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Polish-Wycinanki-paper-cutting reel — extend to 3 minutes, style as Wycinanki-pattern, and overlay English captions.",
    "Uploading a 30-second Polish-Łowicz-paper-cut reel — extend to 90 seconds, convert to Łowicz-pattern, and add English subtitles.",
    "Here's a 45-second Czech-Easter-egg-Kraslice reel — extend to 2 minutes, render as Kraslice-pattern, and overlay English captions.",
    "I have a 1-minute Ukrainian-pysanka-egg reel — extend to 3 minutes, style as Pysanka-pattern, and add English subtitles.",
    "Uploading a 30-second Hungarian-Kalocsa-embroidery reel — extend to 90 seconds, convert to Kalocsa-pattern, and overlay English captions.",
    "Here's a 45-second Hungarian-Matyó-embroidery reel — extend to 2 minutes, render as Matyó-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Romanian-ie-blouse-embroidery reel — extend to 3 minutes, style as Romanian-ie-pattern, and overlay English captions.",
    "Uploading a 30-second Bulgarian-Šopski-embroidery reel — extend to 90 seconds, convert to Bulgarian-Šopski-pattern, and add English subtitles.",
    "Here's a 45-second Greek-Karpathos-embroidery reel — extend to 2 minutes, render as Karpathos-pattern, and overlay English captions.",
    # ── more ceramic / pottery / glass demos + traditional ceramic-pattern styles (50) ──
    "Uploading a 30-second Jingdezhen-Ming-Imperial-kiln reel — extend to 90 seconds, convert to Jingdezhen-blue-and-white, and add English subtitles.",
    "Here's a 45-second Jingdezhen-Qing-famille-rose reel — extend to 2 minutes, render as Qing-famille-rose-pattern, and overlay English captions.",
    "I have a 1-minute Yixing-purple-clay-teapot reel — extend to 3 minutes, style as Yixing-zisha-pattern, and add English subtitles.",
    "Uploading a 30-second Longquan-celadon reel — extend to 90 seconds, convert to Longquan-celadon-glaze, and overlay English captions.",
    "Here's a 45-second Dehua-blanc-de-Chine reel — extend to 2 minutes, render as Dehua-blanc-de-Chine, and add English subtitles.",
    "I'm sending you a 1-minute Bizen-yaki-Japanese reel — extend to 3 minutes, style as Bizen-yaki-pattern, and overlay English captions.",
    "Uploading a 30-second Mashiko-yaki reel — extend to 90 seconds, convert to Mashiko-yaki-pattern, and add English subtitles.",
    "Here's a 45-second Hagi-yaki-tea-bowl reel — extend to 2 minutes, render as Hagi-yaki-pattern, and overlay English captions.",
    "I have a 1-minute Kakiemon-Arita reel — extend to 3 minutes, style as Kakiemon-Arita-pattern, and add English subtitles.",
    "Uploading a 30-second Imari-porcelain reel — extend to 90 seconds, convert to Imari-porcelain-pattern, and overlay English captions.",
    "Here's a 45-second Korean-Joseon-Buncheong reel — extend to 2 minutes, render as Buncheong-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Goryeo-celadon reel — extend to 3 minutes, style as Goryeo-celadon-glaze, and overlay English captions.",
    "Uploading a 30-second Khmer-Angkorian-pottery reel — extend to 90 seconds, convert to Khmer-Angkorian-pattern, and add English subtitles.",
    "Here's a 45-second Sukhothai-pottery reel — extend to 2 minutes, render as Sukhothai-pottery-pattern, and overlay English captions.",
    "I have a 1-minute Ban-Chiang-pottery reel — extend to 3 minutes, style as Ban-Chiang-spiral-pattern, and add English subtitles.",
    "Uploading a 30-second Vietnamese-Bat-Trang reel — extend to 90 seconds, convert to Bat-Trang-pattern, and overlay English captions.",
    "Here's a 45-second Hoi-An-Thanh-Ha-pottery reel — extend to 2 minutes, render as Thanh-Ha-pottery-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Iznik-Turkish-tile reel — extend to 3 minutes, style as Iznik-tile-pattern, and overlay English captions.",
    "Uploading a 30-second Kütahya-Turkish-pottery reel — extend to 90 seconds, convert to Kütahya-pottery-pattern, and add English subtitles.",
    "Here's a 45-second Çanakkale-Turkish-pottery reel — extend to 2 minutes, render as Çanakkale-pottery-pattern, and overlay English captions.",
    "I have a 1-minute Persian-Kashan-pottery reel — extend to 3 minutes, style as Kashan-lustre-pattern, and add English subtitles.",
    "Uploading a 30-second Persian-Mina-Kari-enamel reel — extend to 90 seconds, convert to Mina-Kari-pattern, and overlay English captions.",
    "Here's a 45-second Persian-Khatam-marquetry reel — extend to 2 minutes, render as Khatam-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Moroccan-Fes-Blue-pottery reel — extend to 3 minutes, style as Fes-blue-pattern, and overlay English captions.",
    "Uploading a 30-second Moroccan-Safi-pottery reel — extend to 90 seconds, convert to Safi-Moroccan-pattern, and add English subtitles.",
    "Here's a 45-second Tunisian-Nabeul-pottery reel — extend to 2 minutes, render as Nabeul-Tunisian-pattern, and overlay English captions.",
    "I have a 1-minute Egyptian-Fustat-pottery reel — extend to 3 minutes, style as Fatimid-pottery-pattern, and add English subtitles.",
    "Uploading a 30-second Greek-black-figure-vase reel — extend to 90 seconds, convert to Attic-black-figure-pattern, and overlay English captions.",
    "Here's a 45-second Greek-red-figure-vase reel — extend to 2 minutes, render as Attic-red-figure-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Etruscan-Bucchero-pottery reel — extend to 3 minutes, style as Etruscan-Bucchero-pattern, and overlay English captions.",
    "Uploading a 30-second Italian-Maiolica-Faenza reel — extend to 90 seconds, convert to Faenza-Maiolica-pattern, and add English subtitles.",
    "Here's a 45-second Italian-Maiolica-Deruta reel — extend to 2 minutes, render as Deruta-Maiolica-pattern, and overlay English captions.",
    "I have a 1-minute Italian-Sicilian-Caltagirone-pottery reel — extend to 3 minutes, style as Caltagirone-pattern, and add English subtitles.",
    "Uploading a 30-second French-Sèvres-porcelain reel — extend to 90 seconds, convert to Sèvres-porcelain-pattern, and overlay English captions.",
    "Here's a 45-second French-Limoges-porcelain reel — extend to 2 minutes, render as Limoges-porcelain-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Dutch-Delftware reel — extend to 3 minutes, style as Delft-blue-pattern, and overlay English captions.",
    "Uploading a 30-second German-Meissen-porcelain reel — extend to 90 seconds, convert to Meissen-pattern, and add English subtitles.",
    "Here's a 45-second German-Nymphenburg-porcelain reel — extend to 2 minutes, render as Nymphenburg-pattern, and overlay English captions.",
    "I have a 1-minute Czech-Karlovy-Vary-porcelain reel — extend to 3 minutes, style as Karlovy-Vary-pattern, and add English subtitles.",
    "Uploading a 30-second Hungarian-Herend-porcelain reel — extend to 90 seconds, convert to Herend-pattern, and overlay English captions.",
    "Here's a 45-second Russian-Gzhel-blue-pottery reel — extend to 2 minutes, render as Gzhel-pattern-2, and add English subtitles.",
    "I'm sending you a 1-minute Russian-Lomonosov-porcelain reel — extend to 3 minutes, style as Lomonosov-pattern, and overlay English captions.",
    "Uploading a 30-second Polish-Bolesławiec-pottery reel — extend to 90 seconds, convert to Bolesławiec-pattern, and add English subtitles.",
    "Here's a 45-second Mexican-Talavera-Puebla reel — extend to 2 minutes, render as Talavera-Puebla-pattern-2, and overlay English captions.",
    "I have a 1-minute Mexican-Mata-Ortiz-pottery reel — extend to 3 minutes, style as Mata-Ortiz-pattern-2, and add English subtitles.",
    "Uploading a 30-second Andean-Quechua-pottery reel — extend to 90 seconds, convert to Andean-Quechua-pattern, and overlay English captions.",
    "Here's a 45-second Brazilian-Marajoara-pottery reel — extend to 2 minutes, render as Marajoara-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Pueblo-Acoma-pottery reel — extend to 3 minutes, style as Acoma-pattern-2, and overlay English captions.",
    "Uploading a 30-second Hopi-pottery reel — extend to 90 seconds, convert to Hopi-pattern, and add English subtitles.",
    "Here's a 45-second Cherokee-pottery reel — extend to 2 minutes, render as Cherokee-pottery-pattern, and overlay English captions.",
    # ── more stained-glass + mosaic + Tiffany/Byzantine styles + EN subs (50) ──
    "I have a 1-minute Chartres-Cathedral-rose-window reel — extend to 3 minutes, style as Chartres-stained-glass-pattern, and add English subtitles.",
    "Uploading a 30-second Sainte-Chapelle-Paris-stained-glass reel — extend to 90 seconds, convert to Sainte-Chapelle-pattern, and overlay English captions.",
    "Here's a 45-second Notre-Dame-Paris-rose-window reel — extend to 2 minutes, render as Notre-Dame-rose-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Reims-Cathedral-stained-glass reel — extend to 3 minutes, style as Reims-Gothic-pattern, and overlay English captions.",
    "Uploading a 30-second York-Minster-Great-East-Window reel — extend to 90 seconds, convert to York-Minster-pattern, and add English subtitles.",
    "Here's a 45-second Canterbury-Cathedral-Becket-window reel — extend to 2 minutes, render as Canterbury-Becket-pattern, and overlay English captions.",
    "I have a 1-minute Cologne-Cathedral-Bavarian-windows reel — extend to 3 minutes, style as Cologne-Gothic-pattern, and add English subtitles.",
    "Uploading a 30-second Strasbourg-Cathedral-window reel — extend to 90 seconds, convert to Strasbourg-Gothic-pattern, and overlay English captions.",
    "Here's a 45-second Milan-Duomo-stained-glass reel — extend to 2 minutes, render as Milan-Duomo-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Florence-Duomo-stained-glass reel — extend to 3 minutes, style as Florence-Duomo-pattern, and overlay English captions.",
    "Uploading a 30-second Tiffany-NYC-Lamp-Studio reel — extend to 90 seconds, convert to Tiffany-Wisteria-pattern, and add English subtitles.",
    "Here's a 45-second Tiffany-Lily-Lampshade reel — extend to 2 minutes, render as Tiffany-Lily-pattern, and overlay English captions.",
    "I have a 1-minute Tiffany-Dragonfly-Lampshade reel — extend to 3 minutes, style as Tiffany-Dragonfly-pattern, and add English subtitles.",
    "Uploading a 30-second Tiffany-Peacock-window reel — extend to 90 seconds, convert to Tiffany-Peacock-pattern, and overlay English captions.",
    "Here's a 45-second Frank-Lloyd-Wright-Robie-House-window reel — extend to 2 minutes, render as Wright-Prairie-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Frank-Lloyd-Wright-Avery-Coonley-window reel — extend to 3 minutes, style as Wright-Coonley-pattern, and overlay English captions.",
    "Uploading a 30-second La-Sagrada-Familia-Barcelona-window reel — extend to 90 seconds, convert to Sagrada-Familia-pattern, and add English subtitles.",
    "Here's a 45-second Casa-Batlló-Barcelona-window reel — extend to 2 minutes, render as Casa-Batlló-pattern, and overlay English captions.",
    "I have a 1-minute Park-Güell-Barcelona-trencadís reel — extend to 3 minutes, style as Park-Güell-trencadís-pattern, and add English subtitles.",
    "Uploading a 30-second Hagia-Sophia-Istanbul-mosaic reel — extend to 90 seconds, convert to Hagia-Sophia-Byzantine-pattern, and overlay English captions.",
    "Here's a 45-second Chora-Church-Istanbul-mosaic reel — extend to 2 minutes, render as Chora-Byzantine-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Ravenna-Basilica-San-Vitale-mosaic reel — extend to 3 minutes, style as Ravenna-Byzantine-pattern, and overlay English captions.",
    "Uploading a 30-second Ravenna-Galla-Placidia-mosaic reel — extend to 90 seconds, convert to Galla-Placidia-pattern, and add English subtitles.",
    "Here's a 45-second Monreale-Cathedral-Sicily-mosaic reel — extend to 2 minutes, render as Monreale-Norman-Byzantine-pattern, and overlay English captions.",
    "I have a 1-minute Cefalù-Cathedral-Sicily-mosaic reel — extend to 3 minutes, style as Cefalù-Norman-pattern, and add English subtitles.",
    "Uploading a 30-second Palatine-Chapel-Palermo-mosaic reel — extend to 90 seconds, convert to Palatine-Norman-pattern, and overlay English captions.",
    "Here's a 45-second Daphni-Monastery-Athens-mosaic reel — extend to 2 minutes, render as Daphni-Byzantine-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Hosios-Loukas-mosaic reel — extend to 3 minutes, style as Hosios-Loukas-Byzantine-pattern, and overlay English captions.",
    "Uploading a 30-second Mistra-Peribleptos-Greek-mosaic reel — extend to 90 seconds, convert to Mistra-Byzantine-pattern, and add English subtitles.",
    "Here's a 45-second Pompeii-Alexander-Mosaic reel — extend to 2 minutes, render as Pompeii-Hellenistic-pattern, and overlay English captions.",
    "I have a 1-minute Tunisia-Bardo-Museum-mosaic reel — extend to 3 minutes, style as Bardo-Roman-pattern, and add English subtitles.",
    "Uploading a 30-second Antioch-mosaic-floor reel — extend to 90 seconds, convert to Antioch-Roman-pattern, and overlay English captions.",
    "Here's a 45-second Madaba-Map-mosaic reel — extend to 2 minutes, render as Madaba-Map-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Gaudí-trencadís-mosaic reel — extend to 3 minutes, style as Gaudí-trencadís-pattern-2, and overlay English captions.",
    "Uploading a 30-second Hundertwasser-Vienna-mosaic reel — extend to 90 seconds, convert to Hundertwasser-pattern, and add English subtitles.",
    "Here's a 45-second Chartres-Saint-Anne-window reel — extend to 2 minutes, render as Chartres-Saint-Anne-pattern, and overlay English captions.",
    "I have a 1-minute Chagall-Hadassah-Hospital-window reel — extend to 3 minutes, style as Chagall-Twelve-Tribes-pattern, and add English subtitles.",
    "Uploading a 30-second Chagall-Reims-Cathedral-window reel — extend to 90 seconds, convert to Chagall-Reims-pattern, and overlay English captions.",
    "Here's a 45-second Chagall-Metz-Cathedral-window reel — extend to 2 minutes, render as Chagall-Metz-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Matisse-Vence-Chapel-window reel — extend to 3 minutes, style as Matisse-Vence-pattern, and overlay English captions.",
    "Uploading a 30-second Burne-Jones-stained-glass reel — extend to 90 seconds, convert to Burne-Jones-pre-Raphaelite-pattern, and add English subtitles.",
    "Here's a 45-second William-Morris-Strawberry-Thief-window reel — extend to 2 minutes, render as Morris-pattern, and overlay English captions.",
    "I have a 1-minute John-La-Farge-NYC-window reel — extend to 3 minutes, style as La-Farge-American-pattern, and add English subtitles.",
    "Uploading a 30-second Christopher-Whall-stained-glass reel — extend to 90 seconds, convert to Whall-Arts-Crafts-pattern, and overlay English captions.",
    "Here's a 45-second Veronese-stained-glass-Venice reel — extend to 2 minutes, render as Veronese-Venetian-pattern, and add English subtitles.",
    "I'm sending you a 1-minute Murano-glass-mosaic reel — extend to 3 minutes, style as Murano-glass-pattern, and overlay English captions.",
    "Uploading a 30-second Iznik-tile-mosque reel — extend to 90 seconds, convert to Iznik-Ottoman-pattern, and add English subtitles.",
    "Here's a 45-second Isfahan-Imam-Mosque-mosaic reel — extend to 2 minutes, render as Isfahan-Safavid-pattern, and overlay English captions.",
    "I have a 1-minute Samarkand-Registan-tilework reel — extend to 3 minutes, style as Samarkand-Timurid-pattern, and add English subtitles.",
    "Uploading a 30-second Ghaznavid-Mosque-tilework reel — extend to 90 seconds, convert to Ghaznavid-pattern, and overlay English captions.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
