"""x15 intake_img_cr_bilingual SFT short briefs.

Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video →
       Transcription → Translation → Compositor.
Trigger: user uploads ONE reference image + cinematic mini-drama + bilingual
subtitles. NO music, NO ambience.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a portrait of my late grandfather — make a 1-minute mini-drama imagining his time as a young soldier with English and Spanish subtitles.",
    "Here's a sketch of a young Tang-dynasty calligrapher — build a 45-second cinematic short with Mandarin and English subtitles.",
    "I'm sending you a watercolor of a Mexican vaquero — produce a 30-second piece with Spanish and English subtitles.",
    "Uploading a digital painting of a Mongolian eagle hunter — make a 1-minute mini-drama with Mongolian and Russian subtitles.",
    "Here's a portrait of a young Maori carver — render a 45-second cinematic short with Maori and English subtitles.",
    "I'm attaching a sketch of a young French peasant girl writing to her brother at the front in 1916 — build a 30-second piece with French and English subtitles.",
    "Uploading this concept art of a Heian noblewoman — produce a 1-minute mini-drama with Japanese and English subtitles.",
    "Here's a watercolor of a young Greek herbalist — render a 45-second cinematic short with Greek and English subtitles.",
    "I have a portrait of a young Roman scribe — build a 30-second piece with Latin and English subtitles.",
    "Uploading a sketch of a young Heian-era poet — make a 1-minute mini-drama with Japanese and English subtitles.",
    "Here's a digital painting of a young Cuban grandmother lighting a candle — produce a 45-second short with Spanish and English subtitles.",
    "I'm attaching this image of a Venetian gondolier — build a 30-second cinematic piece with Italian and English subtitles.",
    "Uploading a portrait of a young French ferry captain — make a 1-minute mini-drama with French and English subtitles.",
    "Here's a sketch of a young Andean weaver — render a 45-second cinematic short with Quechua and Spanish subtitles.",
    "I'm sending you a watercolor of a young Persian poet — produce a 30-second piece with Persian and English subtitles.",
    "Uploading a digital portrait of a young Welsh shepherdess — build a 1-minute mini-drama with Welsh and English subtitles.",
    "Here's a portrait of a young Yoruba drummer — render a 45-second cinematic short with Yoruba and English subtitles.",
    "I'm attaching a sketch of a young Sicilian fisherman — make a 30-second piece with Italian and English subtitles.",
    "Uploading a watercolor of a young Hindu priestess — produce a 1-minute mini-drama with Hindi and English subtitles.",
    "Here's a digital painting of a young Lebanese baker — build a 45-second cinematic short with Arabic and English subtitles.",
    "I have a portrait of a young Filipino fisherman — render a 30-second piece with Tagalog and English subtitles.",
    "Uploading a sketch of a young Russian violinmaker — make a 1-minute mini-drama with Russian and English subtitles.",
    "Here's a watercolor of a young Sami reindeer-herder — produce a 45-second short with Sami and Norwegian subtitles.",
    "I'm sending you a portrait of a young Senegalese drummer — build a 30-second cinematic piece with Wolof and French subtitles.",
    "Uploading a digital painting of a young Malagasy weaver — make a 1-minute mini-drama with Malagasy and French subtitles.",
    "Here's a sketch of a young Polish folk-fiddler — render a 45-second cinematic short with Polish and English subtitles.",
    "I'm attaching a portrait of a young Breton sailor — produce a 30-second piece with Breton and French subtitles.",
    "Uploading a watercolor of a young Egyptian dancer — build a 1-minute mini-drama with Arabic and English subtitles.",
    "Here's a digital portrait of a young Berber goat-herd — make a 45-second cinematic short with Berber and Arabic subtitles.",
    "I have a sketch of a young Iranian carpet-weaver — render a 30-second piece with Persian and Arabic subtitles.",
    "Uploading a portrait of a young Turkish meddah storyteller — make a 1-minute mini-drama with Turkish and English subtitles.",
    "Here's a watercolor of a young Mongolian throat-singer — produce a 45-second short with Mongolian and Russian subtitles.",
    "I'm sending you a digital painting of a young Aboriginal didgeridoo-player — build a 30-second cinematic piece with Yolŋu Matha and English subtitles.",
    "Uploading a sketch of a young Maori warrior — render a 1-minute mini-drama with Maori and English subtitles.",
    "Here's a portrait of a young Hawaiian hula dancer — make a 45-second cinematic short with Hawaiian and English subtitles.",
    "I'm attaching a watercolor of a young Tongan fisherman — produce a 30-second piece with Tongan and Samoan subtitles.",
    "Uploading a digital portrait of a young Inuit hunter — build a 1-minute mini-drama with Inuktitut and English subtitles.",
    "Here's a sketch of a young Cree elder — render a 45-second cinematic short with Cree and French subtitles.",
    "I have a portrait of a young Navajo silversmith — make a 30-second piece with Navajo and English subtitles.",
    "Uploading a watercolor of a young Lakota grandmother — produce a 1-minute mini-drama with Lakota and English subtitles.",
    "Here's a digital painting of a young Nahuatl-speaking abuela — build a 45-second cinematic short with Nahuatl and Spanish subtitles.",
    "I'm sending you a sketch of a young Mapuche shepherdess — render a 30-second piece with Mapudungun and Spanish subtitles.",
    "Uploading a portrait of a young Aymara herder — make a 1-minute mini-drama with Aymara and Quechua subtitles.",
    "Here's a watercolor of a young Garifuna drummer — produce a 45-second short with Garifuna and Spanish subtitles.",
    "I'm attaching a digital portrait of a young Haitian Kreyòl baker — build a 30-second cinematic piece with Haitian Kreyòl and French subtitles.",
    "Uploading a sketch of a young Jamaican Patois fisherman — render a 1-minute mini-drama with Jamaican Patois and English subtitles.",
    "Here's a portrait of a young Ethiopian Coptic deacon — make a 45-second cinematic short with Amharic and English subtitles.",
    "I have a watercolor of a young Tigrinya farmer — produce a 30-second piece with Tigrinya and English subtitles.",
    "Uploading a digital painting of a young Somali storyteller — build a 1-minute mini-drama with Somali and Arabic subtitles.",
    "Here's a sketch of a young Swahili coast fisherman — render a 45-second cinematic short with Swahili and Arabic subtitles.",
    # ── more reference-image cinematic shorts with bilingual subtitles (50) ──
    "Uploading a portrait of a young Korean grandmother folding hanbok — make a 1-minute mini-drama with Korean and English subtitles.",
    "Here's a watercolor of a young Vietnamese seamstress — render a 45-second cinematic short with Vietnamese and English subtitles.",
    "I have a sketch of a young Khmer apsara dancer — produce a 30-second piece with Khmer and English subtitles.",
    "Uploading a digital painting of a young Lao Buddhist novice monk — build a 1-minute mini-drama with Lao and Thai subtitles.",
    "Here's a portrait of a young Thai schoolteacher — make a 45-second cinematic short with Thai and English subtitles.",
    "I'm sending you a sketch of a young Burmese saung harpist — produce a 30-second piece with Burmese and English subtitles.",
    "Uploading a watercolor of a young Nepali Sherpa porter — render a 1-minute mini-drama with Nepali and English subtitles.",
    "Here's a digital portrait of a young Bengali poet — build a 45-second cinematic short with Bengali and English subtitles.",
    "I'm attaching a portrait of a young Tamil bharatanatyam dancer — produce a 30-second piece with Tamil and English subtitles.",
    "Uploading a sketch of a young Kerala fisherman — make a 1-minute mini-drama with Malayalam and English subtitles.",
    "Here's a watercolor of a young Sinhalese tea-picker — render a 45-second cinematic short with Sinhalese and English subtitles.",
    "I have a digital painting of a young Tibetan monastery-scribe — produce a 30-second piece with Tibetan and Mandarin subtitles.",
    "Uploading a portrait of a young Bhutanese archer — build a 1-minute mini-drama with Dzongkha and English subtitles.",
    "Here's a sketch of a young Uzbek silk-weaver — render a 45-second cinematic short with Uzbek and Russian subtitles.",
    "I'm sending you a watercolor of a young Kyrgyz eagle-hunter — make a 30-second piece with Kyrgyz and Russian subtitles.",
    "Uploading a digital painting of a young Kazakh dombra-player — build a 1-minute mini-drama with Kazakh and Russian subtitles.",
    "Here's a portrait of a young Turkmen carpet-weaver — produce a 45-second cinematic short with Turkmen and Russian subtitles.",
    "I'm attaching a sketch of a young Tajik mountain-shepherdess — render a 30-second piece with Tajik and Russian subtitles.",
    "Uploading a watercolor of a young Afghan rubab-player — make a 1-minute mini-drama with Pashto and Dari subtitles.",
    "Here's a digital portrait of a young Pakistani Urdu poet — build a 45-second cinematic short with Urdu and English subtitles.",
    "I have a portrait of a young Sindhi ajrak-printer — produce a 30-second piece with Sindhi and Urdu subtitles.",
    "Uploading a sketch of a young Punjabi dhol-player — render a 1-minute mini-drama with Punjabi and Hindi subtitles.",
    "Here's a watercolor of a young Gujarati spice-merchant — make a 45-second cinematic short with Gujarati and Hindi subtitles.",
    "I'm sending you a digital painting of a young Marathi tabla-student — produce a 30-second piece with Marathi and Hindi subtitles.",
    "Uploading a portrait of a young Goan fisherman — build a 1-minute mini-drama with Konkani and Portuguese subtitles.",
    "Here's a sketch of a young Telugu kuchipudi-dancer — render a 45-second cinematic short with Telugu and English subtitles.",
    "I'm attaching a watercolor of a young Norwegian Lofoten fisherman — make a 30-second piece with Norwegian and English subtitles.",
    "Uploading a digital portrait of a young Icelandic shepherd — produce a 1-minute mini-drama with Icelandic and English subtitles.",
    "Here's a portrait of a young Faroese sea-shanty singer — build a 45-second cinematic short with Faroese and Danish subtitles.",
    "I have a sketch of a young Estonian regilaul-singer — render a 30-second piece with Estonian and Russian subtitles.",
    "Uploading a watercolor of a young Latvian midsummer-dancer — make a 1-minute mini-drama with Latvian and Russian subtitles.",
    "Here's a digital painting of a young Lithuanian amber-crafter — produce a 45-second cinematic short with Lithuanian and Polish subtitles.",
    "I'm sending you a portrait of a young Finnish kantele-player — build a 30-second piece with Finnish and Swedish subtitles.",
    "Uploading a sketch of a young Czech glass-blower — render a 1-minute mini-drama with Czech and German subtitles.",
    "Here's a watercolor of a young Slovak fujara-shepherd — make a 45-second cinematic short with Slovak and Hungarian subtitles.",
    "I'm attaching a digital portrait of a young Hungarian csikós horseman — produce a 30-second piece with Hungarian and Romanian subtitles.",
    "Uploading a portrait of a young Romanian Maramureș-shepherdess — build a 1-minute mini-drama with Romanian and Hungarian subtitles.",
    "Here's a sketch of a young Bulgarian rose-picker — render a 45-second cinematic short with Bulgarian and Macedonian subtitles.",
    "I have a watercolor of a young Albanian iso-polyphonic-singer — make a 30-second piece with Albanian and Greek subtitles.",
    "Uploading a digital painting of a young Serbian gusle-player — produce a 1-minute mini-drama with Serbian and Bosnian subtitles.",
    "Here's a portrait of a young Croatian klapa-singer — build a 45-second cinematic short with Croatian and Italian subtitles.",
    "I'm sending you a sketch of a young Slovenian beekeeper — render a 30-second piece with Slovenian and German subtitles.",
    "Uploading a watercolor of a young Catalan casteller — make a 1-minute mini-drama with Catalan and Spanish subtitles.",
    "Here's a digital portrait of a young Basque txalaparta-player — produce a 45-second cinematic short with Basque and Spanish subtitles.",
    "I'm attaching a portrait of a young Galician gaita-piper — build a 30-second piece with Galician and Portuguese subtitles.",
    "Uploading a sketch of a young Igbo mask-carver — render a 1-minute mini-drama with Igbo and English subtitles.",
    "Here's a watercolor of a young Hausa kakaki-trumpeter — make a 45-second cinematic short with Hausa and English subtitles.",
    "I have a digital painting of a young Akan kente-weaver — produce a 30-second piece with Twi and English subtitles.",
    "Uploading a portrait of a young Maasai warrior — build a 1-minute mini-drama with Maa and Swahili subtitles.",
    "Here's a sketch of a young Zulu imbongi praise-poet — render a 45-second cinematic short with Zulu and English subtitles.",
    # ── more reference-image cinematic shorts with bilingual subtitles (50) ──
    "Uploading a portrait of a young Romanian Maramureș shepherdess — make a 1-minute mini-drama with Romanian and Hungarian subtitles.",
    "Here's a watercolor of a young Bulgarian rose-picker — render a 45-second cinematic short with Bulgarian and Macedonian subtitles.",
    "I have a sketch of a young Slovak fujara shepherd — produce a 30-second piece with Slovak and Czech subtitles.",
    "Uploading a digital painting of a young Hungarian csikós horseman — build a 1-minute mini-drama with Hungarian and Slovak subtitles.",
    "Here's a portrait of a young Slovenian beekeeper — make a 45-second cinematic short with Slovenian and Italian subtitles.",
    "I'm sending you a sketch of a young Albanian bagpiper — produce a 30-second piece with Albanian and Greek subtitles.",
    "Uploading a watercolor of a young Croatian klapa singer — render a 1-minute mini-drama with Croatian and Italian subtitles.",
    "Here's a digital portrait of a young Serbian gusle player — build a 45-second cinematic short with Serbian and Bosnian subtitles.",
    "I'm attaching a portrait of a young Bosnian sevdah singer — produce a 30-second piece with Bosnian and Macedonian subtitles.",
    "Uploading a sketch of a young Macedonian zurla player — make a 1-minute mini-drama with Macedonian and Albanian subtitles.",
    "Here's a watercolor of a young Latvian midsummer dancer — render a 45-second cinematic short with Latvian and Lithuanian subtitles.",
    "I have a digital painting of a young Lithuanian amber-crafter — produce a 30-second piece with Lithuanian and Polish subtitles.",
    "Uploading a portrait of a young Finnish kantele-player — build a 1-minute mini-drama with Finnish and Swedish subtitles.",
    "Here's a sketch of a young Karelian rune-singer — render a 45-second cinematic short with Karelian and Russian subtitles.",
    "I'm sending you a watercolor of a young Norwegian Hardanger-fiddler — make a 30-second piece with Norwegian and Sami subtitles.",
    "Uploading a digital portrait of a young Faroese chain-dancer — build a 1-minute mini-drama with Faroese and Danish subtitles.",
    "Here's a portrait of a young Manx storyteller — render a 45-second cinematic short with Manx and English subtitles.",
    "I'm attaching a sketch of a young Walloon coalminer — make a 30-second piece with Walloon and French subtitles.",
    "Uploading a watercolor of a young Anatolian whirling-dervish — build a 1-minute mini-drama with Turkish and Persian subtitles.",
    "Here's a digital painting of a young Cappadocian fresco-painter — render a 45-second cinematic short with Turkish and Greek subtitles.",
    "I have a portrait of a young Kurdish dengbêj-singer — produce a 30-second piece with Kurdish and Arabic subtitles.",
    "Uploading a sketch of a young Syrian oud-maker — make a 1-minute mini-drama with Arabic and Aramaic subtitles.",
    "Here's a watercolor of a young Iraqi kanun-player — render a 45-second cinematic short with Arabic and Kurdish subtitles.",
    "I'm sending you a digital painting of a young Iranian dotar-player — build a 30-second cinematic piece with Persian and Kurdish subtitles.",
    "Uploading a portrait of a young Tajik mountain-girl — make a 1-minute mini-drama with Tajik and Persian subtitles.",
    "Here's a sketch of a young Turkmen carpet-knotter — render a 45-second cinematic short with Turkmen and Persian subtitles.",
    "I'm attaching a watercolor of a young Uzbek silk-painter — produce a 30-second piece with Uzbek and Russian subtitles.",
    "Uploading a digital portrait of a young Kazakh dombra-player — build a 1-minute mini-drama with Kazakh and Mongolian subtitles.",
    "Here's a portrait of a young Kyrgyz manaschi-storyteller — render a 45-second cinematic short with Kyrgyz and Russian subtitles.",
    "I have a sketch of a young Egyptian Coptic monk — make a 30-second piece with Coptic and Arabic subtitles.",
    "Uploading a watercolor of a young Lebanese debke-dancer — build a 1-minute mini-drama with Arabic and French subtitles.",
    "Here's a digital painting of a young Palestinian olive-harvest girl — render a 45-second cinematic short with Arabic and Hebrew subtitles.",
    "I'm sending you a portrait of a young Israeli klezmer-fiddler — make a 30-second piece with Hebrew and Yiddish subtitles.",
    "Uploading a sketch of a young Yemeni Habbani jewelry-maker — produce a 1-minute mini-drama with Yemeni-Arabic and Hebrew subtitles.",
    "Here's a watercolor of a young Saudi falconer — render a 45-second cinematic short with Arabic and English subtitles.",
    "I'm attaching a digital portrait of a young Emirati incense-burner — build a 30-second cinematic piece with Arabic and English subtitles.",
    "Uploading a portrait of a young Bahraini pearl-diver — make a 1-minute mini-drama with Arabic and Persian subtitles.",
    "Here's a sketch of a young Qatari dhow-builder — render a 45-second cinematic short with Arabic and English subtitles.",
    "I have a watercolor of a young Omani halwa-maker — produce a 30-second piece with Arabic and Swahili subtitles.",
    "Uploading a digital painting of a young Iraqi-Kurdish painter — build a 1-minute mini-drama with Kurdish and Arabic subtitles.",
    "Here's a portrait of a young Cypriot lyre-player — render a 45-second cinematic short with Greek and Turkish subtitles.",
    "I'm sending you a sketch of a young Maltese ftira-baker — make a 30-second piece with Maltese and Italian subtitles.",
    "Uploading a watercolor of a young Ladino-singer Sephardi — produce a 1-minute mini-drama with Ladino and Hebrew subtitles.",
    "Here's a digital portrait of a young Yiddish theater-actress — build a 45-second cinematic short with Yiddish and German subtitles.",
    "I'm attaching a portrait of a young Aramaic-prayer-singer — make a 30-second piece with Aramaic and Hebrew subtitles.",
    "Uploading a sketch of a young Coptic-deacon Cairo — render a 1-minute mini-drama with Coptic and Arabic subtitles.",
    "Here's a watercolor of a young Romansh shepherd — produce a 45-second cinematic short with Romansh and Italian subtitles.",
    "I have a digital painting of a young Friulian wheat-farmer — make a 30-second piece with Friulian and Italian subtitles.",
    "Uploading a portrait of a young Sardinian launeddas-player — build a 1-minute mini-drama with Sardinian and Italian subtitles.",
    "Here's a sketch of a young Sicilian opera-puppet-master — render a 45-second cinematic short with Sicilian and Italian subtitles.",
    # ── more reference-image cinematic shorts with bilingual subtitles (50) ──
    "Uploading a portrait of a young Hawaiian taro-farmer — make a 1-minute mini-drama with Hawaiian and English subtitles.",
    "Here's a watercolor of a young Tahitian dancer — render a 45-second cinematic short with Tahitian and French subtitles.",
    "I have a sketch of a young Marshallese weaver — produce a 30-second piece with Marshallese and English subtitles.",
    "Uploading a digital painting of a young Palauan storyteller — build a 1-minute mini-drama with Palauan and English subtitles.",
    "Here's a portrait of a young Yapese stone-money carver — make a 45-second cinematic short with Yapese and English subtitles.",
    "I'm sending you a sketch of a young Pohnpeian sakau-server — produce a 30-second piece with Pohnpeian and English subtitles.",
    "Uploading a watercolor of a young Chamorro chamorrita-singer — render a 1-minute mini-drama with Chamorro and English subtitles.",
    "Here's a digital portrait of a young Niuean coconut-crab fisherman — build a 45-second cinematic short with Niuean and English subtitles.",
    "I'm attaching a portrait of a young Tokelauan fala-weaver — produce a 30-second piece with Tokelauan and English subtitles.",
    "Uploading a sketch of a young Tuvaluan canoe-builder — make a 1-minute mini-drama with Tuvaluan and English subtitles.",
    "Here's a watercolor of a young Kiribati outrigger sailor — render a 45-second cinematic short with Kiribati and English subtitles.",
    "I have a digital painting of a young Nauruan fishing-elder — produce a 30-second piece with Nauruan and English subtitles.",
    "Uploading a portrait of a young Bonaire flamingo-watcher — build a 1-minute mini-drama with Papiamento and Dutch subtitles.",
    "Here's a sketch of a young Aruban cunucu-house artisan — render a 45-second cinematic short with Papiamento and Dutch subtitles.",
    "I'm sending you a watercolor of a young Curaçaoan tula-singer — make a 30-second piece with Papiamento and Dutch subtitles.",
    "Uploading a digital portrait of a young Trinidadian-calypso girl — build a 1-minute mini-drama with Trinidadian-Creole and English subtitles.",
    "Here's a portrait of a young Saint-Lucian limbo-dancer — render a 45-second cinematic short with Saint-Lucian-Creole and English subtitles.",
    "I'm attaching a sketch of a young Antiguan steel-pan player — make a 30-second piece with Antiguan-Creole and English subtitles.",
    "Uploading a watercolor of a young Saint-Kitts mango-vendor — produce a 1-minute mini-drama with Saint-Kitts-Creole and English subtitles.",
    "Here's a digital painting of a young Anguillian fisherman — build a 45-second cinematic short with Anguillian-English and French subtitles.",
    "I have a portrait of a young Saint-Martin créole girl — render a 30-second piece with Saint-Martin-Creole and French subtitles.",
    "Uploading a sketch of a young Saint-Barth-fisherman — make a 1-minute mini-drama with French and English subtitles.",
    "Here's a watercolor of a young Bahamian junkanoo boy — produce a 45-second short with Bahamian-Creole and English subtitles.",
    "I'm sending you a portrait of a young Bermudian gombey dancer — build a 30-second cinematic piece with English and Portuguese subtitles.",
    "Uploading a digital painting of a young Cayman-fisherman — make a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a sketch of a young Saint-Vincent volcano-watcher — render a 45-second cinematic short with English and Spanish subtitles.",
    "I'm attaching a portrait of a young Grenadan nutmeg-farmer — produce a 30-second piece with English and Spanish subtitles.",
    "Uploading a watercolor of a young Dominica-Kalinago basket-weaver — build a 1-minute mini-drama with Kalinago and French subtitles.",
    "Here's a digital portrait of a young Cuban-cigar-roller — render a 45-second cinematic short with Spanish and English subtitles.",
    "I have a sketch of a young Dominican-merengue accordionist — produce a 30-second piece with Spanish and Haitian-Kreyòl subtitles.",
    "Uploading a portrait of a young Puerto-Rican plena-drummer — make a 1-minute mini-drama with Spanish and Yoruba subtitles.",
    "Here's a watercolor of a young Belizean Garifuna fisherman — produce a 45-second short with Garifuna and Spanish subtitles.",
    "I'm sending you a digital painting of a young Honduran Garifuna drummer — build a 30-second cinematic piece with Garifuna and Spanish subtitles.",
    "Uploading a sketch of a young Nicaraguan Miskito fisherman — render a 1-minute mini-drama with Miskito and Spanish subtitles.",
    "Here's a portrait of a young Costa-Rican Bribri farmer — make a 45-second cinematic short with Bribri and Spanish subtitles.",
    "I'm attaching a watercolor of a young Panamanian Kuna mola-maker — produce a 30-second piece with Kuna and Spanish subtitles.",
    "Uploading a digital portrait of a young Colombian Wayuu weaver — build a 1-minute mini-drama with Wayuunaiki and Spanish subtitles.",
    "Here's a sketch of a young Venezuelan Pemon storyteller — render a 45-second cinematic short with Pemon and Spanish subtitles.",
    "I have a portrait of a young Guyanese Lokono fisherman — make a 30-second piece with Lokono and English subtitles.",
    "Uploading a watercolor of a young Surinamese Saramaccan drummer — produce a 1-minute mini-drama with Saramaccan and Dutch subtitles.",
    "Here's a digital painting of a young French-Guianese Wayampi villager — build a 45-second cinematic short with Wayampi and French subtitles.",
    "I'm sending you a sketch of a young Brazilian Yanomami shaman — render a 30-second piece with Yanomami and Portuguese subtitles.",
    "Uploading a portrait of a young Brazilian Xingu painter — make a 1-minute mini-drama with Kayapo and Portuguese subtitles.",
    "Here's a watercolor of a young Bolivian Tsimane fisherman — produce a 45-second short with Tsimane and Spanish subtitles.",
    "I'm attaching a digital portrait of a young Peruvian Asháninka archer — build a 30-second cinematic piece with Asháninka and Spanish subtitles.",
    "Uploading a sketch of a young Ecuadorian Shuar warrior — render a 1-minute mini-drama with Shuar and Spanish subtitles.",
    "Here's a portrait of a young Chilean Yagán seaman — make a 45-second cinematic short with Yagán and Spanish subtitles.",
    "I have a watercolor of a young Argentinian Wichí weaver — produce a 30-second piece with Wichí and Spanish subtitles.",
    "Uploading a digital painting of a young Paraguayan Aché hunter — build a 1-minute mini-drama with Aché and Spanish subtitles.",
    "Here's a sketch of a young Uruguayan Charrúa storyteller — render a 45-second cinematic short with Charrúa and Spanish subtitles.",
    # ── more Pacific-Islander / Aboriginal-Australian / Polynesian (50) ──
    "Uploading a portrait of a young Hawaiian-hula-dancer — make a 1-minute mini-drama with Hawaiian and English subtitles.",
    "Here's a watercolor of a young Tahitian-paddler — produce a 45-second cinematic short with Tahitian and French subtitles.",
    "I have a digital portrait of a young Samoan-warrior — build a 30-second piece with Samoan and English subtitles.",
    "Uploading a sketch of a young Tongan-paddler — render a 1-minute mini-drama with Tongan and English subtitles.",
    "Here's a portrait of a young Fijian-fire-walker — make a 45-second cinematic short with Fijian and English subtitles.",
    "I'm sending you a digital painting of a young Niuean-fisherman — produce a 30-second piece with Niuean and English subtitles.",
    "Uploading a watercolor of a young Tuvaluan-weaver — build a 1-minute mini-drama with Tuvaluan and English subtitles.",
    "Here's a sketch of a young Kiribati-canoe-builder — render a 45-second cinematic short with Gilbertese and English subtitles.",
    "I have a portrait of a young Marshallese-stick-chart-navigator — make a 30-second piece with Marshallese and English subtitles.",
    "I'm attaching a digital portrait of a young Pohnpeian-stone-mover — build a 30-second cinematic piece with Pohnpeian and English subtitles.",
    "Uploading a sketch of a young Chuukese-paddler — render a 1-minute mini-drama with Chuukese and English subtitles.",
    "Here's a portrait of a young Yapese-stone-money-carver — make a 45-second cinematic short with Yapese and English subtitles.",
    "I have a watercolor of a young Palauan-storyboard-carver — produce a 30-second piece with Palauan and English subtitles.",
    "Uploading a digital painting of a young Chamorro-thatcher — build a 1-minute mini-drama with Chamorro and English subtitles.",
    "Here's a sketch of a young Niuafo'ou-shellsmith — render a 45-second cinematic short with Niuafo'ou and Tongan subtitles.",
    "I'm sending you a portrait of a young Rotuman-dancer — make a 30-second piece with Rotuman and English subtitles.",
    "Uploading a watercolor of a young Wallisian-weaver — produce a 1-minute mini-drama with Wallisian and French subtitles.",
    "Here's a digital portrait of a young Futunan-paddler — build a 45-second cinematic short with Futunan and French subtitles.",
    "I have a sketch of a young New-Caledonian-Kanak warrior — render a 30-second piece with Kanak and French subtitles.",
    "I'm attaching a portrait of a young Vanuatu-Big-Nambas chief — make a 30-second cinematic piece with Bislama and English subtitles.",
    "Uploading a digital painting of a young Solomon-Islander shell-money-maker — build a 1-minute mini-drama with Pijin and English subtitles.",
    "Here's a watercolor of a young Papua-New-Guinea Sepik mask-carver — produce a 45-second short with Tok-Pisin and English subtitles.",
    "I'm sending you a sketch of a young Bougainville-bilum-weaver — render a 30-second cinematic piece with Halia and English subtitles.",
    "Uploading a portrait of a young Trobriand-Islander cricket-player — make a 1-minute mini-drama with Kilivila and English subtitles.",
    "Here's a digital painting of a young Cook-Islands-tivaevae quilter — build a 45-second cinematic short with Cook-Islands-Maori and English subtitles.",
    "I have a sketch of a young Tokelauan-fisherman — render a 30-second piece with Tokelauan and English subtitles.",
    "I'm attaching a watercolor of a young Pitcairn-Islander rower — make a 30-second cinematic piece with Pitkern and English subtitles.",
    "Uploading a digital portrait of a young Norfolk-Islander gardener — build a 1-minute mini-drama with Norfuk and English subtitles.",
    "Here's a portrait of a young Aboriginal-Anangu didgeridoo-player — produce a 45-second cinematic short with Pitjantjatjara and English subtitles.",
    "I have a watercolor of a young Aboriginal-Yolngu painter — render a 30-second piece with Yolngu-Matha and English subtitles.",
    "Uploading a sketch of a young Aboriginal-Tiwi-Islander pukamani-pole carver — produce a 1-minute mini-drama with Tiwi and English subtitles.",
    "Here's a digital painting of a young Aboriginal-Warlpiri sand-painter — build a 45-second cinematic short with Warlpiri and English subtitles.",
    "I'm sending you a portrait of a young Aboriginal-Arrernte storyteller — render a 30-second cinematic piece with Arrernte and English subtitles.",
    "Uploading a watercolor of a young Aboriginal-Bunuba rock-art guide — make a 1-minute mini-drama with Bunuba and English subtitles.",
    "Here's a sketch of a young Aboriginal-Wiradjuri dancer — produce a 45-second cinematic short with Wiradjuri and English subtitles.",
    "I have a portrait of a young Aboriginal-Gunditjmara eel-trapper — make a 30-second piece with Gunditjmara and English subtitles.",
    "I'm attaching a digital portrait of a young Aboriginal-Palawa basket-weaver — build a 30-second cinematic piece with Palawa-Kani and English subtitles.",
    "Uploading a sketch of a young Maori-haka-leader — render a 1-minute mini-drama with Te-Reo-Maori and English subtitles.",
    "Here's a watercolor of a young Maori-tā-moko artist — produce a 45-second short with Te-Reo-Maori and Niuean subtitles.",
    "I have a digital painting of a young Maori-poi-twirler — build a 30-second cinematic piece with Te-Reo-Maori and Samoan subtitles.",
    "Uploading a portrait of a young Moriori-storyteller — make a 1-minute mini-drama with Moriori and English subtitles.",
    "Here's a sketch of a young Rapa-Nui-moai-carver — render a 45-second cinematic short with Rapa-Nui and Spanish subtitles.",
    "I'm sending you a watercolor of a young Mangarevan-pearl-diver — produce a 30-second piece with Mangarevan and French subtitles.",
    "Uploading a digital portrait of a young Tuamotu-pearl-farmer — build a 1-minute mini-drama with Tuamotuan and French subtitles.",
    "Here's a portrait of a young Marquesan-tatu-artist — make a 45-second cinematic short with Marquesan and French subtitles.",
    "I have a sketch of a young Austral-Islander dancer — produce a 30-second piece with Austral-Tahitian and French subtitles.",
    "I'm attaching a digital painting of a young Easter-Island birdman-festival diver — build a 30-second cinematic piece with Rapa-Nui and English subtitles.",
    "Uploading a watercolor of a young Hawaiian-canoe-paddler — render a 1-minute mini-drama with Hawaiian and Japanese subtitles.",
    "Here's a sketch of a young Pohnpei-Nan-Madol guide — produce a 45-second cinematic short with Pohnpeian and Japanese subtitles.",
    "I have a portrait of a young Hawaiian-petroglyph guide — make a 30-second piece with Hawaiian and Mandarin subtitles.",
    # ── more medieval European figures (50) ──
    "I'm attaching a portrait of a young Norman-knight squire — make a 1-minute mini-drama with Norman-French and Latin subtitles.",
    "Uploading a watercolor of a young Saxon-thane page — produce a 45-second cinematic short with Old-English and Latin subtitles.",
    "Here's a digital portrait of a young Frankish-knight squire — build a 30-second piece with Old-French and Latin subtitles.",
    "I have a sketch of a young Lombard-shieldmaiden — render a 1-minute mini-drama with Lombard and Latin subtitles.",
    "Uploading a portrait of a young Visigoth-page — make a 45-second cinematic short with Gothic and Latin subtitles.",
    "Here's a watercolor of a young Carolingian-court-page — produce a 30-second piece with Old-French and Latin subtitles.",
    "I'm sending you a digital painting of a young Merovingian-court-cupbearer — build a 1-minute mini-drama with Frankish and Latin subtitles.",
    "Uploading a sketch of a young Anglo-Saxon scop — render a 45-second cinematic short with Old-English and Latin subtitles.",
    "Here's a portrait of a young Norse-skald — produce a 30-second piece with Old-Norse and Old-English subtitles.",
    "I have a watercolor of a young Viking-shipwright apprentice — make a 1-minute mini-drama with Old-Norse and English subtitles.",
    "I'm attaching a digital portrait of a young Rus-druzhina-page — build a 30-second cinematic piece with Old-East-Slavic and Greek subtitles.",
    "Uploading a sketch of a young Byzantine-court-eunuch page — render a 1-minute mini-drama with Greek and Latin subtitles.",
    "Here's a portrait of a young Byzantine-icon-painter apprentice — make a 45-second cinematic short with Greek and Old-Slavonic subtitles.",
    "I have a digital painting of a young Crusader-knight squire — produce a 30-second piece with Old-French and Latin subtitles.",
    "Uploading a watercolor of a young Hospitaller-novice — build a 1-minute mini-drama with Latin and Old-French subtitles.",
    "Here's a sketch of a young Templar-novice — render a 45-second cinematic short with Latin and Old-French subtitles.",
    "I'm sending you a portrait of a young Teutonic-knight novice — produce a 30-second piece with Middle-High-German and Latin subtitles.",
    "Uploading a digital portrait of a young Cistercian-novice — make a 1-minute mini-drama with Latin and Old-French subtitles.",
    "Here's a watercolor of a young Benedictine-scribe — produce a 45-second cinematic short with Latin and Old-English subtitles.",
    "I have a sketch of a young Carthusian-hermit — build a 30-second piece with Latin and Provençal subtitles.",
    "I'm attaching a digital painting of a young Franciscan-friar — render a 1-minute mini-drama with Latin and Italian subtitles.",
    "Uploading a portrait of a young Dominican-novice — make a 45-second cinematic short with Latin and Castilian subtitles.",
    "Here's a sketch of a young Beguine-laywoman — produce a 30-second piece with Middle-Dutch and Latin subtitles.",
    "I have a watercolor of a young Cluniac-novice — build a 1-minute mini-drama with Latin and Old-French subtitles.",
    "I'm sending you a digital portrait of a young Carolingian-illuminator apprentice — render a 45-second cinematic short with Latin and Old-French subtitles.",
    "Uploading a portrait of a young Anglo-Saxon-illuminator apprentice — make a 30-second piece with Latin and Old-English subtitles.",
    "Here's a watercolor of a young Irish-monastery scribe — produce a 1-minute mini-drama with Old-Irish and Latin subtitles.",
    "I have a digital painting of a young Welsh-bardic-school student — build a 45-second cinematic short with Middle-Welsh and Latin subtitles.",
    "Uploading a sketch of a young Scottish-Gaelic-monastic scribe — render a 30-second piece with Scottish-Gaelic and Latin subtitles.",
    "Here's a portrait of a young Manx-court-skald — produce a 1-minute mini-drama with Manx and Old-Norse subtitles.",
    "I'm sending you a watercolor of a young Cornish-mystery-play actor — make a 45-second cinematic short with Cornish and Latin subtitles.",
    "Uploading a digital portrait of a young Provençal-troubadour — build a 30-second piece with Old-Occitan and Latin subtitles.",
    "Here's a sketch of a young Catalan-Trobairitz — render a 1-minute mini-drama with Old-Catalan and Old-Occitan subtitles.",
    "I have a portrait of a young Galician-Portuguese trovador — produce a 45-second cinematic short with Galician-Portuguese and Castilian subtitles.",
    "I'm attaching a digital painting of a young Castilian-mester-de-juglaría — build a 30-second cinematic piece with Old-Castilian and Latin subtitles.",
    "Uploading a watercolor of a young Mozarabic-court-singer — make a 1-minute mini-drama with Mozarabic and Arabic subtitles.",
    "Here's a sketch of a young Andalusi-Sephardi-poet — produce a 45-second cinematic short with Judeo-Arabic and Hebrew subtitles.",
    "I have a digital portrait of a young Florentine-fresco apprentice — render a 30-second piece with Tuscan-Italian and Latin subtitles.",
    "Uploading a portrait of a young Sienese-altarpiece apprentice — make a 1-minute mini-drama with Sienese-Italian and Latin subtitles.",
    "Here's a watercolor of a young Venetian-glass-mosaicist — build a 45-second cinematic short with Venetian-Italian and Greek subtitles.",
    "I'm sending you a digital painting of a young Bolognese-law-student — produce a 30-second piece with Bolognese-Italian and Latin subtitles.",
    "Uploading a sketch of a young Paduan-medical-student — render a 1-minute mini-drama with Veneto and Latin subtitles.",
    "Here's a portrait of a young Salamancan-cleric — make a 45-second cinematic short with Old-Castilian and Latin subtitles.",
    "I have a watercolor of a young Coimbra-monastic novice — produce a 30-second piece with Old-Portuguese and Latin subtitles.",
    "I'm attaching a digital portrait of a young Sorbonne-theology student — build a 1-minute mini-drama with Latin and Old-French subtitles.",
    "Uploading a portrait of a young Heidelberg-scholastic — make a 45-second cinematic short with Middle-High-German and Latin subtitles.",
    "Here's a sketch of a young Prague-Charles-University student — render a 30-second piece with Old-Czech and Latin subtitles.",
    "I have a digital painting of a young Krakow-Jagiellonian student — produce a 1-minute mini-drama with Old-Polish and Latin subtitles.",
    "Uploading a watercolor of a young Cracow-Lwów-itinerant scholar — build a 45-second cinematic short with Old-Polish and Old-Ruthenian subtitles.",
    "Here's a digital portrait of a young Ragusa-Latin-school student — render a 30-second piece with Dalmatian and Latin subtitles.",
    # ── more ancient Near-East / Egypt / classical-antiquity figures (50) ──
    "Uploading a portrait of a young Old-Kingdom Egyptian-pyramid stonemason — make a 1-minute mini-drama with Middle-Egyptian and Coptic subtitles.",
    "Here's a sketch of a young Middle-Kingdom Egyptian-scribe — render a 45-second cinematic short with Middle-Egyptian and Greek subtitles.",
    "I'm sending you a watercolor of a young New-Kingdom Theban-temple priestess — produce a 30-second piece with Middle-Egyptian and Demotic subtitles.",
    "Uploading a digital painting of a young Amarna-period royal-court attendant — build a 1-minute mini-drama with Middle-Egyptian and Akkadian subtitles.",
    "Here's a portrait of a young Saite-period Memphis-craftsman — render a 45-second cinematic short with Demotic and Greek subtitles.",
    "I have a sketch of a young Ptolemaic-Alexandria scholar — produce a 30-second piece with Greek and Demotic subtitles.",
    "Uploading a watercolor of a young Sumerian-Uruk temple-scribe — make a 1-minute mini-drama with Sumerian and Akkadian subtitles.",
    "Here's a digital portrait of a young Old-Babylonian Mari-court diplomat — render a 45-second cinematic short with Akkadian and Amorite subtitles.",
    "I'm sending you a portrait of a young Middle-Assyrian Ashur-temple acolyte — produce a 30-second piece with Akkadian and Hurrian subtitles.",
    "Uploading a sketch of a young Neo-Assyrian Nineveh-palace messenger — build a 1-minute mini-drama with Akkadian and Aramaic subtitles.",
    "Here's a watercolor of a young Neo-Babylonian Babylon-Ishtar-Gate apprentice — render a 45-second cinematic short with Akkadian and Aramaic subtitles.",
    "I have a digital painting of a young Achaemenid-Persepolis page — produce a 30-second piece with Old-Persian and Elamite subtitles.",
    "Uploading a portrait of a young Achaemenid-Susa royal-road courier — make a 1-minute mini-drama with Old-Persian and Aramaic subtitles.",
    "Here's a sketch of a young Achaemenid-Pasargadae garden-attendant — render a 45-second cinematic short with Old-Persian and Median subtitles.",
    "I'm sending you a watercolor of a young Achaemenid-Babylon court-translator — produce a 30-second piece with Old-Persian and Akkadian subtitles.",
    "Uploading a digital portrait of a young Phoenician-Tyre dye-maker — build a 1-minute mini-drama with Phoenician and Greek subtitles.",
    "Here's a portrait of a young Phoenician-Sidon shipwright — render a 45-second cinematic short with Phoenician and Aramaic subtitles.",
    "I have a sketch of a young Carthaginian-Tophet priestess — produce a 30-second piece with Punic and Greek subtitles.",
    "Uploading a watercolor of a young Hittite-Hattusa courtier — make a 1-minute mini-drama with Hittite and Luwian subtitles.",
    "Here's a digital painting of a young Mitanni-Wassukanni horse-trainer — render a 45-second cinematic short with Hurrian and Akkadian subtitles.",
    "I'm sending you a portrait of a young Urartian-Tushpa fortress-scribe — produce a 30-second piece with Urartian and Akkadian subtitles.",
    "Uploading a sketch of a young Lydian-Sardis goldsmith-apprentice — build a 1-minute mini-drama with Lydian and Greek subtitles.",
    "Here's a watercolor of a young Phrygian-Gordion king's-page — render a 45-second cinematic short with Phrygian and Lydian subtitles.",
    "I have a digital portrait of a young Mycenaean-Pylos palace-scribe — produce a 30-second piece with Mycenaean-Greek and Linear-B subtitles.",
    "Uploading a portrait of a young Minoan-Knossos fresco-painter — make a 1-minute mini-drama with Minoan and Linear-A subtitles.",
    "Here's a sketch of a young Archaic-Greek Corinth-vase-painter — render a 45-second cinematic short with Archaic-Greek and Latin subtitles.",
    "I'm sending you a watercolor of a young Athens-Solon-era ephebe — produce a 30-second piece with Attic-Greek and Latin subtitles.",
    "Uploading a digital painting of a young Spartan-agoge candidate — build a 1-minute mini-drama with Doric-Greek and Attic-Greek subtitles.",
    "Here's a portrait of a young Theban-sacred-band recruit — render a 45-second cinematic short with Boeotian-Greek and Attic-Greek subtitles.",
    "I have a sketch of a young Alexandrian-Mouseion librarian — produce a 30-second piece with Koine-Greek and Latin subtitles.",
    "Uploading a watercolor of a young Pergamene-Library copyist — make a 1-minute mini-drama with Koine-Greek and Aramaic subtitles.",
    "Here's a digital portrait of a young Antiochene-court attendant — render a 45-second cinematic short with Koine-Greek and Syriac subtitles.",
    "I'm sending you a portrait of a young Seleucid-Babylon astronomer-trainee — produce a 30-second piece with Akkadian and Koine-Greek subtitles.",
    "Uploading a sketch of a young Arsacid-Ctesiphon court-scribe — build a 1-minute mini-drama with Parthian and Aramaic subtitles.",
    "Here's a watercolor of a young Sassanid-Ctesiphon palace-musician — render a 45-second cinematic short with Middle-Persian and Aramaic subtitles.",
    "I have a digital painting of a young Etruscan-Veii haruspex-apprentice — produce a 30-second piece with Etruscan and Latin subtitles.",
    "Uploading a portrait of a young Roman-Republic Cato-era senator's son — make a 1-minute mini-drama with Classical-Latin and Greek subtitles.",
    "Here's a sketch of a young Roman-Imperial Trajanic-forum scribe — render a 45-second cinematic short with Latin and Greek subtitles.",
    "I'm sending you a watercolor of a young Roman-Britain Vindolanda-fort scribe — produce a 30-second piece with Latin and Brittonic subtitles.",
    "Uploading a digital portrait of a young Roman-Egypt Oxyrhynchus-papyrus copyist — build a 1-minute mini-drama with Greek and Coptic subtitles.",
    "Here's a portrait of a young Roman-Syria Palmyrene-caravan trader — render a 45-second cinematic short with Palmyrene-Aramaic and Greek subtitles.",
    "I have a sketch of a young Nabataean-Petra-Treasury sculptor — produce a 30-second piece with Nabataean-Aramaic and Greek subtitles.",
    "Uploading a watercolor of a young Aksumite-Aksum stelai-mason — make a 1-minute mini-drama with Ge'ez and Greek subtitles.",
    "Here's a digital painting of a young Meroitic-Meroe iron-smelter — render a 45-second cinematic short with Meroitic and Greek subtitles.",
    "I'm sending you a portrait of a young Garamantian-Saharan oasis-trader — produce a 30-second piece with Berber and Punic subtitles.",
    "Uploading a sketch of a young Iberian-Saguntum potter — build a 1-minute mini-drama with Iberian and Latin subtitles.",
    "Here's a watercolor of a young Celtiberian-Numantia warrior-youth — render a 45-second cinematic short with Celtiberian and Latin subtitles.",
    "I have a digital portrait of a young Lusitanian-Conimbriga shepherd — produce a 30-second piece with Lusitanian and Latin subtitles.",
    "Uploading a portrait of a young Dacian-Sarmizegetusa fortress-scribe — make a 1-minute mini-drama with Dacian and Latin subtitles.",
    "Here's a sketch of a young Thracian-Seuthopolis horseman — render a 45-second cinematic short with Thracian and Greek subtitles.",
    # ── more Tang / Song / Yuan / Ming / Qing dynasty figures (50) ──
    "Uploading a portrait of a young Tang-Chang'an Hanlin-academy scholar — make a 1-minute mini-drama with Middle-Chinese and Sogdian subtitles.",
    "Here's a sketch of a young Tang-Dunhuang Mogao-cave painter — render a 45-second cinematic short with Middle-Chinese and Tibetan subtitles.",
    "I'm sending you a watercolor of a young Tang-Yangzhou silk-merchant — produce a 30-second piece with Middle-Chinese and Persian subtitles.",
    "Uploading a digital painting of a young Tang-Guangzhou maritime-customs scribe — build a 1-minute mini-drama with Middle-Chinese and Arabic subtitles.",
    "Here's a portrait of a young Tang-Quanzhou Persian-mosque calligrapher — render a 45-second cinematic short with Middle-Chinese and Pahlavi subtitles.",
    "I have a sketch of a young Tang-Chang'an East-Market caravan-trader — produce a 30-second piece with Middle-Chinese and Uyghur subtitles.",
    "Uploading a watercolor of a young Tang-Luoyang-Imperial-Palace dance-girl — make a 1-minute mini-drama with Middle-Chinese and Tocharian subtitles.",
    "Here's a digital portrait of a young Song-Kaifeng Bianhe-canal boatman — render a 45-second cinematic short with Middle-Chinese and Khitan subtitles.",
    "I'm sending you a portrait of a young Song-Hangzhou West-Lake porcelain-trader — produce a 30-second piece with Middle-Chinese and Tangut subtitles.",
    "Uploading a sketch of a young Song-Jiangnan tea-master apprentice — build a 1-minute mini-drama with Middle-Chinese and Jurchen subtitles.",
    "Here's a watercolor of a young Song-Quanzhou-Marco-Polo-era spice-trader — render a 45-second cinematic short with Middle-Chinese and Italian subtitles.",
    "I have a digital painting of a young Song-Suzhou silk-loom apprentice — produce a 30-second piece with Middle-Chinese and Khitan subtitles.",
    "Uploading a portrait of a young Song-Lin'an Imperial-Examination scholar — make a 1-minute mini-drama with Middle-Chinese and Korean subtitles.",
    "Here's a sketch of a young Liao-Shangjing Khitan court-archer — render a 45-second cinematic short with Khitan and Middle-Chinese subtitles.",
    "I'm sending you a watercolor of a young Jin-Zhongdu Jurchen-court page — produce a 30-second piece with Jurchen and Middle-Chinese subtitles.",
    "Uploading a digital portrait of a young Western-Xia-Khara-Khoto Tangut-monk — build a 1-minute mini-drama with Tangut and Middle-Chinese subtitles.",
    "Here's a portrait of a young Yuan-Dadu Mongol-court translator — render a 45-second cinematic short with Mongolian and Middle-Chinese subtitles.",
    "I have a sketch of a young Yuan-Quanzhou Genoese-merchant apprentice — produce a 30-second piece with Italian and Mongolian subtitles.",
    "Uploading a watercolor of a young Yuan-Hangzhou Marco-Polo's-attendant — make a 1-minute mini-drama with Venetian-Italian and Middle-Chinese subtitles.",
    "Here's a digital painting of a young Yuan-Karakorum Persian-astronomer — render a 45-second cinematic short with Persian and Mongolian subtitles.",
    "I'm sending you a portrait of a young Ming-Nanjing Bao-Chuan shipwright — produce a 30-second piece with Early-Modern-Chinese and Malay subtitles.",
    "Uploading a sketch of a young Ming-Zheng-He-treasure-fleet sailor — build a 1-minute mini-drama with Early-Modern-Chinese and Swahili subtitles.",
    "Here's a watercolor of a young Ming-Beijing-Forbidden-City eunuch-apprentice — render a 45-second cinematic short with Early-Modern-Chinese and Mongolian subtitles.",
    "I have a digital portrait of a young Ming-Suzhou-Wu-school painter — produce a 30-second piece with Early-Modern-Chinese and Korean subtitles.",
    "Uploading a portrait of a young Ming-Jingdezhen porcelain-kiln apprentice — make a 1-minute mini-drama with Early-Modern-Chinese and Portuguese subtitles.",
    "Here's a sketch of a young Ming-Macao Portuguese-trader's interpreter — render a 45-second cinematic short with Early-Modern-Chinese and Portuguese subtitles.",
    "I'm sending you a watercolor of a young Ming-Manila-galleon Sangley-merchant — produce a 30-second piece with Early-Modern-Chinese and Spanish subtitles.",
    "Uploading a digital painting of a young Ming-Nagasaki-Tojinmachi merchant — build a 1-minute mini-drama with Early-Modern-Chinese and Japanese subtitles.",
    "Here's a portrait of a young Ming-Yangzhou salt-merchant's daughter — render a 45-second cinematic short with Early-Modern-Chinese and Manchu subtitles.",
    "I have a sketch of a young Late-Ming-Songjiang cotton-weaver — produce a 30-second piece with Early-Modern-Chinese and Manchu subtitles.",
    "Uploading a watercolor of a young Qing-Beijing Manchu-banner-soldier — make a 1-minute mini-drama with Manchu and Early-Modern-Chinese subtitles.",
    "Here's a digital portrait of a young Qing-Mukden Manchu-court-page — render a 45-second cinematic short with Manchu and Mongolian subtitles.",
    "I'm sending you a portrait of a young Qing-Lhasa Imperial-resident's interpreter — produce a 30-second piece with Manchu and Tibetan subtitles.",
    "Uploading a sketch of a young Qing-Urumqi Imperial-frontier scribe — build a 1-minute mini-drama with Manchu and Uyghur subtitles.",
    "Here's a watercolor of a young Qing-Canton Hong-merchant's clerk — render a 45-second cinematic short with Cantonese and English subtitles.",
    "I have a digital painting of a young Qing-Macao Macanese-Eurasian girl — produce a 30-second piece with Macanese-Patois and Portuguese subtitles.",
    "Uploading a portrait of a young Qing-Shanghai-Bund-foreign-Concession clerk — make a 1-minute mini-drama with Shanghainese and English subtitles.",
    "Here's a sketch of a young Qing-Hong-Kong Tanka-boat girl — render a 45-second cinematic short with Cantonese and English subtitles.",
    "I'm sending you a watercolor of a young Late-Qing-Yangzhou Salt-Comissioner's son — produce a 30-second piece with Yangzhou-Mandarin and Manchu subtitles.",
    "Uploading a digital portrait of a young Late-Qing-Jiangnan-painter Wang-Hui-school student — build a 1-minute mini-drama with Mandarin and Wu subtitles.",
    "Here's a portrait of a young Late-Qing-Tianjin-Imperial-Customs clerk — render a 45-second cinematic short with Mandarin and English subtitles.",
    "I have a sketch of a young Late-Qing-Wuhan-Hankou Sino-French-Concession boy — produce a 30-second piece with Hubei-Mandarin and French subtitles.",
    "Uploading a watercolor of a young Late-Qing-Foochow-Mawei-shipyard apprentice — make a 1-minute mini-drama with Min-Dong and French subtitles.",
    "Here's a digital painting of a young Late-Qing-Amoy tea-merchant's son — render a 45-second cinematic short with Hokkien and English subtitles.",
    "I'm sending you a portrait of a young Late-Qing-Swatow-Teochew opera-girl — produce a 30-second piece with Teochew and English subtitles.",
    "Uploading a sketch of a young Late-Qing-Xian-Drum-Tower calligrapher — build a 1-minute mini-drama with Shaanxi-Mandarin and Manchu subtitles.",
    "Here's a watercolor of a young Late-Qing-Chengdu-Sichuan-opera apprentice — render a 45-second cinematic short with Sichuan-Mandarin and Yi subtitles.",
    "I have a digital portrait of a young Late-Qing-Kunming-Stone-Forest Yi-girl — produce a 30-second piece with Yi and Mandarin subtitles.",
    "Uploading a portrait of a young Late-Qing-Lijiang Naxi-dongba-priest's apprentice — make a 1-minute mini-drama with Naxi and Mandarin subtitles.",
    "Here's a sketch of a young Late-Qing-Dali Bai-three-course-tea girl — render a 45-second cinematic short with Bai and Mandarin subtitles.",
    # ── more Heian / Kamakura / Muromachi / Edo / Meiji-era Japanese figures (50) ──
    "Uploading a portrait of a young Heian-Kyoto-Murasaki-Shikibu-court-lady — make a 1-minute mini-drama with Old-Japanese and Classical-Chinese subtitles.",
    "Here's a sketch of a young Heian-Kyoto-Sei-Shonagon-court-lady — render a 45-second cinematic short with Old-Japanese and Classical-Chinese subtitles.",
    "I'm sending you a watercolor of a young Heian-Kyoto-Imperial-Palace court-musician — produce a 30-second piece with Old-Japanese and Old-Korean subtitles.",
    "Uploading a digital painting of a young Heian-Uji-Byodoin temple-novice — build a 1-minute mini-drama with Old-Japanese and Classical-Chinese subtitles.",
    "Here's a portrait of a young Heian-Mount-Hiei Tendai-monk-novice — render a 45-second cinematic short with Old-Japanese and Sanskrit subtitles.",
    "I have a sketch of a young Heian-Itsukushima-Shrine miko — produce a 30-second piece with Old-Japanese and Korean subtitles.",
    "Uploading a watercolor of a young Kamakura-Kamakura-Hachiman-Shrine miko — make a 1-minute mini-drama with Old-Japanese and Classical-Chinese subtitles.",
    "Here's a digital portrait of a young Kamakura-Kenchoji Zen-novice — render a 45-second cinematic short with Old-Japanese and Classical-Chinese subtitles.",
    "I'm sending you a portrait of a young Kamakura-samurai-page — produce a 30-second piece with Old-Japanese and Mongolian subtitles.",
    "Uploading a sketch of a young Kamakura-Mongol-Invasion-defender — build a 1-minute mini-drama with Old-Japanese and Mongolian subtitles.",
    "Here's a watercolor of a young Muromachi-Kyoto-Ginkakuji tea-novice — render a 45-second cinematic short with Old-Japanese and Classical-Chinese subtitles.",
    "I have a digital painting of a young Muromachi-Kinkakuji acolyte — produce a 30-second piece with Old-Japanese and Classical-Chinese subtitles.",
    "Uploading a portrait of a young Muromachi-Onin-War samurai-page — make a 1-minute mini-drama with Old-Japanese and Korean subtitles.",
    "Here's a sketch of a young Sengoku-Azuchi-Castle samurai-page — render a 45-second cinematic short with Old-Japanese and Portuguese subtitles.",
    "I'm sending you a watercolor of a young Sengoku-Nagashino-battle-archer — produce a 30-second piece with Old-Japanese and Portuguese subtitles.",
    "Uploading a digital portrait of a young Sengoku-Sekigahara-battle samurai-page — build a 1-minute mini-drama with Old-Japanese and Korean subtitles.",
    "Here's a portrait of a young Edo-Edo-Castle pageboy — render a 45-second cinematic short with Edo-Japanese and Dutch subtitles.",
    "I have a sketch of a young Edo-Yoshiwara-Pleasure-Quarter geisha-apprentice — produce a 30-second piece with Edo-Japanese and Korean subtitles.",
    "Uploading a watercolor of a young Edo-Asakusa-temple-festival child — make a 1-minute mini-drama with Edo-Japanese and Ainu subtitles.",
    "Here's a digital portrait of a young Edo-Nihonbashi-fish-market boy — render a 45-second cinematic short with Edo-Japanese and Ryukyuan subtitles.",
    "I'm sending you a portrait of a young Edo-Kabukiza-actor's son — produce a 30-second piece with Edo-Japanese and Korean subtitles.",
    "Uploading a sketch of a young Edo-Tsukiji-fish-market apprentice — build a 1-minute mini-drama with Edo-Japanese and Korean subtitles.",
    "Here's a watercolor of a young Edo-Ueno-Kaneiji-Temple acolyte — render a 45-second cinematic short with Edo-Japanese and Classical-Chinese subtitles.",
    "I have a digital painting of a young Edo-Nikko-Toshogu shrine-attendant — produce a 30-second piece with Edo-Japanese and Korean subtitles.",
    "Uploading a portrait of a young Edo-Ise-Grand-Shrine miko — make a 1-minute mini-drama with Edo-Japanese and Ainu subtitles.",
    "Here's a sketch of a young Edo-Hokkaido-Matsumae Ainu-trader's child — render a 45-second cinematic short with Edo-Japanese and Ainu subtitles.",
    "I'm sending you a watercolor of a young Edo-Ryukyu-Shuri-Castle royal-page — produce a 30-second piece with Ryukyuan and Edo-Japanese subtitles.",
    "Uploading a digital portrait of a young Edo-Nagasaki-Dejima-translator — build a 1-minute mini-drama with Edo-Japanese and Dutch subtitles.",
    "Here's a portrait of a young Edo-Hirado-Dutch-trade-port boy — render a 45-second cinematic short with Edo-Japanese and Dutch subtitles.",
    "I have a sketch of a young Edo-Kyoto-Gion-festival float-bearer — produce a 30-second piece with Edo-Japanese and Korean subtitles.",
    "Uploading a watercolor of a young Edo-Kyoto-Sanjō-bridge-river boatman — make a 1-minute mini-drama with Edo-Japanese and Korean subtitles.",
    "Here's a digital painting of a young Edo-Osaka-Tenma-river merchant's son — render a 45-second cinematic short with Edo-Japanese and Korean subtitles.",
    "I'm sending you a portrait of a young Edo-Osaka-Bunraku-puppet-theater apprentice — produce a 30-second piece with Edo-Japanese and Korean subtitles.",
    "Uploading a sketch of a young Edo-Sumida-River-firework-night festival-girl — build a 1-minute mini-drama with Edo-Japanese and Ainu subtitles.",
    "Here's a watercolor of a young Edo-Bashō-haiku-pupil — render a 45-second cinematic short with Edo-Japanese and Classical-Chinese subtitles.",
    "I have a digital portrait of a young Edo-Hokusai-ukiyo-e-apprentice — produce a 30-second piece with Edo-Japanese and Dutch subtitles.",
    "Uploading a portrait of a young Edo-Hiroshige-ukiyo-e-apprentice — make a 1-minute mini-drama with Edo-Japanese and Korean subtitles.",
    "Here's a sketch of a young Bakumatsu-Shinsengumi-cadet — render a 45-second cinematic short with Edo-Japanese and English subtitles.",
    "I'm sending you a watercolor of a young Bakumatsu-Sakamoto-Ryōma-supporter — produce a 30-second piece with Edo-Japanese and English subtitles.",
    "Uploading a digital portrait of a young Bakumatsu-Yokohama-foreign-settlement boy — build a 1-minute mini-drama with Edo-Japanese and English subtitles.",
    "Here's a portrait of a young Meiji-Tokyo-Shimbashi-railway boy — render a 45-second cinematic short with Meiji-Japanese and English subtitles.",
    "I have a sketch of a young Meiji-Tokyo-Rokumeikan ballroom-attendant — produce a 30-second piece with Meiji-Japanese and French subtitles.",
    "Uploading a watercolor of a young Meiji-Yokohama-port silk-merchant's son — make a 1-minute mini-drama with Meiji-Japanese and English subtitles.",
    "Here's a digital painting of a young Meiji-Sapporo-pioneer farm-boy — render a 45-second cinematic short with Meiji-Japanese and Ainu subtitles.",
    "I'm sending you a portrait of a young Meiji-Kobe-foreign-quarter boy — produce a 30-second piece with Meiji-Japanese and German subtitles.",
    "Uploading a sketch of a young Meiji-Nagasaki-Glover-house houseboy — build a 1-minute mini-drama with Meiji-Japanese and English subtitles.",
    "Here's a watercolor of a young Meiji-Kanazawa-Kenrokuen-garden gardener — render a 45-second cinematic short with Meiji-Japanese and Russian subtitles.",
    "I have a digital portrait of a young Meiji-Hokkaido-Otaru-port boy — produce a 30-second piece with Meiji-Japanese and Russian subtitles.",
    "Uploading a portrait of a young Meiji-Ryukyu-Shuri-Naha port-boy — make a 1-minute mini-drama with Ryukyuan and Meiji-Japanese subtitles.",
    "Here's a sketch of a young Meiji-Tokyo-Imperial-University student — render a 45-second cinematic short with Meiji-Japanese and German subtitles.",
    # ── more Korean dynasty (Silla/Baekje/Goryeo/Joseon) characters (50) ──
    "I'm sending you a portrait of a young Silla-Gyeongju-Bulguksa temple-attendant — produce a 30-second piece with Silla-era-Korean and Chinese subtitles.",
    "Uploading a watercolor of a young Silla-Gyeongju-Cheomseongdae-observatory apprentice — make a 1-minute mini-drama with Silla-era-Korean and English subtitles.",
    "Here's a digital painting of a young Silla-Gyeongju-Anapji-pond pavilion-page — render a 45-second cinematic short with Silla-era-Korean and Japanese subtitles.",
    "I have a sketch of a young Silla-Gyeongju-Tumuli-Park royal-attendant — produce a 30-second piece with Silla-era-Korean and Chinese subtitles.",
    "Uploading a portrait of a young Silla-Hwarang-warrior-trainee — build a 1-minute mini-drama with Silla-era-Korean and Japanese subtitles.",
    "Here's a watercolor of a young Baekje-Buyeo-Busosanseong-fortress soldier-boy — render a 45-second cinematic short with Baekje-era-Korean and Japanese subtitles.",
    "I'm sending you a digital portrait of a young Baekje-Gongju-Hanseong court-page — produce a 30-second piece with Baekje-era-Korean and Chinese subtitles.",
    "Uploading a sketch of a young Baekje-Iksan-Mireuksa temple-attendant — make a 1-minute mini-drama with Baekje-era-Korean and Sanskrit subtitles.",
    "Here's a portrait of a young Goguryeo-Pyongyang-Anhak-Palace court-page — render a 45-second cinematic short with Goguryeo-era-Korean and Chinese subtitles.",
    "I have a watercolor of a young Goguryeo-Jian-tomb-mural artist-apprentice — produce a 30-second piece with Goguryeo-era-Korean and Chinese subtitles.",
    "Uploading a digital painting of a young Goryeo-Gaeseong-Manwoldae-palace court-page — make a 1-minute mini-drama with Goryeo-era-Korean and Mongolian subtitles.",
    "Here's a sketch of a young Goryeo-Ganghwa-island-fortress soldier-boy — render a 45-second cinematic short with Goryeo-era-Korean and Mongolian subtitles.",
    "I'm sending you a portrait of a young Goryeo-Haeinsa-Tripitaka-Koreana woodblock-carver-apprentice — produce a 30-second piece with Goryeo-era-Korean and Chinese subtitles.",
    "Uploading a watercolor of a young Goryeo-Buseoksa-temple monk-novice — build a 1-minute mini-drama with Goryeo-era-Korean and Chinese subtitles.",
    "Here's a digital portrait of a young Goryeo-Cheongju-Heungdeoksa-temple Jikji-printer-apprentice — render a 45-second cinematic short with Goryeo-era-Korean and Chinese subtitles.",
    "I have a sketch of a young Goryeo-Gangjin-celadon-kiln potter-apprentice — produce a 30-second piece with Goryeo-era-Korean and Chinese subtitles.",
    "Uploading a portrait of a young Goryeo-Gyeongju-Gameunsa-temple-stone-pagoda mason-boy — make a 1-minute mini-drama with Goryeo-era-Korean and Chinese subtitles.",
    "Here's a watercolor of a young Joseon-Hanyang-Gyeongbokgung-palace court-page — render a 45-second cinematic short with Joseon-era-Korean and Chinese subtitles.",
    "I'm sending you a digital painting of a young Joseon-Hanyang-Gwanghwamun-gate sentry-boy — produce a 30-second piece with Joseon-era-Korean and Manchu subtitles.",
    "Uploading a sketch of a young Joseon-Hanyang-Changdeokgung-Secret-Garden gardener-boy — build a 1-minute mini-drama with Joseon-era-Korean and Chinese subtitles.",
    "Here's a portrait of a young Joseon-Hanyang-Bukchon-Hanok-village scholar-boy — render a 45-second cinematic short with Joseon-era-Korean and English subtitles.",
    "I have a watercolor of a young Joseon-Hanyang-Sungkyunkwan-academy student — produce a 30-second piece with Joseon-era-Korean and Chinese subtitles.",
    "Uploading a digital portrait of a young Joseon-Hanyang-Bunwon-royal-kiln porcelain-painter-apprentice — make a 1-minute mini-drama with Joseon-era-Korean and Chinese subtitles.",
    "Here's a sketch of a young Joseon-Suwon-Hwaseong-fortress sentry-boy — render a 45-second cinematic short with Joseon-era-Korean and Chinese subtitles.",
    "I'm sending you a portrait of a young Joseon-Andong-Hahoe-village mask-carver-apprentice — produce a 30-second piece with Joseon-era-Korean and English subtitles.",
    "Uploading a watercolor of a young Joseon-Andong-Dosan-Seowon scholar-boy — build a 1-minute mini-drama with Joseon-era-Korean and Chinese subtitles.",
    "Here's a digital painting of a young Joseon-Gyeongju-Yangdong-folk-village houseboy — render a 45-second cinematic short with Joseon-era-Korean and Chinese subtitles.",
    "I have a sketch of a young Joseon-Jeonju-Hanok-village paper-fan-craftsman-apprentice — produce a 30-second piece with Joseon-era-Korean and Japanese subtitles.",
    "Uploading a portrait of a young Joseon-Jeonju-Gaeksa hostel-boy — make a 1-minute mini-drama with Joseon-era-Korean and Chinese subtitles.",
    "Here's a watercolor of a young Joseon-Damyang-bamboo-grove woodcraft-apprentice — render a 45-second cinematic short with Joseon-era-Korean and Japanese subtitles.",
    "I'm sending you a digital portrait of a young Joseon-Boseong-tea-plantation tea-picker-boy — produce a 30-second piece with Joseon-era-Korean and Chinese subtitles.",
    "Uploading a sketch of a young Joseon-Suncheon-Nagan-Eupseong-fortress sentry-boy — build a 1-minute mini-drama with Joseon-era-Korean and Chinese subtitles.",
    "Here's a portrait of a young Joseon-Mokpo-Yudal-mountain-pier dock-boy — render a 45-second cinematic short with Joseon-era-Korean and Japanese subtitles.",
    "I have a watercolor of a young Joseon-Haenam-Daeheungsa-temple monk-novice — produce a 30-second piece with Joseon-era-Korean and Chinese subtitles.",
    "Uploading a digital painting of a young Joseon-Jeju-Seongeup-folk-village haenyeo's-son — make a 1-minute mini-drama with Jeju-dialect and Korean subtitles.",
    "Here's a sketch of a young Joseon-Jeju-Hallasan-mountain shepherd-boy — render a 45-second cinematic short with Jeju-dialect and Japanese subtitles.",
    "I'm sending you a portrait of a young Joseon-Busan-Dongnae-eupseong-fortress sentry-boy — produce a 30-second piece with Joseon-era-Korean and Japanese subtitles.",
    "Uploading a watercolor of a young Joseon-Busan-Choryang-Waegwan Japanese-trade interpreter-boy — build a 1-minute mini-drama with Joseon-era-Korean and Tsushima-Japanese subtitles.",
    "Here's a digital portrait of a young Joseon-Daegu-Dalseong-eupseong court-page — render a 45-second cinematic short with Joseon-era-Korean and Chinese subtitles.",
    "I have a sketch of a young Joseon-Gangneung-Ojukheon scholar-boy — produce a 30-second piece with Joseon-era-Korean and Chinese subtitles.",
    "Uploading a portrait of a young Joseon-Pyongyang-Daedongmun-gate sentry-boy — make a 1-minute mini-drama with Joseon-era-Korean and Chinese subtitles.",
    "Here's a watercolor of a young Joseon-Pyongyang-Jangan-jeonggak-pavilion court-page — render a 45-second cinematic short with Joseon-era-Korean and Manchu subtitles.",
    "I'm sending you a digital painting of a young Joseon-Hamheung-Hamgyeong-province soldier-boy — produce a 30-second piece with Joseon-era-Korean and Manchu subtitles.",
    "Uploading a sketch of a young Joseon-Gaeseong-Manwoldae-Palace ruins gardener-boy — build a 1-minute mini-drama with Joseon-era-Korean and Chinese subtitles.",
    "Here's a portrait of a young Joseon-Yeongdong-Wolak-Mountain hermit-master's apprentice — render a 45-second cinematic short with Joseon-era-Korean and Chinese subtitles.",
    "I have a watercolor of a young Joseon-Jangseong-Pilam-Seowon scholar-boy — produce a 30-second piece with Joseon-era-Korean and Chinese subtitles.",
    "Uploading a digital portrait of a young Joseon-Gimhae-Suro-King-tomb temple-attendant — make a 1-minute mini-drama with Joseon-era-Korean and Sanskrit subtitles.",
    "Here's a sketch of a young Joseon-Sangju-bamboo-mat-weaver apprentice — render a 45-second cinematic short with Joseon-era-Korean and Chinese subtitles.",
    "I'm sending you a portrait of a young Joseon-Ulsan-Yangban-village young-master — produce a 30-second piece with Joseon-era-Korean and Chinese subtitles.",
    "Uploading a watercolor of a young Joseon-Cheongju-Yongduam Hyangyak-school student — build a 1-minute mini-drama with Joseon-era-Korean and Chinese subtitles.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
