"""x15 cr_compositor_only — 14x SFT user_goal expansion (short briefs only).

Schema: USER_GOALS: list[str] (rationale/intents/chain templated downstream).

Chain (blueprint): StoryAgent → ScreenplayAgent → KeyFrameAgent → VideoAgent →
                   CompositorAgent

Reject biases per blueprint notes:
  - NO Music / Ambience — user must not mention BGM / atmosphere
  - NO Transcription / Translation — user must not mention subtitles
  - NO AudioMix — corollary
  - NO VideoAnalysis / Highlight — user did NOT upload a video
  - NO BriefEnricher / IntakeImage — user did NOT upload an image
  - NO StyleTransfer / VideoExtend — clean cinematic generation only

Style: cinematic mini-drama briefs across sci-fi / fantasy / noir / period /
contemporary / horror / western / animation / experimental. Length expectations
explicit (15s / 30s / 1min / 2min etc).

This file holds SHORT briefs only. Long-story (~500-word original fiction)
variants live in shape_cr_compositor_only_long.py per blueprint convention.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    # ── sci-fi / space (40) ───────────────────────────────────────────────
    "I want a 30-second mini-drama about a lone technician aboard a derelict space station picking up a strange signal from a sealed cargo bay.",
    "Make me a 1-minute short film where a colonist on Mars discovers a working antique radio half-buried in red dust.",
    "Create a 45-second cinematic clip about an android in a derelict factory slowly remembering its first activation.",
    "Produce a 30-second sci-fi piece where a deep-space miner finds a child's drawing on the wall of an abandoned habitat.",
    "Build a 2-minute mini-drama: a generation-ship navigator wakes from cryosleep to find every other pod empty.",
    "Render a 30-second short about a librarian on a moon colony discovering a forbidden book hidden inside a hollow rock.",
    "Generate a 1-minute cinematic piece about a teenage girl on a terraformed asteroid receiving a cassette mailed from Earth 200 years ago.",
    "I'd like a 45-second mini-drama where two engineers on a lunar farm watch Earth disappear behind a dust cloud.",
    "Cook up a 30-second sci-fi short where a dishwasher robot in a Mars diner becomes self-aware mid-shift.",
    "Make a 2-minute clip about a courier in a flooded future Tokyo delivering a mysterious package across a sunken intersection.",
    "Produce a 30-second short of a retired starship captain restoring a model spaceship in his cramped habitat unit.",
    "Create a 1-minute mini-drama about a child on a colony ship discovering a stowaway alien creature in the ducts.",
    "Build a 30-second piece where a deep-sea diver finds a crashed UFO emitting a slow blue pulse on the ocean floor.",
    "Render a 45-second short of a janitor on the International Space Station hearing knocking from outside the airlock.",
    "I want a 1-minute cinematic clip about a botanist on a remote rim-world watching a single Earth flower bloom for the first time.",
    "Make me a 30-second mini-drama where a courier drone on a futuristic rooftop refuses to deliver its package and instead opens it.",
    "Generate a 2-minute short about a cyborg veteran returning to her family farm and trying to remember how to cook.",
    "Create a 45-second sci-fi piece where a pilot in a one-person fighter ship watches a binary star eclipse in silence.",
    "Produce a 30-second short of an alien teenager translating a graffiti tag left by a long-vanished human.",
    "I'd like a 1-minute cinematic clip about a robotic gardener tending the last living tree in a domed city.",
    "Build a 30-second mini-drama where a quantum physicist's coffee starts boiling in reverse during a lunch break.",
    "Render a 2-minute piece about a salvager picking through a crashed colony ship and finding her grandmother's wedding ring.",
    "Make a 45-second clip of a cleaning bot mopping a corridor while the station decompresses one room at a time.",
    "Cook up a 30-second short where a hacker in a neon Tokyo apartment discovers a folder labeled with her own name.",
    "Generate a 1-minute mini-drama about a moon-base meteorologist watching a storm form on Earth from orbit.",
    "Create a 30-second cinematic piece where a deep-sea submersible drifts past a school of bioluminescent jellyfish in unison.",
    "Produce a 2-minute short about an asteroid miner whose drill wakes something hibernating inside the rock.",
    "I want a 45-second mini-drama of a customer-service AI in an empty office tower realizing the workday has been over for years.",
    "Build a 30-second short about a teenage astronaut intern fixing her first solar panel during her first spacewalk.",
    "Render a 1-minute clip of an exiled scientist in a glass dome watching a dust storm cross a Martian plain.",
    "Make me a 30-second cinematic piece where a homestead robot reads an old letter addressed to its dead owner.",
    "Generate a 2-minute mini-drama about a tugboat captain ferrying a damaged satellite back through the rings of Saturn.",
    "Create a 45-second short where a future zoo keeper feeds the last pair of giraffes inside an Earth-bound preserve.",
    "Produce a 30-second cinematic piece about a holographic guide leading a child through ruins of an ancient earth city.",
    "I'd like a 1-minute mini-drama of two off-duty engineers playing chess on a viewing deck above an alien sunrise.",
    "Build a 30-second short where an underwater colony's lights flicker as something massive moves past the windows.",
    "Render a 2-minute piece about a child receiving her first letter from her father who works on a mining vessel near Pluto.",
    "Make a 45-second sci-fi clip of an interstellar marketplace with vendors haggling in a hundred different languages.",
    "Cook up a 30-second mini-drama where a sentient AI in a derelict subway station turns off its own power.",
    "Generate a 1-minute short about a young engineer fixing a broken weather satellite while a comet passes nearby.",
    # ── fantasy / mythic (40) ─────────────────────────────────────────────
    "I want a 1-minute mini-drama about a young apprentice mage practicing a flame spell late at night in a wizard's tower.",
    "Make me a 45-second cinematic short where a dragon hatchling emerges from a cave during a snowstorm.",
    "Create a 2-minute piece about a forest witch foraging mushrooms while shadows whisper to her between trees.",
    "Produce a 30-second mini-drama where a knight kneels beside her dying horse as dusk falls over a battlefield.",
    "Build a 45-second short about a young ferryman crossing the river of souls with a single anxious passenger.",
    "Render a 1-minute cinematic clip of a faerie queen holding court in a hollow oak tree at twilight.",
    "Generate a 30-second piece where a mermaid trades a memory to a sea-witch for a single human breath.",
    "I'd like a 2-minute mini-drama about a young scribe in a dragon library transcribing a myth no one has read in centuries.",
    "Cook up a 45-second short where a wandering bard plays a lute in a tavern while a stone gargoyle leans in to listen.",
    "Make a 30-second cinematic piece about a winter spirit kneeling to thaw a single frozen songbird from a branch.",
    "Produce a 1-minute mini-drama about a young alchemist mixing a forbidden tincture in a hidden cellar.",
    "Create a 45-second short of a goblin courier delivering a sealed scroll across a moonlit thieves' market.",
    "Build a 30-second piece where a centaur teacher leads young students through a glade collecting healing herbs.",
    "Render a 2-minute mini-drama of a sorceress racing through stone corridors as her tower collapses behind her.",
    "I want a 1-minute cinematic clip about a desert mystic painting prophecies onto temple walls with finger and ink.",
    "Generate a 30-second short where a cloaked traveler trades a coin to a river dragon for safe passage.",
    "Make me a 45-second mini-drama of a young paladin polishing her grandfather's sword the night before battle.",
    "Cook up a 1-minute short where a forest god heals a wounded fox under a canopy of golden leaves.",
    "Create a 30-second cinematic piece about a witch's familiar — a small black cat — guarding an open spellbook.",
    "Produce a 2-minute mini-drama about a swamp druid coaxing a stubborn vine to release a trapped child.",
    "Build a 45-second short of a clockmaker faerie tuning the gears of a mechanical butterfly.",
    "Render a 30-second clip of a mountain spirit watching the first snow fall on a sleeping village.",
    "I'd like a 1-minute cinematic piece about a sea siren combing her hair while sailors stare from the ship's rail.",
    "Make a 30-second short where a kitchen pixie steals an apple slice from a baker's cooling rack.",
    "Generate a 2-minute mini-drama about a lonely cartographer mapping an enchanted forest that rearranges itself nightly.",
    "Produce a 45-second cinematic piece about an old wizard teaching a young owl to read a single rune.",
    "Build a 30-second short of a cursed knight removing his helm in a meadow of glowing moonflowers.",
    "Render a 1-minute mini-drama where a young fox-spirit girl visits her grandmother's grave in a wooded shrine.",
    "Cook up a 30-second piece about a dwarven smith forging a key from a single drop of starlight.",
    "Make me a 45-second cinematic short where a halfling baker delivers bread to a sleeping giant.",
    "I want a 2-minute mini-drama about a forest druid singing a sapling tree back into bloom.",
    "Generate a 30-second clip of a temple priestess lighting candles around a stone idol at sunrise.",
    "Create a 1-minute short about a young witch riding a broom-cycle home along a country road at dusk.",
    "Produce a 45-second mini-drama where a goblin librarian slams a forbidden book shut as a child walks in.",
    "Build a 30-second piece about a unicorn drinking from a moonlit pond while a deer watches.",
    "Render a 2-minute cinematic clip of a young mage taming a magical fox spirit in a snowed-in cabin.",
    "I'd like a 30-second short where a wood-elf scout reads tracks left by an unknown beast at the forest edge.",
    "Make a 1-minute mini-drama of a sea witch trading a memory for the song of a passing whale.",
    "Cook up a 45-second cinematic piece about a young dragon-rider braiding a flying mount's mane.",
    "Generate a 30-second short of a lonely lighthouse keeper waving back at a passing mermaid in a storm.",
    # ── noir / mystery / detective (30) ───────────────────────────────────
    "Make me a 1-minute noir mini-drama about a tired private detective reviewing case files in a smoke-filled office at 3 AM.",
    "I want a 45-second cinematic short of a femme fatale leaving a key in the rain on a Brooklyn fire-escape.",
    "Create a 30-second piece where a bagman counts cash under a bare bulb in an old hotel basement.",
    "Produce a 2-minute mini-drama about a private eye following a stranger through a fog-soaked Chinatown alley.",
    "Build a 30-second noir clip where a poisoned drink sits untouched on a velvet-cushioned barstool.",
    "Render a 45-second cinematic short of two diplomats exchanging a sealed envelope in a vacant theater lobby.",
    "Cook up a 1-minute mini-drama where a bookkeeper hides a ledger inside a hollowed-out novel as footsteps approach.",
    "Generate a 30-second piece about a detective's hand reaching for a revolver as the office door opens.",
    "Make a 2-minute noir short where a war widow returns to her husband's office and finds it ransacked.",
    "I'd like a 45-second mini-drama of a stranger leaving a coded note tucked inside a folded newspaper on a park bench.",
    "Produce a 30-second cinematic clip where a cabaret singer locks eyes with someone watching from a back booth.",
    "Build a 1-minute noir short of a thief listening to a radio broadcast about her own arrest.",
    "Create a 30-second piece about a forger studying a passport under a magnifier in a dim back room.",
    "Render a 45-second mini-drama where a corrupt official receives a manila folder slid under his door.",
    "Cook up a 2-minute noir piece about a getaway driver waiting in the rain outside a closed jewelry store.",
    "I want a 30-second short of a bartender hiding a gun behind whiskey bottles as two strangers walk in.",
    "Make me a 1-minute mini-drama of a courier stepping off a midnight train and watching the platform empty.",
    "Generate a 45-second cinematic clip where a young secretary reads a letter she wasn't supposed to open.",
    "Produce a 30-second piece about a witness adjusting his hat as he steps into a courtroom.",
    "Build a 2-minute noir mini-drama where a poker game goes silent as a senator sits down at the table.",
    "Create a 30-second short of a stranger lighting two cigarettes in a vacant train compartment.",
    "Render a 45-second cinematic piece about an undercover cop signaling her partner across a crowded ballroom.",
    "I'd like a 1-minute noir clip where a typist finds a bullet on her desk under a stack of memos.",
    "Make a 30-second mini-drama about a chauffeur reading the morning paper while waiting outside an ornate hotel.",
    "Cook up a 45-second short where a stranger hands a child an envelope on a snow-covered park bench.",
    "Generate a 2-minute cinematic piece of a retired detective unrolling an old map across a kitchen table.",
    "Produce a 30-second noir short of a woman climbing a fire-escape ladder in heels under a flickering streetlamp.",
    "Build a 1-minute mini-drama where a pawnshop owner appraises a stolen pocket watch under a green-shaded lamp.",
    "I want a 45-second cinematic clip about a hatcheck girl recognizing a missing diamond on a hat band.",
    "Render a 30-second short of a smuggler hiding microfilm inside a hollow chess piece on a hotel windowsill.",
    # ── period / historical (35) ──────────────────────────────────────────
    "Make me a 1-minute period mini-drama about a Victorian gardener tending a hothouse orchid in winter dawn.",
    "I want a 45-second cinematic short of a Renaissance painter mixing pigments in a candlelit workshop.",
    "Create a 2-minute piece about a young Roman scribe copying senate records by oil-lamp.",
    "Produce a 30-second mini-drama where a Tudor handmaiden lays out her queen's robes for the morning.",
    "Build a 45-second cinematic short of a samurai polishing his katana in a sunlit teahouse.",
    "Render a 1-minute piece about a Han-dynasty potter shaping a celadon bowl on a hand-turned wheel.",
    "Cook up a 30-second short where a Mongol scout reads the wind on a steppe at sunrise.",
    "Generate a 2-minute mini-drama about a French Revolution baker hiding a fugitive in his bread oven.",
    "Make a 45-second period clip of a 1920s flapper reading a love letter in a Manhattan speakeasy.",
    "I'd like a 30-second short of a WWI nurse closing a soldier's eyelids in a candlelit field hospital.",
    "Produce a 1-minute mini-drama about a 16th-century Spanish navigator marking a star chart by lantern.",
    "Build a 45-second cinematic short of a Russian peasant girl carrying water from a frozen well at dawn.",
    "Create a 30-second period piece where an Ottoman calligrapher signs his name with a final precise flourish.",
    "Render a 2-minute mini-drama about an Edwardian maid eavesdropping outside a wood-paneled study.",
    "I want a 45-second cinematic short of a Tang-dynasty poet reading verse to a single lantern by a koi pond.",
    "Make me a 30-second period piece where a Chinese opium-house cook ladles broth into a porcelain bowl.",
    "Generate a 1-minute mini-drama of a medieval monk illuminating a manuscript in a cold scriptorium.",
    "Cook up a 45-second cinematic short where a Victorian astronomer calibrates a brass telescope on a rooftop.",
    "Build a 30-second period clip about an Egyptian priestess inscribing a hieroglyph onto a temple wall.",
    "Produce a 2-minute mini-drama where a Heian noblewoman reads poetry behind a bamboo screen at dusk.",
    "Create a 45-second cinematic short of a Ming dynasty merchant counting coins on an abacus by candlelight.",
    "Render a 30-second period short about a Greek herbalist drying lavender in a sunlit Aegean courtyard.",
    "I'd like a 1-minute mini-drama where a Civil-War-era surgeon scrubs his hands in a basin before operating.",
    "Make a 30-second cinematic piece of a Norse sailor whittling a wooden charm on a longship at dawn.",
    "Cook up a 45-second period clip about an Aztec priest watching the sun rise over a stepped pyramid.",
    "Generate a 2-minute mini-drama of a French peasant girl writing a letter to her brother at the front in 1916.",
    "Build a 30-second short where a Roman legionnaire carves his name into a stone of a frontier fort.",
    "I want a 45-second cinematic piece of a 19th-century Russian violin maker varnishing a finished violin.",
    "Make me a 1-minute mini-drama of a 14th-century Florentine clockmaker oiling tower-clock gears at sunrise.",
    "Produce a 30-second period clip where a Korean queen consort offers tea to a foreign ambassador in silence.",
    "Create a 45-second cinematic short of a dust-bowl Oklahoma farmer surveying his cracked field at dusk.",
    "Render a 30-second mini-drama about an early 20th-century telephone operator plugging a long-distance call.",
    "Build a 1-minute period piece where a Tokugawa-era farmer harvests rice along terraced paddies.",
    "Cook up a 2-minute mini-drama of a 1940s war correspondent typing dispatches in a hotel room in Cairo.",
    "Generate a 45-second cinematic short of an Inca quipu keeper tying knots into a record cord by lamp.",
    # ── contemporary / slice-of-life (35) ─────────────────────────────────
    "Make me a 30-second mini-drama of a single father teaching his daughter how to make pancakes on a Saturday morning.",
    "I want a 1-minute cinematic short about an old man feeding stray cats outside his apartment in winter.",
    "Create a 45-second piece where a teenage girl gets her acceptance letter and reads it alone on her bed.",
    "Produce a 2-minute mini-drama about a delivery worker in monsoon Mumbai sheltering a stray dog under his poncho.",
    "Build a 30-second short of a librarian closing the doors at the end of a long, quiet day.",
    "Render a 45-second cinematic clip of a young couple painting their first apartment together late at night.",
    "Cook up a 1-minute mini-drama where a retired ballet dancer instructs a single child in an empty studio.",
    "Generate a 30-second piece about a marathon runner crossing the finish line behind everyone else, alone.",
    "I'd like a 2-minute short of a barista in Tokyo writing a haiku on every receipt during a slow morning shift.",
    "Make a 45-second cinematic piece of a high-school music teacher conducting an empty rehearsal hall in the dark.",
    "Produce a 30-second mini-drama where a busker plays violin on a Brooklyn subway platform in the rush.",
    "Build a 1-minute short about a window cleaner pausing his work to watch a wedding procession from above.",
    "Create a 45-second cinematic piece of a single mother repairing a broken toy in a New York walk-up.",
    "Render a 30-second mini-drama about a bus driver making her last stop on Christmas Eve.",
    "I want a 2-minute clip of a retired postman delivering one last letter to a friend on his old route.",
    "Generate a 30-second short of a fishmonger packing up unsold fish for a stray cat at closing.",
    "Make me a 45-second cinematic piece about a barber giving a child his first haircut.",
    "Cook up a 1-minute mini-drama of a security guard in a museum quietly admiring a single painting after hours.",
    "Produce a 30-second short where a flower-seller arranges her last bouquet of the day for a customer who never came.",
    "Build a 45-second piece about a window seamstress hand-finishing a wedding dress at dusk.",
    "Create a 2-minute mini-drama about a high-school chess club captain teaching openings to a brand-new freshman.",
    "I'd like a 30-second cinematic short of a hospital cleaner mopping a hallway as a baby's cry echoes down it.",
    "Render a 1-minute clip about a cab driver in São Paulo helping a tourist find an address by hand-drawn map.",
    "Make a 45-second mini-drama of a ferry captain on a slow Greek-island route reading a paperback between stops.",
    "Cook up a 30-second short where a knife-sharpener walks his cart down a cobbled French village street.",
    "Generate a 2-minute cinematic piece about a midwife cycling through dawn fog to deliver a baby in a rural village.",
    "Produce a 45-second mini-drama where a piano tuner finishes a final adjustment in a cathedral as light comes through stained glass.",
    "Build a 30-second short of a sushi chef in Osaka making one last omakase plate for a regular before retirement.",
    "I want a 1-minute cinematic piece about a high-school custodian unlocking the gym before dawn for a basketball game.",
    "Make me a 45-second mini-drama of a recently widowed grandmother tending her vegetable garden alone for the first season.",
    "Render a 30-second clip where a teen guitarist plays in front of a hospital window for her sleeping mother.",
    "Generate a 2-minute short about a young firefighter packing his locker on his last day before a transfer.",
    "Cook up a 30-second cinematic piece of a bookseller hand-wrapping a customer's book in brown paper.",
    "Create a 45-second mini-drama where a midnight diner cook prepares a single grilled-cheese for a regular truck driver.",
    "Build a 1-minute clip of a school-crossing guard waving the last child across just as the rain begins.",
    # ── horror / suspense (25) ────────────────────────────────────────────
    "Make me a 30-second horror mini-drama where a babysitter hears scratching from inside the closet.",
    "I want a 1-minute cinematic short about a hiker realizing the path she's been on is slowly leading her in a circle.",
    "Create a 45-second piece where a child's drawing on the fridge slowly changes overnight.",
    "Produce a 30-second mini-drama about a museum guard noticing one of the wax figures has moved between rounds.",
    "Build a 2-minute horror short where a librarian shelves books at closing time and starts hearing whispering from the rare-books room.",
    "Render a 30-second cinematic clip of a young couple's first night in a new house when the basement door slowly opens by itself.",
    "Cook up a 45-second horror piece where a girl in an attic discovers her grandmother's diary describing her own life.",
    "Generate a 30-second mini-drama about a night nurse hearing her own name being whispered down an empty hallway.",
    "I'd like a 1-minute cinematic short of a woman finding a Polaroid of herself sleeping on her own pillow.",
    "Make a 30-second piece about a deep-sea diver realizing his oxygen line is being held above the water by something not his crew.",
    "Produce a 45-second horror clip where a child's swing in the backyard begins to sway with no wind.",
    "Build a 2-minute mini-drama about a forester noticing the same set of footprints following him for three days.",
    "Create a 30-second short where a security camera at a 24-hour gas station catches a figure that wasn't there a moment before.",
    "Render a 45-second horror cinematic piece about a young couple in a remote cabin discovering the door is locked from outside.",
    "I want a 30-second mini-drama where a woman finds her morning coffee already poured and warm, and she lives alone.",
    "Make me a 1-minute clip of a taxi driver realizing his back-seat passenger never gives an address but is still there.",
    "Cook up a 30-second horror piece where a spelunker in a cave hears a child counting in the dark behind him.",
    "Generate a 45-second mini-drama of a girl in an empty school gymnasium hearing the basketballs start bouncing one by one.",
    "Produce a 30-second cinematic short where a postcard arrives written in the recipient's own handwriting from a place she never visited.",
    "Build a 2-minute horror piece about a writer noticing his typewriter typing a few extra words while he sleeps.",
    "Create a 45-second mini-drama where a man taking down Christmas lights finds an extra string of lights twined around his porch rail.",
    "Render a 30-second clip of a young girl playing piano while a face slowly forms in the wallpaper behind her.",
    "I'd like a 1-minute horror short of a barista finding the same regular customer who drowned last summer ordering a coffee at closing.",
    "Make a 45-second mini-drama where a couple realizes their reflection in the mirror is one beat behind their motion.",
    "Cook up a 30-second cinematic piece of a child waking up to find every door in the house standing slightly ajar.",
    # ── western / frontier (25) ───────────────────────────────────────────
    "Make me a 1-minute western mini-drama about a sheriff cleaning his revolver on the porch of an empty saloon at dusk.",
    "I want a 45-second cinematic clip of a young homesteader chopping firewood at sunrise with a child watching from the porch.",
    "Create a 30-second piece where a stagecoach driver waters his horses at a desert way station at noon.",
    "Produce a 2-minute mini-drama about a Cherokee scout leading a wagon party across a flooded creek.",
    "Build a 45-second short of a cowgirl repairing her saddle by lantern light in a quiet barn.",
    "Render a 30-second cinematic clip of a piano player picking out a tune in a rough mining-town saloon.",
    "Cook up a 1-minute mini-drama where a prospector pans gold at a riverbank as a hawk circles overhead.",
    "Generate a 45-second western piece about a young schoolteacher unloading books from a wagon at her first frontier post.",
    "I'd like a 30-second short of a blacksmith shoeing a horse outside a sun-bleached general store.",
    "Make a 2-minute mini-drama of a former Confederate cavalryman returning home to find his land now belongs to someone else.",
    "Produce a 45-second cinematic piece where a Mexican vaquero ropes a runaway calf at golden hour.",
    "Build a 30-second western short of a doctor riding through a dust storm to reach a sick child on a remote ranch.",
    "Create a 1-minute mini-drama where a frontier preacher reads a sermon to an empty pew on Sunday morning.",
    "Render a 45-second clip of a Pony-Express rider exchanging mailbags at a relay station in the rain.",
    "I want a 30-second cinematic short of a sharpshooter cleaning her rifle by candlelight in a wagon at midnight.",
    "Make me a 2-minute mini-drama about a Texas trail boss leading cattle across a rain-swollen river.",
    "Cook up a 45-second western piece where a young boy tries on his late father's hat in front of a cracked mirror.",
    "Generate a 30-second clip of a bartender pouring whiskey for a stranger as the doors swing open in silence.",
    "Produce a 1-minute mini-drama of a frontier midwife arriving at a homestead by buckboard at dawn.",
    "Build a 45-second short where a railway surveyor marks a peg on a hilltop overlooking endless prairie.",
    "Create a 30-second cinematic piece about a frontier widow lighting a single candle in a cabin window for her son.",
    "Render a 2-minute mini-drama about a Lakota grandfather teaching his granddaughter to read the stars.",
    "I'd like a 45-second western short of a saloon owner sweeping the porch as a tumbleweed rolls past.",
    "Make a 30-second clip of a young trapper checking his snares along a frosted creek in early winter.",
    "Cook up a 1-minute mini-drama of an old Apache scout reading a single arrowhead found on a battlefield ridge.",
    # ── animation-style / experimental (35) ───────────────────────────────
    "Make me a 30-second animation-style mini-drama about a paper-folded crane learning to fly in a Japanese living room.",
    "I want a 1-minute Studio-Ghibli-esque short of a young witch and her cat tending a windowsill herb garden.",
    "Create a 45-second claymation-style piece about a grumpy snail traveling across a tile floor to deliver a postcard.",
    "Produce a 30-second cel-shaded mini-drama of a child befriending a forest spirit at the edge of a sunlit clearing.",
    "Build a 2-minute animated short about a paper boat being chased downstream by curious koi in a stylized river.",
    "Render a 45-second cut-out-collage clip of a girl writing a letter while her words turn into birds and fly out the window.",
    "Cook up a 30-second silent-film-style piece of a bowler-hatted man chasing his runaway hat through a stylized cobbled street.",
    "Generate a 1-minute mini-drama about a sentient teapot in an old Parisian kitchen serving its last customer of the day.",
    "I'd like a 45-second pixel-art-style short of a knight inside a dungeon realizing the dragon is just lonely.",
    "Make a 30-second hand-drawn piece about a single firefly leading a lost child through a glowing forest.",
    "Produce a 2-minute animation-style mini-drama of a paper umbrella protecting a kitten from a stylized rainstorm.",
    "Build a 45-second clay-style short where a brown-paper bag is blown across a stop-motion city park.",
    "Create a 30-second cel-shaded clip of a robot vacuum cleaner falling in love with a single dust mote.",
    "Render a 1-minute mini-drama about a cuckoo-clock cuckoo escaping its clock and exploring an empty parlor.",
    "I want a 45-second silent-cinema-style piece of a chimney sweep dancing on a Parisian rooftop at twilight.",
    "Make me a 30-second dreamy animation about a scarf being blown through a mountain village on a windy day.",
    "Cook up a 2-minute Studio-Ghibli-esque mini-drama about a young train conductor and the passengers' lost luggage.",
    "Generate a 45-second hand-drawn cinematic short of a coastal village's lighthouse keeper befriending a friendly fog.",
    "Produce a 30-second cut-out style clip about a paper airplane flying across an entire city in one continuous shot.",
    "Build a 1-minute dreamlike mini-drama of a girl whose shadow takes a different walk than her body.",
    "Create a 45-second claymation piece of a button falling off a coat and rolling across a busy office.",
    "Render a 30-second cel-shaded short about a cup of tea making conversation with a slice of toast.",
    "I'd like a 2-minute Ghibli-style mini-drama of a young apprentice cloud-painter touching up the morning sky.",
    "Make a 45-second silent-style cinematic piece where a wind-up music-box ballerina dances for a watching cat.",
    "Cook up a 30-second pixel-art short of a wandering pixel knight finding a campfire and a friendly ghost.",
    "Generate a 1-minute hand-drawn mini-drama of a young chimney sweep planting a single flower in a brick crack.",
    "Produce a 45-second experimental piece of a girl whose drawings come to life when she's not watching.",
    "Build a 30-second animation-style short of a boy in a bookshop being led between aisles by a mysterious cat.",
    "Create a 2-minute cel-shaded mini-drama about a tea-shop owner whose teapots tell different fortunes.",
    "Render a 45-second cinematic dreamscape of a child stepping through the back of a wardrobe into a meadow.",
    "I want a 30-second silent-film-style piece of a clown in a deserted circus tent practicing for an empty crowd.",
    "Make me a 1-minute hand-drawn short of a deer mother teaching her fawn to recognize edible mushrooms.",
    "Cook up a 45-second mini-drama where a stuffed bear in a child's room comforts a smaller, newer toy.",
    "Generate a 30-second collage-style piece of newspaper headlines forming a tornado around a confused reader.",
    "Produce a 1-minute experimental cinematic clip of a typewriter typing a love letter all by itself in a vacant office.",
    # ── mythological retellings (35) ──────────────────────────────────────
    "Make me a 1-minute mini-drama retelling Orpheus and Eurydice on a rainy Athens metro platform.",
    "I want a 45-second cinematic short retelling Sisyphus pushing a single shopping cart up a frozen hill.",
    "Create a 30-second piece retelling Persephone returning to Demeter on the steps of a 1950s Detroit row house.",
    "Produce a 2-minute mini-drama retelling Icarus testing his hand-built glider on a chalk cliff at dusk.",
    "Build a 30-second short retelling the Hindu tale of Ganesha's broken tusk in a small Mumbai apartment kitchen.",
    "Render a 45-second cinematic short retelling Anansi tricking the sky-god in a Brooklyn community garden.",
    "Cook up a 1-minute mini-drama retelling Loki forging Mjölnir at a contemporary Reykjavik blacksmith stall.",
    "Generate a 30-second short retelling the Aztec story of Quetzalcoatl bringing maize to a Mexico-City rooftop garden.",
    "I'd like a 45-second cinematic clip retelling Atalanta winning the foot race on a rural Greek high-school track.",
    "Make a 30-second piece retelling the Yoruba tale of Eshu placing a contradictory hat on a small village road.",
    "Produce a 2-minute mini-drama retelling Pygmalion's statue waking inside a Brooklyn pottery studio.",
    "Build a 45-second cinematic short retelling Demeter searching for Persephone across a dust-bowl Oklahoma farm.",
    "Create a 30-second short retelling Mawu-Lisa weaving day and night on a 1970s Lagos textile loom.",
    "Render a 1-minute mini-drama retelling Coyote stealing fire on a remote Arizona mesa at dusk.",
    "I want a 30-second cinematic piece retelling Kintaro wrestling a giant bear inside a quiet Sapporo dojo.",
    "Cook up a 45-second short retelling Mulan tying back her hair on the morning she leaves for the army in 21st-century Shanghai.",
    "Generate a 1-minute mini-drama retelling Vasilisa lighting the skull-lantern in a Saint-Petersburg apartment hallway.",
    "Make me a 30-second short retelling the Cherokee story of how the strawberry came to be on an Appalachian porch.",
    "Produce a 45-second piece retelling the Sami story of the Northern Lights as ancestors playing on a frozen Nordic lake.",
    "Build a 30-second cinematic clip retelling Maui pulling islands from the sea on a Hawaiian fishing pier.",
    "I'd like a 2-minute mini-drama retelling Brahma falling asleep over a creation tablet at a Varanasi study desk.",
    "Render a 45-second clip retelling Athena weaving with Arachne in a contemporary Athens textile-co-op courtyard.",
    "Cook up a 30-second piece retelling Anubis weighing a heart against a feather inside a Cairo museum at midnight.",
    "Make a 1-minute mini-drama retelling Aphrodite emerging from sea-foam on a Naxos beach at dawn.",
    "Produce a 30-second short retelling Pandora opening the box at a Mediterranean storage-unit auction.",
    "Generate a 45-second cinematic short retelling the Maori myth of Maui slowing the sun on a North Island rooftop.",
    "Build a 1-minute mini-drama retelling the Yoruba tale of Oya summoning a storm on a Lagos rooftop.",
    "Create a 30-second short retelling the Inuit myth of Sedna and the creatures of the deep on a contemporary Alaskan dock.",
    "I want a 45-second cinematic short retelling the Norse story of Idunn's golden apples on a Stockholm rooftop garden.",
    "Cook up a 30-second piece retelling Loki disguised as a salmon in a Norwegian river.",
    "Generate a 1-minute mini-drama retelling Dionysus arriving at a small-town Iowa wine festival.",
    "Make me a 45-second cinematic clip retelling Hermes delivering a final telegram across an empty London station.",
    "Produce a 30-second short retelling Hephaestus forging a wedding ring in a Brooklyn jewelry workshop.",
    "Build a 2-minute mini-drama retelling the Hopi creation story on a contemporary Arizona sandstone outcrop.",
    "I'd like a 1-minute mini-drama retelling La Llorona walking a foggy Albuquerque arroyo at midnight.",
    # ── monodrama / character study (30) ──────────────────────────────────
    "Make me a 1-minute monodrama of a former concert pianist discovering she can no longer feel her left hand at her childhood Steinway.",
    "I want a 45-second character study of an aging diner owner closing her restaurant for the last time after 40 years.",
    "Create a 30-second monodrama of a retired ballerina watching her younger self in an old VHS recording.",
    "Produce a 2-minute character study of a long-haul truck driver pulling into a rest-stop on Christmas Eve.",
    "Build a 30-second monodrama of an elderly clockmaker locking his shop on his last working day.",
    "Render a 45-second character study of a war veteran visiting his old commanding officer's grave.",
    "Cook up a 1-minute monodrama of a single mother reading her son's college acceptance letter alone in her kitchen.",
    "Generate a 30-second piece of a retired ferry captain visiting her old vessel one last time before it's scrapped.",
    "I'd like a 45-second character study of an older bookseller wrapping the final book on her closing-day shelf.",
    "Make a 30-second monodrama of an old jazz drummer practicing alone in his garage after his last gig fell through.",
    "Produce a 2-minute character study of a watchmaker assembling his last commission in a quiet workshop.",
    "Build a 45-second monodrama of an old librarian reading at her favorite reading-room window for the last time.",
    "Create a 30-second piece of an aging tightrope walker practicing on a rope strung in her retirement-home backyard.",
    "Render a 1-minute character study of an old shipwright launching a small dinghy he built over a decade.",
    "I want a 30-second monodrama of an older painter cleaning her last brush at the end of a 50-year career.",
    "Cook up a 45-second piece of a retired sea captain folding a flag from his old vessel.",
    "Generate a 1-minute character study of an old cartographer drawing his very last map of a beloved hometown.",
    "Make me a 30-second monodrama of an aging beekeeper saying goodbye to her last hive.",
    "Produce a 45-second character study of an older barber giving himself his very last haircut in his closing shop.",
    "Build a 30-second monodrama of a retired firefighter sitting alone in his old engine on its decommission day.",
    "I'd like a 2-minute character study of an old surveyor walking his favorite ridge for the last time.",
    "Render a 45-second monodrama of an aging tailor pressing the final seam of his closing-day suit.",
    "Cook up a 1-minute character study of an older diving instructor surfacing from her very last reef dive.",
    "Make a 30-second monodrama of an aging chess master setting up his pieces for an empty opponent's chair.",
    "Generate a 45-second piece of an old typesetter pulling the final proof from his decommissioned press.",
    "Produce a 30-second character study of an old radio operator powering down his vacuum-tube set for good.",
    "Build a 1-minute monodrama of an aging cellist tuning her instrument before her last student lesson.",
    "Create a 45-second piece of an old maître d' polishing the silverware for his last Saturday-night service.",
    "I want a 30-second character study of a retiring fishery worker watching her last gillnet leave the harbor.",
    "Render a 2-minute monodrama of an aging stage manager dimming the house lights on her last touring show.",
    # ── road-trip / pilgrimage (15) ───────────────────────────────────────
    "Make me a 1-minute mini-drama about three sisters scattering their mother's ashes along a coastal highway.",
    "I want a 45-second cinematic short of a young woman driving her grandmother's vintage car across a state to a wedding.",
    "Create a 30-second piece where a teenage girl rides her bike across her hometown to deliver a letter she wrote at 14.",
    "Produce a 2-minute mini-drama of a widower walking the Camino de Santiago with his wife's old hiking pole.",
    "Build a 45-second short of a college freshman driving home for Thanksgiving for the first time alone.",
    "Render a 30-second cinematic clip of a soldier on his last leg of a 4,000-mile transcontinental drive home.",
    "Cook up a 1-minute mini-drama of two estranged brothers driving their late father's truck back to his hometown.",
    "Generate a 30-second short of a young Buddhist on a pilgrimage to a remote mountain monastery.",
    "I'd like a 45-second cinematic piece about a teenage runaway hitchhiking across Nevada with a single backpack.",
    "Make a 30-second clip of an immigrant family's first Sunday drive across their new state.",
    "Produce a 2-minute mini-drama of a young woman walking the Appalachian Trail alone after her father's death.",
    "Build a 45-second short about a road-trip diner stop where two strangers share a single piece of pie.",
    "Create a 30-second piece where a daughter drives her mother to the airport for what may be a one-way trip.",
    "Render a 1-minute mini-drama about a couple's first cross-country move in a heavily packed sedan.",
    "I'd like a 45-second cinematic short of a son completing his late father's lifelong roadtrip to all 50 states.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
