"""x15 intake_img_cr_extend SFT short briefs.

Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video →
       VideoExtend → Compositor.
Trigger: user uploads ONE reference image + cinematic mini-drama + extended
duration. NO music, NO ambience, NO subtitle.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a portrait of a young samurai — make a 2-minute extended cinematic mini-drama imagining his last duel.",
    "Here's a sketch of a young space colonist — build a 3-minute extended cinematic short about her first solo spacewalk.",
    "I'm sending you a watercolor of a young alchemist — produce a 4-minute extended mini-drama about her brewing a forbidden tincture.",
    "Uploading a digital painting of a Roman scribe — make a 3-minute extended cinematic piece about his last day at the senate.",
    "Here's a portrait of a young Mongol scout — render a 2-minute extended short about his ride across the steppe at dawn.",
    "I'm attaching a sketch of a Tang-dynasty poet — build a 3-minute extended cinematic mini-drama by a koi pond.",
    "Uploading this concept art of a young Andean shepherdess — produce a 4-minute extended piece of her crossing a high pass at sunset.",
    "Here's a watercolor of a Heian noblewoman — render a 2-minute extended cinematic short of her writing poetry behind a bamboo screen.",
    "I have a portrait of a young Russian officer — build a 3-minute extended mini-drama of his first mission across the Ural snow.",
    "Uploading a sketch of a young Yoruba drummer — make a 4-minute extended cinematic piece about his apprenticeship in Ibadan.",
    "Here's a digital painting of a young Inuit hunter — produce a 2-minute extended short of him on the pack ice.",
    "I'm attaching this image of a young Hawaiian wayfinder — build a 3-minute extended mini-drama of him reading the night sky.",
    "Uploading a portrait of a young Sami reindeer-herder — make a 4-minute extended cinematic piece across a Lapland winter.",
    "Here's a sketch of a young Maori carver — render a 2-minute extended short of him finishing a wharenui pou.",
    "I'm sending you a watercolor of a young Aboriginal songkeeper — produce a 3-minute extended mini-drama at a remote desert songline.",
    "Uploading a digital portrait of a young Tibetan-monk — build a 2-minute extended cinematic piece of him at high monastery dawn.",
    "Here's a portrait of a young Bhutanese archer — render a 3-minute extended mini-drama at the Thimphu archery festival.",
    "I'm attaching a sketch of a young Nepali porter — make a 4-minute extended piece on a Himalayan summit attempt.",
    "Uploading a watercolor of a young Sri-Lankan ayurvedic practitioner — produce a 2-minute extended short of her at a Colombo apothecary.",
    "Here's a digital painting of a young Tamil priest — build a 3-minute extended mini-drama at a Chennai temple festival.",
    "I have a portrait of a young Bangladeshi rickshaw artist — render a 4-minute extended piece of him painting a panel.",
    "Uploading a sketch of a young Marathi textile-merchant — make a 2-minute extended cinematic short at a Mumbai bazaar.",
    "Here's a watercolor of a young Punjabi bhangra dancer — produce a 3-minute extended mini-drama at a Lahore courtyard.",
    "I'm sending you a portrait of a young Kashmiri pashmina-maker — build a 4-minute extended piece at a Srinagar workshop.",
    "Uploading a digital painting of a young Khmer dancer — make a 2-minute extended cinematic short at an Angkor courtyard.",
    "Here's a sketch of a young Lao silk-weaver — render a 3-minute extended mini-drama on her hand loom.",
    "I'm attaching a portrait of a young Hmong embroiderer — produce a 4-minute extended cinematic piece in a Sapa village.",
    "Uploading a watercolor of a young Burmese gold-leaf maker — build a 2-minute extended short at his Mandalay forge.",
    "Here's a digital portrait of a young Cebuano fisherman — make a 3-minute extended mini-drama at his Visayan-island banca.",
    "I have a sketch of a young Javanese gamelan-player — render a 4-minute extended cinematic piece at a Yogyakarta gathering.",
    "Uploading a portrait of a young Sundanese rice-farmer — produce a 2-minute extended short in a misty paddy at dawn.",
    "Here's a watercolor of a young Balinese mask-carver — build a 3-minute extended mini-drama in his temple-side workshop.",
    "I'm sending you a digital painting of a young Tongan fisherman — render a 4-minute extended cinematic piece at sunset.",
    "Uploading a sketch of a young Samoan grandmother — make a 2-minute extended short of her weaving a fala mat.",
    "Here's a portrait of a young Fijian farmer — produce a 3-minute extended mini-drama harvesting yaqona.",
    "I'm attaching a watercolor of a young Maori warrior — build a 4-minute extended cinematic piece on a marae at dawn.",
    "Uploading a digital portrait of a young Tahitian dancer — render a 2-minute extended short rehearsing ote'a in Papeete.",
    "Here's a sketch of a young Hawaiian taro farmer — make a 3-minute extended mini-drama working a Waipi'o lo'i.",
    "I have a portrait of a young Yupik hunter — produce a 4-minute extended cinematic piece checking ice fishing lines.",
    "Uploading a watercolor of a young Cree elder — build a 2-minute extended short telling stories around a fire.",
    "Here's a digital painting of a young Inuktitut grandmother — render a 3-minute extended mini-drama sewing skin boots.",
    "I'm sending you a sketch of a young Ojibwe rice-harvester — make a 4-minute extended cinematic piece at a wild-rice marsh.",
    "Uploading a portrait of a young Navajo silversmith — produce a 2-minute extended short finishing a turquoise ring.",
    "Here's a watercolor of a young Lakota grandmother — build a 3-minute extended mini-drama braiding her granddaughter's hair.",
    "I'm attaching a digital portrait of a young Nahuatl-speaking grandmother — render a 4-minute extended piece making tlacoyos in Puebla.",
    "Uploading a sketch of a young Mapuche elder — make a 2-minute extended cinematic short teaching weaving in Patagonia.",
    "Here's a portrait of a young Aymara herder — produce a 3-minute extended mini-drama across the altiplano at dawn.",
    "I have a watercolor of a young Guaraní fisherman — build a 4-minute extended cinematic piece casting his net in the Iguazú.",
    "Uploading a digital painting of a young Garifuna drummer — render a 2-minute extended short teaching his nephew rhythms.",
    "Here's a sketch of a young Haitian Kreyòl baker — make a 3-minute extended mini-drama firing a stone oven.",
    # ── more reference-image extended cinematic shorts (50) ──────────────
    "Uploading a portrait of a young Spartan hoplite — make a 3-minute extended cinematic mini-drama at the pass of Thermopylae.",
    "Here's a sketch of a young Egyptian pyramid-builder — build a 4-minute extended cinematic short hauling stone in the Khufu noon.",
    "I'm sending you a watercolor of a young Phoenician ship-captain — produce a 2-minute extended mini-drama navigating a Mediterranean storm.",
    "Uploading a digital painting of a young Carthaginian elephant-driver — make a 4-minute extended cinematic piece crossing an alpine pass.",
    "Here's a portrait of a young Greek philosopher — render a 3-minute extended short pacing the Athenian agora at dusk.",
    "I'm attaching a sketch of a young Etruscan augur — build a 2-minute extended cinematic mini-drama reading the bird flights at sunrise.",
    "Uploading this concept art of a young Celtic druid — produce a 4-minute extended piece at Stonehenge solstice dawn.",
    "Here's a watercolor of a young Viking explorer — render a 3-minute extended cinematic short rowing into a Norwegian fjord at first light.",
    "I have a portrait of a young Saxon ploughman — build a 2-minute extended mini-drama on a Wessex hillside in autumn.",
    "Uploading a sketch of a young Norman knight — make a 4-minute extended cinematic piece on the eve of Hastings.",
    "Here's a digital painting of a young Provence pilgrim — produce a 3-minute extended short walking toward Jerusalem at dawn.",
    "I'm attaching this image of a young Templar scribe — build a 2-minute extended mini-drama copying manuscripts in a Provence cloister.",
    "Uploading a portrait of a young Byzantine empress — make a 4-minute extended cinematic piece at a Hippodrome procession.",
    "Here's a sketch of a young Ottoman janissary — render a 3-minute extended short on a Topkapi parade morning.",
    "I'm sending you a watercolor of a young Mughal court-poet — produce a 2-minute extended mini-drama reciting in Agra moonlight.",
    "Uploading a digital portrait of a young Edo-era rōnin — build a 4-minute extended cinematic piece walking a snowy mountain pass.",
    "Here's a portrait of a young Joseon scholar — render a 3-minute extended mini-drama copying texts by candle at midnight.",
    "I'm attaching a sketch of a young Ming-dynasty admiral — make a 2-minute extended piece on the deck of a Treasure Fleet flagship.",
    "Uploading a watercolor of a young Han-dynasty cartographer — produce a 4-minute extended short surveying a Great Wall section.",
    "Here's a digital painting of a young Renaissance fresco-painter — build a 3-minute extended mini-drama atop scaffolding at a Tuscan chapel.",
    "I have a portrait of a young Florentine apothecary — render a 2-minute extended cinematic piece grinding herbs in his shop.",
    "Uploading a sketch of a young Venetian glassblower — make a 4-minute extended cinematic short at the Murano furnace at midnight.",
    "Here's a watercolor of a young Dutch tulip-trader — produce a 3-minute extended mini-drama at a 1637 Amsterdam auction-floor.",
    "I'm sending you a portrait of a young Spanish conquistador — build a 2-minute extended piece climbing an Andean ridge in fog.",
    "Uploading a digital painting of a young Portuguese navigator — make a 4-minute extended cinematic short rounding the Cape of Good Hope.",
    "Here's a sketch of a young Elizabethan playwright — render a 3-minute extended mini-drama at a Globe Theatre rehearsal.",
    "I'm attaching a portrait of a young French musketeer — produce a 2-minute extended cinematic piece in a Paris tavern brawl.",
    "Uploading a watercolor of a young Russian boyar — build a 4-minute extended cinematic short in a Kremlin council chamber.",
    "Here's a digital portrait of a young Victorian governess — make a 3-minute extended mini-drama in a London townhouse drawing-room.",
    "I have a sketch of a young industrial-era loom-worker — render a 2-minute extended cinematic piece at a Manchester mill at dawn.",
    "Uploading a portrait of a young Crimean-war field nurse — produce a 4-minute extended short tending wounded in a Sevastopol tent.",
    "Here's a watercolor of a young Great Plains homesteader — build a 3-minute extended mini-drama on a Nebraska prairie at storm-season.",
    "I'm sending you a digital painting of a young Oregon Trail pioneer — render a 2-minute extended cinematic piece fording the Platte River.",
    "Uploading a sketch of a young 1920s Harlem jazz pianist — make a 4-minute extended cinematic short at a speakeasy after-hours session.",
    "Here's a portrait of a young 1930s Dust-Bowl photographer — produce a 3-minute extended mini-drama on an Oklahoma county-road shoot.",
    "I'm attaching a watercolor of a young 1940s wartime nurse — build a 2-minute extended cinematic piece in a London ward at blackout-hour.",
    "Uploading a digital portrait of a young 1950s diner waitress — render a 4-minute extended short on a Route 66 graveyard shift.",
    "Here's a sketch of a young 1960s Apollo flight engineer — make a 3-minute extended cinematic piece at Mission Control during a burn.",
    "I have a portrait of a young 1970s newsroom reporter — produce a 2-minute extended mini-drama at a downtown copy-desk deadline.",
    "Uploading a watercolor of a young 1980s Wall Street trader — build a 4-minute extended cinematic short on the NYSE floor at opening bell.",
    "Here's a digital painting of a young cyberpunk hacker — render a 3-minute extended mini-drama on a neon-soaked Tokyo rooftop.",
    "I'm sending you a sketch of a young steampunk airship-navigator — produce a 2-minute extended cinematic piece above a Victorian skyline.",
    "Uploading a portrait of a young lighthouse keeper — make a 4-minute extended cinematic short on a stormy Maine coast at midnight.",
    "Here's a watercolor of a young 1944 submarine mechanic — build a 3-minute extended mini-drama on a Pacific patrol.",
    "I'm attaching a digital portrait of a young Antarctic explorer — render a 2-minute extended cinematic piece at Vostok base in polar dusk.",
    "Uploading a sketch of a young Mars rover technician — make a 4-minute extended cinematic short during a dust-storm landing.",
    "Here's a portrait of a young Dyson-sphere repair crewmember — produce a 3-minute extended mini-drama on a solar collector spacewalk.",
    "I have a watercolor of a young generation-ship botanist — build a 2-minute extended cinematic piece tending a hydroponic garden.",
    "Uploading a digital painting of a young asteroid-belt prospector — render a 4-minute extended cinematic short in a mining suit on Ceres.",
    "Here's a sketch of a young lunar geologist — make a 3-minute extended mini-drama sampling the Mare Imbrium.",
    # ── more reference-image extended cinematic shorts (50) ──────────────
    "Uploading a portrait of a young 17th-c. Polish Hussar — make a 3-minute extended cinematic mini-drama at the Siege of Vienna.",
    "Here's a sketch of a young 18th-c. Don Cossack scout — build a 4-minute extended cinematic short on a Volga-bend reconnaissance.",
    "I'm sending you a watercolor of a young 18th-c. Russian Streltsy musketeer — produce a 2-minute extended mini-drama on a Kremlin-wall watch.",
    "Uploading a digital painting of a young 18th-c. French Royal Musketeer — make a 4-minute extended cinematic piece in a Paris guard-room.",
    "Here's a portrait of a young 18th-c. Prussian fife-player — render a 3-minute extended short on a parade-ground at Potsdam.",
    "I'm attaching a sketch of a young 18th-c. Austrian Hussar — build a 2-minute extended cinematic mini-drama on a snowy patrol.",
    "Uploading this concept art of a young 18th-c. British Redcoat sentry — produce a 4-minute extended piece on a foggy Dover post.",
    "Here's a watercolor of a young 18th-c. American Continental scout — render a 3-minute extended cinematic short at a Hudson-Valley campfire.",
    "I have a portrait of a young 18th-c. Royal-Navy midshipman — build a 2-minute extended mini-drama on a quarterdeck dawn.",
    "Uploading a sketch of a young 18th-c. Dutch East-India trader — make a 4-minute extended cinematic piece in an Amsterdam counting-house.",
    "Here's a digital painting of a young 18th-c. Spanish galleon-pilot — produce a 3-minute extended short charting the Pacific stars.",
    "I'm attaching this image of a young 18th-c. Caribbean pirate-quartermaster — build a 2-minute extended mini-drama on a sloop's deck.",
    "Uploading a portrait of a young 18th-c. Barbary corsair — make a 4-minute extended cinematic piece on the Algerian coast.",
    "Here's a sketch of a young 18th-c. tropical-botanist — render a 3-minute extended short pressing specimens in a jungle camp.",
    "I'm sending you a watercolor of a young 19th-c. Galápagos naturalist — produce a 2-minute extended mini-drama sketching finches.",
    "Uploading a digital portrait of a young 19th-c. Andean naturalist — build a 4-minute extended cinematic piece on a Chimborazo ridge.",
    "Here's a portrait of a young 19th-c. Lyme-Regis fossil hunter — render a 3-minute extended mini-drama at a cliff-fall chalk shelf.",
    "I'm attaching a sketch of a young 19th-c. Difference-Engine engineer — make a 2-minute extended piece in a London brass-shop.",
    "Uploading a watercolor of a young 19th-c. Calotype photographer — produce a 4-minute extended short composing on a wet plate.",
    "Here's a digital painting of a young 19th-c. Daguerreotypist — build a 3-minute extended mini-drama in a copper-plate studio.",
    "I have a portrait of a young 18th-c. Cremona violin-maker — render a 2-minute extended cinematic piece carving a maple top.",
    "Uploading a sketch of a young 18th-c. Leipzig organ-maker — make a 4-minute extended cinematic short voicing a flue-pipe.",
    "Here's a watercolor of a young 18th-c. Salzburg keyboard-prodigy — produce a 3-minute extended mini-drama at a court harpsichord.",
    "I'm sending you a portrait of a young 19th-c. Vienna Romantic-piano student — build a 2-minute extended piece preparing a concerto.",
    "Uploading a digital painting of a young 19th-c. Paris café-pianist — make a 4-minute extended cinematic short under café-Concert lamps.",
    "Here's a sketch of a young 19th-c. St-Petersburg conservatory student — render a 3-minute extended mini-drama at a chamber-music rehearsal.",
    "I'm attaching a portrait of a young 19th-c. Moscow Bolshoi ballet pupil — produce a 2-minute extended cinematic piece at a barre.",
    "Uploading a watercolor of a young 1910s Ballets-Russes dancer — build a 4-minute extended cinematic short backstage at the Châtelet.",
    "Here's a digital portrait of a young 1920s Harlem stride-pianist — make a 3-minute extended mini-drama at a Lenox Avenue rent-party.",
    "I have a sketch of a young 1950s Greenwich-Village folk-singer — render a 2-minute extended cinematic piece at a MacDougal Street café.",
    "Uploading a portrait of a young 1950s Beat-poet — produce a 4-minute extended short at a City-Lights bookshop reading.",
    "Here's a watercolor of a young 1950s Mississippi-Delta blues-guitarist — build a 3-minute extended mini-drama on a Greenville porch.",
    "I'm sending you a digital painting of a young 1950s Memphis Sun-Studios session-player — render a 2-minute extended cinematic piece at the live-room mic.",
    "Uploading a sketch of a young 1960s Motown studio-drummer — make a 4-minute extended cinematic short at a Hitsville-USA tracking date.",
    "Here's a portrait of a young 1970s Stax-Records studio-trumpeter — produce a 3-minute extended mini-drama at the Stax horn booth.",
    "I'm attaching a watercolor of a young 1970s CBGB punk-guitarist — build a 2-minute extended cinematic piece at a Bowery dive show.",
    "Uploading a digital portrait of a young 1980s NYC graffiti-artist — render a 4-minute extended short on a Bronx rail-yard wall.",
    "Here's a sketch of a young 1980s Bronx hip-hop DJ — make a 3-minute extended mini-drama at a park-jam turntable.",
    "I have a portrait of a young 1990s Seattle grunge-bassist — produce a 2-minute extended cinematic piece in a Capitol-Hill basement.",
    "Uploading a watercolor of a young 2000s indie-coffee-shop singer — build a 4-minute extended cinematic short at an open-mic night.",
    "Here's a digital painting of a young 2010s SoundCloud-rap producer — render a 3-minute extended mini-drama at a bedroom workstation.",
    "I'm sending you a sketch of a young 18th-c. Edinburgh anatomy-student — make a 2-minute extended piece at a Surgeons-Hall lecture.",
    "Uploading a portrait of a young 19th-c. Vienna medical-student — produce a 4-minute extended cinematic short at the Allgemeines Krankenhaus.",
    "Here's a watercolor of a young 19th-c. Boston-suffragette — build a 3-minute extended mini-drama at a Beacon-Hill parlor meeting.",
    "I'm attaching a digital portrait of a young 19th-c. London-East-End Salvation-Army recruit — render a 2-minute extended cinematic piece at a soup-kitchen line.",
    "Uploading a sketch of a young 19th-c. Quaker peace-advocate — make a 4-minute extended cinematic short at a Friends meeting.",
    "Here's a portrait of a young 19th-c. Harvard divinity-student — produce a 3-minute extended mini-drama at a Cambridge library carrel.",
    "I have a watercolor of a young 19th-c. Yale law-student — build a 2-minute extended cinematic piece at a New-Haven moot court.",
    "Uploading a digital painting of a young 19th-c. Hudson-River-school landscape painter — render a 4-minute extended short at a Catskill overlook.",
    "Here's a sketch of a young 19th-c. Barbizon-school landscape painter — make a 3-minute extended cinematic mini-drama at a Fontainebleau forest clearing.",
    # ── more reference-image extended cinematic shorts (50) ──────────────
    "Uploading a portrait of a young 18th-c. Russian-Orthodox monastery scribe — make a 3-minute extended cinematic mini-drama at a candlelit scriptorium.",
    "Here's a sketch of a young 18th-c. Athonite calligrapher — build a 4-minute extended cinematic short on Mount Athos at dawn.",
    "I'm sending you a watercolor of a young 18th-c. Ethiopian Aksum monk — produce a 2-minute extended mini-drama in a stone-cut church.",
    "Uploading a digital painting of a young 18th-c. Coptic-monastery painter — make a 4-minute extended cinematic piece at a desert-monastery wall.",
    "Here's a portrait of a young 18th-c. Tibetan thangka-painter — render a 3-minute extended short at a Lhasa cloister.",
    "I'm attaching a sketch of a young 18th-c. Mongolian tsam-mask carver — build a 2-minute extended cinematic mini-drama in a steppe-monastery courtyard.",
    "Uploading this concept art of a young 18th-c. Bhutanese woodblock-printer — produce a 4-minute extended piece at a Paro woodblock atelier.",
    "Here's a watercolor of a young 18th-c. Korean Confucian scholar — render a 3-minute extended cinematic short at a Seonggyungwan study hall.",
    "I have a portrait of a young 18th-c. Edo-period haiku-poet — build a 2-minute extended mini-drama at a moonlit garden.",
    "Uploading a sketch of a young 18th-c. Persian-Safavid court-poet — make a 4-minute extended cinematic piece at an Isfahan mosque-courtyard.",
    "Here's a digital painting of a young 18th-c. Mughal-court miniaturist — produce a 3-minute extended short at an Agra atelier.",
    "I'm attaching this image of a young 18th-c. Rajasthani court-singer — build a 2-minute extended mini-drama at a Mewar palace.",
    "Uploading a portrait of a young 18th-c. Burmese palm-leaf scribe — make a 4-minute extended cinematic piece at a Mandalay monastery.",
    "Here's a sketch of a young 18th-c. Sri-Lankan-temple wall-painter — render a 3-minute extended short at a Polonnaruwa cloister.",
    "I'm sending you a watercolor of a young 18th-c. Khmer-Angkor temple-restorer — produce a 2-minute extended mini-drama at a Banteay-Srei courtyard.",
    "Uploading a digital portrait of a young 18th-c. Lao-Vientiane saung-builder — build a 4-minute extended cinematic piece at a Mekong-side workshop.",
    "Here's a portrait of a young 18th-c. Vietnamese imperial-archery student — render a 3-minute extended mini-drama at a Hue courtyard.",
    "I'm attaching a sketch of a young 18th-c. Filipino baroque-fresco painter — make a 2-minute extended piece at an Ilocos church.",
    "Uploading a watercolor of a young 18th-c. Manila-galleon navigator — produce a 4-minute extended short on a Pacific quarterdeck.",
    "Here's a digital painting of a young 18th-c. Mexico-City-mural restorer — build a 3-minute extended mini-drama at a Coyoacán convent.",
    "I have a portrait of a young 18th-c. Lima-Cathedral icon-painter — render a 2-minute extended cinematic piece at a Cusco scriptorium.",
    "Uploading a sketch of a young 18th-c. Quito-school painter — make a 4-minute extended cinematic short at an Andean atelier.",
    "Here's a watercolor of a young 18th-c. Buenos-Aires-pampas mate-merchant — produce a 3-minute extended mini-drama at a Río-de-la-Plata wharf.",
    "I'm sending you a portrait of a young 18th-c. Santiago-Chile-saltpeter trader — build a 2-minute extended piece at a Mapocho-river warehouse.",
    "Uploading a digital painting of a young 18th-c. Cape-Town-Dutch-East-India clerk — make a 4-minute extended cinematic short at a Castle-of-Good-Hope counting-house.",
    "Here's a sketch of a young 18th-c. Madagascar-Antananarivo trader — render a 3-minute extended mini-drama at a highland-market.",
    "I'm attaching a portrait of a young 18th-c. Zanzibar-clove-merchant — produce a 2-minute extended cinematic piece at a Stone-Town spice-market.",
    "Uploading a watercolor of a young 18th-c. Aden-port-Arab-merchant — build a 4-minute extended cinematic short at a Tawila-tank quay.",
    "Here's a digital portrait of a young 18th-c. Bombay-Parsi-banker — make a 3-minute extended mini-drama at a Banganga tank counting-house.",
    "I have a sketch of a young 18th-c. Kolkata-East-India-Company writer — render a 2-minute extended cinematic piece at a Fort-William desk.",
    "Uploading a portrait of a young 18th-c. Madras-cotton-textile-trader — produce a 4-minute extended short at a Fort-Saint-George counter.",
    "Here's a watercolor of a young 18th-c. Macao-Portuguese-trader — build a 3-minute extended mini-drama at a Senado-Square counting-house.",
    "I'm sending you a digital painting of a young 18th-c. Nagasaki-Dutch-Dejima factor — render a 2-minute extended cinematic piece at a Dejima factor's office.",
    "Uploading a sketch of a young 18th-c. Canton-Cohong merchant — make a 4-minute extended cinematic short at a Pearl-River hong.",
    "Here's a portrait of a young 18th-c. Manila-Spanish galleon-captain — produce a 3-minute extended mini-drama on a Cavite quarterdeck.",
    "I'm attaching a watercolor of a young 18th-c. Acapulco-galleon merchant — build a 2-minute extended cinematic piece at a tropical wharf.",
    "Uploading a digital portrait of a young 18th-c. Veracruz-Spanish-treasure-fleet pilot — render a 4-minute extended short on a Caribbean deck.",
    "Here's a sketch of a young 18th-c. Havana-cigar-roller — make a 3-minute extended cinematic piece at a Vedado factory bench.",
    "I have a portrait of a young 18th-c. New-York-Dutch-Burgher — produce a 2-minute extended mini-drama at a Wall-Street counting-house.",
    "Uploading a watercolor of a young 18th-c. Boston-tea-merchant — build a 4-minute extended cinematic short at a Long-Wharf counter.",
    "Here's a digital painting of a young 18th-c. Philadelphia-Quaker-printer — render a 3-minute extended mini-drama at a Front-Street press.",
    "I'm sending you a sketch of a young 18th-c. Charleston-rice-planter — make a 2-minute extended cinematic piece at a Cooper-River dock.",
    "Uploading a portrait of a young 18th-c. Williamsburg-tobacco-planter — produce a 4-minute extended short at a James-River dock.",
    "Here's a watercolor of a young 18th-c. Saint-Louis-fur-trader — build a 3-minute extended mini-drama at a Mississippi-Missouri confluence post.",
    "I'm attaching a digital portrait of a young 18th-c. New-Orleans-Creole-musician — render a 2-minute extended cinematic piece at a Vieux-Carré balcony.",
    "Uploading a sketch of a young 18th-c. Quebec-City-Habitant — make a 4-minute extended cinematic short at a Place-Royale dawn.",
    "Here's a portrait of a young 18th-c. Halifax-port-master — produce a 3-minute extended mini-drama at a Citadel-Hill harbor.",
    "I have a watercolor of a young 18th-c. Newfoundland-cod-fisher — build a 2-minute extended cinematic piece on a Grand-Banks dory.",
    "Uploading a digital painting of a young 18th-c. Greenland-Inuit-trapper — render a 4-minute extended short on a fjord ice-pack.",
    "Here's a sketch of a young 18th-c. Reykjavik-fisher-elder — make a 3-minute extended cinematic mini-drama at a turf-house morning.",
    # ── more 19th-c. industrial-revolution / colonial figures (50) ──
    "Uploading a portrait of a young 19th-c. Manchester-cotton-mill girl — make a 2-minute extended cinematic mini-drama at an Ancoats loom.",
    "Here's a sketch of a young 19th-c. Lancashire-pit-hauler — build a 3-minute extended cinematic short at a Wigan-coal-pit head.",
    "I have a digital portrait of a young 19th-c. Sheffield-cutler — render a 4-minute extended short at a Kelham-Island workshop.",
    "Uploading a watercolor of a young 19th-c. Birmingham-jewel-smith — produce a 3-minute extended mini-drama at a Hockley-jewel-quarter bench.",
    "Here's a portrait of a young 19th-c. Cornwall-tin-miner — make a 2-minute extended cinematic piece at a Geevor-mine shaft.",
    "I'm sending you a digital painting of a young 19th-c. Newcastle-coalship loader — build a 4-minute extended short at a Tyne-quay coal-staith.",
    "Uploading a sketch of a young 19th-c. Glasgow-shipyard riveter — render a 3-minute extended mini-drama at a Govan-yard hull.",
    "Here's a watercolor of a young 19th-c. Belfast-rope-twister — make a 2-minute extended cinematic piece at a Sailortown rope-walk.",
    "I have a digital portrait of a young 19th-c. Dublin-stout-brewer — produce a 4-minute extended short at a Guinness-yard barrel-house.",
    "I'm attaching a sketch of a young 19th-c. Edinburgh-printer's apprentice — build a 3-minute extended cinematic piece at a Cowgate press.",
    "Uploading a portrait of a young 19th-c. Cardiff-coal-trimmer — render a 2-minute extended mini-drama at a Bute-Dock holding-pen.",
    "Here's a watercolor of a young 19th-c. Swansea-tin-plater — make a 4-minute extended cinematic short at a Hafod tin-mill.",
    "I have a digital painting of a young 19th-c. Stoke-on-Trent potter — produce a 3-minute extended cinematic piece at a Burslem bottle-kiln.",
    "Uploading a sketch of a young 19th-c. Stourbridge-glassmaker — build a 2-minute extended mini-drama at a Wordsley furnace.",
    "Here's a portrait of a young 19th-c. Lyon-silk-weaver — render a 4-minute extended short at a Croix-Rousse loft.",
    "I'm sending you a watercolor of a young 19th-c. Marseille-soap-boiler — make a 3-minute extended cinematic piece at a Quartier-de-Vauban vat.",
    "Uploading a digital portrait of a young 19th-c. Bordeaux-cooper — produce a 2-minute extended short at a Chartrons quay barrel-yard.",
    "Here's a sketch of a young 19th-c. Le-Creusot foundry-mate — build a 4-minute extended cinematic short at a Schneider blast-furnace.",
    "I have a portrait of a young 19th-c. Liège-coal-puddler — render a 3-minute extended mini-drama at a Cockerill works.",
    "I'm attaching a digital portrait of a young 19th-c. Charleroi-glassblower — make a 2-minute extended cinematic piece at a Verrerie-d'Aiseau gob-floor.",
    "Uploading a watercolor of a young 19th-c. Essen-Krupp-foundry caster — produce a 4-minute extended short at a Ruhr blast-yard.",
    "Here's a digital painting of a young 19th-c. Hamburg-cigar-roller — build a 3-minute extended mini-drama at a Speicherstadt bench.",
    "I'm sending you a sketch of a young 19th-c. Bremen-shipping-clerk — make a 2-minute extended cinematic piece at a Schlachte-quay desk.",
    "Uploading a portrait of a young 19th-c. Leipzig-book-binder — render a 4-minute extended short at a Buchhändlerhaus loft.",
    "Here's a watercolor of a young 19th-c. Vienna-piano-tuner — produce a 3-minute extended cinematic piece at a Bösendorfer workshop.",
    "I have a digital portrait of a young 19th-c. Prague-music-engraver — build a 2-minute extended mini-drama at a Žofín print-shop.",
    "I'm attaching a sketch of a young 19th-c. Budapest-violin-luthier — make a 4-minute extended cinematic short at an Andrássy-út workshop.",
    "Uploading a portrait of a young 19th-c. Trieste-coffee-roaster — produce a 3-minute extended cinematic piece at a Riva-3-Novembre warehouse.",
    "Here's a watercolor of a young 19th-c. Genoa-quay-loader — build a 2-minute extended mini-drama at a Porto-Antico stevedore-shed.",
    "I have a digital painting of a young 19th-c. Naples-coral-carver — render a 4-minute extended short at a Torre-del-Greco bench.",
    "Uploading a sketch of a young 19th-c. Sicilian-sulfur-mine carusu — make a 3-minute extended cinematic piece at a Caltanissetta calcarella.",
    "Here's a portrait of a young 19th-c. Sardinian-salt-pan worker — produce a 2-minute extended short at a Cagliari saline.",
    "I'm sending you a digital portrait of a young 19th-c. Catalan-textile worker — build a 4-minute extended cinematic short at a Vapor-Aymerich Terrassa floor.",
    "Uploading a watercolor of a young 19th-c. Asturian-coal-miner — render a 3-minute extended mini-drama at a Mieres pit-head.",
    "Here's a sketch of a young 19th-c. Basque-iron-smelter — make a 2-minute extended cinematic piece at an Altos-Hornos-Vizcaya floor.",
    "I have a digital painting of a young 19th-c. Porto-port-shipper — produce a 4-minute extended short at a Vila-Nova-de-Gaia lodge.",
    "I'm attaching a portrait of a young 19th-c. Lisbon-tile-painter — build a 3-minute extended cinematic piece at a Fábrica-Viúva-Lamego bench.",
    "Uploading a sketch of a young 19th-c. Madeira-vintner — render a 2-minute extended mini-drama at a Funchal lodge.",
    "Here's a watercolor of a young 19th-c. Athens-marble-quarrier — make a 4-minute extended cinematic short at a Pentelicus quarry.",
    "I have a digital portrait of a young 19th-c. Smyrna-fig-merchant — produce a 3-minute extended cinematic piece at an İzmir kordon.",
    "Uploading a portrait of a young 19th-c. Cairo-cotton-baler — build a 2-minute extended mini-drama at a Bulaq quay.",
    "Here's a sketch of a young 19th-c. Bombay-cotton-mill girl — render a 4-minute extended short at a Parel mill.",
    "I'm sending you a watercolor of a young 19th-c. Calcutta-jute-mill loader — make a 3-minute extended cinematic piece at a Hooghly mill-jetty.",
    "Uploading a digital portrait of a young 19th-c. Madras-cotton-spinner — produce a 2-minute extended short at a Buckingham mill.",
    "Here's a portrait of a young 19th-c. Singapore-pineapple-cannery worker — build a 4-minute extended cinematic short at a Bukit-Timah cannery.",
    "I have a sketch of a young 19th-c. Yokohama-silk-reeler — render a 3-minute extended mini-drama at a Tomioka mill.",
    "I'm attaching a digital painting of a young 19th-c. Shanghai-Cotton-Mill girl — make a 2-minute extended cinematic piece at a Yangshupu loom.",
    "Uploading a watercolor of a young 19th-c. Hong-Kong-Tai-Pan clerk — produce a 4-minute extended short at a Praya-Central counting-house.",
    "Here's a sketch of a young 19th-c. Manila-sugar-mill worker — build a 3-minute extended cinematic piece at a Pampanga ingenio.",
    "I have a digital portrait of a young 19th-c. Batavia-spice-warehouse clerk — render a 2-minute extended mini-drama at a Kota Tua quay.",
    # ── more Bronze-Age / Iron-Age / Antiquity figures (50) ──
    "Uploading a portrait of a young Sumerian-Uruk-scribe — make a 2-minute extended cinematic mini-drama at an E-anna-temple courtyard.",
    "Here's a sketch of a young Akkadian-Naram-Sin court page — build a 3-minute extended cinematic short at an Akkad-palace hall.",
    "I have a digital portrait of a young Babylonian-Hammurabi-court scribe — render a 4-minute extended short at an Esagila-temple step.",
    "I'm sending you a watercolor of a young Assyrian-Nineveh archer — produce a 3-minute extended mini-drama at an Ashurbanipal-library wall.",
    "Uploading a digital painting of a young Hittite-Hattusa charioteer — build a 2-minute extended cinematic short at a Lion-Gate ramp.",
    "Here's a portrait of a young Egyptian-Old-Kingdom priest — make a 4-minute extended cinematic mini-drama at a Saqqara-pyramid step.",
    "I have a sketch of a young Egyptian-New-Kingdom scribe — render a 3-minute extended short at a Karnak-hypostyle hall.",
    "I'm attaching a digital portrait of a young Egyptian-Amarna-court page — produce a 2-minute extended cinematic piece at an Akhetaten-palace wall.",
    "Uploading a watercolor of a young Nubian-Kerma archer — build a 4-minute extended cinematic short at a Western-Deffufa platform.",
    "Here's a digital painting of a young Kushite-Meroe-pyramid priestess — make a 3-minute extended mini-drama at a Begrawiya-pyramid step.",
    "I have a portrait of a young Phoenician-Tyre dye-worker — produce a 2-minute extended short at a Murex-purple vat.",
    "I'm sending you a sketch of a young Carthaginian-Hannibal-page — render a 4-minute extended cinematic piece at a Cothon-harbor edge.",
    "Uploading a digital portrait of a young Mycenaean-Linear-B scribe — build a 3-minute extended cinematic short at a Pylos-archive room.",
    "Here's a watercolor of a young Minoan-Knossos bull-leaper — produce a 2-minute extended mini-drama at a Knossos-fresco wall.",
    "I have a digital painting of a young Cycladic-figurine carver — make a 4-minute extended cinematic short at an Akrotiri courtyard.",
    "I'm attaching a portrait of a young Etruscan-Tarquinia haruspex — render a 3-minute extended cinematic piece at a Tarquinia-tomb threshold.",
    "Uploading a sketch of a young Roman-Republic-Forum lictor — produce a 2-minute extended short at a Comitium platform.",
    "Here's a digital portrait of a young Roman-Imperial-Senate clerk — build a 4-minute extended cinematic short at a Curia-Julia hall.",
    "I have a watercolor of a young Roman-Pompeii-fresco apprentice — make a 3-minute extended mini-drama at a Villa-of-Mysteries wall.",
    "I'm sending you a portrait of a young Roman-legionary-Vindolanda — produce a 2-minute extended cinematic piece at a Vindolanda fort wall.",
    "Uploading a digital painting of a young Persian-Achaemenid-Persepolis page — render a 4-minute extended cinematic short at an Apadana-stair.",
    "Here's a sketch of a young Persian-Sasanian-court scribe — build a 3-minute extended cinematic piece at a Taq-Kasra arch.",
    "I have a portrait of a young Parthian-Nisa-archer — make a 2-minute extended cinematic mini-drama at a Nisa fortress wall.",
    "I'm attaching a digital portrait of a young Median-Ecbatana-page — produce a 4-minute extended short at an Ecbatana-citadel terrace.",
    "Uploading a watercolor of a young Scythian-burial-mound rider — render a 3-minute extended mini-drama at a Kurgan-mound rim.",
    "Here's a sketch of a young Sarmatian-warrior — produce a 2-minute extended cinematic piece at a Don-River bend.",
    "I have a digital painting of a young Celtic-Hallstatt-prince page — build a 4-minute extended cinematic short at a Heuneburg-mound rampart.",
    "I'm sending you a portrait of a young Celtic-La-Tène-warrior — make a 3-minute extended mini-drama at an Alesia-hilltop ridge.",
    "Uploading a digital portrait of a young Gallic-Bibracte-druid — produce a 2-minute extended short at a Mont-Beuvray hilltop.",
    "Here's a watercolor of a young British-Iceni-charioteer — render a 4-minute extended cinematic short at a Norfolk-fenland edge.",
    "I have a sketch of a young Pictish-Caithness-stone-carver — build a 3-minute extended cinematic piece at a Cairn-of-Get burial-mound.",
    "I'm attaching a digital painting of a young Brigantian-Stanwick warrior — make a 2-minute extended cinematic mini-drama at a Stanwick-rampart edge.",
    "Uploading a portrait of a young Iberian-Numantia warrior — produce a 4-minute extended short at a Numantia-walls breach.",
    "Here's a sketch of a young Tartessian-Cádiz mariner — render a 3-minute extended mini-drama at a Cádiz-channel quay.",
    "I have a digital portrait of a young Lydian-Sardis goldsmith — produce a 2-minute extended cinematic piece at a Pactolus-stream bend.",
    "I'm sending you a portrait of a young Phrygian-Gordion harpist — make a 4-minute extended cinematic short at a Gordion-tumulus chamber.",
    "Uploading a watercolor of a young Lycian-Xanthos sarcophagus-carver — build a 3-minute extended cinematic piece at a Xanthos-pillar tomb.",
    "Here's a digital painting of a young Cretan-Phaistos-disk maker — render a 2-minute extended mini-drama at a Phaistos-palace courtyard.",
    "I have a portrait of a young Mycenaean-Tiryns mason — produce a 4-minute extended short at a Tiryns-cyclopean-wall ramp.",
    "I'm attaching a digital portrait of a young Greek-Olympic-pankration athlete — build a 3-minute extended cinematic short at an Olympia-palaestra court.",
    "Uploading a sketch of a young Greek-Athens-pottery painter — render a 2-minute extended cinematic piece at a Kerameikos workshop.",
    "Here's a portrait of a young Greek-Spartan-helot — make a 4-minute extended cinematic short at a Eurotas-River bank.",
    "I have a watercolor of a young Greek-Corinthian-trireme rower — produce a 3-minute extended mini-drama at a Lechaeum-quay.",
    "I'm sending you a digital painting of a young Greek-Delphic-pythia attendant — build a 2-minute extended cinematic short at a Delphi-stoa step.",
    "Uploading a portrait of a young Hellenistic-Alexandrian-Library scholar — render a 4-minute extended cinematic piece at a Mouseion garden.",
    "Here's a sketch of a young Ptolemaic-Edfu temple-priest — produce a 3-minute extended cinematic short at an Edfu-pylon gate.",
    "I have a digital portrait of a young Seleucid-Antioch courtier — make a 2-minute extended cinematic mini-drama at an Antioch-Plethron forum.",
    "I'm attaching a portrait of a young Bactrian-Ai-Khanoum scholar — build a 4-minute extended short at an Ai-Khanoum-gymnasium colonnade.",
    "Uploading a watercolor of a young Indo-Greek-Taxila scribe — render a 3-minute extended mini-drama at a Sirkap-stupa ramp.",
    "Here's a sketch of a young Maurya-Pataliputra court page — produce a 2-minute extended cinematic piece at a Pataliputra-palace garden.",
    # ── more 19th-c. Industrial-Revolution figures + period scenes (50) ──
    "Uploading a portrait of a young 1820s Manchester-cotton-mill spinner — make a 2-minute extended cinematic mini-drama at a Manchester-Ancoats mill-floor.",
    "Here's a sketch of a young 1830s Lowell-mill-girl — build a 3-minute extended cinematic short at a Merrimack-River loom-row.",
    "I'm sending you a watercolor of a young 1830s Stockport-cotton-mill apprentice — produce a 4-minute extended cinematic piece at a Stockport-viaduct mill-yard.",
    "Uploading a digital painting of a young 1840s Sheffield-cutlery-grinder — render a 2-minute extended mini-drama at a Sheffield-Kelham-Island grindstone-hall.",
    "Here's a portrait of a young 1840s Leeds-locomotive-fitter — make a 3-minute extended cinematic mini-drama at a Leeds-Middleton railway-shed.",
    "I have a sketch of a young 1840s Glasgow-shipyard riveter — produce a 4-minute extended cinematic short at a Clyde-Govan shipyard-slip.",
    "Uploading a watercolor of a young 1840s Birmingham-brassworks apprentice — build a 2-minute extended mini-drama at a Birmingham-Jewellery-Quarter workshop.",
    "Here's a digital portrait of a young 1850s Stoke-on-Trent pottery-girl — render a 3-minute extended cinematic short at a Stoke-Etruria kiln-room.",
    "I'm sending you a portrait of a young 1850s Lancashire-coal-pit hurrier — produce a 4-minute extended cinematic piece at a Wigan-coalpit shaft-head.",
    "Uploading a sketch of a young 1850s Cornwall-tin-mine bal-maiden — make a 2-minute extended mini-drama at a Geevor-mine ore-floor.",
    "Here's a watercolor of a young 1850s Newcastle-shipbuilder apprentice — build a 3-minute extended cinematic short at a Tyne-Walker shipyard-dry-dock.",
    "I have a digital painting of a young 1860s Bradford-wool-comb operator — render a 4-minute extended cinematic piece at a Bradford-Saltaire combing-shed.",
    "Uploading a portrait of a young 1860s Dundee-jute-mill weaver — produce a 2-minute extended mini-drama at a Verdant-Works weaving-shed.",
    "Here's a sketch of a young 1860s Belfast-Harland-Wolff apprentice — make a 3-minute extended cinematic short at a Queen's-Island slipway.",
    "I'm sending you a watercolor of a young 1860s Liverpool-dockside cooper — render a 4-minute extended cinematic piece at an Albert-Dock barrel-yard.",
    "Uploading a digital portrait of a young 1860s Bristol-locomotive-fitter — produce a 2-minute extended mini-drama at a Swindon-Works railway-shop.",
    "Here's a portrait of a young 1860s London-Whitechapel match-girl — build a 3-minute extended cinematic short at a Bryant-and-May match-floor.",
    "I have a sketch of a young 1870s Crewe-railway-locomotive-shop apprentice — make a 4-minute extended cinematic piece at a Crewe-Works erecting-shed.",
    "Uploading a watercolor of a young 1870s Doncaster-railway-carriage-shop fitter — render a 2-minute extended mini-drama at a Doncaster-Plant carriage-shop.",
    "Here's a digital painting of a young 1870s Pittsburgh-Bessemer-converter blower — produce a 3-minute extended cinematic short at a Homestead-Steel converter-pit.",
    "I'm sending you a portrait of a young 1870s Lowell-textile dye-house worker — make a 4-minute extended cinematic piece at a Lowell-Boott-Mills dye-floor.",
    "Uploading a sketch of a young 1870s Chicago-McCormick-reaper assembler — build a 2-minute extended mini-drama at a McCormick-Reaper-Works assembly-floor.",
    "Here's a watercolor of a young 1870s Brooklyn-shipyard caulker — render a 3-minute extended cinematic short at a Brooklyn-Navy-Yard caulking-bay.",
    "I have a digital portrait of a young 1880s Pullman-railcar joiner — produce a 4-minute extended cinematic piece at a Pullman-Town railcar-shop.",
    "Uploading a portrait of a young 1880s Bethlehem-Steel rolling-mill worker — make a 2-minute extended mini-drama at a Bethlehem rolling-mill-floor.",
    "Here's a sketch of a young 1880s Pittsburgh-glass-factory apprentice — build a 3-minute extended cinematic short at a Pittsburgh-Plate-Glass furnace-room.",
    "I'm sending you a watercolor of a young 1880s Lynn-Massachusetts shoe-stitcher — produce a 4-minute extended cinematic piece at a Lynn-shoe-factory stitching-floor.",
    "Uploading a digital painting of a young 1880s Worcester-Massachusetts wire-mill spooler — render a 2-minute extended mini-drama at a Washburn-Wire spooling-floor.",
    "Here's a portrait of a young 1880s Hartford-Connecticut Colt-armory machinist — make a 3-minute extended cinematic short at a Colt-Armory milling-floor.",
    "I have a sketch of a young 1880s Springfield-Massachusetts Smith-Wesson finisher — build a 4-minute extended cinematic piece at a Smith-Wesson polishing-bench.",
    "Uploading a watercolor of a young 1880s Detroit-stove-foundry molder — produce a 2-minute extended mini-drama at a Detroit-Stove-Works molding-floor.",
    "Here's a digital portrait of a young 1880s Cincinnati-meatpacker apprentice — render a 3-minute extended cinematic short at a Cincinnati-Procter-Gamble cutting-room.",
    "I'm sending you a portrait of a young 1890s Chicago-Union-Stockyards drover — make a 4-minute extended cinematic piece at a Union-Stockyards corral-gate.",
    "Uploading a sketch of a young 1890s Chicago-Pullman-strike striker — build a 2-minute extended mini-drama at a Pullman-Town strike-line.",
    "Here's a watercolor of a young 1890s Homestead-strike steelworker — produce a 3-minute extended cinematic short at a Homestead-Steel barricade.",
    "I have a digital painting of a young 1890s New-York-Triangle-Shirtwaist seamstress — render a 4-minute extended cinematic piece at an Asch-Building cutting-table.",
    "Uploading a portrait of a young 1890s Chicago-meatpacking can-line worker — make a 2-minute extended mini-drama at a Swift-and-Co can-line.",
    "Here's a sketch of a young 1890s Pittsburgh-Carnegie-Steel apprentice — build a 3-minute extended cinematic short at an Edgar-Thomson plant-floor.",
    "I'm sending you a watercolor of a young 1890s Buffalo-grain-elevator hand — produce a 4-minute extended cinematic piece at a Buffalo-grain-elevator scale-house.",
    "Uploading a digital portrait of a young 1890s Cleveland-Standard-Oil refinery hand — render a 2-minute extended mini-drama at a Cleveland-Standard-Oil tank-farm.",
    "Here's a portrait of a young 1890s Bayonne-Standard-Oil refinery worker — make a 3-minute extended cinematic short at a Bayonne-Constable-Hook tank-yard.",
    "I have a sketch of a young 1890s Reading-coal-anthracite breaker-boy — build a 4-minute extended cinematic piece at a Pennsylvania-anthracite breaker-tower.",
    "Uploading a watercolor of a young 1890s Wilkes-Barre-coal-anthracite breaker-girl — produce a 2-minute extended mini-drama at a Glen-Lyon breaker-shed.",
    "Here's a digital painting of a young 1890s Scranton-coal-mine mule-driver — render a 3-minute extended cinematic short at a Scranton-anthracite mule-shaft.",
    "I'm sending you a portrait of a young 1890s Connellsville-coke-yard fireman — produce a 4-minute extended cinematic piece at a Connellsville-coke beehive-oven.",
    "Uploading a sketch of a young 1890s Birmingham-Alabama Tannehill-furnace fireman — make a 2-minute extended mini-drama at a Birmingham-Alabama blast-furnace-yard.",
    "Here's a watercolor of a young 1890s Memphis-cotton-compress-press hand — build a 3-minute extended cinematic short at a Memphis-cotton-compress floor.",
    "I have a digital portrait of a young 1890s New-Orleans-sugar-refinery hand — render a 4-minute extended cinematic piece at a Louisiana-sugar-refinery vat-room.",
    "Uploading a portrait of a young 1890s Galveston-cotton-port stevedore — produce a 2-minute extended mini-drama at a Galveston-Strand cotton-bale-yard.",
    "Here's a sketch of a young 1890s Tampa-cigar-roller apprentice — build a 3-minute extended cinematic short at a Ybor-City cigar-factory floor.",
    # ── more Renaissance / Baroque European-court figures (50) ──
    "Uploading a portrait of a young 15th-c. Florentine-Medici-court page — make a 2-minute extended cinematic mini-drama at the Palazzo-Medici-Riccardi courtyard.",
    "Here's a sketch of a young 15th-c. Urbino-Montefeltro-court librarian — build a 3-minute extended cinematic short at the Palazzo-Ducale-Urbino studiolo.",
    "I'm sending you a watercolor of a young 15th-c. Mantua-Gonzaga-court fresco-apprentice — produce a 4-minute extended cinematic piece at the Camera-degli-Sposi.",
    "Uploading a digital painting of a young 15th-c. Ferrara-Este-court astronomer-trainee — render a 2-minute extended mini-drama at the Castello-Estense rooftop.",
    "Here's a portrait of a young 15th-c. Milan-Sforza-court hawking-page — make a 3-minute extended cinematic short at the Castello-Sforzesco courtyard.",
    "I have a sketch of a young 15th-c. Naples-Aragonese-court harpist — produce a 4-minute extended cinematic piece at the Castel-Nuovo throne-room.",
    "Uploading a watercolor of a young 15th-c. Venetian-Doge's-Palace cabinet-clerk — build a 2-minute extended mini-drama at the Palazzo-Ducale-Venezia balcony.",
    "Here's a digital portrait of a young 15th-c. Burgundian-Dijon-court chronicler — render a 3-minute extended cinematic short at the Palais-des-Ducs courtyard.",
    "I'm sending you a portrait of a young 15th-c. Bruges-Burgundian-court tapestry-weaver — produce a 4-minute extended cinematic piece at the Bruges-Belfry-square loom.",
    "Uploading a sketch of a young 15th-c. Paris-Valois-court goldsmith-apprentice — make a 2-minute extended cinematic mini-drama at the Hôtel-Saint-Pol workshop.",
    "Here's a watercolor of a young 15th-c. Avignon-Papal-court scribe — build a 3-minute extended cinematic short at the Palais-des-Papes scriptorium.",
    "I have a digital painting of a young 15th-c. London-Yorkist-court page — render a 4-minute extended cinematic piece at the Tower-of-London inner-ward.",
    "Uploading a portrait of a young 15th-c. Edinburgh-Stewart-court armorer — produce a 2-minute extended mini-drama at the Edinburgh-Castle-Vaults forge.",
    "Here's a sketch of a young 15th-c. Lisbon-Aviz-court navigator-trainee — make a 3-minute extended cinematic short at the Sagres-promontory chart-room.",
    "I'm sending you a watercolor of a young 15th-c. Toledo-Trastámara-court calligrapher — build a 4-minute extended cinematic piece at the Alcázar-de-Toledo court-yard.",
    "Uploading a digital portrait of a young 15th-c. Granada-Nasrid-court mosaicist — render a 2-minute extended mini-drama at the Alhambra-Lion-Court fountain.",
    "Here's a portrait of a young 16th-c. Vatican-Borgia-court fresco-assistant — produce a 3-minute extended cinematic short at the Borgia-Apartments hall.",
    "I have a sketch of a young 16th-c. Rome-Medici-Pope court-jester — build a 4-minute extended cinematic piece at the Castel-Sant'Angelo terrace.",
    "Uploading a watercolor of a young 16th-c. Florence-Medici-Grand-Ducal court-musician — make a 2-minute extended mini-drama at the Palazzo-Pitti garden.",
    "Here's a digital painting of a young 16th-c. Venetian-Republic court-glassblower — render a 3-minute extended cinematic short at the Murano-fornace.",
    "I'm sending you a portrait of a young 16th-c. Mantua-Gonzaga-court court-dwarf — produce a 4-minute extended cinematic piece at the Palazzo-Te grotto.",
    "Uploading a sketch of a young 16th-c. Madrid-Hapsburg-court court-painter-apprentice — make a 2-minute extended mini-drama at the Alcázar-Madrid Hall-of-Mirrors.",
    "Here's a watercolor of a young 16th-c. El-Escorial-Hapsburg-court chant-singer — build a 3-minute extended cinematic short at the El-Escorial Basilica-cloister.",
    "I have a digital portrait of a young 16th-c. Lisbon-Manueline-court navigator's son — render a 4-minute extended cinematic piece at the Belém-Tower-quay.",
    "Uploading a portrait of a young 16th-c. London-Tudor-court page — produce a 2-minute extended mini-drama at the Hampton-Court-Palace Great-Hall.",
    "Here's a sketch of a young 16th-c. Edinburgh-Stewart-court masquer — make a 3-minute extended cinematic short at the Holyrood-Palace gallery.",
    "I'm sending you a watercolor of a young 16th-c. Stockholm-Vasa-court court-jester — build a 4-minute extended cinematic piece at the Tre-Kronor castle-yard.",
    "Uploading a digital portrait of a young 16th-c. Copenhagen-Oldenborg-court astronomer — render a 2-minute extended mini-drama at the Uraniborg-island observatory.",
    "Here's a portrait of a young 16th-c. Krakow-Jagiellonian-court secretary — produce a 3-minute extended cinematic short at the Wawel-Castle Royal-Apartments.",
    "I have a sketch of a young 16th-c. Vienna-Habsburg-court fencing-master — build a 4-minute extended cinematic piece at the Hofburg-Riding-School.",
    "Uploading a watercolor of a young 16th-c. Prague-Habsburg-court alchemist's apprentice — make a 2-minute extended mini-drama at the Prague-Castle Golden-Lane.",
    "Here's a digital painting of a young 16th-c. Innsbruck-Habsburg-court armorer-apprentice — render a 3-minute extended cinematic short at the Innsbruck-Hofkirche court-yard.",
    "I'm sending you a portrait of a young 16th-c. Munich-Wittelsbach-court court-musician — produce a 4-minute extended cinematic piece at the Munich-Residenz Antiquarium.",
    "Uploading a sketch of a young 16th-c. Heidelberg-Palatinate-court emblem-engraver — make a 2-minute extended mini-drama at the Heidelberg-Castle Hortus-Palatinus.",
    "Here's a watercolor of a young 16th-c. Wittenberg-Saxon-court chant-boy — build a 3-minute extended cinematic short at the Schlosskirche bell-tower.",
    "I have a digital portrait of a young 16th-c. Constantinople-Ottoman-court page-Janissary — render a 4-minute extended cinematic piece at the Topkapi-Palace Imperial-Gate.",
    "Uploading a portrait of a young 16th-c. Isfahan-Safavid-court tile-painter — produce a 2-minute extended mini-drama at the Naqsh-e-Jahan-Square Imperial-Mosque.",
    "Here's a sketch of a young 17th-c. Versailles-Bourbon-court court-fencer — make a 3-minute extended cinematic short at the Versailles-Hall-of-Mirrors.",
    "I'm sending you a watercolor of a young 17th-c. Versailles-Bourbon-court court-perfumer — build a 4-minute extended cinematic piece at the Versailles-Trianon orangerie.",
    "Uploading a digital portrait of a young 17th-c. London-Stuart-court court-painter-apprentice — render a 2-minute extended mini-drama at the Whitehall-Palace Banqueting-House.",
    "Here's a portrait of a young 17th-c. Madrid-Hapsburg-court Velázquez-apprentice — produce a 3-minute extended cinematic short at the Alcázar-Madrid Hall-of-Realms.",
    "I have a sketch of a young 17th-c. Vienna-Habsburg-court Imperial-court-organist — build a 4-minute extended cinematic piece at the Hofburg-Imperial-Chapel.",
    "Uploading a watercolor of a young 17th-c. Stockholm-Vasa-court Queen-Christina's librarian — make a 2-minute extended mini-drama at the Tre-Kronor library-room.",
    "Here's a digital painting of a young 17th-c. Copenhagen-Oldenborg-court Christian-IV-court-jester — render a 3-minute extended cinematic short at the Rosenborg-Castle gallery.",
    "I'm sending you a portrait of a young 17th-c. The-Hague-Orange-court court-cartographer — produce a 4-minute extended cinematic piece at the Binnenhof Stadtholder's-quarters.",
    "Uploading a sketch of a young 17th-c. Brussels-Hapsburg-court Rubens-apprentice — make a 2-minute extended mini-drama at the Coudenberg-Palace stair.",
    "Here's a watercolor of a young 17th-c. Florence-Medici-Grand-Ducal court-Galileo's-assistant — build a 3-minute extended cinematic short at the Boboli-Gardens telescope-platform.",
    "I have a digital portrait of a young 17th-c. Rome-Borghese-court Bernini-apprentice — render a 4-minute extended cinematic piece at the Piazza-Navona fountain-base.",
    "Uploading a portrait of a young 17th-c. Vatican-Barberini-court Caravaggio-school painter — produce a 2-minute extended mini-drama at the Palazzo-Barberini stair.",
    "Here's a sketch of a young 17th-c. Naples-Spanish-Viceroy-court court-singer — build a 3-minute extended cinematic short at the Palazzo-Reale-Naples court.",
    # ── more 18th-c. Enlightenment / Revolutionary-era figures (50) ──
    "Uploading a portrait of a young 18th-c. Paris-Encyclopédistes salon-attendant — make a 2-minute extended cinematic mini-drama at the Madame-Geoffrin's-salon Rue-Saint-Honoré.",
    "Here's a sketch of a young 18th-c. Voltaire-Cirey-château secretary — build a 3-minute extended cinematic short at the Château-de-Cirey-Émilie-du-Châtelet study.",
    "I'm sending you a watercolor of a young 18th-c. Edinburgh-David-Hume-Royal-Mile pupil — produce a 4-minute extended cinematic piece at the James's-Court-Royal-Mile flat.",
    "Uploading a digital painting of a young 18th-c. Edinburgh-Adam-Smith-Saltmarket pupil — render a 2-minute extended mini-drama at the Glasgow-University-quad.",
    "Here's a portrait of a young 18th-c. Königsberg-Kant-pupil — make a 3-minute extended cinematic short at the Königsberg-Castle-Garden walk.",
    "I have a sketch of a young 18th-c. Geneva-Rousseau-pupil — produce a 4-minute extended cinematic piece at the Geneva-Lake-Léman-shore promenade.",
    "Uploading a watercolor of a young 18th-c. Paris-Diderot-Encyclopédie-shop apprentice — build a 2-minute extended cinematic mini-drama at the Rue-Taranne shop-floor.",
    "Here's a digital portrait of a young 18th-c. Paris-Café-Procope philosophe-attendant — render a 3-minute extended cinematic short at the Café-Procope marble-table.",
    "I'm sending you a portrait of a young 18th-c. Versailles-Louis-XV-court page — produce a 4-minute extended cinematic piece at the Versailles-Hall-of-Mirrors.",
    "Uploading a sketch of a young 18th-c. Versailles-Marie-Antoinette-Petit-Trianon dairymaid — make a 2-minute extended cinematic mini-drama at the Petit-Trianon-Hameau.",
    "Here's a watercolor of a young 18th-c. Paris-Bastille-prison turnkey-apprentice — build a 3-minute extended cinematic short at the Bastille-courtyard.",
    "I have a digital painting of a young 18th-c. Paris-Tuileries-Garden gardener — render a 4-minute extended cinematic piece at the Tuileries-Carrousel-axis.",
    "Uploading a portrait of a young 18th-c. Paris-Place-de-la-Révolution news-crier — produce a 2-minute extended cinematic mini-drama at the Place-de-la-Concorde scaffold.",
    "Here's a sketch of a young 18th-c. Paris-Convention-Tuileries scribe — make a 3-minute extended cinematic short at the Salle-du-Manège-Tuileries.",
    "I'm sending you a watercolor of a young 18th-c. Paris-Jacobin-Club page — build a 4-minute extended cinematic piece at the Couvent-des-Jacobins-Saint-Honoré.",
    "Uploading a digital portrait of a young 18th-c. Paris-Robespierre-Duplay-house servant — render a 2-minute extended mini-drama at the Maison-Duplay-Saint-Honoré.",
    "Here's a portrait of a young 18th-c. London-Royal-Society-clerk — produce a 3-minute extended cinematic short at the Crane-Court-Royal-Society.",
    "I have a sketch of a young 18th-c. London-Newton-Mint-master apprentice — build a 4-minute extended cinematic piece at the Tower-of-London-Mint.",
    "Uploading a watercolor of a young 18th-c. London-Coffeehouse-Lloyd's-Tower clerk — make a 2-minute extended mini-drama at the Lloyd's-Coffee-House-Tower-Street.",
    "Here's a digital painting of a young 18th-c. London-British-Museum-Montagu-House attendant — render a 3-minute extended cinematic short at the Montagu-House-Russell-Square.",
    "I'm sending you a portrait of a young 18th-c. London-Royal-Academy-Sir-Joshua-Reynolds-pupil — produce a 4-minute extended cinematic piece at the Somerset-House-Strand.",
    "Uploading a sketch of a young 18th-c. London-Royal-Court-St-James's pageboy — make a 2-minute extended cinematic mini-drama at the St-James's-Palace courtyard.",
    "Here's a watercolor of a young 18th-c. Bath-Pump-Room footman — build a 3-minute extended cinematic short at the Bath-Royal-Crescent-Park.",
    "I have a digital portrait of a young 18th-c. Edinburgh-New-Town-Charlotte-Square footman — render a 4-minute extended cinematic piece at the Charlotte-Square-stair.",
    "Uploading a portrait of a young 18th-c. Boston-Tea-Party Sons-of-Liberty apprentice — produce a 2-minute extended mini-drama at the Boston-Long-Wharf.",
    "Here's a sketch of a young 18th-c. Philadelphia-Independence-Hall page — make a 3-minute extended cinematic short at the Pennsylvania-State-House-Liberty-Bell.",
    "I'm sending you a watercolor of a young 18th-c. Philadelphia-Franklin-Print-Shop apprentice — build a 4-minute extended cinematic piece at the High-Street-Print-Shop.",
    "Uploading a digital portrait of a young 18th-c. Mount-Vernon-Washington-estate stablehand — render a 2-minute extended cinematic mini-drama at the Mount-Vernon-bowling-green.",
    "Here's a portrait of a young 18th-c. Monticello-Jefferson-estate gardener — produce a 3-minute extended cinematic short at the Monticello-Vegetable-Garden.",
    "I have a sketch of a young 18th-c. New-York-Federal-Hall-Wall-Street page — build a 4-minute extended cinematic piece at the Federal-Hall-Wall-Street steps.",
    "Uploading a watercolor of a young 18th-c. Charleston-Sullivan's-Island-fort cadet — make a 2-minute extended mini-drama at the Sullivan's-Island-Fort-Moultrie.",
    "Here's a digital painting of a young 18th-c. Williamsburg-Capitol-Hall page — render a 3-minute extended cinematic short at the Williamsburg-Governor's-Palace-Garden.",
    "I'm sending you a portrait of a young 18th-c. Quebec-Citadel cadet — produce a 4-minute extended cinematic piece at the Quebec-Plains-of-Abraham.",
    "Uploading a sketch of a young 18th-c. Halifax-Citadel-fort drummer — make a 2-minute extended cinematic mini-drama at the Halifax-Citadel-Hill ramparts.",
    "Here's a watercolor of a young 18th-c. Saint-Domingue-Cap-Français Toussaint-Louverture-supporter — build a 3-minute extended cinematic short at the Cap-Français harbor-square.",
    "I have a digital portrait of a young 18th-c. Saint-Domingue-Bois-Caïman vodou-novice — render a 4-minute extended cinematic piece at the Bois-Caïman-clearing.",
    "Uploading a portrait of a young 18th-c. Mexico-City-Real-Audiencia-court page — produce a 2-minute extended cinematic mini-drama at the Plaza-Mayor-Mexico.",
    "Here's a sketch of a young 18th-c. Lima-Real-Audiencia-court page — make a 3-minute extended cinematic short at the Plaza-Mayor-Lima.",
    "I'm sending you a watercolor of a young 18th-c. Cuzco-Túpac-Amaru-II-rebellion supporter — build a 4-minute extended cinematic piece at the Cuzco-Plaza-de-Armas.",
    "Uploading a digital portrait of a young 18th-c. Buenos-Aires-Cabildo-Viceroyalty page — render a 2-minute extended cinematic mini-drama at the Cabildo-Plaza-de-Mayo.",
    "Here's a portrait of a young 18th-c. Saint-Petersburg-Catherine-the-Great-court page — produce a 3-minute extended cinematic short at the Winter-Palace-Throne-Room.",
    "I have a sketch of a young 18th-c. Tsarskoye-Selo-Catherine-Palace pageboy — build a 4-minute extended cinematic piece at the Tsarskoye-Selo-Amber-Room.",
    "Uploading a watercolor of a young 18th-c. Vienna-Maria-Theresa-Schönbrunn page — make a 2-minute extended cinematic mini-drama at the Schönbrunn-Palace-Gloriette.",
    "Here's a digital painting of a young 18th-c. Berlin-Sanssouci-Frederick-the-Great pageboy — render a 3-minute extended cinematic short at the Sanssouci-Vine-Terrace.",
    "I'm sending you a portrait of a young 18th-c. Madrid-Bourbon-Palace pageboy — produce a 4-minute extended cinematic piece at the Palacio-Real-Madrid throne-room.",
    "Uploading a sketch of a young 18th-c. Lisbon-Pombaline-rebuild apprentice-mason — make a 2-minute extended cinematic mini-drama at the Lisbon-Praça-do-Comércio.",
    "Here's a watercolor of a young 18th-c. Edinburgh-James-Watt-Glasgow apprentice — build a 3-minute extended cinematic short at the Glasgow-Trongate workshop.",
    "I have a digital portrait of a young 18th-c. Manchester-Arkwright-Cromford-Mill apprentice — render a 4-minute extended cinematic piece at the Cromford-Mill-floor.",
    "Uploading a portrait of a young 18th-c. Birmingham-Lunar-Society-Soho-Manufactory apprentice — produce a 2-minute extended cinematic mini-drama at the Soho-Manufactory-yard.",
    "Here's a sketch of a young 18th-c. Coalbrookdale-Iron-Bridge ironworker — make a 3-minute extended cinematic short at the Coalbrookdale-blast-furnace-yard.",
    # ── more 19th-c. Romantic poets + Victorian writers (50) ──
    "I'm sending you a portrait of a young 19th-c. London-Lord-Byron-Albany-set page — produce a 4-minute extended cinematic piece at the Holland-House-Kensington library.",
    "Uploading a watercolor of a young 19th-c. London-Percy-Bysshe-Shelley boyhood scribe — make a 2-minute extended cinematic mini-drama at the Eton-College-courtyard.",
    "Here's a digital painting of a young 19th-c. Hampstead-John-Keats-house garden-boy — render a 3-minute extended cinematic short at the Wentworth-Place-garden.",
    "I have a sketch of a young 19th-c. Cumbria-Wordsworth-Dove-Cottage gardener-boy — produce a 4-minute extended cinematic piece at the Dove-Cottage-orchard.",
    "Uploading a portrait of a young 19th-c. Cumbria-Coleridge-Greta-Hall page — build a 2-minute extended cinematic mini-drama at the Greta-Hall-window.",
    "Here's a watercolor of a young 19th-c. Yorkshire-Brontë-Haworth-Parsonage stable-boy — render a 3-minute extended cinematic short at the Haworth-Moors.",
    "I'm sending you a digital portrait of a young 19th-c. London-Dickens-Doughty-Street scrivener-apprentice — produce a 4-minute extended cinematic piece at the Doughty-Street-study.",
    "Uploading a sketch of a young 19th-c. Portsmouth-Dickens-Mile-End cabin-boy — make a 2-minute extended cinematic mini-drama at the Portsmouth-Naval-Dockyard.",
    "Here's a portrait of a young 19th-c. London-Thackeray-Kensington-Square page — render a 3-minute extended cinematic short at the Kensington-Palace-Gardens.",
    "I have a watercolor of a young 19th-c. Edinburgh-Walter-Scott-Abbotsford gillie — produce a 4-minute extended cinematic piece at the Abbotsford-Hall-armoury.",
    "Uploading a digital painting of a young 19th-c. Hampshire-Jane-Austen-Chawton-Cottage gardener-boy — make a 2-minute extended cinematic mini-drama at the Chawton-Cottage-parlour.",
    "Here's a sketch of a young 19th-c. Bath-Beau-Brummell-Pump-Room footboy — render a 3-minute extended cinematic short at the Bath-Royal-Crescent.",
    "I'm sending you a portrait of a young 19th-c. London-Shelley-Mary-Wollstonecraft-Godwin-Skinner-Street scribe-boy — produce a 4-minute extended cinematic piece at the Skinner-Street-bookshop.",
    "Uploading a watercolor of a young 19th-c. Geneva-Villa-Diodati-Byron-Shelley-summer house-boy — build a 2-minute extended cinematic mini-drama at the Villa-Diodati-terrace.",
    "Here's a digital portrait of a young 19th-c. Pisa-Shelley-Casa-Magni boatman's son — render a 3-minute extended cinematic short at the Casa-Magni-veranda.",
    "I have a sketch of a young 19th-c. Rome-Keats-Piazza-di-Spagna apothecary-boy — produce a 4-minute extended cinematic piece at the Keats-Shelley-Memorial-stairs.",
    "Uploading a portrait of a young 19th-c. Rome-Shelley-Cimitero-Acattolico stonecutter-apprentice — make a 2-minute extended cinematic mini-drama at the Cimitero-Acattolico.",
    "Here's a watercolor of a young 19th-c. Florence-Brownings-Casa-Guidi page — render a 3-minute extended cinematic short at the Casa-Guidi-balcony.",
    "I'm sending you a digital painting of a young 19th-c. Florence-Robert-Browning-Piazza-San-Felice scribe-boy — produce a 4-minute extended cinematic piece at the Piazza-San-Felice.",
    "Uploading a sketch of a young 19th-c. London-Tennyson-Aldworth-house gardener-boy — make a 2-minute extended cinematic mini-drama at the Aldworth-House-park.",
    "Here's a portrait of a young 19th-c. Isle-of-Wight-Tennyson-Farringford page — render a 3-minute extended cinematic short at the Farringford-Down.",
    "I have a watercolor of a young 19th-c. Concord-Emerson-Old-Manse gardener-boy — produce a 4-minute extended cinematic piece at the Old-Manse-orchard.",
    "Uploading a digital portrait of a young 19th-c. Concord-Hawthorne-Wayside scribe-boy — make a 2-minute extended cinematic mini-drama at the Wayside-veranda.",
    "Here's a sketch of a young 19th-c. Concord-Thoreau-Walden-Pond cabin-boy — render a 3-minute extended cinematic short at the Walden-Pond-shore.",
    "I'm sending you a portrait of a young 19th-c. Salem-Hawthorne-Custom-House clerk-apprentice — produce a 4-minute extended cinematic piece at the Salem-Custom-House-warehouse.",
    "Uploading a watercolor of a young 19th-c. Amherst-Emily-Dickinson-Homestead gardener-boy — build a 2-minute extended cinematic mini-drama at the Dickinson-Homestead-conservatory.",
    "Here's a digital painting of a young 19th-c. Cambridge-Longfellow-Craigie-House page — render a 3-minute extended cinematic short at the Craigie-House-study.",
    "I have a sketch of a young 19th-c. New-York-Poe-Fordham-Cottage scribe-boy — produce a 4-minute extended cinematic piece at the Poe-Fordham-Cottage-yard.",
    "Uploading a portrait of a young 19th-c. Baltimore-Poe-Amity-Street boy — make a 2-minute extended cinematic mini-drama at the Poe-House-attic.",
    "Here's a watercolor of a young 19th-c. Richmond-Poe-Allan-house clerk-boy — render a 3-minute extended cinematic short at the Moldavia-Mansion-parlour.",
    "I'm sending you a digital portrait of a young 19th-c. Brooklyn-Walt-Whitman-Eagle-newspaper printer's-devil — produce a 4-minute extended cinematic piece at the Brooklyn-Eagle-press-room.",
    "Uploading a sketch of a young 19th-c. Camden-Whitman-Mickle-Street boy — make a 2-minute extended cinematic mini-drama at the Whitman-house-porch.",
    "Here's a portrait of a young 19th-c. London-Robert-Browning-Camberwell scribe-boy — render a 3-minute extended cinematic short at the Camberwell-Grove-garden.",
    "I have a watercolor of a young 19th-c. London-Elizabeth-Barrett-50-Wimpole-Street page — produce a 4-minute extended cinematic piece at the Wimpole-Street-drawing-room.",
    "Uploading a digital painting of a young 19th-c. London-William-Blake-Lambeth engraver's-apprentice — make a 2-minute extended cinematic mini-drama at the Lambeth-print-shop.",
    "Here's a sketch of a young 19th-c. London-Charles-Lamb-Inner-Temple page — render a 3-minute extended cinematic short at the Inner-Temple-Garden.",
    "I'm sending you a portrait of a young 19th-c. London-Mary-Lamb-Russell-Street scribe-boy — produce a 4-minute extended cinematic piece at the Russell-Street-bookshop.",
    "Uploading a watercolor of a young 19th-c. London-De-Quincey-Soho opium-shop boy — build a 2-minute extended cinematic mini-drama at the Soho-Greek-Street-attic.",
    "Here's a digital portrait of a young 19th-c. Edinburgh-James-Hogg-Ettrick-Shepherd shepherd-boy — render a 3-minute extended cinematic short at the Ettrick-Shepherd's-cottage.",
    "I have a sketch of a young 19th-c. Edinburgh-Robert-Burns-Mauchline-farm farmhand — produce a 4-minute extended cinematic piece at the Mauchline-farm-byre.",
    "Uploading a portrait of a young 19th-c. Edinburgh-De-Quincey-Cumberland-Street boy — make a 2-minute extended cinematic mini-drama at the Princes-Street-pavement.",
    "Here's a watercolor of a young 19th-c. Lyme-Regis-Mary-Anning fossil-cleaning-boy — render a 3-minute extended cinematic short at the Lyme-Regis-cliff-foreshore.",
    "I'm sending you a digital painting of a young 19th-c. Down-House-Charles-Darwin gardener's-boy — produce a 4-minute extended cinematic piece at the Down-House-sandwalk.",
    "Uploading a sketch of a young 19th-c. London-Royal-Society-Faraday-laboratory bottle-boy — make a 2-minute extended cinematic mini-drama at the Royal-Institution-laboratory.",
    "Here's a portrait of a young 19th-c. Cambridge-Maxwell-Trinity-College scribe-boy — render a 3-minute extended cinematic short at the Trinity-College-Wren-Library.",
    "I have a watercolor of a young 19th-c. Oxford-Newman-Oriel-College page — produce a 4-minute extended cinematic piece at the Oriel-College-quad.",
    "Uploading a digital portrait of a young 19th-c. Oxford-Lewis-Carroll-Christ-Church boy — make a 2-minute extended cinematic mini-drama at the Christ-Church-Meadow.",
    "Here's a sketch of a young 19th-c. London-Thomas-Hardy-Adelphi-Terrace boy — render a 3-minute extended cinematic short at the Adelphi-Terrace-balcony.",
    "I'm sending you a portrait of a young 19th-c. Dorchester-Thomas-Hardy-Max-Gate scribe-boy — produce a 4-minute extended cinematic piece at the Max-Gate-study.",
    "Uploading a watercolor of a young 19th-c. London-Wilkie-Collins-Tavistock-Square page — build a 2-minute extended cinematic mini-drama at the Tavistock-Square-drawing-room.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
