"""x15 cr_subtitle SFT short briefs.

Chain: Story→Screenplay→KeyFrame→Video→Transcription→Compositor.
Trigger: monolingual subtitle/caption overlay (NO translation, NO bilingual).
NO music, NO ambience, NO upload.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Make a 1-minute mini-drama about a courtroom defense lawyer giving closing arguments, with English captions overlaid.",
    "I want a 45-second cinematic short of a paramedic explaining triage to an intern, with English subtitles.",
    "Create a 30-second piece where a high-school principal addresses students at an assembly, with English captions.",
    "Produce a 2-minute mini-drama about a pediatrician explaining a diagnosis to anxious parents, with English subtitles.",
    "Build a 45-second short of a docent leading a museum tour through ancient Egyptian galleries, with English subtitles.",
    "Render a 30-second cinematic clip of a TED-style speaker delivering a 5-minute talk, with English captions.",
    "Cook up a 1-minute mini-drama where a mountain rescue team radios coordinates back to base, with English subtitles.",
    "Generate a 30-second short of a startup founder pitching to investors in a Demo Day, with English captions overlaid.",
    "I'd like a 45-second cinematic piece of a college lecturer explaining quantum mechanics, with English subtitles.",
    "Make a 30-second clip of a chef walking diners through a tasting menu at a fine-dining table, with English captions.",
    "Produce a 2-minute mini-drama about a senior UN translator hosting a press briefing, with English subtitles.",
    "Build a 45-second short of a wedding officiant guiding the couple through their vows, with English subtitles.",
    "Create a 30-second piece where a science journalist interviews a NASA engineer at a launch pad, with English captions.",
    "Render a 1-minute mini-drama of a small-town mayor announcing a new park at a town hall, with English subtitles.",
    "I want a 30-second short of a young coach giving a halftime speech in a basketball locker room, with English captions.",
    "Cook up a 45-second piece of a documentary host explaining tide-pool ecology on a Maine shore, with English subtitles.",
    "Generate a 1-minute mini-drama of a retired senator giving farewell remarks at a Senate session, with English subtitles.",
    "Make me a 30-second clip about a podcast host monologuing on civic engagement, with English captions overlaid.",
    "Produce a 45-second short where a young reporter narrates a field segment from a hurricane, with English subtitles.",
    "Build a 30-second piece of a pastor delivering a Sunday homily in a small chapel, with English captions.",
    "I'd like a 2-minute mini-drama of a public defender preparing closing arguments alone in chambers, with English subtitles.",
    "Render a 45-second clip of a curator walking visitors through a Picasso retrospective, with English captions.",
    "Create a 30-second piece where a librarian tells children a story at a children's-room reading hour, with English subtitles.",
    "Make a 1-minute mini-drama about a NICU nurse explaining a procedure to first-time parents, with English captions.",
    "Cook up a 45-second short of a vintner walking guests through her tasting room, with English subtitles overlaid.",
    "Generate a 30-second clip of a graduate student defending her thesis to a panel, with English captions.",
    "I want a 1-minute mini-drama of a wedding photographer briefing the bridal party, with English subtitles.",
    "Make me a 30-second short about a tour operator briefing climbers at base camp, with English captions.",
    "Produce a 45-second piece where a dentist explains a procedure to a nervous patient, with English subtitles.",
    "Build a 30-second cinematic clip of a high-school physics teacher explaining gravity, with English captions overlaid.",
    "Create a 1-minute mini-drama of a conservation biologist briefing volunteers at a wetland, with English subtitles.",
    "Render a 30-second clip of a bookstore owner introducing an author at a reading, with English captions.",
    "I'd like a 45-second short of a school nurse explaining safety protocols at orientation, with English subtitles.",
    "Cook up a 1-minute mini-drama of a small-town sheriff explaining a missing-person case at a presser, with English captions.",
    "Make a 30-second piece where a charity director thanks donors at a small fundraiser, with English subtitles.",
    "Generate a 45-second cinematic clip of a city engineer explaining a bridge restoration plan, with English captions.",
    "Produce a 30-second short of a yoga instructor leading a sun-salutation flow, with English subtitles.",
    "Build a 1-minute mini-drama about a 911 dispatcher walking a caller through CPR, with English captions overlaid.",
    "Create a 45-second piece where a beekeeper teaches a workshop on honey extraction, with English subtitles.",
    "I want a 30-second cinematic short of a midwife explaining birth options to expectant parents, with English captions.",
    "Render a 1-minute mini-drama of a museum curator narrating a private viewing of a rare artifact, with English subtitles.",
    "Make me a 30-second short about a funeral director officiating a quiet graveside service, with English captions.",
    "Cook up a 45-second piece of a guidance counselor coaching a senior on college applications, with English subtitles.",
    "Produce a 30-second clip of a reading specialist working one-on-one with a struggling student, with English captions.",
    "Build a 1-minute mini-drama of a high-school debate captain delivering closing remarks at finals, with English subtitles.",
    "Generate a 45-second cinematic piece of a pediatric speech therapist working with a young child, with English subtitles.",
    "I'd like a 30-second short of a trial attorney delivering an opening statement, with English captions overlaid.",
    "Cook up a 1-minute mini-drama of a wildlife rehabber explaining a release plan to volunteers, with English subtitles.",
    "Make a 30-second piece where a veterinary surgeon walks a pet owner through anesthesia options, with English captions.",
    "Render a 45-second cinematic clip of a hospice chaplain leading a small bedside service, with English subtitles.",
    "Produce a 30-second short of an architect walking clients through a model of their new home, with English captions.",
    "Build a 1-minute mini-drama about a stage director giving final notes to actors before opening night, with English subtitles.",
    "Create a 45-second piece where an executive coach gives feedback to an exec on leadership style, with English captions.",
    "I want a 30-second cinematic short of a UX researcher debriefing a usability study to a team, with English subtitles.",
    "Render a 1-minute mini-drama of a crisis negotiator talking down a person on a ledge, with English captions overlaid.",
    "Make me a 30-second short about a junior journalist running a broadcast standup outside a courthouse, with English subtitles.",
    "Cook up a 45-second piece of a tour guide leading a small group through the Sistine Chapel, with English captions.",
    "Generate a 30-second clip of a 911 trainee taking her first live call, with English subtitles.",
    "Produce a 1-minute mini-drama of a nutritionist coaching a client on meal planning, with English captions.",
    "Build a 45-second cinematic piece about a young pastor leading a quiet midnight Christmas-Eve service, with English subtitles.",
    "I'd like a 30-second short of a college admissions officer giving a campus-tour talk, with English captions.",
    "Cook up a 1-minute mini-drama of a graduate student explaining her physics thesis at a poster session, with English subtitles.",
    "Make a 30-second piece where a sex-ed teacher leads a classroom discussion at a middle school, with English captions.",
    "Generate a 45-second cinematic clip of a young historian giving a walking tour of a Civil War battlefield, with English subtitles.",
    "Produce a 30-second short of a young coding bootcamp instructor leading a beginner workshop, with English captions.",
    "Build a 1-minute mini-drama about a young tax accountant walking a freelancer through her quarterly filing, with English subtitles.",
    "Create a 45-second piece where a small-town veterinarian explains heartworm prevention to a pet family, with English captions.",
    "I want a 30-second cinematic short of a conservation biologist briefing a film crew about gorilla habituation, with English subtitles.",
    "Render a 1-minute mini-drama of a radiologist explaining an MRI scan to a worried family, with English captions overlaid.",
    "Make me a 30-second short about a science museum guide demonstrating a Foucault pendulum, with English subtitles.",
    "Cook up a 45-second piece of a young mediator helping a divorcing couple draft a parenting plan, with English captions.",
    "Generate a 30-second clip of a high-school principal addressing students after a power outage, with English subtitles.",
    "Produce a 1-minute mini-drama of a young environmental lawyer giving closing remarks at a regulatory hearing, with English captions.",
    "Build a 45-second cinematic piece about a young curator giving a private tour of a Vermeer painting, with English subtitles.",
    "I'd like a 30-second short of a young volunteer firefighter giving a community-room safety briefing, with English captions.",
    "Make a 1-minute mini-drama where a young social worker walks a foster family through transition planning, with English subtitles.",
    # ── more cinematic mini-dramas with English captions (50) ─────────────
    "Make me a 1-minute mini-drama of a young hotel concierge walking VIP guests through their first day at a luxury resort, with English captions.",
    "I want a 45-second cinematic short of a young restaurant manager addressing her team before opening night, with English subtitles.",
    "Create a 30-second piece where a young theater director gives final notes to actors before opening night, with English captions.",
    "Produce a 2-minute mini-drama about a young opera director rehearsing a final scene with her lead, with English subtitles.",
    "Build a 45-second short of a young symphony conductor addressing her orchestra before a Carnegie Hall premiere, with English captions.",
    "Render a 30-second cinematic clip of a young ballet master giving final notes to her principals before a gala, with English subtitles.",
    "Cook up a 1-minute mini-drama where a young art-museum docent gives a private tour to a school group, with English captions.",
    "Generate a 45-second short of a young science-museum guide demonstrating a Foucault pendulum, with English subtitles.",
    "I'd like a 30-second cinematic piece of a young planetarium director narrating a star show, with English captions.",
    "Make a 30-second clip of a young zoo educator narrating a giraffe-feeding session, with English subtitles.",
    "Produce a 2-minute mini-drama about a young aquarium director giving a private tour of a new exhibit, with English captions.",
    "Build a 45-second short of a young national-park ranger leading visitors through a redwood grove, with English subtitles.",
    "Create a 30-second piece where a young heritage docent walks visitors through Independence Hall, with English captions.",
    "Render a 1-minute mini-drama of a young historic-site interpreter explaining a Civil-War battlefield, with English subtitles.",
    "I want a 30-second cinematic short of a young Holocaust-museum docent narrating a Holocaust memorial walk, with English captions.",
    "Cook up a 45-second piece of a young Civil-Rights-museum docent narrating a Birmingham-Selma walk, with English subtitles.",
    "Generate a 1-minute mini-drama of a young presidential-library docent walking visitors through a President's day-to-day, with English captions.",
    "Make me a 30-second clip about a young supreme-court tour-guide walking visitors through the Marble Palace, with English subtitles.",
    "Produce a 45-second short where a young Capitol-tour-guide explains the rotunda paintings to visitors, with English captions.",
    "Build a 30-second cinematic clip of a young White-House-tour-guide explaining the East Room to visitors, with English subtitles.",
    "Create a 1-minute mini-drama of a young Vatican-museum docent leading visitors through the Sistine Chapel, with English captions.",
    "Render a 30-second clip of a young British-Museum docent narrating the Rosetta Stone display, with English subtitles.",
    "I'd like a 45-second short of a young Louvre docent walking visitors through Italian-Renaissance hall, with English captions.",
    "Cook up a 1-minute mini-drama of a young Hermitage docent walking visitors through a Russian-icon exhibit, with English subtitles.",
    "Make a 30-second piece where a young Prado docent explains Goya's Black Paintings to visitors, with English captions.",
    "Generate a 45-second cinematic clip of a young Uffizi docent walking visitors through the Botticelli room, with English subtitles.",
    "Produce a 30-second short of a young Rijksmuseum docent walking visitors through the Vermeer room, with English captions.",
    "Build a 1-minute mini-drama about a young MoMA docent walking visitors through the Pollock room, with English subtitles.",
    "Create a 45-second piece where a young Met docent walks visitors through the Egyptian wing, with English captions.",
    "I want a 30-second cinematic short of a young Tate-Modern docent walking visitors through the Rothko room, with English subtitles.",
    "Render a 1-minute mini-drama of a young Guggenheim docent walking visitors through the Kandinsky room, with English captions.",
    "Make me a 30-second short about a young Whitney docent walking visitors through the Hopper room, with English subtitles.",
    "Cook up a 45-second piece of a young Centre-Pompidou docent walking visitors through the Picasso room, with English captions.",
    "Generate a 30-second clip of a young Pinacoteca docent walking visitors through the di Vinci room, with English subtitles.",
    "Produce a 1-minute mini-drama of a young Reina-Sofia docent walking visitors through the Picasso Guernica room, with English captions.",
    "Build a 45-second cinematic piece about a young Tate-Britain docent walking visitors through the Turner room, with English subtitles.",
    "I'd like a 30-second short of a young Royal-Academy docent walking visitors through the Constable room, with English captions.",
    "Cook up a 1-minute mini-drama of a young Smithsonian docent walking visitors through a space-shuttle room, with English subtitles.",
    "Make a 30-second piece where a young Air-and-Space docent walks visitors through the Wright Brothers room, with English captions.",
    "Generate a 45-second cinematic clip of a young Natural-History docent walking visitors through the dinosaur room, with English subtitles.",
    "Produce a 30-second short of a young Field-Museum docent walking visitors through the Sue T. rex room, with English captions.",
    "Build a 1-minute mini-drama about a young AMNH docent walking visitors through the meteorite room, with English subtitles.",
    "Create a 45-second piece where a young Kennedy-Center docent walks visitors through the Concert-Hall, with English captions.",
    "I want a 30-second cinematic short of a young Sydney-Opera-House docent walking visitors through the Concert-Hall, with English subtitles.",
    "Render a 1-minute mini-drama of a young Metropolitan-Opera docent walking visitors through the orchestra pit, with English captions.",
    "Make me a 30-second short about a young La-Scala docent walking visitors through the Toscanini Foyer, with English subtitles.",
    "Cook up a 45-second piece of a young Bolshoi docent walking visitors through the Tchaikovsky Foyer, with English captions.",
    "Generate a 30-second clip of a young Royal-Opera-House docent walking visitors through the Crush Bar, with English subtitles.",
    "Produce a 1-minute mini-drama of a young Vienna-State-Opera docent walking visitors through the Mozart Foyer, with English captions.",
    "Build a 45-second cinematic piece about a young Berlin-Philharmonie docent walking visitors through the chamber-music hall, with English subtitles.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
