"""x15 cr_bilingual SFT short briefs.

Chain: Story→Screenplay→KeyFrame→Video→Transcription→Translation→Compositor
Trigger: brief explicitly names bilingual subtitle pair (e.g.
'with English/Spanish subtitles'). No audio, no upload.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Make a 1-minute mini-drama about a young Mexican-American chef opening her first taqueria, with English and Spanish subtitles.",
    "I want a 45-second cinematic short of a Korean translator interviewing a witness, with Korean and English subtitles.",
    "Create a 30-second piece where two French scientists debate a theorem, with French and English subtitles.",
    "Produce a 2-minute mini-drama about a Japanese grandmother teaching her granddaughter origami, with Japanese and English subtitles.",
    "Build a 45-second short of a Hindi-speaking father reading a bedtime story, with Hindi and English subtitles.",
    "Render a 30-second cinematic clip of a Cuban grandfather playing dominoes with neighbors, with Spanish and English subtitles.",
    "Cook up a 1-minute mini-drama where a German engineer explains a turbine fault to her American counterpart, with German and English subtitles.",
    "Generate a 30-second short of an Italian opera singer rehearsing arias backstage, with Italian and English subtitles.",
    "I'd like a 45-second cinematic piece of a Swahili-speaking schoolteacher leading a Maasai classroom, with Swahili and English subtitles.",
    "Make a 30-second clip of a Vietnamese pho vendor explaining her broth to a tourist, with Vietnamese and English subtitles.",
    "Produce a 2-minute mini-drama about a Greek fisherman teaching his nephew to mend nets, with Greek and English subtitles.",
    "Build a 45-second short of a Brazilian Capoeira master leading a Salvador class, with Portuguese and English subtitles.",
    "Create a 30-second piece where two Egyptian archaeologists discuss a tomb find, with Arabic and English subtitles.",
    "Render a 1-minute mini-drama of an Iranian poet reading at a Tehran bookshop, with Persian and English subtitles.",
    "I want a 30-second short about a Maori grandmother teaching her granddaughter haka, with Maori and English subtitles.",
    "Cook up a 45-second piece of a Russian astronomer explaining the night sky to her son, with Russian and English subtitles.",
    "Generate a 1-minute mini-drama of a Polish baker training a French apprentice in Krakow, with Polish and French subtitles.",
    "Make me a 30-second clip about a Dutch botanist cataloguing tulips, with Dutch and English subtitles.",
    "Produce a 45-second short where a Tagalog-speaking nurse comforts a patient in Manila, with Tagalog and English subtitles.",
    "Build a 30-second piece of a Turkish carpet weaver teaching her apprentice in Cappadocia, with Turkish and English subtitles.",
    "I'd like a 2-minute mini-drama of a Mongolian shepherd negotiating with a Beijing buyer, with Mongolian and Mandarin subtitles.",
    "Render a 45-second clip of a Serbian violinist playing in a Belgrade café, with Serbian and English subtitles.",
    "Create a 30-second piece where a Senegalese father teaches his son to fish in Dakar, with Wolof and French subtitles.",
    "Make a 1-minute mini-drama about a Norwegian fisherman explaining tides to his daughter, with Norwegian and English subtitles.",
    "Cook up a 45-second short of a Catalan grandmother making paella in Barcelona, with Catalan and Spanish subtitles.",
    "Generate a 30-second clip of a Hungarian violinmaker varnishing a violin in Budapest, with Hungarian and English subtitles.",
    "I want a 1-minute mini-drama of a Czech glassblower teaching her daughter, with Czech and English subtitles.",
    "Make me a 30-second short about a Finnish reindeer herder counting his flock, with Finnish and English subtitles.",
    "Produce a 45-second piece where a Romanian shepherdess weaves wool by lamplight, with Romanian and English subtitles.",
    "Build a 30-second cinematic clip of a Mandarin-speaking grandmother teaching her grandchild calligraphy, with Mandarin and English subtitles.",
    "Create a 1-minute mini-drama of a Bulgarian rose-picker working at dawn, with Bulgarian and English subtitles.",
    "Render a 30-second clip of a Slovak shepherdess crossing a Tatra meadow, with Slovak and English subtitles.",
    "I'd like a 45-second short of a Yiddish-speaking grandfather telling stories to his grandson, with Yiddish and English subtitles.",
    "Cook up a 1-minute mini-drama of an Armenian potter shaping a vase in Yerevan, with Armenian and English subtitles.",
    "Make a 30-second piece where a Georgian winemaker explains qvevri tradition, with Georgian and English subtitles.",
    "Generate a 45-second cinematic clip of an Estonian birch-tapper collecting sap, with Estonian and English subtitles.",
    "Produce a 30-second short of a Lithuanian amber polisher at her workbench, with Lithuanian and English subtitles.",
    "Build a 1-minute mini-drama about a Slovenian beekeeper checking hives, with Slovenian and English subtitles.",
    "Create a 45-second piece where a Croatian fisherman cleans his catch on a Dalmatian dock, with Croatian and English subtitles.",
    "I want a 30-second cinematic short of a Tibetan herder leading yaks across a high pass, with Tibetan and Mandarin subtitles.",
    "Render a 1-minute mini-drama of a Bhutanese monk lighting butter lamps, with Dzongkha and English subtitles.",
    "Make me a 30-second short about a Nepali porter resting on a Himalayan trail, with Nepali and English subtitles.",
    "Cook up a 45-second piece of a Sinhalese mother teaching her daughter to weave reed mats, with Sinhalese and English subtitles.",
    "Produce a 30-second clip of a Tamil grandfather telling sea-stories on a Chennai pier, with Tamil and English subtitles.",
    "Build a 1-minute mini-drama of a Thai chef preparing pad thai for her granddaughter, with Thai and English subtitles.",
    "Generate a 45-second cinematic piece about a Burmese gold-leaf maker hammering at dawn, with Burmese and English subtitles.",
    "I'd like a 30-second short of a Khmer dancer rehearsing in an Angkor courtyard, with Khmer and English subtitles.",
    "Create a 1-minute mini-drama of a Lao grandmother weaving silk on a hand loom, with Lao and English subtitles.",
    "Render a 45-second clip of a Kazakh eagle hunter teaching his son falconry, with Kazakh and Russian subtitles.",
    "I want a 30-second cinematic piece of a Pashto-speaking elder telling stories to his grandchildren, with Pashto and English subtitles.",
    "Make a 45-second short where a Bangla schoolteacher reads to her class in Dhaka, with Bengali and English subtitles.",
    "Cook up a 30-second piece of an Urdu poet reciting on a Lahore rooftop, with Urdu and English subtitles.",
    "Produce a 1-minute mini-drama about a Quechua weaver teaching her daughter in the Andes, with Quechua and Spanish subtitles.",
    "Build a 45-second clip of a Maya grandmother grinding corn at a Yucatán hearth, with Yucatec Maya and Spanish subtitles.",
    "Create a 30-second cinematic short of a Hawaiian elder teaching her granddaughter hula, with Hawaiian and English subtitles.",
    "Render a 1-minute mini-drama of a Welsh shepherdess crossing a Snowdonia ridge, with Welsh and English subtitles.",
    "Generate a 45-second short of an Irish bodhrán player rehearsing in a Dublin pub, with Irish Gaelic and English subtitles.",
    "I'd like a 30-second piece of a Scottish Gaelic singer performing on a Hebridean shore, with Scottish Gaelic and English subtitles.",
    "Make me a 1-minute mini-drama of a Basque grandfather teaching pelota to his grandson, with Basque and Spanish subtitles.",
    "Produce a 30-second cinematic short of a Sami reindeer herder calling her flock, with Sami and Norwegian subtitles.",
    "Build a 45-second short of a Faroese fisherman returning to harbor in storm, with Faroese and Danish subtitles.",
    "I want a 30-second piece of an Icelandic poet reading sagas in a Reykjavik hall, with Icelandic and English subtitles.",
    "Cook up a 1-minute mini-drama about a Greenlandic Inuk hunter reading sea ice with his son, with Greenlandic and Danish subtitles.",
    "Render a 30-second clip of a Yoruba elder teaching drums to apprentices in Ibadan, with Yoruba and English subtitles.",
    "Generate a 45-second cinematic piece of a Zulu grandmother braiding her granddaughter's hair, with Zulu and English subtitles.",
    "Make a 30-second short where an Igbo fisherman explains the river to his daughter, with Igbo and English subtitles.",
    "Produce a 1-minute mini-drama of an Amharic grandfather playing chess in an Addis cafe, with Amharic and English subtitles.",
    "I'd like a 45-second short of a Hausa caravan leader navigating Saharan dunes, with Hausa and French subtitles.",
    "Build a 30-second clip of a Berber weaver coloring wool in an Atlas village, with Berber and Arabic subtitles.",
    "Create a 1-minute mini-drama about an Akan jeweler crafting a ring in Kumasi, with Akan and English subtitles.",
    "Render a 30-second cinematic piece of a Xhosa grandmother teaching beadwork to her granddaughter, with Xhosa and English subtitles.",
    "I want a 45-second short of a Tigrinya farmer threshing teff at harvest, with Tigrinya and English subtitles.",
    "Cook up a 30-second clip of a Somali fisherman mending nets in Mogadishu, with Somali and Arabic subtitles.",
    "Generate a 1-minute mini-drama of a Malay batik artist dyeing cloth in Penang, with Malay and English subtitles.",
    "Make me a 30-second short about an Indonesian gamelan player tuning her instrument, with Indonesian and English subtitles.",
    "Produce a 45-second cinematic piece of a Filipina lola weaving piña fabric in Aklan, with Tagalog and English subtitles.",
    "Build a 30-second clip of a Cantonese tea master pouring oolong in Hong Kong, with Cantonese and English subtitles.",
    "I'd like a 1-minute mini-drama about a Hokkien fisherman teaching his nephew at a Taiwan dock, with Hokkien and Mandarin subtitles.",
    "Render a 45-second short of an Uzbek bread baker stamping non in Bukhara, with Uzbek and Russian subtitles.",
    "Create a 30-second piece where a Tajik grandmother teaches embroidery to her granddaughter, with Tajik and Russian subtitles.",
    "Make a 1-minute mini-drama of a Kyrgyz horseman racing across a steppe, with Kyrgyz and Russian subtitles.",
    "Cook up a 45-second cinematic piece about a Turkmen carpet weaver in an Ashgabat workshop, with Turkmen and Russian subtitles.",
    # ── more bilingual cinematic mini-dramas (50) ─────────────────────────
    "Make me a 1-minute mini-drama about a Yiddish-speaking grandfather telling stories to his grandson in a Jerusalem courtyard, with Yiddish and Hebrew subtitles.",
    "I want a 45-second cinematic short of a Ladino-speaking grandmother teaching cooking in a Thessaloniki kitchen, with Ladino and Greek subtitles.",
    "Create a 30-second piece where a Romanian grandmother braids her granddaughter's hair on a Bucharest balcony, with Romanian and Italian subtitles.",
    "Produce a 2-minute mini-drama about a Hungarian bakeshop owner explaining her chimney-cake to a tourist, with Hungarian and German subtitles.",
    "Build a 45-second short of a Czech grandfather teaching his grandson to brew his first beer, with Czech and German subtitles.",
    "Render a 30-second cinematic clip of a Slovak shepherdess explaining her Tatra cheese to a French traveler, with Slovak and French subtitles.",
    "Cook up a 1-minute mini-drama where an Albanian fisherman explains his nets to his Italian neighbor, with Albanian and Italian subtitles.",
    "Generate a 30-second short of a Bulgarian rose-picker teaching her granddaughter at a Kazanlak field, with Bulgarian and Russian subtitles.",
    "I'd like a 45-second cinematic piece of a Macedonian grandmother teaching cooking to a Greek visitor, with Macedonian and Greek subtitles.",
    "Make a 30-second clip of a Bosnian sevdah singer rehearsing with her Croatian accompanist, with Bosnian and Croatian subtitles.",
    "Produce a 2-minute mini-drama about a Serbian grandfather teaching his Italian grandson to play dominoes, with Serbian and Italian subtitles.",
    "Build a 45-second short of an Estonian grandmother explaining her Saaremaa baking to a Latvian friend, with Estonian and Latvian subtitles.",
    "Create a 30-second piece where a Lithuanian carpenter teaches his Polish nephew traditional joinery, with Lithuanian and Polish subtitles.",
    "Render a 1-minute mini-drama of a Belarusian grandmother teaching her grandson to make blini, with Belarusian and Russian subtitles.",
    "I want a 30-second cinematic short of a Ukrainian grandfather teaching his grandson to play the bandura, with Ukrainian and Polish subtitles.",
    "Cook up a 45-second piece of a Moldovan grandmother teaching her granddaughter to make plăcintă, with Romanian and Russian subtitles.",
    "Generate a 1-minute mini-drama of a Georgian grandmother teaching her granddaughter to make khachapuri, with Georgian and Russian subtitles.",
    "Make me a 30-second clip about an Armenian grandfather teaching his grandson to play duduk, with Armenian and Russian subtitles.",
    "Produce a 45-second short where an Azerbaijani grandmother teaches her granddaughter to make plov, with Azerbaijani and Russian subtitles.",
    "Build a 30-second cinematic clip of a Kazakh grandfather teaching his grandson eagle-hunting basics, with Kazakh and Russian subtitles.",
    "Create a 1-minute mini-drama of a Kyrgyz grandmother teaching her granddaughter felt-rug making, with Kyrgyz and Russian subtitles.",
    "Render a 30-second clip of an Uzbek grandfather teaching his grandson to bake non bread, with Uzbek and Russian subtitles.",
    "I'd like a 45-second short of a Turkmen grandmother teaching her granddaughter to weave a carpet, with Turkmen and Russian subtitles.",
    "Cook up a 1-minute mini-drama of a Tajik grandfather teaching his grandson to play Rubob, with Tajik and Russian subtitles.",
    "Make a 30-second piece where a Mongolian grandmother teaches her granddaughter to make buuz, with Mongolian and Mandarin subtitles.",
    "Generate a 45-second cinematic clip of a Tibetan grandfather teaching his grandson to make butter tea, with Tibetan and Mandarin subtitles.",
    "Produce a 30-second short of a Bhutanese grandmother teaching her granddaughter to weave a Kira, with Dzongkha and English subtitles.",
    "Build a 1-minute mini-drama about a Nepali grandfather teaching his grandson to carry a doko basket, with Nepali and Hindi subtitles.",
    "Create a 45-second piece where a Sinhalese grandmother teaches her granddaughter ayurvedic cooking, with Sinhalese and English subtitles.",
    "I want a 30-second cinematic short of a Tamil grandfather teaching his grandson kolam patterns, with Tamil and English subtitles.",
    "Render a 1-minute mini-drama of a Bengali grandmother teaching her granddaughter to roll luchi, with Bengali and English subtitles.",
    "Make me a 30-second short about a Marathi grandfather teaching his grandson to make thalipeeth, with Marathi and English subtitles.",
    "Cook up a 45-second piece of a Gujarati grandmother teaching her granddaughter to make dhokla, with Gujarati and English subtitles.",
    "Generate a 30-second clip of a Punjabi grandfather teaching his grandson to play the dhol, with Punjabi and Hindi subtitles.",
    "Produce a 1-minute mini-drama of a Kannada grandmother teaching her granddaughter to make holige, with Kannada and English subtitles.",
    "Build a 45-second cinematic piece about a Telugu grandfather teaching his grandson to make pesarattu, with Telugu and English subtitles.",
    "I'd like a 30-second short of a Malayalam grandmother teaching her granddaughter to make appam, with Malayalam and English subtitles.",
    "Cook up a 1-minute mini-drama of an Odia grandfather teaching his grandson to weave ikat, with Odia and English subtitles.",
    "Make a 30-second piece where a Konkani grandmother teaches her granddaughter to make sorpotel, with Konkani and Marathi subtitles.",
    "Generate a 45-second cinematic clip of a Kashmiri grandfather teaching his grandson to make rogan josh, with Kashmiri and Urdu subtitles.",
    "Produce a 30-second short of a Karen grandmother teaching her granddaughter to weave a tunic, with Karen and Burmese subtitles.",
    "Build a 1-minute mini-drama about a Hmong grandfather teaching his grandson to embroider story-cloths, with Hmong and Vietnamese subtitles.",
    "Create a 45-second piece where a Cebuano grandmother teaches her granddaughter to make biko, with Cebuano and English subtitles.",
    "I want a 30-second cinematic short of an Ilocano grandfather teaching his grandson to make basi wine, with Ilocano and Tagalog subtitles.",
    "Render a 1-minute mini-drama of a Javanese grandmother teaching her granddaughter to make kerak telor, with Javanese and Indonesian subtitles.",
    "Make me a 30-second short about a Sundanese grandfather teaching his grandson to make peuyeum, with Sundanese and Indonesian subtitles.",
    "Cook up a 45-second piece of a Balinese grandmother teaching her granddaughter to make canang sari, with Balinese and Indonesian subtitles.",
    "Generate a 30-second clip of a Tongan grandfather teaching his grandson to weave ngatu cloth, with Tongan and English subtitles.",
    "Produce a 1-minute mini-drama of a Samoan grandmother teaching her granddaughter to make 'umu, with Samoan and English subtitles.",
    "Build a 45-second cinematic piece about a Fijian grandfather teaching his grandson to make kava, with Fijian and English subtitles.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
