"""x15 cr_music_ambience SFT short briefs.

Chain: Story→Screenplay→KeyFrame→Video→Music→Ambience→AudioMix→Compositor.
Trigger: brief names BOTH BGM/score AND ambient/atmospheric layer.
NO subtitles, NO upload.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Make a 1-minute mini-drama about a young soldier writing a letter home in a wartime trench, with mournful strings and battlefield ambience (distant artillery, wind through tarps).",
    "I want a 45-second cinematic short of a deep-sea diver descending into a coral wall, with ethereal synth music and underwater ambience (regulator bubbles, distant whale calls).",
    "Create a 30-second piece where a forest ranger pauses on an alpine ridge at dusk, with a sweeping orchestral score and forest ambience (bird calls, wind through pines).",
    "Produce a 2-minute mini-drama about a desert caravan crossing dunes at sunset, with a percussive Middle-Eastern score and desert wind ambience.",
    "Build a 45-second short of a busker playing violin in a Brooklyn subway, with a mournful violin solo and subway ambience (rumble, footfalls, distant announcements).",
    "Render a 30-second cinematic clip of a young priest lighting candles in an empty cathedral, with a pipe-organ score and cathedral ambience (echoes, distant traffic).",
    "Cook up a 1-minute mini-drama where a deep-space miner walks an asteroid surface, with synth orchestral score and spacesuit ambience (HVAC hum, breath, faint static).",
    "Generate a 30-second short of a French chef plating a tasting menu in a Paris bistro, with light jazz piano and bistro ambience (cutlery clinks, café chatter).",
    "I'd like a 45-second cinematic piece of a Tibetan monk lighting butter lamps in a high-altitude monastery, with chanting score and monastery ambience (singing bowls, wind).",
    "Make a 30-second clip of an Arctic researcher walking out of a Quonset hut at dawn, with minimalist piano and polar ambience (wind, generator hum, snow crunch).",
    "Produce a 2-minute mini-drama about a young mother watching a thunderstorm from a porch, with somber piano and storm ambience (rain on tin roof, distant thunder).",
    "Build a 45-second short of an opera singer rehearsing alone backstage, with a single soprano warm-up vocalise and theater ambience (footfalls, distant tuning).",
    "Create a 30-second piece where a young woman walks a Paris pont in autumn rain, with accordion-and-strings musette score and Paris-rain ambience (distant scooters, footfalls).",
    "Render a 1-minute mini-drama of an old fisherman pulling nets at a Cornish dock, with Celtic-fiddle score and harbor ambience (gull cries, lapping water).",
    "I want a 30-second cinematic short of a vineyard worker stomping grapes at harvest, with Italian folk-fiddle score and vineyard ambience (cricket pulse, distant generator).",
    "Cook up a 45-second piece of a girl reading on a porch during a thunderstorm, with soft piano score and storm ambience (rain on tin roof, distant thunder).",
    "Generate a 1-minute mini-drama of a beekeeper checking hives in an alpine meadow, with a delicate string-and-flute score and meadow ambience (bee-hum, wind).",
    "Make me a 30-second clip about a sailor on a destroyer deck reading a final order, with low-brass score and destroyer-deck ambience (waves, rigging clicks, distant horn).",
    "Produce a 45-second short where a child watches the first snowflake of winter, with a quiet piano score and snowfall ambience (muffled distance, soft ticks).",
    "Build a 30-second piece of a glaciologist drilling an ice core, with sustained string score and glacier ambient (wind, distant calving rumble).",
    "I'd like a 2-minute mini-drama of a midwife cycling through dawn fog to deliver a baby, with hopeful folk-violin score and dawn-fog ambience (distant rooster, bicycle squeak).",
    "Render a 45-second clip of a war photographer crossing a snow-covered field at dawn, with melancholic cello score and battlefield ambient (wind, distant artillery).",
    "Create a 30-second piece where a coastal lighthouse keeper sounds her foghorn in a hurricane, with crashing orchestral strings and hurricane ambience (gale, debris).",
    "Make a 1-minute mini-drama about a young volunteer firefighter walking into a wildfire glow at dawn, with mounting low-brass score and wildfire ambience (crackling, distant sirens).",
    "Cook up a 45-second cinematic short of a young paramedic loading survivors into an ambulance, with tense string score and earthquake-aftermath ambience (distant alarms, rubble).",
    "Generate a 30-second clip of a falconer in the Mongolian steppe at dawn, with wind-instrument score and steppe ambience (distant horse hooves, eagle screeches).",
    "I want a 1-minute mini-drama of a young geologist examining lava rock at a Hawaiian crater rim, with deep orchestral brass score and crater ambience (sulfur hiss, distant wind).",
    "Make me a 30-second short about a paleontologist brushing dust off a fossil at a Patagonian dig, with contemplative string score and steppe-wind ambience.",
    "Produce a 45-second piece where a young chef preps mise en place at a packed Mumbai restaurant, with Indian-classical-strings score and kitchen ambience (clatter, chatter).",
    "Build a 30-second cinematic clip of a janitor mopping a Chicago skyscraper lobby at 4 AM, with minimalist piano score and skyscraper ambience (HVAC hum, distant elevator).",
    "Create a 1-minute mini-drama of a forester noticing the same footprints for three days, with eerie strings score and old-growth-forest ambience (creaks, distant ravens).",
    "Render a 30-second clip of a child wandering an abandoned hospital ward, with dissonant piano score and abandoned-hospital ambient (flickering lights, drips).",
    "I'd like a 45-second short of a librarian in a rare-books room hearing whispering, with shimmering uneasy piano score and rare-books-room ambient (page rustle, faint whispers).",
    "Cook up a 1-minute mini-drama of a custodian discovering a basement door slightly ajar, with low rising-string score and haunted-basement ambient (drips, faint whispers).",
    "Make a 30-second piece where a young historian alone in a closed museum gallery hears footsteps, with dissonant strings score and museum ambient (HVAC hum, faint creaks).",
    "Generate a 45-second cinematic clip of a young diver entering a shipwreck hull, with low orchestral drone score and shipwreck ambient (water rumble, hull creaks).",
    "Produce a 30-second short of a forest ranger walking past a long-abandoned camp, with eerie strings score and abandoned-camp ambient (wind through tarps, distant ravens).",
    "Build a 1-minute mini-drama about a girl stepping into an empty cathedral at dusk, with pipe-organ score and cathedral ambience (echoes, distant traffic).",
    "I want a 45-second cinematic piece of a journalist alone in a closed asylum corridor, with dissonant violin score and asylum ambient (faint patient murmurs, distant clatter).",
    "Make me a 30-second short about a girl in an empty school gymnasium hearing basketballs bouncing one by one, with eerie piano score and gymnasium ambient (echoes).",
    "Cook up a 45-second clip of a Roman scribe copying senate records by oil-lamp, with classical-strings score and Roman villa ambient (fountain, crickets, distant chariots).",
    "Generate a 1-minute mini-drama of a Tang-dynasty poet reading verse by a koi pond, with Tang-flute-and-strings score and Tang courtyard ambient (water trickle, cricket pulse).",
    "I'd like a 30-second cinematic short of a 1920s flapper reading a love letter in a Manhattan speakeasy, with Charleston-piano score and speakeasy ambient (chatter, glass clinks).",
    "Render a 45-second clip of a Victorian astronomer adjusting a brass telescope on a London rooftop, with classical-strings score and London-night ambient (carriage, fog horn).",
    "Make a 30-second piece where a Tudor handmaiden lays out her queen's robes, with Renaissance-lute score and castle-morning ambient (distant horse hooves, torches).",
    "Cook up a 1-minute mini-drama of a Heian noblewoman reading poetry behind a bamboo screen, with Heian flute score and Heian courtyard ambient (distant flute, pebbles, crickets).",
    "Produce a 30-second short where a Civil-War surgeon scrubs his hands before operating, with mournful strings score and field-hospital ambient (distant cannon, wind).",
    "Build a 45-second cinematic piece about a Norse sailor whittling a wooden charm on a longship at dawn, with Norse-throat-singing score and longship ambient (waves, oar-locks).",
    "Create a 1-minute mini-drama of a Han-dynasty potter shaping a celadon bowl, with Han flute-and-strings score and Han workshop ambient (water in basins, wheel creaks).",
    "I want a 30-second cinematic short of a Tudor handmaiden dressing her queen at dawn, with Renaissance-lute score and Tudor-castle-morning ambient (distant hooves, torches).",
    "Render a 45-second clip of a Bedouin elder leading evening prayers under desert stars, with sustained vocal-call score and desert-night ambient (cricket pulses, distant goat bells).",
    "Cook up a 30-second piece of a 14th-century Florentine clockmaker oiling tower-clock gears, with classical-strings score and tower-clock ambient (gear ticks, distant church bells).",
    "Generate a 1-minute mini-drama of a young Buddhist monk lighting butter lamps at dawn, with low chanting and singing-bowl score and monastery ambience (distant horns).",
    "Make me a 30-second short about a young Greek-Orthodox priest preparing icons for a feast day, with Byzantine-chant score and Byzantine chapel ambient (incense smoke hiss).",
    "Produce a 45-second piece where a young Sikh worshiper folds a chador for the Guru Granth Sahib, with kirtan-style raag score and gurdwara ambient (distant bells).",
    "Build a 30-second cinematic clip of a young Sufi practitioner whirling slowly in a courtyard, with ney-and-drum sema score and courtyard ambient (footfalls, distant breeze).",
    "I'd like a 1-minute mini-drama of a young Maasai elder lighting a ceremonial fire at twilight, with deep group chant score and Maasai-village ambient (distant cattle).",
    "Make a 45-second cinematic short of a young Vodou priestess pouring libation by candlelight, with traditional drumming-and-chant score and Haitian courtyard ambient (insects).",
    "Cook up a 30-second clip of a young Hindu priestess threading marigolds into a temple garland, with bansuri-and-sitar raag score and temple ambient (distant bells, drips).",
    "Render a 1-minute mini-drama of a young Catholic novice taking final vows in a candlelit chapel, with Gregorian-chant choir score and chapel ambient (echoes, candle flicker).",
    "Generate a 30-second short of a young yarmulke-clad cantor practicing Kol Nidre alone in an empty synagogue, with solo-cantor melody score and synagogue ambient (clock tick).",
    "Produce a 45-second short where a young Quaker reads silently at a Meeting House before service, with sustained-organ-note score and Meeting-House ambient (footsteps, page rustle).",
    "Build a 30-second piece of a young Druid celebrant standing before standing stones at solstice, with single-harp score and standing-stone ambient (wind, distant ravens).",
    "Make me a 1-minute mini-drama about a young Bahá'í youth lighting candles at a Naw-Rúz table, with soft a-cappella score and family-home ambient (distant chatter, clock tick).",
    "I want a 45-second cinematic piece of a young Tibetan monk lighting butter lamps in a Lhasa monastery, with low chanting and singing-bowl score and monastery ambient (footfalls).",
    "Make a 30-second clip of a young Coptic deacon walking through a desert monastery courtyard at dawn, with monastic-chant score and desert-monastery ambient (footfalls, drips).",
    "Cook up a 45-second piece of a young Shinto priest sweeping the path to a shrine, with koto-and-bamboo-flute score and Shinto-shrine ambient (wind, distant bell).",
    "Generate a 1-minute mini-drama of a young Buddhist monastery cook preparing miso at dawn, with bamboo-flute score and monastery-kitchen ambient (water in basins, distant chants).",
    "Produce a 30-second short of a young Bedouin storyteller weaving tales by firelight, with oud score and desert-night ambient (cricket pulses, distant camel).",
    "Build a 45-second cinematic clip of a young Coptic monk transcribing scripture in a desert cell, with monastic-chant score and desert-cell ambient (page rustle, distant wind).",
    "Render a 30-second piece where a young Hindu monk meditates by a temple lake at dawn, with bansuri score and temple-lake ambient (distant bells, water lapping).",
    "Create a 1-minute mini-drama of a young Korean Buddhist monk striking a moktak at dawn, with moktak-and-flute score and Korean-temple ambient (distant chimes, footfalls).",
    "I'd like a 45-second cinematic short of a young Sami noaidi drumming alone in a Sami goahti, with Sami joik score and goahti ambient (fire crackle, wind, distant reindeer).",
    # ── more cinematic music+ambience scenes (50) ─────────────────────────
    "Make me a 1-minute mini-drama of a young war pilot flying a recon mission over fog-bound coast, with brass-and-strings score and cockpit-engine ambient (engine drone, wind hiss).",
    "I want a 45-second cinematic short of a young marine biologist following a whale at sunset, with serene-cello score and ocean-wave ambient (lapping water, distant gulls).",
    "Create a 30-second piece of a young Andean weaver setting up a high-altitude loom, with Andean-pan-flute score and altiplano ambient (wind, distant llama bleats).",
    "Produce a 2-minute mini-drama about a young Korean grandmother preparing kimchi for the winter, with gayageum score and Korean-courtyard ambient (chopping, distant temple bell).",
    "Build a 45-second short of a young Finnish lumberjack felling a tree at dawn, with Finnish-fiddle score and forest ambient (axe thud, distant bird, distant chainsaw).",
    "Render a 30-second cinematic clip of a young Egyptian archaeologist sweeping sand off a tomb threshold, with oud score and desert ambient (sand-hiss, distant generator).",
    "Cook up a 1-minute mini-drama where a young Nepali porter ascends a Himalayan pass, with bansuri score and high-altitude ambient (wind, distant prayer flag flutter).",
    "Generate a 45-second short of a young Greek shepherdess crossing a Cycladic ridge at dusk, with bouzouki score and Aegean-mountain ambient (distant goat bell, breeze).",
    "I'd like a 30-second cinematic piece of a young Syrian potter shaping a vase in a Damascus atelier, with oud score and atelier ambient (wheel creak, water bowl).",
    "Make a 30-second clip of a young Thai dancer rehearsing in an Ayutthaya courtyard at dawn, with Thai-classical score and courtyard ambient (cicadas, distant temple bell).",
    "Produce a 2-minute mini-drama about a young Mongolian wrestler preparing for Naadam in a ger camp, with Mongolian-throat-singing score and steppe-camp ambient (wind, distant horse).",
    "Build a 45-second short of a young Bhutanese archer practicing in Thimphu at dawn, with Bhutanese-flute score and Bhutanese-courtyard ambient (arrow-thud, prayer-flag flutter).",
    "Create a 30-second piece where a young Inuit hunter checks ice-fishing lines on a frozen bay, with Inuit-throat-singing score and frozen-bay ambient (wind, distant huskies).",
    "Render a 1-minute mini-drama of a young Maori tohunga teaching her granddaughter karakia at dawn, with Maori-pūoro score and marae ambient (distant tui call, breeze).",
    "I want a 30-second cinematic short of a young Aboriginal elder painting a rock-art panel at twilight, with didgeridoo score and outback ambient (cricket, distant dingo).",
    "Cook up a 45-second piece of a young Tongan fisherman cleaning his catch on a beach at dusk, with Tongan-lali score and tropical-shore ambient (lapping water, distant gulls).",
    "Generate a 1-minute mini-drama of a young Hawaiian taro-farmer working a Waipi'o lo'i, with Hawaiian-ipu-heke score and lo'i ambient (water trickle, distant waterfall).",
    "Make me a 30-second clip about a young Yupik hunter hauling a sled across pack ice at dawn, with Yupik-drum score and pack-ice ambient (wind, ice creaks).",
    "Produce a 45-second short where a young Cree elder lights a sweetgrass smudge at sunrise, with Plains-Cree-flute score and prairie-dawn ambient (wind, distant raven).",
    "Build a 30-second cinematic clip of a young Inuktitut grandmother sewing skin boots inside a sod hut, with throat-singing score and sod-hut ambient (lamp hiss, distant wind).",
    "Create a 1-minute mini-drama of a young Ojibwe rice-harvester gathering wild rice on a Wisconsin lake, with Ojibwe-flute score and lake ambient (paddle dip, distant loon).",
    "Render a 30-second clip of a young Navajo silversmith finishing a turquoise ring inside a hogan, with Navajo-flute score and hogan ambient (hammer-tap, distant wind).",
    "I'd like a 45-second short of a young Lakota grandmother braiding her granddaughter's hair on a Dakota porch, with Lakota-flute score and prairie ambient (wind, distant horse).",
    "Cook up a 1-minute mini-drama of a young Apache scout reading tracks at dawn on a Sonoran ridge, with Apache-flute score and Sonoran ambient (cricket, distant coyote).",
    "Make a 30-second piece where a young Hopi farmer plants a single seedling in a Mesa-top milpa, with Hopi-rattle score and Mesa-top ambient (wind, distant kachina chant).",
    "Generate a 45-second cinematic clip of a young Zuni potter shaping clay at a courtyard wheel, with Pueblo-drum score and Pueblo ambient (wheel creak, distant chant).",
    "Produce a 30-second short of a young Pueblo bread-baker firing a horno oven, with Pueblo-folk score and Pueblo-courtyard ambient (oven roar, distant chant).",
    "Build a 1-minute mini-drama about a young Mapuche grandmother teaching her granddaughter weaving on a Patagonian loom, with Mapuche-trutruka score and Patagonian-meadow ambient (wind, distant hooves).",
    "Create a 45-second piece where a young Aymara herder leads llamas across an altiplano pass at dawn, with Andean-pan-flute score and altiplano ambient (wind, distant llama bleat).",
    "I want a 30-second cinematic short of a young Quechua weaver setting up a hand loom in a Cusco courtyard, with Andean-charango score and Cusco-courtyard ambient (distant footfalls).",
    "Render a 1-minute mini-drama of a young Garifuna drummer teaching his nephew on a beach at dusk, with Garifuna-drum score and Garifuna-beach ambient (distant waves, distant fire).",
    "Make me a 30-second short about a young Haitian Kreyòl baker firing a stone oven at dawn, with Haitian-rara score and bakery-courtyard ambient (oven roar, distant rooster).",
    "Cook up a 45-second piece of a young Jamaican Patois fishermonger cleaning her catch at a Negril dock, with Jamaican-mento score and Negril-dock ambient (lapping water, distant gulls).",
    "Generate a 30-second clip of a young Trinidadian carnival-girl rehearsing in a courtyard, with steel-pan score and carnival-courtyard ambient (distant parade-crowd, distant calypso).",
    "Produce a 1-minute mini-drama of a young Bahamian junkanoo-boy practicing goombay drumming on a beach at dusk, with goombay-drum score and Bahamian-shore ambient (distant waves, distant fire).",
    "Build a 45-second cinematic piece about a young Dominican abuelita preparing mangú in a Santo Domingo kitchen, with merengue-piano score and kitchen ambient (stovetop, distant traffic).",
    "Render a 30-second clip of a young Cuban grandfather playing dominos on a Havana porch, with Cuban-tres score and Havana-porch ambient (distant traffic, distant son cubano).",
    "I'd like a 45-second short of a young Puerto Rican bombera dancer rehearsing in a Loiza courtyard, with bomba-and-plena score and Loiza-courtyard ambient (distant waves, distant bomba drum).",
    "Cook up a 1-minute mini-drama of a young Argentinian gaucho herding cattle across a Patagonian estancia, with bandoneón score and pampas ambient (distant hooves, breeze).",
    "Make a 30-second piece where a young Chilean huaso polishes his saddle in a hacienda barn at dusk, with Chilean-cueca score and hacienda-barn ambient (distant horse, distant rooster).",
    "Generate a 45-second cinematic clip of a young Brazilian caipira playing viola caipira on a porch at dusk, with viola-caipira score and rural-Minas ambient (distant cicada, distant guitar).",
    "Produce a 30-second short of a young Colombian cumbia-girl rehearsing on a Caribbean shore, with cumbia-accordion score and Caribbean-shore ambient (distant waves, distant tambora).",
    "Build a 1-minute mini-drama about a young Venezuelan llanera-girl playing maracas in a Plain hut at dusk, with llanera score and Plain-hut ambient (distant cattle, distant breeze).",
    "Create a 45-second piece where a young Peruvian quena-player practices on an Andes ridge at dawn, with quena score and Andes-ridge ambient (wind, distant condor).",
    "I want a 30-second cinematic short of a young Bolivian tarka-player rehearsing on a Lake-Titicaca shore, with tarka score and Titicaca-shore ambient (lapping water, distant breeze).",
    "Render a 1-minute mini-drama of a young Ecuadorian rondador-player rehearsing in an Otavalo courtyard, with rondador score and Otavalo-courtyard ambient (distant market chatter, distant breeze).",
    "Make me a 30-second short about a young Paraguayan harpa-player rehearsing in an Asunción patio, with Paraguayan-harp score and Asunción-patio ambient (distant traffic, distant rooster).",
    "Cook up a 45-second piece of a young Uruguayan candombe-drummer rehearsing in a Montevideo barrio, with candombe-drum score and Montevideo-barrio ambient (distant tango, distant traffic).",
    "Generate a 30-second clip of a young Cuban son-cubano singer performing on a Trinidad rooftop at dusk, with son-cubano score and Trinidad-rooftop ambient (distant traffic, distant breeze).",
    "Produce a 1-minute mini-drama of a young Guatemalan marimba-player rehearsing in an Antigua courtyard, with Guatemalan-marimba score and Antigua-courtyard ambient (distant breeze, distant church bell).",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
