"""x15 style_extend_music SFT.
Chain: IntakeVideo → StyleTransfer → VideoExtend → Music → AudioMix → Compositor.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 30-second beach clip — please style as anime, extend to 90 seconds, and add a synthwave BGM.",
    "Here's a 45-second city-street clip — style as Studio Ghibli, extend to 2 minutes, and overlay a Joe-Hisaishi piano BGM.",
    "I have a 1-minute road trip clip — style as watercolor, extend to 3 minutes, and add a dreamy-piano BGM.",
    "Uploading a 30-second skater clip — style as comic-book ink, extend to 90 seconds, and overlay a punk-rock BGM.",
    "Here's a 45-second coffee-shop clip — style as Edward Hopper, extend to 2 minutes, and add a smooth-jazz BGM.",
    "I'm sending you a 30-second mountain-drive clip — style as Bob Ross oil-painting, extend to 90 seconds, and overlay a country-folk BGM.",
    "Uploading a 1-minute beach-running clip — style as Hokusai surimono print, extend to 3 minutes, and add a synthwave BGM.",
    "Here's a 45-second family-cookout clip — style as Norman Rockwell illustration, extend to 2 minutes, and overlay an Americana-folk BGM.",
    "I have a 30-second backyard-bonfire clip — style as Pixar 3D animation, extend to 90 seconds, and add a folksy-banjo BGM.",
    "Uploading a 1-minute park-picnic clip — style as Renoir Impressionism, extend to 3 minutes, and overlay a French-musette BGM.",
    "Here's a 45-second canoe-ride clip — style as Japanese ink-wash, extend to 2 minutes, and add a koto BGM.",
    "I'm sending you a 30-second sushi-prep clip — style as Hokusai woodblock, extend to 90 seconds, and overlay a Japanese-shamisen BGM.",
    "Uploading a 1-minute Italian-vineyard tour — style as Italian fresco, extend to 3 minutes, and add an Italian-mandolin BGM.",
    "Here's a 45-second French-bakery tour — style as Henri Matisse Fauvism, extend to 2 minutes, and overlay a French-musette BGM.",
    "I have a 30-second Spanish-tapas-bar clip — style as Picasso cubism, extend to 90 seconds, and add a flamenco-guitar BGM.",
    "Uploading a 1-minute Greek-island walk — style as Greek-vase black-figure painting, extend to 3 minutes, and overlay a Greek-bouzouki BGM.",
    "Here's a 30-second Provence-lavender field — style as a Cézanne post-Impressionist, extend to 90 seconds, and add a French-musette BGM.",
    "I'm sending you a 45-second Berlin-nightlife reel — style as a German Expressionist painting, extend to 2 minutes, and overlay a Berlin-techno BGM.",
    "Uploading a 1-minute Paris-Montmartre walk — style as a Toulouse-Lautrec poster, extend to 3 minutes, and add a French-jazz BGM.",
    "Here's a 30-second Amsterdam-canal-bike ride — style as a Vermeer interior, extend to 90 seconds, and overlay a Dutch-folk BGM.",
    "I have a 1-minute London-Tube ride — style as a 1960s mod poster, extend to 3 minutes, and add a Britpop BGM.",
    "Uploading a 45-second Tokyo-Shibuya crossing — style as Wong-Kar-wai cinematic look, extend to 2 minutes, and overlay a J-pop BGM.",
    "Here's a 30-second Kyoto-temple-garden reel — style as Japanese sumi-e ink-wash, extend to 90 seconds, and add a koto BGM.",
    "I'm sending you a 45-second Beijing-hutong walk — style as Chinese ink-wash painting, extend to 2 minutes, and overlay a guzheng BGM.",
    "Uploading a 1-minute Hong-Kong-harbor reel — style as Wong-Kar-wai cinematic, extend to 3 minutes, and add a Cantopop BGM.",
    "Here's a 30-second Bangkok-tuk-tuk reel — style as Thai-classical painting, extend to 90 seconds, and overlay a Thai-percussion BGM.",
    "I have a 45-second Hanoi-old-quarter reel — style as Vietnamese-folk illustration, extend to 2 minutes, and add a Vietnamese-dan-bau BGM.",
    "Uploading a 1-minute Mumbai-Chowpatty-beach reel — style as Indian-miniature Mughal painting, extend to 3 minutes, and overlay a Bollywood-strings BGM.",
    "Here's a 30-second Rio-Carnival reel — style as Brazilian-cordel woodcut, extend to 90 seconds, and add a samba-batucada BGM.",
    "I'm sending you a 45-second Buenos-Aires-tango reel — style as Picasso blue-period painting, extend to 2 minutes, and overlay a tango-bandoneón BGM.",
    "Uploading a 1-minute Havana-streets reel — style as Cuban-cordel illustration, extend to 3 minutes, and add a Cuban-son BGM.",
    "Here's a 30-second Cusco-Inca-trail reel — style as Andean-folk illustration, extend to 90 seconds, and overlay an Andean-pan-flute BGM.",
    "I have a 45-second Mexico-City-Zócalo reel — style as Diego-Rivera mural, extend to 2 minutes, and add a Mariachi-trumpet BGM.",
    "Uploading a 1-minute Marrakesh-souk reel — style as Persian miniature, extend to 3 minutes, and overlay an Arabic-oud BGM.",
    "Here's a 30-second Cairo-Khan-el-Khalili reel — style as Egyptian-tomb painting, extend to 90 seconds, and add an Egyptian-oud BGM.",
    # ── more upload + style + extend + BGM requests (50) ──────────────
    "Uploading a 30-second Iceland-glacier hike — style as Caspar-David-Friedrich Romantic, extend to 90 seconds, and add an Icelandic-folk BGM.",
    "Here's a 45-second Norway-fjord cruise — style as Edvard-Munch expressionism, extend to 2 minutes, and overlay a Nordic-strings BGM.",
    "I have a 1-minute Sweden-archipelago kayak — style as Carl-Larsson watercolor, extend to 3 minutes, and add a Swedish-folk-fiddle BGM.",
    "Uploading a 30-second Finland-sauna walk — style as Akseli-Gallen-Kallela folk, extend to 90 seconds, and overlay a Finnish-kantele BGM.",
    "Here's a 45-second Helsinki design-district reel — style as Alvar-Aalto modernist, extend to 2 minutes, and add a Finnish-electronica BGM.",
    "I'm sending you a 30-second Reykjavik thermal-pool clip — style as Erró pop-art, extend to 90 seconds, and overlay a Sigur-Rós-style ambient BGM.",
    "Uploading a 1-minute Nuuk-Greenland walk — style as Inuit graphic art, extend to 3 minutes, and add a Greenlandic-throat-singing BGM.",
    "Here's a 45-second Faroese-village walk — style as Faroese folk-art, extend to 2 minutes, and overlay a Faroese sea-shanty BGM.",
    "I have a 30-second Tallinn-old-town walk — style as medieval engraving, extend to 90 seconds, and add an Estonian regilaul BGM.",
    "Uploading a 1-minute Riga art-nouveau walk — style as Mucha Art-Nouveau, extend to 3 minutes, and overlay a Latvian folk-fiddle BGM.",
    "Here's a 30-second Prague-Castle walk — style as Czech Cubism, extend to 90 seconds, and add a Czech polka BGM.",
    "I'm sending you a 45-second Budapest thermal-bath clip — style as Klimt gold-leaf, extend to 2 minutes, and overlay a Hungarian csárdás BGM.",
    "Uploading a 1-minute Vienna coffeehouse walk — style as Egon-Schiele expressionism, extend to 3 minutes, and add a Viennese-waltz BGM.",
    "Here's a 30-second Munich-Marienplatz walk — style as Bavarian-folk-art, extend to 90 seconds, and overlay a Bavarian-brass-band BGM.",
    "I have a 45-second Salzburg-old-town walk — style as Mozart-era engraving, extend to 2 minutes, and add a Mozart-string-quartet BGM.",
    "Uploading a 1-minute Lake-Como villa tour — style as Italian Renaissance fresco, extend to 3 minutes, and overlay an Italian aria BGM.",
    "Here's a 30-second Sicilian-Etna hike — style as volcanic-fresco, extend to 90 seconds, and add a Sicilian-tarantella BGM.",
    "I'm sending you a 45-second Sardinian-Costa-Smeralda reel — style as Mediterranean-fresco, extend to 2 minutes, and overlay a Sardinian launeddas BGM.",
    "Uploading a 1-minute Portuguese-Alfama walk — style as azulejo-tile, extend to 3 minutes, and add a fado-guitar BGM.",
    "Here's a 30-second Madeira-island levada walk — style as Portuguese-tile, extend to 90 seconds, and overlay a Madeiran folkloric BGM.",
    "I have a 45-second Azores volcanic-crater reel — style as volcanic-mural, extend to 2 minutes, and add a Portuguese-fado BGM.",
    "Uploading a 1-minute Andorran-mountain-town walk — style as Romanesque fresco, extend to 3 minutes, and overlay an Andorran-folk BGM.",
    "Here's a 30-second Monaco-harbor reel — style as Belle-Époque poster, extend to 90 seconds, and add a French-jazz BGM.",
    "I'm sending you a 45-second Belgian-Bruges canal walk — style as Bruegel peasant scene, extend to 2 minutes, and overlay a Flemish-folk BGM.",
    "Uploading a 1-minute Luxembourgish-Castle walk — style as medieval illumination, extend to 3 minutes, and add a Luxembourgish-folk BGM.",
    "Here's a 30-second Liechtenstein-mountain reel — style as Alpine-folk illustration, extend to 90 seconds, and overlay a yodel-folk BGM.",
    "I have a 45-second Estonian-bog walking reel — style as Estonian-folk illustration, extend to 2 minutes, and add an Estonian-folk-flute BGM.",
    "Uploading a 1-minute Norwegian-Lofoten archipelago reel — style as Norse-saga illumination, extend to 3 minutes, and overlay a Sami-yoik-fusion BGM.",
    "Here's a 30-second Bornholm-island walk — style as Danish-folk illustration, extend to 90 seconds, and add a Danish-folk-violin BGM.",
    "I'm sending you a 45-second Skagen-art-light walk — style as Skagen-painters Danish impressionism, extend to 2 minutes, and overlay a Danish chamber-music BGM.",
    "Uploading a 1-minute Seoul-Gangnam street reel — style as Korean-Minhwa folk, extend to 3 minutes, and add a K-pop BGM.",
    "Here's a 30-second Busan-fish-market reel — style as Joseon court-painting, extend to 90 seconds, and overlay a Korean-pansori BGM.",
    "I have a 45-second Taipei-night-market reel — style as Taiwanese-night-market illustration, extend to 2 minutes, and add a Mandopop BGM.",
    "Uploading a 1-minute Macau-Senado-Square reel — style as Portuguese-Chinese fusion-tile, extend to 3 minutes, and overlay a Macanese-fado-fusion BGM.",
    "Here's a 30-second Singapore-Marina-Bay reel — style as neon-futurist, extend to 90 seconds, and add a Singapore-electronic BGM.",
    "I'm sending you a 45-second Kuala-Lumpur-Petronas reel — style as Malay-Songket pattern, extend to 2 minutes, and overlay a Malay-gamelan BGM.",
    "Uploading a 1-minute Jakarta-old-town reel — style as Dutch-colonial-watercolor, extend to 3 minutes, and add an Indonesian-keroncong BGM.",
    "Here's a 30-second Bali-Ubud rice-terrace reel — style as Balinese-Kamasan painting, extend to 90 seconds, and overlay a Balinese-gamelan BGM.",
    "I have a 45-second Phuket-beach reel — style as Thai-temple-mural, extend to 2 minutes, and add a Thai-pin-peat BGM.",
    "Uploading a 1-minute Bali-Tanah-Lot reel — style as Balinese-Wayang shadow, extend to 3 minutes, and overlay a Balinese-rindik BGM.",
    "Here's a 30-second Yangon-Shwedagon reel — style as Burmese-lacquer-painting, extend to 90 seconds, and add a Burmese-saung-harp BGM.",
    "I'm sending you a 45-second Vientiane-temple reel — style as Lao-temple-mural, extend to 2 minutes, and overlay a Lao-khaen-flute BGM.",
    "Uploading a 1-minute Phnom-Penh-Royal-Palace reel — style as Khmer Apsara mural, extend to 3 minutes, and add a Khmer-pinpeat BGM.",
    "Here's a 30-second Hanoi-Hoan-Kiem reel — style as Vietnamese-Đông-Hồ woodblock, extend to 90 seconds, and overlay a Vietnamese-đàn-tranh BGM.",
    "I have a 45-second Hoi-An-lantern-festival reel — style as Vietnamese-silk-painting, extend to 2 minutes, and add a Vietnamese-folk BGM.",
    "Uploading a 1-minute Macau-A-Ma-Temple reel — style as Macanese-azulejo, extend to 3 minutes, and overlay a Cantonese-opera-fusion BGM.",
    "Here's a 30-second Hong-Kong-Lan-Kwai-Fong reel — style as Hong-Kong neon-cinematic, extend to 90 seconds, and add a Cantopop BGM.",
    "I'm sending you a 45-second Mongolian-Ger camp reel — style as Mongolian-thangka, extend to 2 minutes, and overlay a Mongolian-throat-singing BGM.",
    "Uploading a 1-minute Sichuan-pandas-base reel — style as Chinese gongbi, extend to 3 minutes, and add a Chinese-erhu BGM.",
    "Here's a 30-second Lhasa-Potala-Palace reel — style as Tibetan-thangka, extend to 90 seconds, and overlay a Tibetan-singing-bowl BGM.",
    # ── more upload + style + extend + BGM requests (50) ──────────────
    "Uploading a 30-second New-York-Brooklyn-Bridge reel — style as Mary-Cassatt impressionist, extend to 90 seconds, and add a Gershwin-jazz BGM.",
    "Here's a 45-second New-York-Times-Square reel — style as Saul-Bass title sequence, extend to 2 minutes, and overlay a big-band-swing BGM.",
    "I have a 1-minute New-York-Wall-Street reel — style as Edward-Hopper urban-loneliness, extend to 3 minutes, and add a jazz-noir BGM.",
    "Uploading a 30-second Boston-Harbor reel — style as Winslow-Homer marine, extend to 90 seconds, and overlay a New-England-folk BGM.",
    "Here's a 45-second Philadelphia-Liberty-Bell reel — style as Norman-Rockwell illustration, extend to 2 minutes, and add a patriotic-fife BGM.",
    "I'm sending you a 30-second DC-Capitol reel — style as Ed-Ruscha pop-art, extend to 90 seconds, and overlay a patriotic-orchestral BGM.",
    "Uploading a 1-minute Chicago-Lakefront reel — style as Edward-Hopper, extend to 3 minutes, and add a Chicago-blues BGM.",
    "Here's a 45-second New-Orleans-French-Quarter reel — style as Edgar-Degas pastel, extend to 2 minutes, and overlay a Dixieland-jazz BGM.",
    "I have a 30-second Memphis-Beale-Street reel — style as Saul-Bass title, extend to 90 seconds, and add a Memphis-blues BGM.",
    "Uploading a 1-minute Nashville-Music-Row reel — style as Norman-Rockwell, extend to 3 minutes, and overlay a country-fiddle BGM.",
    "Here's a 30-second Atlanta-MLK-memorial reel — style as Jacob-Lawrence Migration Series, extend to 90 seconds, and add a gospel BGM.",
    "I'm sending you a 45-second Miami-Beach reel — style as Britto pop, extend to 2 minutes, and overlay a Cuban-son BGM.",
    "Uploading a 1-minute Austin-6th-Street reel — style as Pop-Art, extend to 3 minutes, and add a country-rock BGM.",
    "Here's a 30-second Houston-Space-Center reel — style as Ed-Ruscha, extend to 90 seconds, and overlay an electronic-pulse BGM.",
    "I have a 45-second Denver-Mile-High reel — style as Ansel-Adams photograph, extend to 2 minutes, and add an Americana-folk BGM.",
    "Uploading a 1-minute Phoenix-Sonoran reel — style as Georgia-O'Keeffe desert, extend to 3 minutes, and overlay a Sonoran-flute BGM.",
    "Here's a 30-second Portland-Powell's reel — style as Maira-Kalman illustration, extend to 90 seconds, and add an indie-folk BGM.",
    "I'm sending you a 45-second Seattle-Pike-Place reel — style as Andy-Warhol screenprint, extend to 2 minutes, and overlay a grunge-rock BGM.",
    "Uploading a 1-minute San-Francisco-Golden-Gate reel — style as James-McNeill-Whistler, extend to 3 minutes, and add a Pacific-jazz BGM.",
    "Here's a 30-second LA-Walk-of-Fame reel — style as Saul-Bass title, extend to 90 seconds, and overlay a Hollywood-orchestral BGM.",
    "I have a 45-second Vegas-Strip reel — style as Ed-Ruscha, extend to 2 minutes, and add a Vegas-lounge BGM.",
    "Uploading a 1-minute Toronto-CN-Tower reel — style as Lawren-Harris Group-of-Seven, extend to 3 minutes, and overlay a Canadian-folk BGM.",
    "Here's a 30-second Vancouver-Stanley-Park reel — style as Tom-Thomson Group-of-Seven, extend to 90 seconds, and add a Pacific-Northwest-flute BGM.",
    "I'm sending you a 45-second Montreal-Old-Port reel — style as Quebec-folk illustration, extend to 2 minutes, and overlay a Quebec-folk-fiddle BGM.",
    "Uploading a 1-minute Guadalajara mariachi-square reel — style as Diego-Rivera mural, extend to 3 minutes, and add a mariachi-trumpet BGM.",
    "Here's a 30-second Bogotá-Old-Town reel — style as Botero rotund, extend to 90 seconds, and overlay a cumbia BGM.",
    "I have a 45-second Lima-Plaza-Mayor reel — style as Fernando-de-Szyszlo, extend to 2 minutes, and add a marinera BGM.",
    "Uploading a 1-minute Buenos-Aires-Recoleta reel — style as Antonio-Berni, extend to 3 minutes, and overlay a tango BGM.",
    "Here's a 30-second Santiago-Plaza-Armas reel — style as Roberto-Matta surrealist, extend to 90 seconds, and add a Chilean-cueca BGM.",
    "I'm sending you a 45-second Rio-Copacabana reel — style as Tarsila-do-Amaral, extend to 2 minutes, and overlay a samba-batucada BGM.",
    "Uploading a 1-minute São-Paulo-Avenida-Paulista reel — style as Lygia-Clark, extend to 3 minutes, and add a bossa-nova BGM.",
    "Here's a 30-second Salvador-Pelourinho reel — style as Cândido-Portinari, extend to 90 seconds, and overlay an axé BGM.",
    "I have a 45-second Cusco-Plaza reel — style as Tito-Espinosa Andean, extend to 2 minutes, and add an Andean-charango BGM.",
    "Uploading a 1-minute La-Paz-altiplano Alasitas reel — style as Aymara folk, extend to 3 minutes, and overlay an Aymara-zampoña BGM.",
    "Here's a 30-second Quito-Old-Town reel — style as Oswaldo-Guayasamín, extend to 90 seconds, and add an Ecuadorian-marimba BGM.",
    "I'm sending you a 45-second Bogotá-Cable-Car reel — style as Fernando-Botero, extend to 2 minutes, and overlay a Colombian-cumbia BGM.",
    "Uploading a 1-minute Cartagena-walls reel — style as Magdalena-Vásquez Latin, extend to 3 minutes, and add a cumbia BGM.",
    "Here's a 30-second Havana-Malecón reel — style as Wifredo-Lam, extend to 90 seconds, and overlay a Cuban-son BGM.",
    "I have a 45-second San-Juan-Old-Town reel — style as Rafael-Tufiño, extend to 2 minutes, and add a Puerto-Rican-bomba BGM.",
    "Uploading a 1-minute Santo-Domingo-Zona-Colonial reel — style as Caribbean-tropical illustration, extend to 3 minutes, and overlay a merengue BGM.",
    "Here's a 30-second Port-au-Prince-Iron-Market reel — style as Hector-Hyppolite naïf, extend to 90 seconds, and add a Haitian-rara BGM.",
    "I'm sending you a 45-second Kingston-Trench-Town reel — style as Barrington-Watson, extend to 2 minutes, and overlay a reggae BGM.",
    "Uploading a 1-minute Bridgetown-Garrison reel — style as Caribbean-tropical, extend to 3 minutes, and add a calypso BGM.",
    "Here's a 30-second Oslo-Vigeland-Park reel — style as Edvard-Munch, extend to 90 seconds, and overlay a Norwegian-folk BGM.",
    "I have a 45-second Stockholm-Gamla-Stan reel — style as Anders-Zorn, extend to 2 minutes, and add a Swedish-folk BGM.",
    "Uploading a 1-minute Helsinki-Suomenlinna reel — style as Akseli-Gallen-Kallela, extend to 3 minutes, and overlay a Finnish-folk BGM.",
    "Here's a 30-second Copenhagen-Nyhavn reel — style as Vilhelm-Hammershøi, extend to 90 seconds, and add a Danish-folk BGM.",
    "I'm sending you a 45-second Reykjavik-Hallgrímskirkja reel — style as Erró pop-art, extend to 2 minutes, and overlay an Icelandic-folk BGM.",
    "Uploading a 1-minute Dublin-Trinity reel — style as Jack-Yeats Irish-modernist, extend to 3 minutes, and add an Irish-fiddle BGM.",
    "Here's a 30-second Edinburgh-Royal-Mile reel — style as Henry-Raeburn, extend to 90 seconds, and overlay a Scottish-fiddle BGM.",
    # ── more African cities / landmarks (50) ──
    "Here's a 30-second Cairo-Pyramids reel — style as Egyptian-tomb-painting, extend to 90 seconds, and overlay an Egyptian-oud BGM.",
    "Uploading a 1-minute Alexandria-Library reel — style as Ptolemaic mosaic, extend to 3 minutes, and add a classical-Mediterranean BGM.",
    "I have a 45-second Luxor-Karnak reel — style as Egyptian-hieroglyph illustration, extend to 2 minutes, and overlay an Egyptian-ney BGM.",
    "I'm sending you a 30-second Aswan-Philae reel — style as Nubian fresco, extend to 90 seconds, and add a Nubian-tar BGM.",
    "Uploading a 1-minute Marrakesh-Jemaa reel — style as Moroccan-zellij, extend to 3 minutes, and overlay a Gnawa BGM.",
    "Here's a 30-second Fez-Medina reel — style as Moroccan illuminated-manuscript, extend to 90 seconds, and add a Moroccan-andalusian BGM.",
    "I have a 45-second Casablanca-Hassan-II reel — style as Moroccan-modernist, extend to 2 minutes, and overlay a chaabi BGM.",
    "I'm sending you a 30-second Tunis-Medina reel — style as Tunisian-tile illustration, extend to 90 seconds, and add a Tunisian-malouf BGM.",
    "Uploading a 1-minute Carthage-ruins reel — style as Punic mosaic, extend to 3 minutes, and overlay a Mediterranean-andalusian BGM.",
    "Here's a 30-second Algiers-Casbah reel — style as Algerian-orientalist, extend to 90 seconds, and add a chaabi-algérois BGM.",
    "I have a 45-second Tripoli-Old-City reel — style as Libyan-Berber, extend to 2 minutes, and overlay a Libyan-folk BGM.",
    "I'm sending you a 30-second Khartoum-Confluence reel — style as Sudanese-folk illustration, extend to 90 seconds, and add a Sudanese-tambour BGM.",
    "Uploading a 1-minute Addis-Ababa-Meskel reel — style as Ethiopian-Orthodox-icon, extend to 3 minutes, and overlay an Ethio-jazz BGM.",
    "Here's a 30-second Lalibela-rock-churches reel — style as Ethiopian medieval-icon, extend to 90 seconds, and add an Ethiopian-azmari BGM.",
    "I have a 45-second Aksum-stelae reel — style as Aksumite-Christian fresco, extend to 2 minutes, and overlay a Tigrinya-folk BGM.",
    "I'm sending you a 30-second Asmara-Fiat reel — style as Eritrean Art-Deco, extend to 90 seconds, and add an Eritrean-krar BGM.",
    "Uploading a 1-minute Mogadishu-Lighthouse reel — style as Somali-Italianate, extend to 3 minutes, and overlay a Somali-banaadiri BGM.",
    "Here's a 30-second Nairobi-Skyline reel — style as Kenyan-modernist, extend to 90 seconds, and add a benga BGM.",
    "I have a 45-second Mombasa-Fort-Jesus reel — style as Swahili-coastal illustration, extend to 2 minutes, and overlay a Swahili-taarab BGM.",
    "I'm sending you a 30-second Zanzibar-Stone-Town reel — style as Swahili-doorway illustration, extend to 90 seconds, and add a Zanzibari-taarab BGM.",
    "Uploading a 1-minute Kampala-Hills reel — style as Ugandan-modernist, extend to 3 minutes, and overlay a Ugandan-kadongo-kamu BGM.",
    "Here's a 30-second Kigali-Genocide-Memorial reel — style as Rwandan-imigongo, extend to 90 seconds, and add a Rwandan-inanga BGM.",
    "I have a 45-second Bujumbura-Lake reel — style as Burundian-tropical, extend to 2 minutes, and overlay a Burundian-drum BGM.",
    "I'm sending you a 30-second Dar-es-Salaam-skyline reel — style as Tanzanian-tropical, extend to 90 seconds, and add a bongo-flava BGM.",
    "Uploading a 1-minute Lusaka-skyline reel — style as Zambian-modernist, extend to 3 minutes, and overlay a Zambian-kalindula BGM.",
    "Here's a 30-second Harare-skyline reel — style as Zimbabwean-shona-stone, extend to 90 seconds, and add a Zimbabwean-mbira BGM.",
    "I have a 45-second Bulawayo-Matobo reel — style as Bushman-rock-art, extend to 2 minutes, and overlay a Ndebele-folk BGM.",
    "I'm sending you a 30-second Maputo-skyline reel — style as Mozambican-Portuguese, extend to 90 seconds, and add a marrabenta BGM.",
    "Uploading a 1-minute Luanda-Bay reel — style as Angolan-modernist, extend to 3 minutes, and overlay a kuduro BGM.",
    "Here's a 30-second Windhoek-Christuskirche reel — style as Namibian-German colonial, extend to 90 seconds, and add a Namibian-folk BGM.",
    "I have a 45-second Cape-Town-Table-Mountain reel — style as Pierneef, extend to 2 minutes, and overlay a Cape-jazz BGM.",
    "I'm sending you a 30-second Johannesburg-Apartheid-Museum reel — style as William-Kentridge, extend to 90 seconds, and add a township-jazz BGM.",
    "Uploading a 1-minute Pretoria-Union-Buildings reel — style as Herbert-Baker, extend to 3 minutes, and overlay an Afrikaans-folk BGM.",
    "Here's a 30-second Durban-Beachfront reel — style as Zulu-beadwork illustration, extend to 90 seconds, and add a maskandi BGM.",
    "I have a 45-second Maseru-citadel reel — style as Basotho-blanket pattern, extend to 2 minutes, and overlay a Basotho-folk BGM.",
    "I'm sending you a 30-second Mbabane-skyline reel — style as Swazi-folk illustration, extend to 90 seconds, and add a Swazi-folk BGM.",
    "Uploading a 1-minute Gaborone-skyline reel — style as Botswana-modernist, extend to 3 minutes, and overlay a Botswana-folk BGM.",
    "Here's a 30-second Lagos-Lekki reel — style as Yoruba adire, extend to 90 seconds, and add an Afrobeats BGM.",
    "I have a 45-second Abuja-Aso-Rock reel — style as Nigerian-modernist, extend to 2 minutes, and overlay a juju BGM.",
    "I'm sending you a 30-second Accra-Independence-Arch reel — style as Kwame-Akoto-Bamfo, extend to 90 seconds, and add a highlife BGM.",
    "Uploading a 1-minute Cape-Coast-Castle reel — style as El-Anatsui textile, extend to 3 minutes, and overlay a Ga-folk BGM.",
    "Here's a 30-second Abidjan-Plateau reel — style as Frédéric-Bruly-Bouabré, extend to 90 seconds, and add a coupé-décalé BGM.",
    "I have a 45-second Dakar-Île-de-Gorée reel — style as Senegalese sous-verre, extend to 2 minutes, and overlay an mbalax BGM.",
    "I'm sending you a 30-second Bamako-Niger reel — style as Bògòlanfini mud-cloth, extend to 90 seconds, and add a Wassoulou BGM.",
    "Uploading a 1-minute Ouagadougou-skyline reel — style as Burkinabé-modernist, extend to 3 minutes, and overlay a Mossi-folk BGM.",
    "Here's a 30-second Niamey-Niger-Bridge reel — style as Tuareg-textile illustration, extend to 90 seconds, and add a Tuareg-tindi BGM.",
    "I have a 45-second N'Djamena-skyline reel — style as Chadian-folk, extend to 2 minutes, and overlay a Chadian-folk BGM.",
    "I'm sending you a 30-second Yaoundé-skyline reel — style as Cameroonian-folk, extend to 90 seconds, and add a makossa BGM.",
    "Uploading a 1-minute Libreville-skyline reel — style as Gabonese-modernist, extend to 3 minutes, and overlay a Bwiti-ritual BGM.",
    "Here's a 30-second Kinshasa-skyline reel — style as Cheri-Samba, extend to 90 seconds, and add a soukous BGM.",
    # ── more South-American cities + Latin-American art-style + folk BGM (50) ──
    "I have a 45-second Buenos-Aires-Caminito reel — style as Quinquela-Martín, extend to 2 minutes, and overlay a tango-bandoneón BGM.",
    "I'm sending you a 30-second Buenos-Aires-Recoleta reel — style as Antonio-Berni, extend to 90 seconds, and add an Argentine-folklore BGM.",
    "Uploading a 1-minute Patagonia-glacier reel — style as Roberto-Matta surrealist, extend to 3 minutes, and overlay a Patagonian-folk BGM.",
    "Here's a 30-second Mendoza-vineyard reel — style as Argentinian-folk illustration, extend to 90 seconds, and add a chacarera BGM.",
    "I have a 45-second Salta-Cerro-de-los-Siete-Colores reel — style as Andean-altiplano illustration, extend to 2 minutes, and overlay a coplero-zamba BGM.",
    "I'm sending you a 30-second Ushuaia-port reel — style as Tierra-del-Fuego folk, extend to 90 seconds, and add a Patagonian-folk-2 BGM.",
    "Uploading a 1-minute Iguazu-Falls reel — style as Brazilian-rainforest illustration, extend to 3 minutes, and overlay a samba-de-roda BGM.",
    "Here's a 30-second Rio-de-Janeiro-Pão-de-Açúcar reel — style as Carybé Bahia, extend to 90 seconds, and add a Brazilian-bossa-nova BGM.",
    "I have a 45-second São-Paulo-Avenida-Paulista reel — style as Tarsila-do-Amaral modernist, extend to 2 minutes, and overlay a samba-rock BGM.",
    "I'm sending you a 30-second Salvador-Pelourinho reel — style as Carybé Bahia-2, extend to 90 seconds, and add an axé BGM.",
    "Uploading a 1-minute Brasília-Catedral reel — style as Niemeyer-modernist, extend to 3 minutes, and overlay a tropicália BGM.",
    "Here's a 30-second Recife-Olinda reel — style as Recife-folk, extend to 90 seconds, and add a frevo BGM.",
    "I have a 45-second Manaus-Teatro-Amazonas reel — style as Amazonian-folk illustration, extend to 2 minutes, and overlay a boi-bumbá BGM.",
    "I'm sending you a 30-second Belém-Ver-o-Peso reel — style as Pará-folk illustration, extend to 90 seconds, and add a carimbó BGM.",
    "Uploading a 1-minute Curitiba-Botanical-Garden reel — style as Curitibano-folk, extend to 3 minutes, and overlay a Brazilian-choro BGM.",
    "Here's a 30-second Florianópolis-Lagoa reel — style as Santa-Catarina folk, extend to 90 seconds, and add a Brazilian-fandango BGM.",
    "I have a 45-second Porto-Alegre-Mercado reel — style as Gaucho folk-illustration, extend to 2 minutes, and overlay a vaneira BGM.",
    "I'm sending you a 30-second Foz-do-Iguaçu reel — style as Tropical-Brazilian illustration, extend to 90 seconds, and add a Brazilian-baião BGM.",
    "Uploading a 1-minute Caracas-Avila reel — style as Cruz-Diez kinetic, extend to 3 minutes, and overlay a Venezuelan-joropo BGM.",
    "Here's a 30-second Maracaibo-bridge reel — style as Venezuelan-tropical, extend to 90 seconds, and add a Venezuelan-gaita BGM.",
    "I have a 45-second Mérida-cable-car reel — style as Andean-Venezuelan, extend to 2 minutes, and overlay a Andean-bambuco BGM.",
    "I'm sending you a 30-second Bogotá-Plaza-Bolívar reel — style as Botero-rotund-2, extend to 90 seconds, and add a Colombian-cumbia BGM.",
    "Uploading a 1-minute Cartagena-Walls-Spanish reel — style as Cartagena-tropical, extend to 3 minutes, and overlay a Colombian-vallenato BGM.",
    "Here's a 30-second Cali-salsa-club reel — style as Cali-modernist, extend to 90 seconds, and add a Colombian-salsa BGM.",
    "I have a 45-second Medellín-Comuna-13 reel — style as Botero-Comuna-13, extend to 2 minutes, and overlay a Colombian-reggaeton BGM.",
    "I'm sending you a 30-second Lima-Plaza-Mayor reel — style as Peruvian-vice-regal, extend to 90 seconds, and add a Peruvian-criolla BGM.",
    "Uploading a 1-minute Cusco-Plaza-Armas reel — style as Cusco-school colonial, extend to 3 minutes, and overlay a Andean-pan-flute BGM.",
    "Here's a 30-second Machu-Picchu-vista reel — style as Andean-altiplano illustration-2, extend to 90 seconds, and add a Quechua-flute BGM.",
    "I have a 45-second Arequipa-Plaza reel — style as Arequipa-school, extend to 2 minutes, and overlay a marinera-arequipeña BGM.",
    "I'm sending you a 30-second La-Paz-El-Alto reel — style as Bolivian-aymara folk, extend to 90 seconds, and add a Bolivian-charango BGM.",
    "Uploading a 1-minute Sucre-historic-center reel — style as Bolivian-vice-regal, extend to 3 minutes, and overlay a Bolivian-cueca BGM.",
    "Here's a 30-second Uyuni-salt-flats reel — style as Bolivian-altiplano, extend to 90 seconds, and add an Andean-quena BGM.",
    "I have a 45-second Asunción-historic-center reel — style as Paraguayan-modernist, extend to 2 minutes, and overlay a Paraguayan-polca BGM.",
    "I'm sending you a 30-second Encarnación-promenade reel — style as Paraguayan-folk, extend to 90 seconds, and add a Paraguayan-galopa BGM.",
    "Uploading a 1-minute Santiago-Plaza-Armas reel — style as Roberto-Matta-Chilean, extend to 3 minutes, and overlay a Chilean-cueca BGM.",
    "Here's a 30-second Valparaíso-cerro reel — style as Valparaíso-graffiti, extend to 90 seconds, and add a Chilean-tonada BGM.",
    "I have a 45-second Easter-Island-Anakena reel — style as Rapa-Nui-rongorongo-2, extend to 2 minutes, and overlay a Rapa-Nui-folk BGM.",
    "I'm sending you a 30-second Punta-Arenas-port reel — style as Patagonian-Chilean folk, extend to 90 seconds, and add a Chilean-cueca-magallánica BGM.",
    "Uploading a 1-minute Quito-La-Ronda reel — style as Quito-school colonial, extend to 3 minutes, and overlay an Ecuadorian-pasillo BGM.",
    "Here's a 30-second Cuenca-historic-center reel — style as Cuenca-school, extend to 90 seconds, and add an Ecuadorian-yumbo BGM.",
    "I have a 45-second Guayaquil-Malecón reel — style as Guayaquil-modernist, extend to 2 minutes, and overlay an Ecuadorian-bomba BGM.",
    "I'm sending you a 30-second Galápagos-Bartolomé reel — style as Galápagos-tropical illustration-2, extend to 90 seconds, and add an Ecuadorian-folk BGM.",
    "Uploading a 1-minute Paramaribo-old-center reel — style as Surinamese-Creole illustration, extend to 3 minutes, and overlay a Surinamese-kaseko BGM.",
    "Here's a 30-second Georgetown-Stabroek reel — style as Guyanese-folk, extend to 90 seconds, and add a Guyanese-chutney BGM.",
    "I have a 45-second Cayenne-old-center reel — style as French-Guiana-folk, extend to 2 minutes, and overlay a French-Guianese-zouk BGM.",
    "I'm sending you a 30-second Georgetown-cathedral reel — style as Guyanese-Anglican-folk, extend to 90 seconds, and add a Guyanese-quadrille BGM.",
    "Uploading a 1-minute San-Pedro-Atacama-stargazing reel — style as Atacameño-folk, extend to 3 minutes, and overlay an Atacameño-flute BGM.",
    "Here's a 30-second Chiloé-stilt-houses reel — style as Chilote-folk, extend to 90 seconds, and add a Chilote-cueca BGM.",
    "I have a 45-second Pucón-volcano reel — style as Mapuche-Chilean illustration, extend to 2 minutes, and overlay a Mapuche-trutruka BGM.",
    "I'm sending you a 30-second Bariloche-Cathedral reel — style as Patagonian-Argentinian, extend to 90 seconds, and add a Patagonian-malambo BGM.",
    # ── more North-American cities + American art-style + folk BGM (50) ──
    "Uploading a 1-minute NYC-Brooklyn-Bridge reel — style as Joseph-Stella-Brooklyn-Bridge, extend to 3 minutes, and overlay a NY-jazz-orchestral BGM.",
    "Here's a 30-second NYC-Times-Square reel — style as Stuart-Davis-modernist, extend to 90 seconds, and add a NY-bebop BGM.",
    "I have a 45-second NYC-Central-Park reel — style as William-Glackens-Central-Park, extend to 2 minutes, and overlay a NY-classical BGM.",
    "I'm sending you a 30-second NYC-Apollo-Theater reel — style as Romare-Bearden-Harlem, extend to 90 seconds, and add a Harlem-jazz BGM.",
    "Uploading a 1-minute Boston-Beacon-Hill reel — style as Childe-Hassam-Boston, extend to 3 minutes, and overlay a Boston-classical BGM.",
    "Here's a 30-second Boston-Harvard-Yard reel — style as John-Singer-Sargent-Boston, extend to 90 seconds, and add a New-England-folk BGM.",
    "I have a 45-second Philadelphia-Liberty-Bell reel — style as Thomas-Eakins-Philadelphia, extend to 2 minutes, and overlay a Philadelphia-soul BGM.",
    "I'm sending you a 30-second Washington-DC-Mall reel — style as Edward-Hopper-DC, extend to 90 seconds, and add a DC-go-go BGM.",
    "Uploading a 1-minute Baltimore-Inner-Harbor reel — style as Jacob-Lawrence-Baltimore, extend to 3 minutes, and overlay a Baltimore-club BGM.",
    "Here's a 30-second Pittsburgh-Three-Rivers reel — style as Charles-Sheeler-Pittsburgh, extend to 90 seconds, and add a Pittsburgh-jazz BGM.",
    "I have a 45-second Cleveland-Lake-Erie reel — style as Edward-Hopper-Cleveland, extend to 2 minutes, and overlay a Cleveland-rock BGM.",
    "I'm sending you a 30-second Detroit-Renaissance-Center reel — style as Diego-Rivera-Detroit-Industry-2, extend to 90 seconds, and add a Motown-soul BGM.",
    "Uploading a 1-minute Chicago-Loop reel — style as Edward-Hopper-Chicago-2, extend to 3 minutes, and overlay a Chicago-blues BGM.",
    "Here's a 30-second Chicago-Lake-Michigan reel — style as Aaron-Bohrod-Chicago, extend to 90 seconds, and add a Chicago-house BGM.",
    "I have a 45-second Milwaukee-Lake reel — style as Edward-Steichen-Milwaukee, extend to 2 minutes, and overlay a Milwaukee-polka BGM.",
    "I'm sending you a 30-second Minneapolis-Mississippi reel — style as Edward-Hopper-Minneapolis, extend to 90 seconds, and add a Minneapolis-funk BGM.",
    "Uploading a 1-minute St-Paul-Cathedral reel — style as Caleb-Bingham-river, extend to 3 minutes, and overlay a Minnesota-folk BGM.",
    "Here's a 30-second St-Louis-Gateway-Arch reel — style as Joseph-Jones-St-Louis, extend to 90 seconds, and add a St-Louis-blues BGM.",
    "I have a 45-second Kansas-City-Plaza reel — style as Thomas-Hart-Benton-Missouri, extend to 2 minutes, and overlay a Kansas-City-jazz BGM.",
    "I'm sending you a 30-second New-Orleans-French-Quarter reel — style as Walter-Anderson-Mississippi-Coast, extend to 90 seconds, and add a New-Orleans-jazz BGM.",
    "Uploading a 1-minute Memphis-Beale-Street reel — style as William-Eggleston-Memphis, extend to 3 minutes, and overlay a Memphis-blues BGM.",
    "Here's a 30-second Nashville-Music-Row reel — style as Red-Grooms-Nashville, extend to 90 seconds, and add a Nashville-country BGM.",
    "I have a 45-second Atlanta-Centennial-Park reel — style as Howard-Finster-Atlanta, extend to 2 minutes, and overlay an Atlanta-trap BGM.",
    "I'm sending you a 30-second Charleston-Battery reel — style as Alfred-Hutty-Charleston, extend to 90 seconds, and add a low-country-folk BGM.",
    "Uploading a 1-minute Savannah-Forsyth-Park reel — style as Christopher-Murphy-Savannah, extend to 3 minutes, and overlay a Savannah-folk BGM.",
    "Here's a 30-second Miami-Ocean-Drive reel — style as Romero-Britto-Miami, extend to 90 seconds, and add a Miami-Latin-pop BGM.",
    "I have a 45-second Tampa-Ybor-City reel — style as Tampa-cigar-poster, extend to 2 minutes, and overlay a Tampa-Cuban-son BGM.",
    "I'm sending you a 30-second Orlando-Lake-Eola reel — style as Robert-Indiana-Orlando, extend to 90 seconds, and add an Orlando-Disney-orchestral BGM.",
    "Uploading a 1-minute Houston-Buffalo-Bayou reel — style as Mark-Rothko-Houston-chapel, extend to 3 minutes, and overlay a Houston-blues BGM.",
    "Here's a 30-second Dallas-skyline reel — style as Albert-Bierstadt-Texas, extend to 90 seconds, and add a Dallas-country BGM.",
    "I have a 45-second Austin-Lady-Bird-Lake reel — style as Forrest-Bess-Austin, extend to 2 minutes, and overlay an Austin-indie-rock BGM.",
    "I'm sending you a 30-second San-Antonio-Riverwalk reel — style as Porfirio-Salinas-Texas-Hill-Country, extend to 90 seconds, and add a Tejano-conjunto BGM.",
    "Uploading a 1-minute El-Paso-Franklin-Mountains reel — style as Tom-Lea-El-Paso, extend to 3 minutes, and overlay a Norteño-banda BGM.",
    "Here's a 30-second Phoenix-Camelback reel — style as Maynard-Dixon-Phoenix, extend to 90 seconds, and add a Phoenix-desert-rock BGM.",
    "I have a 45-second Tucson-Saguaro reel — style as Howard-Pyle-Tucson, extend to 2 minutes, and overlay a Tucson-Sonoran-folk BGM.",
    "I'm sending you a 30-second Albuquerque-Sandia reel — style as Georgia-O'Keeffe-Sandia, extend to 90 seconds, and add an Albuquerque-folk BGM.",
    "Uploading a 1-minute Santa-Fe-Plaza reel — style as Georgia-O'Keeffe-Santa-Fe, extend to 3 minutes, and overlay a Santa-Fe-Hispano-folk BGM.",
    "Here's a 30-second Denver-Mile-High reel — style as Vance-Kirkland-Denver, extend to 90 seconds, and add a Denver-folk BGM.",
    "I have a 45-second Salt-Lake-City-Temple reel — style as LeConte-Stewart-Salt-Lake, extend to 2 minutes, and overlay a Mormon-Tabernacle-choir BGM.",
    "I'm sending you a 30-second Boise-Capitol reel — style as Joseph-Sherman-Boise, extend to 90 seconds, and add an Idaho-folk BGM.",
    "Uploading a 1-minute Portland-Pioneer-Square reel — style as Sally-Haley-Portland, extend to 3 minutes, and overlay a Portland-indie-rock BGM.",
    "Here's a 30-second Seattle-Pike-Place reel — style as Mark-Tobey-Seattle, extend to 90 seconds, and add a Seattle-grunge BGM.",
    "I have a 45-second Vancouver-Stanley-Park reel — style as Emily-Carr-Vancouver, extend to 2 minutes, and overlay a Vancouver-coast-folk BGM.",
    "I'm sending you a 30-second SF-Golden-Gate reel — style as Wayne-Thiebaud-SF, extend to 90 seconds, and add a SF-psych-rock BGM.",
    "Uploading a 1-minute Berkeley-Telegraph reel — style as Richard-Diebenkorn-Berkeley, extend to 3 minutes, and overlay a Berkeley-folk-rock BGM.",
    "Here's a 30-second Sacramento-Old-Town reel — style as Wayne-Thiebaud-Sacramento, extend to 90 seconds, and add a Sacramento-country BGM.",
    "I have a 45-second LA-Hollywood-sign reel — style as David-Hockney-LA-pool, extend to 2 minutes, and overlay an LA-hip-hop BGM.",
    "I'm sending you a 30-second LA-Watts-Towers reel — style as Simon-Rodia-Watts, extend to 90 seconds, and add an LA-Chicano-soul BGM.",
    "Uploading a 1-minute San-Diego-Coronado reel — style as Belmonte-de-Llanos-San-Diego, extend to 3 minutes, and overlay a San-Diego-Latin-jazz BGM.",
    "Here's a 30-second Honolulu-Diamond-Head reel — style as Madge-Tennent-Honolulu, extend to 90 seconds, and add a Hawaiian-slack-key BGM.",
    # ── more South-American cities + Latin-American art styles + BGM (50) ──
    "Uploading a 30-second Buenos-Aires-Caminito reel — please style as Quinquela-Martín-La-Boca, extend to 90 seconds, and add a tango-bandoneón BGM.",
    "Here's a 45-second Buenos-Aires-Recoleta reel — style as Berni-Argentine-modernist, extend to 2 minutes, and overlay an Argentine-folklore BGM.",
    "I have a 1-minute Buenos-Aires-Plaza-de-Mayo reel — style as Argentine-mural-realism, extend to 3 minutes, and add an Argentine-rock BGM.",
    "Uploading a 30-second Mendoza-vineyard reel — style as Carlos-Alonso-Mendoza, extend to 90 seconds, and overlay a Cuyo-folk BGM.",
    "Here's a 45-second Bariloche-Patagonia reel — style as Patagonian-watercolor, extend to 2 minutes, and add a Patagonian-acoustic BGM.",
    "I'm sending you a 30-second Ushuaia-Tierra-del-Fuego reel — style as Tierra-del-Fuego-print, extend to 90 seconds, and overlay a Patagonian-shanty BGM.",
    "Uploading a 1-minute Iguazu-Falls-Argentine reel — style as Iguazu-naturalist-plate, extend to 3 minutes, and add a Misiones-chamamé BGM.",
    "Here's a 30-second Salta-Northwest reel — style as Salta-colonial-baroque, extend to 90 seconds, and overlay a zamba-norteña BGM.",
    "I have a 45-second Cordoba-Argentina-Jesuit reel — style as Cordoba-Jesuit-baroque, extend to 2 minutes, and add a cuarteto-cordobés BGM.",
    "Uploading a 30-second Montevideo-Pocitos reel — style as Pedro-Figari-Uruguayan, extend to 90 seconds, and overlay a candombe-uruguayo BGM.",
    "Here's a 45-second Punta-del-Este reel — style as Carlos-Páez-Vilaró-Casapueblo, extend to 2 minutes, and add an Uruguayan-tango BGM.",
    "I'm sending you a 1-minute Asunción-Paraguay reel — style as Olga-Blinder-Paraguayan, extend to 3 minutes, and overlay a Paraguayan-harp BGM.",
    "Uploading a 30-second Santiago-de-Chile-Cerro-San-Cristóbal reel — style as Roberto-Matta-Chilean, extend to 90 seconds, and add a Chilean-nueva-canción BGM.",
    "Here's a 45-second Valparaíso-cerros reel — style as Valparaíso-cerro-mural, extend to 2 minutes, and overlay a Valparaíso-cueca BGM.",
    "I have a 1-minute Atacama-San-Pedro reel — style as Atacama-naturalist-plate-2, extend to 3 minutes, and add an Andean-flute BGM.",
    "Uploading a 30-second Patagonian-Torres-del-Paine reel — style as Torres-del-Paine-naturalist, extend to 90 seconds, and overlay a Patagonian-orchestral BGM.",
    "Here's a 45-second Lima-Miraflores reel — style as Tilsa-Tsuchiya-Peruvian, extend to 2 minutes, and add a Peruvian-vals-2 BGM.",
    "I'm sending you a 1-minute Cuzco-Plaza-de-Armas reel — style as Cuzco-school-baroque, extend to 3 minutes, and overlay an Andean-orchestral BGM.",
    "Uploading a 30-second Machu-Picchu reel — style as Machu-Picchu-naturalist-plate, extend to 90 seconds, and add an Andean-quena BGM.",
    "Here's a 45-second Arequipa-Mistí reel — style as Arequipa-colonial-watercolor, extend to 2 minutes, and overlay a yaraví BGM.",
    "I have a 1-minute La-Paz-Tiwanaku reel — style as Cecilio-Guzmán-Bolivian, extend to 3 minutes, and add an Andean-zampoña BGM.",
    "Uploading a 30-second Salar-de-Uyuni reel — style as Salar-de-Uyuni-naturalist-plate, extend to 90 seconds, and overlay an Aymara-folkloric BGM.",
    "Here's a 45-second Quito-La-Mariscal reel — style as Oswaldo-Guayasamín-Ecuadorian, extend to 2 minutes, and add a pasillo-ecuatoriano BGM.",
    "I'm sending you a 30-second Cuenca-Ecuador-El-Centro reel — style as Cuenca-Ecuador-watercolor, extend to 90 seconds, and overlay an Ecuadorian-bomba BGM.",
    "Uploading a 1-minute Galápagos-Santa-Cruz reel — style as Galápagos-naturalist-plate-2, extend to 3 minutes, and add a Galápagos-acoustic BGM.",
    "Here's a 30-second Bogotá-La-Candelaria reel — style as Fernando-Botero-Bogotá, extend to 90 seconds, and overlay a Colombian-cumbia BGM.",
    "I have a 45-second Cartagena-de-Indias-Walled-City reel — style as Alejandro-Obregón-Caribbean, extend to 2 minutes, and add a Colombian-vallenato BGM.",
    "Uploading a 30-second Medellín-Comuna-13 reel — style as Comuna-13-mural, extend to 90 seconds, and overlay a Colombian-reggaeton BGM.",
    "Here's a 45-second Cali-Salsa-quarter reel — style as Caribbean-Cali-mural, extend to 2 minutes, and add a salsa-caleña BGM.",
    "I'm sending you a 1-minute Caracas-Mt-Avila reel — style as Armando-Reverón-Venezuelan, extend to 3 minutes, and overlay a joropo-llanero BGM.",
    "Uploading a 30-second Caracas-Plaza-Bolívar reel — style as Caracas-modernist, extend to 90 seconds, and add a salsa-caraqueña BGM.",
    "Here's a 45-second Mérida-Andean-Venezuela reel — style as Mérida-Andean-watercolor, extend to 2 minutes, and overlay an Andean-Venezuelan-folk BGM.",
    "I have a 1-minute Roraima-tepui reel — style as tepui-naturalist-plate, extend to 3 minutes, and add a Pemón-tribal-folk BGM.",
    "Uploading a 30-second Manaus-Amazonas-Opera-House reel — style as Manaus-Belle-Époque, extend to 90 seconds, and overlay a samba-amazônica BGM.",
    "Here's a 45-second Belém-Mercado-Ver-o-Peso reel — style as Belém-Marajoara-Indigenous, extend to 2 minutes, and add a carimbó BGM.",
    "I'm sending you a 1-minute Salvador-Pelourinho reel — style as Carybé-Salvador-Bahia, extend to 3 minutes, and overlay an axé-music BGM.",
    "Uploading a 30-second Recife-Olinda reel — style as Cícero-Dias-Recife, extend to 90 seconds, and add a frevo-pernambucano BGM.",
    "Here's a 45-second Rio-Lapa reel — style as Lapa-bohemian-mural, extend to 2 minutes, and overlay a samba-de-roda BGM.",
    "I have a 1-minute Rio-Christ-Redeemer reel — style as Rio-baía-modernist, extend to 3 minutes, and add a bossa-nova-2 BGM.",
    "Uploading a 30-second São-Paulo-Pinacoteca reel — style as Anita-Malfatti-Paulista, extend to 90 seconds, and overlay a samba-paulista-3 BGM.",
    "Here's a 45-second São-Paulo-Avenida-Paulista reel — style as Avenida-Paulista-modernist, extend to 2 minutes, and add a São-Paulo-rock BGM.",
    "I'm sending you a 1-minute Brasília-Plano-Piloto reel — style as Niemeyer-Brasília, extend to 3 minutes, and overlay an MPB-modernist BGM.",
    "Uploading a 30-second Belo-Horizonte-Pampulha reel — style as Pampulha-Niemeyer-watercolor, extend to 90 seconds, and add a sertanejo-mineiro BGM.",
    "Here's a 45-second Curitiba-Rua-XV reel — style as Curitiba-modernist-print, extend to 2 minutes, and overlay a fandango-curitibano BGM.",
    "I have a 1-minute Florianópolis-Lagoa reel — style as Floripa-azorean-watercolor, extend to 3 minutes, and add a fandango-açoriano BGM.",
    "Uploading a 30-second Porto-Alegre-Mercado-Público reel — style as Iberê-Camargo-Gaúcho, extend to 90 seconds, and overlay a Gaúcho-chamamé BGM.",
    "Here's a 45-second Pantanal-wetlands reel — style as Pantanal-naturalist-plate, extend to 2 minutes, and add a Pantanal-rasqueado BGM.",
    "I'm sending you a 30-second Iguassu-Falls-Brazilian reel — style as Iguassu-Brazilian-watercolor, extend to 90 seconds, and overlay a Paraná-chamamé BGM.",
    "Uploading a 1-minute Fortaleza-Iracema reel — style as Aldemir-Martins-Cearense, extend to 3 minutes, and add a forró-cearense BGM.",
    "Here's a 30-second Natal-Ponta-Negra reel — style as Natal-dunes-watercolor, extend to 90 seconds, and overlay a forró-pé-de-serra BGM.",
    # ── more East / South / Southeast Asian cities + Asian art styles + BGM (50) ──
    "Uploading a 30-second Beijing-Forbidden-City reel — please style as Qing-court-painting, extend to 90 seconds, and add a Beijing-Peking-opera BGM.",
    "Here's a 45-second Beijing-Hutong-alley reel — style as Beijing-Hutong-print, extend to 2 minutes, and overlay a Beijing-folk-erhu BGM.",
    "I have a 1-minute Shanghai-Bund-night reel — style as Shanghai-Art-Deco-poster, extend to 3 minutes, and add a Shanghai-shidaiqu-3 BGM.",
    "Uploading a 30-second Shanghai-Yu-Garden reel — style as Shanghai-Jiangnan-painting, extend to 90 seconds, and overlay a Shanghai-pingtan BGM.",
    "Here's a 45-second Hangzhou-West-Lake reel — style as Song-Jiangnan-ink-painting, extend to 2 minutes, and add a Hangzhou-guqin BGM.",
    "I'm sending you a 1-minute Suzhou-Lingering-Garden reel — style as Suzhou-Wu-school-painting, extend to 3 minutes, and overlay a Suzhou-pingtan BGM.",
    "Uploading a 30-second Xi'an-Drum-Tower reel — style as Tang-Chang'an-fresco, extend to 90 seconds, and add a Tang-court-music BGM.",
    "Here's a 45-second Xi'an-Terracotta-Army reel — style as Qin-Han-painted-pottery, extend to 2 minutes, and overlay a Shaanxi-zither BGM.",
    "I have a 1-minute Chengdu-Wenshu-Monastery reel — style as Sichuan-folk-print, extend to 3 minutes, and add a Sichuan-opera-erhu BGM.",
    "Uploading a 30-second Chongqing-Yangtze-river reel — style as Chongqing-mountain-city-print, extend to 90 seconds, and overlay a Sichuan-folk-pipa BGM.",
    "Here's a 45-second Guilin-Li-River reel — style as Guilin-Lingnan-ink, extend to 2 minutes, and add a Guilin-folk-flute BGM.",
    "I'm sending you a 1-minute Yangshuo-karst reel — style as Yangshuo-Lingnan-watercolor, extend to 3 minutes, and overlay a Guangxi-zhuang-folk BGM.",
    "Uploading a 30-second Lhasa-Potala-Palace reel — style as Tibetan-thangka, extend to 90 seconds, and add a Tibetan-dranyen BGM.",
    "Here's a 45-second Lhasa-Jokhang-Temple reel — style as Lhasa-thangka-mural, extend to 2 minutes, and overlay a Tibetan-throat-singing BGM.",
    "I have a 1-minute Tokyo-Asakusa-Sensoji reel — style as Edo-ukiyo-e, extend to 3 minutes, and add a Tokyo-shamisen BGM.",
    "Uploading a 30-second Tokyo-Shibuya-Crossing reel — style as Tokyo-cyberpunk-poster, extend to 90 seconds, and overlay a Tokyo-J-pop BGM.",
    "Here's a 45-second Kyoto-Fushimi-Inari reel — style as Kyoto-Yamato-e, extend to 2 minutes, and add a Kyoto-koto BGM.",
    "I'm sending you a 1-minute Kyoto-Arashiyama-bamboo reel — style as Kyoto-Sumi-e, extend to 3 minutes, and overlay a Kyoto-shakuhachi BGM.",
    "Uploading a 30-second Osaka-Dotonbori reel — style as Osaka-neon-poster, extend to 90 seconds, and add an Osaka-enka BGM.",
    "Here's a 45-second Nara-Todaiji-Daibutsu reel — style as Nara-Tempyo-painting, extend to 2 minutes, and overlay a Nara-gagaku BGM.",
    "I have a 1-minute Hiroshima-Peace-Memorial reel — style as Hiroshima-monoha, extend to 3 minutes, and add a Hiroshima-koto BGM.",
    "Uploading a 30-second Hokkaido-Otaru-canal reel — style as Hokkaido-Ainu-print, extend to 90 seconds, and overlay a Hokkaido-tonkori BGM.",
    "Here's a 45-second Okinawa-Shuri-Castle reel — style as Okinawan-bingata, extend to 2 minutes, and add an Okinawan-sanshin BGM.",
    "I'm sending you a 1-minute Seoul-Gyeongbokgung reel — style as Joseon-Minhwa, extend to 3 minutes, and overlay a Korean-gayageum BGM.",
    "Uploading a 30-second Seoul-Bukchon-Hanok reel — style as Joseon-folk-print, extend to 90 seconds, and add a Korean-pansori BGM.",
    "Here's a 45-second Busan-Gamcheon-Culture-Village reel — style as Gamcheon-mural, extend to 2 minutes, and overlay a Busan-trot BGM.",
    "I have a 1-minute Jeju-Olle-coast reel — style as Jeju-haenyeo-print, extend to 3 minutes, and add a Jeju-folk-haegeum BGM.",
    "Uploading a 30-second Pyongyang-Juche-Tower reel — style as Pyongyang-Socialist-Realism, extend to 90 seconds, and overlay a Pyongyang-orchestral BGM.",
    "Here's a 45-second Hanoi-Hoan-Kiem reel — style as Hanoi-Đông-Hồ-print, extend to 2 minutes, and add a Hanoi-ca-trù BGM.",
    "I'm sending you a 1-minute Ho-Chi-Minh-City-Notre-Dame reel — style as Saigon-modernist, extend to 3 minutes, and overlay a Saigon-cải-lương BGM.",
    "Uploading a 30-second Hue-Imperial-Citadel reel — style as Nguyen-court-painting, extend to 90 seconds, and add a Huế-nhã-nhạc BGM.",
    "Here's a 45-second Hoi-An-Ancient-Town reel — style as Hoi-An-lantern-print, extend to 2 minutes, and overlay a Hoi-An-bài-chòi BGM.",
    "I have a 1-minute Halong-Bay reel — style as Halong-Bay-watercolor, extend to 3 minutes, and add a Vietnamese-đàn-bầu BGM.",
    "Uploading a 30-second Phnom-Penh-Royal-Palace reel — style as Khmer-temple-bas-relief, extend to 90 seconds, and overlay a Khmer-pinpeat-4 BGM.",
    "Here's a 45-second Siem-Reap-Angkor-Wat reel — style as Angkor-Khmer-fresco, extend to 2 minutes, and add a Khmer-mahori BGM.",
    "I'm sending you a 1-minute Luang-Prabang-Mekong reel — style as Lao-folk-print, extend to 3 minutes, and overlay a Lao-khaen-2 BGM.",
    "Uploading a 30-second Vientiane-Patuxai reel — style as Lao-modernist-print, extend to 90 seconds, and add a Lao-mor-lam BGM.",
    "Here's a 45-second Bangkok-Wat-Phra-Kaew reel — style as Thai-Bangkok-mural, extend to 2 minutes, and overlay a Thai-piphat BGM.",
    "I have a 1-minute Chiang-Mai-Old-City reel — style as Lanna-mural, extend to 3 minutes, and add a Chiang-Mai-saw-i BGM.",
    "Uploading a 30-second Sukhothai-Historical-Park reel — style as Sukhothai-Buddha-print, extend to 90 seconds, and overlay a Thai-classical-piphat BGM.",
    "Here's a 45-second Yangon-Shwedagon-Pagoda reel — style as Burmese-pagoda-mural, extend to 2 minutes, and add a Burmese-saung-3 BGM.",
    "I'm sending you a 1-minute Bagan-temple-plain reel — style as Bagan-Buddhist-mural, extend to 3 minutes, and overlay a Burmese-pat-waing BGM.",
    "Uploading a 30-second Inle-Lake-rowers reel — style as Inle-Intha-print, extend to 90 seconds, and add a Burmese-saung-gauk BGM.",
    "Here's a 45-second Singapore-Marina-Bay reel — style as Singapore-modernist, extend to 2 minutes, and overlay a Mandopop-Singaporean BGM.",
    "I have a 1-minute Singapore-Chinatown reel — style as Peranakan-print, extend to 3 minutes, and add a Hokkien-Nanyang BGM.",
    "Uploading a 30-second Kuala-Lumpur-Petronas reel — style as Malay-modernist-print, extend to 90 seconds, and overlay a Malay-dikir-barat BGM.",
    "Here's a 45-second Penang-George-Town-mural reel — style as Penang-mural-print, extend to 2 minutes, and add a Penang-Hokkien BGM.",
    "I'm sending you a 1-minute Manila-Intramuros reel — style as Filipino-mestizo-print, extend to 3 minutes, and overlay a Filipino-rondalla BGM.",
    "Uploading a 30-second Cebu-Magellan's-Cross reel — style as Cebuano-mural-print, extend to 90 seconds, and add a Cebuano-kundiman BGM.",
    "Here's a 45-second Bali-Ubud-rice-terraces reel — style as Balinese-Kamasan, extend to 2 minutes, and overlay a Balinese-gamelan BGM.",
    # ── more European cities + European art-movement styles + BGM (50) ──
    "Uploading a 30-second Paris-Eiffel-Tower-base reel — please style as Caillebotte-Parisian, extend to 90 seconds, and add a Parisian-musette-2 BGM.",
    "Here's a 45-second Paris-Latin-Quarter-rooftop reel — style as Pissarro-Boulevard, extend to 2 minutes, and overlay a Parisian-chanson BGM.",
    "I have a 1-minute Paris-Sacré-Cœur-steps reel — style as Utrillo-Montmartre, extend to 3 minutes, and add a Montmartre-accordion BGM.",
    "Uploading a 30-second Paris-Tuileries-Garden reel — style as Manet-Tuileries, extend to 90 seconds, and overlay a French-cabaret BGM.",
    "Here's a 45-second Paris-Place-Vendôme reel — style as Belle-Époque-poster, extend to 2 minutes, and add a Parisian-violin-cafe BGM.",
    "I'm sending you a 1-minute Versailles-Hall-of-Mirrors reel — style as Lully-Versailles-court, extend to 3 minutes, and overlay a Lully-court-music BGM.",
    "Uploading a 30-second Saint-Tropez-port reel — style as Signac-Saint-Tropez-2, extend to 90 seconds, and add a Côte-d'Azur-jazz BGM.",
    "Here's a 45-second Côte-d'Azur-Nice-promenade reel — style as Matisse-Nice-2, extend to 2 minutes, and overlay a Riviera-cabaret BGM.",
    "I have a 1-minute Avignon-Pont-d'Avignon reel — style as Provençal-watercolor-2, extend to 3 minutes, and add a Provençal-flûteau-and-tabor BGM.",
    "Uploading a 30-second London-Tower-Bridge reel — style as Whistler-Thames-nocturne, extend to 90 seconds, and overlay a Royal-Philharmonic-strings BGM.",
    "Here's a 45-second London-Westminster-Abbey reel — style as Constable-Westminster, extend to 2 minutes, and add a Royal-Anthem-orchestral BGM.",
    "I'm sending you a 1-minute London-British-Museum-Great-Court reel — style as Hogarth-British-Museum, extend to 3 minutes, and overlay a Vaughan-Williams BGM.",
    "Uploading a 30-second London-South-Bank-Thames reel — style as Frank-Auerbach-South-Bank, extend to 90 seconds, and add a London-grime-instrumental-2 BGM.",
    "Here's a 45-second Edinburgh-Royal-Mile reel — style as Scottish-Romantic-watercolor-2, extend to 2 minutes, and overlay a Scottish-bagpipe BGM.",
    "I have a 1-minute Glasgow-Mackintosh-school reel — style as Glasgow-Boys-Scottish-modern, extend to 3 minutes, and add a Glasgow-folk-fiddle BGM.",
    "Uploading a 30-second Dublin-Trinity-College reel — style as Irish-Georgian-print, extend to 90 seconds, and overlay an Irish-traditional-fiddle BGM.",
    "Here's a 45-second Belfast-Titanic-Quarter reel — style as Belfast-shipyard-modernist, extend to 2 minutes, and add a Belfast-folk-uilleann-pipes BGM.",
    "I'm sending you a 1-minute Berlin-Brandenburg-Gate reel — style as German-Expressionism-Kirchner, extend to 3 minutes, and overlay a Berlin-Weimar-cabaret BGM.",
    "Uploading a 30-second Berlin-Spree-river reel — style as Berlin-Bauhaus, extend to 90 seconds, and add a Berlin-techno-instrumental BGM.",
    "Here's a 45-second Munich-Marienplatz reel — style as Munich-Blue-Rider-Kandinsky, extend to 2 minutes, and overlay a Bavarian-Schuhplattler BGM.",
    "I have a 1-minute Hamburg-Speicherstadt reel — style as Hamburg-Sturm-Expressionism, extend to 3 minutes, and add a Hanseatic-trumpet BGM.",
    "Uploading a 30-second Cologne-Cathedral reel — style as Rhenish-Gothic-stained-glass, extend to 90 seconds, and overlay a Cologne-Carnival-Stunksitzung BGM.",
    "Here's a 45-second Dresden-Frauenkirche reel — style as Saxon-Baroque-painting, extend to 2 minutes, and add a Dresden-Staatskapelle-strings BGM.",
    "I'm sending you a 1-minute Vienna-Schönbrunn reel — style as Klimt-Vienna-Secession-2, extend to 3 minutes, and overlay a Strauss-Vienna-waltz BGM.",
    "Uploading a 30-second Vienna-Stephansdom reel — style as Wiener-Werkstätte, extend to 90 seconds, and add a Schubert-Lieder BGM.",
    "Here's a 45-second Salzburg-Old-Town reel — style as Salzburg-Romantic, extend to 2 minutes, and overlay a Mozart-Salzburg-piano BGM.",
    "I have a 1-minute Prague-Charles-Bridge reel — style as Czech-Cubism, extend to 3 minutes, and add a Prague-Smetana-Vltava BGM.",
    "Uploading a 30-second Krakow-Wawel-Castle reel — style as Polish-Symbolism-Wyspianski, extend to 90 seconds, and overlay a Polish-Chopin-piano BGM.",
    "Here's a 45-second Warsaw-Old-Town reel — style as Polish-modernist, extend to 2 minutes, and add a Polish-folk-Mazurka BGM.",
    "I'm sending you a 1-minute Budapest-Parliament reel — style as Hungarian-Sezession-Lechner, extend to 3 minutes, and overlay a Hungarian-Liszt-Hungarian-Rhapsody BGM.",
    "Uploading a 30-second Bratislava-Old-Town reel — style as Slovak-modernist, extend to 90 seconds, and add a Slovak-fujara-folk BGM.",
    "Here's a 45-second Ljubljana-Triple-Bridge reel — style as Slovene-Plečnik-modernist, extend to 2 minutes, and overlay a Slovene-folk-violin BGM.",
    "I have a 1-minute Zagreb-Upper-Town reel — style as Croatian-Naïve-painting, extend to 3 minutes, and add a Croatian-tamburica BGM.",
    "Uploading a 30-second Belgrade-Kalemegdan-fortress reel — style as Serbian-Naive-Sumadija, extend to 90 seconds, and overlay a Serbian-frula-folk BGM.",
    "Here's a 45-second Sofia-Alexander-Nevsky reel — style as Bulgarian-Orthodox-icon, extend to 2 minutes, and add a Bulgarian-mystery-of-Bulgarian-voices BGM.",
    "I'm sending you a 1-minute Bucharest-Old-Town reel — style as Romanian-Brâncoveanu, extend to 3 minutes, and overlay a Romanian-Bartók-violin BGM.",
    "Uploading a 30-second Tirana-Skanderbeg-Square reel — style as Albanian-Socialist-Realism, extend to 90 seconds, and add an Albanian-iso-polyphony BGM.",
    "Here's a 45-second Athens-Acropolis reel — style as Greek-Byzantine-mosaic, extend to 2 minutes, and overlay a Greek-bouzouki BGM.",
    "I have a 1-minute Thessaloniki-White-Tower reel — style as Greek-Macedonian-print, extend to 3 minutes, and add a Greek-rebetiko BGM.",
    "Uploading a 30-second Madrid-Plaza-Mayor reel — style as Spanish-Goya-Disasters, extend to 90 seconds, and overlay a Spanish-flamenco-2 BGM.",
    "Here's a 45-second Barcelona-Sagrada-Família reel — style as Catalan-Gaudí-Modernisme, extend to 2 minutes, and add a Catalan-sardana BGM.",
    "I'm sending you a 1-minute Seville-Plaza-de-España reel — style as Andalusian-Velázquez-bodegón, extend to 3 minutes, and overlay an Andalusian-flamenco-3 BGM.",
    "Uploading a 30-second Granada-Alhambra reel — style as Moorish-watercolor, extend to 90 seconds, and add a Granada-zambra-flamenco BGM.",
    "Here's a 45-second Bilbao-Guggenheim reel — style as Basque-modernist, extend to 2 minutes, and overlay a Basque-trikitixa BGM.",
    "I have a 1-minute Lisbon-Belém-Tower reel — style as Portuguese-azulejo-pattern, extend to 3 minutes, and add a Portuguese-fado-2 BGM.",
    "Uploading a 30-second Porto-Ribeira reel — style as Portuguese-modernist-Souza-Cardoso, extend to 90 seconds, and overlay a Porto-fado-2 BGM.",
    "Here's a 45-second Florence-Duomo reel — style as Italian-Renaissance-fresco, extend to 2 minutes, and add a Florentine-Renaissance-lute BGM.",
    "I'm sending you a 1-minute Venice-San-Marco reel — style as Tintoretto-Venice, extend to 3 minutes, and overlay a Vivaldi-Venetian-strings BGM.",
    "Uploading a 30-second Rome-Pantheon reel — style as Italian-Baroque-Caravaggio, extend to 90 seconds, and add a Roman-mandolin BGM.",
    "Here's a 45-second Naples-Spaccanapoli reel — style as Neapolitan-Caravaggism, extend to 2 minutes, and overlay a Neapolitan-tarantella-2 BGM.",
    # ── more African landscape + African art + African BGM (50) ──
    "I have a 1-minute Cape-Town-Table-Mountain reel — style as Ndebele-pattern, extend to 3 minutes, and add a Cape-Town-Cape-jazz BGM.",
    "Uploading a 30-second Johannesburg-Hillbrow-Tower reel — style as Sophiatown-pop-art, extend to 90 seconds, and overlay a Johannesburg-mbaqanga BGM.",
    "Here's a 45-second Soweto-Vilakazi-Street reel — style as Soweto-mural, extend to 2 minutes, and add a Soweto-kwaito BGM.",
    "I'm sending you a 1-minute Durban-Beachfront reel — style as Zulu-beadwork, extend to 3 minutes, and overlay a Durban-maskandi BGM.",
    "Uploading a 30-second Pretoria-Voortrekker-Monument reel — style as Afrikaner-monument-print, extend to 90 seconds, and add a Pretoria-boeremusiek BGM.",
    "Here's a 45-second Bloemfontein-Naval-Hill reel — style as Free-State-print, extend to 2 minutes, and overlay a Free-State-vastrap BGM.",
    "I have a 1-minute Maputo-Praça-da-Independência reel — style as Mozambican-tinga-tinga, extend to 3 minutes, and add a Maputo-marrabenta BGM.",
    "Uploading a 30-second Beira-Pungwe-River reel — style as Mozambican-makonde-carving, extend to 90 seconds, and overlay a Mozambican-timbila BGM.",
    "Here's a 45-second Harare-Africa-Unity-Square reel — style as Zimbabwean-stone-sculpture, extend to 2 minutes, and add a Zimbabwean-mbira BGM.",
    "I'm sending you a 1-minute Victoria-Falls-Mosi-oa-Tunya reel — style as Lozi-basket-weave, extend to 3 minutes, and overlay a Zambian-kalindula BGM.",
    "Uploading a 30-second Lusaka-Cairo-Road reel — style as Bemba-mural, extend to 90 seconds, and add a Lusaka-Zamrock BGM.",
    "Here's a 45-second Lilongwe-Old-Town reel — style as Malawian-Chiwoda, extend to 2 minutes, and overlay a Malawian-mganda BGM.",
    "I have a 1-minute Zanzibar-Stone-Town reel — style as Swahili-zellige, extend to 3 minutes, and add a Zanzibar-taarab BGM.",
    "Uploading a 30-second Dar-es-Salaam-Kivukoni-Front reel — style as Tinga-Tinga-painting, extend to 90 seconds, and overlay a Tanzanian-bongo-flava BGM.",
    "Here's a 45-second Arusha-Mount-Meru reel — style as Maasai-shuka-pattern, extend to 2 minutes, and add a Maasai-adumu BGM.",
    "I'm sending you a 1-minute Nairobi-Uhuru-Park reel — style as Kikuyu-print, extend to 3 minutes, and overlay a Nairobi-Benga BGM.",
    "Uploading a 30-second Mombasa-Fort-Jesus reel — style as Mijikenda-print, extend to 90 seconds, and add a Mombasa-Mwambao-taarab BGM.",
    "Here's a 45-second Kampala-Independence-Monument reel — style as Buganda-bark-cloth, extend to 2 minutes, and overlay a Kampala-kadongo-kamu BGM.",
    "I have a 1-minute Kigali-Kigali-Genocide-Memorial reel — style as Imigongo-cow-dung-art, extend to 3 minutes, and add a Rwandan-intore BGM.",
    "Uploading a 30-second Bujumbura-Lake-Tanganyika reel — style as Burundian-fabric, extend to 90 seconds, and overlay a Burundi-drum-ensemble BGM.",
    "Here's a 45-second Addis-Ababa-Meskel-Square reel — style as Ethiopian-Orthodox-icon, extend to 2 minutes, and add a Ethiopian-Ethio-jazz BGM.",
    "I'm sending you a 1-minute Lalibela-Bete-Giyorgis reel — style as Lalibela-rock-hewn-icon, extend to 3 minutes, and overlay an Ethiopian-Bati-azmari BGM.",
    "Uploading a 30-second Asmara-Fiat-Tagliero reel — style as Eritrean-modernist, extend to 90 seconds, and add an Eritrean-tigrinya-tunes BGM.",
    "Here's a 45-second Khartoum-confluence-of-Niles reel — style as Sudanese-jellabiya-pattern, extend to 2 minutes, and overlay a Sudanese-haqibah BGM.",
    "I have a 1-minute Cairo-Khan-el-Khalili reel — style as Mamluk-arabesque, extend to 3 minutes, and add an Egyptian-tarab BGM.",
    "Uploading a 30-second Luxor-Karnak-Temple reel — style as ancient-Egyptian-hieroglyph, extend to 90 seconds, and overlay an Egyptian-Mizmar BGM.",
    "Here's a 45-second Marrakech-Jemaa-el-Fna reel — style as Moroccan-zellige-pattern, extend to 2 minutes, and add a Marrakech-Gnawa BGM.",
    "I'm sending you a 1-minute Fes-Bou-Inania-Madrasa reel — style as Marinid-zellige, extend to 3 minutes, and overlay a Fes-Andalusian-classical BGM.",
    "Uploading a 30-second Casablanca-Hassan-II-Mosque reel — style as Moroccan-Atlasica-zellige, extend to 90 seconds, and add a Casablanca-chaabi BGM.",
    "Here's a 45-second Algiers-Casbah reel — style as Algerian-Casbah-print, extend to 2 minutes, and overlay an Algerian-Rai BGM.",
    "I have a 1-minute Tunis-Sidi-Bou-Said reel — style as Tunisian-blue-and-white-print, extend to 3 minutes, and add a Tunisian-Malouf BGM.",
    "Uploading a 30-second Tripoli-Marcus-Aurelius-Arch reel — style as Libyan-Berber-pattern, extend to 90 seconds, and overlay a Libyan-Maalouf BGM.",
    "Here's a 45-second Dakar-Île-de-Gorée reel — style as Senegalese-glass-painting, extend to 2 minutes, and add a Dakar-mbalax BGM.",
    "I'm sending you a 1-minute Bamako-Niger-River reel — style as Bambara-Bògòlanfini, extend to 3 minutes, and overlay a Mali-Wassoulou BGM.",
    "Uploading a 30-second Timbuktu-Djinguereber-Mosque reel — style as Tuareg-tifinagh-pattern, extend to 90 seconds, and add a Tuareg-Tinariwen BGM.",
    "Here's a 45-second Ouagadougou-Place-de-la-Nation reel — style as Burkinabé-Bogolan, extend to 2 minutes, and overlay a Burkinabé-balafon BGM.",
    "I have a 1-minute Niamey-Niger-River reel — style as Hausa-pattern, extend to 3 minutes, and add a Niger-Hausa-fuji BGM.",
    "Uploading a 30-second N'Djamena-Avenue-Charles-de-Gaulle reel — style as Sara-mask-print, extend to 90 seconds, and overlay a Chadian-sai BGM.",
    "Here's a 45-second Lagos-Lekki-Beach reel — style as Yoruba-Adire, extend to 2 minutes, and add a Lagos-Afrobeats BGM.",
    "I'm sending you a 1-minute Ibadan-Cocoa-House reel — style as Yoruba-Aso-Oke, extend to 3 minutes, and overlay an Ibadan-Apala BGM.",
    "Uploading a 30-second Kano-Emir's-Palace reel — style as Hausa-Wall-tracing, extend to 90 seconds, and add a Kano-Hausa-Goge BGM.",
    "Here's a 45-second Accra-Independence-Square reel — style as Akan-Adinkra-pattern, extend to 2 minutes, and overlay a Ghanaian-Highlife BGM.",
    "I have a 1-minute Kumasi-Manhyia-Palace reel — style as Ashanti-Kente, extend to 3 minutes, and add an Ashanti-fontomfrom BGM.",
    "Uploading a 30-second Cotonou-Place-de-l'Etoile-Rouge reel — style as Beninese-Vodun-print, extend to 90 seconds, and overlay a Cotonou-Tchink-system BGM.",
    "Here's a 45-second Lomé-Independence-Monument reel — style as Togolese-Ewe-Kente, extend to 2 minutes, and add a Togolese-Agbadja BGM.",
    "I'm sending you a 1-minute Abidjan-Cocody-Lagoon reel — style as Baoulé-mask-print, extend to 3 minutes, and overlay an Ivorian-Coupé-Décalé BGM.",
    "Uploading a 30-second Dakar-Almadies-Pointe reel — style as Wolof-glass-painting, extend to 90 seconds, and add a Senegalese-Sabar BGM.",
    "Here's a 45-second Conakry-Avenue-de-la-République reel — style as Susu-Bògòlan, extend to 2 minutes, and overlay a Guinean-griot-kora BGM.",
    "I have a 1-minute Freetown-Cotton-Tree reel — style as Mende-Sande-society-print, extend to 3 minutes, and add a Sierra-Leone-palm-wine-music BGM.",
    "Uploading a 30-second Monrovia-Ducor-Hotel reel — style as Liberian-Mandingo-print, extend to 90 seconds, and overlay a Liberian-Hipco BGM.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
