"""x15 vid_music_ambience SFT short briefs.

Chain: IntakeVideo → Music → Ambience → AudioMix → Compositor.
Trigger: user uploads video + asks for BOTH BGM AND ambient layer.
NO subtitles, NO style.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 1-minute coastal drone clip — please add a calming-piano BGM and ocean-wave ambience.",
    "Here's a 2-minute autumn-forest hike — overlay a folk-fiddle BGM and forest ambience (bird calls, leaf rustle).",
    "I have a 90-second campfire reel — please add an acoustic-guitar BGM and crackling-fire ambience.",
    "Uploading a 45-second farmer's-market visit — overlay a folk-banjo BGM and crowd-chatter ambience.",
    "Here's a 1-minute desert sunset — please add an oud BGM and desert-wind ambience.",
    "I'm sending you a 2-minute jungle-trek video — overlay a tribal-drum BGM and rainforest ambience.",
    "Uploading a 90-second city-rain reel — please add a smooth-jazz BGM and urban-rain ambience.",
    "Here's a 30-second beach barbecue — overlay a beach-rock BGM and ocean-and-grill ambience.",
    "I have a 1-minute mountain-summit drone shot — please add cinematic-orchestral BGM and high-altitude wind ambience.",
    "Uploading a 2-minute scuba-diving reel — overlay an ambient-pad BGM and underwater-bubble ambience.",
    "Here's a 45-second snow-covered village reel — please add a Christmas-piano BGM and winter-wind ambience.",
    "I'm sending you a 90-second fishing-boat clip — overlay a maritime-folk BGM and harbor ambience.",
    "Uploading a 1-minute Tokyo-night-street reel — please add a J-pop BGM and city-night ambience.",
    "Here's a 2-minute Italian-piazza walk — overlay a tarantella BGM and Mediterranean-piazza ambience.",
    "I have a 30-second meadow-picnic clip — please add a pastoral-flute BGM and meadow-bee ambience.",
    "Uploading a 90-second Bali-rice-paddy reel — overlay a gamelan BGM and rice-paddy ambience (frogs, water).",
    "Here's a 1-minute Norwegian-fjord reel — please add a Nordic-strings BGM and fjord ambience (wind, waves).",
    "I'm sending you a 45-second Sahara-camel-trek reel — overlay an Arabic-oud BGM and desert-wind ambience.",
    "Uploading a 2-minute alpine-cable-car ride — please add a classical-strings BGM and high-altitude wind ambience.",
    "Here's a 1-minute Yellowstone-geyser reel — overlay an ambient-pad BGM and steam-and-distant-bison ambience.",
    "I have a 90-second Provence-lavender field — please add a French-musette BGM and meadow-bee ambience.",
    "Uploading a 30-second cherry-blossom-park reel — overlay a koto BGM and breeze-and-distant-temple-bell ambience.",
    "Here's a 2-minute hot-spring-onsen reel — please add a shakuhachi BGM and steam-and-water ambience.",
    "I'm sending you a 1-minute Bedouin-desert-camp reel — overlay a Bedouin-rebab BGM and desert-night-cricket ambience.",
    "Uploading a 45-second Andean-mountain reel — please add an Andean-pan-flute BGM and high-altitude wind ambience.",
    "Here's a 90-second Patagonian-glacier reel — overlay an icy-ambient BGM and glacier-wind ambience.",
    "I have a 1-minute Alaskan-fishing-village reel — please add a maritime-folk BGM and harbor-and-gull ambience.",
    "Uploading a 2-minute Arctic-aurora reel — overlay an ambient-synth BGM and Arctic-wind ambience.",
    "Here's a 30-second Galápagos-tortoise close-up — please add a meditative-flute BGM and tropical-bird ambience.",
    "I'm sending you a 45-second Amazon-canopy reel — overlay a rainforest-flute BGM and rainforest ambience.",
    "Uploading a 1-minute African-savanna reel — please add an African-marimba BGM and savanna-cicada ambience.",
    "Here's a 90-second Kenyan-Maasai-village reel — overlay an African-djembe BGM and Maasai-cattle ambience.",
    "I have a 2-minute Indian-temple reel — please add an Indian-sitar BGM and temple-bell-and-drips ambience.",
    "Uploading a 30-second Tibetan-monastery reel — overlay a Tibetan-singing-bowl BGM and monastery-wind ambience.",
    "Here's a 1-minute Mongolian-steppe reel — please add a Mongolian-throat-singing BGM and steppe-wind ambience.",
    "I'm sending you a 45-second Bhutanese-prayer-flag reel — overlay a Bhutanese-flute BGM and high-altitude-wind ambience.",
    "Uploading a 2-minute Vietnamese-fishing-village reel — please add a Vietnamese-dan-bau BGM and harbor ambience.",
    "Here's a 90-second Cambodian-Angkor-Wat reel — overlay a Khmer-flute BGM and tropical-cicada ambience.",
    "I have a 1-minute Thai-floating-market reel — please add a Thai-percussion BGM and market-chatter ambience.",
    "Uploading a 30-second Lao-Mekong-River reel — overlay a Lao-flute BGM and river-and-bird ambience.",
    "Here's a 2-minute Burmese-pagoda reel — please add a Burmese-saung BGM and pagoda-bell ambience.",
    "I'm sending you a 45-second Nepali-mountain-trek reel — overlay a Nepali-bansuri BGM and high-altitude wind ambience.",
    "Uploading a 1-minute Bhutanese-monastery reel — please add a Bhutanese-flute BGM and monastery-bell ambience.",
    "Here's a 90-second Sri-Lankan-tea-plantation reel — overlay a Sri-Lankan-flute BGM and bird-and-leaf ambience.",
    "I have a 2-minute Maldives-snorkel reel — please add a tropical-steel-drum BGM and underwater-ambience.",
    "Uploading a 30-second Polynesian-canoe reel — overlay a Polynesian-drum BGM and lapping-ocean ambience.",
    "Here's a 1-minute New-Zealand-sheep-station reel — please add a Maori-taonga-pūoro BGM and meadow-and-bird ambience.",
    "I'm sending you a 45-second Australian-outback reel — overlay an Aboriginal-didgeridoo BGM and outback-wind ambience.",
    "Uploading a 2-minute Japanese-rice-paddy reel — please add a koto BGM and rice-paddy-frog ambience.",
    "Here's a 90-second Korean-temple reel — overlay a Korean-haegeum BGM and temple-bell-and-wind ambience.",
    "I have a 1-minute Russian-Siberian-taiga reel — please add a balalaika BGM and taiga-wind-and-bird ambience.",
    "Uploading a 30-second Greek-island-village reel — overlay a Greek-bouzouki BGM and Aegean-wave ambience.",
    "Here's a 2-minute Spanish-Andalusia-vineyard reel — please add a Spanish-flamenco-guitar BGM and vineyard-cicada ambience.",
    "I'm sending you a 45-second Italian-Tuscan-vineyard reel — overlay an Italian-mandolin BGM and Tuscan-cicada ambience.",
    "Uploading a 1-minute French-Provence-lavender reel — please add a French-musette-accordion BGM and Provence-bee ambience.",
    "Here's a 90-second Portuguese-fishing-village reel — overlay a Portuguese-fado-guitar BGM and harbor-gull ambience.",
    "I have a 2-minute Dutch-canal reel — please add a Dutch-folk-accordion BGM and canal-water ambience.",
    "Uploading a 30-second German-Bavarian-Alps reel — overlay a Bavarian-zither BGM and alpine-cowbell ambience.",
    "Here's a 1-minute Czech-Bohemian-village reel — please add a Czech-folk-fiddle BGM and village-rooster ambience.",
    "I'm sending you a 45-second Polish-Tatra-mountain reel — overlay a Polish-folk-violin BGM and mountain-wind ambience.",
    "Uploading a 2-minute Hungarian-puszta-plain reel — please add a Hungarian-violin BGM and plain-wind-and-distant-horse ambience.",
    "Here's a 90-second Romanian-Carpathian-village reel — overlay a Romanian-fiddle BGM and village-rooster ambience.",
    "I have a 1-minute Croatian-coastal-village reel — please add a Croatian-klapa-vocals BGM and coastal-wave ambience.",
    "Uploading a 30-second Slovenian-Lake-Bled reel — overlay a Slovenian-folk-accordion BGM and lake-water ambience.",
    "Here's a 2-minute Finnish-lakeside-cottage reel — please add a Finnish-folk-fiddle BGM and lake-loon ambience.",
    "I'm sending you a 45-second Estonian-old-town reel — overlay an Estonian-folk BGM and cobblestone-footstep ambience.",
    # ── more upload + BGM + ambience requests (50) ────────────────────────
    "Uploading a 1-minute clip of a moonlit beach hike — please add an ambient-pad BGM and ocean-wave ambient.",
    "Here's a 45-second clip of a Sunday-morning farmer's market — overlay a folksy-banjo BGM and market-chatter ambient.",
    "I have a 2-minute clip of a foggy-morning coffee shop — please add a smooth-jazz BGM and espresso-machine ambient.",
    "Uploading a 90-second clip of a campfire roast at dusk — overlay an Americana-folk BGM and crackling-fire ambient.",
    "Here's a 30-second clip of a ranch-house porch swing — please add a country-folk BGM and prairie-cricket ambient.",
    "I'm sending you a 1-minute clip of a beach sunset bonfire — overlay a chill-acoustic BGM and ocean-wave-and-fire-crackle ambient.",
    "Uploading a 2-minute clip of a redwood forest hike — please add a Celtic-flute BGM and forest-bird ambient.",
    "Here's a 45-second clip of a snow-covered village stroll — overlay a Christmas-piano BGM and winter-wind ambient.",
    "I have a 90-second clip of a desert sunrise hike — please add an oud-and-percussion BGM and desert-wind ambient.",
    "Uploading a 30-second clip of an alpine meadow picnic — overlay a Bavarian-zither BGM and meadow-bee ambient.",
    "Here's a 1-minute clip of a hot-air balloon landing — please add a soaring-orchestral BGM and balloon-burner ambient.",
    "I'm sending you a 2-minute clip of a vineyard harvest at sunset — overlay an Italian-mandolin BGM and vineyard-cicada ambient.",
    "Uploading a 45-second clip of a tropical-island lagoon snorkel — please add a tropical-marimba BGM and lagoon-water ambient.",
    "Here's a 90-second clip of an Arctic-aurora time-lapse — overlay an ambient-pad BGM and Arctic-wind ambient.",
    "I have a 30-second clip of a cherry-blossom park reel — please add a soft-koto BGM and park-bird ambient.",
    "Uploading a 1-minute clip of a desert dune dawn — overlay a Bedouin-rebab BGM and desert-cricket ambient.",
    "Here's a 2-minute clip of a Mediterranean fishing-village morning — please add a Greek-bouzouki BGM and harbor-gull ambient.",
    "I'm sending you a 45-second clip of a Cornish cliff hike — overlay a Celtic-fiddle BGM and sea-cliff ambient.",
    "Uploading a 90-second clip of a Welsh-coastal tide-pool — please add a Welsh-folk BGM and tide-pool ambient.",
    "Here's a 30-second clip of an Irish-cottage interior — overlay an Irish-fiddle BGM and peat-fire ambient.",
    "I have a 1-minute clip of a Scottish-Highland trek — please add a bagpipe BGM and moorland-wind ambient.",
    "Uploading a 2-minute clip of a Manx tiger-bay village — overlay a Manx-folk BGM and harbor-gull ambient.",
    "Here's a 45-second clip of a Cornish-tin-mine ruin walk — please add a folk-fiddle BGM and ruin-wind ambient.",
    "I'm sending you a 90-second clip of a Faroese-cliff hike — overlay a Faroese-folk BGM and sea-cliff ambient.",
    "Uploading a 30-second clip of an Icelandic-volcano hike — please add an ambient-pad BGM and volcano-vent ambient.",
    "Here's a 1-minute clip of a Greenlandic-fjord kayak — overlay an Inuit-throat-singing BGM and fjord-water ambient.",
    "I have a 2-minute clip of a Yupik-dog-sled run — please add a Yupik-drum BGM and snow-crunch ambient.",
    "Uploading a 45-second clip of a Cree-grandmother fire-stories — overlay a Plains-Cree-flute BGM and fire-crackle ambient.",
    "Here's a 90-second clip of a Inuktitut-grandmother sewing — please add an Inuit-throat-singing BGM and sod-hut ambient.",
    "I'm sending you a 30-second clip of an Ojibwe-rice harvest — overlay an Ojibwe-flute BGM and lake-water ambient.",
    "Uploading a 1-minute clip of a Lakota-grandmother braiding — please add a Lakota-flute BGM and prairie-wind ambient.",
    "Here's a 2-minute clip of a Navajo-silversmith workshop — overlay a Navajo-flute BGM and hogan-fire ambient.",
    "I have a 45-second clip of an Apache-desert-trail walk — please add an Apache-flute BGM and desert-cricket ambient.",
    "Uploading a 90-second clip of a Cherokee-loom afternoon — overlay a Cherokee-flute BGM and mountain-stream ambient.",
    "Here's a 30-second clip of a Hopi-mesa-top farm — please add a Hopi-rattle BGM and mesa-wind ambient.",
    "I'm sending you a 1-minute clip of a Zuni-courtyard pottery — overlay a Pueblo-drum BGM and pueblo-quiet ambient.",
    "Uploading a 2-minute clip of a Mapuche-loom afternoon — please add a Mapuche-trutruka BGM and Andean-wind ambient.",
    "Here's a 45-second clip of an Aymara-llama-trail morning — overlay an Andean-pan-flute BGM and altiplano-wind ambient.",
    "I have a 90-second clip of a Quechua-market morning — please add an Andean-charango BGM and market-chatter ambient.",
    "Uploading a 30-second clip of a Garifuna-beach drumming — overlay a Garifuna-drum BGM and beach-wave ambient.",
    "Here's a 1-minute clip of a Haitian-Kreyòl bakery morning — please add a Haitian-rara BGM and bakery-courtyard ambient.",
    "I'm sending you a 2-minute clip of a Jamaican-Patois-fishing morning — overlay a Jamaican-mento BGM and beach-wave ambient.",
    "Uploading a 45-second clip of a Trinidadian-carnival parade — please add a steel-pan BGM and parade-crowd ambient.",
    "Here's a 90-second clip of a Bahamian-junkanoo drumming — overlay a goombay-drum BGM and parade-crowd ambient.",
    "I have a 30-second clip of a Saint-Lucian-beach festival — please add a Saint-Lucian-folk BGM and beach-festival ambient.",
    "Uploading a 1-minute clip of a Curaçaoan-tula-singer porch — overlay a tambú BGM and harbor-gull ambient.",
    "Here's a 2-minute clip of a Bonaire-flamingo-watch afternoon — please add a Caribbean-folk BGM and lagoon ambient.",
    "I'm sending you a 45-second clip of a Tongan-shore fisherman — overlay a Tongan-lali BGM and tropical-shore ambient.",
    "Uploading a 90-second clip of a Samoan-grandmother-weaving — please add a Samoan-pate BGM and weaving-courtyard ambient.",
    "Here's a 30-second clip of a Maori-marae-arrival ceremony — overlay a taonga-pūoro BGM and marae ambient.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
