"""x15 highlight_music SFT.
Chain: IntakeVideo → VideoAnalysis → Highlight → Music → AudioMix → Compositor.
Trigger: long video + highlight reel + BGM. NO subtitle, NO ambience.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 90-minute soccer game tape — please cut a highlight reel with epic-orchestral BGM.",
    "Here's a 2-hour wedding reception — extract the best moments with light-jazz BGM.",
    "I have a 3-hour fishing tournament livestream — pull highlights with country-folk BGM.",
    "Uploading a 90-minute esports VOD — cut a highlight reel with EDM BGM.",
    "Here's a 4-hour Yellowstone vacation video — make highlights with acoustic-guitar BGM.",
    "I'm sending you a 2-hour live concert recording — cut a highlight reel with rock-anthem BGM.",
    "Uploading a 3-hour Twitch playthrough VOD — pull highlights with retro-chiptune BGM.",
    "Here's a 4-hour endurance bike race — please cut highlights with hip-hop BGM.",
    "I have a 90-minute karaoke night — make a highlight reel with party-pop BGM.",
    "Uploading a 5-hour wedding video — please cut a highlight reel with romantic-strings BGM.",
    "Here's a 90-minute baseball game — pull highlights with stadium-rock BGM.",
    "I'm sending you a 2-hour ice hockey tournament — cut highlights with rock-anthem BGM.",
    "Uploading a 4-hour D&D campaign — please pull highlights with fantasy-orchestral BGM.",
    "Here's a 90-minute amateur boxing match — cut highlights with hip-hop BGM.",
    "I have a 3-hour MMA cage fights — pull highlights with electronic-rock BGM.",
    "Uploading a 4-hour kart racing event — please cut a highlight reel with synth-rock BGM.",
    "Here's a 90-minute jazz festival — make highlights with smooth-jazz BGM.",
    "I'm sending you a 2-hour stand-up comedy show — pull highlights with light-jazz BGM.",
    "Uploading a 90-minute high-school graduation — make a highlight reel with hopeful-orchestral BGM.",
    "Here's a 4-hour gymnastics meet — cut highlights with cinematic-strings BGM.",
    "I have a 2-hour figure skating tournament — make highlights with classical-strings BGM.",
    "Uploading a 5-hour cricket test match — pull highlights with epic-orchestral BGM.",
    "Here's a 90-minute pickleball tournament — please make highlights with upbeat-pop BGM.",
    "I'm sending you a 4-hour archery field competition — cut highlights with cinematic-strings BGM.",
    "Uploading a 3-hour drone-racing championship — make highlights with synth-rock BGM.",
    "Here's a 2-hour dragon-boat festival — please pull highlights with traditional-Chinese-percussion BGM.",
    "I have a 4-hour pickleball state finals — cut highlights with light-jazz BGM.",
    "Uploading a 90-minute kabaddi championship — make highlights with bhangra BGM.",
    "Here's a 3-hour cornhole national championship — pull highlights with country-rock BGM.",
    "I'm sending you a 2-hour roller-derby final — make a highlight reel with punk-rock BGM.",
    "Uploading a 4-hour Renaissance Faire stage VOD — please pull highlights with medieval-lute BGM.",
    "Here's a 90-minute speed-cubing tournament VOD — cut highlights with electronic-pulse BGM.",
    "I have a 2-hour high-school marching-band finals — make highlights with brass-band BGM.",
    "Uploading a 3-hour fly-fishing tournament — pull highlights with country-folk BGM.",
    "Here's a 5-hour Iditarod sled-dog livestream — please cut highlights with epic-orchestral BGM.",
    # ── more highlight reels with BGM (50) ──────────────────────────────
    "Uploading a 90-minute rugby Six-Nations championship — please cut a highlight reel with epic-orchestral BGM.",
    "Here's a 2-hour lacrosse final — extract the best plays with hip-hop BGM.",
    "I have a 3-hour polo match — pull highlights with classical-strings BGM.",
    "Uploading a 90-minute field-hockey championship — cut a highlight reel with stadium-rock BGM.",
    "Here's a 4-hour water-polo final — make highlights with electronic-rock BGM.",
    "I'm sending you a 2-hour badminton All-England final — cut highlights with synth-pop BGM.",
    "Uploading a 3-hour table-tennis world championship — pull highlights with chiptune BGM.",
    "Here's a 4-hour squash final — please cut highlights with EDM BGM.",
    "I have a 90-minute fencing world championship — make highlights with cinematic-strings BGM.",
    "Uploading a 5-hour judo Grand-Slam tournament — cut a highlight reel with epic-orchestral BGM.",
    "Here's a 90-minute weightlifting Olympic-trial — pull highlights with hard-rock BGM.",
    "I'm sending you a 2-hour climbing IFSC World-Cup — cut highlights with electronic-rock BGM.",
    "Uploading a 4-hour surfing Pipe-Masters — please pull highlights with surf-rock BGM.",
    "Here's a 90-minute kitesurfing world tour — cut highlights with reggae BGM.",
    "I have a 3-hour rowing Henley regatta — pull highlights with classical-strings BGM.",
    "Uploading a 4-hour sailing America's-Cup leg — please cut highlights with cinematic-strings BGM.",
    "Here's a 90-minute Olympic dressage round — make highlights with classical-orchestral BGM.",
    "I'm sending you a 2-hour show-jumping Grand-Prix — pull highlights with cinematic-strings BGM.",
    "Uploading a 90-minute Kentucky-Derby race day — make a highlight reel with country-bluegrass BGM.",
    "Here's a 4-hour NYC-Marathon broadcast — cut highlights with hopeful-orchestral BGM.",
    "I have a 5-hour Ironman Kona triathlon — make highlights with epic-orchestral BGM.",
    "Uploading a 3-hour Westminster dog-show — pull highlights with light-jazz BGM.",
    "Here's a 90-minute ballet Swan-Lake performance — please make highlights with classical-strings BGM.",
    "I'm sending you a 2-hour breakdancing world final — cut highlights with hip-hop BGM.",
    "Uploading a 4-hour cheerleading nationals — make highlights with party-pop BGM.",
    "Here's a 90-minute La-Scala opera — please pull highlights with operatic-orchestral BGM.",
    "I have a 2-hour Vienna orchestral concert — make highlights with classical-orchestral BGM.",
    "Uploading a 3-hour choir Christmas concert — pull highlights with choral-orchestral BGM.",
    "Here's a 90-minute Notre-Dame organ recital — cut highlights with sacred-organ BGM.",
    "I'm sending you a 4-hour country-music festival — pull highlights with country-rock BGM.",
    "Uploading a 5-hour hip-hop festival — please cut highlights with hip-hop BGM.",
    "Here's a 90-minute salsa festival — make highlights with salsa BGM.",
    "I have a 2-hour tango milonga — pull highlights with tango BGM.",
    "Uploading a 3-hour Shakespeare festival performance — make highlights with Renaissance-strings BGM.",
    "Here's a 4-hour science-fair championship — cut highlights with electronic-pulse BGM.",
    "I'm sending you a 2-hour FRC robotics final — pull highlights with electronic-rock BGM.",
    "Uploading a 90-minute debate tournament final — make highlights with cinematic-strings BGM.",
    "Here's a 4-hour Scripps National Spelling-Bee — please pull highlights with hopeful-orchestral BGM.",
    "I have a 5-hour chess Candidates tournament — make highlights with cinematic-strings BGM.",
    "Uploading a 90-minute Diwali festival parade — please pull highlights with bhangra BGM.",
    "Here's a 2-hour Lunar-New-Year parade — make highlights with traditional-Chinese-percussion BGM.",
    "I'm sending you a 4-hour Pebble-Beach concours d'élégance — pull highlights with cinematic-strings BGM.",
    "Uploading a 5-hour Sturgis motorcycle rally — please cut highlights with hard-rock BGM.",
    "Here's a 90-minute Memphis BBQ cook-off — make highlights with country-rock BGM.",
    "I have a 3-hour Terlingua chili cook-off — pull highlights with country-rock BGM.",
    "Uploading a 4-hour Western States 100 ultramarathon — please make highlights with epic-orchestral BGM.",
    "Here's a 90-minute Spartan-race championship — cut highlights with electronic-rock BGM.",
    "I'm sending you a 2-hour Reno airshow — pull highlights with stadium-rock BGM.",
    "Uploading a 4-hour Albuquerque hot-air-balloon fest — make highlights with hopeful-orchestral BGM.",
    "Here's a 5-hour NCAA swim meet championship — please make highlights with electronic-pulse BGM.",
    # ── more highlight reels with BGM (50) ──────────────────────────────
    "Uploading a 3-hour World-Cup soccer final — please cut a highlight reel with cinematic-orchestral BGM.",
    "Here's a 2-hour Champions-League final — extract the best moments with triumphant-orchestral BGM.",
    "I have a 90-minute Premier-League match — pull highlights with stadium-rock BGM.",
    "Uploading a 90-minute La-Liga El-Clásico — cut a highlight reel with dramatic-orchestral BGM.",
    "Here's a 2-hour Serie-A derby — make highlights with cinematic-strings BGM.",
    "I'm sending you a 90-minute Bundesliga derby — cut highlights with stadium-rock BGM.",
    "Uploading a 3-hour NBA-Finals game — pull highlights with hip-hop BGM.",
    "Here's a 4-hour Stanley-Cup-Finals game — please cut highlights with stadium-rock BGM.",
    "I have a 4-hour NFL-Super-Bowl — make a highlight reel with stadium-rock BGM.",
    "Uploading a 4-hour MLB-World-Series game — please cut a highlight reel with Americana-folk BGM.",
    "Here's a 5-hour Indianapolis-500 — pull highlights with heavy-metal BGM.",
    "I'm sending you a 4-hour Daytona-500 — cut highlights with country-rock BGM.",
    "Uploading a 90-minute F1-Monaco-GP — please pull highlights with cinematic-orchestral BGM.",
    "Here's a 90-minute F1-Silverstone — cut highlights with stadium-rock BGM.",
    "I have a 90-minute F1-Suzuka — pull highlights with J-rock BGM.",
    "Uploading a 90-minute MotoGP-Mugello — please cut a highlight reel with heavy-metal BGM.",
    "Here's a 4-hour Tour-de-France stage — make highlights with cinematic-orchestral BGM.",
    "I'm sending you a 5-hour Giro-d'Italia stage — pull highlights with Italian-folk-rock BGM.",
    "Uploading a 4-hour Vuelta-a-España stage — please cut highlights with Spanish-flamenco-rock BGM.",
    "Here's a 4-hour Wimbledon final — cut highlights with classical-strings BGM.",
    "I have a 4-hour US-Open tennis final — please pull highlights with hip-hop BGM.",
    "Uploading a 4-hour Roland-Garros final — make highlights with French-jazz BGM.",
    "Here's a 4-hour Australian-Open tennis final — please cut highlights with upbeat-pop BGM.",
    "I'm sending you a 5-hour Masters-golf round — pull highlights with pastoral-strings BGM.",
    "Uploading a 5-hour PGA-Championship round — please cut a highlight reel with classical-strings BGM.",
    "Here's a 4-hour Open-Championship golf round — make highlights with Highland-folk BGM.",
    "I have a 5-hour US-Open-golf round — please pull highlights with cinematic-strings BGM.",
    "Uploading a 5-hour Ryder-Cup match-play — extract highlights with stadium-rock BGM.",
    "Here's a 4-hour Solheim-Cup match-play — please cut a highlight reel with upbeat-pop BGM.",
    "I'm sending you a 4-hour Olympic-Opening-Ceremony — pull highlights with cinematic-orchestral BGM.",
    "Uploading a 4-hour Olympic-Closing-Ceremony — please extract highlights with hopeful-orchestral BGM.",
    "Here's a 90-minute Winter-Olympics figure-skating final — cut highlights with classical-strings BGM.",
    "I have a 2-hour Olympic curling-final — please pull highlights with electronic-pulse BGM.",
    "Uploading a 90-minute Olympic-skeleton final — make highlights with electronic-rock BGM.",
    "Here's a 90-minute Olympic-bobsled final — please cut a highlight reel with electronic-rock BGM.",
    "I'm sending you a 4-hour World-Athletics Championship session — pull highlights with cinematic-strings BGM.",
    "Uploading a 4-hour World-Swimming Championship session — please extract highlights with electronic-pulse BGM.",
    "Here's a 4-hour World-Aquatics diving final — make highlights with classical-strings BGM.",
    "I have a 4-hour World-Gymnastics final — please pull highlights with delicate-piano BGM.",
    "Uploading a 90-minute Olympic-vault event — extract highlights with delicate-piano BGM.",
    "Here's a 90-minute pommel-horse event — please cut a highlight reel with delicate-piano BGM.",
    "I'm sending you a 90-minute Olympic-beam event — pull highlights with delicate-piano BGM.",
    "Uploading a 90-minute Olympic floor-exercise event — please extract highlights with upbeat-pop BGM.",
    "Here's a 4-hour synchronized-swimming final — cut highlights with ambient-strings BGM.",
    "I have a 90-minute Olympic trampoline final — please pull highlights with playful-clarinet BGM.",
    "Uploading a 4-hour Track-and-field Diamond-League — make highlights with cinematic-orchestral BGM.",
    "Here's a 90-minute World-Cup skiing — please cut a highlight reel with cinematic-orchestral BGM.",
    "I'm sending you a 90-minute World-Cup snowboarding — pull highlights with electronic-rock BGM.",
    "Uploading a 4-hour X-Games session — please extract highlights with punk-rock BGM.",
    "Here's a 5-hour UFC pay-per-view — cut highlights with heavy-metal BGM.",
    # ── more highlight reels with BGM (50) ──────────────────────────────
    "Uploading a 4-hour Cricket-World-Cup final — please cut a highlight reel with Indian-classical BGM.",
    "Here's a 5-hour Cricket-Test-match — extract the best plays with Indian-classical BGM.",
    "I have a 4-hour IPL final — pull highlights with Bollywood-pop BGM.",
    "Uploading a 5-hour India-Pakistan cricket match — cut a highlight reel with patriotic-orchestral BGM.",
    "Here's a 90-minute Liverpool-United derby — make highlights with English-folk-rock BGM.",
    "I'm sending you a 90-minute Schalke-Dortmund derby — cut highlights with German-rock BGM.",
    "Uploading a 90-minute Old-Firm Rangers-Celtic derby — pull highlights with Highland-bagpipe BGM.",
    "Here's a 90-minute Madrid-Atletico derby — please cut highlights with flamenco-rock BGM.",
    "I have a 90-minute Milan derby — make highlights with Italian-pop BGM.",
    "Uploading a 90-minute Roma-Lazio derby — cut a highlight reel with Italian-rock BGM.",
    "Here's a 90-minute Boca-River derby — pull highlights with tango-rock BGM.",
    "I'm sending you a 90-minute Flamengo-Fluminense derby — cut highlights with samba-rock BGM.",
    "Uploading a 90-minute River-Plate Argentina match — please pull highlights with Argentine-rock BGM.",
    "Here's a 90-minute Mexican-Liga-MX derby — cut highlights with banda-rock BGM.",
    "I have a 90-minute MLS final — pull highlights with hip-hop BGM.",
    "Uploading a 90-minute Toronto-FC match — please cut a highlight reel with Canadian-folk BGM.",
    "Here's a 4-hour Olympic-Marathon broadcast — make highlights with cinematic-orchestral BGM.",
    "I'm sending you a 4-hour Boston-Marathon broadcast — pull highlights with Americana-folk BGM.",
    "Uploading a 4-hour London-Marathon broadcast — please cut highlights with English-folk BGM.",
    "Here's a 4-hour Berlin-Marathon broadcast — cut highlights with electronic-pulse BGM.",
    "I have a 4-hour Tokyo-Marathon broadcast — please pull highlights with J-rock BGM.",
    "Uploading a 5-hour Comrades-Marathon — extract highlights with African-percussion BGM.",
    "Here's a 5-hour Two-Oceans-Marathon — please cut a highlight reel with Cape-Town-jazz BGM.",
    "I'm sending you a 4-hour Bay-to-Breakers — pull highlights with indie-rock BGM.",
    "Uploading a 5-hour Hood-to-Coast Relay — please extract highlights with indie-rock BGM.",
    "Here's a 5-hour JFK-50-Mile — cut highlights with cinematic-orchestral BGM.",
    "I have a 5-hour UTMB-trail-race — please pull highlights with French-folk BGM.",
    "Uploading a 5-hour Hardrock-100 — extract highlights with cinematic-orchestral BGM.",
    "Here's a 5-hour Iditarod-finish — please cut a highlight reel with Iditarod-folk BGM.",
    "I'm sending you a 5-hour Yukon-Quest — pull highlights with Yukon-folk BGM.",
    "Uploading a 5-hour Tour-de-Suisse stage — please cut highlights with Swiss-folk BGM.",
    "Here's a 5-hour Tour-Down-Under stage — make highlights with Australian-rock BGM.",
    "I have a 5-hour Paris-Roubaix stage — please pull highlights with French-rock BGM.",
    "Uploading a 5-hour Liège-Bastogne-Liège stage — cut a highlight reel with Walloon-folk BGM.",
    "Here's a 5-hour Vuelta-a-Catalunya stage — pull highlights with Catalan-rock BGM.",
    "I'm sending you a 5-hour Vuelta-a-Burgos stage — cut highlights with Spanish-rock BGM.",
    "Uploading a 5-hour Critérium-du-Dauphiné stage — please pull highlights with French-classical BGM.",
    "Here's a 5-hour Tirreno-Adriatico stage — please cut a highlight reel with Italian-pop BGM.",
    "I have a 5-hour Strade-Bianche stage — pull highlights with Tuscan-folk BGM.",
    "Uploading a 5-hour Milan-San-Remo stage — extract highlights with Italian-rock BGM.",
    "Here's a 5-hour Amstel-Gold-Race stage — please cut highlights with Dutch-folk BGM.",
    "I'm sending you a 5-hour Volta-a-Catalunya stage — pull highlights with Catalan-folk BGM.",
    "Uploading a 5-hour Volta-Algarve stage — please extract highlights with Portuguese-fado BGM.",
    "Here's a 5-hour Tour-de-Romandie stage — cut highlights with Swiss-jazz BGM.",
    "I have a 5-hour Critérium-International stage — please pull highlights with French-folk BGM.",
    "Uploading a 5-hour World-Touring-Car race — extract highlights with electronic-rock BGM.",
    "Here's a 5-hour Le-Mans-24-Hour race — please cut a highlight reel with cinematic-orchestral BGM.",
    "I'm sending you a 5-hour Daytona-24-Hour race — pull highlights with Americana-rock BGM.",
    "Uploading a 5-hour Spa-24-Hour race — please extract highlights with Belgian-rock BGM.",
    "Here's a 5-hour Bathurst-1000 — cut highlights with Australian-rock BGM.",
    # ── more equestrian / dog / cat / agricultural shows + BGM (50) ──
    "I have a 4-hour Kentucky-Derby livestream — please cut a highlight reel with Bluegrass-fiddle BGM.",
    "Uploading a 4-hour Royal-Ascot livestream — extract highlights with British-pomp BGM.",
    "Here's a 4-hour Melbourne-Cup livestream — cut highlights with Australian-orchestral BGM.",
    "I'm sending you a 4-hour Dubai-World-Cup livestream — pull highlights with Arabic-strings BGM.",
    "Uploading a 4-hour Royal-Windsor-Horse-Show — please extract highlights with British-fanfare BGM.",
    "Here's a 4-hour Aachen-CHIO livestream — cut highlights with German-orchestral BGM.",
    "I have a 4-hour Rolex-Kentucky-Three-Day-Event — please pull highlights with American-folk BGM.",
    "Uploading a 4-hour Badminton-Horse-Trials livestream — extract highlights with British-folk-fiddle BGM.",
    "Here's a 4-hour Burghley-Horse-Trials livestream — cut highlights with English-pastoral BGM.",
    "I'm sending you a 4-hour Spruce-Meadows-Masters livestream — pull highlights with Canadian-orchestral BGM.",
    "Uploading a 4-hour Hampton-Classic-Horse-Show — please extract highlights with American-classical BGM.",
    "Here's a 4-hour Devon-Horse-Show livestream — cut highlights with American-pastoral BGM.",
    "I have a 4-hour Calgary-Stampede rodeo — please pull highlights with country-rock BGM.",
    "Uploading a 4-hour Cheyenne-Frontier-Days rodeo — extract highlights with country-fiddle BGM.",
    "Here's a 4-hour Houston-Livestock-Show — please cut a highlight reel with Texas-country BGM.",
    "I'm sending you a 4-hour Pendleton-Round-Up rodeo — pull highlights with Western-fiddle BGM.",
    "Uploading a 4-hour Reno-Rodeo livestream — please extract highlights with Western-rock BGM.",
    "Here's a 4-hour PBR-Bull-Riding finale — cut highlights with Western-rock-2 BGM.",
    "I have a 4-hour Westminster-Kennel-Club Dog-Show — please pull highlights with classical-orchestral BGM.",
    "Uploading a 4-hour Crufts livestream — extract highlights with British-orchestral BGM.",
    "Here's a 4-hour World-Dog-Show livestream — cut highlights with European-folk-orchestral BGM.",
    "I'm sending you a 4-hour AKC-National-Championship — pull highlights with classical-orchestral-2 BGM.",
    "Uploading a 4-hour Eukanuba-World-Challenge — please extract highlights with classical-orchestral-3 BGM.",
    "Here's a 4-hour Iditarod-mushers livestream — cut highlights with Alaskan-folk BGM.",
    "I have a 4-hour Yukon-Quest-mushers livestream — please pull highlights with Yukon-folk BGM.",
    "Uploading a 4-hour Sheep-Dog-Trials livestream — extract highlights with Scottish-folk BGM.",
    "Here's a 4-hour Border-Collie Round-Up — please cut a highlight reel with Scottish-fiddle BGM.",
    "I'm sending you a 4-hour AKC-National-Agility-Championship — pull highlights with playful-orchestral BGM.",
    "Uploading a 4-hour FCI-World-Agility livestream — please extract highlights with European-orchestral BGM.",
    "Here's a 4-hour CFA-International-Cat-Show — cut highlights with classical-orchestral-4 BGM.",
    "I have a 4-hour TICA-Cat-Show livestream — please pull highlights with classical-piano BGM.",
    "Uploading a 4-hour World-Cat-Federation show — extract highlights with European-orchestral-2 BGM.",
    "Here's a 4-hour Royal-Welsh-Show livestream — please cut a highlight reel with Welsh-folk BGM.",
    "I'm sending you a 4-hour Royal-Highland-Show — pull highlights with Scottish-folk-2 BGM.",
    "Uploading a 4-hour Royal-Cornwall-Show — please extract highlights with Cornish-folk BGM.",
    "Here's a 4-hour Royal-Three-Counties-Show — cut highlights with English-folk BGM.",
    "I have a 4-hour Iowa-State-Fair livestream — please pull highlights with Midwestern-country BGM.",
    "Uploading a 4-hour Texas-State-Fair livestream — extract highlights with Texas-country-rock BGM.",
    "Here's a 4-hour Minnesota-State-Fair livestream — cut highlights with Midwestern-folk BGM.",
    "I'm sending you a 4-hour Wisconsin-State-Fair — pull highlights with Wisconsin-country BGM.",
    "Uploading a 4-hour Pennsylvania-Farm-Show — please extract highlights with American-folk-2 BGM.",
    "Here's a 4-hour Royal-Easter-Show-Sydney — cut highlights with Australian-country BGM.",
    "I have a 4-hour Royal-Adelaide-Show — please pull highlights with Australian-folk BGM.",
    "Uploading a 4-hour Royal-Brisbane-Show — extract highlights with Queensland-country BGM.",
    "Here's a 4-hour Royal-Bath-and-West-Show — please cut a highlight reel with West-Country-folk BGM.",
    "I'm sending you a 4-hour Tennessee-Walking-Horse-Celebration — pull highlights with Tennessee-folk BGM.",
    "Uploading a 4-hour American-Quarter-Horse-Congress — please extract highlights with country-rock-2 BGM.",
    "Here's a 4-hour Friesian-Horse-Show livestream — cut highlights with Dutch-folk BGM.",
    "I have a 4-hour Lipizzaner-Spanish-Riding-School — please pull highlights with Viennese-classical BGM.",
    "Uploading a 4-hour Royal-Andalusian-School-of-Equestrian-Art — extract highlights with Spanish-classical BGM.",
    # ── more extreme-sport / endurance event recordings + BGM (50) ──
    "I have a 4-hour IRONMAN-Kona triathlon — please cut a highlight reel with Pacific-orchestral BGM.",
    "Uploading a 4-hour IRONMAN-Nice triathlon — please extract highlights with Mediterranean-orchestral BGM.",
    "Here's a 4-hour Tour-Divide bikepacking — cut highlights with Continental-Divide-folk BGM.",
    "I'm sending you a 4-hour Race-Across-America cycling — pull highlights with Americana-rock-2 BGM.",
    "Uploading a 4-hour Race-Around-Ireland cycling — please extract highlights with Irish-trad BGM.",
    "Here's a 4-hour Trans-Pyrenees bikepacking — cut highlights with Pyrenean-folk BGM.",
    "I have a 4-hour Marathon-des-Sables — please pull highlights with Saharan-Tuareg BGM.",
    "I'm sending you a 4-hour Western-States 100-mile — pull highlights with Sierra-Nevada-folk BGM.",
    "Uploading a 4-hour UTMB Mont-Blanc — please extract highlights with Alpine-orchestral BGM.",
    "Here's a 4-hour Hardrock-100 ultra — cut highlights with Rocky-Mountain-folk BGM.",
    "I have a 4-hour Barkley-Marathons — please pull highlights with Appalachian-fiddle-2 BGM.",
    "Uploading a 4-hour Spartathlon ultra — extract highlights with Greek-folk-marching BGM.",
    "Here's a 4-hour Comrades-Marathon-South-Africa — cut highlights with Zulu-vocal BGM.",
    "I'm sending you a 4-hour Two-Oceans-Marathon — pull highlights with Cape-jazz-2 BGM.",
    "Uploading a 4-hour London-Marathon broadcast — please extract highlights with British-orchestral-2 BGM.",
    "Here's a 4-hour Boston-Marathon broadcast — cut highlights with Bostonian-fanfare BGM.",
    "I have a 4-hour New-York-City-Marathon broadcast — please pull highlights with NYC-orchestral BGM.",
    "I'm sending you a 4-hour Berlin-Marathon broadcast — pull highlights with Berlin-electronic BGM.",
    "Uploading a 4-hour Tokyo-Marathon broadcast — please extract highlights with Tokyo-electronic BGM.",
    "Here's a 4-hour Chicago-Marathon broadcast — cut highlights with Chicago-blues BGM.",
    "I have a 4-hour Iditarod-mushers livestream — please pull highlights with Alaskan-folk-2 BGM.",
    "Uploading a 4-hour Yukon-Quest-mushers livestream — extract highlights with Yukon-folk-2 BGM.",
    "Here's a 4-hour Vendee-Globe-yacht-race — cut highlights with maritime-orchestral BGM.",
    "I'm sending you a 4-hour Volvo-Ocean-Race leg — pull highlights with Volvo-Race-orchestral BGM.",
    "Uploading a 4-hour Sydney-to-Hobart-yacht-race — please extract highlights with Australian-maritime BGM.",
    "Here's a 4-hour Fastnet-yacht-race — cut highlights with British-maritime BGM.",
    "I have a 4-hour America's-Cup-final — please pull highlights with America's-Cup-orchestral BGM.",
    "I'm sending you a 4-hour Trans-Atlantic-rowing — pull highlights with Atlantic-folk BGM.",
    "Uploading a 4-hour Talisker-Whisky-Atlantic-Challenge — please extract highlights with Atlantic-rowing-folk BGM.",
    "Here's a 4-hour Yukon-River-Quest canoe — cut highlights with Yukon-canoe-folk BGM.",
    "I have a 4-hour Great-River-Race-Thames — please pull highlights with English-folk-rowing BGM.",
    "Uploading a 4-hour Henley-Royal-Regatta — extract highlights with English-classical-2 BGM.",
    "Here's a 4-hour Boat-Race-Oxford-Cambridge — cut highlights with Oxford-Cambridge-fanfare BGM.",
    "I'm sending you a 4-hour Head-of-the-Charles regatta — pull highlights with Boston-collegiate BGM.",
    "Uploading a 4-hour Ironbike Italia — please extract highlights with Italian-folk-2 BGM.",
    "Here's a 4-hour Tour-de-Ski cross-country-ski — cut highlights with Alpine-skiing-folk BGM.",
    "I have a 4-hour Vasaloppet ski-marathon — please pull highlights with Swedish-folk-2 BGM.",
    "I'm sending you a 4-hour Birkebeiner ski-marathon — pull highlights with Norwegian-folk-2 BGM.",
    "Uploading a 4-hour Engadin-Skimarathon — please extract highlights with Swiss-folk-2 BGM.",
    "Here's a 4-hour Iditasport ski/bike — cut highlights with Iditarod-blues BGM.",
    "I have a 4-hour Race-the-Reno-River raft — please pull highlights with Reno-River-folk BGM.",
    "Uploading a 4-hour Grand-Canyon-rafting expedition — extract highlights with canyon-folk BGM.",
    "Here's a 4-hour Cliff-diving-World-Series — cut highlights with diving-orchestral BGM.",
    "I'm sending you a 4-hour Big-wave-surfing-Mavericks — pull highlights with surf-rock BGM.",
    "Uploading a 4-hour Eddie-Aikau-Big-Wave-Invitational — please extract highlights with Hawaiian-slack-key BGM.",
    "Here's a 4-hour Pipeline-surfing competition — cut highlights with reggae-rock BGM.",
    "I have a 4-hour Free-Solo-El-Cap-livestream — please pull highlights with rock-climbing-orchestral BGM.",
    "I'm sending you a 4-hour Speed-climbing-finals — pull highlights with speed-rock BGM.",
    "Uploading a 4-hour Bouldering-World-Cup — please extract highlights with bouldering-electronic BGM.",
    "Here's a 4-hour Skeleton-bobsled-World-Cup — cut highlights with bobsled-orchestral BGM.",
    # ── more classical-music concert / orchestra-performance highlight reels (50) ──
    "Uploading a 3-hour Berlin-Philharmonic concert — please cut highlights with Furtwängler-archive BGM.",
    "Here's a 4-hour Vienna-Philharmonic-Musikverein concert — extract highlights with Wiener-Klang BGM.",
    "I have a 90-minute Bayreuth-Festspielhaus Wagner-Ring-cycle — please pull highlights with Wagner-leitmotif BGM.",
    "Uploading a 2-hour Salzburg-Festival Mozart-Don-Giovanni — cut highlights with Mozart-Don-Giovanni BGM.",
    "Here's a 3-hour La-Scala-Milan Verdi-Aida — please cut highlights with Verdi-Aida BGM.",
    "I'm sending you a 4-hour Royal-Opera-House-Covent-Garden Tosca — pull highlights with Puccini-Tosca BGM.",
    "Uploading a 90-minute Metropolitan-Opera La-Bohème — please extract highlights with Puccini-Bohème BGM.",
    "Here's a 2-hour Carnegie-Hall solo-piano-recital — cut highlights with Steinway-piano BGM.",
    "I have a 3-hour Concertgebouw-Amsterdam Mahler-Symphony — please pull highlights with Mahler-symphony BGM.",
    "Uploading a 4-hour Boston-Symphony Beethoven-Ninth — extract highlights with Beethoven-ninth BGM.",
    "Here's a 90-minute Cleveland-Orchestra Brahms-cycle — please cut highlights with Brahms-cycle BGM.",
    "I'm sending you a 2-hour Chicago-Symphony Mahler-Two — pull highlights with Mahler-resurrection BGM.",
    "Uploading a 3-hour LA-Philharmonic-Walt-Disney-Hall Adams-premiere — please extract highlights with John-Adams-minimalist BGM.",
    "Here's a 4-hour San-Francisco-Symphony Tilson-Thomas-farewell — cut highlights with MTT-farewell-orchestral BGM.",
    "I have a 90-minute Philadelphia-Orchestra Yannick-Sibelius — please pull highlights with Sibelius-symphony BGM.",
    "Uploading a 2-hour Pittsburgh-Symphony Honeck-Strauss-tone-poem — extract highlights with Strauss-tone-poem BGM.",
    "Here's a 3-hour Atlanta-Symphony-Spano Vaughan-Williams — please cut highlights with Vaughan-Williams-pastoral BGM.",
    "I'm sending you a 4-hour Houston-Symphony-Orozco Brahms-Symphony — pull highlights with Brahms-orchestral BGM.",
    "Uploading a 90-minute Dallas-Symphony Luisi-Bruckner — please extract highlights with Bruckner-symphony BGM.",
    "Here's a 2-hour Detroit-Symphony-Slatkin Shostakovich-Five — cut highlights with Shostakovich-five BGM.",
    "I have a 3-hour Minnesota-Orchestra-Vänskä Sibelius-cycle — please pull highlights with Sibelius-cycle BGM.",
    "Uploading a 4-hour St-Louis-Symphony Robertson-Adams — extract highlights with John-Adams-orchestral BGM.",
    "Here's a 90-minute Seattle-Symphony-Morlot Dutilleux-symphony — please cut highlights with Dutilleux-French-modernist BGM.",
    "I'm sending you a 2-hour Toronto-Symphony-Oundjian Beethoven-cycle — pull highlights with Beethoven-cycle BGM.",
    "Uploading a 3-hour Montreal-Symphony Nagano-Mahler — please extract highlights with Mahler-late-symphonic BGM.",
    "Here's a 4-hour London-Symphony-Rattle Mahler-Six — cut highlights with Mahler-six BGM.",
    "I have a 90-minute London-Philharmonic Jurowski-Tchaikovsky — please pull highlights with Tchaikovsky-symphony BGM.",
    "Uploading a 2-hour Royal-Liverpool-Philharmonic Petrenko-Shostakovich — extract highlights with Shostakovich-orchestral BGM.",
    "Here's a 3-hour Hallé-Orchestra-Manchester Elder-Mahler — please cut highlights with Mahler-Elder-orchestral BGM.",
    "I'm sending you a 4-hour BBC-Symphony-Proms-Sakari-Oramo Sibelius — pull highlights with Sibelius-Proms BGM.",
    "Uploading a 90-minute Royal-Concertgebouw Haitink-archive — please extract highlights with Haitink-archive BGM.",
    "Here's a 2-hour Munich-Philharmonic Gergiev-Tchaikovsky — cut highlights with Gergiev-Tchaikovsky BGM.",
    "I have a 3-hour Bayerische-Staatsoper Wagner-Tristan — please pull highlights with Tristan-Liebestod BGM.",
    "Uploading a 4-hour Dresden-Staatskapelle Strauss-tone-poems — extract highlights with Strauss-Dresden BGM.",
    "Here's a 90-minute Leipzig-Gewandhaus Bach-B-Minor — please cut highlights with Bach-Mass-B-minor BGM.",
    "I'm sending you a 2-hour Prague-Symphony Suk-Asrael — pull highlights with Suk-Asrael-orchestral BGM.",
    "Uploading a 3-hour Warsaw-Philharmonic Lutosławski-cycle — please extract highlights with Lutosławski-modernist BGM.",
    "Here's a 4-hour Helsinki-Philharmonic Sibelius-marathon — cut highlights with Sibelius-marathon BGM.",
    "I have a 90-minute Oslo-Philharmonic Mäkelä-Sibelius — please pull highlights with Sibelius-Oslo BGM.",
    "Uploading a 2-hour Stockholm-Royal-Philharmonic Nilsson-Brahms — extract highlights with Brahms-Stockholm BGM.",
    "Here's a 3-hour Mariinsky-Theatre Tchaikovsky-Eugene-Onegin — please cut highlights with Tchaikovsky-Onegin BGM.",
    "I'm sending you a 4-hour Bolshoi-Theatre Mussorgsky-Boris-Godunov — pull highlights with Mussorgsky-Boris BGM.",
    "Uploading a 90-minute Budapest-Festival-Orchestra Fischer-Mahler — please extract highlights with Mahler-Fischer-Hungarian BGM.",
    "Here's a 2-hour Hungarian-State-Opera Bartók-Bluebeard — cut highlights with Bartók-Bluebeard BGM.",
    "I have a 3-hour Tokyo-NHK-Symphony Brahms-cycle — please pull highlights with NHK-Brahms BGM.",
    "Uploading a 4-hour Yomiuri-Nippon-Symphony Beethoven — extract highlights with Yomiuri-Beethoven BGM.",
    "Here's a 90-minute Seoul-Philharmonic-Chung Mahler-Three — please cut highlights with Mahler-three BGM.",
    "I'm sending you a 2-hour Hong-Kong-Philharmonic-van-Zweden Mahler — pull highlights with Mahler-van-Zweden BGM.",
    "Uploading a 3-hour Singapore-Symphony Lan-Shui-Chinese-modern — please extract highlights with Chinese-orchestral-modern BGM.",
    "Here's a 4-hour Sydney-Symphony Ashkenazy-Rachmaninoff — cut highlights with Rachmaninoff-Sydney BGM.",
    # ── more ballet / dance-company performance highlight reels (50) ──
    "Uploading a 3-hour Royal-Ballet-Covent-Garden Sleeping-Beauty — please cut highlights with Tchaikovsky-Sleeping-Beauty BGM.",
    "Here's a 4-hour Royal-Ballet-Covent-Garden Swan-Lake — extract highlights with Tchaikovsky-Swan-Lake BGM.",
    "I have a 90-minute Royal-Ballet-Covent-Garden Nutcracker — please pull highlights with Tchaikovsky-Nutcracker BGM.",
    "Uploading a 2-hour Royal-Ballet-Covent-Garden Romeo-and-Juliet — cut highlights with Prokofiev-Romeo-Juliet BGM.",
    "Here's a 3-hour Bolshoi-Ballet-Moscow Spartacus — please cut highlights with Khachaturian-Spartacus BGM.",
    "I'm sending you a 4-hour Bolshoi-Ballet-Moscow Don-Quixote — pull highlights with Minkus-Don-Quixote BGM.",
    "Uploading a 90-minute Bolshoi-Ballet-Moscow Giselle — please extract highlights with Adam-Giselle BGM.",
    "Here's a 2-hour Mariinsky-Ballet-Saint-Petersburg La-Bayadère — cut highlights with Minkus-Bayadère BGM.",
    "I have a 3-hour Mariinsky-Ballet-Saint-Petersburg Raymonda — please pull highlights with Glazunov-Raymonda BGM.",
    "Uploading a 4-hour Mariinsky-Ballet-Saint-Petersburg Sleeping-Beauty — extract highlights with Tchaikovsky-Mariinsky BGM.",
    "Here's a 90-minute Paris-Opera-Ballet Sylvia — please cut highlights with Delibes-Sylvia BGM.",
    "I'm sending you a 2-hour Paris-Opera-Ballet Coppélia — pull highlights with Delibes-Coppélia BGM.",
    "Uploading a 3-hour Paris-Opera-Ballet La-Sylphide — please extract highlights with Schneitzhoeffer-La-Sylphide BGM.",
    "Here's a 4-hour American-Ballet-Theatre Le-Corsaire — cut highlights with Adam-Le-Corsaire BGM.",
    "I have a 90-minute American-Ballet-Theatre Manon — please pull highlights with Massenet-MacMillan-Manon BGM.",
    "Uploading a 2-hour American-Ballet-Theatre Onegin — extract highlights with Tchaikovsky-Onegin-Cranko BGM.",
    "Here's a 3-hour New-York-City-Ballet Serenade — please cut highlights with Tchaikovsky-Serenade BGM.",
    "I'm sending you a 4-hour New-York-City-Ballet Apollo-Balanchine — pull highlights with Stravinsky-Apollo BGM.",
    "Uploading a 90-minute New-York-City-Ballet Symphony-in-C — please extract highlights with Bizet-Symphony-in-C BGM.",
    "Here's a 2-hour New-York-City-Ballet Agon-Stravinsky — cut highlights with Stravinsky-Agon BGM.",
    "I have a 3-hour New-York-City-Ballet Jewels-Balanchine — please pull highlights with Fauré-Stravinsky-Tchaikovsky-Jewels BGM.",
    "Uploading a 4-hour Stuttgart-Ballet John-Cranko-Onegin — extract highlights with Tchaikovsky-Cranko-Onegin BGM.",
    "Here's a 90-minute Hamburg-Ballet John-Neumeier-Lady-of-the-Camellias — please cut highlights with Chopin-Lady-Camellias BGM.",
    "I'm sending you a 2-hour Hamburg-Ballet Neumeier-Mahler-Third — pull highlights with Mahler-Third-Neumeier BGM.",
    "Uploading a 3-hour Royal-Danish-Ballet Bournonville-Napoli — please extract highlights with Bournonville-Napoli BGM.",
    "Here's a 4-hour Royal-Danish-Ballet Bournonville-La-Sylphide — cut highlights with Bournonville-La-Sylphide BGM.",
    "I have a 90-minute Royal-Swedish-Ballet Mats-Ek-Giselle — please pull highlights with Mats-Ek-Giselle BGM.",
    "Uploading a 2-hour Dutch-National-Ballet Hans-van-Manen-Symphonieën — extract highlights with Hans-van-Manen-symphonieën BGM.",
    "Here's a 3-hour Nederlands-Dans-Theater Jiří-Kylián-Petite-Mort — please cut highlights with Mozart-Kylián-Petite-Mort BGM.",
    "I'm sending you a 4-hour Béjart-Ballet-Lausanne Boléro — pull highlights with Ravel-Béjart-Boléro BGM.",
    "Uploading a 90-minute Béjart-Ballet-Lausanne Ninth-Symphony — please extract highlights with Beethoven-Béjart-Ninth BGM.",
    "Here's a 2-hour La-Scala-Ballet-Milan Excelsior — cut highlights with Marenco-Excelsior BGM.",
    "I have a 3-hour La-Scala-Ballet-Milan Don-Quixote — please pull highlights with Minkus-La-Scala-Don-Quixote BGM.",
    "Uploading a 4-hour Vienna-State-Ballet Onegin-Cranko — extract highlights with Vienna-Cranko-Onegin BGM.",
    "Here's a 90-minute Munich-Bavarian-State-Ballet Anna-Karenina — please cut highlights with Shchedrin-Anna-Karenina BGM.",
    "I'm sending you a 2-hour Berlin-Staatsballett Snow-Queen — pull highlights with Snow-Queen-orchestral BGM.",
    "Uploading a 3-hour Cuban-National-Ballet Don-Quixote-Alonso — please extract highlights with Cuban-Don-Quixote-Alonso BGM.",
    "Here's a 4-hour Beijing-Dance-Academy-Theatre Red-Detachment-of-Women — cut highlights with Red-Detachment-of-Women BGM.",
    "I have a 90-minute Beijing-National-Ballet White-Haired-Girl — please pull highlights with White-Haired-Girl-Wu-Zuqiang BGM.",
    "Uploading a 2-hour Shanghai-Ballet Butterfly-Lovers — extract highlights with Butterfly-Lovers-Concerto BGM.",
    "Here's a 3-hour Hong-Kong-Ballet Romeo-and-Juliet-Septime-Webre — please cut highlights with Hong-Kong-Romeo-Juliet BGM.",
    "I'm sending you a 4-hour Tokyo-Ballet Bolero-Béjart-Tokyo — pull highlights with Tokyo-Béjart-Boléro BGM.",
    "Uploading a 90-minute Tokyo-Ballet Bayadère-Tokyo — please extract highlights with Tokyo-Bayadère BGM.",
    "Here's a 2-hour National-Ballet-of-China Raise-the-Red-Lantern — cut highlights with Raise-the-Red-Lantern-orchestral BGM.",
    "I have a 3-hour Korean-National-Ballet Spring-Day — please pull highlights with Korean-Spring-Day-orchestral BGM.",
    "Uploading a 4-hour Royal-Ballet-Wayne-McGregor Woolf-Works — extract highlights with Max-Richter-Woolf-Works BGM.",
    "Here's a 90-minute Royal-Ballet-Christopher-Wheeldon Alice-in-Wonderland — please cut highlights with Talbot-Alice-Wonderland BGM.",
    "I'm sending you a 2-hour Royal-Ballet-Christopher-Wheeldon Winter's-Tale — pull highlights with Talbot-Winter's-Tale BGM.",
    "Uploading a 3-hour Pennsylvania-Ballet George-Balanchine-Theme-and-Variations — please extract highlights with Tchaikovsky-Theme-Variations BGM.",
    "Here's a 4-hour Boston-Ballet Don-Quixote — cut highlights with Boston-Ballet-Don-Quixote BGM.",
    # ── more world opera-house performance highlight reels (50) ──
    "Uploading a 3-hour Met-Opera-NYC La-Bohème — please cut highlights with Puccini-Bohème-Met BGM.",
    "Here's a 4-hour Met-Opera-NYC Madama-Butterfly — extract highlights with Puccini-Butterfly-Met BGM.",
    "I have a 90-minute Met-Opera-NYC Tosca — please pull highlights with Puccini-Tosca-Met BGM.",
    "Uploading a 2-hour Met-Opera-NYC Turandot — cut highlights with Puccini-Turandot-Met BGM.",
    "Here's a 3-hour Met-Opera-NYC Aida-Verdi — please cut highlights with Verdi-Aida-Met BGM.",
    "I'm sending you a 4-hour Met-Opera-NYC Rigoletto-Verdi — pull highlights with Verdi-Rigoletto-Met BGM.",
    "Uploading a 90-minute Met-Opera-NYC Traviata-Verdi — please extract highlights with Verdi-Traviata-Met BGM.",
    "Here's a 2-hour Met-Opera-NYC Otello-Verdi — cut highlights with Verdi-Otello-Met BGM.",
    "I have a 3-hour Met-Opera-NYC Nozze-di-Figaro-Mozart — please pull highlights with Mozart-Nozze-Met BGM.",
    "Uploading a 4-hour Met-Opera-NYC Don-Giovanni-Mozart — extract highlights with Mozart-Don-Giovanni-Met BGM.",
    "Here's a 90-minute Met-Opera-NYC Magic-Flute-Mozart — please cut highlights with Mozart-Zauberflöte-Met BGM.",
    "I'm sending you a 2-hour Royal-Opera-Covent-Garden Tosca-Puccini — pull highlights with ROH-Tosca BGM.",
    "Uploading a 3-hour Royal-Opera-Covent-Garden Bohème-Puccini — please extract highlights with ROH-Bohème BGM.",
    "Here's a 4-hour Royal-Opera-Covent-Garden Carmen-Bizet — cut highlights with ROH-Carmen BGM.",
    "I have a 90-minute Royal-Opera-Covent-Garden Wagner-Tristan — please pull highlights with Wagner-Tristan-ROH BGM.",
    "Uploading a 2-hour Royal-Opera-Covent-Garden Parsifal-Wagner — extract highlights with Wagner-Parsifal-ROH BGM.",
    "Here's a 3-hour La-Scala-Milan Verdi-Aida — please cut highlights with Verdi-Aida-La-Scala BGM.",
    "I'm sending you a 4-hour La-Scala-Milan Verdi-Otello — pull highlights with Verdi-Otello-La-Scala BGM.",
    "Uploading a 90-minute La-Scala-Milan Verdi-Falstaff — please extract highlights with Verdi-Falstaff-La-Scala BGM.",
    "Here's a 2-hour La-Scala-Milan Puccini-Manon-Lescaut — cut highlights with Puccini-Manon-La-Scala BGM.",
    "I have a 3-hour La-Scala-Milan Bellini-Norma — please pull highlights with Bellini-Norma-La-Scala BGM.",
    "Uploading a 4-hour La-Scala-Milan Donizetti-Lucia — extract highlights with Donizetti-Lucia-La-Scala BGM.",
    "Here's a 90-minute Vienna-State-Opera-Wagner-Tannhäuser — please cut highlights with Wagner-Tannhäuser-Vienna BGM.",
    "I'm sending you a 2-hour Vienna-State-Opera-Wagner-Lohengrin — pull highlights with Wagner-Lohengrin-Vienna BGM.",
    "Uploading a 3-hour Vienna-State-Opera-Strauss-Salome — please extract highlights with Strauss-Salome-Vienna BGM.",
    "Here's a 4-hour Vienna-State-Opera-Strauss-Elektra — cut highlights with Strauss-Elektra-Vienna BGM.",
    "I have a 90-minute Vienna-State-Opera-Strauss-Rosenkavalier — please pull highlights with Strauss-Rosenkavalier-Vienna BGM.",
    "Uploading a 2-hour Vienna-State-Opera-Mozart-Idomeneo — extract highlights with Mozart-Idomeneo-Vienna BGM.",
    "Here's a 3-hour Bayreuth-Festspielhaus Tristan-und-Isolde — please cut highlights with Wagner-Tristan-Bayreuth BGM.",
    "I'm sending you a 4-hour Bayreuth-Festspielhaus Parsifal — pull highlights with Wagner-Parsifal-Bayreuth BGM.",
    "Uploading a 90-minute Bayreuth-Festspielhaus Lohengrin — please extract highlights with Wagner-Lohengrin-Bayreuth BGM.",
    "Here's a 2-hour Bayreuth-Festspielhaus Tannhäuser — cut highlights with Wagner-Tannhäuser-Bayreuth BGM.",
    "I have a 3-hour Bayreuth-Festspielhaus Meistersinger — please pull highlights with Wagner-Meistersinger-Bayreuth BGM.",
    "Uploading a 4-hour Bayreuth-Festspielhaus Ring-Rheingold — extract highlights with Wagner-Rheingold-Bayreuth BGM.",
    "Here's a 90-minute Bayreuth-Festspielhaus Ring-Walküre — please cut highlights with Wagner-Walküre-Bayreuth BGM.",
    "I'm sending you a 2-hour Bayreuth-Festspielhaus Ring-Siegfried — pull highlights with Wagner-Siegfried-Bayreuth BGM.",
    "Uploading a 3-hour Bayreuth-Festspielhaus Götterdämmerung — please extract highlights with Wagner-Götterdämmerung-Bayreuth BGM.",
    "Here's a 4-hour Salzburg-Festival Mozart-Don-Giovanni — cut highlights with Mozart-Don-Giovanni-Salzburg BGM.",
    "I have a 90-minute Salzburg-Festival Mozart-Magic-Flute — please pull highlights with Mozart-Zauberflöte-Salzburg BGM.",
    "Uploading a 2-hour Salzburg-Festival Strauss-Rosenkavalier — extract highlights with Strauss-Rosenkavalier-Salzburg BGM.",
    "Here's a 3-hour Glyndebourne-Festival-Opera Mozart-Cosi-fan-tutte — please cut highlights with Mozart-Cosi-Glyndebourne BGM.",
    "I'm sending you a 4-hour Glyndebourne-Festival-Opera Britten-Peter-Grimes — pull highlights with Britten-Peter-Grimes-Glyndebourne BGM.",
    "Uploading a 90-minute Verona-Arena Aida-Verdi-arena — please extract highlights with Verdi-Aida-Verona-Arena BGM.",
    "Here's a 2-hour Verona-Arena Nabucco-Verdi-arena — cut highlights with Verdi-Nabucco-Verona-Arena BGM.",
    "I have a 3-hour Sydney-Opera-House Britten-Death-in-Venice — please pull highlights with Britten-Death-in-Venice-SOH BGM.",
    "Uploading a 4-hour Sydney-Opera-House La-Bohème-Sydney — extract highlights with Puccini-Bohème-SOH BGM.",
    "Here's a 90-minute Mariinsky-Theatre Eugene-Onegin-Tchaikovsky — please cut highlights with Tchaikovsky-Onegin-Mariinsky BGM.",
    "I'm sending you a 2-hour Mariinsky-Theatre Pikovaya-Dama-Tchaikovsky — pull highlights with Tchaikovsky-Pikovaya-Mariinsky BGM.",
    "Uploading a 3-hour Bolshoi-Theatre Boris-Godunov-Mussorgsky — please extract highlights with Mussorgsky-Boris-Bolshoi BGM.",
    "Here's a 4-hour Bolshoi-Theatre Khovanshchina-Mussorgsky — cut highlights with Mussorgsky-Khovanshchina-Bolshoi BGM.",
    # ── more symphony orchestra + concert hall recordings (50) ──
    "I have a 90-minute Vienna-Philharmonic-New-Year-Concert-Musikverein — please pull highlights with Strauss-Radetzky-March-Vienna BGM.",
    "Uploading a 2-hour Vienna-Philharmonic-Beethoven-9th-Musikverein — extract highlights with Beethoven-9th-Vienna-Phil BGM.",
    "Here's a 3-hour Vienna-Philharmonic-Mahler-2nd-Resurrection — please cut highlights with Mahler-2nd-Vienna-Phil BGM.",
    "I'm sending you a 4-hour Vienna-Philharmonic-Bruckner-7th-Musikverein — pull highlights with Bruckner-7th-Vienna-Phil BGM.",
    "Uploading a 90-minute Berlin-Philharmonic-Brahms-1st-Karajan-Saal — please extract highlights with Brahms-1st-Berlin-Phil BGM.",
    "Here's a 2-hour Berlin-Philharmonic-Mahler-9th-Karajan-Saal — cut highlights with Mahler-9th-Berlin-Phil BGM.",
    "I have a 3-hour Berlin-Philharmonic-Bruckner-9th-Karajan-Saal — please pull highlights with Bruckner-9th-Berlin-Phil BGM.",
    "Uploading a 4-hour Berlin-Philharmonic-Strauss-Alpine-Symphony — extract highlights with Strauss-Alpine-Berlin-Phil BGM.",
    "Here's a 90-minute Boston-Symphony-Symphony-Hall-Mahler-1st — please cut highlights with Mahler-1st-Boston-Symphony BGM.",
    "I'm sending you a 2-hour Boston-Symphony-Symphony-Hall-Brahms-2nd — pull highlights with Brahms-2nd-Boston-Symphony BGM.",
    "Uploading a 3-hour Boston-Symphony-Tanglewood-Beethoven-7th — please extract highlights with Beethoven-7th-Tanglewood BGM.",
    "Here's a 4-hour Chicago-Symphony-Orchestra-Hall-Mahler-5th — cut highlights with Mahler-5th-Chicago-Symphony BGM.",
    "I have a 90-minute Chicago-Symphony-Orchestra-Hall-Bruckner-8th — please pull highlights with Bruckner-8th-Chicago-Symphony BGM.",
    "Uploading a 2-hour Chicago-Symphony-Ravinia-Festival-Mahler-6th — extract highlights with Mahler-6th-Ravinia BGM.",
    "Here's a 3-hour New-York-Philharmonic-David-Geffen-Hall-Beethoven-3rd-Eroica — please cut highlights with Beethoven-Eroica-NYC-Phil BGM.",
    "I'm sending you a 4-hour New-York-Philharmonic-David-Geffen-Hall-Mahler-3rd — pull highlights with Mahler-3rd-NYC-Phil BGM.",
    "Uploading a 90-minute New-York-Philharmonic-Dvorak-9th-New-World-DGH — please extract highlights with Dvorak-New-World-NYC-Phil BGM.",
    "Here's a 2-hour Philadelphia-Orchestra-Verizon-Hall-Rachmaninoff-2nd-Symphony — cut highlights with Rachmaninoff-2nd-Philadelphia BGM.",
    "I have a 3-hour Cleveland-Orchestra-Severance-Hall-Brahms-4th — please pull highlights with Brahms-4th-Cleveland-Orchestra BGM.",
    "Uploading a 4-hour Los-Angeles-Philharmonic-Walt-Disney-Hall-Mahler-2nd — extract highlights with Mahler-2nd-LA-Phil BGM.",
    "Here's a 90-minute Los-Angeles-Philharmonic-Hollywood-Bowl-Beethoven-9th — please cut highlights with Beethoven-9th-Hollywood-Bowl BGM.",
    "I'm sending you a 2-hour San-Francisco-Symphony-Davies-Hall-Mahler-8th-Symphony-of-a-Thousand — pull highlights with Mahler-8th-SF-Symphony BGM.",
    "Uploading a 3-hour San-Francisco-Symphony-Davies-Hall-Sibelius-2nd — please extract highlights with Sibelius-2nd-SF-Symphony BGM.",
    "Here's a 4-hour Pittsburgh-Symphony-Heinz-Hall-Brahms-3rd — cut highlights with Brahms-3rd-Pittsburgh-Symphony BGM.",
    "I have a 90-minute London-Symphony-Barbican-Elgar-Enigma-Variations — please pull highlights with Elgar-Enigma-London-Symphony BGM.",
    "Uploading a 2-hour London-Symphony-Barbican-Vaughan-Williams-2nd-London — extract highlights with Vaughan-Williams-London-Symphony BGM.",
    "Here's a 3-hour London-Philharmonic-Royal-Festival-Hall-Holst-Planets — please cut highlights with Holst-Planets-London-Phil BGM.",
    "I'm sending you a 4-hour BBC-Symphony-Royal-Albert-Hall-Last-Night-of-the-Proms — pull highlights with Last-Night-Proms-BBC-Symphony BGM.",
    "Uploading a 90-minute Concertgebouw-Amsterdam-Mahler-4th — please extract highlights with Mahler-4th-Concertgebouw BGM.",
    "Here's a 2-hour Concertgebouw-Amsterdam-Bruckner-4th-Romantic — cut highlights with Bruckner-4th-Concertgebouw BGM.",
    "I have a 3-hour Royal-Concertgebouw-Mahler-7th-Amsterdam — please pull highlights with Mahler-7th-Concertgebouw BGM.",
    "Uploading a 4-hour Saint-Petersburg-Mariinsky-Concert-Hall-Shostakovich-5th — extract highlights with Shostakovich-5th-Mariinsky-Concert BGM.",
    "Here's a 90-minute Saint-Petersburg-Mariinsky-Shostakovich-7th-Leningrad — please cut highlights with Shostakovich-Leningrad-Mariinsky BGM.",
    "I'm sending you a 2-hour Moscow-Tchaikovsky-Hall-Tchaikovsky-Pathétique-6th — pull highlights with Tchaikovsky-Pathétique-Moscow BGM.",
    "Uploading a 3-hour Moscow-Tchaikovsky-Hall-Rachmaninoff-Symphonic-Dances — please extract highlights with Rachmaninoff-Symphonic-Dances-Moscow BGM.",
    "Here's a 4-hour Paris-Philharmonie-Boulez-Notations — cut highlights with Boulez-Notations-Paris-Phil BGM.",
    "I have a 90-minute Paris-Philharmonie-Berlioz-Symphonie-Fantastique — please pull highlights with Berlioz-Fantastique-Paris-Phil BGM.",
    "Uploading a 2-hour Paris-Philharmonie-Debussy-La-Mer — extract highlights with Debussy-La-Mer-Paris-Phil BGM.",
    "Here's a 3-hour Paris-Salle-Pleyel-Ravel-Daphnis-Chloé — please cut highlights with Ravel-Daphnis-Chloé-Pleyel BGM.",
    "I'm sending you a 4-hour Tokyo-Suntory-Hall-NHK-Symphony-Mahler-1st — pull highlights with Mahler-1st-NHK-Suntory BGM.",
    "Uploading a 90-minute Tokyo-Suntory-Hall-NHK-Symphony-Beethoven-9th — please extract highlights with Beethoven-9th-NHK-Suntory BGM.",
    "Here's a 2-hour Seoul-Lotte-Concert-Hall-KBS-Symphony-Brahms-1st — cut highlights with Brahms-1st-KBS-Lotte BGM.",
    "I have a 3-hour Beijing-NCPA-China-Philharmonic-Tchaikovsky-5th — please pull highlights with Tchaikovsky-5th-China-Phil-NCPA BGM.",
    "Uploading a 4-hour Shanghai-Symphony-Hall-Shostakovich-10th — extract highlights with Shostakovich-10th-Shanghai-Symphony BGM.",
    "Here's a 90-minute Hong-Kong-Cultural-Centre-HK-Phil-Sibelius-1st — please cut highlights with Sibelius-1st-HK-Phil BGM.",
    "I'm sending you a 2-hour Singapore-Esplanade-SSO-Mahler-1st — pull highlights with Mahler-1st-Singapore-Symphony BGM.",
    "Uploading a 3-hour Sydney-Opera-House-SSO-Mahler-9th — please extract highlights with Mahler-9th-Sydney-Symphony BGM.",
    "Here's a 4-hour Melbourne-Hamer-Hall-MSO-Brahms-4th — cut highlights with Brahms-4th-Melbourne-Symphony BGM.",
    "I have a 90-minute Toronto-Roy-Thomson-Hall-TSO-Mahler-2nd — please pull highlights with Mahler-2nd-Toronto-Symphony BGM.",
    "Uploading a 2-hour Montreal-Maison-Symphonique-OSM-Bruckner-9th — extract highlights with Bruckner-9th-Montreal-Symphony BGM.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
