"""x15 extend_style SFT.
Chain: IntakeVideo → VideoExtend → StyleTransfer.
Trigger: upload + extend + style transfer. NO music/ambience/subtitle/compositor.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 30-second beach clip — extend to 90 seconds and convert to anime style.",
    "Here's a 45-second mountain clip — extend to 2 minutes and render in watercolor.",
    "I have a 1-minute road-trip clip — extend to 3 minutes and style as oil painting.",
    "Uploading a 30-second city-street clip — extend to 90 seconds and convert to cyberpunk anime.",
    "Here's a 45-second forest hike — extend to 2 minutes and style as Studio Ghibli.",
    "I'm sending you a 30-second cat reel — extend to 90 seconds and render as Pixar 3D.",
    "Uploading a 1-minute dog reel — extend to 3 minutes and style as comic book ink.",
    "Here's a 45-second beach-bonfire reel — extend to 2 minutes and convert to charcoal sketch.",
    "I have a 30-second autumn-park reel — extend to 90 seconds and style as Van Gogh painting.",
    "Uploading a 1-minute cherry-blossom reel — extend to 3 minutes and convert to Japanese woodblock.",
    "Here's a 30-second sunset clip — extend to 90 seconds and render as Bob-Ross oil painting.",
    "I'm sending you a 45-second hiking reel — extend to 2 minutes and style as Hudson-River-School painting.",
    "Uploading a 1-minute coastal drone shot — extend to 3 minutes and convert to Hokusai style.",
    "Here's a 30-second skater montage — extend to 90 seconds and render as graphic-novel ink.",
    "I have a 45-second yoga-flow demo — extend to 2 minutes and style as French Impressionist.",
    "Uploading a 1-minute kids-park reel — extend to 3 minutes and convert to Maurice-Sendak storybook.",
    "Here's a 30-second cooking reel — extend to 90 seconds and style as Norman-Rockwell illustration.",
    "I'm sending you a 45-second baking reel — extend to 2 minutes and render as vintage 1950s diner ad.",
    "Uploading a 1-minute farmers-market reel — extend to 3 minutes and convert to Dutch Old-Master still life.",
    "Here's a 30-second canoe-on-lake reel — extend to 90 seconds and style as Caspar-David-Friedrich Romantic.",
    "I have a 45-second alpine-cable-car reel — extend to 2 minutes and convert to Bavarian-folk-art illustration.",
    "Uploading a 1-minute Italian-piazza walk — extend to 3 minutes and style as Renaissance fresco.",
    "Here's a 30-second French-bistro clip — extend to 90 seconds and render as Toulouse-Lautrec poster.",
    "I'm sending you a 45-second Spanish-tapas reel — extend to 2 minutes and convert to Picasso-cubism.",
    "Uploading a 1-minute Greek-island reel — extend to 3 minutes and style as Greek-vase black-figure painting.",
    "Here's a 30-second Tokyo-night reel — extend to 90 seconds and render as Wong-Kar-wai cinematic.",
    "I have a 45-second Hong-Kong-harbor reel — extend to 2 minutes and convert to Wong-Kar-wai cinematic look.",
    "Uploading a 1-minute Bangkok-tuk-tuk reel — extend to 3 minutes and style as Thai-classical illustration.",
    "Here's a 30-second Hanoi-old-quarter reel — extend to 90 seconds and render as Vietnamese-folk illustration.",
    "I'm sending you a 45-second Mumbai-bazaar reel — extend to 2 minutes and convert to Indian-miniature Mughal style.",
    "Uploading a 1-minute Marrakesh-souk reel — extend to 3 minutes and style as Persian miniature.",
    "Here's a 30-second Berlin-night reel — extend to 90 seconds and render as German-Expressionist painting.",
    "I have a 45-second Paris-Montmartre reel — extend to 2 minutes and convert to a Toulouse-Lautrec poster.",
    "Uploading a 1-minute Amsterdam-canal reel — extend to 3 minutes and style as a Vermeer interior.",
    "Here's a 30-second Reykjavik-northern-lights reel — extend to 90 seconds and render as Icelandic-folk-art illustration.",
    # ── more upload + extend + style transfer requests (50) ──────────────
    "Uploading a 30-second city-park stroll — extend to 90 seconds and convert to Lichtenstein pop-art.",
    "Here's a 45-second supermarket-aisle reel — extend to 2 minutes and style as Andy-Warhol screenprint.",
    "I have a 1-minute alleyway reel — extend to 3 minutes and render as Banksy stencil graffiti.",
    "Uploading a 30-second street-dance reel — extend to 90 seconds and convert to Keith-Haring line art.",
    "Here's a 45-second graffiti-wall reel — extend to 2 minutes and style as Basquiat raw expressionism.",
    "I'm sending you a 30-second museum-staircase reel — extend to 90 seconds and render as M.C.-Escher impossible architecture.",
    "Uploading a 1-minute desert-dream reel — extend to 3 minutes and convert to Salvador-Dalí surrealism.",
    "Here's a 45-second cloudy-balcony reel — extend to 2 minutes and style as René-Magritte surrealism.",
    "I have a 30-second late-night-diner reel — extend to 90 seconds and render as Edward-Hopper Nighthawks.",
    "Uploading a 1-minute Pennsylvania-farmhouse reel — extend to 3 minutes and convert to Andrew-Wyeth tempera.",
    "Here's a 30-second Iowa-cornfield reel — extend to 90 seconds and style as Grant-Wood American-Gothic regionalism.",
    "I'm sending you a 45-second self-portrait close-up reel — extend to 2 minutes and render as Frida-Kahlo self-portrait.",
    "Uploading a 1-minute marketplace reel — extend to 3 minutes and convert to Diego-Rivera mural.",
    "Here's a 30-second wartime-memory reel — extend to 90 seconds and style as Orozco mural.",
    "I have a 45-second factory-floor reel — extend to 2 minutes and render as Siqueiros mural.",
    "Uploading a 1-minute studio-still-life reel — extend to 3 minutes and convert to Matisse cut-out.",
    "Here's a 30-second tropical-canopy reel — extend to 90 seconds and style as Henri-Rousseau jungle naïve.",
    "I'm sending you a 45-second Tahiti-beach reel — extend to 2 minutes and render as Paul-Gauguin tropical.",
    "Uploading a 1-minute Provence-orchard reel — extend to 3 minutes and convert to Cézanne Provençal still life.",
    "Here's a 30-second Sunday-park reel — extend to 90 seconds and style as Seurat pointillism.",
    "I have a 45-second Eragny-village reel — extend to 2 minutes and render as Pissarro impressionist landscape.",
    "Uploading a 1-minute Parisian-park reel — extend to 3 minutes and convert to Manet flat-color realism.",
    "Here's a 30-second ballet-rehearsal reel — extend to 90 seconds and style as Degas pastel.",
    "I'm sending you a 45-second Thames-night reel — extend to 2 minutes and render as Whistler Nocturne.",
    "Uploading a 1-minute Venice-canal reel — extend to 3 minutes and convert to Sargent watercolor.",
    "Here's a 30-second Maine-coast reel — extend to 90 seconds and style as Winslow-Homer marine watercolor.",
    "I have a 45-second mother-and-child reel — extend to 2 minutes and render as Mary-Cassatt impressionist.",
    "Uploading a 1-minute garden-party reel — extend to 3 minutes and convert to Berthe-Morisot impressionist.",
    "Here's a 30-second café-terrace reel — extend to 90 seconds and style as Pierre-Auguste-Renoir.",
    "I'm sending you a 45-second factory-protest reel — extend to 2 minutes and render as Käthe-Kollwitz expressionist drawing.",
    "Uploading a 1-minute studio-portrait reel — extend to 3 minutes and convert to Egon-Schiele angular expressionism.",
    "Here's a 30-second gallery-foyer reel — extend to 90 seconds and style as Klimt gold-leaf decorative.",
    "I have a 45-second poster-shop reel — extend to 2 minutes and render as Mucha Art-Nouveau.",
    "Uploading a 1-minute opium-den-illustration reel — extend to 3 minutes and convert to Aubrey-Beardsley Art-Nouveau.",
    "Here's a 30-second nursery-room reel — extend to 90 seconds and style as Walter-Crane storybook illustration.",
    "I'm sending you a 45-second tall-ship reel — extend to 2 minutes and render as Howard-Pyle Brandywine illustration.",
    "Uploading a 1-minute Treasure-Island reel — extend to 3 minutes and convert to N.C.-Wyeth illustration.",
    "Here's a 30-second twilight-castle reel — extend to 90 seconds and style as Maxfield-Parrish glow.",
    "I have a 45-second forest-fairy-tale reel — extend to 2 minutes and render as Arthur-Rackham ink-and-wash.",
    "Uploading a 1-minute Arabian-Nights reel — extend to 3 minutes and convert to Edmund-Dulac storybook.",
    "Here's a 30-second East-of-the-Sun reel — extend to 90 seconds and style as Kay-Nielsen storybook.",
    "I'm sending you a 45-second rabbit-warren reel — extend to 2 minutes and render as Beatrix-Potter watercolor.",
    "Uploading a 1-minute storybook-loose-line reel — extend to 3 minutes and convert to Quentin-Blake hand-drawn ink.",
    "Here's a 30-second whimsical-NY reel — extend to 90 seconds and style as Maira-Kalman illustration.",
    "I have a 45-second Manhattan-skyline reel — extend to 2 minutes and render as Saul-Steinberg New-Yorker line.",
    "Uploading a 1-minute underground-cafe reel — extend to 3 minutes and convert to R.-Crumb underground comix.",
    "Here's a 30-second Brussels-trip reel — extend to 90 seconds and style as Hergé Tintin ligne-claire.",
    "I'm sending you a 45-second sci-fi-corridor reel — extend to 2 minutes and render as Moebius European comics.",
    "Uploading a 1-minute Neo-Tokyo reel — extend to 3 minutes and convert to Otomo Akira manga.",
    "Here's a 30-second hospital-ward reel — extend to 90 seconds and style as Osamu-Tezuka manga.",
    # ── more upload + extend + style transfer requests (50) ──────────────
    "Uploading a 30-second arctic-glacier reel — extend to 90 seconds and convert to Caspar-David-Friedrich Romantic.",
    "Here's a 45-second desert-canyon reel — extend to 2 minutes and style as Frederic-Remington frontier.",
    "I have a 1-minute cattle-drive reel — extend to 3 minutes and render as Charles-Russell western.",
    "Uploading a 30-second saloon-interior reel — extend to 90 seconds and convert to N.C.-Wyeth illustration.",
    "Here's a 45-second lighthouse reel — extend to 2 minutes and style as Edward-Hopper solitude.",
    "I'm sending you a 30-second fishing-pier reel — extend to 90 seconds and render as Winslow-Homer marine.",
    "Uploading a 1-minute lonely-diner reel — extend to 3 minutes and convert to Hopper Nighthawks.",
    "Here's a 45-second pinball-arcade reel — extend to 2 minutes and overlay Wayne-Thiebaud cake-pop.",
    "I have a 30-second milkshake-counter reel — extend to 90 seconds and style as Wayne-Thiebaud.",
    "Uploading a 1-minute retro-gas-station reel — extend to 3 minutes and convert to Ed-Ruscha pop-art.",
    "Here's a 30-second Hollywood-sign reel — extend to 90 seconds and style as Ed-Ruscha.",
    "I'm sending you a 45-second swimming-pool reel — extend to 2 minutes and render as David-Hockney.",
    "Uploading a 1-minute LA-bungalow reel — extend to 3 minutes and convert to Hockney.",
    "Here's a 30-second concrete-overpass reel — extend to 90 seconds and style as Stephen-Shore.",
    "I have a 45-second roadside-motel reel — extend to 2 minutes and render as Stephen-Shore.",
    "Uploading a 1-minute midwest-farmhouse reel — extend to 3 minutes and convert to Andrew-Wyeth.",
    "Here's a 30-second New-England-saltbox reel — extend to 90 seconds and style as Andrew-Wyeth.",
    "I'm sending you a 45-second backyard-baseball reel — extend to 2 minutes and render as Edward-Hopper everyday.",
    "Uploading a 1-minute county-fair reel — extend to 3 minutes and convert to Thomas-Hart-Benton regionalism.",
    "Here's a 30-second boxing-ring reel — extend to 90 seconds and style as LeRoy-Neiman sport.",
    "I have a 45-second ski-slope reel — extend to 2 minutes and render as LeRoy-Neiman.",
    "Uploading a 1-minute horse-track reel — extend to 3 minutes and convert to LeRoy-Neiman.",
    "Here's a 30-second golf-fairway reel — extend to 90 seconds and style as LeRoy-Neiman.",
    "I'm sending you a 45-second tennis-court reel — extend to 2 minutes and render as LeRoy-Neiman.",
    "Uploading a 1-minute circus-tent reel — extend to 3 minutes and convert to Marc-Chagall.",
    "Here's a 30-second Russian-village reel — extend to 90 seconds and style as Marc-Chagall.",
    "I have a 45-second Jewish-shtetl reel — extend to 2 minutes and render as Chagall.",
    "Uploading a 1-minute Paris-rooftops reel — extend to 3 minutes and convert to Chagall.",
    "Here's a 30-second Russian-Christmas reel — extend to 90 seconds and style as Boris-Kustodiev.",
    "I'm sending you a 45-second winter-troika reel — extend to 2 minutes and render as Kustodiev.",
    "Uploading a 1-minute Russian-bathhouse reel — extend to 3 minutes and convert to Kustodiev.",
    "Here's a 30-second Russian-tea-table reel — extend to 90 seconds and style as Kustodiev.",
    "I have a 45-second Spanish-bullring reel — extend to 2 minutes and render as Joan-Miró.",
    "Uploading a 1-minute Spanish-fishing-village reel — extend to 3 minutes and convert to Joan-Miró.",
    "Here's a 30-second Valencian-vineyard reel — extend to 90 seconds and style as Joaquín-Sorolla light.",
    "I'm sending you a 45-second Beach-Valencia reel — extend to 2 minutes and render as Sorolla.",
    "Uploading a 1-minute Spanish-fountain reel — extend to 3 minutes and convert to Sorolla.",
    "Here's a 30-second Greek-temple reel — extend to 90 seconds and style as Lord-Leighton.",
    "I have a 45-second Roman-forum reel — extend to 2 minutes and render as Lawrence-Alma-Tadema.",
    "Uploading a 1-minute Pompeii-villa reel — extend to 3 minutes and convert to Alma-Tadema.",
    "Here's a 30-second Egyptian-pyramid reel — extend to 90 seconds and style as Edwin-Long Orientalist.",
    "I'm sending you a 45-second Cairo-bazaar reel — extend to 2 minutes and render as Jean-Léon-Gérôme Orientalist.",
    "Uploading a 1-minute Constantinople reel — extend to 3 minutes and convert to Gérôme.",
    "Here's a 30-second Algerian-courtyard reel — extend to 90 seconds and style as Gérôme.",
    "I have a 45-second Marseille-port reel — extend to 2 minutes and render as Paul-Signac pointillism.",
    "Uploading a 1-minute Saint-Tropez reel — extend to 3 minutes and convert to Signac.",
    "Here's a 30-second Le-Havre-harbor reel — extend to 90 seconds and style as Monet impression.",
    "I'm sending you a 45-second Giverny-water-lilies reel — extend to 2 minutes and render as Monet.",
    "Uploading a 1-minute Rouen-cathedral reel — extend to 3 minutes and convert to Monet.",
    "Here's a 30-second Argenteuil-river reel — extend to 90 seconds and style as Monet.",
    # ── more upload + extend + style transfer requests (50) ──────────────
    "Uploading a 30-second Tokyo-Akihabara-arcade reel — extend to 90 seconds and convert to Otomo manga.",
    "Here's a 45-second Harajuku-fashion reel — extend to 2 minutes and style as Yoshitomo-Nara.",
    "I have a 1-minute Asakusa-temple reel — extend to 3 minutes and render as Kawase-Hasui shin-hanga.",
    "Uploading a 30-second Yokohama-harbor reel — extend to 90 seconds and convert to Toulouse-Lautrec poster.",
    "Here's a 45-second Hiroshima-memorial reel — extend to 2 minutes and style as ink-wash monochrome.",
    "I'm sending you a 30-second Okinawa-shisa reel — extend to 90 seconds and render as Ryukyuan folk-illustration.",
    "Uploading a 1-minute Hokkaido-Ainu-village reel — extend to 3 minutes and convert to Ainu folk-illustration.",
    "Here's a 45-second Yogyakarta-Borobudur reel — extend to 2 minutes and style as Javanese relief.",
    "I have a 30-second Surakarta-keraton reel — extend to 90 seconds and render as Javanese Wayang.",
    "Uploading a 1-minute Aceh-Banda reel — extend to 3 minutes and convert to Acehnese mosque-tile.",
    "Here's a 30-second Padang-Bukittinggi reel — extend to 90 seconds and style as Minangkabau songket.",
    "I'm sending you a 45-second Tana-Toraja reel — extend to 2 minutes and render as Toraja tongkonan-art.",
    "Uploading a 1-minute Lake-Toba reel — extend to 3 minutes and convert to Batak ulos.",
    "Here's a 30-second Bali-Tanah-Lot reel — extend to 90 seconds and style as Balinese Kamasan.",
    "I have a 45-second Lombok-Sembalun reel — extend to 2 minutes and render as Sasak tenun.",
    "Uploading a 1-minute Sumba-Wairinding reel — extend to 3 minutes and convert to Sumba marapu.",
    "Here's a 30-second Timor-Leste reel — extend to 90 seconds and style as Timorese tais.",
    "I'm sending you a 45-second Papuan-Asmat reel — extend to 2 minutes and render as Asmat carving.",
    "Uploading a 1-minute Phong-Nha-cave reel — extend to 3 minutes and convert to Vietnamese cave-art.",
    "Here's a 30-second Ha-Long-Bay reel — extend to 90 seconds and style as Vietnamese folk-painting.",
    "I have a 45-second Hue-Imperial reel — extend to 2 minutes and render as Vietnamese imperial-art.",
    "Uploading a 1-minute Hoi-An-Bridge reel — extend to 3 minutes and convert to Vietnamese watercolor.",
    "Here's a 30-second Sapa-terraces reel — extend to 90 seconds and style as Hmong batik.",
    "I'm sending you a 45-second Luang-Prabang reel — extend to 2 minutes and render as Lao temple-mural.",
    "Uploading a 1-minute Siem-Reap-Bayon reel — extend to 3 minutes and convert to Khmer relief.",
    "Here's a 30-second Bagan-Pagodas reel — extend to 90 seconds and style as Burmese Buddhist illustration.",
    "I have a 45-second Inle-Lake reel — extend to 2 minutes and render as Burmese Pa-O folk.",
    "Uploading a 1-minute Cusco-Inca reel — extend to 3 minutes and convert to Andean textile.",
    "Here's a 30-second Sacred-Valley reel — extend to 90 seconds and style as Andean tapestry.",
    "I'm sending you a 45-second Lake-Titicaca reel — extend to 2 minutes and render as Aymara Uros.",
    "Uploading a 1-minute Salar-de-Uyuni reel — extend to 3 minutes and convert to Aymara salt-flat-art.",
    "Here's a 30-second Iguazú-Falls reel — extend to 90 seconds and style as Brazilian cordel woodcut.",
    "I have a 45-second Amazon-Manaus reel — extend to 2 minutes and render as Tikuna bark-painting.",
    "Uploading a 1-minute Lima-Plaza reel — extend to 3 minutes and convert to Cusqueña-school painting.",
    "Here's a 30-second Buenos-Aires-La-Boca reel — extend to 90 seconds and style as Quinquela-Martín.",
    "I'm sending you a 45-second Rio-Sugarloaf reel — extend to 2 minutes and render as Tarsila-do-Amaral.",
    "Uploading a 1-minute Salvador-Pelourinho reel — extend to 3 minutes and convert to Cândido-Portinari.",
    "Here's a 30-second Bahia-Recôncavo reel — extend to 90 seconds and style as Brazilian cordel.",
    "I have a 45-second Cartagena-Walls reel — extend to 2 minutes and render as Fernando-Botero.",
    "Uploading a 1-minute Medellín-cable-car reel — extend to 3 minutes and convert to Botero rotund.",
    "Here's a 30-second Bogotá-Monserrate reel — extend to 90 seconds and style as Botero.",
    "I'm sending you a 45-second Quito-Old-Town reel — extend to 2 minutes and render as Oswaldo-Guayasamín.",
    "Uploading a 1-minute Galápagos-iguana reel — extend to 3 minutes and convert to Oswaldo-Guayasamín.",
    "Here's a 30-second Patagonia-glacier reel — extend to 90 seconds and style as Roberto-Matta surrealist.",
    "I have a 45-second Atacama-stargazing reel — extend to 2 minutes and render as Roberto-Matta.",
    "Uploading a 1-minute Chiloé-island reel — extend to 3 minutes and convert to Mapuche folk.",
    "Here's a 30-second Easter-Island reel — extend to 90 seconds and style as Rapa-Nui rongorongo.",
    "I'm sending you a 45-second Oaxaca-mercado reel — extend to 2 minutes and render as Rufino-Tamayo.",
    "Uploading a 1-minute Yucatán-cenote reel — extend to 3 minutes and convert to Mayan codex.",
    "Here's a 30-second Aztec-Tenochtitlan reel — extend to 90 seconds and style as Aztec codex.",
    # ── more Asian / Middle-Eastern / African landmark + regional art-style (50) ──
    "Uploading a 30-second Kyoto-bamboo reel — extend to 90 seconds and convert to Hokusai-ukiyoe.",
    "Here's a 45-second Mt-Fuji reel — extend to 2 minutes and render as Hokusai 36-views.",
    "I have a 1-minute Tokyo-Shibuya reel — extend to 3 minutes and style as Yoshitomo-Nara.",
    "Uploading a 30-second Osaka-castle reel — extend to 90 seconds and convert to Yoshitoshi ukiyoe.",
    "Here's a 45-second Nara-deer reel — extend to 2 minutes and render as Hiroshige.",
    "I'm sending you a 1-minute Kanazawa-garden reel — extend to 3 minutes and style as Rinpa school.",
    "Uploading a 30-second Hokkaido-snowscape reel — extend to 90 seconds and convert to Edo woodblock.",
    "Here's a 45-second Okinawa-beach reel — extend to 2 minutes and render as Bingata textile.",
    "I have a 1-minute Korean-DMZ reel — extend to 3 minutes and style as Joseon minhwa.",
    "Uploading a 30-second Seoul-Gyeongbokgung reel — extend to 90 seconds and convert to Korean folding-screen.",
    "Here's a 45-second Busan-shore reel — extend to 2 minutes and render as Kim-Hong-do genre.",
    "I'm sending you a 1-minute Jeju-haenyeo reel — extend to 3 minutes and style as Korean folk-painting.",
    "Uploading a 30-second Beijing-Forbidden-City reel — extend to 90 seconds and convert to Song-dynasty landscape.",
    "Here's a 45-second Suzhou-canals reel — extend to 2 minutes and render as Wang-Wei mountain-water.",
    "I have a 1-minute Hangzhou-West-Lake reel — extend to 3 minutes and style as Yuan-dynasty ink-wash.",
    "Uploading a 30-second Guilin-karst reel — extend to 90 seconds and convert to Lingnan school.",
    "Here's a 45-second Chongqing-skyline reel — extend to 2 minutes and render as Liu-Wei-contemporary.",
    "I'm sending you a 1-minute Xi'an-warrior reel — extend to 3 minutes and style as Tang dunhuang fresco.",
    "Uploading a 30-second Yangtze-Three-Gorges reel — extend to 90 seconds and convert to Ming landscape.",
    "Here's a 45-second Hong-Kong-skyline reel — extend to 2 minutes and render as Wucius-Wong.",
    "I have a 1-minute Taipei-night-market reel — extend to 3 minutes and style as Lin-Hwai-min.",
    "Uploading a 30-second Tainan-temple reel — extend to 90 seconds and convert to Taiwanese folk-painting.",
    "Here's a 45-second Macau-old-town reel — extend to 2 minutes and render as Macanese azulejo.",
    "I'm sending you a 1-minute Hanoi-Hoan-Kiem reel — extend to 3 minutes and style as Đông-Hồ folk-print.",
    "Uploading a 30-second Hue-Imperial-City reel — extend to 90 seconds and convert to Vietnamese-court silk-painting.",
    "Here's a 45-second Hoi-An-lantern reel — extend to 2 minutes and render as Vietnamese-lacquer.",
    "I have a 1-minute Saigon-rooftop reel — extend to 3 minutes and style as Vietnamese-modern silk.",
    "Uploading a 30-second Phnom-Penh-palace reel — extend to 90 seconds and convert to Khmer-mural.",
    "Here's a 45-second Angkor-bas-relief reel — extend to 2 minutes and render as Khmer bas-relief.",
    "I'm sending you a 1-minute Vientiane-stupa reel — extend to 3 minutes and style as Lao temple-mural.",
    "Uploading a 30-second Yangon-pagoda reel — extend to 90 seconds and convert to Burmese-mural.",
    "Here's a 45-second Bagan-temples reel — extend to 2 minutes and render as Bagan mural.",
    "I have a 1-minute Bangkok-Wat-Pho reel — extend to 3 minutes and style as Thai-mural.",
    "Uploading a 30-second Chiang-Mai-tribal reel — extend to 90 seconds and convert to Lanna mural.",
    "Here's a 45-second Bali-rice-paddy reel — extend to 2 minutes and render as Balinese Pita-Maha.",
    "I'm sending you a 1-minute Yogyakarta-Borobudur reel — extend to 3 minutes and style as Borobudur bas-relief.",
    "Uploading a 30-second Kuala-Lumpur-Petronas reel — extend to 90 seconds and convert to Malaysian-songket.",
    "Here's a 45-second Singapore-Marina-Bay reel — extend to 2 minutes and render as Liu-Kang-Nanyang.",
    "I have a 1-minute Mumbai-Ganesha-procession reel — extend to 3 minutes and style as Madhubani folk.",
    "Uploading a 30-second Delhi-Red-Fort reel — extend to 90 seconds and convert to Mughal miniature.",
    "Here's a 45-second Jaipur-pink-city reel — extend to 2 minutes and render as Rajput miniature.",
    "I'm sending you a 1-minute Varanasi-ghats reel — extend to 3 minutes and style as Pichvai painting.",
    "Uploading a 30-second Kolkata-Kalighat reel — extend to 90 seconds and convert to Kalighat Pat.",
    "Here's a 45-second Goa-coast reel — extend to 2 minutes and render as Goa azulejo.",
    "I have a 1-minute Tehran-bazaar reel — extend to 3 minutes and style as Persian miniature.",
    "Uploading a 30-second Isfahan-mosque reel — extend to 90 seconds and convert to Persian Safavid tile.",
    "Here's a 45-second Istanbul-Süleymaniye reel — extend to 2 minutes and render as Iznik tile.",
    "I'm sending you a 1-minute Cappadocia-balloon reel — extend to 3 minutes and style as Turkish-miniature.",
    "Uploading a 30-second Cairo-pyramid reel — extend to 90 seconds and convert to Egyptian-tomb-painting.",
    "Here's a 45-second Marrakesh-souk reel — extend to 2 minutes and render as Moroccan zellij.",
    # ── more aerial / wildlife / nature reels + naturalist art (50) ──
    "Uploading a 30-second Serengeti-migration aerial reel — extend to 90 seconds and convert to Audubon-Birds-of-America.",
    "Here's a 45-second Okavango-delta aerial reel — extend to 2 minutes and render as Sibley field-guide.",
    "I have a 1-minute Maasai-Mara wildebeest-crossing reel — extend to 3 minutes and style as Wilhelm-Kuhnert big-game.",
    "Uploading a 30-second Etosha-pan elephant-herd reel — extend to 90 seconds and convert to Carl-Brenders wildlife.",
    "Here's a 45-second Chobe-river hippo reel — extend to 2 minutes and render as Charley-Harper minimalist-fauna.",
    "I'm sending you a 1-minute Kruger-Park leopard reel — extend to 3 minutes and style as Robert-Bateman wildlife.",
    "Uploading a 30-second Madagascar-lemur reel — extend to 90 seconds and convert to Edward-Lear menagerie.",
    "Here's a 45-second Galápagos-tortoise reel — extend to 2 minutes and render as Darwin-Beagle-sketchbook.",
    "I have a 1-minute Amazon-canopy reel — extend to 3 minutes and style as Henri-Rousseau jungle.",
    "Uploading a 30-second Pantanal-jaguar reel — extend to 90 seconds and convert to Pantanal-naturalist plate.",
    "Here's a 45-second Iguazu-falls aerial reel — extend to 2 minutes and render as Frederic-Edwin-Church Andes-2.",
    "I'm sending you a 1-minute Andes-condor reel — extend to 3 minutes and style as Andean-naturalist plate.",
    "Uploading a 30-second Patagonia-glacier-calving reel — extend to 90 seconds and convert to Bierstadt sublime.",
    "Here's a 45-second Yellowstone-geyser-basin reel — extend to 2 minutes and render as Thomas-Moran luminist.",
    "I have a 1-minute Yosemite-Half-Dome aerial reel — extend to 3 minutes and style as Ansel-Adams-monochrome.",
    "Uploading a 30-second Grand-Canyon-Colorado-river reel — extend to 90 seconds and convert to William-Henry-Holmes panorama.",
    "Here's a 45-second Acadia-coastal reel — extend to 2 minutes and render as Marsden-Hartley Maine.",
    "I'm sending you a 1-minute Adirondack-fall-foliage reel — extend to 3 minutes and style as Hudson-River-school.",
    "Uploading a 30-second Everglades-airboat reel — extend to 90 seconds and convert to John-James-Audubon Florida.",
    "Here's a 45-second Big-Sur-coast reel — extend to 2 minutes and render as Edward-Weston-monochrome.",
    "I have a 1-minute Olympic-Peninsula-rainforest reel — extend to 3 minutes and style as Pacific-Northwest naturalist.",
    "Uploading a 30-second Glacier-National-Park aerial reel — extend to 90 seconds and convert to Charles-Russell wildlife.",
    "Here's a 45-second Banff-Lake-Louise reel — extend to 2 minutes and render as Lawren-Harris-Group-of-Seven-2.",
    "I'm sending you a 1-minute Algonquin-park canoe reel — extend to 3 minutes and style as Tom-Thomson Algonquin-2.",
    "Uploading a 30-second Bay-of-Fundy tide reel — extend to 90 seconds and convert to Maritime-naturalist watercolor.",
    "Here's a 45-second Newfoundland-puffin reel — extend to 2 minutes and render as Audubon-puffin plate.",
    "I have a 1-minute Iceland-Vatnajökull aerial reel — extend to 3 minutes and style as Icelandic-naturalist plate.",
    "Uploading a 30-second Lofoten-archipelago reel — extend to 90 seconds and convert to Nikolai-Astrup mountain.",
    "Here's a 45-second Norwegian-fjord reel — extend to 2 minutes and render as J.C.-Dahl Romantic-Norwegian.",
    "I'm sending you a 1-minute Faroe-Islands sheep reel — extend to 3 minutes and style as Faroese-naturalist plate.",
    "Uploading a 30-second Galway-Connemara reel — extend to 90 seconds and convert to Paul-Henry-Connemara.",
    "Here's a 45-second Yorkshire-Dales reel — extend to 2 minutes and render as David-Hockney Yorkshire.",
    "I have a 1-minute Tuscany-vineyard aerial reel — extend to 3 minutes and style as Tuscan-naturalist plate.",
    "Uploading a 30-second Provence-lavender aerial reel — extend to 90 seconds and convert to Van-Gogh Provence-2.",
    "Here's a 45-second Loire-Valley castle reel — extend to 2 minutes and render as Heures-Très-Riches-de-Berry.",
    "I'm sending you a 1-minute Black-Forest deer reel — extend to 3 minutes and style as Hans-Thoma forest.",
    "Uploading a 30-second Carpathian-bear reel — extend to 90 seconds and convert to Carpathian-naturalist plate.",
    "Here's a 45-second Polish-Białowieża bison reel — extend to 2 minutes and render as Bison-naturalist plate.",
    "I have a 1-minute Russian-Kamchatka-volcano aerial reel — extend to 3 minutes and style as Vasily-Vereshchagin.",
    "Uploading a 30-second Siberian-tiger reel — extend to 90 seconds and convert to Russian-naturalist plate.",
    "Here's a 45-second Mongolian-Gobi camel reel — extend to 2 minutes and render as Mongolian-naturalist plate.",
    "I'm sending you a 1-minute Himalayan-snow-leopard reel — extend to 3 minutes and style as Himalayan-naturalist plate.",
    "Uploading a 30-second Sundarbans tiger-mangrove reel — extend to 90 seconds and convert to Bengali-naturalist plate.",
    "Here's a 45-second Ranthambore-tiger reel — extend to 2 minutes and render as Indian-court-naturalist miniature.",
    "I have a 1-minute Borneo-orangutan-canopy reel — extend to 3 minutes and style as Bornean-naturalist plate.",
    "Uploading a 30-second Komodo-island-dragon reel — extend to 90 seconds and convert to Komodo-naturalist plate.",
    "Here's a 45-second Great-Barrier-Reef aerial reel — extend to 2 minutes and render as Coral-Sea-naturalist plate.",
    "I'm sending you a 1-minute Tasmanian-rainforest reel — extend to 3 minutes and style as John-Glover-Tasmanian.",
    "Uploading a 30-second Antarctic-Adelie-penguin reel — extend to 90 seconds and convert to Antarctic-naturalist plate.",
    "Here's a 45-second Arctic-narwhal reel — extend to 2 minutes and render as Arctic-naturalist plate.",
    # ── more travel/architecture reels + watercolor/sketch styles (50) ──
    "Uploading a 30-second Venice-Grand-Canal-gondola reel — extend to 90 seconds and convert to Turner-watercolor.",
    "Here's a 45-second Paris-Eiffel-Tower-base reel — extend to 2 minutes and render as Édouard-Cortès-Paris.",
    "I have a 1-minute Rome-Spanish-Steps reel — extend to 3 minutes and style as Piranesi-etching.",
    "Uploading a 30-second Florence-Ponte-Vecchio reel — extend to 90 seconds and convert to Florentine-watercolor.",
    "Here's a 45-second Naples-bay-Vesuvius reel — extend to 2 minutes and render as Hackert-veduta.",
    "I'm sending you a 1-minute Amalfi-coast-cliffs reel — extend to 3 minutes and style as Sorrentine-watercolor.",
    "Uploading a 30-second Cinque-Terre-village reel — extend to 90 seconds and convert to Ligurian-watercolor.",
    "Here's a 45-second Lake-Como-villa reel — extend to 2 minutes and render as Lombard-watercolor.",
    "I have a 1-minute Dolomites-pass reel — extend to 3 minutes and style as Tirolese-sketch.",
    "Uploading a 30-second Salzburg-Old-Town reel — extend to 90 seconds and convert to Mozart-era-watercolor.",
    "Here's a 45-second Vienna-Schönbrunn-garden reel — extend to 2 minutes and render as Viennese-watercolor.",
    "I'm sending you a 1-minute Hallstatt-village reel — extend to 3 minutes and style as Salzkammergut-sketch.",
    "Uploading a 30-second Český-Krumlov-castle reel — extend to 90 seconds and convert to Bohemian-watercolor.",
    "Here's a 45-second Prague-Charles-Bridge reel — extend to 2 minutes and render as Vyšehrad-watercolor.",
    "I have a 1-minute Budapest-Fisherman's-Bastion reel — extend to 3 minutes and style as Magyar-sketch.",
    "Uploading a 30-second Krakow-Wawel-Castle reel — extend to 90 seconds and convert to Polish-watercolor.",
    "Here's a 45-second Tallinn-Old-Town reel — extend to 2 minutes and render as Hanseatic-watercolor.",
    "I'm sending you a 1-minute Riga-Art-Nouveau-quarter reel — extend to 3 minutes and style as Riga-watercolor.",
    "Uploading a 30-second Vilnius-Užupis reel — extend to 90 seconds and convert to Vilnius-watercolor.",
    "Here's a 45-second Saint-Petersburg-Hermitage reel — extend to 2 minutes and render as Imperial-Russian-watercolor.",
    "I have a 1-minute Moscow-Red-Square reel — extend to 3 minutes and style as Russian-poster-art.",
    "Uploading a 30-second Bergen-Bryggen reel — extend to 90 seconds and convert to Norwegian-watercolor.",
    "Here's a 45-second Lofoten-fishing-village reel — extend to 2 minutes and render as Lofoten-sketch.",
    "I'm sending you a 1-minute Faroe-Islands-cliffs reel — extend to 3 minutes and style as Faroese-watercolor.",
    "Uploading a 30-second Stockholm-archipelago reel — extend to 90 seconds and convert to Swedish-watercolor.",
    "Here's a 45-second Copenhagen-Nyhavn reel — extend to 2 minutes and render as Danish-watercolor.",
    "I have a 1-minute Aarhus-old-town reel — extend to 3 minutes and style as Jutland-sketch.",
    "Uploading a 30-second Bruges-canal reel — extend to 90 seconds and convert to Flemish-watercolor.",
    "Here's a 45-second Ghent-Korenlei reel — extend to 2 minutes and render as Ghent-watercolor.",
    "I'm sending you a 1-minute Amsterdam-canal-belt reel — extend to 3 minutes and style as Dutch-Golden-Age-watercolor.",
    "Uploading a 30-second Delft-blue-pottery-quarter reel — extend to 90 seconds and convert to Delft-blue-watercolor.",
    "Here's a 45-second Haarlem-Grote-Markt reel — extend to 2 minutes and render as Haarlem-watercolor.",
    "I have a 1-minute Edinburgh-Royal-Mile reel — extend to 3 minutes and style as Scottish-Romantic-watercolor.",
    "Uploading a 30-second Skye-Quiraing reel — extend to 90 seconds and convert to Hebridean-watercolor.",
    "Here's a 45-second Dublin-Trinity-College reel — extend to 2 minutes and render as Georgian-Dublin-watercolor.",
    "I'm sending you a 1-minute Galway-Latin-Quarter reel — extend to 3 minutes and style as Connemara-sketch.",
    "Uploading a 30-second Cork-English-Market reel — extend to 90 seconds and convert to Cork-watercolor.",
    "Here's a 45-second Lisbon-Alfama-tram reel — extend to 2 minutes and render as Portuguese-azulejo-style.",
    "I have a 1-minute Porto-Ribeira reel — extend to 3 minutes and style as Porto-watercolor.",
    "Uploading a 30-second Madeira-Funchal reel — extend to 90 seconds and convert to Madeira-watercolor.",
    "Here's a 45-second Seville-Plaza-de-España reel — extend to 2 minutes and render as Andalusian-watercolor.",
    "I'm sending you a 1-minute Granada-Alhambra reel — extend to 3 minutes and style as Moorish-watercolor.",
    "Uploading a 30-second Cordoba-Mezquita reel — extend to 90 seconds and convert to Cordoba-watercolor.",
    "Here's a 45-second Toledo-old-town reel — extend to 2 minutes and render as El-Greco-Toledo.",
    "I have a 1-minute Salamanca-Plaza-Mayor reel — extend to 3 minutes and style as Castilian-watercolor.",
    "Uploading a 30-second Marrakesh-Jemaa-el-Fnaa reel — extend to 90 seconds and convert to Orientalist-watercolor.",
    "Here's a 45-second Fes-medina-tannery reel — extend to 2 minutes and render as Moroccan-watercolor.",
    "I'm sending you a 1-minute Chefchaouen-blue-walls reel — extend to 3 minutes and style as Moroccan-watercolor-2.",
    "Uploading a 30-second Petra-Treasury reel — extend to 90 seconds and convert to Roberts-Petra-lithograph.",
    "Here's a 45-second Wadi-Rum-desert reel — extend to 2 minutes and render as Lawrence-of-Arabia-sketch.",
    # ── more rural-countryside / agricultural reels + Impressionist/Post-Impressionist styles (50) ──
    "Uploading a 30-second Provence-lavender-field reel — extend to 90 seconds and convert to Van-Gogh-Provence.",
    "Here's a 45-second Arles-sunflower-field reel — extend to 2 minutes and render as Van-Gogh-Sunflowers.",
    "I have a 1-minute Saint-Rémy-olive-grove reel — extend to 3 minutes and style as Van-Gogh-Olive-Trees.",
    "Uploading a 30-second Auvers-sur-Oise-wheat-field reel — extend to 90 seconds and convert to Van-Gogh-Wheat-Field-with-Crows.",
    "Here's a 45-second Giverny-water-lily-pond reel — extend to 2 minutes and render as Monet-Water-Lilies.",
    "I'm sending you a 1-minute Giverny-Japanese-bridge reel — extend to 3 minutes and style as Monet-Japanese-Bridge.",
    "Uploading a 30-second Argenteuil-Seine-bank reel — extend to 90 seconds and convert to Monet-Argenteuil.",
    "Here's a 45-second Honfleur-port reel — extend to 2 minutes and render as Boudin-Honfleur.",
    "I have a 1-minute Étretat-cliffs reel — extend to 3 minutes and style as Monet-Étretat.",
    "Uploading a 30-second Pont-Aven-Brittany reel — extend to 90 seconds and convert to Gauguin-Pont-Aven.",
    "Here's a 45-second Tahitian-beach reel — extend to 2 minutes and render as Gauguin-Tahiti.",
    "I'm sending you a 1-minute Mont-Sainte-Victoire reel — extend to 3 minutes and style as Cézanne-Mont-Sainte-Victoire.",
    "Uploading a 30-second L'Estaque-cove reel — extend to 90 seconds and convert to Cézanne-L'Estaque.",
    "Here's a 45-second Aix-en-Provence-Bibemus-quarry reel — extend to 2 minutes and render as Cézanne-Bibemus.",
    "I have a 1-minute Eragny-orchard reel — extend to 3 minutes and style as Pissarro-Eragny.",
    "Uploading a 30-second Pontoise-cabbage-field reel — extend to 90 seconds and convert to Pissarro-Pontoise.",
    "Here's a 45-second Louveciennes-village-road reel — extend to 2 minutes and render as Pissarro-Louveciennes.",
    "I'm sending you a 1-minute Île-Saint-Louis-Seine reel — extend to 3 minutes and style as Renoir-Île-Saint-Louis.",
    "Uploading a 30-second Cagnes-sur-Mer-olive-grove reel — extend to 90 seconds and convert to Renoir-Cagnes.",
    "Here's a 45-second Moulin-de-la-Galette-garden reel — extend to 2 minutes and render as Renoir-Moulin-de-la-Galette.",
    "I have a 1-minute Saint-Tropez-port reel — extend to 3 minutes and style as Signac-Saint-Tropez.",
    "Uploading a 30-second Collioure-fishing-village reel — extend to 90 seconds and convert to Derain-Collioure-Fauve.",
    "Here's a 45-second L'Estaque-port reel — extend to 2 minutes and render as Derain-L'Estaque-Fauve.",
    "I'm sending you a 1-minute Chatou-bridge reel — extend to 3 minutes and style as Vlaminck-Chatou-Fauve.",
    "Uploading a 30-second Les-Baux-de-Provence reel — extend to 90 seconds and convert to Provençal-Fauve.",
    "Here's a 45-second Vence-chapel reel — extend to 2 minutes and render as Matisse-Vence-Chapel.",
    "I have a 1-minute Nice-promenade reel — extend to 3 minutes and style as Matisse-Nice-Côte-d'Azur.",
    "Uploading a 30-second Tuscan-vineyard-Chianti reel — extend to 90 seconds and convert to Macchiaioli-Tuscan.",
    "Here's a 45-second Tuscan-cypress-road reel — extend to 2 minutes and render as Macchiaioli-cypress.",
    "I'm sending you a 1-minute Umbrian-hill-village reel — extend to 3 minutes and style as Umbrian-Renaissance.",
    "Uploading a 30-second Apulian-trulli-field reel — extend to 90 seconds and convert to Apulian-naive.",
    "Here's a 45-second Sicilian-olive-grove reel — extend to 2 minutes and render as Sicilian-Macchiaioli.",
    "I have a 1-minute Sardinian-shepherd-meadow reel — extend to 3 minutes and style as Sardinian-modernist.",
    "Uploading a 30-second Catalan-Empordà-vineyard reel — extend to 90 seconds and convert to Dali-Empordà.",
    "Here's a 45-second Cadaqués-cove reel — extend to 2 minutes and render as Dali-Cadaqués.",
    "I'm sending you a 1-minute Mallorca-Tramuntana reel — extend to 3 minutes and style as Mallorcan-impressionist.",
    "Uploading a 30-second Andalusian-Cortijo-olive-grove reel — extend to 90 seconds and convert to Sorolla-Andalusian.",
    "Here's a 45-second Valencian-orange-grove reel — extend to 2 minutes and render as Sorolla-Valencian-orange.",
    "I have a 1-minute Galician-rias-coastline reel — extend to 3 minutes and style as Sorolla-Galician.",
    "Uploading a 30-second Alentejo-cork-oak reel — extend to 90 seconds and convert to Portuguese-Alentejo.",
    "Here's a 45-second Douro-Valley-vineyard reel — extend to 2 minutes and render as Douro-modernist.",
    "I'm sending you a 1-minute Madeira-terraced-vineyard reel — extend to 3 minutes and style as Madeira-naive.",
    "Uploading a 30-second Highland-glen-Scotland reel — extend to 90 seconds and convert to Glasgow-Boys-Scottish.",
    "Here's a 45-second Yorkshire-Dales reel — extend to 2 minutes and render as British-Newlyn-School.",
    "I have a 1-minute Cornwall-St-Ives-cove reel — extend to 3 minutes and style as St-Ives-School.",
    "Uploading a 30-second Lake-District-fells reel — extend to 90 seconds and convert to Lakeland-Romantic.",
    "Here's a 45-second Connemara-bog reel — extend to 2 minutes and render as Yeats-Connemara.",
    "I'm sending you a 1-minute Achill-Island-cliff reel — extend to 3 minutes and style as Achill-Irish-modernist.",
    "Uploading a 30-second Black-Forest-Schwarzwald reel — extend to 90 seconds and convert to German-Heimat-painting.",
    "Here's a 45-second Bavarian-Alpine-meadow reel — extend to 2 minutes and render as Spitzweg-Biedermeier.",
    # ── more food / still-life cuisine reels + Dutch-Golden-Age still-life / vanitas styles (50) ──
    "Uploading a 30-second cheese-platter-charcuterie reel — extend to 90 seconds and convert to Pieter-Claesz-still-life.",
    "Here's a 45-second oyster-platter reel — extend to 2 minutes and render as Willem-Claesz-Heda-oyster.",
    "I have a 1-minute lobster-platter reel — extend to 3 minutes and style as Frans-Snyders-still-life.",
    "Uploading a 30-second venison-game reel — extend to 90 seconds and convert to Jan-Weenix-game.",
    "Here's a 45-second pheasant-still-life reel — extend to 2 minutes and render as Jan-Fyt-game.",
    "I'm sending you a 1-minute fruit-bowl reel — extend to 3 minutes and style as Caravaggio-fruit-basket.",
    "Uploading a 30-second peach-and-grape-bowl reel — extend to 90 seconds and convert to Jan-Davidsz-de-Heem-fruit.",
    "Here's a 45-second tulip-bouquet reel — extend to 2 minutes and render as Ambrosius-Bosschaert-tulip.",
    "I have a 1-minute peony-and-iris-bouquet reel — extend to 3 minutes and style as Jan-Brueghel-flower.",
    "Uploading a 30-second mixed-bouquet-vase reel — extend to 90 seconds and convert to Rachel-Ruysch-bouquet.",
    "Here's a 45-second forest-flower-bouquet reel — extend to 2 minutes and render as Jan-van-Huysum-floral.",
    "I'm sending you a 1-minute breakfast-table-still-life reel — extend to 3 minutes and style as Floris-van-Dyck-breakfast.",
    "Uploading a 30-second herring-and-bread reel — extend to 90 seconds and convert to Pieter-Claesz-herring.",
    "Here's a 45-second pewter-tankard-still-life reel — extend to 2 minutes and render as Willem-Kalf-pronkstilleven.",
    "I have a 1-minute Chinese-porcelain-still-life reel — extend to 3 minutes and style as Willem-Kalf-Chinese-porcelain.",
    "Uploading a 30-second silver-pitcher-still-life reel — extend to 90 seconds and convert to Abraham-van-Beyeren-pronkstilleven.",
    "Here's a 45-second nautilus-cup-still-life reel — extend to 2 minutes and render as Pieter-de-Ring-nautilus-cup.",
    "I'm sending you a 1-minute lemon-peel-still-life reel — extend to 3 minutes and style as Willem-Heda-lemon.",
    "Uploading a 30-second oranges-still-life reel — extend to 90 seconds and convert to Luis-Meléndez-Spanish-still-life.",
    "Here's a 45-second melon-and-figs reel — extend to 2 minutes and render as Luis-Meléndez-melon.",
    "I have a 1-minute pumpkin-and-squash reel — extend to 3 minutes and style as Cotán-quinces-cabbage.",
    "Uploading a 30-second crystal-decanter-still-life reel — extend to 90 seconds and convert to Zurbarán-crystal.",
    "Here's a 45-second pomegranate-still-life reel — extend to 2 minutes and render as Zurbarán-still-life.",
    "I'm sending you a 1-minute Spanish-bodegón-still-life reel — extend to 3 minutes and style as Velázquez-bodegón.",
    "Uploading a 30-second skull-and-candle-still-life reel — extend to 90 seconds and convert to Vanitas-Steenwyck.",
    "Here's a 45-second hourglass-and-book-still-life reel — extend to 2 minutes and render as Pieter-Claesz-vanitas.",
    "I have a 1-minute soap-bubbles-still-life reel — extend to 3 minutes and style as David-Bailly-vanitas.",
    "Uploading a 30-second melon-and-knife reel — extend to 90 seconds and convert to Juan-Sánchez-Cotán-bodegón.",
    "Here's a 45-second cabbage-and-quince reel — extend to 2 minutes and render as Cotán-cabbage-quince.",
    "I'm sending you a 1-minute Spanish-Sevillan-still-life reel — extend to 3 minutes and style as Antonio-de-Pereda-bodegón.",
    "Uploading a 30-second Italian-still-life-fish reel — extend to 90 seconds and convert to Recco-Neapolitan-fish.",
    "Here's a 45-second Italian-vegetable-market-still-life reel — extend to 2 minutes and render as Vincenzo-Campi-fishmonger.",
    "I have a 1-minute Italian-lemon-bowl-still-life reel — extend to 3 minutes and style as Caravaggio-lemons.",
    "Uploading a 30-second French-pastry-still-life reel — extend to 90 seconds and convert to Chardin-pastry.",
    "Here's a 45-second French-game-still-life reel — extend to 2 minutes and render as Chardin-rabbit.",
    "I'm sending you a 1-minute French-still-life-jug reel — extend to 3 minutes and style as Chardin-glass-jug.",
    "Uploading a 30-second French-strawberry-bowl reel — extend to 90 seconds and convert to Chardin-strawberries.",
    "Here's a 45-second peach-and-grapes-still-life reel — extend to 2 minutes and render as Cézanne-peaches.",
    "I have a 1-minute apple-still-life reel — extend to 3 minutes and style as Cézanne-apples.",
    "Uploading a 30-second pear-and-knife-still-life reel — extend to 90 seconds and convert to Cézanne-pears.",
    "Here's a 45-second sunflower-still-life reel — extend to 2 minutes and render as Van-Gogh-sunflowers-vase.",
    "I'm sending you a 1-minute irises-still-life reel — extend to 3 minutes and style as Van-Gogh-irises-vase.",
    "Uploading a 30-second Tahitian-fruit-still-life reel — extend to 90 seconds and convert to Gauguin-Tahitian-fruits.",
    "Here's a 45-second guava-and-mango-still-life reel — extend to 2 minutes and render as Tropical-still-life.",
    "I have a 1-minute persimmon-and-pear-still-life reel — extend to 3 minutes and style as Mu-Qi-persimmon.",
    "Uploading a 30-second tea-set-and-sweets-still-life reel — extend to 90 seconds and convert to Wu-Changshuo-still-life.",
    "Here's a 45-second sushi-platter reel — extend to 2 minutes and render as Hiroshige-still-life.",
    "I'm sending you a 1-minute ramen-bowl-still-life reel — extend to 3 minutes and style as Yoshitoshi-still-life.",
    "Uploading a 30-second tagine-platter reel — extend to 90 seconds and convert to Moroccan-still-life.",
    "Here's a 45-second mezze-platter reel — extend to 2 minutes and render as Levantine-still-life.",
    # ── more pet/animal candids + Ukiyo-e / Edo woodblock styles (50) ──
    "I have a 1-minute koi-pond-feeding reel — extend to 3 minutes and style as Hokusai-koi.",
    "Uploading a 30-second tabby-cat-window-perch reel — extend to 90 seconds and convert to Kuniyoshi-cat-print.",
    "Here's a 45-second Shiba-Inu-park-walk reel — extend to 2 minutes and render as Hiroshige-Edo-print.",
    "I'm sending you a 1-minute orange-cat-tatami-nap reel — extend to 3 minutes and style as Yoshitoshi-print.",
    "Uploading a 30-second crane-pond-stilling reel — extend to 90 seconds and convert to Hokusai-crane.",
    "Here's a 45-second sparrow-rooftop-flock reel — extend to 2 minutes and render as Hiroshige-sparrow.",
    "I have a 1-minute mountain-monkey-onsen reel — extend to 3 minutes and style as Mori-Sosen-monkey.",
    "Uploading a 30-second deer-Nara-park reel — extend to 90 seconds and convert to Maruyama-Okyo-deer.",
    "Here's a 45-second turtle-Kamogawa-river reel — extend to 2 minutes and render as Kawanabe-Kyosai-turtle.",
    "I'm sending you a 1-minute peacock-courtyard-display reel — extend to 3 minutes and style as Ito-Jakuchu-peacock.",
    "Uploading a 30-second rooster-courtyard-stride reel — extend to 90 seconds and convert to Ito-Jakuchu-rooster.",
    "Here's a 45-second tiger-zoo-pace reel — extend to 2 minutes and render as Maruyama-Okyo-tiger.",
    "I have a 1-minute snow-leopard-zoo reel — extend to 3 minutes and style as Ohara-Koson-snow-leopard.",
    "Uploading a 30-second swan-pond-glide reel — extend to 90 seconds and convert to Ohara-Koson-swan.",
    "Here's a 45-second mandarin-duck-pond reel — extend to 2 minutes and render as Ohara-Koson-mandarin-duck.",
    "I'm sending you a 1-minute heron-marsh-stilt reel — extend to 3 minutes and style as Hiroaki-Takahashi-heron.",
    "Uploading a 30-second crow-rooftop-walk reel — extend to 90 seconds and convert to Watanabe-Seitei-crow.",
    "Here's a 45-second eagle-cliff-perch reel — extend to 2 minutes and render as Watanabe-Seitei-eagle.",
    "I have a 1-minute owl-night-perch reel — extend to 3 minutes and style as Ohara-Koson-owl.",
    "Uploading a 30-second hawk-thermal-soar reel — extend to 90 seconds and convert to Watanabe-Seitei-hawk.",
    "Here's a 45-second pheasant-bamboo-grove reel — extend to 2 minutes and render as Imao-Keinen-pheasant.",
    "I'm sending you a 1-minute mountain-goat-cliff reel — extend to 3 minutes and style as Ohara-Koson-goat.",
    "Uploading a 30-second wild-boar-forest reel — extend to 90 seconds and convert to Mori-Sosen-boar.",
    "Here's a 45-second fox-snow-trot reel — extend to 2 minutes and render as Hiroaki-Takahashi-fox.",
    "I have a 1-minute raccoon-dog-paddy reel — extend to 3 minutes and style as Mori-Sosen-tanuki.",
    "Uploading a 30-second flying-squirrel-tree reel — extend to 90 seconds and convert to Watanabe-Seitei-squirrel.",
    "Here's a 45-second otter-river-swim reel — extend to 2 minutes and render as Ohara-Koson-otter.",
    "I'm sending you a 1-minute carp-banner-flutter reel — extend to 3 minutes and style as Hiroshige-koinobori.",
    "Uploading a 30-second dragonfly-pond-skim reel — extend to 90 seconds and convert to Hokusai-tonbo.",
    "Here's a 45-second cicada-tree-cling reel — extend to 2 minutes and render as Imao-Keinen-cicada.",
    "I have a 1-minute butterfly-iris-garden reel — extend to 3 minutes and style as Hokusai-butterfly.",
    "Uploading a 30-second firefly-rice-paddy reel — extend to 90 seconds and convert to Yoshitoshi-firefly.",
    "Here's a 45-second praying-mantis-leaf reel — extend to 2 minutes and render as Ito-Jakuchu-mantis.",
    "I'm sending you a 1-minute goldfish-bowl-swim reel — extend to 3 minutes and style as Hokusai-kingyo.",
    "Uploading a 30-second eel-river-bottom reel — extend to 90 seconds and convert to Kuniyoshi-unagi.",
    "Here's a 45-second octopus-tide-pool reel — extend to 2 minutes and render as Kuniyoshi-tako.",
    "I have a 1-minute squid-night-fishing reel — extend to 3 minutes and style as Hokusai-ika.",
    "Uploading a 30-second whale-bay-spout reel — extend to 90 seconds and convert to Kuniyoshi-kujira.",
    "Here's a 45-second dolphin-bay-pod reel — extend to 2 minutes and render as Hokusai-iruka.",
    "I'm sending you a 1-minute sea-turtle-coral reel — extend to 3 minutes and style as Hokusai-kame-coral.",
    "Uploading a 30-second sea-otter-kelp reel — extend to 90 seconds and convert to Ohara-Koson-rakko.",
    "Here's a 45-second penguin-Antarctic-march reel — extend to 2 minutes and render as Ohara-Koson-pengin.",
    "I have a 1-minute polar-bear-tundra reel — extend to 3 minutes and style as Watanabe-Seitei-shirokuma.",
    "Uploading a 30-second arctic-fox-tundra reel — extend to 90 seconds and convert to Hiroaki-Takahashi-hokkyokugitsune.",
    "Here's a 45-second gray-wolf-pack reel — extend to 2 minutes and render as Mori-Sosen-okami.",
    "I'm sending you a 1-minute lynx-snow-stalk reel — extend to 3 minutes and style as Ohara-Koson-yamaneko.",
    "Uploading a 30-second mountain-lion-cliff reel — extend to 90 seconds and convert to Maruyama-Okyo-puma.",
    "Here's a 45-second bald-eagle-river reel — extend to 2 minutes and render as Watanabe-Seitei-shirahawashi.",
    "I have a 1-minute albatross-cliff-soar reel — extend to 3 minutes and style as Ohara-Koson-ahodori.",
    "Uploading a 30-second flamingo-lagoon-flock reel — extend to 90 seconds and convert to Imao-Keinen-furamingo.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
