"""x15 extend_only — 14x SFT user_goal expansion pool.

Schema: USER_GOALS: list[str] (lightweight — rationale/intents are filled by
the templating engine in build_templated_sft_jsonl.py from
INTENT_VARIANTS + render_rationale; chain is fixed by blueprint).

Blueprint target: 50 originals × 14 = 700 new user_goals.
Topics deliberately disjoint from raw_samples/shape_extend_only.py originals
(waves crashing / drone mountain ridge / cat yawning / fireworks / skateboard
trick / etc.). Each goal is a SHORT brief (no full-story long inputs — extend
shape has long_story_n=0).
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    # ── nature / weather (50) ─────────────────────────────────────────────
    "Got a 6-second clip of fog rolling over a forest at dawn. Could you extend it to about 25 seconds so I can use it as a cinematic transition shot?",
    "Here's a 9-second sunrise time-lapse over the ocean — please stretch it to roughly 45 seconds for an intro card.",
    "I have a 12-second tide pulling back along a sandy beach. Can you extend it out to about a minute so the receding water keeps going?",
    "5-second clip of red autumn leaves drifting down — please extend to ~30 seconds for a fall-themed loop.",
    "8-second shot of sand dunes shifting in desert wind. Could you stretch this to around 35 seconds so the patterns keep evolving?",
    "Quick 7-second clip of slow-moving lava flow at night — extend to ~40 seconds for a science-channel B-roll.",
    "I shot 11 seconds of a glacier calving with a small ice chunk falling. Extend to 30 seconds with continued ice motion please.",
    "Got a 4-second clip of a geyser erupting — please grow it to about 20 seconds with the steam plume continuing.",
    "10-second timelapse of aurora borealis curtains. Stretch to roughly 60 seconds, keeping the same green ribbon motion.",
    "Here's a short 6-second clip of a comet streaking — please extend to ~25 seconds with the tail trailing behind.",
    "8-second shot of rain hitting a windowpane. Could you extend it to a calm 2-minute loop for a study session?",
    "12-second clip of a thunderstorm cloud rolling across the plains. Extend to about 50 seconds, please.",
    "I have 7 seconds of cherry blossoms falling — stretch to 30 seconds for a slow-motion intro.",
    "5-second clip of frost forming on a windowpane — please extend to about 25 seconds with the ice crystals continuing to grow.",
    "9-second clip of a tornado funnel touching down in the distance. Extend to ~40 seconds keeping the rotation.",
    "Got an 8-second clip of mist rising off a mountain lake. Could you make it about 50 seconds for a meditation app intro?",
    "10-second moonrise over a desert horizon. Please extend to roughly 60 seconds with continuous ascent.",
    "Here's 6 seconds of a rainbow forming after a storm. Stretch to 25 seconds, please.",
    "13-second clip of waves at a rocky shoreline. Extend to about 90 seconds for a desktop screensaver.",
    "Quick 4-second clip of a leaf landing on a still pond — please extend to ~20 seconds with the ripples expanding.",
    "11-second timelapse of clouds rolling over snow-capped peaks. Could you extend to 60 seconds, same direction?",
    "I shot 7 seconds of golden hour light through a wheat field. Extend to ~30 seconds keeping the warm tone.",
    "8-second clip of a meteor shower across a starfield — please make it about 60 seconds for a planetarium loop.",
    "Got a 5-second shot of a dewdrop sliding down a leaf — extend to ~20 seconds with the slow descent continuing.",
    "Here's 9 seconds of a forest path with sunbeams cutting through trees. Stretch to about 45 seconds, please.",
    "10-second clip of waves at a cliff base — extend to roughly 60 seconds for a dramatic landscape reel.",
    "6-second slow-mo of a single raindrop hitting a puddle. Please extend to ~25 seconds with continued droplet ripples.",
    "I have 12 seconds of fog drifting through a redwood grove. Could you extend to about 50 seconds?",
    "8-second clip of a rainbow over Niagara-style falls. Extend to ~35 seconds for a tourism reel.",
    "Quick 5-second clip of a snowflake landing on a glove. Stretch to ~22 seconds with more flakes drifting in.",
    "Here's 7 seconds of a hummingbird hovering at a feeder — please extend to ~30 seconds with continuous wing motion.",
    "11-second clip of bioluminescent waves at night. Extend to about 50 seconds for an ocean-doc segment.",
    "Got a 9-second clip of a thunderhead building over plains. Extend to 40 seconds with continued storm growth.",
    "10-second shot of hail bouncing off pavement. Please stretch to ~45 seconds with continuing hailfall.",
    "I shot 6 seconds of dandelion seeds being blown into the air. Extend to ~25 seconds, drifting away.",
    "8-second clip of a small waterfall in a moss-covered grotto. Extend to about 60 seconds for a yoga-class background.",
    "5-second slow-mo of a ripple expanding outward across a still lake. Please grow it to 25 seconds.",
    "Here's a 7-second clip of swirling autumn fog in a graveyard. Stretch to ~40 seconds for a Halloween intro.",
    "12-second clip of a frozen river thawing. Extend to ~75 seconds with progressing ice melt.",
    "Got a 4-second clip of a flower bud opening. Please extend to ~20 seconds completing the bloom.",
    "8-second shot of cumulus clouds growing in afternoon heat. Stretch to ~45 seconds.",
    "10-second clip of a rocky beach at low tide with crabs scuttling. Extend to ~50 seconds.",
    "9-second sunset over a mountain ridge, reds and purples. Could you extend to ~50 seconds?",
    "5-second shot of a single cherry blossom petal falling. Stretch to ~25 seconds, gently descending.",
    "Here's 7 seconds of mist hovering above a still bog. Extend to ~35 seconds for a fantasy-game cutscene.",
    "11-second clip of a slow zoom into a frozen waterfall. Stretch to 60 seconds, continued zoom.",
    "Got 6 seconds of a meteor trail dissipating across the night sky. Extend to 25 seconds, please.",
    "8-second shot of dawn light spreading across a city skyline. Extend to ~40 seconds.",
    "I have a 10-second clip of fireflies in a meadow at dusk. Could you stretch it to about 60 seconds?",
    "12-second clip of moonlight on rippling water — extend to ~75 seconds for a calm sleep-loop.",
    # ── animals / wildlife (50) ───────────────────────────────────────────
    "Here's a 5-second clip of a kingfisher diving for a fish — please extend to ~22 seconds with continued dives.",
    "Got 8 seconds of an octopus drifting through coral. Stretch to ~40 seconds for an aquarium display.",
    "I have 9 seconds of a deer grazing at the edge of a forest. Could you extend to ~45 seconds?",
    "6-second clip of moths circling a porch light at night. Please extend to ~25 seconds.",
    "Here's a 7-second clip of fireflies blinking in a backyard. Stretch to ~35 seconds for an evening reel.",
    "10-second clip of koi fish swimming under lily pads. Extend to ~60 seconds for a Japanese-garden BG.",
    "Got 5 seconds of a great horned owl turning its head. Please extend to ~20 seconds with continued head turns.",
    "8-second clip of a sloth slowly reaching for a leaf. Stretch to ~45 seconds, slow and steady.",
    "Here's 6 seconds of a leopard gecko climbing a branch. Extend to ~25 seconds.",
    "I shot 11 seconds of a manatee gliding through clear spring water. Extend to about 60 seconds.",
    "9-second clip of a swarm of starlings shaping a murmuration. Please stretch to 50 seconds.",
    "Got a 4-second clip of a chameleon's tongue catching a fly — extend to ~18 seconds with another catch.",
    "7-second clip of a bear cub chasing a butterfly. Stretch to ~30 seconds.",
    "12-second clip of penguins waddling across pack ice. Could you extend to ~70 seconds?",
    "5-second clip of a mantis shrimp striking a snail. Please extend to ~22 seconds with continued strikes.",
    "Here's 8 seconds of an octopus changing color and texture. Stretch to ~40 seconds.",
    "10-second clip of a flock of flamingos taking flight. Extend to ~50 seconds.",
    "Got 6 seconds of a fox stalking through tall grass. Stretch to ~30 seconds.",
    "9-second clip of a humpback whale breaching. Extend to ~45 seconds with another breach.",
    "I have a 4-second clip of a mantis cleaning its forelegs. Please extend to ~18 seconds.",
    "8-second clip of a sea turtle gliding over coral. Stretch to ~45 seconds for a dive-shop loop.",
    "Here's 7 seconds of a snow leopard padding across a rocky ridge. Extend to ~35 seconds.",
    "11-second clip of a colony of penguins huddling in blizzard. Stretch to ~60 seconds.",
    "5-second clip of a wolf howling at dusk. Please extend to ~22 seconds with continued howl.",
    "Got 10 seconds of jellyfish pulsing in deep water. Extend to ~50 seconds.",
    "9-second clip of a peacock fanning its tail. Stretch to ~40 seconds for a wildlife-channel intro.",
    "6-second clip of a toucan grooming its beak. Please extend to ~25 seconds.",
    "Here's 8 seconds of a cheetah running across the savanna. Extend to ~40 seconds, sustained sprint.",
    "12-second clip of orcas breaching in formation. Stretch to ~75 seconds for an ocean-doc cold open.",
    "Got 5 seconds of a sloth hanging upside down asleep. Extend to ~25 seconds, gently swaying.",
    "7-second clip of a pod of dolphins riding a bow wave. Please extend to ~35 seconds.",
    "10-second clip of bats emerging from a cave at dusk. Stretch to ~50 seconds with continued exit.",
    "Here's 6 seconds of a lemur leaping between trees. Extend to ~25 seconds with more leaps.",
    "I shot 9 seconds of a hawk circling a thermal. Could you extend to ~45 seconds?",
    "8-second clip of a giant tortoise plodding across a clearing. Stretch to ~45 seconds.",
    "5-second clip of a manta ray gliding overhead. Please extend to ~25 seconds.",
    "Got 7 seconds of a hummingbird drinking from a hibiscus. Stretch to ~30 seconds.",
    "12-second clip of monarch butterflies clustering on a tree. Extend to ~70 seconds.",
    "Here's 4 seconds of a praying mantis catching a moth. Please extend to ~20 seconds.",
    "9-second clip of an Arctic fox bounding through snow. Stretch to ~45 seconds.",
    "10-second clip of a coral-reef parade — clownfish, blue tang, anemones. Extend to ~55 seconds.",
    "Got 6 seconds of a great blue heron stalking shallow water. Extend to ~25 seconds.",
    "Here's 8 seconds of a snail traversing a wet leaf. Please stretch to ~50 seconds for a meditation loop.",
    "11-second clip of seagulls following a fishing boat. Stretch to ~55 seconds.",
    "5-second clip of an osprey snatching a fish. Please extend to ~22 seconds with another catch.",
    "8-second clip of a meerkat sentinel scanning the horizon. Extend to ~40 seconds.",
    "I have 7 seconds of a pangolin curling into its scales. Could you extend to ~30 seconds?",
    "10-second clip of a colony of ants moving a leaf. Stretch to ~50 seconds.",
    "Got 9 seconds of a snowy owl gliding low across a field. Extend to ~45 seconds.",
    "Here's 6 seconds of a baby otter being fed by its mother. Stretch to ~25 seconds.",
    # ── sports / human action (40) ────────────────────────────────────────
    "Here's an 8-second clip of a rower pulling against open water. Could you extend to ~40 seconds, sustained stroke?",
    "Got 5 seconds of an archer drawing and releasing. Please stretch to ~22 seconds with another release.",
    "9-second clip of a parkour jump across rooftops. Extend to ~45 seconds with continued course.",
    "10-second clip of a kendo bout in a dojo. Stretch to ~50 seconds with continued strikes.",
    "Here's 7 seconds of a breakdancer windmilling on cardboard. Extend to ~35 seconds.",
    "I shot 6 seconds of a gymnast on the balance beam. Please extend to ~30 seconds with continued routine.",
    "12-second clip of a rock climber on an overhang. Stretch to ~60 seconds, sustained climb.",
    "8-second clip of a surfer inside a tube. Extend to ~40 seconds with extended ride.",
    "Got 9 seconds of motocross over rough terrain. Please extend to ~45 seconds.",
    "5-second slow-mo of bowling pins falling. Stretch to ~22 seconds with another roll.",
    "11-second clip of a basketball pickup game. Extend to ~55 seconds with continued play.",
    "Here's 7 seconds of a soccer keeper diving for a save. Please extend to ~30 seconds with another save.",
    "10-second clip of a skater carving a half-pipe. Stretch to ~50 seconds.",
    "8-second clip of a cyclist taking a steep mountain switchback. Extend to ~40 seconds.",
    "Got 6 seconds of a fencer's lunge. Please extend to ~25 seconds with another exchange.",
    "9-second clip of a sprinter's start out of the blocks. Stretch to ~45 seconds, full-speed run.",
    "I have a 5-second clip of a high diver mid-twist. Please extend to ~22 seconds with another dive.",
    "8-second clip of a marathon-runner in the final 100m. Stretch to ~40 seconds, continued sprint.",
    "12-second clip of a kite-surfer cutting across waves. Extend to ~60 seconds.",
    "Here's 7 seconds of a yoga flow on a cliff at sunrise. Extend to ~35 seconds, continued flow.",
    "10-second clip of an ice-skater spinning. Stretch to ~50 seconds with sustained rotation.",
    "Got 6 seconds of a pole vaulter clearing the bar. Please extend to ~25 seconds with another attempt.",
    "8-second clip of a snowboarder carving fresh powder. Extend to ~40 seconds.",
    "5-second clip of a dancer leaping across a stage. Stretch to ~22 seconds.",
    "Here's 9 seconds of a baseball pitcher's wind-up and pitch. Extend to ~45 seconds with another pitch.",
    "11-second clip of a martial-arts kata in a courtyard. Stretch to ~55 seconds.",
    "7-second clip of a freediver descending along a rope. Please extend to ~35 seconds.",
    "10-second clip of beach volleyball — a spike-and-block sequence. Extend to ~50 seconds.",
    "Got 6 seconds of a runner cresting a mountain trail. Stretch to ~30 seconds.",
    "8-second clip of a tennis serve in slow-mo. Extend to ~40 seconds with another serve.",
    "Here's 5 seconds of a weightlifter's clean-and-jerk. Please extend to ~22 seconds with another lift.",
    "12-second clip of a CrossFit athlete on rowing erg. Stretch to ~60 seconds.",
    "9-second clip of a sumo bout in a clay ring. Extend to ~40 seconds with continued match.",
    "10-second clip of a parkour vault across a wall. Stretch to ~50 seconds with continued course.",
    "Got 7 seconds of a hockey player breaking away on a goalie. Please extend to ~30 seconds.",
    "5-second clip of a tightrope walker mid-balance. Stretch to ~25 seconds with sustained walk.",
    "8-second clip of a kayaker punching through whitewater. Extend to ~40 seconds.",
    "Here's 6 seconds of a free-runner rolling onto pavement. Please extend to ~25 seconds.",
    "11-second clip of an ultramarathoner along a desert ridge. Stretch to ~60 seconds.",
    "7-second clip of an Olympic diver entering the pool. Please extend to ~30 seconds with another dive.",
    # ── food / cooking (30) ───────────────────────────────────────────────
    "Got an 8-second clip of noodles being hand-pulled. Could you extend to ~40 seconds with continued pulls?",
    "Here's 6 seconds of dough rising in a glass bowl. Stretch to ~30 seconds for a kitchen-monitor loop.",
    "10-second clip of pizza dough being spun in the air. Extend to ~50 seconds with another spin.",
    "5-second clip of coffee blooming in a pour-over. Please extend to ~22 seconds.",
    "9-second clip of ice melting in a glass of black tea. Stretch to ~45 seconds, continued melt.",
    "8-second clip of butter melting on a hot skillet. Extend to ~40 seconds.",
    "Got 11 seconds of a cake being decorated with piped frosting. Extend to ~55 seconds with continued piping.",
    "7-second clip of sushi being rolled by hand. Stretch to ~30 seconds with another roll.",
    "Here's 5 seconds of espresso pouring into a cup. Please extend to ~22 seconds.",
    "12-second clip of dumplings being pleated by hand. Extend to ~60 seconds with more dumplings.",
    "8-second clip of a chef chopping scallions rapidly. Stretch to ~35 seconds.",
    "6-second clip of crème brûlée being torched. Please extend to ~25 seconds with another torch pass.",
    "10-second clip of a rotating sushi belt at a restaurant. Extend to ~50 seconds, continued rotation.",
    "Got 5 seconds of a steak being seared in a cast-iron pan. Please extend to ~22 seconds.",
    "9-second clip of bread being kneaded on a floured counter. Stretch to ~40 seconds.",
    "8-second clip of a cocktail being poured over crushed ice. Extend to ~40 seconds.",
    "Here's 7 seconds of pasta being twirled around a fork. Please extend to ~30 seconds with continued twirls.",
    "11-second clip of a pour-over coffee dripping into a carafe. Stretch to ~55 seconds.",
    "6-second clip of a chocolate fountain cascading. Please extend to ~25 seconds.",
    "10-second clip of mochi being pounded with mallets. Extend to ~50 seconds with continued pounding.",
    "Got 8 seconds of a wok flambé in a Chinese kitchen. Stretch to ~40 seconds with more tosses.",
    "5-second clip of macarons being piped onto parchment. Please extend to ~22 seconds.",
    "Here's 9 seconds of a cheese wheel being cut at a market. Extend to ~45 seconds.",
    "12-second clip of a tea ceremony — water poured into a clay teapot. Stretch to ~60 seconds.",
    "7-second clip of churros being fried golden. Please extend to ~30 seconds.",
    "10-second clip of a barista making latte art. Extend to ~50 seconds with another pour.",
    "Got 6 seconds of a chef plating an entrée. Stretch to ~25 seconds.",
    "8-second clip of a hot-pot table boiling away. Extend to ~40 seconds.",
    "Here's 5 seconds of a macaron tower being constructed. Please extend to ~22 seconds.",
    "11-second clip of bread loaves emerging from a stone oven. Stretch to ~50 seconds.",
    # ── industrial / craft / making (40) ──────────────────────────────────
    "Here's an 8-second clip of a potter centering clay on a wheel. Could you extend to ~40 seconds with continued shaping?",
    "Got 6 seconds of a glassblower forming a hot glass bulb. Stretch to ~25 seconds.",
    "10-second clip of a welder laying a clean bead. Extend to ~50 seconds.",
    "9-second clip of a blacksmith forging a knife blade. Please extend to ~45 seconds with continued strikes.",
    "5-second clip of a weaver passing the shuttle on a loom. Stretch to ~22 seconds.",
    "Here's 7 seconds of a kiln door being opened to glowing ceramics. Extend to ~30 seconds.",
    "12-second clip of paper being made by hand on a screen. Stretch to ~55 seconds.",
    "8-second clip of candles being hand-dipped in colored wax. Extend to ~40 seconds with more dips.",
    "Got 10 seconds of a 3D printer extruding a complex lattice. Stretch to ~50 seconds.",
    "9-second clip of a lathe turning a wooden bowl. Please extend to ~45 seconds.",
    "6-second clip of a CNC mill cutting an aluminum part. Extend to ~25 seconds with continued cutting.",
    "Here's 11 seconds of a robotic arm assembling a small mechanism. Stretch to ~55 seconds.",
    "7-second clip of an automated bottling line. Please extend to ~35 seconds with continued flow.",
    "10-second clip of a Jacquard loom weaving a pattern. Extend to ~50 seconds.",
    "Got 5 seconds of a calligrapher's brush stroke on rice paper. Stretch to ~22 seconds.",
    "8-second clip of oil paints being blended on a palette. Please extend to ~40 seconds.",
    "Here's 9 seconds of watercolor blooming on damp paper. Extend to ~45 seconds.",
    "12-second clip of monks creating a sand mandala grain by grain. Stretch to ~60 seconds.",
    "6-second clip of an ice sculptor chipping at a swan. Please extend to ~25 seconds.",
    "10-second clip of graffiti being sprayed onto a wall. Extend to ~50 seconds with continued painting.",
    "Got 5 seconds of charcoal being smudged on a portrait. Stretch to ~22 seconds.",
    "8-second clip of a potter applying glaze with a brush. Extend to ~40 seconds.",
    "Here's 7 seconds of glass beads being lampworked over a flame. Stretch to ~30 seconds.",
    "11-second clip of leather being tooled by hand. Extend to ~55 seconds.",
    "9-second clip of woodturning chips flying off a chisel. Please extend to ~45 seconds.",
    "10-second clip of soap-making — cold-process pour into a mold. Stretch to ~50 seconds.",
    "Got 6 seconds of a sewing-machine stitching a curved seam. Please extend to ~25 seconds.",
    "8-second clip of a knife being sharpened on a whetstone. Extend to ~40 seconds.",
    "Here's 7 seconds of a tile mosaic being assembled. Stretch to ~30 seconds with more tiles.",
    "5-second clip of a glassblower spinning hot glass. Please extend to ~22 seconds.",
    "12-second clip of a printing press feeding paper. Extend to ~60 seconds.",
    "9-second clip of a candle being trimmed and lit. Stretch to ~40 seconds.",
    "10-second clip of a jeweler setting a stone with tweezers. Extend to ~50 seconds.",
    "Got 7 seconds of a knitter's hands working circular needles. Please extend to ~30 seconds.",
    "8-second clip of a taxidermist's hands stitching a fox pelt. Stretch to ~35 seconds.",
    "Here's 5 seconds of a barber clipping a fade. Please extend to ~22 seconds.",
    "11-second clip of a screen printer pulling a squeegee. Extend to ~55 seconds.",
    "9-second clip of a spinning-wheel making yarn from raw wool. Stretch to ~45 seconds.",
    "6-second clip of a bookbinder gluing a spine. Please extend to ~25 seconds.",
    "10-second clip of a luthier carving a violin scroll. Extend to ~50 seconds.",
    # ── city / street / urban (40) ────────────────────────────────────────
    "Got an 8-second clip of rain pouring under a streetlight. Could you extend to ~40 seconds for a noir scene?",
    "Here's 6 seconds of a neon sign flickering in an alley. Stretch to ~30 seconds.",
    "10-second clip of escalator traffic in a metro station. Extend to ~50 seconds.",
    "5-second clip of a tram passing a foggy intersection. Please extend to ~25 seconds.",
    "Got 9 seconds of cars on a suspension bridge at dusk. Stretch to ~45 seconds.",
    "8-second clip of pigeons taking off from a piazza. Extend to ~40 seconds.",
    "Here's 7 seconds of a market stall vendor wrapping fruit. Please extend to ~30 seconds.",
    "12-second clip of pedestrians at a crosswalk in slow-mo. Stretch to ~60 seconds.",
    "Got 5 seconds of a street performer juggling fire. Please extend to ~22 seconds.",
    "9-second clip of a vendor flipping a wok at a night market. Extend to ~45 seconds.",
    "10-second clip of taxis weaving through Shibuya. Stretch to ~50 seconds.",
    "Here's 6 seconds of a busker playing violin in a subway tunnel. Extend to ~25 seconds.",
    "8-second clip of bicycle traffic on a Copenhagen avenue. Stretch to ~40 seconds.",
    "11-second clip of a London bus turning into a square. Please extend to ~55 seconds.",
    "7-second clip of a Times Square crowd at night. Extend to ~30 seconds with continued bustle.",
    "Got 5 seconds of a hot-dog cart vendor making a sandwich. Stretch to ~22 seconds.",
    "9-second clip of a rickshaw weaving through Old Delhi. Extend to ~45 seconds.",
    "Here's 12 seconds of a Bangkok floating market. Stretch to ~55 seconds.",
    "10-second clip of an ice-cream truck pulling up — kids crowding. Extend to ~50 seconds.",
    "Got 8 seconds of a Parisian café terrace in afternoon light. Please extend to ~40 seconds.",
    "6-second clip of a fishmonger laying out the morning's catch. Stretch to ~25 seconds.",
    "Here's 7 seconds of a New York yellow cab line at JFK. Extend to ~30 seconds.",
    "9-second clip of a downtown Tokyo intersection at dusk. Please extend to ~45 seconds.",
    "11-second clip of an open-air laundry hanging from balconies. Stretch to ~55 seconds.",
    "5-second clip of a gondola gliding through a Venetian canal. Please extend to ~22 seconds.",
    "8-second clip of a Lisbon tram climbing a steep street. Extend to ~40 seconds.",
    "Got 10 seconds of a Hong Kong tram passing neon ads. Stretch to ~50 seconds.",
    "Here's 6 seconds of a cable car on a San Francisco hill. Extend to ~25 seconds.",
    "9-second clip of a rainy Seoul intersection with umbrellas. Stretch to ~40 seconds.",
    "7-second clip of vendors lighting paper lanterns at dusk. Please extend to ~30 seconds.",
    "12-second clip of foot traffic outside a Tokyo train station. Extend to ~60 seconds.",
    "Got 5 seconds of a pretzel vendor in Munich. Stretch to ~22 seconds.",
    "8-second clip of a flower seller arranging tulips at a Dutch market. Extend to ~40 seconds.",
    "Here's 9 seconds of a Cairo souk at midday. Please extend to ~45 seconds.",
    "10-second clip of an Istanbul ferry crossing the Bosphorus. Stretch to ~50 seconds.",
    "11-second clip of a Mumbai rickshaw stand. Extend to ~55 seconds.",
    "Got 6 seconds of a Hong Kong dim-sum cart in a packed dining hall. Please extend to ~25 seconds.",
    "8-second clip of London Tube doors opening — passengers boarding. Extend to ~40 seconds.",
    "Here's 7 seconds of a Berlin techno-club door line. Stretch to ~30 seconds.",
    "10-second clip of street food being assembled in a Mexico City stall. Extend to ~50 seconds.",
    # ── home / domestic / quiet (30) ──────────────────────────────────────
    "Here's a 6-second clip of a candle flickering on a bedside table. Could you extend to ~30 seconds for a sleep loop?",
    "Got 8 seconds of a sewing machine running a long seam. Stretch to ~40 seconds.",
    "10-second clip of a washing-machine drum tumbling. Extend to ~50 seconds for an ASMR-style loop.",
    "5-second clip of steam rising from a kettle on the stove. Please extend to ~22 seconds.",
    "9-second clip of tea steeping in a glass pot. Stretch to ~45 seconds.",
    "Here's 7 seconds of knitting needles working a sweater sleeve. Extend to ~30 seconds.",
    "12-second clip of a vinyl record spinning on a turntable. Stretch to ~60 seconds.",
    "Got 6 seconds of bubbles in an aquarium with neon tetras. Please extend to ~25 seconds.",
    "8-second clip of a fireplace burning low. Extend to ~40 seconds for a cozy living-room BG.",
    "5-second clip of a clock pendulum swinging. Stretch to ~22 seconds.",
    "Here's 11 seconds of dust motes drifting in a sunbeam. Extend to ~55 seconds.",
    "9-second clip of a cat curled up by a heater. Please extend to ~40 seconds.",
    "10-second clip of an espresso machine pulling a shot. Stretch to ~50 seconds.",
    "Got 7 seconds of laundry drying on a line in a breeze. Extend to ~30 seconds.",
    "8-second clip of a bookshelf with a sleeping cat at the end. Stretch to ~40 seconds.",
    "Here's 6 seconds of soup simmering on a stovetop. Please extend to ~25 seconds.",
    "5-second clip of incense smoke curling upward. Stretch to ~22 seconds.",
    "12-second clip of a sunlit window with potted herbs. Extend to ~55 seconds.",
    "9-second clip of a fountain pen writing on cream paper. Please extend to ~40 seconds.",
    "10-second clip of a piano with a metronome ticking. Stretch to ~50 seconds.",
    "Got 8 seconds of an old rotary fan spinning slowly. Extend to ~35 seconds.",
    "7-second clip of a snow globe being shaken — falling glitter. Please extend to ~30 seconds.",
    "Here's 5 seconds of a wood-burning stove with cracked door. Stretch to ~22 seconds.",
    "11-second clip of a child's mobile spinning above a crib. Extend to ~55 seconds.",
    "9-second clip of a goldfish bowl with one koi swimming. Stretch to ~40 seconds.",
    "10-second clip of a kettle whistling on a gas range. Please extend to ~45 seconds.",
    "8-second clip of an attic with golden afternoon light. Extend to ~40 seconds.",
    "Got 6 seconds of a window with rain streaking down. Stretch to ~25 seconds.",
    "Here's 7 seconds of a chess board mid-game with a hand moving a pawn. Please extend to ~30 seconds.",
    "12-second clip of a cat batting at a ball of yarn. Extend to ~55 seconds.",
    # ── micro / science / abstract (30) ───────────────────────────────────
    "Got a 5-second microscope clip of blood cells flowing through a capillary. Could you extend to ~22 seconds?",
    "Here's 8 seconds of mold growing on a slice of bread (timelapse). Stretch to ~40 seconds.",
    "10-second clip of crystals forming in a saturated solution. Extend to ~50 seconds.",
    "9-second clip of ferrofluid pulled into spikes by a magnet. Please extend to ~40 seconds.",
    "12-second clip of a stalactite slowly dripping in a cave. Stretch to ~75 seconds.",
    "Here's 7 seconds of a plant unfurling new leaves (timelapse). Extend to ~35 seconds.",
    "6-second clip of pollen grains seen through a microscope. Please extend to ~25 seconds.",
    "10-second clip of a bacterial colony spreading across a petri dish. Stretch to ~50 seconds.",
    "Got 5 seconds of a fluid simulation — paint drops colliding. Extend to ~22 seconds.",
    "8-second clip of a CGI smoke ring expanding in slow-mo. Please extend to ~40 seconds.",
    "Here's 9 seconds of a fractal zoom into a Mandelbrot set. Stretch to ~45 seconds.",
    "11-second kaleidoscope clip of geometric shifts. Extend to ~55 seconds.",
    "10-second clip of an ink drop diffusing in clear water. Stretch to ~50 seconds.",
    "5-second clip of a paint splat in slow-mo. Please extend to ~22 seconds.",
    "8-second clip of a soap bubble swirling with iridescent colors. Extend to ~40 seconds.",
    "Got 7 seconds of CGI particles forming a logo. Stretch to ~30 seconds.",
    "12-second clip of an electron micrograph of a butterfly wing. Extend to ~60 seconds.",
    "9-second clip of a Petri dish with growing crystals. Please extend to ~40 seconds.",
    "10-second slow-mo of a water balloon bursting. Stretch to ~45 seconds.",
    "Here's 6 seconds of a glowing plasma globe being touched. Extend to ~25 seconds.",
    "5-second clip of mercury beading on glass. Please extend to ~22 seconds.",
    "8-second clip of a Tesla coil arcing electricity. Stretch to ~40 seconds.",
    "11-second clip of magnetic iron filings rearranging. Extend to ~55 seconds.",
    "9-second timelapse of a mushroom growing from soil. Please extend to ~45 seconds.",
    "10-second clip of CGI particles forming text from dust. Stretch to ~50 seconds.",
    "Got 7 seconds of a chemical reaction turning blue to red. Extend to ~30 seconds.",
    "5-second clip of a slow CGI camera flythrough of a fractal city. Stretch to ~22 seconds.",
    "Here's 8 seconds of a soap film popping in slow-mo. Please extend to ~40 seconds.",
    "12-second clip of dye spreading through a fish tank. Extend to ~60 seconds.",
    "9-second slow-mo of a single match igniting. Stretch to ~40 seconds.",
    # ── transport / travel (30) ───────────────────────────────────────────
    "Here's a 7-second clip of a bullet train passing a station platform. Could you extend to ~30 seconds?",
    "Got 9 seconds of a vintage steam locomotive crossing a trestle bridge. Stretch to ~45 seconds.",
    "10-second clip of a sailboat tacking across a bay. Extend to ~50 seconds.",
    "5-second clip of a hot-air balloon basket lifting off. Please extend to ~22 seconds.",
    "12-second clip of a ferry leaving a Norwegian fjord port. Stretch to ~60 seconds.",
    "Here's 8 seconds of a propeller plane on a grass airstrip. Extend to ~40 seconds.",
    "6-second clip of a bicycle messenger weaving through traffic. Please extend to ~25 seconds.",
    "11-second clip of a cable car climbing a Swiss alp. Stretch to ~55 seconds.",
    "Got 7 seconds of a sailboat racing in heavy winds. Extend to ~30 seconds.",
    "9-second clip of a glider banking over a meadow. Please extend to ~40 seconds.",
    "10-second clip of a paraglider launching off a cliff. Stretch to ~50 seconds.",
    "5-second clip of a cargo ship loaded with containers entering port. Please extend to ~22 seconds.",
    "Here's 8 seconds of a tuk-tuk speeding through Bangkok traffic. Extend to ~40 seconds.",
    "12-second clip of a hot-air balloon festival mass ascension. Stretch to ~75 seconds.",
    "9-second clip of a train passing through tunneling autumn forest. Please extend to ~45 seconds.",
    "7-second clip of a horse-drawn carriage through a cobbled square. Stretch to ~30 seconds.",
    "10-second clip of a vintage motorcycle on a coastal road. Extend to ~50 seconds.",
    "Got 6 seconds of a kayak gliding along a glass-still lake. Please extend to ~25 seconds.",
    "8-second clip of a small fishing boat heading out at dawn. Stretch to ~40 seconds.",
    "11-second clip of a cruise ship pulling into a port at sunset. Extend to ~55 seconds.",
    "Here's 5 seconds of a vintage trolley turning at the end of a line. Please extend to ~22 seconds.",
    "9-second clip of a delivery truck unloading at a market. Stretch to ~40 seconds.",
    "10-second clip of cyclists coasting down an Alpine pass. Extend to ~50 seconds.",
    "7-second clip of a freight train rumbling through a desert. Please extend to ~30 seconds.",
    "12-second clip of a ferry approaching a tropical island dock. Stretch to ~60 seconds.",
    "Got 8 seconds of a vintage convertible on a coastal highway. Extend to ~40 seconds.",
    "Here's 6 seconds of a horse race at the final stretch. Please extend to ~25 seconds.",
    "5-second clip of a hovercraft skimming a calm bay. Stretch to ~22 seconds.",
    "11-second clip of a yacht under spinnaker on the open ocean. Extend to ~55 seconds.",
    "9-second clip of a rural airfield with a Cessna landing. Please extend to ~40 seconds.",
    # ── miscellaneous closers (30) ────────────────────────────────────────
    "I have a 7-second clip of a metronome ticking on a music stand. Could you extend to ~30 seconds?",
    "Got 5 seconds of a slow-motion balloon pop. Please extend to ~22 seconds with another pop.",
    "Here's 9 seconds of a waterfall through a redwood grove in golden light. Stretch to ~45 seconds.",
    "12-second clip of a campfire with a kettle on a tripod. Extend to ~60 seconds.",
    "8-second clip of an ice cube cracking in warm whisky. Please extend to ~35 seconds.",
    "10-second clip of a chandelier slowly turning above a ballroom. Stretch to ~50 seconds.",
    "6-second slow-mo clip of a balloon being squeezed until it pops. Please extend to ~25 seconds.",
    "Here's 11 seconds of a kitten wrestling with a sock. Extend to ~55 seconds.",
    "7-second clip of a spinning top on a wooden table. Please extend to ~30 seconds.",
    "9-second clip of a Newton's cradle clicking. Stretch to ~40 seconds.",
    "5-second clip of a record needle dropping onto vinyl. Please extend to ~22 seconds.",
    "8-second clip of a marble run cascading through ramps. Extend to ~40 seconds.",
    "10-second clip of a Rube Goldberg machine triggering domino chain. Stretch to ~50 seconds.",
    "Got 6 seconds of a chalk-line being snapped on a deck. Please extend to ~25 seconds.",
    "12-second clip of a sundial casting a moving shadow (timelapse). Extend to ~70 seconds.",
    "Here's 7 seconds of a floor-mop swirling soapy water. Please extend to ~30 seconds.",
    "9-second clip of a wind turbine seen from above. Stretch to ~45 seconds.",
    "5-second clip of an old film projector running. Please extend to ~22 seconds.",
    "10-second clip of a brass band marching down a parade route. Extend to ~50 seconds.",
    "8-second clip of a hot-air-balloon shadow drifting across a cornfield. Stretch to ~40 seconds.",
    "11-second clip of a flag rippling in a stiff wind. Please extend to ~55 seconds.",
    "9-second clip of an antique typewriter being typed on. Stretch to ~40 seconds.",
    "6-second clip of an abacus being slid by an experienced clerk. Please extend to ~25 seconds.",
    "Here's 7 seconds of a watchmaker assembling a movement. Extend to ~30 seconds.",
    "10-second clip of a CRT television glitching on static. Stretch to ~50 seconds.",
    "5-second clip of a Polaroid being shaken to develop. Please extend to ~22 seconds.",
    "12-second clip of a vintage carousel turning at dusk. Extend to ~60 seconds.",
    "8-second clip of a drone landing on its launchpad. Stretch to ~35 seconds.",
    "9-second clip of a ferris wheel turning at twilight. Please extend to ~45 seconds.",
    "7-second clip of a pinwheel spinning in a stiff breeze. Extend to ~30 seconds.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
