"""x15 story_music_ambience SFT.
Chain: Narration → Illustration → Narrator → Music → Ambience → AudioMix → Compositor.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Tell me a children's audiobook about a young owl learning to hoot, with soft-piano BGM and forest-night ambience.",
    "I want an illustrated audiobook about a child sleeping under stars, with celesta BGM and meadow-cricket ambience.",
    "Make me a bedtime audiobook about a frog crossing a pond at dusk, with delicate-flute BGM and pond-frog ambience.",
    "Create a picture-book audiobook about a sailboat crossing a quiet bay, with maritime-folk BGM and ocean-and-gull ambience.",
    "Produce an illustrated children's tale about a fawn following her mother, with tender-piano BGM and forest-bird ambience.",
    "Generate a kids' audiobook about a moth circling a porch lantern, with summer-flute BGM and summer-night ambience.",
    "Build a narrated picture-book about a snowy owl gliding over a frozen field, with arctic-strings BGM and winter-wind ambience.",
    "Render a children's audiobook about a kitten napping in a sunlit window-sill, with quiet-piano BGM and sunlit-room ambience.",
    "I'd like a bedtime audiobook about a rabbit watching the moon rise, with quiet-flute BGM and quiet-meadow ambience.",
    "Tell me a children's audiobook about a young hedgehog crossing a country lane, with folk-fiddle BGM and rural-night ambience.",
    "Make a soft picture-book audiobook about a snail traversing a wet leaf, with delicate-harp BGM and rainforest-drip ambience.",
    "Cook up a children's audiobook about a turtle resting in tide-pool ripples, with calm-flute BGM and coastal-tide ambience.",
    "Generate a narrated picture-book about a pigeon perched on a city ledge, with light-jazz BGM and city-rooftop ambience.",
    "Produce a children's audiobook about a deer drinking at a forest stream, with pastoral-strings BGM and forest-stream ambience.",
    "Build a bedtime audiobook about a cat curled by a fireplace, with lullaby-piano BGM and crackling-fire ambience.",
    "Tell me an illustrated children's audiobook about a child napping on a porch swing, with porch-folk BGM and porch-breeze ambience.",
    "Make me a picture-book audiobook about a goldfish circling its bowl, with celesta BGM and bedroom-aquarium ambience.",
    "Cook up a narrated children's audiobook about a sparrow nesting in a barn rafter, with quiet-flute BGM and barn-rustle ambience.",
    "Generate a children's bedtime audiobook about a young bat hanging in a cave, with mysterious-strings BGM and cave-drip ambience.",
    "Produce a kids' picture-book audiobook about a mouse exploring an attic, with playful-pizzicato BGM and attic-creak ambience.",
    "Build an illustrated children's audiobook about a koala dozing in eucalyptus leaves, with didgeridoo BGM and Australian-bush ambience.",
    "Tell me a children's audiobook about a bumblebee weaving through a meadow, with flute BGM and meadow-bee ambience.",
    "Make a narrated picture-book audiobook about a panda chewing bamboo at dawn, with bamboo-flute BGM and bamboo-grove ambience.",
    "Render a children's audiobook about a flamingo standing in a salt pan at sunset, with tropical-marimba BGM and shallow-water ambience.",
    "I'd like a bedtime audiobook about a baby otter sleeping on its mother's belly, with lullaby-flute BGM and calm-sea ambience.",
    "Cook up a children's audiobook about a polar bear walking across pack ice, with ambient-pad BGM and polar-wind ambience.",
    "Generate a kids' picture-book audiobook about a chameleon clinging to a leaf, with rainforest-flute BGM and rainforest-rustle ambience.",
    "Produce a narrated children's audiobook about a meerkat sentinel scanning the savanna, with savanna-marimba BGM and savanna-bird ambience.",
    "Build a bedtime audiobook about a sea turtle floating to the surface, with maritime-flute BGM and underwater ambience.",
    "Tell me an illustrated children's audiobook about a frog hopping along a creek-bank, with playful-clarinet BGM and creek ambience.",
    "Make me a picture-book audiobook about a hummingbird visiting morning glories, with bright-strings BGM and garden-bee ambience.",
    "Cook up a narrated children's audiobook about a snail circling a stone wall, with delicate-harp BGM and garden-night ambience.",
    "Generate a children's bedtime audiobook about a baby fox curled with its mother, with lullaby-piano BGM and quiet-forest ambience.",
    "Produce a kids' picture-book audiobook about a young deer crossing a moonlit field, with pastoral-strings BGM and night-meadow ambience.",
    "Build an illustrated children's audiobook about a barn cat watching a moth at midnight, with quiet-piano BGM and barn-night ambience.",
    # ── more illustrated children's audiobooks with BGM and ambience (50)
    "Tell me a children's audiobook about a young lion cub learning to roar on the savanna at dusk, with heroic-strings BGM and savanna-night ambience.",
    "Make me an illustrated audiobook about a tiger cub stalking a butterfly in a jungle, with jungle-strings BGM and jungle-rain ambience.",
    "Cook up a bedtime audiobook about a baby elephant splashing at a watering hole, with river-strings BGM and river-mud ambience.",
    "Generate a kids' picture-book audiobook about a zebra foal greeting the sun, with dawn-flute BGM and dawn-savanna ambience.",
    "Produce a children's audiobook about a giraffe calf reaching for acacia leaves, with delicate-flute BGM and acacia-tree ambience.",
    "Build a narrated picture-book audiobook about a baby orangutan swinging through the canopy, with playful-flute BGM and Borneo-rainforest ambience.",
    "Render a children's audiobook about a baby gorilla nestled in mountain mist, with ambient-strings BGM and mountain-mist ambience.",
    "I'd like a bedtime audiobook about a red panda dozing on a high branch, with delicate-piano BGM and Himalayan-mist ambience.",
    "Tell me a children's audiobook about a baby penguin huddling in a snowstorm, with icy-strings BGM and Antarctic-blizzard ambience.",
    "Make a picture-book audiobook about an arctic fox watching the aurora, with ambient-strings BGM and tundra-wind ambience.",
    "Cook up a children's audiobook about a snow leopard climbing a high ridge, with ethereal-strings BGM and high-altitude-wind ambience.",
    "Generate a narrated picture-book about a baby seal sleeping on an ice floe, with ambient-pad BGM and ice-floe ambience.",
    "Produce a children's audiobook about a dolphin calf surfacing at sunset, with ambient-flute BGM and open-ocean ambience.",
    "Build a bedtime audiobook about a baby whale singing to its mother, with deep-cello BGM and deep-ocean ambience.",
    "Tell me an illustrated children's audiobook about an octopus hatchling exploring a kelp forest, with ambient-electronic BGM and kelp-forest ambience.",
    "Make me a picture-book audiobook about a crab scuttling across a tide-pool, with playful-pizzicato BGM and tide-pool-bubble ambience.",
    "Cook up a narrated children's audiobook about a starfish glowing in a tide-pool, with delicate-harp BGM and tide-pool ambience.",
    "Generate a children's bedtime audiobook about a seahorse drifting through coral, with delicate-flute BGM and coral-reef ambience.",
    "Produce a kids' picture-book audiobook about a clownfish nestled in an anemone, with playful-flute BGM and anemone-current ambience.",
    "Build an illustrated children's audiobook about a jellyfish drifting in dark water, with ambient-pad BGM and deep-current ambience.",
    "Tell me a children's audiobook about a baby manatee grazing in mangrove roots, with calm-cello BGM and mangrove ambience.",
    "Make a narrated picture-book audiobook about a river otter sliding down a muddy bank, with playful-flute BGM and river ambience.",
    "Render a children's audiobook about a beaver tending its dam, with banjo BGM and dam-stream ambience.",
    "I'd like a bedtime audiobook about a mole burrowing through quiet earth, with playful-bassoon BGM and earthen-tunnel ambience.",
    "Cook up a children's audiobook about a badger emerging from a hedgerow, with playful-bassoon BGM and hedgerow ambience.",
    "Generate a kids' picture-book audiobook about a baby skunk wandering an evening meadow, with playful-pizzicato BGM and evening-meadow ambience.",
    "Produce a narrated children's audiobook about a raccoon exploring a back porch, with mischievous-clarinet BGM and suburban-yard-night ambience.",
    "Build a bedtime audiobook about an opossum visiting a moonlit garden, with playful-pizzicato BGM and suburban-night ambience.",
    "Tell me an illustrated children's audiobook about a squirrel tucking acorns into an oak hollow, with playful-pizzicato BGM and oak-canopy ambience.",
    "Make me a picture-book audiobook about a chipmunk darting along the forest floor, with playful-pizzicato BGM and forest-floor ambience.",
    "Cook up a narrated children's audiobook about a groundhog peeking out of its burrow, with playful-pizzicato BGM and meadow ambience.",
    "Generate a children's bedtime audiobook about a porcupine waddling beneath the pines, with playful-bassoon BGM and pine-forest ambience.",
    "Produce a kids' picture-book audiobook about a wolf pup howling at twilight, with tender-strings BGM and tundra-wind ambience.",
    "Build an illustrated children's audiobook about a bear cub catching its first salmon, with cheerful-fiddle BGM and spring-stream ambience.",
    "Tell me a children's audiobook about a fawn nosing through fallen autumn leaves, with tender-piano BGM and autumn-leaves ambience.",
    "Make a narrated picture-book audiobook about a baby moose splashing in a marsh, with cheerful-fiddle BGM and marsh ambience.",
    "Render a children's audiobook about a baby caribou crossing the tundra, with ambient-strings BGM and Arctic-mossland ambience.",
    "I'd like a bedtime audiobook about a baby bison trotting beside the herd, with heroic-fiddle BGM and prairie-wind ambience.",
    "Cook up a children's audiobook about a foal sleeping in a meadow under stars, with tender-piano BGM and meadow-night ambience.",
    "Generate a kids' picture-book audiobook about a baby donkey curled in a stable, with playful-bassoon BGM and farm-yard ambience.",
    "Produce a narrated children's audiobook about a baby goat skipping along a mountain meadow, with cheerful-fiddle BGM and mountain-meadow ambience.",
    "Build a bedtime audiobook about a lamb following its mother across a hillside, with Welsh-folk BGM and Welsh-hillside ambience.",
    "Tell me an illustrated children's audiobook about a baby llama dozing on an Andean ridge, with Andean-flute BGM and Andean-cloud ambience.",
    "Make me a picture-book audiobook about a baby alpaca grazing in a highland meadow, with Andean-flute BGM and highland-meadow ambience.",
    "Cook up a narrated children's audiobook about a baby vicuna trotting on the altiplano, with pan-flute BGM and Andean-wind ambience.",
    "Generate a children's bedtime audiobook about a baby capybara floating in a Pantanal river, with Pantanal-flute BGM and Pantanal-river ambience.",
    "Produce a kids' picture-book audiobook about a baby tapir splashing in a rainforest stream, with Amazon-flute BGM and Amazon-rain ambience.",
    "Build an illustrated children's audiobook about a baby armadillo padding across a Texas yard, with Texas-fiddle BGM and Texas-night ambience.",
    "Tell me a children's audiobook about a baby aardvark sniffing out termites at midnight, with African-percussion BGM and African-night ambience.",
    "Make a narrated picture-book audiobook about a baby pangolin curled beneath ferns, with jungle-flute BGM and dense-forest ambience.",
    # ── more illustrated children's audiobooks with BGM and ambience (50)
    "Tell me a children's audiobook about an orphaned dragon hatchling waking in a cave, with heroic-strings BGM and cave-drip ambience.",
    "Make me an illustrated audiobook about a lost mermaid finding her way home, with delicate-harp BGM and kelp-forest ambience.",
    "Cook up a bedtime audiobook about a shy gnome tending a mushroom grove, with playful-bassoon BGM and mushroom-grove ambience.",
    "Generate a kids' picture-book audiobook about a timid pixie tip-toeing across a flower, with delicate-flute BGM and meadow-flower ambience.",
    "Produce a children's audiobook about a friendly troll painting his bridge, with oompah BGM and bridge-stream ambience.",
    "Build a narrated picture-book audiobook about a brave little fairy in a forest glade, with shimmering-flute BGM and forest-glade ambience.",
    "Render a children's audiobook about a tiny giant tending sheep on a mountain, with heroic-strings BGM and mountain-meadow ambience.",
    "I'd like a bedtime audiobook about a clumsy unicorn discovering a fairy forest, with harp BGM and fairy-forest ambience.",
    "Tell me a children's audiobook about an enchanted gargoyle waking in a cathedral tower, with organ BGM and cathedral-tower ambience.",
    "Make a picture-book audiobook about a sleeping nymph in a river mist, with delicate-harp BGM and river-mist ambience.",
    "Cook up a children's audiobook about a wandering centaur galloping at sunrise, with pastoral-strings BGM and prairie-wind ambience.",
    "Generate a narrated picture-book about a cheerful brownie at the cottage hearth, with banjo BGM and cottage-hearth ambience.",
    "Produce a children's audiobook about a shy kelpie in a Highland loch, with Celtic-fiddle BGM and Highland-loch ambience.",
    "Build a bedtime audiobook about a magical Selkie at the Atlantic shore, with Celtic-strings BGM and Atlantic-shore ambience.",
    "Tell me an illustrated children's audiobook about a baby gryphon on a cliff at dawn, with heroic-trumpet BGM and cliff-wind ambience.",
    "Make me a picture-book audiobook about a chimera cub by a volcano, with heroic-strings BGM and volcanic-steam ambience.",
    "Cook up a narrated children's audiobook about a tiny phoenix near an ember-hearth, with triumphant-strings BGM and ember-hearth ambience.",
    "Generate a children's bedtime audiobook about a wise owl in a tower room, with celesta BGM and tower-room-quiet ambience.",
    "Produce a kids' picture-book audiobook about a faithful golem at a desert oasis, with low-cello BGM and desert-oasis ambience.",
    "Build an illustrated children's audiobook about a mossy moss-troll on the forest floor, with bassoon BGM and forest-floor ambience.",
    "Tell me a children's audiobook about a baby koala curled in a eucalyptus grove, with delicate-flute BGM and eucalyptus-grove ambience.",
    "Make a narrated picture-book audiobook about a baby sloth napping in a Costa-Rican canopy, with slow-piano BGM and Costa-Rican-canopy ambience.",
    "Render a children's audiobook about a baby red-panda in a Himalayan conifer, with Himalayan-flute BGM and Himalayan-conifer ambience.",
    "I'd like a bedtime audiobook about a baby snow-leopard on a Tian-Shan cliff, with ethereal-strings BGM and Tian-Shan-cliff ambience.",
    "Cook up a children's audiobook about a baby polar-fox crossing the tundra, with ambient-strings BGM and tundra-wind ambience.",
    "Generate a kids' picture-book audiobook about a baby mountain-hare in a highland meadow, with cheerful-flute BGM and highland-meadow ambience.",
    "Produce a narrated children's audiobook about a baby ermine by a winter stream, with delicate-piano BGM and winter-stream ambience.",
    "Build a bedtime audiobook about a baby weasel slipping through a farmyard at night, with playful-bassoon BGM and farm-night ambience.",
    "Tell me an illustrated children's audiobook about a baby otter playing in a stream, with playful-flute BGM and river ambience.",
    "Make me a picture-book audiobook about a baby muskrat building a den in a wetland, with playful-bassoon BGM and wetland ambience.",
    "Cook up a narrated children's audiobook about a baby nutria swimming in a marsh, with playful-bassoon BGM and marsh ambience.",
    "Generate a children's bedtime audiobook about a baby agouti scuttling across a jungle floor, with tropical-flute BGM and jungle-floor ambience.",
    "Produce a kids' picture-book audiobook about a baby paca in the Amazon floor, with Amazon-flute BGM and Amazon-floor ambience.",
    "Build an illustrated children's audiobook about a baby coati climbing a jungle canopy, with playful-flute BGM and jungle-canopy ambience.",
    "Tell me a children's audiobook about a baby kinkajou hanging from a vine, with playful-flute BGM and jungle-canopy ambience.",
    "Make a narrated picture-book audiobook about a baby olingo creeping at night, with tropical-flute BGM and jungle-night ambience.",
    "Render a children's audiobook about a baby tamandua sniffing termites, with Amazon-flute BGM and Amazon-floor ambience.",
    "I'd like a bedtime audiobook about a baby silky-anteater in a tropical tree, with tropical-flute BGM and tropical-tree ambience.",
    "Cook up a children's audiobook about a baby giant-pangolin walking through Congo forest, with jungle-flute BGM and Congo-forest ambience.",
    "Generate a kids' picture-book audiobook about a baby aardwolf in the African savanna at night, with African-percussion BGM and African-savanna-night ambience.",
    "Produce a narrated children's audiobook about a baby civet in an Asian jungle at night, with Asian-flute BGM and Asian-jungle-night ambience.",
    "Build a bedtime audiobook about a baby genet in African shrub at night, with African-flute BGM and African-shrub-night ambience.",
    "Tell me an illustrated children's audiobook about a baby fossa in a Madagascan forest, with Madagascan-flute BGM and Madagascan-forest ambience.",
    "Make me a picture-book audiobook about a baby bongo at a Congo river bank, with pastoral-flute BGM and Congo-river-bank ambience.",
    "Cook up a narrated children's audiobook about a baby eland on a savanna at dawn, with savanna-flute BGM and savanna-dawn ambience.",
    "Generate a children's bedtime audiobook about a baby kudu on a savanna at dusk, with savanna-flute BGM and savanna-dusk ambience.",
    "Produce a kids' picture-book audiobook about a baby gerenuk reaching for an acacia tree, with delicate-flute BGM and acacia-tree ambience.",
    "Build an illustrated children's audiobook about a baby dik-dik in scrub-meadow, with playful-flute BGM and scrub-meadow ambience.",
    "Tell me a children's audiobook about a baby aardvark in a Kalahari night, with African-percussion BGM and Kalahari-night ambience.",
    "Make a narrated picture-book audiobook about a baby suni in a forest thicket, with delicate-flute BGM and forest-thicket ambience.",
    # ── more baby reptiles / amphibians + BGM + ambience (50) ──
    "Generate a kids' picture-book audiobook about a baby Galapagos tortoise crawling on volcanic rock, with serene-flute BGM and volcanic-island ambience.",
    "Produce a narrated children's audiobook about a baby green-sea-turtle paddling near coastal mangroves, with calm-cello BGM and coastal-mangrove ambience.",
    "Build a bedtime audiobook about a baby leatherback turtle hatching on a tropical beach, with delicate-strings BGM and tropical-beach-dusk ambience.",
    "Tell me an illustrated children's audiobook about a baby loggerhead crawling toward the surf, with calm-piano BGM and moonlit-beach ambience.",
    "Make me a picture-book audiobook about a baby box-turtle exploring a damp forest floor, with woodland-flute BGM and damp-forest ambience.",
    "Cook up a narrated children's audiobook about a baby red-eared slider sunning on a log, with playful-pizzicato BGM and pond-edge ambience.",
    "Generate a children's bedtime audiobook about a baby softshell turtle gliding under a slow river, with calm-strings BGM and slow-river ambience.",
    "Produce a kids' picture-book audiobook about a baby snapping-turtle hiding in a swamp, with eerie-celesta BGM and swamp-dusk ambience.",
    "Build an illustrated children's audiobook about a baby alligator-snapper hunting a still pond, with mysterious-cello BGM and still-pond ambience.",
    "Tell me a children's audiobook about a baby American-alligator drifting in a Florida wetland, with ambient-strings BGM and Florida-wetland ambience.",
    "Make a narrated picture-book audiobook about a baby Nile-crocodile sunbathing on a riverbank, with African-flute BGM and African-riverbank ambience.",
    "Cook up a children's audiobook about a baby caiman hiding among Amazonian water-lilies, with Amazonian-flute BGM and Amazonian-lily ambience.",
    "Generate a kids' picture-book audiobook about a baby gharial slipping into the Ganges, with Hindustani-flute BGM and Ganges-river ambience.",
    "Produce a narrated children's audiobook about a baby saltwater-crocodile in a mangrove channel, with mangrove-flute BGM and mangrove-channel ambience.",
    "Build a bedtime audiobook about a baby chameleon climbing a Madagascan branch, with Madagascan-flute-2 BGM and Madagascan-canopy ambience.",
    "Tell me an illustrated children's audiobook about a baby green-iguana lounging in a Mesoamerican tree, with marimba-flute BGM and Mesoamerican-canopy ambience.",
    "Make me a picture-book audiobook about a baby blue-iguana exploring a Cayman beach, with Caribbean-flute BGM and Cayman-beach ambience.",
    "Cook up a narrated children's audiobook about a baby marine-iguana sunning on Galápagos rocks, with serene-flute-2 BGM and Galápagos-coast ambience.",
    "Generate a children's bedtime audiobook about a baby gecko clinging to a desert rock, with desert-flute BGM and desert-night ambience.",
    "Produce a kids' picture-book audiobook about a baby leopard-gecko hunting in an Iranian desert, with Iranian-flute BGM and Iranian-desert-night ambience.",
    "Build an illustrated children's audiobook about a baby crested-gecko in a New-Caledonian forest, with Pacific-flute BGM and New-Caledonian-forest ambience.",
    "Tell me a children's audiobook about a baby tokay-gecko calling at night, with tropical-flute-2 BGM and tropical-night ambience.",
    "Make a narrated picture-book audiobook about a baby anole basking on a Caribbean leaf, with Caribbean-pizzicato BGM and Caribbean-leaf ambience.",
    "Cook up a children's audiobook about a baby horned-lizard hiding among Sonoran rocks, with Sonoran-flute BGM and Sonoran-desert ambience.",
    "Generate a kids' picture-book audiobook about a baby skink scurrying through an Australian leaf-litter, with Australian-flute BGM and Australian-leaf-litter ambience.",
    "Produce a narrated children's audiobook about a baby blue-tongued-skink wandering a backyard garden, with garden-pizzicato BGM and Australian-garden ambience.",
    "Build a bedtime audiobook about a baby thorny-devil crossing a Western-Australian desert, with desert-percussion BGM and Western-Australian-desert ambience.",
    "Tell me an illustrated children's audiobook about a baby frilled-lizard climbing a eucalyptus, with eucalyptus-flute BGM and eucalyptus-canopy ambience.",
    "Make me a picture-book audiobook about a baby bearded-dragon basking in an outback rock, with outback-fiddle BGM and outback-rock ambience.",
    "Cook up a narrated children's audiobook about a baby Komodo-dragon trekking through Indonesian scrub, with gamelan-flute BGM and Indonesian-scrub ambience.",
    "Generate a children's bedtime audiobook about a baby Gila-monster venturing in the Mojave, with Southwestern-flute BGM and Mojave-night ambience.",
    "Produce a kids' picture-book audiobook about a baby beaded-lizard exploring a Mexican thornscrub, with Mexican-flute BGM and Mexican-thornscrub ambience.",
    "Build an illustrated children's audiobook about a baby tuatara emerging from a New-Zealand burrow, with Maori-flute BGM and New-Zealand-burrow ambience.",
    "Tell me a children's audiobook about a baby corn-snake slithering through a Carolina meadow, with Appalachian-fiddle BGM and Carolina-meadow ambience.",
    "Make a narrated picture-book audiobook about a baby king-cobra weaving through Indian jungle, with sitar-flute BGM and Indian-jungle ambience.",
    "Cook up a children's audiobook about a baby black-mamba gliding across an African savanna, with savanna-percussion BGM and savanna-bush ambience.",
    "Generate a kids' picture-book audiobook about a baby anaconda slipping into Amazon water, with Amazonian-pan-flute BGM and Amazon-water ambience.",
    "Produce a narrated children's audiobook about a baby boa-constrictor curling on a tropical branch, with tropical-pan-flute BGM and tropical-canopy ambience.",
    "Build a bedtime audiobook about a baby ball-python hiding in a savanna burrow, with African-flute-2 BGM and savanna-burrow ambience.",
    "Tell me an illustrated children's audiobook about a baby garter-snake basking on a Vermont stone wall, with New-England-fiddle BGM and Vermont-stone-wall ambience.",
    "Make me a picture-book audiobook about a baby tree-frog calling from a rainforest leaf, with rainforest-pan-flute BGM and rainforest-canopy ambience.",
    "Cook up a narrated children's audiobook about a baby poison-dart-frog hopping in Amazonian leaf-litter, with Amazonian-marimba BGM and Amazonian-leaf-litter-2 ambience.",
    "Generate a children's bedtime audiobook about a baby strawberry-poison-frog exploring a Costa-Rican stream, with Costa-Rican-marimba BGM and Costa-Rican-stream ambience.",
    "Produce a kids' picture-book audiobook about a baby bullfrog croaking at a pond's edge, with pond-flute BGM and pond-edge-night ambience.",
    "Build an illustrated children's audiobook about a baby Goliath-frog wading in a Cameroonian river, with African-flute-3 BGM and Cameroonian-river ambience.",
    "Tell me a children's audiobook about a baby Surinam-toad floating in a Surinam stream, with Surinamese-flute BGM and Surinam-stream ambience.",
    "Make a narrated picture-book audiobook about a baby axolotl drifting in Mexican lake water, with Mexican-marimba BGM and Xochimilco-lake ambience.",
    "Cook up a children's audiobook about a baby Chinese-giant-salamander resting in a mountain stream, with Chinese-erhu BGM and Chinese-mountain-stream ambience.",
    "Generate a kids' picture-book audiobook about a baby fire-salamander emerging from European leaves, with European-folk-flute BGM and European-leaf-litter ambience.",
    "Produce a narrated children's audiobook about a baby red-eft walking on damp moss, with delicate-flute-2 BGM and damp-moss ambience.",
    # ── more baby insects / arthropods + BGM + biome ambience (50) ──
    "Build a bedtime audiobook about a baby monarch-butterfly flapping in a milkweed-meadow, with delicate-flute-3 BGM and milkweed-meadow ambience.",
    "Tell me an illustrated children's audiobook about a baby swallowtail-butterfly visiting a wildflower-patch, with playful-pizzicato-2 BGM and wildflower-patch ambience.",
    "Make me a picture-book audiobook about a baby morpho-butterfly fluttering in an Amazon-canopy, with Amazonian-pan-flute BGM and Amazon-canopy-2 ambience.",
    "Cook up a narrated children's audiobook about a baby atlas-moth resting on a Sumatran-leaf, with Sumatran-folk BGM and Sumatran-jungle ambience.",
    "Generate a children's bedtime audiobook about a baby luna-moth hovering by a New-England-porch-light, with New-England-fiddle-2 BGM and New-England-summer-night ambience.",
    "Produce a kids' picture-book audiobook about a baby honeybee buzzing around a clover-field, with playful-flute-2 BGM and clover-field ambience.",
    "Build an illustrated children's audiobook about a baby bumblebee tumbling on a foxglove-flower, with cottage-fiddle BGM and cottage-garden ambience.",
    "Tell me a children's audiobook about a baby leafcutter-ant carrying a leaf in a rainforest, with rainforest-pizzicato BGM and rainforest-floor ambience.",
    "Make a narrated picture-book audiobook about a baby fire-ant scurrying across an Amazon log, with Amazon-pizzicato BGM and Amazon-log ambience.",
    "Cook up a children's audiobook about a baby army-ant marching through Costa-Rican leaf-litter, with Costa-Rican-percussion BGM and Costa-Rican-leaf-litter ambience.",
    "Generate a kids' picture-book audiobook about a baby ladybug climbing a rose-bud, with English-pizzicato BGM and English-rose-garden ambience.",
    "Produce a narrated children's audiobook about a baby fireflies blinking in a summer-meadow, with shimmering-celesta BGM and summer-meadow-night ambience.",
    "Build a bedtime audiobook about a baby grasshopper hopping in a savanna-grass, with savanna-pizzicato BGM and savanna-grass ambience.",
    "Tell me an illustrated children's audiobook about a baby cricket chirping under a Tuscan-villa stoop, with Tuscan-folk-2 BGM and Tuscan-villa-night ambience.",
    "Make me a picture-book audiobook about a baby cicada emerging from a hot-summer-tree, with playful-strings-3 BGM and hot-summer-tree ambience.",
    "Cook up a narrated children's audiobook about a baby praying-mantis stalking on a hibiscus-flower, with hibiscus-flute BGM and hibiscus-garden ambience.",
    "Generate a children's bedtime audiobook about a baby dragonfly hovering over a lotus-pond, with lotus-flute BGM and lotus-pond ambience.",
    "Produce a kids' picture-book audiobook about a baby damselfly dancing over a creek, with woodland-pizzicato BGM and woodland-creek ambience.",
    "Build an illustrated children's audiobook about a baby mayfly emerging from a still pond, with delicate-celesta-2 BGM and still-pond-2 ambience.",
    "Tell me a children's audiobook about a baby caddisfly drifting under a stream-rock, with stream-pizzicato BGM and stream-rock ambience.",
    "Make a narrated picture-book audiobook about a baby stick-insect blending into a banyan branch, with banyan-flute BGM and banyan-canopy ambience.",
    "Cook up a children's audiobook about a baby leaf-insect mimicking a forest-leaf, with forest-flute-2 BGM and forest-canopy-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby weta hopping in a New-Zealand cave, with NZ-folk-flute BGM and NZ-cave ambience.",
    "Produce a narrated children's audiobook about a baby Goliath-beetle walking on a Congo trunk, with Congo-percussion BGM and Congo-trunk ambience.",
    "Build a bedtime audiobook about a baby Hercules-beetle climbing a tropical log, with tropical-percussion BGM and tropical-log ambience.",
    "Tell me an illustrated children's audiobook about a baby stag-beetle wrestling on an oak-trunk, with European-folk-fiddle BGM and European-oak ambience.",
    "Make me a picture-book audiobook about a baby rhinoceros-beetle pushing a fig, with Bornean-folk-flute BGM and Bornean-fig-tree ambience.",
    "Cook up a narrated children's audiobook about a baby weaver-spider weaving a dewy web, with dewy-celesta BGM and dewy-meadow-dawn ambience.",
    "Generate a children's bedtime audiobook about a baby tarantula creeping on a Sonoran rock, with Sonoran-flute-2 BGM and Sonoran-rock-night ambience.",
    "Produce a kids' picture-book audiobook about a baby trapdoor-spider lifting its lid, with chaparral-pizzicato BGM and chaparral-burrow ambience.",
    "Build an illustrated children's audiobook about a baby orchid-mantis perched on a vanda-flower, with delicate-glass-armonica BGM and orchid-greenhouse ambience.",
    "Tell me a children's audiobook about a baby walking-stick climbing a eucalyptus-twig, with eucalyptus-pizzicato BGM and eucalyptus-canopy-2 ambience.",
    "Make a narrated picture-book audiobook about a baby millipede curling under a fallen-leaf, with deciduous-pizzicato BGM and deciduous-floor ambience.",
    "Cook up a children's audiobook about a baby centipede slipping under a stone, with mossy-flute BGM and mossy-stone-pile ambience.",
    "Generate a kids' picture-book audiobook about a baby hermit-crab trying on a shell, with rocky-tide-pool-flute BGM and rocky-tide-pool ambience.",
    "Produce a narrated children's audiobook about a baby coconut-crab clambering up a palm, with Pacific-atoll-flute BGM and Pacific-atoll-night ambience.",
    "Build a bedtime audiobook about a baby fiddler-crab waving a claw, with mangrove-pizzicato BGM and mangrove-mudflat ambience.",
    "Tell me an illustrated children's audiobook about a baby pistol-shrimp clicking in a coral-crevice, with coral-pizzicato BGM and coral-crevice ambience.",
    "Make me a picture-book audiobook about a baby mantis-shrimp punching a snail, with reef-percussion BGM and reef-snail-shore ambience.",
    "Cook up a narrated children's audiobook about a baby horseshoe-crab walking on Delaware-Bay sand, with Delaware-Bay-fiddle BGM and Delaware-Bay-shore ambience.",
    "Generate a children's bedtime audiobook about a baby scorpion glowing under blacklight, with desert-pad BGM and desert-night-2 ambience.",
    "Produce a kids' picture-book audiobook about a baby pseudoscorpion riding a beetle, with library-pizzicato BGM and library-shelf ambience.",
    "Build an illustrated children's audiobook about a baby velvet-worm shooting slime, with damp-pad BGM and damp-leaf-litter ambience.",
    "Tell me a children's audiobook about a baby earthworm tunneling under a garden, with garden-pizzicato BGM and garden-soil ambience.",
    "Make a narrated picture-book audiobook about a baby snail leaving a silver-trail, with rainy-celesta BGM and rainy-garden-leaves ambience.",
    "Cook up a children's audiobook about a baby slug munching on a lettuce-leaf, with cozy-pizzicato BGM and damp-vegetable-bed ambience.",
    "Generate a kids' picture-book audiobook about a baby giant-African-snail sliding on a bamboo-stalk, with Tanzanian-marimba BGM and Tanzanian-bamboo ambience.",
    "Produce a narrated children's audiobook about a baby flatworm gliding on a wet-rock, with shaded-flute BGM and shaded-stream-bank ambience.",
    "Build a bedtime audiobook about a baby leech swimming in a leaf-pool, with rainforest-pad BGM and rainforest-leaf-pool ambience.",
    "Tell me an illustrated children's audiobook about a baby wood-louse curling under a log, with deciduous-flute BGM and deciduous-log ambience.",
    # ── more baby primates / apes + BGM + biome ambience (50) ──
    "Make me a picture-book audiobook about a baby mountain-gorilla cuddling in a Virunga nest, with Rwandan-inanga BGM and Virunga-bamboo-forest ambience.",
    "Cook up a narrated children's audiobook about a baby western-lowland-gorilla in a Congo swamp, with Congolese-likembe BGM and Congo-swamp-canopy ambience.",
    "Generate a children's bedtime audiobook about a baby chimpanzee in a Kibale fig-tree, with Ugandan-folk-2 BGM and Kibale-rainforest ambience.",
    "Produce a kids' picture-book audiobook about a baby bonobo in a Salonga forest, with Congolese-rumba-2 BGM and Salonga-rainforest ambience.",
    "Build an illustrated children's audiobook about a baby orangutan swinging on a Borneo dipterocarp, with Bornean-sape BGM and Borneo-canopy-dawn ambience.",
    "Tell me a children's audiobook about a baby Sumatran-orangutan in a Gunung-Leuser canopy, with Sumatran-gendang BGM and Sumatran-canopy ambience.",
    "Make a narrated picture-book audiobook about a baby siamang gibbon hooting at sunrise, with Sumatran-gambus BGM and Sumatran-canopy-dawn ambience.",
    "Cook up a children's audiobook about a baby white-handed-gibbon swinging in Khao-Yai, with Thai-piphat-2 BGM and Khao-Yai-canopy ambience.",
    "Generate a kids' picture-book audiobook about a baby Hoolock-gibbon in an Assam canopy, with Assamese-bihu-2 BGM and Assam-canopy ambience.",
    "Produce a narrated children's audiobook about a baby black-crested-gibbon in Yunnan, with Yunnan-folk BGM and Yunnan-canopy ambience.",
    "Build a bedtime audiobook about a baby Müller's-Bornean-gibbon in Sabah, with Sabah-sompoton-2 BGM and Sabah-canopy ambience.",
    "Tell me an illustrated children's audiobook about a baby Javan-gibbon in a Halimun canopy, with Javanese-gamelan-3 BGM and Halimun-canopy ambience.",
    "Make me a picture-book audiobook about a baby spider-monkey in Tikal, with Mayan-marimba-2 BGM and Tikal-canopy ambience.",
    "Cook up a narrated children's audiobook about a baby howler-monkey at Iguazú, with Brazilian-pan-flute-2 BGM and Iguazú-canopy-dawn ambience.",
    "Generate a children's bedtime audiobook about a baby capuchin in a Brazilian-cerrado, with Brazilian-cavaquinho BGM and Brazilian-cerrado-canopy ambience.",
    "Produce a kids' picture-book audiobook about a baby squirrel-monkey in a Manú canopy, with Peruvian-quena BGM and Manú-canopy ambience.",
    "Build an illustrated children's audiobook about a baby tamarin in a Tambopata bromeliad, with Peruvian-pan-flute-2 BGM and Tambopata-bromeliad ambience.",
    "Tell me a children's audiobook about a baby uakari in a Mamirauá igapó, with Brazilian-cuíca BGM and Mamirauá-igapó ambience.",
    "Make a narrated picture-book audiobook about a baby titi-monkey in a Pacaya-Samiria forest, with Amazonian-flute-2 BGM and Pacaya-Samiria-canopy ambience.",
    "Cook up a children's audiobook about a baby muriqui in an Atlantic-Forest, with Brazilian-choro-flute BGM and Atlantic-Forest-canopy ambience.",
    "Generate a kids' picture-book audiobook about a baby pygmy-marmoset on a Yasuní liana, with Ecuadorian-pan-flute BGM and Yasuní-liana ambience.",
    "Produce a narrated children's audiobook about a baby golden-lion-tamarin in Poço-das-Antas, with Brazilian-bossa-2 BGM and Atlantic-Forest-coastal ambience.",
    "Build a bedtime audiobook about a baby cottontop-tamarin in a Colombian-dry-forest, with Colombian-tiple BGM and Colombian-dry-forest ambience.",
    "Tell me an illustrated children's audiobook about a baby black-handed-spider-monkey in Costa-Rica, with Costa-Rican-marimba-3 BGM and Costa-Rican-canopy-dawn ambience.",
    "Make me a picture-book audiobook about a baby red-howler-monkey in Llanos, with Llanos-arpa BGM and Llanos-savanna ambience.",
    "Cook up a narrated children's audiobook about a baby long-tailed-macaque in a Bali-temple, with Balinese-suling BGM and Bali-temple-stone ambience.",
    "Generate a children's bedtime audiobook about a baby rhesus-macaque on a Varanasi ghat, with Varanasi-shehnai BGM and Varanasi-ghat ambience.",
    "Produce a kids' picture-book audiobook about a baby Japanese-macaque in a Jigokudani hot-spring, with Japanese-shakuhachi-2 BGM and Jigokudani-hot-spring ambience.",
    "Build an illustrated children's audiobook about a baby Tibetan-macaque on Mount-Emei, with Tibetan-singing-bowl BGM and Emei-mountain ambience.",
    "Tell me a children's audiobook about a baby Barbary-macaque on Gibraltar, with Andalusian-classical-guitar BGM and Gibraltar-cliff ambience.",
    "Make a narrated picture-book audiobook about a baby snub-nosed-monkey in a Shennongjia mist, with Chinese-erhu-2 BGM and Shennongjia-mist ambience.",
    "Cook up a children's audiobook about a baby proboscis-monkey on a Kinabatangan riverbank, with Kinabatangan-sape BGM and Kinabatangan-riverbank ambience.",
    "Generate a kids' picture-book audiobook about a baby douc-langur in Son-Tra, with Vietnamese-đàn-bầu BGM and Son-Tra-canopy ambience.",
    "Produce a narrated children's audiobook about a baby silvered-langur in a Tonle-Sap mangrove, with Khmer-pinpeat-2 BGM and Tonle-Sap-mangrove ambience.",
    "Build a bedtime audiobook about a baby colobus-monkey in a Kakum canopy, with Akan-balafon BGM and Kakum-canopy ambience.",
    "Tell me an illustrated children's audiobook about a baby vervet on a Maasai-Mara fig, with Maasai-osingolio-2 BGM and Maasai-Mara-fig-tree ambience.",
    "Make me a picture-book audiobook about a baby De-Brazza's-monkey on a Kakum branch, with Akan-kete BGM and Kakum-branch-shade ambience.",
    "Cook up a narrated children's audiobook about a baby mandrill in a Lopé forest, with Gabonese-mvet BGM and Lopé-forest ambience.",
    "Generate a children's bedtime audiobook about a baby drill in a Korup canopy, with Korup-folk BGM and Korup-canopy ambience.",
    "Produce a kids' picture-book audiobook about a baby mangabey in a Tana-River gallery-forest, with Pokomo-folk BGM and Tana-River-gallery ambience.",
    "Build an illustrated children's audiobook about a baby gelada on Simien escarpment, with Ethio-krar BGM and Simien-escarpment ambience.",
    "Tell me a children's audiobook about a baby olive-baboon at a Lake-Manyara fig, with Maasai-flute BGM and Lake-Manyara-fig ambience.",
    "Make a narrated picture-book audiobook about a baby chacma-baboon in Tankwa-Karoo, with Karoo-fiddle BGM and Tankwa-Karoo ambience.",
    "Cook up a children's audiobook about a baby hamadryas-baboon on Awash cliffs, with Awash-folk BGM and Awash-cliff-dusk ambience.",
    "Generate a kids' picture-book audiobook about a baby loris on a Sri-Lankan-tea-estate, with Sinhala-vannam BGM and Sri-Lankan-tea-night ambience.",
    "Produce a narrated children's audiobook about a baby slow-loris on a Cardamom-Mountains branch, with Khmer-tro-sau BGM and Cardamom-Mountain-night ambience.",
    "Build a bedtime audiobook about a baby tarsier on a Bohol-Tarsier-Foundation branch, with Filipino-kulintang BGM and Bohol-night-canopy ambience.",
    "Tell me an illustrated children's audiobook about a baby aye-aye in a Ranomafana forest, with Madagascan-valiha-2 BGM and Ranomafana-night ambience.",
    "Make me a picture-book audiobook about a baby ring-tailed-lemur in Anja-reserve, with Madagascan-marovany BGM and Anja-reserve ambience.",
    "Cook up a narrated children's audiobook about a baby indri in Andasibe, with Andasibe-marovany BGM and Andasibe-canopy-dawn ambience.",
    # ── more baby marine-mammal stories + BGM + ocean ambience (50) ──
    "Tell me a children's audiobook about a baby bottlenose-dolphin in Sarasota-Bay, with Florida-marimba BGM and Sarasota-Bay-shallow ambience.",
    "I want an illustrated audiobook about a baby spinner-dolphin off Hawaii's-Big-Island, with Hawaiian-slack-key-2 BGM and Big-Island-tropical-bay ambience.",
    "Make me a bedtime audiobook about a baby orca calf in the Salish-Sea, with Coast-Salish-cedar-flute BGM and Salish-Sea-pod ambience.",
    "Create a picture-book audiobook about a baby beluga in Hudson-Bay, with Inuit-throat-singing-2 BGM and Hudson-Bay-summer-shallow ambience.",
    "Produce an illustrated children's tale about a baby narwhal in Lancaster-Sound, with Inuit-drum-dance BGM and Lancaster-Sound-arctic ambience.",
    "Cook up a narrated children's audiobook about a baby blue-whale in the Gulf-of-California, with Mexican-Sea-of-Cortez-marimba BGM and Gulf-of-California-cetacean ambience.",
    "Generate a kids' picture-book audiobook about a baby humpback-whale in Maui's-Au'au-Channel, with Hawaiian-falsetto BGM and Maui-Au'au-Channel-breeding ambience.",
    "Build a bedtime audiobook about a baby gray-whale in Laguna-San-Ignacio, with Baja-California-Sur-folk BGM and Laguna-San-Ignacio-nursery ambience.",
    "Tell me an illustrated children's audiobook about a baby right-whale in Cape-Cod-Bay, with Cape-Cod-sea-shanty BGM and Cape-Cod-Bay-shallow ambience.",
    "Make me a picture-book audiobook about a baby sperm-whale in Dominica's-Caribbean-Sea, with Dominican-bélé BGM and Dominica-Caribbean-deep ambience.",
    "Cook up a children's audiobook about a baby beaked-whale off the Bahamas-Tongue-of-the-Ocean, with Bahamian-Junkanoo BGM and Bahamas-Tongue-of-the-Ocean ambience.",
    "Produce a narrated children's audiobook about a baby pilot-whale in the Strait-of-Gibraltar, with Andalusian-fandango BGM and Strait-of-Gibraltar-pod ambience.",
    "Generate a kids' picture-book audiobook about a baby vaquita in the Sea-of-Cortez, with Sea-of-Cortez-jarocho BGM and Sea-of-Cortez-Vaquita-refuge ambience.",
    "Build a bedtime audiobook about a baby Yangtze-finless-porpoise in Poyang-Lake, with Jiangxi-folk BGM and Poyang-Lake-river-porpoise ambience.",
    "Tell me an illustrated children's audiobook about a baby boto-river-dolphin in Mamirauá-reserve, with Amazonian-flute BGM and Mamirauá-flooded-forest ambience.",
    "Make me a picture-book audiobook about a baby Ganges-river-dolphin in the Brahmaputra-river, with Assamese-bihu BGM and Brahmaputra-river-eddy ambience.",
    "Cook up a children's audiobook about a baby Indus-river-dolphin in the Indus-river, with Sindhi-folk-2 BGM and Indus-river-channel ambience.",
    "I want an illustrated audiobook about a baby harbor-seal pup on the Wadden-Sea-sandbar, with Frisian-folk BGM and Wadden-Sea-sandbar ambience.",
    "Make me a bedtime audiobook about a baby gray-seal pup on Sable-Island, with Acadian-fiddle-2 BGM and Sable-Island-haul-out ambience.",
    "Create a picture-book audiobook about a baby harp-seal pup on the Gulf-of-St-Lawrence-pack-ice, with Newfoundland-folk BGM and Gulf-of-St-Lawrence-pack-ice ambience.",
    "Produce an illustrated children's tale about a baby hooded-seal pup on the Greenland-pack-ice, with Greenlandic-Inuit-drum BGM and Greenland-pack-ice-pup ambience.",
    "Cook up a narrated children's audiobook about a baby ringed-seal pup on Lake-Saimaa-Finland, with Finnish-kantele BGM and Lake-Saimaa-ice-cave ambience.",
    "Generate a kids' picture-book audiobook about a baby leopard-seal pup off the South-Shetland-Islands, with Antarctic-orchestral BGM and South-Shetland-Islands ambience.",
    "Build a bedtime audiobook about a baby Weddell-seal pup on the McMurdo-Sound-fast-ice, with McMurdo-Sound-orchestral BGM and McMurdo-Sound-fast-ice-haul-out ambience.",
    "Tell me an illustrated children's audiobook about a baby crabeater-seal pup on the Antarctic-Peninsula-pack-ice, with Antarctic-Peninsula-orchestral BGM and Antarctic-Peninsula-pack-ice ambience.",
    "Make me a picture-book audiobook about a baby Ross-seal pup on the Ross-Sea-pack-ice, with Ross-Sea-orchestral BGM and Ross-Sea-pack-ice-pup ambience.",
    "Cook up a children's audiobook about a baby Hawaiian-monk-seal pup on a Papahānaumokuākea-atoll, with Hawaiian-slack-key-3 BGM and Papahānaumokuākea-atoll ambience.",
    "Produce a narrated children's audiobook about a baby Mediterranean-monk-seal pup in a Cabo-Blanco-cave, with Mauritanian-azan BGM and Cabo-Blanco-sea-cave ambience.",
    "Generate a kids' picture-book audiobook about a baby Caribbean-monk-seal-archive pup near Serrana-Bank, with Bahamian-Junkanoo-2 BGM and Serrana-Bank-historical ambience.",
    "Build a bedtime audiobook about a baby Northern-fur-seal pup on the Pribilof-Islands, with Aleut-throat-song BGM and Pribilof-Islands-rookery ambience.",
    "Tell me an illustrated children's audiobook about a baby Galápagos-fur-seal pup on Fernandina-Island, with Ecuadorian-charango BGM and Fernandina-Island-lava-coast ambience.",
    "Make me a picture-book audiobook about a baby Cape-fur-seal pup on Cape-Cross-Namibia, with Damara-punch-2 BGM and Cape-Cross-Namibia-rookery ambience.",
    "Cook up a children's audiobook about a baby South-American-sea-lion pup on the Patagonian-coast, with Patagonian-folk BGM and Patagonian-coast-rookery ambience.",
    "Produce a narrated children's audiobook about a baby Australian-sea-lion pup on Kangaroo-Island, with Kangaroo-Island-folk BGM and Kangaroo-Island-Seal-Bay ambience.",
    "Generate a kids' picture-book audiobook about a baby New-Zealand-sea-lion pup on the Auckland-Islands, with Auckland-Islands-Maori-folk BGM and Auckland-Islands-sea-lion-rookery ambience.",
    "Build a bedtime audiobook about a baby Steller-sea-lion pup on the Aleutian-Forrester-Island, with Aleutian-throat-song BGM and Aleutian-Forrester-Island-rookery ambience.",
    "Tell me an illustrated children's audiobook about a baby walrus calf on Round-Island-Alaska, with Alaskan-Yup'ik-drum BGM and Round-Island-Alaska-haul-out ambience.",
    "Make me a picture-book audiobook about a baby Pacific-walrus on the Chukchi-Sea-pack-ice, with Chukchi-Sea-throat-song BGM and Chukchi-Sea-pack-ice ambience.",
    "Cook up a children's audiobook about a baby Atlantic-walrus on the Svalbard-Moffen, with Svalbard-folk BGM and Svalbard-Moffen-haul-out ambience.",
    "I want an illustrated audiobook about a baby manatee in the Crystal-River-Florida, with Crystal-River-folk BGM and Crystal-River-Florida-spring ambience.",
    "Make me a bedtime audiobook about a baby West-Indian-manatee in the Belize-Sarstoon-Temash, with Belizean-marimba BGM and Belize-Sarstoon-Temash ambience.",
    "Create a picture-book audiobook about a baby West-African-manatee in the Bandiagara-Niger-River, with Bambara-balafon-2 BGM and Bandiagara-Niger-River ambience.",
    "Produce an illustrated children's tale about a baby Amazonian-manatee in the Mamirauá-Lagoon, with Amazonian-charango BGM and Mamirauá-Lagoon ambience.",
    "Cook up a narrated children's audiobook about a baby dugong in the Shark-Bay-seagrass-meadow, with Yamatji-clapsticks BGM and Shark-Bay-seagrass-meadow ambience.",
    "Generate a kids' picture-book audiobook about a baby dugong in the Persian-Gulf-Sirri-Island, with Persian-Gulf-Bandari BGM and Persian-Gulf-Sirri-Island ambience.",
    "Build a bedtime audiobook about a baby sea-otter pup in the Monterey-Bay-kelp-forest, with Monterey-Bay-folk BGM and Monterey-Bay-kelp-forest ambience.",
    "Tell me an illustrated children's audiobook about a baby southern-sea-otter pup in Elkhorn-Slough, with Salinas-Valley-folk BGM and Elkhorn-Slough-marsh ambience.",
    "Make me a picture-book audiobook about a baby northern-sea-otter pup on the Aleutian-coast, with Aleutian-throat-song-2 BGM and Aleutian-coast-kelp ambience.",
    "Cook up a children's audiobook about a baby giant-otter cub in the Pantanal, with Pantanal-rasqueado-2 BGM and Pantanal-river-bank ambience.",
    "Produce a narrated children's audiobook about a baby polar-bear cub on the Wapusk-Cape-Churchill, with Wapusk-Inuit-throat-song BGM and Wapusk-Cape-Churchill-den ambience.",
    # ── more baby reptile / amphibian stories + BGM + biome ambience (50) ──
    "Tell me a children's audiobook about a baby green-sea-turtle hatchling on a Tortuguero-beach, with Tortuguero-Caribbean-marimba BGM and Tortuguero-beach-night-2 ambience.",
    "I want an illustrated audiobook about a baby loggerhead-turtle hatchling on a Zakynthos-Sekania-cove, with Zakynthos-Greek-bouzouki BGM and Zakynthos-Sekania-cove-2 ambience.",
    "Make me a bedtime audiobook about a baby leatherback-turtle hatchling on a Grande-Riviere-Trinidad, with Trinidad-soca-pan BGM and Grande-Riviere-night-2 ambience.",
    "Create a picture-book audiobook about a baby hawksbill-turtle hatchling on a Conflict-Islands-Papua, with Papuan-string-band BGM and Conflict-Islands-night-2 ambience.",
    "Produce an illustrated children's tale about a baby olive-ridley-turtle hatchling on Rushikulya-Odisha, with Odissi-classical BGM and Rushikulya-Odisha-arribada-2 ambience.",
    "Cook up a narrated children's audiobook about a baby Kemp's-ridley-turtle hatchling on Rancho-Nuevo-Mexico, with Tamaulipas-corrido BGM and Rancho-Nuevo-arribada-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby flatback-turtle hatchling on Crab-Island-Queensland, with Cape-York-didjeridu BGM and Crab-Island-Queensland-night-2 ambience.",
    "Build a bedtime audiobook about a baby Galapagos-tortoise hatchling on Santa-Cruz-Highlands, with Galápagos-charango BGM and Santa-Cruz-Highlands-mist-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby Aldabra-giant-tortoise hatchling on Aldabra-atoll, with Seychellois-moutya BGM and Aldabra-atoll-shore-2 ambience.",
    "Make me a picture-book audiobook about a baby Komodo-dragon hatchling on a Komodo-Island-savanna, with Flores-gendang-folk BGM and Komodo-savanna-morning-2 ambience.",
    "Cook up a children's audiobook about a baby Nile-crocodile hatchling on the Mara-River-bank, with Maasai-Mara-vocal BGM and Mara-River-bank-noon-2 ambience.",
    "Produce a narrated children's audiobook about a baby American-alligator hatchling in the Everglades-cypress-swamp, with Everglades-Cajun-fiddle BGM and Everglades-cypress-swamp-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby gharial hatchling on the Chambal-River-bank, with Chambal-Brij-folk BGM and Chambal-River-bank-noon-2 ambience.",
    "Build a bedtime audiobook about a baby saltwater-crocodile hatchling in a Daintree-mangrove, with Daintree-Aboriginal-folk BGM and Daintree-mangrove-night-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby Cuban-crocodile hatchling in Zapata-Swamp, with Zapata-son-cubano BGM and Zapata-Swamp-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby Philippine-crocodile hatchling in Lake-Mainit, with Mindanao-kulintang BGM and Lake-Mainit-morning-2 ambience.",
    "Cook up a children's audiobook about a baby tuatara hatchling on Stephens-Island, with Stephens-Island-koauau BGM and Stephens-Island-night-2 ambience.",
    "Produce a narrated children's audiobook about a baby green-iguana hatchling on a Costa-Rican-river-tree, with Costa-Rican-marimba-2 BGM and Costa-Rican-river-tree-noon-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby marine-iguana hatchling on Fernandina-Island-lava, with Galápagos-vals BGM and Fernandina-Island-lava-shore-2 ambience.",
    "Build a bedtime audiobook about a baby Galapagos-land-iguana hatchling on South-Plaza-Island, with South-Plaza-charango BGM and South-Plaza-Island-noon-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby blue-iguana hatchling on Grand-Cayman-bluff, with Cayman-mento BGM and Grand-Cayman-bluff-noon-2 ambience.",
    "Make me a picture-book audiobook about a baby Fijian-crested-iguana hatchling on Yadua-Taba, with Fijian-meke BGM and Yadua-Taba-island-morning-2 ambience.",
    "Cook up a children's audiobook about a baby chameleon hatchling on a Madagascan-Andasibe-branch, with Andasibe-valiha BGM and Andasibe-branch-noon-2 ambience.",
    "Produce a narrated children's audiobook about a baby panther-chameleon hatchling on Nosy-Be-leaf, with Nosy-Be-salegy BGM and Nosy-Be-leaf-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby leaf-tailed-gecko hatchling in a Marojejy-rainforest, with Marojejy-marovany BGM and Marojejy-rainforest-night-2 ambience.",
    "Build a bedtime audiobook about a baby tokay-gecko hatchling on a Chiang-Mai-temple-eave, with Chiang-Mai-saw-i-2 BGM and Chiang-Mai-temple-eave-night-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby Komodo-monitor hatchling on a Rinca-Island-shore, with Rinca-Manggarai-folk BGM and Rinca-Island-shore-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby Gila-monster hatchling in a Sonoran-Desert-wash, with Sonoran-Pima-folk BGM and Sonoran-Desert-wash-morning-2 ambience.",
    "Cook up a children's audiobook about a baby beaded-lizard hatchling in a Yucatán-thornscrub, with Yucatán-trova BGM and Yucatán-thornscrub-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby horned-lizard hatchling on a Sonoran-cactus-shadow, with Sonoran-Tohono-O'odham-folk BGM and Sonoran-cactus-shadow-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby green-anole hatchling on a Florida-palmetto, with Florida-Seminole-flute-2 BGM and Florida-palmetto-noon-2 ambience.",
    "Build a bedtime audiobook about a baby alligator-snapping-turtle hatchling in a Bayou-Lafourche, with Bayou-Cajun-fiddle BGM and Bayou-Lafourche-noon-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby box-turtle hatchling in a Smoky-Mountain-leaf-litter, with Smoky-Mountain-bluegrass-2 BGM and Smoky-Mountain-leaf-litter-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby spotted-turtle hatchling in a Cape-Cod-vernal-pool, with Cape-Cod-folk-2 BGM and Cape-Cod-vernal-pool-morning-2 ambience.",
    "Cook up a children's audiobook about a baby wood-frog tadpole in a Maine-vernal-pool, with Maine-Acadian-fiddle-2 BGM and Maine-vernal-pool-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby red-eyed-tree-frog tadpole in a Costa-Rican-rainforest-pool, with Costa-Rican-marimba-3 BGM and Costa-Rican-rainforest-pool-night-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby poison-dart-frog tadpole on a Bromeliad-leaf-pool, with Costa-Rican-tamboroa BGM and Bromeliad-leaf-pool-noon-2 ambience.",
    "Build a bedtime audiobook about a baby strawberry-poison-frog tadpole on a Bocas-del-Toro-leaf, with Bocas-del-Toro-mejorana BGM and Bocas-del-Toro-leaf-noon-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby tomato-frog hatchling in a Madagascan-rice-paddy, with Madagascan-marovany-2 BGM and Madagascan-rice-paddy-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby axolotl hatchling in a Xochimilco-canal, with Xochimilco-marimba BGM and Xochimilco-canal-morning-2 ambience.",
    "Cook up a children's audiobook about a baby Chinese-giant-salamander larva in a Zhangjiajie-cave-stream, with Hunan-pipa BGM and Zhangjiajie-cave-stream-2 ambience.",
    "Produce a narrated children's audiobook about a baby Japanese-giant-salamander larva in a Hino-River-Tottori, with Tottori-koto BGM and Hino-River-Tottori-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby olm hatchling in a Postojna-cave-stream, with Slovenian-zither BGM and Postojna-cave-stream-2 ambience.",
    "Build a bedtime audiobook about a baby fire-salamander larva in a Black-Forest-stream, with Black-Forest-zither-2 BGM and Black-Forest-stream-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby spotted-salamander larva in a Connecticut-vernal-pool, with Connecticut-folk-fiddle BGM and Connecticut-vernal-pool-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby hellbender larva in a Smoky-Mountain-stream, with Smoky-Mountain-old-time BGM and Smoky-Mountain-stream-morning-2 ambience.",
    "Cook up a children's audiobook about a baby Surinam-toad tadpole in an Amazon-flooded-forest, with Suriname-kawina BGM and Amazon-flooded-forest-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby goliath-frog tadpole in a Mongo-Ma-Loba-Cameroon, with Cameroonian-makossa BGM and Mongo-Ma-Loba-Cameroon-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby cane-toad tadpole in a Northern-Territory-billabong, with Northern-Territory-didjeridu BGM and Northern-Territory-billabong-morning-2 ambience.",
    "Build a bedtime audiobook about a baby spadefoot-toad tadpole in a Mojave-Desert-rain-pool, with Mojave-Pinte-folk BGM and Mojave-Desert-rain-pool-2 ambience.",
    # ── more baby ungulate / grazer stories + BGM + grassland ambience (50) ──
    "Tell me a children's audiobook about a baby white-tailed-deer fawn in a Smoky-Mountain-meadow, with Appalachian-Smoky-folk BGM and Smoky-Mountain-meadow-dawn-2 ambience.",
    "I want an illustrated audiobook about a baby moose calf in a Kenai-Alaska-bog, with Alaskan-folk-fiddle BGM and Kenai-Alaska-bog-morning-2 ambience.",
    "Make me a bedtime audiobook about a baby red-deer calf in a Scottish-Highlands-glen, with Highland-bagpipe-2 BGM and Scottish-Highlands-glen-dawn-2 ambience.",
    "Create a picture-book audiobook about a baby roe-deer fawn in a Hampshire-wood, with Hampshire-folk BGM and Hampshire-wood-morning-2 ambience.",
    "Produce an illustrated children's tale about a baby Pere-David's-deer fawn in a Dafeng-reserve, with Dafeng-reserve-folk BGM and Dafeng-reserve-dawn-2 ambience.",
    "Cook up a narrated children's audiobook about a baby reindeer calf on a Sápmi-lichen-tundra, with Sámi-yoik BGM and Sápmi-lichen-tundra-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby caribou calf on the Porcupine-Caribou-calving-ground, with Gwich'in-fiddle BGM and Porcupine-Caribou-calving-ground-2 ambience.",
    "Build a bedtime audiobook about a baby bison calf on the Yellowstone-Lamar-Valley, with Lakota-flute BGM and Yellowstone-Lamar-Valley-dawn-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby pronghorn fawn on the Wyoming-sagebrush-prairie, with Cowboy-fiddle BGM and Wyoming-sagebrush-prairie-dawn-2 ambience.",
    "Make me a picture-book audiobook about a baby muskox calf on the Banks-Island-tundra, with Inuit-throat-singing-4 BGM and Banks-Island-tundra-morning-2 ambience.",
    "Cook up a children's audiobook about a baby gemsbok calf in the Etosha-Pan, with Damara-punch-3 BGM and Etosha-Pan-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby Thomson's-gazelle fawn on the Maasai-Mara-savanna, with Maasai-vocal-4 BGM and Maasai-Mara-savanna-dawn-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby impala fawn on the Kruger-bushveld, with Tsonga-marimba BGM and Kruger-bushveld-dawn-2 ambience.",
    "Build a bedtime audiobook about a baby kudu calf in a Zambian-mopane-woodland, with Bemba-folk BGM and Zambian-mopane-woodland-dawn-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby eland calf on the Serengeti-acacia-plain, with San-bow-song-2 BGM and Serengeti-acacia-plain-dawn-2 ambience.",
    "Make me a picture-book audiobook about a baby wildebeest calf on the Mara-River-crossing, with Maasai-vocal-5 BGM and Mara-River-crossing-dawn-2 ambience.",
    "Cook up a children's audiobook about a baby topi calf on the Maasai-Mara-Topi-Plains, with Kalenjin-folk BGM and Maasai-Mara-Topi-Plains-dawn-2 ambience.",
    "Produce a narrated children's audiobook about a baby hartebeest calf on the Lewa-Conservancy-plain, with Samburu-vocal BGM and Lewa-Conservancy-plain-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby waterbuck calf on the Okavango-floodplain, with Botswanan-mokoro-folk BGM and Okavango-floodplain-morning-2 ambience.",
    "Build a bedtime audiobook about a baby sable-antelope calf in the Hwange-mopane, with Shona-mbira BGM and Hwange-mopane-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby roan-antelope calf in the Akagera-savanna, with Rwandan-amasunzu-folk BGM and Akagera-savanna-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby Saiga-antelope calf on the Betpak-Dala-steppe, with Kazakh-dombra BGM and Betpak-Dala-steppe-morning-2 ambience.",
    "Cook up a children's audiobook about a baby Mongolian-gazelle calf on the Eastern-Mongolian-steppe, with Mongolian-morin-khuur BGM and Eastern-Mongolian-steppe-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby blackbuck fawn in the Velavadar-grassland, with Gujarati-folk BGM and Velavadar-grassland-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby chinkara fawn in the Thar-Desert-scrub, with Rajasthani-folk-tabla BGM and Thar-Desert-scrub-morning-2 ambience.",
    "Build a bedtime audiobook about a baby chital fawn in the Kanha-sal-forest, with Madhya-Pradesh-folk BGM and Kanha-sal-forest-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby sambar calf in a Periyar-tropical-woodland, with Kerala-folk-bansuri BGM and Periyar-tropical-woodland-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby Eld's-deer fawn in a Manipur-Keibul-Lamjao, with Manipuri-pena BGM and Manipur-Keibul-Lamjao-morning-2 ambience.",
    "Cook up a children's audiobook about a baby Hog-deer fawn in the Kaziranga-grass, with Assamese-bihu BGM and Kaziranga-grass-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby Père-David's-deer-rewild calf in the Dafeng-Milu, with Jiangsu-folk BGM and Dafeng-Milu-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby sika-deer fawn in a Nara-park, with Nara-shakuhachi BGM and Nara-park-morning-2 ambience.",
    "Build a bedtime audiobook about a baby fallow-deer fawn in a Richmond-Park-London, with English-folk BGM and Richmond-Park-London-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby zebra-Burchell foal on the Etosha-pan-shore, with Ovambo-folk BGM and Etosha-pan-shore-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby Grevy's-zebra foal on the Samburu-plain, with Samburu-vocal-2 BGM and Samburu-plain-morning-2 ambience.",
    "Cook up a children's audiobook about a baby mountain-zebra foal in the Hartmann-Valley-Namibia, with Himba-folk BGM and Hartmann-Valley-Namibia-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby Przewalski's-horse foal on the Hustai-Mongolian-steppe, with Mongolian-igil BGM and Hustai-Mongolian-steppe-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby kiang foal on the Changthang-Tibetan-plateau, with Tibetan-dranyen BGM and Changthang-Tibetan-plateau-morning-2 ambience.",
    "Build a bedtime audiobook about a baby onager foal on the Iranian-Touran-steppe, with Persian-tar-4 BGM and Iranian-Touran-steppe-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby Mongolian-wild-ass foal on the Galba-Gobi, with Mongolian-tovshuur BGM and Galba-Gobi-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby Bactrian-camel calf on the Galba-Gobi-dune, with Mongolian-yatga BGM and Galba-Gobi-dune-morning-2 ambience.",
    "Cook up a children's audiobook about a baby dromedary calf on the Sahara-erg-dune, with Tuareg-imzad-3 BGM and Sahara-erg-dune-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby llama cria on the Andean-Salar-de-Surire, with Aymara-zampoña-2 BGM and Andean-Salar-de-Surire-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby alpaca cria on the Apolobamba-altiplano, with Aymara-charango BGM and Apolobamba-altiplano-morning-2 ambience.",
    "Build a bedtime audiobook about a baby vicuña cria on the Pampa-Galeras-Peru, with Quechua-quena-3 BGM and Pampa-Galeras-Peru-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby guanaco chulengo on the Patagonian-pampa, with Mapuche-trutruka BGM and Patagonian-pampa-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby ibex kid in the Gran-Paradiso-Italian-Alps, with Italian-Alpine-yodel BGM and Gran-Paradiso-Italian-Alps-morning-2 ambience.",
    "Cook up a children's audiobook about a baby chamois kid in a Slovenian-Triglav, with Slovenian-zither BGM and Slovenian-Triglav-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby Markhor kid on the Hindu-Kush-cliffs, with Pashto-rabab BGM and Hindu-Kush-cliffs-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby Argali-sheep lamb on the Pamir-mountains, with Tajik-pamiri-rubab BGM and Pamir-mountains-morning-2 ambience.",
    "Build a bedtime audiobook about a baby Bighorn-sheep lamb in the Yellowstone-Slide-Lake, with Shoshone-flute BGM and Yellowstone-Slide-Lake-morning-2 ambience.",
    # ── more baby reptiles + amphibians + BGM + swamp ambience (50) ──
    "Tell me an illustrated children's audiobook about a baby green-sea-turtle hatchling on a Tortuguero-Costa-Rica beach, with Costa-Rica-marimba BGM and Tortuguero-beach-night-2 ambience.",
    "Make me a picture-book audiobook about a baby loggerhead-turtle hatchling on a Zakynthos-Greek-beach, with Greek-bouzouki BGM and Zakynthos-beach-night-2 ambience.",
    "Cook up a children's audiobook about a baby leatherback-turtle hatchling on a Grande-Riviere-Trinidad-beach, with Trinidad-steelpan BGM and Trinidad-beach-night-2 ambience.",
    "Produce a narrated children's audiobook about a baby hawksbill-turtle hatchling on a Seychelles-Cousin-Island-beach, with Seychelles-sega BGM and Cousin-Island-beach-night-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby Kemp's-ridley-turtle hatchling on a Rancho-Nuevo-Mexico-beach, with Mexican-marimba BGM and Rancho-Nuevo-beach-night-2 ambience.",
    "Build a bedtime audiobook about a baby olive-ridley-turtle hatchling on a Gahirmatha-Odisha-beach, with Odissi-pakhawaj BGM and Gahirmatha-beach-night-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby Nile-crocodile hatchling on a Mara-River-bank, with Maasai-vocal-7 BGM and Mara-River-bank-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby saltwater-crocodile hatchling on a Kakadu-billabong, with Aboriginal-didgeridoo BGM and Kakadu-billabong-morning-2 ambience.",
    "Cook up a children's audiobook about a baby American-alligator hatchling in a Everglades-marsh, with Seminole-flute BGM and Everglades-marsh-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby gharial hatchling on a Chambal-River-sandbank, with Rajasthani-sarangi BGM and Chambal-River-sandbank-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby Cuban-crocodile hatchling in a Zapata-Swamp, with Cuban-tres BGM and Zapata-Swamp-morning-2 ambience.",
    "Build a bedtime audiobook about a baby Komodo-dragon hatchling on a Komodo-Island, with Indonesian-gamelan BGM and Komodo-Island-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby green-iguana on a Costa-Rica-canopy, with Costa-Rica-quijongo BGM and Costa-Rica-canopy-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby marine-iguana on a Galapagos-Fernandina-rocks, with Ecuadorian-rondador BGM and Fernandina-shore-morning-2 ambience.",
    "Cook up a children's audiobook about a baby land-iguana on a Galapagos-Santa-Fe-Island, with Ecuadorian-pasillo BGM and Santa-Fe-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby Fiji-banded-iguana on a Yadua-Taba-Island, with Fijian-meke BGM and Yadua-Taba-canopy-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby panther-chameleon on a Madagascar-eastern-rainforest-canopy, with Malagasy-valiha BGM and Madagascar-canopy-morning-2 ambience.",
    "Build a bedtime audiobook about a baby veiled-chameleon on a Yemeni-highland-tree, with Yemeni-oud BGM and Yemeni-highland-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby leaf-tailed-gecko on a Ranomafana-leaf-litter, with Malagasy-marovany BGM and Ranomafana-leaf-litter-night-2 ambience.",
    "Make me a picture-book audiobook about a baby tokay-gecko on a Bali-temple-wall, with Balinese-gamelan BGM and Bali-temple-wall-night-2 ambience.",
    "Cook up a children's audiobook about a baby leopard-gecko in a Pakistani-Balochistan-rocky-plain, with Baloch-suroz BGM and Balochistan-rocky-plain-night-2 ambience.",
    "Produce a narrated children's audiobook about a baby crested-gecko on a New-Caledonia-Île-des-Pins-canopy, with Kanak-bwanjep BGM and Île-des-Pins-canopy-night-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby blue-tongue-skink on a Australian-eucalypt-floor, with Aboriginal-clapsticks BGM and Australian-eucalypt-floor-morning-2 ambience.",
    "Build a bedtime audiobook about a baby thorny-devil on a Australian-Great-Sandy-Desert, with Anangu-yidaki BGM and Great-Sandy-Desert-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby tuatara on a Stephens-Island-burrow, with Maori-koauau BGM and Stephens-Island-burrow-night-2 ambience.",
    "Make me a picture-book audiobook about a baby red-eyed-tree-frog on a La-Selva-Costa-Rica-leaf, with Costa-Rica-ocarina BGM and La-Selva-leaf-night-2 ambience.",
    "Cook up a children's audiobook about a baby poison-dart-frog tadpole in a Yasuni-Ecuador-bromeliad, with Quichua-pingullo BGM and Yasuni-bromeliad-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby glass-frog tadpole in a Monteverde-Costa-Rica-stream, with Costa-Rica-pasillo BGM and Monteverde-stream-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby Wallace's-flying-frog on a Borneo-Mulu-canopy, with Bornean-sape BGM and Borneo-Mulu-canopy-night-2 ambience.",
    "Build a bedtime audiobook about a baby Goliath-frog on a Cameroon-Mbini-stream, with Cameroonian-bikutsi BGM and Cameroon-Mbini-stream-night-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby American-bullfrog tadpole in a Pennsylvania-pond, with Appalachian-banjo BGM and Pennsylvania-pond-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby cane-toad in a Queensland-cane-field, with Queensland-bushdance BGM and Queensland-cane-field-night-2 ambience.",
    "Cook up a children's audiobook about a baby axolotl in a Xochimilco-canal, with Xochimilco-jarana BGM and Xochimilco-canal-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby Chinese-giant-salamander in a Zhangjiajie-stream, with Tujia-bamboo-flute BGM and Zhangjiajie-stream-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby Japanese-giant-salamander in a Hiroshima-Tonoyama-stream, with Japanese-shakuhachi BGM and Hiroshima-stream-morning-2 ambience.",
    "Build a bedtime audiobook about a baby fire-salamander on a Black-Forest-leaf-litter, with Black-Forest-zither BGM and Black-Forest-leaf-litter-night-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby alpine-newt on an Austrian-Tyrol-pond, with Tyrolean-zither BGM and Austrian-Tyrol-pond-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby smooth-newt in a Norfolk-Broads-pond, with English-folk-fiddle BGM and Norfolk-Broads-pond-morning-2 ambience.",
    "Cook up a children's audiobook about a baby caecilian in a Western-Ghats-leaf-litter, with Carnatic-mridangam BGM and Western-Ghats-leaf-litter-night-2 ambience.",
    "Produce a narrated children's audiobook about a baby anaconda hatchling in a Pantanal-floodplain, with Pantanaleiro-viola BGM and Pantanal-floodplain-night-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby reticulated-python hatchling on a Sumatra-Bukit-Lawang-canopy, with Sumatran-rebana BGM and Bukit-Lawang-canopy-night-2 ambience.",
    "Build a bedtime audiobook about a baby green-tree-python hatchling on a Daintree-canopy, with Aboriginal-yidaki BGM and Daintree-canopy-night-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby ball-python hatchling on a Ghanaian-savanna-burrow, with Ghanaian-kpanlogo BGM and Ghanaian-savanna-burrow-night-2 ambience.",
    "Make me a picture-book audiobook about a baby king-cobra hatchling on a Kerala-Western-Ghats-leaf-litter, with Kerala-chenda BGM and Kerala-Western-Ghats-night-2 ambience.",
    "Cook up a children's audiobook about a baby black-mamba hatchling on a Kruger-Park-rock-cleft, with Tsonga-xitende BGM and Kruger-Park-rock-cleft-night-2 ambience.",
    "Produce a narrated children's audiobook about a baby coral-snake hatchling on a Florida-pine-flatwoods, with Seminole-flute-2 BGM and Florida-pine-flatwoods-night-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby gartersnake on a Manitoba-Narcisse-snake-pit, with Métis-fiddle BGM and Narcisse-snake-pit-morning-2 ambience.",
    "Build a bedtime audiobook about a baby rat-snake on a Smoky-Mountains-rock-ledge, with Cherokee-flute BGM and Smoky-Mountains-rock-ledge-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby green-anaconda on a Llanos-Venezuelan-flooded-savanna, with Venezuelan-joropo BGM and Llanos-flooded-savanna-night-2 ambience.",
    "Make me a picture-book audiobook about a baby gaboon-viper hatchling on a Cross-River-Nigerian-leaf-litter, with Cross-River-Igbo-ekwe BGM and Cross-River-leaf-litter-night-2 ambience.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
