"""x15 vid_analysis_cr SFT.
Chain: IntakeVideo → VideoAnalysis → Story → Screenplay → KeyFrame → Video → Compositor.
Trigger: user uploads reference video for analysis + new cinematic mini-drama. NO music/ambience/subtitle.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a clip from a David Fincher film as reference — please analyze it and produce a 1-minute new mini-drama inspired by it.",
    "Here's a Paul Thomas Anderson reference scene — analyze the long take and create a 45-second new cinematic short.",
    "I'm sending you a Greta Gerwig film clip — please analyze and produce a 30-second new mini-drama.",
    "Uploading a Quentin Tarantino dialogue scene — analyze the rhythm and create a 2-minute new cinematic short.",
    "Here's a Spike Lee reference scene — analyze its tone and produce a 1-minute new mini-drama.",
    "I have a reference scene from a Spike Jonze film — please analyze and create a 30-second new cinematic short.",
    "Uploading a Kathryn Bigelow combat-scene reference — analyze the kinetic camera and produce a 45-second new mini-drama.",
    "Here's a Sofia-Coppola reference — analyze the languid pacing and create a 1-minute new cinematic short.",
    "I'm sending you a Lulu Wang reference scene — please analyze the family-drama framing and produce a 2-minute new mini-drama.",
    "Uploading a Chloé Zhao reference — analyze its naturalist look and create a 30-second new cinematic short.",
    "Here's a Barry Jenkins reference scene — analyze the close-ups and produce a 45-second new mini-drama.",
    "I have a reference scene from a Sean Baker film — please analyze its handheld energy and create a 1-minute new cinematic short.",
    "Uploading a clip from a Joel Coen film — analyze its deadpan tone and produce a 30-second new mini-drama.",
    "Here's a Wes Anderson reference scene — analyze the symmetric framing and create a 2-minute new cinematic short.",
    "I'm sending you a Yorgos Lanthimos film clip — please analyze the deadpan stillness and produce a 1-minute new mini-drama.",
    "Uploading a Park-Chan-wook reference scene — analyze the elaborate staging and create a 30-second new cinematic short.",
    "Here's a clip from a Hong Sang-soo film — analyze the conversational realism and produce a 45-second new mini-drama.",
    "I have a Pedro Almodóvar reference scene — please analyze its color palette and create a 1-minute new cinematic short.",
    "Uploading an Alejandro González Iñárritu reference — analyze the overlapping narratives and produce a 30-second new mini-drama.",
    "Here's a Lucrecia Martel reference scene — analyze the ambient sound design and create a 2-minute new cinematic short.",
    "I'm sending you a Pawel Pawlikowski reference scene — please analyze the black-and-white framing and produce a 1-minute new mini-drama.",
    "Uploading an Asghar Farhadi reference — analyze the moral ambiguity and create a 45-second new cinematic short.",
    "Here's a Jafar Panahi reference scene — analyze the constrained camera and produce a 30-second new mini-drama.",
    "I have a Ramin Bahrani reference scene — please analyze its working-class realism and create a 1-minute new cinematic short.",
    "Uploading a Mira Nair reference — analyze the diaspora-portrayal and produce a 30-second new mini-drama.",
    "Here's a Deepa Mehta reference scene — analyze its political layering and create a 45-second new cinematic short.",
    "I'm sending you a Bahman Ghobadi reference — please analyze the Kurdish landscape framing and produce a 1-minute new mini-drama.",
    "Uploading a Mohsen Makhmalbaf reference — analyze the cinema-vérité texture and create a 30-second new cinematic short.",
    "Here's a Samira Makhmalbaf reference — analyze the youth-perspective framing and produce a 2-minute new mini-drama.",
    "I have a Tarsem Singh reference — please analyze its painterly visual style and create a 1-minute new cinematic short.",
    "Uploading a Steve McQueen reference scene — analyze its long-take intensity and produce a 45-second new mini-drama.",
    "Here's a Lynne Ramsay reference scene — analyze its sensory-dread close-ups and create a 30-second new cinematic short.",
    "I'm sending you a Jane Campion reference — please analyze the female-gaze framing and produce a 1-minute new mini-drama.",
    "Uploading a Andrea Arnold reference scene — analyze the handheld realism and create a 30-second new cinematic short.",
    "Here's a Sarah Polley reference scene — analyze the chamber-drama framing and produce a 45-second new mini-drama.",
    # ── more reference-video → new cinematic shorts (50) ──────────────
    "Uploading a Robert-Bresson reference scene — please analyze its austere model-actor performance and produce a 1-minute new mini-drama.",
    "Here's a Carl-Theodor-Dreyer Joan-of-Arc close-up — analyze its facial-stillness and create a 45-second new cinematic short.",
    "I'm sending you a Jean-Pierre-Melville noir scene — please analyze the silent professionalism and produce a 30-second new mini-drama.",
    "Uploading a Jacques-Tati Playtime tableau — analyze its physical-comedy choreography and create a 2-minute new cinematic short.",
    "Here's an Eric-Rohmer conversational scene — analyze its talking rhythm and produce a 1-minute new mini-drama.",
    "I have a reference scene from a Jacques-Demy musical — please analyze its candy-colored choreography and create a 30-second new cinematic short.",
    "Uploading a Louis-Malle reference — analyze its observational tone and produce a 45-second new mini-drama.",
    "Here's a Bertolucci reference scene — analyze the operatic staging and create a 1-minute new cinematic short.",
    "I'm sending you a Pier-Paolo-Pasolini reference — please analyze its lay-actor framing and produce a 2-minute new mini-drama.",
    "Uploading an Antonioni L'Avventura reference — analyze the absences in the frame and create a 30-second new cinematic short.",
    "Here's a Dario-Argento giallo reference — analyze its primary-color lighting and produce a 45-second new mini-drama.",
    "I have a Mario-Bava reference — please analyze its expressionist horror and create a 1-minute new cinematic short.",
    "Uploading a Sergio-Leone spaghetti-western reference — analyze its extreme close-ups and produce a 30-second new mini-drama.",
    "Here's a Lina-Wertmüller reference — analyze its political-grotesque tone and create a 2-minute new cinematic short.",
    "I'm sending you a Marco-Bellocchio reference — please analyze its familial tension and produce a 1-minute new mini-drama.",
    "Uploading a Paolo-Sorrentino reference — analyze its ornamental Roman tableau and create a 45-second new cinematic short.",
    "Here's a Matteo-Garrone reference — analyze its naturalistic Naples grit and produce a 30-second new mini-drama.",
    "I have an Alice-Rohrwacher reference — please analyze its rural-magical realism and create a 1-minute new cinematic short.",
    "Uploading a Luca-Guadagnino reference — analyze its summer sensuality and produce a 2-minute new mini-drama.",
    "Here's a Nanni-Moretti reference scene — analyze its self-aware monologue and create a 30-second new cinematic short.",
    "I'm sending you a Carlos-Saura flamenco reference — please analyze its dance choreography and produce a 45-second new mini-drama.",
    "Uploading a Víctor-Erice reference — analyze its child-perspective stillness and create a 1-minute new cinematic short.",
    "Here's a Luis-García-Berlanga ensemble scene — analyze its Spanish satire rhythm and produce a 30-second new mini-drama.",
    "I have a Pere-Portabella avant-garde reference — please analyze its sound-image rupture and create a 45-second new cinematic short.",
    "Uploading a Manoel-de-Oliveira reference — analyze its theatrical staging and produce a 2-minute new mini-drama.",
    "Here's a Pedro-Costa reference — analyze its hand-held Lisbon-housing observation and create a 1-minute new cinematic short.",
    "I'm sending you a Miguel-Gomes reference — please analyze its formally-divided narrative and produce a 30-second new mini-drama.",
    "Uploading a Howard-Hawks western reference — analyze its laconic dialogue and create a 45-second new cinematic short.",
    "Here's a John-Ford Searchers reference — analyze its desert-vista framing and produce a 1-minute new mini-drama.",
    "I have a Billy-Wilder noir reference — please analyze its cynical voice-over and create a 30-second new cinematic short.",
    "Uploading a Frank-Capra reference — analyze its populist montage and produce a 2-minute new mini-drama.",
    "Here's a George-Cukor women's-picture reference — analyze its drawing-room blocking and create a 1-minute new cinematic short.",
    "I'm sending you a Douglas-Sirk 1950s-melodrama reference — please analyze its saturated colors and produce a 45-second new mini-drama.",
    "Uploading a Vincente-Minnelli musical reference — analyze its mobile camera and create a 30-second new cinematic short.",
    "Here's a Stanley-Donen Singin'-in-the-Rain reference — analyze its dance choreography and produce a 1-minute new mini-drama.",
    "I have a Martin-Scorsese Mean-Streets reference — please analyze its needle-drop kinetic energy and create a 45-second new cinematic short.",
    "Uploading a Francis-Ford-Coppola Godfather reference — analyze its operatic staging and produce a 2-minute new mini-drama.",
    "Here's a Robert-Altman ensemble reference — analyze its overlapping-dialogue rhythm and create a 30-second new cinematic short.",
    "I'm sending you a Hal-Ashby reference — please analyze its 1970s-character-study tone and produce a 1-minute new mini-drama.",
    "Uploading a Sidney-Lumet reference — analyze its claustrophobic interiors and create a 45-second new cinematic short.",
    "Here's a Sam-Peckinpah western reference — analyze its slow-motion violence ballet and produce a 30-second new mini-drama.",
    "I have a Brian-De-Palma split-screen reference — please analyze its formal duality and create a 1-minute new cinematic short.",
    "Uploading a Paul-Schrader reference — analyze its God's-lonely-man journaling and produce a 2-minute new mini-drama.",
    "Here's a Michael-Mann Heat reference — analyze its glassy nightscape and create a 45-second new cinematic short.",
    "I'm sending you a David-O.-Russell reference — please analyze its kinetic ensemble dialogue and produce a 30-second new mini-drama.",
    "Uploading a John-Carpenter The-Thing reference — analyze its synth-and-shadow tension and create a 1-minute new cinematic short.",
    "Here's a George-Romero Night-of-the-Living-Dead reference — analyze its low-budget claustrophobia and produce a 45-second new mini-drama.",
    "I have a Tom-Tykwer Run-Lola-Run reference — please analyze its three-act-loop structure and create a 30-second new cinematic short.",
    "Uploading a Doris-Dörrie reference — analyze its German-Japanese cross-cultural framing and produce a 2-minute new mini-drama.",
    "Here's a David-Lean Lawrence-of-Arabia reference — analyze its desert wide-shots and create a 1-minute new cinematic short.",
    # ── more reference-video → new cinematic shorts (50) ──────────────
    "Uploading a Federico-Fellini 8½ reference — please analyze its dreamlike memory parade and produce a 1-minute new mini-drama.",
    "Here's an F.W.-Murnau Sunrise reference — analyze its expressionist city-and-country and create a 45-second new cinematic short.",
    "I'm sending you a Fritz-Lang Metropolis reference — please analyze its monumental art-deco staging and produce a 30-second new mini-drama.",
    "Uploading a Charlie-Chaplin City-Lights reference — analyze its silent pantomime tenderness and create a 2-minute new cinematic short.",
    "Here's a Buster-Keaton silent-comedy reference — analyze its deadpan stunt geometry and produce a 1-minute new mini-drama.",
    "I have a Harold-Lloyd silent-comedy reference — please analyze its everyman peril and create a 30-second new cinematic short.",
    "Uploading an Orson-Welles Citizen-Kane reference — analyze its deep-focus monumentality and produce a 45-second new mini-drama.",
    "Here's a John-Huston noir reference — analyze its hard-bitten ensemble and create a 1-minute new cinematic short.",
    "I'm sending you an Anthony-Mann western reference — please analyze its psychological vista and produce a 2-minute new mini-drama.",
    "Uploading a Budd-Boetticher western reference — analyze its lean-frame morality play and create a 30-second new cinematic short.",
    "Here's a Don-Siegel hardboiled reference — analyze its terse procedural rhythm and produce a 45-second new mini-drama.",
    "I have a Sam-Fuller pulp reference — please analyze its tabloid-headline urgency and create a 1-minute new cinematic short.",
    "Uploading a Paul-Verhoeven Robocop reference — analyze its satirical tech-violence and produce a 30-second new mini-drama.",
    "Here's a Ridley-Scott Blade-Runner reference — analyze its rain-and-neon dystopia and create a 2-minute new cinematic short.",
    "I'm sending you a James-Cameron Aliens reference — please analyze its kinetic squad-tension and produce a 1-minute new mini-drama.",
    "Uploading a John-McTiernan Predator reference — analyze its jungle-stalk dread and create a 45-second new cinematic short.",
    "Here's a Walter-Hill The-Warriors reference — analyze its stylized urban myth and produce a 30-second new mini-drama.",
    "I have a Michael-Cimino Deer-Hunter reference — please analyze its long-take Pennsylvania communion and create a 2-minute new cinematic short.",
    "Uploading a Terrence-Malick Days-of-Heaven reference — analyze its magic-hour pastoral and produce a 1-minute new mini-drama.",
    "Here's a Richard-Linklater Boyhood reference — analyze its longitudinal everyday and create a 30-second new cinematic short.",
    "I'm sending you a Gus-Van-Sant Elephant reference — please analyze its long-Steadicam school-day and produce a 45-second new mini-drama.",
    "Uploading a John-Cassavetes A-Woman-Under-the-Influence reference — analyze its raw improvisational intimacy and create a 1-minute new cinematic short.",
    "Here's a Kenneth-Lonergan Manchester-by-the-Sea reference — analyze its understated grief and produce a 2-minute new mini-drama.",
    "I have a Greta-Gerwig Lady-Bird reference — please analyze its rapid character-cluster and create a 30-second new cinematic short.",
    "Uploading a Noah-Baumbach Marriage-Story reference — analyze its wounded dialogue volley and produce a 45-second new mini-drama.",
    "Here's a Whit-Stillman Metropolitan reference — analyze its young-set mannered talk and create a 1-minute new cinematic short.",
    "I'm sending you a Hal-Hartley Trust reference — please analyze its deadpan small-town logic and produce a 30-second new mini-drama.",
    "Uploading a Todd-Solondz Happiness reference — analyze its uncomfortable suburban gaze and create a 2-minute new cinematic short.",
    "Here's a Harmony-Korine Gummo reference — analyze its loose vignette montage and produce a 1-minute new mini-drama.",
    "I have a Larry-Clark Kids reference — please analyze its handheld youth-portraiture and create a 30-second new cinematic short.",
    "Uploading a Nicolas-Winding-Refn Drive reference — analyze its synthwave silence and produce a 45-second new mini-drama.",
    "Here's an Alejandro-Jodorowsky El-Topo reference — analyze its surreal pilgrimage and create a 1-minute new cinematic short.",
    "I'm sending you an Athina-Rachel-Tsangari Attenberg reference — please analyze its Greek deadpan tableau and produce a 30-second new mini-drama.",
    "Uploading a Jessica-Hausner Lourdes reference — analyze its ascetic Catholic stillness and create a 45-second new cinematic short.",
    "Here's a Markus-Schleinzer Michael reference — analyze its measured banality of evil and produce a 1-minute new mini-drama.",
    "I have a Sebastian-Schipper Victoria reference — please analyze its single-take urban heist and create a 2-minute new cinematic short.",
    "Uploading a Volker-Schlöndorff Tin-Drum reference — analyze its grotesque historical fable and produce a 30-second new mini-drama.",
    "Here's a Wolfgang-Petersen Das-Boot reference — analyze its claustrophobic submarine tension and create a 1-minute new cinematic short.",
    "I'm sending you an Edgar-Reitz Heimat reference — please analyze its village-chronicle pacing and produce a 45-second new mini-drama.",
    "Uploading an Andreas-Dresen Wolke-9 reference — analyze its later-life intimacy and create a 30-second new cinematic short.",
    "Here's a Dominik-Graf Fabian reference — analyze its Weimar-era restless camera and produce a 1-minute new mini-drama.",
    "I have a Margarethe-von-Trotta Hannah-Arendt reference — please analyze its philosophical interiority and create a 2-minute new cinematic short.",
    "Uploading a Helma-Sanders-Brahms Germany-Pale-Mother reference — analyze its postwar maternal narration and produce a 30-second new mini-drama.",
    "Here's a Werner-Schroeter Malina reference — analyze its operatic interior breakdown and create a 45-second new cinematic short.",
    "I'm sending you an Alexander-Kluge Yesterday-Girl reference — please analyze its essayistic interruption and produce a 1-minute new mini-drama.",
    "Uploading a Romuald-Karmakar Manila reference — analyze its tropical close-observation and create a 30-second new cinematic short.",
    "Here's a Christian-Schwochow Cracks-in-the-Shell reference — analyze its psychological theater frame and produce a 45-second new mini-drama.",
    "I have a Stanley-Kubrick The-Shining reference — please analyze its symmetrical Steadicam dread and create a 2-minute new cinematic short.",
    "Uploading a James-Wan The-Conjuring reference — analyze its haunted-house jump scares and produce a 1-minute new mini-drama.",
    "Here's a Sam-Raimi Evil-Dead reference — analyze its shaky-cam cabin terror and create a 30-second new cinematic short.",
    # ── more reference-video → new cinematic shorts (50) ──────────────
    "Uploading an Albert-Lamorisse Red-Balloon reference — please analyze its silent Parisian-childhood whimsy and produce a 1-minute new mini-drama.",
    "Here's a Ladislaw-Starewicz stop-motion-pioneer reference — analyze its insect-puppetry uncanny and create a 45-second new cinematic short.",
    "I'm sending you a Norman-McLaren animated-shorts reference — please analyze its hand-painted-frame rhythm and produce a 30-second new mini-drama.",
    "Uploading a Len-Lye direct-film reference — analyze its scratched-emulsion kinesis and create a 2-minute new cinematic short.",
    "Here's a Stan-Brakhage avant-garde reference — analyze its hand-painted celluloid ecstatic and produce a 1-minute new mini-drama.",
    "I have a Maya-Deren avant-garde reference — please analyze its trance-dance-and-mirror choreography and create a 30-second new cinematic short.",
    "Uploading a Kenneth-Anger occult avant-garde reference — analyze its glamour-magick montage and produce a 45-second new mini-drama.",
    "Here's a Jonas-Mekas diaristic avant-garde reference — analyze its first-person 16mm journal and create a 1-minute new cinematic short.",
    "I'm sending you a Bruce-Conner found-footage reference — please analyze its compiled-archive shock-and-elegy and produce a 2-minute new mini-drama.",
    "Uploading a Hollis-Frampton structural reference — analyze its alphabet-of-images temporal puzzle and create a 30-second new cinematic short.",
    "Here's a Michael-Snow structural reference — analyze its long-zoom durational room and produce a 45-second new mini-drama.",
    "I have a James-Benning landscape-essay reference — please analyze its single-take pastoral frame and create a 1-minute new cinematic short.",
    "Uploading a Peter-Hutton silent landscape reference — analyze its black-and-white observational poem and produce a 30-second new mini-drama.",
    "Here's a Sharon-Lockhart durational reference — analyze its long-take working-body study and create a 2-minute new cinematic short.",
    "I'm sending you a Heinz-Emigholz architectural reference — please analyze its slow architectural inventory and produce a 1-minute new mini-drama.",
    "Uploading a Jean-Vigo Zéro-de-conduite reference — analyze its boarding-school revolt slow-motion and create a 45-second new cinematic short.",
    "Here's a Jean-Renoir La-Grande-Illusion reference — analyze its prison-camp humanist deep-staging and produce a 30-second new mini-drama.",
    "I have a Marcel-Carné Quai-des-brumes reference — please analyze its fog-slick poetic-realism and create a 1-minute new cinematic short.",
    "Uploading a René-Clair À-Nous-la-Liberté reference — analyze its musical-machine factory satire and produce a 2-minute new mini-drama.",
    "Here's a Sacha-Guitry chronological-narrative reference — analyze its breezy fourth-wall exposition and create a 30-second new cinematic short.",
    "I'm sending you a Roberto-Rossellini Rome-Open-City reference — please analyze its neorealist street observation and produce a 45-second new mini-drama.",
    "Uploading a Vittorio-De-Sica Bicycle-Thieves reference — analyze its quiet father-son framing and create a 1-minute new cinematic short.",
    "Here's a Luchino-Visconti The-Leopard reference — analyze its crumbling-aristocracy ballroom and produce a 30-second new mini-drama.",
    "I have a Cesare-Zavattini neorealist reference — please analyze its 'a-day-in-the-life' framing and create a 2-minute new cinematic short.",
    "Uploading a Pier-Paolo-Pasolini Mamma-Roma reference — analyze its Roman-borgata Madonna-and-son and produce a 1-minute new mini-drama.",
    "Here's a Bernardo-Bertolucci 1900 reference — analyze its multi-decade epic agrarian gaze and create a 45-second new cinematic short.",
    "I'm sending you a Liliana-Cavani The-Night-Porter reference — please analyze its postwar transgressive memory and produce a 30-second new mini-drama.",
    "Uploading a Marco-Ferreri La-Grande-Bouffe reference — analyze its decadent-feast satire and create a 2-minute new cinematic short.",
    "Here's an Ettore-Scola Le-Bal reference — analyze its single-set decade-spanning waltz and produce a 1-minute new mini-drama.",
    "I have a Vittorio-Taviani Padre-Padrone reference — please analyze its Sardinian-shepherd autobiography and create a 30-second new cinematic short.",
    "Uploading an Ermanno-Olmi Il-Posto reference — analyze its small-job Milanese melancholy and produce a 45-second new mini-drama.",
    "Here's a Giuseppe-De-Santis Bitter-Rice reference — analyze its rice-paddy ensemble glamour and create a 1-minute new cinematic short.",
    "I'm sending you a Gillo-Pontecorvo Battle-of-Algiers reference — please analyze its docu-fiction urban-resistance and produce a 30-second new mini-drama.",
    "Uploading a Costa-Gavras Z reference — analyze its propulsive political-thriller cutting and create a 2-minute new cinematic short.",
    "Here's an Alain-Resnais Last-Year-at-Marienbad reference — analyze its labyrinthine memory architecture and produce a 1-minute new mini-drama.",
    "I have a Marguerite-Duras India-Song reference — please analyze its decoupled-voice tableau and create a 30-second new cinematic short.",
    "Uploading a Chantal-Akerman Jeanne-Dielman reference — analyze its real-time domestic ritual and produce a 45-second new mini-drama.",
    "Here's an Agnès-Varda The-Gleaners-and-I reference — analyze its essay-film first-person warmth and create a 1-minute new cinematic short.",
    "I'm sending you a Margarethe-von-Trotta The-German-Sisters reference — please analyze its political-and-personal sisterhood and produce a 30-second new mini-drama.",
    "Uploading a Jean-Eustache The-Mother-and-the-Whore reference — analyze its post-1968 talky disenchantment and create a 2-minute new cinematic short.",
    "Here's a Maurice-Pialat À-Nos-Amours reference — analyze its volatile family-drama immediacy and produce a 1-minute new mini-drama.",
    "I have a Jacques-Doillon Ponette reference — please analyze its child-actor naturalism and create a 30-second new cinematic short.",
    "Uploading a Léos-Carax The-Lovers-on-the-Bridge reference — analyze its bridge-of-arts romantic excess and produce a 45-second new mini-drama.",
    "Here's an Olivier-Assayas Demonlover reference — analyze its glassy corporate-thriller paranoia and create a 1-minute new cinematic short.",
    "I'm sending you a Catherine-Breillat Romance reference — please analyze its intimate-procedural transgression and produce a 30-second new mini-drama.",
    "Uploading a Claire-Denis Beau-Travail reference — analyze its Foreign-Legion bodily-rite and create a 2-minute new cinematic short.",
    "Here's a Bruno-Dumont L'Humanité reference — analyze its Pas-de-Calais ascetic landscape and produce a 1-minute new mini-drama.",
    "I have a Gaspar-Noé Irréversible reference — please analyze its reverse-chronology nightmare and create a 30-second new cinematic short.",
    "Uploading a Philippe-Garrel Regular-Lovers reference — analyze its post-1968 Parisian melancholy and produce a 45-second new mini-drama.",
    "Here's an Arnaud-Desplechin Esther-Kahn reference — analyze its London-stage actress arc and create a 1-minute new cinematic short.",
    # ── more East-Asian auteur cinema (50) ──
    "Here's a Wong-Kar-wai In-the-Mood-for-Love reference — analyze its slow-motion alley walk and produce a 1-minute new mini-drama.",
    "Uploading a Wong-Kar-wai Chungking-Express reference — analyze its hand-held Hong-Kong eatery vibe and create a 45-second new cinematic short.",
    "I'm sending you a Wong-Kar-wai Happy-Together reference — please analyze its Buenos-Aires longing and produce a 30-second new mini-drama.",
    "I have a Wong-Kar-wai Fallen-Angels reference — please analyze its blue-fluorescent late-night and create a 1-minute new cinematic short.",
    "Uploading a Wong-Kar-wai 2046 reference — analyze its time-loop hotel-corridor and produce a 45-second new mini-drama.",
    "Here's a Hou-Hsiao-Hsien Three-Times reference — analyze its three-era love-triptych and create a 1-minute new cinematic short.",
    "I have an Edward-Yang Yi-Yi reference — please analyze its multi-generational Taipei family and produce a 30-second new mini-drama.",
    "Uploading an Edward-Yang A-Brighter-Summer-Day reference — analyze its 1960s-Taiwan-youth-gang and create a 2-minute new cinematic short.",
    "Here's a Tsai-Ming-liang Vive-l'Amour reference — analyze its empty-apartment ennui and produce a 1-minute new mini-drama.",
    "I'm sending you a Tsai-Ming-liang Goodbye-Dragon-Inn reference — please analyze its dying-cinema final-screening and create a 30-second new cinematic short.",
    "Uploading a Tsai-Ming-liang Stray-Dogs reference — analyze its slow-cinema homeless duration and produce a 45-second new mini-drama.",
    "Here's an Ang-Lee Crouching-Tiger-Hidden-Dragon reference — analyze its bamboo-forest fight and create a 1-minute new cinematic short.",
    "I have an Ang-Lee Brokeback-Mountain reference — please analyze its Wyoming-landscape longing and produce a 30-second new mini-drama.",
    "Uploading an Ang-Lee Lust-Caution reference — analyze its 1940s Shanghai espionage and create a 2-minute new cinematic short.",
    "Here's a Zhang-Yimou Raise-the-Red-Lantern reference — analyze its courtyard-mansion ritual and produce a 1-minute new mini-drama.",
    "I'm sending you a Zhang-Yimou Hero reference — please analyze its color-coded martial-arts and create a 30-second new cinematic short.",
    "Uploading a Zhang-Yimou Curse-of-the-Golden-Flower reference — analyze its imperial-palace gold-spectacle and produce a 45-second new mini-drama.",
    "Here's a Chen-Kaige Farewell-My-Concubine reference — analyze its Peking-opera lifelong arc and create a 1-minute new cinematic short.",
    "I have a Jia-Zhangke Still-Life reference — please analyze its Three-Gorges relocation poignancy and produce a 30-second new mini-drama.",
    "Uploading a Jia-Zhangke Mountains-May-Depart reference — analyze its three-decade time-shift and create a 45-second new cinematic short.",
    "Here's a Jia-Zhangke Ash-Is-Purest-White reference — analyze its jianghu-couple geographic sweep and produce a 1-minute new mini-drama.",
    "I'm sending you a Lou-Ye Suzhou-River reference — please analyze its Shanghai-canal POV-noir and create a 30-second new cinematic short.",
    "Uploading a Lou-Ye Summer-Palace reference — analyze its 1980s campus-political pulse and produce a 2-minute new mini-drama.",
    "Here's a Bi-Gan Long-Day's-Journey-into-Night reference — analyze its 3D one-take dream and create a 1-minute new cinematic short.",
    "I have a Bi-Gan Kaili-Blues reference — please analyze its 41-minute long-take and produce a 30-second new mini-drama.",
    "Uploading a Hirokazu-Kore-eda Shoplifters reference — analyze its makeshift-Tokyo family and create a 45-second new cinematic short.",
    "Here's a Hirokazu-Kore-eda Still-Walking reference — analyze its single-day-anniversary intimacy and produce a 1-minute new mini-drama.",
    "I'm sending you a Hirokazu-Kore-eda After-the-Storm reference — please analyze its post-divorce typhoon-night and create a 30-second new cinematic short.",
    "Uploading a Hirokazu-Kore-eda Like-Father-Like-Son reference — analyze its hospital-swap fatherhood and produce a 45-second new mini-drama.",
    "Here's a Naomi-Kawase The-Mourning-Forest reference — analyze its dementia-forest pilgrimage and create a 1-minute new cinematic short.",
    "I have a Naomi-Kawase Sweet-Bean reference — please analyze its dorayaki-shop apprentice and produce a 30-second new mini-drama.",
    "Uploading a Hayao-Kawai Tokyo-Sonata reference — analyze its post-recession Tokyo family and create a 2-minute new cinematic short.",
    "Here's a Kiyoshi-Kurosawa Pulse reference — analyze its J-horror digital-haunting and produce a 1-minute new mini-drama.",
    "I'm sending you a Kiyoshi-Kurosawa Cure reference — please analyze its hypnotist-detective dread and create a 30-second new cinematic short.",
    "Uploading a Takeshi-Kitano Hana-bi reference — analyze its yakuza-painter melancholy and produce a 45-second new mini-drama.",
    "Here's a Takeshi-Kitano Sonatine reference — analyze its Okinawa beach-yakuza idleness and create a 1-minute new cinematic short.",
    "I have a Shunji-Iwai All-About-Lily-Chou-Chou reference — please analyze its rural-bullying internet-fandom and produce a 30-second new mini-drama.",
    "Uploading a Shunji-Iwai Love-Letter reference — analyze its Otaru-snowfield missed-letter and create a 45-second new cinematic short.",
    "Here's a Tomu-Uchida Bloody-Spear-at-Mount-Fuji reference — analyze its samurai-procession humanism and produce a 1-minute new mini-drama.",
    "I'm sending you a Yasujirō-Ozu Tokyo-Story reference — please analyze its low-tatami family-stillness and create a 30-second new cinematic short.",
    "Uploading a Yasujirō-Ozu Late-Spring reference — analyze its father-daughter quiet-departure and produce a 2-minute new mini-drama.",
    "Here's a Mikio-Naruse When-a-Woman-Ascends-the-Stairs reference — analyze its Ginza-bar-hostess melancholy and create a 1-minute new cinematic short.",
    "I have a Kenji-Mizoguchi Ugetsu reference — please analyze its 16th-c. ghost-bride lakeside and produce a 30-second new mini-drama.",
    "Uploading a Kenji-Mizoguchi Sansho-the-Bailiff reference — analyze its Heian-orphan-slave epic and create a 45-second new cinematic short.",
    "Here's an Akira-Kurosawa Seven-Samurai reference — analyze its rain-mud bandit-village climax and produce a 1-minute new mini-drama.",
    "I'm sending you an Akira-Kurosawa Rashomon reference — please analyze its forest-glade truth-multiplicity and create a 30-second new cinematic short.",
    "Uploading an Akira-Kurosawa Ran reference — analyze its Sengoku-period flag-color carnage and produce a 2-minute new mini-drama.",
    "Here's an Akira-Kurosawa Ikiru reference — analyze its dying-bureaucrat playground arc and create a 1-minute new cinematic short.",
    "I have a Park-Chan-wook Oldboy reference — please analyze its hammer-corridor single-take and produce a 30-second new mini-drama.",
    "Uploading a Bong-Joon-ho Memories-of-Murder reference — analyze its rural-Korean unsolved-case dread and create a 45-second new cinematic short.",
    # ── more British / Irish / Heritage cinema (50) ──
    "Here's an Alexander-Mackendrick Ladykillers reference — analyze its Kings-Cross-boarding-house heist and produce a 1-minute new cinematic short.",
    "I have a Robert-Hamer Kind-Hearts-and-Coronets reference — please analyze its serial-aristocrat eight-portrait and create a 30-second new mini-drama.",
    "I'm sending you a Charles-Crichton The-Lavender-Hill-Mob reference — please analyze its London-foundry gold-bar plan and produce a 45-second new cinematic piece.",
    "Uploading a Henry-Cornelius Passport-to-Pimlico reference — analyze its Pimlico-independence farce and create a 1-minute new mini-drama.",
    "Here's a Carol-Reed The-Third-Man reference — analyze its Vienna-sewer chase and produce a 30-second new cinematic short.",
    "I have a David-Lean Brief-Encounter reference — please analyze its railway-station tea-room ache and create a 45-second new mini-drama.",
    "Uploading a Powell-Pressburger Red-Shoes reference — analyze its ballet-within-film vortex and produce a 1-minute new cinematic short.",
    "Here's a Powell-Pressburger A-Matter-of-Life-and-Death reference — analyze its Technicolor-heaven escalator and create a 30-second new mini-drama.",
    "I'm sending you a Joseph-Losey The-Servant reference — please analyze its Knightsbridge-staircase power-flip and produce a 45-second new cinematic short.",
    "Uploading a Lindsay-Anderson If…. reference — analyze its public-school-revolt rooftop and create a 1-minute new mini-drama.",
    "Here's a Tony-Richardson Tom-Jones reference — analyze its Georgian-romp banquet and produce a 30-second new cinematic short.",
    "I have a Karel-Reisz Saturday-Night-and-Sunday-Morning reference — please analyze its Nottingham-factory weekend and create a 45-second new mini-drama.",
    "Uploading a John-Schlesinger Billy-Liar reference — analyze its Yorkshire-clerk fantasy and produce a 1-minute new cinematic short.",
    "Here's a Ken-Loach Kes reference — analyze its Barnsley-coal-town kestrel and create a 30-second new mini-drama.",
    "I'm sending you a Ken-Loach Riff-Raff reference — please analyze its London-building-site banter and produce a 45-second new cinematic short.",
    "Uploading a Mike-Leigh Naked reference — analyze its London-night insomnia-monologue and create a 1-minute new mini-drama.",
    "Here's a Mike-Leigh Secrets-and-Lies reference — analyze its long-lost-daughter cafe-meeting and produce a 30-second new cinematic short.",
    "I have a Stephen-Frears My-Beautiful-Laundrette reference — please analyze its Thatcher-era launderette opening and create a 45-second new mini-drama.",
    "Uploading a Derek-Jarman Caravaggio reference — analyze its anachronistic-painter studio and produce a 1-minute new cinematic short.",
    "Here's a Terence-Davies Distant-Voices-Still-Lives reference — analyze its Liverpool-1940s pub-songs and create a 30-second new mini-drama.",
    "I'm sending you a Bill-Forsyth Local-Hero reference — please analyze its Highland-village-windfall and produce a 45-second new cinematic short.",
    "Uploading a Lynne-Ramsay Ratcatcher reference — analyze its Glasgow-bin-strike summer and create a 1-minute new mini-drama.",
    "Here's a Lynne-Ramsay We-Need-to-Talk-About-Kevin reference — analyze its tomato-festival flashback and produce a 30-second new cinematic short.",
    "I have a Andrea-Arnold Fish-Tank reference — please analyze its Essex-estate kitchen-dance and create a 45-second new mini-drama.",
    "Uploading a Andrea-Arnold American-Honey reference — analyze its Midwest-mag-crew van and produce a 1-minute new cinematic short.",
    "Here's a Steve-McQueen Hunger reference — analyze its Maze-Prison hunger-strike monologue and create a 30-second new mini-drama.",
    "I'm sending you a Steve-McQueen Shame reference — please analyze its NYC-subway addiction-ride and produce a 45-second new cinematic short.",
    "Uploading a Steve-McQueen 12-Years-a-Slave reference — analyze its Louisiana-plantation hanging-tree and create a 1-minute new mini-drama.",
    "Here's a Sam-Mendes American-Beauty reference — analyze its suburban-rose-petal fantasy and produce a 30-second new cinematic short.",
    "I have a Sam-Mendes 1917 reference — please analyze its WW1-trench long-take and create a 45-second new mini-drama.",
    "Uploading a Christopher-Nolan Dunkirk reference — analyze its mole-air-sea timeline-weave and produce a 1-minute new cinematic short.",
    "Here's a Christopher-Nolan Following reference — analyze its London-monochrome stalker-debut and create a 30-second new mini-drama.",
    "I'm sending you a Edgar-Wright Hot-Fuzz reference — please analyze its Sandford-village shoot-out and produce a 45-second new cinematic short.",
    "Uploading a Edgar-Wright Last-Night-in-Soho reference — analyze its 60s-Soho dream-mirror and create a 1-minute new mini-drama.",
    "Here's a Yorgos-Lanthimos The-Favourite reference — analyze its Queen-Anne-court rabbit-room and produce a 30-second new cinematic short.",
    "I have a Yorgos-Lanthimos Killing-of-a-Sacred-Deer reference — please analyze its surgeon-family-curse ER and create a 45-second new mini-drama.",
    "Uploading a Joanna-Hogg Souvenir reference — analyze its 1980s-Knightsbridge film-school memoir and produce a 1-minute new cinematic short.",
    "Here's a Charlotte-Wells Aftersun reference — analyze its Turkish-resort camcorder-melancholy and create a 30-second new mini-drama.",
    "I'm sending you a Lone-Scherfig An-Education reference — please analyze its Twickenham-Oxford courtship and produce a 45-second new cinematic short.",
    "Uploading a Saul-Dibb Suite-Française reference — analyze its WW2-occupied-village piano-window and create a 1-minute new mini-drama.",
    "Here's a Joe-Wright Atonement reference — analyze its Dunkirk-beach-Steadicam long-take and produce a 30-second new cinematic short.",
    "I have a Joe-Wright Pride-and-Prejudice reference — please analyze its Pemberley-rain-confession and create a 45-second new mini-drama.",
    "Uploading a Jane-Campion Bright-Star reference — analyze its Hampstead-Heath Keats-letter and produce a 1-minute new cinematic short.",
    "Here's a Sarah-Gavron Suffragette reference — analyze its Bethnal-Green-laundry strike-march and create a 30-second new mini-drama.",
    "I'm sending you a Phyllida-Lloyd The-Iron-Lady reference — please analyze its Westminster-corridor speech and produce a 45-second new cinematic short.",
    "Uploading a Tom-Hooper The-King's-Speech reference — analyze its Logue-consultation stutter-room and create a 1-minute new mini-drama.",
    "Here's a Sally-Wainwright To-Walk-Invisible reference — analyze its Brontë-Haworth parsonage-window and produce a 30-second new cinematic short.",
    "I have a Stephen-Frears Philomena reference — please analyze its Roscrea-mother-and-baby-home gate and create a 45-second new mini-drama.",
    "Uploading a Mike-Newell Four-Weddings-and-a-Funeral reference — analyze its country-church confetti-toss and produce a 1-minute new cinematic short.",
    "Here's a Richard-Curtis Notting-Hill reference — analyze its Portobello-blue-door bookshop and create a 30-second new mini-drama.",
    # ── more French New Wave / nouvelle vague references (50) ──
    "Uploading a Jean-Luc-Godard Breathless reference — please analyze its Champs-Élysées jump-cut walking and produce a 1-minute new mini-drama.",
    "Here's a Jean-Luc-Godard Vivre-sa-Vie reference — analyze its 12-tableaux Paris-café and create a 45-second new cinematic short.",
    "I'm sending you a Jean-Luc-Godard Pierrot-le-Fou reference — please analyze its Côte-d'Azur dynamite-finale and produce a 30-second new mini-drama.",
    "Uploading a Jean-Luc-Godard Contempt reference — analyze its Capri-villa Brigitte-Bardot and create a 1-minute new cinematic short.",
    "Here's a Jean-Luc-Godard Alphaville reference — analyze its Paris-future Lemmy-Caution interrogation and produce a 30-second new mini-drama.",
    "I have a Jean-Luc-Godard Band-of-Outsiders reference — please analyze its Louvre-run sprint and create a 45-second new cinematic short.",
    "Uploading a Jean-Luc-Godard Weekend reference — analyze its highway-traffic-jam tracking-shot and produce a 1-minute new mini-drama.",
    "Here's a François-Truffaut 400-Blows reference — please analyze its Antoine-Doinel beach-final-shot and create a 45-second new cinematic short.",
    "I'm sending you a François-Truffaut Jules-et-Jim reference — analyze its Belle-Époque bicycle bridge and produce a 30-second new mini-drama.",
    "Uploading a François-Truffaut Shoot-the-Piano-Player reference — analyze its Charlie-Kohler bar-scene and create a 1-minute new cinematic short.",
    "Here's a François-Truffaut Stolen-Kisses reference — please analyze its Antoine-Doinel-shoe-store and produce a 30-second new mini-drama.",
    "I have a François-Truffaut Day-for-Night reference — please analyze its film-within-a-film set and create a 45-second new cinematic short.",
    "Uploading a François-Truffaut Wild-Child reference — analyze its Aveyron-forest feral-boy-discovery and produce a 1-minute new mini-drama.",
    "Here's an Alain-Resnais Hiroshima-Mon-Amour reference — please analyze its Hiroshima-hotel-room flashback and create a 30-second new cinematic short.",
    "I'm sending you an Alain-Resnais Last-Year-at-Marienbad reference — analyze its château-corridor tracking-shot and produce a 45-second new mini-drama.",
    "Uploading an Alain-Resnais Muriel reference — analyze its Boulogne-sur-Mer Algerian-war flashback and create a 1-minute new cinematic short.",
    "Here's an Alain-Resnais Night-and-Fog reference — please analyze its Auschwitz-color-archive intercut and produce a 30-second new mini-drama.",
    "I have an Agnès-Varda Cléo-from-5-to-7 reference — please analyze its Paris-real-time-clock-walk and create a 45-second new cinematic short.",
    "Uploading an Agnès-Varda Vagabond reference — analyze its Languedoc-tramp-girl-roadside and produce a 1-minute new mini-drama.",
    "Here's an Agnès-Varda Le-Bonheur reference — analyze its Provence-picnic adultery and create a 30-second new cinematic short.",
    "I'm sending you an Agnès-Varda Faces-Places reference — please analyze its rural-France photo-mural and produce a 45-second new mini-drama.",
    "Uploading a Claude-Chabrol Le-Beau-Serge reference — analyze its Sardent-village-return and create a 1-minute new cinematic short.",
    "Here's a Claude-Chabrol Les-Bonnes-Femmes reference — please analyze its Paris-shopgirls evening-walk and produce a 30-second new mini-drama.",
    "I have a Claude-Chabrol La-Cérémonie reference — please analyze its Brittany-bourgeois-house dinner and create a 45-second new cinematic short.",
    "Uploading a Jacques-Demy Umbrellas-of-Cherbourg reference — analyze its Cherbourg-station farewell-platform and produce a 1-minute new mini-drama.",
    "Here's a Jacques-Demy Young-Girls-of-Rochefort reference — analyze its Rochefort-square sailor-twin dance and create a 30-second new cinematic short.",
    "I'm sending you a Jacques-Demy Lola reference — please analyze its Nantes-cabaret white-feather and produce a 45-second new mini-drama.",
    "Uploading a Jacques-Rivette Celine-and-Julie-Go-Boating reference — analyze its haunted-house tea-party and create a 1-minute new cinematic short.",
    "Here's a Jacques-Rivette Out-1 reference — please analyze its Paris-theater-troupe pursuit and produce a 30-second new mini-drama.",
    "I have an Eric-Rohmer My-Night-at-Maud's reference — please analyze its Clermont-Ferrand discussion-night and create a 45-second new cinematic short.",
    "Uploading an Eric-Rohmer Claire's-Knee reference — analyze its Lake-Annecy summer-cottage and produce a 1-minute new mini-drama.",
    "Here's an Eric-Rohmer Pauline-at-the-Beach reference — analyze its Normandy-beach-house adolescent-summer and create a 30-second new cinematic short.",
    "I'm sending you an Eric-Rohmer Green-Ray reference — please analyze its Biarritz-sunset solo-vacation and produce a 45-second new mini-drama.",
    "Uploading a Louis-Malle Elevator-to-the-Gallows reference — analyze its Champs-Élysées-elevator-trapped corporate-murder and create a 1-minute new cinematic short.",
    "Here's a Louis-Malle Zazie-dans-le-Métro reference — please analyze its Paris-Métro tomboy-tour and produce a 30-second new mini-drama.",
    "I have a Louis-Malle Lacombe-Lucien reference — please analyze its Vichy-village-collaborator and create a 45-second new cinematic short.",
    "Uploading a Louis-Malle Au-Revoir-les-Enfants reference — analyze its Carmelite-school hidden-Jewish-boy and produce a 1-minute new mini-drama.",
    "Here's a Maurice-Pialat Loulou reference — analyze its Paris-suburbs working-class affair and create a 30-second new cinematic short.",
    "I'm sending you a Maurice-Pialat À-Nos-Amours reference — please analyze its Suzanne-15-year-old-summer and produce a 45-second new mini-drama.",
    "Uploading a Maurice-Pialat Police reference — analyze its Belleville-Maghrebi-drug-bust and create a 1-minute new cinematic short.",
    "Here's a Bertrand-Tavernier Round-Midnight reference — please analyze its Paris-jazz-club-1959 expat-saxophonist and produce a 30-second new mini-drama.",
    "I have an André-Téchiné Wild-Reeds reference — please analyze its 1962-Aquitaine schoolboys-summer and create a 45-second new cinematic short.",
    "Uploading a Catherine-Breillat Romance reference — analyze its Marie-existential-Paris-night and produce a 1-minute new mini-drama.",
    "Here's a Catherine-Breillat Fat-Girl reference — analyze its sister-roadside-trauma and create a 30-second new cinematic short.",
    "I'm sending you a Patrice-Chéreau Queen-Margot reference — please analyze its Saint-Bartholomew's-Day Paris-massacre and produce a 45-second new mini-drama.",
    "Uploading a Patrice-Chéreau Intimacy reference — analyze its London-flat-Wednesday-encounter and create a 1-minute new cinematic short.",
    "Here's a Léos-Carax Holy-Motors reference — please analyze its Mr-Oscar-limousine multi-role and produce a 30-second new mini-drama.",
    "I have a Léos-Carax Lovers-on-the-Bridge reference — please analyze its Pont-Neuf-fireworks dance and create a 45-second new cinematic short.",
    "Uploading a Léos-Carax Boy-Meets-Girl reference — analyze its Paris-night-Mireille-Alex and produce a 1-minute new mini-drama.",
    "Here's a Bertrand-Blier Going-Places reference — analyze its road-trip provincial-France escape and create a 30-second new cinematic short.",
    # ── more Italian Neorealism / Cinecittà-era references (50) ──
    "Uploading a Roberto-Rossellini Rome-Open-City reference — please analyze its Pina-on-the-stair sequence and produce a 1-minute new mini-drama.",
    "Here's a Roberto-Rossellini Paisà reference — analyze its Florence-snipers-Arno episode and create a 45-second new cinematic short.",
    "I'm sending you a Roberto-Rossellini Germany-Year-Zero reference — please analyze its Berlin-rubble-child sequence and produce a 30-second new mini-drama.",
    "Uploading a Roberto-Rossellini Stromboli reference — analyze its Aeolian-Island-fishing-village and create a 1-minute new cinematic short.",
    "Here's a Roberto-Rossellini Voyage-to-Italy reference — please analyze its Naples-Pompeii-couple and produce a 45-second new cinematic short.",
    "I have a Vittorio-De-Sica Bicycle-Thieves reference — please analyze its Roman-pawnshop bicycle-stolen and produce a 1-minute new mini-drama.",
    "Uploading a Vittorio-De-Sica Shoeshine reference — analyze its Roman-juvenile-prison and create a 45-second new cinematic short.",
    "Here's a Vittorio-De-Sica Umberto-D reference — please analyze its retired-civil-servant-Rome and produce a 30-second new mini-drama.",
    "I'm sending you a Vittorio-De-Sica Miracle-in-Milan reference — analyze its postwar-Milan shantytown-broom-flight and create a 45-second new cinematic short.",
    "Uploading a Vittorio-De-Sica Two-Women reference — analyze its Sophia-Loren-Ciociaria-evacuation and produce a 1-minute new cinematic short.",
    "Here's a Luchino-Visconti Ossessione reference — please analyze its Po-Valley-trattoria-affair and create a 30-second new mini-drama.",
    "I have a Luchino-Visconti Earth-Trembles reference — please analyze its Aci-Trezza-fishing-village and produce a 45-second new cinematic short.",
    "Uploading a Luchino-Visconti Senso reference — analyze its 1866-Venice-La-Fenice opera-box and create a 1-minute new cinematic short.",
    "Here's a Luchino-Visconti Rocco-and-His-Brothers reference — please analyze its Milan-boxing-gym and produce a 30-second new mini-drama.",
    "I'm sending you a Luchino-Visconti Leopard reference — analyze its Donnafugata-ballroom mazurka and create a 45-second new cinematic short.",
    "Uploading a Luchino-Visconti Death-in-Venice reference — analyze its Lido-Hotel-des-Bains and produce a 1-minute new cinematic short.",
    "Here's a Federico-Fellini La-Strada reference — please analyze its strongman-Zampanò roadside and create a 30-second new mini-drama.",
    "I have a Federico-Fellini Nights-of-Cabiria reference — please analyze its Rome-streetwalker pilgrimage and produce a 45-second new cinematic short.",
    "Uploading a Federico-Fellini La-Dolce-Vita reference — analyze its Trevi-Fountain Anita-Ekberg and create a 1-minute new cinematic short.",
    "Here's a Federico-Fellini 8-and-1/2 reference — please analyze its Guido-Anselmi-circus-finale and produce a 30-second new mini-drama.",
    "I'm sending you a Federico-Fellini Amarcord reference — analyze its Rimini-fascist-procession and create a 45-second new cinematic short.",
    "Uploading a Federico-Fellini Roma reference — analyze its Cinecittà-pope's-fashion-show and produce a 1-minute new cinematic short.",
    "Here's a Federico-Fellini Casanova reference — please analyze its Venetian-carnival-mechanical-doll and create a 30-second new mini-drama.",
    "I have a Michelangelo-Antonioni L'Avventura reference — please analyze its Lisca-Bianca-island-disappearance and produce a 45-second new cinematic short.",
    "Uploading a Michelangelo-Antonioni La-Notte reference — analyze its Milan-nighttime-walk-Pirelli and create a 1-minute new cinematic short.",
    "Here's a Michelangelo-Antonioni Eclipse reference — please analyze its EUR-Rome-stock-exchange and produce a 30-second new mini-drama.",
    "I'm sending you a Michelangelo-Antonioni Red-Desert reference — analyze its Ravenna-petrochemical-factory and create a 45-second new cinematic short.",
    "Uploading a Michelangelo-Antonioni Blow-Up reference — analyze its London-Maryon-Park photograph and produce a 1-minute new cinematic short.",
    "Here's a Michelangelo-Antonioni Passenger reference — please analyze its Saharan-hotel-room identity-swap and create a 30-second new mini-drama.",
    "I have a Pier-Paolo-Pasolini Accattone reference — please analyze its Roman-borgata-Tiber and produce a 45-second new cinematic short.",
    "Uploading a Pier-Paolo-Pasolini Mamma-Roma reference — analyze its Casalbertone-housing-block and create a 1-minute new cinematic short.",
    "Here's a Pier-Paolo-Pasolini Gospel-According-to-St-Matthew reference — please analyze its Calabria-Sermon-on-the-Mount and produce a 30-second new mini-drama.",
    "I'm sending you a Pier-Paolo-Pasolini Theorem reference — analyze its Milanese-bourgeois-house-visitor and create a 45-second new cinematic short.",
    "Uploading a Pier-Paolo-Pasolini Salò reference — analyze its Republic-of-Salò-villa and produce a 1-minute new cinematic short.",
    "Here's a Pier-Paolo-Pasolini Decameron reference — please analyze its Naples-Boccaccio-tales and create a 30-second new mini-drama.",
    "I have a Bernardo-Bertolucci Conformist reference — please analyze its Paris-fascist-betrayal and produce a 45-second new cinematic short.",
    "Uploading a Bernardo-Bertolucci Last-Tango-in-Paris reference — analyze its Passy-empty-apartment and create a 1-minute new cinematic short.",
    "Here's a Bernardo-Bertolucci 1900 reference — please analyze its Emilia-Romagna-peasant-padrone and produce a 30-second new mini-drama.",
    "I'm sending you a Bernardo-Bertolucci Last-Emperor reference — analyze its Forbidden-City-Pu-Yi-childhood and create a 45-second new cinematic short.",
    "Uploading a Bernardo-Bertolucci Sheltering-Sky reference — analyze its Saharan-Tangier-couple and produce a 1-minute new cinematic short.",
    "Here's a Sergio-Leone Once-Upon-a-Time-in-the-West reference — please analyze its Flagstone-train-station harmonica and create a 30-second new mini-drama.",
    "I have a Sergio-Leone Good-the-Bad-and-the-Ugly reference — please analyze its Sad-Hill-Cemetery showdown and produce a 45-second new cinematic short.",
    "Uploading a Sergio-Leone Once-Upon-a-Time-in-America reference — analyze its Manhattan-Williamsburg flashback and create a 1-minute new cinematic short.",
    "Here's a Vittorio-and-Paolo-Taviani Padre-Padrone reference — please analyze its Sardinian-shepherd-rebellion and produce a 30-second new mini-drama.",
    "I'm sending you a Vittorio-and-Paolo-Taviani Caesar-Must-Die reference — analyze its Rebibbia-prison-Shakespeare and create a 45-second new cinematic short.",
    "Uploading an Ermanno-Olmi Tree-of-Wooden-Clogs reference — analyze its Bergamo-1898-tenant-farmer and produce a 1-minute new cinematic short.",
    "Here's a Marco-Bellocchio Fists-in-the-Pocket reference — please analyze its Bobbio-villa-epileptic-son and create a 30-second new mini-drama.",
    "I have a Marco-Bellocchio Vincere reference — please analyze its Milan-Mussolini-secret-wife and produce a 45-second new cinematic short.",
    "Uploading a Paolo-Sorrentino Great-Beauty reference — analyze its Rome-rooftop-party-Jep-Gambardella and create a 1-minute new cinematic short.",
    "Here's a Paolo-Sorrentino Hand-of-God reference — please analyze its Naples-Maradona-arrival and produce a 30-second new mini-drama.",
    # ── more Russian / Soviet cinema references (50) ──
    "Uploading a Sergei-Eisenstein Battleship-Potemkin reference — please analyze its Odessa-Steps-massacre and produce a 1-minute new mini-drama.",
    "Here's a Sergei-Eisenstein October reference — analyze its Winter-Palace-storming sequence and create a 45-second new cinematic short.",
    "I'm sending you a Sergei-Eisenstein Ivan-the-Terrible reference — please analyze its Anastasia-poisoning Kremlin-throne and produce a 30-second new mini-drama.",
    "Uploading a Sergei-Eisenstein Alexander-Nevsky reference — analyze its Lake-Peipus-ice-battle and create a 45-second new short.",
    "Here's a Dziga-Vertov Man-with-a-Movie-Camera reference — please analyze its Odessa-Kyiv-cinema-eye and produce a 1-minute new cinematic short.",
    "I have a Vsevolod-Pudovkin Mother reference — please analyze its 1905-revolution Tatar mother-son and produce a 30-second new mini-drama.",
    "Uploading a Mikhail-Kalatozov Cranes-Are-Flying reference — analyze its WWII-Moscow-air-raid and create a 45-second new cinematic short.",
    "Here's a Mikhail-Kalatozov I-Am-Cuba reference — please analyze its Havana-Capitolio-tracking-shot and produce a 1-minute new cinematic short.",
    "I'm sending you a Andrei-Tarkovsky Ivan's-Childhood reference — analyze its WWII-marsh-scout-boy and create a 30-second new mini-drama.",
    "Uploading a Andrei-Tarkovsky Andrei-Rublev reference — analyze its medieval-Russian-bell-foundry and produce a 45-second new short.",
    "Here's a Andrei-Tarkovsky Solaris reference — please analyze its alien-ocean-station and create a 1-minute new cinematic short.",
    "I have a Andrei-Tarkovsky Mirror reference — please analyze its rural-Russia-mother-flashback and produce a 30-second new mini-drama.",
    "Uploading a Andrei-Tarkovsky Stalker reference — analyze its post-industrial-Zone-room and create a 45-second new short.",
    "Here's a Andrei-Tarkovsky Nostalghia reference — please analyze its Tuscan-thermal-bath candle-walk and produce a 1-minute new cinematic short.",
    "I'm sending you a Andrei-Tarkovsky Sacrifice reference — analyze its Gotland-island-house-burning and create a 30-second new mini-drama.",
    "Uploading a Larisa-Shepitko Ascent reference — analyze its WWII-Belarus-snow-execution and produce a 45-second new cinematic short.",
    "Here's a Sergei-Parajanov Color-of-Pomegranates reference — please analyze its Sayat-Nova-poet-tableaux and create a 1-minute new cinematic short.",
    "I have a Sergei-Parajanov Shadows-of-Forgotten-Ancestors reference — please analyze its Carpathian-Hutsul-village and produce a 30-second new mini-drama.",
    "Uploading a Andrei-Konchalovsky Asya's-Happiness reference — analyze its Kuban-Cossack-village-romance and create a 45-second new cinematic short.",
    "Here's a Andrei-Konchalovsky Siberiade reference — please analyze its Siberian-village-oilrig generations and produce a 1-minute new cinematic short.",
    "I'm sending you a Nikita-Mikhalkov Burnt-by-the-Sun reference — analyze its 1936-Stalin-purge-dacha and create a 30-second new mini-drama.",
    "Uploading a Nikita-Mikhalkov Slave-of-Love reference — analyze its Russian-Civil-War-film-troupe and produce a 45-second new short.",
    "Here's a Nikita-Mikhalkov Unfinished-Piece-for-Mechanical-Piano reference — please analyze its Chekhovian-country-estate and create a 1-minute new cinematic short.",
    "I have a Aleksei-German Khrustalyov-My-Car reference — please analyze its 1953-Stalin-death-Moscow and produce a 30-second new mini-drama.",
    "Uploading a Aleksei-German My-Friend-Ivan-Lapshin reference — analyze its 1930s-Stalinist-province and create a 45-second new short.",
    "Here's a Aleksandr-Sokurov Russian-Ark reference — please analyze its Hermitage-single-take-300-years and produce a 1-minute new cinematic short.",
    "I'm sending you a Aleksandr-Sokurov Mother-and-Son reference — analyze its hilltop-cottage-mother-deathbed and create a 30-second new mini-drama.",
    "Uploading a Aleksandr-Sokurov Faust reference — analyze its Faust-Mephistopheles-mountain-path and produce a 45-second new short.",
    "Here's a Aleksandr-Sokurov Francofonia reference — please analyze its Louvre-Nazi-occupation and create a 1-minute new cinematic short.",
    "I have a Aleksandr-Sokurov Father-and-Son reference — please analyze its Lisbon-rooftop-tableaux and produce a 30-second new mini-drama.",
    "Uploading a Andrey-Zvyagintsev Return reference — analyze its Russian-island-father-sons and create a 45-second new cinematic short.",
    "Here's a Andrey-Zvyagintsev Elena reference — please analyze its Moscow-mid-rise-husband-poisoning and produce a 1-minute new cinematic short.",
    "I'm sending you a Andrey-Zvyagintsev Leviathan reference — analyze its Murmansk-coast-mayor-corruption and create a 30-second new mini-drama.",
    "Uploading a Andrey-Zvyagintsev Loveless reference — analyze its Moscow-divorcing-couple-missing-son and produce a 45-second new short.",
    "Here's a Pavel-Lungin Taxi-Blues reference — please analyze its 1990-Moscow-cabbie-saxophonist and create a 1-minute new cinematic short.",
    "I have a Pavel-Lungin Tsar reference — please analyze its 16th-c-Ivan-the-Terrible-Metropolitan and produce a 30-second new mini-drama.",
    "Uploading a Aleksei-Balabanov Brother reference — analyze its 1990s-St-Petersburg-mafia and create a 45-second new cinematic short.",
    "Here's a Aleksei-Balabanov Cargo-200 reference — please analyze its 1984-Soviet-rural-detective and produce a 1-minute new cinematic short.",
    "I'm sending you a Aleksei-Balabanov Of-Freaks-and-Men reference — analyze its 1900s-St-Petersburg-erotic-photographer and create a 30-second new mini-drama.",
    "Uploading a Kantemir-Balagov Closeness reference — analyze its 1998-Nalchik-Jewish-family and produce a 45-second new short.",
    "Here's a Kantemir-Balagov Beanpole reference — please analyze its 1945-Leningrad-hospital-survivors and create a 1-minute new cinematic short.",
    "I have a Kira-Muratova Brief-Encounters reference — please analyze its 1960s-Odessa-water-shortage and produce a 30-second new mini-drama.",
    "Uploading a Kira-Muratova Asthenic-Syndrome reference — analyze its perestroika-Moscow-school and create a 45-second new short.",
    "Here's a Boris-Khlebnikov Arrhythmia reference — please analyze its provincial-Russia-paramedic-couple and produce a 1-minute new cinematic short.",
    "I'm sending you a Yuri-Bykov Major reference — analyze its Moscow-region-officer-cover-up and create a 30-second new mini-drama.",
    "Uploading a Aleksandr-Khant How-Viktor-the-Garlic-Took-Alexey-the-Stud-to-the-Nursing-Home reference — analyze its Russian-far-east-road-trip and produce a 45-second new short.",
    "Here's a Anna-Melikyan Star reference — please analyze its Moscow-millennial-fairy-tale and create a 1-minute new cinematic short.",
    "I have a Aleksei-Fedorchenko Silent-Souls reference — please analyze its Mari-El-funeral-rite-river and produce a 30-second new mini-drama.",
    "Uploading a Aleksei-Fedorchenko Celestial-Wives-of-the-Meadow-Mari reference — analyze its Mari-folk-tales-23-women and create a 45-second new short.",
    "Here's a Vasili-Shukshin Kalina-Krasnaya reference — please analyze its Soviet-prison-released-thief and produce a 1-minute new cinematic short.",
    # ── more Italian Neorealism (50) ──
    "I have a De-Sica-Bicycle-Thieves reference — please analyze its post-war-Rome-stolen-bicycle and produce a 30-second new mini-drama.",
    "Uploading a De-Sica-Umberto-D reference — analyze its Rome-pensioner-and-dog and create a 45-second new short.",
    "Here's a De-Sica-Shoeshine reference — please analyze its post-war-Rome-orphan-boys-prison and produce a 1-minute new cinematic short.",
    "I'm sending you a De-Sica-Miracle-in-Milan reference — analyze its Milan-shantytown-fairy-tale and create a 30-second new mini-drama.",
    "Uploading a De-Sica-Two-Women reference — analyze its Ciociaria-mother-daughter-war and produce a 45-second new short.",
    "Here's a De-Sica-Marriage-Italian-Style reference — please analyze its Naples-prostitute-and-merchant and create a 1-minute new cinematic short.",
    "I have a Rossellini-Rome-Open-City reference — please analyze its Nazi-occupied-Rome-resistance and produce a 30-second new mini-drama.",
    "Uploading a Rossellini-Paisan reference — analyze its 6-episode-WWII-Italian-liberation and create a 45-second new short.",
    "Here's a Rossellini-Germany-Year-Zero reference — please analyze its post-war-Berlin-ruins-boy and produce a 1-minute new cinematic short.",
    "I'm sending you a Rossellini-Stromboli reference — analyze its Stromboli-volcanic-island-marriage and create a 30-second new mini-drama.",
    "Uploading a Rossellini-Voyage-to-Italy reference — analyze its Naples-Pompeii-couple-crisis and produce a 45-second new short.",
    "Here's a Rossellini-Europe-51 reference — please analyze its Rome-bourgeois-conversion and create a 1-minute new cinematic short.",
    "I have a Visconti-Ossessione reference — please analyze its Po-Valley-roadside-trattoria-noir and produce a 30-second new mini-drama.",
    "Uploading a Visconti-La-Terra-Trema reference — analyze its Aci-Trezza-Sicily-fishermen and create a 45-second new short.",
    "Here's a Visconti-Rocco-and-His-Brothers reference — please analyze its Milan-Lucanian-brothers-boxing and produce a 1-minute new cinematic short.",
    "I'm sending you a Visconti-The-Leopard reference — analyze its 1860s-Sicily-Risorgimento-aristocracy and create a 30-second new mini-drama.",
    "Uploading a Visconti-Senso reference — analyze its 1866-Venetian-third-Italian-war and produce a 45-second new short.",
    "Here's a Visconti-Bellissima reference — please analyze its Rome-Cinecittà-stage-mother and create a 1-minute new cinematic short.",
    "I have a Fellini-La-Strada reference — please analyze its Italy-itinerant-strongman-Gelsomina and produce a 30-second new mini-drama.",
    "Uploading a Fellini-Nights-of-Cabiria reference — analyze its Rome-streetwalker-Cabiria and create a 45-second new short.",
    "Here's a Fellini-I-Vitelloni reference — please analyze its Rimini-1950s-young-loafers and produce a 1-minute new cinematic short.",
    "I'm sending you a Fellini-La-Dolce-Vita reference — analyze its Rome-Via-Veneto-paparazzo-week and create a 30-second new mini-drama.",
    "Uploading a Fellini-8-1/2 reference — analyze its Chianciano-Terme-director-block and produce a 45-second new short.",
    "Here's a Fellini-Amarcord reference — please analyze its Rimini-fascist-coastal-childhood and create a 1-minute new cinematic short.",
    "I have a Fellini-The-White-Sheik reference — please analyze its Rome-honeymoon-Fotoromanzi-set and produce a 30-second new mini-drama.",
    "Uploading a Fellini-Variety-Lights reference — analyze its 1950s-Italian-traveling-vaudeville and create a 45-second new short.",
    "Here's a Antonioni-L'Avventura reference — please analyze its Aeolian-Islands-disappeared-friend and produce a 1-minute new cinematic short.",
    "I'm sending you a Antonioni-La-Notte reference — analyze its Milan-marriage-walk-night and create a 30-second new mini-drama.",
    "Uploading a Antonioni-L'Eclisse reference — analyze its Rome-EUR-stock-exchange-couple and produce a 45-second new short.",
    "Here's a Antonioni-Red-Desert reference — please analyze its Ravenna-petrochemical-couple-crisis and create a 1-minute new cinematic short.",
    "I have a Antonioni-Il-Grido reference — please analyze its Po-Valley-mill-worker-wandering and produce a 30-second new mini-drama.",
    "Uploading a Antonioni-Story-of-a-Love-Affair reference — analyze its Milan-bourgeois-affair-noir and create a 45-second new short.",
    "Here's a Pasolini-Accattone reference — please analyze its Rome-Pigneto-pimp and produce a 1-minute new cinematic short.",
    "I'm sending you a Pasolini-Mamma-Roma reference — analyze its Rome-INA-Casa-tenement-mother-son and create a 30-second new mini-drama.",
    "Uploading a Pasolini-The-Gospel-According-to-St-Matthew reference — analyze its Matera-Sassi-Christ and produce a 45-second new short.",
    "Here's a Pasolini-Hawks-and-Sparrows reference — please analyze its Roman-suburbs-father-son-crow and create a 1-minute new cinematic short.",
    "I have a Pasolini-Theorem reference — please analyze its Milan-bourgeois-family-stranger-visit and produce a 30-second new mini-drama.",
    "Uploading a De-Santis-Bitter-Rice reference — analyze its Po-Valley-rice-paddy-women and create a 45-second new short.",
    "Here's a De-Santis-Tragic-Hunt reference — please analyze its Po-Valley-1946-bandit-postwar and produce a 1-minute new cinematic short.",
    "I'm sending you a Lattuada-Without-Pity reference — analyze its post-war-Tombolo-Livorno-camp-romance and create a 30-second new mini-drama.",
    "Uploading a Castellani-Two-Cents-Worth-of-Hope reference — analyze its Boscotrecase-Vesuvius-village-couple and produce a 45-second new short.",
    "Here's a Germi-In-the-Name-of-the-Law reference — please analyze its 1949-Sicily-judge-Mafia and create a 1-minute new cinematic short.",
    "I have a Germi-Path-of-Hope reference — please analyze its Sicily-Sicilian-miners-emigration and produce a 30-second new mini-drama.",
    "Uploading a Germi-Divorce-Italian-Style reference — analyze its Sicily-baron-divorce-scheme and create a 45-second new short.",
    "Here's a Olmi-Il-Posto reference — please analyze its Milan-Edison-clerk-first-job and produce a 1-minute new cinematic short.",
    "I'm sending you a Olmi-Tree-of-Wooden-Clogs reference — analyze its 1898-Bergamo-peasant-family and create a 30-second new mini-drama.",
    "Uploading a Olmi-The-Fiances reference — analyze its Sicily-Milan-petrochemical-engineer and produce a 45-second new short.",
    "Here's a Bertolucci-Before-the-Revolution reference — please analyze its Parma-bourgeois-aunt-affair and create a 1-minute new cinematic short.",
    "I have a Bertolucci-The-Spider's-Stratagem reference — please analyze its Sabbioneta-anti-fascist-son-investigation and produce a 30-second new mini-drama.",
    "Uploading a Bertolucci-1900 reference — analyze its Emilia-Romagna-1900s-1945-twin-births-class-saga and create a 45-second new short.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
