"""x15 vid_analysis_music_subtitle SFT.
Chain: IntakeVideo → VideoAnalysis → Transcription → Music → AudioMix → Compositor.
Trigger: video upload + analyze + monolingual subtitle + new BGM.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 2-minute travel-vlog clip — please analyze it, add English subtitles, and swap in an indie-rock BGM.",
    "Here's a 90-second wedding-reception clip — analyze it, overlay English captions, and add romantic-piano BGM.",
    "I have a 3-minute documentary segment — please analyze it, add English subtitles, and overlay cinematic-strings BGM.",
    "Uploading a 1-minute conference panel — analyze it, overlay English captions, and add corporate-uplift BGM.",
    "Here's a 90-second cooking-show segment — analyze it, add English subtitles, and overlay smooth-jazz BGM.",
    "I'm sending you a 2-minute museum-tour walkthrough — analyze it, add English subtitles, and overlay classical-strings BGM.",
    "Uploading a 4-minute author-interview — please analyze it, add English captions, and add quiet-piano BGM.",
    "Here's a 90-second TED-style talk — analyze it, overlay English subtitles, and add hopeful-orchestral BGM.",
    "I have a 2-minute fitness-instructor demo — please analyze it, add English subtitles, and overlay upbeat-electronic BGM.",
    "Uploading a 3-minute yoga-flow demo — analyze it, add English captions, and add meditative-flute BGM.",
    "Here's a 1-minute fashion-show clip — analyze it, overlay English subtitles, and add electronic-house BGM.",
    "I'm sending you a 90-second sports-interview clip — analyze it, add English captions, and overlay stadium-rock BGM.",
    "Uploading a 4-minute political-speech excerpt — please analyze it, add English subtitles, and overlay solemn-strings BGM.",
    "Here's a 2-minute commencement-speech excerpt — analyze it, add English captions, and add hopeful-strings BGM.",
    "I have a 3-minute live-comedy clip — please analyze it, add English subtitles, and overlay light-jazz BGM.",
    "Uploading a 90-second magic-trick reveal — analyze it, add English captions, and add mysterious-strings BGM.",
    "Here's a 2-minute music-festival clip — please analyze it, add English subtitles, and overlay synthwave BGM.",
    "I'm sending you a 4-minute baking-show segment — analyze it, add English captions, and add smooth-jazz BGM.",
    "Uploading a 1-minute travel-vlog city-tour — please analyze it, overlay English subtitles, and add indie-folk BGM.",
    "Here's a 3-minute parenting-advice clip — analyze it, add English captions, and overlay tender-piano BGM.",
    "I have a 90-second pet-care tutorial — analyze it, add English subtitles, and overlay playful-pizzicato BGM.",
    "Uploading a 2-minute home-improvement tip — please analyze it, add English captions, and add warm-folk BGM.",
    "Here's a 4-minute coding-tutorial — analyze it, add English subtitles, and overlay chill-electronic BGM.",
    "I'm sending you a 90-second film-photography tutorial — analyze it, add English captions, and add nostalgic-piano BGM.",
    "Uploading a 1-minute meditation guide — please analyze it, add English subtitles, and overlay ambient-pad BGM.",
    "Here's a 2-minute classroom recording — analyze it, add English captions, and add gentle-strings BGM.",
    "I have a 3-minute museum-curator talk — please analyze it, add English subtitles, and overlay classical-piano BGM.",
    "Uploading a 90-second poetry reading — analyze it, overlay English captions, and add quiet-acoustic-guitar BGM.",
    "Here's a 4-minute startup-pitch — please analyze it, add English subtitles, and add corporate-uplift BGM.",
    "I'm sending you a 2-minute documentary segment — analyze it, add English captions, and overlay cinematic-orchestral BGM.",
    "Uploading a 1-minute book-trailer — please analyze it, overlay English subtitles, and add tense-orchestral BGM.",
    "Here's a 3-minute language-tutor demo — analyze it, add English subtitles, and overlay light-pizzicato BGM.",
    "I have a 90-second dance-instruction clip — analyze it, add English captions, and add upbeat-pop BGM.",
    "Uploading a 2-minute gardening-tutorial — please analyze it, add English subtitles, and overlay pastoral-strings BGM.",
    "Here's a 4-minute woodworking demo — analyze it, add English captions, and add country-folk BGM.",
    # ── more upload + analyze + subtitle + BGM requests (50) ──────────────
    "Uploading a 90-second real-estate walkthrough — please analyze it, add English subtitles, and overlay ambient-house BGM.",
    "Here's a 2-minute car-review video — analyze it, add English captions, and add hard-rock BGM.",
    "I have a 3-minute tech-product unboxing — please analyze it, add English subtitles, and overlay electronic-pulse BGM.",
    "Uploading a 4-minute drone-footage clip — analyze it, add English captions, and add cinematic-strings BGM.",
    "Here's a 90-second underwater-diving clip — analyze it, add English subtitles, and overlay ambient-pad BGM.",
    "I'm sending you a 2-minute snow-day morning ritual — please analyze it, add English captions, and add hygge-piano BGM.",
    "Uploading a 3-minute street-food tour — please analyze it, add English subtitles, and overlay world-fusion BGM.",
    "Here's a 4-minute coffee-shop atmosphere video — analyze it, add English captions, and add bossa-nova BGM.",
    "I have a 90-second craft-beer brewing tutorial — please analyze it, add English subtitles, and overlay indie-folk BGM.",
    "Uploading a 2-minute wine-tasting walkthrough — analyze it, add English captions, and add French-jazz BGM.",
    "Here's a 3-minute ice-cream-shop tour — please analyze it, add English subtitles, and overlay playful-pop BGM.",
    "I'm sending you a 4-minute tea-ceremony lesson — analyze it, add English captions, and add shakuhachi BGM.",
    "Uploading a 90-second boba-tea tutorial — please analyze it, add English subtitles, and overlay city-pop BGM.",
    "Here's a 2-minute sushi-rolling tutorial — analyze it, add English captions, and add Japanese-koto BGM.",
    "I have a 3-minute pasta-making tutorial — please analyze it, add English subtitles, and overlay Italian-mandolin BGM.",
    "Uploading a 4-minute sourdough tutorial — analyze it, add English captions, and add cozy-folk BGM.",
    "Here's a 90-second pottery-throwing demo — please analyze it, add English subtitles, and overlay delicate-piano BGM.",
    "I'm sending you a 2-minute weaving demo — analyze it, add English captions, and add Andean-flute BGM.",
    "Uploading a 3-minute embroidery demo — please analyze it, add English subtitles, and overlay pastoral-strings BGM.",
    "Here's a 4-minute quilting demo — analyze it, add English captions, and add Americana-folk BGM.",
    "I have a 90-second blacksmithing demo — please analyze it, add English subtitles, and overlay industrial-rock BGM.",
    "Uploading a 2-minute leatherworking demo — analyze it, add English captions, and add country-folk BGM.",
    "Here's a 3-minute bookbinding demo — please analyze it, add English subtitles, and overlay Renaissance-lute BGM.",
    "I'm sending you a 4-minute calligraphy demo — analyze it, add English captions, and add meditative-flute BGM.",
    "Uploading a 90-second origami tutorial — please analyze it, add English subtitles, and overlay delicate-piano BGM.",
    "Here's a 2-minute flower-arranging demo — analyze it, add English captions, and add pastoral-strings BGM.",
    "I have a 3-minute car-mechanic walkthrough — please analyze it, add English subtitles, and overlay hard-rock BGM.",
    "Uploading a 4-minute bike-mechanic tutorial — analyze it, add English captions, and add electronic-rock BGM.",
    "Here's a 90-second plumbing tutorial — please analyze it, add English subtitles, and overlay industrial-rock BGM.",
    "I'm sending you a 2-minute electrical-wiring tutorial — analyze it, add English captions, and add electronic-pulse BGM.",
    "Uploading a 3-minute house-painting tutorial — please analyze it, add English subtitles, and overlay cozy-folk BGM.",
    "Here's a 4-minute tile-installation tutorial — analyze it, add English captions, and add upbeat-pop BGM.",
    "I have a 90-second drywall-installation tutorial — please analyze it, add English subtitles, and overlay country-rock BGM.",
    "Uploading a 2-minute roofing tutorial — analyze it, add English captions, and add hard-rock BGM.",
    "Here's a 3-minute solar-panel install demo — please analyze it, add English subtitles, and overlay solar-electronic BGM.",
    "I'm sending you a 4-minute EV-charger install tutorial — analyze it, add English captions, and add electronic-pulse BGM.",
    "Uploading a 90-second smart-home setup tutorial — please analyze it, add English subtitles, and overlay ambient-electronic BGM.",
    "Here's a 2-minute AI-art tutorial — analyze it, add English captions, and add electronic-house BGM.",
    "I have a 3-minute data-visualization tutorial — please analyze it, add English subtitles, and overlay ambient-electronic BGM.",
    "Uploading a 4-minute spreadsheet-formula tutorial — analyze it, add English captions, and add playful-piano BGM.",
    "Here's a 90-second accounting tutorial — please analyze it, add English subtitles, and overlay corporate-uplift BGM.",
    "I'm sending you a 2-minute legal-research tutorial — analyze it, add English captions, and add solemn-strings BGM.",
    "Uploading a 3-minute medical-consultation segment — please analyze it, add English subtitles, and overlay tender-piano BGM.",
    "Here's a 4-minute dental-hygiene tutorial — analyze it, add English captions, and add playful-pizzicato BGM.",
    "I have a 90-second veterinarian visit clip — please analyze it, add English subtitles, and overlay tender-piano BGM.",
    "Uploading a 2-minute equine-care tutorial — analyze it, add English captions, and add pastoral-strings BGM.",
    "Here's a 3-minute dog-training demo — please analyze it, add English subtitles, and overlay playful-pizzicato BGM.",
    "I'm sending you a 4-minute cat-grooming tutorial — analyze it, add English captions, and add delicate-piano BGM.",
    "Uploading a 90-second bird-grooming tutorial — please analyze it, add English subtitles, and overlay pastoral-strings BGM.",
    "Here's a 2-minute aquarium-care tutorial — analyze it, add English captions, and add ambient-electronic BGM.",
    # ── more upload + analyze + subtitle + BGM requests (50) ──────────────
    "Uploading a 90-second brand-launch event clip — please analyze it, add English subtitles, and overlay cinematic-strings BGM.",
    "Here's a 2-minute earnings-call recap — analyze it, add English captions, and add corporate-uplift BGM.",
    "I have a 3-minute quarterly-results presentation — please analyze it, add English subtitles, and overlay corporate-uplift BGM.",
    "Uploading a 4-minute annual-report video — analyze it, add English captions, and add cinematic-strings BGM.",
    "Here's a 90-second shareholder-meeting clip — please analyze it, add English subtitles, and overlay solemn-strings BGM.",
    "I'm sending you a 2-minute M&A-announcement video — analyze it, add English captions, and add cinematic-orchestral BGM.",
    "Uploading a 3-minute board-meeting recap — please analyze it, add English subtitles, and overlay solemn-strings BGM.",
    "Here's a 4-minute CEO-address video — analyze it, add English captions, and add corporate-uplift BGM.",
    "I have a 90-second CFO-investor-update video — please analyze it, add English subtitles, and overlay corporate-uplift BGM.",
    "Uploading a 2-minute CTO-keynote video — analyze it, add English captions, and add electronic-pulse BGM.",
    "Here's a 3-minute tech-product-tour — please analyze it, add English subtitles, and overlay electronic-pulse BGM.",
    "I'm sending you a 4-minute SaaS-feature walkthrough — analyze it, add English captions, and add electronic-house BGM.",
    "Uploading a 90-second mobile-app demo — please analyze it, add English subtitles, and overlay upbeat-pop BGM.",
    "Here's a 2-minute game-launch trailer — analyze it, add English captions, and add adventurous-orchestral BGM.",
    "I have a 3-minute e-commerce shop tour — please analyze it, add English subtitles, and overlay upbeat-pop BGM.",
    "Uploading a 4-minute dropshipping tutorial — analyze it, add English captions, and add electronic-house BGM.",
    "Here's a 90-second influencer-marketing tutorial — please analyze it, add English subtitles, and overlay upbeat-pop BGM.",
    "I'm sending you a 2-minute brand-collaboration tutorial — analyze it, add English captions, and add cinematic-strings BGM.",
    "Uploading a 3-minute content-strategy tutorial — please analyze it, add English subtitles, and overlay electronic-pulse BGM.",
    "Here's a 4-minute SEO-update walkthrough — analyze it, add English captions, and add electronic-pulse BGM.",
    "I have a 90-second PPC-campaign tutorial — please analyze it, add English subtitles, and overlay electronic-pulse BGM.",
    "Uploading a 2-minute email-marketing tutorial — analyze it, add English captions, and add electronic-pulse BGM.",
    "Here's a 3-minute CRM-walkthrough — please analyze it, add English subtitles, and overlay corporate-uplift BGM.",
    "I'm sending you a 4-minute lead-generation tutorial — analyze it, add English captions, and add electronic-pulse BGM.",
    "Uploading a 90-second sales-pitch tutorial — please analyze it, add English subtitles, and overlay cinematic-strings BGM.",
    "Here's a 2-minute negotiation-tactics tutorial — analyze it, add English captions, and add tense-strings BGM.",
    "I have a 3-minute public-speaking tutorial — please analyze it, add English subtitles, and overlay hopeful-orchestral BGM.",
    "Uploading a 4-minute presentation-skills tutorial — analyze it, add English captions, and add cinematic-strings BGM.",
    "Here's a 90-second resume-writing tutorial — please analyze it, add English subtitles, and overlay hopeful-orchestral BGM.",
    "I'm sending you a 2-minute cover-letter tutorial — analyze it, add English captions, and add hopeful-orchestral BGM.",
    "Uploading a 3-minute interview-prep tutorial — please analyze it, add English subtitles, and overlay tense-strings BGM.",
    "Here's a 4-minute job-hunting strategy tutorial — analyze it, add English captions, and add cinematic-strings BGM.",
    "I have a 90-second salary-negotiation tutorial — please analyze it, add English subtitles, and overlay tense-strings BGM.",
    "Uploading a 2-minute workplace-conflict tutorial — analyze it, add English captions, and add tense-strings BGM.",
    "Here's a 3-minute burnout-recovery tutorial — please analyze it, add English subtitles, and overlay tender-piano BGM.",
    "I'm sending you a 4-minute work-life-balance tutorial — analyze it, add English captions, and add calm-piano BGM.",
    "Uploading a 90-second mindfulness-at-work tutorial — please analyze it, add English subtitles, and overlay ambient-pad BGM.",
    "Here's a 2-minute desk-stretch tutorial — analyze it, add English captions, and add calm-piano BGM.",
    "I have a 3-minute computer-vision tutorial — please analyze it, add English subtitles, and overlay electronic-pulse BGM.",
    "Uploading a 4-minute NLP tutorial — analyze it, add English captions, and add electronic-pulse BGM.",
    "Here's a 90-second ML-Ops tutorial — please analyze it, add English subtitles, and overlay electronic-pulse BGM.",
    "I'm sending you a 2-minute PyTorch tutorial — analyze it, add English captions, and add electronic-pulse BGM.",
    "Uploading a 3-minute TensorFlow tutorial — please analyze it, add English subtitles, and overlay electronic-pulse BGM.",
    "Here's a 4-minute Hugging-Face tutorial — analyze it, add English captions, and add electronic-pulse BGM.",
    "I have a 90-second ChatGPT-prompting tutorial — please analyze it, add English subtitles, and overlay electronic-house BGM.",
    "Uploading a 2-minute Stable-Diffusion tutorial — analyze it, add English captions, and add electronic-house BGM.",
    "Here's a 3-minute Midjourney tutorial — please analyze it, add English subtitles, and overlay electronic-house BGM.",
    "I'm sending you a 4-minute AI-music-generation tutorial — analyze it, add English captions, and add electronic-house BGM.",
    "Uploading a 90-second AI-voice-cloning tutorial — please analyze it, add English subtitles, and overlay ambient-electronic BGM.",
    "Here's a 2-minute AI-deepfake-detection tutorial — analyze it, add English captions, and add tense-electronic BGM.",
    # ── more upload + analyze + subtitle + BGM requests (50) ──────────────
    "Uploading a 90-second dance-flash-mob clip — please analyze it, add English subtitles, and overlay upbeat-pop BGM.",
    "Here's a 2-minute street-busker clip — analyze it, add English captions, and add French-jazz BGM.",
    "I have a 3-minute open-mic comedy clip — please analyze it, add English subtitles, and overlay jazz-piano BGM.",
    "Uploading a 4-minute drum-circle-park clip — analyze it, add English captions, and add tribal-percussion BGM.",
    "Here's a 90-second flash-fiction reading — please analyze it, add English subtitles, and overlay delicate-piano BGM.",
    "I'm sending you a 2-minute poetry-slam recording — analyze it, add English captions, and add spoken-word-jazz BGM.",
    "Uploading a 3-minute memoir-reading recording — please analyze it, add English subtitles, and overlay wistful-piano BGM.",
    "Here's a 4-minute children's-storytime recording — analyze it, add English captions, and add playful-flute BGM.",
    "I have a 90-second magician-busker clip — please analyze it, add English subtitles, and overlay mysterious-strings BGM.",
    "Uploading a 2-minute balloon-twister-busker clip — analyze it, add English captions, and add playful-clarinet BGM.",
    "Here's a 3-minute fire-eater-busker clip — please analyze it, add English subtitles, and overlay tribal-percussion BGM.",
    "I'm sending you a 4-minute juggler-busker clip — analyze it, add English captions, and add playful-clarinet BGM.",
    "Uploading a 90-second mime-busker clip — please analyze it, add English subtitles, and overlay delicate-piano BGM.",
    "Here's a 2-minute portrait-artist-park clip — analyze it, add English captions, and add French-musette BGM.",
    "I have a 3-minute caricature-artist-park clip — please analyze it, add English subtitles, and overlay jazz-piano BGM.",
    "Uploading a 4-minute henna-artist-festival clip — analyze it, add English captions, and add Indian-bansuri BGM.",
    "Here's a 90-second face-painter-festival clip — please analyze it, add English subtitles, and overlay playful-flute BGM.",
    "I'm sending you a 2-minute balloon-artist-festival clip — analyze it, add English captions, and add playful-clarinet BGM.",
    "Uploading a 3-minute tarot-reader-festival clip — please analyze it, add English subtitles, and overlay mysterious-strings BGM.",
    "Here's a 4-minute palmistry-festival clip — analyze it, add English captions, and add mysterious-strings BGM.",
    "I have a 90-second food-truck-tour clip — please analyze it, add English subtitles, and overlay upbeat-pop BGM.",
    "Uploading a 2-minute pop-up-restaurant tour — analyze it, add English captions, and add French-jazz BGM.",
    "Here's a 3-minute supper-club tour — please analyze it, add English subtitles, and overlay jazz-piano BGM.",
    "I'm sending you a 4-minute sushi-omakase tour — analyze it, add English captions, and add Japanese-koto BGM.",
    "Uploading a 90-second omakase-tasting clip — please analyze it, add English subtitles, and overlay Japanese-koto BGM.",
    "Here's a 2-minute wine-pairing dinner — analyze it, add English captions, and add French-classical BGM.",
    "I have a 3-minute cocktail-tasting tour — please analyze it, add English subtitles, and overlay jazz-piano BGM.",
    "Uploading a 4-minute craft-beer pairing — analyze it, add English captions, and add Bavarian-folk BGM.",
    "Here's a 90-second cigar-tasting room — please analyze it, add English subtitles, and overlay Cuban-son BGM.",
    "I'm sending you a 2-minute cheese-pairing tour — analyze it, add English captions, and add French-musette BGM.",
    "Uploading a 3-minute olive-oil-tasting tour — please analyze it, add English subtitles, and overlay Italian-mandolin BGM.",
    "Here's a 4-minute coffee-cupping room — analyze it, add English captions, and add Latin-folk BGM.",
    "I have a 90-second tea-tasting room — please analyze it, add English subtitles, and overlay Chinese-guzheng BGM.",
    "Uploading a 2-minute chocolate-pairing tour — analyze it, add English captions, and add French-Belle-Époque BGM.",
    "Here's a 3-minute honey-tasting tour — please analyze it, add English subtitles, and overlay pastoral-strings BGM.",
    "I'm sending you a 4-minute truffle-hunting clip — analyze it, add English captions, and add French-folk BGM.",
    "Uploading a 90-second mushroom-foraging clip — please analyze it, add English subtitles, and overlay Celtic-flute BGM.",
    "Here's a 2-minute wild-edibles-foraging clip — analyze it, add English captions, and add meditative-flute BGM.",
    "I have a 3-minute seaweed-foraging clip — please analyze it, add English subtitles, and overlay Japanese-shakuhachi BGM.",
    "Uploading a 4-minute shellfish-foraging clip — analyze it, add English captions, and add maritime-folk BGM.",
    "Here's a 90-second fly-fishing tutorial — please analyze it, add English subtitles, and overlay pastoral-strings BGM.",
    "I'm sending you a 2-minute trout-fishing tutorial — analyze it, add English captions, and add pastoral-strings BGM.",
    "Uploading a 3-minute bass-fishing tutorial — please analyze it, add English subtitles, and overlay country-rock BGM.",
    "Here's a 4-minute salmon-fishing tutorial — analyze it, add English captions, and add Pacific-Northwest-flute BGM.",
    "I have a 90-second ice-fishing tutorial — please analyze it, add English subtitles, and overlay winter-piano BGM.",
    "Uploading a 2-minute spearfishing tutorial — analyze it, add English captions, and add ambient-pad BGM.",
    "Here's a 3-minute squid-jigging tutorial — please analyze it, add English subtitles, and overlay Japanese-shamisen BGM.",
    "I'm sending you a 4-minute abalone-diving tutorial — analyze it, add English captions, and add Korean-pansori BGM.",
    "Uploading a 90-second sea-urchin-diving tutorial — please analyze it, add English subtitles, and overlay Japanese-shakuhachi BGM.",
    "Here's a 2-minute octopus-diving tutorial — analyze it, add English captions, and add ambient-electronic BGM.",
    # ── more European craftsman / artisan studios + craft-folk BGM (50) ──
    "Uploading a 2-minute Murano-glassblower studio reel — please analyze it, add English subtitles, and overlay Venetian-baroque BGM.",
    "Here's a 90-second Cremona-violin-maker workshop — analyze it, add English captions, and add Italian-baroque BGM.",
    "I have a 3-minute Tuscan-leather-tannery walkthrough — please analyze it, add English subtitles, and overlay Italian-folk BGM.",
    "Uploading a 4-minute Carrara-marble-quarry walkthrough — analyze it, add English captions, and add Italian-orchestral BGM.",
    "Here's a 90-second Parisian-haute-couture atelier — please analyze it, add English subtitles, and overlay French-cabaret BGM.",
    "I'm sending you a 2-minute Lyon-silk-weaver workshop — analyze it, add English captions, and add Lyon-baroque BGM.",
    "Uploading a 3-minute Limoges-porcelain-painter studio — please analyze it, add English subtitles, and overlay French-rococo BGM.",
    "Here's a 4-minute Bordeaux-cooper-barrel walkthrough — analyze it, add English captions, and add Aquitaine-folk BGM.",
    "I have a 90-second Cognac-distillery walkthrough — please analyze it, add English subtitles, and overlay French-classical BGM.",
    "Uploading a 2-minute Provençal-soap-boiler workshop — analyze it, add English captions, and add Provençal-folk BGM.",
    "Here's a 3-minute Calais-lace-maker workshop — please analyze it, add English subtitles, and overlay French-chamber BGM.",
    "I'm sending you a 4-minute Geneva-watchmaker bench walkthrough — analyze it, add English captions, and add Swiss-classical BGM.",
    "Uploading a 90-second Black-Forest-clockmaker workshop — please analyze it, add English subtitles, and overlay German-folk-zither BGM.",
    "Here's a 2-minute Solingen-knife-maker workshop — analyze it, add English captions, and add German-industrial-folk BGM.",
    "I have a 3-minute Meissen-porcelain studio walkthrough — please analyze it, add English subtitles, and overlay German-classical BGM.",
    "Uploading a 4-minute Munich-beer-brewery walkthrough — analyze it, add English captions, and add Bavarian-oompah BGM.",
    "Here's a 90-second Stuttgart-piano-maker workshop — please analyze it, add English subtitles, and overlay German-romantic BGM.",
    "I'm sending you a 2-minute Lübeck-marzipan workshop — analyze it, add English captions, and add Hanseatic-folk BGM.",
    "Uploading a 3-minute Bohemian-glass workshop walkthrough — please analyze it, add English subtitles, and overlay Czech-folk BGM.",
    "Here's a 4-minute Polish-amber jeweler workshop — analyze it, add English captions, and add Polish-folk BGM.",
    "I have a 90-second Lithuanian-amber-carver workshop — please analyze it, add English subtitles, and overlay Lithuanian-folk BGM.",
    "Uploading a 2-minute Latvian-textile workshop walkthrough — analyze it, add English captions, and add Latvian-folk BGM.",
    "Here's a 3-minute Estonian-juniper-cooper workshop — please analyze it, add English subtitles, and overlay Estonian-folk BGM.",
    "I'm sending you a 4-minute Helsinki-glass-design workshop — analyze it, add English captions, and add Finnish-folk BGM.",
    "Uploading a 90-second Stockholm-tin-soldier workshop — please analyze it, add English subtitles, and overlay Swedish-folk BGM.",
    "Here's a 2-minute Oslo-Hardanger-fiddle-maker workshop — analyze it, add English captions, and add Norwegian-Hardanger-fiddle BGM.",
    "I have a 3-minute Copenhagen-silversmith workshop — please analyze it, add English subtitles, and overlay Danish-spillemand BGM.",
    "Uploading a 4-minute Reykjavik-knitter workshop — analyze it, add English captions, and add Icelandic-folk BGM.",
    "Here's a 90-second Edinburgh-tartan-loom workshop — please analyze it, add English subtitles, and overlay Scottish-fiddle BGM.",
    "I'm sending you a 2-minute Welsh-slate-quarry walkthrough — analyze it, add English captions, and add Welsh-male-choir BGM.",
    "Uploading a 3-minute Connemara-marble workshop — please analyze it, add English subtitles, and overlay Irish-uilleann-pipe BGM.",
    "Here's a 4-minute Donegal-tweed-weaver workshop — analyze it, add English captions, and add Donegal-fiddle BGM.",
    "I have a 90-second Kerry-blackthorn-shillelagh workshop — please analyze it, add English subtitles, and overlay Irish-tin-whistle BGM.",
    "Uploading a 2-minute Toledo-sword-maker workshop — analyze it, add English captions, and add Spanish-classical-guitar BGM.",
    "Here's a 3-minute Granada-marquetry workshop — please analyze it, add English subtitles, and overlay Andalusian-flamenco BGM.",
    "I'm sending you a 4-minute Sevilla-espadrille workshop — analyze it, add English captions, and add Spanish-zarzuela BGM.",
    "Uploading a 90-second Manises-tile-painter workshop — please analyze it, add English subtitles, and overlay Spanish-folk BGM.",
    "Here's a 2-minute Lisbon-azulejo-painter workshop — analyze it, add English captions, and add fado BGM.",
    "I have a 3-minute Porto-port-wine-cooperage walkthrough — please analyze it, add English subtitles, and overlay Portuguese-folk BGM.",
    "Uploading a 4-minute Madeira-embroidery workshop — analyze it, add English captions, and add Madeira-folk BGM.",
    "Here's a 90-second Athens-marble-cutter workshop — please analyze it, add English subtitles, and overlay Greek-bouzouki BGM.",
    "I'm sending you a 2-minute Crete-loom workshop — analyze it, add English captions, and add Cretan-lyra BGM.",
    "Uploading a 3-minute Mykonos-sail-maker workshop — please analyze it, add English subtitles, and overlay Greek-folk BGM.",
    "Here's a 4-minute Istanbul-Iznik-tile workshop — analyze it, add English captions, and add Ottoman-classical BGM.",
    "I have a 90-second Bursa-silk workshop — please analyze it, add English subtitles, and overlay Turkish-saz BGM.",
    "Uploading a 2-minute Kütahya-ceramic workshop — analyze it, add English captions, and add Turkish-makam BGM.",
    "Here's a 3-minute Konya-ney-flute workshop — please analyze it, add English subtitles, and overlay Sufi-ney BGM.",
    "I'm sending you a 4-minute Cairo-papyrus-painter workshop — analyze it, add English captions, and add Egyptian-oud BGM.",
    "Uploading a 90-second Alexandria-mosaic workshop — please analyze it, add English subtitles, and overlay Mediterranean-classical BGM.",
    "Here's a 2-minute Damascus-mosaic-inlay workshop — analyze it, add English captions, and add Levantine-oud BGM.",
    # ── more nature / science documentary clips + documentary BGM (50) ──
    "Uploading a 3-minute Serengeti-wildebeest-migration documentary clip — please analyze it, add English subtitles, and overlay savanna-orchestral BGM.",
    "Here's a 4-minute Okavango-Delta-elephants documentary clip — analyze it, add English captions, and add Pan-African-orchestral BGM.",
    "I have a 90-second Galápagos-marine-iguana documentary clip — please analyze it, add English subtitles, and overlay tropical-orchestral BGM.",
    "I'm sending you a 2-minute Madagascar-lemur documentary clip — analyze it, add English captions, and add Madagascan-folk-orchestral BGM.",
    "Uploading a 3-minute Borneo-orangutan documentary clip — please analyze it, add English subtitles, and overlay Bornean-jungle-orchestral BGM.",
    "Here's a 4-minute Amazon-jaguar documentary clip — analyze it, add English captions, and add Amazon-orchestral BGM.",
    "I have a 90-second Pantanal-anaconda documentary clip — please analyze it, add English subtitles, and overlay Pantanal-orchestral BGM.",
    "I'm sending you a 2-minute Andes-condor documentary clip — analyze it, add English captions, and add Andean-pan-flute-orchestral BGM.",
    "Uploading a 3-minute Patagonia-puma documentary clip — please analyze it, add English subtitles, and overlay Patagonian-orchestral BGM.",
    "Here's a 4-minute Antarctica-emperor-penguin documentary clip — analyze it, add English captions, and add Antarctic-orchestral BGM.",
    "I have a 90-second Arctic-narwhal documentary clip — please analyze it, add English subtitles, and overlay Arctic-orchestral BGM.",
    "I'm sending you a 2-minute Kamchatka-volcano documentary clip — analyze it, add English captions, and add Kamchatka-orchestral BGM.",
    "Uploading a 3-minute Yellowstone-wolf-pack documentary clip — please analyze it, add English subtitles, and overlay Rocky-Mountain-orchestral BGM.",
    "Here's a 4-minute Yosemite-El-Capitan-time-lapse documentary — analyze it, add English captions, and add Sierra-Nevada-orchestral BGM.",
    "I have a 90-second Grand-Canyon-condor documentary clip — please analyze it, add English subtitles, and overlay Southwestern-orchestral BGM.",
    "I'm sending you a 2-minute Great-Barrier-Reef-coral-spawning documentary clip — analyze it, add English captions, and add Coral-Sea-orchestral BGM.",
    "Uploading a 3-minute Maldives-manta-ray documentary clip — please analyze it, add English subtitles, and overlay Indian-Ocean-orchestral BGM.",
    "Here's a 4-minute Mariana-Trench-bathysphere documentary clip — analyze it, add English captions, and add deep-sea-ambient BGM.",
    "I have a 90-second Hubble-deep-field astronomy documentary — please analyze it, add English subtitles, and overlay cosmic-ambient BGM.",
    "I'm sending you a 2-minute James-Webb-cosmic-cliffs documentary — analyze it, add English captions, and add JWST-cosmic-orchestral BGM.",
    "Uploading a 3-minute Curiosity-rover-Mars-panorama documentary — please analyze it, add English subtitles, and overlay Mars-ambient BGM.",
    "Here's a 4-minute Cassini-Saturn-rings documentary — analyze it, add English captions, and add Saturn-ambient BGM.",
    "I have a 90-second Voyager-pale-blue-dot documentary — please analyze it, add English subtitles, and overlay deep-space-ambient BGM.",
    "I'm sending you a 2-minute LIGO-gravitational-wave documentary — analyze it, add English captions, and add LIGO-pulse BGM.",
    "Uploading a 3-minute LHC-collider documentary — please analyze it, add English subtitles, and overlay particle-physics-orchestral BGM.",
    "Here's a 4-minute IceCube-neutrino-observatory documentary — analyze it, add English captions, and add Antarctic-physics-orchestral BGM.",
    "I have a 90-second Antarctic-ice-core documentary — please analyze it, add English subtitles, and overlay glacial-ambient BGM.",
    "I'm sending you a 2-minute Greenland-meltwater documentary — analyze it, add English captions, and add Arctic-melt-orchestral BGM.",
    "Uploading a 3-minute Iceland-volcano-lava-flow documentary — please analyze it, add English subtitles, and overlay Icelandic-orchestral BGM.",
    "Here's a 4-minute Hawaii-Kilauea-eruption documentary — analyze it, add English captions, and add Hawaiian-volcanic-orchestral BGM.",
    "I have a 90-second Mount-Etna-eruption documentary — please analyze it, add English subtitles, and overlay Sicilian-orchestral BGM.",
    "I'm sending you a 2-minute Iguazu-Falls-aerial documentary — analyze it, add English captions, and add Iguazu-orchestral BGM.",
    "Uploading a 3-minute Victoria-Falls-aerial documentary — please analyze it, add English subtitles, and overlay Zambezi-orchestral BGM.",
    "Here's a 4-minute Niagara-Falls-night documentary — analyze it, add English captions, and add Niagara-orchestral BGM.",
    "I have a 90-second Aurora-borealis-Tromsø documentary — please analyze it, add English subtitles, and overlay aurora-ambient BGM.",
    "I'm sending you a 2-minute Aurora-australis-Tasmania documentary — analyze it, add English captions, and add Tasmanian-aurora-ambient BGM.",
    "Uploading a 3-minute Northern-Lights-Iceland documentary — please analyze it, add English subtitles, and overlay Icelandic-aurora-ambient BGM.",
    "Here's a 4-minute Milky-Way-Atacama documentary — analyze it, add English captions, and add Atacama-celestial-ambient BGM.",
    "I have a 90-second Total-solar-eclipse documentary — please analyze it, add English subtitles, and overlay solar-eclipse-orchestral BGM.",
    "I'm sending you a 2-minute Lunar-eclipse documentary — analyze it, add English captions, and add lunar-eclipse-ambient BGM.",
    "Uploading a 3-minute Annular-eclipse documentary — please analyze it, add English subtitles, and overlay annular-orchestral BGM.",
    "Here's a 4-minute Perseid-meteor-shower documentary — analyze it, add English captions, and add Perseid-orchestral BGM.",
    "I have a 90-second Geminid-meteor-shower documentary — please analyze it, add English subtitles, and overlay Geminid-orchestral BGM.",
    "I'm sending you a 2-minute Lyrid-meteor-shower documentary — analyze it, add English captions, and add Lyrid-orchestral BGM.",
    "Uploading a 3-minute Orionid-meteor-shower documentary — please analyze it, add English subtitles, and overlay Orionid-orchestral BGM.",
    "Here's a 4-minute SpaceX-Falcon-Heavy launch documentary — analyze it, add English captions, and add SpaceX-orchestral BGM.",
    "I have a 90-second SpaceX-Starship test-flight documentary — please analyze it, add English subtitles, and overlay Starship-orchestral BGM.",
    "I'm sending you a 2-minute Blue-Origin-New-Shepard documentary — analyze it, add English captions, and add Blue-Origin-orchestral BGM.",
    "Uploading a 3-minute ISS-spacewalk documentary — please analyze it, add English subtitles, and overlay ISS-ambient BGM.",
    "Here's a 4-minute Apollo-11-launch archival documentary — analyze it, add English captions, and add Apollo-orchestral BGM.",
    # ── more travel-vlog / destination clips + travel-cinematic BGM (50) ──
    "Uploading a 2-minute Iceland-Vík-black-sand vlog — please analyze it, add English subtitles, and swap in Icelandic-cinematic BGM.",
    "Here's a 90-second Faroe-Islands-Múlafossur-waterfall vlog — analyze it, overlay English captions, and add Faroese-cinematic BGM.",
    "I have a 3-minute Lofoten-Norway-Reine vlog — please analyze it, add English subtitles, and overlay Norwegian-cinematic BGM.",
    "Uploading a 1-minute Greenland-Ilulissat-icefjord vlog — analyze it, overlay English captions, and add Inuit-cinematic BGM.",
    "Here's a 90-second Patagonia-Torres-del-Paine vlog — analyze it, add English subtitles, and overlay Patagonian-cinematic BGM.",
    "I'm sending you a 2-minute Atacama-Desert-stargazing vlog — analyze it, add English captions, and add Atacama-cinematic BGM.",
    "Uploading a 3-minute Salar-de-Uyuni-mirror vlog — please analyze it, add English subtitles, and overlay Bolivian-cinematic BGM.",
    "Here's a 4-minute Machu-Picchu-sunrise vlog — analyze it, add English captions, and add Peruvian-cinematic BGM.",
    "I have a 90-second Galápagos-Islands-cruise vlog — please analyze it, add English subtitles, and overlay Galápagos-cinematic BGM.",
    "I'm sending you a 2-minute Easter-Island-Moai vlog — analyze it, add English captions, and add Rapa-Nui-cinematic BGM.",
    "Uploading a 3-minute French-Polynesia-Bora-Bora vlog — please analyze it, add English subtitles, and overlay Tahitian-cinematic BGM.",
    "Here's a 4-minute Maldives-overwater-bungalow vlog — analyze it, add English captions, and add Maldivian-cinematic BGM.",
    "I have a 90-second Seychelles-Anse-Source-d'Argent vlog — please analyze it, add English subtitles, and overlay Seychellois-cinematic BGM.",
    "Uploading a 2-minute Mauritius-Le-Morne vlog — analyze it, overlay English captions, and add Mauritian-cinematic BGM.",
    "Here's a 90-second Madagascar-Avenue-of-Baobabs vlog — analyze it, add English subtitles, and overlay Malagasy-cinematic BGM.",
    "I'm sending you a 3-minute Zanzibar-Stone-Town vlog — analyze it, add English captions, and add Zanzibari-cinematic BGM.",
    "Uploading a 1-minute Kenya-Maasai-Mara vlog — please analyze it, add English subtitles, and overlay Maasai-cinematic BGM.",
    "Here's a 4-minute Tanzania-Serengeti-migration vlog — analyze it, add English captions, and add Serengeti-cinematic BGM.",
    "I have a 90-second Botswana-Okavango-Delta vlog — please analyze it, add English subtitles, and overlay Botswanan-cinematic BGM.",
    "I'm sending you a 2-minute Namibia-Sossusvlei-dunes vlog — analyze it, add English captions, and add Namibian-cinematic BGM.",
    "Uploading a 3-minute Egypt-Pyramids-Giza vlog — please analyze it, add English subtitles, and overlay Egyptian-cinematic BGM.",
    "Here's a 4-minute Jordan-Petra-Treasury vlog — analyze it, add English captions, and add Petra-cinematic BGM.",
    "I have a 90-second Wadi-Rum-Mars-Valley vlog — please analyze it, add English subtitles, and overlay Wadi-Rum-cinematic BGM.",
    "Uploading a 2-minute Uzbekistan-Samarkand-Registan vlog — analyze it, overlay English captions, and add Uzbek-cinematic BGM.",
    "Here's a 90-second Bukhara-Old-Town vlog — analyze it, add English subtitles, and overlay Bukharan-cinematic BGM.",
    "I'm sending you a 3-minute Khiva-Itchan-Kala vlog — analyze it, add English captions, and add Khivan-cinematic BGM.",
    "Uploading a 1-minute Turkmenistan-Darvaza-gas-crater vlog — please analyze it, add English subtitles, and overlay Turkmen-cinematic BGM.",
    "Here's a 4-minute Kyrgyzstan-Issyk-Kul vlog — analyze it, add English captions, and add Kyrgyz-cinematic BGM.",
    "I have a 90-second Tajikistan-Pamir-Highway vlog — please analyze it, add English subtitles, and overlay Pamiri-cinematic BGM.",
    "I'm sending you a 2-minute Bhutan-Tiger's-Nest vlog — analyze it, add English captions, and add Bhutanese-cinematic BGM.",
    "Uploading a 3-minute Nepal-Annapurna-circuit vlog — please analyze it, add English subtitles, and overlay Nepalese-cinematic BGM.",
    "Here's a 4-minute Sikkim-Yumthang-valley vlog — analyze it, add English captions, and add Sikkimese-cinematic BGM.",
    "I have a 90-second Ladakh-Pangong-Tso vlog — please analyze it, add English subtitles, and overlay Ladakhi-cinematic BGM.",
    "Uploading a 2-minute Kashmir-Dal-Lake vlog — analyze it, overlay English captions, and add Kashmiri-cinematic BGM.",
    "Here's a 90-second Spiti-Valley-monastery vlog — analyze it, add English subtitles, and overlay Spiti-cinematic BGM.",
    "I'm sending you a 3-minute Mongolia-Gobi-camel vlog — analyze it, add English captions, and add Mongolian-cinematic BGM.",
    "Uploading a 1-minute Russian-Lake-Baikal-ice vlog — please analyze it, add English subtitles, and overlay Baikal-cinematic BGM.",
    "Here's a 4-minute Kamchatka-volcano vlog — analyze it, add English captions, and add Kamchatkan-cinematic BGM.",
    "I have a 90-second Trans-Siberian-railway vlog — please analyze it, add English subtitles, and overlay Trans-Siberian-cinematic BGM.",
    "I'm sending you a 2-minute Hokkaido-Furano-lavender vlog — analyze it, add English captions, and add Hokkaido-cinematic BGM.",
    "Uploading a 3-minute Kyoto-Arashiyama-bamboo vlog — please analyze it, add English subtitles, and overlay Kyoto-cinematic BGM.",
    "Here's a 4-minute Yakushima-cedar-forest vlog — analyze it, add English captions, and add Yakushima-cinematic BGM.",
    "I have a 90-second Okinawa-Kerama-island vlog — please analyze it, add English subtitles, and overlay Okinawan-cinematic BGM.",
    "Uploading a 2-minute Halong-Bay-cruise vlog — analyze it, overlay English captions, and add Vietnamese-cinematic BGM.",
    "Here's a 90-second Ninh-Binh-Tam-Coc vlog — analyze it, add English subtitles, and overlay Tam-Coc-cinematic BGM.",
    "I'm sending you a 3-minute Luang-Prabang-monk-walk vlog — analyze it, add English captions, and add Lao-cinematic BGM.",
    "Uploading a 1-minute Angkor-Wat-sunrise vlog — please analyze it, add English subtitles, and overlay Khmer-cinematic BGM.",
    "Here's a 4-minute Bagan-temple-balloon vlog — analyze it, add English captions, and add Bagan-cinematic BGM.",
    "I have a 90-second Inle-Lake-Burma vlog — please analyze it, add English subtitles, and overlay Inle-cinematic BGM.",
    "I'm sending you a 2-minute Komodo-island vlog — analyze it, add English captions, and add Komodo-cinematic BGM.",
    "Uploading a 3-minute Raja-Ampat-snorkel vlog — please analyze it, add English subtitles, and overlay Raja-Ampat-cinematic BGM.",
    # ── more sports-broadcast / Olympic-final / world-cup-final highlight clips + epic-orchestral BGM (50) ──
    "Uploading a 2-minute 2014-FIFA-World-Cup-Final-Germany-Argentina clip — please analyze it, add English subtitles, and swap in 2014-WC-Final-orchestral BGM.",
    "Here's a 90-second 2018-FIFA-World-Cup-Final-France-Croatia clip — analyze it, overlay English captions, and add 2018-WC-Final-orchestral BGM.",
    "I have a 3-minute 2022-FIFA-World-Cup-Final-Argentina-France clip — please analyze it, add English subtitles, and overlay 2022-Lusail-orchestral BGM.",
    "Uploading a 1-minute 2010-FIFA-World-Cup-Final-Spain-Netherlands clip — analyze it, overlay English captions, and add 2010-Soccer-City-orchestral BGM.",
    "Here's a 90-second UEFA-Champions-League-Final-2023-City-Inter clip — analyze it, add English subtitles, and overlay UCL-Final-2023-orchestral BGM.",
    "I'm sending you a 2-minute UEFA-Euro-2020-Final-Italy-England clip — analyze it, add English captions, and add Euro-2020-Final-orchestral BGM.",
    "Uploading a 3-minute Copa-América-Final-Argentina-Brazil-2021 clip — please analyze it, add English subtitles, and overlay Copa-América-2021-orchestral BGM.",
    "Here's a 4-minute AFCON-Final-Senegal-Egypt-2022 clip — analyze it, add English captions, and add AFCON-2022-orchestral BGM.",
    "I have a 90-second AFC-Asian-Cup-Final-Qatar-Jordan-2023 clip — please analyze it, add English subtitles, and overlay AFC-2023-orchestral BGM.",
    "I'm sending you a 2-minute Super-Bowl-LVIII-Chiefs-49ers clip — analyze it, add English captions, and add Super-Bowl-LVIII-orchestral BGM.",
    "Uploading a 3-minute Super-Bowl-LV-Buccaneers-Chiefs clip — please analyze it, add English subtitles, and overlay Super-Bowl-LV-orchestral BGM.",
    "Here's a 4-minute NBA-Finals-2023-Nuggets-Heat clip — analyze it, add English captions, and add NBA-Finals-2023-orchestral BGM.",
    "I have a 90-second NBA-Finals-2024-Celtics-Mavericks clip — please analyze it, add English subtitles, and overlay NBA-Finals-2024-orchestral BGM.",
    "Uploading a 2-minute NBA-Finals-2016-Cavs-Warriors-Game-7 clip — analyze it, overlay English captions, and add NBA-2016-G7-orchestral BGM.",
    "Here's a 90-second 2023-MLB-World-Series-Rangers-Diamondbacks clip — analyze it, add English subtitles, and overlay MLB-2023-WS-orchestral BGM.",
    "I'm sending you a 3-minute 2024-MLB-World-Series-Dodgers-Yankees clip — analyze it, add English captions, and add MLB-2024-WS-orchestral BGM.",
    "Uploading a 1-minute NHL-Stanley-Cup-2024-Panthers-Oilers clip — please analyze it, add English subtitles, and overlay Stanley-Cup-2024-orchestral BGM.",
    "Here's a 4-minute 2024-Paris-Olympics-Opening-Ceremony clip — analyze it, add English captions, and add Paris-2024-Opening-orchestral BGM.",
    "I have a 90-second 2024-Paris-Olympics-100m-Final clip — please analyze it, add English subtitles, and overlay Paris-100m-orchestral BGM.",
    "I'm sending you a 2-minute 2024-Paris-Olympics-Marathon clip — analyze it, add English captions, and add Paris-Marathon-orchestral BGM.",
    "Uploading a 3-minute 2024-Paris-Olympics-Gymnastics clip — please analyze it, add English subtitles, and overlay Paris-Gymnastics-orchestral BGM.",
    "Here's a 4-minute 2024-Paris-Olympics-Swimming-Final clip — analyze it, add English captions, and add Paris-Swimming-orchestral BGM.",
    "I have a 90-second 2020-Tokyo-Olympics-Opening-Ceremony clip — please analyze it, add English subtitles, and overlay Tokyo-2020-Opening-orchestral BGM.",
    "Uploading a 2-minute 2016-Rio-Olympics-Opening-Ceremony clip — analyze it, overlay English captions, and add Rio-2016-Opening-orchestral BGM.",
    "Here's a 90-second 2012-London-Olympics-Opening-Ceremony clip — analyze it, add English subtitles, and overlay London-2012-Opening-orchestral BGM.",
    "I'm sending you a 3-minute 2008-Beijing-Olympics-Opening-Ceremony clip — analyze it, add English captions, and add Beijing-2008-Opening-orchestral BGM.",
    "Uploading a 1-minute 2024-UEFA-Champions-League-Final-Real-Dortmund clip — please analyze it, add English subtitles, and overlay UCL-2024-orchestral BGM.",
    "Here's a 4-minute Wimbledon-Men's-Final-2023-Alcaraz-Djokovic clip — analyze it, add English captions, and add Wimbledon-2023-orchestral BGM.",
    "I have a 90-second Wimbledon-Women's-Final-2024-Krejcikova-Paolini clip — please analyze it, add English subtitles, and overlay Wimbledon-2024-W-orchestral BGM.",
    "I'm sending you a 2-minute French-Open-Men's-Final-2024-Alcaraz-Zverev clip — analyze it, add English captions, and add French-Open-2024-orchestral BGM.",
    "Uploading a 3-minute Australian-Open-Men's-Final-2024-Sinner-Medvedev clip — please analyze it, add English subtitles, and overlay AusOpen-2024-orchestral BGM.",
    "Here's a 4-minute US-Open-Men's-Final-2024-Sinner-Fritz clip — analyze it, add English captions, and add USOpen-2024-orchestral BGM.",
    "I have a 90-second Masters-2024-Augusta-Scheffler clip — please analyze it, add English subtitles, and overlay Masters-2024-orchestral BGM.",
    "Uploading a 2-minute British-Open-2024-Schauffele clip — analyze it, overlay English captions, and add British-Open-2024-orchestral BGM.",
    "Here's a 90-second Ryder-Cup-2023-Marco-Simone clip — analyze it, add English subtitles, and overlay Ryder-Cup-2023-orchestral BGM.",
    "I'm sending you a 3-minute Tour-de-France-2024-Pogačar-Champs-Elysées clip — analyze it, add English captions, and add Tour-de-France-2024-orchestral BGM.",
    "Uploading a 1-minute Giro-d'Italia-2024 clip — please analyze it, add English subtitles, and overlay Giro-2024-orchestral BGM.",
    "Here's a 4-minute Vuelta-a-España-2024 clip — analyze it, add English captions, and add Vuelta-2024-orchestral BGM.",
    "I have a 90-second F1-Monaco-Grand-Prix-2024-Leclerc clip — please analyze it, add English subtitles, and overlay F1-Monaco-2024-orchestral BGM.",
    "I'm sending you a 2-minute F1-Abu-Dhabi-2021-Verstappen clip — analyze it, add English captions, and add F1-Abu-Dhabi-2021-orchestral BGM.",
    "Uploading a 3-minute MotoGP-2024-Bagnaia clip — please analyze it, add English subtitles, and overlay MotoGP-2024-orchestral BGM.",
    "Here's a 4-minute Indianapolis-500-2024 clip — analyze it, add English captions, and add Indy-500-2024-orchestral BGM.",
    "I have a 90-second Daytona-500-2024 clip — please analyze it, add English subtitles, and overlay Daytona-500-2024-orchestral BGM.",
    "Uploading a 2-minute Kentucky-Derby-2024 clip — analyze it, overlay English captions, and add Kentucky-Derby-2024-orchestral BGM.",
    "Here's a 90-second Royal-Ascot-Gold-Cup clip — analyze it, add English subtitles, and overlay Royal-Ascot-orchestral BGM.",
    "I'm sending you a 3-minute Boston-Marathon-2024 clip — analyze it, add English captions, and add Boston-Marathon-orchestral BGM.",
    "Uploading a 1-minute Tour-de-Ski-Holmenkollen clip — please analyze it, add English subtitles, and overlay Holmenkollen-orchestral BGM.",
    "Here's a 4-minute Iditarod-Sled-Dog-Race clip — analyze it, add English captions, and add Iditarod-orchestral BGM.",
    "I have a 90-second Tour-de-France-Femmes-2024 clip — please analyze it, add English subtitles, and overlay TdF-Femmes-2024-orchestral BGM.",
    "I'm sending you a 2-minute Wimbledon-Doubles-Final-2024 clip — analyze it, add English captions, and add Wimbledon-Doubles-2024-orchestral BGM.",
    # ── more cooking-competition / culinary-TV clips + upbeat-cooking BGM (50) ──
    "Uploading a 2-minute MasterChef-US-Final clip — please analyze it, add English subtitles, and swap in MasterChef-US-Final-upbeat BGM.",
    "Here's a 90-second MasterChef-Australia-Final clip — analyze it, overlay English captions, and add MasterChef-Australia-upbeat BGM.",
    "I have a 3-minute MasterChef-Junior-pressure-test clip — please analyze it, add English subtitles, and overlay MasterChef-Junior-upbeat BGM.",
    "Uploading a 1-minute Hell's-Kitchen-Final clip — analyze it, overlay English captions, and add Hell's-Kitchen-Final-upbeat BGM.",
    "Here's a 90-second Hell's-Kitchen-Black-Jacket-dinner-service clip — analyze it, add English subtitles, and overlay Hell's-Kitchen-Black-Jacket-upbeat BGM.",
    "I'm sending you a 2-minute Top-Chef-Quickfire clip — analyze it, add English captions, and add Top-Chef-Quickfire-upbeat BGM.",
    "Uploading a 3-minute Top-Chef-Restaurant-Wars clip — please analyze it, add English subtitles, and overlay Top-Chef-Restaurant-Wars-upbeat BGM.",
    "Here's a 4-minute Top-Chef-Final clip — analyze it, add English captions, and add Top-Chef-Final-upbeat BGM.",
    "I have a 90-second Chopped-Mystery-Basket clip — please analyze it, add English subtitles, and overlay Chopped-Mystery-Basket-upbeat BGM.",
    "I'm sending you a 2-minute Iron-Chef-America-Battle clip — analyze it, add English captions, and add Iron-Chef-America-upbeat BGM.",
    "Uploading a 3-minute Iron-Chef-Japan-Battle-archive clip — please analyze it, add English subtitles, and overlay Iron-Chef-Japan-upbeat BGM.",
    "Here's a 4-minute Beat-Bobby-Flay-duel clip — analyze it, add English captions, and add Beat-Bobby-Flay-upbeat BGM.",
    "I have a 90-second Cutthroat-Kitchen-sabotage clip — please analyze it, add English subtitles, and overlay Cutthroat-Kitchen-upbeat BGM.",
    "Uploading a 2-minute Worst-Cooks-in-America clip — analyze it, overlay English captions, and add Worst-Cooks-upbeat BGM.",
    "Here's a 90-second Restaurant-Impossible-Robert-Irvine clip — analyze it, add English subtitles, and overlay Restaurant-Impossible-upbeat BGM.",
    "I'm sending you a 3-minute Kitchen-Nightmares-Gordon-Ramsay clip — analyze it, add English captions, and add Kitchen-Nightmares-upbeat BGM.",
    "Uploading a 1-minute Hotel-Hell-Gordon-Ramsay clip — please analyze it, add English subtitles, and overlay Hotel-Hell-upbeat BGM.",
    "Here's a 4-minute Bake-Off-Tent-Showstopper clip — analyze it, add English captions, and add Bake-Off-Showstopper-upbeat BGM.",
    "I have a 90-second Bake-Off-Technical-Challenge clip — please analyze it, add English subtitles, and overlay Bake-Off-Technical-upbeat BGM.",
    "I'm sending you a 2-minute Bake-Off-Final clip — analyze it, add English captions, and add Bake-Off-Final-upbeat BGM.",
    "Uploading a 3-minute Bake-Off-Junior-Final clip — please analyze it, add English subtitles, and overlay Bake-Off-Junior-Final-upbeat BGM.",
    "Here's a 4-minute Bake-Off-Bake-Christmas-Special clip — analyze it, add English captions, and add Bake-Off-Christmas-upbeat BGM.",
    "I have a 90-second Nailed-It-cake-fail clip — please analyze it, add English subtitles, and overlay Nailed-It-upbeat BGM.",
    "Uploading a 2-minute Sugar-Rush-Netflix clip — analyze it, overlay English captions, and add Sugar-Rush-upbeat BGM.",
    "Here's a 90-second Cake-Boss-Carlo's-Bakery clip — analyze it, add English subtitles, and overlay Cake-Boss-upbeat BGM.",
    "I'm sending you a 3-minute Cake-Wars-Final clip — analyze it, add English captions, and add Cake-Wars-Final-upbeat BGM.",
    "Uploading a 1-minute Halloween-Wars-Sugar-Skull clip — please analyze it, add English subtitles, and overlay Halloween-Wars-upbeat BGM.",
    "Here's a 4-minute Holiday-Baking-Championship clip — analyze it, add English captions, and add Holiday-Baking-upbeat BGM.",
    "I have a 90-second Spring-Baking-Championship clip — please analyze it, add English subtitles, and overlay Spring-Baking-upbeat BGM.",
    "I'm sending you a 2-minute Kids-Baking-Championship clip — analyze it, add English captions, and add Kids-Baking-upbeat BGM.",
    "Uploading a 3-minute Final-Table-Netflix clip — please analyze it, add English subtitles, and overlay Final-Table-upbeat BGM.",
    "Here's a 4-minute Chef's-Table-segment clip — analyze it, add English captions, and add Chef's-Table-upbeat BGM.",
    "I have a 90-second Chef's-Table-France-segment clip — please analyze it, add English subtitles, and overlay Chef's-Table-France-upbeat BGM.",
    "Uploading a 2-minute Chef's-Table-BBQ-segment clip — analyze it, overlay English captions, and add Chef's-Table-BBQ-upbeat BGM.",
    "Here's a 90-second Chef's-Table-Pastry-segment clip — analyze it, add English subtitles, and overlay Chef's-Table-Pastry-upbeat BGM.",
    "I'm sending you a 3-minute Ugly-Delicious-David-Chang clip — analyze it, add English captions, and add Ugly-Delicious-upbeat BGM.",
    "Uploading a 1-minute Salt-Fat-Acid-Heat-Samin-Nosrat clip — please analyze it, add English subtitles, and overlay Salt-Fat-Acid-Heat-upbeat BGM.",
    "Here's a 4-minute Street-Food-Asia-Netflix clip — analyze it, add English captions, and add Street-Food-Asia-upbeat BGM.",
    "I have a 90-second Street-Food-Latin-America clip — please analyze it, add English subtitles, and overlay Street-Food-Latin-America-upbeat BGM.",
    "Uploading a 2-minute Street-Food-Africa-Netflix clip — analyze it, overlay English captions, and add Street-Food-Africa-upbeat BGM.",
    "Here's a 90-second Magnolia-Network-Magnolia-Table-Joanna-Gaines clip — analyze it, add English subtitles, and overlay Magnolia-Table-upbeat BGM.",
    "I'm sending you a 3-minute Pioneer-Woman-Ree-Drummond clip — analyze it, add English captions, and add Pioneer-Woman-upbeat BGM.",
    "Uploading a 1-minute Barefoot-Contessa-Ina-Garten clip — please analyze it, add English subtitles, and overlay Barefoot-Contessa-upbeat BGM.",
    "Here's a 4-minute Giada-At-Home-De-Laurentiis clip — analyze it, add English captions, and add Giada-At-Home-upbeat BGM.",
    "I have a 90-second Anthony-Bourdain-Parts-Unknown-Vietnam clip — please analyze it, add English subtitles, and overlay Bourdain-Parts-Unknown-upbeat BGM.",
    "Uploading a 2-minute Bourdain-No-Reservations-Tokyo clip — analyze it, overlay English captions, and add Bourdain-No-Reservations-upbeat BGM.",
    "Here's a 90-second Stanley-Tucci-Searching-for-Italy clip — analyze it, add English subtitles, and overlay Tucci-Searching-Italy-upbeat BGM.",
    "I'm sending you a 3-minute Phil-Rosenthal-Somebody-Feed-Phil clip — analyze it, add English captions, and add Somebody-Feed-Phil-upbeat BGM.",
    "Uploading a 1-minute Padma-Lakshmi-Taste-the-Nation clip — please analyze it, add English subtitles, and overlay Taste-the-Nation-upbeat BGM.",
    "Here's a 4-minute David-Chang-Eater clip — analyze it, add English captions, and add David-Chang-Eater-upbeat BGM.",
    "I have a 90-second Munchies-Vice-segment clip — please analyze it, add English subtitles, and overlay Munchies-Vice-upbeat BGM.",
    # ── more nature documentary references (50) ──
    "Uploading a 2-minute BBC-Planet-Earth-mountains clip — analyze it, overlay English captions, and add BBC-Planet-Earth-mountains-orchestral BGM.",
    "Here's a 90-second BBC-Planet-Earth-jungles clip — analyze it, add English subtitles, and overlay BBC-Planet-Earth-jungles-orchestral BGM.",
    "I'm sending you a 3-minute BBC-Planet-Earth-deserts clip — analyze it, add English captions, and add BBC-Planet-Earth-deserts-orchestral BGM.",
    "Uploading a 1-minute BBC-Planet-Earth-poles clip — please analyze it, add English subtitles, and overlay BBC-Planet-Earth-poles-orchestral BGM.",
    "Here's a 4-minute BBC-Frozen-Planet-Arctic clip — analyze it, add English captions, and add BBC-Frozen-Planet-Arctic-orchestral BGM.",
    "I have a 90-second BBC-Frozen-Planet-Antarctic clip — please analyze it, add English subtitles, and overlay BBC-Frozen-Planet-Antarctic-orchestral BGM.",
    "Uploading a 2-minute BBC-Blue-Planet-coral-reef clip — analyze it, overlay English captions, and add BBC-Blue-Planet-coral-reef-orchestral BGM.",
    "Here's a 90-second BBC-Blue-Planet-deep-sea clip — analyze it, add English subtitles, and overlay BBC-Blue-Planet-deep-sea-orchestral BGM.",
    "I'm sending you a 3-minute BBC-Blue-Planet-II-open-ocean clip — analyze it, add English captions, and add BBC-Blue-Planet-II-open-ocean-orchestral BGM.",
    "Uploading a 1-minute BBC-Africa-Kalahari clip — please analyze it, add English subtitles, and overlay BBC-Africa-Kalahari-orchestral BGM.",
    "Here's a 4-minute BBC-Africa-Sahara clip — analyze it, add English captions, and add BBC-Africa-Sahara-orchestral BGM.",
    "I have a 90-second BBC-Africa-Cape clip — please analyze it, add English subtitles, and overlay BBC-Africa-Cape-orchestral BGM.",
    "Uploading a 2-minute BBC-Life-mammals clip — analyze it, overlay English captions, and add BBC-Life-mammals-orchestral BGM.",
    "Here's a 90-second BBC-Life-birds clip — analyze it, add English subtitles, and overlay BBC-Life-birds-orchestral BGM.",
    "I'm sending you a 3-minute BBC-Life-reptiles clip — analyze it, add English captions, and add BBC-Life-reptiles-orchestral BGM.",
    "Uploading a 1-minute BBC-Dynasties-chimpanzees clip — please analyze it, add English subtitles, and overlay BBC-Dynasties-chimpanzees-orchestral BGM.",
    "Here's a 4-minute BBC-Dynasties-emperor-penguins clip — analyze it, add English captions, and add BBC-Dynasties-emperor-penguins-orchestral BGM.",
    "I have a 90-second BBC-Dynasties-tigers clip — please analyze it, add English subtitles, and overlay BBC-Dynasties-tigers-orchestral BGM.",
    "Uploading a 2-minute BBC-Seven-Worlds-Asia clip — analyze it, overlay English captions, and add BBC-Seven-Worlds-Asia-orchestral BGM.",
    "Here's a 90-second BBC-Seven-Worlds-South-America clip — analyze it, add English subtitles, and overlay BBC-Seven-Worlds-South-America-orchestral BGM.",
    "I'm sending you a 3-minute BBC-Seven-Worlds-Australia clip — analyze it, add English captions, and add BBC-Seven-Worlds-Australia-orchestral BGM.",
    "Uploading a 1-minute BBC-Our-Planet-Frozen-Worlds clip — please analyze it, add English subtitles, and overlay BBC-Our-Planet-Frozen-orchestral BGM.",
    "Here's a 4-minute BBC-Our-Planet-jungles clip — analyze it, add English captions, and add BBC-Our-Planet-jungles-orchestral BGM.",
    "I have a 90-second BBC-Our-Planet-coastal-seas clip — please analyze it, add English subtitles, and overlay BBC-Our-Planet-coastal-seas-orchestral BGM.",
    "Uploading a 2-minute BBC-Earthflight-Africa clip — analyze it, overlay English captions, and add BBC-Earthflight-Africa-orchestral BGM.",
    "Here's a 90-second BBC-Earthflight-North-America clip — analyze it, add English subtitles, and overlay BBC-Earthflight-North-America-orchestral BGM.",
    "I'm sending you a 3-minute Disneynature-African-Cats clip — analyze it, add English captions, and add Disneynature-African-Cats-orchestral BGM.",
    "Uploading a 1-minute Disneynature-Earth clip — please analyze it, add English subtitles, and overlay Disneynature-Earth-orchestral BGM.",
    "Here's a 4-minute Disneynature-Chimpanzee clip — analyze it, add English captions, and add Disneynature-Chimpanzee-orchestral BGM.",
    "I have a 90-second Disneynature-Born-in-China clip — please analyze it, add English subtitles, and overlay Disneynature-Born-in-China-orchestral BGM.",
    "Uploading a 2-minute Disneynature-Penguins clip — analyze it, overlay English captions, and add Disneynature-Penguins-orchestral BGM.",
    "Here's a 90-second Disneynature-Bears clip — analyze it, add English subtitles, and overlay Disneynature-Bears-orchestral BGM.",
    "I'm sending you a 3-minute Disneynature-Polar-Bear clip — analyze it, add English captions, and add Disneynature-Polar-Bear-orchestral BGM.",
    "Uploading a 1-minute Netflix-Tiny-Creatures clip — please analyze it, add English subtitles, and overlay Tiny-Creatures-orchestral BGM.",
    "Here's a 4-minute Netflix-Night-on-Earth clip — analyze it, add English captions, and add Night-on-Earth-orchestral BGM.",
    "I have a 90-second Netflix-Our-Great-National-Parks clip — please analyze it, add English subtitles, and overlay Our-Great-National-Parks-orchestral BGM.",
    "Uploading a 2-minute Netflix-Wild-Babies clip — analyze it, overlay English captions, and add Wild-Babies-orchestral BGM.",
    "Here's a 90-second Netflix-72-Cutest-Animals clip — analyze it, add English subtitles, and overlay 72-Cutest-Animals-orchestral BGM.",
    "I'm sending you a 3-minute National-Geographic-Hostile-Planet clip — analyze it, add English captions, and add Hostile-Planet-orchestral BGM.",
    "Uploading a 1-minute National-Geographic-One-Strange-Rock clip — please analyze it, add English subtitles, and overlay One-Strange-Rock-orchestral BGM.",
    "Here's a 4-minute National-Geographic-Wild-Yellowstone clip — analyze it, add English captions, and add Wild-Yellowstone-orchestral BGM.",
    "I have a 90-second National-Geographic-Mission-Galapagos clip — please analyze it, add English subtitles, and overlay Mission-Galapagos-orchestral BGM.",
    "Uploading a 2-minute Apple-TV-Tiny-World clip — analyze it, overlay English captions, and add Apple-TV-Tiny-World-orchestral BGM.",
    "Here's a 90-second Apple-TV-Earth-at-Night-in-Color clip — analyze it, add English subtitles, and overlay Earth-at-Night-in-Color-orchestral BGM.",
    "I'm sending you a 3-minute Apple-TV-Prehistoric-Planet clip — analyze it, add English captions, and add Prehistoric-Planet-orchestral BGM.",
    "Uploading a 1-minute Apple-TV-Big-Beasts clip — please analyze it, add English subtitles, and overlay Apple-TV-Big-Beasts-orchestral BGM.",
    "Here's a 4-minute IMAX-Galapagos clip — analyze it, add English captions, and add IMAX-Galapagos-orchestral BGM.",
    "I have a 90-second IMAX-Deep-Sea clip — please analyze it, add English subtitles, and overlay IMAX-Deep-Sea-orchestral BGM.",
    "Uploading a 2-minute IMAX-Born-to-Be-Wild clip — analyze it, overlay English captions, and add IMAX-Born-to-Be-Wild-orchestral BGM.",
    "Here's a 90-second IMAX-Pandas clip — analyze it, add English subtitles, and overlay IMAX-Pandas-orchestral BGM.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
