"""x15 style_subtitle SFT short briefs.

Chain: IntakeVideo → StyleTransfer → Transcription → Compositor.
Trigger: user uploads video + asks for style transfer + monolingual subtitle.
NO music, NO ambience, NO translation, NO extend.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 1-minute talking-head clip — please convert to anime style and add English subtitles.",
    "Here's a 90-second tutorial video — render in watercolor style and overlay English captions.",
    "I have a 2-minute interview clip — please style as oil painting and add English subtitles.",
    "Uploading a 45-second product demo — convert to cel-shaded style and overlay English captions.",
    "Here's a 1-minute lecture clip — please render as charcoal sketch and add English subtitles.",
    "I'm sending you a 30-second cooking tutorial — style as Studio Ghibli and overlay English captions.",
    "Uploading a 90-second yoga-instructor demo — please render as pencil sketch and add English subtitles.",
    "Here's a 2-minute history-explainer video — convert to vintage 1960s film and overlay English captions.",
    "I have a 1-minute self-help monologue — please style as a French Impressionist painting and add English subtitles.",
    "Uploading a 45-second TED-style talk — render as a 1950s Hollywood B&W film and overlay English captions.",
    "Here's a 2-minute philosophy lecture — please convert to a Japanese woodblock print and add English subtitles.",
    "I'm sending you a 30-second explainer video — style as cyberpunk anime and overlay English captions.",
    "Uploading a 1-minute makeup-tutorial — please render as Renaissance painting and add English subtitles.",
    "Here's a 45-second food-blogger clip — convert to vintage cookbook illustration and overlay English captions.",
    "I have a 90-second museum-curator tour — please style as Dutch Old-Master and add English subtitles.",
    "Uploading a 2-minute book-review monologue — render as Edwardian sepia photograph and overlay English captions.",
    "Here's a 1-minute meditation guide — please convert to Tibetan thangka and add English subtitles.",
    "I'm sending you a 30-second poetry reading — style as a German Expressionist film and overlay English captions.",
    "Uploading a 45-second startup pitch video — please render as Soviet Constructivist poster and add English subtitles.",
    "Here's a 2-minute educational explainer — convert to chalkboard hand-drawing and overlay English captions.",
    "I have a 1-minute corporate training video — please style as 1970s 16mm film and add English subtitles.",
    "Uploading a 90-second documentary segment — render as a 1940s newsreel and overlay English captions.",
    "Here's a 30-second history podcast clip — please convert to 1900s sepia film and add English subtitles.",
    "I'm sending you a 45-second museum-tour walkthrough — style as a Persian miniature painting and overlay English captions.",
    "Uploading a 1-minute science-explainer monologue — please render as a 1980s VHS aesthetic and add English subtitles.",
    "Here's a 2-minute philosophy-channel monologue — convert to a Victorian etching and overlay English captions.",
    "I have a 90-second motivational speech clip — please style as an Art Deco poster and add English subtitles.",
    "Uploading a 30-second author interview — render as Klimt's golden-portrait phase and overlay English captions.",
    "Here's a 1-minute celebrity-interview clip — please convert to anime cel-shading and add English subtitles.",
    "I'm sending you a 45-second fitness-instructor demo — style as a Pixar 3D animation and overlay English captions.",
    "Uploading a 2-minute classroom-recording clip — please render as 1990s Saturday-morning cartoon and add English subtitles.",
    "Here's a 90-second TED-talk excerpt — convert to a Wong-Kar-wai cinematic look and overlay English captions.",
    "I have a 30-second life-coach monologue — please style as a French Nouvelle-Vague film and add English subtitles.",
    "Uploading a 1-minute museum-docent tour — render as a Vermeer interior painting and overlay English captions.",
    "Here's a 45-second yoga-flow demo — please convert to a Bharatanatyam-style miniature and add English subtitles.",
    "I'm sending you a 2-minute career-coaching clip — style as a 1950s magazine illustration and overlay English captions.",
    "Uploading a 90-second podcast video — please render as a Bauhaus poster and add English subtitles.",
    "Here's a 1-minute science-news monologue — convert to a Studio Ghibli aesthetic and overlay English captions.",
    "I have a 30-second therapy-channel clip — please style as a watercolor children's-book and add English subtitles.",
    "Uploading a 45-second cooking-show monologue — render as a Norman Rockwell painting and overlay English captions.",
    "Here's a 2-minute tax-tips video — please convert to a 1960s Saul Bass-style title card and add English subtitles.",
    "I'm sending you a 1-minute gardening-tutorial — style as a William Morris wallpaper pattern and overlay English captions.",
    "Uploading a 90-second physics-explainer — please render as Caspar David Friedrich and add English subtitles.",
    "Here's a 30-second magic-trick reveal — convert to vintage 1900s magic-show poster and overlay English captions.",
    "I have a 45-second writers-workshop clip — please style as Edwardian etching and add English subtitles.",
    "Uploading a 2-minute language-tutor demo — render as Persian miniature illuminated manuscript and overlay English captions.",
    "Here's a 1-minute product-walkthrough video — please convert to Mid-century-modern advertising poster and add English subtitles.",
    "I'm sending you a 30-second VR-headset demo — style as a 1980s synthwave aesthetic and overlay English captions.",
    "Uploading a 45-second car-review clip — please render as a 1960s muscle-car magazine cover and add English subtitles.",
    "Here's a 90-second motorcycle-review video — convert to a chrome-and-leather 1950s aesthetic and overlay English captions.",
    "I have a 2-minute architectural-walkthrough — please style as a Frank Lloyd Wright drafting plate and add English subtitles.",
    "Uploading a 1-minute interior-design walkthrough — render as a Maison-Lassance illustration and overlay English captions.",
    "Here's a 30-second fashion-design pitch — please convert to an Art Nouveau Mucha poster and add English subtitles.",
    "I'm sending you a 45-second jewelry-design walkthrough — style as a Faberge enamel and overlay English captions.",
    "Uploading a 90-second perfume-launch video — please render as a 1930s Vogue magazine cover and add English subtitles.",
    "Here's a 1-minute corporate-CEO speech — convert to a 1960s newsreel film and overlay English captions.",
    "I have a 2-minute political-debate clip — please style as a Soviet Constructivist propaganda poster and add English subtitles.",
    "Uploading a 30-second gossip-talk-show monologue — render as a 1950s tabloid illustration and overlay English captions.",
    "Here's a 45-second magic-trick reveal — please convert to a vintage circus poster and add English subtitles.",
    "I'm sending you a 1-minute fortune-teller monologue — style as a 1920s tarot-deck illustration and overlay English captions.",
    "Uploading a 90-second escape-room walkthrough — please render as a vintage detective-novel cover and add English subtitles.",
    "Here's a 2-minute true-crime monologue — convert to a 1940s noir-film aesthetic and overlay English captions.",
    "I have a 1-minute documentary-history clip — please style as a 1900s daguerreotype and add English subtitles.",
    "Uploading a 30-second nature-documentary monologue — render as a Audubon ornithological illustration and overlay English captions.",
    "Here's a 45-second wildlife-tour walkthrough — please convert to a 1970s National Geographic photo essay and add English subtitles.",
    "I'm sending you a 2-minute cooking-show monologue — style as a 1950s diner advertisement and overlay English captions.",
    "Uploading a 1-minute baker-tutorial — please render as a vintage French patisserie poster and add English subtitles.",
    # ── more upload + style + subtitle requests (50) ──────────────────────
    "Uploading a 90-second gardener-tutorial — please convert to a Beatrix-Potter illustration and add English captions.",
    "Here's a 2-minute carpenter-tutorial — style as a vintage Popular-Mechanics plate and overlay English subtitles.",
    "I have a 1-minute knitter-tutorial — please render as a Granny-square mid-century kitsch poster and add English captions.",
    "Uploading a 30-second crocheter-tutorial — convert to a Norse-tapestry illustration and overlay English subtitles.",
    "Here's a 45-second weaver-tutorial — please style as a Navajo-rug pattern and add English captions.",
    "I'm sending you a 30-second tailor-tutorial — convert to a Persian-miniature gold-thread design and overlay English subtitles.",
    "Uploading a 1-minute jeweler-walkthrough — please render as a Faberge-enamel illustration and add English captions.",
    "Here's a 45-second clockmaker-walkthrough — style as a Vienna-watchmaker illustration and overlay English subtitles.",
    "I have a 30-second pottery-glazer-tutorial — please convert to a Greek-black-figure-vase painting and add English captions.",
    "Uploading a 1-minute glassblower-tutorial — render as a Murano-glass design illustration and overlay English subtitles.",
    "Here's a 30-second leather-tooler-tutorial — please style as a Renaissance-craftsman engraving and add English captions.",
    "I'm sending you a 45-second cobbler-tutorial — convert to a 1900s shoemaker illustration and overlay English subtitles.",
    "Uploading a 1-minute saddle-maker-tutorial — please render as a vintage Western leather-shop poster and add English captions.",
    "Here's a 30-second bow-maker-tutorial — style as a Native-American craft illustration and overlay English subtitles.",
    "I have a 45-second arrow-fletcher-tutorial — please convert to a Field-and-Stream vintage illustration and add English captions.",
    "Uploading a 1-minute fly-tier-tutorial — render as a vintage trout-fishing magazine plate and overlay English subtitles.",
    "Here's a 30-second fishing-knot tutorial — please style as a maritime nautical-knot guide and add English captions.",
    "I'm sending you a 45-second sailing-knot tutorial — convert to a 1900s sailor's-handbook illustration and overlay English subtitles.",
    "Uploading a 1-minute rope-splicer-tutorial — please render as a maritime guide illustration and add English captions.",
    "Here's a 30-second whittler-tutorial — style as a Boy-Scout-handbook illustration and overlay English subtitles.",
    "I have a 45-second carver-tutorial — please convert to a Pacific-Northwest tribal carving plate and add English captions.",
    "Uploading a 1-minute totem-pole-tutorial — render as a Pacific-Northwest tribal woodblock and overlay English subtitles.",
    "Here's a 30-second wood-burning-tutorial — please style as a Boy-Scout-craft illustration and add English captions.",
    "I'm sending you a 45-second linocut-tutorial — convert to a Berlin Bauhaus print and overlay English subtitles.",
    "Uploading a 1-minute screen-print-tutorial — please render as an Andy-Warhol Pop-Art poster and add English captions.",
    "Here's a 30-second risograph-tutorial — style as a 1980s zine illustration and overlay English subtitles.",
    "I have a 45-second letterpress-tutorial — please convert to a Gutenberg-printer illustration and add English captions.",
    "Uploading a 1-minute bookbinder-tutorial — render as a Renaissance book-binder illustration and overlay English subtitles.",
    "Here's a 30-second bookmark-maker-tutorial — please style as an illuminated manuscript and add English captions.",
    "I'm sending you a 45-second journal-maker-tutorial — convert to a Persian illuminated manuscript and overlay English subtitles.",
    "Uploading a 1-minute paper-marbler-tutorial — please render as a Turkish ebru-artisan illustration and add English captions.",
    "Here's a 30-second soap-carver-tutorial — style as a vintage carving-handbook plate and overlay English subtitles.",
    "I have a 45-second candle-maker-walkthrough — please convert to a vintage candle-maker poster and add English captions.",
    "Uploading a 1-minute soap-maker-walkthrough — render as a 1900s apothecary illustration and overlay English subtitles.",
    "Here's a 30-second perfume-blender-walkthrough — please style as a 1920s Vogue cover and add English captions.",
    "I'm sending you a 45-second wax-sealing-tutorial — convert to a Victorian-engineering plate and overlay English subtitles.",
    "Uploading a 1-minute calligrapher-walkthrough — please render as a Persian-miniature gold-leaf design and add English captions.",
    "Here's a 30-second feather-quill-pen tutorial — style as a Renaissance-era illuminated manuscript and overlay English subtitles.",
    "I have a 45-second mosaic-tutorial — please convert to a Byzantine-mosaic illustration and add English captions.",
    "Uploading a 1-minute fresco-painter walkthrough — render as a Pompeii-fresco style and overlay English subtitles.",
    "Here's a 30-second tempera-painter walkthrough — please style as an Andrew-Wyeth tempera-realist and add English captions.",
    "I'm sending you a 45-second egg-tempera tutorial — convert to a Sandro-Botticelli style and overlay English subtitles.",
    "Uploading a 1-minute lithograph-press tutorial — please render as a Toulouse-Lautrec poster and add English captions.",
    "Here's a 30-second etching tutorial — style as a Rembrandt-etching plate and overlay English subtitles.",
    "I have a 45-second drypoint-engraver tutorial — please convert to a Käthe-Kollwitz print and add English captions.",
    "Uploading a 1-minute woodcut tutorial — render as a Albrecht-Dürer woodcut and overlay English subtitles.",
    "Here's a 30-second silkscreen tutorial — please style as a Roy-Lichtenstein Pop-Art panel and add English captions.",
    "I'm sending you a 45-second monoprint tutorial — convert to a Mary-Cassatt monoprint plate and overlay English subtitles.",
    "Uploading a 1-minute aquatint tutorial — please render as a Goya-aquatint plate and add English captions.",
    "Here's a 30-second mezzotint tutorial — style as a Velázquez-mezzotint plate and overlay English subtitles.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
