"""x15 extend_subtitle SFT short briefs.

Chain: IntakeVideo → VideoExtend → Transcription → Compositor.
Trigger: user uploads video + extend longer + monolingual subtitles.
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 30-second talking-head clip — please extend to 90 seconds and add English subtitles.",
    "Here's a 45-second product-demo video — extend to 2 minutes and overlay English captions.",
    "I have a 1-minute lecture clip — please extend to 3 minutes and add English subtitles.",
    "Uploading a 30-second tutorial — extend to 90 seconds and overlay English captions.",
    "Here's a 45-second motivational speech — please extend to 2 minutes and add English subtitles.",
    "I'm sending you a 30-second cooking-tutorial — extend to 90 seconds and overlay English captions.",
    "Uploading a 1-minute fitness-instructor demo — please extend to 3 minutes and add English subtitles.",
    "Here's a 45-second meditation guide — extend to 2 minutes and overlay English captions.",
    "I have a 30-second author-interview clip — please extend to 90 seconds and add English subtitles.",
    "Uploading a 1-minute corporate-training video — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second yoga-flow demo — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second explainer — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute startup-pitch video — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second product-walkthrough — extend to 90 seconds and overlay English captions.",
    "I have a 45-second documentary segment — please extend to 2 minutes and add English subtitles.",
    "Uploading a 30-second podcast-clip — extend to 90 seconds and overlay English captions.",
    "Here's a 1-minute book-review — please extend to 3 minutes and add English subtitles.",
    "I'm sending you a 30-second history-lesson — extend to 90 seconds and overlay English captions.",
    "Uploading a 45-second philosophy-explainer — please extend to 2 minutes and add English subtitles.",
    "Here's a 1-minute psychology-tutorial — extend to 3 minutes and overlay English captions.",
    "I have a 30-second therapy-channel clip — please extend to 90 seconds and add English subtitles.",
    "Uploading a 45-second baking-tip video — extend to 2 minutes and overlay English captions.",
    "Here's a 1-minute coffee-brewing tutorial — please extend to 3 minutes and add English subtitles.",
    "I'm sending you a 30-second art-tutorial — extend to 90 seconds and overlay English captions.",
    "Uploading a 45-second science-explainer — please extend to 2 minutes and add English subtitles.",
    "Here's a 1-minute travel-vlog segment — extend to 3 minutes and overlay English captions.",
    "I have a 30-second pet-care tip clip — please extend to 90 seconds and add English subtitles.",
    "Uploading a 45-second gardening-tip — extend to 2 minutes and overlay English captions.",
    "Here's a 1-minute home-repair tutorial — please extend to 3 minutes and add English subtitles.",
    "I'm sending you a 30-second car-maintenance tip — extend to 90 seconds and overlay English captions.",
    "Uploading a 45-second tech-news commentary — please extend to 2 minutes and add English subtitles.",
    "Here's a 1-minute investment-advice video — extend to 3 minutes and overlay English captions.",
    "I have a 30-second tax-tip clip — please extend to 90 seconds and add English subtitles.",
    "Uploading a 45-second life-coaching video — extend to 2 minutes and overlay English captions.",
    "Here's a 1-minute parenting-advice video — please extend to 3 minutes and add English subtitles.",
    "I'm sending you a 30-second poetry-reading — extend to 90 seconds and overlay English captions.",
    "Uploading a 45-second science-news explainer — please extend to 2 minutes and add English subtitles.",
    "Here's a 1-minute language-tutor video — extend to 3 minutes and overlay English captions.",
    "I have a 30-second photography-tip clip — please extend to 90 seconds and add English subtitles.",
    "Uploading a 45-second crafting-tutorial — extend to 2 minutes and overlay English captions.",
    "Here's a 1-minute knitting-lesson — please extend to 3 minutes and add English subtitles.",
    "I'm sending you a 30-second jewelry-design tutorial — extend to 90 seconds and overlay English captions.",
    "Uploading a 45-second sourdough-bread tutorial — please extend to 2 minutes and add English subtitles.",
    "Here's a 1-minute pottery-throwing demo — extend to 3 minutes and overlay English captions.",
    "I have a 30-second watercolor tutorial — please extend to 90 seconds and add English subtitles.",
    "Uploading a 45-second calligraphy lesson — extend to 2 minutes and overlay English captions.",
    "Here's a 1-minute oil-painting tutorial — please extend to 3 minutes and add English subtitles.",
    "I'm sending you a 30-second chess-strategy clip — extend to 90 seconds and overlay English captions.",
    "Uploading a 45-second guitar-lesson — please extend to 2 minutes and add English subtitles.",
    "Here's a 1-minute piano-lesson — extend to 3 minutes and overlay English captions.",
    # ── more upload + extend + subtitle requests (50) ─────────────────────
    "Uploading a 30-second drum-lesson — please extend to 90 seconds and add English subtitles.",
    "Here's a 45-second violin-lesson — extend to 2 minutes and overlay English captions.",
    "I have a 1-minute flute-lesson — please extend to 3 minutes and add English subtitles.",
    "Uploading a 30-second cello-lesson — extend to 90 seconds and overlay English captions.",
    "Here's a 45-second harp-lesson — please extend to 2 minutes and add English subtitles.",
    "I'm sending you a 30-second oboe-lesson — extend to 90 seconds and overlay English captions.",
    "Uploading a 1-minute organ-lesson — please extend to 3 minutes and add English subtitles.",
    "Here's a 45-second double-bass lesson — extend to 2 minutes and overlay English captions.",
    "I have a 30-second timpani lesson — please extend to 90 seconds and add English subtitles.",
    "Uploading a 1-minute marimba lesson — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second djembe lesson — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second tabla lesson — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute sitar lesson — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second guzheng lesson — extend to 90 seconds and overlay English captions.",
    "I have a 45-second pipa lesson — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute erhu lesson — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second shamisen lesson — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second koto lesson — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute shakuhachi lesson — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second bansuri lesson — extend to 90 seconds and overlay English captions.",
    "I have a 45-second berimbau lesson — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute kora lesson — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second balafon lesson — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second mbira lesson — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute kalimba lesson — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second darbuka lesson — extend to 90 seconds and overlay English captions.",
    "I have a 45-second oud lesson — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute saz lesson — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second baglama lesson — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second bouzouki lesson — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute mandolin lesson — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second lute lesson — extend to 90 seconds and overlay English captions.",
    "I have a 45-second harpsichord lesson — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute clavichord lesson — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second viol-da-gamba lesson — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second psaltery lesson — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute hurdy-gurdy lesson — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second nyckelharpa lesson — extend to 90 seconds and overlay English captions.",
    "I have a 45-second hardanger-fiddle lesson — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute kantele lesson — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second balalaika lesson — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second domra lesson — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute bandura lesson — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second cimbalom lesson — extend to 90 seconds and overlay English captions.",
    "I have a 45-second tarogato lesson — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute zither lesson — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second accordion lesson — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second concertina lesson — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute melodica lesson — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second harmonica lesson — extend to 90 seconds and overlay English captions.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
