"""GRPO shape: story_ambience long-story (10 samples)."""
from __future__ import annotations


def _make(topic, art_style, descriptor, ambience):
    return {
        "rationale": (
            f"{topic} from a user-provided story + {art_style} illustrations + "
            f"slideshow narration with {ambience} ambient bed."
        ),
        "intents": [
            f"Write the narration script from the user's supplied {descriptor}.",
            f"Generate one {art_style} illustration per scene of the {descriptor}.",
            f"Produce a measured TTS narrator track for the {descriptor}.",
            f"Generate the {ambience} ambient atmosphere as the audio bed.",
            f"Layer the {ambience} ambient bed under the narrator track into one final mixed wav.",
            f"Compose the final slideshow pairing {art_style} illustrations with mixed narrator-and-ambience audio.",
        ],
    }


SAMPLES: list[dict] = [
    {**_make("Forest-rabbit bedtime tale", "soft watercolor", "forest-rabbit bedtime tale", "soft forest-night"),
     "user_goal": "Here's my story I want to process — soft watercolor please, with a soft forest-night ambient bed: There once was a small brown rabbit named Pip who lived in a meadow at the edge of a sleeping forest. One evening Pip found a glowing seed. He carried it home through the long grass and planted it on his doorstep. By morning the seed had grown into a single white flower with a tiny voice that thanked him for finding it. Pip and the flower became great friends. Every spring after that, the meadow filled with one hundred glowing white flowers, and the forest creatures came at night to listen to the flowers sing soft songs to one another. Pip grew old surrounded by their light. He never traveled far from the meadow, because he had everything he needed at home. The flowers, when Pip finally went to sleep for the last time, sang for him through that whole long night, so that he would not be alone."},
    {**_make("Tide-pool starfish storytime", "watercolor", "tide-pool starfish storytime", "gentle ocean-shore"),
     "user_goal": "Here's my story I want to process — watercolor please, with a gentle ocean-shore ambient bed: A small purple starfish named Tess lived in a rocky tide pool with her many siblings and one very old uncle who had once seen a whale. Tess wanted to see a whale too. She crawled, very slowly, from her tide pool toward the open sea. The journey took her three full tides. She passed an octopus who told her she would not survive the open sea. She passed a hermit crab who told her she should turn around. On the third tide she finally reached the edge of the rocks. The whale was there, far out, exhaling a great spout of mist. Tess watched until her arms grew tired. She crawled back to her tide pool. She told her uncle. He smiled. He had been waiting for her to return."},
    {**_make("Andean condor-mother storytime", "Inca-textile", "Andean condor-mother storytime", "high-Andean-wind"),
     "user_goal": "Here's my story I want to process — Inca-textile please, with a high-Andean-wind ambient bed: High in the Andean cordillera, a great condor-mother had built her nest on a cliff that overlooked seven valleys. Her single chick had been born thin and weak. The mother flew further than she had ever flown to find food. She flew over llama herds and over sleeping mountains and over villages where the children watched her shadow pass. She brought back more than she could carry. The chick grew strong. The chick fledged after many seasons of patient feeding. On the morning the chick made his first long flight, the mother circled with him over the seven valleys. She did not lead him; she let him choose where to go. He chose to circle back to the nest. They returned to the nest together. The mother knew, then, that she had raised him well."},
    {**_make("Arctic-fox kit's first winter", "soft pastel", "Arctic-fox kit's first winter", "Arctic-wind"),
     "user_goal": "Here's my story I want to process — soft pastel please, with an Arctic-wind ambient bed: A young Arctic fox named Nuka lost her mother in her first autumn. She did not understand at first that her mother was not coming back. She slept in their old burrow alone. The first winter came hard. Nuka had to learn to listen for lemmings beneath the snow without her mother's guidance. She learned slowly. She was hungry many days. One night she met an old fox, white-furred and tired, who showed her where the wind always brought lemmings up to the surface. Nuka watched and listened. The old fox taught her without speaking, just by the way he tilted his head. By spring Nuka had grown into her thick winter coat and was no longer hungry. The old fox had passed in the long cold. Nuka, when her own kits were born the next year, taught them in the same silent way."},
    {**_make("Amazon jaguar-cub story", "tropical watercolor", "Amazon jaguar-cub story", "tropical-rainforest-bird-and-insect"),
     "user_goal": "Here's my story I want to process — tropical watercolor please, with a tropical-rainforest-bird-and-insect ambient bed: A young Amazon jaguar named Ipy was learning to hunt with her mother. The first time she missed a capybara her mother did not scold her, but she did not bring her home either. She made Ipy try again. The second time Ipy succeeded. She brought the capybara home. Her mother taught her how to share, how to eat the best parts last, how to bury the rest for tomorrow. The lessons took the entire wet season. By the dry season Ipy was hunting alone. She returned to her mother every evening to sleep beside her in the canopy. One morning her mother was not there. Ipy waited two days. Her mother had left to find a new mate. Ipy understood. She moved her own territory east, where the river bent through old trees, and she lived there by herself for many years."},
    {**_make("Highland-lake selkie tale", "Celtic-knot watercolor", "Highland-lake selkie tale", "Highland-lake-shore"),
     "user_goal": "Here's my story I want to process — Celtic-knot watercolor please, with a Highland-lake-shore ambient bed: A young woman named Ailish lived alone by a Highland lake after her family had all died of fever. One summer evening she went down to the shore and saw a sealskin folded on a rock. She picked it up. She knew the legends. She knew it was a selkie's. She put it in her cottage and waited. The selkie came at midnight, as a young woman with sad eyes. Ailish did not hide the skin. She handed it back. The selkie wept. She thanked Ailish and gave her, in return, a small white pebble. The selkie returned to the lake and was gone. Ailish kept the pebble her whole life. Whenever she was lonely she would take it down to the water and hold it. Sometimes, on certain nights, the selkie would come back to talk with her, just to talk. Ailish was never lonely again."},
    {**_make("Mongolian foal-and-mother story", "Mongolian-folk-art", "Mongolian foal-and-mother story", "open-steppe-wind"),
     "user_goal": "Here's my story I want to process — Mongolian-folk-art please, with an open-steppe-wind ambient bed: On the open steppe a mare named Zoloo gave birth to a small black foal at the very start of spring. The foal was the smallest of his cohort. The other foals teased him. Zoloo did not let them harm him, but she did not coddle him either. She let him follow her on the long migrations. She let him struggle through the rivers. She let him learn the wind by walking into it. By the autumn the small black foal had grown taller than his cohort. He had stronger lungs. He was the fastest of all the colts in the herd. The next spring he led the foals of the year through their first migration alongside Zoloo. The herders said: Zoloo did not protect him. She prepared him. The herders carved his shape into a small wooden charm and gave it to a child whose mother had also been busy preparing her."},
    {**_make("Coral-reef clownfish-family story", "underwater watercolor", "coral-reef clownfish-family story", "underwater-reef"),
     "user_goal": "Here's my story I want to process — underwater watercolor please, with an underwater-reef ambient bed: A clownfish named Suri lived among the tendrils of an anemone on a coral reef in the Sulu Sea. She had three brothers and a sister. The reef was their whole world. One morning a storm raged on the surface and the reef shook. The anemone they lived in was knocked loose. Suri's family scattered. Suri found her sister wedged behind a piece of coral. They waited together for the storm to pass. The current carried other reef creatures past them — angelfish, parrotfish, a single bewildered turtle. After three days the storm cleared. Suri and her sister found their family. The anemone had reattached itself to a different coral. They moved in. The reef went on. Suri later told her own children, when she had any, the story of the storm and the kindness of an anemone that had let them come home."},
    {**_make("Tibetan-monastery cat tale", "Tibetan-thangka", "Tibetan-monastery cat tale", "monastery-bell-and-mountain-wind"),
     "user_goal": "Here's my story I want to process — Tibetan-thangka please, with a monastery-bell-and-mountain-wind ambient bed: A small cat named Ozer lived at a Tibetan-mountain monastery and watched the monks chant from the rafters. She was not anyone's cat in particular. She slept where she was warm and ate where she was given food. One winter the youngest monk fell ill with a fever. The senior monks tried what medicines they had. They did not work. The fever lasted nine nights. Ozer slept on the young monk's chest every one of those nights. The senior monks did not chase her off, even though they should have, because they were trying to keep him quiet. On the tenth morning the fever broke. The young monk woke up. Ozer climbed off his chest and went to find her breakfast. The young monk lived to be very old. He told the cat story to anyone who asked, and to many who did not. The cat was a small one. The story was a long one."},
    {**_make("Norse-fjord salmon-leap story", "Bilibin-style", "Norse-fjord salmon-leap story", "fjord-water-and-distant-bird"),
     "user_goal": "Here's my story I want to process — Bilibin-style please, with a fjord-water-and-distant-bird ambient bed: A young salmon named Skarn was born in a small stream that fed a Norse fjord. She lived in fresh water for two years, learned to hunt smaller fish, and then made the long swim out to the open sea. She lived in the sea for four years. She traveled across the cold currents of the North Atlantic. She returned, when she was strong enough, to the fjord she had been born in. She remembered it by the taste of the water. She climbed her stream. The waterfall halfway up was the hardest. She tried to leap it. She fell back. She tried again. She fell back. On the seventh try she made it. She found the small pool where she had hatched. She laid her eggs. Then she let go. The current carried her gently down the stream. The young, in their season, would come up the same way. The fjord, the storyteller says, has been doing this for ten thousand years."},
]
