"""GRPO shape: cr_music — long-story variant (10 samples).

Companion to shape_cr_music.py. Each user_goal starts with "Here's my
story I want to process: " followed by an original ~200-word story plus
a music-style modifier. Same chain: Story → Screenplay → KeyFrame →
Video → Music → AudioMix → Compositor.
"""
from __future__ import annotations


_REJECT = (
    "Reject AmbienceAgent, Transcription/Translation, VideoAnalysis/IntakeVideo/"
    "StyleTransfer/VideoExtend/Highlight, Narration/Illustration/Narrator."
)


def _make(theme, arc, scenes, settings, aesthetic, bgm, score):
    return {
        "rationale": (
            f"{theme} mini-drama from a user-provided novella + {bgm} BGM. StoryAgent "
            f"drafts the {arc} blueprint from the supplied story. ScreenplayAgent breaks "
            f"it into {scenes} scenes. KeyFrameAgent plans keyframes for the {settings} "
            "settings from text alone. VideoAgent assembles the multi-shot film. "
            f"MusicAgent composes the {score} score. AudioMixAgent layers it under the "
            "dialogue+foley. CompositorAgent muxes the final mp4. " + _REJECT
        ),
        "intents": [
            f"Draft the {theme} story blueprint — {arc} arc — from the user's supplied novella.",
            f"Decompose the {arc} arc into {scenes} scenes.",
            f"Plan keyframes for the {settings} settings; text-only generation, no reference images supplied.",
            f"Render per-shot clips preserving {aesthetic} visual continuity.",
            f"Compose the {bgm} BGM the user requested, matching the {aesthetic} register.",
            f"Layer the {bgm} BGM under the clip's baked dialogue+foley track into one final mixed wav.",
            f"Composite the final {aesthetic} mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    }


SAMPLES: list[dict] = [
    {**_make("Cultivation-fantasy bloodline-awakening", "young-disciple / awakening / sect-trial",
             "cultivation-bloodline awakening", "sect mountain / underground cave / trial peak",
             "cultivation-bloodline awakening", "epic erhu-and-percussion", "epic erhu-and-percussion"),
     "user_goal": "Here's my story I want to process — set it to epic erhu-and-percussion BGM: Bai Lan was the lowest disciple of the Cloud-Threaded Sect when the dormant bloodline her mother had hidden from her woke up in the middle of evening cultivation practice. The other disciples felt the pressure first as wind, then as something they did not understand. The senior watching the practice ordered Bai Lan to leave the hall. She left, walked to the master's pavilion, and asked to be expelled. The master refused. He said: the bloodline is not yours to refuse. He gave her seven days to consider whether to continue or to depart. Bai Lan spent four of them sitting on a cliff above the southern forest. On the fifth day she walked back into the hall and resumed practice. On the sixth day a fellow disciple challenged her in the courtyard. She did not fight him; she let the bloodline answer for her. He was unhurt. He understood. On the seventh day the master told her: you have decided. The trial peak is yours next month if you want it. She wanted it. She passed."},
    {**_make("CEO-romance contemporary", "waitress / billionaire-regular / years-later recognition",
             "CEO-romance", "café / boardroom / private-rooftop reveal",
             "CEO-romance", "gentle piano BGM", "gentle piano"),
     "user_goal": "Here's my story I want to process — set it to gentle piano BGM: Chen Yueyao had served the rude regular at table six for nine months before she figured out who he was, and by then she had already cut him off twice for being rude to other customers. He had paid each time and come back the next morning. He never tipped. She did not know that he had been the boy she had pulled out of a flooded subway tunnel when she was sixteen and he was eleven. He had grown up. She had not noticed. On the morning he came in for the last time before flying back to Shanghai he asked her if she remembered the floods. She did. He told her his name. She had pulled fourteen children out that day. She had only asked one of them his name. It had been him. He invited her to dinner. She accepted on one condition — that the dinner be held in the same café, after closing, with no audience and no executive table. He came back that night. He brought no security. They talked until three in the morning. He did not propose. They corresponded for two years."},
    {**_make("Time-loop second-chance romance", "thirty-four-year-old / pushed off subway platform / time-rewind moment",
             "time-loop second-chance", "subway platform / hospital corridor / coffee shop reunion",
             "time-loop second-chance", "ambient piano-and-strings", "ambient piano-and-strings"),
     "user_goal": "Here's my story I want to process — set it to ambient piano-and-strings BGM: Ingrid Lin died the first time on a Tuesday afternoon at thirty-four, pushed from a subway platform by a man she did not see. She woke up in the same Tuesday morning at six thirteen. The push happened again. She woke up again. By the eighth Tuesday she had memorized the man — pale jacket, dropped phone — and the platform. By the eleventh she had stopped him from being on the platform at all. She had not, however, stopped the larger thing — whatever the loop was telling her she had to fix. On the fourteenth Tuesday she walked into the coffee shop two blocks from the platform and saw, sitting at the back booth, the boyfriend who had left her three years earlier and whom she had not seen since. He looked up. He did not seem surprised to see her. He said: do you remember the floods. She did. He had been the friend who had walked her home through the rising water. She sat down. They talked all afternoon. The next day was Wednesday."},
    {**_make("Underdog-comeback son-in-law conglomerate", "thrown-out son-in-law / hidden-conglomerate-heir / family-clash reveal",
             "underdog-comeback", "rich-family villa / hidden-conglomerate boardroom / final family banquet",
             "underdog-comeback", "uplifting orchestral", "uplifting orchestral"),
     "user_goal": "Here's my story I want to process — set it to uplifting orchestral BGM: Joseph Lin had married into the Park family eleven years before they threw him out for being unable to provide for their daughter, and he had walked out of the gate with the same coat he had walked in with. What the Park family did not know — what Joseph had not told his own wife — was that he was the heir to the second-largest agricultural conglomerate in Korea, and he had been quietly running it from a coffee shop in their town since the year after the wedding. He had hidden the company because he had wanted to be loved for himself. The Park family discovered this when their own business was acquired by Joseph's company in a hostile move that Joseph had not even initiated. The board of his company had simply done what they always did. The Park family invited Joseph back for a banquet that evening. He went. His wife sat across from him. He told her, in front of her parents, that he had not engineered the acquisition; he had not wanted to. She believed him. She left her parents' house with him that night. They did not return."},
    {**_make("Workplace-revenge corporate-thriller", "overlooked-analyst / boss's-insider-trading / rival-firm CEO rise",
             "workplace-revenge", "corporate office / SEC tip-line / rival-firm CEO chair",
             "workplace-revenge", "tense thriller BGM", "tense thriller"),
     "user_goal": "Here's my story I want to process — set it to tense thriller BGM: Annika Voss had been overlooked at Quantitative Capital for eight years and on the ninth she discovered that her boss had been insider-trading on the same M&A pipeline she had been building. Annika did not confront him. She did not report him to compliance. She copied the records to a personal drive, walked them across the street to a rival firm's recruiter, and accepted a position there at three times her current salary. From the rival firm's CEO seat — which she earned six years later — she filed the SEC tip that ended her old boss's career. She testified at his trial without ever raising her voice. The judge asked her, on the stand, why she had not simply reported him at the time. Annika said: because no one would have listened to me. The judge had no follow-up question. Annika returned to her firm that afternoon and chaired the board meeting that approved the company's most ambitious acquisition. Her old boss watched her on the news from prison."},
    {**_make("Adaora corporate-empowerment", "African-American senior partner / glass-ceiling / equity-line crossing",
             "corporate-empowerment", "law-firm boardroom / managing-partner's office / equity-firm celebration",
             "corporate-empowerment", "uplifting strings-and-piano", "uplifting strings-and-piano"),
     "user_goal": "Here's my story I want to process — set it to uplifting strings-and-piano BGM: Adaora Okonkwo had spent nine years being the smartest person in every conference room at Pierson & Hale, and on the day they passed her over for partner the third time, she resigned. The managing partner asked her to reconsider. She did not. The managing partner asked her, off the record, what would change her mind. Adaora said: nothing you can offer. She started her own firm with two associates the next month. The associates were both Black women whom Pierson & Hale had also passed over. Within two years Adaora's firm had taken three of Pierson & Hale's largest clients, including the one whose lead counsel had been her direct competitor for the partner seat. The competitor called Adaora six months after the loss and asked her, openly, whether the firm was hiring. Adaora hired her. Three years later Adaora's firm became the first majority-Black-owned firm to be admitted to the AmLaw 100. The managing partner of Pierson & Hale sent her flowers. She did not send a thank-you note."},
    {**_make("Cultivation-fantasy young-master Xue Yan", "young-master / pure-cultivator-body / sect-betrayal vendetta",
             "cultivation young-master", "sect courtyard / poisoned spring / mountain duel platform",
             "cultivation young-master", "epic guzheng-and-percussion", "epic guzheng-and-percussion"),
     "user_goal": "Here's my story I want to process — set it to epic guzheng-and-percussion BGM: Young Master Xue Yan was born with a cultivator's body — slender, clear-eyed, impossible to corrupt — and the elders of the Mountain-Cloud Sect had raised him for sixteen years to be the next sect heir. He did not become the heir. The night before the inheritance ceremony his half-brother poisoned the spring that fed the sect's cultivation pavilions, and although Xue Yan survived, three of his closest classmates did not. The half-brother fled. The elders held the inheritance ceremony anyway, and named the half-brother's mother as guardian-regent. Xue Yan did not contest the decision in the hall. He left the sect that night carrying only his sword. For the next six years he was reported as a wandering cultivator. He was not wandering. He was tracking his half-brother across seven provinces, building a single-strike technique that no extant master taught. He found his half-brother on a mountain platform in the seventh year. The fight took less than nine breaths. Xue Yan returned to the sect, deposed the regent, refused the inheritance, and walked back into the wilderness."},
    {**_make("Royal-bloodline awakening fantasy-prince", "forgotten-prince / village raised / kingdom restoration",
             "royal-bloodline-awakening", "hidden village / royal archive / coronation throne",
             "royal-bloodline-awakening", "sweeping orchestral", "sweeping orchestral"),
     "user_goal": "Here's my story I want to process — set it to sweeping orchestral BGM: Aldric had been raised in a village so far from the capital that he had never seen a royal coin until the day a stranger handed him one and asked him to look at the face on the tail side. The face was his. He was nineteen. The stranger was a court historian who had been searching for him for fourteen years. The boy-king Aldric's uncle had crowned in his stead — claiming the rightful prince had died in the same fire that had killed the queen — was now a tyrant whose tax decrees had begun to push villages into rebellion. The historian asked Aldric whether he wanted to walk with him to the capital and reclaim what was his. Aldric did not answer for two days. On the third day he handed his apprentice's tools to the smith who had raised him and walked. The journey was eight weeks. He met the loyalists. He met the rebellion. He met his uncle face-to-face in the throne room. He did not draw a sword. He spoke. The uncle listened, then knelt. The kingdom recognized Aldric. He ruled for forty-one years."},
    {**_make("Mecha-military squadron-loss", "rookie-pilot / debut-mission / solo-defense after squadron-loss",
             "mecha-military", "mecha-hangar / battlefield ridge / final-defense valley",
             "mecha-military", "brassy military fanfare", "brassy military fanfare"),
     "user_goal": "Here's my story I want to process — set it to brassy military fanfare BGM: Pilot Tomoko Saitō was nineteen the first time she launched her unit's lightest mecha into combat, and she was nineteen and a half by the time the mission was over. Her squadron had been ambushed at the southern ridge. Within seven minutes the squadron leader was dead, the second-in-command's mecha was burning, and the four other pilots had been pinned in a valley they could not climb out of. Tomoko was the highest unit on the ridge. She had two engagement options: retreat to base and report, or descend into the valley and screen the survivors' withdrawal alone. The rules of engagement said retreat. She descended. She held the valley mouth for forty-three minutes against three enemy heavies, two of which she destroyed and one of which she damaged badly enough to force its pilot to break engagement. The four surviving pilots withdrew through her position. The last one out — a sergeant who had been her instructor — sent her a single radio message: thank you. Tomoko did not retreat after they cleared. She was rescued from her cockpit forty hours later by a recovery team who had assumed she was dead. She returned to duty in three months."},
    {**_make("CIA Berlin-extraction mole", "junior-analyst / Berlin-op / mole-reveal at extraction",
             "CIA Berlin-extraction", "CIA war-room / Berlin alley / mole-confrontation safehouse",
             "CIA Berlin-extraction", "pulsing electronic-thriller", "electronic-thriller"),
     "user_goal": "Here's my story I want to process — set it to pulsing electronic-thriller BGM: Junior Analyst Catherine Reyes was twenty-eight when she ran her first Berlin extraction, and she was twenty-eight and one day when she figured out the mole was someone in her own task force. The asset had been compromised before her plane landed; she could see that the moment she walked into the safehouse and the asset's wife asked her, in unprompted English, who the new American was. The mole had been feeding the wife — and through her, the local Stasi remnants — every detail of the operation. Catherine spent the next four hours pretending to run the extraction by the original plan while she set up an alternative through a tunnel she had walked alone the previous night. She extracted the asset through the tunnel at three in the morning. She left a falsified extraction-completion message in the safehouse for the mole to find. The mole walked into the trap she had set in the second safehouse — the one the original plan called for — at four-thirty. It was the unit chief. Catherine had suspected him for forty-eight hours. She arrested him herself with the Berlin station's deputy as witness, and flew home."},
]
