"""Shape: intake_img_cr_extend —
    IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor.

Image-referenced mini-drama, extended beyond default duration, no audio overlay. (Path B alignment with v3 eval — opt-in audio: chain has Music/Ambience/AudioMix iff user_goal explicitly mentions audio.)
"""
from __future__ import annotations

SAMPLES: list[dict] = [
    {
        "user_goal": ".",
        "rationale": "Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded K-pop-idol portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the K-pop-idol portrait reference image's descriptive content.",
            "Draft the Extended K-pop drama story blueprint — backup-dancer Seoul-substitution full-arc arc — anchored to the K-pop-idol portrait reference, scoped for extended runtime.",
            "Decompose the backup-dancer Seoul-substitution full-arc arc into K-pop industry scenes.",
            "Plan keyframes for the studio / backstage / Seoul stadium / aftermath settings, depicting the K-pop-idol portrait reference.",
            "Render per-shot clips preserving K-pop industry visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended K-pop industry mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a martial-arts-costume portrait — produce an extended wuxia mini-drama where she avenges her master with a full-arc vendetta.",
        "rationale": "Extended wuxia revenge mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded young-disciple portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the young-disciple portrait reference image's descriptive content.",
            "Draft the Extended wuxia revenge story blueprint — junior-disciple sect-betrayal full-vendetta arc — anchored to the young-disciple portrait reference, scoped for extended runtime.",
            "Decompose the junior-disciple sect-betrayal full-vendetta arc into wuxia revenge scenes.",
            "Plan keyframes for the ancient temple / bamboo forest / mountain duel / aftermath rite settings, depicting the young-disciple portrait reference.",
            "Render per-shot clips preserving wuxia revenge visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended wuxia revenge mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's an astronaut-suit portrait — make an extended sci-fi mini-drama where she's a junior officer leading mutiny defense and the rebuild after.",
        "rationale": "Extended sci-fi mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded astronaut portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the astronaut portrait reference image's descriptive content.",
            "Draft the Extended sci-fi story blueprint — junior-officer mutiny full-rebuild arc — anchored to the astronaut portrait reference, scoped for extended runtime.",
            "Decompose the junior-officer mutiny full-rebuild arc into sci-fi space-station scenes.",
            "Plan keyframes for the crew quarters / engineering / command bridge / aftermath rebuild settings, depicting the astronaut portrait reference.",
            "Render per-shot clips preserving sci-fi space-station visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended sci-fi space-station mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a cyberpunk-costume portrait — produce an extended cyberpunk mini-drama where she's a hacker through a multi-night chase to sanctuary.",
        "rationale": "Extended cyberpunk mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded cyberpunk-portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the cyberpunk-portrait reference image's descriptive content.",
            "Draft the Extended cyberpunk story blueprint — hacker-fugitive cyber-samurai full-arc arc — anchored to the cyberpunk-portrait reference, scoped for extended runtime.",
            "Decompose the hacker-fugitive cyber-samurai full-arc arc into cyberpunk scenes.",
            "Plan keyframes for the neon street / rooftop chase / underground arena / sanctuary settings, depicting the cyberpunk-portrait reference.",
            "Render per-shot clips preserving cyberpunk visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended cyberpunk mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's an armor portrait — make an extended medieval mini-drama covering the full multi-day siege defense.",
        "rationale": "Extended medieval-castle siege mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded knight portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the knight portrait reference image's descriptive content.",
            "Draft the Extended medieval-castle siege story blueprint — young-castellan full-siege defense arc — anchored to the knight portrait reference, scoped for extended runtime.",
            "Decompose the young-castellan full-siege defense arc into medieval-castle siege scenes.",
            "Plan keyframes for the outer wall / breach / inner keep / aftermath settings, depicting the knight portrait reference.",
            "Render per-shot clips preserving medieval-castle siege visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended medieval-castle siege mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a Western-costume portrait — produce an extended Wild-West mini-drama covering the full investigation and showdown.",
        "rationale": "Extended Wild-West mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Western-cowboy portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Western-cowboy portrait reference image's descriptive content.",
            "Draft the Extended Wild-West story blueprint — young-marshal full-investigation showdown arc — anchored to the Western-cowboy portrait reference, scoped for extended runtime.",
            "Decompose the young-marshal full-investigation showdown arc into Western shootout scenes.",
            "Plan keyframes for the frontier town / sheriff's office / saloon / aftermath settings, depicting the Western-cowboy portrait reference.",
            "Render per-shot clips preserving Wild-West shootout visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Wild-West shootout mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a Victorian-portrait — make an extended Victorian-London mini-drama covering the full case from clue to inquiry.",
        "rationale": "Extended Victorian-London murder mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Victorian-detective portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Victorian-detective portrait reference image's descriptive content.",
            "Draft the Extended Victorian-London murder story blueprint — young-inspector full-pursuit confrontation arc — anchored to the Victorian-detective portrait reference, scoped for extended runtime.",
            "Decompose the young-inspector full-pursuit confrontation arc into Victorian-London scenes.",
            "Plan keyframes for the gas-lit street / Scotland-Yard / fog dock / aftermath inquiry settings, depicting the Victorian-detective portrait reference.",
            "Render per-shot clips preserving Victorian-London murder visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Victorian-London murder mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a young-naval-officer portrait — produce an extended Cold-War submarine mini-drama covering the full patrol.",
        "rationale": "Extended Cold-War submarine mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded submarine-officer portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the submarine-officer portrait reference image's descriptive content.",
            "Draft the Extended Cold-War submarine story blueprint — young-XO full-patrol survival arc — anchored to the submarine-officer portrait reference, scoped for extended runtime.",
            "Decompose the young-XO full-patrol survival arc into Cold-War submarine scenes.",
            "Plan keyframes for the control room / silent-running / sea-floor / port return settings, depicting the submarine-officer portrait reference.",
            "Render per-shot clips preserving Cold-War submarine visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Cold-War submarine mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a Highland-dress portrait — make an extended Highland-uprising mini-drama covering the full 1745 arc through Culloden.",
        "rationale": "Extended Highland uprising mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Highland-warrior portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Highland-warrior portrait reference image's descriptive content.",
            "Draft the Extended Highland uprising story blueprint — young-clan-warrior full-1745-arc arc — anchored to the Highland-warrior portrait reference, scoped for extended runtime.",
            "Decompose the young-clan-warrior full-1745-arc arc into Highland-Scottish uprising scenes.",
            "Plan keyframes for the Highland village / rebel rally / Culloden moor / aftermath retreat settings, depicting the Highland-warrior portrait reference.",
            "Render per-shot clips preserving Highland uprising visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Highland uprising mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a gladiator-costume portrait — produce an extended Roman-gladiator mini-drama covering the full Colosseum arc.",
        "rationale": "Extended Roman gladiator mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded gladiator portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the gladiator portrait reference image's descriptive content.",
            "Draft the Extended Roman gladiator story blueprint — slave-gladiator full-Colosseum-arc arc — anchored to the gladiator portrait reference, scoped for extended runtime.",
            "Decompose the slave-gladiator full-Colosseum-arc arc into Roman gladiator scenes.",
            "Plan keyframes for the ludus / hypogeum / arena / aftermath manumission settings, depicting the gladiator portrait reference.",
            "Render per-shot clips preserving Roman gladiator visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Roman gladiator mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's an Egyptian-priestess portrait — make an extended ancient-Egyptian mini-drama covering the full burial rite and tomb-robber confrontation.",
        "rationale": "Extended Egyptian-temple mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded priestess portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the priestess portrait reference image's descriptive content.",
            "Draft the Extended Egyptian-temple story blueprint — young-priestess full-burial-rite tomb-robber arc — anchored to the priestess portrait reference, scoped for extended runtime.",
            "Decompose the young-priestess full-burial-rite tomb-robber arc into Egyptian-temple priestess scenes.",
            "Plan keyframes for the temple sanctum / burial chamber / sealed tomb / aftermath settings, depicting the priestess portrait reference.",
            "Render per-shot clips preserving Egyptian-temple priestess visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Egyptian-temple priestess mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a pirate-costume portrait — produce an extended pirate-ship mini-drama covering the full naval campaign.",
        "rationale": "Extended pirate-ship battle mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded pirate-captain portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the pirate-captain portrait reference image's descriptive content.",
            "Draft the Extended pirate-ship battle story blueprint — young-captain full-naval campaign arc — anchored to the pirate-captain portrait reference, scoped for extended runtime.",
            "Decompose the young-captain full-naval campaign arc into pirate-ship battle scenes.",
            "Plan keyframes for the pirate deck / cannon deck / boarded frigate / port aftermath settings, depicting the pirate-captain portrait reference.",
            "Render per-shot clips preserving pirate-ship battle visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended pirate-ship battle mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's an Aztec-warrior portrait — make an extended Aztec mini-drama covering the full ritual-battle and aftermath rite.",
        "rationale": "Extended Aztec eagle-knight mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Aztec-warrior portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Aztec-warrior portrait reference image's descriptive content.",
            "Draft the Extended Aztec eagle-knight story blueprint — young-knight full-ritual-battle aftermath arc — anchored to the Aztec-warrior portrait reference, scoped for extended runtime.",
            "Decompose the young-knight full-ritual-battle aftermath arc into Aztec eagle-knight scenes.",
            "Plan keyframes for the training plaza / battlefield / sacrifice altar / aftermath rite settings, depicting the Aztec-warrior portrait reference.",
            "Render per-shot clips preserving Aztec eagle-knight visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Aztec eagle-knight mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a Mongolian-warrior portrait — produce an extended Mongolian-empire mini-drama covering the full Khwarezmian campaign.",
        "rationale": "Extended Mongolian conquest mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Mongolian-warrior portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Mongolian-warrior portrait reference image's descriptive content.",
            "Draft the Extended Mongolian conquest story blueprint — young-officer full-Khwarezm-campaign arc — anchored to the Mongolian-warrior portrait reference, scoped for extended runtime.",
            "Decompose the young-officer full-Khwarezm-campaign arc into Mongolian conquest scenes.",
            "Plan keyframes for the encampment / siege battlement / fallen city / return ride settings, depicting the Mongolian-warrior portrait reference.",
            "Render per-shot clips preserving Mongolian conquest visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Mongolian conquest mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a Renaissance-dress portrait — make an extended Renaissance-Florence mini-drama covering the full Medici-rivalry arc.",
        "rationale": "Extended Renaissance-Florence mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Renaissance-courtier portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Renaissance-courtier portrait reference image's descriptive content.",
            "Draft the Extended Renaissance-Florence story blueprint — young-courtier full-Medici-rivalry arc arc — anchored to the Renaissance-courtier portrait reference, scoped for extended runtime.",
            "Decompose the young-courtier full-Medici-rivalry arc arc into Renaissance-Florence scenes.",
            "Plan keyframes for the Medici palace / banquet hall / midnight courtyard / dawn audience settings, depicting the Renaissance-courtier portrait reference.",
            "Render per-shot clips preserving Renaissance-Florence visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Renaissance-Florence mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a conquistador portrait — produce an extended Spanish-conquistador mini-drama covering the full temple-raid arc.",
        "rationale": "Extended Spanish-conquistador mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded conquistador portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the conquistador portrait reference image's descriptive content.",
            "Draft the Extended Spanish-conquistador story blueprint — young-soldier full-temple-raid arc arc — anchored to the conquistador portrait reference, scoped for extended runtime.",
            "Decompose the young-soldier full-temple-raid arc arc into Spanish-conquistador scenes.",
            "Plan keyframes for the Spanish encampment / jungle approach / temple summit / return march settings, depicting the conquistador portrait reference.",
            "Render per-shot clips preserving Spanish-conquistador visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Spanish-conquistador mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a Tudor-costume portrait — make an extended Tudor-court mini-drama covering the full intrigue arc.",
        "rationale": "Extended Tudor-court mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Tudor-courtier portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Tudor-courtier portrait reference image's descriptive content.",
            "Draft the Extended Tudor-court story blueprint — young-lady-in-waiting full-court-intrigue arc arc — anchored to the Tudor-courtier portrait reference, scoped for extended runtime.",
            "Decompose the young-lady-in-waiting full-court-intrigue arc arc into Tudor-court scenes.",
            "Plan keyframes for the queen's chamber / privy hall / midnight corridor / scaffold dawn settings, depicting the Tudor-courtier portrait reference.",
            "Render per-shot clips preserving Tudor-court visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Tudor-court mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a Persian-warrior portrait — produce an extended Persian-empire mini-drama covering the full single-combat arc.",
        "rationale": "Extended Persian-empire mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Persian-warrior portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Persian-warrior portrait reference image's descriptive content.",
            "Draft the Extended Persian-empire story blueprint — young-warrior full-single-combat arc arc — anchored to the Persian-warrior portrait reference, scoped for extended runtime.",
            "Decompose the young-warrior full-single-combat arc arc into Persian-empire battle scenes.",
            "Plan keyframes for the Persian palace / battle encampment / single-combat plain / triumphal return settings, depicting the Persian-warrior portrait reference.",
            "Render per-shot clips preserving Persian-empire battle visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Persian-empire battle mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a warrior-monk portrait — make an extended Tibetan-monastery mini-drama covering the full siege-defense arc.",
        "rationale": "Extended Tibetan-monastery mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded warrior-monk portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the warrior-monk portrait reference image's descriptive content.",
            "Draft the Extended Tibetan-monastery story blueprint — young-warrior-monk full-defense arc arc — anchored to the warrior-monk portrait reference, scoped for extended runtime.",
            "Decompose the young-warrior-monk full-defense arc arc into Tibetan-monastery scenes.",
            "Plan keyframes for the monastery courtyard / mountain pass / inner-defense hall / aftermath rite settings, depicting the warrior-monk portrait reference.",
            "Render per-shot clips preserving Tibetan-monastery visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Tibetan-monastery mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a Shaolin-gear portrait — produce an extended Shaolin-monastery mini-drama covering the full bandit-raid defense arc.",
        "rationale": "Extended Shaolin mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Shaolin-monk portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Shaolin-monk portrait reference image's descriptive content.",
            "Draft the Extended Shaolin story blueprint — young-fighter full-bandit-raid arc arc — anchored to the Shaolin-monk portrait reference, scoped for extended runtime.",
            "Decompose the young-fighter full-bandit-raid arc arc into Shaolin-monastery scenes.",
            "Plan keyframes for the Shaolin training hall / outer wall / inner courtyard / aftermath rite settings, depicting the Shaolin-monk portrait reference.",
            "Render per-shot clips preserving Shaolin-monastery visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Shaolin-monastery mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's an Arctic-gear portrait — make an extended Arctic-explorer mini-drama covering the full expedition survival arc.",
        "rationale": "Extended Arctic-explorer mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Arctic-explorer portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Arctic-explorer portrait reference image's descriptive content.",
            "Draft the Extended Arctic-explorer story blueprint — young-team-member full-expedition survival arc — anchored to the Arctic-explorer portrait reference, scoped for extended runtime.",
            "Decompose the young-team-member full-expedition survival arc into Arctic-explorer scenes.",
            "Plan keyframes for the Arctic encampment / pack-ice traverse / final camp / rescue ship settings, depicting the Arctic-explorer portrait reference.",
            "Render per-shot clips preserving Arctic-explorer visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Arctic-explorer mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a nomad-costume portrait — produce an extended Saharan-caravan mini-drama covering the full bandit-ambush escape into oasis.",
        "rationale": "Extended Saharan-caravan mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded caravan-guard portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the caravan-guard portrait reference image's descriptive content.",
            "Draft the Extended Saharan-caravan story blueprint — young-guard full-bandit-ambush escape arc — anchored to the caravan-guard portrait reference, scoped for extended runtime.",
            "Decompose the young-guard full-bandit-ambush escape arc into Saharan-caravan scenes.",
            "Plan keyframes for the caravan camp / dune crossing / sandstorm / oasis arrival settings, depicting the caravan-guard portrait reference.",
            "Render per-shot clips preserving Saharan-caravan visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Saharan-caravan mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's an Andean-costume portrait — make an extended Andean-Inca rebellion mini-drama covering the full uprising arc.",
        "rationale": "Extended Andean-Inca mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Quechua-leader portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Quechua-leader portrait reference image's descriptive content.",
            "Draft the Extended Andean-Inca story blueprint — young-Quechua-leader full-rebellion arc arc — anchored to the Quechua-leader portrait reference, scoped for extended runtime.",
            "Decompose the young-Quechua-leader full-rebellion arc arc into Andean-Inca rebellion scenes.",
            "Plan keyframes for the Andean village / encomendero hacienda / mountain-pass ambush / temple sanctuary settings, depicting the Quechua-leader portrait reference.",
            "Render per-shot clips preserving Andean-Inca rebellion visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Andean-Inca rebellion mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a Tang-robe portrait — produce an extended Tang-dynasty mini-drama covering the full imperial-commission arc.",
        "rationale": "Extended Tang-court mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Tang-apprentice portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Tang-apprentice portrait reference image's descriptive content.",
            "Draft the Extended Tang-court story blueprint — apprentice full-imperial-commission arc arc — anchored to the Tang-apprentice portrait reference, scoped for extended runtime.",
            "Decompose the apprentice full-imperial-commission arc arc into Tang-court calligraphy scenes.",
            "Plan keyframes for the master's studio / mountain stream / Tang court / aftermath ceremony settings, depicting the Tang-apprentice portrait reference.",
            "Render per-shot clips preserving Tang-court calligraphy visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Tang-court calligraphy mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a samurai-gear portrait — make an extended Edo-period mini-drama covering the full clan-vendetta arc.",
        "rationale": "Extended Edo-period samurai mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded ronin portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the ronin portrait reference image's descriptive content.",
            "Draft the Extended Edo-period samurai story blueprint — ronin full-clan-vendetta arc arc — anchored to the ronin portrait reference, scoped for extended runtime.",
            "Decompose the ronin full-clan-vendetta arc arc into Edo-period samurai scenes.",
            "Plan keyframes for the Edo merchant district / mountain-mist forest / dawn duel / temple aftermath settings, depicting the ronin portrait reference.",
            "Render per-shot clips preserving Edo-period samurai visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Edo-period samurai mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a Heian-dress portrait — produce an extended Heian-court mini-drama covering the full poetry-faction arc.",
        "rationale": "Extended Heian-court mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Heian-courtier portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Heian-courtier portrait reference image's descriptive content.",
            "Draft the Extended Heian-court story blueprint — young-courtier full-poetry-faction arc arc — anchored to the Heian-courtier portrait reference, scoped for extended runtime.",
            "Decompose the young-courtier full-poetry-faction arc arc into Heian-court intrigue scenes.",
            "Plan keyframes for the Heian palace / inner garden / midnight corridor / dawn audience settings, depicting the Heian-courtier portrait reference.",
            "Render per-shot clips preserving Heian-court intrigue visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Heian-court intrigue mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's an Ottoman-costume portrait — make an extended Ottoman-sultanate mini-drama covering the full vizier-conspiracy arc.",
        "rationale": "Extended Ottoman-sultanate mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Ottoman-favorite portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Ottoman-favorite portrait reference image's descriptive content.",
            "Draft the Extended Ottoman-sultanate story blueprint — young-favorite full-vizier-conspiracy arc arc — anchored to the Ottoman-favorite portrait reference, scoped for extended runtime.",
            "Decompose the young-favorite full-vizier-conspiracy arc arc into Ottoman-sultanate scenes.",
            "Plan keyframes for the harem courtyard / vizier's chamber / sultan's audience / aftermath audience settings, depicting the Ottoman-favorite portrait reference.",
            "Render per-shot clips preserving Ottoman-sultanate visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Ottoman-sultanate mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a Mughal-princess portrait — produce an extended Mughal-court mini-drama covering the full succession-secure arc.",
        "rationale": "Extended Mughal-court mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Mughal-princess portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Mughal-princess portrait reference image's descriptive content.",
            "Draft the Extended Mughal-court story blueprint — young-princess full-succession arc arc — anchored to the Mughal-princess portrait reference, scoped for extended runtime.",
            "Decompose the young-princess full-succession arc arc into Mughal-court scenes.",
            "Plan keyframes for the Mughal palace / inner garden / pavilion / coronation hall settings, depicting the Mughal-princess portrait reference.",
            "Render per-shot clips preserving Mughal-court visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Mughal-court mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a Versailles-court portrait — make an extended Versailles mini-drama covering the full cardinal-rivalry arc.",
        "rationale": "Extended Versailles-court mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Versailles-marquise portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Versailles-marquise portrait reference image's descriptive content.",
            "Draft the Extended Versailles-court story blueprint — young-marquise full-cardinal-rivalry arc arc — anchored to the Versailles-marquise portrait reference, scoped for extended runtime.",
            "Decompose the young-marquise full-cardinal-rivalry arc arc into Versailles-court scenes.",
            "Plan keyframes for the hall of mirrors / cardinal's apartments / royal audience / aftermath promenade settings, depicting the Versailles-marquise portrait reference.",
            "Render per-shot clips preserving Versailles-court visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Versailles-court mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
    {
        "user_goal": "Here's a 19th-century Russian-court portrait — produce an extended Imperial-Russian-court mini-drama covering the full Romanov-rivalry arc.",
        "rationale": "Extended Imperial-Russian-court mini-drama from a text brief. Chain: IntakeImage → BriefEnricher → Story → Screenplay → KeyFrame → Video → VideoExtend → Compositor → done.",
        "intents": [
            "Register the user's uploaded Russian-lady-in-waiting portrait reference image as a captioned workspace artifact.",
            "Enrich the brief by integrating the Russian-lady-in-waiting portrait reference image's descriptive content.",
            "Draft the Extended Imperial-Russian-court story blueprint — young-lady-in-waiting full-Romanov-rivalry arc arc — anchored to the Russian-lady-in-waiting portrait reference, scoped for extended runtime.",
            "Decompose the young-lady-in-waiting full-Romanov-rivalry arc arc into Imperial-Russian-court scenes.",
            "Plan keyframes for the Winter Palace corridor / private chamber / palace ballroom / imperial dawn audience settings, depicting the Russian-lady-in-waiting portrait reference.",
            "Render per-shot clips preserving Imperial-Russian-court visual continuity.",
            "Extend the rendered video with continuation footage to reach the requested longer runtime.",
            "Composite the final extended Imperial-Russian-court mini-drama mp4 with mixed audio and inter-shot transitions.",
        ],
    },
]
