"""GRPO shape: highlight_music_subtitle — IntakeVideo → VideoAnalysis → Highlight → Music → Transcription → AudioMix → Compositor.

40 samples (target_n=40). Highlight reel + BGM + same-language subtitles. (gt_bug shape, kept logically correct.)
"""
from __future__ import annotations


def _make(topic, focus, music, lang):
    return {
        "rationale": (
            f"{topic} + {focus} highlight + {music} BGM + same-language {lang} subtitles. "
            "Reject AmbienceAgent, TranslationAgent (no bilingual), StyleTransfer/VideoExtend."
        ),
        "intents": [
            f"Ingest the user's uploaded {topic} recording into the workspace.",
            f"Analyze the {topic} to locate {focus} moments.",
            f"Extract the {focus} as highlight segments.",
            f"Compose the {music} BGM the user requested.",
            f"Transcribe the highlight-segment {lang} dialogue.",
            f"Layer the {music} BGM under the highlight segments into one final mixed wav.",
            f"Composite the final highlight reel mp4 with {lang} subtitles and mixed audio.",
        ],
    }


SAMPLES: list[dict] = [
    {**_make("English-language wedding-day video", "vow-and-toast", "romantic-strings", "English"),
     "user_goal": "Make a highlight reel of vows and toasts from my wedding-day video with English subtitles and romantic-strings BGM."},
    {**_make("Spanish cooking show", "judging-moment", "playful-piano", "Spanish"),
     "user_goal": "Cut highlights of judging moments from my Spanish cooking show with Spanish subtitles and playful-piano BGM."},
    {**_make("Japanese baseball game", "home-run-and-strikeout", "stadium-organ", "Japanese"),
     "user_goal": "Make a highlight reel of home runs from my Japanese baseball game with Japanese subtitles and stadium-organ BGM."},
    {**_make("French film panel", "audience-question", "Parisian-cafe-strings", "French"),
     "user_goal": "Cut highlights of audience questions from my French film panel with French subtitles and Parisian-cafe-strings BGM."},
    {**_make("German political debate", "sharpest-exchange", "tense-strings", "German"),
     "user_goal": "Make a highlight reel of sharpest exchanges from my German political debate with German subtitles and tense-strings BGM."},
    {**_make("Italian opera production", "climactic-aria", "swelling-strings", "Italian"),
     "user_goal": "Cut highlights of climactic arias from my Italian opera production with Italian subtitles and swelling-strings BGM."},
    {**_make("Russian-ballet performance", "principal-solo", "Tchaikovsky-style-strings", "Russian"),
     "user_goal": "Make a highlight reel of principal solos from my Russian-ballet performance with Russian subtitles and Tchaikovsky-style-strings BGM."},
    {**_make("Mandarin variety show", "guest-performance", "celebratory-orchestral", "Mandarin"),
     "user_goal": "Cut highlights of guest performances from my Mandarin variety show with Mandarin subtitles and celebratory-orchestral BGM."},
    {**_make("Hindi cricket Test", "boundary-and-wicket", "Indian-celebratory", "Hindi"),
     "user_goal": "Make a highlight reel of boundaries and wickets from my Hindi cricket Test with Hindi subtitles and Indian-celebratory BGM."},
    {**_make("Korean K-drama episode", "romance-confession", "tender-piano", "Korean"),
     "user_goal": "Cut highlights of romance-confession scenes from my Korean K-drama with Korean subtitles and tender-piano BGM."},
    {**_make("Cantonese cooking competition", "elimination-moment", "playful-piano", "Cantonese"),
     "user_goal": "Make a highlight reel of elimination moments from my Cantonese cooking competition with Cantonese subtitles and playful-piano BGM."},
    {**_make("Arabic news debate", "key-rebuttal", "tense-oud-and-percussion", "Arabic"),
     "user_goal": "Cut highlights of key rebuttals from my Arabic news debate with Arabic subtitles and tense-oud-and-percussion BGM."},
    {**_make("Turkish soap-opera season", "cliffhanger", "Turkish-strings", "Turkish"),
     "user_goal": "Make a highlight reel of cliffhanger moments from my Turkish soap-opera season with Turkish subtitles and Turkish-strings BGM."},
    {**_make("Vietnamese cooking show", "judges-tasting", "Vietnamese-strings", "Vietnamese"),
     "user_goal": "Cut highlights of judges'-tasting moments from my Vietnamese cooking show with Vietnamese subtitles and Vietnamese-strings BGM."},
    {**_make("Thai boxing match", "knockdown", "Thai-percussion", "Thai"),
     "user_goal": "Make a highlight reel of knockdowns from my Thai boxing match with Thai subtitles and Thai-percussion BGM."},
    {**_make("Polish parliamentary session", "vote-tally", "tense-orchestral", "Polish"),
     "user_goal": "Cut highlights of vote-tally moments from my Polish parliamentary session with Polish subtitles and tense-orchestral BGM."},
    {**_make("Portuguese soccer match", "goal-and-save", "stadium-fado", "Portuguese"),
     "user_goal": "Make a highlight reel of goals and saves from my Portuguese soccer match with Portuguese subtitles and stadium-fado BGM."},
    {**_make("Dutch art-fair tour", "artist-introduction", "Dutch-baroque-strings", "Dutch"),
     "user_goal": "Cut highlights of artist-introduction segments from my Dutch art-fair tour with Dutch subtitles and Dutch-baroque-strings BGM."},
    {**_make("Swedish ice-hockey final", "goal-and-fight", "Nordic-rock", "Swedish"),
     "user_goal": "Make a highlight reel of goals and fights from my Swedish ice-hockey final with Swedish subtitles and Nordic-rock BGM."},
    {**_make("Norwegian-fjord travel show", "ferry-arrival", "Nordic-strings", "Norwegian"),
     "user_goal": "Cut highlights of ferry-arrival moments from my Norwegian-fjord travel show with Norwegian subtitles and Nordic-strings BGM."},
    {**_make("Finnish-forest hiking show", "wildlife-sighting", "minimal-Finnish-strings", "Finnish"),
     "user_goal": "Make a highlight reel of wildlife-sighting moments from my Finnish-forest hiking show with Finnish subtitles and minimal-Finnish-strings BGM."},
    {**_make("Hebrew rabbinical seminar", "key-Q-and-A", "Israeli-folk strings", "Hebrew"),
     "user_goal": "Cut highlights of key Q&A exchanges from my Hebrew rabbinical seminar with Hebrew subtitles and Israeli-folk-strings BGM."},
    {**_make("Persian poetry recital", "encore-recitation", "Persian-setar-and-tar", "Persian"),
     "user_goal": "Make a highlight reel of encore-recitation segments from my Persian poetry recital with Persian subtitles and Persian-setar-and-tar BGM."},
    {**_make("Bengali theatre performance", "act-finale", "Bengali-sitar-and-violin", "Bengali"),
     "user_goal": "Cut highlights of act-finale moments from my Bengali theatre performance with Bengali subtitles and Bengali-sitar-and-violin BGM."},
    {**_make("Tamil dance competition", "winner-routine", "Carnatic-veena-and-mridangam", "Tamil"),
     "user_goal": "Make a highlight reel of winning routines from my Tamil dance competition with Tamil subtitles and Carnatic-veena-and-mridangam BGM."},
    {**_make("Yoruba elder-council meeting", "decisive-vote", "Yoruba talking-drum", "Yoruba"),
     "user_goal": "Cut highlights of decisive-vote moments from my Yoruba elder-council meeting with Yoruba subtitles and Yoruba-talking-drum BGM."},
    {**_make("Swahili Mombasa-port news", "vessel-arrival", "Swahili-oud", "Swahili"),
     "user_goal": "Make a highlight reel of vessel-arrival announcements from my Swahili Mombasa-port news with Swahili subtitles and Swahili-oud BGM."},
    {**_make("Tagalog noontime variety show", "celebrity-interview", "OPM strings", "Tagalog"),
     "user_goal": "Cut highlights of celebrity-interview segments from my Tagalog noontime variety show with Tagalog subtitles and OPM-strings BGM."},
    {**_make("Indonesian wayang performance", "battle-scene", "gamelan", "Indonesian"),
     "user_goal": "Make a highlight reel of battle scenes from my Indonesian wayang performance with Indonesian subtitles and gamelan BGM."},
    {**_make("Greek-island wedding-festival", "dance-circle-moment", "bouzouki", "Greek"),
     "user_goal": "Cut highlights of dance-circle moments from my Greek-island wedding-festival with Greek subtitles and bouzouki BGM."},
    {**_make("3-hour NBA game", "dunk-and-block", "high-energy hip-hop", "English"),
     "user_goal": "Make a highlight reel of dunks and blocks from my 3-hour NBA game with English subtitles and high-energy hip-hop BGM."},
    {**_make("4-hour cooking competition", "judging-moment", "playful piano-and-strings", "English"),
     "user_goal": "Cut highlights of judging moments from my 4-hour cooking competition with English subtitles and playful piano-and-strings BGM."},
    {**_make("8-hour gaming tournament", "boss-kill-and-final-round", "epic gaming-orchestral", "English"),
     "user_goal": "Make a highlight reel of boss kills and final rounds from my 8-hour gaming tournament with English subtitles and epic gaming-orchestral BGM."},
    {**_make("90-minute soccer match", "goal-and-save", "stadium anthem", "English"),
     "user_goal": "Cut highlights of goals and saves from my 90-minute soccer match with English subtitles and stadium-anthem BGM."},
    {**_make("4-hour F1 race weekend", "overtake-and-pit-stop", "orchestral-electronic", "English"),
     "user_goal": "Make a highlight reel of overtakes and pit stops from my 4-hour F1 race weekend with English subtitles and orchestral-electronic BGM."},
    {**_make("90-minute boxing title fight", "knockdown", "powerful-percussion", "English"),
     "user_goal": "Cut highlights of knockdowns from my 90-minute boxing title fight with English subtitles and powerful-percussion BGM."},
    {**_make("3-hour MMA championship", "knockout-and-submission", "intense-electronic", "English"),
     "user_goal": "Make a highlight reel of knockouts and submissions from my 3-hour MMA championship with English subtitles and intense-electronic BGM."},
    {**_make("6-hour Olympic gymnastics broadcast", "perfect-score-routine", "Olympic-fanfare", "English"),
     "user_goal": "Cut highlights of perfect-score routines from my 6-hour Olympic gymnastics broadcast with English subtitles and Olympic-fanfare BGM."},
    {**_make("4-hour tennis grand slam final", "break-point-and-match-point", "tense-strings", "English"),
     "user_goal": "Make a highlight reel of break-points and match-points from my 4-hour tennis grand slam final with English subtitles and tense-strings BGM."},
    {**_make("5-hour swimming championship", "gold-medal-heat", "uplifting orchestral", "English"),
     "user_goal": "Cut highlights of gold-medal heats from my 5-hour swimming championship with English subtitles and uplifting-orchestral BGM."},
]
