"""Shape: cr_subtitle —
    Story → Screenplay → KeyFrame → Video → Transcription → Compositor.

Cinematic mini-drama with monolingual subtitles, no audio overlay. (Path B alignment with v3 eval — opt-in audio: chain has Music/Ambience/AudioMix iff user_goal explicitly mentions audio.)
"""
from __future__ import annotations

SAMPLES: list[dict] = [
    {
        "user_goal": "Make a Spanish-language soccer mini-drama about a captain rallying her team in the locker room before the championship penalty shoot-out, and Spanish subtitles.",
        "rationale": "Spanish soccer locker-room mini-drama from a text brief + Spanish monolingual subtitles. StoryAgent drafts the captain / pre-final pep-talk / penalty-shoot-out blueprint. ScreenplayAgent breaks it into soccer locker-room scenes. KeyFrameAgent plans keyframes for the locker-room corridor / tunnel / final-shoot-out goal-line settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Spanish subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Spanish soccer locker-room story blueprint — captain / pre-final pep-talk / penalty-shoot-out arc.",
            "Decompose the captain / pre-final pep-talk / penalty-shoot-out arc into soccer locker-room scenes.",
            "Plan keyframes for the locker-room corridor / tunnel / final-shoot-out goal-line settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Spanish soccer locker-room visual continuity.",
            "Transcribe the Spanish dialogue into timestamped subtitle segments.",
            "Composite the final Spanish soccer locker-room mini-drama mp4 with mixed audio and Spanish subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Korean-language medical thriller mini-drama about a young resident who exposes the chief-of-surgery's protocol that's killing trauma patients, and Korean subtitles.",
        "rationale": "Korean medical thriller mini-drama from a text brief + Korean monolingual subtitles. StoryAgent drafts the young-resident / mass-casualty / chief-confrontation blueprint. ScreenplayAgent breaks it into Korean medical thriller scenes. KeyFrameAgent plans keyframes for the ER triage / OR theater / hospital-rooftop confrontation settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Korean subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Korean medical thriller story blueprint — young-resident / mass-casualty / chief-confrontation arc.",
            "Decompose the young-resident / mass-casualty / chief-confrontation arc into Korean medical thriller scenes.",
            "Plan keyframes for the ER triage / OR theater / hospital-rooftop confrontation settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Korean medical thriller visual continuity.",
            "Transcribe the Korean dialogue into timestamped subtitle segments.",
            "Composite the final Korean medical thriller mini-drama mp4 with mixed audio and Korean subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Japanese-language corporate-rivalry mini-drama about a junior sales rep who must out-pitch the rival firm's incumbent for a flagship account, and Japanese subtitles.",
        "rationale": "Japanese corporate-rivalry mini-drama from a text brief + Japanese monolingual subtitles. StoryAgent drafts the junior-sales / rival-firm / boardroom-final-pitch blueprint. ScreenplayAgent breaks it into Japanese corporate-rivalry scenes. KeyFrameAgent plans keyframes for the Tokyo office / pitch-rehearsal room / boardroom presentation settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Japanese subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Japanese corporate-rivalry story blueprint — junior-sales / rival-firm / boardroom-final-pitch arc.",
            "Decompose the junior-sales / rival-firm / boardroom-final-pitch arc into Japanese corporate-rivalry scenes.",
            "Plan keyframes for the Tokyo office / pitch-rehearsal room / boardroom presentation settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Japanese corporate-rivalry visual continuity.",
            "Transcribe the Japanese dialogue into timestamped subtitle segments.",
            "Composite the final Japanese corporate-rivalry mini-drama mp4 with mixed audio and Japanese subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a French-language Parisian fashion-house mini-drama about a young designer racing to finish her debut couture collection as her muse defects to a rival house, and French subtitles.",
        "rationale": "French Parisian fashion-house mini-drama from a text brief + French monolingual subtitles. StoryAgent drafts the young-designer / final-couture-show / muse-betrayal blueprint. ScreenplayAgent breaks it into Parisian fashion-house scenes. KeyFrameAgent plans keyframes for the atelier studio / fitting room / runway-show backstage settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts French subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the French Parisian fashion-house story blueprint — young-designer / final-couture-show / muse-betrayal arc.",
            "Decompose the young-designer / final-couture-show / muse-betrayal arc into Parisian fashion-house scenes.",
            "Plan keyframes for the atelier studio / fitting room / runway-show backstage settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Parisian fashion-house visual continuity.",
            "Transcribe the French dialogue into timestamped subtitle segments.",
            "Composite the final Parisian fashion-house mini-drama mp4 with mixed audio and French subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a German-language Cold-War mini-drama about a young Stasi officer working a Western asset whose safe-house is compromised — dawn extraction or arrest, and German subtitles.",
        "rationale": "German East-Berlin spy mini-drama from a text brief + German monolingual subtitles. StoryAgent drafts the young-Stasi-officer / Western asset / dawn-extraction blueprint. ScreenplayAgent breaks it into East-Berlin spy scenes. KeyFrameAgent plans keyframes for the Stasi office / safe-house apartment / Wall-side dawn extraction settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts German subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the German East-Berlin spy story blueprint — young-Stasi-officer / Western asset / dawn-extraction arc.",
            "Decompose the young-Stasi-officer / Western asset / dawn-extraction arc into East-Berlin spy scenes.",
            "Plan keyframes for the Stasi office / safe-house apartment / Wall-side dawn extraction settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving East-Berlin spy visual continuity.",
            "Transcribe the German dialogue into timestamped subtitle segments.",
            "Composite the final East-Berlin spy mini-drama mp4 with mixed audio and German subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce an Italian-language 1970s political thriller mini-drama about a young prosecutor uncovering the mafia pact behind a politician's kidnapping, and Italian subtitles.",
        "rationale": "Italian 1970s political-thriller mini-drama from a text brief + Italian monolingual subtitles. StoryAgent drafts the young-prosecutor / kidnapped-politician / mafia-pact discovery blueprint. ScreenplayAgent breaks it into Italian 1970s political-thriller scenes. KeyFrameAgent plans keyframes for the Rome courthouse / Naples-port stakeout / underground meeting settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Italian subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Italian 1970s political-thriller story blueprint — young-prosecutor / kidnapped-politician / mafia-pact discovery arc.",
            "Decompose the young-prosecutor / kidnapped-politician / mafia-pact discovery arc into Italian 1970s political-thriller scenes.",
            "Plan keyframes for the Rome courthouse / Naples-port stakeout / underground meeting settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Italian 1970s political-thriller visual continuity.",
            "Transcribe the Italian dialogue into timestamped subtitle segments.",
            "Composite the final Italian 1970s political-thriller mini-drama mp4 with mixed audio and Italian subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Russian-language ballet-academy mini-drama about a young soloist whose aging coach insists she's not ready for the principal-role audition that decides her career, and Russian subtitles.",
        "rationale": "Russian ballet academy mini-drama from a text brief + Russian monolingual subtitles. StoryAgent drafts the young-soloist / aging-coach / final-audition blueprint. ScreenplayAgent breaks it into Russian ballet academy scenes. KeyFrameAgent plans keyframes for the studio mirror / academy theatre / artistic-director audition room settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Russian subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Russian ballet academy story blueprint — young-soloist / aging-coach / final-audition arc.",
            "Decompose the young-soloist / aging-coach / final-audition arc into Russian ballet academy scenes.",
            "Plan keyframes for the studio mirror / academy theatre / artistic-director audition room settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Russian ballet academy visual continuity.",
            "Transcribe the Russian dialogue into timestamped subtitle segments.",
            "Composite the final Russian ballet academy mini-drama mp4 with mixed audio and Russian subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Mandarin-language cultivation-fantasy mini-drama about a junior disciple whose awakened bloodline forces her to face the sect's final trial three years early, and Mandarin subtitles.",
        "rationale": "Mandarin cultivation-fantasy mini-drama from a text brief + Mandarin monolingual subtitles. StoryAgent drafts the junior-disciple / awakening-bloodline / sect-final-trial blueprint. ScreenplayAgent breaks it into Mandarin cultivation-fantasy scenes. KeyFrameAgent plans keyframes for the sect mountain / underground cave / final-trial peak settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Mandarin subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Mandarin cultivation-fantasy story blueprint — junior-disciple / awakening-bloodline / sect-final-trial arc.",
            "Decompose the junior-disciple / awakening-bloodline / sect-final-trial arc into Mandarin cultivation-fantasy scenes.",
            "Plan keyframes for the sect mountain / underground cave / final-trial peak settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Mandarin cultivation-fantasy visual continuity.",
            "Transcribe the Mandarin dialogue into timestamped subtitle segments.",
            "Composite the final Mandarin cultivation-fantasy mini-drama mp4 with mixed audio and Mandarin subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Mandarin-language Tang-dynasty mini-drama about a young scholar exposing examination fraud that reaches the palace's inner circle, and Mandarin subtitles.",
        "rationale": "Mandarin Tang-period drama mini-drama from a text brief + Mandarin monolingual subtitles. StoryAgent drafts the young-imperial-scholar / examination-fraud / palace-confrontation blueprint. ScreenplayAgent breaks it into Tang-period palace drama scenes. KeyFrameAgent plans keyframes for the imperial examination hall / Tang capital street / palace audience hall settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Mandarin subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Mandarin Tang-period drama story blueprint — young-imperial-scholar / examination-fraud / palace-confrontation arc.",
            "Decompose the young-imperial-scholar / examination-fraud / palace-confrontation arc into Tang-period palace drama scenes.",
            "Plan keyframes for the imperial examination hall / Tang capital street / palace audience hall settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Tang-period palace drama visual continuity.",
            "Transcribe the Mandarin dialogue into timestamped subtitle segments.",
            "Composite the final Tang-period palace drama mini-drama mp4 with mixed audio and Mandarin subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Hindi-language family-saga mini-drama about the youngest daughter forced to confront her brothers over the family inheritance on her own wedding day, and Hindi subtitles.",
        "rationale": "Hindi family-saga mini-drama from a text brief + Hindi monolingual subtitles. StoryAgent drafts the youngest-daughter / inheritance-fight / wedding-day showdown blueprint. ScreenplayAgent breaks it into Hindi family-saga scenes. KeyFrameAgent plans keyframes for the ancestral haveli courtyard / wedding mandap / inheritance-document study settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Hindi subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Hindi family-saga story blueprint — youngest-daughter / inheritance-fight / wedding-day showdown arc.",
            "Decompose the youngest-daughter / inheritance-fight / wedding-day showdown arc into Hindi family-saga scenes.",
            "Plan keyframes for the ancestral haveli courtyard / wedding mandap / inheritance-document study settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Hindi family-saga visual continuity.",
            "Transcribe the Hindi dialogue into timestamped subtitle segments.",
            "Composite the final Hindi family-saga mini-drama mp4 with mixed audio and Hindi subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Brazilian-Portuguese favela-cartel mini-drama about a young photographer whose photos of a Rio cartel boss are about to leak — and the dawn extraction trying to get her out, and Portuguese subtitles.",
        "rationale": "Brazilian favela-cartel mini-drama from a text brief + Portuguese monolingual subtitles. StoryAgent drafts the young-photographer / cartel-photo-leak / safe-extraction blueprint. ScreenplayAgent breaks it into Brazilian favela-cartel scenes. KeyFrameAgent plans keyframes for the favela alley / photographer's roof-top studio / dawn extraction route settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Portuguese subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Brazilian favela-cartel story blueprint — young-photographer / cartel-photo-leak / safe-extraction arc.",
            "Decompose the young-photographer / cartel-photo-leak / safe-extraction arc into Brazilian favela-cartel scenes.",
            "Plan keyframes for the favela alley / photographer's roof-top studio / dawn extraction route settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Brazilian favela-cartel visual continuity.",
            "Transcribe the Portuguese dialogue into timestamped subtitle segments.",
            "Composite the final Brazilian favela-cartel mini-drama mp4 with mixed audio and Portuguese subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Turkish-language Ottoman-empire mini-drama about a young janissary uncovering a vizier's plot against the sultan and racing to the palace audience-chamber, and Turkish subtitles.",
        "rationale": "Turkish Ottoman-empire mini-drama from a text brief + Turkish monolingual subtitles. StoryAgent drafts the young-janissary / sultan-conspiracy / palace-showdown blueprint. ScreenplayAgent breaks it into Turkish Ottoman-empire scenes. KeyFrameAgent plans keyframes for the Ottoman palace / janissary barracks / sultan's audience chamber settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Turkish subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Turkish Ottoman-empire story blueprint — young-janissary / sultan-conspiracy / palace-showdown arc.",
            "Decompose the young-janissary / sultan-conspiracy / palace-showdown arc into Turkish Ottoman-empire scenes.",
            "Plan keyframes for the Ottoman palace / janissary barracks / sultan's audience chamber settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Turkish Ottoman-empire visual continuity.",
            "Transcribe the Turkish dialogue into timestamped subtitle segments.",
            "Composite the final Turkish Ottoman-empire mini-drama mp4 with mixed audio and Turkish subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make an Arabic-language old-Damascus mini-drama about a young merchant's daughter renegotiating her late father's caravan debt with the souk elders before they seize the family stall, and Arabic subtitles.",
        "rationale": "Arabic old-Damascus merchant mini-drama from a text brief + Arabic monolingual subtitles. StoryAgent drafts the young-merchant-daughter / caravan-debt / souk-confrontation blueprint. ScreenplayAgent breaks it into old-Damascus merchant scenes. KeyFrameAgent plans keyframes for the souk stall / caravan staging-yard / souk-elder confrontation settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Arabic subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Arabic old-Damascus merchant story blueprint — young-merchant-daughter / caravan-debt / souk-confrontation arc.",
            "Decompose the young-merchant-daughter / caravan-debt / souk-confrontation arc into old-Damascus merchant scenes.",
            "Plan keyframes for the souk stall / caravan staging-yard / souk-elder confrontation settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving old-Damascus merchant visual continuity.",
            "Transcribe the Arabic dialogue into timestamped subtitle segments.",
            "Composite the final old-Damascus merchant mini-drama mp4 with mixed audio and Arabic subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Vietnamese-language postwar mini-drama about a young woman whose father's old wartime comrades visit and slowly reveal the family truth he never told her, and Vietnamese subtitles.",
        "rationale": "Vietnamese postwar family mini-drama from a text brief + Vietnamese monolingual subtitles. StoryAgent drafts the young-daughter / father's-old-comrades visit / family-truth reveal blueprint. ScreenplayAgent breaks it into Vietnamese postwar family scenes. KeyFrameAgent plans keyframes for the Saigon family home / pho-stall street-corner / ancestor-altar room settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Vietnamese subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Vietnamese postwar family story blueprint — young-daughter / father's-old-comrades visit / family-truth reveal arc.",
            "Decompose the young-daughter / father's-old-comrades visit / family-truth reveal arc into Vietnamese postwar family scenes.",
            "Plan keyframes for the Saigon family home / pho-stall street-corner / ancestor-altar room settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Vietnamese postwar family visual continuity.",
            "Transcribe the Vietnamese dialogue into timestamped subtitle segments.",
            "Composite the final Vietnamese postwar family mini-drama mp4 with mixed audio and Vietnamese subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Thai-language village-spirit mini-drama about a young shaman summoned to her grandmother's village to perform the final ritual on a spirit her grandmother failed to bind, and Thai subtitles.",
        "rationale": "Thai village-spirit mini-drama from a text brief + Thai monolingual subtitles. StoryAgent drafts the young-shaman / village-spirit-disturbance / final-ritual confrontation blueprint. ScreenplayAgent breaks it into Thai village-spirit scenes. KeyFrameAgent plans keyframes for the rural Thai village / spirit-house grove / final-ritual clearing settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Thai subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Thai village-spirit story blueprint — young-shaman / village-spirit-disturbance / final-ritual confrontation arc.",
            "Decompose the young-shaman / village-spirit-disturbance / final-ritual confrontation arc into Thai village-spirit scenes.",
            "Plan keyframes for the rural Thai village / spirit-house grove / final-ritual clearing settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Thai village-spirit visual continuity.",
            "Transcribe the Thai dialogue into timestamped subtitle segments.",
            "Composite the final Thai village-spirit mini-drama mp4 with mixed audio and Thai subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Polish-language WW2-resistance mini-drama about a young courier carrying microfilm across occupied Warsaw — one dead-drop, one extraction, one chance, and Polish subtitles.",
        "rationale": "Polish WW2-resistance mini-drama from a text brief + Polish monolingual subtitles. StoryAgent drafts the young-courier / occupied-Warsaw / dead-drop final run blueprint. ScreenplayAgent breaks it into Polish WW2-resistance scenes. KeyFrameAgent plans keyframes for the Warsaw safe-house cellar / occupied-street / sewer-extraction settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Polish subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Polish WW2-resistance story blueprint — young-courier / occupied-Warsaw / dead-drop final run arc.",
            "Decompose the young-courier / occupied-Warsaw / dead-drop final run arc into Polish WW2-resistance scenes.",
            "Plan keyframes for the Warsaw safe-house cellar / occupied-street / sewer-extraction settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Polish WW2-resistance visual continuity.",
            "Transcribe the Polish dialogue into timestamped subtitle segments.",
            "Composite the final Polish WW2-resistance mini-drama mp4 with mixed audio and Polish subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Greek-language Aegean-island mini-drama about a young woman captaining her father's failing fishing boat for the catch that pays his last debt, and Greek subtitles.",
        "rationale": "Greek-island fishing-family mini-drama from a text brief + Greek monolingual subtitles. StoryAgent drafts the young-daughter / father's-debt / final-catch decision blueprint. ScreenplayAgent breaks it into Greek-island fishing-family scenes. KeyFrameAgent plans keyframes for the harbor cottage / fishing-boat deck / taverna evening settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Greek subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Greek-island fishing-family story blueprint — young-daughter / father's-debt / final-catch decision arc.",
            "Decompose the young-daughter / father's-debt / final-catch decision arc into Greek-island fishing-family scenes.",
            "Plan keyframes for the harbor cottage / fishing-boat deck / taverna evening settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Greek-island fishing-family visual continuity.",
            "Transcribe the Greek dialogue into timestamped subtitle segments.",
            "Composite the final Greek-island fishing-family mini-drama mp4 with mixed audio and Greek subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Dutch-language 17th-century VOC mini-drama about a young trader sent to Batavia to expose the spice-route fraud that made her brother disappear, and Dutch subtitles.",
        "rationale": "Dutch 17th-century VOC-trader mini-drama from a text brief + Dutch monolingual subtitles. StoryAgent drafts the young-trader / spice-route betrayal / Batavia-final showdown blueprint. ScreenplayAgent breaks it into Dutch VOC-trader scenes. KeyFrameAgent plans keyframes for the Amsterdam dockside warehouse / open-ocean voyage / Batavia colonial office settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Dutch subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Dutch 17th-century VOC-trader story blueprint — young-trader / spice-route betrayal / Batavia-final showdown arc.",
            "Decompose the young-trader / spice-route betrayal / Batavia-final showdown arc into Dutch VOC-trader scenes.",
            "Plan keyframes for the Amsterdam dockside warehouse / open-ocean voyage / Batavia colonial office settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Dutch VOC-trader visual continuity.",
            "Transcribe the Dutch dialogue into timestamped subtitle segments.",
            "Composite the final Dutch VOC-trader mini-drama mp4 with mixed audio and Dutch subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Swedish-language Stockholm noir mini-drama about a young detective tracking a serial disappearance into the archipelago — and confronting the suspect at his island cabin alone, and Swedish subtitles.",
        "rationale": "Swedish Stockholm noir mini-drama from a text brief + Swedish monolingual subtitles. StoryAgent drafts the young-detective / serial-disappearance / suspect-confrontation in archipelago blueprint. ScreenplayAgent breaks it into Swedish Stockholm noir scenes. KeyFrameAgent plans keyframes for the Stockholm precinct / waterfront pier / archipelago island cabin settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Swedish subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Swedish Stockholm noir story blueprint — young-detective / serial-disappearance / suspect-confrontation in archipelago arc.",
            "Decompose the young-detective / serial-disappearance / suspect-confrontation in archipelago arc into Swedish Stockholm noir scenes.",
            "Plan keyframes for the Stockholm precinct / waterfront pier / archipelago island cabin settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Swedish Stockholm noir visual continuity.",
            "Transcribe the Swedish dialogue into timestamped subtitle segments.",
            "Composite the final Swedish Stockholm noir mini-drama mp4 with mixed audio and Swedish subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Norwegian-language Arctic-trawler mini-drama about a young deck officer caught between her mutinous crew and the captain who refuses to turn back from the storm, and Norwegian subtitles.",
        "rationale": "Norwegian Arctic-trawler mini-drama from a text brief + Norwegian monolingual subtitles. StoryAgent drafts the young-deck-officer / mutiny / storm-bound bridge standoff blueprint. ScreenplayAgent breaks it into Norwegian Arctic-trawler scenes. KeyFrameAgent plans keyframes for the trawler bridge / engine-room corridor / storm-deck wheelhouse settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Norwegian subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Norwegian Arctic-trawler story blueprint — young-deck-officer / mutiny / storm-bound bridge standoff arc.",
            "Decompose the young-deck-officer / mutiny / storm-bound bridge standoff arc into Norwegian Arctic-trawler scenes.",
            "Plan keyframes for the trawler bridge / engine-room corridor / storm-deck wheelhouse settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Norwegian Arctic-trawler visual continuity.",
            "Transcribe the Norwegian dialogue into timestamped subtitle segments.",
            "Composite the final Norwegian Arctic-trawler mini-drama mp4 with mixed audio and Norwegian subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Finnish-language Winter-War mini-drama about a young ski-soldier covering the dawn extraction of her unit across a frozen lake under threat of breaking ice, and Finnish subtitles.",
        "rationale": "Finnish Winter-War ski-troops mini-drama from a text brief + Finnish monolingual subtitles. StoryAgent drafts the young-ski-soldier / ambush / dawn-extraction across frozen lake blueprint. ScreenplayAgent breaks it into Finnish Winter-War ski-troops scenes. KeyFrameAgent plans keyframes for the snow-bound forest / ambush-pass valley / frozen-lake crossing settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Finnish subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Finnish Winter-War ski-troops story blueprint — young-ski-soldier / ambush / dawn-extraction across frozen lake arc.",
            "Decompose the young-ski-soldier / ambush / dawn-extraction across frozen lake arc into Finnish Winter-War ski-troops scenes.",
            "Plan keyframes for the snow-bound forest / ambush-pass valley / frozen-lake crossing settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Finnish Winter-War ski-troops visual continuity.",
            "Transcribe the Finnish dialogue into timestamped subtitle segments.",
            "Composite the final Finnish Winter-War ski-troops mini-drama mp4 with mixed audio and Finnish subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Mexican-Spanish-language border-narco mini-drama about a young customs officer offered a cartel bribe she refused, facing the dawn shift she might not survive, and Mexican-Spanish subtitles.",
        "rationale": "Mexican border-narco mini-drama from a text brief + Mexican Spanish monolingual subtitles. StoryAgent drafts the young-customs-officer / cartel-bribe / dawn-station standoff blueprint. ScreenplayAgent breaks it into Mexican border-narco scenes. KeyFrameAgent plans keyframes for the border-station office / cartel-truck checkpoint / dawn-bridge confrontation settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Mexican Spanish subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Mexican border-narco story blueprint — young-customs-officer / cartel-bribe / dawn-station standoff arc.",
            "Decompose the young-customs-officer / cartel-bribe / dawn-station standoff arc into Mexican border-narco scenes.",
            "Plan keyframes for the border-station office / cartel-truck checkpoint / dawn-bridge confrontation settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Mexican border-narco visual continuity.",
            "Transcribe the Mexican Spanish dialogue into timestamped subtitle segments.",
            "Composite the final Mexican border-narco mini-drama mp4 with mixed audio and Mexican Spanish subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Brazilian-Portuguese favela mini-drama about a young community organizer leading the march that confronts the police line her older brother is on, and Brazilian-Portuguese subtitles.",
        "rationale": "Brazilian favela-uprising mini-drama from a text brief + Brazilian Portuguese monolingual subtitles. StoryAgent drafts the young-organizer / community-march / police-line confrontation blueprint. ScreenplayAgent breaks it into Brazilian favela-uprising scenes. KeyFrameAgent plans keyframes for the favela community center / march-route street / police-line plaza settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Brazilian Portuguese subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Brazilian favela-uprising story blueprint — young-organizer / community-march / police-line confrontation arc.",
            "Decompose the young-organizer / community-march / police-line confrontation arc into Brazilian favela-uprising scenes.",
            "Plan keyframes for the favela community center / march-route street / police-line plaza settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Brazilian favela-uprising visual continuity.",
            "Transcribe the Brazilian Portuguese dialogue into timestamped subtitle segments.",
            "Composite the final Brazilian favela-uprising mini-drama mp4 with mixed audio and Brazilian Portuguese subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce an Argentine-Spanish pampas-rancher mini-drama about a young gaucha refusing the land-baron's drought-buyout offer for her family ranch, and Argentine-Spanish subtitles.",
        "rationale": "Argentine pampas-rancher mini-drama from a text brief + Argentine Spanish monolingual subtitles. StoryAgent drafts the young-gaucha / drought / land-baron-confrontation blueprint. ScreenplayAgent breaks it into Argentine pampas-rancher scenes. KeyFrameAgent plans keyframes for the ranch homestead / dry pampa / land-baron's estancia settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Argentine Spanish subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Argentine pampas-rancher story blueprint — young-gaucha / drought / land-baron-confrontation arc.",
            "Decompose the young-gaucha / drought / land-baron-confrontation arc into Argentine pampas-rancher scenes.",
            "Plan keyframes for the ranch homestead / dry pampa / land-baron's estancia settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Argentine pampas-rancher visual continuity.",
            "Transcribe the Argentine Spanish dialogue into timestamped subtitle segments.",
            "Composite the final Argentine pampas-rancher mini-drama mp4 with mixed audio and Argentine Spanish subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Cuban-Spanish 1959 revolution mini-drama about a young fighter from a Sierra Maestra camp marching into Havana the day the regime falls, and Cuban-Spanish subtitles.",
        "rationale": "Cuban 1959 revolution mini-drama from a text brief + Cuban Spanish monolingual subtitles. StoryAgent drafts the young-fighter / sierra mountain camp / Havana-march final day blueprint. ScreenplayAgent breaks it into Cuban 1959 revolution scenes. KeyFrameAgent plans keyframes for the sierra mountain camp / dirt-road advance / Havana-plaza final day settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Cuban Spanish subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Cuban 1959 revolution story blueprint — young-fighter / sierra mountain camp / Havana-march final day arc.",
            "Decompose the young-fighter / sierra mountain camp / Havana-march final day arc into Cuban 1959 revolution scenes.",
            "Plan keyframes for the sierra mountain camp / dirt-road advance / Havana-plaza final day settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Cuban 1959 revolution visual continuity.",
            "Transcribe the Cuban Spanish dialogue into timestamped subtitle segments.",
            "Composite the final Cuban 1959 revolution mini-drama mp4 with mixed audio and Cuban Spanish subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Hebrew-language early-kibbutz mini-drama about a young founder defending the kibbutz's claim to a disputed field at the community meeting that decides whether to fight or negotiate, and Hebrew subtitles.",
        "rationale": "Hebrew early-kibbutz mini-drama from a text brief + Hebrew monolingual subtitles. StoryAgent drafts the young-founder / land-dispute / kibbutz-meeting decision blueprint. ScreenplayAgent breaks it into Hebrew early-kibbutz scenes. KeyFrameAgent plans keyframes for the kibbutz dining hall / disputed-field boundary / community meeting room settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Hebrew subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Hebrew early-kibbutz story blueprint — young-founder / land-dispute / kibbutz-meeting decision arc.",
            "Decompose the young-founder / land-dispute / kibbutz-meeting decision arc into Hebrew early-kibbutz scenes.",
            "Plan keyframes for the kibbutz dining hall / disputed-field boundary / community meeting room settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Hebrew early-kibbutz visual continuity.",
            "Transcribe the Hebrew dialogue into timestamped subtitle segments.",
            "Composite the final Hebrew early-kibbutz mini-drama mp4 with mixed audio and Hebrew subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Persian-language shahnameh mini-drama about a young warrior returning from a mythic trial to face the king who sent her expecting her never to come back, and Persian subtitles.",
        "rationale": "Persian shahnameh-tale mini-drama from a text brief + Persian monolingual subtitles. StoryAgent drafts the young-warrior / mythic-trial / king-court return blueprint. ScreenplayAgent breaks it into Persian shahnameh-tale scenes. KeyFrameAgent plans keyframes for the Persian palace court / mountain mythic-trial / triumphal return road settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Persian subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Persian shahnameh-tale story blueprint — young-warrior / mythic-trial / king-court return arc.",
            "Decompose the young-warrior / mythic-trial / king-court return arc into Persian shahnameh-tale scenes.",
            "Plan keyframes for the Persian palace court / mountain mythic-trial / triumphal return road settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Persian shahnameh-tale visual continuity.",
            "Transcribe the Persian dialogue into timestamped subtitle segments.",
            "Composite the final Persian shahnameh-tale mini-drama mp4 with mixed audio and Persian subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Quebec-French 1949 asbestos-strike mini-drama about a young organizer rallying mining-town workers as Church mediators try to broker a deal, and Quebec-French subtitles.",
        "rationale": "Quebec-asbestos strike 1949 mini-drama from a text brief + Quebec French monolingual subtitles. StoryAgent drafts the young-organizer / mining-town / Church-mediation meeting blueprint. ScreenplayAgent breaks it into Quebec-asbestos strike 1949 scenes. KeyFrameAgent plans keyframes for the mining-town diner / company picket line / Church-mediation hall settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Quebec French subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Quebec-asbestos strike 1949 story blueprint — young-organizer / mining-town / Church-mediation meeting arc.",
            "Decompose the young-organizer / mining-town / Church-mediation meeting arc into Quebec-asbestos strike 1949 scenes.",
            "Plan keyframes for the mining-town diner / company picket line / Church-mediation hall settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Quebec-asbestos strike 1949 visual continuity.",
            "Transcribe the Quebec French dialogue into timestamped subtitle segments.",
            "Composite the final Quebec-asbestos strike 1949 mini-drama mp4 with mixed audio and Quebec French subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Bengali-language Calcutta family-saga mini-drama about the youngest daughter returning for the patriarch's funeral and the inheritance decision that will reshape three generations, and Bengali subtitles.",
        "rationale": "Bengali Calcutta family-saga mini-drama from a text brief + Bengali monolingual subtitles. StoryAgent drafts the youngest-daughter / patriarch's-funeral / inheritance-decision blueprint. ScreenplayAgent breaks it into Bengali Calcutta family-saga scenes. KeyFrameAgent plans keyframes for the ancestral Calcutta home / Hooghly-river ghat / inheritance lawyer's office settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Bengali subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Bengali Calcutta family-saga story blueprint — youngest-daughter / patriarch's-funeral / inheritance-decision arc.",
            "Decompose the youngest-daughter / patriarch's-funeral / inheritance-decision arc into Bengali Calcutta family-saga scenes.",
            "Plan keyframes for the ancestral Calcutta home / Hooghly-river ghat / inheritance lawyer's office settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Bengali Calcutta family-saga visual continuity.",
            "Transcribe the Bengali dialogue into timestamped subtitle segments.",
            "Composite the final Bengali Calcutta family-saga mini-drama mp4 with mixed audio and Bengali subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Punjabi-language 1947-Partition mini-drama about a young mother carrying her infant across the new border on the midnight train that history later named for the violence on it, and Punjabi subtitles.",
        "rationale": "Punjabi 1947-Partition mini-drama from a text brief + Punjabi monolingual subtitles. ScreenplayAgent breaks it into Punjabi 1947-Partition scenes. KeyFrameAgent plans keyframes for the village home / midnight train station / partition-line refugee camp settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Punjabi subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Punjabi 1947-Partition story blueprint — young-mother / cross-border journey / midnight-line crossing arc.",
            "Decompose the young-mother / cross-border journey / midnight-line crossing arc into Punjabi 1947-Partition scenes.",
            "Plan keyframes for the village home / midnight train station / partition-line refugee camp settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Punjabi 1947-Partition visual continuity.",
            "Transcribe the Punjabi dialogue into timestamped subtitle segments.",
            "Composite the final Punjabi 1947-Partition mini-drama mp4 with mixed audio and Punjabi subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Tamil-language temple-festival mini-drama about a young priestess defending her temple's ritual against a rival clan's challenge during the annual festival procession, and Tamil subtitles.",
        "rationale": "Tamil temple-festival mini-drama from a text brief + Tamil monolingual subtitles. StoryAgent drafts the young-priestess / temple-festival / rival-clan ritual challenge blueprint. ScreenplayAgent breaks it into Tamil temple-festival scenes. KeyFrameAgent plans keyframes for the temple inner sanctum / festival procession route / rival-clan ritual ground settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Tamil subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Tamil temple-festival story blueprint — young-priestess / temple-festival / rival-clan ritual challenge arc.",
            "Decompose the young-priestess / temple-festival / rival-clan ritual challenge arc into Tamil temple-festival scenes.",
            "Plan keyframes for the temple inner sanctum / festival procession route / rival-clan ritual ground settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Tamil temple-festival visual continuity.",
            "Transcribe the Tamil dialogue into timestamped subtitle segments.",
            "Composite the final Tamil temple-festival mini-drama mp4 with mixed audio and Tamil subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Yoruba-language Ifá-prophecy mini-drama about a young Babalawo apprentice whose first divination predicts a calamity the village elders refuse to accept, and Yoruba subtitles.",
        "rationale": "Yoruba Ifá prophecy mini-drama from a text brief + Yoruba monolingual subtitles. StoryAgent drafts the young-Babalawo apprentice / dangerous-prophecy / village-elder confrontation blueprint. ScreenplayAgent breaks it into Yoruba Ifá prophecy scenes. KeyFrameAgent plans keyframes for the Babalawo's compound / village square / elder-council meeting hut settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Yoruba subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Yoruba Ifá prophecy story blueprint — young-Babalawo apprentice / dangerous-prophecy / village-elder confrontation arc.",
            "Decompose the young-Babalawo apprentice / dangerous-prophecy / village-elder confrontation arc into Yoruba Ifá prophecy scenes.",
            "Plan keyframes for the Babalawo's compound / village square / elder-council meeting hut settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Yoruba Ifá prophecy visual continuity.",
            "Transcribe the Yoruba dialogue into timestamped subtitle segments.",
            "Composite the final Yoruba Ifá prophecy mini-drama mp4 with mixed audio and Yoruba subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Swahili-language Mombasa-trader mini-drama about a young dhow trader fighting the port-master's seizure of her cargo on the day before her wedding, and Swahili subtitles.",
        "rationale": "Swahili Mombasa trader mini-drama from a text brief + Swahili monolingual subtitles. StoryAgent drafts the young-trader / dhow-cargo seizure / port-master confrontation blueprint. ScreenplayAgent breaks it into Swahili Mombasa trader scenes. KeyFrameAgent plans keyframes for the harbor warehouse / dhow deck / port-master office settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Swahili subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Swahili Mombasa trader story blueprint — young-trader / dhow-cargo seizure / port-master confrontation arc.",
            "Decompose the young-trader / dhow-cargo seizure / port-master confrontation arc into Swahili Mombasa trader scenes.",
            "Plan keyframes for the harbor warehouse / dhow deck / port-master office settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Swahili Mombasa trader visual continuity.",
            "Transcribe the Swahili dialogue into timestamped subtitle segments.",
            "Composite the final Swahili Mombasa trader mini-drama mp4 with mixed audio and Swahili subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce an Amharic-language Solomonic-court mini-drama about a young court scribe whose accidental discovery of a regicide plot puts her between the conspirator-uncle and the emperor she serves, and Amharic subtitles.",
        "rationale": "Amharic Solomonic-court mini-drama from a text brief + Amharic monolingual subtitles. StoryAgent drafts the young-court-scribe / regicide-plot / emperor's-audience reveal blueprint. ScreenplayAgent breaks it into Amharic Solomonic-court scenes. KeyFrameAgent plans keyframes for the Solomonic palace court / scribe's archive / emperor's audience hall settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Amharic subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Amharic Solomonic-court story blueprint — young-court-scribe / regicide-plot / emperor's-audience reveal arc.",
            "Decompose the young-court-scribe / regicide-plot / emperor's-audience reveal arc into Amharic Solomonic-court scenes.",
            "Plan keyframes for the Solomonic palace court / scribe's archive / emperor's audience hall settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Amharic Solomonic-court visual continuity.",
            "Transcribe the Amharic dialogue into timestamped subtitle segments.",
            "Composite the final Amharic Solomonic-court mini-drama mp4 with mixed audio and Amharic subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Maori-language iwi-confederation mini-drama about a young rangatira convincing rival iwi to form a pre-treaty alliance the night before the British envoys arrive, and Maori subtitles.",
        "rationale": "Maori iwi-confederation mini-drama from a text brief + Maori monolingual subtitles. StoryAgent drafts the young-rangatira / iwi-meeting / pre-treaty alliance decision blueprint. ScreenplayAgent breaks it into Maori iwi-confederation scenes. KeyFrameAgent plans keyframes for the marae meeting house / coastal beach negotiation / inland iwi-council fire settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Maori subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Maori iwi-confederation story blueprint — young-rangatira / iwi-meeting / pre-treaty alliance decision arc.",
            "Decompose the young-rangatira / iwi-meeting / pre-treaty alliance decision arc into Maori iwi-confederation scenes.",
            "Plan keyframes for the marae meeting house / coastal beach negotiation / inland iwi-council fire settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Maori iwi-confederation visual continuity.",
            "Transcribe the Maori dialogue into timestamped subtitle segments.",
            "Composite the final Maori iwi-confederation mini-drama mp4 with mixed audio and Maori subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Quechua-language Andean-rebellion mini-drama about a young leader rallying the village to a final stand against the Spanish encomendero who's been seizing tribute land, and Quechua subtitles.",
        "rationale": "Quechua Andean-rebellion mini-drama from a text brief + Quechua monolingual subtitles. StoryAgent drafts the young-Quechua-leader / Spanish-encomendero / rebellion-final stand blueprint. ScreenplayAgent breaks it into Quechua Andean-rebellion scenes. KeyFrameAgent plans keyframes for the Andean village / Spanish-encomendero hacienda / final-stand mountain pass settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Quechua subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Quechua Andean-rebellion story blueprint — young-Quechua-leader / Spanish-encomendero / rebellion-final stand arc.",
            "Decompose the young-Quechua-leader / Spanish-encomendero / rebellion-final stand arc into Quechua Andean-rebellion scenes.",
            "Plan keyframes for the Andean village / Spanish-encomendero hacienda / final-stand mountain pass settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Quechua Andean-rebellion visual continuity.",
            "Transcribe the Quechua dialogue into timestamped subtitle segments.",
            "Composite the final Quechua Andean-rebellion mini-drama mp4 with mixed audio and Quechua subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Navajo-language coming-of-age mini-drama about a young girl preparing for her kinaaldá ceremony as the elder who's supposed to lead it disagrees with her family on tradition, and Navajo subtitles.",
        "rationale": "Navajo coming-of-age mini-drama from a text brief + Navajo monolingual subtitles. StoryAgent drafts the young-girl / kinaaldá ceremony / family-elder confrontation blueprint. ScreenplayAgent breaks it into Navajo coming-of-age scenes. KeyFrameAgent plans keyframes for the family hogan / desert mesa / ceremony-ground hogan settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Navajo subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Navajo coming-of-age story blueprint — young-girl / kinaaldá ceremony / family-elder confrontation arc.",
            "Decompose the young-girl / kinaaldá ceremony / family-elder confrontation arc into Navajo coming-of-age scenes.",
            "Plan keyframes for the family hogan / desert mesa / ceremony-ground hogan settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Navajo coming-of-age visual continuity.",
            "Transcribe the Navajo dialogue into timestamped subtitle segments.",
            "Composite the final Navajo coming-of-age mini-drama mp4 with mixed audio and Navajo subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Lakota-language 1876 Black-Hills mini-drama about a young warrior the night before Little Bighorn, talking with her uncle who survived a previous fight, and Lakota subtitles.",
        "rationale": "Lakota Black-Hills resistance mini-drama from a text brief + Lakota monolingual subtitles. StoryAgent drafts the young-warrior / 1876 / Custer-engagement blueprint. ScreenplayAgent breaks it into Lakota Black-Hills resistance scenes. KeyFrameAgent plans keyframes for the Lakota encampment / Black-Hills ridge / Little-Bighorn-river battlefield settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Lakota subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Lakota Black-Hills resistance story blueprint — young-warrior / 1876 / Custer-engagement arc.",
            "Decompose the young-warrior / 1876 / Custer-engagement arc into Lakota Black-Hills resistance scenes.",
            "Plan keyframes for the Lakota encampment / Black-Hills ridge / Little-Bighorn-river battlefield settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Lakota Black-Hills resistance visual continuity.",
            "Transcribe the Lakota dialogue into timestamped subtitle segments.",
            "Composite the final Lakota Black-Hills resistance mini-drama mp4 with mixed audio and Lakota subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make an Inuktitut-language Arctic-hunter mini-drama about a young hunter taking her sick father's place on the seal hunt the community depends on, and Inuktitut subtitles.",
        "rationale": "Inuktitut Arctic-hunter family mini-drama from a text brief + Inuktitut monolingual subtitles. StoryAgent drafts the young-hunter / father's-illness / final-seal-hunt blueprint. ScreenplayAgent breaks it into Inuktitut Arctic-hunter family scenes. KeyFrameAgent plans keyframes for the snow-house / sea-ice hunting ground / community gathering hall settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Inuktitut subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Inuktitut Arctic-hunter family story blueprint — young-hunter / father's-illness / final-seal-hunt arc.",
            "Decompose the young-hunter / father's-illness / final-seal-hunt arc into Inuktitut Arctic-hunter family scenes.",
            "Plan keyframes for the snow-house / sea-ice hunting ground / community gathering hall settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Inuktitut Arctic-hunter family visual continuity.",
            "Transcribe the Inuktitut dialogue into timestamped subtitle segments.",
            "Composite the final Inuktitut Arctic-hunter family mini-drama mp4 with mixed audio and Inuktitut subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Welsh-language coal-mining mini-drama about a young miner's daughter testifying at the inquiry into the disaster that killed her brother, against the colliery owner who employed her father, and Welsh subtitles.",
        "rationale": "Welsh coal-mining village mini-drama from a text brief + Welsh monolingual subtitles. StoryAgent drafts the young-miner-daughter / pit-disaster / inquiry-confrontation blueprint. ScreenplayAgent breaks it into Welsh coal-mining village scenes. KeyFrameAgent plans keyframes for the miner's cottage / colliery pit-head / public-inquiry hall settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Welsh subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Welsh coal-mining village story blueprint — young-miner-daughter / pit-disaster / inquiry-confrontation arc.",
            "Decompose the young-miner-daughter / pit-disaster / inquiry-confrontation arc into Welsh coal-mining village scenes.",
            "Plan keyframes for the miner's cottage / colliery pit-head / public-inquiry hall settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Welsh coal-mining village visual continuity.",
            "Transcribe the Welsh dialogue into timestamped subtitle segments.",
            "Composite the final Welsh coal-mining village mini-drama mp4 with mixed audio and Welsh subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Catalan-language Spanish-Civil-War mini-drama about a young anarchist defending Barcelona's barricades for the final radio broadcast before fascist troops take the telegraph station, and Catalan subtitles.",
        "rationale": "Catalan Spanish-Civil-War Barcelona mini-drama from a text brief + Catalan monolingual subtitles. StoryAgent drafts the young-anarchist-fighter / Barcelona-barricades / final-stand telegraph station blueprint. ScreenplayAgent breaks it into Catalan Spanish-Civil-War Barcelona scenes. KeyFrameAgent plans keyframes for the Barcelona barricade / printing-press cellar / Catalonia telegraph station settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Catalan subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Catalan Spanish-Civil-War Barcelona story blueprint — young-anarchist-fighter / Barcelona-barricades / final-stand telegraph station arc.",
            "Decompose the young-anarchist-fighter / Barcelona-barricades / final-stand telegraph station arc into Catalan Spanish-Civil-War Barcelona scenes.",
            "Plan keyframes for the Barcelona barricade / printing-press cellar / Catalonia telegraph station settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Catalan Spanish-Civil-War Barcelona visual continuity.",
            "Transcribe the Catalan dialogue into timestamped subtitle segments.",
            "Composite the final Catalan Spanish-Civil-War Barcelona mini-drama mp4 with mixed audio and Catalan subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Basque-language Franco-era underground mini-drama about a young courier guiding a hunted political prisoner across the Basque mountain border to a French safe-house, and Basque subtitles.",
        "rationale": "Basque underground-resistance mini-drama from a text brief + Basque monolingual subtitles. StoryAgent drafts the young-courier / Franco-era / cross-border safe-house blueprint. ScreenplayAgent breaks it into Basque underground-resistance scenes. KeyFrameAgent plans keyframes for the Basque farmhouse / mountain-border path / cross-border safe-house settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Basque subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Basque underground-resistance story blueprint — young-courier / Franco-era / cross-border safe-house arc.",
            "Decompose the young-courier / Franco-era / cross-border safe-house arc into Basque underground-resistance scenes.",
            "Plan keyframes for the Basque farmhouse / mountain-border path / cross-border safe-house settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Basque underground-resistance visual continuity.",
            "Transcribe the Basque dialogue into timestamped subtitle segments.",
            "Composite the final Basque underground-resistance mini-drama mp4 with mixed audio and Basque subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Mongolian-language conquest mini-drama about a young officer in Genghis Khan's army on the morning the Khwarezmian city falls — and what she sees that changes her, and Mongolian subtitles.",
        "rationale": "Mongolian conquest siege mini-drama from a text brief + Mongolian monolingual subtitles. StoryAgent drafts the young-officer / Khwarezm-siege / city-fall morning blueprint. ScreenplayAgent breaks it into Mongolian conquest siege scenes. KeyFrameAgent plans keyframes for the siege encampment / siege-tower platform / fallen-city street settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Mongolian subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Mongolian conquest siege story blueprint — young-officer / Khwarezm-siege / city-fall morning arc.",
            "Decompose the young-officer / Khwarezm-siege / city-fall morning arc into Mongolian conquest siege scenes.",
            "Plan keyframes for the siege encampment / siege-tower platform / fallen-city street settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Mongolian conquest siege visual continuity.",
            "Transcribe the Mongolian dialogue into timestamped subtitle segments.",
            "Composite the final Mongolian conquest siege mini-drama mp4 with mixed audio and Mongolian subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Tibetan-language monastery-defense mini-drama about a young warrior-monk forced to break her vow to defend the monastery from a rival army's siege, and Tibetan subtitles.",
        "rationale": "Tibetan-monastery defense mini-drama from a text brief + Tibetan monolingual subtitles. StoryAgent drafts the young-warrior-monk / rival-army siege / final-defense temple blueprint. ScreenplayAgent breaks it into Tibetan-monastery defense scenes. KeyFrameAgent plans keyframes for the monastery courtyard / mountain pass / temple inner-defense hall settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Tibetan subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Tibetan-monastery defense story blueprint — young-warrior-monk / rival-army siege / final-defense temple arc.",
            "Decompose the young-warrior-monk / rival-army siege / final-defense temple arc into Tibetan-monastery defense scenes.",
            "Plan keyframes for the monastery courtyard / mountain pass / temple inner-defense hall settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Tibetan-monastery defense visual continuity.",
            "Transcribe the Tibetan dialogue into timestamped subtitle segments.",
            "Composite the final Tibetan-monastery defense mini-drama mp4 with mixed audio and Tibetan subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Dzongkha-language Bhutanese archery mini-drama about a young archer-girl shooting in a royal festival against the men's-only archers who tried to ban her entry, and Dzongkha subtitles.",
        "rationale": "Bhutanese archery contest mini-drama from a text brief + Dzongkha monolingual subtitles. StoryAgent drafts the young-archer-girl / royal-archery festival / final-arrow standoff blueprint. ScreenplayAgent breaks it into Bhutanese archery contest scenes. KeyFrameAgent plans keyframes for the village archery field / royal-pavilion / final-target line settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Dzongkha subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Bhutanese archery contest story blueprint — young-archer-girl / royal-archery festival / final-arrow standoff arc.",
            "Decompose the young-archer-girl / royal-archery festival / final-arrow standoff arc into Bhutanese archery contest scenes.",
            "Plan keyframes for the village archery field / royal-pavilion / final-target line settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Bhutanese archery contest visual continuity.",
            "Transcribe the Dzongkha dialogue into timestamped subtitle segments.",
            "Composite the final Bhutanese archery contest mini-drama mp4 with mixed audio and Dzongkha subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Khmer-language Angkor-court mini-drama about a young court-dancer whose ritual-dance debut is also her king's coded acceptance of her family's political alliance, and Khmer subtitles.",
        "rationale": "Khmer Angkor-court mini-drama from a text brief + Khmer monolingual subtitles. StoryAgent drafts the young-court-dancer / king-courtship / ritual-dance debut blueprint. ScreenplayAgent breaks it into Khmer Angkor-court scenes. KeyFrameAgent plans keyframes for the Angkor temple complex / royal palace audience hall / ritual-dance platform settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Khmer subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Khmer Angkor-court story blueprint — young-court-dancer / king-courtship / ritual-dance debut arc.",
            "Decompose the young-court-dancer / king-courtship / ritual-dance debut arc into Khmer Angkor-court scenes.",
            "Plan keyframes for the Angkor temple complex / royal palace audience hall / ritual-dance platform settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Khmer Angkor-court visual continuity.",
            "Transcribe the Khmer dialogue into timestamped subtitle segments.",
            "Composite the final Khmer Angkor-court mini-drama mp4 with mixed audio and Khmer subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Burmese-language pagoda-festival mini-drama about a young novice monk whose festival-day return home forces her family to confront the truth they sent her to the monastery to avoid, and Burmese subtitles.",
        "rationale": "Burmese pagoda-festival mini-drama from a text brief + Burmese monolingual subtitles. StoryAgent drafts the young-novice-monk / pagoda-festival / family-truth confrontation blueprint. ScreenplayAgent breaks it into Burmese pagoda-festival scenes. KeyFrameAgent plans keyframes for the monastery quarters / festival pagoda plaza / family courtyard settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Burmese subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Burmese pagoda-festival story blueprint — young-novice-monk / pagoda-festival / family-truth confrontation arc.",
            "Decompose the young-novice-monk / pagoda-festival / family-truth confrontation arc into Burmese pagoda-festival scenes.",
            "Plan keyframes for the monastery quarters / festival pagoda plaza / family courtyard settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Burmese pagoda-festival visual continuity.",
            "Transcribe the Burmese dialogue into timestamped subtitle segments.",
            "Composite the final Burmese pagoda-festival mini-drama mp4 with mixed audio and Burmese subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce a Sinhala-language Sri-Lanka fishing-village mini-drama about a young fisherwoman whose failing catch puts her in front of the village-elder council demanding her family's debt, and Sinhala subtitles.",
        "rationale": "Sinhala Sri-Lanka fishing-village mini-drama from a text brief + Sinhala monolingual subtitles. StoryAgent drafts the young-fisherwoman / failing-catch / village-debt confrontation blueprint. ScreenplayAgent breaks it into Sinhala Sri-Lanka fishing-village scenes. KeyFrameAgent plans keyframes for the fishing-village dock / open-sea fishing ground / village-elder council porch settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Sinhala subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Sinhala Sri-Lanka fishing-village story blueprint — young-fisherwoman / failing-catch / village-debt confrontation arc.",
            "Decompose the young-fisherwoman / failing-catch / village-debt confrontation arc into Sinhala Sri-Lanka fishing-village scenes.",
            "Plan keyframes for the fishing-village dock / open-sea fishing ground / village-elder council porch settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Sinhala Sri-Lanka fishing-village visual continuity.",
            "Transcribe the Sinhala dialogue into timestamped subtitle segments.",
            "Composite the final Sinhala Sri-Lanka fishing-village mini-drama mp4 with mixed audio and Sinhala subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Make a Filipino-language 1896 revolution mini-drama about a young katipunera firing the battery at Manila Bay against the Spanish gunboat, and Filipino subtitles.",
        "rationale": "Filipino Philippine-revolution mini-drama from a text brief + Filipino monolingual subtitles. StoryAgent drafts the young-katipunera / 1896 / Manila Bay final-stand blueprint. ScreenplayAgent breaks it into Filipino Philippine-revolution scenes. KeyFrameAgent plans keyframes for the Manila Katipunan house / Bonifacio cry-of-Pugad-Lawin clearing / Manila Bay battery settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Filipino subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Filipino Philippine-revolution story blueprint — young-katipunera / 1896 / Manila Bay final-stand arc.",
            "Decompose the young-katipunera / 1896 / Manila Bay final-stand arc into Filipino Philippine-revolution scenes.",
            "Plan keyframes for the Manila Katipunan house / Bonifacio cry-of-Pugad-Lawin clearing / Manila Bay battery settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Filipino Philippine-revolution visual continuity.",
            "Transcribe the Filipino dialogue into timestamped subtitle segments.",
            "Composite the final Filipino Philippine-revolution mini-drama mp4 with mixed audio and Filipino subtitles overlaid.",
        ],
    },
    {
        "user_goal": "Produce an Indonesian-language batik-master mini-drama about a young apprentice helping her dying master complete the royal-court commission that will define his legacy and her right to inherit his workshop, and Indonesian subtitles.",
        "rationale": "Indonesian batik-master apprentice mini-drama from a text brief + Indonesian monolingual subtitles. StoryAgent drafts the young-apprentice / dying-master / final-batik signature blueprint. ScreenplayAgent breaks it into Indonesian batik-master apprentice scenes. KeyFrameAgent plans keyframes for the batik workshop / market batik-stall / royal-court presentation hall settings from text alone. VideoAgent assembles the multi-shot film. TranscriptionAgent extracts Indonesian subtitles from the dialogue audio. CompositorAgent muxes the final mp4 with subtitle overlay. Reject TranslationAgent (monolingual subtitles, not bilingual), VideoAnalysisAgent / IntakeVideoAgent / StyleTransferAgent / VideoExtendAgent / HighlightAgent (no video uploaded), NarrationAgent / IllustrationAgent / NarratorAgent (not a slideshow / illustrated-storytelling format). Chain: Story → Screenplay → KeyFrame → Video → Transcription → Compositor → done.",
        "intents": [
            "Draft the Indonesian batik-master apprentice story blueprint — young-apprentice / dying-master / final-batik signature arc.",
            "Decompose the young-apprentice / dying-master / final-batik signature arc into Indonesian batik-master apprentice scenes.",
            "Plan keyframes for the batik workshop / market batik-stall / royal-court presentation hall settings; text-only generation, no reference images supplied.",
            "Render per-shot clips preserving Indonesian batik-master apprentice visual continuity.",
            "Transcribe the Indonesian dialogue into timestamped subtitle segments.",
            "Composite the final Indonesian batik-master apprentice mini-drama mp4 with mixed audio and Indonesian subtitles overlaid.",
        ],
    },
]
