"""GRPO shape: style_only — IntakeVideo → StyleTransfer.

50 samples (target_n=50). Style-transfer on uploaded video, raw output as deliverable.
"""
from __future__ import annotations


def _make(topic, style):
    return {
        "rationale": (
            f"{topic} clip + {style} style-transfer request. Raw style-transferred "
            "output is the deliverable — no audio overlay, no subtitle, no length change."
        ),
        "intents": [
            f"Ingest the user's uploaded {topic} clip into the workspace.",
            f"Apply {style} style transfer to the {topic} clip and output the restyled video.",
        ],
    }


SAMPLES: list[dict] = [
    {**_make("vacation beach", "watercolor painting"),
     "user_goal": "Apply a watercolor-painting style transfer to my vacation beach clip."},
    {**_make("birthday party", "Pixar-3D animation"),
     "user_goal": "Restyle my birthday-party video in Pixar-3D animation style."},
    {**_make("street-food market", "Studio-Ghibli anime"),
     "user_goal": "Re-render my street-food market video in Studio-Ghibli anime style."},
    {**_make("graduation ceremony", "oil-painting Impressionist"),
     "user_goal": "Apply an oil-painting Impressionist style transfer to my graduation ceremony clip."},
    {**_make("city-tour", "ink-wash Chinese-painting"),
     "user_goal": "Restyle my city-tour video in ink-wash Chinese-painting style."},
    {**_make("hiking trail", "Bob-Ross-style oil-painting"),
     "user_goal": "Apply Bob-Ross-style oil-painting style transfer to my hiking trail clip."},
    {**_make("dance recital", "comic-book ink-and-color"),
     "user_goal": "Re-render my dance recital video in comic-book ink-and-color style."},
    {**_make("concert footage", "neon-cyberpunk"),
     "user_goal": "Apply a neon-cyberpunk style transfer to my concert footage."},
    {**_make("wedding ceremony", "vintage-1950s Technicolor"),
     "user_goal": "Restyle my wedding ceremony video in vintage-1950s Technicolor style."},
    {**_make("cooking demo", "1970s home-movie grain"),
     "user_goal": "Apply a 1970s home-movie grain style transfer to my cooking demo."},
    {**_make("yoga session", "Japanese-ukiyo-e woodblock"),
     "user_goal": "Re-render my yoga session video in Japanese-ukiyo-e woodblock style."},
    {**_make("road-trip", "Wes-Anderson-pastel"),
     "user_goal": "Apply a Wes-Anderson-pastel style transfer to my road-trip video."},
    {**_make("baby's first steps", "soft-watercolor children's-book"),
     "user_goal": "Restyle my baby's-first-steps clip in soft-watercolor children's-book style."},
    {**_make("museum tour", "Renaissance-fresco"),
     "user_goal": "Apply a Renaissance-fresco style transfer to my museum tour clip."},
    {**_make("gym workout", "graphic-novel halftone"),
     "user_goal": "Re-render my gym workout video in graphic-novel halftone style."},
    {**_make("autumn-leaves walk", "Monet-Impressionist"),
     "user_goal": "Apply a Monet-Impressionist style transfer to my autumn-leaves walk video."},
    {**_make("ski-trip", "Andy-Warhol pop-art"),
     "user_goal": "Restyle my ski-trip clip in Andy-Warhol pop-art style."},
    {**_make("coastal drone footage", "Salvador-Dalí surrealist"),
     "user_goal": "Apply a Salvador-Dalí surrealist style transfer to my coastal drone footage."},
    {**_make("backyard barbecue", "Norman-Rockwell-Americana"),
     "user_goal": "Re-render my backyard barbecue video in Norman-Rockwell-Americana style."},
    {**_make("fishing trip", "Hokusai-wave woodblock"),
     "user_goal": "Apply a Hokusai-wave woodblock style transfer to my fishing trip clip."},
    {**_make("Christmas-morning", "Hallmark-card watercolor"),
     "user_goal": "Restyle my Christmas-morning clip in Hallmark-card watercolor style."},
    {**_make("snowboarding", "comic-book Frank-Miller noir"),
     "user_goal": "Apply a Frank-Miller-comic-book noir style transfer to my snowboarding video."},
    {**_make("aquarium visit", "stained-glass cathedral"),
     "user_goal": "Re-render my aquarium visit clip in stained-glass cathedral style."},
    {**_make("garden tour", "Beatrix-Potter watercolor"),
     "user_goal": "Apply a Beatrix-Potter watercolor style transfer to my garden tour video."},
    {**_make("volunteer-work footage", "documentary-film black-and-white"),
     "user_goal": "Restyle my volunteer-work footage in documentary-film black-and-white style."},
    {**_make("amusement-park ride", "Saturday-morning-cartoon"),
     "user_goal": "Apply a Saturday-morning-cartoon style transfer to my amusement-park ride clip."},
    {**_make("first-day-of-school", "low-poly geometric"),
     "user_goal": "Re-render my first-day-of-school video in low-poly geometric style."},
    {**_make("autumn-pumpkin-patch", "Edward-Hopper Americana"),
     "user_goal": "Apply an Edward-Hopper Americana style transfer to my autumn-pumpkin-patch video."},
    {**_make("ice-rink skating", "vintage-Disney 1940s"),
     "user_goal": "Restyle my ice-rink skating clip in vintage-Disney 1940s style."},
    {**_make("hot-air-balloon ride", "art-nouveau Mucha"),
     "user_goal": "Apply an art-nouveau Mucha style transfer to my hot-air-balloon ride clip."},
    {**_make("hiking summit", "Caspar-David-Friedrich Romantic"),
     "user_goal": "Re-render my hiking-summit footage in Caspar-David-Friedrich Romantic painting style."},
    {**_make("urban-skyline night", "Vincent-van-Gogh post-Impressionist"),
     "user_goal": "Apply a Vincent-van-Gogh post-Impressionist style transfer to my urban-skyline night video."},
    {**_make("flower-show", "art-deco poster"),
     "user_goal": "Restyle my flower-show video in art-deco poster style."},
    {**_make("kayaking trip", "Jean-Honoré-Fragonard Rococo"),
     "user_goal": "Apply a Rococo Fragonard style transfer to my kayaking trip clip."},
    {**_make("airport-tarmac", "1980s-VHS retro"),
     "user_goal": "Re-render my airport-tarmac footage in 1980s-VHS retro style."},
    {**_make("morning-fog forest", "Sumi-e brush-painting"),
     "user_goal": "Apply a Sumi-e brush-painting style transfer to my morning-fog forest video."},
    {**_make("ferry crossing", "Turner Romantic-seascape"),
     "user_goal": "Restyle my ferry-crossing clip in Turner Romantic-seascape style."},
    {**_make("desert sunrise", "Frederic-Remington Western"),
     "user_goal": "Apply a Frederic-Remington Western style transfer to my desert-sunrise video."},
    {**_make("rooftop party", "Fauvist bold-color"),
     "user_goal": "Re-render my rooftop-party clip in Fauvist bold-color style."},
    {**_make("vineyard tour", "Tuscan-Renaissance landscape"),
     "user_goal": "Apply a Tuscan-Renaissance landscape style transfer to my vineyard tour video."},
    {**_make("subway commute", "moody graphic-novel"),
     "user_goal": "Restyle my subway-commute clip in moody graphic-novel style."},
    {**_make("art-fair walkthrough", "Henri-Matisse cut-out"),
     "user_goal": "Apply a Henri-Matisse cut-out style transfer to my art-fair walkthrough video."},
    {**_make("highway-night drive", "synthwave 80s"),
     "user_goal": "Re-render my highway-night-drive video in synthwave 80s style."},
    {**_make("library reading", "Renaissance-illuminated-manuscript"),
     "user_goal": "Apply a Renaissance-illuminated-manuscript style transfer to my library-reading clip."},
    {**_make("playground walk", "Eric-Carle collage"),
     "user_goal": "Restyle my playground-walk video in Eric-Carle collage style."},
    {**_make("pier-fishing", "Winslow-Homer maritime"),
     "user_goal": "Apply a Winslow-Homer maritime style transfer to my pier-fishing clip."},
    {**_make("street-art tour", "Banksy stencil-style"),
     "user_goal": "Re-render my street-art tour clip in Banksy stencil-style."},
    {**_make("birthday-cake reveal", "Suzy-Lee picture-book"),
     "user_goal": "Apply a Suzy-Lee picture-book style transfer to my birthday-cake-reveal video."},
    {**_make("airport-arrival", "Jacob-Lawrence migration-series"),
     "user_goal": "Restyle my airport-arrival clip in Jacob-Lawrence migration-series style."},
    {**_make("forest-cabin getaway", "Bavarian-folk-art"),
     "user_goal": "Apply a Bavarian-folk-art style transfer to my forest-cabin-getaway video."},
    {**_make("scuba diving", "stained-glass aquatic"),
     "user_goal": "Re-render my scuba-diving footage in stained-glass aquatic style."},
]
