"""x15 highlight_subtitle GRPO short briefs. Disjoint from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 2-hour podcast interview — please cut a highlight reel and add English subtitles.",
    "Here's a 90-minute book-launch event — extract the highlight Q&A moments and overlay English captions.",
    "I have a 3-hour online-course recording — please pull the highlight teaching moments and add English subtitles.",
    "Uploading a 90-minute MasterClass-style lesson — extract the highlight clips and overlay English captions.",
    "Here's a 4-hour Coursera-MOOC lecture — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour Khan-Academy walkthrough — pull the highlights and overlay English captions.",
    "Uploading a 3-hour Skillshare-tutorial — please extract the highlight exercises and add English subtitles.",
    "Here's a 90-minute YouTube-Live Q&A session — cut a highlight reel and overlay English captions.",
    "I have a 2-hour Twitch-IRL stream — please pull the highlight moments and add English subtitles.",
    "Uploading a 4-hour Reddit-AMA recording — extract the highlight questions and overlay English captions.",
    "Here's a 90-minute Discord-AMA recording — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour Twitter-Spaces recording — pull the highlight moments and overlay English captions.",
    "Uploading a 3-hour Clubhouse-room recording — please extract the highlight exchanges and add English subtitles.",
    "Here's a 90-minute LinkedIn-live event — cut a highlight reel and overlay English captions.",
    "I have a 2-hour Zoom-webinar recording — please pull the highlight moments and add English subtitles.",
    "Uploading a 4-hour Microsoft-Teams all-hands — extract the highlight announcements and overlay English captions.",
    "Here's a 90-minute Slack-huddle recording — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour Google-Meet workshop — pull the highlight teaching moments and overlay English captions.",
    "Uploading a 3-hour BlueJeans-conference recording — please extract the highlight panels and add English subtitles.",
    "Here's a 90-minute Webex-Town-Hall — cut a highlight reel and overlay English captions.",
    "I have a 2-hour StreamYard-LiveStream — please pull the highlight moments and add English subtitles.",
    "Uploading a 4-hour Riverside-FM podcast recording — extract the highlight chapters and overlay English captions.",
    "Here's a 90-minute Otter-AI transcribed meeting — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour SquadCast-podcast recording — pull the highlight moments and overlay English captions.",
    "Uploading a 3-hour Anchor-podcast episode — please extract the highlight chapters and add English subtitles.",
    "Here's a 90-minute Spotify-podcast extended interview — cut a highlight reel and overlay English captions.",
    "I have a 2-hour Apple-podcast interview — please pull the highlight quotes and add English subtitles.",
    "Uploading a 4-hour Audible-original audiobook recording — extract the highlight chapters and overlay English captions.",
    "Here's a 90-minute Substack-Live event — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour Patreon-creator-Q&A — pull the highlight moments and overlay English captions.",
    "Uploading a 3-hour Buy-Me-a-Coffee creator stream — please extract the highlight exchanges and add English subtitles.",
    "Here's a 90-minute Kickstarter-AMA — cut a highlight reel and overlay English captions.",
    "I have a 2-hour IndieGoGo-creator-stream — please pull the highlight moments and add English subtitles.",
    "Uploading a 4-hour ProductHunt-launch livestream — extract the highlight pitches and overlay English captions.",
    "Here's a 90-minute Y-Combinator-demo-day — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour TechCrunch-Disrupt panel — pull the highlight moments and overlay English captions.",
    "Uploading a 3-hour Web-Summit-conference recording — please extract the highlight talks and add English subtitles.",
    "Here's a 90-minute SXSW-panel discussion — cut a highlight reel and overlay English captions.",
    "I have a 2-hour Davos-WEF panel — please pull the highlight quotes and add English subtitles.",
    "Uploading a 4-hour Aspen-Ideas Festival panel — extract the highlight talks and overlay English captions.",
    "Here's a 90-minute Code-Conference fireside — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour DLD-conference panel — pull the highlight moments and overlay English captions.",
    "Uploading a 3-hour AllThingsD-conference panel — please extract the highlight quotes and add English subtitles.",
    "Here's a 90-minute Web-Summit-fireside — cut a highlight reel and overlay English captions.",
    "I have a 2-hour Cannes-Lions panel — please pull the highlight pitches and add English subtitles.",
    "Uploading a 4-hour Sundance-Film-Festival panel — extract the highlight talks and overlay English captions.",
    "Here's a 90-minute SXSW-Music keynote — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour Coachella-onstage Q&A — pull the highlight quotes and overlay English captions.",
    "Uploading a 3-hour Bonnaroo-onstage chat — please extract the highlight quotes and add English subtitles.",
    "Here's a 90-minute Lollapalooza-keynote — cut a highlight reel and overlay English captions.",
    # ── more highlight reels with monolingual subtitles (50) ──────────────
    "Uploading a 3-hour Glastonbury-festival mainstage recording — please cut a highlight reel and add English subtitles.",
    "Here's a 4-hour Roskilde-festival mainstage recording — extract the highlight performances and overlay English captions.",
    "I have a 2-hour Outside-Lands festival recording — please pull the highlight sets and add English subtitles.",
    "Uploading a 90-minute Burning-Man-art-talk recording — extract the highlight discussions and overlay English captions.",
    "Here's a 4-hour Reading-and-Leeds festival recording — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour Tomorrowland mainstage recording — pull the highlight DJ sets and overlay English captions.",
    "Uploading a 3-hour Ultra-Music-Festival recording — please extract the highlight sets and add English subtitles.",
    "Here's a 90-minute Rolling-Loud rapper-onstage chat — cut a highlight reel and overlay English captions.",
    "I have a 2-hour Pitchfork-Music-Festival recording — please pull the highlight performances and add English subtitles.",
    "Uploading a 3-hour Newport-Folk-Festival recording — extract the highlight singer-songwriter sets and overlay English captions.",
    "Here's a 90-minute Berlinale press-conference — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour Venice-Film-Festival press-day — pull the highlight Q&A moments and overlay English captions.",
    "Uploading a 3-hour Toronto-TIFF director-panel — please extract the highlight exchanges and add English subtitles.",
    "Here's a 90-minute Tribeca-Film-Festival press-day — cut a highlight reel and overlay English captions.",
    "I have a 2-hour Telluride-Film-Festival panel — please pull the highlight quotes and add English subtitles.",
    "Uploading a 4-hour Karlovy-Vary Film-Festival press-day — extract the highlight Q&A moments and overlay English captions.",
    "Here's a 90-minute Locarno-Film-Festival panel — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour Busan-International-Film-Festival press-day — pull the highlight quotes and overlay English captions.",
    "Uploading a 3-hour Edinburgh-International-Film-Festival panel — please extract the highlight Q&A moments and add English subtitles.",
    "Here's a 90-minute Rotterdam-International-Film-Festival panel — cut a highlight reel and overlay English captions.",
    "I have a 3-hour Joe-Rogan-Experience interview — please pull the highlight moments and add English subtitles.",
    "Uploading a 4-hour Lex-Fridman-Podcast deep-dive — extract the highlight quotes and overlay English captions.",
    "Here's a 2-hour Tim-Ferriss-Show interview — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 3-hour Huberman-Lab episode — pull the highlight protocols and overlay English captions.",
    "Uploading a 90-minute Diary-of-a-CEO interview — please extract the highlight stories and add English subtitles.",
    "Here's a 2-hour SmartLess podcast episode — cut a highlight reel and overlay English captions.",
    "I have a 90-minute Armchair-Expert interview — please pull the highlight exchanges and add English subtitles.",
    "Uploading a 2-hour Stuff-You-Should-Know episode — extract the highlight explanations and overlay English captions.",
    "Here's a 3-hour Marc-Maron-WTF interview — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 90-minute Conan-Needs-a-Friend interview — pull the highlight jokes and overlay English captions.",
    "Uploading a 4-hour League-of-Legends-Worlds final — please extract the highlight team-fights and add English subtitles.",
    "Here's a 3-hour Dota-International grand-final — cut a highlight reel and overlay English captions.",
    "I have a 2-hour CS:GO-Major grand-final — please pull the highlight rounds and add English subtitles.",
    "Uploading a 90-minute Fortnite-World-Cup final — extract the highlight plays and overlay English captions.",
    "Here's a 4-hour Overwatch-League grand-final — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour Oscars-press-conference recording — pull the highlight quotes and overlay English captions.",
    "Uploading a 90-minute Emmys-after-show panel — please extract the highlight moments and add English subtitles.",
    "Here's a 3-hour Grammys-media-Q&A — cut a highlight reel and overlay English captions.",
    "I have a 2-hour Golden-Globes-press-room recording — please pull the highlight quotes and add English subtitles.",
    "Uploading a 90-minute BAFTA-press-conference — extract the highlight Q&A moments and overlay English captions.",
    "Here's a 2-hour Hillsong-Sunday-service livestream — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 3-hour Joel-Osteen Lakewood-Church livestream — pull the highlight sermon moments and overlay English captions.",
    "Uploading a 4-hour Bethel-Church Sunday-service livestream — please extract the highlight worship moments and add English subtitles.",
    "Here's a 90-minute Saddleback-Church Sunday-service livestream — cut a highlight reel and overlay English captions.",
    "I have a 2-hour Life-Church-livestream recording — please pull the highlight teaching moments and add English subtitles.",
    "Uploading a 3-hour edX-course-recording — extract the highlight lessons and overlay English captions.",
    "Here's a 4-hour Udacity-Nanodegree-lecture series — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour Codecademy-bootcamp recording — pull the highlight exercises and overlay English captions.",
    "Uploading a 90-minute Pluralsight-course recording — please extract the highlight modules and add English subtitles.",
    "Here's a 3-hour Brilliant.org masterclass recording — cut a highlight reel and overlay English captions.",
    # ── more long video + highlight reel + monolingual subtitles (50) ──────
    "Uploading a 90-minute tech-startup AMA livestream — please cut a highlight reel and add English subtitles.",
    "Here's a 2-hour crypto-conference panel — extract the highlight discussions and overlay English captions.",
    "I have a 3-hour NFT-summit keynote — please pull the highlight reveals and add English subtitles.",
    "Uploading a 90-minute blockchain-developer meetup — extract the highlight talks and overlay English captions.",
    "Here's a 4-hour fintech-conference keynote — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour SaaS-summit panel — pull the highlight talks and overlay English captions.",
    "Uploading a 3-hour women-in-tech panel — please extract the highlight discussions and add English subtitles.",
    "Here's a 90-minute diversity-in-tech panel — cut a highlight reel and overlay English captions.",
    "I have a 2-hour Black-tech panel — please pull the highlight stories and add English subtitles.",
    "Uploading a 4-hour Latina-in-tech panel — extract the highlight moments and overlay English captions.",
    "Here's a 90-minute LGBTQ+-tech panel — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour Veterans-in-tech panel — pull the highlight discussions and overlay English captions.",
    "Uploading a 3-hour Disability-tech panel — please extract the highlight stories and add English subtitles.",
    "Here's a 90-minute AI-safety panel — cut a highlight reel and overlay English captions.",
    "I have a 2-hour AI-ethics conference — please pull the highlight talks and add English subtitles.",
    "Uploading a 4-hour Effective-Altruism conference — extract the highlight talks and overlay English captions.",
    "Here's a 90-minute Less-Wrong meetup — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour EA-Global summit — pull the highlight talks and overlay English captions.",
    "Uploading a 3-hour AI-alignment workshop — please extract the highlight talks and add English subtitles.",
    "Here's a 90-minute open-source maintainers' summit — cut a highlight reel and overlay English captions.",
    "I have a 2-hour Linux-kernel-developer summit — please pull the highlight talks and add English subtitles.",
    "Uploading a 4-hour PyData conference — extract the highlight talks and overlay English captions.",
    "Here's a 90-minute useR! R-conference — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour SciPy conference — pull the highlight talks and overlay English captions.",
    "Uploading a 3-hour JuliaCon — please extract the highlight talks and add English subtitles.",
    "Here's a 90-minute RustWeek talks — cut a highlight reel and overlay English captions.",
    "I have a 2-hour WWDC keynote — please pull the highlight reveals and add English subtitles.",
    "Uploading a 4-hour WWDC State-of-the-Union — extract the highlight reveals and overlay English captions.",
    "Here's a 90-minute WWDC platform-state-of-the-union — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour Apple Vision-Pro launch — pull the highlight demos and overlay English captions.",
    "Uploading a 3-hour Meta Connect keynote — please extract the highlight reveals and add English subtitles.",
    "Here's a 90-minute Meta Reality-Labs presentation — cut a highlight reel and overlay English captions.",
    "I have a 2-hour Snap Partner-Summit — please pull the highlight reveals and add English subtitles.",
    "Uploading a 4-hour TikTok TikTokWorld panel — extract the highlight talks and overlay English captions.",
    "Here's a 90-minute YouTube Brandcast keynote — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour Twitch TwitchCon main-stage — pull the highlight moments and overlay English captions.",
    "Uploading a 3-hour Reddit Recap conference — please extract the highlight panels and add English subtitles.",
    "Here's a 90-minute Discord HackWeek presentations — cut a highlight reel and overlay English captions.",
    "I have a 2-hour Slack Dreamforce track — please pull the highlight talks and add English subtitles.",
    "Uploading a 4-hour Notion Make-or-Break panel — extract the highlight talks and overlay English captions.",
    "Here's a 90-minute Figma Config keynote — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour Sketch Layers conference — pull the highlight talks and overlay English captions.",
    "Uploading a 3-hour Adobe MAX Sneaks — please extract the highlight reveals and add English subtitles.",
    "Here's a 90-minute Cinema-4D conference — cut a highlight reel and overlay English captions.",
    "I have a 2-hour Houdini-User-Group meetup — please pull the highlight talks and add English subtitles.",
    "Uploading a 4-hour Blender-Conference talk — extract the highlight talks and overlay English captions.",
    "Here's a 90-minute Unity-GDC panel — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour Unreal-Engine summit — pull the highlight reveals and overlay English captions.",
    "Uploading a 3-hour Roblox-Developer-Conference — please extract the highlight talks and add English subtitles.",
    "Here's a 90-minute Epic-Online-Services summit — cut a highlight reel and overlay English captions.",
    # ── more long video + highlight reel + monolingual subtitles (50) ──────
    "Uploading a 90-minute ASMR-livestream — please cut a highlight reel and add English subtitles.",
    "Here's a 2-hour mukbang livestream — extract the highlight bites and overlay English captions.",
    "I have a 3-hour cooking-livestream — please pull the highlight steps and add English subtitles.",
    "Uploading a 90-minute crochet-livestream — extract the highlight stitches and overlay English captions.",
    "Here's a 4-hour knitting-livestream — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour art-streaming session — pull the highlight strokes and overlay English captions.",
    "Uploading a 3-hour drawing-stream — please extract the highlight sketches and add English subtitles.",
    "Here's a 90-minute painting-livestream — cut a highlight reel and overlay English captions.",
    "I have a 2-hour Twitch-IRL Outside-Broadcast stream — please pull the highlight moments and add English subtitles.",
    "Uploading a 4-hour Just-Chatting stream — extract the highlight quips and overlay English captions.",
    "Here's a 90-minute variety-streamer marathon — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour talkshow-podcast — pull the highlight quotes and overlay English captions.",
    "Uploading a 3-hour interview-podcast — please extract the highlight stories and add English subtitles.",
    "Here's a 90-minute tech-podcast episode — cut a highlight reel and overlay English captions.",
    "I have a 2-hour health-podcast episode — please pull the highlight tips and add English subtitles.",
    "Uploading a 4-hour business-podcast — extract the highlight insights and overlay English captions.",
    "Here's a 90-minute crypto-podcast episode — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour AI-podcast episode — pull the highlight predictions and overlay English captions.",
    "Uploading a 3-hour data-science podcast — please extract the highlight techniques and add English subtitles.",
    "Here's a 90-minute machine-learning podcast — cut a highlight reel and overlay English captions.",
    "I have a 2-hour design-podcast episode — please pull the highlight critiques and add English subtitles.",
    "Uploading a 4-hour game-design podcast — extract the highlight talks and overlay English captions.",
    "Here's a 90-minute UX-podcast episode — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour UI-podcast episode — pull the highlight critiques and overlay English captions.",
    "Uploading a 3-hour typography-podcast episode — please extract the highlight typesetting tips and add English subtitles.",
    "Here's a 90-minute film-podcast episode — cut a highlight reel and overlay English captions.",
    "I have a 2-hour TV-podcast episode — please pull the highlight recaps and add English subtitles.",
    "Uploading a 4-hour anime-podcast episode — extract the highlight reviews and overlay English captions.",
    "Here's a 90-minute comics-podcast episode — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour literature-podcast episode — pull the highlight readings and overlay English captions.",
    "Uploading a 3-hour science-fiction-podcast — please extract the highlight discussions and add English subtitles.",
    "Here's a 90-minute fantasy-podcast episode — cut a highlight reel and overlay English captions.",
    "I have a 2-hour horror-podcast episode — please pull the highlight stories and add English subtitles.",
    "Uploading a 4-hour mystery-podcast episode — extract the highlight clues and overlay English captions.",
    "Here's a 90-minute true-crime podcast — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour paranormal-podcast — pull the highlight encounters and overlay English captions.",
    "Uploading a 3-hour UFO-podcast episode — please extract the highlight sightings and add English subtitles.",
    "Here's a 90-minute cryptid-podcast episode — cut a highlight reel and overlay English captions.",
    "I have a 2-hour archaeology-podcast — please pull the highlight discoveries and add English subtitles.",
    "Uploading a 4-hour anthropology-podcast — extract the highlight ethnographies and overlay English captions.",
    "Here's a 90-minute linguistics-podcast — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour philosophy-podcast — pull the highlight arguments and overlay English captions.",
    "Uploading a 3-hour ethics-podcast — please extract the highlight dilemmas and add English subtitles.",
    "Here's a 90-minute religion-podcast — cut a highlight reel and overlay English captions.",
    "I have a 2-hour spirituality-podcast — please pull the highlight teachings and add English subtitles.",
    "Uploading a 4-hour meditation-podcast — extract the highlight guided sessions and overlay English captions.",
    "Here's a 90-minute wellness-podcast — please cut a highlight reel and add English subtitles.",
    "I'm sending you a 2-hour nutrition-podcast — pull the highlight tips and overlay English captions.",
    "Uploading a 3-hour parenting-podcast — please extract the highlight advice and add English subtitles.",
    "Here's a 90-minute relationship-podcast — cut a highlight reel and overlay English captions.",
    # ── more academic conferences / scientific sessions (50) ──
    "I have a 90-minute NeurIPS keynote — cut a highlight reel and overlay English captions.",
    "I'm sending you a 2-hour ICML keynote recording — please pull the highlight findings and add English subtitles.",
    "Uploading a 4-hour ICLR session — extract the highlight talks and overlay English captions.",
    "Here's a 90-minute CVPR oral-session — please cut a highlight reel and add English subtitles.",
    "I have a 2-hour ACL keynote — pull the highlight findings and overlay English captions.",
    "Uploading a 3-hour EMNLP session — please extract the highlight talks and add English subtitles.",
    "Here's a 4-hour SIGGRAPH presentation-day — cut the highlight talks and overlay English captions.",
    "I'm sending you a 90-minute IROS plenary — please pull the highlight robotics demos and add English subtitles.",
    "Uploading a 2-hour ICRA keynote — extract the highlight robotics talks and overlay English captions.",
    "Here's a 3-hour AAAI session — cut the highlight talks and add English subtitles.",
    "I have a 90-minute ACM-CCS keynote — pull the highlight findings and overlay English captions.",
    "Uploading a 2-hour USENIX-Security session — please extract the highlight talks and add English subtitles.",
    "Here's a 4-hour Black-Hat-USA briefing — cut the highlight findings and overlay English captions.",
    "I'm sending you a 90-minute DEF-CON-talk recording — please pull the highlight reveals and add English subtitles.",
    "Uploading a 2-hour PyCon keynote — pull the highlight talks and overlay English captions.",
    "Here's a 3-hour KubeCon session — please extract the highlight demos and add English subtitles.",
    "I have a 4-hour Strange-Loop session — cut the highlight talks and overlay English captions.",
    "I'm sending you a 90-minute Lambda-Conf keynote — please pull the highlight talks and add English subtitles.",
    "Uploading a 2-hour APS-March-Meeting session — extract the highlight physics talks and overlay English captions.",
    "Here's a 3-hour APS-April-Meeting session — cut the highlight physics talks and add English subtitles.",
    "I have a 90-minute AGU-Fall-Meeting talk — pull the highlight earth-science findings and overlay English captions.",
    "Uploading a 2-hour AAS-Winter-Meeting session — please extract the highlight astronomy talks and add English subtitles.",
    "Here's a 4-hour ASBMB-meeting recording — cut the highlight biochem talks and overlay English captions.",
    "I'm sending you a 90-minute SfN-meeting talk — please pull the highlight neuroscience findings and add English subtitles.",
    "Uploading a 2-hour ASCO oncology-session — pull the highlight clinical-trial talks and overlay English captions.",
    "Here's a 3-hour ASH-hematology session — please extract the highlight clinical talks and add English subtitles.",
    "I have a 4-hour AHA-cardiology session — cut the highlight clinical talks and overlay English captions.",
    "I'm sending you a 90-minute ADA-diabetes session — please pull the highlight clinical talks and add English subtitles.",
    "Uploading a 2-hour ATS-pulmonology session — extract the highlight clinical talks and overlay English captions.",
    "Here's a 3-hour ASCO-GU session — cut the highlight clinical talks and add English subtitles.",
    "I have a 90-minute ESMO-oncology session — pull the highlight clinical talks and overlay English captions.",
    "Uploading a 2-hour ECTRIMS-MS session — please extract the highlight clinical talks and add English subtitles.",
    "Here's a 4-hour ESC-cardiology session — cut the highlight clinical talks and overlay English captions.",
    "I'm sending you a 90-minute ESHG-genetics session — please pull the highlight findings and add English subtitles.",
    "Uploading a 2-hour Cold-Spring-Harbor symposium — pull the highlight findings and overlay English captions.",
    "Here's a 3-hour Gordon-research conference — please extract the highlight talks and add English subtitles.",
    "I have a 4-hour Lindau-Nobel-Laureate-Meeting — cut the highlight talks and overlay English captions.",
    "I'm sending you a 90-minute Solvay-conference recording — please pull the highlight discussions and add English subtitles.",
    "Uploading a 2-hour AGU-Ocean-Sciences session — extract the highlight talks and overlay English captions.",
    "Here's a 3-hour ASLO-aquatic-sciences session — cut the highlight talks and add English subtitles.",
    "I have a 90-minute ESA-ecology session — pull the highlight findings and overlay English captions.",
    "Uploading a 2-hour SIAM-applied-math session — please extract the highlight talks and add English subtitles.",
    "Here's a 4-hour AMS-mathematics session — cut the highlight talks and overlay English captions.",
    "I'm sending you a 90-minute APA-psychology session — please pull the highlight talks and add English subtitles.",
    "Uploading a 2-hour APS-psychology session — pull the highlight talks and overlay English captions.",
    "Here's a 3-hour AERA-education session — please extract the highlight talks and add English subtitles.",
    "I have a 4-hour ASA-sociology session — cut the highlight talks and overlay English captions.",
    "I'm sending you a 90-minute MLA-language-association session — please pull the highlight talks and add English subtitles.",
    "Uploading a 2-hour APSA-political-science session — extract the highlight talks and overlay English captions.",
    "Here's a 3-hour AHA-historian-association session — cut the highlight talks and add English subtitles.",
    # ── more gaming / esports / influencer livestreams (50) ──
    "I have a 4-hour League-of-Legends-Worlds-Final — please pull the highlight teamfights and add English subtitles.",
    "Uploading a 3-hour Dota-2 The-International-grand-final — please extract the highlight teamfights and overlay English captions.",
    "Here's a 4-hour CS-GO-major-final — cut the highlight clutches and add English subtitles.",
    "I'm sending you a 90-minute Valorant-Champions final — pull the highlight clutches and overlay English captions.",
    "Uploading a 3-hour Overwatch-League grand-final — please extract the highlight team-fights and add English subtitles.",
    "Here's a 4-hour StarCraft-2-WCS-final — cut the highlight engagements and overlay English captions.",
    "I have a 2-hour Hearthstone-World-Championship final — please pull the highlight plays and add English subtitles.",
    "I'm sending you a 90-minute Smash-Ultimate-Genesis-final — pull the highlight combos and overlay English captions.",
    "Uploading a 4-hour EVO-Street-Fighter-finals — please extract the highlight matches and add English subtitles.",
    "Here's a 3-hour EVO-Tekken-finals — cut the highlight matches and overlay English captions.",
    "I have a 2-hour Fortnite-World-Cup-final — please pull the highlight builds and add English subtitles.",
    "I'm sending you a 90-minute PUBG-Global-Championship — pull the highlight encounters and overlay English captions.",
    "Uploading a 4-hour Apex-Legends-Global-Series final — please extract the highlight squads and add English subtitles.",
    "Here's a 3-hour Rocket-League-Championship final — cut the highlight goals and overlay English captions.",
    "I have a 2-hour FIFA-eWorld-Cup final — please pull the highlight goals and add English subtitles.",
    "I'm sending you a 90-minute NBA-2K-League final — pull the highlight dunks and overlay English captions.",
    "Uploading a 4-hour Madden-Bowl final — please extract the highlight drives and add English subtitles.",
    "Here's a 3-hour iRacing-Daytona-24h — cut the highlight laps and overlay English captions.",
    "I have a 2-hour speedrun-AGDQ-marathon — please pull the highlight runs and add English subtitles.",
    "I'm sending you a 90-minute SGDQ speedrun-block — pull the highlight runs and overlay English captions.",
    "Uploading a 4-hour Twitch-subathon — please extract the highlight raids and add English subtitles.",
    "Here's a 3-hour Kick-streamer subathon — cut the highlight moments and overlay English captions.",
    "I have a 2-hour Mr-Beast-challenge livestream — please pull the highlight challenges and add English subtitles.",
    "I'm sending you a 90-minute KSI-streamer livestream — pull the highlight banter and overlay English captions.",
    "Uploading a 4-hour PewDiePie variety livestream — please extract the highlight reactions and add English subtitles.",
    "Here's a 3-hour Markiplier horror-game stream — cut the highlight scares and overlay English captions.",
    "I have a 2-hour Jacksepticeye Let's-Play livestream — please pull the highlight reactions and add English subtitles.",
    "I'm sending you a 90-minute Ninja Fortnite-stream — pull the highlight victories and overlay English captions.",
    "Uploading a 4-hour TimTheTatman variety stream — please extract the highlight clutches and add English subtitles.",
    "Here's a 3-hour Shroud-tactical-shooter stream — cut the highlight headshots and overlay English captions.",
    "I have a 2-hour summit1g GTA-RP stream — please pull the highlight roleplay and add English subtitles.",
    "I'm sending you a 90-minute Pokimane variety stream — pull the highlight reactions and overlay English captions.",
    "Uploading a 4-hour xQc variety-stream — please extract the highlight rants and add English subtitles.",
    "Here's a 3-hour Asmongold-WoW stream — cut the highlight raids and overlay English captions.",
    "I have a 2-hour Dr-Disrespect arena-stream — please pull the highlight kills and add English subtitles.",
    "I'm sending you a 90-minute Lirik variety-stream — pull the highlight reactions and overlay English captions.",
    "Uploading a 4-hour Sykkuno among-us stream — please extract the highlight rounds and add English subtitles.",
    "Here's a 3-hour Valkyrae among-us stream — cut the highlight imposter-rounds and overlay English captions.",
    "I have a 2-hour Disguised-Toast streamer-collab — please pull the highlight plays and add English subtitles.",
    "I'm sending you a 90-minute Fuslie variety stream — pull the highlight chats and overlay English captions.",
    "Uploading a 4-hour Ludwig subathon-marathon — please extract the highlight moments and add English subtitles.",
    "Here's a 3-hour Hasanabi political-commentary stream — cut the highlight rants and overlay English captions.",
    "I have a 2-hour Forsen Hearthstone-stream — please pull the highlight memes and add English subtitles.",
    "I'm sending you a 90-minute MOONMOON-stream — pull the highlight reactions and overlay English captions.",
    "Uploading a 4-hour Northernlion roguelike-marathon — please extract the highlight runs and add English subtitles.",
    "Here's a 3-hour DoctorDisrespect-arena stream — cut the highlight matches and overlay English captions.",
    "I have a 2-hour Critical-Role D&D livestream — please pull the highlight roleplay and add English subtitles.",
    "I'm sending you a 90-minute Dimension-20 D&D stream — pull the highlight encounters and overlay English captions.",
    "Uploading a 4-hour Lost-Ark-MMO raid-livestream — please extract the highlight bosses and add English subtitles.",
    "Here's a 3-hour FFXIV raid-livestream — cut the highlight encounters and overlay English captions.",
    # ── more fitness / yoga / workout livestream highlight reels (50) ──
    "Uploading a 90-minute Peloton-cycling-class livestream — please cut the highlight intervals and add English subtitles.",
    "Here's a 2-hour Peloton-yoga-flow livestream — extract the highlight asanas and overlay English captions.",
    "I have a 3-hour SoulCycle-master-class livestream — please pull the highlight climbs and add English subtitles.",
    "Uploading a 4-hour Equinox-Tier-X-personal-training livestream — extract the highlight sets and overlay English captions.",
    "Here's a 90-minute Barry's-Bootcamp livestream — please cut the highlight drills and add English subtitles.",
    "I'm sending you a 2-hour Orangetheory livestream — pull the highlight splat-rounds and overlay English captions.",
    "Uploading a 3-hour CrossFit-Open-WOD livestream — please extract the highlight benchmark workouts and add English subtitles.",
    "Here's a 4-hour CrossFit-Games livestream — cut the highlight events and overlay English captions.",
    "I have a 90-minute F45-functional-training livestream — please pull the highlight stations and add English subtitles.",
    "Uploading a 2-hour Tonal-strength livestream — extract the highlight digital-weight sets and overlay English captions.",
    "Here's a 3-hour Mirror-fitness livestream — please cut the highlight cardio-rounds and add English subtitles.",
    "I'm sending you a 4-hour Zwift-cycling-race livestream — pull the highlight breakaways and overlay English captions.",
    "Uploading a 90-minute Strava-virtual-marathon livestream — please extract the highlight splits and add English subtitles.",
    "Here's a 2-hour Garmin-running-club livestream — cut the highlight pace-segments and overlay English captions.",
    "I have a 3-hour Beachbody-P90X livestream — please pull the highlight muscle-groups and add English subtitles.",
    "Uploading a 4-hour Beachbody-Insanity livestream — extract the highlight HIIT-blocks and overlay English captions.",
    "Here's a 90-minute Tracy-Anderson method livestream — please cut the highlight choreography sets and add English subtitles.",
    "I'm sending you a 2-hour Pvolve livestream — pull the highlight resistance-band rounds and overlay English captions.",
    "Uploading a 3-hour Megan-Roup Sculpt-Society livestream — please extract the highlight dance-cardio rounds and add English subtitles.",
    "Here's a 4-hour Melissa-Wood Health livestream — cut the highlight pilates flows and overlay English captions.",
    "I have a 90-minute Sara-Beth-Yoga livestream — please pull the highlight vinyasa flows and add English subtitles.",
    "Uploading a 2-hour Yoga-with-Adriene livestream — extract the highlight 30-day-yoga moments and overlay English captions.",
    "Here's a 3-hour Boho-Beautiful yoga livestream — please cut the highlight beach-yoga flows and add English subtitles.",
    "I'm sending you a 4-hour Yoga-with-Kassandra Vinyasa livestream — pull the highlight kriya sequences and overlay English captions.",
    "Uploading a 90-minute Cody-App yoga livestream — please extract the highlight master-class flows and add English subtitles.",
    "Here's a 2-hour Glo Yoga livestream — cut the highlight Iyengar sequences and overlay English captions.",
    "I have a 3-hour Down-Dog yoga livestream — please pull the highlight power-yoga flows and add English subtitles.",
    "Uploading a 4-hour Alo-Moves livestream — extract the highlight HIIT-yoga rounds and overlay English captions.",
    "Here's a 90-minute Rodney-Yee yoga livestream — please cut the highlight prana-flow moments and add English subtitles.",
    "I'm sending you a 2-hour Baron-Baptiste power-yoga livestream — pull the highlight asana sequences and overlay English captions.",
    "Uploading a 3-hour Kino-MacGregor Ashtanga livestream — please extract the highlight primary-series moments and add English subtitles.",
    "Here's a 4-hour Tim-Miller Ashtanga livestream — cut the highlight Mysore-style sequences and overlay English captions.",
    "I have a 90-minute Bikram-yoga livestream — please pull the highlight 26-pose sequences and add English subtitles.",
    "Uploading a 2-hour Hot-Yoga-Sculpt livestream — extract the highlight weight-flows and overlay English captions.",
    "Here's a 3-hour Bryan-Kest Power-Yoga livestream — please cut the highlight power-flow sequences and add English subtitles.",
    "I'm sending you a 4-hour Dharma-Mittra livestream — pull the highlight inversion sequences and overlay English captions.",
    "Uploading a 90-minute Sri-K-Pattabhi-Jois Ashtanga-archive livestream — please extract the highlight sequences and add English subtitles.",
    "Here's a 2-hour B-K-S-Iyengar archive livestream — cut the highlight asana-demos and overlay English captions.",
    "I have a 3-hour T-K-V-Desikachar archive livestream — please pull the highlight Krishnamacharya-tradition demos and add English subtitles.",
    "Uploading a 4-hour Joseph-Pilates archive livestream — extract the highlight matwork sequences and overlay English captions.",
    "Here's a 90-minute Stott-Pilates livestream — please cut the highlight reformer flows and add English subtitles.",
    "I'm sending you a 2-hour Classical-Pilates Romana-tradition livestream — pull the highlight cadillac sequences and overlay English captions.",
    "Uploading a 3-hour Tony-Horton P90X3 livestream — please extract the highlight 30-minute rounds and add English subtitles.",
    "Here's a 4-hour Shaun-T Insanity-Max-30 livestream — cut the highlight max-out rounds and overlay English captions.",
    "I have a 90-minute Jillian-Michaels 30-Day-Shred livestream — please pull the highlight circuit rounds and add English subtitles.",
    "Uploading a 2-hour Bob-Harper kettlebell livestream — extract the highlight kettlebell flows and overlay English captions.",
    "Here's a 3-hour Joe-Wicks Body-Coach livestream — please cut the highlight HIIT-rounds and add English subtitles.",
    "I'm sending you a 4-hour Caroline-Girvan Iron-series livestream — pull the highlight strength-blocks and overlay English captions.",
    "Uploading a 90-minute Sydney-Cummings strength livestream — please extract the highlight upper-lower splits and add English subtitles.",
    "Here's a 2-hour Heather-Robertson HIIT livestream — cut the highlight tabata rounds and overlay English captions.",
    # ── more late-night / talk-show / variety-show livestream highlight reels (50) ──
    "Uploading a 3-hour Late-Show-with-Stephen-Colbert livestream — please cut the highlight monologues and add English subtitles.",
    "Here's a 4-hour Late-Show-Colbert-election-night livestream — extract the highlight panels and overlay English captions.",
    "I have a 90-minute Tonight-Show-Jimmy-Fallon livestream — please pull the highlight monologues and add English subtitles.",
    "Uploading a 2-hour Tonight-Show-Fallon-musical-segment livestream — extract the highlight performances and overlay English captions.",
    "Here's a 3-hour Jimmy-Kimmel-Live livestream — please cut the highlight monologues and add English subtitles.",
    "I'm sending you a 4-hour Jimmy-Kimmel-Live-mean-tweets livestream — pull the highlight bits and overlay English captions.",
    "Uploading a 90-minute Late-Late-Show-with-James-Corden livestream — please extract the highlight Carpool-Karaoke and add English subtitles.",
    "Here's a 2-hour Late-Late-Show-Corden-finale livestream — cut the highlight tributes and overlay English captions.",
    "I have a 3-hour Daily-Show-with-Jon-Stewart-archive livestream — please pull the highlight monologues and add English subtitles.",
    "Uploading a 4-hour Daily-Show-with-Trevor-Noah livestream — extract the highlight monologues and overlay English captions.",
    "Here's a 90-minute Daily-Show-with-Jordan-Klepper-field-piece livestream — please cut the highlight field-bits and add English subtitles.",
    "I'm sending you a 2-hour Daily-Show-with-Jon-Stewart-return livestream — pull the highlight monologues and overlay English captions.",
    "Uploading a 3-hour Conan-O'Brien-on-TBS livestream — please extract the highlight bits and add English subtitles.",
    "Here's a 4-hour Conan-Late-Night-archive livestream — cut the highlight bits and overlay English captions.",
    "I have a 90-minute David-Letterman-Late-Show-archive livestream — please pull the highlight Top-Ten-lists and add English subtitles.",
    "Uploading a 2-hour Letterman-Stupid-Pet-Tricks livestream — extract the highlight bits and overlay English captions.",
    "Here's a 3-hour Tonight-Show-with-Johnny-Carson-archive livestream — please cut the highlight monologues and add English subtitles.",
    "I'm sending you a 4-hour Tonight-Show-with-Jay-Leno-archive livestream — pull the highlight monologues and overlay English captions.",
    "Uploading a 90-minute Saturday-Night-Live-cold-open livestream — please extract the highlight cold-opens and add English subtitles.",
    "Here's a 2-hour Saturday-Night-Live-Weekend-Update livestream — cut the highlight Weekend-Updates and overlay English captions.",
    "I have a 3-hour Saturday-Night-Live-musical-guest livestream — please pull the highlight performances and add English subtitles.",
    "Uploading a 4-hour Saturday-Night-Live-host-monologue livestream — extract the highlight monologues and overlay English captions.",
    "Here's a 90-minute MADtv-archive livestream — please cut the highlight sketches and add English subtitles.",
    "I'm sending you a 2-hour Inside-Amy-Schumer livestream — pull the highlight sketches and overlay English captions.",
    "Uploading a 3-hour Key-Peele-Comedy-Central livestream — please extract the highlight sketches and add English subtitles.",
    "Here's a 4-hour Chappelle's-Show-archive livestream — cut the highlight sketches and overlay English captions.",
    "I have a 90-minute Whose-Line-Is-It-Anyway livestream — please pull the highlight improv-rounds and add English subtitles.",
    "Uploading a 2-hour SNL-50th-anniversary-special livestream — extract the highlight tributes and overlay English captions.",
    "Here's a 3-hour Graham-Norton-Show-BBC livestream — please cut the highlight panels and add English subtitles.",
    "I'm sending you a 4-hour Jonathan-Ross-Show livestream — pull the highlight panels and overlay English captions.",
    "Uploading a 90-minute Mock-the-Week-BBC livestream — please extract the highlight rounds and add English subtitles.",
    "Here's a 2-hour Have-I-Got-News-for-You-BBC livestream — cut the highlight rounds and overlay English captions.",
    "I have a 3-hour Would-I-Lie-to-You-BBC livestream — please pull the highlight rounds and add English subtitles.",
    "Uploading a 4-hour QI-Stephen-Fry-BBC livestream — extract the highlight rounds and overlay English captions.",
    "Here's a 90-minute QI-Sandi-Toksvig-BBC livestream — please cut the highlight rounds and add English subtitles.",
    "I'm sending you a 2-hour 8-Out-of-10-Cats-Channel-4 livestream — pull the highlight rounds and overlay English captions.",
    "Uploading a 3-hour 8-Out-of-10-Cats-Does-Countdown livestream — please extract the highlight rounds and add English subtitles.",
    "Here's a 4-hour Last-Leg-Channel-4 livestream — cut the highlight bits and overlay English captions.",
    "I have a 90-minute Big-Fat-Quiz-of-the-Year livestream — please pull the highlight rounds and add English subtitles.",
    "Uploading a 2-hour Tonight-Show-Conan-Korea-special livestream — extract the highlight bits and overlay English captions.",
    "Here's a 3-hour Tonight-Show-Conan-Italy-special livestream — please cut the highlight bits and add English subtitles.",
    "I'm sending you a 4-hour Tonight-Show-Conan-Israel-special livestream — pull the highlight bits and overlay English captions.",
    "Uploading a 90-minute Tonight-Show-Conan-Cuba-special livestream — please extract the highlight bits and add English subtitles.",
    "Here's a 2-hour Tonight-Show-Conan-Japan-special livestream — cut the highlight bits and overlay English captions.",
    "I have a 3-hour SNL-Lonely-Island-digital-shorts livestream — please pull the highlight digital-shorts and add English subtitles.",
    "Uploading a 4-hour SNL-Andy-Samberg-archive livestream — extract the highlight bits and overlay English captions.",
    "Here's a 90-minute Real-Time-Bill-Maher-Overtime livestream — please cut the highlight Overtime-segments and add English subtitles.",
    "I'm sending you a 2-hour Last-Week-Tonight-mainsegment livestream — pull the highlight main-segments and overlay English captions.",
    "Uploading a 3-hour Patriot-Act-with-Hasan-Minhaj livestream — please extract the highlight monologues and add English subtitles.",
    "Here's a 4-hour Wait-Wait-Don't-Tell-Me-NPR livestream — cut the highlight rounds and overlay English captions.",
    # ── more megachurch / religious-service livestream highlight reels (50) ──
    "Uploading a 3-hour Lakewood-Church-Joel-Osteen livestream — please cut the highlight sermon and add English subtitles.",
    "Here's a 4-hour Hillsong-Church-Sydney-livestream — extract the highlight worship-set and overlay English captions.",
    "I have a 90-minute Saddleback-Church-Rick-Warren livestream — please pull the highlight Purpose-Driven-Life-segments and add English subtitles.",
    "Uploading a 2-hour Willow-Creek-Bill-Hybels livestream — extract the highlight teaching-segments and overlay English captions.",
    "Here's a 3-hour Bethel-Church-Redding-Bill-Johnson livestream — please cut the highlight worship-and-prophecy and add English subtitles.",
    "I'm sending you a 4-hour Elevation-Church-Steven-Furtick livestream — pull the highlight sermon-and-call and overlay English captions.",
    "Uploading a 90-minute Life-Church-Craig-Groeschel livestream — please extract the highlight teaching-segments and add English subtitles.",
    "Here's a 2-hour Mariners-Church-Kenton-Beshore livestream — cut the highlight sermon-and-music and overlay English captions.",
    "I have a 3-hour Vous-Church-Rich-Wilkerson-Jr livestream — please pull the highlight Miami-style-sermon and add English subtitles.",
    "Uploading a 4-hour Hillsong-NYC-Carl-Lentz-archive livestream — extract the highlight worship-set and overlay English captions.",
    "Here's a 90-minute Fellowship-Church-Ed-Young-Grapevine livestream — please cut the highlight sermon and add English subtitles.",
    "I'm sending you a 2-hour Gateway-Church-Robert-Morris livestream — pull the highlight teaching-segments and overlay English captions.",
    "Uploading a 3-hour Joyce-Meyer-Ministries livestream — please extract the highlight teaching-segments and add English subtitles.",
    "Here's a 4-hour T-D-Jakes-Potter's-House livestream — cut the highlight sermon-and-altar-call and overlay English captions.",
    "I have a 90-minute Joel-Osteen-Lakewood-radio livestream — please pull the highlight inspirational-talk and add English subtitles.",
    "Uploading a 2-hour Andy-Stanley-North-Point livestream — extract the highlight teaching-segments and overlay English captions.",
    "Here's a 3-hour Charles-Stanley-In-Touch livestream — please cut the highlight sermon and add English subtitles.",
    "I'm sending you a 4-hour Billy-Graham-Crusade-archive livestream — pull the highlight altar-call-segments and overlay English captions.",
    "Uploading a 90-minute Franklin-Graham-Decision-America livestream — please extract the highlight evangelistic-segments and add English subtitles.",
    "Here's a 2-hour Hillsong-Worship-Conference livestream — cut the highlight worship-anthems and overlay English captions.",
    "I have a 3-hour Passion-Conference-Atlanta livestream — please pull the highlight worship-and-teaching and add English subtitles.",
    "Uploading a 4-hour Catalyst-Conference livestream — extract the highlight leadership-segments and overlay English captions.",
    "Here's a 90-minute Ramp-Conference-Karen-Wheaton livestream — please cut the highlight worship-and-prophecy and add English subtitles.",
    "I'm sending you a 2-hour Bethel-Worship-Night livestream — pull the highlight worship-anthems and overlay English captions.",
    "Uploading a 3-hour Maverick-City-Music livestream — please extract the highlight worship-set and add English subtitles.",
    "Here's a 4-hour Elevation-Worship-Night livestream — cut the highlight worship-anthems and overlay English captions.",
    "I have a 90-minute Hillsong-United-Concert livestream — please pull the highlight worship-set and add English subtitles.",
    "Uploading a 2-hour Vatican-Easter-Vigil livestream — extract the highlight Mass-segments and overlay English captions.",
    "Here's a 3-hour Vatican-Christmas-Eve-Mass livestream — please cut the highlight Mass-segments and add English subtitles.",
    "I'm sending you a 4-hour Pope-Francis-Wednesday-General-Audience livestream — pull the highlight catechesis-segments and overlay English captions.",
    "Uploading a 90-minute World-Youth-Day-papal-vigil livestream — please extract the highlight worship-segments and add English subtitles.",
    "Here's a 2-hour Holy-Week-Stations-of-the-Cross livestream — cut the highlight Stations-readings and overlay English captions.",
    "I have a 3-hour Christ-Hospital-Ahmedabad-Christian-rally livestream — please pull the highlight altar-call-segments and add English subtitles.",
    "Uploading a 4-hour Karol-Wojtyła-archive-mass livestream — extract the highlight homily-segments and overlay English captions.",
    "Here's a 90-minute Sunday-Morning-Brooklyn-Tabernacle livestream — please cut the highlight choir-and-sermon and add English subtitles.",
    "I'm sending you a 2-hour Salt-Lake-Tabernacle-Choir livestream — pull the highlight choir-anthems and overlay English captions.",
    "Uploading a 3-hour LDS-General-Conference-Salt-Lake livestream — please extract the highlight talks and add English subtitles.",
    "Here's a 4-hour LDS-Sunday-Sacrament-Meeting livestream — cut the highlight talks and overlay English captions.",
    "I have a 90-minute Buddhist-Vipassana-retreat-Goenka livestream — please pull the highlight discourse-segments and add English subtitles.",
    "Uploading a 2-hour Plum-Village-Thich-Nhat-Hanh-archive livestream — extract the highlight dharma-talks and overlay English captions.",
    "Here's a 3-hour Drepung-Loseling-Dalai-Lama-teaching livestream — please cut the highlight teaching-segments and add English subtitles.",
    "I'm sending you a 4-hour Sri-Sri-Ravi-Shankar-Art-of-Living livestream — pull the highlight discourse-segments and overlay English captions.",
    "Uploading a 90-minute Sadhguru-Isha-Foundation livestream — please extract the highlight discourse-segments and add English subtitles.",
    "Here's a 2-hour Brahma-Kumaris-meditation-livestream — cut the highlight meditation-segments and overlay English captions.",
    "I have a 3-hour ISKCON-Bhagavad-Gita-class livestream — please pull the highlight class-segments and add English subtitles.",
    "Uploading a 4-hour Friday-Khutbah-Sheikh-Yasir-Qadhi livestream — extract the highlight khutbah-segments and overlay English captions.",
    "Here's a 90-minute Friday-Khutbah-Mecca-Imam-Sudais livestream — please cut the highlight khutbah-segments and add English subtitles.",
    "I'm sending you a 2-hour Eid-Mubarak-livestream-Mecca — pull the highlight prayer-segments and overlay English captions.",
    "Uploading a 3-hour Yom-Kippur-Kol-Nidre-Park-Avenue-Synagogue livestream — please extract the highlight liturgy-segments and add English subtitles.",
    "Here's a 4-hour Hanukkah-candle-lighting-livestream — cut the highlight candle-blessing-segments and overlay English captions.",
    # ── more charity telethon + marathon livestreams + EN subs (50) ──
    "I'm sending you a 4-hour Comic-Relief-Red-Nose-Day-BBC-livestream — pull the highlight celebrity-sketch-segments and overlay English captions.",
    "Uploading a 5-hour Children-in-Need-BBC-Telethon livestream — please extract the highlight Pudsey-Bear-segments and add English subtitles.",
    "Here's a 3-hour Telethon-of-Stars-Stand-Up-To-Cancer livestream — cut the highlight survivor-story-segments and overlay English captions.",
    "I have a 4-hour American-Cancer-Society-Relay-For-Life livestream — please pull the highlight luminaria-ceremony-segments and add English subtitles.",
    "Uploading a 5-hour Jerry-Lewis-MDA-Telethon-archival livestream — extract the highlight celebrity-host-segments and overlay English captions.",
    "Here's a 3-hour MDA-Show-of-Strength-Telethon livestream — please cut the highlight Goldenrod-tally-segments and add English subtitles.",
    "I'm sending you a 4-hour St.-Jude-Country-Cares-Radiothon livestream — pull the highlight patient-family-segments and overlay English captions.",
    "Uploading a 5-hour Salvation-Army-Red-Kettle-Kickoff-Cowboys-Stadium livestream — please extract the highlight halftime-show-segments and add English subtitles.",
    "Here's a 3-hour Macy's-Thanksgiving-Day-Parade-NYC livestream — cut the highlight balloon-handler-segments and overlay English captions.",
    "I have a 4-hour Rose-Parade-Pasadena-livestream — please pull the highlight float-procession-segments and add English subtitles.",
    "Uploading a 5-hour Ireland-Late-Late-Toy-Show-RTE-Telethon livestream — extract the highlight gift-reveal-segments and overlay English captions.",
    "Here's a 3-hour Australia-7-News-Bushfire-Appeal-Telethon livestream — please cut the highlight pledge-board-segments and add English subtitles.",
    "I'm sending you a 4-hour Channel-4-Stand-Up-To-Cancer-UK-Telethon livestream — pull the highlight celebrity-bake-off-segments and overlay English captions.",
    "Uploading a 5-hour ITV-Soccer-Aid-UNICEF-charity-match livestream — please extract the highlight goal-segments and add English subtitles.",
    "Here's a 3-hour BBC-Sport-Relief-Mile-marathon livestream — cut the highlight celebrity-runner-segments and overlay English captions.",
    "I have a 4-hour Hand-in-Hand-Hurricane-Harvey-Telethon livestream — please pull the highlight celebrity-call-center-segments and add English subtitles.",
    "Uploading a 5-hour One-World-Together-At-Home-Lady-Gaga-WHO-Telethon livestream — extract the highlight artist-performance-segments and overlay English captions.",
    "Here's a 3-hour Concert-for-NYC-Madison-Square-Garden-9/11-Benefit livestream — please cut the highlight rock-set-segments and add English subtitles.",
    "I'm sending you a 4-hour Live-Aid-Wembley-Philadelphia-archival livestream — pull the highlight Queen-set-segments and overlay English captions.",
    "Uploading a 5-hour Farm-Aid-Willie-Nelson-archival livestream — please extract the highlight country-set-segments and add English subtitles.",
    "Here's a 3-hour MTV-Live-Earth-NYC-archival livestream — cut the highlight rock-set-segments and overlay English captions.",
    "I have a 4-hour Global-Citizen-Festival-Central-Park livestream — please pull the highlight headliner-segments and add English subtitles.",
    "Uploading a 5-hour Robin-Hood-Foundation-Benefit-Javits-Center livestream — extract the highlight gala-auction-segments and overlay English captions.",
    "Here's a 3-hour New-York-City-Marathon-livestream — please cut the highlight Verrazzano-Bridge-segments and add English subtitles.",
    "I'm sending you a 4-hour Boston-Marathon-livestream — pull the highlight Heartbreak-Hill-segments and overlay English captions.",
    "Uploading a 5-hour Chicago-Marathon-livestream — please extract the highlight finish-line-segments and add English subtitles.",
    "Here's a 3-hour Berlin-Marathon-livestream — cut the highlight Brandenburg-Gate-segments and overlay English captions.",
    "I have a 4-hour Tokyo-Marathon-livestream — please pull the highlight Imperial-Palace-segments and add English subtitles.",
    "Uploading a 5-hour London-Marathon-livestream — extract the highlight Tower-Bridge-segments and overlay English captions.",
    "Here's a 3-hour Boston-Athletic-Association-half-marathon livestream — please cut the highlight finish-line-segments and add English subtitles.",
    "I'm sending you a 4-hour Brooklyn-Half-Marathon-livestream — pull the highlight Coney-Island-Boardwalk-segments and overlay English captions.",
    "Uploading a 5-hour LA-Marathon-livestream — please extract the highlight Sunset-Boulevard-segments and add English subtitles.",
    "Here's a 3-hour San-Francisco-Marathon-Golden-Gate livestream — cut the highlight bridge-crossing-segments and overlay English captions.",
    "I have a 4-hour Dublin-Marathon-livestream — please pull the highlight Phoenix-Park-segments and add English subtitles.",
    "Uploading a 5-hour Edinburgh-Marathon-livestream — extract the highlight Holyrood-Park-segments and overlay English captions.",
    "Here's a 3-hour Reykjavik-Marathon-livestream — please cut the highlight Tjörnin-Lake-segments and add English subtitles.",
    "I'm sending you a 4-hour Sydney-Running-Festival-livestream — pull the highlight Harbour-Bridge-segments and overlay English captions.",
    "Uploading a 5-hour Auckland-Marathon-livestream — please extract the highlight Sky-Tower-segments and add English subtitles.",
    "Here's a 3-hour Singapore-Standard-Chartered-Marathon livestream — cut the highlight Marina-Bay-Sands-segments and overlay English captions.",
    "I have a 4-hour Hong-Kong-Marathon-livestream — please pull the highlight Tsing-Ma-Bridge-segments and add English subtitles.",
    "Uploading a 5-hour Mumbai-Marathon-livestream — extract the highlight Marine-Drive-segments and overlay English captions.",
    "Here's a 3-hour Cape-Town-Two-Oceans-Ultramarathon livestream — please cut the highlight Chapman's-Peak-segments and add English subtitles.",
    "I'm sending you a 4-hour Comrades-Marathon-Pietermaritzburg-Durban livestream — pull the highlight Polly-Shorts-segments and overlay English captions.",
    "Uploading a 5-hour New-Year-Sydney-Harbour-fireworks-charity-livestream — please extract the highlight Opera-House-segments and add English subtitles.",
    "Here's a 3-hour Sao-Paulo-Reveillon-Avenida-Paulista-livestream — cut the highlight DJ-set-segments and overlay English captions.",
    "I have a 4-hour Rio-Reveillon-Copacabana-Beach-livestream — please pull the highlight fireworks-finale-segments and add English subtitles.",
    "Uploading a 5-hour Times-Square-New-Year-Ball-Drop-livestream — extract the highlight Ryan-Seacrest-segments and overlay English captions.",
    "Here's a 3-hour Nashville-Music-City-New-Year-livestream — please cut the highlight country-music-segments and add English subtitles.",
    "I'm sending you a 4-hour Las-Vegas-Strip-New-Year-fireworks-livestream — pull the highlight Bellagio-Fountain-segments and overlay English captions.",
    "Uploading a 5-hour Disneyland-New-Year-fireworks-livestream — please extract the highlight Sleeping-Beauty-Castle-segments and add English subtitles.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
