"""x15 vid_music_ambience GRPO short briefs. Disjoint from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 1-minute backyard-bonfire family clip — please add a folksy-banjo BGM and crackling-fire ambience.",
    "Here's a 2-minute fishing-cabin morning — overlay an acoustic-guitar BGM and lake-loon ambience.",
    "I have a 90-second hammock-by-the-lake reel — please add a chill-acoustic BGM and lake-and-cicada ambience.",
    "Uploading a 45-second wood-stove kitchen reel — overlay a hearth-folk BGM and crackling-wood-and-kettle ambience.",
    "Here's a 1-minute child's-treehouse reel — please add a playful-flute BGM and backyard-bird ambience.",
    "I'm sending you a 2-minute snow-covered cabin morning — overlay a Scandinavian-folk BGM and snow-and-distant-bird ambience.",
    "Uploading a 90-second beachfront yoga session — please add a meditative-flute BGM and ocean-wave ambience.",
    "Here's a 30-second tide-pool exploration with my niece — overlay a curious-pizzicato BGM and tide-pool ambience.",
    "I have a 1-minute pier-fishing reel — please add a maritime-fiddle BGM and pier-water-and-gull ambience.",
    "Uploading a 2-minute mountain-cabin sunrise reel — overlay a hopeful-piano BGM and mountain-bird ambience.",
    "Here's a 45-second hot-air-balloon reel — please add a soaring-orchestral BGM and balloon-burner ambience.",
    "I'm sending you a 90-second covered-wagon-themed-park reel — overlay a Western-fiddle BGM and creaking-wagon ambience.",
    "Uploading a 1-minute amusement-park-carousel reel — please add a carousel-organ BGM and carousel-music-box ambience.",
    "Here's a 2-minute county-fair midway reel — overlay a carnival-organ BGM and crowd-and-game-machine ambience.",
    "I have a 30-second pumpkin-patch reel — please add a folksy-banjo BGM and crow-and-leaf-rustle ambience.",
    "Uploading a 90-second apple-orchard reel — overlay an Americana-folk BGM and orchard-bee ambience.",
    "Here's a 1-minute corn-maze reel — please add a spooky-celesta BGM and night-cricket ambience.",
    "I'm sending you a 45-second drive-in-movie reel — overlay a 1950s-doo-wop BGM and parking-lot ambience.",
    "Uploading a 2-minute baseball-stadium tailgate reel — please add a stadium-rock BGM and tailgate-crowd ambience.",
    "Here's a 90-second roller-rink reel — overlay a 1970s-disco BGM and skating-and-music-rink ambience.",
    "I have a 1-minute bowling-alley reel — please add a 1960s-rock BGM and bowling-and-pin ambience.",
    "Uploading a 30-second arcade-day reel — overlay a chiptune BGM and arcade-cabinet ambience.",
    "Here's a 2-minute miniature-golf reel — please add a playful-acoustic BGM and water-fountain ambience.",
    "I'm sending you a 45-second go-kart-track reel — overlay an upbeat-electronic BGM and go-kart-engine ambience.",
    "Uploading a 1-minute dirt-bike-trail reel — please add a hard-rock BGM and dirt-bike-engine ambience.",
    "Here's a 90-second lake-tubing reel — overlay a beach-rock BGM and motorboat-and-water ambience.",
    "I have a 30-second jet-ski reel — please add a synth-rock BGM and jet-ski-engine-and-water ambience.",
    "Uploading a 2-minute waterski reel — overlay an upbeat-pop BGM and motorboat-and-spray ambience.",
    "Here's a 1-minute paddleboard reel — please add a chill-acoustic BGM and lapping-water ambience.",
    "I'm sending you a 45-second canoe-on-glassy-lake reel — overlay a meditative-piano BGM and lake-loon ambience.",
    "Uploading a 90-second whitewater-raft reel — please add an adventure-orchestral BGM and rushing-water ambience.",
    "Here's a 2-minute river-tubing reel — overlay an upbeat-folk BGM and river-and-cicada ambience.",
    "I have a 1-minute waterfall-rappelling reel — please add an epic-orchestral BGM and waterfall-rush ambience.",
    "Uploading a 30-second cliff-jumping reel — overlay a hard-rock BGM and water-splash-and-cheer ambience.",
    "Here's a 45-second cave-spelunking reel — please add a mysterious-strings BGM and cave-drip ambience.",
    "I'm sending you a 1-minute sandboarding-dune reel — overlay a Middle-Eastern-percussion BGM and sand-hiss ambience.",
    "Uploading a 90-second hot-spring-soak reel — please add a meditative-shakuhachi BGM and steam-and-water ambience.",
    "Here's a 2-minute beach-bonfire reel — overlay a chill-folk BGM and crackling-fire-and-wave ambience.",
    "I have a 1-minute lake-skipping-stones reel — please add a folksy-banjo BGM and lake-and-cricket ambience.",
    "Uploading a 30-second forest-mushroom-foraging reel — overlay a meditative-flute BGM and forest-bird ambience.",
    "Here's a 45-second mushroom-farming reel — please add a pastoral-strings BGM and mushroom-misting ambience.",
    "I'm sending you a 90-second fern-harvesting reel — overlay a Celtic-flute BGM and forest-stream ambience.",
    "Uploading a 2-minute foraged-greens-cooking reel — please add a folksy-banjo BGM and kitchen-stovetop ambience.",
    "Here's a 1-minute home-canning reel — overlay a vintage-piano BGM and kitchen-stovetop-and-mason-jar ambience.",
    "I have a 45-second jam-making reel — please add a vintage-piano BGM and jam-pot-and-clinking-jar ambience.",
    "Uploading a 30-second pickle-fermenting reel — overlay a folksy-banjo BGM and brine-bubble-and-jar-clink ambience.",
    "Here's a 1-minute kombucha-brewing reel — please add a chill-acoustic BGM and brewing-bubble ambience.",
    "I'm sending you a 90-second mead-making reel — overlay a Celtic-folk BGM and brewing-bubble-and-honey ambience.",
    "Uploading a 2-minute beer-brewing reel — please add an Americana-folk BGM and brewery-bubble-and-tank ambience.",
    "Here's a 45-second wine-pressing reel — overlay an Italian-mandolin BGM and grape-press-and-cellar ambience.",
    "I have a 1-minute olive-harvesting reel — please add a Tuscan-mandolin BGM and olive-shake-and-net ambience.",
    "Uploading a 30-second saffron-harvesting reel — overlay a Persian-santur BGM and saffron-field-and-bee ambience.",
    "Here's a 2-minute lavender-harvesting reel — please add a French-musette BGM and lavender-field-and-bee ambience.",
    "I'm sending you a 45-second tea-leaf-picking reel — overlay a Chinese-guzheng BGM and tea-field-bird ambience.",
    "Uploading a 90-second coffee-cherry harvest reel — please add a Latin-folk BGM and harvester-and-leaf ambience.",
    "Here's a 1-minute cocoa-pod harvest reel — overlay a Caribbean-steel-drum BGM and harvest-machete-and-bird ambience.",
    "I have a 30-second sugarcane-cutting reel — please add a Brazilian-cuíca BGM and harvest-blade ambience.",
    "Uploading a 45-second rice-paddy-planting reel — overlay an Indonesian-gamelan BGM and paddy-water-and-frog ambience.",
    "Here's a 1-minute corn-husking reel — please add an Americana-banjo BGM and husking-and-leaf ambience.",
    "I'm sending you a 90-second potato-harvesting reel — overlay an Irish-folk-fiddle BGM and field-and-pickup-truck ambience.",
    "Uploading a 2-minute apple-cider-pressing reel — please add a Vermont-folk BGM and pressing-and-jug ambience.",
    "Here's a 1-minute maple-syrup-tapping reel — overlay a Quebec-folk BGM and syrup-drip-and-spile ambience.",
    "I have a 45-second cheese-making reel — please add a Swiss-zither BGM and stirring-curds ambience.",
    "Uploading a 30-second yogurt-straining reel — overlay a Greek-folk BGM and ladle-and-cheesecloth ambience.",
    "Here's a 2-minute butter-churning reel — please add an Americana-folk BGM and churning-and-creamy ambience.",
    "I'm sending you a 1-minute pasta-rolling reel — overlay an Italian-mandolin BGM and rolling-pin-and-flour ambience.",
    "Uploading a 90-second tortilla-press reel — please add a mariachi-trumpet BGM and tortilla-press-and-flour ambience.",
    # ── more upload + BGM + ambience requests (50) ────────────────────────
    "Uploading a 1-minute clip of a Vermont-cabin morning — please add a quiet-piano BGM and wood-stove-crackle ambient.",
    "Here's a 45-second clip of a Maine-lighthouse evening — overlay a maritime-fiddle BGM and foghorn-and-gull ambient.",
    "I have a 2-minute clip of a Adirondack-fall-foliage hike — please add a folksy-banjo BGM and forest-bird ambient.",
    "Uploading a 90-second clip of a Smoky-Mountain stream walk — overlay a bluegrass-fiddle BGM and stream-water ambient.",
    "Here's a 30-second clip of a Big-Sur cliffside hike — please add a serene-cello BGM and ocean-wave ambient.",
    "I'm sending you a 1-minute clip of a Olympic-rainforest hike — overlay a Celtic-flute BGM and rainforest-drip ambient.",
    "Uploading a 2-minute clip of a Cascade-volcano-summit hike — please add a soaring-orchestral BGM and high-altitude-wind ambient.",
    "Here's a 45-second clip of a Glacier-National-Park lake — overlay a sparse-piano BGM and loon-call ambient.",
    "I have a 90-second clip of a Yosemite-meadow morning — please add a pastoral-strings BGM and meadow-bird ambient.",
    "Uploading a 30-second clip of a Sequoia-grove hike — overlay a Celtic-flute BGM and forest-canopy ambient.",
    "Here's a 1-minute clip of a Joshua-Tree-desert dawn — please add an oud-and-percussion BGM and desert-wind ambient.",
    "I'm sending you a 2-minute clip of a Death-Valley salt-flats — overlay an ambient-pad BGM and desert-cricket ambient.",
    "Uploading a 45-second clip of a Mojave-desert sunrise — please add a Bedouin-rebab BGM and sand-hiss ambient.",
    "Here's a 90-second clip of a White-Sands dunes hike — overlay an ambient-pad BGM and sand-shift ambient.",
    "I have a 30-second clip of a Sonoran-cactus-flower bloom — please add a Mexican-folk BGM and Sonoran-cricket ambient.",
    "Uploading a 1-minute clip of a Saguaro-National-Park dawn — overlay a flamenco-guitar BGM and desert-bird ambient.",
    "Here's a 2-minute clip of a Big-Bend canyon hike — please add a Tex-Mex-fiddle BGM and canyon-wind ambient.",
    "I'm sending you a 45-second clip of a Carlsbad-cavern descent — overlay a mysterious-strings BGM and cave-drip ambient.",
    "Uploading a 90-second clip of a Mammoth-cave tour — please add a quiet-piano BGM and cave-drip ambient.",
    "Here's a 30-second clip of a Wind-Cave room — overlay a sparse-piano BGM and cave-drip ambient.",
    "I have a 1-minute clip of a Bryce-Canyon hoodoo hike — please add a Native-American-flute BGM and canyon-wind ambient.",
    "Uploading a 2-minute clip of a Zion-Narrows wade hike — overlay a Native-American-flute BGM and stream-and-canyon ambient.",
    "Here's a 45-second clip of a Grand-Canyon-rim hike — please add a sweeping-orchestral BGM and canyon-wind ambient.",
    "I'm sending you a 90-second clip of a Glen-Canyon-dam tour — overlay a sparse-piano BGM and dam-machinery ambient.",
    "Uploading a 30-second clip of a Lake-Powell houseboat day — please add a chill-acoustic BGM and lapping-water ambient.",
    "Here's a 1-minute clip of a Monument-Valley dawn — overlay a Navajo-flute BGM and desert-wind ambient.",
    "I have a 2-minute clip of a Antelope-Canyon walk — please add a sparse-piano BGM and canyon-echo ambient.",
    "Uploading a 45-second clip of a Horseshoe-Bend overlook — overlay a sweeping-orchestral BGM and Colorado-River ambient.",
    "Here's a 90-second clip of a Mesa-Verde cliff-dwelling tour — please add a Pueblo-flute BGM and cliff-dwelling-quiet ambient.",
    "I'm sending you a 30-second clip of a Chaco-Canyon ruins walk — overlay a Pueblo-drum BGM and desert-wind ambient.",
    "Uploading a 1-minute clip of a Canyon-de-Chelly hike — please add a Navajo-flute BGM and canyon-bird ambient.",
    "Here's a 2-minute clip of a Rio-Grande river-rafting — overlay an adventure-orchestral BGM and rushing-water ambient.",
    "I have a 45-second clip of a Yellowstone-geyser eruption — please add a sparse-piano BGM and geyser-steam ambient.",
    "Uploading a 90-second clip of a Yellowstone-prismatic-spring walk — overlay an ambient-pad BGM and spring-bubble ambient.",
    "Here's a 30-second clip of a Old-Faithful watch — please add a soaring-orchestral BGM and crowd-and-geyser ambient.",
    "I'm sending you a 1-minute clip of a Hayden-Valley bison watch — overlay a pastoral-strings BGM and bison-and-prairie ambient.",
    "Uploading a 2-minute clip of a Lamar-Valley wolf watch — please add a sparse-piano BGM and prairie-wind ambient.",
    "Here's a 45-second clip of a Grand-Teton-canoe morning — overlay a quiet-piano BGM and lake-loon ambient.",
    "I have a 90-second clip of a Banff-Lake-Louise canoe — please add a Celtic-flute BGM and alpine-lake ambient.",
    "Uploading a 30-second clip of a Jasper-icefield-walk — overlay an ambient-pad BGM and glacier-wind ambient.",
    "Here's a 1-minute clip of a Whistler-mountain hike — please add a Celtic-flute BGM and high-altitude-wind ambient.",
    "I'm sending you a 2-minute clip of a Vancouver-Stanley-Park bike — overlay a chill-acoustic BGM and forest-and-ocean ambient.",
    "Uploading a 45-second clip of a Vancouver-Granville-Island stroll — please add a smooth-jazz BGM and harbor-and-market ambient.",
    "Here's a 90-second clip of a Toronto-CN-Tower elevator — overlay a synth-electronic BGM and elevator-and-city ambient.",
    "I have a 30-second clip of a Niagara-Falls-Maid-of-the-Mist — please add a sweeping-orchestral BGM and rushing-water ambient.",
    "Uploading a 1-minute clip of a Quebec-City-old-town stroll — overlay a French-Canadian-fiddle BGM and cobblestone-and-bell ambient.",
    "Here's a 2-minute clip of a Halifax-harbor walk — please add a maritime-fiddle BGM and harbor-gull ambient.",
    "I'm sending you a 45-second clip of a Newfoundland-iceberg watch — overlay a sparse-piano BGM and ocean-wave ambient.",
    "Uploading a 90-second clip of a Yukon-aurora time-lapse — please add an ambient-pad BGM and Arctic-wind ambient.",
    "Here's a 30-second clip of a Alaskan-glacier-cruise — overlay a sweeping-orchestral BGM and glacier-and-water ambient.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
