"""x15 vid_bilingual_sub GRPO short briefs. Disjoint from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 2-minute Korean grandmother kimchi tutorial — please add Korean and Japanese subtitles.",
    "Here's a 1-minute Cantonese opera rehearsal — overlay Cantonese and Mandarin captions.",
    "I have a 90-second Hindi cricket commentary — please add Hindi and Tamil subtitles.",
    "Uploading a 2-minute French farmer interview — overlay French and German subtitles.",
    "Here's a 3-minute Spanish wine-tasting class — please add Spanish and Portuguese subtitles.",
    "I'm sending you a 1-minute Mandarin tea-ceremony narration — overlay Mandarin and Cantonese subtitles.",
    "Uploading a 90-second Russian chess commentary — please add Russian and Ukrainian subtitles.",
    "Here's a 2-minute Italian opera rehearsal — overlay Italian and French subtitles.",
    "I have a 4-minute Polish accordion lesson — please add Polish and Russian subtitles.",
    "Uploading a 1-minute Brazilian samba rehearsal — overlay Portuguese and Spanish subtitles.",
    "Here's a 3-minute Portuguese fado history lecture — please add Portuguese and English subtitles.",
    "I'm sending you a 90-second Greek dance lesson — overlay Greek and Italian subtitles.",
    "Uploading a 2-minute Turkish whirling dervish explanation — please add Turkish and English subtitles.",
    "Here's a 1-minute Egyptian belly-dance lesson — overlay Arabic and English subtitles.",
    "I have a 4-minute Lebanese poetry recitation — please add Arabic and French subtitles.",
    "Uploading a Persian rug-weaving demo, 3 minutes — overlay Persian and Arabic subtitles.",
    "Here's a 2-minute Dari poetry reading — please add Dari and English subtitles.",
    "I'm sending you a 90-second Sinhalese cooking demo — overlay Sinhalese and Tamil subtitles.",
    "Uploading a Tamil priest blessing video, 3 minutes — please add Tamil and Sinhalese subtitles.",
    "Here's a 1-minute Bengali poet reciting — overlay Bengali and Hindi subtitles.",
    "I have a 4-minute Marathi shipping-yard explainer — please add Marathi and Gujarati subtitles.",
    "Uploading a 2-minute Gujarati merchant negotiation demo — overlay Gujarati and English subtitles.",
    "Here's a 90-second Punjabi farming explainer — please add Punjabi and Hindi subtitles.",
    "I'm sending you a Kannada potter demo, 3 minutes — overlay Kannada and English subtitles.",
    "Uploading a 1-minute Telugu rice-farming interview — please add Telugu and Tamil subtitles.",
    "Here's a 2-minute Malayalam fishermen explainer — overlay Malayalam and Tamil subtitles.",
    "I have a 4-minute Odia weaving-process demo — please add Odia and Hindi subtitles.",
    "Uploading a Bhojpuri folk-singer interview, 3 minutes — overlay Bhojpuri and Hindi subtitles.",
    "Here's a 90-second Awadhi storyteller video — please add Awadhi and Hindi subtitles.",
    "I'm sending you a 2-minute Konkani fisherman demo — overlay Konkani and Marathi subtitles.",
    "Uploading a 1-minute Kashmiri pashmina-maker — please add Kashmiri and Urdu subtitles.",
    "Here's a 4-minute Karen weaver explainer — overlay Karen and Burmese subtitles.",
    "I have a 2-minute Hmong embroiderer interview — please add Hmong and Vietnamese subtitles.",
    "Uploading a Cebuano fisherman repair demo, 3 minutes — overlay Cebuano and Tagalog subtitles.",
    "Here's a 90-second Ilocano farmer interview — please add Ilocano and English subtitles.",
    "I'm sending you a Javanese gamelan-player explainer, 2 minutes — overlay Javanese and Indonesian subtitles.",
    "Uploading a Sundanese rice-farmer interview, 1 minute — please add Sundanese and Indonesian subtitles.",
    "Here's a Balinese mask-carver demo, 4 minutes — overlay Balinese and English subtitles.",
    "I have a 2-minute Tongan fisherman interview — please add Tongan and Samoan subtitles.",
    "Uploading a 90-second Samoan grandmother demo — overlay Samoan and English subtitles.",
    "Here's a 3-minute Fijian farmer interview — please add Fijian and English subtitles.",
    "I'm sending you a Maori carver demonstration, 2 minutes — overlay Maori and English subtitles.",
    "Uploading a Tahitian dancer rehearsal, 1 minute — please add Tahitian and French subtitles.",
    "Here's a 4-minute Hawaiian taro-farmer demo — overlay Hawaiian and Japanese subtitles.",
    "I have a 90-second Yupik hunter interview — please add Yupik and English subtitles.",
    "Uploading a 2-minute Cree elder storytelling — overlay Cree and French subtitles.",
    "Here's an Inuktitut grandmother sewing demo, 3 minutes — please add Inuktitut and French subtitles.",
    "I'm sending you a 1-minute Ojibwe wild-rice harvester — overlay Ojibwe and English subtitles.",
    "Uploading a Navajo silversmith demo, 4 minutes — please add Navajo and Spanish subtitles.",
    "Here's a 2-minute Lakota grandmother braiding demo — overlay Lakota and English subtitles.",
    "I have a 90-second Nahuatl grandmother making tlacoyos — please add Nahuatl and English subtitles.",
    "Uploading a 3-minute Mapuche elder weaving demo — overlay Mapudungun and Quechua subtitles.",
    "Here's a 1-minute Aymara herder interview — please add Aymara and Quechua subtitles.",
    "I'm sending you a Guaraní fisherman cast demo, 2 minutes — overlay Guaraní and Spanish subtitles.",
    "Uploading a Garifuna drummer lesson, 4 minutes — please add Garifuna and English subtitles.",
    "Here's a 90-second Haitian Kreyòl baker — overlay Haitian Kreyòl and Spanish subtitles.",
    "I have a Jamaican Patois fisherman interview, 3 minutes — please add Jamaican Patois and Spanish subtitles.",
    "Uploading a 2-minute Afrikaans winemaker demonstration — overlay Afrikaans and Zulu subtitles.",
    "Here's a 1-minute Shona drummer rehearsal — please add Shona and Ndebele subtitles.",
    "I'm sending you a Sotho braiding tutorial, 4 minutes — overlay Sotho and Zulu subtitles.",
    "Uploading a 90-second Tswana cattle-counter interview — please add Tswana and Afrikaans subtitles.",
    "Here's a 2-minute Swahili fisherman tide demo — overlay Swahili and French subtitles.",
    "I have an Oromo coffee-farmer interview, 3 minutes — please add Oromo and Arabic subtitles.",
    "Uploading a 1-minute Wolof tailor demo — overlay Wolof and Mandinka subtitles.",
    "Here's a Bambara griot, 4 minutes — please add Bambara and Soninke subtitles.",
    "I'm sending you a Mande blacksmith forging demo, 2 minutes — overlay Mandinka and Bambara subtitles.",
    "Uploading a 90-second Malagasy vanilla-bean farmer — please add Malagasy and Comorian subtitles.",
    "Here's a 3-minute Kinyarwanda agaseke-weaving demo — overlay Kinyarwanda and Kirundi subtitles.",
    "I have a 1-minute Lingala dock-loading interview — please add Lingala and Kikongo subtitles.",
    "Uploading a Kongo dancer rehearsal, 4 minutes — overlay Kikongo and Lingala subtitles.",
    "Here's a Bemba copper miner interview, 90 seconds — please add Bemba and Tonga subtitles.",
    "I'm sending you a Chichewa cassava-leaf demo, 2 minutes — overlay Chichewa and Tumbuka subtitles.",
    "Uploading a 1-minute Tigré camel-herder demo — please add Tigré and Tigrinya subtitles.",
    "Here's a 4-minute Wolof teacher classroom video — overlay Wolof and Sereer subtitles.",
    "I have a 2-minute Yoruba market-vendor explainer — please add Yoruba and Igbo subtitles.",
    # ── more bilingual subtitle requests (50) ─────────────────────────────
    "Uploading a 2-minute Maltese-cuisine demo — please add Maltese and English subtitles.",
    "Here's a 90-second Sardinian-bread-baker — overlay Sardinian and Italian subtitles.",
    "I have a 3-minute Sicilian-fishmonger video — please add Sicilian and Italian subtitles.",
    "Uploading a 1-minute Romansh-shepherd interview — overlay Romansh and German subtitles.",
    "Here's a 4-minute Ladin-glassblower demo — please add Ladin and Italian subtitles.",
    "I'm sending you a 90-second Friulian-folk-musician — overlay Friulian and Italian subtitles.",
    "Uploading a 2-minute Occitan-rosé winemaker demo — please add Occitan and French subtitles.",
    "Here's a 3-minute Galego-fisherman interview — overlay Galego and Spanish subtitles.",
    "I have a 1-minute Asturian-cider-maker demo — please add Asturian and Spanish subtitles.",
    "Uploading a 4-minute Aragonese-shepherd interview — overlay Aragonese and Spanish subtitles.",
    "Here's a 90-second Aranese-shepherd video — please add Aranese and Catalan subtitles.",
    "I'm sending you a 2-minute Aromanian-grandmother cooking — overlay Aromanian and Greek subtitles.",
    "Uploading a 3-minute Megleno-Romanian shepherd demo — please add Megleno-Romanian and Macedonian subtitles.",
    "Here's a 1-minute Pomak-grandmother weaving demo — overlay Pomak and Bulgarian subtitles.",
    "I have a 4-minute Gagauz-grandmother making manjas — please add Gagauz and Romanian subtitles.",
    "Uploading a 90-second Lemko-folk-singer performance — overlay Lemko and Polish subtitles.",
    "Here's a 2-minute Rusyn-grandmother weaving demo — please add Rusyn and Slovak subtitles.",
    "I'm sending you a 3-minute Kashubian-fisherman interview — overlay Kashubian and Polish subtitles.",
    "Uploading a 1-minute Silesian-coal-miner demo — please add Silesian and Polish subtitles.",
    "Here's a 4-minute Sorbian-grandmother making cottage cheese — overlay Sorbian and German subtitles.",
    "I have a 90-second Plautdietsch-Mennonite-grandmother baking — please add Plautdietsch and German subtitles.",
    "Uploading a 2-minute Yiddish-Hasidic-baker bread demo — overlay Yiddish and Hebrew subtitles.",
    "Here's a 3-minute Ladino-Sephardic-grandmother cooking — please add Ladino and Spanish subtitles.",
    "I'm sending you a 1-minute Karaim-grandmother ribbon-cookie making — overlay Karaim and Lithuanian subtitles.",
    "Uploading a 4-minute Crimean-Tatar-grandmother dolma-making — please add Crimean Tatar and Russian subtitles.",
    "Here's a 90-second Karachay-grandfather felt-making demo — overlay Karachay-Balkar and Russian subtitles.",
    "I have a 2-minute Kabardian-shepherd making khinkali — please add Kabardian and Russian subtitles.",
    "Uploading a 3-minute Adyghe-grandfather sword-smithing demo — overlay Adyghe and Russian subtitles.",
    "Here's a 1-minute Abkhaz-grandmother cornbread baking — please add Abkhaz and Russian subtitles.",
    "I'm sending you a 4-minute Ossetian-grandfather millet-cake making — overlay Ossetian and Russian subtitles.",
    "Uploading a 90-second Chechen-grandmother chepalgash baking — please add Chechen and Russian subtitles.",
    "Here's a 2-minute Ingush-grandfather kurkay flute demo — overlay Ingush and Russian subtitles.",
    "I have a 3-minute Avar-grandmother dolma making — please add Avar and Russian subtitles.",
    "Uploading a 1-minute Lezgi-grandmother dargiya cooking — overlay Lezgi and Russian subtitles.",
    "Here's a 4-minute Dargwa-grandfather kura-stick game — please add Dargwa and Russian subtitles.",
    "I'm sending you a 90-second Lak-grandmother khinkali making — overlay Lak and Russian subtitles.",
    "Uploading a 2-minute Tabasaran-grandmother carpet-weaving — please add Tabasaran and Russian subtitles.",
    "Here's a 3-minute Tat-grandmother chudu-baking — overlay Tat and Russian subtitles.",
    "I have a 1-minute Talysh-grandmother lavash-baking — please add Talysh and Persian subtitles.",
    "Uploading a 4-minute Khakas-grandmother boorsok making — overlay Khakas and Russian subtitles.",
    "Here's a 90-second Tuvan-throat-singer performance — please add Tuvan and Russian subtitles.",
    "I'm sending you a 2-minute Yakut-grandmother making salamat — overlay Yakut and Russian subtitles.",
    "Uploading a 3-minute Buryat-grandfather buuza making — please add Buryat and Russian subtitles.",
    "Here's a 1-minute Evenki-reindeer-herder interview — overlay Evenki and Russian subtitles.",
    "I have a 4-minute Even-grandmother making salamat — please add Even and Russian subtitles.",
    "Uploading a 90-second Chukchi-grandmother making mantak — overlay Chukchi and Russian subtitles.",
    "Here's a 2-minute Koryak-grandmother making yikupukin — please add Koryak and Russian subtitles.",
    "I'm sending you a 3-minute Itelmen-grandmother fish-pie making — overlay Itelmen and Russian subtitles.",
    "Uploading a 1-minute Nivkh-grandmother salmon-fishing demo — please add Nivkh and Russian subtitles.",
    "Here's a 4-minute Ainu-grandmother making citatap — overlay Ainu and Japanese subtitles.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
