"""x15 highlight_only GRPO short briefs. Disjoint from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 2-hour Sunday morning sermon recording — please extract the highlight teaching points.",
    "Here's a 4-hour wildlife photography safari recording — pull the highlight animal sightings.",
    "I have a 3-hour livestream of my Saturday hike — please extract the highlight scenic moments.",
    "Uploading a 5-hour open-water diving recording — extract the highlight reef moments.",
    "Here's a 90-minute SpaceX launch livestream — please pull the highlight separation moments.",
    "I'm sending you a 2-hour Stargate session VOD — pull the highlight cinematic moments.",
    "Uploading a 4-hour orchid-show recording — please extract the highlight rare-bloom moments.",
    "Here's a 3-hour fly-tying livestream — pull the highlight finished-fly reveals.",
    "I have a 90-minute amateur drone aerial-surveillance recording — extract the highlight property views.",
    "Uploading a 2-hour bird-watching video from a Costa Rica reserve — pull the highlight bird sightings.",
    "Here's a 4-hour aurora-borealis overnight time-lapse — please extract the highlight peak displays.",
    "I'm sending you a 3-hour amateur taxidermy documentary — pull the highlight detailing moments.",
    "Uploading a 90-minute robotics-competition VOD — extract the highlight match clips.",
    "Here's a 2-hour ASMR cooking livestream — please pull the highlight knife-work moments.",
    "I have a 4-hour beekeeping inspection livestream — extract the highlight queen-spotting moments.",
    "Uploading a 5-hour amateur astronomy live recording — pull the highlight celestial moments.",
    "Here's a 90-minute pottery workshop livestream — please extract the highlight wheel-throwing demos.",
    "I'm sending you a 2-hour glass-blowing studio livestream — pull the highlight finished-piece reveals.",
    "Uploading a 3-hour aquarium night-watch recording — extract the highlight predator-feeding moments.",
    "Here's a 4-hour woodworking shop livestream — please pull the highlight finishing-step demos.",
    "I have a 90-minute ham-radio contest recording — extract the highlight contact moments.",
    "Uploading a 2-hour kite-festival video — pull the highlight launches and aerobatics.",
    "Here's a 5-hour cosplay-convention masquerade — please extract the highlight runway walks.",
    "I'm sending you a 3-hour magic-conference livestream — pull the highlight closing-trick moments.",
    "Uploading a 90-minute spelling bee preliminary — extract the highlight word moments.",
    "Here's a 4-hour Renaissance Faire stage VOD — please pull the highlight performance moments.",
    "I have a 2-hour comedy improv long-form VOD — extract the highlight improv scenes.",
    "Uploading a 3-hour state-fair beauty pageant — pull the highlight crowning moments.",
    "Here's a 90-minute amateur magic show — please extract the highlight illusion moments.",
    "I'm sending you a 2-hour barbershop quartet competition — pull the highlight harmony moments.",
    "Uploading a 4-hour book-fair livestream — extract the highlight author-reading moments.",
    "Here's a 5-hour county-fair eating-contest — please pull the highlight finishing moments.",
    "I have a 90-minute axe-throwing-league night — extract the highlight bullseye throws.",
    "Uploading a 2-hour disc-jockey livestream from a beach club — pull the highlight drop moments.",
    "Here's a 3-hour circus-arts open-stage VOD — please extract the highlight aerial-silk moments.",
    "I'm sending you a 4-hour storm-chasing recording — pull the highlight tornado-spotting moments.",
    "Uploading a 90-minute speed-cubing tournament VOD — extract the highlight sub-10-second solves.",
    "Here's a 2-hour amateur-radio Field Day recording — please pull the highlight contact moments.",
    "I have a 5-hour youth choir competition — extract the highlight performance moments.",
    "Uploading a 3-hour high-school marching-band finals — pull the highlight halftime moments.",
    "Here's a 90-minute high-school dance-team competition — please extract the highlight routine moments.",
    "I'm sending you a 2-hour pickleball-instructor demo session — pull the highlight teaching moments.",
    "Uploading a 4-hour fly-fishing tournament — extract the highlight catch-and-release moments.",
    "Here's a 3-hour bow-fishing tournament — please pull the highlight catch moments.",
    "I have a 90-minute bee-keeping inspection livestream — extract the highlight inspection moments.",
    "Uploading a 2-hour amateur sumo wrestling tournament — pull the highlight bouts.",
    "Here's a 4-hour falconry-meet competition — please extract the highlight flight moments.",
    "I'm sending you a 3-hour Junior Olympics rowing event — pull the highlight finishes.",
    "Uploading a 90-minute college a-cappella championship — extract the highlight performance moments.",
    "Here's a 2-hour amateur stand-up comedy night — please pull the highlight bits.",
    "I have a 5-hour Iditarod sled-dog livestream — extract the highlight checkpoint moments.",
    "Uploading a 90-minute regional spelling-bee — pull the highlight winning moments.",
    "Here's a 2-hour amateur juggling festival — please extract the highlight pattern attempts.",
    "I'm sending you a 3-hour competitive eating contest — pull the highlight finishing moments.",
    "Uploading a 4-hour amateur chess tournament — extract the highlight winning moves.",
    "Here's a 90-minute axe-throwing-league finals — please pull the highlight bullseyes.",
    "I have a 2-hour dragon-boat-festival opening — extract the highlight launch moments.",
    "Uploading a 3-hour synchronized-swimming nationals — pull the highlight routine moments.",
    "Here's a 4-hour ultramarathon livestream — please extract the highlight finishing moments.",
    "I'm sending you a 5-hour amateur sailing regatta — pull the highlight tack moments.",
    "Uploading a 90-minute amateur amateur boxing exhibition — extract the highlight scoring moments.",
    "Here's a 2-hour judo state finals — please pull the highlight throw moments.",
    "I have a 3-hour amateur kickboxing tournament — extract the highlight knockout moments.",
    "Uploading a 4-hour amateur cornhole nationals — pull the highlight bag-toss moments.",
    "Here's a 90-minute youth volleyball state finals — please extract the highlight rallies.",
    "I'm sending you a 2-hour amateur dirt-bike racing event — pull the highlight overtakes.",
    "Uploading a 3-hour amateur bowling-league tournament — extract the highlight strikes.",
    "Here's a 4-hour college water-polo championship — please pull the highlight goals.",
    "I have a 5-hour high-school girls' lacrosse tournament — extract the highlight goal moments.",
    "Uploading a 90-minute high-school robotics competition — pull the highlight match moments.",
    "Here's a 2-hour amateur ham-radio contest — please extract the highlight contact moments.",
    "I'm sending you a 3-hour state-fair pole-vault competition — pull the highlight clearings.",
    "Uploading a 4-hour amateur orienteering meet — extract the highlight finishing moments.",
    "Here's a 90-minute lawn-bowling tournament — please pull the highlight strike moments.",
    "I have a 2-hour amateur hockey league tournament — extract the highlight goals.",
    "Uploading a 3-hour amateur curling provincials — pull the highlight stone moments.",
    # ── more highlight extractions (50) ───────────────────────────────────
    "Uploading a 2-hour wedding anniversary party recording — please extract the highlight toasts.",
    "Here's a 3-hour 50th-birthday celebration — pull the highlight speeches.",
    "I have a 4-hour quinceañera celebration recording — please extract the highlight dance moments.",
    "Uploading a 90-minute bar-mitzvah ceremony — pull the highlight Torah-reading moments.",
    "Here's a 2-hour bat-mitzvah ceremony recording — please extract the highlight family moments.",
    "I'm sending you a 5-hour Indian wedding ceremony — pull the highlight ritual moments.",
    "Uploading a 3-hour Korean traditional wedding — please extract the highlight ceremony moments.",
    "Here's a 2-hour Chinese wedding banquet — pull the highlight tea-ceremony moments.",
    "I have a 4-hour Greek wedding reception — please extract the highlight zeibekiko moments.",
    "Uploading a 3-hour Italian wedding reception — pull the highlight tarantella moments.",
    "Here's a 90-minute Filipino baptism celebration — please extract the highlight ninang/ninong moments.",
    "I'm sending you a 2-hour Mexican quinceañera — pull the highlight waltz moments.",
    "Uploading a 3-hour Brazilian birthday celebration — please extract the highlight samba moments.",
    "Here's a 4-hour Argentinian asado celebration — pull the highlight dance moments.",
    "I have a 90-minute Japanese tea ceremony — please extract the highlight chanoyu moments.",
    "Uploading a 2-hour Korean dol-jabi ceremony — pull the highlight first-pick moments.",
    "Here's a 3-hour Vietnamese Tet celebration — please extract the highlight family-blessing moments.",
    "I'm sending you a 4-hour Thai Songkran celebration — pull the highlight water-festival moments.",
    "Uploading a 5-hour Indian Diwali celebration — please extract the highlight diya-lighting moments.",
    "Here's a 90-minute Persian Nowruz celebration — pull the highlight haft-sin moments.",
    "I have a 2-hour Egyptian Eid celebration — please extract the highlight family-meal moments.",
    "Uploading a 3-hour Saudi Hajj documentary — pull the highlight Tawaf moments.",
    "Here's a 4-hour Mecca-Hajj documentary — please extract the highlight Sa'i moments.",
    "I'm sending you a 90-minute Turkish whirling-dervish ceremony — pull the highlight sema moments.",
    "Uploading a 2-hour Sufi-tariqa gathering — please extract the highlight zikr moments.",
    "Here's a 3-hour Eastern-Orthodox Easter vigil — pull the highlight chant moments.",
    "I have a 4-hour Catholic-Easter vigil — please extract the highlight Exsultet moments.",
    "Uploading a 90-minute Quaker silent-meeting — pull the highlight ministry moments.",
    "Here's a 2-hour Bahá'í-fast celebration — please extract the highlight devotional moments.",
    "I'm sending you a 5-hour Hindu-puja gathering — pull the highlight aarti moments.",
    "Uploading a 3-hour Sikh-kirtan gathering — please extract the highlight harmonium moments.",
    "Here's a 2-hour Buddhist-uposatha-day gathering — pull the highlight chant moments.",
    "I have a 4-hour Tibetan Losar celebration — please extract the highlight tsampa-throwing moments.",
    "Uploading a 3-hour Mongolian Naadam festival — pull the highlight wrestling moments.",
    "Here's a 90-minute Inuit-throat-singing competition — please extract the highlight katajjaq moments.",
    "I'm sending you a 2-hour Sami-yoik festival — pull the highlight yoik moments.",
    "Uploading a 3-hour Faroese-grindadrap commemoration — please extract the highlight ceremony moments.",
    "Here's a 4-hour Maori-haka competition — pull the highlight haka moments.",
    "I have a 90-minute Hawaiian-hula festival — please extract the highlight hula moments.",
    "Uploading a 2-hour Aboriginal-corroboree gathering — pull the highlight ceremonial moments.",
    "Here's a 3-hour Zulu-Reed Dance ceremony — please extract the highlight ceremonial moments.",
    "I'm sending you a 4-hour Maasai-warrior-graduation ceremony — pull the highlight ceremonial moments.",
    "Uploading a 90-minute Igbo masquerade festival — please extract the highlight masquerade moments.",
    "Here's a 2-hour Yoruba-Egungun festival — pull the highlight masquerade moments.",
    "I have a 3-hour Ghanaian-Adae festival — please extract the highlight ritual moments.",
    "Uploading a 4-hour Senegalese-Wolof gamou celebration — pull the highlight chant moments.",
    "Here's a 90-minute Ethiopian-Timkat celebration — please extract the highlight procession moments.",
    "I'm sending you a 2-hour Moroccan-Mawlid celebration — pull the highlight chant moments.",
    "Uploading a 3-hour Sudanese-Mawlid celebration — please extract the highlight Sufi-zikr moments.",
    "Here's a 4-hour Tanzanian-Maulidi celebration — pull the highlight chant moments.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
