"""x15 style_music GRPO short briefs. Disjoint from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 1-minute desert-camping clip — please convert to Bedouin-tent illustration style and add a Sufi-ney BGM.",
    "Here's a 90-second Mongolian-steppe reel — render as Mongolian-thangka and overlay a Mongolian-throat-singing BGM.",
    "I have a 2-minute Tibetan-monastery reel — please style as a Tibetan-thangka and add a Tibetan-singing-bowl BGM.",
    "Uploading a 45-second Bhutanese-prayer-flag reel — convert to a Bhutanese-folk-art illustration and overlay a Bhutanese-flute BGM.",
    "Here's a 1-minute Nepali-Annapurna reel — please render as a Nepali-thangka and add a bansuri-Nepali BGM.",
    "I'm sending you a 30-second Sri-Lanka-stilt-fishing reel — style as a Sri-Lankan-folk illustration and overlay a Sri-Lankan-rabana-drum BGM.",
    "Uploading a 90-second Maldives-snorkel reel — please render as an Indian-Ocean-art illustration and add a tropical-steel-drum BGM.",
    "Here's a 2-minute Madagascar-baobab reel — convert to a Madagascan-folk-art illustration and overlay a Malagasy-valiha BGM.",
    "I have a 1-minute Zanzibar-spice-market reel — please style as a Swahili-coastal illustration and add a Swahili-taarab BGM.",
    "Uploading a 30-second Lamu-Old-Town reel — render as a Swahili-coastal illustration and overlay a Swahili-taarab BGM.",
    "Here's a 45-second Cape-Town-Table-Mountain reel — please convert to a South-African-folk illustration and add a South-African-marabi BGM.",
    "I'm sending you a 1-minute Kenya-Maasai-Mara reel — style as a Maasai-folk illustration and overlay a Kenyan-benga BGM.",
    "Uploading a 90-second Ethiopia-Lalibela reel — please render as an Ethiopian-Coptic illumination and add an Ethiopian-azmari BGM.",
    "Here's a 2-minute Egypt-Aswan-felucca reel — convert to an Egyptian-tomb-painting style and overlay an Egyptian-oud BGM.",
    "I have a 1-minute Morocco-Chefchaouen reel — please style as a Moroccan-zellige tile pattern and add a Moroccan-gnawa BGM.",
    "Uploading a 30-second Senegal-Goree-Island reel — render as a Senegalese-folk-art illustration and overlay a Senegalese-mbalax BGM.",
    "Here's a 45-second Ghana-Accra-market reel — please convert to a Ghanaian-folk-art illustration and add a Ghanaian-highlife BGM.",
    "I'm sending you a 1-minute Nigeria-Lagos-street reel — style as a Yoruba-folk-art illustration and overlay a Nigerian-juju BGM.",
    "Uploading a 90-second Mali-Timbuktu reel — please render as a Songhai-Empire illuminated manuscript and add a Mali-kora BGM.",
    "Here's a 2-minute Cote-d-Ivoire-Abidjan reel — convert to an Akan-cloth Kente-pattern style and overlay an Ivorian-zouglou BGM.",
    "I have a 1-minute Cameroon-rainforest reel — please style as a Bamileke-folk-art illustration and add a Cameroonian-makossa BGM.",
    "Uploading a 30-second Gabon-jungle reel — render as a Punu-mask illustration and overlay a Gabonese-mvet BGM.",
    "Here's a 45-second Congo-Kinshasa reel — please convert to a Kongo-folk-art illustration and add a Congolese-rumba BGM.",
    "I'm sending you a 1-minute Zambia-Victoria-Falls reel — style as a Zambian-folk-art illustration and overlay a Zambian-kalimba BGM.",
    "Uploading a 90-second Zimbabwe-Great-Zimbabwe ruin reel — please render as a Shona-stone-sculpture illustration and add a Zimbabwean-mbira BGM.",
    "Here's a 2-minute Botswana-Okavango reel — convert to a Tswana-folk-art illustration and overlay a Tswana-segaba BGM.",
    "I have a 1-minute Namibia-Sossusvlei reel — please style as a Himba-folk-art illustration and add a Namibian-oviritje BGM.",
    "Uploading a 30-second Mozambique-Bazaruto reel — render as a Makonde-mask illustration and overlay a Mozambican-marrabenta BGM.",
    "Here's a 45-second Madagascar-Avenue-of-the-Baobabs reel — please convert to a Malagasy-folk-art illustration and add a Malagasy-valiha BGM.",
    "I'm sending you a 1-minute Réunion-volcano reel — style as a Réunionese-folk-art illustration and overlay a Réunionese-maloya BGM.",
    "Uploading a 90-second Mauritius-Le-Morne reel — please render as a Mauritian-folk-art illustration and add a Mauritian-séga BGM.",
    "Here's a 2-minute Seychelles-Praslin-beach reel — convert to a Seychellois-folk-art illustration and overlay a Seychellois-séga BGM.",
    "I have a 1-minute Comoros-volcano reel — please style as a Comorian-folk-art illustration and add a Comorian-twarab BGM.",
    "Uploading a 30-second Sao-Tome-and-Principe reel — render as a São-Toméan-folk-art illustration and overlay a Lundum BGM.",
    "Here's a 45-second Cape-Verde-Tarrafal reel — please convert to a Cape-Verdean-folk-art illustration and add a Cape-Verdean-morna BGM.",
    "I'm sending you a 1-minute Algeria-Sahara-dune reel — style as an Algerian-Berber illustration and overlay an Algerian-rai BGM.",
    "Uploading a 90-second Tunisia-Sidi-Bou-Said reel — please render as a Tunisian-tile-pattern illustration and add a Tunisian-mizoued BGM.",
    "Here's a 2-minute Libya-Leptis-Magna reel — convert to a Roman-Libyan mosaic illustration and overlay a Libyan-tabl-baladi BGM.",
    "I have a 1-minute Sudan-Meroë-pyramid reel — please style as a Nubian-illumination and add a Sudanese-tambour BGM.",
    "Uploading a 30-second Eritrea-Asmara reel — render as an Eritrean-folk-art illustration and overlay an Eritrean-krar BGM.",
    "Here's a 45-second Djibouti-Lake-Assal reel — please convert to a Djiboutian-folk-art illustration and add a Djiboutian-tanbura BGM.",
    "I'm sending you a 1-minute Somalia-coastal reel — style as a Somali-folk-art illustration and overlay a Somali-oud BGM.",
    "Uploading a 90-second South-Sudan-Sudd reel — please render as a Dinka-folk-art illustration and add a South-Sudanese-thom BGM.",
    "Here's a 2-minute Uganda-Kampala reel — convert to a Bagandan-folk-art illustration and overlay a Ugandan-akogo BGM.",
    "I have a 1-minute Rwanda-Lake-Kivu reel — please style as a Rwandan-Imigongo-pattern illustration and add a Rwandan-inanga BGM.",
    "Uploading a 30-second Burundi-Bujumbura reel — render as a Burundian-folk-art illustration and overlay a Burundian-ikembe BGM.",
    "Here's a 45-second Tanzania-Serengeti reel — please convert to a Tanzanian-Tinga-Tinga painting and add a Tanzanian-bongo-flava BGM.",
    "I'm sending you a 1-minute Kenya-Mount-Kenya reel — style as a Kikuyu-folk-art illustration and overlay a Kenyan-benga BGM.",
    "Uploading a 90-second Malawi-Lake-Malawi reel — please render as a Malawian-folk-art illustration and add a Malawian-malipenga BGM.",
    "Here's a 2-minute Lesotho-Maluti-mountains reel — convert to a Basotho-blanket-pattern illustration and overlay a Basotho-lekolulo BGM.",
    "I have a 1-minute Eswatini-Mlilwane reel — please style as a Swazi-folk-art illustration and add a Swazi-makhweyana BGM.",
    "Uploading a 30-second Angola-Tundavala reel — render as an Angolan-folk-art illustration and overlay an Angolan-kuduro BGM.",
    "Here's a 45-second Equatorial-Guinea-Bioko reel — please convert to a Bubi-folk-art illustration and add an Equatoguinean-kamba BGM.",
    "I'm sending you a 1-minute Central-African-Republic-rainforest reel — style as a Bayaka-folk-art illustration and overlay a CAR-ngombi BGM.",
    "Uploading a 90-second Chad-Ennedi reel — please render as a Toubou-folk-art illustration and add a Chadian-kakaki BGM.",
    "Here's a 2-minute Niger-Aïr-Mountains reel — convert to a Tuareg-leather-art illustration and overlay a Tuareg-tinde BGM.",
    "I have a 1-minute Burkina-Faso-Banfora reel — please style as a Mossi-folk-art illustration and add a Burkinabé-kora BGM.",
    "Uploading a 30-second Benin-Cotonou reel — render as a Fon-appliqué illustration and overlay a Beninese-zinli BGM.",
    "Here's a 45-second Togo-Lome reel — please convert to an Ewe-folk-art illustration and add a Togolese-agbadza BGM.",
    "I'm sending you a 1-minute Liberia-coastal reel — style as a Kru-folk-art illustration and overlay a Liberian-konghoma BGM.",
    "Uploading a 90-second Sierra-Leone-Banana-Islands reel — please render as a Mende-folk-art illustration and add a Sierra-Leonean-balangi BGM.",
    "Here's a 2-minute Guinea-Bissau-Bijagos-Islands reel — convert to a Bijago-folk-art illustration and overlay a Bissau-Guinean-gumbe BGM.",
    "I have a 1-minute Guinea-Conakry reel — please style as a Manding-folk-art illustration and add a Guinean-bolon BGM.",
    "Uploading a 30-second Mauritania-Banc-d-Arguin reel — render as an Imraguen-folk-art illustration and overlay a Mauritanian-tidinit BGM.",
    "Here's a 45-second Western-Sahara-Sahara-coastal reel — please convert to a Sahrawi-folk-art illustration and add a Sahrawi-haul BGM.",
    # ── more style + BGM combo requests (50) ──────────────────────────────
    "Uploading a 1-minute clip of an Antarctic-research-station — please style as a Caspar-David-Friedrich Romantic painting and add a sparse-piano BGM.",
    "Here's a 30-second clip of an Arctic-aurora-dome — convert to an Inuit-folk-art illustration and overlay an ambient-pad BGM.",
    "I have a 45-second clip of a Sami-reindeer-herding morning — please style as a Sami-duodji illustration and add a Sami-yoik BGM.",
    "Uploading a 2-minute clip of a Mongolian-yurt-camp — render as a Mongolian-thangka illustration and overlay a Mongolian-throat-singing BGM.",
    "Here's a 90-second clip of a Tibetan-monastery courtyard — please convert to a Tibetan-thangka and add a Tibetan-singing-bowl BGM.",
    "I'm sending you a 30-second clip of a Bhutanese-prayer-flag pass — style as a Bhutanese-folk-art illustration and overlay a Bhutanese-flute BGM.",
    "Uploading a 1-minute clip of a Nepali-Annapurna trek — please render as a Nepali-thangka and add a bansuri-Nepali BGM.",
    "Here's a 45-second clip of a Sri-Lanka stilt-fishing — convert to a Sri-Lankan-folk illustration and overlay a Sri-Lankan-rabana-drum BGM.",
    "I have a 2-minute clip of a Maldives snorkel reef — please style as an Indian-Ocean-art illustration and add a tropical-steel-drum BGM.",
    "Uploading a 90-second clip of a Madagascar-baobab valley — render as a Madagascan-folk-art illustration and overlay a Malagasy-valiha BGM.",
    "Here's a 30-second clip of a Zanzibar spice-market — please convert to a Swahili-coastal illustration and add a Swahili-taarab BGM.",
    "I'm sending you a 1-minute clip of a Lamu-Old-Town stroll — style as a Swahili-coastal illustration and overlay a Swahili-taarab BGM.",
    "Uploading a 2-minute clip of a Cape-Town-Table-Mountain trek — please render as a South-African-folk illustration and add a South-African-marabi BGM.",
    "Here's a 45-second clip of a Kenya-Maasai-Mara safari — convert to a Maasai-folk illustration and overlay a Kenyan-benga BGM.",
    "I have a 90-second clip of an Ethiopia-Lalibela tour — please style as an Ethiopian-Coptic illumination and add an Ethiopian-azmari BGM.",
    "Uploading a 30-second clip of an Egypt-Aswan-felucca ride — render as an Egyptian-tomb-painting style and overlay an Egyptian-oud BGM.",
    "Here's a 1-minute clip of a Morocco-Chefchaouen blue-village — please convert to a Moroccan-zellige tile pattern and add a Moroccan-gnawa BGM.",
    "I'm sending you a 2-minute clip of a Senegal-Goree-Island stroll — style as a Senegalese-folk-art illustration and overlay a Senegalese-mbalax BGM.",
    "Uploading a 45-second clip of a Ghana-Accra-market — please render as a Ghanaian-folk-art illustration and add a Ghanaian-highlife BGM.",
    "Here's a 90-second clip of a Nigeria-Lagos-street — convert to a Yoruba-folk-art illustration and overlay a Nigerian-juju BGM.",
    "I have a 30-second clip of a Mali-Timbuktu sunset — please style as a Songhai-Empire illuminated manuscript and add a Mali-kora BGM.",
    "Uploading a 1-minute clip of a Cote-d-Ivoire-Abidjan stroll — render as an Akan-cloth Kente-pattern style and overlay an Ivorian-zouglou BGM.",
    "Here's a 2-minute clip of a Cameroon-rainforest hike — please convert to a Bamileke-folk-art illustration and add a Cameroonian-makossa BGM.",
    "I'm sending you a 45-second clip of a Gabon-jungle hike — style as a Punu-mask illustration and overlay a Gabonese-mvet BGM.",
    "Uploading a 90-second clip of a Congo-Kinshasa stroll — please render as a Kongo-folk-art illustration and add a Congolese-rumba BGM.",
    "Here's a 30-second clip of a Zambia-Victoria-Falls overlook — convert to a Zambian-folk-art illustration and overlay a Zambian-kalimba BGM.",
    "I have a 1-minute clip of a Zimbabwe-Great-Zimbabwe ruin — please style as a Shona-stone-sculpture illustration and add a Zimbabwean-mbira BGM.",
    "Uploading a 2-minute clip of a Botswana-Okavango boat — render as a Tswana-folk-art illustration and overlay a Tswana-segaba BGM.",
    "Here's a 45-second clip of a Namibia-Sossusvlei dawn — please convert to a Himba-folk-art illustration and add a Namibian-oviritje BGM.",
    "I'm sending you a 90-second clip of a Mozambique-Bazaruto reef — style as a Makonde-mask illustration and overlay a Mozambican-marrabenta BGM.",
    "Uploading a 30-second clip of a Madagascar-Avenue-of-the-Baobabs — please render as a Malagasy-folk-art illustration and add a Malagasy-valiha BGM.",
    "Here's a 1-minute clip of a Réunion-volcano hike — convert to a Réunionese-folk-art illustration and overlay a Réunionese-maloya BGM.",
    "I have a 2-minute clip of a Mauritius-Le-Morne mountain trek — please style as a Mauritian-folk-art illustration and add a Mauritian-séga BGM.",
    "Uploading a 45-second clip of a Seychelles-Praslin-beach — render as a Seychellois-folk-art illustration and overlay a Seychellois-séga BGM.",
    "Here's a 90-second clip of a Comoros-volcano hike — please convert to a Comorian-folk-art illustration and add a Comorian-twarab BGM.",
    "I'm sending you a 30-second clip of a Sao-Tome-and-Principe coast — style as a São-Toméan-folk-art illustration and overlay a Lundum BGM.",
    "Uploading a 1-minute clip of a Cape-Verde-Tarrafal beach — please render as a Cape-Verdean-folk-art illustration and add a Cape-Verdean-morna BGM.",
    "Here's a 2-minute clip of an Algeria-Sahara-dune sunset — convert to an Algerian-Berber illustration and overlay an Algerian-rai BGM.",
    "I have a 45-second clip of a Tunisia-Sidi-Bou-Said stroll — please style as a Tunisian-tile-pattern illustration and add a Tunisian-mizoued BGM.",
    "Uploading a 90-second clip of a Libya-Leptis-Magna ruin — render as a Roman-Libyan mosaic illustration and overlay a Libyan-tabl-baladi BGM.",
    "Here's a 30-second clip of a Sudan-Meroë-pyramid sunset — please convert to a Nubian-illumination and add a Sudanese-tambour BGM.",
    "I'm sending you a 1-minute clip of an Eritrea-Asmara stroll — style as an Eritrean-folk-art illustration and overlay an Eritrean-krar BGM.",
    "Uploading a 2-minute clip of a Djibouti-Lake-Assal overlook — please render as a Djiboutian-folk-art illustration and add a Djiboutian-tanbura BGM.",
    "Here's a 45-second clip of a Somalia-coastal stroll — convert to a Somali-folk-art illustration and overlay a Somali-oud BGM.",
    "I have a 90-second clip of a South-Sudan-Sudd swamp — please style as a Dinka-folk-art illustration and add a South-Sudanese-thom BGM.",
    "Uploading a 30-second clip of an Uganda-Kampala stroll — render as a Bagandan-folk-art illustration and overlay a Ugandan-akogo BGM.",
    "Here's a 1-minute clip of a Rwanda-Lake-Kivu boat — please convert to a Rwandan-Imigongo-pattern illustration and add a Rwandan-inanga BGM.",
    "I'm sending you a 2-minute clip of a Burundi-Bujumbura stroll — style as a Burundian-folk-art illustration and overlay a Burundian-ikembe BGM.",
    "Uploading a 45-second clip of a Tanzania-Serengeti safari — please render as a Tanzanian-Tinga-Tinga painting and add a Tanzanian-bongo-flava BGM.",
    "Here's a 90-second clip of a Kenya-Mount-Kenya climb — convert to a Kikuyu-folk-art illustration and overlay a Kenyan-benga BGM.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
