"""x15 vid_analysis_cr GRPO. Disjoint from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a Studio Ghibli forest-scene reference — please analyze its mood and produce a 1-minute new mini-drama.",
    "Here's a Cartoon-Saloon scene reference — analyze its Celtic-folk style and create a 45-second new cinematic short.",
    "I'm sending you a Laika stop-motion scene — please analyze the tactility and produce a 30-second new mini-drama.",
    "Uploading a Disney 2D classic scene — analyze the musical staging and create a 2-minute new cinematic short.",
    "Here's a Pixar emotional reference — analyze the arc and produce a 1-minute new mini-drama.",
    "I have a Don-Bluth reference scene — please analyze its expressive animation and create a 30-second new cinematic short.",
    "Uploading a Don-Hertzfeldt reference — analyze its surreal abstraction and produce a 45-second new mini-drama.",
    "Here's a Suzie Templeton stop-motion scene — analyze the tactile worldbuilding and create a 1-minute new cinematic short.",
    "I'm sending you a Wes-Anderson stop-motion reference — please analyze the symmetric framing and produce a 2-minute new mini-drama.",
    "Uploading a Tim-Burton reference — analyze the Gothic-whimsical mood and create a 30-second new cinematic short.",
    "Here's a Henry-Selick stop-motion reference — analyze the puppet character work and produce a 45-second new mini-drama.",
    "I have a Hayao-Miyazaki sky-creature reference — please analyze its motion and create a 1-minute new cinematic short.",
    "Uploading an Isao-Takahata observational reference — analyze the daily-life framing and produce a 30-second new mini-drama.",
    "Here's a Mamoru-Hosoda family-drama reference — analyze the warmth and create a 2-minute new cinematic short.",
    "I'm sending you a Makoto-Shinkai romantic reference — please analyze the melancholic light and produce a 1-minute new mini-drama.",
    "Uploading a Satoshi-Kon dream-sequence reference — analyze its surreal montage and create a 30-second new cinematic short.",
    "Here's a Mamoru-Oshii reference — analyze its philosophical pacing and produce a 45-second new mini-drama.",
    "I have a Katsuhiro-Otomo cyberpunk reference — please analyze its kinetic camera and create a 1-minute new cinematic short.",
    "Uploading a Cartoon-Network adult-swim reference — analyze its absurd comic timing and produce a 30-second new mini-drama.",
    "Here's a Genndy-Tartakovsky action reference — analyze the silent-action choreography and create a 2-minute new cinematic short.",
    "I'm sending you a Lord-and-Miller reference — please analyze its self-reference humor and produce a 1-minute new mini-drama.",
    "Uploading a Brad-Bird reference — analyze its character-staging and create a 30-second new cinematic short.",
    "Here's a Chris-Sanders reference — analyze its loose-line warmth and produce a 45-second new mini-drama.",
    "I have a Glen-Keane reference — please analyze its expressive line and create a 1-minute new cinematic short.",
    "Uploading a Hayao-Miyazaki opening-flight reference — analyze the wind choreography and produce a 30-second new mini-drama.",
    "Here's a Mary-Blair concept-art reference — analyze the color palette and create a 45-second new cinematic short.",
    "I'm sending you a Eyvind-Earle background reference — please analyze the stylized landscape and produce a 1-minute new mini-drama.",
    "Uploading a Maurice Noble background reference — analyze the abstract-modernist sets and create a 30-second new cinematic short.",
    "Here's a Pendleton-Ward Adventure-Time scene — analyze its absurd whimsy and produce a 2-minute new mini-drama.",
    "I have a Rebecca-Sugar Steven-Universe reference — please analyze its emotional close-ups and create a 1-minute new cinematic short.",
    "Uploading a Bryan-Konietzko Avatar reference — analyze its martial-art choreography and produce a 30-second new mini-drama.",
    "Here's a Mike DiMartino Korra reference — analyze its character-dynamic framing and create a 45-second new cinematic short.",
    "I'm sending you a Chloe-Zhao Eternals reference — please analyze the naturalist landscape and produce a 1-minute new mini-drama.",
    "Uploading a Taika-Waititi reference — analyze its absurd warmth and create a 30-second new cinematic short.",
    "Here's a Edgar-Wright reference — analyze its kinetic editing and produce a 45-second new mini-drama.",
    # ── more reference-video → new cinematic shorts (50) ──────────────
    "Uploading a Nick-Park Wallace-and-Gromit reference — please analyze its tactile claymation timing and produce a 1-minute new mini-drama.",
    "Here's a Sylvain-Chomet Triplets-of-Belleville reference — analyze its caricatured silent-comedy gags and create a 45-second new cinematic short.",
    "I'm sending you a Michel-Ocelot Kirikou reference — please analyze its silhouette aesthetic and produce a 30-second new mini-drama.",
    "Uploading a Tomm-Moore Wolfwalkers reference — analyze its hand-drawn dual-line aesthetic and create a 2-minute new cinematic short.",
    "Here's a Sergio-Pablos Klaus reference — analyze its volumetric 2D lighting and produce a 1-minute new mini-drama.",
    "I have a Jeremy-Clapin I-Lost-My-Body reference — please analyze its disembodied-perspective framing and create a 30-second new cinematic short.",
    "Uploading an Ari-Folman Waltz-with-Bashir reference — analyze its memory-as-animation collage and produce a 45-second new mini-drama.",
    "Here's a Marjane-Satrapi Persepolis reference — analyze its black-and-white memoir line and create a 1-minute new cinematic short.",
    "I'm sending you a Pete-Docter Inside-Out reference — please analyze its emotion-as-character design and produce a 30-second new mini-drama.",
    "Uploading an Andrew-Stanton Wall-E reference — analyze its dialogue-free opening pantomime and create a 2-minute new cinematic short.",
    "Here's a Lee-Unkrich Toy-Story-3 reference — analyze its incinerator-scene dread and produce a 1-minute new mini-drama.",
    "I have a Phil-Tippett Mad-God reference — please analyze its 30-year stop-motion grotesquerie and create a 45-second new cinematic short.",
    "Uploading a Jan-Švankmajer reference — analyze its Czech surreal object-animation and produce a 30-second new mini-drama.",
    "Here's a Jean-Pierre-Jeunet Amélie reference — analyze its saturated whimsy and create a 1-minute new cinematic short.",
    "I'm sending you a Marc-Caro Delicatessen reference — please analyze its grotesque tenement framing and produce a 2-minute new mini-drama.",
    "Uploading a Tom-Hooper Les-Misérables reference — analyze its live-singing close-ups and create a 30-second new cinematic short.",
    "Here's a Joe-Wright Atonement reference — analyze its Dunkirk long-take and produce a 45-second new mini-drama.",
    "I have a Sam-Mendes 1917 reference — please analyze its single-take illusion and create a 1-minute new cinematic short.",
    "Uploading a Steven-Soderbergh reference — analyze its split-diopter focus and produce a 30-second new mini-drama.",
    "Here's an Andrew-Dominik Killing-Them-Softly reference — analyze its slow-motion bullet ballet and create a 2-minute new cinematic short.",
    "I'm sending you a Denis-Villeneuve Arrival reference — please analyze its alien-language tableau and produce a 1-minute new mini-drama.",
    "Uploading a Christopher-McQuarrie Mission-Impossible reference — analyze its IMAX-set-piece coverage and create a 45-second new cinematic short.",
    "Here's a Mel-Brooks Producers reference — analyze its meta-theatrical staging and produce a 30-second new mini-drama.",
    "I have a Woody-Allen Annie-Hall reference — please analyze its fourth-wall asides and create a 1-minute new cinematic short.",
    "Uploading an Albert-Brooks Real-Life reference — analyze its mockumentary self-skewering and produce a 2-minute new mini-drama.",
    "Here's a Mike-Nichols Graduate reference — analyze its alienating long lens and create a 30-second new cinematic short.",
    "I'm sending you an Elaine-May Heartbreak-Kid reference — please analyze its wincing improvised dialogue and produce a 45-second new mini-drama.",
    "Uploading a Chuck-Jones Looney-Tunes reference — analyze its character-driven gag timing and create a 1-minute new cinematic short.",
    "Here's a Tex-Avery cartoon reference — analyze its rubber-limb extreme exaggeration and produce a 30-second new mini-drama.",
    "I have a Bill-Plympton indie-animation reference — please analyze its hand-drawn metamorphic gags and create a 45-second new cinematic short.",
    "Uploading a Ralph-Bakshi Fritz-the-Cat reference — analyze its rotoscoped urban grit and produce a 2-minute new mini-drama.",
    "Here's a Richard-Williams Thief-and-Cobbler reference — analyze its hyper-detailed Persian frame and create a 1-minute new cinematic short.",
    "I'm sending you a Hideaki-Anno Evangelion reference — please analyze its mecha-introspective close-up and produce a 30-second new mini-drama.",
    "Uploading a Yoshiaki-Kawajiri Wicked-City reference — analyze its neon-noir character animation and create a 45-second new cinematic short.",
    "Here's a Yasuhiro-Yoshiura Time-of-Eve reference — analyze its café-tableau composition and produce a 1-minute new mini-drama.",
    "I have a Masaaki-Yuasa Devilman-Crybaby reference — please analyze its expressionistic line metamorphosis and create a 30-second new cinematic short.",
    "Uploading a Naoko-Yamada Liz-and-the-Blue-Bird reference — analyze its delicate body-language framing and produce a 2-minute new mini-drama.",
    "Here's a Sunao-Katabuchi In-This-Corner-of-the-World reference — analyze its watercolor-inflected daily life and create a 1-minute new cinematic short.",
    "I'm sending you a Mike-Judge Office-Space reference — please analyze its deadpan corporate humor and produce a 45-second new mini-drama.",
    "Uploading a Trey-Parker Team-America reference — analyze its marionette-driven satire and create a 30-second new cinematic short.",
    "Here's an Adam-Curtis essay-film reference — analyze its archive-and-narration collage and produce a 1-minute new mini-drama.",
    "I have a Joshua-Oppenheimer Act-of-Killing reference — please analyze its perpetrator-reenactment framing and create a 45-second new cinematic short.",
    "Uploading an Aleksandr-Sokurov Russian-Ark reference — analyze its single-take Hermitage promenade and produce a 2-minute new mini-drama.",
    "Here's a Karen-Shakhnazarov Courier reference — analyze its late-Soviet tonal drift and create a 30-second new cinematic short.",
    "I'm sending you a Larisa-Shepitko Ascent reference — please analyze its winter-spiritual close-ups and produce a 1-minute new mini-drama.",
    "Uploading a Kira-Muratova Brief-Encounters reference — analyze its anti-melodic dialogue and create a 45-second new cinematic short.",
    "Here's an Alexei-Balabanov Brother reference — analyze its 1990s post-Soviet drift and produce a 30-second new mini-drama.",
    "I have a Kornél-Mundruczó Pieces-of-a-Woman reference — please analyze its 24-minute birth-scene long take and create a 1-minute new cinematic short.",
    "Uploading a György-Pálfi Hukkle reference — analyze its dialogue-free village ambient and produce a 2-minute new mini-drama.",
    "Here's a Yuriy-Norshteyn Hedgehog-in-the-Fog reference — analyze its hand-cut paper stop-motion and create a 45-second new cinematic short.",
    # ── more reference-video → new cinematic shorts (50) ──────────────
    "Uploading a Hayao-Miyazaki Spirited-Away reference — please analyze its bath-house tableau and produce a 1-minute new mini-drama.",
    "Here's an Isao-Takahata Grave-of-the-Fireflies reference — analyze its quiet wartime grief and create a 45-second new cinematic short.",
    "I'm sending you a Mamoru-Oshii Ghost-in-the-Shell reference — please analyze its rain-soaked cyberpunk staging and produce a 30-second new mini-drama.",
    "Uploading a Satoshi-Kon Paprika reference — analyze its dream-flow editing and create a 2-minute new cinematic short.",
    "Here's a Mamoru-Hosoda Wolf-Children reference — analyze its rural family-warmth and produce a 1-minute new mini-drama.",
    "I have a Makoto-Shinkai Weathering-with-You reference — please analyze its Tokyo-rain melancholia and create a 30-second new cinematic short.",
    "Uploading a Hideaki-Anno Shin-Godzilla reference — analyze its bureaucratic catastrophe rhythm and produce a 45-second new mini-drama.",
    "Here's a Yoshiaki-Kawajiri Vampire-Hunter-D reference — analyze its gothic-horror ink and create a 1-minute new cinematic short.",
    "I'm sending you a Studio-Trigger Cyberpunk-Edgerunners reference — please analyze its neon-Night-City frenzy and produce a 30-second new mini-drama.",
    "Uploading a Studio-Sunrise Gundam-Wing reference — analyze its mecha-pilot sortie and create a 2-minute new cinematic short.",
    "Here's a Studio-Bones My-Hero-Academia reference — analyze its hero-school exuberance and produce a 1-minute new mini-drama.",
    "I have a Studio-Wit Attack-on-Titan reference — please analyze its 3D-maneuver-gear chase and create a 30-second new cinematic short.",
    "Uploading a Studio-Madhouse Trigun reference — analyze its desert-gunslinger tone and produce a 45-second new mini-drama.",
    "Here's a Production-IG Psycho-Pass reference — analyze its near-future surveillance frame and create a 1-minute new cinematic short.",
    "I'm sending you a Studio-Pierrot Naruto reference — please analyze its hidden-village exposition and produce a 30-second new mini-drama.",
    "Uploading a Toei Dragon-Ball-Z reference — analyze its power-up tableau and create a 2-minute new cinematic short.",
    "Here's a Studio-Ufotable Demon-Slayer reference — analyze its watercolor sword choreography and produce a 1-minute new mini-drama.",
    "I have a CloverWorks Bocchi-the-Rock reference — please analyze its anxious-band-girl framing and create a 30-second new cinematic short.",
    "Uploading a Studio-MAPPA Jujutsu-Kaisen reference — analyze its kinetic curse-fight and produce a 45-second new mini-drama.",
    "Here's a Studio-Trigger Promare reference — analyze its triangle-and-pixel pop and create a 1-minute new cinematic short.",
    "I'm sending you a Studio-Bones Mob-Psycho-100 reference — please analyze its monochrome-burst esper energy and produce a 30-second new mini-drama.",
    "Uploading a Studio-Madhouse One-Punch-Man reference — analyze its parodic battle-power scaling and create a 2-minute new cinematic short.",
    "Here's a Studio-Ponoc Mary-and-the-Witch's-Flower reference — analyze its Ghibli-inheritor pacing and produce a 1-minute new mini-drama.",
    "I have a Studio-Gainax FLCL reference — please analyze its rapid-fire genre collage and create a 30-second new cinematic short.",
    "Uploading a Studio-Bones Cowboy-Bebop reference — analyze its jazz-noir saunter and produce a 45-second new mini-drama.",
    "Here's a Production-IG Stand-Alone-Complex reference — analyze its information-flow framing and create a 1-minute new cinematic short.",
    "I'm sending you a Yuriy-Norshteyn Tale-of-Tales reference — please analyze its layered cut-out poetry and produce a 30-second new mini-drama.",
    "Uploading a Soyuzmultfilm Cheburashka reference — analyze its hand-puppet warmth and create a 2-minute new cinematic short.",
    "Here's an Aardman Chicken-Run reference — analyze its plasticine-prison comedy and produce a 1-minute new mini-drama.",
    "I have a Pixar Inner-Workings reference — please analyze its bisected-body humor and create a 30-second new cinematic short.",
    "Uploading a Pixar Bao reference — analyze its silent dumpling-poignancy and produce a 45-second new mini-drama.",
    "Here's a Studio-Laika Kubo reference — analyze its origami-stop-motion magic and create a 1-minute new cinematic short.",
    "I'm sending you a Studio-Cartoon-Saloon Song-of-the-Sea reference — please analyze its Celtic-line storybook and produce a 30-second new mini-drama.",
    "Uploading an Aardman Shaun-the-Sheep reference — analyze its silent-pantomime farm gag and create a 2-minute new cinematic short.",
    "Here's a Disney Bolt reference — analyze its 3D-pup road-movie warmth and produce a 1-minute new mini-drama.",
    "I have a Disney Wreck-It-Ralph reference — please analyze its arcade-cabinet world-jumping and create a 30-second new cinematic short.",
    "Uploading a Disney Zootopia reference — analyze its anthropomorphic city tableau and produce a 45-second new mini-drama.",
    "Here's a Disney Frozen reference — analyze its musical icy-emotion arc and create a 1-minute new cinematic short.",
    "I'm sending you a Disney Encanto reference — please analyze its Colombian magical-realism family and produce a 30-second new mini-drama.",
    "Uploading a Disney Moana reference — analyze its Polynesian seafaring rhythm and create a 2-minute new cinematic short.",
    "Here's a Disney Tangled reference — analyze its tower-and-tower-down energy and produce a 1-minute new mini-drama.",
    "I have a Disney Princess-and-the-Frog reference — please analyze its 2D-revival jazz-bayou and create a 30-second new cinematic short.",
    "Uploading a Sony Spider-Verse Into-the-Spider-Verse reference — analyze its comic-book frame breaks and produce a 45-second new mini-drama.",
    "Here's a Sony Spider-Verse Across-the-Spider-Verse reference — analyze its multi-style multi-verse and create a 1-minute new cinematic short.",
    "I'm sending you a Netflix Mitchells-vs-the-Machines reference — please analyze its scrapbook family-rebellion and produce a 30-second new mini-drama.",
    "Uploading a Netflix Sea-Beast reference — analyze its sea-monster lore and create a 2-minute new cinematic short.",
    "Here's a DreamWorks Kung-Fu-Panda reference — analyze its martial-arts splash-page humor and produce a 1-minute new mini-drama.",
    "I have a DreamWorks How-to-Train-Your-Dragon reference — please analyze its dragon-flight intimacy and create a 30-second new cinematic short.",
    "Uploading an Illumination Despicable-Me reference — analyze its minion-mob slapstick and produce a 45-second new mini-drama.",
    "Here's a Pixar Soul reference — analyze its Great-Before metaphysical staging and create a 1-minute new cinematic short.",
    # ── more reference-video → new cinematic shorts (50) ──────────────
    "Uploading a Larry-David Curb-Your-Enthusiasm reference — please analyze its improvised-cringe rhythm and produce a 1-minute new mini-drama.",
    "Here's a Jerry-Seinfeld Seinfeld reference — analyze its observational-no-hugging-no-learning and create a 45-second new cinematic short.",
    "I'm sending you a Jenji-Kohan Orange-Is-the-New-Black reference — please analyze its ensemble-prison flashback and produce a 30-second new mini-drama.",
    "Uploading a Lena-Dunham Girls reference — analyze its Brooklyn-millennial discomfort and create a 2-minute new cinematic short.",
    "Here's a Mike-Schur Parks-and-Recreation reference — analyze its earnest-civic ensemble warmth and produce a 1-minute new mini-drama.",
    "I have a Mike-Schur The-Good-Place reference — please analyze its philosophical-twist comedy and create a 30-second new cinematic short.",
    "Uploading a Tina-Fey 30-Rock reference — analyze its rapid-meta-NBC humor and produce a 45-second new mini-drama.",
    "Here's a Mindy-Kaling The-Office reference — analyze its mockumentary cubicle pathos and create a 1-minute new cinematic short.",
    "I'm sending you a Donald-Glover Atlanta reference — please analyze its surreal-vignette anthology and produce a 2-minute new mini-drama.",
    "Uploading a Justin-Simien Dear-White-People reference — analyze its campus social-satire and create a 30-second new cinematic short.",
    "Here's a Lin-Manuel-Miranda In-the-Heights-film reference — analyze its block-party choreography and produce a 45-second new mini-drama.",
    "I have a Marielle-Heller Diary-of-a-Teenage-Girl reference — please analyze its diaristic 1970s SF and create a 1-minute new cinematic short.",
    "Uploading a Sara-Driver Sleepwalk reference — analyze its NY-no-wave deadpan and produce a 30-second new mini-drama.",
    "Here's a Hal-Hartley Henry-Fool reference — analyze its Long-Island deadpan philosophical garbage-man and create a 2-minute new cinematic short.",
    "I'm sending you a Whit-Stillman Damsels-in-Distress reference — please analyze its mannered-college talk and produce a 1-minute new mini-drama.",
    "Uploading a Noah-Baumbach Margot-at-the-Wedding reference — analyze its acidic-family-summer and create a 45-second new cinematic short.",
    "Here's a Joachim-Trier The-Worst-Person-in-the-World reference — analyze its time-leaping romantic chronicle and produce a 1-minute new mini-drama.",
    "I have a Lukas-Moodysson Lilya-4-Ever reference — please analyze its harrowing trafficking gaze and create a 30-second new cinematic short.",
    "Uploading a Roy-Andersson You-the-Living reference — analyze its static-tableau absurdity and produce a 2-minute new mini-drama.",
    "Here's an Aki-Kaurismäki Le-Havre reference — analyze its deadpan-port humanism and create a 1-minute new cinematic short.",
    "I'm sending you a Mike-Leigh Naked reference — please analyze its Thatcher-era street-monologue and produce a 30-second new mini-drama.",
    "Uploading a Ken-Loach Sweet-Sixteen reference — analyze its Glaswegian working-class realism and create a 45-second new cinematic short.",
    "Here's a Lynne-Ramsay You-Were-Never-Really-Here reference — analyze its hammer-violence and trauma-fragments and produce a 1-minute new mini-drama.",
    "I have an Andrea-Arnold Cow reference — please analyze its dairy-cow durational gaze and create a 30-second new cinematic short.",
    "Uploading a Steve-McQueen Hunger reference — analyze its Bobby-Sands long-take dialogue and produce a 2-minute new mini-drama.",
    "Here's a Joanna-Hogg The-Souvenir reference — analyze its 1980s-art-school memoir and create a 1-minute new cinematic short.",
    "I'm sending you an Andrew-Haigh 45-Years reference — please analyze its late-marriage quiet-fracture and produce a 30-second new mini-drama.",
    "Uploading a Charlie-Kaufman Synecdoche-New-York reference — analyze its life-as-meta-theatre and create a 45-second new cinematic short.",
    "Here's a Spike-Jonze Adaptation reference — analyze its meta-screenwriter recursion and produce a 1-minute new mini-drama.",
    "I have a Michel-Gondry Be-Kind-Rewind reference — please analyze its handmade-VHS sweded charm and create a 30-second new cinematic short.",
    "Uploading a PT-Anderson Boogie-Nights reference — analyze its Steadicam Valley ensemble and produce a 2-minute new mini-drama.",
    "Here's a PT-Anderson There-Will-Be-Blood reference — analyze its monumental drilling-and-faith and create a 1-minute new cinematic short.",
    "I'm sending you a PT-Anderson The-Master reference — please analyze its postwar masculine-cult dialogue and produce a 30-second new mini-drama.",
    "Uploading a PT-Anderson Phantom-Thread reference — analyze its couture-courtship rituals and create a 45-second new cinematic short.",
    "Here's a Coen-Brothers Fargo reference — analyze its Minnesota-nice grim-noir and produce a 1-minute new mini-drama.",
    "I have a Coen-Brothers The-Big-Lebowski reference — please analyze its noir-shaggy-dog and create a 30-second new cinematic short.",
    "Uploading a Coen-Brothers No-Country-for-Old-Men reference — analyze its sparse Texas dread and produce a 2-minute new mini-drama.",
    "Here's a Coen-Brothers Inside-Llewyn-Davis reference — analyze its 1961 folk-circular fatalism and create a 1-minute new cinematic short.",
    "I'm sending you a Wes-Anderson The-Royal-Tenenbaums reference — please analyze its dollhouse-family symmetry and produce a 30-second new mini-drama.",
    "Uploading a Wes-Anderson Moonrise-Kingdom reference — analyze its 1965 island-summer scout and create a 45-second new cinematic short.",
    "Here's a Wes-Anderson The-French-Dispatch reference — analyze its anthology-magazine vignettes and produce a 1-minute new mini-drama.",
    "I have a Sofia-Coppola Lost-in-Translation reference — please analyze its Tokyo-jet-lag intimacy and create a 30-second new cinematic short.",
    "Uploading a Sofia-Coppola Marie-Antoinette reference — analyze its post-punk Versailles and produce a 2-minute new mini-drama.",
    "Here's a Sofia-Coppola The-Virgin-Suicides reference — analyze its 1970s Detroit-suburb haze and create a 1-minute new cinematic short.",
    "I'm sending you a Greta-Gerwig Little-Women reference — please analyze its time-shuffled March-sisters and produce a 30-second new mini-drama.",
    "Uploading a Marielle-Heller Can-You-Ever-Forgive-Me reference — analyze its NY literary-forger melancholy and create a 45-second new cinematic short.",
    "Here's a Lila-Avilés The-Chambermaid reference — analyze its Mexico-City hotel-floor durational and produce a 1-minute new mini-drama.",
    "I have a Lila-Avilés Tótem reference — please analyze its single-day family-celebration and create a 30-second new cinematic short.",
    "Uploading a Mia-Hansen-Løve Bergman-Island reference — analyze its Fårö meta-Bergman echo and produce a 45-second new mini-drama.",
    "Here's a Mia-Hansen-Løve One-Fine-Morning reference — analyze its quiet-Parisian dual-life and create a 2-minute new cinematic short.",
    # ── more documentary / experimental / queer auteur cinema (50) ──
    "I have a Chris-Marker La-Jetée reference — please analyze its still-photo time-travel and produce a 1-minute new cinematic short.",
    "Uploading a Chris-Marker Sans-Soleil reference — analyze its essay-film Tokyo-Africa montage and create a 45-second new mini-drama.",
    "Here's a Maya-Deren Meshes-of-the-Afternoon reference — analyze its dream-mirror loop and produce a 1-minute new cinematic short.",
    "I'm sending you a Stan-Brakhage Mothlight reference — please analyze its insect-wing collage and create a 30-second new mini-drama.",
    "Uploading a Stan-Brakhage Window-Water-Baby-Moving reference — analyze its home-birth witness and produce a 45-second new cinematic short.",
    "Here's a Jonas-Mekas Walden reference — analyze its diary-film NY-bohemia and create a 1-minute new mini-drama.",
    "I have a Jonas-Mekas As-I-Was-Moving-Ahead reference — please analyze its 5-hour memory-collage and produce a 30-second new cinematic short.",
    "Uploading a Hollis-Frampton Zorns-Lemma reference — analyze its alphabet-cycle structuralism and create a 45-second new mini-drama.",
    "Here's a Michael-Snow Wavelength reference — analyze its 45-minute zoom-in and produce a 1-minute new cinematic short.",
    "I'm sending you a Michael-Snow La-Région-Centrale reference — please analyze its mountain-360-mechanical and create a 30-second new mini-drama.",
    "Uploading an Andy-Warhol Empire reference — analyze its 8-hour Empire-State stare and produce a 45-second new cinematic short.",
    "Here's an Andy-Warhol Sleep reference — analyze its 5-hour sleeping-poet and create a 1-minute new mini-drama.",
    "I have a Kenneth-Anger Scorpio-Rising reference — please analyze its biker-occult pop-soundtrack and produce a 30-second new cinematic short.",
    "Uploading a Derek-Jarman Blue reference — analyze its single-blue-screen chant and create a 45-second new mini-drama.",
    "Here's a Derek-Jarman The-Last-of-England reference — analyze its Super-8 Thatcher-era collage and produce a 1-minute new cinematic short.",
    "I'm sending you a Sally-Potter Orlando reference — please analyze its centuries-spanning Tilda-Swinton and create a 30-second new mini-drama.",
    "Uploading a Sally-Potter The-Tango-Lesson reference — analyze its Paris-Buenos-Aires meta-romance and produce a 45-second new cinematic short.",
    "Here's a Patricio-Guzmán Nostalgia-for-the-Light reference — analyze its Atacama astronomy-and-bones essay and create a 1-minute new mini-drama.",
    "I have an Errol-Morris Fog-of-War reference — please analyze its McNamara-confessional interview-frame and produce a 30-second new cinematic short.",
    "Uploading a Werner-Herzog Cave-of-Forgotten-Dreams reference — analyze its 3D Chauvet-cave reverence and create a 45-second new mini-drama.",
    "Here's a Werner-Herzog Fitzcarraldo reference — analyze its boat-over-mountain madness and produce a 1-minute new cinematic short.",
    "I'm sending you a Werner-Herzog Aguirre-Wrath-of-God reference — please analyze its Amazon-raft conquistador and create a 30-second new mini-drama.",
    "Uploading a Werner-Herzog Stroszek reference — analyze its Wisconsin-immigrant dancing-chicken and produce a 45-second new cinematic short.",
    "Here's a Pedro-Almodóvar All-About-My-Mother reference — analyze its Barcelona-grief-trans family and create a 1-minute new mini-drama.",
    "I have a Pedro-Almodóvar Talk-to-Her reference — please analyze its bullfighter-coma love and produce a 30-second new cinematic short.",
    "Uploading a Pedro-Almodóvar Volver reference — analyze its La-Mancha-mother return and create a 45-second new mini-drama.",
    "Here's a Pedro-Almodóvar Pain-and-Glory reference — analyze its director-memoir-pain melancholy and produce a 1-minute new cinematic short.",
    "I'm sending you a Todd-Haynes Carol reference — please analyze its 1950s NY-romance glance and create a 30-second new mini-drama.",
    "Uploading a Todd-Haynes Far-from-Heaven reference — analyze its Sirk-pastiche suburbia and produce a 45-second new cinematic short.",
    "Here's a Todd-Haynes Velvet-Goldmine reference — analyze its glam-rock 70s-mosaic and create a 1-minute new mini-drama.",
    "I have a Cheryl-Dunye The-Watermelon-Woman reference — please analyze its mockumentary lesbian-archive and produce a 30-second new cinematic short.",
    "Uploading a Marlon-Riggs Tongues-Untied reference — analyze its Black-gay-poetic essay and create a 45-second new mini-drama.",
    "Here's an Isaac-Julien Looking-for-Langston reference — analyze its Harlem-Renaissance-dream-collage and produce a 1-minute new cinematic short.",
    "I'm sending you a Lana-Wachowski Cloud-Atlas reference — please analyze its six-era reincarnation-mosaic and create a 30-second new mini-drama.",
    "Uploading a Lana-Wachowski Speed-Racer reference — analyze its kaleidoscopic-track candy-color and produce a 45-second new cinematic short.",
    "Here's a Frances-Ha reference (Noah-Baumbach) — analyze its Brooklyn-twentysomething drift and create a 1-minute new mini-drama.",
    "I have a Joachim-Trier The-Worst-Person-in-the-World reference — please analyze its Oslo-twelve-chapter coming-of-age and produce a 30-second new cinematic short.",
    "Uploading a Joachim-Trier Oslo-31-August reference — analyze its single-day-recovery walking arc and create a 45-second new mini-drama.",
    "Here's a Lukas-Moodysson Show-Me-Love reference — analyze its Swedish-rural teen-queer awakening and produce a 1-minute new cinematic short.",
    "I'm sending you a Roy-Andersson Songs-from-the-Second-Floor reference — please analyze its tableau-deadpan absurdity and create a 30-second new mini-drama.",
    "Uploading a Roy-Andersson You-the-Living reference — analyze its dream-diary tableau-vignettes and produce a 45-second new cinematic short.",
    "Here's a Béla-Tarr Sátántangó reference — analyze its 7-hour Hungarian-village-decay and create a 1-minute new mini-drama.",
    "I have a Béla-Tarr The-Turin-Horse reference — please analyze its end-times farmhouse-wind and produce a 30-second new cinematic short.",
    "Uploading an Aleksandr-Sokurov Russian-Ark reference — analyze its single-take Hermitage-historical and create a 45-second new mini-drama.",
    "Here's a Sergei-Parajanov The-Color-of-Pomegranates reference — analyze its Armenian-iconographic tableau and produce a 1-minute new cinematic short.",
    "I'm sending you a Theo-Angelopoulos Eternity-and-a-Day reference — please analyze its dying-poet Thessaloniki and create a 30-second new mini-drama.",
    "Uploading an Apichatpong-Weerasethakul Uncle-Boonmee reference — analyze its Thai-jungle reincarnation and produce a 45-second new cinematic short.",
    "Here's an Apichatpong-Weerasethakul Memoria reference — analyze its Bogotá-jet-bang trance and create a 1-minute new mini-drama.",
    "I have a Tsai-Ming-liang Days reference — please analyze its silent-Taipei healing-massage and produce a 30-second new cinematic short.",
    "Uploading a Lav-Diaz From-What-Is-Before reference — analyze its 5-hour Filipino-rural-folklore and produce a 45-second new mini-drama.",
    # ── more Australian / NZ / South-African / Pacific cinema (50) ──
    "Here's a Peter-Weir Picnic-at-Hanging-Rock reference — analyze its Edwardian-girls-school disappearance and produce a 1-minute new cinematic short.",
    "I have a Peter-Weir Witness reference — please analyze its Amish-barn-raising sequence and create a 30-second new mini-drama.",
    "Uploading a Peter-Weir Truman-Show reference — analyze its dome-set fake-sky reveal and produce a 45-second new cinematic short.",
    "Here's a Bruce-Beresford Breaker-Morant reference — analyze its Boer-War court-martial and create a 1-minute new mini-drama.",
    "I'm sending you a Fred-Schepisi Chant-of-Jimmie-Blacksmith reference — please analyze its 19th-century Aboriginal-rage and produce a 30-second new cinematic short.",
    "Uploading a Peter-Faiman Crocodile-Dundee reference — analyze its Walkabout-NYC-fish-out-of-water and create a 45-second new mini-drama.",
    "Here's a Phillip-Noyce Rabbit-Proof-Fence reference — analyze its Stolen-Generations 1500-mile walk and produce a 1-minute new cinematic short.",
    "I have a George-Miller Mad-Max-Fury-Road reference — please analyze its War-Rig flame-guitar chase and create a 30-second new mini-drama.",
    "Uploading a George-Miller Babe reference — analyze its sheep-pig-trial farmyard and produce a 45-second new cinematic short.",
    "Here's a Baz-Luhrmann Strictly-Ballroom reference — analyze its Pan-Pacific-Grand-Prix paso-doble and create a 1-minute new mini-drama.",
    "I'm sending you a Baz-Luhrmann Romeo+Juliet reference — please analyze its Verona-Beach pool-meet and produce a 30-second new cinematic short.",
    "Uploading a Baz-Luhrmann Moulin-Rouge reference — analyze its Paris-windmill-cabaret elephant-room and create a 45-second new mini-drama.",
    "Here's a Cate-Shortland Somersault reference — analyze its Jindabyne-snowfield drift and produce a 1-minute new cinematic short.",
    "I have a Cate-Shortland Lore reference — please analyze its post-war German-children walk and create a 30-second new mini-drama.",
    "Uploading a Jennifer-Kent Babadook reference — analyze its single-mother bedroom-shadow and produce a 45-second new cinematic short.",
    "Here's a Jennifer-Kent Nightingale reference — analyze its 1825-Tasmanian-revenge-trek and create a 1-minute new mini-drama.",
    "I'm sending you a Warwick-Thornton Sweet-Country reference — please analyze its outback-fugitive-drover and produce a 30-second new cinematic short.",
    "Uploading a Rolf-de-Heer Ten-Canoes reference — analyze its Yolngu-language-canoe-prologue and create a 45-second new mini-drama.",
    "Here's a Ivan-Sen Mystery-Road reference — analyze its outback-detective long-shot and produce a 1-minute new cinematic short.",
    "I have a David-Michôd Animal-Kingdom reference — please analyze its Melbourne-crime-family kitchen and create a 30-second new mini-drama.",
    "Uploading a Justin-Kurzel Snowtown reference — analyze its Adelaide-suburban-killer kitchen and produce a 45-second new cinematic short.",
    "Here's a Justin-Kurzel Macbeth reference — analyze its Skye-battlefield slow-motion and create a 1-minute new mini-drama.",
    "I'm sending you a Garth-Davis Lion reference — please analyze its Calcutta-train Saroo-search and produce a 30-second new cinematic short.",
    "Uploading a Mel-Gibson Apocalypto reference — analyze its Mayan-jungle-chase and create a 45-second new mini-drama.",
    "Here's a Niki-Caro Whale-Rider reference — analyze its Whangara-Maori-leadership rite and produce a 1-minute new cinematic short.",
    "I have a Lee-Tamahori Once-Were-Warriors reference — please analyze its South-Auckland-domestic-violence kitchen and create a 30-second new mini-drama.",
    "Uploading a Taika-Waititi Hunt-for-the-Wilderpeople reference — analyze its NZ-bush-runaway boy and produce a 45-second new cinematic short.",
    "Here's a Taika-Waititi Boy reference — analyze its 1984-Waihau-Bay-marae visit and create a 1-minute new mini-drama.",
    "I'm sending you a Vincent-Ward Map-of-the-Human-Heart reference — please analyze its Inuit-WW2 epic and produce a 30-second new cinematic short.",
    "Uploading a Jane-Campion The-Piano reference — analyze its Te-Awamutu-beach piano-on-sand and create a 45-second new mini-drama.",
    "Here's a Jane-Campion Power-of-the-Dog reference — analyze its Montana-1925-ranch hide-tanning and produce a 1-minute new cinematic short.",
    "I have a Roger-Donaldson Smash-Palace reference — please analyze its NZ-wrecker-yard-custody and create a 30-second new mini-drama.",
    "Uploading a Geoff-Murphy Utu reference — analyze its 19th-century Maori-revenge raid and produce a 45-second new cinematic short.",
    "Here's a Vincent-Ward Vigil reference — analyze its NZ-mountain-farm grief and create a 1-minute new mini-drama.",
    "I'm sending you a Christine-Jeffs Rain reference — please analyze its New-Zealand-summer-bach drift and produce a 30-second new cinematic short.",
    "Uploading a Justin-Kurzel True-History-of-the-Kelly-Gang reference — analyze its outlaw-1870s-monologue and create a 45-second new mini-drama.",
    "Here's a Gillian-Armstrong My-Brilliant-Career reference — analyze its 1890s-Australian-bush-girl pen and produce a 1-minute new cinematic short.",
    "I have a Stephan-Elliott Priscilla-Queen-of-the-Desert reference — please analyze its drag-bus-outback drag-show and create a 30-second new mini-drama.",
    "Uploading a Cate-Blanchett-Stagecoach-2025 reference — analyze its rebooted-stagecoach desert-canyon and produce a 45-second new cinematic short.",
    "Here's a P.J.-Hogan Muriel's-Wedding reference — analyze its Porpoise-Spit-fantasy chapel and create a 1-minute new mini-drama.",
    "I'm sending you a Gavin-Hood Tsotsi reference — please analyze its Soweto-shantytown infant-encounter and produce a 30-second new cinematic short.",
    "Uploading a Neill-Blomkamp District-9 reference — analyze its Johannesburg-prawn-camp eviction and create a 45-second new mini-drama.",
    "Here's a John-Trengove The-Wound reference — analyze its Xhosa-initiation rural-mountain and produce a 1-minute new cinematic short.",
    "I have a Oliver-Hermanus Moffie reference — please analyze its 1980s-South-African-conscript barracks and create a 30-second new mini-drama.",
    "Uploading a Atom-Egoyan Sweet-Hereafter reference — analyze its BC-school-bus-tragedy aftermath and produce a 45-second new cinematic short.",
    "Here's a Sarah-Polley Away-from-Her reference — analyze its Ontario-nursing-home memory-loss and create a 1-minute new mini-drama.",
    "I'm sending you a Denis-Villeneuve Polytechnique reference — please analyze its Montreal-massacre quiet-hallway and produce a 30-second new cinematic short.",
    "Uploading a Denis-Villeneuve Incendies reference — analyze its Quebec-twins-Lebanon journey and create a 45-second new mini-drama.",
    "Here's a Xavier-Dolan Mommy reference — analyze its Quebec-Outaouais 1:1-aspect-ratio and produce a 1-minute new cinematic short.",
    "I have a Anne-Émond Nelly reference — please analyze its Montreal-Arcand multilayer-portrait and create a 30-second new mini-drama.",
    # ── more German New Cinema (Fassbinder/Herzog/Wenders/Schlöndorff) references (50) ──
    "Uploading a Rainer-Werner-Fassbinder Marriage-of-Maria-Braun reference — please analyze its post-war Berlin-rubble matrimony and produce a 1-minute new mini-drama.",
    "Here's a Rainer-Werner-Fassbinder Ali-Fear-Eats-the-Soul reference — analyze its Munich-bar Moroccan-immigrant tableau and create a 45-second new cinematic short.",
    "I'm sending you a Rainer-Werner-Fassbinder Bitter-Tears-of-Petra-von-Kant reference — please analyze its Bremen-apartment fashion-designer breakdown and produce a 30-second new mini-drama.",
    "Uploading a Rainer-Werner-Fassbinder Berlin-Alexanderplatz reference — analyze its Weimar-Franz-Biberkopf street-corner and create a 1-minute new cinematic short.",
    "Here's a Rainer-Werner-Fassbinder Lola reference — please analyze its 1950s-Coburg cabaret-singer-mayor and produce a 30-second new mini-drama.",
    "I have a Rainer-Werner-Fassbinder Veronika-Voss reference — please analyze its Munich-1955 morphine-faded-star and create a 45-second new cinematic short.",
    "Uploading a Werner-Herzog Aguirre-Wrath-of-God reference — analyze its Amazon-raft conquistador-decay and produce a 1-minute new mini-drama.",
    "Here's a Werner-Herzog Fitzcarraldo reference — please analyze its Andean-mountain ship-haul and create a 30-second new cinematic short.",
    "I'm sending you a Werner-Herzog Nosferatu-Phantom-of-the-Night reference — analyze its Wismar-Klaus-Kinski plague-arrival and produce a 45-second new mini-drama.",
    "Uploading a Werner-Herzog Stroszek reference — analyze its Wisconsin-trailer-park existential-collapse and create a 1-minute new cinematic short.",
    "Here's a Werner-Herzog Heart-of-Glass reference — please analyze its Bavarian-glassblower hypnotized-cast and produce a 30-second new mini-drama.",
    "I have a Werner-Herzog Enigma-of-Kaspar-Hauser reference — please analyze its Nuremberg-foundling square-encounter and create a 45-second new cinematic short.",
    "Uploading a Werner-Herzog Even-Dwarfs-Started-Small reference — analyze its Lanzarote-institution rebellion and produce a 1-minute new mini-drama.",
    "Here's a Werner-Herzog Land-of-Silence-and-Darkness reference — please analyze its deafblind-woman tactile-encounter and create a 30-second new cinematic short.",
    "I'm sending you a Werner-Herzog Lessons-of-Darkness reference — analyze its Kuwait-oil-fire post-Gulf-War landscape and produce a 45-second new mini-drama.",
    "Uploading a Wim-Wenders Paris-Texas reference — analyze its Texas-desert-roadside Travis-rebirth and create a 1-minute new cinematic short.",
    "Here's a Wim-Wenders Wings-of-Desire reference — please analyze its Berlin-angel-library tracking-shot and produce a 30-second new mini-drama.",
    "I have a Wim-Wenders Alice-in-the-Cities reference — please analyze its New-York-Wuppertal odyssey and create a 45-second new cinematic short.",
    "Uploading a Wim-Wenders Kings-of-the-Road reference — analyze its East-German-border-projector-truck and produce a 1-minute new mini-drama.",
    "Here's a Wim-Wenders American-Friend reference — please analyze its Hamburg-Ripley framing-craftsman and create a 30-second new cinematic short.",
    "I'm sending you a Wim-Wenders Lisbon-Story reference — analyze its Lisbon-sound-recordist trams and produce a 45-second new mini-drama.",
    "Uploading a Wim-Wenders Until-the-End-of-the-World reference — analyze its global-chase Outback-laboratory and create a 1-minute new cinematic short.",
    "Here's a Volker-Schlöndorff Tin-Drum reference — please analyze its Danzig-Oskar-Matzerath drum-scream and produce a 30-second new mini-drama.",
    "I have a Volker-Schlöndorff Young-Törless reference — please analyze its Austro-Hungarian boarding-school cruelty and create a 45-second new cinematic short.",
    "Uploading a Volker-Schlöndorff Lost-Honor-of-Katharina-Blum reference — analyze its tabloid-press doorstep-harassment and produce a 1-minute new mini-drama.",
    "Here's a Volker-Schlöndorff Coup-de-Grâce reference — please analyze its Latvian-Baltic-1919 manor-siege and create a 30-second new cinematic short.",
    "I'm sending you a Volker-Schlöndorff Death-of-a-Salesman-1985 reference — analyze its Brooklyn-Loman-kitchen and produce a 45-second new mini-drama.",
    "Uploading a Margarethe-von-Trotta Marianne-and-Juliane reference — analyze its sisters-RAF political-divide and create a 1-minute new cinematic short.",
    "Here's a Margarethe-von-Trotta Rosa-Luxemburg reference — please analyze its 1919-Berlin-canal political-execution and produce a 30-second new mini-drama.",
    "I have a Margarethe-von-Trotta Hannah-Arendt reference — please analyze its Eichmann-trial banality-of-evil and create a 45-second new cinematic short.",
    "Uploading a Werner-Schroeter Malina reference — analyze its Vienna-apartment Isabelle-Huppert split-self and produce a 1-minute new mini-drama.",
    "Here's an Alexander-Kluge Yesterday-Girl reference — please analyze its East-West-German girl-on-the-run and create a 30-second new cinematic short.",
    "I'm sending you an Alexander-Kluge Strongman-Ferdinand reference — analyze its industrial-security comedy and produce a 45-second new mini-drama.",
    "Uploading a Helma-Sanders-Brahms Germany-Pale-Mother reference — analyze its WW2 mother-daughter trek and create a 1-minute new cinematic short.",
    "Here's a Hans-Jürgen-Syberberg Hitler-A-Film-from-Germany reference — please analyze its puppet-theater Wagner-soundscape and produce a 30-second new mini-drama.",
    "I have an Edgar-Reitz Heimat reference — please analyze its Hunsrück-village 20th-century-saga and create a 45-second new cinematic short.",
    "Uploading a Doris-Dörrie Men reference — analyze its Munich-yuppie-best-friend-affair and produce a 1-minute new mini-drama.",
    "Here's a Tom-Tykwer Run-Lola-Run reference — please analyze its Berlin-three-runs phone-receiver and create a 30-second new cinematic short.",
    "I'm sending you a Tom-Tykwer Heaven reference — analyze its Turin-courtroom escape and produce a 45-second new mini-drama.",
    "Uploading a Wolfgang-Petersen Das-Boot reference — analyze its U-boat-claustrophobic depth-charge sequence and create a 1-minute new cinematic short.",
    "Here's an Oliver-Hirschbiegel Downfall reference — please analyze its Berlin-bunker April-1945 chancellery and produce a 30-second new mini-drama.",
    "I have a Florian-Henckel-von-Donnersmarck Lives-of-Others reference — please analyze its East-Berlin Stasi-attic surveillance and create a 45-second new cinematic short.",
    "Uploading a Christian-Petzold Phoenix reference — analyze its post-war-Berlin disfigured-survivor recognition and produce a 1-minute new mini-drama.",
    "Here's a Christian-Petzold Transit reference — please analyze its Marseille-stuck-refugee identity-swap and create a 30-second new cinematic short.",
    "I'm sending you a Christian-Petzold Barbara reference — analyze its 1980-East-German-coast doctor-defection and produce a 45-second new mini-drama.",
    "Uploading a Maren-Ade Toni-Erdmann reference — analyze its Bucharest-corporate-father prosthetic-teeth and create a 1-minute new cinematic short.",
    "Here's a Fatih-Akin Head-On reference — please analyze its Hamburg-Turkish-immigrant marriage-of-convenience and produce a 30-second new mini-drama.",
    "I have a Fatih-Akin Edge-of-Heaven reference — please analyze its Istanbul-Bremen mother-daughter-search and create a 45-second new cinematic short.",
    "Uploading a Caroline-Link Nowhere-in-Africa reference — analyze its Kenya-1938 Jewish-refugee farm and produce a 1-minute new mini-drama.",
    "Here's an Andreas-Dresen Cloud-9 reference — please analyze its East-Berlin elderly-affair and create a 30-second new cinematic short.",
    # ── more Spanish / Iberian cinema references (50) ──
    "Uploading a Pedro-Almodóvar Women-on-the-Verge-of-a-Nervous-Breakdown reference — please analyze its Madrid-penthouse gazpacho-suicide and produce a 1-minute new mini-drama.",
    "Here's a Pedro-Almodóvar Tie-Me-Up-Tie-Me-Down reference — analyze its Madrid-actress-apartment and create a 45-second new cinematic short.",
    "I'm sending you a Pedro-Almodóvar High-Heels reference — please analyze its Madrid-jail-mother-daughter-reunion and produce a 30-second new mini-drama.",
    "Uploading a Pedro-Almodóvar Live-Flesh reference — analyze its Madrid-Plaza-Mayor shooting and create a 45-second new cinematic short.",
    "Here's a Pedro-Almodóvar All-About-My-Mother reference — please analyze its Barcelona-Las-Ramblas mother-grief and produce a 1-minute new cinematic short.",
    "I have a Pedro-Almodóvar Talk-to-Her reference — please analyze its Madrid-coma-clinic dancer and produce a 30-second new mini-drama.",
    "Uploading a Pedro-Almodóvar Bad-Education reference — analyze its 1980s-Madrid-school-reunion and create a 45-second new cinematic short.",
    "Here's a Pedro-Almodóvar Volver reference — please analyze its La-Mancha-village-windmill mother and produce a 1-minute new cinematic short.",
    "I'm sending you a Pedro-Almodóvar Broken-Embraces reference — analyze its Lanzarote-cliff-accident and create a 30-second new mini-drama.",
    "Uploading a Pedro-Almodóvar Skin-I-Live-In reference — analyze its Toledo-mansion-laboratory and produce a 45-second new cinematic short.",
    "Here's a Pedro-Almodóvar Julieta reference — please analyze its Madrid-train-flashback and create a 1-minute new cinematic short.",
    "I have a Pedro-Almodóvar Pain-and-Glory reference — please analyze its Madrid-Salvador-Mallo-bedroom and produce a 30-second new mini-drama.",
    "Uploading a Pedro-Almodóvar Parallel-Mothers reference — analyze its Madrid-mass-grave-investigation and create a 45-second new cinematic short.",
    "Here's a Luis-Buñuel Discreet-Charm-of-the-Bourgeoisie reference — please analyze its Paris-dinner-party-cycle and produce a 1-minute new cinematic short.",
    "I'm sending you a Luis-Buñuel Belle-de-Jour reference — analyze its Paris-Séverine-brothel and create a 30-second new mini-drama.",
    "Uploading a Luis-Buñuel That-Obscure-Object-of-Desire reference — analyze its Seville-Mathieu-train and produce a 45-second new cinematic short.",
    "Here's a Luis-Buñuel Viridiana reference — please analyze its Don-Jaime-estate-Last-Supper and create a 1-minute new cinematic short.",
    "I have a Luis-Buñuel Tristana reference — please analyze its Toledo-orphan-uncle and produce a 30-second new mini-drama.",
    "Uploading a Luis-Buñuel Phantom-of-Liberty reference — analyze its Paris-bourgeois-vignette and create a 45-second new cinematic short.",
    "Here's a Luis-Buñuel Andalusian-Dog reference — please analyze its Surrealist-eyeball-cloud and produce a 1-minute new cinematic short.",
    "I'm sending you a Carlos-Saura Cría-Cuervos reference — analyze its Madrid-mansion-Ana-grief and create a 30-second new mini-drama.",
    "Uploading a Carlos-Saura Blood-Wedding reference — analyze its flamenco-rehearsal-studio and produce a 45-second new cinematic short.",
    "Here's a Carlos-Saura Carmen-1983 reference — please analyze its Seville-flamenco-rehearsal and create a 1-minute new cinematic short.",
    "I have a Carlos-Saura Tango reference — please analyze its Buenos-Aires-tango-stage and produce a 30-second new mini-drama.",
    "Uploading a Víctor-Erice Spirit-of-the-Beehive reference — analyze its Castilian-countryside-Ana-Frankenstein and create a 45-second new cinematic short.",
    "Here's a Víctor-Erice South reference — please analyze its Cantabrian-northern-Spain-mansion and produce a 1-minute new cinematic short.",
    "I'm sending you a Víctor-Erice Quince-Tree-Sun reference — analyze its Madrid-painter-quince-tree and create a 30-second new mini-drama.",
    "Uploading a Víctor-Erice Close-Your-Eyes reference — analyze its Madrid-aging-director and produce a 45-second new cinematic short.",
    "Here's a Juan-Antonio-Bayona Orphanage reference — please analyze its Asturian-coast-mansion-orphans and create a 1-minute new cinematic short.",
    "I have a Juan-Antonio-Bayona Impossible reference — please analyze its Khao-Lak-tsunami-2004 and produce a 30-second new mini-drama.",
    "Uploading a Juan-Antonio-Bayona Society-of-the-Snow reference — analyze its Andes-Uruguayan-rugby-crash and create a 45-second new cinematic short.",
    "Here's a Alejandro-Amenábar Tesis reference — please analyze its Madrid-film-school-snuff and produce a 1-minute new cinematic short.",
    "I'm sending you a Alejandro-Amenábar Open-Your-Eyes reference — analyze its Madrid-mask-mansion-cryogenic and create a 30-second new mini-drama.",
    "Uploading a Alejandro-Amenábar Others reference — analyze its Jersey-mansion-photo-sensitive and produce a 45-second new cinematic short.",
    "Here's a Alejandro-Amenábar Mar-Adentro reference — please analyze its Galician-bedridden-poet and create a 1-minute new cinematic short.",
    "I have a Isabel-Coixet My-Life-Without-Me reference — please analyze its Vancouver-trailer-mother-tape-list and produce a 30-second new mini-drama.",
    "Uploading a Isabel-Coixet Secret-Life-of-Words reference — analyze its North-Sea-oil-rig-nurse and create a 45-second new cinematic short.",
    "Here's a Iciar-Bollaín Take-My-Eyes reference — please analyze its Toledo-domestic-violence and produce a 1-minute new cinematic short.",
    "I'm sending you a Iciar-Bollaín Even-the-Rain reference — analyze its Cochabamba-water-war-film-shoot and create a 30-second new mini-drama.",
    "Uploading a Pablo-Berger Snow-White-Blancanieves reference — analyze its 1920s-Andalusian-bullring and produce a 45-second new cinematic short.",
    "Here's a Pablo-Berger Robot-Dreams reference — please analyze its 1980s-Manhattan-robot-friendship and create a 1-minute new cinematic short.",
    "I have a Manoel-de-Oliveira Voyage-to-the-Beginning reference — please analyze its Northern-Portugal-rural-roots and produce a 30-second new mini-drama.",
    "Uploading a Pedro-Costa Vitalina-Varela reference — analyze its Lisbon-Cova-da-Moura-Cape-Verdean and create a 45-second new cinematic short.",
    "Here's a Pedro-Costa Colossal-Youth reference — please analyze its Lisbon-Fontainhas-immigrant and produce a 1-minute new cinematic short.",
    "I'm sending you a Miguel-Gomes Tabu reference — analyze its Lisbon-Aurora-Mount-Tabu-flashback and create a 30-second new mini-drama.",
    "Uploading a Miguel-Gomes Arabian-Nights reference — analyze its Portuguese-austerity-storyteller and produce a 45-second new cinematic short.",
    "Here's a João-Pedro-Rodrigues To-Die-Like-a-Man reference — please analyze its Lisbon-fado-trans-singer and create a 1-minute new cinematic short.",
    "I have a Carlos-Vermut Magical-Girl reference — please analyze its Madrid-suburb-debt-spiral and produce a 30-second new mini-drama.",
    "Uploading a Albert-Serra Pacifiction reference — analyze its Tahiti-French-High-Commissioner and create a 45-second new cinematic short.",
    "Here's a Rodrigo-Sorogoyen As-Bestas reference — please analyze its Galician-village-French-couple-feud and produce a 1-minute new cinematic short.",
    # ── more Eastern European cinema (Polish / Czech / Hungarian / Romanian) (50) ──
    "Uploading a Andrzej-Wajda Ashes-and-Diamonds reference — please analyze its 1945-Polish-resistance-bar and produce a 1-minute new mini-drama.",
    "Here's a Andrzej-Wajda Kanal reference — analyze its Warsaw-Uprising-sewer-escape and create a 45-second new cinematic short.",
    "I have a Andrzej-Wajda Man-of-Marble reference — please analyze its Stalinist-bricklayer-flashback and produce a 30-second new mini-drama.",
    "Uploading a Andrzej-Wajda Man-of-Iron reference — analyze its Solidarity-Gdansk-shipyard and create a 45-second new short.",
    "Here's a Andrzej-Wajda Katyn reference — please analyze its 1940-Soviet-Polish-officer-massacre and produce a 1-minute new cinematic short.",
    "I'm sending you a Krzysztof-Kieslowski Dekalog reference — analyze its Warsaw-housing-bloc-Ten-Commandments and create a 30-second new mini-drama.",
    "Uploading a Krzysztof-Kieslowski Three-Colors-Blue reference — analyze its Paris-widow-piano and produce a 45-second new short.",
    "Here's a Krzysztof-Kieslowski Three-Colors-White reference — please analyze its Warsaw-Polish-divorce and create a 1-minute new cinematic short.",
    "I have a Krzysztof-Kieslowski Three-Colors-Red reference — please analyze its Geneva-judge-fashion-model and produce a 30-second new mini-drama.",
    "Uploading a Krzysztof-Kieslowski Double-Life-of-Veronique reference — analyze its Paris-Krakow-doppelgänger and create a 45-second new short.",
    "Here's a Roman-Polanski Knife-in-the-Water reference — please analyze its Mazury-lake-yacht-stranger and produce a 1-minute new cinematic short.",
    "I'm sending you a Pawel-Pawlikowski Ida reference — analyze its 1962-Polish-convent-Jewish-novice and create a 30-second new mini-drama.",
    "Uploading a Pawel-Pawlikowski Cold-War reference — analyze its 1949-Polish-folk-troupe-Paris-jazz and produce a 45-second new short.",
    "Here's a Jerzy-Skolimowski Deep-End reference — please analyze its London-bathhouse and create a 1-minute new cinematic short.",
    "I have a Jerzy-Skolimowski Essential-Killing reference — please analyze its Afghan-snowy-mountains-escape and produce a 30-second new mini-drama.",
    "Uploading a Jerzy-Skolimowski EO reference — analyze its Polish-circus-donkey-odyssey and create a 45-second new short.",
    "Here's a Agnieszka-Holland In-Darkness reference — please analyze its Lwów-sewer-Holocaust and produce a 1-minute new cinematic short.",
    "I'm sending you a Agnieszka-Holland Mr-Jones reference — analyze its 1933-Soviet-Ukraine-Holodomor-correspondent and create a 30-second new mini-drama.",
    "Uploading a Wojciech-Smarzowski Volhynia reference — analyze its 1943-Volhynia-Polish-Ukrainian-massacre and produce a 45-second new short.",
    "Here's a Milos-Forman Loves-of-a-Blonde reference — please analyze its Czech-textile-factory-girl and create a 1-minute new cinematic short.",
    "I have a Milos-Forman Firemen's-Ball reference — please analyze its Vrchlabí-fire-brigade-ball and produce a 30-second new mini-drama.",
    "Uploading a Jiri-Menzel Closely-Watched-Trains reference — analyze its WWII-Czech-station-trainee and create a 45-second new short.",
    "Here's a Jiri-Menzel I-Served-the-King-of-England reference — please analyze its Prague-hotel-waiter-Sudeten and produce a 1-minute new cinematic short.",
    "I'm sending you a Vera-Chytilova Daisies reference — analyze its absurdist-Marie-banquet and create a 30-second new mini-drama.",
    "Uploading a Jan-Nemec Diamonds-of-the-Night reference — analyze its WWII-Czech-train-escape-forest and produce a 45-second new short.",
    "Here's a Frantisek-Vlacil Marketa-Lazarova reference — please analyze its 13th-c-Bohemian-tribe and create a 1-minute new cinematic short.",
    "I have a Jan-Svankmajer Alice reference — please analyze its stop-motion-Carrollian-attic and produce a 30-second new mini-drama.",
    "Uploading a Jan-Svankmajer Faust reference — analyze its Prague-Faustian-puppet-theater and create a 45-second new short.",
    "Here's a Bela-Tarr Werckmeister-Harmonies reference — please analyze its Hungarian-village-whale-truck and produce a 1-minute new cinematic short.",
    "I'm sending you a Bela-Tarr Turin-Horse reference — analyze its Hungarian-windswept-cottage-decline and create a 30-second new mini-drama.",
    "Uploading a Bela-Tarr Sátántangó reference — analyze its Puszta-failing-collective and produce a 45-second new short.",
    "Here's a Miklos-Jancso Red-and-the-White reference — please analyze its Russian-Civil-War-Volga-massacre and create a 1-minute new cinematic short.",
    "I have a Istvan-Szabo Mephisto reference — please analyze its 1930s-Hamburg-Hendrik-Hofgen and produce a 30-second new mini-drama.",
    "Uploading a Istvan-Szabo Sunshine reference — analyze its three-generations-Hungarian-Jewish-family and create a 45-second new short.",
    "Here's a Laszlo-Nemes Son-of-Saul reference — please analyze its Auschwitz-Sonderkommando-Saul and produce a 1-minute new cinematic short.",
    "I'm sending you a Laszlo-Nemes Sunset reference — analyze its 1913-Budapest-millinery and create a 30-second new mini-drama.",
    "Uploading a Ildiko-Enyedi On-Body-and-Soul reference — analyze its Hungarian-slaughterhouse-shared-dream and produce a 45-second new short.",
    "Here's a Cristian-Mungiu 4-Months-3-Weeks-and-2-Days reference — please analyze its Romanian-Ceausescu-illegal-abortion and create a 1-minute new cinematic short.",
    "I have a Cristian-Mungiu Beyond-the-Hills reference — please analyze its Moldavian-Orthodox-monastery-exorcism and produce a 30-second new mini-drama.",
    "Uploading a Cristian-Mungiu Graduation reference — analyze its Cluj-doctor-daughter-exam-bribe and create a 45-second new short.",
    "Here's a Cristi-Puiu Death-of-Mr-Lazarescu reference — please analyze its Bucharest-night-ER-corridors and produce a 1-minute new cinematic short.",
    "I'm sending you a Corneliu-Porumboiu 12:08-East-of-Bucharest reference — analyze its post-Ceausescu-talk-show and create a 30-second new mini-drama.",
    "Uploading a Corneliu-Porumboiu Police-Adjective reference — analyze its Vaslui-undercover-detective and produce a 45-second new short.",
    "Here's a Radu-Jude Aferim reference — please analyze its 1830s-Wallachia-bounty-hunter and create a 1-minute new cinematic short.",
    "I have a Radu-Jude Bad-Luck-Banging reference — please analyze its Bucharest-pandemic-leaked-tape and produce a 30-second new mini-drama.",
    "Uploading a Theo-Angelopoulos Eternity-and-a-Day reference — analyze its Thessaloniki-poet-Albanian-boy and create a 45-second new short.",
    "Here's a Theo-Angelopoulos Ulysses-Gaze reference — please analyze its Balkans-film-archive-quest and produce a 1-minute new cinematic short.",
    "I'm sending you a Theo-Angelopoulos Landscape-in-the-Mist reference — analyze its Greek-children-train-search and create a 30-second new mini-drama.",
    "Uploading a Theo-Angelopoulos Beekeeper reference — analyze its Greek-itinerant-beekeeper and produce a 45-second new short.",
    "Here's a Yorgos-Lanthimos Dogtooth reference — please analyze its Athens-suburb-isolated-family and create a 1-minute new cinematic short.",
    # ── more New German Cinema (Fassbinder/Herzog/Wenders/Kluge/Schlöndorff) (50) ──
    "I have a Fassbinder-Marriage-of-Maria-Braun reference — please analyze its post-war-Bavaria-rising-businesswoman and produce a 30-second new mini-drama.",
    "Uploading a Fassbinder-Ali-Fear-Eats-the-Soul reference — analyze its Munich-elderly-cleaner-Moroccan-romance and create a 45-second new short.",
    "Here's a Fassbinder-Berlin-Alexanderplatz reference — please analyze its Weimar-Berlin-released-convict and produce a 1-minute new cinematic short.",
    "I'm sending you a Fassbinder-Lola reference — analyze its 1950s-Coburg-cabaret-Lola and create a 30-second new mini-drama.",
    "Uploading a Fassbinder-Veronika-Voss reference — analyze its post-war-Munich-faded-actress and produce a 45-second new short.",
    "Here's a Fassbinder-The-Bitter-Tears-of-Petra-von-Kant reference — please analyze its Bremen-fashion-designer-claustrophobia and create a 1-minute new cinematic short.",
    "I have a Fassbinder-Fox-and-His-Friends reference — please analyze its Munich-carnival-worker-bourgeois-affair and produce a 30-second new mini-drama.",
    "Uploading a Fassbinder-Effi-Briest reference — analyze its Bismarck-era-Pomeranian-baroness and create a 45-second new short.",
    "Here's a Fassbinder-The-Merchant-of-Four-Seasons reference — please analyze its Munich-fruit-vendor-marriage and produce a 1-minute new cinematic short.",
    "I'm sending you a Fassbinder-Querelle reference — analyze its Brest-port-sailor-and-mob and create a 30-second new mini-drama.",
    "Uploading a Herzog-Aguirre-Wrath-of-God reference — analyze its 1560-Amazon-conquistador-raft-descent and produce a 45-second new short.",
    "Here's a Herzog-Fitzcarraldo reference — please analyze its Iquitos-rubber-baron-ship-over-mountain and create a 1-minute new cinematic short.",
    "I have a Herzog-Nosferatu-the-Vampyre reference — please analyze its Wismar-vampire-plague-arrival and produce a 30-second new mini-drama.",
    "Uploading a Herzog-Stroszek reference — analyze its Berlin-busker-Wisconsin-emigration and create a 45-second new short.",
    "Here's a Herzog-The-Enigma-of-Kaspar-Hauser reference — please analyze its 1828-Nuremberg-feral-foundling and produce a 1-minute new cinematic short.",
    "I'm sending you a Herzog-Heart-of-Glass reference — analyze its Bavarian-glassblower-village-trance and create a 30-second new mini-drama.",
    "Uploading a Herzog-Even-Dwarves-Started-Small reference — analyze its Lanzarote-island-asylum-uprising and produce a 45-second new short.",
    "Here's a Herzog-Where-the-Green-Ants-Dream reference — please analyze its Coober-Pedy-Aboriginal-mining-suit and create a 1-minute new cinematic short.",
    "I have a Wenders-Paris-Texas reference — please analyze its Big-Bend-amnesiac-Travis-and-son and produce a 30-second new mini-drama.",
    "Uploading a Wenders-Wings-of-Desire reference — analyze its Berlin-Wall-angel-and-trapeze-artist and create a 45-second new short.",
    "Here's a Wenders-Kings-of-the-Road reference — please analyze its East-West-German-border-projector-mechanic and produce a 1-minute new cinematic short.",
    "I'm sending you a Wenders-Alice-in-the-Cities reference — analyze its NYC-Wuppertal-journalist-and-girl and create a 30-second new mini-drama.",
    "Uploading a Wenders-The-American-Friend reference — analyze its Hamburg-Tom-Ripley-Hamburg-frame-maker and produce a 45-second new short.",
    "Here's a Wenders-Until-the-End-of-the-World reference — please analyze its near-future-globe-trotting-image-recorder and create a 1-minute new cinematic short.",
    "I have a Wenders-Lisbon-Story reference — please analyze its Lisbon-sound-recordist-Madredeus and produce a 30-second new mini-drama.",
    "Uploading a Schlöndorff-The-Tin-Drum reference — analyze its Danzig-Oskar-refusing-to-grow and create a 45-second new short.",
    "Here's a Schlöndorff-Young-Törless reference — please analyze its 1900s-Austrian-military-academy-cruelty and produce a 1-minute new cinematic short.",
    "I'm sending you a Schlöndorff-The-Lost-Honor-of-Katharina-Blum reference — analyze its Cologne-tabloid-targeted-housekeeper and create a 30-second new mini-drama.",
    "Uploading a Schlöndorff-Coup-de-Grâce reference — analyze its 1919-Baltic-civil-war-fortress and produce a 45-second new short.",
    "Here's a Kluge-Yesterday-Girl reference — please analyze its East-German-defector-Frankfurt-girl and create a 1-minute new cinematic short.",
    "I have a Kluge-Strongman-Ferdinand reference — please analyze its West-German-paranoid-security-chief and produce a 30-second new mini-drama.",
    "Uploading a Kluge-The-Patriot reference — analyze its history-teacher-archaeology-of-Germany and create a 45-second new short.",
    "Here's a Wim-Wenders-Buena-Vista-Social-Club reference — please analyze its Havana-Compay-Segundo-rediscovery and produce a 1-minute new cinematic short.",
    "I'm sending you a Achternbusch-Das-letzte-Loch reference — analyze its Bavarian-grotesque-Holocaust-comedy and create a 30-second new mini-drama.",
    "Uploading a Hark-Bohm-Nordsee-ist-Mordsee reference — analyze its Hamburg-Wilhelmsburg-immigrant-Turkish-boy and produce a 45-second new short.",
    "Here's a Doris-Dörrie-Men reference — please analyze its Munich-yuppie-husband-undercover-affair and create a 1-minute new cinematic short.",
    "I have a Doris-Dörrie-Cherry-Blossoms reference — please analyze its Bavaria-widower-Tokyo-pilgrimage and produce a 30-second new mini-drama.",
    "Uploading a Margarethe-von-Trotta-Marianne-and-Juliane reference — analyze its 1970s-RAF-prison-sister-visits and create a 45-second new short.",
    "Here's a Margarethe-von-Trotta-The-Second-Awakening-of-Christa-Klages reference — please analyze its Munich-bank-heist-kindergarten-fundraiser and produce a 1-minute new cinematic short.",
    "I'm sending you a Margarethe-von-Trotta-Hannah-Arendt reference — analyze its New-York-Eichmann-trial-banality-of-evil and create a 30-second new mini-drama.",
    "Uploading a Edgar-Reitz-Heimat reference — analyze its Hunsrück-village-1919-2000-saga and produce a 45-second new short.",
    "Here's a Helma-Sanders-Brahms-Germany-Pale-Mother reference — please analyze its WWII-housewife-mother-daughter and create a 1-minute new cinematic short.",
    "I have a Christian-Petzold-Barbara reference — please analyze its 1980s-East-Germany-rural-doctor-defection-plan and produce a 30-second new mini-drama.",
    "Uploading a Christian-Petzold-Phoenix reference — analyze its post-war-Berlin-Auschwitz-survivor-husband and create a 45-second new short.",
    "Here's a Christian-Petzold-Transit reference — please analyze its Marseille-refugee-1940-2018-time-collapse and produce a 1-minute new cinematic short.",
    "I'm sending you a Maren-Ade-Toni-Erdmann reference — analyze its Bucharest-corporate-consultant-prankster-father and create a 30-second new mini-drama.",
    "Uploading a Tom-Tykwer-Run-Lola-Run reference — analyze its Berlin-Lola-three-takes-DM-100k and produce a 45-second new short.",
    "Here's a Tom-Tykwer-The-Princess-and-the-Warrior reference — please analyze its Wuppertal-psychiatric-nurse-soldier and create a 1-minute new cinematic short.",
    "I have a Werner-Herzog-The-Mystery-of-Kaspar-Hauser reference — please analyze its 1828-Nuremberg-foundling-civilization-experiment and produce a 30-second new mini-drama.",
    "Uploading a Volker-Schlöndorff-Homo-Faber reference — analyze its 1957-trans-Atlantic-engineer-and-girl and create a 45-second new short.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
