"""x15 story_pure — 14x GRPO user_goal expansion (short briefs only).

Schema: USER_GOALS: list[str].

Chain: NarrationAgent → IllustrationAgent → NarratorAgent → CompositorAgent.

Style: illustrated audiobook / picture-book / narrated children's stories,
disjoint topic pool from SFT side. GRPO branch leans into:
  - historical biographical kid-stories
  - cross-cultural myths retold
  - STEM-themed children's tales (inventors, scientists, naturalists)
  - classic literature retellings (kid-friendly)
  - environmental / conservation tales
  - sports / craft hero kids stories
  - quiet inner-voice meditative stories
  - child-pet bonds
  - intergenerational family stories
  - made-up fables w/ moral focus
"""
from __future__ import annotations

USER_GOALS: list[str] = [
    # ── historical biographical kid-stories (30) ──────────────────────────
    "Tell me a children's audiobook about young Mary Anning hunting for fossils on the Lyme Regis cliffs as a girl.",
    "I want an illustrated picture-book story about young Marie Curie helping her father in his Warsaw classroom.",
    "Make me a kids' storybook about young Ada Lovelace tracing her first set of analytical-engine notes by candlelight.",
    "Create a narrated children's tale about a young Frederick Douglass teaching himself to read in secret.",
    "Produce an illustrated audiobook for kids about young Helen Keller learning the word 'water' by the pump.",
    "Build a children's storybook about a young Wangari Maathai planting her first seedling on a Kenyan hillside.",
    "Generate an illustrated kids' audiobook about young Sequoyah inventing the Cherokee syllabary in his cabin.",
    "Render a picture-book children's tale about young Ruth Bader Ginsburg reading on the steps of her Brooklyn library.",
    "I'd like a kids' audiobook about young Katherine Johnson solving math problems by lamplight.",
    "Tell me a children's storybook about young Florence Nightingale tending a wounded sparrow in her garden.",
    "Make a narrated picture-book about young Jane Goodall watching backyard squirrels with a tiny notebook.",
    "Cook up a children's audiobook about young George Washington Carver pressing leaves into his first journal.",
    "Build an illustrated kids' story about young Harriet Tubman learning songs that secretly carried directions.",
    "Create a children's audiobook about young Sojourner Truth listening to her mother's lullabies under the stars.",
    "Produce a picture-book children's tale about a young Toni Morrison writing her first short story at the kitchen table.",
    "Generate a kids' storybook about young Sally Ride looking up at the night sky from her California rooftop.",
    "I want a children's audiobook about young Roald Amundsen sketching maps of his fjord by oil lamp.",
    "Tell me an illustrated picture-book for kids about young Sun Yat-sen reading Latin grammar by his uncle's lantern.",
    "Render a children's audiobook about young Anna Pavlova practicing arabesques in her grandmother's parlor.",
    "Make me a kids' picture-book about young Shirley Chisholm reading her father's news clippings at breakfast.",
    "Cook up a children's audiobook about young Charles Drew running a backyard scientific experiment with his sister.",
    "Build an illustrated kids' tale about young Bessie Coleman teaching herself French to attend flight school.",
    "Create a narrated picture-book children's story about young Mary McLeod Bethune reading aloud to her younger siblings.",
    "Produce a kids' audiobook about young Octavia Butler typing on a thrift-shop typewriter at dawn.",
    "Generate a children's picture-book about young Hedy Lamarr taking apart a radio at her father's workshop.",
    "I'd like a children's audiobook about young Vera Rubin watching her bedroom-window stars on a winter night.",
    "Tell me an illustrated children's story about young Gabriel García Márquez listening to his grandmother's stories on a porch in Aracataca.",
    "Render a picture-book children's tale about young Frida Kahlo painting her first self-portrait propped up in bed.",
    "Make a kids' audiobook about young Ruth Asawa weaving wire baskets in her California internment classroom.",
    "Cook up a narrated children's storybook about young Diana Nyad swimming her first long lap in a Florida quarry.",
    # ── cross-cultural myth retellings for kids (25) ──────────────────────
    "Tell me an illustrated children's audiobook retelling the Maori story of how the kiwi gave up its wings.",
    "I want a kids' picture-book retelling of an Inuit story about Sedna and the creatures of the deep.",
    "Make me a children's audiobook based on a Polynesian myth about Pele lighting the first volcano.",
    "Create an illustrated children's tale based on a Mongolian story of how the moon got its rabbit.",
    "Produce a kids' picture-book audiobook based on an Egyptian tale of Bastet protecting a single granary.",
    "Build a children's audiobook retelling a Lakota story of the buffalo woman teaching the people to be kind.",
    "Generate an illustrated kids' tale based on a Yoruba story about Oshun bringing sweetness to the river.",
    "Render a children's picture-book retelling of a Norse myth about Idunn's golden apples — kid-friendly.",
    "I'd like a children's audiobook based on a Chinese myth about the Cowherd and the Weaver across the Milky Way.",
    "Tell me an illustrated kids' tale based on a Hindu story of young Krishna stealing butter from his mother's pot.",
    "Make me a children's audiobook based on an Anishinaabe story of how the loon got its necklace of stars.",
    "Cook up a kids' picture-book retelling of a Korean myth about the moon rabbit pounding rice cakes.",
    "Build a children's audiobook based on a Maasai tale of how the giraffe got its long neck.",
    "Create an illustrated children's storybook based on a Slovak folk story about Janosik and the snow.",
    "Produce a kids' picture-book children's tale based on a Dineh story of Coyote and First Woman.",
    "Generate a children's audiobook based on a Greek tale of how Athena planted the first olive tree.",
    "I want an illustrated kids' picture-book based on an Aztec myth about Quetzalcoatl bringing maize.",
    "Tell me a children's audiobook retelling a Yupik tale of the raven who brought daylight.",
    "Render an illustrated kids' tale based on a Vietnamese story of how the watermelon came to be.",
    "Make me a children's storybook based on a Bedouin folktale about a girl who found a star fallen in the dunes.",
    "Cook up a kids' picture-book based on a Hawaiian myth of Pele teaching her sister Hi'iaka to dance hula.",
    "Build a children's audiobook based on a Sami tale of the Northern Lights as ancestors playing a game.",
    "Create an illustrated children's storybook based on a Fijian myth about a sea turtle and the first navigator.",
    "Produce a kids' picture-book retelling a Cherokee story about how the strawberry came to be.",
    "Generate a children's audiobook based on a Zulu myth of the wise hare who chose his own moon.",
    # ── STEM-themed kids tales (25) ───────────────────────────────────────
    "Tell me a children's audiobook about a young girl building her first paper-airplane runway in her backyard.",
    "I want an illustrated picture-book about a child meeting a friendly cloud who explains how thunder forms.",
    "Make me a kids' storybook about a small boy talking to his vegetable garden about photosynthesis.",
    "Create a children's audiobook about a young girl following an ant home and learning about colonies.",
    "Produce an illustrated children's tale about a small child watching a tadpole turn into a frog over a season.",
    "Build a kids' picture-book about a young girl using a magnifying glass to study spider webs in her grandmother's garden.",
    "Generate a children's audiobook about a small boy building his first wind-chime and learning about pitch.",
    "Render an illustrated children's storybook about a child counting stars in the Milky Way.",
    "I'd like a kids' picture-book audiobook about a young girl helping her mother bake bread and watching yeast at work.",
    "Tell me a children's audiobook about a child mapping every shadow in her courtyard from dawn to dusk.",
    "Make me an illustrated kids' tale about a small boy sending a paper boat down a stream and counting eddies.",
    "Cook up a children's storybook about a young girl noting every kind of leaf in the autumn park.",
    "Build a picture-book audiobook for kids about a small boy learning how a kite stays up in the air.",
    "Create an illustrated children's tale about a young girl talking to her grandmother about why the moon changes shape.",
    "Produce a children's audiobook about a small girl observing tide pools and naming every creature.",
    "Generate an illustrated kids' storybook about a child measuring rainfall with a glass jar over a week.",
    "I want a kids' picture-book about a young boy listening to crickets and wondering how they sing.",
    "Tell me a narrated children's audiobook about a small girl watching frost climb up her window in slow motion.",
    "Render an illustrated children's tale about a curious child following a single bee through her grandmother's garden.",
    "Make me a children's storybook about a child watching an apple fall and asking her father about gravity.",
    "Cook up a kids' picture-book audiobook about a small girl assembling a homemade compass.",
    "Build a children's audiobook about a young child counting growth rings on a fallen log.",
    "Create an illustrated children's tale about a kid building a backyard birdhouse and recording every bird that visits.",
    "Produce a kids' picture-book story about a child using a flashlight to study moths under a bedsheet.",
    "Generate a children's audiobook about a young girl discovering the fizz of a vinegar-and-baking-soda volcano.",
    # ── classic-lit retellings for kids (25) ──────────────────────────────
    "Tell me a children's picture-book audiobook retelling Treasure Island, kid-friendly, told from young Jim Hawkins' first day.",
    "I want a narrated children's audiobook based on Black Beauty, gentle, told from a young carriage-horse's foal years.",
    "Make me an illustrated kids' picture-book retelling The Wind in the Willows, focused on Mole's first picnic.",
    "Create a children's audiobook retelling A Little Princess, gentle, told from a young Sara's first day at boarding school.",
    "Produce an illustrated children's tale retelling Heidi, focused on her arrival at her grandfather's mountain cottage.",
    "Build a kids' audiobook retelling Anne of Green Gables, gentle, told from her arrival at the train station.",
    "Generate an illustrated picture-book retelling The Secret Garden, focused on Mary unlocking the door.",
    "Render a children's audiobook retelling Peter Pan, kid-friendly, told from Wendy's first night-time visit to the nursery.",
    "I'd like a kids' picture-book retelling The Jungle Book, focused on Mowgli's first lesson with Baloo.",
    "Tell me a narrated children's audiobook retelling Pollyanna, gentle, focused on her first 'glad game' on the train.",
    "Make me a kids' picture-book retelling Charlotte's Web, focused on the morning Wilbur finds his first message in the web.",
    "Cook up an illustrated children's tale retelling The Velveteen Rabbit, gentle, the day the rabbit first becomes loved.",
    "Build a children's audiobook retelling The Tale of Peter Rabbit, gentle, told from Mrs. Rabbit's worried morning.",
    "Create a kids' picture-book retelling Little Women, focused on the March sisters' first Christmas morning.",
    "Produce an illustrated children's storybook retelling Pippi Longstocking, focused on her first day at the new house.",
    "Generate a children's audiobook retelling Mary Poppins, gentle, focused on the umbrella arrival at the front door.",
    "I want a kids' picture-book retelling Stuart Little, focused on Stuart's first morning sitting at the breakfast table.",
    "Tell me a children's audiobook retelling Charlie and the Chocolate Factory, kid-friendly, focused on the day Charlie finds the ticket.",
    "Render an illustrated kids' tale retelling The Hobbit, gentle, focused on Bilbo's first knock-at-the-door morning.",
    "Make me a children's audiobook retelling The Princess and the Goblin, focused on Irene's first walk through the upstairs corridor.",
    "Cook up a kids' picture-book retelling Five Children and It, focused on the first beach day with the Psammead.",
    "Build a children's audiobook retelling Tom Sawyer, gentle, focused on the morning of the famous fence-painting.",
    "Create an illustrated kids' tale retelling Alice in Wonderland, focused on her first quiet conversation with the Cheshire Cat.",
    "Produce a children's audiobook retelling Just So Stories, gentle, focused on how the elephant got his trunk.",
    "Generate an illustrated kids' picture-book retelling The Wonderful Wizard of Oz, focused on Dorothy's first morning in Munchkin Country.",
    # ── environmental / conservation kids tales (25) ──────────────────────
    "Tell me a children's audiobook about a young girl planting a single tree on a bare hillside in her village.",
    "I want an illustrated kids' picture-book about a small boy collecting plastic from a beach with his grandmother.",
    "Make me a children's storybook about a class of school children adopting a stretch of riverbank for a year.",
    "Create a kids' audiobook about a young girl helping a frog return to a restored pond on her family farm.",
    "Produce an illustrated children's tale about a small boy leading a town to install a single bee garden.",
    "Build a kids' picture-book about a young girl tracking a single migrating monarch butterfly across her garden.",
    "Generate a children's audiobook about a small boy and his sister rebuilding their grandmother's wildflower meadow.",
    "Render an illustrated kids' tale about a young girl sewing reusable bags for her village's market stalls.",
    "I'd like a children's audiobook about a small boy installing a rain-barrel under the eaves of his grandmother's house.",
    "Tell me a kids' picture-book about a young girl building a backyard compost bin with her father.",
    "Make me an illustrated children's tale about a small boy adopting a single fledgling owl rescued from a barn.",
    "Cook up a kids' audiobook about a young girl noting every species of bird at her grandparents' feeder.",
    "Build a children's picture-book story about a small boy raising tadpoles in jars to release into a wetland.",
    "Create a children's audiobook about a young girl convincing her family to switch their porch light to a warm-tone bulb to help moths.",
    "Produce an illustrated kids' picture-book about a small boy building a hedgehog hibernation house in his garden.",
    "Generate a kids' audiobook about a young girl helping at a sea-turtle hatchling release on a beach.",
    "I want an illustrated children's tale about a small boy filling out his first wildlife survey along a hedgerow.",
    "Tell me a children's audiobook about a young girl trading with her village to plant a community orchard.",
    "Render an illustrated kids' picture-book about a small boy helping his uncle clean salmon migration ladders.",
    "Make me a children's audiobook about a young girl spotting her first ribbon snake along a creek bank.",
    "Cook up a kids' picture-book story about a small boy raising a single firefly in a screened jar to learn its blink pattern.",
    "Build a children's audiobook about a young girl mapping every native pollinator plant in her town park.",
    "Create an illustrated children's tale about a small boy joining a beach-cleanup crew during turtle-nesting season.",
    "Produce a kids' picture-book audiobook about a young girl rescuing a single hummingbird trapped in a porch light fixture.",
    "Generate a children's audiobook about a small boy and his cousin building bird-houses for their school garden.",
    # ── child-pet bond kids stories (25) ──────────────────────────────────
    "Tell me a children's audiobook about a young girl bringing home a shelter dog and naming her on the bus ride home.",
    "I want an illustrated kids' picture-book about a small boy whose first goldfish teaches him about patience.",
    "Make me a children's storybook about a young girl whose family rabbit follows her around the apartment.",
    "Create a kids' audiobook about a small boy whose pet snail teaches him to slow down on busy mornings.",
    "Produce an illustrated children's tale about a young girl whose puppy adopts her grandmother's old slippers.",
    "Build a kids' picture-book about a small boy teaching his hermit crab to recognize his footsteps.",
    "Generate a children's audiobook about a young girl whose parakeet whistles back her favorite lullaby.",
    "Render an illustrated kids' tale about a small boy whose pet hedgehog hides his missing socks.",
    "I'd like a children's audiobook about a young girl whose family kitten learns to nap in her open backpack.",
    "Tell me an illustrated children's storybook about a small boy whose pet tortoise grows alongside him over years.",
    "Make me a kids' picture-book audiobook about a young girl whose cockatiel waits at the window for her school bus.",
    "Cook up a children's audiobook about a small boy whose pet fish responds to his bedtime stories with bubbles.",
    "Build a kids' picture-book about a young girl whose corgi adopts her younger brother as a charge.",
    "Create an illustrated children's audiobook about a small boy whose pet ferret keeps stealing the same single sock.",
    "Produce a children's storybook about a young girl whose chicken hen lays an egg precisely as she gets home from school.",
    "Generate an illustrated kids' picture-book about a small boy whose pet beetle becomes the class show-and-tell hero.",
    "I want a children's audiobook about a young girl whose adopted pony is afraid of puddles for an entire winter.",
    "Tell me a kids' picture-book about a small boy whose pet rabbit taps a warning when the kettle is boiling.",
    "Render an illustrated children's tale about a young girl whose dog brings home a single feather every morning.",
    "Make me a kids' audiobook about a small boy whose cat insists on sleeping on top of his homework.",
    "Cook up a children's picture-book about a young girl whose pet parrot learns to call out her grandmother's nickname.",
    "Build a kids' audiobook story about a small boy whose adopted greyhound finally learns to relax on a couch.",
    "Create an illustrated children's tale about a young girl whose pet duck waddles after her on every walk.",
    "Produce a kids' picture-book audiobook about a small boy whose pet lamb becomes the village's morning alarm.",
    "Generate a children's audiobook about a young girl whose fish pond koi recognize each family member by tap pattern.",
    # ── intergenerational family kids stories (25) ────────────────────────
    "Tell me a children's audiobook about a young girl learning to knit alongside her grandmother on a porch swing.",
    "I want an illustrated kids' picture-book about a small boy baking with his great-grandfather for the first time.",
    "Make me a children's storybook about a young girl visiting her grandmother in a small Italian village every summer.",
    "Create a kids' audiobook about a small boy learning to sew a button onto his own coat with his grandmother.",
    "Produce an illustrated children's tale about a young girl listening to her grandfather play the harmonica on a porch.",
    "Build a kids' picture-book about a small boy receiving his grandfather's old camera and learning to use it.",
    "Generate a children's audiobook about a young girl helping her grandmother make pierogies in a Polish kitchen.",
    "Render an illustrated kids' tale about a small boy learning to whittle from his uncle on a fishing trip.",
    "I'd like a children's audiobook about a young girl discovering her grandmother's old photo album in a quiet attic.",
    "Tell me an illustrated children's storybook about a small boy carrying his great-grandfather's medal during a parade.",
    "Make me a kids' picture-book about a young girl reading her grandmother's letters from when she was a teenager.",
    "Cook up a children's audiobook about a small boy planting tulips with his grandfather every spring.",
    "Build a kids' picture-book audiobook about a young girl helping her aunt make tamales for the holidays.",
    "Create an illustrated children's tale about a small boy learning origami from his great-aunt at her bedside.",
    "Produce a children's audiobook about a young girl playing chess with her grandfather every Sunday afternoon.",
    "Generate an illustrated kids' picture-book about a small boy learning to cast a fly rod from his uncle.",
    "I want a children's audiobook about a young girl helping her grandmother feed the strays in her courtyard.",
    "Tell me a kids' picture-book about a small boy learning to oil his grandfather's old leather work-boots.",
    "Render an illustrated children's tale about a young girl visiting her great-grandmother in an assisted-living home each week.",
    "Make me a kids' audiobook about a small boy teaching his grandfather how to use a smartphone.",
    "Cook up a children's picture-book audiobook about a young girl carrying her grandmother's recipe box across town.",
    "Build a kids' audiobook story about a small boy and his grandmother walking the same forest trail every Saturday morning.",
    "Create an illustrated children's tale about a young girl helping her uncle build a small wooden boat in his shed.",
    "Produce a kids' picture-book audiobook about a small boy learning to braid bread with his grandmother.",
    "Generate a children's audiobook about a young girl helping her great-grandfather record his stories onto a tape recorder.",
    # ── moral fables (25) ─────────────────────────────────────────────────
    "Tell me a children's audiobook fable about two squirrels who learn the value of saving for winter.",
    "I want an illustrated kids' picture-book fable about a young owl learning that being clever is not the same as being kind.",
    "Make me a children's storybook fable about a small mouse teaching a quick-tempered cat the value of patience.",
    "Create a kids' audiobook fable about a young deer who learns that boasting can scare away even the friendliest birds.",
    "Produce an illustrated children's tale fable about a young river-stone learning that being smooth takes time.",
    "Build a kids' picture-book fable about two crows learning the value of sharing a single worm.",
    "Generate a children's audiobook fable about a young goat learning that gratitude buys more friends than gold.",
    "Render an illustrated kids' tale fable about a young sparrow learning to forgive a careless wind.",
    "I'd like a children's audiobook fable about a young rabbit learning that 'too much hurry' loses more carrots than too little.",
    "Tell me an illustrated children's storybook fable about a young snail and a hare meeting the same finish line.",
    "Make me a kids' picture-book fable about two beetles learning that no work is too small to be praised.",
    "Cook up a children's audiobook fable about a young lion who learns that roaring scares away the best company.",
    "Build a kids' picture-book audiobook fable about a young swan learning to look for kindness, not for praise.",
    "Create an illustrated children's tale fable about a young horse learning that a heavy load is lighter when shared.",
    "Produce a children's audiobook fable about a young hen who learns the value of her smaller eggs.",
    "Generate an illustrated kids' picture-book fable about a young wolf learning to listen before he howls.",
    "I want a children's audiobook fable about a young oak who learns that bending in the wind is wiser than breaking.",
    "Tell me a kids' picture-book fable about a young fish who learns there are deeper currents than the ones nearest the surface.",
    "Render an illustrated children's tale fable about a young bee who learns that one daisy at a time fills the hive.",
    "Make me a kids' audiobook fable about a young bear learning that not every honey-tree is meant to be climbed.",
    "Cook up a children's picture-book fable about a young pigeon learning to choose her landing carefully.",
    "Build a kids' audiobook fable about a young magpie learning that a shiny object is not always a treasure.",
    "Create an illustrated children's tale fable about a young goose learning that flying together carries everyone farther.",
    "Produce a kids' picture-book audiobook fable about a young lamb learning that a soft answer can turn away even a wolf.",
    "Generate a children's audiobook fable about a young lark who learns that the best song is the one sung at dawn.",
    # ── world-folktale retelling for kids (30) ────────────────────────────
    "Tell me a children's audiobook retelling the Czech tale of Krakonoš, the mountain spirit who tests travelers' kindness.",
    "I want an illustrated picture-book retelling the Hungarian tale of Toldi the strong farm-boy.",
    "Make me a kids' storybook retelling the Romanian story of Făt-Frumos rescuing a cursed maiden.",
    "Create a narrated children's tale retelling the Bulgarian story of Hitar Petar outsmarting a greedy nobleman.",
    "Produce an illustrated audiobook retelling the Slovenian myth of Zlatorog, the white chamois with golden horns.",
    "Build a children's storybook retelling the Croatian tale of the Kosjenić brothers and their giant well.",
    "Generate a kids' audiobook retelling the Serbian story of Marko Kraljević and his magic horse Šarac.",
    "Render an illustrated children's tale retelling the Macedonian story of Itar Pejo's clever bargain.",
    "I'd like a kids' picture-book retelling the Albanian tale of Kostandini and Doruntina.",
    "Tell me a children's audiobook retelling the Kosovan story of the wise old woman of the mountain.",
    "Make a narrated picture-book retelling the Lithuanian tale of Eglė, the queen of the grass snakes.",
    "Cook up a children's audiobook retelling the Latvian story of the daughter of the moon.",
    "Build an illustrated kids' tale retelling the Estonian myth of Kalevipoeg the giant hero.",
    "Create a children's audiobook retelling the Belarusian story of the wise stork who guards a village.",
    "Produce a picture-book children's tale retelling the Ukrainian story of Kotyhoroshko the rolling-pea hero.",
    "Generate an illustrated kids' picture-book retelling the Moldovan tale of the white wolf of the forest.",
    "I want a children's audiobook retelling the Georgian story of Etseri, the boy who tamed the eagles.",
    "Tell me an illustrated children's tale retelling the Armenian story of David of Sasun's sword of light.",
    "Render a kids' audiobook retelling the Azerbaijani tale of Köroğlu, the singer-rebel.",
    "Make me a picture-book retelling the Turkmen story of the falcon and the desert prince.",
    "Cook up a narrated children's audiobook retelling the Uzbek tale of Nasreddin Hodja and the donkey.",
    "Build a kids' picture-book audiobook retelling the Tajik story of Rustam and the white div.",
    "Create a children's bedtime audiobook retelling the Kazakh tale of Aldar Kose, the trickster of the steppe.",
    "Produce an illustrated picture-book retelling the Kyrgyz story of Manas and his forty companions.",
    "I'd like a children's audiobook retelling the Pashtun story of Adam Khan and Durkhanai.",
    "Tell me a kids' picture-book retelling the Sindhi tale of Sohni and Mahiwal.",
    "Render an illustrated children's tale retelling the Punjabi story of Heer Ranjha.",
    "Make me a kids' audiobook retelling the Bengali story of Thakurmar Jhuli's sleeping princess.",
    "Cook up a children's picture-book retelling the Odia tale of the seven sisters of Konark.",
    "Generate a kids' audiobook retelling the Malayalam story of the magical Onam pookalam.",
    # ── seasonal & inclusive kids stories (continued) (30) ────────────────
    "Tell me a children's audiobook about a young girl helping her grandfather rake autumn leaves into a giant pile to jump in.",
    "I want an illustrated picture-book about a small boy decorating his first jack-o-lantern with his older sister.",
    "Make me a kids' storybook about a young girl carrying water across a field for the family Diwali diyas.",
    "Create a narrated children's tale about a small boy threading his first popcorn-and-cranberry garland.",
    "Produce an illustrated audiobook about a young girl writing her first thank-you card after a snow-day.",
    "Build a children's storybook about a small boy walking his very first lantern in a Mid-Autumn parade.",
    "Generate a kids' bedtime audiobook about a young girl trimming her first sukkah with her grandfather.",
    "Render an illustrated children's tale about a small boy lighting the first match of Hanukkah at his grandmother's table.",
    "I'd like a kids' picture-book about a young girl decorating her first Día de los Muertos altar with marigolds.",
    "Tell me a children's audiobook about a small boy stringing his first set of paper cranes for a Tanabata festival.",
    "Make a narrated picture-book about a young girl walking the first night of Las Posadas in her grandmother's village.",
    "Cook up a children's audiobook about a small boy setting out cookies for Father Christmas with his older brother.",
    "Build an illustrated kids' tale about a young girl filling her grandmother's tray of tsampa for Losar.",
    "Create a children's audiobook about a small boy floating his first paper boat for Loy Krathong.",
    "Produce a picture-book children's tale about a young girl placing her first egg in a Nowruz haft-sin.",
    "Generate an illustrated kids' picture-book about a small boy pasting his first paper cuts on the lunar-new-year window.",
    "I want a children's audiobook about a young girl helping her grandmother trim her first ofrenda altar.",
    "Tell me an illustrated children's tale about a small boy lighting his first Lohri bonfire with his uncle.",
    "Render a kids' audiobook about a young girl baking her first batch of Chinese-New-Year tang yuan.",
    "Make me a picture-book about a small boy delivering his first loaf of challah for Shabbat.",
    "Cook up a narrated children's audiobook about a young girl placing her first daffodil for Mothering Sunday.",
    "Build a kids' picture-book audiobook about a small boy folding his first origami crane for hospital visitors.",
    "Create a children's bedtime audiobook about a young girl carrying her grandmother's tray of tea-cakes for a Mother's Day picnic.",
    "Produce an illustrated picture-book about a small boy delivering his first hand-made valentine to his teacher.",
    "I'd like a children's audiobook about a young girl who uses a wheelchair leading the parade in a small hometown.",
    "Tell me an illustrated children's tale about a small boy who is non-verbal communicating love through a painting.",
    "Render a kids' audiobook about a young girl with diabetes baking a special-recipe birthday cake.",
    "Make a children's picture-book about a small boy with a hearing aid singing a solo at his school's spring concert.",
    "Cook up a children's audiobook about a young girl with celiac disease teaching her friends about gluten-free cookies.",
    "Generate an illustrated children's tale about a small boy with autism arranging his marble collection by color and shine.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
