"""x15 intake_img_cr_bilingual GRPO short briefs. Disjoint from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a portrait of a young 1880s Wild West sheriff — make a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a sketch of a young 1920s Russian ballerina — build a 45-second cinematic short with Russian and English subtitles.",
    "I'm sending you a watercolor of a young Chinese opera star — produce a 30-second piece with Mandarin and English subtitles.",
    "Uploading a digital painting of a young 1960s Mexican-American journalist — make a 1-minute mini-drama with Spanish and English subtitles.",
    "Here's a portrait of a young 1900s Norwegian whaler — render a 45-second cinematic short with Norwegian and English subtitles.",
    "I'm attaching a sketch of a young 1880s Texas trail boss — build a 30-second piece with English and Spanish subtitles.",
    "Uploading this concept art of a young 1900s Russian Jewish tailor — produce a 1-minute mini-drama with Yiddish and English subtitles.",
    "Here's a watercolor of a young 1850s Underground-Railroad conductor — render a 45-second short with English and French subtitles.",
    "I have a portrait of a young 1930s Polish émigré pianist — build a 30-second piece with Polish and English subtitles.",
    "Uploading a sketch of a young 1900s Sicilian immigrant — make a 1-minute mini-drama with Sicilian and Italian subtitles.",
    "Here's a digital painting of a young 1910s Greek immigrant — produce a 45-second short with Greek and English subtitles.",
    "I'm attaching this image of a young 1930s Irish dockworker — build a 30-second cinematic piece with Irish Gaelic and English subtitles.",
    "Uploading a portrait of a young 1900s Lebanese peddler — make a 1-minute mini-drama with Arabic and English subtitles.",
    "Here's a sketch of a young 1920s Armenian rug-merchant — render a 45-second cinematic short with Armenian and English subtitles.",
    "I'm sending you a watercolor of a young 1910s Finnish lumberjack — produce a 30-second piece with Finnish and English subtitles.",
    "Uploading a digital portrait of a young 1900s Czech glassblower — build a 1-minute mini-drama with Czech and English subtitles.",
    "Here's a portrait of a young 1910s Hungarian violinist — render a 45-second cinematic short with Hungarian and English subtitles.",
    "I'm attaching a sketch of a young 1920s Estonian carpenter — make a 30-second piece with Estonian and Russian subtitles.",
    "Uploading a watercolor of a young 1900s Latvian seamstress — produce a 1-minute mini-drama with Latvian and English subtitles.",
    "Here's a digital painting of a young 1910s Lithuanian baker — build a 45-second cinematic short with Lithuanian and English subtitles.",
    "I have a portrait of a young 1900s Albanian shepherdess — render a 30-second piece with Albanian and Greek subtitles.",
    "Uploading a sketch of a young 1920s Macedonian farmer — make a 1-minute mini-drama with Macedonian and Bulgarian subtitles.",
    "Here's a watercolor of a young 1910s Bulgarian rose-picker — produce a 45-second short with Bulgarian and English subtitles.",
    "I'm sending you a portrait of a young 1900s Slovenian beekeeper — build a 30-second cinematic piece with Slovenian and Italian subtitles.",
    "Uploading a digital painting of a young 1910s Croatian fisherman — make a 1-minute mini-drama with Croatian and Italian subtitles.",
    "Here's a sketch of a young 1900s Bosnian sevdah singer — render a 45-second cinematic short with Bosnian and English subtitles.",
    "I'm attaching a portrait of a young 1920s Serbian violinist — produce a 30-second piece with Serbian and English subtitles.",
    "Uploading a watercolor of a young 1900s Romanian fiddler — build a 1-minute mini-drama with Romanian and Hungarian subtitles.",
    "Here's a digital portrait of a young 1910s Catalan baker — make a 45-second cinematic short with Catalan and Spanish subtitles.",
    "I have a sketch of a young 1900s Galician fishmonger — render a 30-second piece with Galician and Spanish subtitles.",
    "Uploading a portrait of a young 1910s Basque pelota player — make a 1-minute mini-drama with Basque and Spanish subtitles.",
    "Here's a watercolor of a young 1900s Sardinian bread-baker — produce a 45-second short with Sardinian and Italian subtitles.",
    "I'm sending you a digital painting of a young 1920s Sicilian fisherman — build a 30-second cinematic piece with Sicilian and Italian subtitles.",
    "Uploading a sketch of a young 1900s Maltese ftira-baker — render a 1-minute mini-drama with Maltese and English subtitles.",
    "Here's a portrait of a young 1910s Welsh coal-miner — make a 45-second cinematic short with Welsh and English subtitles.",
    "I'm attaching a watercolor of a young 1900s Manx fisherman — produce a 30-second piece with Manx and English subtitles.",
    "Uploading a digital portrait of a young 1920s Cornish-tin miner — build a 1-minute mini-drama with Cornish and English subtitles.",
    "Here's a sketch of a young 1900s Faroese fisherman — render a 45-second cinematic short with Faroese and Danish subtitles.",
    "I have a portrait of a young 1910s Icelandic poet — make a 30-second piece with Icelandic and English subtitles.",
    "Uploading a watercolor of a young 1900s Greenlandic Inuk hunter — produce a 1-minute mini-drama with Greenlandic and Danish subtitles.",
    "Here's a digital painting of a young 1920s Yupik storyteller — build a 45-second cinematic short with Yupik and English subtitles.",
    "I'm sending you a sketch of a young 1900s Cree trapper — render a 30-second piece with Cree and English subtitles.",
    "Uploading a portrait of a young 1910s Inuktitut grandmother — make a 1-minute mini-drama with Inuktitut and French subtitles.",
    "Here's a watercolor of a young 1920s Ojibwe wild-rice harvester — produce a 45-second short with Ojibwe and English subtitles.",
    "I'm attaching a digital portrait of a young 1900s Anishinaabe storyteller — build a 30-second cinematic piece with Anishinaabe and English subtitles.",
    "Uploading a sketch of a young 1910s Lakota grandfather — render a 1-minute mini-drama with Lakota and English subtitles.",
    "Here's a portrait of a young 1920s Cherokee weaver — make a 45-second cinematic short with Cherokee and English subtitles.",
    "I have a watercolor of a young 1900s Apache scout — produce a 30-second piece with Apache and English subtitles.",
    "Uploading a digital painting of a young 1910s Hopi farmer — build a 1-minute mini-drama with Hopi and English subtitles.",
    "Here's a sketch of a young 1920s Zuni potter — render a 45-second cinematic short with Zuni and English subtitles.",
    # ── more reference-image cinematic shorts with bilingual subtitles (50) ──
    "Uploading a portrait of a young 1850s California gold-rush prospector — make a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a sketch of a young 1880s Yukon gold-rush prospector — build a 45-second cinematic short with English and French subtitles.",
    "I'm sending you a watercolor of a young 1890s Klondike prospector — produce a 30-second piece with English and Tlingit subtitles.",
    "Uploading a digital painting of a young 1850s Australian gold-rush digger — make a 1-minute mini-drama with English and Cantonese subtitles.",
    "Here's a portrait of a young 1890s Boer-war soldier — render a 45-second cinematic short with Afrikaans and English subtitles.",
    "I'm attaching a sketch of a young 1900s Dutch tulip-grower — build a 30-second piece with Dutch and English subtitles.",
    "Uploading this concept art of a young 1910s Belgian Flemish lacemaker — produce a 1-minute mini-drama with Flemish and French subtitles.",
    "Here's a watercolor of a young 1920s Luxembourgish ironworker — render a 45-second short with Luxembourgish and German subtitles.",
    "I have a portrait of a young 1930s Swiss alphorn-player — build a 30-second piece with Swiss German and French subtitles.",
    "Uploading a sketch of a young 1920s Manchurian railroad-worker — make a 1-minute mini-drama with Mandarin and Russian subtitles.",
    "Here's a digital painting of a young 1900s Cantonese opera apprentice — produce a 45-second short with Cantonese and English subtitles.",
    "I'm attaching this image of a young 1880s Hakka tea farmer — build a 30-second cinematic piece with Hakka and Mandarin subtitles.",
    "Uploading a portrait of a young 1900s Hokkien sailor — make a 1-minute mini-drama with Hokkien and English subtitles.",
    "Here's a sketch of a young 1890s Korean palace-guard — render a 45-second cinematic short with Korean and English subtitles.",
    "I'm sending you a watercolor of a young 1920s Joseon court-painter — produce a 30-second piece with Korean and Mandarin subtitles.",
    "Uploading a digital portrait of a young 1910s Edo-era kimono-maker — build a 1-minute mini-drama with Japanese and English subtitles.",
    "Here's a portrait of a young 1900s Ryukyuan sanshin-singer — render a 45-second cinematic short with Okinawan and Japanese subtitles.",
    "I'm attaching a sketch of a young 1880s Ainu hunter — make a 30-second piece with Ainu and Japanese subtitles.",
    "Uploading a watercolor of a young 1910s Vietnamese rice-farmer — produce a 1-minute mini-drama with Vietnamese and French subtitles.",
    "Here's a digital painting of a young 1900s Philippine Spanish-mestiza — build a 45-second cinematic short with Tagalog and Spanish subtitles.",
    "I have a portrait of a young 1920s Javanese batik-maker — render a 30-second piece with Javanese and Indonesian subtitles.",
    "Uploading a sketch of a young 1900s Sundanese gamelan-player — make a 1-minute mini-drama with Sundanese and Indonesian subtitles.",
    "Here's a watercolor of a young 1910s Balinese temple-dancer — produce a 45-second short with Balinese and Indonesian subtitles.",
    "I'm sending you a portrait of a young 1920s Malay sultanate-court musician — build a 30-second cinematic piece with Malay and English subtitles.",
    "Uploading a digital painting of a young 1900s Singaporean Peranakan trader — make a 1-minute mini-drama with Hokkien and Malay subtitles.",
    "Here's a sketch of a young 1900s Zulu warrior — render a 45-second cinematic short with Zulu and English subtitles.",
    "I'm attaching a portrait of a young 1920s Swahili coast trader — produce a 30-second piece with Swahili and Arabic subtitles.",
    "Uploading a watercolor of a young 1910s Yoruba palace-bard — build a 1-minute mini-drama with Yoruba and English subtitles.",
    "Here's a digital portrait of a young 1900s Igbo blacksmith — make a 45-second cinematic short with Igbo and English subtitles.",
    "I have a sketch of a young 1920s Akan goldsmith — render a 30-second piece with Twi and English subtitles.",
    "Uploading a portrait of a young 1900s Hausa trans-Saharan trader — make a 1-minute mini-drama with Hausa and Arabic subtitles.",
    "Here's a watercolor of a young 1910s Wolof griot — produce a 45-second short with Wolof and French subtitles.",
    "I'm sending you a digital painting of a young 1900s Maasai herder — build a 30-second cinematic piece with Maa and Swahili subtitles.",
    "Uploading a sketch of a young 1920s Kikuyu farmer — render a 1-minute mini-drama with Kikuyu and English subtitles.",
    "Here's a portrait of a young 1910s Amhara monastery-monk — make a 45-second cinematic short with Amharic and Ge'ez subtitles.",
    "I'm attaching a watercolor of a young 1900s Tigrinya caravan-trader — produce a 30-second piece with Tigrinya and Arabic subtitles.",
    "Uploading a digital portrait of a young 1920s Somali camel-herder — build a 1-minute mini-drama with Somali and Arabic subtitles.",
    "Here's a sketch of a young 1900s Ottoman Cairo merchant — render a 45-second cinematic short with Ottoman Turkish and Arabic subtitles.",
    "I have a portrait of a young 1920s Persian carpet-weaver — make a 30-second piece with Persian and Azerbaijani subtitles.",
    "Uploading a watercolor of a young 1910s Kurdish shepherdess — produce a 1-minute mini-drama with Kurdish and Turkish subtitles.",
    "Here's a digital painting of a young 1900s Georgian winemaker — build a 45-second cinematic short with Georgian and Russian subtitles.",
    "I'm sending you a sketch of a young 1920s Armenian Yerevan poet — render a 30-second piece with Armenian and Russian subtitles.",
    "Uploading a portrait of a young 1900s Azerbaijani tar-player — make a 1-minute mini-drama with Azerbaijani and Russian subtitles.",
    "Here's a watercolor of a young 1900s Argentinian pampas gaucho — produce a 45-second short with Spanish and Mapudungun subtitles.",
    "I'm attaching a digital portrait of a young 1920s Bahian capoeirista — build a 30-second cinematic piece with Portuguese and Yoruba subtitles.",
    "Uploading a sketch of a young 1910s Peruvian Andean shepherd — render a 1-minute mini-drama with Quechua and Spanish subtitles.",
    "Here's a portrait of a young 1900s Bolivian tin-miner — make a 45-second cinematic short with Aymara and Spanish subtitles.",
    "I have a watercolor of a young 1920s Chilean Mapuche weaver — produce a 30-second piece with Mapudungun and Spanish subtitles.",
    "Uploading a digital painting of a young 1910s Paraguayan Guaraní harpist — build a 1-minute mini-drama with Guaraní and Spanish subtitles.",
    "Here's a sketch of a young 1900s Uruguayan candombe drummer — render a 45-second cinematic short with Spanish and Portuguese subtitles.",
    # ── more reference-image cinematic shorts with bilingual subtitles (50) ──
    "Uploading a portrait of a young 1850s Boston abolitionist printer — make a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a sketch of a young 1880s Frontier postmistress — render a 45-second cinematic short with English and Lakota subtitles.",
    "I have a watercolor of a young 1900s Cumbrian fisherwoman — produce a 30-second piece with Cumbrian and English subtitles.",
    "Uploading a digital painting of a young 1920s Manchurian railway engineer — build a 1-minute mini-drama with Mandarin and Russian subtitles.",
    "Here's a portrait of a young 1950s Hollywood starlet — make a 45-second cinematic short with English and Yiddish subtitles.",
    "I'm attaching a sketch of a young 1880s Yukon trapper — produce a 30-second piece with English and Tlingit subtitles.",
    "Uploading this concept art of a young 1900s Boer farmer — produce a 1-minute mini-drama with Afrikaans and English subtitles.",
    "Here's a watercolor of a young 1920s Australian outback ranger — render a 45-second short with English and Yolŋu Matha subtitles.",
    "I have a portrait of a young 1880s Argentine pampas gaucho — build a 30-second piece with Spanish and Mapudungun subtitles.",
    "Uploading a sketch of a young 1900s Uruguayan candombe drummer-elder — make a 1-minute mini-drama with Spanish and Yoruba subtitles.",
    "Here's a digital painting of a young 1920s Argentine tango-singer — produce a 45-second short with Spanish and Italian subtitles.",
    "I'm attaching this image of a young 1900s Brazilian sertão violeiro — build a 30-second cinematic piece with Portuguese and Tupi subtitles.",
    "Uploading a portrait of a young 1920s Cuban rumba-singer — make a 1-minute mini-drama with Spanish and Yoruba subtitles.",
    "Here's a sketch of a young 1900s Dominican merengue accordionist — render a 45-second cinematic short with Spanish and Haitian-Kreyòl subtitles.",
    "I'm sending you a watercolor of a young 1900s Puerto-Rican plena-drummer — produce a 30-second piece with Spanish and Yoruba subtitles.",
    "Uploading a digital portrait of a young 1900s Ozark fiddler — build a 1-minute mini-drama with English and Cherokee subtitles.",
    "Here's a portrait of a young 1880s Appalachian banjo-player — render a 45-second cinematic short with English and Cherokee subtitles.",
    "I'm attaching a sketch of a young 1900s New-Orleans jazz-cornetist — make a 30-second piece with English and Louisiana-Creole subtitles.",
    "Uploading a watercolor of a young 1920s Memphis-blues guitarist — produce a 1-minute mini-drama with English and Choctaw subtitles.",
    "Here's a digital painting of a young 1900s Texas cowboy — build a 45-second cinematic short with English and Spanish subtitles.",
    "I have a portrait of a young 1880s frontier midwife — render a 30-second piece with English and Lakota subtitles.",
    "Uploading a sketch of a young 1900s Frontier farmwife — make a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a watercolor of a young 1880s Frontier cattle-rustler — produce a 45-second short with English and Spanish subtitles.",
    "I'm sending you a portrait of a young 1900s gold-rush prospector — build a 30-second cinematic piece with English and Tlingit subtitles.",
    "Uploading a digital painting of a young 1880s Frontier saloon-keeper — make a 1-minute mini-drama with English and Mandarin subtitles.",
    "Here's a sketch of a young 1900s Frontier Chinese laundress — render a 45-second cinematic short with Mandarin and English subtitles.",
    "I'm attaching a portrait of a young 1900s Hawaiian-Japanese plantation worker — produce a 30-second piece with Hawaiian and Japanese subtitles.",
    "Uploading a watercolor of a young 1900s Fijian-Indian indenture-laborer — build a 1-minute mini-drama with Fijian and Hindi subtitles.",
    "Here's a digital portrait of a young 1900s Trinidadian-Indian indenture-laborer — make a 45-second cinematic short with Trinidadian-Creole and Hindi subtitles.",
    "I have a sketch of a young 1900s Surinamese-Javanese indenture-worker — render a 30-second piece with Sranan-Tongo and Javanese subtitles.",
    "Uploading a portrait of a young 1900s Mauritian-Indian indenture-laborer — make a 1-minute mini-drama with Mauritian-Creole and Hindi subtitles.",
    "Here's a watercolor of a young 1900s East-African-Indian shopkeeper — produce a 45-second short with Swahili and Gujarati subtitles.",
    "I'm sending you a digital painting of a young 1900s Burma-British administrator — build a 30-second cinematic piece with English and Burmese subtitles.",
    "Uploading a sketch of a young 1900s Hong-Kong British policeman — render a 1-minute mini-drama with English and Cantonese subtitles.",
    "Here's a portrait of a young 1900s Manila Spanish-mestiza — make a 45-second cinematic short with Tagalog and Spanish subtitles.",
    "I'm attaching a watercolor of a young 1900s Macau Chinese-Portuguese clerk — produce a 30-second piece with Cantonese and Portuguese subtitles.",
    "Uploading a digital portrait of a young 1900s Goa Portuguese-Indian merchant — build a 1-minute mini-drama with Konkani and Portuguese subtitles.",
    "Here's a sketch of a young 1900s Saigon French-Indochinese pharmacist — render a 45-second cinematic short with Vietnamese and French subtitles.",
    "I have a portrait of a young 1900s Pondicherry Tamil-French clerk — make a 30-second piece with Tamil and French subtitles.",
    "Uploading a watercolor of a young 1900s Algerian Pied-Noir farmer — produce a 1-minute mini-drama with French and Algerian-Arabic subtitles.",
    "Here's a digital painting of a young 1900s Tunisian-Jewish seamstress — build a 45-second cinematic short with Arabic and Hebrew subtitles.",
    "I'm sending you a sketch of a young 1900s Aleppo Armenian merchant — render a 30-second piece with Armenian and Arabic subtitles.",
    "Uploading a portrait of a young 1900s Istanbul Greek shopkeeper — make a 1-minute mini-drama with Greek and Turkish subtitles.",
    "Here's a watercolor of a young 1900s Ottoman Anatolian Armenian deacon — produce a 45-second short with Armenian and Turkish subtitles.",
    "I'm attaching a digital portrait of a young 1900s Czarist Cossack horseman — build a 30-second cinematic piece with Russian and Ukrainian subtitles.",
    "Uploading a sketch of a young 1900s Belarusian-Jewish shtetl-elder — render a 1-minute mini-drama with Yiddish and Belarusian subtitles.",
    "Here's a portrait of a young 1900s Lithuanian-Jewish yeshiva student — make a 45-second cinematic short with Yiddish and Lithuanian subtitles.",
    "I have a watercolor of a young 1900s Hungarian-Slovak miner — produce a 30-second piece with Slovak and Hungarian subtitles.",
    "Uploading a digital painting of a young 1900s Ottoman Balkan barrel-maker — build a 1-minute mini-drama with Turkish and Bulgarian subtitles.",
    "Here's a sketch of a young 1900s Greek-Macedonian shepherd — render a 45-second cinematic short with Greek and Slavomacedonian subtitles.",
    # ── more reference-image cinematic shorts with bilingual subtitles (50) ──
    "Uploading a portrait of a young 1820s Greek-revolutionary — make a 1-minute mini-drama with Greek and Turkish subtitles.",
    "Here's a sketch of a young 1830s Polish-November-uprising fighter — render a 45-second cinematic short with Polish and Russian subtitles.",
    "I have a watercolor of a young 1830s French-July-Revolution barricader — produce a 30-second piece with French and English subtitles.",
    "Uploading a digital painting of a young 1840s Irish-famine emigrant — build a 1-minute mini-drama with Irish and English subtitles.",
    "Here's a portrait of a young 1840s German-Forty-Eighter — make a 45-second cinematic short with German and English subtitles.",
    "I'm attaching a sketch of a young 1850s Hungarian-1848-revolutionary — produce a 30-second piece with Hungarian and German subtitles.",
    "Uploading this concept art of a young 1860s Italian-Risorgimento volunteer — produce a 1-minute mini-drama with Italian and French subtitles.",
    "Here's a watercolor of a young 1870s Paris-Commune barricader — render a 45-second short with French and German subtitles.",
    "I have a portrait of a young 1880s Bulgarian-revolutionary — build a 30-second piece with Bulgarian and Russian subtitles.",
    "Uploading a sketch of a young 1890s Cuban-revolution mambí — make a 1-minute mini-drama with Spanish and English subtitles.",
    "Here's a digital painting of a young 1900s Yiddish-theater actress — produce a 45-second short with Yiddish and Russian subtitles.",
    "I'm attaching this image of a young 1900s Polish-resistance courier — build a 30-second cinematic piece with Polish and German subtitles.",
    "Uploading a portrait of a young 1900s Romanian-folk-singer — make a 1-minute mini-drama with Romanian and Hungarian subtitles.",
    "Here's a sketch of a young 1910s Slovak-folk-musician — render a 45-second cinematic short with Slovak and Hungarian subtitles.",
    "I'm sending you a watercolor of a young 1910s Czech-puppeteer — produce a 30-second piece with Czech and German subtitles.",
    "Uploading a digital portrait of a young 1910s Vienna-Secession-art-student — build a 1-minute mini-drama with German and Hungarian subtitles.",
    "Here's a portrait of a young 1910s Berlin-Bauhaus-student — render a 45-second cinematic short with German and Hungarian subtitles.",
    "I'm attaching a sketch of a young 1920s Weimar-cabaret-dancer — make a 30-second piece with German and French subtitles.",
    "Uploading a watercolor of a young 1920s Soviet-OSA-architect — produce a 1-minute mini-drama with Russian and Ukrainian subtitles.",
    "Here's a digital painting of a young 1920s Constructivist-poster designer — build a 45-second cinematic short with Russian and Belarusian subtitles.",
    "I have a portrait of a young 1920s Harlem-Renaissance-poet — render a 30-second piece with English and Yoruba subtitles.",
    "Uploading a sketch of a young 1920s Caribbean-Garveyite — make a 1-minute mini-drama with English and Twi subtitles.",
    "Here's a watercolor of a young 1920s Pan-Africanist organizer — produce a 45-second short with English and Wolof subtitles.",
    "I'm sending you a portrait of a young 1930s Spanish-Civil-War nurse — build a 30-second cinematic piece with Spanish and Catalan subtitles.",
    "Uploading a digital painting of a young 1930s Republican-Brigadista — make a 1-minute mini-drama with Spanish and English subtitles.",
    "Here's a sketch of a young 1930s Catalan resistance girl — render a 45-second cinematic short with Catalan and Spanish subtitles.",
    "I'm attaching a portrait of a young 1930s French-Popular-Front organizer — produce a 30-second piece with French and Italian subtitles.",
    "Uploading a watercolor of a young 1940s French-Resistance courier — build a 1-minute mini-drama with French and Hebrew subtitles.",
    "Here's a digital portrait of a young 1940s Polish-Warsaw-Uprising fighter — render a 45-second cinematic short with Polish and Yiddish subtitles.",
    "I have a sketch of a young 1940s Norwegian-Resistance ski-courier — produce a 30-second piece with Norwegian and Sami subtitles.",
    "Uploading a portrait of a young 1940s Greek-Resistance partisan — make a 1-minute mini-drama with Greek and Albanian subtitles.",
    "Here's a watercolor of a young 1940s Yugoslav-Partisan — produce a 45-second short with Serbo-Croatian and Slovenian subtitles.",
    "I'm sending you a digital painting of a young 1940s Italian-Resistance partisan — build a 30-second cinematic piece with Italian and Friulian subtitles.",
    "Uploading a sketch of a young 1940s Dutch-Resistance bicycle-courier — render a 1-minute mini-drama with Dutch and Frisian subtitles.",
    "Here's a portrait of a young 1940s Belgian-Resistance courier — make a 45-second cinematic short with French and Walloon subtitles.",
    "I'm attaching a watercolor of a young 1940s Filipino-Hukbalahap fighter — produce a 30-second piece with Tagalog and Spanish subtitles.",
    "Uploading a digital portrait of a young 1940s Korean-Independence-fighter — build a 1-minute mini-drama with Korean and Japanese subtitles.",
    "Here's a sketch of a young 1940s Chinese-People's-Army medic — render a 45-second cinematic short with Mandarin and Cantonese subtitles.",
    "I have a portrait of a young 1940s Vietnamese-Viet-Minh courier — make a 30-second piece with Vietnamese and French subtitles.",
    "Uploading a watercolor of a young 1950s Algerian-FLN courier — produce a 1-minute mini-drama with Arabic and Berber subtitles.",
    "Here's a digital painting of a young 1950s Cypriot-EOKA messenger — build a 45-second cinematic short with Greek and Turkish subtitles.",
    "I'm sending you a sketch of a young 1950s Mau-Mau-Kenyan organizer — render a 30-second piece with Kikuyu and English subtitles.",
    "Uploading a portrait of a young 1950s Cuban-26th-of-July fighter — make a 1-minute mini-drama with Spanish and English subtitles.",
    "Here's a watercolor of a young 1960s Algerian-independence-poet — produce a 45-second short with Arabic and French subtitles.",
    "I'm attaching a digital portrait of a young 1960s Black-Panther organizer — build a 30-second cinematic piece with English and Spanish subtitles.",
    "Uploading a sketch of a young 1960s Quebec-FLQ activist — render a 1-minute mini-drama with Quebec-French and English subtitles.",
    "Here's a portrait of a young 1960s Catalan-protest student — make a 45-second cinematic short with Catalan and Spanish subtitles.",
    "I have a watercolor of a young 1960s Basque-Euskera-protest organizer — produce a 30-second piece with Basque and Spanish subtitles.",
    "Uploading a digital painting of a young 1960s Welsh-language-protest student — build a 1-minute mini-drama with Welsh and English subtitles.",
    "Here's a sketch of a young 1960s Irish-civil-rights-marcher — render a 45-second cinematic short with Irish-Gaelic and English subtitles.",
    # ── more historic-era artists / musicians / writers (50) ──
    "Uploading a portrait of a young Renaissance-Florentine fresco-apprentice — make a 1-minute mini-drama with Italian and Latin subtitles.",
    "Here's a watercolor of a young Renaissance-Venetian glassblower — produce a 45-second cinematic short with Venetian and Italian subtitles.",
    "I have a digital portrait of a young Baroque-Roman sculpture-apprentice — build a 30-second piece with Italian and Latin subtitles.",
    "Uploading a sketch of a young Baroque-Dutch tulip-painter — render a 1-minute mini-drama with Dutch and Latin subtitles.",
    "Here's a portrait of a young Baroque-Flemish lace-maker — make a 45-second cinematic short with Flemish and French subtitles.",
    "I'm sending you a digital painting of a young Rococo-French miniaturist — produce a 30-second piece with French and Italian subtitles.",
    "Uploading a watercolor of a young Romantic-German violinist — build a 1-minute mini-drama with German and French subtitles.",
    "Here's a sketch of a young Romantic-English landscape-painter — render a 45-second cinematic short with English and French subtitles.",
    "I have a portrait of a young Pre-Raphaelite-London illustrator — make a 30-second piece with English and Italian subtitles.",
    "I'm attaching a digital portrait of a young Impressionist-Paris café-painter — build a 30-second cinematic piece with French and English subtitles.",
    "Uploading a sketch of a young Post-Impressionist-Aix painter — render a 1-minute mini-drama with French and Provençal subtitles.",
    "Here's a portrait of a young Belle-Époque cabaret-singer — make a 45-second cinematic short with French and English subtitles.",
    "I have a watercolor of a young Vienna-Secession architect-apprentice — produce a 30-second piece with German and Czech subtitles.",
    "Uploading a digital painting of a young Bauhaus weaver — build a 1-minute mini-drama with German and English subtitles.",
    "Here's a sketch of a young Cubist-Paris collage-artist — render a 45-second cinematic short with French and Spanish subtitles.",
    "I'm sending you a portrait of a young Surrealist-Paris dream-illustrator — make a 30-second piece with French and Spanish subtitles.",
    "Uploading a watercolor of a young Dada-Zürich poet — produce a 1-minute mini-drama with German and French subtitles.",
    "Here's a digital portrait of a young Futurist-Milan poster-artist — build a 45-second cinematic short with Italian and French subtitles.",
    "I have a sketch of a young Constructivist-Moscow poster-designer — render a 30-second piece with Russian and German subtitles.",
    "I'm attaching a portrait of a young Suprematist-Vitebsk geometrist — make a 30-second cinematic piece with Russian and Yiddish subtitles.",
    "Uploading a digital painting of a young Mexican-muralist apprentice — build a 1-minute mini-drama with Spanish and Nahuatl subtitles.",
    "Here's a watercolor of a young Harlem-Renaissance jazz-pianist — produce a 45-second short with English and French subtitles.",
    "I'm sending you a sketch of a young Harlem-Renaissance dancer — render a 30-second cinematic piece with English and Spanish subtitles.",
    "Uploading a portrait of a young Bauhaus typographer — make a 1-minute mini-drama with German and English subtitles.",
    "Here's a digital painting of a young Berlin-Cabaret singer — build a 45-second cinematic short with German and English subtitles.",
    "I have a sketch of a young Weimar film-poster artist — render a 30-second piece with German and English subtitles.",
    "I'm attaching a watercolor of a young Latin-American-Boom novelist-apprentice — make a 30-second cinematic piece with Spanish and Portuguese subtitles.",
    "Uploading a digital portrait of a young Beat-Generation poet — build a 1-minute mini-drama with English and French subtitles.",
    "Here's a portrait of a young Greenwich-Village folk-singer — produce a 45-second cinematic short with English and Spanish subtitles.",
    "I have a watercolor of a young Swinging-Sixties-London fashion-designer — render a 30-second piece with English and French subtitles.",
    "Uploading a sketch of a young Tropicália-Bahia musician — produce a 1-minute mini-drama with Portuguese and Spanish subtitles.",
    "Here's a digital painting of a young Nouvelle-Vague-Paris filmmaker — build a 45-second cinematic short with French and English subtitles.",
    "I'm sending you a portrait of a young Polish-Solidarity poster-artist — render a 30-second cinematic piece with Polish and English subtitles.",
    "Uploading a watercolor of a young East-Berlin underground-zinemaker — make a 1-minute mini-drama with German and English subtitles.",
    "Here's a sketch of a young Prague-Spring poet-apprentice — produce a 45-second cinematic short with Czech and German subtitles.",
    "I have a portrait of a young Yugoslav-Black-Wave filmmaker — make a 30-second piece with Serbo-Croatian and English subtitles.",
    "I'm attaching a digital portrait of a young 1980s-Brazilian-rock guitarist — build a 30-second cinematic piece with Portuguese and English subtitles.",
    "Uploading a sketch of a young 1980s-Cuban-nueva-trova singer — render a 1-minute mini-drama with Spanish and English subtitles.",
    "Here's a watercolor of a young 1980s-Argentinian-Rock-Nacional singer — produce a 45-second short with Spanish and English subtitles.",
    "I have a digital painting of a young 1980s-Chilean-Nueva-Canción singer — build a 30-second cinematic piece with Spanish and Mapudungun subtitles.",
    "Uploading a portrait of a young 1980s-Iranian-underground singer — make a 1-minute mini-drama with Persian and English subtitles.",
    "Here's a sketch of a young 1980s-Soviet-rock-underground guitarist — render a 45-second cinematic short with Russian and English subtitles.",
    "I'm sending you a watercolor of a young 1990s-Britpop singer — produce a 30-second piece with English and German subtitles.",
    "Uploading a digital portrait of a young 1990s-Madchester-rave DJ — build a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a portrait of a young 1990s-Rotterdam-Gabber DJ — make a 45-second cinematic short with Dutch and German subtitles.",
    "I have a sketch of a young 1990s-Berlin-Techno DJ — produce a 30-second piece with German and English subtitles.",
    "I'm attaching a digital painting of a young 1990s-Bristol-Trip-Hop producer — build a 30-second cinematic piece with English and French subtitles.",
    "Uploading a watercolor of a young 1990s-Detroit-Techno DJ — render a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a sketch of a young 1990s-Chicago-House producer — produce a 45-second cinematic short with English and Spanish subtitles.",
    "I have a portrait of a young 2000s-Reykjavik-electronica producer — make a 30-second piece with Icelandic and English subtitles.",
    # ── more contemporary childhood / school-yard / family scenes (50) ──
    "I'm sending you a portrait of a young Brooklyn-stoop kid — produce a 1-minute mini-drama with English and Spanish subtitles.",
    "Uploading a watercolor of a young Queens-soccer kid — build an illustrated children's tale with English and Mandarin subtitles.",
    "Here's a digital portrait of a young Bronx-double-dutch kid — render a 45-second cinematic short with English and Spanish subtitles.",
    "I have a sketch of a young Manhattan-private-school kid — produce a 30-second piece with English and French subtitles.",
    "Uploading a portrait of a young Boston-Common-skater kid — make a 1-minute mini-drama with English and Portuguese subtitles.",
    "Here's a watercolor of a young Chicago-jump-rope kid — build a 45-second cinematic short with English and Spanish subtitles.",
    "I'm sending you a digital painting of a young Detroit-art-school kid — render a 30-second piece with English and Arabic subtitles.",
    "Uploading a sketch of a young Cleveland-Lake-Erie kid — produce a 1-minute mini-drama with English and Hungarian subtitles.",
    "Here's a portrait of a young Pittsburgh-Strip-District kid — make a 45-second cinematic short with English and Italian subtitles.",
    "I have a watercolor of a young Philadelphia-row-house kid — produce a 30-second piece with English and Spanish subtitles.",
    "I'm attaching a digital portrait of a young Baltimore-stoop kid — build a 1-minute mini-drama with English and Patois subtitles.",
    "Uploading a sketch of a young Atlanta-pickup-basketball kid — render a 45-second cinematic short with English and Spanish subtitles.",
    "Here's a portrait of a young New-Orleans-second-line kid — produce a 30-second piece with English and French subtitles.",
    "I have a digital painting of a young Houston-tex-mex-kitchen kid — build a 1-minute mini-drama with English and Spanish subtitles.",
    "Uploading a watercolor of a young Austin-music-festival kid — make a 45-second cinematic short with English and Spanish subtitles.",
    "Here's a sketch of a young Dallas-yard-sale kid — render a 30-second piece with English and Vietnamese subtitles.",
    "I'm sending you a portrait of a young Phoenix-cactus-yard kid — produce a 1-minute mini-drama with English and Spanish subtitles.",
    "Uploading a digital portrait of a young San-Diego-beach kid — make a 45-second cinematic short with English and Spanish subtitles.",
    "Here's a watercolor of a young LA-Echo-Park kid — build a 30-second piece with English and Korean subtitles.",
    "I have a sketch of a young SF-Mission-District kid — produce a 1-minute mini-drama with English and Spanish subtitles.",
    "I'm attaching a digital painting of a young Seattle-Pike-Place kid — render a 45-second cinematic short with English and Filipino subtitles.",
    "Uploading a portrait of a young Portland-skate-park kid — make a 30-second piece with English and Russian subtitles.",
    "Here's a sketch of a young Honolulu-tide-pool kid — produce a 1-minute mini-drama with English and Hawaiian subtitles.",
    "I have a watercolor of a young Anchorage-snow-fort kid — build a 45-second cinematic short with English and Yupik subtitles.",
    "I'm sending you a digital portrait of a young Toronto-CN-Tower kid — render a 30-second piece with English and French subtitles.",
    "Uploading a portrait of a young Montreal-Plateau kid — make a 1-minute mini-drama with French and English subtitles.",
    "Here's a watercolor of a young Vancouver-Granville-Island kid — produce a 45-second cinematic short with English and Cantonese subtitles.",
    "I have a digital painting of a young Mexico-City-Coyoacán kid — build a 30-second piece with Spanish and Nahuatl subtitles.",
    "Uploading a sketch of a young Buenos-Aires-La-Boca kid — render a 1-minute mini-drama with Spanish and Italian subtitles.",
    "Here's a portrait of a young São-Paulo-favela-funk kid — make a 45-second cinematic short with Portuguese and Spanish subtitles.",
    "I'm sending you a watercolor of a young Rio-Cantagalo kid — produce a 30-second piece with Portuguese and English subtitles.",
    "Uploading a digital portrait of a young London-Brick-Lane kid — build a 1-minute mini-drama with English and Bengali subtitles.",
    "Here's a sketch of a young Manchester-park kid — render a 45-second cinematic short with English and Urdu subtitles.",
    "I have a portrait of a young Liverpool-Anfield kid — produce a 30-second piece with English and Welsh subtitles.",
    "I'm attaching a digital painting of a young Edinburgh-Royal-Mile kid — make a 1-minute mini-drama with English and Scottish-Gaelic subtitles.",
    "Uploading a watercolor of a young Cardiff-Bay kid — build a 45-second cinematic short with English and Welsh subtitles.",
    "Here's a sketch of a young Dublin-Liberties kid — render a 30-second piece with English and Irish subtitles.",
    "I have a digital portrait of a young Belfast-Falls-Road kid — produce a 1-minute mini-drama with English and Irish subtitles.",
    "Uploading a portrait of a young Paris-Belleville kid — make a 45-second cinematic short with French and Arabic subtitles.",
    "Here's a watercolor of a young Marseille-Panier kid — produce a 30-second piece with French and Arabic subtitles.",
    "I'm sending you a digital painting of a young Berlin-Kreuzberg kid — build a 1-minute mini-drama with German and Turkish subtitles.",
    "Uploading a sketch of a young Hamburg-Schanzenviertel kid — render a 45-second cinematic short with German and Polish subtitles.",
    "Here's a portrait of a young Vienna-Naschmarkt kid — produce a 30-second piece with German and Serbian subtitles.",
    "I have a watercolor of a young Prague-Vinohrady kid — make a 1-minute mini-drama with Czech and Vietnamese subtitles.",
    "I'm attaching a digital portrait of a young Moscow-Khamovniki kid — build a 45-second cinematic short with Russian and English subtitles.",
    "Uploading a portrait of a young Seoul-Hongdae kid — render a 30-second piece with Korean and English subtitles.",
    "Here's a sketch of a young Tokyo-Shimokitazawa kid — produce a 1-minute mini-drama with Japanese and English subtitles.",
    "I have a digital painting of a young Hong-Kong-Tin-Hau kid — build a 45-second cinematic short with Cantonese and English subtitles.",
    "Uploading a watercolor of a young Mumbai-Dharavi kid — render a 30-second piece with Hindi and Marathi subtitles.",
    "Here's a portrait of a young Cairo-Khan-el-Khalili kid — produce a 1-minute mini-drama with Arabic and English subtitles.",
    # ── more futuristic / sci-fi / space-colony scenes (50) ──
    "Uploading a digital painting of a young Mars-Olympus-City colonist-kid — make a 1-minute mini-drama with English and Mandarin subtitles.",
    "Here's a sketch of a young Lunar-Tycho-base apprentice — render a 45-second cinematic short with English and Russian subtitles.",
    "I'm sending you a portrait of a young Europa-ice-station diver — produce a 30-second piece with English and German subtitles.",
    "Uploading a digital portrait of a young Titan-methane-lake hauler — build a 1-minute mini-drama with English and Japanese subtitles.",
    "Here's a watercolor of a young Ganymede-research-dome botanist-apprentice — render a 45-second cinematic short with English and Korean subtitles.",
    "I have a digital painting of a young Ceres-mining-belt operator-kid — produce a 30-second piece with English and Spanish subtitles.",
    "Uploading a portrait of a young Vesta-asteroid-colony tinkerer — make a 1-minute mini-drama with English and French subtitles.",
    "Here's a sketch of a young Phobos-orbital-station courier — render a 45-second cinematic short with English and Hindi subtitles.",
    "I'm sending you a digital painting of a young Deimos-shipyard apprentice — produce a 30-second piece with English and Arabic subtitles.",
    "Uploading a watercolor of a young Kepler-186f settler-kid — build a 1-minute mini-drama with English and Portuguese subtitles.",
    "Here's a portrait of a young Proxima-b colony farmer — render a 45-second cinematic short with English and Italian subtitles.",
    "I have a sketch of a young Trappist-1e ocean-station diver — produce a 30-second piece with English and Vietnamese subtitles.",
    "Uploading a digital portrait of a young Alpha-Centauri-Bb settler — make a 1-minute mini-drama with English and Indonesian subtitles.",
    "Here's a watercolor of a young O'Neill-cylinder-Stanford-Torus farmer — render a 45-second cinematic short with English and Thai subtitles.",
    "I'm sending you a digital painting of a young Bernal-sphere-habitat tinkerer — produce a 30-second piece with English and Tagalog subtitles.",
    "Uploading a portrait of a young Lagrange-L5-station docking-tech kid — build a 1-minute mini-drama with English and Malay subtitles.",
    "Here's a sketch of a young Asteroid-Belt-Eros-station mechanic — render a 45-second cinematic short with English and Turkish subtitles.",
    "I have a digital painting of a young Oort-cloud-comet-prospector kid — produce a 30-second piece with English and Polish subtitles.",
    "Uploading a watercolor of a young Kuiper-Belt-Pluto-base courier — make a 1-minute mini-drama with English and Czech subtitles.",
    "Here's a digital portrait of a young Charon-port apprentice — render a 45-second cinematic short with English and Hungarian subtitles.",
    "I'm sending you a portrait of a young Enceladus-geyser-research diver — produce a 30-second piece with English and Swedish subtitles.",
    "Uploading a sketch of a young Mimas-orbital-station signal-tech — build a 1-minute mini-drama with English and Norwegian subtitles.",
    "Here's a watercolor of a young Iapetus-walled-colony archivist-kid — render a 45-second cinematic short with English and Danish subtitles.",
    "I have a digital painting of a young Rhea-shipyard-yard apprentice — produce a 30-second piece with English and Finnish subtitles.",
    "Uploading a portrait of a young Hyperion-orbital-survey kid — make a 1-minute mini-drama with English and Greek subtitles.",
    "Here's a sketch of a young Tethys-research-base ice-driller — render a 45-second cinematic short with English and Romanian subtitles.",
    "I'm sending you a digital painting of a young Dione-helium-3-extraction kid — produce a 30-second piece with English and Bulgarian subtitles.",
    "Uploading a watercolor of a young Amalthea-orbital-mining apprentice — build a 1-minute mini-drama with English and Croatian subtitles.",
    "Here's a digital portrait of a young Io-volcano-survey kid — render a 45-second cinematic short with English and Serbian subtitles.",
    "I have a portrait of a young Callisto-radiation-shielded-colony kid — produce a 30-second piece with English and Slovenian subtitles.",
    "Uploading a sketch of a young Triton-cryovolcano-research kid — make a 1-minute mini-drama with English and Slovak subtitles.",
    "Here's a watercolor of a young Nereid-far-orbit-station apprentice — render a 45-second cinematic short with English and Lithuanian subtitles.",
    "I'm sending you a digital painting of a young Miranda-cliff-colony rope-rigger kid — produce a 30-second piece with English and Latvian subtitles.",
    "Uploading a portrait of a young Ariel-research-station kid — build a 1-minute mini-drama with English and Estonian subtitles.",
    "Here's a digital portrait of a young Umbriel-orbital-survey kid — render a 45-second cinematic short with English and Ukrainian subtitles.",
    "I have a sketch of a young Titania-deep-mining-colony kid — produce a 30-second piece with English and Belarusian subtitles.",
    "Uploading a watercolor of a young Oberon-far-rim-station kid — make a 1-minute mini-drama with English and Georgian subtitles.",
    "Here's a digital painting of a young Halley-comet-survey-vessel kid — render a 45-second cinematic short with English and Armenian subtitles.",
    "I'm sending you a portrait of a young Hayabusa-asteroid-mission-base kid — produce a 30-second piece with English and Hebrew subtitles.",
    "Uploading a sketch of a young Voyager-3-deep-space-relay kid — build a 1-minute mini-drama with English and Persian subtitles.",
    "Here's a watercolor of a young Galileo-orbital-Ganymede kid — render a 45-second cinematic short with English and Urdu subtitles.",
    "I have a digital portrait of a young Cassini-Saturn-orbital kid — produce a 30-second piece with English and Bengali subtitles.",
    "Uploading a portrait of a young New-Horizons-Pluto-flyby-base kid — make a 1-minute mini-drama with English and Tamil subtitles.",
    "Here's a sketch of a young Dragonfly-Titan-rotorcraft-base kid — render a 45-second cinematic short with English and Telugu subtitles.",
    "I'm sending you a digital painting of a young Lucy-Trojan-asteroid-survey kid — produce a 30-second piece with English and Marathi subtitles.",
    "Uploading a watercolor of a young Psyche-asteroid-mining kid — build a 1-minute mini-drama with English and Gujarati subtitles.",
    "Here's a digital portrait of a young DART-asteroid-redirection-station kid — render a 45-second cinematic short with English and Punjabi subtitles.",
    "I have a portrait of a young James-Webb-L2-station maintenance-kid — produce a 30-second piece with English and Sinhala subtitles.",
    "Uploading a sketch of a young Hubble-LEO-tour kid — make a 1-minute mini-drama with English and Nepali subtitles.",
    "Here's a watercolor of a young Mir-2-orbital-station apprentice — render a 45-second cinematic short with Russian and English subtitles.",
    # ── more post-apocalyptic / dystopian survival scenes (50) ──
    "Uploading a digital painting of a young post-nuclear Detroit-ruins scavenger — make a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a sketch of a young post-nuclear NYC-subway-tunnel survivor — render a 45-second cinematic short with English and Mandarin subtitles.",
    "I'm sending you a portrait of a young post-pandemic London-Tower-Bridge wanderer — produce a 30-second piece with English and French subtitles.",
    "Uploading a digital portrait of a young post-pandemic Tokyo-Shibuya-overgrown street-kid — build a 1-minute mini-drama with Japanese and English subtitles.",
    "Here's a watercolor of a young post-flood Venice-rooftop survivor — render a 45-second cinematic short with Italian and English subtitles.",
    "I have a digital painting of a young post-drought Phoenix-cracked-pavement scavenger — produce a 30-second piece with English and Spanish subtitles.",
    "Uploading a portrait of a young post-collapse Paris-Catacombs survivor — make a 1-minute mini-drama with French and English subtitles.",
    "Here's a sketch of a young post-collapse Berlin-Tempelhof-airfield squatter — render a 45-second cinematic short with German and Turkish subtitles.",
    "I'm sending you a digital painting of a young post-collapse Moscow-Metro-Polis settler — produce a 30-second piece with Russian and English subtitles.",
    "Uploading a watercolor of a young post-collapse Dubai-skyscraper-shell rooftop-tribe member — build a 1-minute mini-drama with Arabic and English subtitles.",
    "Here's a portrait of a young post-collapse Mumbai-Marine-Drive flooded-promenade kid — render a 45-second cinematic short with Hindi and English subtitles.",
    "I have a sketch of a young post-collapse Mexico-City-cathedral-square scavenger — produce a 30-second piece with Spanish and Nahuatl subtitles.",
    "Uploading a digital portrait of a young post-collapse São-Paulo-favela-rooftop archer — make a 1-minute mini-drama with Portuguese and Spanish subtitles.",
    "Here's a watercolor of a young post-collapse Buenos-Aires-Avenida-9-de-Julio walker — render a 45-second cinematic short with Spanish and Italian subtitles.",
    "I'm sending you a digital painting of a young post-collapse Lima-Lima-promenade scavenger — produce a 30-second piece with Spanish and Quechua subtitles.",
    "Uploading a portrait of a young post-collapse Bogotá-Monserrate-overlook lookout — build a 1-minute mini-drama with Spanish and English subtitles.",
    "Here's a sketch of a young post-collapse Cairo-pyramid-shadow trader — render a 45-second cinematic short with Arabic and English subtitles.",
    "I have a digital painting of a young post-collapse Lagos-third-mainland-bridge fisher — produce a 30-second piece with Yoruba and English subtitles.",
    "Uploading a watercolor of a young post-collapse Nairobi-Nyayo-stadium-rooftop sentinel — make a 1-minute mini-drama with Swahili and English subtitles.",
    "Here's a digital portrait of a young post-collapse Cape-Town-Table-Mountain-cable-car-shell forager — render a 45-second cinematic short with English and Xhosa subtitles.",
    "I'm sending you a portrait of a young post-collapse Marrakesh-Medina-night-market scavenger — produce a 30-second piece with Arabic and Berber subtitles.",
    "Uploading a sketch of a young post-collapse Istanbul-Galata-Tower lookout — build a 1-minute mini-drama with Turkish and English subtitles.",
    "Here's a watercolor of a young post-collapse Tehran-Azadi-Tower trader — render a 45-second cinematic short with Persian and English subtitles.",
    "I have a digital portrait of a young post-collapse Baghdad-Tigris-River-bridge sentinel — produce a 30-second piece with Arabic and Kurdish subtitles.",
    "Uploading a portrait of a young post-collapse Damascus-Old-City-Citadel scout — make a 1-minute mini-drama with Arabic and Aramaic subtitles.",
    "Here's a sketch of a young post-collapse Beirut-Pigeon-Rocks-corniche walker — render a 45-second cinematic short with Arabic and French subtitles.",
    "I'm sending you a digital painting of a young post-collapse Jerusalem-Old-City-Ramparts watcher — produce a 30-second piece with Hebrew and Arabic subtitles.",
    "Uploading a watercolor of a young post-collapse Amman-Citadel-Hill scavenger — build a 1-minute mini-drama with Arabic and English subtitles.",
    "Here's a portrait of a young post-collapse Athens-Acropolis-cliff lookout — render a 45-second cinematic short with Greek and English subtitles.",
    "I have a sketch of a young post-collapse Rome-Colosseum-arena scavenger — produce a 30-second piece with Italian and Latin subtitles.",
    "Uploading a digital portrait of a young post-collapse Madrid-Plaza-Mayor pigeon-keeper — make a 1-minute mini-drama with Spanish and Catalan subtitles.",
    "Here's a watercolor of a young post-collapse Lisbon-Castelo-São-Jorge sentinel — render a 45-second cinematic short with Portuguese and English subtitles.",
    "I'm sending you a digital painting of a young post-collapse Warsaw-Old-Town-Square ruin-walker — produce a 30-second piece with Polish and Yiddish subtitles.",
    "Uploading a portrait of a young post-collapse Prague-Charles-Bridge fisherman — build a 1-minute mini-drama with Czech and German subtitles.",
    "Here's a sketch of a young post-collapse Stockholm-Gamla-Stan harbor-trader — render a 45-second cinematic short with Swedish and Finnish subtitles.",
    "I have a digital painting of a young post-collapse Oslo-Operaen-rooftop fisher — produce a 30-second piece with Norwegian and Sami subtitles.",
    "Uploading a watercolor of a young post-collapse Helsinki-Senate-Square-step squatter — make a 1-minute mini-drama with Finnish and Russian subtitles.",
    "Here's a digital portrait of a young post-collapse Reykjavik-Hallgrímskirkja-step lookout — render a 45-second cinematic short with Icelandic and English subtitles.",
    "I'm sending you a portrait of a young post-collapse Sydney-Harbour-Bridge-pylon climber — produce a 30-second piece with English and Mandarin subtitles.",
    "Uploading a sketch of a young post-collapse Auckland-Sky-Tower-shell sentinel — build a 1-minute mini-drama with English and Maori subtitles.",
    "Here's a watercolor of a young post-collapse Bangkok-Wat-Arun ruin-walker — render a 45-second cinematic short with Thai and English subtitles.",
    "I have a digital portrait of a young post-collapse Hanoi-Hoan-Kiem-Lake fisher — produce a 30-second piece with Vietnamese and French subtitles.",
    "Uploading a portrait of a young post-collapse Seoul-Gyeongbokgung-palace squatter — make a 1-minute mini-drama with Korean and English subtitles.",
    "Here's a sketch of a young post-collapse Pyongyang-Juche-Tower lookout — render a 45-second cinematic short with Korean and Russian subtitles.",
    "I'm sending you a digital painting of a young post-collapse Manila-Intramuros-walls sentinel — produce a 30-second piece with Tagalog and Spanish subtitles.",
    "Uploading a watercolor of a young post-collapse Jakarta-Monas-tower lookout — build a 1-minute mini-drama with Indonesian and English subtitles.",
    "Here's a portrait of a young post-collapse Singapore-Marina-Bay-Sands ruin-walker — render a 45-second cinematic short with English and Mandarin subtitles.",
    "I have a sketch of a young post-collapse Kuala-Lumpur-Petronas-Towers climber — produce a 30-second piece with Malay and English subtitles.",
    "Uploading a digital portrait of a young post-collapse Beijing-Tiananmen-Square wanderer — make a 1-minute mini-drama with Mandarin and English subtitles.",
    "Here's a watercolor of a young post-collapse Shanghai-Bund-Pudong-skyline lookout — render a 45-second cinematic short with Shanghainese and English subtitles.",
    # ── more superhero / fantasy / video-game cosplay scenes (50) ──
    "Uploading a digital painting of a Spider-Man-Miles-Morales cosplay-kid — make a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a sketch of a Spider-Man-Peter-Parker cosplay-kid — render a 45-second cinematic short with English and French subtitles.",
    "I'm sending you a portrait of a Wonder-Woman cosplay-kid — produce a 30-second piece with English and Italian subtitles.",
    "Uploading a digital portrait of a Captain-America cosplay-kid — build a 1-minute mini-drama with English and German subtitles.",
    "Here's a watercolor of a Black-Panther cosplay-kid — render a 45-second cinematic short with English and Xhosa subtitles.",
    "I have a digital painting of a Iron-Man cosplay-kid — produce a 30-second piece with English and Mandarin subtitles.",
    "Uploading a portrait of a Thor cosplay-kid — make a 1-minute mini-drama with English and Old-Norse subtitles.",
    "Here's a sketch of a Hulk cosplay-kid — render a 45-second cinematic short with English and Spanish subtitles.",
    "I'm sending you a digital painting of a Scarlet-Witch cosplay-kid — produce a 30-second piece with English and Sokovian subtitles.",
    "Uploading a watercolor of a Doctor-Strange cosplay-kid — build a 1-minute mini-drama with English and Tibetan subtitles.",
    "Here's a portrait of a Black-Widow cosplay-kid — render a 45-second cinematic short with English and Russian subtitles.",
    "I have a sketch of a Hawkeye cosplay-kid — produce a 30-second piece with English and Spanish subtitles.",
    "Uploading a digital portrait of a Star-Lord cosplay-kid — make a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a watercolor of a Gamora cosplay-kid — render a 45-second cinematic short with English and Korean subtitles.",
    "I'm sending you a digital painting of a Loki cosplay-kid — produce a 30-second piece with English and Old-Norse subtitles.",
    "Uploading a portrait of a Batman cosplay-kid — build a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a sketch of a Robin cosplay-kid — render a 45-second cinematic short with English and French subtitles.",
    "I have a digital painting of a Joker cosplay-kid — produce a 30-second piece with English and Italian subtitles.",
    "Uploading a watercolor of a Harley-Quinn cosplay-kid — make a 1-minute mini-drama with English and German subtitles.",
    "Here's a digital portrait of a Catwoman cosplay-kid — render a 45-second cinematic short with English and French subtitles.",
    "I'm sending you a portrait of a Aquaman cosplay-kid — produce a 30-second piece with English and Greek subtitles.",
    "Uploading a sketch of a Flash cosplay-kid — build a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a watercolor of a Cyborg cosplay-kid — render a 45-second cinematic short with English and Spanish subtitles.",
    "I have a digital portrait of a Green-Lantern cosplay-kid — produce a 30-second piece with English and French subtitles.",
    "Uploading a portrait of a Supergirl cosplay-kid — make a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a sketch of a Frodo-Baggins cosplay-kid — render a 45-second cinematic short with English and Sindarin subtitles.",
    "I'm sending you a digital painting of a Aragorn cosplay-kid — produce a 30-second piece with English and Quenya subtitles.",
    "Uploading a watercolor of a Legolas cosplay-kid — build a 1-minute mini-drama with English and Sindarin subtitles.",
    "Here's a portrait of a Gandalf-the-Grey cosplay-kid — render a 45-second cinematic short with English and Black-Speech subtitles.",
    "I have a sketch of a Daenerys-Targaryen cosplay-kid — produce a 30-second piece with English and Valyrian subtitles.",
    "Uploading a digital portrait of a Jon-Snow cosplay-kid — make a 1-minute mini-drama with English and Old-Tongue subtitles.",
    "Here's a watercolor of a Arya-Stark cosplay-kid — render a 45-second cinematic short with English and Braavosi subtitles.",
    "I'm sending you a digital painting of a Tyrion-Lannister cosplay-kid — produce a 30-second piece with English and Valyrian subtitles.",
    "Uploading a portrait of a Geralt-of-Rivia cosplay-kid — build a 1-minute mini-drama with English and Polish subtitles.",
    "Here's a sketch of a Yennefer cosplay-kid — render a 45-second cinematic short with English and Polish subtitles.",
    "I have a digital painting of a Ciri cosplay-kid — produce a 30-second piece with English and Polish subtitles.",
    "Uploading a watercolor of a Mario cosplay-kid — make a 1-minute mini-drama with English and Italian subtitles.",
    "Here's a digital portrait of a Princess-Peach cosplay-kid — render a 45-second cinematic short with English and Italian subtitles.",
    "I'm sending you a portrait of a Link-Hyrule cosplay-kid — produce a 30-second piece with English and Hylian subtitles.",
    "Uploading a sketch of a Zelda cosplay-kid — build a 1-minute mini-drama with English and Hylian subtitles.",
    "Here's a watercolor of a Master-Chief-Halo cosplay-kid — render a 45-second cinematic short with English and Spanish subtitles.",
    "I have a digital portrait of a Cortana-Halo cosplay-kid — produce a 30-second piece with English and Russian subtitles.",
    "Uploading a portrait of a Lara-Croft cosplay-kid — make a 1-minute mini-drama with English and French subtitles.",
    "Here's a sketch of a Solid-Snake cosplay-kid — render a 45-second cinematic short with English and Russian subtitles.",
    "I'm sending you a digital painting of a Cloud-Strife cosplay-kid — produce a 30-second piece with English and Japanese subtitles.",
    "Uploading a watercolor of a Tifa-Lockhart cosplay-kid — build a 1-minute mini-drama with English and Japanese subtitles.",
    "Here's a portrait of a Sora-Kingdom-Hearts cosplay-kid — render a 45-second cinematic short with English and Japanese subtitles.",
    "I have a sketch of a Pikachu cosplay-kid — produce a 30-second piece with English and Japanese subtitles.",
    "Uploading a digital portrait of a Ash-Ketchum cosplay-kid — make a 1-minute mini-drama with English and Japanese subtitles.",
    "Here's a watercolor of a Sailor-Moon cosplay-kid — render a 45-second cinematic short with English and Japanese subtitles.",
    # ── more vintage-decade Halloween costumes (50) ──
    "I'm sending you a portrait of a 1950s-Halloween Casper-the-Friendly-Ghost bedsheet-costume kid — produce a 30-second piece with English and French subtitles.",
    "Uploading a watercolor of a 1950s-Halloween Roy-Rogers cowboy-costume kid — make a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a digital painting of a 1950s-Halloween Davy-Crockett coonskin-cap kid — render a 45-second cinematic short with English and German subtitles.",
    "I have a sketch of a 1950s-Halloween Howdy-Doody marionette-costume kid — produce a 30-second piece with English and Italian subtitles.",
    "Uploading a portrait of a 1950s-Halloween Lone-Ranger masked-costume kid — build a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a watercolor of a 1950s-Halloween Mickey-Mouse-Club Mouseketeer-costume kid — render a 45-second cinematic short with English and French subtitles.",
    "I'm sending you a digital portrait of a 1950s-Halloween Lucy-Ricardo polka-dot-dress costume kid — produce a 30-second piece with English and Spanish subtitles.",
    "Uploading a sketch of a 1950s-Halloween Zorro mask-and-cape costume kid — make a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a portrait of a 1960s-Halloween Batman-1966 Adam-West costume kid — render a 45-second cinematic short with English and Japanese subtitles.",
    "I have a watercolor of a 1960s-Halloween Robin-Burt-Ward sidekick-costume kid — produce a 30-second piece with English and Italian subtitles.",
    "Uploading a digital painting of a 1960s-Halloween Bewitched-Samantha costume kid — make a 1-minute mini-drama with English and German subtitles.",
    "Here's a sketch of a 1960s-Halloween Jeannie-I-Dream-of-Jeannie costume kid — render a 45-second cinematic short with English and Arabic subtitles.",
    "I'm sending you a portrait of a 1960s-Halloween Munster-Family-Lily costume kid — produce a 30-second piece with English and German subtitles.",
    "Uploading a watercolor of a 1960s-Halloween Addams-Family-Wednesday costume kid — build a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a digital portrait of a 1960s-Halloween Star-Trek-Mr-Spock costume kid — render a 45-second cinematic short with English and Klingon subtitles.",
    "I have a sketch of a 1960s-Halloween Beatles-Yellow-Submarine costume kid — produce a 30-second piece with English and Liverpool-dialect subtitles.",
    "Uploading a portrait of a 1970s-Halloween Charlie's-Angels-Farrah-Fawcett costume kid — make a 1-minute mini-drama with English and French subtitles.",
    "Here's a watercolor of a 1970s-Halloween Six-Million-Dollar-Man costume kid — render a 45-second cinematic short with English and German subtitles.",
    "I'm sending you a digital painting of a 1970s-Halloween Bionic-Woman costume kid — produce a 30-second piece with English and Italian subtitles.",
    "Uploading a sketch of a 1970s-Halloween Wonder-Woman-Lynda-Carter costume kid — make a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a portrait of a 1970s-Halloween Star-Wars-Luke-Skywalker costume kid — render a 45-second cinematic short with English and Tatooine-Huttese subtitles.",
    "I have a watercolor of a 1970s-Halloween Star-Wars-Princess-Leia costume kid — produce a 30-second piece with English and Alderaan-Basic subtitles.",
    "Uploading a digital portrait of a 1970s-Halloween Fonzie-Happy-Days leather-jacket costume kid — make a 1-minute mini-drama with English and Italian subtitles.",
    "Here's a sketch of a 1970s-Halloween Saturday-Night-Fever-Tony-Manero costume kid — render a 45-second cinematic short with English and Italian subtitles.",
    "I'm sending you a portrait of a 1970s-Halloween Kiss-Gene-Simmons costume kid — produce a 30-second piece with English and German subtitles.",
    "Uploading a watercolor of a 1980s-Halloween E.T.-the-Extra-Terrestrial costume kid — build a 1-minute mini-drama with English and Spanish subtitles.",
    "Here's a digital painting of a 1980s-Halloween Indiana-Jones-Raiders costume kid — render a 45-second cinematic short with English and Arabic subtitles.",
    "I have a sketch of a 1980s-Halloween Ghostbusters-proton-pack costume kid — produce a 30-second piece with English and French subtitles.",
    "Uploading a portrait of a 1980s-Halloween Slimer-Ghostbusters-mascot costume kid — make a 1-minute mini-drama with English and Italian subtitles.",
    "Here's a watercolor of a 1980s-Halloween He-Man-Masters-of-the-Universe costume kid — render a 45-second cinematic short with English and Eternian subtitles.",
    "I'm sending you a digital portrait of a 1980s-Halloween She-Ra-Princess-of-Power costume kid — produce a 30-second piece with English and Etherian subtitles.",
    "Uploading a sketch of a 1980s-Halloween Care-Bears-Cheer-Bear costume kid — make a 1-minute mini-drama with English and German subtitles.",
    "Here's a portrait of a 1980s-Halloween Strawberry-Shortcake costume kid — render a 45-second cinematic short with English and French subtitles.",
    "I have a watercolor of a 1980s-Halloween Rainbow-Brite costume kid — produce a 30-second piece with English and Spanish subtitles.",
    "Uploading a digital painting of a 1980s-Halloween Punky-Brewster mismatched-outfit costume kid — make a 1-minute mini-drama with English and Italian subtitles.",
    "Here's a sketch of a 1980s-Halloween Pee-wee-Herman-Playhouse costume kid — render a 45-second cinematic short with English and French subtitles.",
    "I'm sending you a portrait of a 1990s-Halloween Power-Rangers-Red-Ranger costume kid — produce a 30-second piece with English and Japanese subtitles.",
    "Uploading a watercolor of a 1990s-Halloween Power-Rangers-Pink-Ranger costume kid — build a 1-minute mini-drama with English and Japanese subtitles.",
    "Here's a digital portrait of a 1990s-Halloween Teenage-Mutant-Ninja-Turtles-Leonardo costume kid — render a 45-second cinematic short with English and Italian subtitles.",
    "I have a sketch of a 1990s-Halloween Rugrats-Tommy-Pickles costume kid — produce a 30-second piece with English and Russian subtitles.",
    "Uploading a portrait of a 1990s-Halloween Hey-Arnold-football-head costume kid — make a 1-minute mini-drama with English and Brooklyn-dialect subtitles.",
    "Here's a watercolor of a 1990s-Halloween Doug-Funnie costume kid — render a 45-second cinematic short with English and Bluffington-dialect subtitles.",
    "I'm sending you a digital painting of a 1990s-Halloween Beetlejuice-stripe-suit costume kid — produce a 30-second piece with English and German subtitles.",
    "Uploading a sketch of a 1990s-Halloween Edward-Scissorhands costume kid — make a 1-minute mini-drama with English and German subtitles.",
    "Here's a portrait of a 1990s-Halloween Spice-Girls-Scary-Spice costume kid — render a 45-second cinematic short with English and Spanish subtitles.",
    "I have a watercolor of a 1990s-Halloween Spice-Girls-Sporty-Spice costume kid — produce a 30-second piece with English and Italian subtitles.",
    "Uploading a digital portrait of a 1990s-Halloween Britney-Spears-schoolgirl costume kid — make a 1-minute mini-drama with English and French subtitles.",
    "Here's a sketch of a 1990s-Halloween Britney-Spears-red-jumpsuit costume kid — render a 45-second cinematic short with English and Korean subtitles.",
    "I'm sending you a portrait of a 1990s-Halloween N-Sync-Justin-Timberlake-frosted-tips costume kid — produce a 30-second piece with English and Russian subtitles.",
    "Uploading a watercolor of a 1990s-Halloween Backstreet-Boys-AJ-McLean costume kid — build a 1-minute mini-drama with English and Italian subtitles.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
