"""x15 extend_subtitle GRPO short briefs. Disjoint from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 30-second physician-explainer clip — please extend to 90 seconds and add English subtitles.",
    "Here's a 45-second nutritionist-tip video — extend to 2 minutes and overlay English captions.",
    "I have a 1-minute legal-counsel explainer — please extend to 3 minutes and add English subtitles.",
    "Uploading a 30-second tax-attorney clip — extend to 90 seconds and overlay English captions.",
    "Here's a 45-second estate-planning tip — please extend to 2 minutes and add English subtitles.",
    "I'm sending you a 30-second insurance-policy walkthrough — extend to 90 seconds and overlay English captions.",
    "Uploading a 1-minute mortgage-advisor video — please extend to 3 minutes and add English subtitles.",
    "Here's a 45-second financial-planner advice — extend to 2 minutes and overlay English captions.",
    "I have a 30-second retirement-planning clip — please extend to 90 seconds and add English subtitles.",
    "Uploading a 1-minute will-drafting walkthrough — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second debt-consolidation overview — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second credit-score explainer — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute compound-interest tutorial — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second index-fund explainer — extend to 90 seconds and overlay English captions.",
    "I have a 45-second small-business-launch tip — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute LLC-formation walkthrough — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second small-business taxes video — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second marketing-strategy clip — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute SEO-best-practices video — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second content-marketing tip — extend to 90 seconds and overlay English captions.",
    "I have a 45-second social-media-strategy video — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute Pinterest-growth video — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second Instagram-reels strategy — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second YouTube-monetization video — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute TikTok-algorithm tip — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second newsletter-launch tip — extend to 90 seconds and overlay English captions.",
    "I have a 45-second podcast-startup tip — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute affiliate-marketing tip — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second productized-service tip — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second SaaS-pricing explainer — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute customer-acquisition tip — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second sales-funnel walkthrough — extend to 90 seconds and overlay English captions.",
    "I have a 45-second cold-email-template explainer — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute LinkedIn-outreach tutorial — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second hiring-best-practices clip — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second remote-team management tip — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute async-communication explainer — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second time-management tutorial — extend to 90 seconds and overlay English captions.",
    "I have a 45-second deep-work productivity tip — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute Pomodoro-method explainer — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second habit-formation tutorial — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second morning-routine tip — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute sleep-optimization tutorial — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second mindfulness-meditation guide — extend to 90 seconds and overlay English captions.",
    "I have a 45-second breathwork tutorial — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute sound-bath session explainer — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second stretching-routine tip — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second mobility-drill tutorial — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute hip-flexor stretching explainer — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second lower-back-pain relief tutorial — extend to 90 seconds and overlay English captions.",
    # ── more upload + extend + subtitle requests (50) ─────────────────────
    "Uploading a 30-second knee-rehab tutorial — please extend to 90 seconds and add English subtitles.",
    "Here's a 45-second shoulder-rehab tutorial — extend to 2 minutes and overlay English captions.",
    "I have a 1-minute Achilles-rehab tutorial — please extend to 3 minutes and add English subtitles.",
    "Uploading a 30-second plantar-fasciitis rehab — extend to 90 seconds and overlay English captions.",
    "Here's a 45-second IT-band rehab — please extend to 2 minutes and add English subtitles.",
    "I'm sending you a 30-second tennis-elbow rehab — extend to 90 seconds and overlay English captions.",
    "Uploading a 1-minute golfer's-elbow rehab — please extend to 3 minutes and add English subtitles.",
    "Here's a 45-second carpal-tunnel rehab — extend to 2 minutes and overlay English captions.",
    "I have a 30-second trigger-point self-massage — please extend to 90 seconds and add English subtitles.",
    "Uploading a 1-minute foam-rolling routine — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second lacrosse-ball-massage tutorial — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second theragun-routine — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute cupping-therapy tutorial — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second kinesio-tape tutorial — extend to 90 seconds and overlay English captions.",
    "I have a 45-second dry-needling explainer — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute acupuncture-tutorial — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second tai-chi tutorial — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second qigong tutorial — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute mindful-walking tutorial — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second loving-kindness meditation — extend to 90 seconds and overlay English captions.",
    "I have a 45-second body-scan meditation — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute mantra-meditation — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second zen-meditation — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second vipassana-meditation — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute transcendental-meditation explainer — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second breath-counting meditation — extend to 90 seconds and overlay English captions.",
    "I have a 45-second candle-gazing meditation — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute sound-bath tutorial — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second Tibetan-singing-bowl tutorial — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second crystal-bowl tutorial — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute strength-training tutorial — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second kettlebell-clean-and-jerk tutorial — extend to 90 seconds and overlay English captions.",
    "I have a 45-second squat-form tutorial — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute deadlift-form tutorial — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second bench-press-form tutorial — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second overhead-press tutorial — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute olympic-lifting tutorial — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second pull-up form tutorial — extend to 90 seconds and overlay English captions.",
    "I have a 45-second push-up form tutorial — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute plank-variation tutorial — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second core-stability tutorial — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second glute-activation tutorial — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute hip-mobility tutorial — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second thoracic-mobility tutorial — extend to 90 seconds and overlay English captions.",
    "I have a 45-second ankle-mobility tutorial — please extend to 2 minutes and add English subtitles.",
    "Uploading a 1-minute wrist-mobility tutorial — extend to 3 minutes and overlay English captions.",
    "Here's a 30-second shoulder-mobility tutorial — please extend to 90 seconds and add English subtitles.",
    "I'm sending you a 45-second neck-mobility tutorial — extend to 2 minutes and overlay English captions.",
    "Uploading a 1-minute lower-back-mobility tutorial — please extend to 3 minutes and add English subtitles.",
    "Here's a 30-second upper-back-mobility tutorial — extend to 90 seconds and overlay English captions.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
