"""x15 extend_ambience GRPO. Disjoint from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 30-second backyard-bonfire family clip — extend to 90 seconds and overlay crackling-fire ambience.",
    "Here's a 45-second porch-rocking-chair reel — extend to 2 minutes and add porch-breeze ambience.",
    "I have a 1-minute farm-life reel — extend to 3 minutes and overlay rooster-and-cowbell ambience.",
    "Uploading a 30-second snowy-village reel — extend to 90 seconds and add winter-wind-and-bell ambience.",
    "Here's a 45-second beach-shore reel — extend to 2 minutes and overlay tide-pool-and-gull ambience.",
    "I'm sending you a 30-second mountain-trail reel — extend to 90 seconds and add mountain-bird ambience.",
    "Uploading a 1-minute autumn-leaves reel — extend to 3 minutes and overlay autumn-leaf-rustle ambience.",
    "Here's a 45-second backyard-pool reel — extend to 2 minutes and add lapping-water ambience.",
    "I have a 30-second desert-dune reel — extend to 90 seconds and overlay sand-hiss ambience.",
    "Uploading a 1-minute jungle-canopy reel — extend to 3 minutes and add rainforest-bird ambience.",
    "Here's a 45-second carnival-ride reel — extend to 2 minutes and overlay carnival-crowd ambience.",
    "I'm sending you a 30-second orchestra-rehearsal reel — extend to 90 seconds and add concert-hall hush ambience.",
    "Uploading a 1-minute street-musician reel — extend to 3 minutes and overlay street-traffic ambience.",
    "Here's a 30-second moss-rock reel — extend to 90 seconds and add forest-drip ambience.",
    "I have a 45-second canoe-still-lake reel — extend to 2 minutes and overlay loon-call ambience.",
    "Uploading a 1-minute salt-flat reel — extend to 3 minutes and add salt-flat wind ambience.",
    "Here's a 30-second tea-garden reel — extend to 90 seconds and overlay water-and-bird ambience.",
    "I'm sending you a 45-second floating-market reel — extend to 2 minutes and add market-chatter ambience.",
    "Uploading a 1-minute monastic-courtyard reel — extend to 3 minutes and overlay distant-bell ambience.",
    "Here's a 30-second deep-sea reel — extend to 90 seconds and add underwater-bubble ambience.",
    "I have a 45-second bird-feeder reel — extend to 2 minutes and overlay backyard-bird ambience.",
    "Uploading a 1-minute botanical-garden reel — extend to 3 minutes and add garden-bee ambience.",
    "Here's a 30-second insect-close-up reel — extend to 90 seconds and overlay garden-cricket ambience.",
    "I'm sending you a 45-second farmhouse-kitchen reel — extend to 2 minutes and add kitchen-stovetop ambience.",
    "Uploading a 1-minute baker-shop reel — extend to 3 minutes and overlay bakery-oven ambience.",
    "Here's a 30-second bookshelf reel — extend to 90 seconds and add quiet-library ambience.",
    "I have a 45-second herb-garden reel — extend to 2 minutes and overlay garden-bee ambience.",
    "Uploading a 1-minute rooftop-garden reel — extend to 3 minutes and add city-rooftop ambience.",
    "Here's a 30-second pottery-studio reel — extend to 90 seconds and overlay studio-wheel ambience.",
    "I'm sending you a 45-second jewelry-display reel — extend to 2 minutes and add quiet-shop ambience.",
    "Uploading a 1-minute leatherwork reel — extend to 3 minutes and overlay leather-tooling ambience.",
    "Here's a 30-second cobbler-shop reel — extend to 90 seconds and add cobbler-shop ambience.",
    "I have a 45-second saddle-shop reel — extend to 2 minutes and overlay leather-and-creak ambience.",
    "Uploading a 1-minute bow-maker reel — extend to 3 minutes and add workshop-quiet ambience.",
    "Here's a 30-second carving-shop reel — extend to 90 seconds and add wood-shaving ambience.",
    # ── more upload + extend + ambience requests (50) ──────────────────
    "Uploading a 30-second ice-skating rink reel — extend to 90 seconds and add ice-skate-glide ambience.",
    "Here's a 45-second tennis-court rally reel — extend to 2 minutes and overlay tennis-bounce ambience.",
    "I have a 1-minute fire-station tour reel — extend to 3 minutes and add siren-radio ambience.",
    "Uploading a 30-second taxi-ride night reel — extend to 90 seconds and overlay taxi-meter ambience.",
    "Here's a 45-second amusement-park midway reel — extend to 2 minutes and add midway-crowd ambience.",
    "I'm sending you a 30-second ferris-wheel reel — extend to 90 seconds and overlay ferris-wheel-creak ambience.",
    "Uploading a 1-minute roller-coaster pov reel — extend to 3 minutes and add coaster-rattle ambience.",
    "Here's a 45-second carousel ride reel — extend to 2 minutes and overlay carousel-organ ambience.",
    "I have a 30-second kindergarten classroom reel — extend to 90 seconds and add kindergarten-chatter ambience.",
    "Uploading a 1-minute school-playground reel — extend to 3 minutes and overlay playground-laughter ambience.",
    "Here's a 30-second library-stacks reel — extend to 90 seconds and add library-quiet ambience.",
    "I'm sending you a 45-second art-museum gallery reel — extend to 2 minutes and overlay museum-quiet ambience.",
    "Uploading a 1-minute concert-hall foyer reel — extend to 3 minutes and add foyer-murmur ambience.",
    "Here's a 30-second opera-house corridor reel — extend to 90 seconds and overlay opera-distant-aria ambience.",
    "I have a 45-second cinema-lobby walk reel — extend to 2 minutes and add cinema-lobby ambience.",
    "Uploading a 1-minute record-shop browse reel — extend to 3 minutes and overlay vinyl-store ambience.",
    "Here's a 30-second brewery floor reel — extend to 90 seconds and add brewery-machinery ambience.",
    "I'm sending you a 45-second distillery tour reel — extend to 2 minutes and overlay still-rumble ambience.",
    "Uploading a 1-minute winery harvest reel — extend to 3 minutes and add winery-harvest ambience.",
    "Here's a 30-second cheesemaker walkthrough reel — extend to 90 seconds and overlay cheese-cellar ambience.",
    "I have a 45-second butcher-shop walkthrough reel — extend to 2 minutes and add butcher-shop ambience.",
    "Uploading a 1-minute fishmonger market reel — extend to 3 minutes and overlay fishmonger-ice ambience.",
    "Here's a 30-second spice-market walkthrough reel — extend to 90 seconds and add spice-market ambience.",
    "I'm sending you a 45-second tea-merchant walkthrough reel — extend to 2 minutes and overlay tea-pour ambience.",
    "Uploading a 1-minute coffee-roastery reel — extend to 3 minutes and add coffee-roaster ambience.",
    "Here's a 30-second chocolate-shop reel — extend to 90 seconds and overlay chocolatier-counter ambience.",
    "I have a 45-second ice-cream-parlor reel — extend to 2 minutes and add ice-cream-scoop ambience.",
    "Uploading a 1-minute soda-fountain reel — extend to 3 minutes and overlay soda-fountain-fizz ambience.",
    "Here's a 30-second milkshake-bar reel — extend to 90 seconds and add milkshake-blender ambience.",
    "I'm sending you a 45-second donut-shop reel — extend to 2 minutes and overlay donut-fryer ambience.",
    "Uploading a 1-minute cupcake-shop reel — extend to 3 minutes and add cupcake-counter ambience.",
    "Here's a 30-second macaron-shop reel — extend to 90 seconds and overlay macaron-counter ambience.",
    "I have a 45-second patisserie-window reel — extend to 2 minutes and add patisserie-counter ambience.",
    "Uploading a 1-minute boulangerie-morning reel — extend to 3 minutes and overlay boulangerie-oven ambience.",
    "Here's a 30-second fromagerie-tasting reel — extend to 90 seconds and add fromagerie-counter ambience.",
    "I'm sending you a 45-second charcuterie-tasting reel — extend to 2 minutes and overlay charcuterie-counter ambience.",
    "Uploading a 1-minute pizzeria-Naples reel — extend to 3 minutes and add pizzeria-oven ambience.",
    "Here's a 30-second trattoria-Florence reel — extend to 90 seconds and overlay trattoria-clatter ambience.",
    "I have a 45-second osteria-Bologna reel — extend to 2 minutes and add osteria-clatter ambience.",
    "Uploading a 1-minute enoteca-Rome reel — extend to 3 minutes and overlay enoteca-quiet ambience.",
    "Here's a 30-second gelateria-Milan reel — extend to 90 seconds and add gelateria-counter ambience.",
    "I'm sending you a 45-second caffè-Trieste reel — extend to 2 minutes and overlay caffè-bustle ambience.",
    "Uploading a 1-minute brasserie-Paris reel — extend to 3 minutes and add brasserie-Paris ambience.",
    "Here's a 30-second taverna-Athens reel — extend to 90 seconds and overlay taverna-clatter ambience.",
    "I have a 45-second pub-Edinburgh reel — extend to 2 minutes and add pub-Edinburgh ambience.",
    "Uploading a 1-minute cantina-Madrid reel — extend to 3 minutes and overlay cantina-Madrid ambience.",
    "Here's a 30-second izakaya-Tokyo reel — extend to 90 seconds and add izakaya-clatter ambience.",
    "I'm sending you a 45-second real-estate walkthrough — extend to 2 minutes and overlay empty-room ambience.",
    "Uploading a 1-minute car-review reel — extend to 3 minutes and add car-engine ambience.",
    "Here's a 30-second drone-footage clip — extend to 90 seconds and overlay drone-buzz ambience.",
    # ── more upload + extend + ambience requests (50) ──────────────────
    "Uploading a 30-second movie-theater reel — extend to 90 seconds and add movie-theater-quiet ambience.",
    "Here's a 45-second theater-stage rehearsal reel — extend to 2 minutes and overlay theater-rustle ambience.",
    "I have a 1-minute orchestra-pit reel — extend to 3 minutes and add orchestra-tuning ambience.",
    "Uploading a 30-second backstage dressing-room reel — extend to 90 seconds and overlay dressing-room ambience.",
    "Here's a 45-second costume-shop reel — extend to 2 minutes and add costume-rustle ambience.",
    "I'm sending you a 30-second wig-shop reel — extend to 90 seconds and overlay wig-shop ambience.",
    "Uploading a 1-minute magic-shop reel — extend to 3 minutes and add magic-trick-quiet ambience.",
    "Here's a 45-second occult-bookstore reel — extend to 2 minutes and overlay occult-quiet ambience.",
    "I have a 30-second tarot-reading-room reel — extend to 90 seconds and add candle-flame ambience.",
    "Uploading a 1-minute crystal-ball-shop reel — extend to 3 minutes and overlay crystal-shop ambience.",
    "Here's a 30-second herbalist-apothecary reel — extend to 90 seconds and add apothecary-bottle ambience.",
    "I'm sending you a 45-second mortuary-coffin-maker reel — extend to 2 minutes and overlay workshop-quiet ambience.",
    "Uploading a 1-minute taxidermy-shop reel — extend to 3 minutes and add shop-quiet ambience.",
    "Here's a 30-second natural-history-museum reel — extend to 90 seconds and overlay museum-echo ambience.",
    "I have a 45-second planetarium-projection reel — extend to 2 minutes and add planetarium-quiet ambience.",
    "Uploading a 1-minute observatory-dome reel — extend to 3 minutes and overlay telescope-mechanism ambience.",
    "Here's a 30-second radio-tower-summit reel — extend to 90 seconds and add radio-static ambience.",
    "I'm sending you a 45-second weather-station reel — extend to 2 minutes and overlay wind-anemometer ambience.",
    "Uploading a 1-minute lighthouse-keeper reel — extend to 3 minutes and add lighthouse-fog-horn ambience.",
    "Here's a 30-second control-tower air-traffic reel — extend to 90 seconds and overlay control-tower ambience.",
    "I have a 45-second submarine-bridge reel — extend to 2 minutes and add submarine-sonar ambience.",
    "Uploading a 1-minute bridge-engine-room reel — extend to 3 minutes and overlay engine-rumble ambience.",
    "Here's a 30-second cargo-hold reel — extend to 90 seconds and add cargo-creak ambience.",
    "I'm sending you a 45-second shipyard-dry-dock reel — extend to 2 minutes and overlay shipyard-clang ambience.",
    "Uploading a 1-minute oil-rig-deck reel — extend to 3 minutes and add oil-rig ambience.",
    "Here's a 30-second wind-farm-turbine reel — extend to 90 seconds and overlay turbine-hum ambience.",
    "I have a 45-second solar-farm-array reel — extend to 2 minutes and add solar-farm-hum ambience.",
    "Uploading a 1-minute nuclear-cooling-tower reel — extend to 3 minutes and overlay cooling-tower-hum ambience.",
    "Here's a 30-second coal-power-plant reel — extend to 90 seconds and add power-plant-turbine-hum ambience.",
    "I'm sending you a 45-second hydroelectric-dam reel — extend to 2 minutes and overlay dam-water ambience.",
    "Uploading a 1-minute desalination-plant reel — extend to 3 minutes and add pump-hum ambience.",
    "Here's a 30-second recycling-center reel — extend to 90 seconds and overlay conveyor ambience.",
    "I have a 45-second sewage-treatment reel — extend to 2 minutes and add treatment-pump-hum ambience.",
    "Uploading a 1-minute mushroom-farm reel — extend to 3 minutes and overlay mushroom-house ambience.",
    "Here's a 30-second greenhouse-tomatoes reel — extend to 90 seconds and add greenhouse-bee ambience.",
    "I'm sending you a 45-second greenhouse-orchid reel — extend to 2 minutes and overlay greenhouse-quiet ambience.",
    "Uploading a 1-minute vivarium-reptile reel — extend to 3 minutes and add vivarium-quiet ambience.",
    "Here's a 30-second butterfly-house reel — extend to 90 seconds and overlay butterfly-house ambience.",
    "I have a 45-second aquarium-shark-tank reel — extend to 2 minutes and add aquarium-bubble ambience.",
    "Uploading a 1-minute dolphinarium-pool reel — extend to 3 minutes and overlay dolphin-tank ambience.",
    "Here's a 30-second seal-rehab-pool reel — extend to 90 seconds and add seal-tank ambience.",
    "I'm sending you a 45-second bird-aviary reel — extend to 2 minutes and overlay aviary-chatter ambience.",
    "Uploading a 1-minute bat-cave-rehab reel — extend to 3 minutes and add bat-cave ambience.",
    "Here's a 30-second wildlife-rehab-center reel — extend to 90 seconds and overlay wildlife-shelter ambience.",
    "I have a 45-second animal-hospital reel — extend to 2 minutes and add clinic-quiet ambience.",
    "Uploading a 1-minute veterinary-clinic reel — extend to 3 minutes and overlay vet-clinic-quiet ambience.",
    "Here's a 30-second dog-shelter reel — extend to 90 seconds and add shelter-bark ambience.",
    "I'm sending you a 45-second cat-shelter reel — extend to 2 minutes and overlay shelter-purr ambience.",
    "Uploading a 1-minute horse-stable reel — extend to 3 minutes and add horse-stable ambience.",
    "Here's a 30-second cattle-barn reel — extend to 90 seconds and overlay barn-bellow ambience.",
    # ── more industrial / urban-work / factory reels (50) ──
    "I have a 30-second steel-mill reel — extend to 90 seconds and add steel-mill ambience.",
    "I'm sending you a 45-second copper-smelter reel — extend to 2 minutes and overlay smelter ambience.",
    "Uploading a 1-minute aluminum-rolling-mill reel — extend to 3 minutes and add rolling-mill ambience.",
    "Here's a 30-second auto-assembly-line reel — extend to 90 seconds and overlay assembly-line ambience.",
    "I have a 45-second car-paint-shop reel — extend to 2 minutes and add paint-booth ambience.",
    "I'm sending you a 1-minute bus-factory reel — extend to 3 minutes and overlay bus-assembly ambience.",
    "Uploading a 30-second train-rolling-stock factory reel — extend to 90 seconds and add train-factory ambience.",
    "Here's a 45-second locomotive-shed reel — extend to 2 minutes and overlay locomotive-shed ambience.",
    "I have a 1-minute aircraft-hangar reel — extend to 3 minutes and add aircraft-hangar ambience.",
    "I'm sending you a 30-second shipyard reel — extend to 90 seconds and overlay shipyard ambience.",
    "Uploading a 45-second dry-dock reel — extend to 2 minutes and add dry-dock ambience.",
    "Here's a 1-minute container-port reel — extend to 3 minutes and overlay container-crane ambience.",
    "I have a 30-second oil-refinery reel — extend to 90 seconds and add refinery ambience.",
    "I'm sending you a 45-second LNG-terminal reel — extend to 2 minutes and overlay LNG-terminal ambience.",
    "Uploading a 1-minute power-plant reel — extend to 3 minutes and add turbine-hall ambience.",
    "Here's a 30-second hydro-dam reel — extend to 90 seconds and overlay hydro-spillway ambience.",
    "I have a 45-second wind-farm reel — extend to 2 minutes and add wind-turbine ambience.",
    "I'm sending you a 1-minute solar-farm reel — extend to 3 minutes and overlay solar-array ambience.",
    "Uploading a 30-second nuclear-control-room reel — extend to 90 seconds and add control-room ambience.",
    "Here's a 45-second water-treatment-plant reel — extend to 2 minutes and overlay treatment-plant ambience.",
    "I have a 1-minute desalination-plant reel — extend to 3 minutes and add desalination ambience.",
    "I'm sending you a 30-second sewage-treatment reel — extend to 90 seconds and overlay treatment-pump ambience.",
    "Uploading a 45-second textile-mill reel — extend to 2 minutes and add textile-loom ambience.",
    "Here's a 1-minute paper-mill reel — extend to 3 minutes and overlay paper-mill ambience.",
    "I have a 30-second logging-camp reel — extend to 90 seconds and add logging-camp ambience.",
    "I'm sending you a 45-second sawmill reel — extend to 2 minutes and overlay sawmill ambience.",
    "Uploading a 1-minute brewery-bottling reel — extend to 3 minutes and add bottling-line ambience.",
    "Here's a 30-second winery-fermenter reel — extend to 90 seconds and overlay fermenter-tank ambience.",
    "I have a 45-second distillery-still reel — extend to 2 minutes and add distillery ambience.",
    "I'm sending you a 1-minute cider-press reel — extend to 3 minutes and overlay cider-press ambience.",
    "Uploading a 30-second cheese-cave reel — extend to 90 seconds and add cheese-cave ambience.",
    "Here's a 45-second salt-flat-2 reel — extend to 2 minutes and overlay salt-flat-2 ambience.",
    "I have a 1-minute ice-house reel — extend to 3 minutes and add ice-house ambience.",
    "I'm sending you a 30-second bakery-oven reel — extend to 90 seconds and overlay bakery-kitchen ambience.",
    "Uploading a 45-second pasta-factory reel — extend to 2 minutes and add pasta-line ambience.",
    "Here's a 1-minute candy-factory reel — extend to 3 minutes and overlay candy-line ambience.",
    "I have a 30-second chocolate-conching reel — extend to 90 seconds and add chocolate-factory ambience.",
    "I'm sending you a 45-second tea-factory reel — extend to 2 minutes and overlay tea-rolling ambience.",
    "Uploading a 1-minute coffee-roaster reel — extend to 3 minutes and add coffee-roaster ambience.",
    "Here's a 30-second mushroom-farm reel — extend to 90 seconds and overlay mushroom-farm ambience.",
    "I have a 45-second hydroponic-farm reel — extend to 2 minutes and add hydroponic-farm ambience.",
    "I'm sending you a 1-minute greenhouse-tomato reel — extend to 3 minutes and overlay greenhouse-fan ambience.",
    "Uploading a 30-second silk-factory reel — extend to 90 seconds and add silk-loom ambience.",
    "Here's a 45-second carpet-loom reel — extend to 2 minutes and overlay carpet-loom ambience.",
    "I have a 1-minute glass-bottle factory reel — extend to 3 minutes and add glass-factory ambience.",
    "I'm sending you a 30-second tile-kiln reel — extend to 90 seconds and overlay tile-kiln ambience.",
    "Uploading a 45-second ceramics-factory reel — extend to 2 minutes and add ceramics-line ambience.",
    "Here's a 1-minute cement-plant reel — extend to 3 minutes and overlay cement-mill ambience.",
    "I have a 30-second quarry reel — extend to 90 seconds and add quarry-blast ambience.",
    "I'm sending you a 45-second open-pit-mine reel — extend to 2 minutes and overlay mine-haul-truck ambience.",
    # ── more medical / lab / clean-room / scientific facilities (50) ──
    "Uploading a 30-second operating-theatre reel — extend to 90 seconds and add operating-theatre ambience.",
    "Here's a 45-second hospital-ICU reel — extend to 2 minutes and overlay ICU-monitor ambience.",
    "I have a 1-minute pediatric-ward reel — extend to 3 minutes and add pediatric-ward ambience.",
    "I'm sending you a 30-second neonatal-incubator reel — extend to 90 seconds and overlay incubator-hum ambience.",
    "Uploading a 45-second emergency-room-triage reel — extend to 2 minutes and add ER-triage ambience.",
    "Here's a 1-minute MRI-scanner room reel — extend to 3 minutes and overlay MRI-scanner ambience.",
    "I have a 30-second CT-scanner room reel — extend to 90 seconds and add CT-scanner ambience.",
    "I'm sending you a 45-second PET-scanner room reel — extend to 2 minutes and overlay PET-scanner ambience.",
    "Uploading a 1-minute proton-therapy bunker reel — extend to 3 minutes and add proton-therapy ambience.",
    "Here's a 30-second linear-accelerator reel — extend to 90 seconds and overlay linac-room ambience.",
    "I have a 45-second nuclear-medicine reel — extend to 2 minutes and add nuclear-medicine-quiet ambience.",
    "I'm sending you a 1-minute pathology-lab reel — extend to 3 minutes and overlay pathology-lab ambience.",
    "Uploading a 30-second microbiology-lab reel — extend to 90 seconds and add microbiology-lab ambience.",
    "Here's a 45-second virology-BSL3 reel — extend to 2 minutes and overlay BSL3-airlock ambience.",
    "I have a 1-minute biosafety-BSL4 reel — extend to 3 minutes and add BSL4-suit-room ambience.",
    "I'm sending you a 30-second cytology-lab reel — extend to 90 seconds and overlay cytology-microscope ambience.",
    "Uploading a 45-second hematology-lab reel — extend to 2 minutes and add hematology-analyzer ambience.",
    "Here's a 1-minute clinical-chemistry-lab reel — extend to 3 minutes and overlay chemistry-analyzer ambience.",
    "I have a 30-second molecular-diagnostics reel — extend to 90 seconds and add PCR-thermocycler ambience.",
    "I'm sending you a 45-second sequencing-core reel — extend to 2 minutes and overlay sequencer-fan ambience.",
    "Uploading a 1-minute mass-spectrometry-core reel — extend to 3 minutes and add mass-spec-vacuum-pump ambience.",
    "Here's a 30-second NMR-spectrometer-core reel — extend to 90 seconds and overlay NMR-helium-fill ambience.",
    "I have a 45-second X-ray-crystallography-core reel — extend to 2 minutes and add X-ray-crystallography ambience.",
    "I'm sending you a 1-minute electron-microscopy-suite reel — extend to 3 minutes and overlay EM-suite ambience.",
    "Uploading a 30-second cryo-EM-room reel — extend to 90 seconds and add cryo-EM-cold-room ambience.",
    "Here's a 45-second confocal-microscopy-suite reel — extend to 2 minutes and overlay confocal-suite ambience.",
    "I have a 1-minute super-resolution-microscopy-suite reel — extend to 3 minutes and add super-res-suite ambience.",
    "I'm sending you a 30-second fly-genetics-stockroom reel — extend to 90 seconds and overlay fly-stockroom ambience.",
    "Uploading a 45-second mouse-vivarium reel — extend to 2 minutes and add mouse-vivarium ambience.",
    "Here's a 1-minute zebrafish-aquatics reel — extend to 3 minutes and overlay zebrafish-aquatics ambience.",
    "I have a 30-second tissue-culture-hood reel — extend to 90 seconds and add tissue-culture-hood ambience.",
    "I'm sending you a 45-second flow-cytometry-suite reel — extend to 2 minutes and overlay flow-cytometer ambience.",
    "Uploading a 1-minute organoid-culture-suite reel — extend to 3 minutes and add organoid-suite ambience.",
    "Here's a 30-second stem-cell-bank reel — extend to 90 seconds and overlay stem-cell-bank ambience.",
    "I have a 45-second blood-bank reel — extend to 2 minutes and add blood-bank ambience.",
    "I'm sending you a 1-minute cord-blood-storage reel — extend to 3 minutes and overlay cord-blood-cryo ambience.",
    "Uploading a 30-second cryostorage-LN2-tank reel — extend to 90 seconds and add LN2-tank ambience.",
    "Here's a 45-second pharmacy-compounding-cleanroom reel — extend to 2 minutes and overlay compounding-hood ambience.",
    "I have a 1-minute IV-drug-mix-cleanroom reel — extend to 3 minutes and add IV-cleanroom ambience.",
    "I'm sending you a 30-second pharmaceutical-cGMP-cleanroom reel — extend to 90 seconds and overlay cGMP-cleanroom ambience.",
    "Uploading a 45-second semiconductor-fab-cleanroom reel — extend to 2 minutes and add semiconductor-fab ambience.",
    "Here's a 1-minute photolithography-bay reel — extend to 3 minutes and overlay photolithography ambience.",
    "I have a 30-second wafer-test-floor reel — extend to 90 seconds and add wafer-test ambience.",
    "I'm sending you a 45-second optical-bench-room reel — extend to 2 minutes and overlay optical-bench ambience.",
    "Uploading a 1-minute laser-physics-lab reel — extend to 3 minutes and add laser-lab ambience.",
    "Here's a 30-second cold-atom-physics-lab reel — extend to 90 seconds and overlay cold-atom-lab ambience.",
    "I have a 45-second neutrino-detector-tank reel — extend to 2 minutes and add neutrino-detector ambience.",
    "I'm sending you a 1-minute particle-accelerator-tunnel reel — extend to 3 minutes and overlay accelerator-tunnel ambience.",
    "Uploading a 30-second telescope-control-room reel — extend to 90 seconds and add observatory-control ambience.",
    "Here's a 45-second astronaut-ISS-module reel — extend to 2 minutes and overlay ISS-module ambience.",
    # ── more world airport/airfield/runway reels + airport ambience (50) ──
    "Uploading a 30-second JFK-Terminal-4 reel — extend to 90 seconds and add JFK-T4-concourse ambience.",
    "Here's a 45-second LAX-Tom-Bradley-terminal reel — extend to 2 minutes and overlay LAX-TBIT-concourse ambience.",
    "I have a 1-minute SFO-International-terminal reel — extend to 3 minutes and add SFO-international-concourse ambience.",
    "I'm sending you a 30-second Chicago-O'Hare-Terminal-3 reel — extend to 90 seconds and overlay O'Hare-T3-concourse ambience.",
    "Uploading a 45-second Atlanta-Hartsfield-Jackson reel — extend to 2 minutes and add ATL-concourse-T ambience.",
    "Here's a 1-minute Dallas-Fort-Worth-Terminal-D reel — extend to 3 minutes and overlay DFW-TD-concourse ambience.",
    "I have a 30-second Miami-International-Concourse-D reel — extend to 90 seconds and add MIA-concourse-D ambience.",
    "Uploading a 45-second Denver-International-Concourse-B reel — extend to 2 minutes and overlay DEN-concourse-B ambience.",
    "Here's a 1-minute Seattle-Tacoma-N-concourse reel — extend to 3 minutes and add SEA-N-concourse ambience.",
    "I'm sending you a 30-second Boston-Logan-Terminal-E reel — extend to 90 seconds and overlay BOS-TE-concourse ambience.",
    "Uploading a 45-second Toronto-Pearson-Terminal-1 reel — extend to 2 minutes and add YYZ-T1-concourse ambience.",
    "Here's a 1-minute Mexico-City-Benito-Juárez-T2 reel — extend to 3 minutes and overlay MEX-T2-concourse ambience.",
    "I have a 30-second London-Heathrow-Terminal-5 reel — extend to 90 seconds and add LHR-T5-concourse ambience.",
    "I'm sending you a 45-second London-Heathrow-Terminal-2 reel — extend to 2 minutes and overlay LHR-T2-concourse ambience.",
    "Uploading a 1-minute Paris-Charles-de-Gaulle-Terminal-2E reel — extend to 3 minutes and add CDG-T2E-concourse ambience.",
    "Here's a 30-second Frankfurt-Airport-Terminal-1 reel — extend to 90 seconds and overlay FRA-T1-concourse ambience.",
    "I have a 45-second Munich-Airport-Terminal-2 reel — extend to 2 minutes and add MUC-T2-concourse ambience.",
    "Uploading a 1-minute Amsterdam-Schiphol-departure-hall reel — extend to 3 minutes and overlay Schiphol-departure-hall ambience.",
    "Here's a 30-second Zurich-Airport-Dock-B reel — extend to 90 seconds and add ZRH-Dock-B-concourse ambience.",
    "I'm sending you a 45-second Vienna-Airport-Terminal-3 reel — extend to 2 minutes and overlay VIE-T3-concourse ambience.",
    "Uploading a 1-minute Copenhagen-Airport-Terminal-3 reel — extend to 3 minutes and add CPH-T3-concourse ambience.",
    "Here's a 30-second Stockholm-Arlanda-Terminal-5 reel — extend to 90 seconds and overlay ARN-T5-concourse ambience.",
    "I have a 45-second Helsinki-Vantaa-Terminal-2 reel — extend to 2 minutes and add HEL-T2-concourse ambience.",
    "I'm sending you a 1-minute Oslo-Gardermoen-departure reel — extend to 3 minutes and overlay OSL-departure-concourse ambience.",
    "Uploading a 30-second Madrid-Barajas-Terminal-4 reel — extend to 90 seconds and add MAD-T4-concourse ambience.",
    "Here's a 45-second Barcelona-El-Prat-Terminal-1 reel — extend to 2 minutes and overlay BCN-T1-concourse ambience.",
    "I have a 1-minute Lisbon-Humberto-Delgado-Terminal-1 reel — extend to 3 minutes and add LIS-T1-concourse ambience.",
    "Uploading a 30-second Rome-Fiumicino-Terminal-3 reel — extend to 90 seconds and overlay FCO-T3-concourse ambience.",
    "Here's a 45-second Milan-Malpensa-Terminal-1 reel — extend to 2 minutes and add MXP-T1-concourse ambience.",
    "I'm sending you a 1-minute Athens-Eleftherios-Venizelos reel — extend to 3 minutes and overlay ATH-concourse ambience.",
    "Uploading a 30-second Istanbul-IST-airport reel — extend to 90 seconds and add IST-concourse ambience.",
    "Here's a 45-second Dubai-DXB-Terminal-3 reel — extend to 2 minutes and overlay DXB-T3-concourse ambience.",
    "I have a 1-minute Doha-Hamad-International reel — extend to 3 minutes and add DOH-concourse ambience.",
    "I'm sending you a 30-second Abu-Dhabi-AUH-Terminal-3 reel — extend to 90 seconds and overlay AUH-T3-concourse ambience.",
    "Uploading a 45-second Cairo-CAI-Terminal-3 reel — extend to 2 minutes and add CAI-T3-concourse ambience.",
    "Here's a 1-minute Johannesburg-OR-Tambo reel — extend to 3 minutes and overlay JNB-concourse ambience.",
    "I have a 30-second Cape-Town-CPT-airport reel — extend to 90 seconds and add CPT-concourse ambience.",
    "Uploading a 45-second Mumbai-Chhatrapati-Shivaji-T2 reel — extend to 2 minutes and overlay BOM-T2-concourse ambience.",
    "Here's a 1-minute Delhi-Indira-Gandhi-T3 reel — extend to 3 minutes and add DEL-T3-concourse ambience.",
    "I'm sending you a 30-second Bangkok-Suvarnabhumi reel — extend to 90 seconds and overlay BKK-concourse ambience.",
    "Uploading a 45-second Singapore-Changi-Terminal-3 reel — extend to 2 minutes and add SIN-T3-concourse ambience.",
    "Here's a 1-minute Singapore-Changi-Jewel reel — extend to 3 minutes and overlay Changi-Jewel-atrium ambience.",
    "I have a 30-second Hong-Kong-HKG-Terminal-1 reel — extend to 90 seconds and add HKG-T1-concourse ambience.",
    "I'm sending you a 45-second Tokyo-Haneda-Terminal-3 reel — extend to 2 minutes and overlay HND-T3-concourse ambience.",
    "Uploading a 1-minute Tokyo-Narita-Terminal-1 reel — extend to 3 minutes and add NRT-T1-concourse ambience.",
    "Here's a 30-second Seoul-Incheon-Terminal-2 reel — extend to 90 seconds and overlay ICN-T2-concourse ambience.",
    "I have a 45-second Beijing-Capital-Terminal-3 reel — extend to 2 minutes and add PEK-T3-concourse ambience.",
    "Uploading a 1-minute Shanghai-Pudong-Terminal-2 reel — extend to 3 minutes and overlay PVG-T2-concourse ambience.",
    "Here's a 30-second Sydney-Kingsford-Smith-T1 reel — extend to 90 seconds and add SYD-T1-concourse ambience.",
    "I'm sending you a 45-second Auckland-AKL-international reel — extend to 2 minutes and overlay AKL-international-concourse ambience.",
    # ── more world stadium / sports-arena reels + arena ambience (50) ──
    "Uploading a 30-second Wembley-Stadium-London reel — extend to 90 seconds and add Wembley-Stadium-bowl ambience.",
    "Here's a 45-second Old-Trafford-Manchester reel — extend to 2 minutes and overlay Old-Trafford-bowl ambience.",
    "I have a 1-minute Anfield-Liverpool reel — extend to 3 minutes and add Anfield-Kop-stand ambience.",
    "Uploading a 30-second Stamford-Bridge-London reel — extend to 90 seconds and overlay Stamford-Bridge-bowl ambience.",
    "Here's a 45-second Emirates-Stadium-London reel — extend to 2 minutes and add Emirates-Stadium-bowl ambience.",
    "I'm sending you a 1-minute Tottenham-Hotspur-Stadium reel — extend to 3 minutes and overlay Tottenham-Hotspur-Stadium-bowl ambience.",
    "Uploading a 30-second Camp-Nou-Barcelona reel — extend to 90 seconds and add Camp-Nou-bowl ambience.",
    "Here's a 45-second Santiago-Bernabéu-Madrid reel — extend to 2 minutes and overlay Santiago-Bernabéu-bowl ambience.",
    "I have a 1-minute Wanda-Metropolitano-Madrid reel — extend to 3 minutes and add Wanda-Metropolitano-bowl ambience.",
    "Uploading a 30-second Allianz-Arena-Munich reel — extend to 90 seconds and overlay Allianz-Arena-bowl ambience.",
    "Here's a 45-second Signal-Iduna-Park-Dortmund reel — extend to 2 minutes and add Signal-Iduna-Park-Yellow-Wall ambience.",
    "I'm sending you a 1-minute Olympiastadion-Berlin reel — extend to 3 minutes and overlay Olympiastadion-Berlin-bowl ambience.",
    "Uploading a 30-second San-Siro-Milan reel — extend to 90 seconds and add San-Siro-bowl ambience.",
    "Here's a 45-second Stadio-Olimpico-Rome reel — extend to 2 minutes and overlay Stadio-Olimpico-Roma ambience.",
    "I have a 1-minute Stade-de-France-Paris reel — extend to 3 minutes and add Stade-de-France-bowl ambience.",
    "Uploading a 30-second Parc-des-Princes-Paris reel — extend to 90 seconds and overlay Parc-des-Princes-bowl ambience.",
    "Here's a 45-second Vélodrome-Marseille reel — extend to 2 minutes and add Vélodrome-Marseille-bowl ambience.",
    "I'm sending you a 1-minute Johan-Cruyff-Arena-Amsterdam reel — extend to 3 minutes and overlay Johan-Cruyff-Arena-bowl ambience.",
    "Uploading a 30-second De-Kuip-Rotterdam reel — extend to 90 seconds and add De-Kuip-bowl ambience.",
    "Here's a 45-second Estádio-da-Luz-Lisbon reel — extend to 2 minutes and overlay Estádio-da-Luz-bowl ambience.",
    "I have a 1-minute Estádio-do-Dragão-Porto reel — extend to 3 minutes and add Estádio-do-Dragão-bowl ambience.",
    "Uploading a 30-second Estadio-Azteca-Mexico-City reel — extend to 90 seconds and overlay Estadio-Azteca-bowl ambience.",
    "Here's a 45-second Maracanã-Rio-de-Janeiro reel — extend to 2 minutes and add Maracanã-bowl ambience.",
    "I'm sending you a 1-minute La-Bombonera-Buenos-Aires reel — extend to 3 minutes and overlay La-Bombonera-bowl ambience.",
    "Uploading a 30-second Estadio-Monumental-Buenos-Aires reel — extend to 90 seconds and add Estadio-Monumental-bowl ambience.",
    "Here's a 45-second Estadio-Centenario-Montevideo reel — extend to 2 minutes and overlay Estadio-Centenario-bowl ambience.",
    "I have a 1-minute MetLife-Stadium-New-Jersey reel — extend to 3 minutes and add MetLife-Stadium-bowl ambience.",
    "Uploading a 30-second SoFi-Stadium-Los-Angeles reel — extend to 90 seconds and overlay SoFi-Stadium-bowl ambience.",
    "Here's a 45-second AT&T-Stadium-Arlington reel — extend to 2 minutes and add AT&T-Stadium-bowl ambience.",
    "I'm sending you a 1-minute Mercedes-Benz-Stadium-Atlanta reel — extend to 3 minutes and overlay Mercedes-Benz-Stadium-bowl ambience.",
    "Uploading a 30-second Allegiant-Stadium-Las-Vegas reel — extend to 90 seconds and add Allegiant-Stadium-bowl ambience.",
    "Here's a 45-second Hard-Rock-Stadium-Miami reel — extend to 2 minutes and overlay Hard-Rock-Stadium-bowl ambience.",
    "I have a 1-minute Lambeau-Field-Green-Bay reel — extend to 3 minutes and add Lambeau-Field-bowl ambience.",
    "Uploading a 30-second Soldier-Field-Chicago reel — extend to 90 seconds and overlay Soldier-Field-bowl ambience.",
    "Here's a 45-second Madison-Square-Garden-NYC reel — extend to 2 minutes and add Madison-Square-Garden-bowl ambience.",
    "I'm sending you a 1-minute Crypto.com-Arena-Los-Angeles reel — extend to 3 minutes and overlay Crypto.com-Arena-bowl ambience.",
    "Uploading a 30-second TD-Garden-Boston reel — extend to 90 seconds and add TD-Garden-bowl ambience.",
    "Here's a 45-second United-Center-Chicago reel — extend to 2 minutes and overlay United-Center-bowl ambience.",
    "I have a 1-minute Fenway-Park-Boston reel — extend to 3 minutes and add Fenway-Park-Green-Monster ambience.",
    "Uploading a 30-second Wrigley-Field-Chicago reel — extend to 90 seconds and overlay Wrigley-Field-Bleachers ambience.",
    "Here's a 45-second Yankee-Stadium-NYC reel — extend to 2 minutes and add Yankee-Stadium-bowl ambience.",
    "I'm sending you a 1-minute Dodger-Stadium-LA reel — extend to 3 minutes and overlay Dodger-Stadium-bowl ambience.",
    "Uploading a 30-second Tokyo-National-Stadium reel — extend to 90 seconds and add Tokyo-National-Stadium-bowl ambience.",
    "Here's a 45-second Tokyo-Dome reel — extend to 2 minutes and overlay Tokyo-Dome-bowl ambience.",
    "I have a 1-minute Saitama-Super-Arena reel — extend to 3 minutes and add Saitama-Super-Arena-bowl ambience.",
    "Uploading a 30-second Beijing-National-Stadium-Bird's-Nest reel — extend to 90 seconds and overlay Bird's-Nest-bowl ambience.",
    "Here's a 45-second Shanghai-Stadium reel — extend to 2 minutes and add Shanghai-Stadium-bowl ambience.",
    "I'm sending you a 1-minute Hong-Kong-Stadium reel — extend to 3 minutes and overlay Hong-Kong-Stadium-bowl ambience.",
    "Uploading a 30-second Singapore-National-Stadium reel — extend to 90 seconds and add Singapore-National-Stadium-bowl ambience.",
    "Here's a 45-second Sydney-Cricket-Ground reel — extend to 2 minutes and overlay Sydney-Cricket-Ground-bowl ambience.",
    # ── more world traditional-market / souk / bazaar interior reels + market ambience (50) ──
    "Uploading a 30-second Istanbul-Grand-Bazaar reel — extend to 90 seconds and add Grand-Bazaar-vault ambience.",
    "Here's a 45-second Istanbul-Spice-Bazaar reel — extend to 2 minutes and overlay Spice-Bazaar-Misir-Carsisi ambience.",
    "I have a 1-minute Marrakesh-Jemaa-el-Fnaa-souk reel — extend to 3 minutes and add Jemaa-el-Fnaa-souk ambience.",
    "Uploading a 30-second Fes-Medina-Tannery reel — extend to 90 seconds and overlay Fes-Medina-Tannery ambience.",
    "Here's a 45-second Cairo-Khan-el-Khalili-souk reel — extend to 2 minutes and add Khan-el-Khalili-souk ambience.",
    "I'm sending you a 1-minute Damascus-Souk-al-Hamidiyya reel — extend to 3 minutes and overlay Souk-al-Hamidiyya ambience.",
    "Uploading a 30-second Aleppo-Souk-al-Madina reel — extend to 90 seconds and add Souk-al-Madina-Aleppo ambience.",
    "Here's a 45-second Tunis-Medina-Souk reel — extend to 2 minutes and overlay Tunis-Medina-Souk ambience.",
    "I have a 1-minute Tehran-Grand-Bazaar reel — extend to 3 minutes and add Tehran-Grand-Bazaar ambience.",
    "Uploading a 30-second Isfahan-Bazar-e-Bozorg reel — extend to 90 seconds and overlay Isfahan-Bazar-e-Bozorg ambience.",
    "Here's a 45-second Tabriz-Bazaar reel — extend to 2 minutes and add Tabriz-Bazaar ambience.",
    "I'm sending you a 1-minute Shiraz-Vakil-Bazaar reel — extend to 3 minutes and overlay Vakil-Bazaar-Shiraz ambience.",
    "Uploading a 30-second Bukhara-Trading-Domes reel — extend to 90 seconds and add Bukhara-Trading-Domes ambience.",
    "Here's a 45-second Samarkand-Siab-Bazaar reel — extend to 2 minutes and overlay Samarkand-Siab-Bazaar ambience.",
    "I have a 1-minute Khiva-Itchan-Kala-bazaar reel — extend to 3 minutes and add Khiva-Itchan-Kala-bazaar ambience.",
    "Uploading a 30-second Kashgar-Sunday-Bazaar reel — extend to 90 seconds and overlay Kashgar-Sunday-Bazaar ambience.",
    "Here's a 45-second Beijing-Panjiayuan-antique-market reel — extend to 2 minutes and add Beijing-Panjiayuan-antique-market ambience.",
    "I'm sending you a 1-minute Shanghai-Yu-Garden-Bazaar reel — extend to 3 minutes and overlay Shanghai-Yu-Garden-Bazaar ambience.",
    "Uploading a 30-second Hong-Kong-Temple-Street-Night-Market reel — extend to 90 seconds and add Temple-Street-Night-Market ambience.",
    "Here's a 45-second Hong-Kong-Ladies-Market-Mong-Kok reel — extend to 2 minutes and overlay Ladies-Market-Mong-Kok ambience.",
    "I have a 1-minute Macau-Red-Market reel — extend to 3 minutes and add Macau-Red-Market ambience.",
    "Uploading a 30-second Bangkok-Chatuchak-Weekend-Market reel — extend to 90 seconds and overlay Chatuchak-Weekend-Market ambience.",
    "Here's a 45-second Bangkok-Damnoen-Saduak-Floating-Market reel — extend to 2 minutes and add Damnoen-Saduak-Floating-Market ambience.",
    "I'm sending you a 1-minute Hanoi-Dong-Xuan-Market reel — extend to 3 minutes and overlay Dong-Xuan-Market-Hanoi ambience.",
    "Uploading a 30-second Ho-Chi-Minh-Ben-Thanh-Market reel — extend to 90 seconds and add Ben-Thanh-Market-HCMC ambience.",
    "Here's a 45-second Phnom-Penh-Central-Market reel — extend to 2 minutes and overlay Phsar-Thmei-Central-Market ambience.",
    "I have a 1-minute Yangon-Bogyoke-Aung-San-Market reel — extend to 3 minutes and add Bogyoke-Aung-San-Market-Yangon ambience.",
    "Uploading a 30-second Kuala-Lumpur-Central-Market reel — extend to 90 seconds and overlay KL-Central-Market ambience.",
    "Here's a 45-second Singapore-Tekka-Centre reel — extend to 2 minutes and add Singapore-Tekka-Centre ambience.",
    "I'm sending you a 1-minute Jakarta-Pasar-Baru reel — extend to 3 minutes and overlay Jakarta-Pasar-Baru ambience.",
    "Uploading a 30-second Manila-Divisoria-Market reel — extend to 90 seconds and add Manila-Divisoria-Market ambience.",
    "Here's a 45-second Tokyo-Tsukiji-Outer-Market reel — extend to 2 minutes and overlay Tsukiji-Outer-Market-Tokyo ambience.",
    "I have a 1-minute Tokyo-Ameyoko-Ueno reel — extend to 3 minutes and add Ameyoko-Ueno-Tokyo ambience.",
    "Uploading a 30-second Kyoto-Nishiki-Market reel — extend to 90 seconds and overlay Nishiki-Market-Kyoto ambience.",
    "Here's a 45-second Osaka-Kuromon-Ichiba reel — extend to 2 minutes and add Kuromon-Ichiba-Osaka ambience.",
    "I'm sending you a 1-minute Seoul-Gwangjang-Market reel — extend to 3 minutes and overlay Gwangjang-Market-Seoul ambience.",
    "Uploading a 30-second Seoul-Namdaemun-Market reel — extend to 90 seconds and add Namdaemun-Market-Seoul ambience.",
    "Here's a 45-second Mumbai-Crawford-Market reel — extend to 2 minutes and overlay Crawford-Market-Mumbai ambience.",
    "I have a 1-minute Delhi-Chandni-Chowk-Bazaar reel — extend to 3 minutes and add Chandni-Chowk-Bazaar ambience.",
    "Uploading a 30-second Jaipur-Bapu-Bazaar reel — extend to 90 seconds and overlay Jaipur-Bapu-Bazaar ambience.",
    "Here's a 45-second Mexico-City-Mercado-de-la-Merced reel — extend to 2 minutes and add Mercado-de-la-Merced-Mexico-City ambience.",
    "I'm sending you a 1-minute Mexico-City-Mercado-Roma reel — extend to 3 minutes and overlay Mercado-Roma-Mexico-City ambience.",
    "Uploading a 30-second Oaxaca-Mercado-de-Abastos reel — extend to 90 seconds and add Oaxaca-Mercado-de-Abastos ambience.",
    "Here's a 45-second Lima-Mercado-de-Surquillo reel — extend to 2 minutes and overlay Lima-Mercado-de-Surquillo ambience.",
    "I have a 1-minute Cuzco-San-Pedro-Market reel — extend to 3 minutes and add San-Pedro-Market-Cuzco ambience.",
    "Uploading a 30-second La-Paz-Mercado-de-las-Brujas reel — extend to 90 seconds and overlay La-Paz-Mercado-de-las-Brujas ambience.",
    "Here's a 45-second Buenos-Aires-Mercado-San-Telmo reel — extend to 2 minutes and add Mercado-San-Telmo-Buenos-Aires ambience.",
    "I'm sending you a 1-minute São-Paulo-Mercado-Municipal reel — extend to 3 minutes and overlay Mercado-Municipal-São-Paulo ambience.",
    "Uploading a 30-second Rio-Feira-de-São-Cristóvão reel — extend to 90 seconds and add Feira-de-São-Cristóvão-Rio ambience.",
    "Here's a 45-second Cartagena-Mercado-de-Bazurto reel — extend to 2 minutes and overlay Mercado-de-Bazurto-Cartagena ambience.",
    # ── more amusement parks + theme parks (50) ──
    "I'm sending you a 30-second Disneyland-Anaheim-Main-Street reel — extend to 90 seconds and add Disneyland-Anaheim-Main-Street ambience.",
    "Uploading a 1-minute Disneyland-Anaheim-Adventureland reel — extend to 3 minutes and overlay Disneyland-Anaheim-Adventureland ambience.",
    "Here's a 45-second Disneyland-Anaheim-Tomorrowland reel — extend to 2 minutes and add Disneyland-Anaheim-Tomorrowland ambience.",
    "I have a 30-second Disney-California-Adventure-Cars-Land reel — extend to 90 seconds and overlay Disney-California-Cars-Land ambience.",
    "Uploading a 1-minute Magic-Kingdom-Orlando-Cinderella-Castle-plaza reel — extend to 3 minutes and add Magic-Kingdom-Cinderella-Castle-plaza ambience.",
    "Here's a 45-second Magic-Kingdom-Orlando-Frontierland reel — extend to 2 minutes and overlay Magic-Kingdom-Frontierland ambience.",
    "I'm sending you a 30-second EPCOT-Orlando-Spaceship-Earth reel — extend to 90 seconds and add EPCOT-Spaceship-Earth-plaza ambience.",
    "Uploading a 1-minute EPCOT-Orlando-World-Showcase-promenade reel — extend to 3 minutes and overlay EPCOT-World-Showcase-promenade ambience.",
    "Here's a 45-second Disney's-Hollywood-Studios-Galaxy's-Edge reel — extend to 2 minutes and add Hollywood-Studios-Galaxy's-Edge ambience.",
    "I have a 30-second Disney's-Animal-Kingdom-Pandora reel — extend to 90 seconds and overlay Animal-Kingdom-Pandora ambience.",
    "Uploading a 1-minute Universal-Studios-Hollywood-backlot-tour reel — extend to 3 minutes and add Universal-Studios-Hollywood-backlot-tour ambience.",
    "Here's a 45-second Universal-Studios-Orlando-Diagon-Alley reel — extend to 2 minutes and overlay Universal-Orlando-Diagon-Alley ambience.",
    "I'm sending you a 30-second Universal's-Islands-of-Adventure-Hogsmeade reel — extend to 90 seconds and add Islands-of-Adventure-Hogsmeade ambience.",
    "Uploading a 1-minute SeaWorld-Orlando-Mako-coaster-plaza reel — extend to 3 minutes and overlay SeaWorld-Orlando-Mako-plaza ambience.",
    "Here's a 45-second Busch-Gardens-Tampa-Serengeti-Plain reel — extend to 2 minutes and add Busch-Gardens-Tampa-Serengeti-Plain ambience.",
    "I have a 30-second Cedar-Point-Sandusky-Millennium-Force-queue reel — extend to 90 seconds and overlay Cedar-Point-Millennium-Force-queue ambience.",
    "Uploading a 1-minute Six-Flags-Magic-Mountain-Valencia-Wonder-Woman-plaza reel — extend to 3 minutes and add Six-Flags-Magic-Mountain-Wonder-Woman-plaza ambience.",
    "Here's a 45-second Six-Flags-Great-Adventure-Jackson-Kingda-Ka-plaza reel — extend to 2 minutes and overlay Six-Flags-Great-Adventure-Kingda-Ka-plaza ambience.",
    "I'm sending you a 30-second Knott's-Berry-Farm-Buena-Park-Ghost-Town reel — extend to 90 seconds and add Knott's-Berry-Farm-Ghost-Town ambience.",
    "Uploading a 1-minute Hersheypark-Pennsylvania-Chocolatetown reel — extend to 3 minutes and overlay Hersheypark-Chocolatetown ambience.",
    "Here's a 45-second Dollywood-Pigeon-Forge-Showstreet reel — extend to 2 minutes and add Dollywood-Showstreet ambience.",
    "I have a 30-second Kings-Island-Mason-International-Street reel — extend to 90 seconds and overlay Kings-Island-International-Street ambience.",
    "Uploading a 1-minute Carowinds-Charlotte-Carolina-Boardwalk reel — extend to 3 minutes and add Carowinds-Carolina-Boardwalk ambience.",
    "Here's a 45-second Tokyo-Disneyland-World-Bazaar reel — extend to 2 minutes and overlay Tokyo-Disneyland-World-Bazaar ambience.",
    "I'm sending you a 30-second Tokyo-DisneySea-Mediterranean-Harbor reel — extend to 90 seconds and add Tokyo-DisneySea-Mediterranean-Harbor ambience.",
    "Uploading a 1-minute Universal-Studios-Japan-Wizarding-World reel — extend to 3 minutes and overlay Universal-Studios-Japan-Wizarding-World ambience.",
    "Here's a 45-second Fuji-Q-Highland-Yamanashi-Eejanaika-plaza reel — extend to 2 minutes and add Fuji-Q-Highland-Eejanaika-plaza ambience.",
    "I have a 30-second Hong-Kong-Disneyland-Main-Street reel — extend to 90 seconds and overlay Hong-Kong-Disneyland-Main-Street ambience.",
    "Uploading a 1-minute Hong-Kong-Ocean-Park-Aqua-City reel — extend to 3 minutes and add Hong-Kong-Ocean-Park-Aqua-City ambience.",
    "Here's a 45-second Shanghai-Disneyland-Mickey-Avenue reel — extend to 2 minutes and overlay Shanghai-Disneyland-Mickey-Avenue ambience.",
    "I'm sending you a 30-second Shanghai-Disneyland-Treasure-Cove reel — extend to 90 seconds and add Shanghai-Disneyland-Treasure-Cove ambience.",
    "Uploading a 1-minute Beijing-Universal-Studios-Hollywood-Boulevard reel — extend to 3 minutes and overlay Beijing-Universal-Hollywood-Boulevard ambience.",
    "Here's a 45-second Chimelong-Ocean-Kingdom-Zhuhai-Whale-Shark-Aquarium-plaza reel — extend to 2 minutes and add Chimelong-Ocean-Kingdom-plaza ambience.",
    "I have a 30-second Lotte-World-Seoul-Adventure-plaza reel — extend to 90 seconds and overlay Lotte-World-Seoul-Adventure-plaza ambience.",
    "Uploading a 1-minute Everland-Yongin-Magic-Land reel — extend to 3 minutes and add Everland-Yongin-Magic-Land ambience.",
    "Here's a 45-second Universal-Studios-Singapore-Hollywood-zone reel — extend to 2 minutes and overlay Universal-Studios-Singapore-Hollywood-zone ambience.",
    "I'm sending you a 30-second Disneyland-Paris-Main-Street-USA reel — extend to 90 seconds and add Disneyland-Paris-Main-Street-USA ambience.",
    "Uploading a 1-minute Disneyland-Paris-Adventureland reel — extend to 3 minutes and overlay Disneyland-Paris-Adventureland ambience.",
    "Here's a 45-second Walt-Disney-Studios-Park-Paris-Avenue-Studios reel — extend to 2 minutes and add Walt-Disney-Studios-Paris-Avenue-Studios ambience.",
    "I have a 30-second Parc-Astérix-Paris-village-Gaulois reel — extend to 90 seconds and overlay Parc-Astérix-village-Gaulois ambience.",
    "Uploading a 1-minute Europa-Park-Rust-Italian-quarter reel — extend to 3 minutes and add Europa-Park-Italian-quarter ambience.",
    "Here's a 45-second Phantasialand-Brühl-Berlin-quarter reel — extend to 2 minutes and overlay Phantasialand-Berlin-quarter ambience.",
    "I'm sending you a 30-second Heide-Park-Soltau-Pirates-Bay reel — extend to 90 seconds and add Heide-Park-Pirates-Bay ambience.",
    "Uploading a 1-minute Tivoli-Gardens-Copenhagen-main-promenade reel — extend to 3 minutes and overlay Tivoli-Gardens-main-promenade ambience.",
    "Here's a 45-second Liseberg-Gothenburg-Balder-coaster-plaza reel — extend to 2 minutes and add Liseberg-Balder-coaster-plaza ambience.",
    "I have a 30-second Linnanmäki-Helsinki-Vuoristorata-plaza reel — extend to 90 seconds and overlay Linnanmäki-Vuoristorata-plaza ambience.",
    "Uploading a 1-minute Gröna-Lund-Stockholm-Insane-coaster-plaza reel — extend to 3 minutes and add Gröna-Lund-Insane-coaster-plaza ambience.",
    "Here's a 45-second Alton-Towers-Staffordshire-Towers-Gardens reel — extend to 2 minutes and overlay Alton-Towers-Towers-Gardens ambience.",
    "I'm sending you a 30-second Thorpe-Park-Surrey-Stealth-coaster-plaza reel — extend to 90 seconds and add Thorpe-Park-Stealth-coaster-plaza ambience.",
    "Uploading a 1-minute Blackpool-Pleasure-Beach-Big-One-coaster-plaza reel — extend to 3 minutes and overlay Blackpool-Pleasure-Beach-Big-One-plaza ambience.",
    # ── more beach resorts (50) ──
    "Here's a 45-second Maldives-Conrad-Rangali-overwater-villa reel — extend to 2 minutes and add Conrad-Rangali-overwater-villa ambience.",
    "I have a 30-second Maldives-Soneva-Fushi-beach-villa reel — extend to 90 seconds and overlay Soneva-Fushi-beach-villa ambience.",
    "Uploading a 1-minute Bora-Bora-Four-Seasons-overwater-villa reel — extend to 3 minutes and add Bora-Bora-Four-Seasons-overwater-villa ambience.",
    "Here's a 45-second Bora-Bora-St-Regis-Lagoon-Villa reel — extend to 2 minutes and overlay Bora-Bora-St-Regis-Lagoon-Villa ambience.",
    "I'm sending you a 30-second Tahiti-Brando-private-island reel — extend to 90 seconds and add Tahiti-Brando-private-island ambience.",
    "Uploading a 1-minute Fiji-Laucala-Island-resort reel — extend to 3 minutes and overlay Fiji-Laucala-Island-resort ambience.",
    "Here's a 45-second Bali-Ayana-Resort-Jimbaran reel — extend to 2 minutes and add Bali-Ayana-Resort-Jimbaran ambience.",
    "I have a 30-second Bali-Bulgari-Uluwatu-cliffside reel — extend to 90 seconds and overlay Bali-Bulgari-Uluwatu-cliffside ambience.",
    "Uploading a 1-minute Bali-Mulia-Nusa-Dua reel — extend to 3 minutes and add Bali-Mulia-Nusa-Dua ambience.",
    "Here's a 45-second Phuket-Amanpuri-resort reel — extend to 2 minutes and overlay Phuket-Amanpuri-resort ambience.",
    "I'm sending you a 30-second Phuket-Trisara-Layan-Beach reel — extend to 90 seconds and add Phuket-Trisara-Layan-Beach ambience.",
    "Uploading a 1-minute Koh-Samui-Six-Senses-Yao-Noi reel — extend to 3 minutes and overlay Koh-Samui-Six-Senses-Yao-Noi ambience.",
    "Here's a 45-second Krabi-Rayavadee-Phra-Nang-Beach reel — extend to 2 minutes and add Krabi-Rayavadee-Phra-Nang-Beach ambience.",
    "I have a 30-second Maldives-Velassaru-overwater-bungalow reel — extend to 90 seconds and overlay Maldives-Velassaru-overwater-bungalow ambience.",
    "Uploading a 1-minute Mauritius-One-Only-Le-Saint-Géran reel — extend to 3 minutes and add Mauritius-One-Only-Le-Saint-Géran ambience.",
    "Here's a 45-second Seychelles-North-Island-resort reel — extend to 2 minutes and overlay Seychelles-North-Island-resort ambience.",
    "I'm sending you a 30-second Zanzibar-Mnemba-Island-Lodge reel — extend to 90 seconds and add Zanzibar-Mnemba-Island-Lodge ambience.",
    "Uploading a 1-minute Mozambique-Vamizi-Island reel — extend to 3 minutes and overlay Mozambique-Vamizi-Island ambience.",
    "Here's a 45-second Cape-Town-Cape-Grace-V-A-Waterfront reel — extend to 2 minutes and add Cape-Town-Cape-Grace-V-A-Waterfront ambience.",
    "I have a 30-second Costa-Rica-Four-Seasons-Peninsula-Papagayo reel — extend to 90 seconds and overlay Costa-Rica-Four-Seasons-Peninsula-Papagayo ambience.",
    "Uploading a 1-minute Tulum-Azulik-cliffside reel — extend to 3 minutes and add Tulum-Azulik-cliffside ambience.",
    "Here's a 45-second Cancun-Rosewood-Mayakoba reel — extend to 2 minutes and overlay Cancun-Rosewood-Mayakoba ambience.",
    "I'm sending you a 30-second Riviera-Maya-Banyan-Tree reel — extend to 90 seconds and add Riviera-Maya-Banyan-Tree ambience.",
    "Uploading a 1-minute Punta-Cana-Tortuga-Bay-Puntacana reel — extend to 3 minutes and overlay Punta-Cana-Tortuga-Bay-Puntacana ambience.",
    "Here's a 45-second Saint-Barths-Cheval-Blanc-Isle-de-France reel — extend to 2 minutes and add Saint-Barths-Cheval-Blanc-Isle-de-France ambience.",
    "I have a 30-second Anguilla-Belmond-Cap-Juluca reel — extend to 90 seconds and overlay Anguilla-Belmond-Cap-Juluca ambience.",
    "Uploading a 1-minute Turks-and-Caicos-Amanyara-Northwest-Point reel — extend to 3 minutes and add Turks-and-Caicos-Amanyara-Northwest-Point ambience.",
    "Here's a 45-second Bahamas-Atlantis-Paradise-Island reel — extend to 2 minutes and overlay Bahamas-Atlantis-Paradise-Island ambience.",
    "I'm sending you a 30-second Bermuda-Rosewood-Tucker's-Point reel — extend to 90 seconds and add Bermuda-Rosewood-Tucker's-Point ambience.",
    "Uploading a 1-minute Hawaii-Four-Seasons-Hualalai reel — extend to 3 minutes and overlay Hawaii-Four-Seasons-Hualalai ambience.",
    "Here's a 45-second Maui-Grand-Wailea reel — extend to 2 minutes and add Maui-Grand-Wailea ambience.",
    "I have a 30-second Kauai-St-Regis-Princeville reel — extend to 90 seconds and overlay Kauai-St-Regis-Princeville ambience.",
    "Uploading a 1-minute Lanai-Four-Seasons-Resort reel — extend to 3 minutes and add Lanai-Four-Seasons-Resort ambience.",
    "Here's a 45-second Costa-Smeralda-Cala-di-Volpe-Sardinia reel — extend to 2 minutes and overlay Costa-Smeralda-Cala-di-Volpe ambience.",
    "I'm sending you a 30-second Capri-Jumeirah-Capri-Palace reel — extend to 90 seconds and add Capri-Jumeirah-Capri-Palace ambience.",
    "Uploading a 1-minute Positano-Le-Sirenuse reel — extend to 3 minutes and overlay Positano-Le-Sirenuse ambience.",
    "Here's a 45-second Mykonos-Belvedere-Hotel reel — extend to 2 minutes and add Mykonos-Belvedere-Hotel ambience.",
    "I have a 30-second Santorini-Canaves-Oia-Suites reel — extend to 90 seconds and overlay Santorini-Canaves-Oia-Suites ambience.",
    "Uploading a 1-minute Crete-Blue-Palace-Elounda reel — extend to 3 minutes and add Crete-Blue-Palace-Elounda ambience.",
    "Here's a 45-second Ibiza-Six-Senses-Cap-de-Falcó reel — extend to 2 minutes and overlay Ibiza-Six-Senses-Cap-de-Falcó ambience.",
    "I'm sending you a 30-second Mallorca-Belmond-La-Residencia reel — extend to 90 seconds and add Mallorca-Belmond-La-Residencia ambience.",
    "Uploading a 1-minute Marbella-Marbella-Club-Hotel reel — extend to 3 minutes and overlay Marbella-Marbella-Club-Hotel ambience.",
    "Here's a 45-second Algarve-Vila-Vita-Parc reel — extend to 2 minutes and add Algarve-Vila-Vita-Parc ambience.",
    "I have a 30-second Madeira-Reid's-Palace reel — extend to 90 seconds and overlay Madeira-Reid's-Palace ambience.",
    "Uploading a 1-minute Cabo-San-Lucas-Esperanza-Auberge reel — extend to 3 minutes and add Cabo-Esperanza-Auberge ambience.",
    "Here's a 45-second Los-Cabos-One-Only-Palmilla reel — extend to 2 minutes and overlay Los-Cabos-One-Only-Palmilla ambience.",
    "I'm sending you a 30-second Hamilton-Island-qualia-Great-Barrier-Reef reel — extend to 90 seconds and add Hamilton-Island-qualia ambience.",
    "Uploading a 1-minute Lord-Howe-Capella-Lodge reel — extend to 3 minutes and overlay Lord-Howe-Capella-Lodge ambience.",
    "Here's a 45-second Byron-Bay-Raes-on-Wategos reel — extend to 2 minutes and add Byron-Bay-Raes-on-Wategos ambience.",
    "I have a 30-second Phu-Quoc-JW-Marriott-Emerald-Bay reel — extend to 90 seconds and overlay Phu-Quoc-JW-Marriott-Emerald-Bay ambience.",
    "Uploading a 1-minute Boracay-Shangri-La-Boracay reel — extend to 3 minutes and add Boracay-Shangri-La-Boracay ambience.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
