"""x15 highlight_music_subtitle GRPO short briefs. Disjoint from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 2-hour Sunday-morning sermon recording — please cut a highlight reel with reverent-organ BGM and English captions.",
    "Here's a 4-hour wildlife-photography safari recording — make highlights with adventure-orchestral BGM and English subtitles.",
    "I have a 3-hour Saturday-hike livestream — pull highlights with acoustic-folk BGM and English captions.",
    "Uploading a 5-hour open-water diving recording — assemble highlights with ambient-pad BGM and English subtitles.",
    "Here's a 90-minute SpaceX-launch livestream — please make a highlight reel with cinematic-orchestral BGM and English captions.",
    "I'm sending you a 2-hour Stargate session VOD — cut highlights with synthwave BGM and English subtitles.",
    "Uploading a 4-hour orchid-show recording — make a highlight reel with delicate-harp BGM and English captions.",
    "Here's a 3-hour fly-tying livestream — please pull highlights with bluegrass-fiddle BGM and English subtitles.",
    "I have a 90-minute amateur drone aerial-surveillance — make a highlight reel with cinematic-orchestral BGM and English captions.",
    "Uploading a 2-hour Costa-Rica bird-watching video — cut highlights with rainforest-flute BGM and English subtitles.",
    "Here's a 4-hour aurora-borealis time-lapse — please make a highlight reel with ambient-pad BGM and English captions.",
    "I'm sending you a 3-hour amateur taxidermy documentary — pull highlights with acoustic-folk BGM and English subtitles.",
    "Uploading a 90-minute robotics-competition VOD — make a highlight reel with electronic-rock BGM and English captions.",
    "Here's a 2-hour ASMR cooking livestream — please cut highlights with smooth-jazz BGM and English subtitles.",
    "I have a 4-hour beekeeping inspection livestream — assemble a highlight reel with pastoral-strings BGM and English captions.",
    "Uploading a 5-hour amateur astronomy livestream — make highlights with cosmic-ambient BGM and English subtitles.",
    "Here's a 90-minute pottery workshop livestream — please make a highlight reel with delicate-piano BGM and English captions.",
    "I'm sending you a 2-hour glass-blowing studio livestream — pull highlights with industrial-rock BGM and English subtitles.",
    "Uploading a 3-hour aquarium night-watch — cut highlights with ambient-electronic BGM and English captions.",
    "Here's a 4-hour woodworking shop livestream — please make a highlight reel with country-folk BGM and English subtitles.",
    "I have a 90-minute ham-radio contest — make a highlight reel with electronic-pulse BGM and English captions.",
    "Uploading a 2-hour kite-festival video — pull highlights with playful-orchestral BGM and English subtitles.",
    "Here's a 5-hour cosplay-convention masquerade — please cut highlights with synthwave BGM and English captions.",
    "I'm sending you a 3-hour magic-conference livestream — make a highlight reel with mysterious-strings BGM and English subtitles.",
    "Uploading a 90-minute spelling bee preliminary — assemble highlights with playful-pizzicato BGM and English captions.",
    "Here's a 4-hour Renaissance Faire stage VOD — please make a highlight reel with medieval-lute BGM and English subtitles.",
    "I have a 2-hour comedy improv long-form VOD — cut highlights with light-jazz BGM and English captions.",
    "Uploading a 3-hour state-fair beauty pageant — make a highlight reel with classical-strings BGM and English subtitles.",
    "Here's a 90-minute amateur magic show — please pull highlights with whimsical-orchestral BGM and English captions.",
    "I'm sending you a 2-hour barbershop-quartet competition — make a highlight reel with vocal-jazz BGM and English subtitles.",
    "Uploading a 4-hour book-fair livestream — cut highlights with classical-piano BGM and English captions.",
    "Here's a 5-hour county-fair eating-contest — please assemble highlights with circus-march BGM and English subtitles.",
    "I have a 90-minute axe-throwing-league night — make a highlight reel with country-rock BGM and English captions.",
    "Uploading a 2-hour beach club DJ livestream — pull highlights with electronic-house BGM and English subtitles.",
    "Here's a 3-hour circus-arts open-stage VOD — please make a highlight reel with carnival-orchestral BGM and English captions.",
    "I'm sending you a 4-hour storm-chasing recording — cut highlights with tense-orchestral BGM and English subtitles.",
    "Uploading a 90-minute speed-cubing tournament VOD — make a highlight reel with electronic-pulse BGM and English captions.",
    "Here's a 2-hour amateur-radio Field Day — please pull highlights with corporate-uplift BGM and English subtitles.",
    "I have a 5-hour youth choir competition — make a highlight reel with classical-strings BGM and English captions.",
    "Uploading a 3-hour high-school marching-band finals — cut highlights with brass-band BGM and English subtitles.",
    "Here's a 90-minute high-school dance-team competition — please make a highlight reel with pop-cheer BGM and English captions.",
    "I'm sending you a 2-hour pickleball-instructor demo session — assemble highlights with light-jazz BGM and English subtitles.",
    "Uploading a 4-hour fly-fishing tournament — make a highlight reel with country-folk BGM and English captions.",
    "Here's a 3-hour bow-fishing tournament — please pull highlights with country-rock BGM and English subtitles.",
    "I have a 90-minute beekeeping inspection livestream — make a highlight reel with pastoral-flute BGM and English captions.",
    "Uploading a 2-hour amateur sumo wrestling tournament — cut highlights with traditional-Japanese-taiko BGM and English subtitles.",
    "Here's a 4-hour falconry-meet — please make a highlight reel with cinematic-orchestral BGM and English captions.",
    "I'm sending you a 3-hour Junior Olympics rowing — pull highlights with hopeful-orchestral BGM and English subtitles.",
    "Uploading a 90-minute college a-cappella championship — make a highlight reel with vocal-pop BGM and English captions.",
    "Here's a 2-hour amateur stand-up comedy night — please cut highlights with bouncy-jazz BGM and English subtitles.",
    "I have a 5-hour Iditarod sled-dog livestream — make a highlight reel with epic-orchestral BGM and English captions.",
    "Uploading a 90-minute regional spelling-bee — assemble highlights with playful-pizzicato BGM and English subtitles.",
    "Here's a 2-hour amateur juggling festival — please make a highlight reel with carnival-march BGM and English captions.",
    "I'm sending you a 3-hour competitive eating contest — cut highlights with circus-orchestral BGM and English subtitles.",
    "Uploading a 4-hour amateur chess tournament — make a highlight reel with classical-piano BGM and English captions.",
    "Here's a 90-minute axe-throwing-league finals — please pull highlights with country-rock BGM and English subtitles.",
    "I have a 2-hour dragon-boat-festival opening — make a highlight reel with traditional-Chinese-drum BGM and English captions.",
    "Uploading a 3-hour synchronized-swimming nationals — cut highlights with classical-strings BGM and English subtitles.",
    "Here's a 4-hour ultramarathon livestream — please make a highlight reel with electronic-pulse BGM and English captions.",
    "I'm sending you a 5-hour amateur sailing regatta — pull highlights with maritime-folk BGM and English subtitles.",
    "Uploading a 90-minute amateur boxing exhibition — make a highlight reel with hip-hop BGM and English captions.",
    "Here's a 2-hour judo state finals — please cut highlights with traditional-Japanese-taiko BGM and English subtitles.",
    "I have a 3-hour amateur kickboxing tournament — make a highlight reel with electronic-rock BGM and English captions.",
    "Uploading a 4-hour amateur cornhole nationals — pull highlights with country-rock BGM and English subtitles.",
    "Here's a 90-minute youth volleyball state finals — please make a highlight reel with upbeat-pop BGM and English captions.",
    "I'm sending you a 2-hour amateur dirt-bike racing event — cut highlights with hard-rock BGM and English subtitles.",
    "Uploading a 3-hour amateur bowling-league tournament — make a highlight reel with classic-rock BGM and English captions.",
    "Here's a 4-hour college water-polo championship — please pull highlights with cinematic-orchestral BGM and English subtitles.",
    "I have a 5-hour high-school girls' lacrosse tournament — make a highlight reel with stadium-rock BGM and English captions.",
    "Uploading a 90-minute high-school robotics competition — assemble highlights with electronic-rock BGM and English subtitles.",
    "Here's a 2-hour amateur ham-radio contest — please make a highlight reel with corporate-uplift BGM and English captions.",
    "I'm sending you a 3-hour state-fair pole-vault competition — pull highlights with cinematic-orchestral BGM and English subtitles.",
    "Uploading a 4-hour amateur orienteering meet — make a highlight reel with adventure-orchestral BGM and English captions.",
    "Here's a 90-minute lawn-bowling tournament — please cut highlights with light-pizzicato BGM and English subtitles.",
    "I have a 2-hour amateur hockey league tournament — make a highlight reel with rock-anthem BGM and English captions.",
    "Uploading a 3-hour amateur curling provincials — pull highlights with playful-pizzicato BGM and English subtitles.",
    # ── more highlight reels with BGM + subtitles (50) ────────────────────
    "Uploading a 2-hour wedding-anniversary party — please cut a highlight reel with romantic-strings BGM and English captions.",
    "Here's a 3-hour 50th-birthday celebration — extract highlights with classic-rock BGM and English subtitles.",
    "I have a 4-hour quinceañera celebration — please pull highlights with mariachi-trumpet BGM and English captions.",
    "Uploading a 90-minute bar-mitzvah ceremony — cut highlights with Klezmer-clarinet BGM and English subtitles.",
    "Here's a 2-hour bat-mitzvah ceremony — please extract highlights with Klezmer-violin BGM and English captions.",
    "I'm sending you a 5-hour Indian wedding ceremony — pull highlights with bhangra-percussion BGM and English subtitles.",
    "Uploading a 3-hour Korean traditional wedding — cut highlights with traditional-Korean-percussion BGM and English captions.",
    "Here's a 2-hour Chinese wedding banquet — please make a highlight reel with traditional-Chinese-erhu BGM and English subtitles.",
    "I have a 4-hour Greek wedding reception — pull highlights with Greek-bouzouki BGM and English captions.",
    "Uploading a 3-hour Italian wedding reception — make a highlight reel with Italian-mandolin BGM and English subtitles.",
    "Here's a 90-minute Filipino baptism celebration — please cut highlights with Filipino-folk BGM and English captions.",
    "I'm sending you a 2-hour Mexican quinceañera — extract highlights with mariachi-trumpet BGM and English subtitles.",
    "Uploading a 3-hour Brazilian birthday celebration — make highlights with samba-cuíca BGM and English captions.",
    "Here's a 4-hour Argentinian asado celebration — please pull highlights with tango-bandoneón BGM and English subtitles.",
    "I have a 90-minute Japanese tea ceremony — cut highlights with shakuhachi BGM and English captions.",
    "Uploading a 2-hour Korean dol-jabi ceremony — make a highlight reel with Korean-haegeum BGM and English subtitles.",
    "Here's a 3-hour Vietnamese Tet celebration — please extract highlights with Vietnamese-dan-bau BGM and English captions.",
    "I'm sending you a 4-hour Thai Songkran celebration — pull highlights with Thai-percussion BGM and English subtitles.",
    "Uploading a 5-hour Indian Diwali celebration — make highlights with Indian-classical-strings BGM and English captions.",
    "Here's a 90-minute Persian Nowruz celebration — please cut highlights with Persian-santur BGM and English subtitles.",
    "I have a 2-hour Egyptian Eid celebration — extract highlights with oud BGM and English captions.",
    "Uploading a 3-hour Saudi Hajj documentary — pull highlights with sustained-vocal-call BGM and English subtitles.",
    "Here's a 4-hour Mecca-Hajj documentary — please make a highlight reel with Sufi-zikr BGM and English captions.",
    "I'm sending you a 90-minute Turkish whirling-dervish ceremony — cut highlights with ney-and-drum BGM and English subtitles.",
    "Uploading a 2-hour Sufi-tariqa gathering — make highlights with ney-and-drum BGM and English captions.",
    "Here's a 3-hour Eastern-Orthodox Easter vigil — please extract highlights with Byzantine-chant BGM and English subtitles.",
    "I have a 4-hour Catholic-Easter vigil — pull highlights with Gregorian-chant BGM and English captions.",
    "Uploading a 90-minute Quaker silent-meeting — cut highlights with single-organ-note BGM and English subtitles.",
    "Here's a 2-hour Bahá'í-fast celebration — make a highlight reel with soft-a-cappella BGM and English captions.",
    "I'm sending you a 5-hour Hindu-puja gathering — please pull highlights with bansuri-and-sitar BGM and English subtitles.",
    "Uploading a 3-hour Sikh-kirtan gathering — extract highlights with kirtan-style-raag BGM and English captions.",
    "Here's a 2-hour Buddhist-uposatha-day gathering — please make a highlight reel with singing-bowl BGM and English subtitles.",
    "I have a 4-hour Tibetan Losar celebration — cut highlights with Tibetan-flute BGM and English captions.",
    "Uploading a 3-hour Mongolian Naadam festival — make highlights with Mongolian-throat-singing BGM and English subtitles.",
    "Here's a 90-minute Inuit-throat-singing competition — please extract highlights with Inuit-throat-singing BGM and English captions.",
    "I'm sending you a 2-hour Sami-yoik festival — pull highlights with Sami-yoik BGM and English subtitles.",
    "Uploading a 3-hour Faroese-grindadrap commemoration — please make a highlight reel with Faroese-folk BGM and English captions.",
    "Here's a 4-hour Maori-haka competition — cut highlights with taonga-pūoro BGM and English subtitles.",
    "I have a 90-minute Hawaiian-hula festival — make a highlight reel with Hawaiian-ipu-heke BGM and English captions.",
    "Uploading a 2-hour Aboriginal-corroboree gathering — please extract highlights with didgeridoo BGM and English subtitles.",
    "Here's a 3-hour Zulu-Reed Dance ceremony — pull highlights with Zulu-isicathamiya BGM and English captions.",
    "I'm sending you a 4-hour Maasai-warrior-graduation ceremony — make highlights with Maasai-chant BGM and English subtitles.",
    "Uploading a 90-minute Igbo masquerade festival — cut highlights with Igbo-highlife BGM and English captions.",
    "Here's a 2-hour Yoruba-Egungun festival — please make a highlight reel with Yoruba-juju BGM and English subtitles.",
    "I have a 3-hour Ghanaian-Adae festival — extract highlights with Ghanaian-highlife BGM and English captions.",
    "Uploading a 4-hour Senegalese-Wolof gamou celebration — pull highlights with Senegalese-mbalax BGM and English subtitles.",
    "Here's a 90-minute Ethiopian-Timkat celebration — please make a highlight reel with Ethiopian-azmari BGM and English captions.",
    "I'm sending you a 2-hour Moroccan-Mawlid celebration — cut highlights with Moroccan-gnawa BGM and English subtitles.",
    "Uploading a 3-hour Sudanese-Mawlid celebration — make highlights with Sudanese-tambour BGM and English captions.",
    "Here's a 4-hour Tanzanian-Maulidi celebration — please extract highlights with Tanzanian-bongo-flava BGM and English subtitles.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
