"""x15 story_music_ambience GRPO. Disjoint from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Tell me a children's audiobook about a young whale learning her songs, with deep-cello BGM and underwater ambience.",
    "I want an illustrated audiobook about a baby seahorse finding her father, with delicate-harp BGM and reef ambience.",
    "Make me a bedtime audiobook about a glowworm lighting up her cave, with celesta BGM and cave-drip ambience.",
    "Create a picture-book audiobook about a baby bat flying for the first time, with flute BGM and twilight-cricket ambience.",
    "Produce an illustrated children's tale about a young raccoon raiding the kitchen, with mischievous-clarinet BGM and house-night ambience.",
    "Generate a kids' audiobook about a baby porcupine making her first friend, with playful-bassoon BGM and forest-twilight ambience.",
    "Build a narrated picture-book about a young moose finding her shadow, with bright-fiddle BGM and meadow-bird ambience.",
    "Render a children's audiobook about a young cricket learning to chirp, with night-time-strings BGM and cricket-night ambience.",
    "I'd like a bedtime audiobook about a baby hummingbird tucked in a flower, with lullaby-flute BGM and garden-bee ambience.",
    "Tell me a children's audiobook about a young tarantula spinning her first web, with playful-pizzicato BGM and rainforest-drip ambience.",
    "Make a soft picture-book audiobook about a young scorpion learning to dance, with desert-percussion BGM and desert-cricket ambience.",
    "Cook up a children's audiobook about a young centipede counting her legs, with quirky-bassoon BGM and forest-floor ambience.",
    "Generate a narrated picture-book about a young toad making her first hop, with bouncy-tuba BGM and marsh-frog ambience.",
    "Produce a children's audiobook about a baby octopus changing color, with whimsical-clarinet BGM and reef-bubble ambience.",
    "Build a bedtime audiobook about a young jellyfish drifting in moonlight, with ambient-pad BGM and deep-sea ambience.",
    "Tell me an illustrated children's audiobook about a baby dolphin riding a wave, with bright-strings BGM and surf ambience.",
    "Make me a picture-book audiobook about a young sea-otter rolling on her back, with playful-flute BGM and rocky-shore ambience.",
    "Cook up a narrated children's audiobook about a young manatee gliding through warm water, with serene-cello BGM and slough ambience.",
    "Generate a children's bedtime audiobook about a young narwhal carving the perfect spiral, with delicate-harp BGM and arctic-sea ambience.",
    "Produce a kids' picture-book audiobook about a young walrus practicing her whistle, with playful-bassoon BGM and pack-ice ambience.",
    "Build an illustrated children's audiobook about a young manta ray gliding past coral, with serene-strings BGM and reef ambience.",
    "Tell me a children's audiobook about a baby mantis shrimp punching her first snail, with quirky-percussion BGM and reef-rubble ambience.",
    "Make a narrated picture-book audiobook about a young pelican catching her first fish, with bouncy-clarinet BGM and pier ambience.",
    "Render a children's audiobook about a baby kingfisher diving for her first meal, with bright-strings BGM and stream ambience.",
    "I'd like a bedtime audiobook about a young flamingo learning to stand on one leg, with calm-flute BGM and lagoon ambience.",
    "Cook up a children's audiobook about a young heron stalking her first frog, with playful-bassoon BGM and marsh ambience.",
    "Generate a kids' picture-book audiobook about a young toucan learning to balance her beak, with tropical-marimba BGM and rainforest-canopy ambience.",
    "Produce a narrated children's audiobook about a baby parrot mimicking her father, with playful-clarinet BGM and rainforest-canopy ambience.",
    "Build a bedtime audiobook about a young owl finding her wisdom in moonlight, with celesta BGM and night-forest ambience.",
    "Tell me an illustrated children's audiobook about a baby crow remembering her treasure, with playful-pizzicato BGM and orchard-evening ambience.",
    "Make me a picture-book audiobook about a young raven solving a puzzle, with mysterious-strings BGM and high-forest ambience.",
    "Cook up a narrated children's audiobook about a young magpie collecting shiny things, with quirky-pizzicato BGM and meadow-edge ambience.",
    "Generate a children's bedtime audiobook about a young swallow building her first nest, with tender-flute BGM and barn-eaves ambience.",
    "Produce a kids' picture-book audiobook about a young goldfinch finding the perfect seed, with bright-flute BGM and hedge ambience.",
    "Build an illustrated children's audiobook about a young woodpecker drumming her first rhythm, with playful-percussion BGM and oak-trunk ambience.",
    # ── more illustrated children's audiobooks with BGM and ambience (50)
    "Tell me a children's audiobook about a baby ladybug counting her spots, with playful-pizzicato BGM and garden-flower ambience.",
    "Make me an illustrated audiobook about a baby praying mantis learning to wait, with stealthy-strings BGM and leaf-rustle ambience.",
    "Cook up a bedtime audiobook about a baby cicada singing her first song, with hot-summer-strings BGM and hot-afternoon ambience.",
    "Generate a kids' picture-book audiobook about a baby grasshopper learning her highest leap, with bouncy-flute BGM and meadow-grass ambience.",
    "Produce a children's audiobook about a baby firefly lighting her first signal, with twinkling-celesta BGM and summer-night ambience.",
    "Build a narrated picture-book audiobook about a baby silkworm spinning her first thread, with meditative-flute BGM and mulberry-leaf ambience.",
    "Render a children's audiobook about a baby earthworm tunneling through warm soil, with pizzicato BGM and soft-soil ambience.",
    "I'd like a bedtime audiobook about a baby slug gliding across damp leaves, with slow-piano BGM and moss ambience.",
    "Tell me a children's audiobook about a baby anole hunting flies on a fence, with tropical-flute BGM and tropical-night ambience.",
    "Make a picture-book audiobook about a baby gecko clinging to a window, with tropical-marimba BGM and tropical-window ambience.",
    "Cook up a children's audiobook about a baby skink darting through leaf litter, with playful-pizzicato BGM and leaf-litter ambience.",
    "Generate a narrated picture-book about a baby iguana sunning on a beach rock, with beach-marimba BGM and beach-rock ambience.",
    "Produce a children's audiobook about a baby tortoise plodding to the watering hole, with wise-cello BGM and ancient-island ambience.",
    "Build a bedtime audiobook about a baby alligator learning her first hiss, with river-strings BGM and river-bank ambience.",
    "Tell me an illustrated children's audiobook about a baby snake shedding her first skin, with hypnotic-flute BGM and tropical-tree ambience.",
    "Make me a picture-book audiobook about a baby treefrog learning her first ribbit, with jungle-pizzicato BGM and jungle-night ambience.",
    "Cook up a narrated children's audiobook about a baby kiwi sniffing her way through the forest, with native-Maori BGM and kiwi-forest ambience.",
    "Generate a children's bedtime audiobook about a baby kakapo climbing her first tree, with deep-bass-strings BGM and kauri-forest ambience.",
    "Produce a kids' picture-book audiobook about a baby cassowary running through the rainforest, with tropical-flute BGM and cassowary-undergrowth ambience.",
    "Build an illustrated children's audiobook about a baby ostrich taking her first sprint, with playful-clarinet BGM and dune-wind ambience.",
    "Tell me a children's audiobook about a baby emu following her father, with Australian-folk BGM and outback ambience.",
    "Make a narrated picture-book audiobook about a baby hawk testing her wings, with heroic-strings BGM and prairie-wind ambience.",
    "Render a children's audiobook about a baby falcon learning to dive, with adventurous-strings BGM and cliff ambience.",
    "I'd like a bedtime audiobook about a baby eagle gliding above a canyon, with triumphant-strings BGM and canyon-thermal ambience.",
    "Cook up a children's audiobook about a baby vulture circling a desert ridge, with wistful-strings BGM and desert-thermal ambience.",
    "Generate a kids' picture-book audiobook about a baby albatross gliding over the open ocean, with open-ocean-strings BGM and open-ocean ambience.",
    "Produce a narrated children's audiobook about a baby frigatebird perched on a tropical mast, with tropical-strings BGM and tropical-mast ambience.",
    "Build a bedtime audiobook about a baby axolotl drifting through a Mexican canal, with Mexican-canal-flute BGM and Mexican-canal ambience.",
    "Tell me an illustrated children's audiobook about a baby salamander resting on damp moss, with forest-flute BGM and forest-pond ambience.",
    "Make me a picture-book audiobook about a baby newt swimming through a forest pond, with pond-pizzicato BGM and pond ambience.",
    "Cook up a narrated children's audiobook about a baby Amazon tree-frog calling at dusk, with Amazon-flute BGM and Amazon-rain ambience.",
    "Generate a children's bedtime audiobook about a baby beaver tending her first dam, with river-banjo BGM and beaver-dam-river ambience.",
    "Produce a kids' picture-book audiobook about a baby armadillo curling into a ball, with Texas-fiddle BGM and Texas-night-lawn ambience.",
    "Build an illustrated children's audiobook about a baby aardvark sniffing for termites, with African-percussion BGM and termite-mound ambience.",
    "Tell me a children's audiobook about a baby pangolin curled like a fern, with jungle-flute BGM and forest-undergrowth ambience.",
    "Make a narrated picture-book audiobook about a baby anteater following her mother, with Amazon-flute BGM and Amazon-floor ambience.",
    "Render a children's audiobook about a baby capybara floating through the Pantanal, with Pantanal-flute BGM and Pantanal-river ambience.",
    "I'd like a bedtime audiobook about a baby tapir splashing in a rainforest stream, with rainforest-drum BGM and rainforest-stream ambience.",
    "Cook up a children's audiobook about a baby sloth napping on a vine, with slow-piano BGM and Costa-Rican-canopy ambience.",
    "Generate a kids' picture-book audiobook about a baby quokka grinning in the sun, with playful-flute BGM and Rottnest-Island ambience.",
    "Produce a narrated children's audiobook about a baby wombat digging her first burrow, with bouncy-bassoon BGM and wombat-burrow ambience.",
    "Build a bedtime audiobook about a baby kangaroo bouncing in the outback, with playful-bassoon BGM and outback ambience.",
    "Tell me an illustrated children's audiobook about a baby possum playing dead, with playful-pizzicato BGM and backyard-night ambience.",
    "Make me a picture-book audiobook about a baby pika gathering grass for winter, with cheerful-flute BGM and rocky-slope ambience.",
    "Cook up a narrated children's audiobook about a baby marmot whistling on a rocky slope, with cheerful-flute BGM and alpine-rocks ambience.",
    "Generate a children's bedtime audiobook about a baby badger emerging from her sett, with playful-bassoon BGM and sett-night ambience.",
    "Produce a kids' picture-book audiobook about a baby fennec fox padding across a Saharan dune, with Saharan-flute BGM and Saharan-dune ambience.",
    "Build an illustrated children's audiobook about a baby red panda curled on a high branch, with Himalayan-flute BGM and Himalayan-conifer ambience.",
    "Tell me a children's audiobook about a baby okapi stepping through Congo undergrowth, with pastoral-flute BGM and Congo-undergrowth ambience.",
    "Make a narrated picture-book audiobook about a baby lemur swinging through Madagascar trees, with Madagascan-flute BGM and Madagascan-tree ambience.",
    # ── more illustrated children's audiobooks with BGM and ambience (50)
    "Tell me a children's audiobook about a wise sea-witch tending a tide-pool, with tide-pool-celesta BGM and tide-pool-bubble ambience.",
    "Make me an illustrated audiobook about a baby kraken curled in a deep-sea trench, with deep-cello BGM and deep-current ambience.",
    "Cook up a bedtime audiobook about a baby mer-baby in a coral nursery, with delicate-harp BGM and coral-nursery ambience.",
    "Generate a kids' picture-book audiobook about a baby siren learning her song on a rocky cove, with ocean-strings BGM and rocky-cove ambience.",
    "Produce a children's audiobook about a baby Loch-Ness creature surfacing through fog, with Celtic-fiddle BGM and loch-mist ambience.",
    "Build a narrated picture-book audiobook about a baby Yeti padding across the Himalayan snow, with ethereal-strings BGM and Himalayan-snow ambience.",
    "Render a children's audiobook about a baby Sasquatch in a pine forest, with tribal-flute BGM and pine-forest ambience.",
    "I'd like a bedtime audiobook about a baby will-o-wisp dancing in a marsh, with shimmering-celesta BGM and marsh-fog ambience.",
    "Tell me a children's audiobook about a baby naga curled by a river temple, with Indian-bansuri BGM and river-temple ambience.",
    "Make a picture-book audiobook about a baby phoenix sparking near an ember, with triumphant-strings BGM and ember-glow ambience.",
    "Cook up a children's audiobook about a wise wizard's owl in a library tower, with delicate-piano BGM and library-quiet ambience.",
    "Generate a narrated picture-book about a moonbeam fairy in a moonlit meadow, with shimmering-celesta BGM and moonlit-meadow ambience.",
    "Produce a children's audiobook about a starlight pixie weaving through a forest canopy, with twinkling-celesta BGM and forest-canopy-stars ambience.",
    "Build a bedtime audiobook about a dewdrop sprite balanced on a spider's web at dawn, with delicate-flute BGM and spider-web-dawn ambience.",
    "Tell me an illustrated children's audiobook about a cloud-shepherd guiding clouds along a peak, with ambient-pad BGM and mountain-mist ambience.",
    "Make me a picture-book audiobook about a wind-rider sailing along a cliff, with ambient-strings BGM and cliff-air ambience.",
    "Cook up a narrated children's audiobook about a snowflake fairy fluttering through a winter snowfall, with winter-piano BGM and winter-snowfall ambience.",
    "Generate a children's bedtime audiobook about an icicle sprite napping above a frozen pond, with delicate-celesta BGM and frozen-pond ambience.",
    "Produce a kids' picture-book audiobook about an autumn-leaf-spirit drifting through an autumn park, with wistful-piano BGM and autumn-park ambience.",
    "Build an illustrated children's audiobook about a cherry-blossom-spirit twirling in a sakura park, with Japanese-koto BGM and cherry-blossom-park ambience.",
    "Tell me a children's audiobook about a baby field-mouse curled in barley, with playful-pizzicato BGM and barley-field ambience.",
    "Make a narrated picture-book audiobook about a baby vole tunneling through heather, with playful-pizzicato BGM and heather-moor ambience.",
    "Render a children's audiobook about a baby shrew darting beneath a fern, with playful-pizzicato BGM and fern-shade ambience.",
    "I'd like a bedtime audiobook about a baby pika gathering grass on a rocky slope, with cheerful-flute BGM and rocky-slope ambience.",
    "Cook up a children's audiobook about a baby chinchilla bouncing on Andean rocks, with cheerful-flute BGM and Andean-rocky-slope ambience.",
    "Generate a kids' picture-book audiobook about a baby viscacha along an Andean cliff, with Andean-flute BGM and Andean-cliff-wind ambience.",
    "Produce a narrated children's audiobook about a baby capuchin learning to crack a nut in the jungle, with tropical-flute BGM and jungle-canopy ambience.",
    "Build a bedtime audiobook about a baby spider-monkey swinging through the canopy, with tropical-flute BGM and jungle-canopy ambience.",
    "Tell me an illustrated children's audiobook about a baby howler-monkey calling at dusk, with tropical-flute BGM and howler-night ambience.",
    "Make me a picture-book audiobook about a baby tarsier blinking at midnight, with Philippine-flute BGM and Philippine-jungle-night ambience.",
    "Cook up a narrated children's audiobook about a baby loris creeping along a branch, with Asian-flute BGM and Asian-rainforest-night ambience.",
    "Generate a children's bedtime audiobook about a baby colugo gliding between trees, with tropical-flute BGM and tropical-canopy-night ambience.",
    "Produce a kids' picture-book audiobook about a baby flying-squirrel landing on an oak, with playful-pizzicato BGM and oak-night ambience.",
    "Build an illustrated children's audiobook about a baby flying-fox roosting with its colony, with tropical-flute BGM and fruit-bat-colony ambience.",
    "Tell me a children's audiobook about a baby fruit-bat hanging upside-down in a cave, with ambient-flute BGM and cave-roost ambience.",
    "Make a narrated picture-book audiobook about a baby vampire-bat in a cool cave, with eerie-strings BGM and cave-roost ambience.",
    "Render a children's audiobook about a baby mantis-shrimp punching at reef rubble, with quirky-percussion BGM and reef-rubble ambience.",
    "I'd like a bedtime audiobook about a baby horseshoe-crab in a tide pool, with ancient-strings BGM and tide-pool ambience.",
    "Cook up a children's audiobook about a baby spiny-lobster sheltering in a reef cave, with playful-pizzicato BGM and reef-cave ambience.",
    "Generate a kids' picture-book audiobook about a baby parrotfish nibbling coral, with playful-flute BGM and coral-reef ambience.",
    "Produce a narrated children's audiobook about a baby angelfish flitting around coral, with delicate-flute BGM and coral-reef ambience.",
    "Build a bedtime audiobook about a baby pipefish weaving through coral grass, with delicate-flute BGM and coral-grass ambience.",
    "Tell me an illustrated children's audiobook about a baby cuttlefish drifting in open water, with ambient-flute BGM and open-water ambience.",
    "Make me a picture-book audiobook about a baby nautilus rising through deep currents, with ambient-pad BGM and deep-current ambience.",
    "Cook up a narrated children's audiobook about a baby krill drifting in the open ocean, with ambient-pad BGM and open-ocean ambience.",
    "Generate a children's bedtime audiobook about a baby beluga calling to its pod, with ambient-strings BGM and Arctic-pod ambience.",
    "Produce a kids' picture-book audiobook about a baby porpoise swimming in the North Sea, with ambient-strings BGM and North-Sea ambience.",
    "Build an illustrated children's audiobook about a baby manatee in a Florida spring, with calm-cello BGM and Florida-spring ambience.",
    "Tell me a children's audiobook about a baby dugong nibbling Indo-Pacific seagrass, with ambient-flute BGM and Indo-Pacific-seagrass ambience.",
    "Make a narrated picture-book audiobook about a baby quokka grinning at Rottnest Island, with playful-flute BGM and Rottnest-Island-shrub ambience.",
    # ── more baby birds + BGM + ambience (50) ──
    "Build a bedtime audiobook about a baby bald-eagle peering from an Alaskan nest, with Alaskan-flute BGM and Alaskan-cliff ambience.",
    "Tell me an illustrated children's audiobook about a baby golden-eagle gliding over Scottish highlands, with Scottish-bagpipe BGM and Scottish-highland ambience.",
    "Make me a picture-book audiobook about a baby harpy-eagle resting in an Amazonian canopy, with Amazonian-flute BGM and Amazonian-canopy ambience.",
    "Cook up a narrated children's audiobook about a baby Philippine-eagle perched on a Mindanao branch, with Mindanao-kulintang BGM and Mindanao-canopy ambience.",
    "Generate a children's bedtime audiobook about a baby Steller's-sea-eagle on a Russian ice floe, with Russian-balalaika BGM and Russian-ice-floe ambience.",
    "Produce a kids' picture-book audiobook about a baby peregrine-falcon learning to dive over cliffs, with cliff-flute BGM and cliff-edge ambience.",
    "Build an illustrated children's audiobook about a baby gyrfalcon perched on Arctic tundra, with Arctic-flute BGM and Arctic-tundra ambience.",
    "Tell me a children's audiobook about a baby kestrel hovering above a meadow, with meadow-flute BGM and meadow-breeze ambience.",
    "Make a narrated picture-book audiobook about a baby barn-owl peering from an English barn, with English-folk-flute BGM and English-barn-night ambience.",
    "Cook up a children's audiobook about a baby snowy-owl hidden in tundra grass, with snowy-flute BGM and tundra-grass-night ambience.",
    "Generate a kids' picture-book audiobook about a baby great-horned-owl in a deciduous forest, with deciduous-flute BGM and deciduous-night ambience.",
    "Produce a narrated children's audiobook about a baby boreal-owl in a Finnish spruce, with Finnish-kantele BGM and Finnish-spruce-night ambience.",
    "Build a bedtime audiobook about a baby pygmy-owl peeking from a Mexican cactus, with Mexican-flute BGM and Mexican-cactus ambience.",
    "Tell me an illustrated children's audiobook about a baby Eurasian-eagle-owl atop a cliff, with Eurasian-flute BGM and cliff-night ambience.",
    "Make me a picture-book audiobook about a baby kakapo waddling in a New-Zealand fern, with Maori-koauau BGM and New-Zealand-fern ambience.",
    "Cook up a narrated children's audiobook about a baby kea exploring an alpine ridge, with alpine-flute BGM and alpine-ridge ambience.",
    "Generate a children's bedtime audiobook about a baby kookaburra laughing at sunrise, with eucalyptus-flute BGM and eucalyptus-dawn ambience.",
    "Produce a kids' picture-book audiobook about a baby lyrebird mimicking forest sounds, with Australian-flute BGM and Australian-forest ambience.",
    "Build an illustrated children's audiobook about a baby cassowary stalking a Queensland forest, with Queensland-percussion BGM and Queensland-forest ambience.",
    "Tell me a children's audiobook about a baby emu wandering an Australian outback, with outback-didgeridoo BGM and Australian-outback ambience.",
    "Make a narrated picture-book audiobook about a baby ostrich loping across a savanna, with African-percussion BGM and savanna-loping ambience.",
    "Cook up a children's audiobook about a baby rhea grazing on a Patagonian plain, with Patagonian-pan-flute BGM and Patagonian-plain ambience.",
    "Generate a kids' picture-book audiobook about a baby kiwi sniffing through a New-Zealand forest, with Maori-flute BGM and New-Zealand-night-forest ambience.",
    "Produce a narrated children's audiobook about a baby penguin chick on Antarctic ice, with Antarctic-flute BGM and Antarctic-ice ambience.",
    "Build a bedtime audiobook about a baby emperor-penguin huddling in a colony, with Antarctic-strings BGM and Antarctic-colony ambience.",
    "Tell me an illustrated children's audiobook about a baby king-penguin sliding on snow, with sub-Antarctic-flute BGM and sub-Antarctic-snow ambience.",
    "Make me a picture-book audiobook about a baby gentoo-penguin chasing krill, with sub-Antarctic-strings BGM and sub-Antarctic-water ambience.",
    "Cook up a narrated children's audiobook about a baby chinstrap-penguin scaling a rock pile, with sub-Antarctic-percussion BGM and sub-Antarctic-rock ambience.",
    "Generate a children's bedtime audiobook about a baby fairy-penguin in a Phillip-Island burrow, with island-flute BGM and Phillip-Island-burrow ambience.",
    "Produce a kids' picture-book audiobook about a baby flamingo flapping in a Kenyan lake, with Kenyan-flute BGM and Kenyan-soda-lake ambience.",
    "Build an illustrated children's audiobook about a baby pelican gliding over a Florida lagoon, with Floridian-flute BGM and Florida-lagoon ambience.",
    "Tell me a children's audiobook about a baby toucan calling from an Amazon canopy, with Amazon-pan-flute BGM and Amazon-canopy ambience.",
    "Make a narrated picture-book audiobook about a baby hornbill peering from a Bornean tree-hole, with Bornean-flute BGM and Bornean-tree-hole ambience.",
    "Cook up a children's audiobook about a baby quetzal flitting through Costa-Rican cloud-forest, with Costa-Rican-flute BGM and cloud-forest ambience.",
    "Generate a kids' picture-book audiobook about a baby hummingbird sipping a Costa-Rican flower, with Costa-Rican-marimba BGM and Costa-Rican-garden ambience.",
    "Produce a narrated children's audiobook about a baby kingfisher diving into an English brook, with English-folk-flute-2 BGM and English-brook ambience.",
    "Build a bedtime audiobook about a baby puffin balancing on an Icelandic cliff, with Icelandic-flute BGM and Icelandic-cliff ambience.",
    "Tell me an illustrated children's audiobook about a baby gannet plunging off a Scottish stack, with Scottish-flute BGM and Scottish-stack ambience.",
    "Make me a picture-book audiobook about a baby albatross gliding over the Southern-Ocean, with Southern-Ocean-strings BGM and Southern-Ocean-wind ambience.",
    "Cook up a narrated children's audiobook about a baby frigatebird hovering above a tropical reef, with tropical-flute BGM and tropical-reef-wind ambience.",
    "Generate a children's bedtime audiobook about a baby blue-footed-booby strutting on Galápagos lava, with Galápagos-flute BGM and Galápagos-lava ambience.",
    "Produce a kids' picture-book audiobook about a baby cormorant drying its wings on a Pacific rock, with Pacific-flute BGM and Pacific-rock ambience.",
    "Build an illustrated children's audiobook about a baby crane wading in a Hokkaido marsh, with Hokkaido-shakuhachi BGM and Hokkaido-marsh ambience.",
    "Tell me a children's audiobook about a baby stork nesting on a German rooftop, with German-folk-flute BGM and German-village-roof ambience.",
    "Make a narrated picture-book audiobook about a baby heron wading in a Korean rice-paddy, with Korean-daegeum BGM and Korean-rice-paddy ambience.",
    "Cook up a children's audiobook about a baby ibis foraging on the Nile shore, with Nile-flute BGM and Nile-shore ambience.",
    "Generate a kids' picture-book audiobook about a baby spoonbill sweeping a Texas wetland, with Texas-fiddle BGM and Texas-wetland ambience.",
    "Produce a narrated children's audiobook about a baby roseate-spoonbill in a Florida estuary, with Floridian-strings BGM and Florida-estuary ambience.",
    "Build a bedtime audiobook about a baby trumpeter-swan gliding on a Yellowstone lake, with American-folk-flute BGM and Yellowstone-lake ambience.",
    "Tell me an illustrated children's audiobook about a baby black-swan paddling in an Australian park, with Australian-pizzicato BGM and Australian-park-pond ambience.",
    # ── more baby small mammals + BGM + biome ambience (50) ──
    "Make me a picture-book audiobook about a baby red-fox kit peeking from a den, with English-folk-fiddle BGM and English-hedgerow ambience.",
    "Cook up a narrated children's audiobook about a baby Arctic-fox kit on tundra snow, with Arctic-flute-2 BGM and Arctic-tundra-snow ambience.",
    "Generate a children's bedtime audiobook about a baby fennec-fox kit in Saharan dunes, with Saharan-oud BGM and Saharan-dune-night ambience.",
    "Produce a kids' picture-book audiobook about a baby Ethiopian-wolf pup on the Bale-Mountains, with Ethiopian-flute BGM and Bale-Mountain-meadow ambience.",
    "Build an illustrated children's audiobook about a baby maned-wolf pup in a cerrado-grassland, with Brazilian-cerrado-flute BGM and cerrado-grassland ambience.",
    "Tell me a children's audiobook about a baby raccoon kit on a Vermont-cabin porch, with New-England-folk-fiddle BGM and Vermont-cabin-porch-night ambience.",
    "Make a narrated picture-book audiobook about a baby coati pup on a Costa-Rican forest-floor, with Costa-Rican-marimba-2 BGM and Costa-Rican-forest-floor ambience.",
    "Cook up a children's audiobook about a baby kinkajou pup on a fig-canopy, with Mesoamerican-marimba BGM and Mesoamerican-fig-canopy ambience.",
    "Generate a kids' picture-book audiobook about a baby red-panda cub on a Sichuan bamboo-branch, with Sichuan-erhu BGM and Sichuan-bamboo-canopy ambience.",
    "Produce a narrated children's audiobook about a baby giant-panda cub munching bamboo, with Sichuan-pipa BGM and Sichuan-bamboo-grove ambience.",
    "Build a bedtime audiobook about a baby otter pup splashing in a Welsh river, with Welsh-harp BGM and Welsh-river ambience.",
    "Tell me an illustrated children's audiobook about a baby sea-otter pup floating on California kelp, with California-folk-fiddle BGM and California-kelp-bed ambience.",
    "Make me a picture-book audiobook about a baby beaver kit in a New-England-pond lodge, with New-England-banjo BGM and New-England-pond-lodge ambience.",
    "Cook up a narrated children's audiobook about a baby muskrat kit in a marsh, with prairie-fiddle BGM and prairie-marsh-cattail ambience.",
    "Generate a children's bedtime audiobook about a baby capybara pup at a Pantanal pond-edge, with Brazilian-pan-flute BGM and Pantanal-pond-edge ambience.",
    "Produce a kids' picture-book audiobook about a baby agouti pup in a Trinidadian forest, with Trinidadian-steel-pan BGM and Trinidadian-forest-floor ambience.",
    "Build an illustrated children's audiobook about a baby paca pup foraging in Belizean undergrowth, with Belizean-marimba BGM and Belizean-undergrowth ambience.",
    "Tell me a children's audiobook about a baby chipmunk pup on a New-England stone wall, with New-England-fiddle-3 BGM and New-England-stone-wall ambience.",
    "Make a narrated picture-book audiobook about a baby groundhog pup at a meadow-burrow, with American-folk-banjo BGM and American-meadow-burrow ambience.",
    "Cook up a children's audiobook about a baby prairie-dog pup on a Colorado prairie, with prairie-banjo BGM and Colorado-prairie-burrow ambience.",
    "Generate a kids' picture-book audiobook about a baby gerbil pup in a desert burrow, with Mongolian-morin-khuur BGM and Mongolian-steppe-burrow ambience.",
    "Produce a narrated children's audiobook about a baby Mongolian-jerboa pup on a steppe-night, with Mongolian-throat-singing BGM and Mongolian-steppe-night ambience.",
    "Build a bedtime audiobook about a baby kangaroo-rat pup in a Mojave-desert burrow, with Mojave-flute BGM and Mojave-desert-burrow ambience.",
    "Tell me an illustrated children's audiobook about a baby pika pup on an Alpine talus, with Alpine-fiddle BGM and Alpine-talus-meadow ambience.",
    "Make me a picture-book audiobook about a baby vole pup in an English meadow, with English-meadow-pizzicato BGM and English-meadow-grass ambience.",
    "Cook up a narrated children's audiobook about a baby lemming pup in Norwegian tundra, with Norwegian-Hardanger-fiddle-2 BGM and Norwegian-tundra-summer ambience.",
    "Generate a children's bedtime audiobook about a baby naked-mole-rat pup in a Kenyan tunnel, with Kenyan-flute BGM and Kenyan-soil-tunnel ambience.",
    "Produce a kids' picture-book audiobook about a baby flying-squirrel pup gliding under a moonlit pine, with Appalachian-fiddle-2 BGM and Appalachian-pine-night ambience.",
    "Build an illustrated children's audiobook about a baby red-squirrel pup chasing through a Scottish pinewood, with Scottish-bagpipe-2 BGM and Scottish-pinewood ambience.",
    "Tell me a children's audiobook about a baby grey-squirrel pup raiding a London park-bin, with London-piano BGM and London-park-morning ambience.",
    "Make a narrated picture-book audiobook about a baby Siberian-chipmunk pup on a taiga forest-floor, with Siberian-balalaika BGM and Siberian-taiga-floor ambience.",
    "Cook up a children's audiobook about a baby dormouse pup curled in a hazel-bush, with English-folk-pizzicato BGM and English-hazel-coppice ambience.",
    "Generate a kids' picture-book audiobook about a baby hedgehog pup snuffling under a hedge, with cozy-fiddle BGM and English-hedge-night ambience.",
    "Produce a narrated children's audiobook about a baby tenrec pup foraging on a Madagascan path, with Madagascan-valiha BGM and Madagascan-path-night ambience.",
    "Build a bedtime audiobook about a baby solenodon pup in a Hispaniolan forest, with Hispaniolan-folk BGM and Hispaniolan-forest-night ambience.",
    "Tell me an illustrated children's audiobook about a baby bat pup hanging in a Texan limestone cave, with Texan-fiddle BGM and Texan-cave-roost ambience.",
    "Make me a picture-book audiobook about a baby fruit-bat pup hanging from a fig tree, with Bornean-flute-2 BGM and Bornean-fig-grove-dusk ambience.",
    "Cook up a narrated children's audiobook about a baby vampire-bat pup in a Mexican cave, with Mexican-marimba-2 BGM and Mexican-cave-night ambience.",
    "Generate a children's bedtime audiobook about a baby flying-fox pup in a Queensland mangrove, with Queensland-didgeridoo BGM and Queensland-mangrove ambience.",
    "Produce a kids' picture-book audiobook about a baby short-tailed-bat pup foraging on a NZ flax, with NZ-koauau BGM and NZ-flax-night ambience.",
    "Build an illustrated children's audiobook about a baby koala joey clinging to a eucalyptus, with Australian-didgeridoo BGM and Australian-eucalyptus-canopy ambience.",
    "Tell me a children's audiobook about a baby wombat joey peeking from a burrow, with Australian-bush-folk BGM and Australian-bush-burrow ambience.",
    "Make a narrated picture-book audiobook about a baby Tasmanian-devil joey wrestling at dusk, with Tasmanian-folk BGM and Tasmanian-bush-dusk ambience.",
    "Cook up a children's audiobook about a baby bilby joey in an outback warren, with outback-fiddle-2 BGM and Australian-outback-warren ambience.",
    "Generate a kids' picture-book audiobook about a baby numbat joey foraging in a Western-Australian woodland, with WA-folk-flute BGM and WA-woodland ambience.",
    "Produce a narrated children's audiobook about a baby sugar-glider joey gliding in a Eucalypt forest, with Eucalypt-pizzicato BGM and Eucalypt-night-canopy ambience.",
    "Build a bedtime audiobook about a baby possum joey in a New-Zealand canopy, with NZ-flute-2 BGM and NZ-canopy-night ambience.",
    "Tell me an illustrated children's audiobook about a baby red-kangaroo joey on outback plains, with red-kangaroo-fiddle BGM and red-kangaroo-outback ambience.",
    "Make me a picture-book audiobook about a baby Eastern-grey-kangaroo joey grazing at dawn, with eastern-grey-fiddle BGM and eastern-grey-meadow-dawn ambience.",
    "Cook up a narrated children's audiobook about a baby tree-kangaroo joey on a Daintree branch, with Daintree-flute BGM and Daintree-canopy ambience.",
    # ── more baby big-cats / wild-felines + BGM + biome ambience (50) ──
    "Generate a kids' picture-book audiobook about a baby African-lion cub at a Maasai-Mara den, with Maasai-Mara-orchestral BGM and Maasai-Mara-acacia-den ambience.",
    "Produce a narrated children's audiobook about a baby Asiatic-lion cub at Gir-forest, with Gujarati-folk-2 BGM and Gir-forest ambience.",
    "Build a bedtime audiobook about a baby cheetah cub on a Kgalagadi dune, with Kgalagadi-folk BGM and Kgalagadi-dune ambience.",
    "Tell me an illustrated children's audiobook about a baby leopard cub on a Sabi-Sand branch, with Sabi-Sand-folk BGM and Sabi-Sand-canopy ambience.",
    "Make me a picture-book audiobook about a baby snow-leopard cub on a Hemis-ridge, with Hemis-Ladakhi-flute BGM and Hemis-ridge-snow ambience.",
    "Cook up a narrated children's audiobook about a baby clouded-leopard cub in a Borneo dipterocarp, with Bornean-Iban-sape BGM and Borneo-canopy-dusk ambience.",
    "Generate a children's bedtime audiobook about a baby Sunda-clouded-leopard in a Kerinci canopy, with Sumatran-folk-2 BGM and Kerinci-canopy ambience.",
    "Produce a kids' picture-book audiobook about a baby Bengal-tiger cub at a Ranthambore lake, with Hindustani-classical-3 BGM and Ranthambore-lake-edge ambience.",
    "Build an illustrated children's audiobook about a baby Sumatran-tiger cub in Way-Kambas, with Sumatran-talempong BGM and Way-Kambas-jungle ambience.",
    "Tell me a children's audiobook about a baby Amur-tiger cub on a Sikhote-Alin slope, with Russian-Far-Eastern-folk BGM and Sikhote-Alin-snow ambience.",
    "Make a narrated picture-book audiobook about a baby South-China-tiger cub in a Meihuashan reserve, with Chinese-pipa BGM and Meihuashan-bamboo ambience.",
    "Cook up a children's audiobook about a baby Indochinese-tiger cub in Cambodia's Cardamoms, with Khmer-tro-2 BGM and Cardamom-jungle ambience.",
    "Generate a kids' picture-book audiobook about a baby Caspian-tiger cub on a Hyrcanian forest-floor, with Persian-tar-2 BGM and Hyrcanian-forest ambience.",
    "Produce a narrated children's audiobook about a baby jaguar cub at a Pantanal pond, with Pantanal-fife BGM and Pantanal-pond-night ambience.",
    "Build a bedtime audiobook about a baby black-panther cub in a Periyar canopy, with Malayalam-mridangam BGM and Periyar-canopy ambience.",
    "Tell me an illustrated children's audiobook about a baby cougar cub on a Yellowstone bluff, with Rocky-Mountain-folk-2 BGM and Yellowstone-bluff-night ambience.",
    "Make me a picture-book audiobook about a baby Florida-panther cub in Big-Cypress, with Floridian-folk BGM and Big-Cypress-swamp-night ambience.",
    "Cook up a narrated children's audiobook about a baby ocelot cub on a Texan-brushland, with Tejano-conjunto-2 BGM and Texan-brushland-night ambience.",
    "Generate a children's bedtime audiobook about a baby margay cub on an Atlantic-Forest branch, with Brazilian-baião-2 BGM and Atlantic-Forest-canopy-2 ambience.",
    "Produce a kids' picture-book audiobook about a baby oncilla cub in a Costa-Rican cloud-forest, with Costa-Rican-folk BGM and Costa-Rican-cloud-forest ambience.",
    "Build an illustrated children's audiobook about a baby Geoffroy's-cat in Patagonian-pampas, with Patagonian-malambo-2 BGM and Patagonian-pampas ambience.",
    "Tell me a children's audiobook about a baby pampas-cat on Argentine-grassland, with Argentine-folklore-2 BGM and Argentine-grassland ambience.",
    "Make a narrated picture-book audiobook about a baby Andean-cat on Bolivian-altiplano, with Bolivian-charango-2 BGM and Bolivian-altiplano ambience.",
    "Cook up a children's audiobook about a baby kodkod in a Chiloé temperate-forest, with Chilote-cueca-2 BGM and Chiloé-temperate-forest ambience.",
    "Generate a kids' picture-book audiobook about a baby fishing-cat in a Sundarbans mangrove, with Bengali-baul-2 BGM and Sundarbans-mangrove-night ambience.",
    "Produce a narrated children's audiobook about a baby flat-headed-cat in a Borneo peat-swamp, with Iban-sape-2 BGM and Borneo-peat-swamp ambience.",
    "Build a bedtime audiobook about a baby rusty-spotted-cat in a Sri-Lankan dry-zone, with Sinhala-baila-2 BGM and Sri-Lankan-dry-zone-night ambience.",
    "Tell me an illustrated children's audiobook about a baby leopard-cat on a Bornean palm-plantation, with Bornean-folk BGM and Bornean-palm-plantation-night ambience.",
    "Make me a picture-book audiobook about a baby black-footed-cat in a Karoo den, with Karoo-folk-2 BGM and Karoo-night-burrow ambience.",
    "Cook up a narrated children's audiobook about a baby sand-cat in a Sahara dune, with Tuareg-imzad BGM and Sahara-dune-night ambience.",
    "Generate a children's bedtime audiobook about a baby caracal cub in Kalahari sand, with San-musical-bow BGM and Kalahari-sand-burrow ambience.",
    "Produce a kids' picture-book audiobook about a baby serval cub in Ngorongoro grass, with Maasai-osingolio-3 BGM and Ngorongoro-grassland ambience.",
    "Build an illustrated children's audiobook about a baby African-golden-cat in a Bwindi canopy, with Bwindi-thumb-piano BGM and Bwindi-canopy-night ambience.",
    "Tell me a children's audiobook about a baby Asian-golden-cat in Xishuangbanna, with Yunnan-folk-2 BGM and Xishuangbanna-canopy ambience.",
    "Make a narrated picture-book audiobook about a baby Pallas's-cat on Mongolian-steppe, with Mongolian-morin-khuur-2 BGM and Mongolian-steppe-burrow ambience.",
    "Cook up a children's audiobook about a baby Eurasian-lynx cub in a Bialowieza forest, with Polish-folk-2 BGM and Bialowieza-forest ambience.",
    "Generate a kids' picture-book audiobook about a baby Iberian-lynx cub in Coto-Doñana, with Andalusian-flamenco-2 BGM and Coto-Doñana-cork-oak ambience.",
    "Produce a narrated children's audiobook about a baby Canada-lynx cub in a Boreal-forest, with Canadian-folk-fiddle BGM and Boreal-forest-snow ambience.",
    "Build a bedtime audiobook about a baby bobcat kit in a Sonoran desert wash, with Sonoran-folk BGM and Sonoran-wash-night ambience.",
    "Tell me an illustrated children's audiobook about a baby jaguarundi cub in Ramsar coastal-scrub, with Ramsar-coastal-folk BGM and Ramsar-coastal-scrub ambience.",
    "Make me a picture-book audiobook about a baby manul kitten on a Tibetan plateau, with Tibetan-dranyen BGM and Tibetan-plateau-burrow ambience.",
    "Cook up a narrated children's audiobook about a baby clouded-tiger-cat-Andean in cloud-forest, with Andean-charango-2 BGM and Andean-cloud-forest ambience.",
    "Generate a children's bedtime audiobook about a baby Mexican-jaguarundi cub in Yucatán-thornscrub, with Yucatán-jarana BGM and Yucatán-thornscrub-night ambience.",
    "Produce a kids' picture-book audiobook about a baby Borneo-bay-cat on a peat-swamp branch, with Bornean-sape-2 BGM and Borneo-peat-canopy ambience.",
    "Build an illustrated children's audiobook about a baby Iriomote-cat on a Yaeyama coastline, with Yaeyama-shanshin BGM and Yaeyama-coast-night ambience.",
    "Tell me a children's audiobook about a baby Andean-mountain-cat on a Quechua-plateau, with Andean-quena-2 BGM and Quechua-plateau-burrow ambience.",
    "Make a narrated picture-book audiobook about a baby ocelot-Yucatán in Calakmul rainforest, with Yucatán-folk BGM and Calakmul-rainforest-night ambience.",
    "Cook up a children's audiobook about a baby tiger-cub-Sundarbans-Bengal in mangrove channel, with Bengali-baul-3 BGM and Bengal-mangrove-night ambience.",
    "Generate a kids' picture-book audiobook about a baby Persian-leopard cub on a Zagros ridge, with Persian-setar BGM and Zagros-ridge-night ambience.",
    "Produce a narrated children's audiobook about a baby Arabian-leopard cub on a Wadi-Aïn Mahdah, with Bedouin-rebab-3 BGM and Wadi-Aïn-Mahdah-night ambience.",
    # ── more baby raptor / owl / parrot / songbird stories + BGM + sky/forest ambience (50) ──
    "Tell me a children's audiobook about a baby bald-eagle eaglet on a Chesapeake-Bay-pine, with Chesapeake-Bay-folk BGM and Chesapeake-Bay-pine-nest ambience.",
    "I want an illustrated audiobook about a baby golden-eagle eaglet on a Scottish-Highlands-cliff, with Highland-bagpipe BGM and Scottish-Highlands-cliff-nest ambience.",
    "Make me a bedtime audiobook about a baby Steller's-sea-eagle eaglet on a Kamchatka-coast, with Kamchatkan-Itelmen-drum BGM and Kamchatka-coast-cliff-nest ambience.",
    "Create a picture-book audiobook about a baby harpy-eagle eaglet on a Darien-rainforest-emergent-tree, with Darién-Embera-flute BGM and Darien-rainforest-canopy ambience.",
    "Produce an illustrated children's tale about a baby Philippine-eagle eaglet on a Mt-Apo-canopy, with Bagobo-kulintang BGM and Mt-Apo-canopy-nest ambience.",
    "Cook up a narrated children's audiobook about a baby crowned-eagle eaglet on an Ituri-forest-emergent, with Mbuti-pygmy-flute BGM and Ituri-forest-emergent-nest ambience.",
    "Generate a kids' picture-book audiobook about a baby martial-eagle eaglet on a Kalahari-acacia, with San-bow-song BGM and Kalahari-acacia-nest ambience.",
    "Build a bedtime audiobook about a baby Verreaux's-eagle eaglet on a Walter-Sisulu-cliff, with Sotho-folk BGM and Walter-Sisulu-cliff-nest ambience.",
    "Tell me an illustrated children's audiobook about a baby imperial-eagle eaglet on a Doñana-cork-oak, with Andalusian-flamenco-2 BGM and Doñana-cork-oak-nest ambience.",
    "Make me a picture-book audiobook about a baby Bonelli's-eagle eaglet on a Pyrenean-cliff, with Pyrenean-Catalan-folk BGM and Pyrenean-cliff-nest ambience.",
    "Cook up a children's audiobook about a baby short-toed-eagle eaglet on a Provence-pine, with Provençal-folk-2 BGM and Provence-pine-nest ambience.",
    "Produce a narrated children's audiobook about a baby osprey chick on a Cape-Cod-platform, with Cape-Cod-folk BGM and Cape-Cod-platform-nest ambience.",
    "Generate a kids' picture-book audiobook about a baby Andean-condor chick on a Colca-Canyon-cliff, with Andean-quena-3 BGM and Colca-Canyon-cliff-nest ambience.",
    "Build a bedtime audiobook about a baby California-condor chick on a Big-Sur-redwood-snag, with Big-Sur-folk BGM and Big-Sur-redwood-snag-nest ambience.",
    "Tell me an illustrated children's audiobook about a baby gyrfalcon chick on a Greenland-tundra-cliff, with Greenlandic-Inuit-drum-2 BGM and Greenland-tundra-cliff-nest ambience.",
    "Make me a picture-book audiobook about a baby peregrine-falcon chick on a Manhattan-skyscraper-ledge, with Manhattan-jazz BGM and Manhattan-skyscraper-ledge-nest ambience.",
    "Cook up a children's audiobook about a baby saker-falcon chick on a Hortobágy-puszta-snag, with Magyar-puszta-folk BGM and Hortobágy-puszta-snag-nest ambience.",
    "I want an illustrated audiobook about a baby snowy-owl chick on the Hudson-Bay-Lowlands-tundra, with Cree-folk BGM and Hudson-Bay-Lowlands-tundra-nest ambience.",
    "Make me a bedtime audiobook about a baby great-grey-owl chick on a Yellowstone-Northwest-Forest, with Yellowstone-Shoshone-flute BGM and Yellowstone-Northwest-Forest-nest ambience.",
    "Create a picture-book audiobook about a baby Eurasian-eagle-owl chick on a Bavarian-cliff, with Bavarian-zither BGM and Bavarian-cliff-nest ambience.",
    "Produce an illustrated children's tale about a baby Blakiston's-fish-owl chick on a Hokkaido-river-tree, with Ainu-tonkori BGM and Hokkaido-river-tree-nest ambience.",
    "Cook up a narrated children's audiobook about a baby Pel's-fishing-owl chick on a Chobe-River-fig-tree, with Chobe-Tswana-folk BGM and Chobe-River-fig-tree-nest ambience.",
    "Generate a kids' picture-book audiobook about a baby spectacled-owl chick on a Costa-Rican-Cloud-forest-emergent, with Costa-Rican-marimba BGM and Costa-Rican-Cloud-forest-emergent ambience.",
    "Build a bedtime audiobook about a baby tawny-owl chick in a Hampstead-Heath-oak, with English-folk BGM and Hampstead-Heath-oak-nest ambience.",
    "Tell me an illustrated children's audiobook about a baby barn-owl chick in a Suffolk-barn-loft, with Suffolk-folk BGM and Suffolk-barn-loft-nest ambience.",
    "Make me a picture-book audiobook about a baby long-eared-owl chick in a Negev-acacia, with Negev-Bedouin-rebaba BGM and Negev-acacia-nest ambience.",
    "Cook up a children's audiobook about a baby short-eared-owl chick on a Hokkaido-grassland, with Ainu-mukkuri BGM and Hokkaido-grassland-nest ambience.",
    "Produce a narrated children's audiobook about a baby Eurasian-pygmy-owl chick in a Norwegian-spruce-cavity, with Norwegian-hardingfele BGM and Norwegian-spruce-cavity-nest ambience.",
    "Generate a kids' picture-book audiobook about a baby boreal-owl chick in a Rocky-Mountain-aspen-cavity, with Colorado-folk BGM and Rocky-Mountain-aspen-cavity ambience.",
    "Build a bedtime audiobook about a baby burrowing-owl chick in a South-Florida-prairie-burrow, with Florida-Seminole-flute BGM and South-Florida-prairie-burrow ambience.",
    "Tell me an illustrated children's audiobook about a baby kakapo chick on a Codfish-Island-tussock, with Maori-koauau BGM and Codfish-Island-tussock-nest ambience.",
    "Make me a picture-book audiobook about a baby kea chick on a Mt-Cook-alpine-rock, with Mt-Cook-Maori-folk BGM and Mt-Cook-alpine-rock-nest ambience.",
    "Cook up a children's audiobook about a baby hyacinth-macaw chick in a Pantanal-manduvi-tree-cavity, with Pantanal-rasqueado-3 BGM and Pantanal-manduvi-cavity ambience.",
    "Produce a narrated children's audiobook about a baby scarlet-macaw chick in a Tambopata-clay-cliff, with Tambopata-Quechua-flute BGM and Tambopata-clay-cliff-nest ambience.",
    "Generate a kids' picture-book audiobook about a baby blue-and-yellow-macaw chick in a Cristalino-rainforest, with Cristalino-Amazonian-flute BGM and Cristalino-rainforest-cavity-nest ambience.",
    "Build a bedtime audiobook about a baby Spix's-macaw chick on a Curaçá-caatinga-tree, with Caatinga-Bahian-forró BGM and Curaçá-caatinga-tree-nest ambience.",
    "Tell me an illustrated children's audiobook about a baby Lear's-macaw chick on a Canudos-cliff, with Canudos-Bahian-forró BGM and Canudos-cliff-nest ambience.",
    "Make me a picture-book audiobook about a baby palm-cockatoo chick in a Cape-York-eucalyptus, with Cape-York-Aboriginal-didjeridu BGM and Cape-York-eucalyptus-cavity ambience.",
    "Cook up a children's audiobook about a baby gang-gang-cockatoo chick in a Tidbinbilla-tree-cavity, with Tidbinbilla-Aboriginal-clapsticks BGM and Tidbinbilla-tree-cavity-nest ambience.",
    "Produce a narrated children's audiobook about a baby red-tailed-black-cockatoo chick in a Carnarvon-eucalyptus, with Carnarvon-Aboriginal-flute BGM and Carnarvon-eucalyptus-cavity ambience.",
    "Generate a kids' picture-book audiobook about a baby keel-billed-toucan chick in a Belize-fig-tree-cavity, with Belizean-marimba-2 BGM and Belize-fig-tree-cavity-nest ambience.",
    "Build a bedtime audiobook about a baby toco-toucan chick in a Cerrado-tree-cavity, with Cerrado-sertaneja BGM and Cerrado-tree-cavity-nest ambience.",
    "Tell me an illustrated children's audiobook about a baby quetzal chick in a Monteverde-cloud-forest-snag, with Monteverde-Costa-Rican-marimba BGM and Monteverde-cloud-forest-snag ambience.",
    "Make me a picture-book audiobook about a baby Andean-cock-of-the-rock chick on a Manú-cliff-cave, with Manú-Quechua-quena BGM and Manú-cliff-cave-nest ambience.",
    "Cook up a children's audiobook about a baby Guianan-cock-of-the-rock chick on a Kaieteur-cliff-cave, with Kaieteur-Akawaio-flute BGM and Kaieteur-cliff-cave-nest ambience.",
    "Produce a narrated children's audiobook about a baby hoatzin chick in a Manú-flooded-forest-vine, with Manú-Amazonian-flute BGM and Manú-flooded-forest-vine ambience.",
    "Generate a kids' picture-book audiobook about a baby kingfisher chick in a Wye-Valley-river-bank-burrow, with Welsh-harp BGM and Wye-Valley-river-bank-burrow ambience.",
    "Build a bedtime audiobook about a baby pileated-woodpecker chick in a Great-Smoky-Mountain-snag, with Smoky-Mountain-bluegrass BGM and Great-Smoky-Mountain-snag-cavity ambience.",
    "Tell me an illustrated children's audiobook about a baby ivory-billed-woodpecker chick on a Singer-Tract-archive, with Louisiana-Cajun-fiddle BGM and Singer-Tract-archive-snag ambience.",
    "Make me a picture-book audiobook about a baby red-cockaded-woodpecker chick in a Croatan-longleaf-pine, with North-Carolina-old-time BGM and Croatan-longleaf-pine-cavity ambience.",
    # ── more baby insect / butterfly / arachnid stories + BGM + meadow/garden ambience (50) ──
    "Tell me a children's audiobook about a baby monarch-butterfly caterpillar on a Texas-Hill-Country-milkweed, with Texas-Hill-Country-fiddle BGM and Texas-Hill-Country-milkweed-morning-2 ambience.",
    "I want an illustrated audiobook about a baby swallowtail-butterfly caterpillar on a Florida-fennel-stem, with Florida-Cracker-fiddle BGM and Florida-fennel-stem-morning-2 ambience.",
    "Make me a bedtime audiobook about a baby morpho-butterfly caterpillar on an Amazon-Kapok-leaf, with Amazon-Kapok-flute BGM and Amazon-Kapok-leaf-morning-2 ambience.",
    "Create a picture-book audiobook about a baby zebra-longwing-butterfly caterpillar on a Bocas-del-Toro-passion-vine, with Bocas-del-Toro-mejorana-2 BGM and Bocas-del-Toro-passion-vine-2 ambience.",
    "Produce an illustrated children's tale about a baby glasswing-butterfly caterpillar on a Costa-Rican-Solanum, with Costa-Rican-marimba-4 BGM and Costa-Rican-Solanum-morning-2 ambience.",
    "Cook up a narrated children's audiobook about a baby owl-butterfly caterpillar on a Trinidad-banana-leaf, with Trinidad-soca-pan-2 BGM and Trinidad-banana-leaf-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby red-postman-butterfly caterpillar on a Manuel-Antonio-passion-vine, with Manuel-Antonio-marimba BGM and Manuel-Antonio-passion-vine-morning-2 ambience.",
    "Build a bedtime audiobook about a baby Atlas-moth caterpillar on a Borneo-cinnamon-leaf, with Borneo-Iban-sape-2 BGM and Borneo-cinnamon-leaf-night-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby luna-moth caterpillar on a Smoky-Mountain-walnut-leaf, with Smoky-Mountain-old-time-2 BGM and Smoky-Mountain-walnut-leaf-night-2 ambience.",
    "Make me a picture-book audiobook about a baby silkworm caterpillar on a Suzhou-mulberry-leaf, with Suzhou-pingtan-2 BGM and Suzhou-mulberry-leaf-morning-2 ambience.",
    "Cook up a children's audiobook about a baby honeybee larva in a Provençal-lavender-hive, with Provençal-musette-2 BGM and Provençal-lavender-hive-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby leafcutter-bee larva in a Sonoran-cottonwood-cell, with Sonoran-Pima-folk-2 BGM and Sonoran-cottonwood-cell-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby mason-bee larva in a Tuscan-stone-wall-tube, with Tuscan-stornello BGM and Tuscan-stone-wall-tube-morning-2 ambience.",
    "Build a bedtime audiobook about a baby orchid-bee larva in a Costa-Rican-orchid-cup, with Costa-Rican-quitiplas BGM and Costa-Rican-orchid-cup-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby sweat-bee larva on a North-Dakota-prairie-flower, with North-Dakota-Plains-fiddle BGM and North-Dakota-prairie-flower-2 ambience.",
    "Make me a picture-book audiobook about a baby giant-leafcutter-ant grub in a Pantanal-tree-canopy-nest, with Pantanal-rasqueado-4 BGM and Pantanal-tree-canopy-nest-morning-2 ambience.",
    "Cook up a children's audiobook about a baby weaver-ant grub on a Vietnamese-mango-leaf, with Vietnamese-đàn-bầu-2 BGM and Vietnamese-mango-leaf-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby Argentine-ant grub in a Mendoza-vineyard-soil, with Cuyo-folk BGM and Mendoza-vineyard-soil-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby army-ant grub in a Cocha-Cashu-bivouac, with Cocha-Cashu-Quechua-flute BGM and Cocha-Cashu-bivouac-night-2 ambience.",
    "Build a bedtime audiobook about a baby leafcutter-ant grub in a Soberanía-tree-soil-tunnel, with Panamanian-mejorana-2 BGM and Soberanía-tree-soil-tunnel-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby firefly larva in a Smoky-Mountain-Synchronous-meadow, with Smoky-Mountain-old-time-3 BGM and Smoky-Mountain-Synchronous-meadow-night-2 ambience.",
    "Make me a picture-book audiobook about a baby glow-worm larva in a Waitomo-cave-thread, with Waitomo-Maori-koauau BGM and Waitomo-cave-thread-night-2 ambience.",
    "Cook up a children's audiobook about a baby cicada nymph on a Cicadas-of-Brood-X-Maryland-root, with Maryland-old-time BGM and Brood-X-Maryland-root-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby dragonfly nymph in a Norfolk-Broads-pond, with Norfolk-fiddle BGM and Norfolk-Broads-pond-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby damselfly nymph in a Cévennes-stream, with Cévennes-cabrette-2 BGM and Cévennes-stream-morning-2 ambience.",
    "Build a bedtime audiobook about a baby praying-mantis nymph on a California-poppy-stem, with California-poppy-strings BGM and California-poppy-stem-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby orchid-mantis nymph on a Sumatran-orchid-petal, with Sumatran-Batak-gondang-2 BGM and Sumatran-orchid-petal-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby walking-stick nymph on a Eucalyptus-twig-Tasmania, with Tasmanian-folk-fiddle BGM and Eucalyptus-twig-Tasmania-morning-2 ambience.",
    "Cook up a children's audiobook about a baby leaf-insect nymph on a Bornean-Macaranga-leaf, with Bornean-Iban-sape-3 BGM and Bornean-Macaranga-leaf-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby ladybug larva on a Cotswold-aphid-cluster, with Cotswold-fiddle BGM and Cotswold-aphid-cluster-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby stag-beetle larva in a Burnham-Beeches-oak-log, with Burnham-Beeches-fife BGM and Burnham-Beeches-oak-log-2 ambience.",
    "Build a bedtime audiobook about a baby dung-beetle larva in a Maasai-Mara-dung-ball, with Maasai-vocal-2 BGM and Maasai-Mara-dung-ball-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby goliath-beetle larva in a Cameroonian-rotten-log, with Cameroonian-makossa-2 BGM and Cameroonian-rotten-log-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby Hercules-beetle larva in a Costa-Rican-rotten-log, with Costa-Rican-marimba-5 BGM and Costa-Rican-rotten-log-morning-2 ambience.",
    "Cook up a children's audiobook about a baby Atlas-beetle larva in a Sumatran-rainforest-log, with Sumatran-saluang BGM and Sumatran-rainforest-log-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby tarantula spiderling on a Texas-Hill-Country-burrow, with Texas-Hill-Country-fiddle-2 BGM and Texas-Hill-Country-burrow-night-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby Goliath-bird-eater spiderling in a Guianan-burrow, with Guianan-folk-flute BGM and Guianan-burrow-night-2 ambience.",
    "Build a bedtime audiobook about a baby Sydney-funnel-web spiderling in a Royal-National-Park-burrow, with Sydney-Aboriginal-clapsticks BGM and Royal-National-Park-burrow-night-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby Brazilian-wandering-spider spiderling on a banana-leaf, with Pernambucano-frevo-2 BGM and banana-leaf-Pernambuco-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby orb-weaver spiderling on a Cotswold-hedgerow, with Cotswold-folk-fiddle-2 BGM and Cotswold-hedgerow-morning-2 ambience.",
    "Cook up a children's audiobook about a baby jumping-spider spiderling on a London-park-bench, with London-park-piano BGM and London-park-bench-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby peacock-spider spiderling on an Australian-coastal-heath, with Australian-coastal-heath-folk BGM and Australian-coastal-heath-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby crab-spider spiderling on a Pyrenean-meadow-flower, with Pyrenean-Catalan-folk-2 BGM and Pyrenean-meadow-flower-morning-2 ambience.",
    "Build a bedtime audiobook about a baby scorpion baby on a Sahara-rock-shadow, with Saharan-imzad-2 BGM and Sahara-rock-shadow-night-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby emperor-scorpion baby in a Senegalese-savanna-burrow, with Senegalese-mbalax-2 BGM and Senegalese-savanna-burrow-night-2 ambience.",
    "Make me a picture-book audiobook about a baby Death-Stalker-scorpion baby in a Negev-rock, with Negev-Bedouin-rebaba-2 BGM and Negev-rock-night-2 ambience.",
    "Cook up a children's audiobook about a baby Brazilian-yellow-scorpion baby in a São-Paulo-garden, with São-Paulo-samba-paulista-2 BGM and São-Paulo-garden-night-2 ambience.",
    "Produce a narrated children's audiobook about a baby Madagascar-hissing-cockroach nymph in a Andasibe-leaf-litter, with Andasibe-valiha-3 BGM and Andasibe-leaf-litter-night-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby American-cockroach nymph in a Charleston-attic, with Charleston-Gullah-spiritual-2 BGM and Charleston-attic-night-2 ambience.",
    "Build a bedtime audiobook about a baby periodical-cicada nymph emerging in a Long-Island-suburb, with Long-Island-fiddle BGM and Long-Island-suburb-emergence-2 ambience.",
    # ── more baby rodent / lagomorph / small-mammal stories + BGM + woodland/meadow ambience (50) ──
    "Tell me a children's audiobook about a baby European-rabbit kit in a Norfolk-Broads-warren, with Norfolk-fiddle-2 BGM and Norfolk-Broads-warren-morning-2 ambience.",
    "I want an illustrated audiobook about a baby cottontail kit in a Cape-Cod-meadow, with Cape-Cod-folk-3 BGM and Cape-Cod-meadow-morning-2 ambience.",
    "Make me a bedtime audiobook about a baby snowshoe-hare leveret in a Yukon-spruce-thicket, with Yukon-folk BGM and Yukon-spruce-thicket-morning-2 ambience.",
    "Create a picture-book audiobook about a baby Arctic-hare leveret on Ellesmere-Island, with Inuit-throat-singing-5 BGM and Ellesmere-Island-tundra-morning-2 ambience.",
    "Produce an illustrated children's tale about a baby black-tailed-jackrabbit leveret in a Sonoran-creosote-flat, with Sonoran-norteño BGM and Sonoran-creosote-flat-morning-2 ambience.",
    "Cook up a narrated children's audiobook about a baby pika in a Bridger-Teton-talus, with Bridger-Teton-fiddle BGM and Bridger-Teton-talus-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby Plateau-pika on the Tibetan-grassland, with Tibetan-dranyen-2 BGM and Tibetan-grassland-morning-2 ambience.",
    "Build a bedtime audiobook about a baby Eastern-grey-squirrel kit in a Central-Park-oak, with Central-Park-piano BGM and Central-Park-oak-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby red-squirrel kit in a Cairngorms-pine, with Highland-fiddle BGM and Cairngorms-pine-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby flying-squirrel kit in a Smoky-Mountain-snag, with Smoky-Mountain-bluegrass-3 BGM and Smoky-Mountain-snag-night-2 ambience.",
    "Cook up a children's audiobook about a baby Japanese-flying-squirrel kit on a Hokkaido-spruce, with Ainu-tonkori-2 BGM and Hokkaido-spruce-night-2 ambience.",
    "Produce a narrated children's audiobook about a baby chipmunk kit in a Vermont-stone-wall, with Vermont-folk-fiddle BGM and Vermont-stone-wall-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby Siberian-chipmunk kit in a Primorsky-pine, with Primorsky-folk BGM and Primorsky-pine-morning-2 ambience.",
    "Build a bedtime audiobook about a baby groundhog kit in a Pennsylvania-hayfield-burrow, with Pennsylvania-folk BGM and Pennsylvania-hayfield-burrow-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby Alpine-marmot kit in a Mont-Blanc-meadow-burrow, with Savoyard-fiddle BGM and Mont-Blanc-meadow-burrow-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby yellow-bellied-marmot kit on a Glacier-National-Park-talus, with Montana-folk BGM and Glacier-National-Park-talus-morning-2 ambience.",
    "Cook up a children's audiobook about a baby prairie-dog pup on a South-Dakota-Badlands-prairie, with Lakota-flute-2 BGM and South-Dakota-Badlands-prairie-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby black-tailed-prairie-dog pup on a Wind-Cave-South-Dakota, with Sioux-fiddle BGM and Wind-Cave-South-Dakota-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby beaver kit in a Yellowstone-pond-lodge, with Yellowstone-Shoshone-flute-2 BGM and Yellowstone-pond-lodge-morning-2 ambience.",
    "Build a bedtime audiobook about a baby Eurasian-beaver kit in a Bavarian-Forest-stream-lodge, with Bavarian-zither-2 BGM and Bavarian-Forest-stream-lodge-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby muskrat kit in a Cape-May-marsh-lodge, with Cape-May-folk BGM and Cape-May-marsh-lodge-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby porcupine kit in a New-Hampshire-hemlock-grove, with New-Hampshire-folk BGM and New-Hampshire-hemlock-grove-night-2 ambience.",
    "Cook up a children's audiobook about a baby Cape-porcupine kit in a Drakensberg-grassland-burrow, with Zulu-isigubhu-2 BGM and Drakensberg-grassland-burrow-night-2 ambience.",
    "Produce a narrated children's audiobook about a baby Indian-crested-porcupine kit in a Ranthambore-grass-burrow, with Rajasthani-tabla BGM and Ranthambore-grass-burrow-night-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby capybara pup in a Pantanal-river-bank, with Pantanal-rasqueado-5 BGM and Pantanal-river-bank-morning-2 ambience.",
    "Build a bedtime audiobook about a baby agouti pup in a Soberanía-rainforest-floor, with Soberanía-Embera-flute BGM and Soberanía-rainforest-floor-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby paca pup in a Costa-Rican-stream-burrow, with Costa-Rican-marimba-6 BGM and Costa-Rican-stream-burrow-night-2 ambience.",
    "Make me a picture-book audiobook about a baby coypu pup in a Camargue-marsh-lodge, with Camargue-folk BGM and Camargue-marsh-lodge-morning-2 ambience.",
    "Cook up a children's audiobook about a baby kangaroo-rat pup in a Carrizo-Plain-burrow, with Carrizo-Plain-Yokuts-flute BGM and Carrizo-Plain-burrow-night-2 ambience.",
    "Produce a narrated children's audiobook about a baby pocket-mouse pup in a Sonoran-cactus-burrow, with Sonoran-Tohono-O'odham-flute BGM and Sonoran-cactus-burrow-night-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby jerboa pup on the Karakum-desert-burrow, with Turkmen-dutar-2 BGM and Karakum-desert-burrow-night-2 ambience.",
    "Build a bedtime audiobook about a baby gerbil pup on a Mongolian-Gobi-burrow, with Mongolian-morin-khuur-2 BGM and Mongolian-Gobi-burrow-night-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby vole pup in a Yorkshire-hedgerow, with Yorkshire-folk BGM and Yorkshire-hedgerow-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby harvest-mouse pup in a Sussex-wheat-field, with Sussex-folk BGM and Sussex-wheat-field-morning-2 ambience.",
    "Cook up a children's audiobook about a baby field-mouse pup in a Cotswold-meadow, with Cotswold-folk-fiddle-3 BGM and Cotswold-meadow-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby dormouse pup in a Welsh-hazel-coppice, with Welsh-harp-2 BGM and Welsh-hazel-coppice-night-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby hazel-dormouse pup in a Sussex-bramble, with Sussex-folk-2 BGM and Sussex-bramble-night-2 ambience.",
    "Build a bedtime audiobook about a baby edible-dormouse pup in a Surrey-beech, with Surrey-folk BGM and Surrey-beech-night-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby red-panda kit in a Singalila-bamboo-forest, with Sikkimese-folk BGM and Singalila-bamboo-forest-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby ringtail kit in a Big-Bend-sotol-canyon, with Tex-Mex-norteño BGM and Big-Bend-sotol-canyon-night-2 ambience.",
    "Cook up a children's audiobook about a baby coati pup in a Manuel-Antonio-canopy, with Manuel-Antonio-marimba-2 BGM and Manuel-Antonio-canopy-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby kinkajou pup in a Costa-Rican-Sarapiquí-canopy, with Costa-Rican-Sarapiquí-marimba BGM and Costa-Rican-Sarapiquí-canopy-night-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby olingo pup in a Soberanía-mid-canopy, with Soberanía-Embera-flute-2 BGM and Soberanía-mid-canopy-night-2 ambience.",
    "Build a bedtime audiobook about a baby Eurasian-red-fox kit in a Hampstead-Heath-den, with Hampstead-Heath-folk BGM and Hampstead-Heath-den-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby fennec-fox kit in a Tunisian-Sahara-burrow, with Tunisian-malouf-2 BGM and Tunisian-Sahara-burrow-night-2 ambience.",
    "Make me a picture-book audiobook about a baby Arctic-fox kit on a Svalbard-tundra-den, with Svalbard-folk-2 BGM and Svalbard-tundra-den-morning-2 ambience.",
    "Cook up a children's audiobook about a baby kit-fox kit in a Carrizo-Plain-fox-burrow, with Carrizo-Plain-Yokuts-flute-2 BGM and Carrizo-Plain-fox-burrow-night-2 ambience.",
    "Produce a narrated children's audiobook about a baby bat-eared-fox kit on a Maasai-Mara-termite-mound, with Maasai-vocal-6 BGM and Maasai-Mara-termite-mound-night-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby maned-wolf pup on a Cerrado-grass, with Cerrado-sertaneja-2 BGM and Cerrado-grass-night-2 ambience.",
    "Build a bedtime audiobook about a baby African-wild-dog pup in a Mana-Pools-floodplain-den, with Mana-Pools-Shona-mbira BGM and Mana-Pools-floodplain-den-morning-2 ambience.",
    # ── more baby birds + BGM + tundra/cliff ambience (50) ──
    "Tell me an illustrated children's audiobook about a baby bald-eagle eaglet in a Skagit-River-cottonwood-nest, with Salish-cedar-flute BGM and Skagit-River-cottonwood-nest-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby golden-eagle eaglet on a Cairngorms-cliff-eyrie, with Scottish-fiddle BGM and Cairngorms-cliff-eyrie-morning-2 ambience.",
    "Cook up a children's audiobook about a baby Steller's-sea-eagle eaglet on a Kamchatka-coastal-pine, with Itelmen-tymtin BGM and Kamchatka-coastal-pine-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby Philippine-eagle eaglet in a Mount-Apo-canopy, with Manobo-kulintang BGM and Mount-Apo-canopy-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby harpy-eagle eaglet in a Darién-canopy, with Embera-flute BGM and Darién-canopy-morning-2 ambience.",
    "Build a bedtime audiobook about a baby snowy-owl owlet on a Wapusk-tundra, with Cree-frame-drum BGM and Wapusk-tundra-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby great-horned-owl owlet on a Tucson-saguaro-nest, with Tohono-O'odham-flute BGM and Tucson-saguaro-nest-night-2 ambience.",
    "Make me a picture-book audiobook about a baby barn-owl owlet in a Cotswold-barn-loft, with English-folk-melodeon BGM and Cotswold-barn-loft-night-2 ambience.",
    "Cook up a children's audiobook about a baby Eurasian-eagle-owl owlet on a Bavarian-Donautal-cliff, with Bavarian-zither BGM and Bavarian-Donautal-cliff-night-2 ambience.",
    "Produce a narrated children's audiobook about a baby burrowing-owl owlet on a Texas-Llano-Estacado-burrow, with Tex-Mex-norteno BGM and Llano-Estacado-burrow-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby spectacled-owl owlet in a Manú-Peru-canopy, with Quechua-quena-4 BGM and Manú-canopy-night-2 ambience.",
    "Build a bedtime audiobook about a baby tawny-owl owlet on an Ashdown-Forest-oak, with English-recorder BGM and Ashdown-Forest-oak-night-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby long-eared-owl owlet on a Hortobágy-Hungary-pine, with Hungarian-cimbalom BGM and Hortobágy-pine-night-2 ambience.",
    "Make me a picture-book audiobook about a baby boreal-owl owlet in a Karelian-spruce-cavity, with Karelian-kantele BGM and Karelian-spruce-cavity-night-2 ambience.",
    "Cook up a children's audiobook about a baby mallard duckling on a Norfolk-Broads-reedbed, with English-folk-melodeon-2 BGM and Norfolk-Broads-reedbed-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby mandarin-duck duckling on a Beijing-Yiheyuan-pond, with Chinese-pipa-3 BGM and Yiheyuan-pond-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby wood-duck duckling in a Smoky-Mountain-stream, with Appalachian-dulcimer BGM and Smoky-Mountain-stream-morning-2 ambience.",
    "Build a bedtime audiobook about a baby Muscovy-duck duckling in a Pantanal-floodplain, with Pantanaleiro-viola-2 BGM and Pantanal-floodplain-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby emperor-penguin chick on a Snow-Hill-Antarctica-rookery, with Antarctic-station-folk BGM and Snow-Hill-rookery-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby king-penguin chick on a South-Georgia-Salisbury-Plain-rookery, with Falklands-fiddle BGM and Salisbury-Plain-rookery-morning-2 ambience.",
    "Cook up a children's audiobook about a baby Adélie-penguin chick on a Cape-Adare-rookery, with Antarctic-explorer-shanty BGM and Cape-Adare-rookery-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby gentoo-penguin chick on a Falkland-Saunders-Island-rookery, with Falklands-bagpipe BGM and Saunders-Island-rookery-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby chinstrap-penguin chick on a Deception-Island-rookery, with Antarctic-explorer-folk BGM and Deception-Island-rookery-morning-2 ambience.",
    "Build a bedtime audiobook about a baby rockhopper-penguin chick on a Falkland-West-Point-Island-cliff, with Falklands-fiddle-2 BGM and West-Point-Island-cliff-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby Galapagos-penguin chick on a Fernandina-lava-rocks, with Ecuadorian-rondador-2 BGM and Fernandina-lava-rocks-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby African-penguin chick on a Boulders-Beach-Cape-Town, with Cape-jazz BGM and Boulders-Beach-morning-2 ambience.",
    "Cook up a children's audiobook about a baby Magellanic-penguin chick on a Punta-Tombo-Patagonia-burrow, with Argentine-folklore-zamba BGM and Punta-Tombo-burrow-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby ostrich chick on a Etosha-pan-savanna, with Himba-ondoroka BGM and Etosha-pan-savanna-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby emu chick on a Western-Australia-mulga-shrubland, with Aboriginal-clapsticks-2 BGM and Western-Australia-mulga-morning-2 ambience.",
    "Build a bedtime audiobook about a baby cassowary chick in a Daintree-rainforest-floor, with Aboriginal-yidaki-2 BGM and Daintree-rainforest-floor-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby kiwi chick in a Stewart-Island-Rakiura-burrow, with Maori-koauau-2 BGM and Stewart-Island-burrow-night-2 ambience.",
    "Make me a picture-book audiobook about a baby kakapo chick on a Whenua-Hou-Codfish-Island-burrow, with Maori-poi BGM and Whenua-Hou-burrow-night-2 ambience.",
    "Cook up a children's audiobook about a baby kea fledgling on a Mount-Cook-alpine-meadow, with Maori-purerehua BGM and Mount-Cook-alpine-meadow-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby tūī fledgling on a Tiritiri-Matangi-pohutukawa-tree, with Maori-koauau-3 BGM and Tiritiri-Matangi-pohutukawa-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby New-Zealand-fantail fledgling on a Wellington-Zealandia-canopy, with Maori-haka-vocals BGM and Zealandia-canopy-morning-2 ambience.",
    "Build a bedtime audiobook about a baby flamingo chick on a Lake-Nakuru-mudflat, with Kikuyu-mwomboko BGM and Lake-Nakuru-mudflat-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby Andean-flamingo chick on a Salar-de-Atacama, with Atacameño-andina BGM and Salar-de-Atacama-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby Caribbean-flamingo chick on a Bonaire-pekelmeer, with Bonaire-tumba BGM and Bonaire-pekelmeer-morning-2 ambience.",
    "Cook up a children's audiobook about a baby greater-flamingo chick on a Camargue-lagoon, with Provençal-galoubet BGM and Camargue-lagoon-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby roseate-spoonbill chick on a Florida-Tampa-Bay-mangrove, with Florida-Cracker-fiddle BGM and Tampa-Bay-mangrove-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby Atlantic-puffin chick on a Skomer-Island-burrow, with Welsh-harp-2 BGM and Skomer-Island-burrow-morning-2 ambience.",
    "Build a bedtime audiobook about a baby tufted-puffin chick on a Saint-Paul-Pribilof-cliff, with Aleut-iglak BGM and Saint-Paul-Pribilof-cliff-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby horned-puffin chick on a Lake-Clark-Alaska-cliff, with Alaska-Athabaskan-fiddle BGM and Lake-Clark-cliff-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby albatross chick on a Bird-Island-South-Georgia-tussock, with South-Georgia-shanty BGM and Bird-Island-tussock-morning-2 ambience.",
    "Cook up a children's audiobook about a baby Laysan-albatross chick on a Midway-Atoll-Sand-Island, with Hawaiian-slack-key BGM and Midway-Sand-Island-morning-2 ambience.",
    "Produce a narrated children's audiobook about a baby blue-footed-booby chick on a Galapagos-Española-Suárez-Point, with Ecuadorian-pasillo-2 BGM and Española-Suárez-Point-morning-2 ambience.",
    "Generate a kids' picture-book audiobook about a baby red-footed-booby chick on a Christmas-Island-rainforest-canopy, with Christmas-Island-Malay-keroncong BGM and Christmas-Island-canopy-morning-2 ambience.",
    "Build a bedtime audiobook about a baby frigatebird chick on a Aldabra-Atoll, with Seychellois-moutia BGM and Aldabra-Atoll-morning-2 ambience.",
    "Tell me an illustrated children's audiobook about a baby pelican chick on a Carolina-Pea-Island-shore, with Carolina-shag-folk BGM and Pea-Island-shore-morning-2 ambience.",
    "Make me a picture-book audiobook about a baby ibis chick on a Camargue-marsh-reed, with Provençal-fife BGM and Camargue-marsh-reed-morning-2 ambience.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
