"""x15 extend_style_subtitle GRPO. Disjoint from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a 30-second baker tutorial — extend to 90 seconds, render as Beatrix-Potter illustration, and add English captions.",
    "Here's a 45-second carpenter demo — extend to 2 minutes, style as a vintage Popular Mechanics plate, and overlay English subtitles.",
    "I have a 1-minute knitter tutorial — extend to 3 minutes, convert to a Granny-square mid-century kitsch poster, and add English captions.",
    "Uploading a 30-second crocheter demo — extend to 90 seconds, render as a Norse-tapestry illustration, and overlay English subtitles.",
    "Here's a 45-second weaver tutorial — extend to 2 minutes, style as a Navajo-rug pattern, and add English captions.",
    "I'm sending you a 30-second tailor demo — extend to 90 seconds, convert to a Persian-miniature gold-thread design, and overlay English subtitles.",
    "Uploading a 1-minute jeweler walkthrough — extend to 3 minutes, render as a Faberge enamel illustration, and add English captions.",
    "Here's a 45-second clockmaker walkthrough — extend to 2 minutes, style as a Vienna-watchmaker illustration, and overlay English subtitles.",
    "I have a 30-second pottery glazer demo — extend to 90 seconds, convert to a Greek black-figure vase painting, and add English captions.",
    "Uploading a 1-minute glassblower demo — extend to 3 minutes, style as a Murano-glass design illustration, and overlay English subtitles.",
    "Here's a 30-second leather-tooler tutorial — extend to 90 seconds, render as a Renaissance-craftsman engraving, and add English captions.",
    "I'm sending you a 45-second cobbler demo — extend to 2 minutes, style as a 1900s shoemaker illustration, and overlay English subtitles.",
    "Uploading a 1-minute saddle-maker demo — extend to 3 minutes, convert to a vintage Western leather-shop poster, and add English captions.",
    "Here's a 30-second bow-maker demo — extend to 90 seconds, render as a Native-American craft illustration, and overlay English subtitles.",
    "I have a 45-second arrow-fletcher demo — extend to 2 minutes, style as a Field-and-Stream vintage plate, and add English captions.",
    "Uploading a 1-minute fly-tier demo — extend to 3 minutes, convert to a vintage trout-fishing magazine plate, and overlay English subtitles.",
    "Here's a 30-second fishing-knot tutorial — extend to 90 seconds, style as a maritime nautical-knot guide, and add English captions.",
    "I'm sending you a 45-second sailing-knot tutorial — extend to 2 minutes, render as a 1900s sailor's-handbook illustration, and overlay English subtitles.",
    "Uploading a 1-minute rope-splicer demo — extend to 3 minutes, convert to a maritime guide illustration, and add English captions.",
    "Here's a 30-second whittler demo — extend to 90 seconds, style as a Boy-Scout-handbook illustration, and overlay English subtitles.",
    "I have a 45-second carver demo — extend to 2 minutes, render as a Pacific-Northwest tribal carving plate, and add English captions.",
    "Uploading a 1-minute totem-pole demo — extend to 3 minutes, style as a Pacific-Northwest tribal woodblock, and overlay English subtitles.",
    "Here's a 30-second wood-burner demo — extend to 90 seconds, convert to a Boy-Scout-craft illustration, and add English captions.",
    "I'm sending you a 45-second linocut tutorial — extend to 2 minutes, render as a Berlin Bauhaus print, and overlay English subtitles.",
    "Uploading a 1-minute screen-print tutorial — extend to 3 minutes, style as an Andy-Warhol Pop-Art poster, and add English captions.",
    "Here's a 30-second risograph tutorial — extend to 90 seconds, render as a 1980s zine illustration, and overlay English subtitles.",
    "I have a 45-second letterpress tutorial — extend to 2 minutes, convert to a Gutenberg-printer illustration, and add English captions.",
    "Uploading a 1-minute bookbinder tutorial — extend to 3 minutes, style as a Renaissance book-binder illustration, and overlay English subtitles.",
    "Here's a 30-second bookmark-maker tutorial — extend to 90 seconds, render as an illuminated manuscript, and add English captions.",
    "I'm sending you a 45-second journal-maker tutorial — extend to 2 minutes, style as a Persian illuminated manuscript, and overlay English subtitles.",
    "Uploading a 1-minute paper-marbler tutorial — extend to 3 minutes, convert to a Turkish ebru-artisan illustration, and add English captions.",
    "Here's a 30-second soap-carver tutorial — extend to 90 seconds, render as a vintage carving-handbook plate, and overlay English subtitles.",
    "I have a 45-second candle-maker walkthrough — extend to 2 minutes, style as a vintage candle-maker poster, and add English captions.",
    "Uploading a 1-minute soap-maker walkthrough — extend to 3 minutes, convert to a 1900s apothecary illustration, and overlay English subtitles.",
    "Here's a 30-second perfume-blender walkthrough — extend to 90 seconds, style as a 1920s Vogue cover, and add English captions.",
    # ── more upload + extend + style + subtitle requests (50) ──────────────
    "Uploading a 30-second gardener tutorial — extend to 90 seconds, render as Heian Yamato-e, and add English captions.",
    "Here's a 45-second arborist demo — extend to 2 minutes, style as Kano-school painting, and overlay English subtitles.",
    "I have a 1-minute bonsai-master tutorial — extend to 3 minutes, convert to Edo-period ukiyo-e, and add English captions.",
    "Uploading a 30-second floral-arrangement class — extend to 90 seconds, render as Mughal Akbarnama miniature, and overlay English subtitles.",
    "Here's a 45-second ikebana lesson — extend to 2 minutes, style as Chinese gongbi fine-line, and add English captions.",
    "I'm sending you a 30-second terrarium-builder demo — extend to 90 seconds, convert to Korean Joseon court painting, and overlay English subtitles.",
    "Uploading a 1-minute aquarium-design tutorial — extend to 3 minutes, render as Persian Safavid miniature, and add English captions.",
    "Here's a 45-second hydroponic-grower demo — extend to 2 minutes, style as Ottoman Tezhip illumination, and overlay English subtitles.",
    "I have a 30-second mushroom-cultivator demo — extend to 90 seconds, convert to Coptic icon, and add English captions.",
    "Uploading a 1-minute wine-maker tutorial — extend to 3 minutes, style as Ethiopian Magdala icon, and overlay English subtitles.",
    "Here's a 30-second cheese-maker tutorial — extend to 90 seconds, render as Caucasian rug pattern, and add English captions.",
    "I'm sending you a 45-second charcuterie-maker tutorial — extend to 2 minutes, style as Oriental kilim, and overlay English subtitles.",
    "Uploading a 1-minute chocolatier demo — extend to 3 minutes, convert to Berber tribal weaving, and add English captions.",
    "Here's a 30-second macaron-maker tutorial — extend to 90 seconds, render as Andean weaving, and overlay English subtitles.",
    "I have a 45-second honey-extractor tutorial — extend to 2 minutes, style as Pre-Columbian goldwork, and add English captions.",
    "Uploading a 1-minute mead-maker tutorial — extend to 3 minutes, convert to Olmec stone-relief, and overlay English subtitles.",
    "Here's a 30-second distiller tutorial — extend to 90 seconds, style as Maya ceramic painting, and add English captions.",
    "I'm sending you a 45-second coffee-roaster demo — extend to 2 minutes, render as Inca Quero cup design, and overlay English subtitles.",
    "Uploading a 1-minute tea-blender tutorial — extend to 3 minutes, convert to Mochica pottery, and add English captions.",
    "Here's a 30-second spice-merchant demo — extend to 90 seconds, style as Nazca line geoglyph, and overlay English subtitles.",
    "I have a 45-second herbalist tutorial — extend to 2 minutes, render as Sumerian cuneiform tablet, and add English captions.",
    "Uploading a 1-minute apothecary tutorial — extend to 3 minutes, convert to Babylonian relief, and overlay English subtitles.",
    "Here's a 30-second aromatherapist demo — extend to 90 seconds, style as Assyrian palace relief, and add English captions.",
    "I'm sending you a 45-second barber tutorial — extend to 2 minutes, render as Persepolis Persian relief, and overlay English subtitles.",
    "Uploading a 1-minute nail-artist demo — extend to 3 minutes, convert to Egyptian papyrus illustration, and add English captions.",
    "Here's a 30-second tattoo-artist demo — extend to 90 seconds, style as Dead-Sea-Scrolls Hebrew, and overlay English subtitles.",
    "I have a 45-second hairstylist tutorial — extend to 2 minutes, render as Talmud-illumination Hebrew, and add English captions.",
    "Uploading a 1-minute hair-braider tutorial — extend to 3 minutes, convert to Hebrew micrography, and overlay English subtitles.",
    "Here's a 30-second makeup-artist tutorial — extend to 90 seconds, style as Armenian khachkar relief, and add English captions.",
    "I'm sending you a 45-second mask-maker tutorial — extend to 2 minutes, render as Georgian fresco, and overlay English subtitles.",
    "Uploading a 1-minute balloon-artist demo — extend to 3 minutes, convert to Russian birch-bark gramota, and add English captions.",
    "Here's a 30-second face-painter demo — extend to 90 seconds, style as Norse runestone, and overlay English subtitles.",
    "I have a 45-second caricature-artist demo — extend to 2 minutes, render as Celtic-knot illumination, and add English captions.",
    "Uploading a 1-minute sand-artist demo — extend to 3 minutes, convert to Anglo-Saxon Lindisfarne Gospels, and overlay English subtitles.",
    "Here's a 30-second ice-sculptor demo — extend to 90 seconds, style as Carolingian manuscript, and add English captions.",
    "I'm sending you a 45-second snow-sculptor demo — extend to 2 minutes, render as Romanesque tympanum carving, and overlay English subtitles.",
    "Uploading a 1-minute chalk-artist demo — extend to 3 minutes, convert to Gothic stained-glass rose, and add English captions.",
    "Here's a 30-second mosaic-artist demo — extend to 90 seconds, style as Trecento Sienese gold-ground, and overlay English subtitles.",
    "I have a 45-second stained-glass tutorial — extend to 2 minutes, render as Quattrocento Florentine fresco, and add English captions.",
    "Uploading a 1-minute terra-cotta-tile demo — extend to 3 minutes, convert to Cinquecento Venetian glaze, and overlay English subtitles.",
    "Here's a 30-second fresco-restorer demo — extend to 90 seconds, style as Rococo pastel, and add English captions.",
    "I'm sending you a 45-second gilder tutorial — extend to 2 minutes, render as Orientalist fantasy 1860s, and overlay English subtitles.",
    "Uploading a 1-minute icon-painter demo — extend to 3 minutes, convert to Pre-Raphaelite Brotherhood, and add English captions.",
    "Here's a 30-second thangka-painter demo — extend to 90 seconds, style as Symbolist French, and overlay English subtitles.",
    "I have a 45-second mehndi-artist demo — extend to 2 minutes, render as Vienna Secession, and add English captions.",
    "Uploading a 1-minute henna-tattoo demo — extend to 3 minutes, convert to Russian World-of-Art, and overlay English subtitles.",
    "Here's a 30-second ribbon-embroiderer tutorial — extend to 90 seconds, style as Munich Secession, and add English captions.",
    "I'm sending you a 45-second lace-maker tutorial — extend to 2 minutes, render as Soviet OSA Constructivism, and overlay English subtitles.",
    "Uploading a 1-minute tatting-lace tutorial — extend to 3 minutes, convert to Italian Futurism, and add English captions.",
    "Here's a 30-second quilter tutorial — extend to 90 seconds, style as Hawaiian kapa cloth pattern, and overlay English subtitles.",
    # ── more upload + extend + style + subtitle requests (50) ──────────────
    "Uploading a 30-second spin-class clip — extend to 90 seconds, convert to cyclorama-art, and add English subtitles.",
    "Here's a 45-second SoulCycle-class clip — extend to 2 minutes, render as neon-fitness aesthetic, and overlay English captions.",
    "I have a 1-minute boxing-class clip — extend to 3 minutes, style as George-Bellows boxing-painting, and add English subtitles.",
    "Uploading a 30-second yoga-class clip — extend to 90 seconds, convert to Bengal-school, and overlay English captions.",
    "Here's a 45-second Pilates-class clip — extend to 2 minutes, style as Hilma-af-Klint geometric, and add English subtitles.",
    "I'm sending you a 30-second CrossFit-class clip — extend to 90 seconds, render as Russian-Constructivist poster, and overlay English captions.",
    "Uploading a 1-minute Zumba-class clip — extend to 3 minutes, convert to Tarsila-do-Amaral, and add English subtitles.",
    "Here's a 45-second aerobics-class clip — extend to 2 minutes, style as Memphis-1980s design, and overlay English captions.",
    "I have a 30-second barre-class clip — extend to 90 seconds, render as Berthe-Morisot impressionist, and add English subtitles.",
    "Uploading a 1-minute cycling-tour clip — extend to 3 minutes, convert to Pre-Raphaelite Brotherhood, and overlay English captions.",
    "Here's a 30-second trail-running clip — extend to 90 seconds, style as Hudson-River-school, and add English subtitles.",
    "I'm sending you a 45-second hiking-trail clip — extend to 2 minutes, render as Bierstadt monumental, and overlay English captions.",
    "Uploading a 1-minute backpacking tutorial — extend to 3 minutes, convert to Thomas-Cole Hudson-River, and add English subtitles.",
    "Here's a 30-second camping tutorial — extend to 90 seconds, style as NPS National-Parks poster, and overlay English captions.",
    "I have a 45-second fishing tutorial — extend to 2 minutes, render as Field-and-Stream vintage poster, and add English subtitles.",
    "Uploading a 1-minute hunting tutorial — extend to 3 minutes, convert to Currier-and-Ives, and overlay English captions.",
    "Here's a 30-second archery-class clip — extend to 90 seconds, style as Akira-Kurosawa film-frame, and add English subtitles.",
    "I'm sending you a 45-second fencing-class clip — extend to 2 minutes, render as Velázquez court-painting, and overlay English captions.",
    "Uploading a 1-minute horse-riding class — extend to 3 minutes, convert to Stubbs equestrian, and add English subtitles.",
    "Here's a 30-second polo-match clip — extend to 90 seconds, style as Stubbs equestrian, and overlay English captions.",
    "I have a 45-second sailing-tutorial clip — extend to 2 minutes, render as Hopper coast, and add English subtitles.",
    "Uploading a 1-minute kayaking-tutorial clip — extend to 3 minutes, convert to Hopper coast, and overlay English captions.",
    "Here's a 30-second canoe-paddling clip — extend to 90 seconds, style as Frederic-Edwin-Church Hudson-River-luminist, and add English subtitles.",
    "I'm sending you a 45-second SUP clip — extend to 2 minutes, render as Hockney, and overlay English captions.",
    "Uploading a 1-minute snorkeling-tutorial clip — extend to 3 minutes, convert to Yves-Klein blue, and add English subtitles.",
    "Here's a 30-second scuba-diving-class clip — extend to 90 seconds, style as Yves-Klein blue, and overlay English captions.",
    "I have a 45-second free-diving tutorial — extend to 2 minutes, render as Hopper sea, and add English subtitles.",
    "Uploading a 1-minute spearfishing-tutorial clip — extend to 3 minutes, convert to Hopper, and overlay English captions.",
    "Here's a 30-second skim-boarding clip — extend to 90 seconds, style as Manet flat-color, and add English subtitles.",
    "I'm sending you a 45-second surfing-tutorial clip — extend to 2 minutes, render as Manet, and overlay English captions.",
    "Uploading a 1-minute bodyboarding clip — extend to 3 minutes, convert to Manet, and add English subtitles.",
    "Here's a 30-second skiing-class clip — extend to 90 seconds, style as Norwegian folk-illustration, and overlay English captions.",
    "I have a 45-second snowboarding-class clip — extend to 2 minutes, render as Norwegian folk-illustration, and add English subtitles.",
    "Uploading a 1-minute ice-fishing tutorial — extend to 3 minutes, convert to Carl-Larsson watercolor, and overlay English captions.",
    "Here's a 30-second snowshoeing tutorial — extend to 90 seconds, style as Carl-Larsson watercolor, and add English subtitles.",
    "I'm sending you a 45-second cross-country-skiing clip — extend to 2 minutes, render as Carl-Larsson, and overlay English captions.",
    "Uploading a 1-minute sled-dog-driving clip — extend to 3 minutes, convert to Tom-Thomson Group-of-Seven, and add English subtitles.",
    "Here's a 30-second bobsled-class clip — extend to 90 seconds, style as Lichtenstein pop-art, and overlay English captions.",
    "I have a 45-second luge-class clip — extend to 2 minutes, render as Pop-Art screenprint, and add English subtitles.",
    "Uploading a 1-minute ice-skating-class clip — extend to 3 minutes, convert to Mary-Cassatt impressionist, and overlay English captions.",
    "Here's a 30-second figure-skating-class clip — extend to 90 seconds, style as Mary-Cassatt impressionist, and add English subtitles.",
    "I'm sending you a 45-second hockey-game clip — extend to 2 minutes, render as Pop-Art screenprint, and overlay English captions.",
    "Uploading a 1-minute curling-tutorial clip — extend to 3 minutes, convert to Pop-Art screenprint, and add English subtitles.",
    "Here's a 30-second skating-rink-class clip — extend to 90 seconds, style as art-deco, and overlay English captions.",
    "I have a 45-second roller-derby-class clip — extend to 2 minutes, render as graffiti, and add English subtitles.",
    "Uploading a 1-minute BMX-class clip — extend to 3 minutes, convert to graffiti, and overlay English captions.",
    "Here's a 30-second skateboarding-class clip — extend to 90 seconds, style as Basquiat raw expressionism, and add English subtitles.",
    "I'm sending you a 45-second parkour-tutorial clip — extend to 2 minutes, render as Basquiat, and overlay English captions.",
    "Uploading a 1-minute Ninja-Warrior course clip — extend to 3 minutes, convert to Frank-Frazetta fantasy, and add English subtitles.",
    "Here's a 30-second American-Ninja course clip — extend to 90 seconds, style as Frank-Frazetta, and overlay English captions.",
    # ── more upload + extend + style + subtitle requests (50) ──────────────
    "Uploading a 30-second coding-bootcamp graduation clip — extend to 90 seconds, convert to Bauhaus poster, and add English subtitles.",
    "Here's a 45-second hackathon-pitch clip — extend to 2 minutes, render as Russian-Constructivist, and overlay English captions.",
    "I have a 1-minute data-science conference talk — extend to 3 minutes, style as Eduardo-Paolozzi pop, and add English subtitles.",
    "Uploading a 30-second AI-research talk — extend to 90 seconds, convert to Mondrian grid, and overlay English captions.",
    "Here's a 45-second machine-learning tutorial — extend to 2 minutes, style as De-Stijl, and add English subtitles.",
    "I'm sending you a 30-second blockchain tutorial — extend to 90 seconds, render as cyberpunk-neon, and overlay English captions.",
    "Uploading a 1-minute crypto-meetup recording — extend to 3 minutes, convert to Lichtenstein dot, and add English subtitles.",
    "Here's a 45-second Web3-talk recording — extend to 2 minutes, style as cyberpunk, and overlay English captions.",
    "I have a 30-second NFT-art-show recording — extend to 90 seconds, render as glitch-art, and add English subtitles.",
    "Uploading a 1-minute metaverse event — extend to 3 minutes, convert to wireframe-3D, and overlay English captions.",
    "Here's a 30-second SaaS-demo clip — extend to 90 seconds, style as Bauhaus, and add English subtitles.",
    "I'm sending you a 45-second UX-workshop clip — extend to 2 minutes, render as Mondrian grid, and overlay English captions.",
    "Uploading a 1-minute UI-redesign walkthrough — extend to 3 minutes, convert to De-Stijl, and add English subtitles.",
    "Here's a 30-second typography-class clip — extend to 90 seconds, style as Paula-Scher, and overlay English captions.",
    "I have a 45-second graphic-design-class clip — extend to 2 minutes, render as Mucha, and add English subtitles.",
    "Uploading a 1-minute illustration-class clip — extend to 3 minutes, convert to Quentin-Blake, and overlay English captions.",
    "Here's a 30-second animation-tutorial clip — extend to 90 seconds, style as Don-Hertzfeldt, and add English subtitles.",
    "I'm sending you a 45-second motion-graphics class — extend to 2 minutes, render as Saul-Bass title, and overlay English captions.",
    "Uploading a 1-minute visual-effects tutorial — extend to 3 minutes, convert to Ralph-Bakshi rotoscope, and add English subtitles.",
    "Here's a 30-second 3D-rendering tutorial — extend to 90 seconds, style as low-poly PS1, and overlay English captions.",
    "I have a 45-second game-engine tutorial — extend to 2 minutes, render as Unreal-tech-art, and add English subtitles.",
    "Uploading a 1-minute game-design tutorial — extend to 3 minutes, convert to Yoshitomo-Nara, and overlay English captions.",
    "Here's a 30-second level-design tutorial — extend to 90 seconds, style as pixel-art, and add English subtitles.",
    "I'm sending you a 45-second character-design tutorial — extend to 2 minutes, render as Mary-Blair, and overlay English captions.",
    "Uploading a 1-minute concept-art tutorial — extend to 3 minutes, convert to Frank-Frazetta fantasy, and add English subtitles.",
    "Here's a 30-second matte-painting tutorial — extend to 90 seconds, style as Norman-Rockwell, and overlay English captions.",
    "I have a 45-second storyboard tutorial — extend to 2 minutes, render as hand-drawn ink, and add English subtitles.",
    "Uploading a 1-minute comic-art tutorial — extend to 3 minutes, convert to Frank-Miller noir, and overlay English captions.",
    "Here's a 30-second manga-art tutorial — extend to 90 seconds, style as Otomo manga, and add English subtitles.",
    "I'm sending you a 45-second anime tutorial — extend to 2 minutes, render as Akira-Toriyama, and overlay English captions.",
    "Uploading a 1-minute webcomic tutorial — extend to 3 minutes, convert to R.-Crumb underground, and add English subtitles.",
    "Here's a 30-second webtoon tutorial — extend to 90 seconds, style as Korean-manhwa, and overlay English captions.",
    "I have a 45-second fan-art tutorial — extend to 2 minutes, render as Yoshitomo-Nara, and add English subtitles.",
    "Uploading a 1-minute fan-fiction writing class — extend to 3 minutes, convert to medieval illumination, and overlay English captions.",
    "Here's a 30-second screenplay-writing class — extend to 90 seconds, style as Saul-Bass title, and add English subtitles.",
    "I'm sending you a 45-second novel-writing class — extend to 2 minutes, render as medieval illumination, and overlay English captions.",
    "Uploading a 1-minute poetry-reading clip — extend to 3 minutes, convert to Persian miniature, and add English subtitles.",
    "Here's a 30-second spoken-word clip — extend to 90 seconds, style as Basquiat raw expressionism, and overlay English captions.",
    "I have a 45-second slam-poetry clip — extend to 2 minutes, render as Banksy stencil, and add English subtitles.",
    "Uploading a 1-minute open-mic stand-up — extend to 3 minutes, convert to Lichtenstein dot, and overlay English captions.",
    "Here's a 30-second improv-class clip — extend to 90 seconds, style as Reginald-Marsh, and add English subtitles.",
    "I'm sending you a 45-second acting-class clip — extend to 2 minutes, render as Edgar-Degas pastel, and overlay English captions.",
    "Uploading a 1-minute voice-acting class — extend to 3 minutes, convert to Mary-Blair concept-art, and add English subtitles.",
    "Here's a 30-second casting-call recording — extend to 90 seconds, style as Saul-Bass title, and overlay English captions.",
    "I have a 45-second audition-prep clip — extend to 2 minutes, render as Saul-Bass title, and add English subtitles.",
    "Uploading a 1-minute headshot-session reel — extend to 3 minutes, convert to Mary-Cassatt impressionist, and overlay English captions.",
    "Here's a 30-second portfolio-review reel — extend to 90 seconds, style as Andy-Warhol screenprint, and add English subtitles.",
    "I'm sending you a 45-second lookbook-shoot reel — extend to 2 minutes, render as Helmut-Newton black-and-white, and overlay English captions.",
    "Uploading a 1-minute fashion-week-runway reel — extend to 3 minutes, convert to Erté Art-Deco, and add English subtitles.",
    "Here's a 30-second couture-fitting reel — extend to 90 seconds, style as Toulouse-Lautrec poster, and overlay English captions.",
    # ── more cooking-show / culinary scenes + food-art-style + subtitle (50) ──
    "Uploading a 30-second pasta-making reel — extend to 90 seconds, convert to Giuseppe-Arcimboldo composite-portrait, and add English subtitles.",
    "Here's a 45-second pizza-oven reel — extend to 2 minutes, render as Caravaggio chiaroscuro, and overlay English captions.",
    "I have a 1-minute risotto-stir reel — extend to 3 minutes, style as Italian-Renaissance still-life, and add English subtitles.",
    "Uploading a 30-second espresso-pull reel — extend to 90 seconds, convert to Italian-coffee-poster Bialetti, and overlay English captions.",
    "Here's a 45-second tiramisu-layering reel — extend to 2 minutes, render as Italian-bakery-poster, and add English subtitles.",
    "I'm sending you a 1-minute French-bread-bake reel — extend to 3 minutes, style as Manet still-life, and overlay English captions.",
    "Uploading a 30-second baguette-shape reel — extend to 90 seconds, convert to French-bistro-poster Cassandre, and add English subtitles.",
    "Here's a 45-second crêpe-flip reel — extend to 2 minutes, render as Edgar-Degas pastel-2, and overlay English captions.",
    "I have a 1-minute soufflé-bake reel — extend to 3 minutes, style as Henri-de-Toulouse-Lautrec cabaret, and add English subtitles.",
    "Uploading a 30-second cassoulet-simmer reel — extend to 90 seconds, convert to Provençal still-life, and overlay English captions.",
    "Here's a 45-second beurre-blanc-saucy reel — extend to 2 minutes, render as Chardin still-life, and add English subtitles.",
    "I'm sending you a 1-minute escargots-prep reel — extend to 3 minutes, style as French-art-deco menu, and overlay English captions.",
    "Uploading a 30-second tarte-tatin reel — extend to 90 seconds, convert to Pierre-Bonnard kitchen, and add English subtitles.",
    "Here's a 45-second macaron-bake reel — extend to 2 minutes, render as Ladurée-pastel, and overlay English captions.",
    "I have a 1-minute croquembouche reel — extend to 3 minutes, style as French-rococo confectionery, and add English subtitles.",
    "Uploading a 30-second sushi-roll reel — extend to 90 seconds, convert to Hokusai sea-wave, and overlay English captions.",
    "Here's a 45-second tempura-fry reel — extend to 2 minutes, render as Hiroshige fan-print, and add English subtitles.",
    "I'm sending you a 1-minute udon-knead reel — extend to 3 minutes, style as Japanese-shoji-screen, and overlay English captions.",
    "Uploading a 30-second matcha-whisk reel — extend to 90 seconds, convert to Sengai zen-ink, and add English subtitles.",
    "Here's a 45-second wagashi-mold reel — extend to 2 minutes, render as Edo woodblock, and overlay English captions.",
    "I have a 1-minute kaiseki-plating reel — extend to 3 minutes, style as Rinpa-school folding-screen, and add English subtitles.",
    "Uploading a 30-second ramen-broth reel — extend to 90 seconds, convert to Japanese izakaya-poster, and overlay English captions.",
    "Here's a 45-second yakitori-grill reel — extend to 2 minutes, render as Showa-era enka poster, and add English subtitles.",
    "I'm sending you a 1-minute kimchi-pack reel — extend to 3 minutes, style as Joseon minhwa, and overlay English captions.",
    "Uploading a 30-second bibimbap-mix reel — extend to 90 seconds, convert to Korean-folk-bowl, and add English subtitles.",
    "Here's a 45-second tteokbokki-stir reel — extend to 2 minutes, render as Korean-pop street-illustration, and overlay English captions.",
    "I have a 1-minute Korean-BBQ-grill reel — extend to 3 minutes, style as Korean-han-paper, and add English subtitles.",
    "Uploading a 30-second xiaolongbao-fold reel — extend to 90 seconds, convert to Song-dynasty-still-life, and overlay English captions.",
    "Here's a 45-second peking-duck-carve reel — extend to 2 minutes, render as Qing-court-banquet, and add English subtitles.",
    "I'm sending you a 1-minute mapo-tofu-wok reel — extend to 3 minutes, style as Sichuan-Shu-embroidery, and overlay English captions.",
    "Uploading a 30-second dim-sum-cart reel — extend to 90 seconds, convert to Cantonese-tea-house illustration, and add English subtitles.",
    "Here's a 45-second hand-pulled-noodle reel — extend to 2 minutes, render as Lanzhou-mural, and overlay English captions.",
    "I have a 1-minute hotpot-bubble reel — extend to 3 minutes, style as Chongqing-mural, and add English subtitles.",
    "Uploading a 30-second pho-bowl reel — extend to 90 seconds, convert to Vietnamese-silk-painting, and overlay English captions.",
    "Here's a 45-second banh-mi-stack reel — extend to 2 minutes, render as Vietnamese-propaganda-poster, and add English subtitles.",
    "I'm sending you a 1-minute pad-thai-toss reel — extend to 3 minutes, style as Thai-mural, and overlay English captions.",
    "Uploading a 30-second green-curry-pour reel — extend to 90 seconds, convert to Thai-temple-fresco, and add English subtitles.",
    "Here's a 45-second nasi-goreng-stir reel — extend to 2 minutes, render as Balinese-batik, and overlay English captions.",
    "I have a 1-minute rendang-simmer reel — extend to 3 minutes, style as Sumatran-songket, and add English subtitles.",
    "Uploading a 30-second satay-grill reel — extend to 90 seconds, convert to Javanese-batik, and overlay English captions.",
    "Here's a 45-second laksa-bowl reel — extend to 2 minutes, render as Peranakan-tile, and add English subtitles.",
    "I'm sending you a 1-minute biryani-layer reel — extend to 3 minutes, style as Mughal-miniature, and overlay English captions.",
    "Uploading a 30-second tandoori-grill reel — extend to 90 seconds, convert to Madhubani-folk, and add English subtitles.",
    "Here's a 45-second masala-dosa-flip reel — extend to 2 minutes, render as Tanjore-painting, and overlay English captions.",
    "I have a 1-minute samosa-fold reel — extend to 3 minutes, style as Pichvai-painting, and add English subtitles.",
    "Uploading a 30-second falafel-fry reel — extend to 90 seconds, convert to Persian-miniature, and overlay English captions.",
    "Here's a 45-second hummus-swirl reel — extend to 2 minutes, render as Iznik-tile, and add English subtitles.",
    "I'm sending you a 1-minute kebab-grill reel — extend to 3 minutes, style as Turkish-miniature, and overlay English captions.",
    "Uploading a 30-second baklava-layer reel — extend to 90 seconds, convert to Ottoman-illumination, and add English subtitles.",
    "Here's a 45-second tagine-simmer reel — extend to 2 minutes, render as Moroccan-zellij, and overlay English captions.",
    # ── more tech-product / unboxing / gadget-review reels + tech-poster-art (50) ──
    "I have a 30-second iPhone-unboxing reel — extend to 90 seconds, style as Apple-glassmorphism poster, and add English subtitles.",
    "Uploading a 45-second MacBook-Pro-unboxing reel — extend to 2 minutes, render as Apple-Aluminum-CAD, and overlay English captions.",
    "Here's a 1-minute iPad-Pro-Pencil reel — extend to 3 minutes, convert to Apple-Procreate-illustration, and add English subtitles.",
    "I'm sending you a 30-second Apple-Vision-Pro reel — extend to 90 seconds, style as Apple-spatial-render, and overlay English captions.",
    "Uploading a 45-second Apple-Watch-Ultra reel — extend to 2 minutes, render as Apple-watchface-render, and add English subtitles.",
    "Here's a 1-minute AirPods-Pro reel — extend to 3 minutes, convert to Apple-acoustic-graph, and overlay English captions.",
    "I have a 30-second Samsung-Galaxy-S-Ultra reel — extend to 90 seconds, style as Samsung-glassmorphism, and add English subtitles.",
    "Uploading a 45-second Samsung-foldable reel — extend to 2 minutes, render as Samsung-foldable-render, and overlay English captions.",
    "Here's a 1-minute Google-Pixel reel — extend to 3 minutes, convert to Google-Material-Design poster, and add English subtitles.",
    "I'm sending you a 30-second Google-Pixel-Watch reel — extend to 90 seconds, style as Material-You-render, and overlay English captions.",
    "Uploading a 45-second OnePlus-flagship reel — extend to 2 minutes, render as OnePlus-Hasselblad-render, and add English subtitles.",
    "Here's a 1-minute Xiaomi-flagship reel — extend to 3 minutes, convert to Xiaomi-Mi-render, and overlay English captions.",
    "I have a 30-second Huawei-flagship reel — extend to 90 seconds, style as Huawei-Leica-render, and add English subtitles.",
    "Uploading a 45-second Sony-Walkman-DAP reel — extend to 2 minutes, render as Sony-vintage-poster, and overlay English captions.",
    "Here's a 1-minute Sony-A7R-camera reel — extend to 3 minutes, convert to Sony-camera-blueprint, and add English subtitles.",
    "I'm sending you a 30-second Canon-EOS-R reel — extend to 90 seconds, style as Canon-blueprint, and overlay English captions.",
    "Uploading a 45-second Nikon-Z-camera reel — extend to 2 minutes, render as Nikon-blueprint, and add English subtitles.",
    "Here's a 1-minute Leica-M11 reel — extend to 3 minutes, convert to Leica-Bauhaus poster, and overlay English captions.",
    "I have a 30-second Fujifilm-X100V reel — extend to 90 seconds, style as Fujifilm-rangefinder-poster, and add English subtitles.",
    "Uploading a 45-second Hasselblad-X2D reel — extend to 2 minutes, render as Hasselblad-medium-format-blueprint, and overlay English captions.",
    "Here's a 1-minute DJI-Mavic-3 reel — extend to 3 minutes, convert to DJI-aerial-blueprint, and add English subtitles.",
    "I'm sending you a 30-second GoPro-Hero-12 reel — extend to 90 seconds, style as GoPro-action-poster, and overlay English captions.",
    "Uploading a 45-second Insta360-X4 reel — extend to 2 minutes, render as Insta360-360-render, and add English subtitles.",
    "Here's a 1-minute drone-FPV-quadcopter reel — extend to 3 minutes, convert to Drone-FPV-poster, and overlay English captions.",
    "I have a 30-second Tesla-Model-S reel — extend to 90 seconds, style as Tesla-CAD-blueprint, and add English subtitles.",
    "Uploading a 45-second Tesla-Cybertruck reel — extend to 2 minutes, render as Cybertruck-render, and overlay English captions.",
    "Here's a 1-minute Lucid-Air reel — extend to 3 minutes, convert to Lucid-luxury-render, and add English subtitles.",
    "I'm sending you a 30-second Rivian-R1T reel — extend to 90 seconds, style as Rivian-adventure-poster, and overlay English captions.",
    "Uploading a 45-second Porsche-Taycan reel — extend to 2 minutes, render as Porsche-CAD-blueprint, and add English subtitles.",
    "Here's a 1-minute BMW-iX reel — extend to 3 minutes, convert to BMW-Bauhaus poster, and overlay English captions.",
    "I have a 30-second Mercedes-EQS reel — extend to 90 seconds, style as Mercedes-Bauhaus poster, and add English subtitles.",
    "Uploading a 45-second Audi-e-tron reel — extend to 2 minutes, render as Audi-Bauhaus poster, and overlay English captions.",
    "Here's a 1-minute Volvo-EX90 reel — extend to 3 minutes, convert to Volvo-Scandi-design poster, and add English subtitles.",
    "I'm sending you a 30-second Polestar-3 reel — extend to 90 seconds, style as Polestar-Scandi-design poster, and overlay English captions.",
    "Uploading a 45-second NIO-EV reel — extend to 2 minutes, render as NIO-render, and add English subtitles.",
    "Here's a 1-minute BYD-Atto-3 reel — extend to 3 minutes, convert to BYD-render, and overlay English captions.",
    "I have a 30-second PlayStation-5-unboxing reel — extend to 90 seconds, style as PS5-glassmorphism-poster, and add English subtitles.",
    "Uploading a 45-second Xbox-Series-X-unboxing reel — extend to 2 minutes, render as Xbox-render, and overlay English captions.",
    "Here's a 1-minute Nintendo-Switch-OLED reel — extend to 3 minutes, convert to Nintendo-pop-poster, and add English subtitles.",
    "I'm sending you a 30-second Steam-Deck reel — extend to 90 seconds, style as Valve-tech-poster, and overlay English captions.",
    "Uploading a 45-second Meta-Quest-3 reel — extend to 2 minutes, render as Meta-VR-render, and add English subtitles.",
    "Here's a 1-minute NVIDIA-RTX-GPU-unboxing reel — extend to 3 minutes, convert to NVIDIA-render, and overlay English captions.",
    "I have a 30-second AMD-Ryzen-CPU-unboxing reel — extend to 90 seconds, style as AMD-cyber-poster, and add English subtitles.",
    "Uploading a 45-second Intel-Core-i9-unboxing reel — extend to 2 minutes, render as Intel-blueprint, and overlay English captions.",
    "Here's a 1-minute Logitech-MX-Master reel — extend to 3 minutes, convert to Logitech-Industrial-design poster, and add English subtitles.",
    "I'm sending you a 30-second Razer-Blade-laptop reel — extend to 90 seconds, style as Razer-neon poster, and overlay English captions.",
    "Uploading a 45-second Asus-ROG-laptop reel — extend to 2 minutes, render as ROG-cyber-poster, and add English subtitles.",
    "Here's a 1-minute Framework-Laptop reel — extend to 3 minutes, convert to Framework-modular-blueprint, and overlay English captions.",
    "I have a 30-second Sonos-Era-300 reel — extend to 90 seconds, style as Sonos-acoustic-poster, and add English subtitles.",
    "Uploading a 45-second Bose-QuietComfort reel — extend to 2 minutes, render as Bose-acoustic-blueprint, and overlay English captions.",
    # ── more car / motorcycle reviews + automotive-illustration styles (50) ──
    "Uploading a 30-second Porsche-911-GT3-RS reel — extend to 90 seconds, convert to Porsche-Werks-poster, and add English subtitles.",
    "Here's a 45-second Porsche-Taycan reel — extend to 2 minutes, render as Porsche-EV-blueprint, and overlay English captions.",
    "I have a 1-minute Porsche-Cayenne reel — extend to 3 minutes, style as Porsche-Cayenne-poster, and add English subtitles.",
    "Uploading a 30-second Ferrari-SF90-Stradale reel — extend to 90 seconds, convert to Ferrari-Cavallino-poster, and overlay English captions.",
    "Here's a 45-second Ferrari-296-GTB reel — extend to 2 minutes, render as Ferrari-Maranello-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute Lamborghini-Huracán-STO reel — extend to 3 minutes, style as Sant'Agata-poster, and overlay English captions.",
    "Uploading a 30-second Lamborghini-Revuelto reel — extend to 90 seconds, convert to Lamborghini-V12-blueprint, and add English subtitles.",
    "Here's a 45-second Lamborghini-Urus reel — extend to 2 minutes, render as Lamborghini-SUV-poster, and overlay English captions.",
    "I have a 1-minute McLaren-750S reel — extend to 3 minutes, style as McLaren-Woking-poster, and add English subtitles.",
    "Uploading a 30-second McLaren-Artura reel — extend to 90 seconds, convert to McLaren-hybrid-blueprint, and overlay English captions.",
    "Here's a 45-second Aston-Martin-Vantage reel — extend to 2 minutes, render as Aston-Martin-poster, and add English subtitles.",
    "I'm sending you a 1-minute Aston-Martin-DB12 reel — extend to 3 minutes, style as Gaydon-blueprint, and overlay English captions.",
    "Uploading a 30-second Bentley-Continental-GT reel — extend to 90 seconds, convert to Bentley-Crewe-poster, and add English subtitles.",
    "Here's a 45-second Bentley-Bentayga reel — extend to 2 minutes, render as Bentley-luxury-blueprint, and overlay English captions.",
    "I have a 1-minute Rolls-Royce-Spectre reel — extend to 3 minutes, style as Goodwood-poster, and add English subtitles.",
    "Uploading a 30-second Rolls-Royce-Phantom reel — extend to 90 seconds, convert to Rolls-Royce-blueprint, and overlay English captions.",
    "Here's a 45-second Mercedes-AMG-GT-Black-Series reel — extend to 2 minutes, render as Affalterbach-poster, and add English subtitles.",
    "I'm sending you a 1-minute Mercedes-EQS reel — extend to 3 minutes, style as Stuttgart-EV-blueprint, and overlay English captions.",
    "Uploading a 30-second Mercedes-G-Wagon-W464 reel — extend to 90 seconds, convert to G-Wagon-poster, and add English subtitles.",
    "Here's a 45-second BMW-M5-CS reel — extend to 2 minutes, render as Munich-blueprint, and overlay English captions.",
    "I have a 1-minute BMW-M3-Competition reel — extend to 3 minutes, style as Munich-M-poster, and add English subtitles.",
    "Uploading a 30-second BMW-i7 reel — extend to 90 seconds, convert to BMW-EV-blueprint, and overlay English captions.",
    "Here's a 45-second Audi-RS6-Avant reel — extend to 2 minutes, render as Ingolstadt-poster, and add English subtitles.",
    "I'm sending you a 1-minute Audi-RS-e-tron-GT reel — extend to 3 minutes, style as Audi-EV-blueprint, and overlay English captions.",
    "Uploading a 30-second Audi-Q8 reel — extend to 90 seconds, convert to Audi-SUV-poster, and add English subtitles.",
    "Here's a 45-second VW-Golf-R reel — extend to 2 minutes, render as Wolfsburg-poster, and overlay English captions.",
    "I have a 1-minute Volvo-EX90 reel — extend to 3 minutes, style as Gothenburg-EV-blueprint, and add English subtitles.",
    "Uploading a 30-second Polestar-2 reel — extend to 90 seconds, convert to Polestar-Scandinavian-poster, and overlay English captions.",
    "Here's a 45-second Lucid-Air reel — extend to 2 minutes, render as Lucid-EV-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute Rivian-R1T reel — extend to 3 minutes, style as Rivian-Adventure-poster, and overlay English captions.",
    "Uploading a 30-second Rivian-R1S reel — extend to 90 seconds, convert to Rivian-SUV-blueprint, and add English subtitles.",
    "Here's a 45-second Tesla-Cybertruck reel — extend to 2 minutes, render as Cybertruck-poster, and overlay English captions.",
    "I have a 1-minute Tesla-Model-S-Plaid reel — extend to 3 minutes, style as Tesla-Plaid-blueprint, and add English subtitles.",
    "Uploading a 30-second Hyundai-Ioniq-5-N reel — extend to 90 seconds, convert to Hyundai-N-poster, and overlay English captions.",
    "Here's a 45-second Genesis-GV70 reel — extend to 2 minutes, render as Genesis-luxury-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute Kia-EV9 reel — extend to 3 minutes, style as Kia-EV-poster, and overlay English captions.",
    "Uploading a 30-second Toyota-GR-Corolla reel — extend to 90 seconds, convert to Toyota-Gazoo-poster, and add English subtitles.",
    "Here's a 45-second Toyota-Crown-Signia reel — extend to 2 minutes, render as Toyota-Crown-blueprint, and overlay English captions.",
    "I have a 1-minute Lexus-LC500 reel — extend to 3 minutes, style as Lexus-flagship-poster, and add English subtitles.",
    "Uploading a 30-second Honda-Civic-Type-R reel — extend to 90 seconds, convert to Mugen-poster, and overlay English captions.",
    "Here's a 45-second Acura-Integra-Type-S reel — extend to 2 minutes, render as Acura-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute Mazda-MX-5-Miata-RF reel — extend to 3 minutes, style as Mazda-Hiroshima-poster, and overlay English captions.",
    "Uploading a 30-second Subaru-WRX-STI reel — extend to 90 seconds, convert to Subaru-rally-blueprint, and add English subtitles.",
    "Here's a 45-second Nissan-Z reel — extend to 2 minutes, render as Nissan-Z-poster, and overlay English captions.",
    "I have a 1-minute Nissan-GT-R-Nismo reel — extend to 3 minutes, style as Nismo-blueprint, and add English subtitles.",
    "Uploading a 30-second Ducati-Panigale-V4 reel — extend to 90 seconds, convert to Ducati-Borgo-Panigale-poster, and overlay English captions.",
    "Here's a 45-second BMW-M-1000-RR reel — extend to 2 minutes, render as BMW-Motorrad-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute Aprilia-RSV4 reel — extend to 3 minutes, style as Noale-poster, and overlay English captions.",
    "Uploading a 30-second MV-Agusta-Brutale reel — extend to 90 seconds, convert to MV-Agusta-Schiranna-blueprint, and add English subtitles.",
    "Here's a 45-second Triumph-Speed-Triple reel — extend to 2 minutes, render as Triumph-Hinckley-poster, and overlay English captions.",
    # ── more luxury-watch / jewelry / leather-goods reviews + heritage-poster styles (50) ──
    "Uploading a 30-second Patek-Philippe-Calatrava reel — extend to 90 seconds, convert to Patek-Philippe-Geneva-poster, and add English subtitles.",
    "Here's a 45-second Patek-Philippe-Nautilus reel — extend to 2 minutes, render as Patek-Nautilus-blueprint, and overlay English captions.",
    "I have a 1-minute Patek-Philippe-Aquanaut reel — extend to 3 minutes, style as Patek-Aquanaut-poster, and add English subtitles.",
    "Uploading a 30-second Audemars-Piguet-Royal-Oak reel — extend to 90 seconds, convert to AP-Le-Brassus-poster, and overlay English captions.",
    "Here's a 45-second Audemars-Piguet-Royal-Oak-Offshore reel — extend to 2 minutes, render as AP-Offshore-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute Vacheron-Constantin-Overseas reel — extend to 3 minutes, style as Vacheron-Geneva-poster, and overlay English captions.",
    "Uploading a 30-second Vacheron-Constantin-Patrimony reel — extend to 90 seconds, convert to Vacheron-Patrimony-blueprint, and add English subtitles.",
    "Here's a 45-second A-Lange-Sohne-Lange-1 reel — extend to 2 minutes, render as Lange-Glashütte-poster, and overlay English captions.",
    "I have a 1-minute A-Lange-Sohne-Datograph reel — extend to 3 minutes, style as Lange-Datograph-blueprint, and add English subtitles.",
    "Uploading a 30-second Rolex-Submariner reel — extend to 90 seconds, convert to Rolex-Geneva-poster, and overlay English captions.",
    "Here's a 45-second Rolex-Daytona reel — extend to 2 minutes, render as Rolex-Daytona-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute Rolex-GMT-Master-II reel — extend to 3 minutes, style as Rolex-GMT-poster, and overlay English captions.",
    "Uploading a 30-second Omega-Speedmaster-Moonwatch reel — extend to 90 seconds, convert to Omega-Biel-poster, and add English subtitles.",
    "Here's a 45-second Omega-Seamaster-300 reel — extend to 2 minutes, render as Omega-Seamaster-blueprint, and overlay English captions.",
    "I have a 1-minute IWC-Big-Pilot reel — extend to 3 minutes, style as IWC-Schaffhausen-poster, and add English subtitles.",
    "Uploading a 30-second IWC-Portugieser reel — extend to 90 seconds, convert to IWC-Portugieser-blueprint, and overlay English captions.",
    "Here's a 45-second Jaeger-LeCoultre-Reverso reel — extend to 2 minutes, render as JLC-Le-Sentier-poster, and add English subtitles.",
    "I'm sending you a 1-minute Jaeger-LeCoultre-Master-Control reel — extend to 3 minutes, style as JLC-Master-blueprint, and overlay English captions.",
    "Uploading a 30-second Cartier-Tank reel — extend to 90 seconds, convert to Cartier-Paris-poster, and add English subtitles.",
    "Here's a 45-second Cartier-Santos reel — extend to 2 minutes, render as Cartier-Santos-blueprint, and overlay English captions.",
    "I have a 1-minute Cartier-Ballon-Bleu reel — extend to 3 minutes, style as Cartier-Ballon-poster, and add English subtitles.",
    "Uploading a 30-second Hermès-Birkin-bag reel — extend to 90 seconds, convert to Hermès-Faubourg-poster, and overlay English captions.",
    "Here's a 45-second Hermès-Kelly-bag reel — extend to 2 minutes, render as Hermès-Kelly-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute Hermès-Constance-bag reel — extend to 3 minutes, style as Hermès-Constance-poster, and overlay English captions.",
    "Uploading a 30-second Louis-Vuitton-Speedy reel — extend to 90 seconds, convert to LV-Asnières-poster, and add English subtitles.",
    "Here's a 45-second Louis-Vuitton-Neverfull reel — extend to 2 minutes, render as LV-Neverfull-blueprint, and overlay English captions.",
    "I have a 1-minute Louis-Vuitton-Capucines reel — extend to 3 minutes, style as LV-Capucines-poster, and add English subtitles.",
    "Uploading a 30-second Chanel-2.55-flap-bag reel — extend to 90 seconds, convert to Chanel-Rue-Cambon-poster, and overlay English captions.",
    "Here's a 45-second Chanel-Boy-bag reel — extend to 2 minutes, render as Chanel-Boy-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute Chanel-Classic-Flap reel — extend to 3 minutes, style as Chanel-Classic-poster, and overlay English captions.",
    "Uploading a 30-second Dior-Lady-Dior-bag reel — extend to 90 seconds, convert to Dior-Avenue-Montaigne-poster, and add English subtitles.",
    "Here's a 45-second Dior-Saddle-bag reel — extend to 2 minutes, render as Dior-Saddle-blueprint, and overlay English captions.",
    "I have a 1-minute Dior-Book-Tote reel — extend to 3 minutes, style as Dior-Book-poster, and add English subtitles.",
    "Uploading a 30-second Bottega-Veneta-Pouch reel — extend to 90 seconds, convert to Bottega-Veneta-Vicenza-poster, and overlay English captions.",
    "Here's a 45-second Bottega-Veneta-Cassette reel — extend to 2 minutes, render as Bottega-Cassette-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute Loewe-Puzzle-bag reel — extend to 3 minutes, style as Loewe-Madrid-poster, and overlay English captions.",
    "Uploading a 30-second Loewe-Hammock-bag reel — extend to 90 seconds, convert to Loewe-Hammock-blueprint, and add English subtitles.",
    "Here's a 45-second Goyard-Saint-Louis-tote reel — extend to 2 minutes, render as Goyard-Faubourg-poster, and overlay English captions.",
    "I have a 1-minute Berluti-shoe-patina reel — extend to 3 minutes, style as Berluti-Paris-poster, and add English subtitles.",
    "Uploading a 30-second Edward-Green-shoe-patina reel — extend to 90 seconds, convert to Edward-Green-Northampton-poster, and overlay English captions.",
    "Here's a 45-second John-Lobb-shoemaking reel — extend to 2 minutes, render as John-Lobb-Saint-James-poster, and add English subtitles.",
    "I'm sending you a 1-minute Crockett-and-Jones reel — extend to 3 minutes, style as Crockett-Jones-Northampton-poster, and overlay English captions.",
    "Uploading a 30-second Tiffany-Schlumberger-jewelry reel — extend to 90 seconds, convert to Tiffany-Fifth-Avenue-poster, and add English subtitles.",
    "Here's a 45-second Bulgari-Serpenti-bracelet reel — extend to 2 minutes, render as Bulgari-Roma-poster, and overlay English captions.",
    "I have a 1-minute Van-Cleef-and-Arpels-Alhambra reel — extend to 3 minutes, style as Van-Cleef-Place-Vendôme-poster, and add English subtitles.",
    "Uploading a 30-second Boucheron-Quatre-ring reel — extend to 90 seconds, convert to Boucheron-Place-Vendôme-poster, and overlay English captions.",
    "Here's a 45-second Mikimoto-pearl-strand reel — extend to 2 minutes, render as Mikimoto-Toba-poster, and add English subtitles.",
    "I'm sending you a 1-minute Pomellato-Nudo-ring reel — extend to 3 minutes, style as Pomellato-Milano-poster, and overlay English captions.",
    "Uploading a 30-second Buccellati-Tulle-bracelet reel — extend to 90 seconds, convert to Buccellati-Milano-poster, and add English subtitles.",
    "Here's a 45-second Verdura-Maltese-cross-cuff reel — extend to 2 minutes, render as Verdura-Fifth-Avenue-poster, and overlay English captions.",
    # ── more home-renovation / DIY-tutorial reels + blueprint / architectural illustration styles (50) ──
    "Uploading a 30-second IKEA-Pax-wardrobe-build reel — extend to 90 seconds, convert to IKEA-Pax-blueprint, and add English subtitles.",
    "Here's a 45-second IKEA-Hemnes-bed-build reel — extend to 2 minutes, render as IKEA-Hemnes-blueprint, and overlay English captions.",
    "I have a 1-minute IKEA-Billy-bookcase-build reel — extend to 3 minutes, style as IKEA-Billy-blueprint, and add English subtitles.",
    "Uploading a 30-second IKEA-Kallax-shelf-build reel — extend to 90 seconds, convert to IKEA-Kallax-blueprint, and overlay English captions.",
    "Here's a 45-second IKEA-Malm-dresser-build reel — extend to 2 minutes, render as IKEA-Malm-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute IKEA-kitchen-Method-cabinet-install reel — extend to 3 minutes, style as IKEA-Method-blueprint, and overlay English captions.",
    "Uploading a 30-second laminate-flooring-install reel — extend to 90 seconds, convert to floor-cross-section-blueprint, and add English subtitles.",
    "Here's a 45-second engineered-hardwood-install reel — extend to 2 minutes, render as engineered-hardwood-blueprint, and overlay English captions.",
    "I have a 1-minute herringbone-parquet-install reel — extend to 3 minutes, style as herringbone-parquet-blueprint, and add English subtitles.",
    "Uploading a 30-second subway-tile-bathroom-install reel — extend to 90 seconds, convert to subway-tile-grout-blueprint, and overlay English captions.",
    "Here's a 45-second hexagonal-tile-floor-install reel — extend to 2 minutes, render as hexagonal-tile-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute encaustic-cement-tile-install reel — extend to 3 minutes, style as encaustic-cement-tile-blueprint, and overlay English captions.",
    "Uploading a 30-second drywall-skim-coat-install reel — extend to 90 seconds, convert to drywall-finish-blueprint, and add English subtitles.",
    "Here's a 45-second crown-molding-install reel — extend to 2 minutes, render as crown-molding-cross-section-blueprint, and overlay English captions.",
    "I have a 1-minute wainscoting-install reel — extend to 3 minutes, style as wainscoting-blueprint, and add English subtitles.",
    "Uploading a 30-second beadboard-paneling-install reel — extend to 90 seconds, convert to beadboard-blueprint, and overlay English captions.",
    "Here's a 45-second shiplap-wall-install reel — extend to 2 minutes, render as shiplap-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute coffered-ceiling-install reel — extend to 3 minutes, style as coffered-ceiling-blueprint, and overlay English captions.",
    "Uploading a 30-second tray-ceiling-install reel — extend to 90 seconds, convert to tray-ceiling-blueprint, and add English subtitles.",
    "Here's a 45-second custom-built-in-bookcase reel — extend to 2 minutes, render as built-in-bookcase-blueprint, and overlay English captions.",
    "I have a 1-minute kitchen-island-install reel — extend to 3 minutes, style as kitchen-island-blueprint, and add English subtitles.",
    "Uploading a 30-second waterfall-quartz-counter-install reel — extend to 90 seconds, convert to waterfall-counter-blueprint, and overlay English captions.",
    "Here's a 45-second butcher-block-counter-install reel — extend to 2 minutes, render as butcher-block-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute farmhouse-sink-install reel — extend to 3 minutes, style as farmhouse-sink-blueprint, and overlay English captions.",
    "Uploading a 30-second clawfoot-tub-install reel — extend to 90 seconds, convert to clawfoot-tub-blueprint, and add English subtitles.",
    "Here's a 45-second walk-in-shower-install reel — extend to 2 minutes, render as walk-in-shower-blueprint, and overlay English captions.",
    "I have a 1-minute steam-shower-install reel — extend to 3 minutes, style as steam-shower-blueprint, and add English subtitles.",
    "Uploading a 30-second sauna-cedar-install reel — extend to 90 seconds, convert to cedar-sauna-blueprint, and overlay English captions.",
    "Here's a 45-second wood-burning-fireplace-install reel — extend to 2 minutes, render as wood-burning-fireplace-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute pellet-stove-install reel — extend to 3 minutes, style as pellet-stove-blueprint, and overlay English captions.",
    "Uploading a 30-second deck-building reel — extend to 90 seconds, convert to deck-blueprint, and add English subtitles.",
    "Here's a 45-second pergola-build reel — extend to 2 minutes, render as pergola-blueprint, and overlay English captions.",
    "I have a 1-minute gazebo-build reel — extend to 3 minutes, style as gazebo-blueprint, and add English subtitles.",
    "Uploading a 30-second she-shed-build reel — extend to 90 seconds, convert to she-shed-blueprint, and overlay English captions.",
    "Here's a 45-second tiny-house-build reel — extend to 2 minutes, render as tiny-house-cross-section-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute van-conversion-build reel — extend to 3 minutes, style as van-conversion-blueprint, and overlay English captions.",
    "Uploading a 30-second tiny-house-on-wheels-build reel — extend to 90 seconds, convert to tiny-house-on-wheels-blueprint, and add English subtitles.",
    "Here's a 45-second container-house-build reel — extend to 2 minutes, render as container-house-blueprint, and overlay English captions.",
    "I have a 1-minute cob-cottage-build reel — extend to 3 minutes, style as cob-cottage-blueprint, and add English subtitles.",
    "Uploading a 30-second straw-bale-house-build reel — extend to 90 seconds, convert to straw-bale-blueprint, and overlay English captions.",
    "Here's a 45-second adobe-courtyard-house-build reel — extend to 2 minutes, render as adobe-courtyard-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute earthship-Taos-build reel — extend to 3 minutes, style as earthship-Taos-blueprint, and overlay English captions.",
    "Uploading a 30-second timber-frame-barn-build reel — extend to 90 seconds, convert to timber-frame-barn-blueprint, and add English subtitles.",
    "Here's a 45-second post-and-beam-build reel — extend to 2 minutes, render as post-and-beam-blueprint, and overlay English captions.",
    "I have a 1-minute log-cabin-build reel — extend to 3 minutes, style as log-cabin-blueprint, and add English subtitles.",
    "Uploading a 30-second yurt-frame-build reel — extend to 90 seconds, convert to yurt-blueprint, and overlay English captions.",
    "Here's a 45-second hexa-yurt-build reel — extend to 2 minutes, render as hexayurt-blueprint, and add English subtitles.",
    "I'm sending you a 1-minute geodesic-dome-build reel — extend to 3 minutes, style as geodesic-dome-blueprint, and overlay English captions.",
    "Uploading a 30-second backyard-pizza-oven-build reel — extend to 90 seconds, convert to wood-fired-pizza-oven-blueprint, and add English subtitles.",
    "Here's a 45-second masonry-wood-fired-oven-build reel — extend to 2 minutes, render as masonry-oven-blueprint, and overlay English captions.",
    # ── more glassblowing + metalsmithing + technical-illustration styles + EN subs (50) ──
    "I'm sending you a 1-minute Murano-glass-blowing-furnace reel — extend to 3 minutes, style as Murano-technical-illustration, and overlay English captions.",
    "Uploading a 30-second Venetian-cristallo-pull reel — extend to 90 seconds, convert to Venetian-cristallo-illustration, and add English subtitles.",
    "Here's a 45-second Czech-Bohemian-crystal-cutting reel — extend to 2 minutes, render as Bohemian-crystal-illustration, and overlay English captions.",
    "I have a 1-minute Waterford-crystal-blowing reel — extend to 3 minutes, style as Waterford-crystal-illustration, and add English subtitles.",
    "Uploading a 30-second Steuben-American-crystal-blowing reel — extend to 90 seconds, convert to Steuben-illustration, and overlay English captions.",
    "Here's a 45-second Lalique-French-crystal-cast reel — extend to 2 minutes, render as Lalique-cast-illustration, and add English subtitles.",
    "I'm sending you a 1-minute Baccarat-crystal-blowing reel — extend to 3 minutes, style as Baccarat-illustration, and overlay English captions.",
    "Uploading a 30-second Riedel-stemware-blowing reel — extend to 90 seconds, convert to Riedel-stemware-illustration, and add English subtitles.",
    "Here's a 45-second Edinburgh-crystal-cutting reel — extend to 2 minutes, render as Edinburgh-crystal-illustration, and overlay English captions.",
    "I have a 1-minute Swedish-Orrefors-crystal reel — extend to 3 minutes, style as Orrefors-crystal-illustration, and add English subtitles.",
    "Uploading a 30-second Finnish-Iittala-glass-blowing reel — extend to 90 seconds, convert to Iittala-glass-illustration, and overlay English captions.",
    "Here's a 45-second Danish-Holmegaard-glass-blowing reel — extend to 2 minutes, render as Holmegaard-illustration, and add English subtitles.",
    "I'm sending you a 1-minute Czech-Moser-cut-glass reel — extend to 3 minutes, style as Moser-illustration, and overlay English captions.",
    "Uploading a 30-second Polish-Krosno-glass reel — extend to 90 seconds, convert to Krosno-illustration, and add English subtitles.",
    "Here's a 45-second German-Riedel-blowing-Tirol reel — extend to 2 minutes, render as Riedel-Tirol-illustration, and overlay English captions.",
    "I have a 1-minute Japanese-Edo-Kiriko-cut-glass reel — extend to 3 minutes, style as Edo-Kiriko-illustration, and add English subtitles.",
    "Uploading a 30-second Japanese-Satsuma-Kiriko-cut reel — extend to 90 seconds, convert to Satsuma-Kiriko-illustration, and overlay English captions.",
    "Here's a 45-second Tibetan-thangka-bronze-casting reel — extend to 2 minutes, render as Tibetan-bronze-illustration, and add English subtitles.",
    "I'm sending you a 1-minute Indian-Dhokra-lost-wax-casting reel — extend to 3 minutes, style as Dhokra-illustration, and overlay English captions.",
    "Uploading a 30-second Damascus-steel-folding-forge reel — extend to 90 seconds, convert to Damascus-steel-illustration, and add English subtitles.",
    "Here's a 45-second Toledo-Spanish-sword-forge reel — extend to 2 minutes, render as Toledo-sword-illustration, and overlay English captions.",
    "I have a 1-minute Solingen-German-knife-forge reel — extend to 3 minutes, style as Solingen-illustration, and add English subtitles.",
    "Uploading a 30-second Sheffield-English-cutlery-forge reel — extend to 90 seconds, convert to Sheffield-cutlery-illustration, and overlay English captions.",
    "Here's a 45-second Seki-Japanese-katana-forge reel — extend to 2 minutes, render as Seki-katana-illustration, and add English subtitles.",
    "I'm sending you a 1-minute Sakai-Japanese-knife-forge reel — extend to 3 minutes, style as Sakai-knife-illustration, and overlay English captions.",
    "Uploading a 30-second Echizen-Japanese-knife-forge reel — extend to 90 seconds, convert to Echizen-illustration, and add English subtitles.",
    "Here's a 45-second Tosa-Japanese-tool-forge reel — extend to 2 minutes, render as Tosa-tool-illustration, and overlay English captions.",
    "I have a 1-minute Bizen-Japanese-pottery-kiln reel — extend to 3 minutes, style as Bizen-kiln-illustration, and add English subtitles.",
    "Uploading a 30-second Albanian-filigree-silversmith reel — extend to 90 seconds, convert to Albanian-filigree-illustration, and overlay English captions.",
    "Here's a 45-second Yemeni-silver-filigree reel — extend to 2 minutes, render as Yemeni-silver-illustration, and add English subtitles.",
    "I'm sending you a 1-minute Berber-silver-jewelry reel — extend to 3 minutes, style as Berber-silver-illustration, and overlay English captions.",
    "Uploading a 30-second Hmong-silver-jewelry reel — extend to 90 seconds, convert to Hmong-silver-illustration, and add English subtitles.",
    "Here's a 45-second Bedouin-silver-jewelry reel — extend to 2 minutes, render as Bedouin-silver-illustration, and overlay English captions.",
    "I have a 1-minute Tuareg-silver-cross-of-Agadez reel — extend to 3 minutes, style as Tuareg-silver-illustration, and add English subtitles.",
    "Uploading a 30-second Nubian-Sudanese-gold reel — extend to 90 seconds, convert to Nubian-gold-illustration, and overlay English captions.",
    "Here's a 45-second Ashanti-Ghanaian-gold-weight reel — extend to 2 minutes, render as Ashanti-gold-illustration, and add English subtitles.",
    "I'm sending you a 1-minute Inca-Peruvian-goldsmith reel — extend to 3 minutes, style as Inca-gold-illustration, and overlay English captions.",
    "Uploading a 30-second Aztec-Mexican-goldsmith reel — extend to 90 seconds, convert to Aztec-gold-illustration, and add English subtitles.",
    "Here's a 45-second Etruscan-granulation-gold reel — extend to 2 minutes, render as Etruscan-gold-illustration, and overlay English captions.",
    "I have a 1-minute Fabergé-Russian-egg-craft reel — extend to 3 minutes, style as Fabergé-illustration, and add English subtitles.",
    "Uploading a 30-second Tiffany-NYC-silversmith-shop reel — extend to 90 seconds, convert to Tiffany-NYC-silver-illustration, and overlay English captions.",
    "Here's a 45-second Cartier-Paris-jewelry-atelier reel — extend to 2 minutes, render as Cartier-atelier-illustration, and add English subtitles.",
    "I'm sending you a 1-minute Bulgari-Rome-atelier reel — extend to 3 minutes, style as Bulgari-atelier-illustration, and overlay English captions.",
    "Uploading a 30-second Van-Cleef-Arpels-Place-Vendôme reel — extend to 90 seconds, convert to Van-Cleef-atelier-illustration, and add English subtitles.",
    "Here's a 45-second Boucheron-Paris-jewelry-atelier reel — extend to 2 minutes, render as Boucheron-atelier-illustration, and overlay English captions.",
    "I have a 1-minute Mikimoto-Tokyo-pearl-stringing reel — extend to 3 minutes, style as Mikimoto-pearl-illustration, and add English subtitles.",
    "Uploading a 30-second Ago-Bay-Japanese-pearl-farm reel — extend to 90 seconds, convert to Ago-Bay-pearl-illustration, and overlay English captions.",
    "Here's a 45-second Bahrain-pearl-diving reel — extend to 2 minutes, render as Bahrain-pearl-illustration, and add English subtitles.",
    "I'm sending you a 1-minute Tahiti-black-pearl-farm reel — extend to 3 minutes, style as Tahiti-black-pearl-illustration, and overlay English captions.",
    "Uploading a 30-second Broome-Australian-pearl-farm reel — extend to 90 seconds, convert to Broome-pearl-illustration, and add English subtitles.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
