"""x15 story_imgref GRPO. Disjoint from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a sketch of a young Yupik fisherboy — make a children's audiobook of his Arctic-shore day.",
    "Here's a portrait of a young Cree-elder grandmother — produce a kids' audiobook of her storytelling around a fire.",
    "I'm sending you a watercolor of a young Inuktitut grandmother — build an illustrated children's tale of her sewing skin boots.",
    "Uploading a digital painting of a young Ojibwe boy — make a bedtime audiobook of his wild-rice harvest.",
    "Here's a sketch of a young Lakota grandmother — render a kids' audiobook of her hair-braiding lesson.",
    "Attaching a portrait of a young Navajo silversmith girl — produce a children's audiobook of her turquoise-ring day.",
    "Uploading a digital portrait of a young Apache girl — make a bedtime audiobook of her desert-trail walk.",
    "Here's a watercolor of a young Cherokee weaver girl — build an illustrated children's tale of her loom afternoon.",
    "I'd like a kids' audiobook from this sketch of a young Hopi farmer-girl.",
    "Uploading a digital painting of a young Zuni potter girl — render a picture-book audiobook of her clay morning.",
    "Here's a portrait of a young Navajo weaver-grandmother — produce a children's audiobook of her loom day.",
    "I have a sketch of a young Pueblo bread-baker girl — make a bedtime audiobook of her morning at the horno oven.",
    "Uploading a watercolor of a young Mapuche-grandmother weaver — build an illustrated children's tale of her loom afternoon.",
    "Here's a digital painting of a young Aymara herdsboy — render a picture-book audiobook of his llama-trail morning.",
    "I'm sending you a sketch of a young Quechua-grandmother weaver — produce a children's audiobook of her market morning.",
    "Uploading a portrait of a young Garifuna drummer — make a bedtime audiobook of his ocean-side rhythm.",
    "Here's a watercolor of a young Haitian Kreyòl baker girl — build an illustrated children's tale of her firing the stone oven.",
    "I have a digital portrait of a young Jamaican Patois fishergirl — render a children's audiobook of her Negril morning catch.",
    "Uploading a sketch of a young Rastafarian drummer-boy — produce a kids' audiobook of his hilltop reggae lesson.",
    "Here's a portrait of a young Trinidadian carnival girl — make a bedtime audiobook of her parade afternoon.",
    "I'm sending you a watercolor of a young Saint-Lucian limbo girl — build an illustrated children's tale of her beach festival.",
    "Uploading a digital painting of a young Bahamian junkanoo boy — render a kids' audiobook of his goombay drumming.",
    "Here's a sketch of a young Bermudian bermuda-shorts grandfather — produce a children's audiobook of his pink-sand-beach morning.",
    "I have a portrait of a young Cayman-fisherman boy — make a bedtime audiobook of his island-cave morning.",
    "Uploading a watercolor of a young Curaçaoan tula-singer girl — build an illustrated children's tale of her Willemstad porch concert.",
    "Here's a digital portrait of a young Aruban cunucu-house girl — render a kids' audiobook of her cactus-garden morning.",
    "I'm sending you a sketch of a young Bonaire flamingo-watcher girl — produce a children's audiobook of her salt-pond afternoon.",
    "Uploading a portrait of a young Saint-Vincent volcano-watcher boy — make a bedtime audiobook of his rainforest hike.",
    "Here's a watercolor of a young Grenadan nutmeg-farmer girl — build an illustrated children's tale of her market morning.",
    "I have a digital painting of a young Dominica-Kalinago basket-weaver girl — render a kids' audiobook of her village afternoon.",
    "Uploading a sketch of a young Antiguan steel-pan player girl — produce a children's audiobook of her courtyard practice.",
    "Here's a portrait of a young Saint-Kitts mango-vendor girl — make a bedtime audiobook of her market afternoon.",
    "I'm sending you a watercolor of a young Anguillian fisherman boy — build an illustrated children's tale of his beach morning.",
    "Uploading a digital portrait of a young Saint-Martin créole girl — render a kids' audiobook of her marina-stroll morning.",
    "Here's a sketch of a young Saint-Barth-fisherman girl — produce a children's audiobook of her dawn boat.",
    # ── more reference-image illustrated children's audiobooks (50) ────────
    "Uploading a portrait of a young Filipino fisher girl — make a children's audiobook of her Visayan-island morning.",
    "Here's a sketch of a young Hong-Kong tea-seller boy — produce a kids' picture-book audiobook of his market dawn.",
    "I'm sending you a watercolor of a young Macau Patuá girl — build an illustrated children's tale of her Senado-Square afternoon.",
    "Uploading a digital painting of a young Taiwanese Atayal girl — make a bedtime audiobook of her mountain-village morning.",
    "Here's a sketch of a young Mongolian Kazakh eagle-hunter — render an illustrated children's audiobook of her snow-ridge dawn.",
    "Attaching a portrait of a young Buryat shamanka — produce a children's audiobook of her Lake-Baikal morning.",
    "Uploading a digital portrait of a young Yakut horse-girl — make a bedtime audiobook of her Sakha-summer ride.",
    "Here's a watercolor of a young Ainu fisherman boy — build an illustrated children's tale of his Hokkaido-shore dawn.",
    "I'd like a kids' audiobook from this sketch of a young Ryukyuan dancer girl in Naha.",
    "Uploading a digital painting of a young Tuvan throat-singer boy — render a picture-book audiobook of his steppe-evening practice.",
    "Here's a portrait of a young Yemeni Sana'a old-city girl — produce a children's audiobook of her tower-house morning.",
    "I have a sketch of a young Omani frankincense-collector girl — make a bedtime audiobook of her Boswellia-grove dawn.",
    "Uploading a watercolor of a young Druze grandmother — build an illustrated children's tale of her mountain-village afternoon.",
    "Here's a digital painting of a young Bedouin-Negev girl — render a picture-book audiobook of her tent-tea morning.",
    "I'm sending you a sketch of a young Iranian Qom calligrapher girl — produce a children's audiobook of her ink-and-reed afternoon.",
    "Uploading a portrait of a young Kurdish shepherdess girl — make a bedtime audiobook of her Zagros-mountain morning.",
    "Here's a watercolor of a young Georgian wine-maker girl — build an illustrated children's audiobook of her Kakheti-vineyard afternoon.",
    "I have a digital portrait of a young Armenian Yerevan poet girl — render a children's audiobook of her café-balcony evening.",
    "Uploading a sketch of a young Azerbaijani tar-player girl — produce a kids' audiobook of her Baku-courtyard rehearsal.",
    "Here's a portrait of a young Chechen mountain-girl — make a bedtime audiobook of her Caucasus-meadow morning.",
    "I'm sending you a watercolor of a young Pomeranian fisherman boy — build an illustrated children's tale of his Baltic-shore dawn.",
    "Uploading a digital painting of a young Frisian dyke-keeper boy — render a kids' audiobook of his sea-wall morning.",
    "Here's a sketch of a young Walloon coalminer boy — produce a children's audiobook of his pithead morning.",
    "I have a portrait of a young Flemish lace-maker girl — make a bedtime audiobook of her Bruges-window afternoon.",
    "Uploading a watercolor of a young Luxembourgish ironworker boy — build an illustrated children's tale of his foundry-floor morning.",
    "Here's a digital portrait of a young Swiss alphorn-player boy — render a kids' audiobook of his alpine-dawn melody.",
    "I'm sending you a sketch of a young Tyrolean shepherdess — produce a children's audiobook of her dolomite-pasture afternoon.",
    "Uploading a portrait of a young Bavarian beer-keeper girl — make a bedtime audiobook of her cellar-stairs evening.",
    "Here's a watercolor of a young Black-Forest cuckoo-clock-maker girl — build an illustrated children's tale of her workshop-window afternoon.",
    "I have a digital painting of a young Schleswig-Holstein boatbuilder boy — render a kids' audiobook of his slipway morning.",
    "Uploading a sketch of a young Egyptian Nubian girl — produce a children's audiobook of her Aswan-island morning.",
    "Here's a portrait of a young Sudanese Nubian girl — make a bedtime audiobook of her Nile-river afternoon.",
    "I'm sending you a watercolor of a young Ugandan Buganda drummer — build an illustrated children's tale of his courtyard rehearsal.",
    "Uploading a digital portrait of a young Tanzanian Sukuma villager — render a kids' audiobook of her Mwanza-shore morning.",
    "Here's a sketch of a young Kenyan Turkana fisherboy — produce a children's audiobook of his Lake-Turkana dawn.",
    "I have a portrait of a young Ethiopian Oromo girl — make a bedtime audiobook of her highland-meadow afternoon.",
    "Uploading a watercolor of a young Somali fisherman boy — build an illustrated children's tale of his Mogadishu-harbor dawn.",
    "Here's a digital portrait of a young Eritrean tea-girl — render a kids' audiobook of her Asmara-cafe morning.",
    "I'm sending you a sketch of a young Mozambican Makonde mask-carver — produce a children's audiobook of his Pemba-village afternoon.",
    "Uploading a portrait of a young South-African Xhosa girl — make a bedtime audiobook of her Eastern-Cape morning.",
    "Here's a watercolor of a young Punjabi dhol-player boy — build an illustrated children's tale of his courtyard practice.",
    "I have a digital painting of a young Bengali Durga-puja girl — render a kids' audiobook of her pandal-evening procession.",
    "Uploading a sketch of a young Marathi tabla-student boy — produce a children's audiobook of his Pune-courtyard morning.",
    "Here's a portrait of a young Telugu Kuchipudi girl — make a bedtime audiobook of her temple-courtyard rehearsal.",
    "I'm sending you a watercolor of a young Kerala fisher girl — build an illustrated children's tale of her backwater dawn.",
    "Uploading a digital painting of a young Sinhalese mask-maker boy — render a kids' audiobook of his Ambalangoda-workshop afternoon.",
    "Here's a sketch of a young Nepali Sherpa porter — produce a children's audiobook of his Khumbu-valley climb.",
    "I have a portrait of a young Bhutanese archer girl — make a bedtime audiobook of her Thimphu-festival afternoon.",
    "Uploading a watercolor of a young Tibetan monastery-scribe boy — build an illustrated children's tale of his Lhasa-temple morning.",
    "Here's a digital portrait of a young Bangladeshi rickshaw-art girl — render a kids' audiobook of her Dhaka-courtyard afternoon.",
    # ── more reference-image illustrated children's audiobooks (50) ────────
    "Uploading a portrait of a young 1860s Lehigh Valley coal-breaker boy — make a children's audiobook of his pithead morning.",
    "Here's a sketch of a young 1880s Pennsylvania Quaker girl — produce a kids' picture-book audiobook of her meeting-house afternoon.",
    "I'm sending you a watercolor of a young 1890s Atlantic-City lifeguard — build an illustrated children's tale of her boardwalk morning.",
    "Uploading a digital painting of a young 1900s Coney-Island ride-attendant — make a bedtime audiobook of his carousel evening.",
    "Here's a sketch of a young 1920s Times-Square newspaperboy — render an illustrated children's audiobook of his crosswalk dawn.",
    "Attaching a portrait of a young 1930s WPA muralist — produce a children's audiobook of her post-office wall afternoon.",
    "Uploading a digital portrait of a young 1940s Rosie-the-Riveter — make a bedtime audiobook of her aircraft-factory shift.",
    "Here's a watercolor of a young 1950s drive-in-attendant — build an illustrated children's tale of her speaker-pole evening.",
    "I'd like a kids' audiobook from this sketch of a young 1960s civil-rights organizer at a community center.",
    "Uploading a digital painting of a young 1970s second-wave feminist organizer — render a picture-book audiobook of her March-rally afternoon.",
    "Here's a portrait of a young 1980s NYC subway-dancer — produce a children's audiobook of her platform evening.",
    "I have a sketch of a young 1990s riot-grrrl drummer — make a bedtime audiobook of her Olympia basement-show.",
    "Uploading a watercolor of a young 2000s San-Francisco skater — build an illustrated children's tale of her Embarcadero afternoon.",
    "Here's a digital painting of a young 2010s Brooklyn coffee-roaster — render a picture-book audiobook of her Bushwick-roastery morning.",
    "I'm sending you a sketch of a young 1880s Wisconsin cheesemaker boy — produce a children's audiobook of his cheese-cellar morning.",
    "Uploading a portrait of a young 1900s North-Dakota homestead girl — make a bedtime audiobook of her sod-house morning.",
    "Here's a watercolor of a young 1900s North-Dakota wheat-farmer boy — build an illustrated children's audiobook of his harvest-day morning.",
    "I have a digital portrait of a young 1900s Montana sheep-herder — render a children's audiobook of his pasture afternoon.",
    "Uploading a sketch of a young 1900s Wyoming cowgirl — produce a kids' audiobook of her round-up afternoon.",
    "Here's a portrait of a young 1900s Idaho potato-farmer — make a bedtime audiobook of his furrow morning.",
    "I'm sending you a watercolor of a young 1880s Utah pioneer girl — build an illustrated children's tale of her Salt-Lake-Valley dawn.",
    "Uploading a digital painting of a young 1880s Nevada miner — render a kids' audiobook of his silver-mine night.",
    "Here's a sketch of a young 1880s Colorado-silver-miner — produce a children's audiobook of his pithead morning.",
    "I have a portrait of a young 1880s Washington-territory logger — make a bedtime audiobook of his cedar-grove morning.",
    "Uploading a watercolor of a young 1880s Oregon-Trail wagon-girl — build an illustrated children's tale of her Platte-River morning.",
    "Here's a digital portrait of a young 1880s California-mission boy — render a kids' audiobook of his bell-tower evening.",
    "I'm sending you a sketch of a young 1880s San-Francisco shipwright — produce a children's audiobook of his shipyard morning.",
    "Uploading a portrait of a young 1900s Alaskan canning-girl — make a bedtime audiobook of her Bristol-Bay afternoon.",
    "Here's a watercolor of a young 1900s Maine-lobsterman boy — build an illustrated children's audiobook of his Penobscot-Bay dawn.",
    "I have a digital painting of a young 1900s New-Hampshire textile-mill girl — render a kids' audiobook of her Manchester-mill afternoon.",
    "Uploading a sketch of a young 1900s Vermont maple-tapper — produce a children's audiobook of his sugar-shack dawn.",
    "Here's a portrait of a young 1900s Cape-Cod whaler boy — make a bedtime audiobook of his Provincetown harbor evening.",
    "I'm sending you a watercolor of a young 1900s Rhode-Island silversmith — build an illustrated children's tale of her Providence-bench afternoon.",
    "Uploading a digital portrait of a young 1900s Connecticut clockmaker — render a kids' audiobook of his Hartford-bench morning.",
    "Here's a sketch of a young 1900s NY-Lower-East-Side garment-girl — produce a children's audiobook of her Allen-Street-loft afternoon.",
    "I have a portrait of a young 1900s Pittsburgh steel-girl — make a bedtime audiobook of her Bessemer-mill afternoon.",
    "Uploading a watercolor of a young 1900s Detroit auto-line worker — build an illustrated children's tale of his Highland-Park-floor afternoon.",
    "Here's a digital painting of a young 1900s Chicago meatpacker — render a picture-book audiobook of her stockyards-line morning.",
    "I'm sending you a sketch of a young 1900s Cincinnati pork-butcher — produce a children's audiobook of his Over-the-Rhine shop morning.",
    "Uploading a portrait of a young 1900s Memphis cotton-picker — make a bedtime audiobook of her Mississippi-river-field morning.",
    "Here's a watercolor of a young 1900s Texas oil-driller — build an illustrated children's audiobook of his Spindletop-tower afternoon.",
    "I have a digital portrait of a young 1900s Mississippi-Delta sharecropper — render a kids' audiobook of his levee-evening.",
    "Uploading a sketch of a young 1900s Louisiana-shrimp-boat girl — produce a children's audiobook of her Bayou-Lafourche dawn.",
    "Here's a portrait of a young 1900s Florida-citrus-picker boy — make a bedtime audiobook of his orange-grove morning.",
    "I'm sending you a watercolor of a young 1900s Cuban-cigar-roller — build an illustrated children's tale of her Ybor-City-bench afternoon.",
    "Uploading a digital painting of a young 1900s Mexican-American taqueria-girl — render a kids' audiobook of her Olvera-Street afternoon.",
    "Here's a sketch of a young 1900s Arizona-territory ranch-boy — produce a children's audiobook of his cactus-pasture morning.",
    "I have a portrait of a young 1900s New-Mexico-territory Pueblo-trader — make a bedtime audiobook of his Albuquerque-plaza afternoon.",
    "Uploading a watercolor of a young 1900s Colorado-mining-camp boy — build an illustrated children's tale of his Cripple-Creek morning.",
    "Here's a digital portrait of a young 1900s Yellowstone-park ranger — render a kids' audiobook of her Old-Faithful morning.",
    # ── more 1900s European workers / youths (50) ──
    "I have a portrait of a young 1900s East-End-London match-girl — make a bedtime audiobook of her factory-evening.",
    "Uploading a watercolor of a young 1900s Welsh coal-mining boy — build an illustrated children's tale of his pit-dawn.",
    "Here's a digital portrait of a young 1900s Scottish-shipbuilder daughter — render a kids' audiobook of her Clydeside morning.",
    "I'm sending you a sketch of a young 1900s Liverpool-dock loader — produce a children's audiobook of his Mersey-quay afternoon.",
    "Uploading a portrait of a young 1900s Belfast-linen-mill girl — make a bedtime audiobook of her loom evening.",
    "Here's a watercolor of a young 1900s Dublin-tenement boy — build an illustrated children's tale of his Liffey morning.",
    "I have a digital painting of a young 1900s Cork-fish-curing girl — render a kids' audiobook of her quay afternoon.",
    "Uploading a sketch of a young 1900s Galway-island schoolgirl — produce a children's audiobook of her stone-cottage morning.",
    "Here's a portrait of a young 1900s Paris-Montmartre flower-seller — make a bedtime audiobook of her Sacré-Coeur evening.",
    "I'm sending you a watercolor of a young 1900s Belle-Époque seamstress — build an illustrated children's tale of her Marais workshop afternoon.",
    "Uploading a digital portrait of a young 1900s Marseille-fish-market girl — render a kids' audiobook of her Vieux-Port morning.",
    "Here's a sketch of a young 1900s Provence-lavender harvester — produce a children's audiobook of his hilltop afternoon.",
    "I have a portrait of a young 1900s Bordeaux-vineyard girl — make a bedtime audiobook of her chateau-dusk.",
    "Uploading a watercolor of a young 1900s Brittany-fisherwife daughter — build an illustrated children's tale of her quay-dawn.",
    "Here's a digital painting of a young 1900s Alsace-baker apprentice — render a kids' audiobook of his Strasbourg morning.",
    "I'm sending you a sketch of a young 1900s Berlin-Mietskaserne boy — produce a children's audiobook of his courtyard afternoon.",
    "Uploading a portrait of a young 1900s Ruhr-coal-miner — make a bedtime audiobook of his pit-evening.",
    "Here's a watercolor of a young 1900s Hamburg-fish-cannery girl — build an illustrated children's tale of her harbor afternoon.",
    "I have a digital portrait of a young 1900s Munich-brewery apprentice — render a kids' audiobook of his Hofbräuhaus morning.",
    "Uploading a sketch of a young 1900s Black-Forest clockmaker — produce a children's audiobook of his cottage-evening.",
    "Here's a portrait of a young 1900s Vienna-coffee-house waiter — make a bedtime audiobook of his Stephansplatz afternoon.",
    "I'm sending you a watercolor of a young 1900s Salzburg-Christmas-market girl — build an illustrated children's tale of her stall evening.",
    "Uploading a digital painting of a young 1900s Tyrol-shepherd boy — render a kids' audiobook of his alpine morning.",
    "Here's a sketch of a young 1900s Budapest-bath-house attendant — produce a children's audiobook of her Gellért afternoon.",
    "I have a portrait of a young 1900s Prague-glassblower apprentice — make a bedtime audiobook of his Bohemia evening.",
    "Uploading a watercolor of a young 1900s Krakow-market-flower girl — build an illustrated children's tale of her Rynek morning.",
    "Here's a digital portrait of a young 1900s Łódź-textile-mill girl — render a kids' audiobook of her loom-afternoon.",
    "I'm sending you a sketch of a young 1900s Warsaw-tenement boy — produce a children's audiobook of his Praga evening.",
    "Uploading a portrait of a young 1900s Vilnius-bookbinder — make a bedtime audiobook of her workshop afternoon.",
    "Here's a watercolor of a young 1900s Riga-amber-carver — build an illustrated children's tale of his Daugava morning.",
    "I have a digital painting of a young 1900s Tallinn-port girl — render a kids' audiobook of her harbor afternoon.",
    "Uploading a sketch of a young 1900s Helsinki-pulp-mill boy — produce a children's audiobook of his Töölö evening.",
    "Here's a portrait of a young 1900s Stockholm-island fisher-girl — make a bedtime audiobook of her archipelago dawn.",
    "I'm sending you a watercolor of a young 1900s Oslo-fjord boatman — build an illustrated children's tale of his Aker morning.",
    "Uploading a digital portrait of a young 1900s Bergen-fishmonger — render a kids' audiobook of her Bryggen afternoon.",
    "Here's a sketch of a young 1900s Reykjavik-knitter — produce a children's audiobook of her cottage evening.",
    "I have a portrait of a young 1900s Copenhagen-bakery apprentice — make a bedtime audiobook of her Nyhavn morning.",
    "Uploading a watercolor of a young 1900s Madrid-tavern girl — build an illustrated children's tale of her La-Latina afternoon.",
    "Here's a digital painting of a young 1900s Barcelona-mosaic-tile apprentice — render a kids' audiobook of her Eixample morning.",
    "I'm sending you a sketch of a young 1900s Seville-orange-picker — produce a children's audiobook of his Triana afternoon.",
    "Uploading a portrait of a young 1900s Lisbon-fado-club waitress — make a bedtime audiobook of her Alfama evening.",
    "Here's a watercolor of a young 1900s Porto-port-wine apprentice — build an illustrated children's tale of his Ribeira morning.",
    "I have a digital portrait of a young 1900s Naples-fishmonger boy — render a kids' audiobook of his Spaccanapoli afternoon.",
    "Uploading a sketch of a young 1900s Sicilian-sulfur-mine boy — produce a children's audiobook of his Caltanissetta morning.",
    "Here's a portrait of a young 1900s Venice-glassblower apprentice — make a bedtime audiobook of his Murano evening.",
    "I'm sending you a watercolor of a young 1900s Florentine-leather-tannery boy — build an illustrated children's tale of his Oltrarno morning.",
    "Uploading a digital painting of a young 1900s Rome-fountain-water-girl — render a kids' audiobook of her Trevi afternoon.",
    "Here's a sketch of a young 1900s Athens-marble-cutter apprentice — produce a children's audiobook of his Plaka afternoon.",
    "I have a portrait of a young 1900s Istanbul-Grand-Bazaar carpet-weaver — make a bedtime audiobook of her stall evening.",
    "Uploading a watercolor of a young 1900s St-Petersburg-Imperial-Ballet apprentice — build an illustrated children's tale of her Mariinsky morning.",
    # ── more 1900s African / Asian / colonial-era youths (50) ──
    "I have a portrait of a young 1900s Cape-Town-District-Six child — make a bedtime audiobook of her Hanover-Street evening.",
    "I'm sending you a sketch of a young 1900s Johannesburg-Kimberley diamond-sifter — produce a children's audiobook of his diamond-yard afternoon.",
    "Uploading a portrait of a young 1900s Kimberley-Big-Hole boy — make a bedtime audiobook of his pit-rim morning.",
    "Here's a watercolor of a young 1900s Mombasa-port girl — build an illustrated children's tale of her Old-Town quay afternoon.",
    "I have a digital painting of a young 1900s Zanzibar-clove-picker — render a kids' audiobook of her Pemba clove-grove morning.",
    "Uploading a sketch of a young 1900s Lamu-Swahili-dhow boy — produce a children's audiobook of his Lamu harbor afternoon.",
    "Here's a portrait of a young 1900s Asmara-Italian-colonial student — make a bedtime audiobook of her Asmara cinema evening.",
    "I'm sending you a watercolor of a young 1900s Addis-Ababa Imperial-court page — build an illustrated children's tale of her Menelik palace afternoon.",
    "Uploading a digital portrait of a young 1900s Cairo-British-colony schoolboy — render a kids' audiobook of his Garden-City morning.",
    "Here's a sketch of a young 1900s Alexandria-Greek-quarter girl — produce a children's audiobook of her Cleopatra-Boulevard afternoon.",
    "I have a portrait of a young 1900s Tunis-French-protectorate child — make a bedtime audiobook of her Avenue-Bourguiba evening.",
    "Uploading a watercolor of a young 1900s Algiers-Casbah water-seller — build an illustrated children's tale of his Casbah morning.",
    "Here's a digital painting of a young 1900s Oran-French-colony — render a kids' audiobook of his Place-d'Armes afternoon.",
    "I'm sending you a sketch of a young 1900s Marrakesh-medina-mint-tea boy — produce a children's audiobook of his Jemaa-el-Fna afternoon.",
    "Uploading a portrait of a young 1900s Fez-medina-tannery boy — make a bedtime audiobook of his Chouara dye-pit afternoon.",
    "Here's a watercolor of a young 1900s Dakar-Plateau colonial student — build an illustrated children's tale of her Place-de-l'Indépendance afternoon.",
    "I have a digital portrait of a young 1900s Saint-Louis-Senegalese fisher-girl — render a kids' audiobook of her Île-Nord-Saint-Louis afternoon.",
    "Uploading a sketch of a young 1900s Bamako-French-Soudan student — produce a children's audiobook of her Niger-River afternoon.",
    "Here's a portrait of a young 1900s Lagos-Brazilian-Quarter girl — make a bedtime audiobook of her Tinubu-Square afternoon.",
    "I'm sending you a watercolor of a young 1900s Accra-Cape-Coast student — build an illustrated children's tale of his Cape-Coast-Castle afternoon.",
    "Uploading a digital portrait of a young 1900s Freetown-Krio-girl — render a kids' audiobook of her Cotton-Tree afternoon.",
    "Here's a sketch of a young 1900s Monrovia-Americo-Liberian student — produce a children's audiobook of her Mamba-Point afternoon.",
    "I have a portrait of a young 1900s Léopoldville-Belgian-colony port-boy — make a bedtime audiobook of his Stanley-Pool afternoon.",
    "Uploading a watercolor of a young 1900s Brazzaville-French-Equatorial child — build an illustrated children's tale of her Plateau Hotel-Excelsior morning.",
    "Here's a digital painting of a young 1900s Antananarivo-Imerina-court page — render a kids' audiobook of her Rova-palace afternoon.",
    "I'm sending you a sketch of a young 1900s Mauritius-sugar-plantation girl — produce a children's audiobook of her Pamplemousses afternoon.",
    "Uploading a portrait of a young 1900s Réunion-Saint-Denis French girl — make a bedtime audiobook of her Saint-Denis Capucins afternoon.",
    "Here's a watercolor of a young 1900s Mumbai-Bombay-Presidency clerk — build an illustrated children's tale of his Fort-area afternoon.",
    "I have a digital portrait of a young 1900s Calcutta-Bengal-Presidency student — render a kids' audiobook of her College-Street morning.",
    "Uploading a sketch of a young 1900s Madras-Madras-Presidency child — produce a children's audiobook of her Mylapore-Mada-Streets afternoon.",
    "Here's a portrait of a young 1900s Delhi-Lutyens-bungalow servant — make a bedtime audiobook of her Connaught-Place evening.",
    "I'm sending you a watercolor of a young 1900s Karachi-Sindh student — build an illustrated children's tale of his Empress-Market afternoon.",
    "Uploading a digital portrait of a young 1900s Lahore-Punjab-college student — render a kids' audiobook of her Anarkali afternoon.",
    "Here's a sketch of a young 1900s Kabul-Afghan-court page — produce a children's audiobook of his Bala-Hissar afternoon.",
    "I have a portrait of a young 1900s Tehran-Qajar-court student — make a bedtime audiobook of his Golestan-Palace afternoon.",
    "Uploading a watercolor of a young 1900s Baghdad-Ottoman-province student — build an illustrated children's tale of his Mutanabbi-Street afternoon.",
    "Here's a digital painting of a young 1900s Damascus-Ottoman-province student — render a kids' audiobook of her Hamidiyya-Souq afternoon.",
    "I'm sending you a sketch of a young 1900s Beirut-Maronite-Quarter student — produce a children's audiobook of her Gemmayzeh afternoon.",
    "Uploading a portrait of a young 1900s Jerusalem-Armenian-Quarter student — make a bedtime audiobook of her Old-City evening.",
    "Here's a watercolor of a young 1900s Alexandria-Levantine merchant — build an illustrated children's tale of his Ramleh-Station morning.",
    "I have a digital portrait of a young 1900s Saigon-French-Cochinchina girl — render a kids' audiobook of her Rue-Catinat afternoon.",
    "Uploading a sketch of a young 1900s Hanoi-French-Tonkin student — produce a children's audiobook of her Hoan-Kiem-lake afternoon.",
    "Here's a portrait of a young 1900s Phnom-Penh-French-Cambodia child — make a bedtime audiobook of her Royal-Palace evening.",
    "I'm sending you a watercolor of a young 1900s Vientiane-French-Laos child — build an illustrated children's tale of his Patuxay morning.",
    "Uploading a digital portrait of a young 1900s Rangoon-British-Burma student — render a kids' audiobook of her Sule-Pagoda afternoon.",
    "Here's a sketch of a young 1900s Singapore-Straits-Settlements student — produce a children's audiobook of her Boat-Quay afternoon.",
    "I have a portrait of a young 1900s Penang-Straits-Settlements student — make a bedtime audiobook of his Georgetown-Hill evening.",
    "Uploading a watercolor of a young 1900s Manila-Spanish-then-American girl — build an illustrated children's tale of her Escolta-Street afternoon.",
    "Here's a digital painting of a young 1900s Cebu-American-colonial student — render a kids' audiobook of her Magellan-Cross afternoon.",
    "I'm sending you a sketch of a young 1900s Jakarta-Dutch-Batavia child — produce a children's audiobook of her Kota-Tua morning.",
    # ── more 1920s–1930s art-deco / interwar urban (50) ──
    "I have a portrait of a young 1920s NYC-Cotton-Club waiter — make a bedtime audiobook of his Lenox-Avenue evening.",
    "I'm attaching a digital portrait of a young 1920s Chicago-speakeasy bootlegger — build a 30-second cinematic piece at a Cicero-corner.",

    "Uploading a watercolor of a young 1920s Berlin-Romanisches-Café waiter — produce a 30-second piece at a Tauentzienstraße terrace.",
    "Here's a sketch of a young 1920s Paris-Le-Bœuf-sur-le-Toit pianist — make a bedtime audiobook of her Montmartre evening.",
    "I have a digital painting of a young 1920s Vienna-Café-Central waiter — render a kids' audiobook of his Herrengasse morning.",
    "I'm sending you a portrait of a young 1920s Prague-Slavia café-poet — produce a children's audiobook of his Národní-třída afternoon.",
    "Uploading a sketch of a young 1920s Budapest-Café-New-York waiter — build an illustrated children's tale of her Erzsébet-körút morning.",
    "Here's a watercolor of a young 1920s Warsaw-Café-Ziemiańska poet — make a bedtime audiobook of her Mazowiecka afternoon.",
    "I have a digital portrait of a young 1920s Moscow-Stray-Dog cabaret-singer — render a kids' audiobook of his Vasilevsky-Island evening.",
    "Uploading a portrait of a young 1920s Petrograd-NEP-trader — produce a children's audiobook of his Nevsky-Prospect afternoon.",
    "Here's a sketch of a young 1920s Shanghai-Bund-French-Concession dandy — make a bedtime audiobook of his Avenue-Joffre evening.",
    "I'm sending you a watercolor of a young 1920s Shanghai-Cathay-Hotel-jazz singer — build an illustrated children's tale of her Bund-rooftop afternoon.",
    "Uploading a digital portrait of a young 1920s Yokohama-jazz dance-hall girl — render a kids' audiobook of her Bashamichi evening.",
    "Here's a portrait of a young 1920s Tokyo-Ginza-modan-girl — produce a children's audiobook of her Hattori-Clock-Tower afternoon.",
    "I have a watercolor of a young 1920s Osaka-Shinsaibashi café-girl — make a bedtime audiobook of her Shinsaibashi-suji evening.",
    "I'm sending you a digital painting of a young 1920s Bombay-Marine-Drive Anglo-Indian flapper — render a kids' audiobook of her Marine-Drive afternoon.",
    "Uploading a sketch of a young 1920s Calcutta-Park-Street jazz-club girl — produce a children's audiobook of her Park-Street evening.",
    "Here's a portrait of a young 1920s Cairo-Groppi-café — make a bedtime audiobook of his Talaat-Harb-Square afternoon.",
    "I have a watercolor of a young 1920s Alexandria-Cecil-Hotel-jazz pianist — build an illustrated children's tale of his Corniche evening.",
    "I'm sending you a digital portrait of a young 1920s Beirut-Bristol-Hotel waiter — render a kids' audiobook of her Bliss-Street afternoon.",
    "Uploading a portrait of a young 1920s Istanbul-Pera-Palas-Hotel page — produce a children's audiobook of his Tepebaşı evening.",
    "Here's a sketch of a young 1930s NYC-Stork-Club hat-check girl — make a bedtime audiobook of her 53rd-Street evening.",
    "I have a watercolor of a young 1930s NYC-Apollo-Theater amateur-night singer — build an illustrated children's tale of her 125th-Street afternoon.",
    "I'm sending you a digital portrait of a young 1930s Hollywood-Brown-Derby car-hop — render a kids' audiobook of her Wilshire-Vine evening.",
    "Uploading a sketch of a young 1930s Hollywood-Schwab's-Pharmacy soda-jerk — produce a children's audiobook of his Sunset-Blvd afternoon.",
    "Here's a portrait of a young 1930s Miami-Art-Deco-Hotel doorman — make a bedtime audiobook of his Ocean-Drive evening.",
    "I have a watercolor of a young 1930s Havana-Tropicana-cabaret dancer — build an illustrated children's tale of her Calle-72 evening.",
    "I'm sending you a digital painting of a young 1930s Mexico-City-Salón-México danzón-girl — render a kids' audiobook of her Roma-Norte afternoon.",
    "Uploading a portrait of a young 1930s Buenos-Aires-Tortoni café-tango dancer — produce a children's audiobook of her Avenida-de-Mayo evening.",
    "Here's a sketch of a young 1930s Rio-de-Janeiro-Copacabana-Palace pageboy — make a bedtime audiobook of his Avenida-Atlântica evening.",
    "I have a watercolor of a young 1930s São-Paulo-Mappin café-girl — build an illustrated children's tale of her Praça-do-Patriarca afternoon.",
    "I'm sending you a digital portrait of a young 1930s Lima-Hotel-Bolívar pianist — render a kids' audiobook of his Plaza-San-Martín evening.",
    "Uploading a sketch of a young 1930s Bogotá-Hotel-Granada bellhop — produce a children's audiobook of his Plaza-Bolívar afternoon.",
    "Here's a portrait of a young 1930s Caracas-Hotel-Majestic page — make a bedtime audiobook of his Avenida-Urdaneta evening.",
    "I have a watercolor of a young 1930s Marrakesh-La-Mamounia bellhop — build an illustrated children's tale of his Bab-Jdid afternoon.",
    "I'm sending you a digital painting of a young 1930s Algiers-Casino-Saint-Eugène waiter — render a kids' audiobook of his Square-Bresson afternoon.",
    "Uploading a portrait of a young 1930s Tangier-Café-Hafa kif-server — produce a children's audiobook of his Marshan-cliff afternoon.",
    "Here's a sketch of a young 1930s Cairo-Shepheard's-Hotel doorman — make a bedtime audiobook of his Ezbekieh-Garden evening.",
    "I have a watercolor of a young 1930s Tel-Aviv-Café-Cassit waiter — build an illustrated children's tale of his Allenby-Street afternoon.",
    "I'm sending you a digital portrait of a young 1930s Jerusalem-King-David-Hotel page — render a kids' audiobook of her Mamilla-Pool afternoon.",
    "Uploading a sketch of a young 1930s Beirut-Saint-Georges-Hotel pianist — produce a children's audiobook of her Saint-Georges-Bay evening.",
    "Here's a portrait of a young 1930s Damascus-Café-Naufara storyteller — make a bedtime audiobook of his Umayyad-Mosque-square afternoon.",
    "I have a watercolor of a young 1930s Baghdad-Café-Shahbandar tea-server — build an illustrated children's tale of his Mutanabbi-Street afternoon.",
    "I'm sending you a digital painting of a young 1930s Tehran-Lalehzar-jazz cabaret-girl — render a kids' audiobook of her Lalehzar-Avenue evening.",
    "Uploading a portrait of a young 1930s Bombay-Astoria-jazz singer — produce a children's audiobook of her Churchgate-Station evening.",
    "Here's a sketch of a young 1930s Calcutta-Grand-Hotel pianist — make a bedtime audiobook of his Chowringhee evening.",
    "I have a watercolor of a young 1930s Singapore-Raffles-Hotel page — build an illustrated children's tale of his Long-Bar afternoon.",
    "I'm sending you a digital portrait of a young 1930s Hong-Kong-Peninsula-Hotel page — render a kids' audiobook of her Salisbury-Road afternoon.",
    "Uploading a sketch of a young 1930s Macau-Hotel-Lisboa bellhop — produce a children's audiobook of her Avenida-da-Praia-Grande evening.",
    "Here's a portrait of a young 1930s Manila-Manila-Hotel page — make a bedtime audiobook of his Roxas-Boulevard evening.",
    # ── more 1960s civil-rights / protest-era figures (50) ──
    "Uploading a portrait of a young 1960s Selma-march bridge-walker — make me a children's audiobook of her Edmund-Pettus-Bridge morning.",
    "Here's a sketch of a young 1960s Greensboro-Woolworth-counter sit-in student — produce a kids' picture-book audiobook of his lunch-counter afternoon.",
    "I'm sending you a watercolor of a young 1960s Birmingham-children's-march participant — build an illustrated children's tale of her Kelly-Ingram-Park afternoon.",
    "Uploading a digital painting of a young 1960s Montgomery-bus-boycott walker — make a bedtime audiobook of her Cleveland-Avenue-stop evening.",
    "Here's a sketch of a young 1960s Washington-March-on-Washington volunteer — render an illustrated children's audiobook of her Lincoln-Memorial morning.",
    "I have a portrait of a young 1960s Mississippi-Freedom-Summer organizer — produce a children's audiobook of his Jackson-Tougaloo-College afternoon.",
    "Uploading a watercolor of a young 1960s Albany-Movement marcher — build an illustrated children's tale of her Albany-Georgia-Shiloh-Church evening.",
    "Here's a digital portrait of a young 1960s SNCC-organizer Atlanta — render a kids' audiobook of her Auburn-Avenue afternoon.",
    "I'm sending you a portrait of a young 1960s Oxford-Mississippi-James-Meredith-supporter — produce a children's audiobook of his University-of-Mississippi afternoon.",
    "Uploading a sketch of a young 1960s Watts-uprising witness — make a bedtime audiobook of her Watts-103rd-Street evening.",
    "Here's a watercolor of a young 1960s Detroit-1967-uprising witness — build an illustrated children's tale of his 12th-Street morning.",
    "I have a digital painting of a young 1960s Memphis-sanitation-strike supporter — render a kids' audiobook of his I-Am-A-Man-march afternoon.",
    "Uploading a portrait of a young 1960s Resurrection-City-Washington volunteer — produce a children's audiobook of her tent-encampment morning.",
    "Here's a sketch of a young 1960s SCLC-Lawndale-Chicago organizer — make a bedtime audiobook of his Chicago-Open-Housing afternoon.",
    "I'm sending you a watercolor of a young 1960s Boston-school-busing organizer — build an illustrated children's tale of her Mattapan-evening.",
    "Uploading a digital portrait of a young 1960s East-LA-Chicano-walkout student — render a kids' audiobook of her Garfield-High-School-walkout afternoon.",
    "Here's a portrait of a young 1960s Delano-grape-strike picket — produce a children's audiobook of her vineyard-row morning.",
    "I have a sketch of a young 1960s Sacramento-pilgrimage marcher — make a bedtime audiobook of his Capitol-stair evening.",
    "Uploading a watercolor of a young 1960s Crusade-for-Justice-Denver organizer — build an illustrated children's tale of his Auraria-courtyard afternoon.",
    "Here's a digital painting of a young 1960s Tijerina-Alianza-New-Mexico organizer — render a kids' audiobook of his Tierra-Amarilla courthouse morning.",
    "I'm sending you a portrait of a young 1960s Stonewall-Inn-NYC patron — produce a children's audiobook of her Christopher-Street evening.",
    "Uploading a sketch of a young 1960s San-Francisco-Compton's-Cafeteria-riot witness — make a bedtime audiobook of her Tenderloin night.",
    "Here's a watercolor of a young 1960s Greenwich-Village-cafe poet — build an illustrated children's tale of his MacDougal-Street afternoon.",
    "I have a digital portrait of a young 1960s Berkeley-Free-Speech-Movement student — render a kids' audiobook of her Sproul-Plaza afternoon.",
    "Uploading a portrait of a young 1960s Berkeley-People's-Park organizer — produce a children's audiobook of his Telegraph-Avenue morning.",
    "Here's a sketch of a young 1960s Columbia-University-1968 occupation student — make a bedtime audiobook of his Hamilton-Hall afternoon.",
    "I'm sending you a watercolor of a young 1960s Kent-State student — build an illustrated children's tale of her Commons-bell-tower morning.",
    "Uploading a digital painting of a young 1960s San-Francisco-State-strike student — render a kids' audiobook of his BSU-courtyard afternoon.",
    "Here's a portrait of a young 1960s Cornell-Willard-Straight occupation student — produce a children's audiobook of his AAS-courtyard morning.",
    "I have a sketch of a young 1960s SDS-Port-Huron organizer — make a bedtime audiobook of his Lake-Huron-camp evening.",
    "Uploading a watercolor of a young 1960s Vietnam-anti-war marcher Pentagon — build an illustrated children's tale of her March-on-the-Pentagon morning.",
    "Here's a digital portrait of a young 1960s Chicago-1968-DNC protest marcher — render a kids' audiobook of his Grant-Park evening.",
    "I'm sending you a portrait of a young 1960s Moratorium-March DC participant — produce a children's audiobook of her National-Mall morning.",
    "Uploading a sketch of a young 1960s Kent-State-Vigil student — make a bedtime audiobook of his Old-Main-bell evening.",
    "Here's a watercolor of a young 1960s Jackson-State protest student — build an illustrated children's tale of her Lynch-Street afternoon.",
    "I have a digital painting of a young 1960s Wounded-Knee-occupation Lakota-organizer — render a kids' audiobook of his Pine-Ridge morning.",
    "Uploading a portrait of a young 1960s Alcatraz-occupation Indian-of-All-Tribes student — produce a children's audiobook of her Alcatraz-shore afternoon.",
    "Here's a sketch of a young 1960s NAACP-Youth-Council-Jackson organizer — make a bedtime audiobook of his Lynch-Street evening.",
    "I'm sending you a watercolor of a young 1960s SNCC-Selma-organizer — build an illustrated children's tale of her Brown-Chapel morning.",
    "Uploading a digital portrait of a young 1960s Mississippi-Freedom-Democratic-Party delegate — render a kids' audiobook of her Atlantic-City-Convention afternoon.",
    "Here's a portrait of a young 1960s Black-Panther-Oakland breakfast-program volunteer — produce a children's audiobook of his West-Oakland-church morning.",
    "I have a sketch of a young 1960s Black-Panther-Chicago organizer — make a bedtime audiobook of his West-Side-meeting-room evening.",
    "Uploading a watercolor of a young 1960s Brown-Berets-East-LA organizer — build an illustrated children's tale of her City-Terrace afternoon.",
    "Here's a digital painting of a young 1960s Young-Lords-NYC-East-Harlem organizer — render a kids' audiobook of his East-Harlem-streetcorner morning.",
    "I'm sending you a portrait of a young 1960s Young-Patriots-Chicago organizer — produce a children's audiobook of his Uptown-Chicago afternoon.",
    "Uploading a sketch of a young 1960s Combahee-River-Collective forerunner — make a bedtime audiobook of her Boston-meeting-room evening.",
    "Here's a watercolor of a young 1960s Highlander-Folk-School-Tennessee student — build an illustrated children's tale of her Monteagle-mountain morning.",
    "I have a digital portrait of a young 1960s Citizenship-School-Sea-Islands student — render a kids' audiobook of her Johns-Island afternoon.",
    "Uploading a portrait of a young 1960s Birmingham-Children's-Crusade marcher — produce a children's audiobook of his Sixteenth-Street-Baptist-Church afternoon.",
    "Here's a sketch of a young 1960s Edmund-Pettus-Bridge-Bloody-Sunday marcher — make a bedtime audiobook of her Brown-Chapel-Selma evening.",
    # ── more 1980s American suburban / Reagan-era kids (50) ──
    "Uploading a portrait of a 1980s Levittown-Pennsylvania-cul-de-sac kid — make me a children's audiobook of her bicycle-driveway afternoon.",
    "Here's a sketch of a 1980s Cherry-Hill-New-Jersey-mall kid — produce a kids' picture-book audiobook of his food-court afternoon.",
    "I'm sending you a watercolor of a 1980s Plano-Texas-cul-de-sac kid — build an illustrated children's tale of her Garland-Road afternoon.",
    "Uploading a digital painting of a 1980s Naperville-Illinois-cul-de-sac kid — make a bedtime audiobook of his Riverwalk evening.",
    "Here's a sketch of a 1980s Fairfax-County-Virginia-cul-de-sac kid — render an illustrated children's audiobook of her Burke-Lake afternoon.",
    "I have a portrait of a 1980s Bethesda-Maryland-cul-de-sac kid — produce a children's audiobook of his Cabin-John afternoon.",
    "Uploading a watercolor of a 1980s Westlake-California-cul-de-sac kid — build an illustrated children's tale of her Westlake-Boulevard afternoon.",
    "Here's a digital portrait of a 1980s Mission-Viejo-California-cul-de-sac kid — render a kids' audiobook of her Lake-Mission-Viejo afternoon.",
    "I'm sending you a portrait of a 1980s Walnut-Creek-California-Concord-Plaza kid — produce a children's audiobook of his Sunvalley-Mall afternoon.",
    "Uploading a sketch of a 1980s Pleasanton-California-cul-de-sac kid — make a bedtime audiobook of her Pleasanton-Stoneridge-Mall evening.",
    "Here's a watercolor of a 1980s Centennial-Colorado-cul-de-sac kid — build an illustrated children's tale of his Centennial-Park afternoon.",
    "I have a digital painting of a 1980s Naperville-Fox-Valley-Mall kid — render a kids' audiobook of her Fox-Valley-Mall afternoon.",
    "Uploading a portrait of a 1980s Schaumburg-Illinois-Woodfield-Mall kid — produce a children's audiobook of his arcade-corner afternoon.",
    "Here's a sketch of a 1980s Edina-Minnesota-Southdale-Mall kid — make a bedtime audiobook of her food-court evening.",
    "I'm sending you a watercolor of a 1980s Bloomington-Minnesota-Mall-of-America-precursor kid — build an illustrated children's tale of her Lindale-Mall afternoon.",
    "Uploading a digital portrait of a 1980s Tysons-Corner-Virginia-Mall kid — render a kids' audiobook of his Tysons-Corner-Center afternoon.",
    "Here's a portrait of a 1980s King-of-Prussia-Pennsylvania-Mall kid — produce a children's audiobook of his food-court afternoon.",
    "I have a sketch of a 1980s Paramus-New-Jersey-Garden-State-Plaza kid — make a bedtime audiobook of her arcade-stand evening.",
    "Uploading a watercolor of a 1980s Rosedale-Maryland-Eastpoint-Mall kid — build an illustrated children's tale of her Eastpoint-Mall afternoon.",
    "Here's a digital painting of a 1980s Sherman-Oaks-California-Galleria kid — render a kids' audiobook of her Sherman-Oaks-Galleria afternoon.",
    "I'm sending you a portrait of a 1980s San-Diego-Chula-Vista kid — produce a children's audiobook of his Plaza-Bonita-Mall afternoon.",
    "Uploading a sketch of a 1980s Phoenix-Metrocenter-Mall kid — make a bedtime audiobook of his arcade-row evening.",
    "Here's a watercolor of a 1980s Houston-Galleria kid — build an illustrated children's tale of her ice-skating-rink afternoon.",
    "I have a digital portrait of a 1980s Dallas-NorthPark-Center kid — render a kids' audiobook of her NorthPark-Center afternoon.",
    "Uploading a portrait of a 1980s Atlanta-Lenox-Square kid — produce a children's audiobook of his Lenox-Square afternoon.",
    "Here's a sketch of a 1980s Tampa-WestShore-Plaza kid — make a bedtime audiobook of her food-court evening.",
    "I'm sending you a watercolor of a 1980s Orlando-Florida-Mall kid — build an illustrated children's tale of his Florida-Mall afternoon.",
    "Uploading a digital portrait of a 1980s Virginia-Beach-Pembroke-Mall kid — render a kids' audiobook of her Pembroke-Mall afternoon.",
    "Here's a portrait of a 1980s Denver-Cherry-Creek-Mall kid — produce a children's audiobook of his Cherry-Creek-Mall afternoon.",
    "I have a sketch of a 1980s Salt-Lake-City-ZCMI-Center kid — make a bedtime audiobook of his ZCMI-Center evening.",
    "Uploading a watercolor of a 1980s Boise-Idaho-Boise-Towne-Square kid — build an illustrated children's tale of her arcade-stand afternoon.",
    "Here's a digital painting of a 1980s Portland-Oregon-Lloyd-Center kid — render a kids' audiobook of her ice-rink afternoon.",
    "I'm sending you a portrait of a 1980s Seattle-Northgate-Mall kid — produce a children's audiobook of his food-court afternoon.",
    "Uploading a sketch of a 1980s Tacoma-Tacoma-Mall kid — make a bedtime audiobook of her Tacoma-Mall evening.",
    "Here's a watercolor of a 1980s Pittsburgh-Monroeville-Mall kid — build an illustrated children's tale of his Monroeville-Mall afternoon.",
    "I have a digital portrait of a 1980s Cleveland-Randall-Park-Mall kid — render a kids' audiobook of her Randall-Park-Mall afternoon.",
    "Uploading a portrait of a 1980s Detroit-Northland-Center kid — produce a children's audiobook of his Northland-Center afternoon.",
    "Here's a sketch of a 1980s St-Louis-Saint-Louis-Galleria kid — make a bedtime audiobook of her Saint-Louis-Galleria evening.",
    "I'm sending you a watercolor of a 1980s Indianapolis-Lafayette-Square-Mall kid — build an illustrated children's tale of her Lafayette-Square-Mall afternoon.",
    "Uploading a digital portrait of a 1980s Cincinnati-Tri-County-Mall kid — render a kids' audiobook of his Tri-County-Mall afternoon.",
    "Here's a portrait of a 1980s Memphis-Mall-of-Memphis kid — produce a children's audiobook of his Mall-of-Memphis afternoon.",
    "I have a sketch of a 1980s Nashville-Hickory-Hollow-Mall kid — make a bedtime audiobook of her Hickory-Hollow-Mall evening.",
    "Uploading a watercolor of a 1980s Birmingham-Alabama-Riverchase-Galleria kid — build an illustrated children's tale of her Riverchase-Galleria afternoon.",
    "Here's a digital painting of a 1980s Charlotte-SouthPark-Mall kid — render a kids' audiobook of her SouthPark-Mall afternoon.",
    "I'm sending you a portrait of a 1980s Raleigh-Crabtree-Valley-Mall kid — produce a children's audiobook of his Crabtree-Valley-Mall afternoon.",
    "Uploading a sketch of a 1980s Richmond-Cloverleaf-Mall kid — make a bedtime audiobook of his Cloverleaf-Mall evening.",
    "Here's a watercolor of a 1980s Hartford-Westfarms-Mall kid — build an illustrated children's tale of her Westfarms-Mall afternoon.",
    "I have a digital portrait of a 1980s Buffalo-Walden-Galleria kid — render a kids' audiobook of his Walden-Galleria afternoon.",
    "Uploading a portrait of a 1980s Rochester-Marketplace-Mall kid — produce a children's audiobook of his arcade-row afternoon.",
    "Here's a sketch of a 1980s Albany-Crossgates-Mall kid — make a bedtime audiobook of her Crossgates-Mall evening.",
    # ── more 2010s social-media influencer / YouTuber / streamer kids (50) ──
    "Uploading a portrait of a 2010s YouTube-Diana-Kids kid — make me a children's audiobook of her toy-review afternoon.",
    "Here's a sketch of a 2010s YouTube-Ryan-ToysReview kid — produce a kids' picture-book audiobook of his unboxing-floor afternoon.",
    "I'm sending you a watercolor of a 2010s YouTube-Like-Nastya kid — build an illustrated children's tale of her playroom afternoon.",
    "Uploading a digital painting of a 2010s YouTube-Vlad-and-Niki kid — make a bedtime audiobook of his playground evening.",
    "Here's a sketch of a 2010s YouTube-FGTeeV kid — render an illustrated children's audiobook of his gaming-couch afternoon.",
    "I have a portrait of a 2010s YouTube-Sssniperwolf kid — produce a children's audiobook of her gaming-room afternoon.",
    "Uploading a watercolor of a 2010s YouTube-Markiplier-fan kid — build an illustrated children's tale of his bedroom-streaming afternoon.",
    "Here's a digital portrait of a 2010s YouTube-PewDiePie-fan kid — render a kids' audiobook of his bedroom-meme-collection afternoon.",
    "I'm sending you a portrait of a 2010s Twitch-Ninja-Fortnite-fan kid — produce a children's audiobook of his gaming-chair afternoon.",
    "Uploading a sketch of a 2010s Twitch-Pokimane-fan kid — make a bedtime audiobook of her bedroom-streaming evening.",
    "Here's a watercolor of a 2010s Twitch-Ludwig-fan kid — build an illustrated children's tale of his bedroom-stream-setup afternoon.",
    "I have a digital painting of a 2010s YouTube-MrBeast-fan kid — render a kids' audiobook of his Greenville-NC-fan-mail afternoon.",
    "Uploading a portrait of a 2010s YouTube-DanTDM-fan kid — produce a children's audiobook of his Minecraft-room afternoon.",
    "Here's a sketch of a 2010s YouTube-Stampylonghead-fan kid — make a bedtime audiobook of his Minecraft-Lovely-World afternoon.",
    "I'm sending you a watercolor of a 2010s YouTube-Captain-Sparklez-fan kid — build an illustrated children's tale of his Minecraft-Hunger-Games afternoon.",
    "Uploading a digital portrait of a 2010s TikTok-Charli-D'Amelio-fan kid — render a kids' audiobook of her bedroom-dance afternoon.",
    "Here's a portrait of a 2010s TikTok-Addison-Rae-fan kid — produce a children's audiobook of her bedroom-mirror-dance afternoon.",
    "I have a sketch of a 2010s TikTok-Bella-Poarch-fan kid — make a bedtime audiobook of her bedroom-lip-sync evening.",
    "Uploading a watercolor of a 2010s TikTok-Khaby-Lame-fan kid — build an illustrated children's tale of his bedroom-deadpan afternoon.",
    "Here's a digital painting of a 2010s TikTok-Bryce-Hall-fan kid — render a kids' audiobook of his bedroom-creator-collab afternoon.",
    "I'm sending you a portrait of a 2010s Instagram-Selena-Gomez-fan kid — produce a children's audiobook of her bedroom-mirror-selfie afternoon.",
    "Uploading a sketch of a 2010s Instagram-Kylie-Jenner-fan kid — make a bedtime audiobook of her bedroom-makeup evening.",
    "Here's a watercolor of a 2010s Instagram-Cristiano-Ronaldo-fan kid — build an illustrated children's tale of his backyard-soccer afternoon.",
    "I have a digital portrait of a 2010s Instagram-Lionel-Messi-fan kid — render a kids' audiobook of his backyard-Argentina-jersey afternoon.",
    "Uploading a portrait of a 2010s Snapchat-DJ-Khaled-fan kid — produce a children's audiobook of his bedroom-fan-pic afternoon.",
    "Here's a sketch of a 2010s YouTube-James-Charles-fan kid — make a bedtime audiobook of her bedroom-makeup-video evening.",
    "I'm sending you a watercolor of a 2010s YouTube-Jeffree-Star-fan kid — build an illustrated children's tale of her bedroom-makeup afternoon.",
    "Uploading a digital portrait of a 2010s YouTube-Tati-Westbrook-fan kid — render a kids' audiobook of her bedroom-beauty-review afternoon.",
    "Here's a portrait of a 2010s YouTube-Shane-Dawson-fan kid — produce a children's audiobook of his bedroom-conspiracy-vlog afternoon.",
    "I have a sketch of a 2010s YouTube-David-Dobrik-fan kid — make a bedtime audiobook of his Hollywood-Hills-shenanigans evening.",
    "Uploading a watercolor of a 2010s YouTube-Jenna-Marbles-fan kid — build an illustrated children's tale of her bedroom-comedy-vlog afternoon.",
    "Here's a digital painting of a 2010s YouTube-Casey-Neistat-fan kid — render a kids' audiobook of his Manhattan-skateboard afternoon.",
    "I'm sending you a portrait of a 2010s YouTube-Peter-McKinnon-fan kid — produce a children's audiobook of his Toronto-cinematography-vlog afternoon.",
    "Uploading a sketch of a 2010s YouTube-Marques-Brownlee-MKBHD-fan kid — make a bedtime audiobook of his bedroom-tech-review afternoon.",
    "Here's a watercolor of a 2010s YouTube-Linus-Tech-Tips-fan kid — build an illustrated children's tale of his bedroom-gaming-PC-build afternoon.",
    "I have a digital portrait of a 2010s YouTube-Gordon-Ramsay-fan kid — render a kids' audiobook of his kitchen-cooking-attempt afternoon.",
    "Uploading a portrait of a 2010s YouTube-Tasty-fan kid — produce a children's audiobook of her kitchen-food-photography afternoon.",
    "Here's a sketch of a 2010s YouTube-Bon-Appétit-Test-Kitchen-fan kid — make a bedtime audiobook of his kitchen-cooking-show evening.",
    "I'm sending you a watercolor of a 2010s YouTube-Binging-with-Babish-fan kid — build an illustrated children's tale of his kitchen-movie-food afternoon.",
    "Uploading a digital portrait of a 2010s YouTube-Joshua-Weissman-fan kid — render a kids' audiobook of his bedroom-cooking-vlog afternoon.",
    "Here's a portrait of a 2010s YouTube-Adam-Ragusea-fan kid — produce a children's audiobook of his kitchen-explainer-cooking afternoon.",
    "I have a sketch of a 2010s YouTube-Mark-Rober-fan kid — make a bedtime audiobook of his backyard-engineering-experiment afternoon.",
    "Uploading a watercolor of a 2010s YouTube-Veritasium-fan kid — build an illustrated children's tale of his bedroom-physics-experiment afternoon.",
    "Here's a digital painting of a 2010s YouTube-Tom-Scott-fan kid — render a kids' audiobook of his park-explainer-stand afternoon.",
    "I'm sending you a portrait of a 2010s YouTube-Vsauce-fan kid — produce a children's audiobook of his bedroom-philosophy-vlog afternoon.",
    "Uploading a sketch of a 2010s YouTube-Kurzgesagt-fan kid — make a bedtime audiobook of his bedroom-animation-explainer afternoon.",
    "Here's a watercolor of a 2010s YouTube-CGP-Grey-fan kid — build an illustrated children's tale of his bedroom-explainer-vlog afternoon.",
    "I have a digital portrait of a 2010s YouTube-MinutePhysics-fan kid — render a kids' audiobook of his bedroom-physics-explainer afternoon.",
    "Uploading a portrait of a 2010s YouTube-Smarter-Every-Day-fan kid — produce a children's audiobook of his backyard-rocket-experiment afternoon.",
    "Here's a sketch of a 2010s YouTube-NileRed-fan kid — make a bedtime audiobook of his garage-chemistry-experiment evening.",
    # ── more Tang dynasty poets (50) ──
    "I'm sending you a portrait of a young Tang-Li-Bai-Sichuan-Jiangyou roaming poet — produce a children's audiobook of his Jiangyou-Mount-Daitian afternoon.",
    "Uploading a watercolor of a young Tang-Du-Fu-Henan-Gongxian thatched-cottage poet — make a bedtime audiobook of his Gongxian-Yaowan afternoon.",
    "Here's a digital painting of a young Tang-Bai-Juyi-Shaanxi-Xinzheng young scribe — render a kids' audiobook of his Xinzheng-Bai-Yangling-courtyard afternoon.",
    "I have a sketch of a young Tang-Wang-Wei-Shanxi-Puzhou young scribe — produce a children's audiobook of his Puzhou-Pucheng afternoon.",
    "Uploading a portrait of a young Tang-Meng-Haoran-Hubei-Xiangyang young scribe — make a bedtime audiobook of his Xiangyang-Lumenshan-thatched-hut afternoon.",
    "Here's a watercolor of a young Tang-Wang-Zhihuan-Shanxi-Bingzhou young scribe — build an illustrated children's tale of his Bingzhou-Yumen-Pass afternoon.",
    "I'm sending you a digital portrait of a young Tang-Cen-Shen-Henan-Nanyang young scribe — render a kids' audiobook of his Nanyang-Cen-courtyard afternoon.",
    "Uploading a sketch of a young Tang-Gao-Shi-Hebei-Cangzhou young scribe — produce a children's audiobook of his Cangzhou-Gao-courtyard afternoon.",
    "Here's a portrait of a young Tang-Wang-Changling-Shanxi-Taiyuan young scribe — make a bedtime audiobook of his Taiyuan-Jinyang-courtyard afternoon.",
    "I have a watercolor of a young Tang-Liu-Zongyuan-Shanxi-Yongji young scribe — build an illustrated children's tale of his Yongji-Liu-courtyard afternoon.",
    "Uploading a digital painting of a young Tang-Han-Yu-Henan-Mengzhou young scribe — render a kids' audiobook of his Mengzhou-Han-courtyard afternoon.",
    "Here's a sketch of a young Tang-Yuan-Zhen-Henan-Luoyang young scribe — produce a children's audiobook of his Luoyang-Yuan-courtyard afternoon.",
    "I'm sending you a portrait of a young Tang-Li-He-Henan-Yiyang young scribe — make a bedtime audiobook of his Yiyang-Changgu afternoon.",
    "Uploading a watercolor of a young Tang-Li-Shangyin-Henan-Qinyang young scribe — build an illustrated children's tale of his Qinyang-Li-courtyard afternoon.",
    "Here's a digital portrait of a young Tang-Du-Mu-Shaanxi-Chang'an young scribe — render a kids' audiobook of his Chang'an-Du-courtyard afternoon.",
    "I have a sketch of a young Tang-Wei-Yingwu-Shaanxi-Chang'an young scribe — produce a children's audiobook of his Chang'an-Wei-courtyard afternoon.",
    "Uploading a portrait of a young Tang-Liu-Yuxi-Henan-Luoyang young scribe — make a bedtime audiobook of his Luoyang-Liu-courtyard afternoon.",
    "Here's a watercolor of a young Tang-Lu-Zhao-lin-Hebei-Youzhou young scribe — build an illustrated children's tale of his Youzhou-Lu-courtyard afternoon.",
    "I'm sending you a digital painting of a young Tang-Luo-Bin-wang-Zhejiang-Yiwu young scribe — render a kids' audiobook of his Yiwu-Luo-courtyard afternoon.",
    "Uploading a sketch of a young Tang-Wang-Bo-Shanxi-Hejin young scribe — produce a children's audiobook of his Hejin-Wang-Tongchun-pavilion afternoon.",
    "Here's a portrait of a young Tang-Yang-Jiong-Shaanxi-Huayin young scribe — make a bedtime audiobook of his Huayin-Yang-courtyard afternoon.",
    "I have a watercolor of a young Tang-Chen-Zi-ang-Sichuan-Shehong young scribe — build an illustrated children's tale of his Shehong-Chen-courtyard afternoon.",
    "Uploading a digital portrait of a young Tang-Zhang-Jiuling-Guangdong-Shaoguan young scribe — render a kids' audiobook of his Shaoguan-Zhang-courtyard afternoon.",
    "Here's a sketch of a young Tang-He-Zhizhang-Zhejiang-Xiaoshan young scribe — produce a children's audiobook of his Xiaoshan-He-courtyard afternoon.",
    "I'm sending you a portrait of a young Tang-Zhang-Ruoxu-Jiangsu-Yangzhou young scribe — make a bedtime audiobook of his Yangzhou-Spring-River-Flower-Moon-Night afternoon.",
    "Uploading a watercolor of a young Tang-Wang-Han-Shanxi-Bingzhou young scribe — build an illustrated children's tale of his Bingzhou-Liangzhou-Frontier-poem afternoon.",
    "Here's a digital painting of a young Tang-Zu-Yong-Hebei-Youzhou young scribe — render a kids' audiobook of his Youzhou-Zu-courtyard afternoon.",
    "I have a sketch of a young Tang-Cui-Hao-Henan-Bianzhou young scribe — produce a children's audiobook of his Bianzhou-Yellow-Crane-Tower afternoon.",
    "Uploading a portrait of a young Tang-Cui-Tu-Shanxi-Bingzhou young scribe — make a bedtime audiobook of his Bingzhou-Cui-courtyard afternoon.",
    "Here's a watercolor of a young Tang-Wei-Zhuang-Shaanxi-Duling young scribe — build an illustrated children's tale of his Duling-Wei-courtyard afternoon.",
    "I'm sending you a digital portrait of a young Tang-Pi-Rixiu-Anhui-Xiangyang young scribe — render a kids' audiobook of his Xiangyang-Pi-courtyard afternoon.",
    "Uploading a sketch of a young Tang-Lu-Guimeng-Jiangsu-Suzhou young scribe — produce a children's audiobook of his Suzhou-Lu-thatched-hut afternoon.",
    "Here's a portrait of a young Tang-Yu-Xuanji-Shaanxi-Chang'an young Daoist — make a bedtime audiobook of his Chang'an-Xianyi-Daoist-temple afternoon.",
    "I have a watercolor of a young Tang-Xue-Tao-Sichuan-Chengdu young Daoist — build an illustrated children's tale of his Chengdu-Wangjianglou-poem-pavilion afternoon.",
    "Uploading a digital painting of a young Tang-Li-Ye-Zhejiang-Wuzhou young Daoist — render a kids' audiobook of his Wuzhou-Li-courtyard afternoon.",
    "Here's a sketch of a young Tang-Liu-Caichun-Zhejiang-Yueyang young scribe — produce a children's audiobook of his Yueyang-Liu-courtyard afternoon.",
    "I'm sending you a portrait of a young Tang-Wang-Jian-Henan-Yingchuan young scribe — make a bedtime audiobook of his Yingchuan-Wang-courtyard afternoon.",
    "Uploading a watercolor of a young Tang-Zhang-Ji-Anhui-Hezhou young scribe — build an illustrated children's tale of his Hezhou-Zhang-courtyard afternoon.",
    "Here's a digital portrait of a young Tang-Yuan-Jie-Henan-Luyang young scribe — render a kids' audiobook of his Luyang-Yuan-courtyard afternoon.",
    "I have a sketch of a young Tang-Qian-Qi-Zhejiang-Wuxing young scribe — produce a children's audiobook of his Wuxing-Qian-courtyard afternoon.",
    "Uploading a portrait of a young Tang-Liu-Changqing-Hebei-Hejian young scribe — make a bedtime audiobook of his Hejian-Liu-courtyard afternoon.",
    "Here's a watercolor of a young Tang-Si-Kongtu-Shanxi-Yongji young scribe — build an illustrated children's tale of his Yongji-Sikong-courtyard afternoon.",
    "I'm sending you a digital painting of a young Tang-Wei-Yingwu-Shaanxi-Jingzhao young scribe — render a kids' audiobook of his Jingzhao-Wei-courtyard afternoon.",
    "Uploading a sketch of a young Tang-Lin-Pu-Zhejiang-Hangzhou young Daoist — produce a children's audiobook of his Hangzhou-Lonely-Mountain afternoon.",
    "Here's a portrait of a young Tang-Liu-Yong-Fujian-Chongan young scribe — make a bedtime audiobook of his Chongan-Liu-courtyard afternoon.",
    "I have a watercolor of a young Tang-Su-Shi-Sichuan-Meishan young scribe — build an illustrated children's tale of his Meishan-Su-East-Slope-courtyard afternoon.",
    "Uploading a digital portrait of a young Tang-Su-Zhe-Sichuan-Meishan young scribe — render a kids' audiobook of his Meishan-Su-courtyard afternoon.",
    "Here's a sketch of a young Tang-Su-Xun-Sichuan-Meishan young scribe — produce a children's audiobook of his Meishan-Su-academy afternoon.",
    "I'm sending you a portrait of a young Tang-Wang-Anshi-Jiangxi-Linchuan young scribe — make a bedtime audiobook of his Linchuan-Wang-courtyard afternoon.",
    "Uploading a watercolor of a young Tang-Ouyang-Xiu-Sichuan-Mianzhou young scribe — build an illustrated children's tale of his Mianzhou-Ouyang-courtyard afternoon.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
