"""x15 intake_img_cr_extend GRPO short briefs. Disjoint from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Uploading a portrait of a young 1880s frontier doctor — make a 2-minute extended cinematic mini-drama imagining his ride to a remote ranch.",
    "Here's a sketch of a young 1900s lighthouse keeper — build a 3-minute extended cinematic short of her storm-night vigil.",
    "I'm sending you a watercolor of a young 1860s railroad surveyor — produce a 4-minute extended mini-drama on a transcontinental route.",
    "Uploading a digital painting of a young 1940s Bletchley codebreaker — make a 3-minute extended cinematic piece of her decoding intercepts.",
    "Here's a portrait of a young 1920s Pulitzer journalist — render a 2-minute extended short of her newsroom evening.",
    "I'm attaching a sketch of a young 1880s Pinkerton detective — build a 3-minute extended cinematic mini-drama on a stakeout.",
    "Uploading this concept art of a young 1900s circus tightrope walker — produce a 4-minute extended piece of her practice.",
    "Here's a watercolor of a young 1920s East-Village radical printer — render a 2-minute extended short at her press.",
    "I have a portrait of a young 1900s San-Francisco gold panner — build a 3-minute extended mini-drama of her stream.",
    "Uploading a sketch of a young 1880s Welsh coal miner — make a 4-minute extended cinematic piece of his pit walk.",
    "Here's a digital painting of a young 1910s Argentine tango bandoneonist — produce a 2-minute extended short at his café gig.",
    "I'm attaching this image of a young 1850s Boston abolitionist — build a 3-minute extended mini-drama at a printing press.",
    "Uploading a portrait of a young 1900s Oxford library cataloger — make a 4-minute extended cinematic piece in her stacks.",
    "Here's a sketch of a young 1820s Caribbean rum-distiller — render a 2-minute extended short at her vat.",
    "I'm sending you a watercolor of a young 1880s Texas cattle drover — produce a 3-minute extended mini-drama on a trail drive.",
    "Uploading a digital portrait of a young 1970s East-Berlin dissident — build a 4-minute extended cinematic piece at her press.",
    "Here's a portrait of a young 1900s Mongolian Buddhist novice — render a 2-minute extended short at his monastery dawn.",
    "I'm attaching a sketch of a young 1880s Klondike-era saloon-keeper — make a 3-minute extended mini-drama on her porch.",
    "Uploading a watercolor of a young 1840s New England widow — produce a 4-minute extended cinematic piece at her cottage.",
    "Here's a digital painting of a young 1910s Polish nurse — build a 2-minute extended short on her ward.",
    "I have a portrait of a young 1880s North Sea trawler captain — render a 3-minute extended mini-drama on his bridge.",
    "Uploading a sketch of a young 1860s Japanese sword-smith — make a 4-minute extended cinematic piece at his forge.",
    "Here's a watercolor of a young 1950s Detroit auto-line worker — produce a 2-minute extended short on his assembly line.",
    "I'm sending you a portrait of a young 1820s Greek revolutionary — build a 3-minute extended mini-drama of his ambush.",
    "Uploading a digital painting of a young 1900s Vienna café chess hustler — make a 4-minute extended cinematic piece of his games.",
    "Here's a sketch of a young 1880s Klondike-era saloon-keeper — render a 2-minute extended short at her saloon.",
    "I'm attaching a portrait of a young 1900s Irish dockworker — produce a 3-minute extended mini-drama at the Brooklyn docks.",
    "Uploading a watercolor of a young 1880s Wild West stagecoach driver — build a 4-minute extended cinematic piece on his run.",
    "Here's a digital portrait of a young 1820s harbor pilot — render a 2-minute extended short at the helm.",
    "I have a sketch of a young 1880s Sicilian fisherman — make a 3-minute extended mini-drama at dawn nets.",
    "Uploading a portrait of a young 1970s feminist organizer — make a 4-minute extended cinematic piece at a community-room meeting.",
    "Here's a watercolor of a young 1840s steamboat engineer — produce a 2-minute extended short in the engine room.",
    "I'm sending you a digital painting of a young 1820s frontier midwife — build a 3-minute extended mini-drama on horseback at dawn.",
    "Uploading a sketch of a young 1900s suffragette — make a 4-minute extended cinematic piece at a march.",
    "Here's a portrait of a young 1880s circus tightrope walker — render a 2-minute extended short at her practice.",
    "I'm attaching a watercolor of a young Sephardic violinmaker — make a 3-minute extended mini-drama varnishing a violin.",
    "Uploading a digital art of a young 1960s civil rights organizer — build a 4-minute extended cinematic piece at a sit-in.",
    "Here's a portrait of my great-aunt as a young 1920s aviator — render a 2-minute extended short of her flight.",
    "I have a sketch of a young 1890s coal-yard accountant — make a 3-minute extended mini-drama at his ledger.",
    "Uploading a digital painting of a young 1850s Underground Railroad conductor — produce a 4-minute extended cinematic piece on her route.",
    "Here's a sketch of a young 1920s East-Village radical printer — render a 2-minute extended short at her press.",
    "I'm sending you a portrait of a young 1900s Italian immigrant — build a 3-minute extended mini-drama of his arrival.",
    "Uploading a digital painting of a young 1900s Oxford library cataloger — make a 4-minute extended cinematic piece in her stacks.",
    "Here's a watercolor of a young 1820s Caribbean rum-distiller — produce a 2-minute extended short at her vat.",
    "I'm attaching a sketch of a young 1880s Welsh coal miner — render a 3-minute extended mini-drama on his pit walk.",
    "Uploading a digital art of a young 1910s Argentine tango bandoneonist — make a 4-minute extended cinematic piece at his café gig.",
    "Here's a portrait of a young 1860s Confederate widow — produce a 2-minute extended short on the porch.",
    "I have a sketch of a young 1900s Welsh schoolteacher — build a 3-minute extended mini-drama at her schoolhouse.",
    "Uploading a digital painting of a young 1860s Transcontinental Railroad worker — make a 4-minute extended cinematic piece on his shift.",
    "Here's a portrait of a young 1850s California gold panner — render a 2-minute extended short at her stream.",
    # ── more reference-image extended cinematic shorts (50) ──────────────
    "Uploading a portrait of a young 1840s Mississippi riverboat gambler — make a 3-minute extended cinematic mini-drama on a paddle-steamer card-table.",
    "Here's a sketch of a young 1870s frontier blacksmith — build a 4-minute extended cinematic short at his Wyoming forge.",
    "I'm sending you a watercolor of a young 1890s telegraph operator — produce a 2-minute extended mini-drama at a Western Union desk.",
    "Uploading a digital painting of a young 1900s vaudeville magician — make a 4-minute extended cinematic piece backstage at the Palace Theatre.",
    "Here's a portrait of a young 1910s Coney Island fortune-teller — render a 3-minute extended short in her boardwalk booth.",
    "I'm attaching a sketch of a young 1920s flapper jazz singer — build a 2-minute extended cinematic mini-drama at a Chicago speakeasy.",
    "Uploading this concept art of a young 1930s big-band trumpeter — produce a 4-minute extended piece at a New Orleans riverboat.",
    "Here's a watercolor of a young 1940s wartime radio operator — render a 3-minute extended cinematic short at a London listening post.",
    "I have a portrait of a young 1950s drive-in projectionist — build a 2-minute extended mini-drama at his Texas drive-in booth.",
    "Uploading a sketch of a young 1960s Greenwich Village folk singer — make a 4-minute extended cinematic piece at a MacDougal Street café.",
    "Here's a digital painting of a young 1970s Studio 54 doorman — produce a 3-minute extended short at the velvet rope.",
    "I'm attaching this image of a young 1980s arcade game programmer — build a 2-minute extended mini-drama at a Sunnyvale workstation.",
    "Uploading a portrait of a young 1990s grunge guitarist — make a 4-minute extended cinematic piece at a Seattle basement rehearsal.",
    "Here's a sketch of a young 1830s Ottoman court calligrapher — render a 3-minute extended short at a Topkapi atelier.",
    "I'm sending you a watercolor of a young 1850s Crimean cossack — produce a 2-minute extended mini-drama on a steppe patrol.",
    "Uploading a digital portrait of a young 1870s German railway engineer — build a 4-minute extended cinematic piece at the Berlin-Hamburg line.",
    "Here's a portrait of a young 1880s Vienna piano-tuner — render a 3-minute extended mini-drama at the Bösendorfer workshop.",
    "I'm attaching a sketch of a young 1900s Berlin tram conductor — make a 2-minute extended piece on a Kurfürstendamm line.",
    "Uploading a watercolor of a young 1910s Paris perfumer — produce a 4-minute extended short at a Place Vendôme atelier.",
    "Here's a digital painting of a young 1920s Riviera casino croupier — build a 3-minute extended mini-drama at a Monte Carlo blackjack table.",
    "I have a portrait of a young 1930s Berlin cabaret singer — render a 2-minute extended cinematic piece at a Friedrichstrasse stage.",
    "Uploading a sketch of a young 1940s Lisbon expatriate musician — make a 4-minute extended cinematic short at an Alfama fado bar.",
    "Here's a watercolor of a young 1950s Roman taxi driver — produce a 3-minute extended mini-drama on a Via Veneto night-shift.",
    "I'm sending you a portrait of a young 1960s Carnaby Street tailor — build a 2-minute extended piece in his King's Road shop.",
    "Uploading a digital painting of a young 1970s Rotterdam dockworker — make a 4-minute extended cinematic short at the Maashaven crane.",
    "Here's a sketch of a young 1830s Russian forester — render a 3-minute extended mini-drama in a Karelian birch grove.",
    "I'm attaching a portrait of a young 1860s Saint Petersburg ballet master — produce a 2-minute extended cinematic piece at a Mariinsky rehearsal.",
    "Uploading a watercolor of a young 1880s Baltic amber-trader — build a 4-minute extended cinematic short at a Königsberg counting-house.",
    "Here's a digital portrait of a young 1900s Helsinki librarian — make a 3-minute extended mini-drama in the Cathedral library stacks.",
    "I have a sketch of a young 1820s Stockholm watchmaker — render a 2-minute extended cinematic piece at his Gamla Stan bench.",
    "Uploading a portrait of a young 1850s Copenhagen porcelain-painter — produce a 4-minute extended short at a Royal-Copenhagen kiln.",
    "Here's a watercolor of a young 1830s Swedish iron-master — build a 3-minute extended mini-drama at a Bergslagen blast-furnace.",
    "I'm sending you a digital painting of a young 1900s Trans-Siberian railway dispatcher — render a 2-minute extended cinematic piece at the Irkutsk junction.",
    "Uploading a sketch of a young 1920s Moscow ballerina — make a 4-minute extended cinematic short at a Bolshoi rehearsal.",
    "Here's a portrait of a young 1930s Leningrad music conservator — produce a 3-minute extended mini-drama in the Mariinsky archive.",
    "I'm attaching a watercolor of a young 1880s Buenos Aires cattle-rancher — build a 2-minute extended cinematic piece on the pampas at dawn.",
    "Uploading a digital portrait of a young 1900s São Paulo coffee-baron's daughter — render a 4-minute extended short at a fazenda veranda.",
    "Here's a sketch of a young 1910s Havana tobacco-roller — make a 3-minute extended cinematic piece at a Vedado factory bench.",
    "I have a portrait of a young 1920s Mexican Revolution cinematographer — produce a 2-minute extended mini-drama on a Sonora outdoor shoot.",
    "Uploading a watercolor of a young 1880s Cape Town railway engineer — build a 4-minute extended cinematic short at the Hex River pass.",
    "Here's a digital painting of a young 1900s Cairo telegraph operator — render a 3-minute extended mini-drama at a Khedival exchange.",
    "I'm sending you a sketch of a young 1920s Casablanca harbor-customs officer — produce a 2-minute extended cinematic piece at the medina pier.",
    "Uploading a portrait of a young 1870s Ottoman shipyard apprentice — make a 4-minute extended cinematic short at the Tersane drydock.",
    "Here's a watercolor of a young 1900s Damascus mosaic artisan — build a 3-minute extended mini-drama at his Old-City workshop.",
    "I'm attaching a digital portrait of a young 1880s Tehran Qajar court scribe — render a 2-minute extended cinematic piece at the Golestan Palace.",
    "Uploading a sketch of a young 1910s Bombay film-set designer — make a 4-minute extended cinematic short at a Dadasaheb Phalke studio.",
    "Here's a portrait of a young 1900s Shanghai jazz-club hostess — produce a 3-minute extended mini-drama at a Bund speakeasy.",
    "I have a watercolor of a young 1920s Hong Kong bookseller — build a 2-minute extended cinematic piece in a Sheung Wan stall.",
    "Uploading a digital painting of a young 1930s Tokyo radio actress — render a 4-minute extended cinematic short at the JOAK studio.",
    "Here's a sketch of a young 1880s Khedival Cairo court translator — make a 3-minute extended cinematic piece at a Dar al-Kutub library.",
    # ── more reference-image extended cinematic shorts (50) ──────────────
    "Uploading a portrait of a young 1860s Crimean-war field-photographer — make a 3-minute extended cinematic mini-drama at a Sevastopol bivouac.",
    "Here's a sketch of a young 1880s Boer-war field-photographer — build a 4-minute extended cinematic short on a Karoo wagon-trail.",
    "I'm sending you a watercolor of a young 1900s Russo-Japanese-war photographer — produce a 2-minute extended mini-drama at a Mukden street-scene.",
    "Uploading a digital painting of a young 1900s World's-Fair architect — make a 4-minute extended cinematic piece on a Paris Exposition gallery.",
    "Here's a portrait of a young 1900s Worth-Paris fashion-house seamstress — render a 3-minute extended short on the Rue de la Paix workroom.",
    "I'm attaching a sketch of a young 1900s Belle-Époque cabaret dancer — build a 2-minute extended cinematic mini-drama at a Pigalle dressing-room.",
    "Uploading this concept art of a young 1900s Le-Chat-Noir café cabaret-singer — produce a 4-minute extended piece at a Montmartre stage.",
    "Here's a watercolor of a young 1900s Toulouse-Lautrec poster-printer — render a 3-minute extended cinematic short at a lithograph press.",
    "I have a portrait of a young 1900s Munich Jugendstil illustrator — build a 2-minute extended mini-drama at a Schwabing atelier.",
    "Uploading a sketch of a young 1900s Vienna-Secession poster-artist — make a 4-minute extended cinematic piece at a Karlsplatz gallery.",
    "Here's a digital painting of a young 1900s Glasgow Mackintosh-school designer — produce a 3-minute extended short at a Charles-Rennie-Mackintosh studio.",
    "I'm attaching this image of a young 1900s Glasgow tenement charwoman — build a 2-minute extended mini-drama on a back-court close.",
    "Uploading a portrait of a young 1900s Manchester-cotton-mill spinner — make a 4-minute extended cinematic piece on a humming spinning floor.",
    "Here's a sketch of a young 1900s Sheffield steel-cutler apprentice — render a 3-minute extended short at a grinding-wheel bench.",
    "I'm sending you a watercolor of a young 1900s Birmingham brass-foundry apprentice — produce a 2-minute extended mini-drama at a furnace pour.",
    "Uploading a digital portrait of a young 1900s Cardiff coal-trimmer — build a 4-minute extended cinematic piece in a steamer hold.",
    "Here's a portrait of a young 1900s Liverpool dockworker — render a 3-minute extended mini-drama on a Mersey quay morning.",
    "I'm attaching a sketch of a young 1900s Belfast shipyard riveter — make a 2-minute extended piece on a Harland-and-Wolff slipway.",
    "Uploading a watercolor of a young 1900s Glasgow-Clyde shipyard plater — produce a 4-minute extended short on a Govan slip dawn.",
    "Here's a digital painting of a young 1900s Copenhagen porcelain-painter — build a 3-minute extended mini-drama at a Royal-Copenhagen kiln.",
    "I have a portrait of a young 1900s Stockholm match-factory worker — render a 2-minute extended cinematic piece at a Jönköping packing line.",
    "Uploading a sketch of a young 1900s Helsinki port-customs clerk — make a 4-minute extended cinematic short at a South-Harbor counter.",
    "Here's a watercolor of a young 1900s St-Petersburg telegraph-clerk — produce a 3-minute extended mini-drama at a Nevsky exchange.",
    "I'm sending you a portrait of a young 1900s Warsaw-Łódź textile-worker — build a 2-minute extended piece on a Łódź mill-floor.",
    "Uploading a digital painting of a young 1900s Łódź-textile loom-mender — make a 4-minute extended cinematic short on a noisy weaving floor.",
    "Here's a sketch of a young 1900s Vienna-Hofbrauerei brewer — render a 3-minute extended mini-drama at a copper kettle.",
    "I'm attaching a portrait of a young 1900s Prague Plzeň brewer — produce a 2-minute extended cinematic piece in a Pilsner cellar.",
    "Uploading a watercolor of a young 1900s Munich Hofbräuhaus brewer — build a 4-minute extended cinematic short in a Bavarian cellar.",
    "Here's a digital portrait of a young 1900s Brussels chocolatier — make a 3-minute extended mini-drama at a Sablon shop counter.",
    "I have a sketch of a young 1900s Antwerp diamond-cutter — render a 2-minute extended cinematic piece at a Pelikaanstraat bench.",
    "Uploading a portrait of a young 1900s Amsterdam diamond-polisher — produce a 4-minute extended short at a Jodenbreestraat bench.",
    "Here's a watercolor of a young 1900s Rotterdam shipping-clerk — build a 3-minute extended mini-drama at a Maashaven quay-office.",
    "I'm sending you a digital painting of a young 1900s Bremen-shipping clerk — render a 2-minute extended cinematic piece at a Norddeutscher-Lloyd counter.",
    "Uploading a sketch of a young 1900s Hamburg dockworker — make a 4-minute extended cinematic short on a Speicherstadt wharf.",
    "Here's a portrait of a young 1900s Bremerhaven emigrant officer — produce a 3-minute extended mini-drama at the Auswandererhaus desk.",
    "I'm attaching a watercolor of a young 1900s Genoa emigrant agent — build a 2-minute extended cinematic piece at a Stazione-Marittima counter.",
    "Uploading a digital portrait of a young 1900s Naples emigrant porter — render a 4-minute extended short on a Molo Beverello quay.",
    "Here's a sketch of a young 1900s Marseille port-clerk — make a 3-minute extended cinematic piece at a Vieux-Port counter.",
    "I have a portrait of a young 1900s Le-Havre transatlantic clerk — produce a 2-minute extended mini-drama at a Compagnie-Générale-Transatlantique counter.",
    "Uploading a watercolor of a young 1900s Liverpool transatlantic clerk — build a 4-minute extended cinematic short at a Pier-Head counter.",
    "Here's a digital painting of a young 1900s Glasgow transatlantic clerk — render a 3-minute extended mini-drama at a Broomielaw counter.",
    "I'm sending you a sketch of a young 1900s Belfast transatlantic clerk — make a 2-minute extended cinematic piece at a Donegall-Quay counter.",
    "Uploading a portrait of a young 1900s Bremen-Lloyd cabin-clerk — produce a 4-minute extended short at a passenger-list desk.",
    "Here's a watercolor of a young 1900s Hamburg-Amerika-Linie clerk — build a 3-minute extended mini-drama at a Sankt-Pauli pier office.",
    "I'm attaching a digital portrait of a young 1900s Cunard-Line steward — render a 2-minute extended cinematic piece in a Lusitania first-class corridor.",
    "Uploading a sketch of a young 1900s White-Star-Line steward — make a 4-minute extended cinematic short on an Olympic boat-deck.",
    "Here's a portrait of a young 1900s Ellis-Island clerk — produce a 3-minute extended mini-drama at the Great-Hall registry desk.",
    "I have a watercolor of a young 1900s Lower-East-Side garment-shop floor-sweeper — render a 2-minute extended cinematic piece on a Grand-Street stair.",
    "Uploading a digital painting of a young 1900s Triangle-Shirtwaist-Factory seamstress — build a 4-minute extended cinematic short on a Washington-Place loft floor.",
    "Here's a sketch of a young 1900s Castle-Garden NY-immigration clerk — make a 3-minute extended cinematic mini-drama at a Battery-Park counter.",
    # ── more reference-image extended cinematic shorts (50) ──────────────
    "Uploading a portrait of a young 1920s Berlin-Weimar street-photographer — make a 3-minute extended cinematic mini-drama at an Alexanderplatz tram stop.",
    "Here's a sketch of a young 1920s Paris-Surrealist-poet — build a 4-minute extended cinematic short at a Café-Cyrano Montmartre table.",
    "I'm sending you a watercolor of a young 1920s Lost-Generation novelist — produce a 2-minute extended mini-drama at a Shakespeare-and-Company shelf.",
    "Uploading a digital painting of a young 1920s Algonquin-Round-Table wit — make a 4-minute extended cinematic piece at a Rose-Room round-table.",
    "Here's a portrait of a young 1920s NY-Bohemia salon-hostess — render a 3-minute extended short in a Gramercy parlor.",
    "I'm attaching a sketch of a young 1920s Greenwich-Village painter — build a 2-minute extended cinematic mini-drama at a Washington-Square studio.",
    "Uploading this concept art of a young 1930s WPA-muralist — produce a 4-minute extended piece on a public-library scaffold.",
    "Here's a watercolor of a young 1930s Federal-Theatre-Project actor — render a 3-minute extended cinematic short at a community-stage rehearsal.",
    "I have a portrait of a young 1930s WPA-Photographer — build a 2-minute extended mini-drama at a Dust-Bowl ranch.",
    "Uploading a sketch of a young 1930s Federal-Writers-Project oral-historian — make a 4-minute extended cinematic piece at a slave-narrative interview.",
    "Here's a digital painting of a young 1940s WAC clerk — produce a 3-minute extended short at a Pentagon corridor.",
    "I'm attaching this image of a young 1940s Tuskegee-Airman pilot — build a 2-minute extended mini-drama at a Ramitelli airfield.",
    "Uploading a portrait of a young 1940s Navajo-code-talker — make a 4-minute extended cinematic piece at a Pacific-front bunker.",
    "Here's a sketch of a young 1940s OSS-Jedburgh agent — render a 3-minute extended short at a moonlit drop-zone.",
    "I'm sending you a watercolor of a young 1940s WAVES navy-reservist — produce a 2-minute extended mini-drama at a Boston-Navy-Yard pier.",
    "Uploading a digital portrait of a young 1940s ENIAC computer-operator — build a 4-minute extended cinematic piece at a Penn-engineering room.",
    "Here's a portrait of a young 1940s Manhattan-Project secretary — render a 3-minute extended mini-drama at a Los-Alamos office.",
    "I'm attaching a sketch of a young 1950s ad-agency copywriter — make a 2-minute extended piece at a Madison-Avenue bullpen.",
    "Uploading a watercolor of a young 1950s Mercury-7 secretary — produce a 4-minute extended short at a Cape-Canaveral office.",
    "Here's a digital painting of a young 1950s Disney-Imagineer — build a 3-minute extended mini-drama at a Burbank model-shop.",
    "I have a portrait of a young 1960s Pan-Am stewardess — render a 2-minute extended cinematic piece at a Worldport gate.",
    "Uploading a sketch of a young 1960s NASA-Mission-Control engineer — make a 4-minute extended cinematic short at a Houston flight-control room.",
    "Here's a watercolor of a young 1960s NASA-software programmer — produce a 3-minute extended mini-drama at an MIT-instrumentation-lab terminal.",
    "I'm sending you a portrait of a young 1960s NASA-Apollo-medical officer — build a 2-minute extended piece at a Cape-Kennedy clinic.",
    "Uploading a digital painting of a young 1960s Beatlemania concert-photographer — make a 4-minute extended cinematic short at a Shea-Stadium pit.",
    "Here's a sketch of a young 1960s Liverpool-Cavern bouncer — render a 3-minute extended mini-drama at a Mathew-Street stairway.",
    "I'm attaching a portrait of a young 1960s Carnaby-Street fashion-photographer — produce a 2-minute extended cinematic piece at a King's-Road shop.",
    "Uploading a watercolor of a young 1960s Saigon war-correspondent — build a 4-minute extended cinematic short at a Continental-Hotel rooftop.",
    "Here's a digital portrait of a young 1970s NYT investigative reporter — make a 3-minute extended mini-drama at a 43rd-Street newsroom.",
    "I have a sketch of a young 1970s ABC-Mod-Squad scriptwriter — render a 2-minute extended cinematic piece at a Burbank writers' room.",
    "Uploading a portrait of a young 1970s Sesame-Street puppeteer — produce a 4-minute extended short at a Children's-Television-Workshop studio.",
    "Here's a watercolor of a young 1970s SNL writer — build a 3-minute extended mini-drama at a 30-Rock writers' room.",
    "I'm sending you a digital painting of a young 1970s SNL costume-designer — render a 2-minute extended cinematic piece at a wardrobe department.",
    "Uploading a sketch of a young 1970s Columbia-Studios sound-engineer — make a 4-minute extended cinematic short at a Studio-A console.",
    "Here's a portrait of a young 1970s Capitol-Records studio-A engineer — produce a 3-minute extended mini-drama at a Capitol-Tower booth.",
    "I'm attaching a watercolor of a young 1980s MTV-VJ — build a 2-minute extended cinematic piece at a Times-Square studio.",
    "Uploading a digital portrait of a young 1980s CNN-anchor — render a 4-minute extended short at an Atlanta news-desk.",
    "Here's a sketch of a young 1980s Reuters-foreign correspondent — make a 3-minute extended cinematic piece at a Beirut bureau.",
    "I have a portrait of a young 1980s Fleet-Street tabloid editor — produce a 2-minute extended mini-drama at a Daily-Mirror layout-table.",
    "Uploading a watercolor of a young 1990s dot-com startup engineer — build a 4-minute extended cinematic short at a SOMA loft.",
    "Here's a digital painting of a young 1990s Wired-magazine editor — render a 3-minute extended mini-drama at a 3rd-Street office.",
    "I'm sending you a sketch of a young 1990s Nintendo-Power-magazine editor — make a 2-minute extended cinematic piece at a Redmond newsroom.",
    "Uploading a portrait of a young 1990s skater-magazine photographer — produce a 4-minute extended short at a SF Embarcadero ramp.",
    "Here's a watercolor of a young 1990s NYT-Style-Magazine editor — build a 3-minute extended mini-drama at a Times-Square fashion closet.",
    "I'm attaching a digital portrait of a young 2000s Brooklyn-letterpress shop printer — render a 2-minute extended cinematic piece at a Williamsburg press.",
    "Uploading a sketch of a young 2000s Brooklyn-vintage-clothing-buyer — make a 4-minute extended cinematic short at a Bedford-Avenue boutique.",
    "Here's a portrait of a young 2000s LA-coffee-shop-barista — produce a 3-minute extended mini-drama at a Silver-Lake espresso bar.",
    "I have a watercolor of a young 2000s Portland-vinyl-DJ — build a 2-minute extended cinematic piece at a Mississippi-Avenue bar.",
    "Uploading a digital painting of a young 2010s Brooklyn-cocktail-bartender — render a 4-minute extended short at a Crown-Heights speakeasy.",
    "Here's a sketch of a young 2010s Bay-Area startup-founder — make a 3-minute extended cinematic mini-drama at a SoMa whiteboard.",
    # ── more 2020s+ tech / 2030s+ space / 2050s+ sci-fi figures (50) ──
    "Uploading a portrait of a young 2020s remote-worker software-engineer — make a 2-minute extended cinematic mini-drama in a Lisbon-coliving co-working pod.",
    "Here's a sketch of a young 2020s Berlin-Mitte UX-designer — build a 3-minute extended cinematic short at a Mitte rooftop standup.",
    "I have a digital portrait of a young 2020s Bangalore-startup founder — render a 4-minute extended short at an Indiranagar whiteboard.",
    "Uploading a watercolor of a young 2020s Dubai-AI-lab researcher — produce a 3-minute extended mini-drama at a DIFC GPU-rack.",
    "Here's a portrait of a young 2020s Singapore-fintech compliance-officer — make a 2-minute extended cinematic piece at a Marina-Bay-Sands desk.",
    "I'm sending you a digital painting of a young 2020s Stockholm-sustainability designer — build a 4-minute extended short at a Norrsken-House desk.",
    "Uploading a sketch of a young 2020s Mexico-City data-scientist — render a 3-minute extended mini-drama at a Roma-Norte loft.",
    "Here's a watercolor of a young 2020s Lagos-fintech operator — make a 2-minute extended cinematic piece at a Yaba startup-row office.",
    "I have a digital portrait of a young 2020s Nairobi-mobile-banking founder — produce a 4-minute extended short at a Westlands hub-desk.",
    "I'm attaching a sketch of a young 2020s Cape-Town-ESG analyst — build a 3-minute extended cinematic piece at a Woodstock co-op.",
    "Uploading a portrait of a young 2020s Tel-Aviv-cyber-security analyst — render a 2-minute extended mini-drama at a Rothschild-Boulevard SOC.",
    "Here's a watercolor of a young 2020s Riga-cross-border fintech operator — make a 4-minute extended cinematic short at a Spīķeri loft.",
    "I have a digital painting of a young 2020s Tallinn-e-residency clerk — produce a 3-minute extended cinematic piece at a Telliskivi office.",
    "Uploading a sketch of a young 2020s Reykjavik-data-center operator — build a 2-minute extended mini-drama at a Hafnarfjörður server-hall.",
    "Here's a portrait of a young 2030s Mars-colony hydroponic-engineer — render a 4-minute extended short at a Cydonia greenhouse.",
    "I'm sending you a watercolor of a young 2030s Lunar-Gateway-quartermaster — make a 3-minute extended cinematic piece at a Shackleton-Crater airlock.",
    "Uploading a digital portrait of a young 2030s asteroid-belt prospector — produce a 2-minute extended short at a Vesta mining-rig.",
    "Here's a sketch of a young 2030s Europa-ice-station diver — build a 4-minute extended cinematic short at a sub-ice-bunker airlock.",
    "I have a portrait of a young 2030s Titan-methane-station chemist — render a 3-minute extended mini-drama at a Kraken-Mare gantry.",
    "I'm attaching a digital portrait of a young 2030s Ceres-water-mining foreman — make a 2-minute extended cinematic piece at an Occator gantry.",
    "Uploading a watercolor of a young 2040s orbital-tether elevator-tech — produce a 4-minute extended short at a Quito-equatorial cable-station.",
    "Here's a digital painting of a young 2040s solar-power satellite-operator — build a 3-minute extended mini-drama at a GEO power-relay deck.",
    "I'm sending you a sketch of a young 2040s underwater-city engineer — make a 2-minute extended cinematic piece at a Sub-Pacific dome.",
    "Uploading a portrait of a young 2040s Antarctica-research climatologist — render a 4-minute extended short at a Vostok-2 station.",
    "Here's a watercolor of a young 2040s Greenland-glacial-retreat surveyor — produce a 3-minute extended cinematic piece at an Ilulissat outlook.",
    "I have a digital portrait of a young 2040s Sahel-reforestation-corps planter — build a 2-minute extended mini-drama at a Great-Green-Wall site.",
    "I'm attaching a sketch of a young 2040s Indonesia-mangrove restoration-corps diver — make a 4-minute extended cinematic short at a Bali nursery.",
    "Uploading a portrait of a young 2040s Pacific-coral-restoration diver — produce a 3-minute extended cinematic piece at a Great-Barrier-Reef nursery.",
    "Here's a watercolor of a young 2040s vertical-farm operator — build a 2-minute extended mini-drama at a Tokyo high-rise hydroponic floor.",
    "I have a digital painting of a young 2050s neural-interface developer — render a 4-minute extended short at a São-Paulo neurotech lab.",
    "Uploading a sketch of a young 2050s synthetic-biology engineer — make a 3-minute extended cinematic piece at a Cambridge bioreactor.",
    "Here's a portrait of a young 2050s xenotransplant surgeon — produce a 2-minute extended short at a Kyoto medical-center theater.",
    "I'm sending you a digital portrait of a young 2050s gene-therapy clinic technician — build a 4-minute extended cinematic short at a Boston biolab.",
    "Uploading a watercolor of a young 2050s artificial-organ printer — render a 3-minute extended mini-drama at a Rotterdam tissue-lab.",
    "Here's a sketch of a young 2050s memory-archive technician — make a 2-minute extended cinematic piece at a Helsinki memory-vault.",
    "I have a digital painting of a young 2050s consciousness-uploading consultant — produce a 4-minute extended short at a Singapore upload-clinic.",
    "I'm attaching a portrait of a young 2050s holodeck-content designer — build a 3-minute extended cinematic piece at an LA holo-studio.",
    "Uploading a sketch of a young 2050s deep-fake-forensics investigator — render a 2-minute extended mini-drama at a Paris cybercrime lab.",
    "Here's a watercolor of a young 2050s climate-engineering aerosol pilot — make a 4-minute extended cinematic short at a stratospheric airfield.",
    "I have a digital portrait of a young 2050s solar-shade orbital-mechanic — produce a 3-minute extended cinematic piece at an L1 station.",
    "Uploading a portrait of a young 2050s deep-sea geothermal-station operator — build a 2-minute extended mini-drama at a Mariana-Trench rig.",
    "Here's a sketch of a young 2050s arctic-ice-shelf engineer — render a 4-minute extended short at a Nunavut ice-platform.",
    "I'm sending you a watercolor of a young 2060s exoplanet-rover pilot — make a 3-minute extended cinematic piece at a Proxima-Centauri-b dome.",
    "Uploading a digital portrait of a young 2060s tachyon-relay technician — produce a 2-minute extended short at a Kuiper-Belt relay.",
    "Here's a portrait of a young 2060s warp-drive engineer — build a 4-minute extended cinematic short at a Vega test-yard.",
    "I have a sketch of a young 2060s alien-contact diplomat — render a 3-minute extended mini-drama at a Trappist-1 outpost.",
    "I'm attaching a digital painting of a young 2060s xeno-archeologist — make a 2-minute extended cinematic piece at a Mars-sands dig.",
    "Uploading a watercolor of a young 2060s post-singularity ethicist — produce a 4-minute extended short at a Reykjavik-Singularity-Institute desk.",
    "Here's a sketch of a young 2070s deep-time archivist — build a 3-minute extended cinematic piece at a Svalbard knowledge-vault.",
    "I have a digital portrait of a young 2070s atmosphere-restoration steward — render a 2-minute extended mini-drama at an Andean condor-monitor station.",
    # ── more 1950s–1970s American suburban / counter-culture / Vietnam-era figures (50) ──
    "Uploading a portrait of a young 1950s Levittown-suburb housewife — make a 2-minute extended cinematic mini-drama at a kitchen-formica counter.",
    "Here's a sketch of a young 1950s Detroit-auto-line worker — build a 3-minute extended cinematic short at a Ford-Rouge plant floor.",
    "I have a digital portrait of a young 1950s Cape-Canaveral mission-control technician — render a 4-minute extended short at a launch-control console.",
    "I'm sending you a watercolor of a young 1950s Las-Vegas Sands-Hotel showgirl — produce a 3-minute extended mini-drama at a Sands-stage backstage.",
    "Uploading a digital painting of a young 1950s Greenwich-Village-Beat poet — build a 2-minute extended cinematic short at a Gaslight-Cafe stage.",
    "Here's a portrait of a young 1950s Brooklyn-stickball kid — make a 4-minute extended cinematic mini-drama at a row-house alley.",
    "I have a sketch of a young 1950s Boston-streetcar conductor — render a 3-minute extended short at a Park-Street platform.",
    "I'm attaching a digital portrait of a young 1950s Hollywood studio-system starlet — produce a 2-minute extended cinematic piece at an MGM-backlot soundstage.",
    "Uploading a watercolor of a young 1950s San-Francisco-North-Beach jazz-club-singer — build a 4-minute extended cinematic short at a Hungry-i basement stage.",
    "Here's a digital painting of a young 1950s Chicago-South-Side blues-guitarist — make a 3-minute extended mini-drama at a Maxwell-Street market corner.",
    "I have a portrait of a young 1950s Kansas-City BBQ-pit master — produce a 2-minute extended short at an 18th-and-Vine smokehouse.",
    "I'm sending you a sketch of a young 1950s Memphis-Sun-Studio session musician — render a 4-minute extended cinematic piece at a Sun-Studio recording booth.",
    "Uploading a digital portrait of a young 1960s Mississippi-civil-rights-marcher — build a 3-minute extended cinematic short at a Selma-Edmund-Pettus-Bridge approach.",
    "Here's a watercolor of a young 1960s Chicago-Democratic-Convention protester — produce a 2-minute extended mini-drama at a Grant-Park rally.",
    "I have a digital painting of a young 1960s Berkeley-Free-Speech-Movement activist — make a 4-minute extended cinematic short at a Sproul-Plaza step.",
    "I'm attaching a portrait of a young 1960s Haight-Ashbury hippie — render a 3-minute extended cinematic piece at a Diggers Free-Store doorway.",
    "Uploading a sketch of a young 1960s Greenwich-Village folk-revival singer — produce a 2-minute extended short at a Cafe-Wha basement stage.",
    "Here's a portrait of a young 1960s Newport-Folk-Festival kid — build a 4-minute extended cinematic short at a Festival Field rope-edge.",
    "I have a watercolor of a young 1960s Woodstock concertgoer — make a 3-minute extended mini-drama at a Bethel-pasture muddy slope.",
    "I'm sending you a digital painting of a young 1960s Memphis-Stax studio session-singer — produce a 2-minute extended cinematic piece at a Stax recording-floor.",
    "Uploading a digital portrait of a young 1960s Detroit-Motown studio session-drummer — build a 4-minute extended short at a Hitsville-USA basement.",
    "Here's a sketch of a young 1960s Vietnam-1st-Cav radio-operator — render a 3-minute extended cinematic short at an A-Shau-Valley fire-base.",
    "I have a portrait of a young 1960s Vietnam-101st-Airborne medic — produce a 2-minute extended cinematic piece at a Hill-937-Hamburger ridge.",
    "I'm attaching a digital portrait of a young 1960s Saigon-AP wire-service photojournalist — make a 4-minute extended cinematic short at a Caravelle-rooftop bar.",
    "Uploading a watercolor of a young 1960s NASA-Houston flight-controller — build a 3-minute extended cinematic short at a Mission-Control-Apollo-11 console.",
    "Here's a digital painting of a young 1960s NASA-Cape-Kennedy launch-engineer — render a 2-minute extended mini-drama at a Saturn-V gantry.",
    "I have a portrait of a young 1960s Black-Panther free-breakfast volunteer — produce a 4-minute extended cinematic piece at an Oakland-school cafeteria.",
    "I'm sending you a sketch of a young 1960s Chicano-Brown-Beret organizer — make a 3-minute extended cinematic short at an East-LA-school walkout.",
    "Uploading a digital portrait of a young 1960s Stonewall-Inn drag-queen — produce a 2-minute extended short at a Christopher-Street barricade.",
    "Here's a watercolor of a young 1970s San-Francisco-Castro-Street activist — build a 4-minute extended cinematic short at a Castro-Camera doorway.",
    "I have a digital painting of a young 1970s Los-Angeles-Sunset-Strip rock-club doorgirl — make a 3-minute extended mini-drama at a Whisky-a-Go-Go entrance.",
    "I'm attaching a portrait of a young 1970s Studio-54-NYC dance-floor regular — render a 2-minute extended cinematic piece at a 54th-Street velvet-rope.",
    "Uploading a sketch of a young 1970s CBGB-NYC punk-bartender — produce a 4-minute extended cinematic short at a Bowery dive-bar counter.",
    "Here's a portrait of a young 1970s Berkeley-People's-Park gardener — build a 3-minute extended cinematic short at a Telegraph-Avenue fence.",
    "I have a watercolor of a young 1970s Madison-protester — render a 2-minute extended mini-drama at a Bascom-Hill rally.",
    "I'm sending you a digital painting of a young 1970s Kent-State-after-shock student — produce a 4-minute extended cinematic piece at a Memorial-Gym path.",
    "Uploading a digital portrait of a young 1970s Vietnam-anti-war-march flag-bearer — make a 3-minute extended cinematic short at a Washington-Mall lawn.",
    "Here's a sketch of a young 1970s Montgomery-bus-line driver — build a 2-minute extended cinematic short at a Dexter-Avenue stop.",
    "I have a portrait of a young 1970s Brooklyn-graffiti-writer — render a 4-minute extended mini-drama at a 1-train Lexington-Ave-platform.",
    "I'm attaching a digital portrait of a young 1970s Bronx-block-party DJ — produce a 3-minute extended cinematic piece at a Sedgwick-Avenue stoop.",
    "Uploading a watercolor of a young 1970s Apollo-Theater-Amateur-Night singer — build a 2-minute extended cinematic short at a 125th-Street stage-edge.",
    "Here's a digital painting of a young 1970s Sausalito-houseboat artist — make a 4-minute extended cinematic short at a Gate-5-dock railing.",
    "I have a portrait of a young 1970s Aspen-ski-bum waiter — render a 3-minute extended mini-drama at a Hotel-Jerome-bar tap.",
    "I'm sending you a sketch of a young 1970s Nantucket-clam-bake server — produce a 2-minute extended cinematic piece at a Wauwinet-Inn beach.",
    "Uploading a digital portrait of a young 1970s Martha's-Vineyard ferry-boat deckhand — build a 4-minute extended cinematic short at a Vineyard-Haven slip.",
    "Here's a watercolor of a young 1970s Hamptons-summer-share housekeeper — make a 3-minute extended cinematic short at a Sag-Harbor wharf.",
    "I have a digital painting of a young 1970s Fire-Island-house-share kid — render a 2-minute extended mini-drama at a Pines-boardwalk crossing.",
    "I'm attaching a portrait of a young 1970s Seattle-Space-Needle-elevator operator — produce a 4-minute extended cinematic piece at a Skytop-overlook deck.",
    "Uploading a sketch of a young 1970s Portland-coffee-cart barista — build a 3-minute extended cinematic short at a Pioneer-Square cart counter.",
    "Here's a portrait of a young 1970s Albuquerque-Atomic-Museum docent — make a 2-minute extended cinematic mini-drama at a Trinity-test replica.",
    # ── more 1980s-90s subcultures (punk / grunge / hip-hop / rave) (50) ──
    "Uploading a portrait of a 1980s NYC-CBGB punk drummer — make a 2-minute extended cinematic mini-drama at a CBGB-Bowery stage.",
    "Here's a sketch of a 1980s NYC-Lower-East-Side hardcore-skater — build a 3-minute extended cinematic short at a Tompkins-Square skate-bowl.",
    "I'm sending you a watercolor of a 1980s NYC-Mudd-Club no-wave keyboardist — produce a 4-minute extended cinematic piece at a Mudd-Club basement.",
    "Uploading a digital painting of a 1980s NYC-Danceteria hi-NRG dancer — render a 2-minute extended mini-drama at a Danceteria-Chelsea floor.",
    "Here's a portrait of a 1980s LA-Rainbow-Bar-and-Grill hair-metal roadie — make a 3-minute extended cinematic short at a Sunset-Strip backstage.",
    "I have a sketch of a 1980s LA-Whisky-a-Go-Go punk bassist — produce a 4-minute extended cinematic piece at a Whisky-a-Go-Go corner-stage.",
    "Uploading a watercolor of a 1980s LA-Madame-Wong's punk lead-singer — build a 2-minute extended mini-drama at a Chinatown-club back-alley.",
    "Here's a digital portrait of a 1980s LA-Olvera-Street-X-band drummer — render a 3-minute extended cinematic short at a Plaza-Olvera bandstand.",
    "I'm sending you a portrait of a 1980s SF-Mabuhay-Gardens punk vocalist — produce a 4-minute extended cinematic piece at a Mabuhay-Gardens stage.",
    "Uploading a sketch of a 1980s SF-Sound-of-Music punk fan — make a 2-minute extended mini-drama at a Tenderloin-club doorway.",
    "Here's a watercolor of a 1980s DC-9:30-Club-hardcore singer — build a 3-minute extended cinematic short at a 9:30-Club original-stage.",
    "I have a digital painting of a 1980s DC-dischord-house-recording bassist — render a 4-minute extended cinematic piece at an Arlington dischord-house basement.",
    "Uploading a portrait of a 1980s Boston-Rat-club punk drummer — produce a 2-minute extended mini-drama at a Kenmore-Square Rat-club doorway.",
    "Here's a sketch of a 1980s Detroit-Bookies-Club-808 industrial-musician — make a 3-minute extended cinematic short at a Bookies-Club-808 backroom.",
    "I'm sending you a watercolor of a 1980s Detroit-techno Belleville-Three follower — render a 4-minute extended cinematic piece at a Music-Institute dance-floor.",
    "Uploading a digital portrait of a 1980s Chicago-house-music Warehouse-club dancer — produce a 2-minute extended mini-drama at a Warehouse-club main-floor.",
    "Here's a portrait of a 1980s Chicago-Music-Box DJ — build a 3-minute extended cinematic short at a Music-Box-Chicago booth.",
    "I have a sketch of a 1980s NYC-Paradise-Garage Larry-Levan-era dancer — make a 4-minute extended cinematic piece at a Paradise-Garage main-floor.",
    "Uploading a watercolor of a 1980s NYC-Roxy roller-rink hip-hop fan — render a 2-minute extended mini-drama at a Roxy-NYC roller-rink floor.",
    "Here's a digital painting of a 1980s Bronx-Zulu-Nation block-party dancer — produce a 3-minute extended cinematic short at a Bronx-1520-Sedgwick block-party.",
    "I'm sending you a portrait of a 1980s Brooklyn-Latin-Quarter hip-hop MC — make a 4-minute extended cinematic piece at a Latin-Quarter-Times-Square stage.",
    "Uploading a sketch of a 1980s Queens-Run-DMC-era b-boy — build a 2-minute extended mini-drama at a Hollis-Queens stoop.",
    "Here's a watercolor of a 1980s LA-Compton-NWA-era b-boy — render a 3-minute extended cinematic short at a Compton-Park drum-circle.",
    "I have a digital portrait of a 1980s Philadelphia-DJ-Jazzy-Jeff-era b-boy — produce a 4-minute extended cinematic piece at a Philadelphia-North block-party.",
    "Uploading a portrait of a 1980s Atlanta-Freaknik street-DJ — make a 2-minute extended mini-drama at a Centennial-Park-Atlanta DJ-truck.",
    "Here's a sketch of a 1980s Houston-Geto-Boys-era DJ — build a 3-minute extended cinematic short at a Houston-Fifth-Ward block-party.",
    "I'm sending you a watercolor of a 1980s Miami-2-Live-Crew-era dancer — produce a 4-minute extended cinematic piece at a South-Beach-Miami stage.",
    "Uploading a digital portrait of a 1980s Memphis-Three-Six-Mafia-era b-boy — render a 2-minute extended mini-drama at a Memphis-Beale-Street curb.",
    "Here's a portrait of a 1980s Kingston-dancehall-Jamaica selector — produce a 3-minute extended cinematic short at a Kingston-Jamaica sound-system rig.",
    "I have a sketch of a 1980s London-Notting-Hill-Carnival sound-system DJ — make a 4-minute extended cinematic piece at a Notting-Hill-Carnival sound-truck.",
    "Uploading a watercolor of a 1990s Seattle-Sub-Pop-grunge guitarist — build a 2-minute extended mini-drama at a Sub-Pop-Belltown studio.",
    "Here's a digital painting of a 1990s Seattle-Crocodile-Café grunge-fan — render a 3-minute extended cinematic short at a Crocodile-Café-Seattle stage-pit.",
    "I'm sending you a portrait of a 1990s Olympia-Riot-Grrrl bass-player — produce a 4-minute extended cinematic piece at a Olympia-K-Records basement.",
    "Uploading a sketch of a 1990s Portland-X-Ray-Cafe punk lead-singer — make a 2-minute extended mini-drama at a X-Ray-Cafe-Portland stage.",
    "Here's a watercolor of a 1990s Aberdeen-Washington grunge-teenager — build a 3-minute extended cinematic short at an Aberdeen-Wishkah-River bridge.",
    "I have a digital portrait of a 1990s Tacoma-grunge-fan — render a 4-minute extended cinematic piece at a Tacoma-Tides skate-park.",
    "Uploading a portrait of a 1990s NYC-Wetlands-Preserve jam-band fan — produce a 2-minute extended mini-drama at a Wetlands-NYC-Hudson-Square dance-floor.",
    "Here's a sketch of a 1990s NYC-Limelight-club rave-kid — make a 3-minute extended cinematic short at a Limelight-Chelsea altar.",
    "I'm sending you a watercolor of a 1990s NYC-Tunnel-club rave-DJ — render a 4-minute extended cinematic piece at a Tunnel-club-NYC main-room.",
    "Uploading a digital portrait of a 1990s Detroit-Movement-festival techno-fan — produce a 2-minute extended mini-drama at a Hart-Plaza Detroit-Electronic-Music-Festival stage.",
    "Here's a portrait of a 1990s Berlin-Tresor club-kid — build a 3-minute extended cinematic short at a Tresor-Berlin vault.",
    "I have a sketch of a 1990s Berlin-Love-Parade Christopher-Street-Day raver — make a 4-minute extended cinematic piece at a Tiergarten-Berlin Love-Parade truck.",
    "Uploading a watercolor of a 1990s Manchester-Hacienda-club Madchester dancer — render a 2-minute extended mini-drama at a Hacienda-Manchester floor.",
    "Here's a digital painting of a 1990s London-Ministry-of-Sound club-fan — produce a 3-minute extended cinematic short at a Ministry-of-Sound-Elephant-and-Castle main-room.",
    "I'm sending you a portrait of a 1990s London-Brixton-Academy Britpop fan — make a 4-minute extended cinematic piece at a Brixton-Academy-O2 pit.",
    "Uploading a sketch of a 1990s Tokyo-Shibuya-kogal — build a 2-minute extended mini-drama at a Shibuya-109 escalator.",
    "Here's a watercolor of a 1990s Tokyo-Harajuku Decora-fashion fan — render a 3-minute extended cinematic short at a Harajuku-Takeshita street-corner.",
    "I have a digital portrait of a 1990s Osaka-Amerikamura street-fashion fan — produce a 4-minute extended cinematic piece at an Amerikamura-Triangle-Park bench.",
    "Uploading a portrait of a 1990s Seoul-Hongdae punk-fan — make a 2-minute extended mini-drama at a Hongdae-Seoul punk-club doorway.",
    "Here's a sketch of a 1990s Bangkok-RCA-club rave-kid — build a 3-minute extended cinematic short at a Bangkok-RCA Royal-City-Avenue.",
    # ── more 2000s-2010s tech-startup / hacker / cyberculture (50) ──
    "Uploading a portrait of a 2000s Palo-Alto-Stanford-dorm-room hacker-founder — make a 2-minute extended cinematic mini-drama at a Stanford-Wilbur-Hall hallway.",
    "Here's a sketch of a 2000s Mountain-View-Googleplex-bike-cubicle engineer — build a 3-minute extended cinematic short at a Google-Charleston-Park lawn.",
    "I'm sending you a watercolor of a 2000s Cupertino-Apple-Infinite-Loop intern — produce a 4-minute extended cinematic piece at an Apple-Loop-cafeteria patio.",
    "Uploading a digital painting of a 2000s Menlo-Park-Sand-Hill-Road VC-analyst — render a 2-minute extended mini-drama at a Sand-Hill-Road-conference-room glass-wall.",
    "Here's a portrait of a 2000s San-Francisco-South-Park startup-coder — make a 3-minute extended cinematic short at a SoMa-loft window.",
    "I have a sketch of a 2000s Mission-District-Mission-Cliffs hacker — produce a 4-minute extended cinematic piece at a Mission-Cliffs climbing-wall.",
    "Uploading a watercolor of a 2000s Berkeley-CSUA-Soda-Hall undergraduate — build a 2-minute extended mini-drama at a Soda-Hall basement-cluster.",
    "Here's a digital portrait of a 2000s MIT-Media-Lab grad-student — render a 3-minute extended cinematic short at a MIT-Stata-Center atrium.",
    "I'm sending you a portrait of a 2000s Cambridge-Kendall-Square biotech-coder — produce a 4-minute extended cinematic piece at a Kendall-Square-rooftop garden.",
    "Uploading a sketch of a 2000s NYC-Flatiron-Building startup-founder — make a 2-minute extended cinematic mini-drama at a Flatiron-Building elevator-lobby.",
    "Here's a watercolor of a 2000s Brooklyn-DUMBO-Etsy-coder — build a 3-minute extended cinematic short at a DUMBO-cobblestone alley.",
    "I have a digital painting of a 2000s NYC-Williamsburg-WeWork freelancer — render a 4-minute extended cinematic piece at a Williamsburg-rooftop pool.",
    "Uploading a portrait of a 2000s Austin-East-Sixth-Street SXSW-developer — produce a 2-minute extended mini-drama at an Austin-Rainey-Street bar-patio.",
    "Here's a sketch of a 2000s Seattle-South-Lake-Union Amazon-coder — make a 3-minute extended cinematic short at an Amazon-Spheres atrium.",
    "I'm sending you a watercolor of a 2000s Seattle-Capitol-Hill startup-CTO — build a 4-minute extended cinematic piece at a Capitol-Hill-bar back-room.",
    "Uploading a digital portrait of a 2000s Boulder-Pearl-Street tech-founder — render a 2-minute extended mini-drama at a Pearl-Street-Mall pedestrian-walk.",
    "Here's a portrait of a 2000s Denver-LoDo-RiNo blockchain-engineer — produce a 3-minute extended cinematic short at a RiNo-Mural-District alley.",
    "I have a sketch of a 2000s Las-Vegas-DefCon-Black-Badge hacker — build a 4-minute extended cinematic piece at a Las-Vegas-Riviera ballroom.",
    "Uploading a watercolor of a 2000s Las-Vegas-Caesars-DefCon CTF-team — make a 2-minute extended cinematic mini-drama at a Caesars-Forum hallway.",
    "Here's a digital painting of a 2000s Berlin-Mitte-CCC-Club hacker — render a 3-minute extended cinematic short at a CCC-Berlin-club-house basement.",
    "I'm sending you a portrait of a 2000s Berlin-Hamburg-Chaos-Communication-Camp camper — produce a 4-minute extended cinematic piece at a CCC-Camp-Mildenberg field.",
    "Uploading a sketch of a 2000s Amsterdam-OHM-camp hacker — make a 2-minute extended cinematic mini-drama at an OHM-Het-Twiske field.",
    "Here's a watercolor of a 2000s London-Silicon-Roundabout startup-founder — build a 3-minute extended cinematic short at an Old-Street-roundabout bench.",
    "I have a digital portrait of a 2000s London-Shoreditch-WeWork developer — render a 4-minute extended cinematic piece at a Shoreditch-Boxpark food-court.",
    "Uploading a portrait of a 2000s Paris-Station-F startup-coder — produce a 2-minute extended mini-drama at a Station-F-Halle-Freyssinet hall.",
    "Here's a sketch of a 2000s Stockholm-Spotify-HQ engineer — build a 3-minute extended cinematic short at a Spotify-Stockholm-rooftop terrace.",
    "I'm sending you a watercolor of a 2000s Helsinki-Slush-Festival founder — produce a 4-minute extended cinematic piece at a Slush-Helsinki-Messukeskus exhibition-hall.",
    "Uploading a digital portrait of a 2000s Tel-Aviv-Rothschild-Boulevard cybersecurity-coder — make a 2-minute extended mini-drama at a Rothschild-Boulevard café-terrace.",
    "Here's a portrait of a 2000s Bangalore-Whitefield-Bagmane-Tech-Park engineer — render a 3-minute extended cinematic short at a Bagmane-Tech-Park tower-lobby.",
    "I have a sketch of a 2000s Hyderabad-Hi-Tech-City coder — build a 4-minute extended cinematic piece at a Hi-Tech-City Cyberabad-overpass.",
    "Uploading a watercolor of a 2000s Beijing-Zhongguancun-Z-Park startup-founder — produce a 2-minute extended mini-drama at a Zhongguancun-Soho lobby.",
    "Here's a digital painting of a 2000s Shenzhen-Huaqiangbei-electronics-market maker — make a 3-minute extended cinematic short at a Huaqiangbei-SEG market-aisle.",
    "I'm sending you a portrait of a 2000s Hangzhou-Alibaba-Xixi-Park-coder — render a 4-minute extended cinematic piece at an Alibaba-Xixi-Park lake-walk.",
    "Uploading a sketch of a 2000s Tokyo-Roppongi-Hills startup-CEO — produce a 2-minute extended cinematic mini-drama at a Roppongi-Hills-Mori-Tower lobby.",
    "Here's a watercolor of a 2000s Tokyo-Shibuya-Bit-Valley-Cygames coder — build a 3-minute extended cinematic short at a Cygames-Shibuya hallway.",
    "I have a digital portrait of a 2000s Seoul-Gangnam-Pangyo-Tech-Valley engineer — render a 4-minute extended cinematic piece at a Pangyo-Tech-Valley plaza.",
    "Uploading a portrait of a 2000s Singapore-Block-71 startup-founder — make a 2-minute extended cinematic mini-drama at a Block-71-Ayer-Rajah café.",
    "Here's a sketch of a 2000s Sydney-Surry-Hills-Atlassian engineer — build a 3-minute extended cinematic short at an Atlassian-Sydney glass-stair.",
    "I'm sending you a watercolor of a 2010s Toronto-MaRS-Discovery-District founder — produce a 4-minute extended cinematic piece at a MaRS-Atrium.",
    "Uploading a digital portrait of a 2010s Vancouver-Yaletown-Hootsuite engineer — make a 2-minute extended mini-drama at a Yaletown-Hootsuite rooftop.",
    "Here's a portrait of a 2010s Montreal-Mile-End-Element-AI researcher — render a 3-minute extended cinematic short at a Mile-End-loft window.",
    "I have a sketch of a 2010s São-Paulo-Vila-Madalena startup-coder — build a 4-minute extended cinematic piece at a Vila-Madalena bar-rooftop.",
    "Uploading a watercolor of a 2010s Buenos-Aires-Palermo-Hollywood developer — produce a 2-minute extended cinematic mini-drama at a Palermo-Hollywood café.",
    "Here's a digital painting of a 2010s Mexico-City-Roma-Norte coder — make a 3-minute extended cinematic short at a Roma-Norte rooftop-terrace.",
    "I'm sending you a portrait of a 2010s Bogotá-Chapinero-startup founder — render a 4-minute extended cinematic piece at a Chapinero-Cra-7 café.",
    "Uploading a sketch of a 2010s Lagos-Yaba-Co-creation-Hub developer — make a 2-minute extended mini-drama at a Yaba-Co-Creation-Hub lobby.",
    "Here's a watercolor of a 2010s Nairobi-iHub-Ngong-Road developer — build a 3-minute extended cinematic short at an iHub-Ngong-Road balcony.",
    "I have a digital portrait of a 2010s Cape-Town-Woodstock-Bandwidth-Barn coder — render a 4-minute extended cinematic piece at a Woodstock-Old-Biscuit-Mill courtyard.",
    "Uploading a portrait of a 2010s Cairo-AUC-startup founder — produce a 2-minute extended cinematic mini-drama at a AUC-New-Cairo plaza.",
    "Here's a sketch of a 2010s Dubai-DIFC-Fintech-Hive coder — build a 3-minute extended cinematic short at a DIFC-Gate-Avenue food-court.",
    # ── more 1990s-2000s skater / mall-goth / nu-metal / emo subcultures (50) ──
    "Uploading a portrait of a 1990s Venice-Beach-Skate-Park kid — make a 2-minute extended cinematic mini-drama at a Venice-Beach-skate-bowl.",
    "Here's a sketch of a 1990s San-Diego-Tony-Hawk skate-park kid — build a 3-minute extended cinematic short at a Carlsbad-skate-park bowl.",
    "I'm sending you a watercolor of a 1990s Burnside-Skate-Park-Portland skater — produce a 4-minute extended cinematic piece at a Burnside-bridge-skate-bowl.",
    "Uploading a digital painting of a 1990s Brooklyn-Banks-NYC-skate kid — render a 2-minute extended mini-drama at a Brooklyn-Banks-Pier-17 ledge.",
    "Here's a portrait of a 1990s Love-Park-Philadelphia skater — make a 3-minute extended cinematic short at a Love-Park-JFK-Plaza ledge.",
    "I have a sketch of a 1990s Embarcadero-SF-EMB-skate kid — produce a 4-minute extended cinematic piece at an Embarcadero-Justin-Herman-Plaza.",
    "Uploading a watercolor of a 1990s Hubba-Hideout-SF skater — build a 2-minute extended mini-drama at a Hubba-Hideout-Embarcadero-Promenade.",
    "Here's a digital portrait of a 1990s Westside-LA-Lockwood-skate-park kid — render a 3-minute extended cinematic short at a West-LA-skate-park bowl.",
    "I'm sending you a portrait of a 1990s Texas-Houston-skate-park kid — produce a 4-minute extended cinematic piece at a Houston-Lee-and-Joe-Jamail skate-park.",
    "Uploading a sketch of a 1990s Tampa-FL-skate-park kid — make a 2-minute extended cinematic mini-drama at a Bro-Bowl-Tampa.",
    "Here's a watercolor of a 1990s Atlanta-Old-Fourth-Ward-skate-park kid — build a 3-minute extended cinematic short at a Old-Fourth-Ward-skate-park.",
    "I have a digital painting of a 1990s Mall-Goth-Hot-Topic-Hot-Topic kid — render a 4-minute extended cinematic piece at a Hot-Topic-Mall-of-America.",
    "Uploading a portrait of a 1990s Hot-Topic-Sherman-Oaks-Galleria mall-goth — produce a 2-minute extended mini-drama at a Sherman-Oaks-Galleria-Hot-Topic.",
    "Here's a sketch of a 1990s Hot-Topic-Tysons-Corner mall-goth — make a 3-minute extended cinematic short at a Tysons-Corner-Hot-Topic-storefront.",
    "I'm sending you a watercolor of a 1990s Hot-Topic-King-of-Prussia-Mall mall-goth — build a 4-minute extended cinematic piece at a King-of-Prussia-Hot-Topic-back-corner.",
    "Uploading a digital portrait of a 1990s Hot-Topic-South-Coast-Plaza mall-goth — render a 2-minute extended mini-drama at a South-Coast-Plaza-Hot-Topic.",
    "Here's a portrait of a 1990s Marilyn-Manson-tour-Worcester fan — produce a 3-minute extended cinematic short at a Worcester-Centrum-merch-line.",
    "I have a sketch of a 1990s KMFDM-tour-Cleveland fan — build a 4-minute extended cinematic piece at a Cleveland-Agora-Theatre lobby.",
    "Uploading a watercolor of a 1990s Nine-Inch-Nails-tour-LA fan — make a 2-minute extended cinematic mini-drama at the LA-Forum-merch-stand.",
    "Here's a digital painting of a 1990s Korn-tour-Detroit fan — render a 3-minute extended cinematic short at a Detroit-Cobo-Arena entrance.",
    "I'm sending you a portrait of a 1990s Limp-Bizkit-Family-Values-Tour fan — produce a 4-minute extended cinematic piece at a Family-Values-amphitheater.",
    "Uploading a sketch of a 1990s Slipknot-Ozzfest-Mansfield-Massachusetts fan — make a 2-minute extended cinematic mini-drama at a Mansfield-Tweeter-Center.",
    "Here's a watercolor of a 1990s Linkin-Park-Projekt-Revolution-Tour fan — build a 3-minute extended cinematic short at a Projekt-Revolution-amphitheater pit.",
    "I have a digital portrait of a 1990s Tool-tour-Chicago fan — render a 4-minute extended cinematic piece at a Chicago-Allstate-Arena entrance.",
    "Uploading a portrait of a 1990s System-of-a-Down-tour-Glendale fan — produce a 2-minute extended cinematic mini-drama at a Glendale-Civic-Auditorium-pit.",
    "Here's a sketch of a 1990s Deftones-tour-Sacramento fan — build a 3-minute extended cinematic short at a Sacramento-Memorial-Auditorium-pit.",
    "I'm sending you a watercolor of a 1990s Soulfly-tour-Phoenix fan — produce a 4-minute extended cinematic piece at a Phoenix-Celebrity-Theatre-pit.",
    "Uploading a digital portrait of a 2000s My-Chemical-Romance-Black-Parade-tour fan — make a 2-minute extended cinematic mini-drama at a Worcester-DCU-Center-pit.",
    "Here's a portrait of a 2000s Fall-Out-Boy-tour fan — render a 3-minute extended cinematic short at a Allstate-Arena-Chicago-pit.",
    "I have a sketch of a 2000s Panic-at-the-Disco-Las-Vegas-Pretty-Odd-tour fan — produce a 4-minute extended cinematic piece at a Las-Vegas-Hard-Rock-Cafe-pit.",
    "Uploading a watercolor of a 2000s Paramore-RIOT-tour fan — build a 2-minute extended cinematic mini-drama at a Nashville-Ryman-Auditorium-pit.",
    "Here's a digital painting of a 2000s Avenged-Sevenfold-tour fan — render a 3-minute extended cinematic short at a Huntington-Beach-amphitheater-pit.",
    "I'm sending you a portrait of a 2000s Bring-Me-the-Horizon-tour fan — produce a 4-minute extended cinematic piece at a Sheffield-O2-Academy-pit.",
    "Uploading a sketch of a 2000s Sum-41-tour fan — make a 2-minute extended cinematic mini-drama at a Toronto-Phoenix-Concert-Theatre-pit.",
    "Here's a watercolor of a 2000s Good-Charlotte-tour fan — build a 3-minute extended cinematic short at a Annapolis-Charlotte-Park-pit.",
    "I have a digital portrait of a 2000s Simple-Plan-tour fan — render a 4-minute extended cinematic piece at a Montreal-Centre-Bell-pit.",
    "Uploading a portrait of a 2000s Yellowcard-tour fan — produce a 2-minute extended cinematic mini-drama at a Jacksonville-Florida-Theater-pit.",
    "Here's a sketch of a 2000s New-Found-Glory-tour fan — make a 3-minute extended cinematic short at a Coral-Springs-amphitheater-pit.",
    "I'm sending you a watercolor of a 2000s All-Time-Low-tour fan — build a 4-minute extended cinematic piece at a Baltimore-Soundstage-pit.",
    "Uploading a digital portrait of a 2000s Rise-Against-tour fan — render a 2-minute extended cinematic mini-drama at a Chicago-Riviera-Theatre-pit.",
    "Here's a portrait of a 2000s Anti-Flag-tour fan — produce a 3-minute extended cinematic short at a Pittsburgh-Mr-Smalls-Theatre-pit.",
    "I have a sketch of a 2000s Bad-Religion-tour fan — build a 4-minute extended cinematic piece at a Hollywood-Palladium-pit.",
    "Uploading a watercolor of a 2000s NOFX-tour fan — make a 2-minute extended cinematic mini-drama at a Berkeley-924-Gilman-pit.",
    "Here's a digital painting of a 2000s Pennywise-tour fan — render a 3-minute extended cinematic short at a Hermosa-Beach-Pier-pit.",
    "I'm sending you a portrait of a 2000s Hatebreed-tour fan — produce a 4-minute extended cinematic piece at a New-Haven-Toad's-Place-pit.",
    "Uploading a sketch of a 2000s Killswitch-Engage-tour fan — make a 2-minute extended cinematic mini-drama at a Boston-Palladium-pit.",
    "Here's a watercolor of a 2000s Lamb-of-God-tour fan — build a 3-minute extended cinematic short at a Richmond-National-pit.",
    "I have a digital portrait of a 2000s Mastodon-tour fan — render a 4-minute extended cinematic piece at a Atlanta-Variety-Playhouse-pit.",
    "Uploading a portrait of a 2000s Coheed-and-Cambria-tour fan — produce a 2-minute extended cinematic mini-drama at a Chappaqua-NYC-amphitheater-pit.",
    "Here's a sketch of a 2000s Thursday-tour fan — make a 3-minute extended cinematic short at a New-Brunswick-Court-Tavern-pit.",
    # ── more Y2K (2000-2005) preppy + pop-punk + emo (50) ──
    "I'm sending you a portrait of a Y2K Abercrombie-and-Fitch-cargo-shorts preppy kid — produce a 4-minute extended cinematic piece at a Westchester-County-Country-Club-pool.",
    "Uploading a watercolor of a Y2K Hollister-flip-flops preppy kid — make a 2-minute extended cinematic mini-drama at a Newport-Beach-pier-promenade.",
    "Here's a digital painting of a Y2K Aeropostale-polo preppy kid — render a 3-minute extended cinematic short at a Garden-State-Plaza-food-court.",
    "I have a sketch of a Y2K Ralph-Lauren-Polo-Sport preppy kid — produce a 4-minute extended cinematic piece at a Greenwich-Round-Hill-Club-veranda.",
    "Uploading a portrait of a Y2K Lacoste-tennis-polo preppy kid — build a 2-minute extended cinematic mini-drama at a Forest-Hills-USTA-courts.",
    "Here's a watercolor of a Y2K Vineyard-Vines-whale-belt preppy kid — render a 3-minute extended cinematic short at a Martha's-Vineyard-Edgartown-dock.",
    "I'm sending you a digital portrait of a Y2K J-Crew-cable-knit preppy kid — produce a 4-minute extended cinematic piece at a Nantucket-Brant-Point-lighthouse.",
    "Uploading a sketch of a Y2K Brooks-Brothers-button-down preppy kid — make a 2-minute extended cinematic mini-drama at a Manhattan-Madison-Avenue-flagship.",
    "Here's a portrait of a Y2K American-Eagle-Outfitters cargo-pants preppy kid — render a 3-minute extended cinematic short at a King-of-Prussia-Mall-atrium.",
    "I have a watercolor of a Y2K Tommy-Hilfiger-flag-windbreaker preppy kid — produce a 4-minute extended cinematic piece at a Montauk-Surf-Lodge-deck.",
    "Uploading a digital painting of a Y2K Blink-182-tour fan — make a 2-minute extended cinematic mini-drama at a San-Diego-Sports-Arena-pit.",
    "Here's a sketch of a Y2K Sum-41-tour fan — render a 3-minute extended cinematic short at a Toronto-Phoenix-Concert-Theatre-pit.",
    "I'm sending you a portrait of a Y2K Simple-Plan-tour fan — produce a 4-minute extended cinematic piece at a Montreal-Metropolis-pit.",
    "Uploading a watercolor of a Y2K Good-Charlotte-tour fan — build a 2-minute extended cinematic mini-drama at a Annapolis-Rams-Head-pit.",
    "Here's a digital portrait of a Y2K Yellowcard-tour fan — render a 3-minute extended cinematic short at a Jacksonville-Florida-Theatre-pit.",
    "I have a sketch of a Y2K New-Found-Glory-tour fan — produce a 4-minute extended cinematic piece at a Coral-Springs-Cocoa-Beach-pit.",
    "Uploading a portrait of a Y2K Fall-Out-Boy-tour fan — make a 2-minute extended cinematic mini-drama at a Wilmette-Knights-of-Columbus-hall-pit.",
    "Here's a watercolor of a Y2K Panic-At-The-Disco-tour fan — render a 3-minute extended cinematic short at a Las-Vegas-House-of-Blues-pit.",
    "I'm sending you a digital painting of a Y2K My-Chemical-Romance-tour fan — produce a 4-minute extended cinematic piece at a Newark-Eyrie-pit.",
    "Uploading a sketch of a Y2K The-Used-tour fan — make a 2-minute extended cinematic mini-drama at a Salt-Lake-City-DV8-pit.",
    "Here's a portrait of a Y2K Taking-Back-Sunday-tour fan — render a 3-minute extended cinematic short at a Long-Island-Crazy-Donkey-pit.",
    "I have a watercolor of a Y2K Brand-New-tour fan — produce a 4-minute extended cinematic piece at a Levittown-Knights-of-Columbus-hall-pit.",
    "Uploading a digital portrait of a Y2K Saves-The-Day-tour fan — make a 2-minute extended cinematic mini-drama at a Princeton-Eden-Pit.",
    "Here's a sketch of a Y2K Jimmy-Eat-World-tour fan — render a 3-minute extended cinematic short at a Mesa-Marquee-Theatre-pit.",
    "I'm sending you a portrait of a Y2K Dashboard-Confessional-tour fan — produce a 4-minute extended cinematic piece at a Boca-Raton-Mizner-Park-pit.",
    "Uploading a watercolor of a Y2K Death-Cab-for-Cutie-tour fan — build a 2-minute extended cinematic mini-drama at a Bellingham-Showbox-pit.",
    "Here's a digital painting of a Y2K Weezer-Green-Album-tour fan — render a 3-minute extended cinematic short at a Hollywood-Palladium-pit.",
    "I have a sketch of a Y2K Avril-Lavigne-Sk8er-Boi tour fan — produce a 4-minute extended cinematic piece at a Napanee-Ontario-fairgrounds-pit.",
    "Uploading a portrait of a Y2K Ashlee-Simpson-Autobiography tour fan — make a 2-minute extended cinematic mini-drama at a Waco-Texas-fairgrounds-pit.",
    "Here's a watercolor of a Y2K Hilary-Duff-Metamorphosis tour fan — render a 3-minute extended cinematic short at a Houston-Toyota-Center-pit.",
    "I'm sending you a digital portrait of a Y2K Lindsay-Lohan-Speak tour fan — produce a 4-minute extended cinematic piece at a Long-Island-Westbury-Theater-pit.",
    "Uploading a sketch of a Y2K Cute-is-What-We-Aim-For tour fan — make a 2-minute extended cinematic mini-drama at a Buffalo-Town-Ballroom-pit.",
    "Here's a portrait of a Y2K Boys-Like-Girls tour fan — render a 3-minute extended cinematic short at a Andover-Massachusetts-Knights-Hall-pit.",
    "I have a watercolor of a Y2K Cobra-Starship tour fan — produce a 4-minute extended cinematic piece at a Times-Square-Roseland-Ballroom-pit.",
    "Uploading a digital painting of a Y2K All-Time-Low tour fan — make a 2-minute extended cinematic mini-drama at a Towson-Maryland-Senator-Theatre-pit.",
    "Here's a sketch of a Y2K Mayday-Parade tour fan — render a 3-minute extended cinematic short at a Tallahassee-Beta-Bar-pit.",
    "I'm sending you a portrait of a Y2K Hawthorne-Heights tour fan — produce a 4-minute extended cinematic piece at a Dayton-Newport-Music-Hall-pit.",
    "Uploading a watercolor of a Y2K Senses-Fail tour fan — build a 2-minute extended cinematic mini-drama at a Ridgewood-Birch-Hill-pit.",
    "Here's a digital portrait of a Y2K AFI-Sing-the-Sorrow tour fan — render a 3-minute extended cinematic short at a Berkeley-Greek-Theatre-pit.",
    "I have a sketch of a Y2K Thrice-tour fan — produce a 4-minute extended cinematic piece at a Costa-Mesa-Chain-Reaction-pit.",
    "Uploading a portrait of a Y2K Story-of-the-Year tour fan — make a 2-minute extended cinematic mini-drama at a St.-Louis-Mississippi-Nights-pit.",
    "Here's a watercolor of a Y2K The-Starting-Line tour fan — render a 3-minute extended cinematic short at a Churchville-Pennsylvania-Croc-Rock-pit.",
    "I'm sending you a digital painting of a Y2K Motion-City-Soundtrack tour fan — produce a 4-minute extended cinematic piece at a Minneapolis-Triple-Rock-pit.",
    "Uploading a sketch of a Y2K Plain-White-T's tour fan — make a 2-minute extended cinematic mini-drama at a Lombard-Illinois-Knights-Hall-pit.",
    "Here's a portrait of a Y2K Yellowcard-Ocean-Avenue tour fan — render a 3-minute extended cinematic short at a Atlantic-Beach-Florida-pit.",
    "I have a watercolor of a Y2K Switchfoot-Beautiful-Letdown tour fan — produce a 4-minute extended cinematic piece at a San-Diego-Soma-pit.",
    "Uploading a digital portrait of a Y2K Relient-K tour fan — make a 2-minute extended cinematic mini-drama at a Canton-Ohio-Lions-Lincoln-pit.",
    "Here's a sketch of a Y2K Anberlin-tour fan — render a 3-minute extended cinematic short at a Winter-Haven-Florida-Tigertown-pit.",
    "I'm sending you a portrait of a Y2K Underoath-tour fan — produce a 4-minute extended cinematic piece at a Tampa-Florida-State-Fairgrounds-pit.",
    "Uploading a watercolor of a Y2K Norma-Jean-tour fan — build a 2-minute extended cinematic mini-drama at a Atlanta-Masquerade-pit.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
