"""x15 cr_bilingual GRPO short briefs. Disjoint topics from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Make a 1-minute mini-drama of a Mandarin-speaking grandfather teaching his grandson tai chi in a Beijing courtyard, with Mandarin and English subtitles.",
    "I want a 45-second cinematic short of a Cantonese fishmonger preparing dim sum in Guangzhou, with Cantonese and English subtitles.",
    "Create a 30-second piece where a Hindi-speaking auto-rickshaw driver helps a tourist, with Hindi and English subtitles.",
    "Produce a 2-minute mini-drama of a Russian violinist auditioning at a Moscow conservatory, with Russian and English subtitles.",
    "Build a 45-second short of a Spanish flamenco guitarist tuning before a Sevillian show, with Spanish and English subtitles.",
    "Render a 30-second clip of an Arab calligrapher inking a wedding scroll in Damascus, with Arabic and English subtitles.",
    "Cook up a 1-minute mini-drama where a Korean grandmother teaches kimchi-making, with Korean and English subtitles.",
    "Generate a 30-second short of a French sommelier opening rare bottles for guests, with French and English subtitles.",
    "I'd like a 45-second cinematic piece of a Polish farmer harvesting rye at dawn, with Polish and German subtitles.",
    "Make a 30-second clip of a Portuguese fado singer rehearsing in Alfama, with Portuguese and English subtitles.",
    "Produce a 2-minute mini-drama about a Spanish abuela teaching her granddaughter to make churros, with Spanish and English subtitles.",
    "Build a 45-second short of a Romanian shepherd herding sheep across the Carpathians, with Romanian and Hungarian subtitles.",
    "Create a 30-second piece where a Hebrew-speaking violinist plays in a Jerusalem street, with Hebrew and Arabic subtitles.",
    "Render a 1-minute mini-drama of a Yiddish bookseller closing his Kraków shop, with Yiddish and Polish subtitles.",
    "I want a 30-second short about a Galician baker firing a stone oven in Santiago, with Galician and Spanish subtitles.",
    "Cook up a 45-second piece of a Provençal lavender farmer cutting her field, with Occitan and French subtitles.",
    "Generate a 1-minute mini-drama of an Albanian fisherman mending nets at Lake Ohrid, with Albanian and Macedonian subtitles.",
    "Make me a 30-second clip about a Latvian beekeeper checking hives in summer, with Latvian and English subtitles.",
    "Produce a 45-second short where a Bosnian Sevdah singer performs at a Sarajevo gathering, with Bosnian and English subtitles.",
    "Build a 30-second piece of a Pashtun storyteller weaving tales in Peshawar, with Pashto and Urdu subtitles.",
    "I'd like a 2-minute mini-drama of a Marathi farmer reaping cane in Maharashtra, with Marathi and Hindi subtitles.",
    "Render a 45-second clip of a Punjabi bhangra dancer rehearsing in a Lahore courtyard, with Punjabi and Urdu subtitles.",
    "Create a 30-second piece where a Gujarati merchant counts coins in a Surat shop, with Gujarati and English subtitles.",
    "Make a 1-minute mini-drama about a Kannada potter shaping clay in Mysuru, with Kannada and English subtitles.",
    "Cook up a 45-second short of a Telugu rice farmer threshing at harvest, with Telugu and English subtitles.",
    "Generate a 30-second clip of a Malayalam fisherman casting nets at a Kerala backwater, with Malayalam and English subtitles.",
    "I want a 1-minute mini-drama of an Odia weaver tying ikat threads in Bhubaneswar, with Odia and English subtitles.",
    "Make me a 30-second short about a Bengali rickshaw artist painting a panel in Kolkata, with Bengali and English subtitles.",
    "Produce a 45-second piece where a Sinhalese herbalist sells ayurvedic powders in Colombo, with Sinhalese and Tamil subtitles.",
    "Build a 30-second cinematic clip of a Mongolian throat singer performing on the steppe, with Mongolian and Russian subtitles.",
    "Create a 1-minute mini-drama of a Tibetan grandmother lighting butter lamps in Lhasa, with Tibetan and Mandarin subtitles.",
    "Render a 30-second clip of a Bhutanese archer practicing in Thimphu, with Dzongkha and Hindi subtitles.",
    "I'd like a 45-second short of a Karen weaver coloring threads in a Burmese village, with Karen and Burmese subtitles.",
    "Cook up a 1-minute mini-drama of a Hmong embroiderer stitching motifs in Sapa, with Hmong and Vietnamese subtitles.",
    "Make a 30-second piece where a Cebuano fisherman repairs a banca in the Visayas, with Cebuano and English subtitles.",
    "Generate a 45-second cinematic clip of an Ilocano farmer harvesting tobacco at dawn, with Ilocano and Tagalog subtitles.",
    "Produce a 30-second short of a Javanese gamelan player rehearsing in Yogyakarta, with Javanese and Indonesian subtitles.",
    "Build a 1-minute mini-drama about a Sundanese rice farmer planting paddy seedlings, with Sundanese and Indonesian subtitles.",
    "Create a 45-second piece where a Balinese mask-carver finishes a topeng for a temple, with Balinese and Indonesian subtitles.",
    "I want a 30-second cinematic short of a Tongan fisherman casting his net at sunrise, with Tongan and English subtitles.",
    "Render a 1-minute mini-drama of a Samoan grandmother weaving a fala mat, with Samoan and English subtitles.",
    "Make me a 30-second short about a Fijian farmer harvesting yaqona, with Fijian and English subtitles.",
    "Cook up a 45-second piece of a Maori carver finishing a wharenui pou, with Maori and English subtitles.",
    "Produce a 30-second clip of a Tahitian dancer rehearsing ote'a in Papeete, with Tahitian and French subtitles.",
    "Build a 1-minute mini-drama of a Hawaiian taro farmer working a Waipi'o lo'i, with Hawaiian and English subtitles.",
    "Generate a 45-second cinematic piece about a Yupik hunter checking ice fishing lines, with Yupik and English subtitles.",
    "I'd like a 30-second short of a Cree elder telling stories around a fire in Saskatchewan, with Cree and English subtitles.",
    "Create a 1-minute mini-drama of an Inuktitut grandmother sewing skin boots, with Inuktitut and English subtitles.",
    "Render a 45-second clip of an Ojibwe rice harvester gathering wild rice, with Ojibwe and English subtitles.",
    "I want a 30-second cinematic piece of a Navajo silversmith finishing a turquoise ring, with Navajo and English subtitles.",
    "Make a 45-second short where a Lakota grandmother braids her granddaughter's hair, with Lakota and English subtitles.",
    "Cook up a 30-second piece of a Nahuatl-speaking grandmother making tlacoyos in Puebla, with Nahuatl and Spanish subtitles.",
    "Produce a 1-minute mini-drama about a Mapuche elder teaching weaving in Patagonia, with Mapudungun and Spanish subtitles.",
    "Build a 45-second clip of an Aymara herder leading llamas across the altiplano, with Aymara and Spanish subtitles.",
    "Create a 30-second cinematic short of a Guaraní fisherman casting his net in the Iguazú, with Guaraní and Portuguese subtitles.",
    "Render a 1-minute mini-drama of a Garifuna drummer teaching his nephew rhythms, with Garifuna and Spanish subtitles.",
    "Generate a 45-second short of a Haitian Kreyòl baker firing a stone oven, with Haitian Kreyòl and French subtitles.",
    "I'd like a 30-second piece of a Jamaican Patois fisherman mending nets in Negril, with Jamaican Patois and English subtitles.",
    "Make me a 1-minute mini-drama of an Afrikaans winemaker pruning vines in Stellenbosch, with Afrikaans and English subtitles.",
    "Produce a 30-second cinematic short of a Shona drummer rehearsing in a Harare courtyard, with Shona and English subtitles.",
    "Build a 45-second short of a Sotho grandmother braiding her granddaughter's hair, with Sotho and English subtitles.",
    "I want a 30-second piece of a Tswana herder counting cattle on the Kalahari edge, with Tswana and English subtitles.",
    "Cook up a 1-minute mini-drama about a Swahili coast fisherman teaching his son to read tides, with Swahili and Arabic subtitles.",
    "Render a 30-second clip of an Oromo coffee farmer harvesting cherries in Sidamo, with Oromo and Amharic subtitles.",
    "Generate a 45-second cinematic piece of a Wolof tailor cutting boubou cloth in Saint-Louis, with Wolof and French subtitles.",
    "Make a 30-second short where a Bambara griot tells stories in Bamako, with Bambara and French subtitles.",
    "Produce a 1-minute mini-drama of a Mande blacksmith forging a hoe in Mopti, with Mandinka and French subtitles.",
    "I'd like a 45-second short of a Malagasy farmer harvesting vanilla beans on Sambava, with Malagasy and French subtitles.",
    "Build a 30-second clip of a Kinyarwanda grandmother teaching her granddaughter to weave agaseke, with Kinyarwanda and English subtitles.",
    "Create a 1-minute mini-drama about a Lingala dock worker loading riverboats in Kinshasa, with Lingala and French subtitles.",
    "Render a 30-second cinematic piece of a Kongo dancer rehearsing in a Brazzaville courtyard, with Kikongo and French subtitles.",
    "I want a 45-second short of a Bemba copper miner returning home in Kitwe, with Bemba and English subtitles.",
    "Cook up a 30-second clip of a Chichewa grandmother braiding cassava leaves in Lilongwe, with Chichewa and English subtitles.",
    "Generate a 1-minute mini-drama of a Tigré camel herder crossing the Eritrean coast, with Tigré and Arabic subtitles.",
    # ── more bilingual cinematic mini-dramas (50) ─────────────────────────
    "Make me a 1-minute mini-drama of a Persian poet reciting verse on an Isfahan rooftop at sunrise, with Persian and Arabic subtitles.",
    "I want a 45-second cinematic short of a Pashto storyteller telling tales to children in Peshawar, with Pashto and Urdu subtitles.",
    "Create a 30-second piece where a Hazaragi grandmother shows her granddaughter how to bake naan in Bamiyan, with Hazaragi and Persian subtitles.",
    "Produce a 2-minute mini-drama of a Balochi fisherman teaching his son to mend nets at Gwadar, with Balochi and Urdu subtitles.",
    "Build a 45-second short of a Sindhi musician playing the Yaktaro at Hyderabad, with Sindhi and Urdu subtitles.",
    "Render a 30-second cinematic clip of a Saraiki potter shaping clay in Multan, with Saraiki and Urdu subtitles.",
    "Cook up a 1-minute mini-drama where a Kashmiri shawl-weaver pulls threads in a Srinagar workshop, with Kashmiri and Hindi subtitles.",
    "Generate a 30-second short of a Dogri grandmother weaving a basket in Jammu, with Dogri and Hindi subtitles.",
    "I'd like a 45-second cinematic piece of a Garhwali shepherd trekking across a high meadow in Uttarakhand, with Garhwali and Hindi subtitles.",
    "Make a 30-second clip of a Kumaoni woman lighting an aarti at a Naina-Devi temple, with Kumaoni and Hindi subtitles.",
    "Produce a 2-minute mini-drama about a Tulu fisherman casting nets at a Mangalore harbor, with Tulu and Kannada subtitles.",
    "Build a 45-second short of a Konkani priest preparing sannas in a Goa kitchen, with Konkani and Portuguese subtitles.",
    "Create a 30-second piece where a Santali grandmother teaches her granddaughter to weave a kanthikia, with Santali and Bengali subtitles.",
    "Render a 1-minute mini-drama of a Mundari grandfather carving a flute by lamplight, with Mundari and Hindi subtitles.",
    "I want a 30-second cinematic short of a Bodo grandmother weaving a dokhona, with Bodo and Assamese subtitles.",
    "Cook up a 45-second piece of a Manipuri grandmother teaching her granddaughter Ras Lila steps, with Manipuri and Hindi subtitles.",
    "Generate a 1-minute mini-drama of a Mizo grandfather playing the rawchhem flute, with Mizo and English subtitles.",
    "Make me a 30-second clip about a Khasi grandmother brushing rice husks at a Cherrapunji house, with Khasi and English subtitles.",
    "Produce a 45-second short where a Nagamese grandfather teaches his grandson to make zutho, with Nagamese and English subtitles.",
    "Build a 30-second cinematic clip of a Garhwali horseman crossing a Yamuna ford, with Garhwali and Hindi subtitles.",
    "Create a 1-minute mini-drama of a Bhojpuri grandmother teaching her granddaughter to play dhol, with Bhojpuri and Hindi subtitles.",
    "Render a 30-second clip of an Awadhi grandfather teaching his grandson to play a Kathak step, with Awadhi and Hindi subtitles.",
    "I'd like a 45-second short of a Maithili grandmother teaching her granddaughter to make pukauns, with Maithili and Hindi subtitles.",
    "Cook up a 1-minute mini-drama of a Magahi grandfather teaching his grandson to play Bhojpuri folk-songs, with Magahi and Hindi subtitles.",
    "Make a 30-second piece where a Sambalpuri weaver teaches her daughter ikat patterns, with Odia and Hindi subtitles.",
    "Generate a 45-second cinematic clip of a Cuttacki silver-filigree maker shaping a piece, with Odia and English subtitles.",
    "Produce a 30-second short of a Mundari healer preparing herbs in a Jharkhand grove, with Mundari and Hindi subtitles.",
    "Build a 1-minute mini-drama about a Kurukh grandfather teaching his grandson to play the mandar drum, with Kurukh and Hindi subtitles.",
    "Create a 45-second piece where a Saora woman paints a Saora-icon on a wall, with Saora and Odia subtitles.",
    "I want a 30-second cinematic short of a Toda woman embroidering a mantle in the Nilgiris, with Toda and Tamil subtitles.",
    "Render a 1-minute mini-drama of a Kota musician playing a Kobu flute, with Kota and Tamil subtitles.",
    "Make me a 30-second short about a Badaga grandmother making millet porridge, with Badaga and Tamil subtitles.",
    "Cook up a 45-second piece of a Yerukala grandfather teaching his grandson to weave a basket, with Yerukala and Telugu subtitles.",
    "Generate a 30-second clip of a Lambadi woman embroidering a mirror-skirt, with Lambadi and Telugu subtitles.",
    "Produce a 1-minute mini-drama of a Soliga elder teaching his grandson honey-collecting in Karnataka, with Soliga and Kannada subtitles.",
    "Build a 45-second cinematic piece about a Dongria-Kondh grandmother dancing on a Niyamgiri hill, with Dongria-Kondh and Odia subtitles.",
    "I'd like a 30-second short of a Bhili woman weaving on a Madhya-Pradesh loom, with Bhili and Hindi subtitles.",
    "Cook up a 1-minute mini-drama of a Gondi grandfather teaching his grandson to play a dhol, with Gondi and Hindi subtitles.",
    "Make a 30-second piece where a Halbi woman demonstrates a Ganaur dance, with Halbi and Hindi subtitles.",
    "Generate a 45-second cinematic clip of a Korku grandmother making mahua cakes, with Korku and Marathi subtitles.",
    "Produce a 30-second short of a Pardhan-Gond bard playing a Bana fiddle, with Pardhan-Gond and Hindi subtitles.",
    "Build a 1-minute mini-drama about a Bhuiya grandfather teaching his grandson to play a flute, with Bhuiya and Odia subtitles.",
    "Create a 45-second piece where a Khasi grandmother brushes betel-leaves at a Shillong stall, with Khasi and English subtitles.",
    "I want a 30-second cinematic short of a Nyishi grandfather teaching his grandson archery in Arunachal, with Nyishi and English subtitles.",
    "Render a 1-minute mini-drama of an Adi grandmother teaching her granddaughter to weave a galuk, with Adi and English subtitles.",
    "Make me a 30-second short about a Galo grandfather teaching his grandson to forge a dao, with Galo and English subtitles.",
    "Cook up a 45-second piece of an Apatani grandmother teaching her granddaughter to rear a pig, with Apatani and English subtitles.",
    "Generate a 30-second clip of an Idu-Mishmi grandfather teaching his grandson to play a tata flute, with Idu-Mishmi and English subtitles.",
    "Produce a 1-minute mini-drama of a Singpho grandmother teaching her granddaughter Singpho weaving, with Singpho and English subtitles.",
    "Build a 45-second cinematic piece about a Tangkhul grandfather teaching his grandson to play a Yangkahui, with Tangkhul and English subtitles.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
