"""x15 cr_music_ambience GRPO short briefs. Disjoint topics from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Make a 1-minute mini-drama of a young whaling-station archivist walking the rusted Grytviken floor, with mournful brass score and decaying-station ambient (wind through metal, distant gulls).",
    "I want a 45-second cinematic short of a young restorer cleaning a Pompeii fresco, with Roman-lyre score and Pompeii-villa ambient (echoing footfalls, distant generator).",
    "Create a 30-second piece where a young heritage curator unlocks Versailles' Hall of Mirrors at dawn, with classical-strings score and Versailles ambient (footstep echoes, distant clocks).",
    "Produce a 2-minute mini-drama about a young geologist hammering samples in a Faroese cliff cave, with Nordic-fiddle score and sea-cave ambient (lapping water, gull cries).",
    "Build a 45-second short of a young volunteer pruning vines in a Tuscan vineyard at dawn, with Tuscan-mandolin score and vineyard-dawn ambient (distant rooster, cicadas).",
    "Render a 30-second cinematic clip of a young diver descending past coral into a Yucatán cenote chamber, with synth-pad score and cenote ambient (regulator bubbles, cave echoes).",
    "Cook up a 1-minute mini-drama where a young researcher tends instruments in a McMurdo Antarctic lab, with minimalist piano score and McMurdo-lab ambient (HVAC hum, distant generator).",
    "Generate a 30-second short of a young diplomat preparing remarks in an embassy reading room, with classical-strings score and embassy ambient (clock tick, distant chatter).",
    "I'd like a 45-second cinematic piece of a young keeper polishing brass in a Norwegian lighthouse, with Norwegian-fiddle score and lighthouse-interior ambient (lamp hum, waves).",
    "Make a 30-second clip of a young Tibetan monk sweeping a monastery courtyard at dawn, with singing-bowl-and-flute score and Tibetan-monastery ambient (horns, distant chants).",
    "Produce a 2-minute mini-drama about a young judge entering chambers before a high-profile trial, with low-strings score and chambers ambient (clock tick, footsteps, page rustle).",
    "Build a 45-second short of a young Carmelite nun walking a cloister at dawn, with chant score and cloister ambient (footstep echoes, distant bell, breeze).",
    "Create a 30-second piece where a young Sufi practitioner whirls in a quiet courtyard, with ney-and-drum score and tekke ambient (footfalls, courtyard drips).",
    "Render a 1-minute mini-drama of a young coal-yard worker tending a fire in winter, with mournful-violin score and coal-yard ambient (shovel scrape, distant train, fire roar).",
    "I want a 30-second cinematic short of a young winery worker turning barrels in a cool cellar, with French-fiddle score and wine-cellar ambient (drips, barrel creaks).",
    "Cook up a 45-second piece of a young textile-mill manager doing morning rounds, with industrial-percussion score and textile-floor ambient (loom thumps, fan hum).",
    "Generate a 1-minute mini-drama of a young paper-mill control-room engineer monitoring rolls, with electronic-score and paper-mill-control ambient (servo whirs, fan hum).",
    "Make me a 30-second clip about a young technician inside a wind-farm gearbox housing, with synth-orchestral score and turbine-housing ambient (gear whir, blade whoosh).",
    "Produce a 45-second short where a young engineer monitors a hydroelectric-dam turbine room, with deep-orchestral score and turbine-room ambient (deep rumble, water drone).",
    "Build a 30-second piece of a young night-shift operator in a Houston petrochemical control room, with electronic-pulse score and petrochemical-control ambient (HVAC hum, alarm pings).",
    "I'd like a 2-minute mini-drama of a young engineer servicing an Alaska pipeline pumping station, with mournful-strings score and pumping-station ambient (pump rumble, wind).",
    "Render a 45-second clip of a young dock worker washing nets at a Gloucester pier at dusk, with Celtic-fiddle score and fishing-port ambient (gull cries, hose hiss).",
    "Create a 30-second piece where a young coal miner ascends a cage at shift end, with low-brass score and coal-mine ambient (cable creaks, distant ventilation, dripping water).",
    "Make a 1-minute mini-drama about a young grain-silo worker monitoring a corn dryer, with folk-banjo score and grain-silo ambient (blower roar, distant trucks).",
    "Cook up a 45-second short of a young cargo-ship engineer below decks at midnight, with low-orchestral score and engine-room ambient (deep diesel rumble, valve hiss).",
    "Generate a 30-second clip of a young brick-kiln worker stacking fired bricks at dawn, with Eastern-European-fiddle score and brick-yard ambient (kiln roar, brick clinks).",
    "I want a 1-minute mini-drama of a young tannery worker rinsing leather in a vat, with industrial-pulse score and tannery ambient (water sluicing, distant motor).",
    "Make me a 30-second short about a young deep-sea submersible engineer mid-descent, with synth-orchestral score and submersible ambient (HVAC hum, instrument beeps).",
    "Produce a 45-second piece where a young aquarist feeds penguins at a polar display, with light-string score and polar-aquarium ambient (penguin calls, water splash).",
    "Build a 30-second cinematic clip of a young diver mapping a coral wall on a Coral-Sea liveaboard, with synth-pad score and coral-wall ambient (regulator bubbles, water swirl).",
    "Create a 1-minute mini-drama of a young researcher walking out of a polar-station hut at dawn, with sparse piano score and polar-station ambient (wind, generator).",
    "Render a 30-second clip of a young polar diver suiting up at an ice hole, with sparse-strings score and polar-ice-hole ambient (wind, ice creaks, dive-tender chatter).",
    "I'd like a 45-second short of a young biologist tagging a seal pup at a polar field site, with delicate piano score and field-site ambient (wind, distant seal calls).",
    "Cook up a 1-minute mini-drama of a young Inuit hunter checking a frozen-bay fishing hole, with Inuit-throat-singing score and frozen-bay ambient (wind, distant huskies).",
    "Make a 30-second piece where a young researcher reads data in a polar-station mess hall, with quiet piano score and polar-mess ambient (HVAC hum, distant chatter).",
    "Generate a 45-second cinematic clip of a young volunteer feeding sled dogs at a polar kennel, with folk-fiddle score and polar-kennel ambient (dog barks, wind).",
    "Produce a 30-second short of a young geologist calibrating instruments in a McMurdo lab, with sparse-piano score and McMurdo-lab ambient (HVAC hum, fan whirr).",
    "Build a 1-minute mini-drama about a young historian unrolling a manuscript in a Vatican archive, with Renaissance-lute score and Vatican-archive ambient (page rustle, footsteps).",
    "Create a 45-second piece where a young restorer cleans Angkor Wat bas-relief, with Cambodian-flute score and Angkor-Wat ambient (distant chants, monkey calls).",
    "I want a 30-second cinematic short of a young heritage volunteer cataloging items in a Devonshire abbey, with chant score and Devon-abbey ambient (clock chime, drips).",
    "Render a 1-minute mini-drama of a young pilot inside an Arctic helicopter at idle, with synth-orchestral score and Arctic-helicopter ambient (rotor wash, intercom static).",
    "Make me a 30-second short about a young researcher walking the frozen Lake Vostok at dusk, with sparse-strings score and frozen-lake ambient (wind, ice creaks).",
    "Cook up a 45-second piece of a young weather observer inside an Antarctic weather station, with sparse-piano score and Antarctic-weather-station ambient (wind, anemometer click).",
    "Produce a 30-second clip of a young fire-lookout volunteer scanning a forest from her tower at sunset, with Americana-folk score and fire-tower ambient (wind, ravens).",
    "Build a 1-minute mini-drama of a young keeper inside a remote Scottish lighthouse, with Hebridean-fiddle score and Scottish-lighthouse-interior ambient (wind, waves).",
    "Generate a 45-second cinematic piece about a young researcher inside a Greenland weather hut at 3 AM, with sparse-piano score and Greenland-hut ambient (wind, fluorescent buzz).",
    "I'd like a 30-second short of a young lookout descending a fire-tower stair at dawn, with folk-violin score and fire-tower-stair ambient (wind, footstep clangs).",
    "Make a 1-minute mini-drama of a young volunteer reading sensors at a remote alpine weather station, with Alpine-fiddle score and weather-station ambient (wind, anemometer).",
    "Cook up a 45-second short of a young soldier in a WWI trench writing home by candlelight, with mournful-violin score and trench ambient (artillery, mud-shifts, faint rain).",
    "Generate a 30-second clip of a young coder in a 1940s Bletchley hut decoding intercepts, with classical-piano score and Bletchley-hut ambient (typewriter clatters, fan whirr).",
    "Produce a 1-minute mini-drama of a young pilot reading a map in a 1944 cockpit at dawn, with hopeful brass score and vintage-cockpit ambient (engine drone, intercom static).",
    "Build a 45-second piece about a young Resistance courier hiding in a 1944 Paris cellar, with tense-strings score and Paris-cellar ambient (distant footsteps, Nazi-radio static).",
    "Create a 30-second cinematic short of a young Cold-War radar operator in a 1960s NORAD bunker, with electronic-pulse score and NORAD-bunker ambient (radar pings, fan whirr).",
    "Render a 1-minute mini-drama of a young radio operator inside a vintage WWII destroyer cabin, with low-strings score and destroyer-cabin ambient (engine drone, distant Morse).",
    "I want a 30-second short of a young Vietnam-era nurse inside a triage tent, with mournful-strings score and triage-tent ambient (helicopter rotor, IV-drip clicks).",
    "Cook up a 45-second piece of a young Cold-War analyst alone in a Pentagon SCIF at 4 AM, with electronic-drone score and SCIF ambient (HVAC hum, fluorescent buzz, fan whirr).",
    "Make a 30-second cinematic clip of a young dirigible navigator setting course over a steam-powered London, with brass-and-strings steampunk score and dirigible-deck ambient (engine, wind).",
    "Generate a 1-minute mini-drama of a young inventor activating a brass-and-glass time-machine prototype, with clockwork-orchestra score and Victorian-workshop ambient (gears, distant clock).",
    "Produce a 45-second short where a young engineer cranks a brass-and-copper airship engine, with steampunk-orchestral score and airship-deck ambient (boilers, distant wind).",
    "Build a 30-second piece of a young watchmaker assembling a clockwork bird, with music-box score and Victorian-workshop ambient (gear ticks, distant rain).",
    "I'd like a 2-minute mini-drama of a young captain piloting a brass dirigible through alpine clouds, with steampunk-pipe-organ score and dirigible ambient (engine, wind, distant chimes).",
    "Make me a 30-second short about a young inventor lighting a Tesla coil in her London workshop, with electronic-and-brass score and workshop ambient (electric arcs, distant rain).",
    "Cook up a 45-second clip of a young dirigible navigator setting course over Victorian London, with steampunk-strings score and London-aerial ambient (wind, distant Big-Ben chime).",
    "Generate a 1-minute mini-drama of a young swordswoman walking a bamboo-grove path at dusk, with erhu-and-pipa score and bamboo-grove ambient (wind through bamboo, distant birds).",
    "Produce a 30-second cinematic clip of a young kung-fu student practicing forms on a temple roof at dawn, with erhu score and temple-roof ambient (wind, distant chants, distant bells).",
    "Build a 45-second short of a young master pouring tea for a visiting student, with guzheng-and-erhu score and Chinese tea-house ambient (water in cup, distant bird).",
    "I want a 30-second cinematic piece of a young swordsman walking across a frosted moonlit lake, with erhu-and-strings score and frozen-lake ambient (ice creaks, wind).",
    "Render a 1-minute mini-drama of a young kung-fu student lighting incense for her late master, with bamboo-flute score and Chinese-temple ambient (distant chimes, drips).",
    "Cook up a 45-second piece of a young swordswoman climbing a temple's stone steps at dawn, with orchestral-erhu score and temple-stair ambient (distant bell, footfalls).",
    "Make a 30-second cinematic clip of a young master practicing calligraphy under a courtyard lantern, with guzheng score and Chinese-courtyard ambient (cricket pulse, distant flute).",
    "Generate a 1-minute mini-drama of a young samurai polishing his katana in a sunlit teahouse, with shakuhachi score and Japanese-teahouse ambient (wood-floor creaks, distant koi pond).",
    "Produce a 30-second short of a young geisha tying her obi by candlelight, with shamisen score and Japanese-okiya ambient (paper-screen rustle, distant koto).",
    "Build a 45-second cinematic piece about two samurai bowing before a duel at dawn, with taiko-and-flute score and dueling-ground ambient (wind, distant cherry blossoms drifting).",
    # ── more cinematic music+ambience scenes (50) ─────────────────────────
    "Make me a 1-minute mini-drama of a young Patagonian shepherd checking his flock at dawn, with Argentine-folk-fiddle score and Patagonian-meadow ambient (wind, distant horse).",
    "I want a 45-second cinematic short of a young Galápagos researcher tagging a tortoise, with serene-cello score and Galápagos ambient (wind, distant bird calls).",
    "Create a 30-second piece of a young Bahian abuela teaching her granddaughter samba steps, with samba-batucada score and Salvador-courtyard ambient (distant traffic, distant batucada).",
    "Produce a 2-minute mini-drama about a young Italian baker firing a wood-fired oven at dawn, with Italian-mandolin score and bakery-courtyard ambient (oven roar, distant Vespa).",
    "Build a 45-second short of a young French sommelier preparing a cellar tasting at dusk, with French-musette score and cellar ambient (distant pour, footstep echoes).",
    "Render a 30-second cinematic clip of a young Spanish flamenco-girl rehearsing in a Sevillian courtyard, with flamenco-guitar score and Sevillian-courtyard ambient (handclaps, distant footfalls).",
    "Cook up a 1-minute mini-drama where a young Portuguese fado-singer rehearses on an Alfama rooftop, with fado-guitar score and Alfama-rooftop ambient (distant tram, distant breeze).",
    "Generate a 45-second short of a young Greek bouzouki-player rehearsing in a Plaka taverna, with bouzouki score and Plaka-taverna ambient (distant footfalls, distant tourist chatter).",
    "I'd like a 30-second cinematic piece of a young Turkish saz-player rehearsing in an Istanbul rooftop, with Turkish-saz score and Istanbul-rooftop ambient (distant ferry horn, distant call to prayer).",
    "Make a 30-second clip of a young Iranian santur-player practicing at a Shiraz courtyard, with Persian-santur score and Shiraz-courtyard ambient (distant water-fountain, distant tea-house chatter).",
    "Produce a 2-minute mini-drama about a young Egyptian oud-player rehearsing in an Aswan courtyard, with Egyptian-oud score and Aswan-courtyard ambient (distant Nile breeze, distant felucca).",
    "Build a 45-second short of a young Lebanese tabla-player rehearsing in a Beirut rooftop, with Lebanese-tabla score and Beirut-rooftop ambient (distant traffic, distant call to prayer).",
    "Create a 30-second piece where a young Jordanian rebab-player rehearses in a Petra courtyard, with rebab score and Petra-courtyard ambient (wind, distant breeze).",
    "Render a 1-minute mini-drama of a young Moroccan gnawa-musician rehearsing in a Marrakesh riad, with gnawa score and riad-courtyard ambient (distant souk chatter, distant breeze).",
    "I want a 30-second cinematic short of a young Algerian rai-singer rehearsing in an Oran courtyard, with rai score and Oran-courtyard ambient (distant traffic, distant breeze).",
    "Cook up a 45-second piece of a young Tunisian malouf-player rehearsing in a Sidi Bou Said courtyard, with Tunisian-malouf score and Sidi-Bou-Said ambient (distant Mediterranean wave, distant breeze).",
    "Generate a 1-minute mini-drama of a young Libyan tabl-baladi-drummer rehearsing in a Tripoli courtyard, with Libyan-tabl score and Tripoli-courtyard ambient (distant breeze, distant footfalls).",
    "Make me a 30-second clip about a young Senegalese kora-player rehearsing in a Dakar courtyard, with Senegalese-kora score and Dakar-courtyard ambient (distant traffic, distant ocean).",
    "Produce a 45-second short where a young Malian balafon-player rehearses in a Bamako courtyard, with Mali-balafon score and Bamako-courtyard ambient (distant breeze, distant donkey).",
    "Build a 30-second cinematic clip of a young Ghanaian highlife-band rehearsing in an Accra courtyard, with Ghanaian-highlife score and Accra-courtyard ambient (distant traffic, distant chatter).",
    "Create a 1-minute mini-drama of a young Nigerian juju-band rehearsing in a Lagos rooftop, with Nigerian-juju score and Lagos-rooftop ambient (distant traffic, distant breeze).",
    "Render a 30-second clip of a young Cameroonian makossa-band rehearsing in a Douala courtyard, with Cameroonian-makossa score and Douala-courtyard ambient (distant traffic, distant breeze).",
    "I'd like a 45-second short of a young Congolese rumba-band rehearsing in a Kinshasa courtyard, with Congolese-rumba score and Kinshasa-courtyard ambient (distant traffic, distant Lingala chatter).",
    "Cook up a 1-minute mini-drama of a young Angolan kuduro-band rehearsing in a Luanda courtyard, with Angolan-kuduro score and Luanda-courtyard ambient (distant traffic, distant breeze).",
    "Make a 30-second piece where a young Mozambican marrabenta-band rehearses in a Maputo courtyard, with Mozambican-marrabenta score and Maputo-courtyard ambient (distant traffic, distant breeze).",
    "Generate a 45-second cinematic clip of a young Madagascan valiha-player rehearsing in an Antananarivo courtyard, with valiha score and Antananarivo-courtyard ambient (distant breeze, distant chatter).",
    "Produce a 30-second short of a young Réunionese maloya-band rehearsing in a Saint-Denis courtyard, with maloya score and Saint-Denis-courtyard ambient (distant traffic, distant breeze).",
    "Build a 1-minute mini-drama about a young Mauritian séga-band rehearsing in a Port-Louis courtyard, with séga score and Port-Louis-courtyard ambient (distant traffic, distant breeze).",
    "Create a 45-second piece where a young Comorian twarab-band rehearses in a Moroni courtyard, with Comorian-twarab score and Moroni-courtyard ambient (distant breeze, distant ocean).",
    "I want a 30-second cinematic short of a young Capeverdean morna-singer rehearsing in a Mindelo courtyard, with Cape-Verdean-morna score and Mindelo-courtyard ambient (distant traffic, distant breeze).",
    "Render a 1-minute mini-drama of a young Bissau-Guinean gumbe-band rehearsing in a Bissau courtyard, with Bissau-Guinean-gumbe score and Bissau-courtyard ambient (distant traffic, distant breeze).",
    "Make me a 30-second short about a young Guinean bolon-player rehearsing in a Conakry courtyard, with Guinean-bolon score and Conakry-courtyard ambient (distant traffic, distant breeze).",
    "Cook up a 45-second piece of a young Ivorian zouglou-band rehearsing in an Abidjan courtyard, with Ivorian-zouglou score and Abidjan-courtyard ambient (distant traffic, distant breeze).",
    "Generate a 30-second clip of a young Liberian konghoma-player rehearsing in a Monrovia courtyard, with Liberian-konghoma score and Monrovia-courtyard ambient (distant traffic, distant breeze).",
    "Produce a 1-minute mini-drama of a young Sierra-Leonean balangi-player rehearsing in a Freetown courtyard, with Sierra-Leonean-balangi score and Freetown-courtyard ambient (distant traffic, distant breeze).",
    "Build a 45-second cinematic piece about a young Togolese agbadza-band rehearsing in a Lomé courtyard, with Togolese-agbadza score and Lomé-courtyard ambient (distant traffic, distant breeze).",
    "I'd like a 30-second short of a young Beninese zinli-band rehearsing in a Cotonou courtyard, with Beninese-zinli score and Cotonou-courtyard ambient (distant traffic, distant breeze).",
    "Cook up a 1-minute mini-drama of a young Burkinabé kora-player rehearsing in an Ouagadougou courtyard, with Burkinabé-kora score and Ouagadougou-courtyard ambient (distant breeze, distant chatter).",
    "Make a 30-second piece where a young Nigerien kakaki-player rehearses in a Niamey courtyard, with Nigerien-kakaki score and Niamey-courtyard ambient (distant breeze, distant chatter).",
    "Generate a 45-second cinematic clip of a young Chadian kakaki-player rehearsing in an N'Djamena courtyard, with Chadian-kakaki score and N'Djamena-courtyard ambient (distant breeze, distant chatter).",
    "Produce a 30-second short of a young CAR ngombi-player rehearsing in a Bangui courtyard, with CAR-ngombi score and Bangui-courtyard ambient (distant breeze, distant chatter).",
    "Build a 1-minute mini-drama about a young Equatoguinean kamba-player rehearsing in a Malabo courtyard, with Equatoguinean-kamba score and Malabo-courtyard ambient (distant breeze, distant chatter).",
    "Create a 45-second piece where a young Gabonese mvet-player rehearses in a Libreville courtyard, with Gabonese-mvet score and Libreville-courtyard ambient (distant breeze, distant chatter).",
    "I want a 30-second cinematic short of a young Sao-Toméan lundum-band rehearsing in a São-Tomé courtyard, with São-Toméan-lundum score and São-Tomé-courtyard ambient (distant breeze, distant chatter).",
    "Render a 1-minute mini-drama of a young Mauritanian tidinit-player rehearsing in a Nouakchott courtyard, with Mauritanian-tidinit score and Nouakchott-courtyard ambient (distant breeze, distant chatter).",
    "Make me a 30-second short about a young Sahrawi haul-player rehearsing in a Western-Saharan camp, with Sahrawi-haul score and Sahrawi-camp ambient (wind, distant camel).",
    "Cook up a 45-second piece of a young Sudanese tambour-player rehearsing in a Khartoum courtyard, with Sudanese-tambour score and Khartoum-courtyard ambient (distant breeze, distant chatter).",
    "Generate a 30-second clip of a young South-Sudanese thom-player rehearsing in a Juba courtyard, with South-Sudanese-thom score and Juba-courtyard ambient (distant breeze, distant chatter).",
    "Produce a 1-minute mini-drama of a young Eritrean krar-player rehearsing in an Asmara courtyard, with Eritrean-krar score and Asmara-courtyard ambient (distant breeze, distant chatter).",
    "Build a 45-second cinematic piece about a young Djiboutian tanbura-player rehearsing in a Djibouti courtyard, with Djiboutian-tanbura score and Djibouti-courtyard ambient (distant breeze, distant chatter).",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
