"""x15 story_music_bilingual GRPO. Disjoint from SFT pool."""
from __future__ import annotations

USER_GOALS: list[str] = [
    "Tell me a children's audiobook in Catalan about a young rabbit, with Catalan-cobla BGM and Spanish subtitles.",
    "I want an illustrated audiobook in Galician about a young albatross, with Galician-folk BGM and Spanish subtitles.",
    "Make me a bedtime audiobook in Basque about a young eagle, with Basque-trikitixa BGM and Spanish subtitles.",
    "Create a picture-book audiobook in Welsh about a young dragon, with Welsh-folk BGM and English subtitles.",
    "Produce an illustrated children's tale in Irish-Gaelic about a young selkie, with Irish-fiddle BGM and English subtitles.",
    "Generate a kids' audiobook in Scottish-Gaelic about a young Highland cow, with bagpipe BGM and English subtitles.",
    "Build a narrated picture-book in Manx about a young sheepdog, with Manx-folk BGM and English subtitles.",
    "Render a children's audiobook in Cornish about a young pisky, with Cornish-folk BGM and English subtitles.",
    "I'd like a bedtime audiobook in Breton about a young salmon, with Breton-bombarde BGM and French subtitles.",
    "Tell me a children's audiobook in Frisian about a young swan, with Frisian-folk BGM and Dutch subtitles.",
    "Make a soft picture-book audiobook in Luxembourgish about a young hedgehog, with Luxembourgish-folk BGM and German subtitles.",
    "Cook up a children's audiobook in Maltese about a young tuna, with Maltese-folk BGM and English subtitles.",
    "Generate a narrated picture-book in Romansh about a young marmot, with Swiss-zither BGM and German subtitles.",
    "Produce a children's audiobook in Sardinian about a young flamingo, with Sardinian-launeddas BGM and Italian subtitles.",
    "Build a bedtime audiobook in Sicilian about a young dolphin, with Sicilian-folk BGM and Italian subtitles.",
    "Tell me an illustrated children's audiobook in Sami about a young reindeer, with Sami-yoik BGM and Norwegian subtitles.",
    "Make me a picture-book audiobook in Faroese about a young puffin, with Faroese-folk BGM and Danish subtitles.",
    "Cook up a narrated children's audiobook in Greenlandic about a young polar bear, with Inuit-throat-singing BGM and Danish subtitles.",
    "Generate a children's bedtime audiobook in Inuktitut about a young narwhal, with Inuit-throat-singing BGM and French subtitles.",
    "Produce a kids' picture-book audiobook in Cree about a young moose, with Cree-flute BGM and French subtitles.",
    "Build an illustrated children's audiobook in Ojibwe about a young loon, with Ojibwe-flute BGM and English subtitles.",
    "Tell me a children's audiobook in Navajo about a young coyote pup, with Navajo-flute BGM and English subtitles.",
    "Make a narrated picture-book audiobook in Lakota about a young bison calf, with Lakota-flute BGM and English subtitles.",
    "Render a children's audiobook in Cherokee about a young river otter, with Cherokee-flute BGM and English subtitles.",
    "I'd like a bedtime audiobook in Apache about a young desert hare, with Apache-flute BGM and English subtitles.",
    "Cook up a children's audiobook in Hopi about a young roadrunner, with Hopi-rattle BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Zuni about a young prairie dog, with Pueblo-drum BGM and English subtitles.",
    "Produce a narrated children's audiobook in Tongan about a young sea-turtle, with Tongan-lali BGM and English subtitles.",
    "Build a bedtime audiobook in Samoan about a young flying fox, with Samoan-pate BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Fijian about a young iguana, with Fijian-folk BGM and English subtitles.",
    "Make me a picture-book audiobook in Tahitian about a young dolphin, with Tahitian-pahu BGM and French subtitles.",
    "Cook up a narrated children's audiobook in Hawaiian about a young monk seal, with Hawaiian-ipu-heke BGM and English subtitles.",
    "Generate a children's bedtime audiobook in Maori about a young kiwi, with taonga-pūoro BGM and English subtitles.",
    "Produce a kids' picture-book audiobook in Yupik about a young walrus, with Yupik-drum BGM and English subtitles.",
    "Build an illustrated children's audiobook in Inupiat about a young snow owl, with Inupiat-throat-singing BGM and English subtitles.",
    # ── more illustrated children's audiobooks with BGM and bilingual subtitles (50)
    "Tell me a children's audiobook in Macedonian about a young olive-grove finch, with Macedonian-zurla BGM and Albanian subtitles.",
    "Make me an illustrated audiobook in Moldovan about a young steppe stork, with Moldovan-țambal BGM and Romanian subtitles.",
    "Cook up a bedtime audiobook in Ladino about a young old-port donkey, with Ladino-folk BGM and Spanish subtitles.",
    "Generate a kids' picture-book audiobook in Yiddish about a young shtetl mouse, with Klezmer BGM and English subtitles.",
    "Produce a children's audiobook in Aramaic about a young marketplace lamb, with Aramaic-chant BGM and Arabic subtitles.",
    "Build a narrated picture-book audiobook in Coptic about a young Nile lotus turtle, with Coptic-chant BGM and Arabic subtitles.",
    "Render a children's audiobook in Berber about a young oasis fennec, with Berber-bendir BGM and Arabic subtitles.",
    "I'd like a bedtime audiobook in Tuareg about a young Sahara dune fox, with Tuareg-tinde BGM and French subtitles.",
    "Tell me a children's audiobook in Bambara about a young Niger-River hippo, with Bambara-kora BGM and French subtitles.",
    "Make a picture-book audiobook in Mandinka about a young Senegal-River otter, with Mandinka-kora BGM and French subtitles.",
    "Cook up a children's audiobook in Lingala about a young Congo-forest okapi, with Lingala-rumba BGM and French subtitles.",
    "Generate a narrated picture-book in Kikongo about a young jungle bonobo, with Kikongo-mbiyo BGM and French subtitles.",
    "Produce a children's audiobook in Bemba about a young copperbelt elephant, with Bemba-kalimba BGM and English subtitles.",
    "Build a bedtime audiobook in Chichewa about a young Lake-Malawi cichlid, with Chichewa-malipenga BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Shona about a young Zimbabwe sable, with Shona-mbira BGM and English subtitles.",
    "Make me a picture-book audiobook in Sotho about a young Drakensberg lammergeier, with Sotho-lekolulo BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Tswana about a young Kalahari oryx, with Tswana-segaba BGM and Afrikaans subtitles.",
    "Generate a children's bedtime audiobook in Ndebele about a young Matabeleland kudu, with Ndebele-iimbongi BGM and English subtitles.",
    "Produce a kids' picture-book audiobook in Afrikaans about a young Cape penguin, with Afrikaans-boeremusiek BGM and English subtitles.",
    "Build an illustrated children's audiobook in Tigrinya about a young Eritrean-coffee chick, with Tigrinya-krar BGM and English subtitles.",
    "Tell me a children's audiobook in Somali about a young Horn-of-Africa cheetah cub, with Somali-tambour BGM and Arabic subtitles.",
    "Make a narrated picture-book audiobook in Oromo about a young Ethiopian-highlands ibex, with Oromo-masenqo BGM and Amharic subtitles.",
    "Render a children's audiobook in Hausa about a young Sahel cobra, with Hausa-kakaki BGM and Arabic subtitles.",
    "I'd like a bedtime audiobook in Igbo about a young Niger-Delta turtle, with Igbo-percussion BGM and English subtitles.",
    "Cook up a children's audiobook in Twi about a young Ashanti golden cat, with Akan-fontomfrom BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Ewe about a young West-African jerboa, with Ewe-drum BGM and French subtitles.",
    "Produce a narrated children's audiobook in Kinyarwanda about a young Rwandan mountain-gorilla, with Rwandan-inanga BGM and English subtitles.",
    "Build a bedtime audiobook in Luganda about a young Lake-Victoria fish, with Luganda-akogo BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Kikuyu about a young Mount-Kenya colobus, with Kikuyu-mwomboko BGM and Swahili subtitles.",
    "Make me a picture-book audiobook in Maa about a young Maasai-Mara lion cub, with Maasai-chant BGM and Swahili subtitles.",
    "Cook up a narrated children's audiobook in Kannada about a young Western-Ghats elephant calf, with Kannada-folk BGM and English subtitles.",
    "Generate a children's bedtime audiobook in Odia about a young Chilika-Lagoon dolphin, with Odia-folk BGM and Hindi subtitles.",
    "Produce a kids' picture-book audiobook in Assamese about a young Brahmaputra river-dolphin, with Assamese-flute BGM and Bengali subtitles.",
    "Build an illustrated children's audiobook in Bhojpuri about a young Gangetic-plain peacock, with Bhojpuri-folk BGM and Hindi subtitles.",
    "Tell me a children's audiobook in Sindhi about a young Indus-river dolphin, with Sindhi-folk BGM and Urdu subtitles.",
    "Make a narrated picture-book audiobook in Karelian about a young birch-bark mouse, with Karelian-kantele BGM and Finnish subtitles.",
    "Render a children's audiobook in Veps about a young Onega-lake duck, with Veps-folk BGM and Russian subtitles.",
    "I'd like a bedtime audiobook in Komi about a young Northern-taiga reindeer, with Komi-folk BGM and Russian subtitles.",
    "Cook up a children's audiobook in Mari about a young Volga-river beaver, with Mari-folk BGM and Russian subtitles.",
    "Generate a kids' picture-book audiobook in Udmurt about a young Kama-river otter, with Udmurt-folk BGM and Russian subtitles.",
    "Produce a narrated children's audiobook in Bashkir about a young Ural sheep, with Bashkir-kurai BGM and Russian subtitles.",
    "Build a bedtime audiobook in Tatar about a young Volga-river fox, with Tatar-folk BGM and Russian subtitles.",
    "Tell me an illustrated children's audiobook in Chechen about a young Caucasus eagle, with Chechen-pondar BGM and Russian subtitles.",
    "Make me a picture-book audiobook in Ossetian about a young Caucasus mountain hare, with Ossetian-doli BGM and Russian subtitles.",
    "Cook up a narrated children's audiobook in Abkhaz about a young Black-Sea coast crab, with Abkhaz-folk BGM and Russian subtitles.",
    "Generate a children's bedtime audiobook in Chuvash about a young Volga-region wolf cub, with Chuvash-folk BGM and Russian subtitles.",
    "Produce a kids' picture-book audiobook in Yakut about a young Sakha reindeer, with Yakut-khomus BGM and Russian subtitles.",
    "Build an illustrated children's audiobook in Buryat about a young Lake-Baikal seal, with Buryat-throat-singing BGM and Russian subtitles.",
    "Tell me a children's audiobook in Kalmyk about a young Caspian-steppe saiga, with Kalmyk-folk BGM and Russian subtitles.",
    "Make a narrated picture-book audiobook in Tuvan about a young Sayan-Mountain ibex, with Tuvan-throat-singing BGM and Russian subtitles.",
    # ── more illustrated children's audiobooks with BGM and bilingual subtitles (50)
    "Tell me a children's audiobook in Nigerian-Pidgin about a young Lagos monkey, with Naija-Afrobeat BGM and English subtitles.",
    "Make me an illustrated audiobook in Krio about a young Sierra-Leone leopard, with Krio-folk BGM and English subtitles.",
    "Cook up a bedtime audiobook in Cape-Verdean-Creole about a young Cape-Verdean turtle, with Cape-Verdean-funaná BGM and Portuguese subtitles.",
    "Generate a kids' picture-book audiobook in Mauritian-Creole about a young Mauritian dodo-cousin, with sega BGM and French subtitles.",
    "Produce a children's audiobook in Seychellois-Creole about a young Aldabra tortoise, with moutya BGM and French subtitles.",
    "Build a narrated picture-book audiobook in Reunionese-Creole about a young Réunion cuckoo, with maloya BGM and French subtitles.",
    "Render a children's audiobook in Antillean-Creole about a young Martinique iguana, with bèlè BGM and French subtitles.",
    "I'd like a bedtime audiobook in Hawaiian-Pidgin about a young Hawaiian honeycreeper, with Hawaiian-slack-key BGM and English subtitles.",
    "Tell me a children's audiobook in Tok-Pisin about a young Bird-of-Paradise, with Tok-Pisin-singsing BGM and English subtitles.",
    "Make a picture-book audiobook in Hiri-Motu about a young Papuan tree-kangaroo, with PNG-folk BGM and English subtitles.",
    "Cook up a children's audiobook in Bislama about a young Vanuatu flying-fox, with Vanuatu-string-band BGM and French subtitles.",
    "Generate a narrated picture-book in Solomon-Pijin about a young Solomon cockatoo, with Solomon-pan-flute BGM and English subtitles.",
    "Produce a children's audiobook in Niuean about a young Niue coconut-crab, with Niuean-folk BGM and English subtitles.",
    "Build a bedtime audiobook in Tokelauan about a young Tokelau fairy-tern, with Tokelauan-folk BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Tuvaluan about a young Tuvalu frigatebird, with Tuvaluan-fatele BGM and English subtitles.",
    "Make me a picture-book audiobook in Kiribati about a young Kiribati turtle, with Kiribati-te-tirere BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Nauruan about a young Nauru frigatebird, with Nauruan-folk BGM and English subtitles.",
    "Generate a children's bedtime audiobook in Yapese about a young Yap fruit-bat, with Yapese-folk BGM and English subtitles.",
    "Produce a kids' picture-book audiobook in Pohnpeian about a young Pohnpei flying-fox, with Pohnpeian-folk BGM and English subtitles.",
    "Build an illustrated children's audiobook in Chamorro about a young Mariana fruit-bat, with Chamorro-folk BGM and English subtitles.",
    "Tell me a children's audiobook in Vietnamese about a young Cuc-Phuong langur, with Vietnamese-đàn-tranh BGM and English subtitles.",
    "Make a narrated picture-book audiobook in Vietnamese about a young Saola antelope, with Vietnamese-folk BGM and English subtitles.",
    "Render a children's audiobook in Korean about a young Korean magpie, with Korean-pansori BGM and English subtitles.",
    "I'd like a bedtime audiobook in Japanese about a young Hokkaido fox, with Japanese-koto BGM and English subtitles.",
    "Cook up a children's audiobook in Japanese about a young Japanese macaque, with Japanese-Bon-odori BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Mongolian about a young Mongolian gazelle, with Mongolian-throat-singing BGM and Russian subtitles.",
    "Produce a narrated children's audiobook in Kazakh about a young Kazakh saiga, with Kazakh-dombra BGM and Russian subtitles.",
    "Build a bedtime audiobook in Uyghur about a young Tian-Shan bear, with Uyghur-dutar BGM and Mandarin subtitles.",
    "Tell me an illustrated children's audiobook in Uzbek about a young Uzbek desert-lynx, with Uzbek-doira BGM and Russian subtitles.",
    "Make me a picture-book audiobook in Tajik about a young Tajik markhor, with Tajik-rubab BGM and Persian subtitles.",
    "Cook up a narrated children's audiobook in Turkmen about a young Turkmen onager, with Turkmen-dutar BGM and Persian subtitles.",
    "Generate a children's bedtime audiobook in Kyrgyz about a young Kyrgyz snow-leopard, with Kyrgyz-komuz BGM and Russian subtitles.",
    "Produce a kids' picture-book audiobook in Yakut about a young Yakut laika dog, with Yakut-khomus BGM and Russian subtitles.",
    "Build an illustrated children's audiobook in Buryat about a young Lake-Baikal omul, with Buryat-throat-singing BGM and Russian subtitles.",
    "Tell me a children's audiobook in Tibetan about a young Tibetan yak, with Tibetan-dungchen BGM and Mandarin subtitles.",
    "Make a narrated picture-book audiobook in Sherpa about a young Khumbu bharal, with Sherpa-cymbal BGM and Nepali subtitles.",
    "Render a children's audiobook in Newari about a young Newari rhesus monkey, with Newari-folk BGM and Nepali subtitles.",
    "I'd like a bedtime audiobook in Bundeli about a young Bundeli blackbuck, with Bundeli-folk BGM and Hindi subtitles.",
    "Cook up a children's audiobook in Awadhi about a young Awadhi langur, with Awadhi-folk BGM and Hindi subtitles.",
    "Generate a kids' picture-book audiobook in Marwari about a young Thar desert-fox, with Rajasthani-folk BGM and Hindi subtitles.",
    "Produce a narrated children's audiobook in Konkani about a young Goan cobra, with Konkani-mando BGM and Portuguese subtitles.",
    "Build a bedtime audiobook in Tulu about a young Tulu king-cobra, with Tulu-folk BGM and Kannada subtitles.",
    "Tell me an illustrated children's audiobook in Kodava about a young Kodagu elephant, with Kodava-folk BGM and Kannada subtitles.",
    "Make me a picture-book audiobook in Beary about a young Beary tropical fish, with Beary-folk BGM and Kannada subtitles.",
    "Cook up a narrated children's audiobook in Sanskrit about a young mythical snake, with Sanskrit-classical BGM and Hindi subtitles.",
    "Generate a children's bedtime audiobook in Pali about a young Buddhist deer, with Pali-chant BGM and English subtitles.",
    "Produce a kids' picture-book audiobook in Tibetan-Bonpo about a young Bonpo mountain goat, with Bon-chant BGM and English subtitles.",
    "Build an illustrated children's audiobook in Liberian-English about a young Liberian leopard, with Liberian-highlife BGM and English subtitles.",
    "Tell me a children's audiobook in Sango about a young Bangui okapi, with Sango-mvet BGM and French subtitles.",
    "Make a narrated picture-book audiobook in Tigré about a young Tigré coast fish, with Tigré-folk BGM and Tigrinya subtitles.",
    # ── more major-language city-tour audiobooks + BGM + subtitles (50) ──
    "Cook up a children's audiobook in Italian about a young Florentine apprentice exploring Renaissance Florence, with Tuscan-folk BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Italian about a young gondolier sailing through Venetian canals, with Venetian-baroque BGM and German subtitles.",
    "Produce a narrated children's audiobook in Italian about a young Roman child running through the Forum, with Roman-stornello BGM and English subtitles.",
    "Build a bedtime audiobook in Italian about a young pizza-baker in Naples, with Neapolitan-tarantella BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Italian about a young Sicilian sponge-fisher, with Sicilian-folk BGM and English subtitles.",
    "Make me a picture-book audiobook in Spanish about a young flamenco dancer in Seville, with Andalusian-flamenco BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Spanish about a young Madrileño running through Plaza Mayor, with Spanish-zarzuela BGM and French subtitles.",
    "Generate a children's bedtime audiobook in Spanish about a young Catalan modernism explorer in Barcelona, with Catalan-sardana BGM and English subtitles.",
    "Produce a kids' picture-book audiobook in Spanish about a young child watching Granada's Alhambra at sunset, with Andalusian-classical BGM and English subtitles.",
    "Build an illustrated children's audiobook in Spanish about a young Bilbao steelworker's daughter, with Basque-txistu BGM and Basque subtitles.",
    "Tell me a children's audiobook in Portuguese about a young child fado-dancer in Lisbon, with fado BGM and English subtitles.",
    "Make a narrated picture-book audiobook in Portuguese about a young Porto wine apprentice, with Portuguese-folk BGM and Spanish subtitles.",
    "Render a children's audiobook in French about a young Parisian on a boulevard, with French-musette BGM and English subtitles.",
    "I'd like a bedtime audiobook in French about a young Provençal lavender farmer, with Provençal-folk BGM and German subtitles.",
    "Cook up a children's audiobook in French about a young Marseillais sailor, with French-shanty BGM and Italian subtitles.",
    "Generate a kids' picture-book audiobook in French about a young Strasbourg boulanger, with Alsatian-folk BGM and German subtitles.",
    "Produce a narrated children's audiobook in German about a young Berliner riding the U-Bahn, with Berlin-cabaret BGM and English subtitles.",
    "Build a bedtime audiobook in German about a young Bavarian alpine hiker, with Bavarian-oompah BGM and French subtitles.",
    "Tell me an illustrated children's audiobook in German about a young Hamburger crossing the Alster, with German-shanty BGM and English subtitles.",
    "Make me a picture-book audiobook in German about a young Frankfurter visiting the bourse, with German-folk BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Dutch about a young Amsterdam canal-boat captain, with Dutch-folk BGM and English subtitles.",
    "Generate a children's bedtime audiobook in Dutch about a young Delft-pottery apprentice, with Dutch-folk-2 BGM and French subtitles.",
    "Produce a kids' picture-book audiobook in Dutch about a young Rotterdam dock worker, with Dutch-shanty BGM and English subtitles.",
    "Build an illustrated children's audiobook in Flemish about a young Bruges chocolate-maker, with Flemish-folk BGM and French subtitles.",
    "Tell me a children's audiobook in Russian about a young Moscovite riding the metro, with Russian-balalaika BGM and English subtitles.",
    "Make a narrated picture-book audiobook in Russian about a young St-Petersburg ballerina, with Tchaikovsky-orchestral BGM and English subtitles.",
    "Render a children's audiobook in Russian about a young Trans-Siberian-train traveler, with Russian-orchestral BGM and Mandarin subtitles.",
    "I'd like a bedtime audiobook in Greek about a young child climbing Athens's Acropolis, with Greek-bouzouki BGM and English subtitles.",
    "Cook up a children's audiobook in Greek about a young Santorini fisher, with Greek-rebetiko BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Greek about a young Crete olive-harvester, with Cretan-lyra BGM and English subtitles.",
    "Produce a narrated children's audiobook in Turkish about a young Istanbul-bridge crosser, with Turkish-saz BGM and English subtitles.",
    "Build a bedtime audiobook in Turkish about a young Cappadocia balloon-pilot, with Turkish-makam BGM and German subtitles.",
    "Tell me an illustrated children's audiobook in Arabic about a young Cairo-bazaar merchant, with Arabic-oud BGM and English subtitles.",
    "Make me a picture-book audiobook in Arabic about a young Marrakech-souk apprentice, with Moroccan-andalusian BGM and French subtitles.",
    "Cook up a narrated children's audiobook in Arabic about a young Bedouin in the Empty Quarter, with Bedouin-rebab BGM and English subtitles.",
    "Generate a children's bedtime audiobook in Persian about a young Isfahan miniature-painter, with Persian-tar BGM and English subtitles.",
    "Produce a kids' picture-book audiobook in Hebrew about a young Jerusalem-Old-City explorer, with Israeli-folk BGM and English subtitles.",
    "Build an illustrated children's audiobook in Mandarin about a young Beijing-hutong child, with Chinese-erhu BGM and English subtitles.",
    "Tell me a children's audiobook in Mandarin about a young Shanghai-Bund stroller, with Shanghai-jazz BGM and Japanese subtitles.",
    "Make a narrated picture-book audiobook in Mandarin about a young Xi'an-warrior-tomb visitor, with Chinese-classical BGM and Korean subtitles.",
    "Render a children's audiobook in Cantonese about a young Hong-Kong-Star-Ferry rider, with Cantonese-opera BGM and English subtitles.",
    "I'd like a bedtime audiobook in Japanese about a young Kyoto-tea-ceremony apprentice, with Kyoto-koto BGM and English subtitles.",
    "Cook up a children's audiobook in Japanese about a young Tokyo-shibuya-crossing child, with Japanese-city-pop BGM and Mandarin subtitles.",
    "Generate a kids' picture-book audiobook in Japanese about a young Hokkaido-snow-festival child, with Hokkaido-shakuhachi BGM and English subtitles.",
    "Produce a narrated children's audiobook in Korean about a young Seoul-palace child, with Korean-gugak BGM and English subtitles.",
    "Build a bedtime audiobook in Korean about a young Jeju-haenyeo apprentice, with Korean-pansori BGM and Japanese subtitles.",
    "Tell me an illustrated children's audiobook in Vietnamese about a young Hoi-An-lantern-maker, with Vietnamese-nhã-nhạc BGM and English subtitles.",
    "Make me a picture-book audiobook in Thai about a young Bangkok-tuk-tuk-driver child, with Thai-piphat BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Indonesian about a young Bali-temple child, with Balinese-gamelan BGM and English subtitles.",
    "Generate a children's bedtime audiobook in Tagalog about a young Manila-jeepney child, with kundiman BGM and English subtitles.",
    # ── more Latin-American / Caribbean city-tour audiobooks + regional BGM + bilingual (50) ──
    "Tell me a children's audiobook in Spanish about a young Mexico-City-mariachi-watcher, with mariachi BGM and English subtitles.",
    "Make a narrated picture-book audiobook in Spanish about a young Oaxaca-mole-cook, with Oaxacan-marimba BGM and English subtitles.",
    "Render a children's audiobook in Spanish about a young Yucatán-cenote-diver, with Mayan-flute BGM and Mayan subtitles.",
    "I'd like a bedtime audiobook in Spanish about a young Havana-Malecón-stroller, with Cuban-son-2 BGM and English subtitles.",
    "Cook up a children's audiobook in Spanish about a young Santo-Domingo-Zona-Colonial child, with Dominican-merengue BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Spanish about a young San-Juan-Old-Town child, with Puerto-Rican-bomba BGM and English subtitles.",
    "Produce a narrated children's audiobook in Spanish about a young Cartagena-Walls walker, with Colombian-cumbia-2 BGM and English subtitles.",
    "Build a bedtime audiobook in Spanish about a young Bogotá-Monserrate cable-car-rider, with Andean-bambuco BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Spanish about a young Medellín-Comuna-13 child, with Colombian-reggaeton-2 BGM and English subtitles.",
    "Make me a picture-book audiobook in Spanish about a young Quito-Old-Town child, with Ecuadorian-pasillo BGM and Quechua subtitles.",
    "Cook up a narrated children's audiobook in Spanish about a young Galápagos-iguana-watcher, with Ecuadorian-marimba BGM and English subtitles.",
    "Generate a children's bedtime audiobook in Spanish about a young Lima-Plaza-Mayor child, with Peruvian-criolla BGM and Quechua subtitles.",
    "Produce a kids' picture-book audiobook in Spanish about a young Cusco-Sacsayhuamán child, with Andean-quena BGM and Quechua subtitles.",
    "Build an illustrated children's audiobook in Spanish about a young La-Paz-Cable-car child, with Bolivian-charango BGM and Aymara subtitles.",
    "Tell me a children's audiobook in Spanish about a young Sucre-historic-center child, with Bolivian-cueca BGM and Quechua subtitles.",
    "Make a narrated picture-book audiobook in Spanish about a young Asunción-old-center child, with Paraguayan-polca BGM and Guaraní subtitles.",
    "Render a children's audiobook in Spanish about a young Buenos-Aires-Caminito tango-watcher, with tango-bandoneón-2 BGM and English subtitles.",
    "I'd like a bedtime audiobook in Spanish about a young Patagonia-glacier guide, with Patagonian-folk-2 BGM and English subtitles.",
    "Cook up a children's audiobook in Spanish about a young Mendoza-vineyard child, with Argentine-folklore BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Spanish about a young Santiago-Plaza-Armas child, with Chilean-cueca-2 BGM and English subtitles.",
    "Produce a narrated children's audiobook in Spanish about a young Valparaíso-cerro-graffiti child, with Chilean-tonada BGM and English subtitles.",
    "Build a bedtime audiobook in Spanish about a young Easter-Island-moai-keeper, with Rapa-Nui-folk BGM and Rapa-Nui subtitles.",
    "Tell me an illustrated children's audiobook in Portuguese about a young Rio-Pão-de-Açúcar child, with Brazilian-bossa-nova-2 BGM and English subtitles.",
    "Make me a picture-book audiobook in Portuguese about a young Salvador-Pelourinho child, with axé BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Portuguese about a young São-Paulo-Avenida-Paulista child, with Brazilian-MPB BGM and English subtitles.",
    "Generate a children's bedtime audiobook in Portuguese about a young Brasília-Catedral child, with tropicália-2 BGM and English subtitles.",
    "Produce a kids' picture-book audiobook in Portuguese about a young Recife-Olinda child, with frevo-2 BGM and English subtitles.",
    "Build an illustrated children's audiobook in Portuguese about a young Manaus-Teatro-Amazonas child, with boi-bumbá BGM and English subtitles.",
    "Tell me a children's audiobook in Portuguese about a young Belém-Ver-o-Peso market-child, with carimbó BGM and English subtitles.",
    "Make a narrated picture-book audiobook in Portuguese about a young Curitiba-Botanical-Garden child, with Brazilian-choro BGM and English subtitles.",
    "Render a children's audiobook in Portuguese about a young Florianópolis-Lagoa child, with Brazilian-fandango BGM and English subtitles.",
    "I'd like a bedtime audiobook in Portuguese about a young Porto-Alegre-Mercado child, with Gaucho-vaneira BGM and Spanish subtitles.",
    "Cook up a children's audiobook in Portuguese about a young Foz-do-Iguaçu child, with Brazilian-baião BGM and Spanish subtitles.",
    "Generate a kids' picture-book audiobook in French about a young Port-au-Prince Iron-Market child, with Haitian-rara BGM and Haitian-Creole subtitles.",
    "Produce a narrated children's audiobook in Haitian-Creole about a young Cap-Haïtien Citadelle child, with Haitian-konpa BGM and French subtitles.",
    "Build a bedtime audiobook in French about a young Fort-de-France market child, with Martinican-zouk BGM and Martinican-Creole subtitles.",
    "Tell me an illustrated children's audiobook in French about a young Pointe-à-Pitre child, with Guadeloupean-gwoka BGM and Guadeloupean-Creole subtitles.",
    "Make me a picture-book audiobook in French about a young Cayenne-old-center child, with French-Guianese-zouk BGM and French-Guianese-Creole subtitles.",
    "Cook up a narrated children's audiobook in Dutch about a young Willemstad-Punda child, with Curaçaoan-tumba BGM and Papiamentu subtitles.",
    "Generate a children's bedtime audiobook in Papiamentu about a young Oranjestad-Aruba child, with Aruban-tumba BGM and Dutch subtitles.",
    "Produce a kids' picture-book audiobook in English about a young Bridgetown-Garrison child, with calypso BGM and Bajan-Creole subtitles.",
    "Build an illustrated children's audiobook in English about a young Kingston-Trench-Town child, with reggae BGM and Jamaican-Patois subtitles.",
    "Tell me a children's audiobook in English about a young Port-of-Spain-Carnival child, with Trinidadian-soca BGM and Trinidadian-Creole subtitles.",
    "Make a narrated picture-book audiobook in English about a young Nassau-Bay-Street child, with Bahamian-Junkanoo BGM and Bahamian-Creole subtitles.",
    "Render a children's audiobook in English about a young Havana-Vieja-cigar-roller child, with Cuban-mambo BGM and Spanish subtitles.",
    "I'd like a bedtime audiobook in Spanish about a young Trinidad-de-Cuba colonial-square child, with Cuban-trova BGM and English subtitles.",
    "Cook up a children's audiobook in Spanish about a young Caracas-Avila child, with Venezuelan-joropo BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Spanish about a young Maracaibo-bridge child, with Venezuelan-gaita BGM and English subtitles.",
    "Produce a narrated children's audiobook in Spanish about a young Montevideo-Rambla child, with Uruguayan-candombe BGM and Portuguese subtitles.",
    "Build a bedtime audiobook in Spanish about a young Punta-del-Este beach child, with Uruguayan-murga BGM and Portuguese subtitles.",
    # ── more Pacific / Oceania city-tour audiobooks + native BGM + bilingual (50) ──
    "Tell me an illustrated children's audiobook in English about a young Sydney-Bondi-Beach child, with Australian-surf-rock BGM and Mandarin subtitles.",
    "Make me a picture-book audiobook in English about a young Sydney-Opera-House child, with Sydney-Opera-classical BGM and Italian subtitles.",
    "Cook up a narrated children's audiobook in English about a young Melbourne-Federation-Square child, with Melbourne-indie-rock BGM and Greek subtitles.",
    "Generate a children's bedtime audiobook in English about a young Brisbane-South-Bank child, with Queensland-folk BGM and Mandarin subtitles.",
    "Produce a kids' picture-book audiobook in English about a young Perth-Fremantle child, with Western-Australian-folk BGM and Italian subtitles.",
    "Build an illustrated children's audiobook in English about a young Adelaide-Glenelg child, with South-Australian-folk BGM and German subtitles.",
    "Tell me a children's audiobook in English about a young Hobart-Salamanca-Place child, with Tasmanian-folk-2 BGM and Tasmanian-Aboriginal subtitles.",
    "Make a narrated picture-book audiobook in English about a young Canberra-War-Memorial child, with Canberra-fanfare BGM and Mandarin subtitles.",
    "Render a children's audiobook in English about a young Darwin-Mindil-Beach child, with Top-End-folk BGM and Indonesian subtitles.",
    "I'd like a bedtime audiobook in English about a young Cairns-Esplanade child, with Far-North-Queensland-folk BGM and Yidinji subtitles.",
    "Cook up a children's audiobook in English about a young Gold-Coast-Surfers-Paradise child, with Gold-Coast-pop BGM and Korean subtitles.",
    "Generate a kids' picture-book audiobook in English about a young Sunshine-Coast-Mooloolaba child, with Sunshine-Coast-folk BGM and Mandarin subtitles.",
    "Produce a narrated children's audiobook in English about a young Newcastle-Hunter-Valley child, with Hunter-Valley-folk BGM and Croatian subtitles.",
    "Build a bedtime audiobook in English about a young Wollongong-Lighthouse child, with Illawarra-folk BGM and Macedonian subtitles.",
    "Tell me an illustrated children's audiobook in English about a young Auckland-Sky-Tower child, with Maori-pukāea BGM and Maori subtitles.",
    "Make me a picture-book audiobook in English about a young Wellington-Cuba-Street child, with Wellington-indie BGM and Maori subtitles.",
    "Cook up a narrated children's audiobook in English about a young Christchurch-Cathedral-Square child, with Canterbury-folk BGM and Maori subtitles.",
    "Generate a children's bedtime audiobook in English about a young Queenstown-Lakefront child, with Queenstown-folk BGM and Mandarin subtitles.",
    "Produce a kids' picture-book audiobook in English about a young Rotorua-Te-Puia child, with Te-Arawa-haka BGM and Maori subtitles.",
    "Build an illustrated children's audiobook in English about a young Nelson-Tasman-Bay child, with Nelson-folk BGM and Maori subtitles.",
    "Tell me a children's audiobook in Maori about a young Whangarei-Tutukaka child, with Northland-Maori-pūtātara BGM and English subtitles.",
    "Make a narrated picture-book audiobook in Maori about a young Tauranga-Mount-Maunganui child, with Bay-of-Plenty-Maori BGM and English subtitles.",
    "Render a children's audiobook in Maori about a young Hamilton-Waikato-River child, with Waikato-Maori BGM and English subtitles.",
    "I'd like a bedtime audiobook in Maori about a young Napier-Art-Deco child, with Hawke's-Bay-folk BGM and English subtitles.",
    "Cook up a children's audiobook in Maori about a young New-Plymouth-Coastal-Walkway child, with Taranaki-Maori BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Maori about a young Dunedin-Octagon child, with Otago-Scots-fiddle BGM and Scots-Gaelic subtitles.",
    "Produce a narrated children's audiobook in Maori about a young Invercargill-Bluff child, with Southland-folk BGM and English subtitles.",
    "Build a bedtime audiobook in Samoan about a young Apia-Beach-Road child, with Samoan-pate-2 BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Samoan about a young Pago-Pago harbor child, with American-Samoan-pate BGM and English subtitles.",
    "Make me a picture-book audiobook in Tongan about a young Nuku'alofa Royal-Palace child, with Tongan-lakalaka-3 BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Fijian about a young Suva-quay child, with Fijian-meke-2 BGM and English subtitles.",
    "Generate a children's bedtime audiobook in Fijian about a young Nadi-Mamanuca child, with Fijian-iri-2 BGM and Hindi subtitles.",
    "Produce a kids' picture-book audiobook in French about a young Tahiti-Papeete-market child, with Tahitian-pahu-2 BGM and Tahitian subtitles.",
    "Build an illustrated children's audiobook in French about a young Bora-Bora-lagoon child, with Tahitian-himene-tarava-2 BGM and Tahitian subtitles.",
    "Tell me a children's audiobook in French about a young Moorea-Cook-Bay child, with Marquesan-haka-3 BGM and Tahitian subtitles.",
    "Make a narrated picture-book audiobook in French about a young Marquesas-Hiva-Oa child, with Marquesan-tatu-folk BGM and Marquesan subtitles.",
    "Render a children's audiobook in French about a young New-Caledonia-Noumea child, with Kanak-pilou-2 BGM and Kanak subtitles.",
    "I'd like a bedtime audiobook in Bislama about a young Vanuatu-Port-Vila-market child, with Vanuatu-tamtam-2 BGM and English subtitles.",
    "Cook up a children's audiobook in Pijin about a young Solomon-Honiara-quay child, with Solomon-pan-pipe-2 BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Tok-Pisin about a young Port-Moresby-Ela-Beach child, with Papua-kundu-2 BGM and English subtitles.",
    "Produce a narrated children's audiobook in Tok-Pisin about a young Mt-Hagen Sing-Sing child, with Highland-PNG-chant-2 BGM and English subtitles.",
    "Build a bedtime audiobook in Hawaiian about a young Honolulu-Diamond-Head child, with Hawaiian-slack-key-2 BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Hawaiian about a young Maui-Hana-Highway child, with Hawaiian-pahu-2 BGM and English subtitles.",
    "Make me a picture-book audiobook in Hawaiian about a young Kauai-Waimea-Canyon child, with Hawaiian-ipu BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Hawaiian about a young Big-Island-Volcano child, with Hawaiian-mele BGM and English subtitles.",
    "Generate a children's bedtime audiobook in Marshallese about a young Majuro-Atoll child, with Marshallese-jebwa-2 BGM and English subtitles.",
    "Produce a kids' picture-book audiobook in Pohnpeian about a young Pohnpei-Nan-Madol child, with Pohnpeian-lihli-2 BGM and English subtitles.",
    "Build an illustrated children's audiobook in Chuukese about a young Chuuk-lagoon child, with Chuukese-folk-3 BGM and English subtitles.",
    "Tell me a children's audiobook in Yapese about a young Yap-stone-money child, with Yapese-folk-3 BGM and English subtitles.",
    "Make a narrated picture-book audiobook in Palauan about a young Koror-Rock-Islands child, with Palauan-derebechesiil-2 BGM and English subtitles.",
    # ── more classic European fairy-tale retellings (Grimm / Perrault / Andersen) + BGM (50) ──
    "Tell me a children's audiobook in German about Hansel-and-Gretel-in-the-Black-Forest, with Black-Forest-zither BGM and English subtitles.",
    "I want an illustrated audiobook in German about Snow-White-and-the-Seven-Dwarfs, with Bavarian-folk-2 BGM and English subtitles.",
    "Make me a bedtime audiobook in German about young Cinderella-Aschenputtel by the hazel-tree, with German-Romantic-piano BGM and English subtitles.",
    "Create a picture-book audiobook in German about young Sleeping-Beauty-Dornröschen at the spindle, with Hessian-folk BGM and English subtitles.",
    "Produce an illustrated children's tale in German about Rumpelstiltskin in the spinning-room, with German-zither BGM and English subtitles.",
    "Cook up a narrated children's audiobook in German about Rapunzel in the tower, with Tower-of-Trier-flute BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in German about The-Frog-Prince at the well, with German-folk-flute BGM and English subtitles.",
    "Build a bedtime audiobook in German about Brother-Grimm Brementown-Musicians, with Bremen-Hanseatic-flute BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in German about The-Goose-Girl on the Falada-road, with German-folk-3 BGM and English subtitles.",
    "Make me a picture-book audiobook in German about The-Twelve-Dancing-Princesses underground, with German-court-strings BGM and English subtitles.",
    "Cook up a children's audiobook in German about Hansel-and-Gretel-gingerbread-house finale, with Black-Forest-zither-2 BGM and English subtitles.",
    "Produce a narrated children's audiobook in German about The-Fisherman-and-his-Wife on the Baltic shore, with Baltic-shore-folk BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in German about The-Six-Swans at the linden-tree, with German-Romantic-strings BGM and English subtitles.",
    "Build a bedtime audiobook in German about Iron-John in the dark forest, with Schwarzwald-strings BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in German about The-Star-Money on the cold winter night, with German-celesta BGM and English subtitles.",
    "Make me a picture-book audiobook in French about Little-Red-Riding-Hood-Le-Petit-Chaperon-Rouge, with French-musette BGM and English subtitles.",
    "Cook up a children's audiobook in French about Cinderella-Cendrillon at the ball, with French-Baroque-strings BGM and English subtitles.",
    "Produce a narrated children's audiobook in French about Sleeping-Beauty-La-Belle-au-Bois-Dormant, with French-Baroque-harpsichord BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in French about Beauty-and-the-Beast-La-Belle-et-la-Bête, with French-Romantic-piano-2 BGM and English subtitles.",
    "Build a bedtime audiobook in French about Puss-in-Boots-Le-Chat-Botté, with French-Baroque-recorder BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in French about Bluebeard-Barbe-Bleue, with French-clavichord BGM and English subtitles.",
    "Make me a picture-book audiobook in French about Tom-Thumb-Le-Petit-Poucet, with French-folk-fiddle BGM and English subtitles.",
    "Cook up a children's audiobook in French about Donkey-Skin-Peau-d'Âne, with French-Renaissance-lute BGM and English subtitles.",
    "Produce a narrated children's audiobook in French about Diamonds-and-Toads-Les-Fées, with French-Baroque-viola-da-gamba BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in French about Ricky-with-the-Tuft-Riquet-à-la-Houppe, with French-Baroque-theorbo BGM and English subtitles.",
    "Build a bedtime audiobook in Danish about The-Little-Mermaid-Den-lille-Havfrue, with Copenhagen-Royal-strings BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Danish about The-Ugly-Duckling-Den-grimme-Ælling, with Danish-folk-piano BGM and English subtitles.",
    "Make me a picture-book audiobook in Danish about The-Snow-Queen-Snedronningen, with Nordic-celesta BGM and English subtitles.",
    "Cook up a children's audiobook in Danish about Thumbelina-Tommelise, with Danish-Romantic-harp BGM and English subtitles.",
    "Produce a narrated children's audiobook in Danish about The-Princess-and-the-Pea-Prinsessen-paa-Ærten, with Danish-Royal-piano BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Danish about The-Steadfast-Tin-Soldier-Den-standhaftige-Tinsoldat, with Danish-music-box BGM and English subtitles.",
    "Build a bedtime audiobook in Danish about The-Emperor's-New-Clothes-Kejserens-nye-Klæder, with Danish-Royal-court-strings BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Danish about The-Little-Match-Girl-Den-lille-Pige-med-Svovlstikkerne, with Copenhagen-winter-piano BGM and English subtitles.",
    "Make me a picture-book audiobook in Danish about The-Tinder-Box-Fyrtøjet, with Danish-folk-violin BGM and English subtitles.",
    "Cook up a children's audiobook in Danish about The-Wild-Swans-De-vilde-Svaner, with Danish-bird-flute BGM and English subtitles.",
    "Produce a narrated children's audiobook in Danish about The-Red-Shoes-De-røde-Sko, with Danish-folk-fiddle BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Danish about The-Nightingale-Nattergalen at the Chinese-Emperor, with Chinese-Sino-Danish-flute BGM and English subtitles.",
    "Build a bedtime audiobook in Italian about Pinocchio in Geppetto's-workshop, with Italian-mandolin BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Italian about Pulcinella-Naples-mask, with Neapolitan-tarantella BGM and English subtitles.",
    "Make me a picture-book audiobook in Italian about Calandrino at Boccaccio-Decameron, with Tuscan-vihuela BGM and English subtitles.",
    "Cook up a children's audiobook in Russian about Vasilisa-the-Beautiful in Baba-Yaga's-hut, with Russian-balalaika-2 BGM and English subtitles.",
    "Produce a narrated children's audiobook in Russian about The-Firebird-Zhar-Ptitsa, with Russian-Romantic-piano BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Russian about Ivan-Tsarevich and the Grey-Wolf, with Russian-folk-domra BGM and English subtitles.",
    "Build a bedtime audiobook in Russian about Snegurochka-the-Snow-Maiden, with Russian-celesta BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Russian about Sadko at the Volkhov-river, with Russian-gusli-2 BGM and English subtitles.",
    "Make me a picture-book audiobook in Russian about Ruslan and Lyudmila, with Russian-Romantic-strings BGM and English subtitles.",
    "Cook up a children's audiobook in Czech about Otesanek-the-wooden-baby, with Czech-cimbalom BGM and English subtitles.",
    "Produce a narrated children's audiobook in Czech about Princess-Krasomila in the Šumava-forest, with Czech-folk-fujara BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Polish about Wanda the queen of the Vistula, with Polish-folk-mandolin BGM and English subtitles.",
    "Build a bedtime audiobook in Polish about The-Wawel-Dragon-Smok-Wawelski, with Polish-Highlander-flute BGM and English subtitles.",
    # ── more world creation myths / origin tales + BGM (50) ──
    "Tell me a children's audiobook in Maori about Ranginui-and-Papatuanuku-sky-earth-separation, with Maori-koauau-2 BGM and English subtitles.",
    "I want an illustrated audiobook in Hawaiian about Wakea-and-Papahanaumoku-creation, with Hawaiian-slack-key-4 BGM and English subtitles.",
    "Make me a bedtime audiobook in Tahitian about Ta'aroa-shell-creation-Polynesian, with Tahitian-pahu-drum BGM and English subtitles.",
    "Create a picture-book audiobook in Old-Norse about Ginnungagap-Norse-creation, with Norse-tagelharpa-2 BGM and English subtitles.",
    "Produce an illustrated children's tale in Old-Norse about Ymir-and-the-cosmic-cow-Audhumla, with Norse-langeleik BGM and English subtitles.",
    "Cook up a narrated children's audiobook in Old-Norse about Yggdrasil-World-Tree, with Norse-jouhikko-2 BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Norse about Asgard-and-the-nine-worlds, with Norse-frame-drum-2 BGM and English subtitles.",
    "Build a bedtime audiobook in Middle-Egyptian about Atum-and-the-primordial-mound, with Egyptian-double-pipe BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Middle-Egyptian about Ra's-solar-barque-and-Apophis, with Egyptian-arched-harp BGM and English subtitles.",
    "Make me a picture-book audiobook in Middle-Egyptian about Isis-and-Osiris-Nile-fertility, with Egyptian-sistrum-2 BGM and English subtitles.",
    "Cook up a children's audiobook in Sumerian about Enki-and-Ninhursag-creation, with Sumerian-lyre-of-Ur-2 BGM and English subtitles.",
    "Produce a narrated children's audiobook in Akkadian about Enuma-Elish-Marduk-Tiamat, with Akkadian-arched-harp-2 BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Akkadian about Apsu-and-Tiamat-primordial-waters, with Babylonian-tigi-drum BGM and English subtitles.",
    "Build a bedtime audiobook in Sanskrit about Purusha-Sukta-cosmic-being, with Indian-tanpura-2 BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Sanskrit about Vishnu-and-the-cosmic-ocean, with Indian-rudra-veena-3 BGM and English subtitles.",
    "Make me a picture-book audiobook in Sanskrit about Brahma-the-cosmic-egg-Hiranyagarbha, with Indian-bansuri-3 BGM and English subtitles.",
    "Cook up a children's audiobook in Sanskrit about Samudra-Manthan-churning-cosmic-ocean, with Indian-shankha-conch-2 BGM and English subtitles.",
    "Produce a narrated children's audiobook in Tibetan about Avalokiteshvara-and-the-Tibetan-monkey, with Tibetan-singing-bowl BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Chinese about Pangu-and-the-cosmic-egg, with Chinese-guqin-3 BGM and Modern-Chinese subtitles.",
    "Build a bedtime audiobook in Old-Chinese about Nüwa-mending-the-sky, with Chinese-guzheng-3 BGM and Modern-Chinese subtitles.",
    "Tell me an illustrated children's audiobook in Old-Chinese about Fuxi-and-the-Eight-Trigrams, with Chinese-pipa-3 BGM and Modern-Chinese subtitles.",
    "Make me a picture-book audiobook in Old-Chinese about Shennong-the-Divine-Farmer, with Chinese-erhu-3 BGM and Modern-Chinese subtitles.",
    "Cook up a children's audiobook in Old-Japanese about Izanagi-and-Izanami-creating-Japan, with Japanese-koto-3 BGM and Modern-Japanese subtitles.",
    "Produce a narrated children's audiobook in Old-Japanese about Amaterasu-emerging-from-the-cave, with Japanese-shakuhachi-3 BGM and Modern-Japanese subtitles.",
    "Generate a kids' picture-book audiobook in Korean about Dangun-Tangun-founder-myth, with Korean-piri BGM and English subtitles.",
    "Build a bedtime audiobook in Korean about Jumong-Goguryeo-founding, with Korean-haegeum-3 BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Vietnamese about Lac-Long-Quan-and-Au-Co-100-eggs, with Vietnamese-đàn-bầu-3 BGM and English subtitles.",
    "Make me a picture-book audiobook in Lakota about White-Buffalo-Calf-Woman-pipe, with Lakota-flute BGM and English subtitles.",
    "Cook up a children's audiobook in Iroquois about Sky-Woman-and-Turtle-Island, with Iroquois-water-drum BGM and English subtitles.",
    "Produce a narrated children's audiobook in Diné-Navajo about First-Man-First-Woman-and-the-Four-Worlds, with Navajo-cedar-flute BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Hopi about Spider-Grandmother-Kokyangwuti, with Hopi-flute BGM and English subtitles.",
    "Build a bedtime audiobook in Inuktitut about Sedna-mother-of-the-sea-creatures, with Inuit-throat-singing-3 BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Yoruba about Olodumare-Olorun-and-Obatala-creation, with Yoruba-bata-2 BGM and English subtitles.",
    "Make me a picture-book audiobook in Yoruba about Oduduwa-Ile-Ife-creation, with Yoruba-talking-drum BGM and English subtitles.",
    "Cook up a children's audiobook in Akan about Nyame-and-Asase-Yaa-Sky-Earth, with Akan-fontomfrom-drum BGM and English subtitles.",
    "Produce a narrated children's audiobook in Zulu about uNkulunkulu-First-One-from-the-reeds, with Zulu-isigubhu-drum BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Maasai about Enkai-Ngai-cattle-from-the-sky, with Maasai-vocal-3 BGM and English subtitles.",
    "Build a bedtime audiobook in Dogon about Amma-Nommo-creation-from-Mali, with Dogon-balafon BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Aboriginal-language about Rainbow-Serpent-Dreamtime, with Aboriginal-didjeridu BGM and English subtitles.",
    "Make me a picture-book audiobook in Aboriginal-language about Wandjina-creation-spirits, with Aboriginal-clapsticks-2 BGM and English subtitles.",
    "Cook up a children's audiobook in Quechua about Viracocha-Andean-creator, with Quechua-quena-2 BGM and English subtitles.",
    "Produce a narrated children's audiobook in Quechua about Inti-and-Mama-Killa-Sun-Moon, with Quechua-charango BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Aymara about Tunupa-Andean-creation, with Aymara-zampoña BGM and English subtitles.",
    "Build a bedtime audiobook in Nahuatl about Quetzalcoatl-and-the-Five-Suns, with Nahuatl-teponaztli-drum BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Nahuatl about Aztec-Tonatiuh-fifth-sun, with Nahuatl-huehuetl-drum BGM and English subtitles.",
    "Make me a picture-book audiobook in Mayan-K'iche' about Popol-Vuh-creation, with Mayan-tunkul-drum BGM and English subtitles.",
    "Cook up a children's audiobook in Mayan-K'iche' about Hero-Twins-Hunahpu-Xbalanque, with Mayan-marimba BGM and English subtitles.",
    "Produce a narrated children's audiobook in Finnish about Kalevala-Ilmatar-and-the-egg-of-creation, with Finnish-kantele-2 BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Finnish about Väinämöinen-Kalevala-bard, with Finnish-jouhikko BGM and English subtitles.",
    "Build a bedtime audiobook in Estonian about Kalevipoeg-Estonian-epic, with Estonian-kannel BGM and English subtitles.",
    # ── more classic detective / mystery short-story retellings + BGM (50) ──
    "Tell me a children's audiobook in English about Sherlock-Holmes-A-Scandal-in-Bohemia, with Sherlock-Holmes-Baker-Street-violin BGM and French subtitles.",
    "I want an illustrated audiobook in English about Sherlock-Holmes-The-Red-Headed-League, with Holmes-Red-Headed-League-piano BGM and German subtitles.",
    "Make me a bedtime audiobook in English about Sherlock-Holmes-A-Study-in-Scarlet, with Holmes-Study-in-Scarlet-piano BGM and Italian subtitles.",
    "Create a picture-book audiobook in English about Sherlock-Holmes-The-Sign-of-the-Four, with Holmes-Sign-of-the-Four-strings BGM and Spanish subtitles.",
    "Produce an illustrated children's tale in English about Sherlock-Holmes-The-Hound-of-the-Baskervilles, with Holmes-Baskervilles-orchestral BGM and French subtitles.",
    "Cook up a narrated children's audiobook in English about Sherlock-Holmes-The-Speckled-Band, with Holmes-Speckled-Band-strings BGM and German subtitles.",
    "Generate a kids' picture-book audiobook in English about Sherlock-Holmes-The-Final-Problem, with Holmes-Reichenbach-Falls-orchestral BGM and Italian subtitles.",
    "Build a bedtime audiobook in English about Sherlock-Holmes-The-Empty-House, with Holmes-Empty-House-piano BGM and Spanish subtitles.",
    "Tell me an illustrated children's audiobook in English about Sherlock-Holmes-The-Six-Napoleons, with Holmes-Six-Napoleons-piano BGM and Russian subtitles.",
    "Make me a picture-book audiobook in English about Sherlock-Holmes-The-Adventure-of-the-Dancing-Men, with Holmes-Dancing-Men-piano BGM and Russian subtitles.",
    "Cook up a children's audiobook in English about Hercule-Poirot-The-Murder-of-Roger-Ackroyd, with Poirot-Roger-Ackroyd-piano BGM and French subtitles.",
    "Produce a narrated children's audiobook in English about Hercule-Poirot-Murder-on-the-Orient-Express, with Poirot-Orient-Express-orchestral BGM and French subtitles.",
    "Generate a kids' picture-book audiobook in English about Hercule-Poirot-Death-on-the-Nile, with Poirot-Death-on-the-Nile-orchestral BGM and Arabic subtitles.",
    "Build a bedtime audiobook in English about Hercule-Poirot-The-ABC-Murders, with Poirot-ABC-Murders-piano BGM and Spanish subtitles.",
    "Tell me an illustrated children's audiobook in English about Hercule-Poirot-Five-Little-Pigs, with Poirot-Five-Little-Pigs-piano BGM and Spanish subtitles.",
    "Make me a picture-book audiobook in English about Hercule-Poirot-Curtain-final-case, with Poirot-Curtain-piano BGM and French subtitles.",
    "Cook up a children's audiobook in English about Miss-Marple-Murder-at-the-Vicarage, with Miss-Marple-Vicarage-piano BGM and French subtitles.",
    "Produce a narrated children's audiobook in English about Miss-Marple-The-Body-in-the-Library, with Miss-Marple-Body-Library-piano BGM and German subtitles.",
    "Generate a kids' picture-book audiobook in English about Miss-Marple-A-Pocket-Full-of-Rye, with Miss-Marple-Pocket-Rye-piano BGM and Italian subtitles.",
    "Build a bedtime audiobook in English about Miss-Marple-4-50-from-Paddington, with Miss-Marple-Paddington-piano BGM and Spanish subtitles.",
    "Tell me an illustrated children's audiobook in English about Agatha-Christie-And-Then-There-Were-None, with Christie-And-Then-None-orchestral BGM and French subtitles.",
    "Make me a picture-book audiobook in English about Agatha-Christie-The-Mysterious-Affair-at-Styles, with Christie-Mysterious-Affair-piano BGM and German subtitles.",
    "Cook up a children's audiobook in English about Edgar-Allan-Poe-The-Murders-in-the-Rue-Morgue, with Poe-Rue-Morgue-piano BGM and French subtitles.",
    "Produce a narrated children's audiobook in English about Edgar-Allan-Poe-The-Mystery-of-Marie-Roget, with Poe-Marie-Roget-piano BGM and French subtitles.",
    "Generate a kids' picture-book audiobook in English about Edgar-Allan-Poe-The-Purloined-Letter, with Poe-Purloined-Letter-piano BGM and French subtitles.",
    "Build a bedtime audiobook in English about Edgar-Allan-Poe-The-Gold-Bug, with Poe-Gold-Bug-piano BGM and Spanish subtitles.",
    "Tell me an illustrated children's audiobook in English about Wilkie-Collins-The-Moonstone, with Wilkie-Collins-Moonstone-piano BGM and Hindi subtitles.",
    "Make me a picture-book audiobook in English about Wilkie-Collins-The-Woman-in-White, with Wilkie-Collins-Woman-White-piano BGM and Italian subtitles.",
    "Cook up a children's audiobook in English about G-K-Chesterton-Father-Brown-The-Blue-Cross, with Chesterton-Father-Brown-piano BGM and Polish subtitles.",
    "Produce a narrated children's audiobook in English about G-K-Chesterton-Father-Brown-The-Innocence-of-Father-Brown, with Chesterton-Innocence-piano BGM and German subtitles.",
    "Generate a kids' picture-book audiobook in English about Dorothy-Sayers-Lord-Peter-Wimsey-Whose-Body, with Sayers-Wimsey-piano BGM and French subtitles.",
    "Build a bedtime audiobook in English about Dorothy-Sayers-Murder-Must-Advertise, with Sayers-Must-Advertise-piano BGM and German subtitles.",
    "Tell me an illustrated children's audiobook in English about Raymond-Chandler-The-Big-Sleep, with Chandler-Big-Sleep-jazz BGM and Spanish subtitles.",
    "Make me a picture-book audiobook in English about Raymond-Chandler-The-Long-Goodbye, with Chandler-Long-Goodbye-jazz BGM and Spanish subtitles.",
    "Cook up a children's audiobook in English about Dashiell-Hammett-The-Maltese-Falcon, with Hammett-Maltese-Falcon-jazz BGM and Spanish subtitles.",
    "Produce a narrated children's audiobook in English about Dashiell-Hammett-The-Thin-Man, with Hammett-Thin-Man-jazz BGM and French subtitles.",
    "Generate a kids' picture-book audiobook in English about Patricia-Highsmith-The-Talented-Mr-Ripley, with Highsmith-Ripley-jazz BGM and Italian subtitles.",
    "Build a bedtime audiobook in English about Patricia-Highsmith-Strangers-on-a-Train, with Highsmith-Strangers-on-a-Train-piano BGM and German subtitles.",
    "Tell me an illustrated children's audiobook in English about P-D-James-Cover-Her-Face-Adam-Dalgliesh, with PD-James-Dalgliesh-piano BGM and French subtitles.",
    "Make me a picture-book audiobook in English about Ruth-Rendell-Inspector-Wexford-From-Doon-with-Death, with Ruth-Rendell-Wexford-piano BGM and German subtitles.",
    "Cook up a children's audiobook in Swedish about Stieg-Larsson-Girl-with-the-Dragon-Tattoo, with Larsson-Girl-Dragon-Tattoo-electronic BGM and English subtitles.",
    "Produce a narrated children's audiobook in Swedish about Henning-Mankell-Wallander-Faceless-Killers, with Mankell-Wallander-Skåne-strings BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Swedish about Camilla-Läckberg-Ice-Princess, with Läckberg-Fjällbacka-strings BGM and English subtitles.",
    "Build a bedtime audiobook in Norwegian about Jo-Nesbø-Harry-Hole-The-Bat, with Nesbø-Harry-Hole-jazz BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Danish about Jussi-Adler-Olsen-Department-Q-Keeper-of-Lost-Causes, with Adler-Olsen-Department-Q-piano BGM and English subtitles.",
    "Make me a picture-book audiobook in Icelandic about Arnaldur-Indriðason-Jar-City, with Indriðason-Reykjavik-strings BGM and English subtitles.",
    "Cook up a children's audiobook in Italian about Andrea-Camilleri-Inspector-Montalbano-The-Shape-of-Water, with Camilleri-Vigàta-mandolin BGM and English subtitles.",
    "Produce a narrated children's audiobook in Spanish about Manuel-Vázquez-Montalbán-Pepe-Carvalho-Tatuaje, with Vázquez-Montalbán-Carvalho-jazz BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in French about Georges-Simenon-Maigret-Pietr-the-Latvian, with Simenon-Maigret-Paris-piano BGM and English subtitles.",
    "Build a bedtime audiobook in Japanese about Edogawa-Rampo-The-Two-Sen-Copper-Coin, with Edogawa-Rampo-Tokyo-piano BGM and English subtitles.",
    # ── more Norse myths + BGM (50) ──
    "Tell me an illustrated children's audiobook in Old-Norse about Odin's-quest-for-wisdom-at-Mimir's-Well, with Norse-tagelharpa-Odin BGM and English subtitles.",
    "Make me a picture-book audiobook in Old-Norse about Thor-and-the-Midgard-Serpent, with Norse-lyre-Thor BGM and English subtitles.",
    "Cook up a children's audiobook in Old-Norse about Thor-fishing-for-Jörmungandr, with Norse-lyre-Jörmungandr BGM and English subtitles.",
    "Produce a narrated children's audiobook in Old-Norse about Loki-and-the-mistletoe, with Norse-tagelharpa-Loki BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Norse about Baldur's-death-and-Hel, with Norse-tagelharpa-Baldur BGM and English subtitles.",
    "Build a bedtime audiobook in Old-Norse about Frigg-the-mother-goddess, with Norse-tagelharpa-Frigg BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Old-Norse about Freya-and-the-Brisingamen-necklace, with Norse-tagelharpa-Freya BGM and English subtitles.",
    "Make me a picture-book audiobook in Old-Norse about Freyr-and-the-giantess-Gerd, with Norse-tagelharpa-Freyr BGM and English subtitles.",
    "Cook up a children's audiobook in Old-Norse about Tyr-and-the-binding-of-Fenrir, with Norse-tagelharpa-Tyr BGM and English subtitles.",
    "Produce a narrated children's audiobook in Old-Norse about Heimdall-the-watchman-of-Bifrost, with Norse-tagelharpa-Heimdall BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Norse about the-creation-of-the-world-from-Ymir, with Norse-tagelharpa-Ymir BGM and English subtitles.",
    "Build a bedtime audiobook in Old-Norse about Yggdrasil-the-World-Tree, with Norse-tagelharpa-Yggdrasil BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Old-Norse about Ratatoskr-the-squirrel-of-Yggdrasil, with Norse-tagelharpa-Ratatoskr BGM and English subtitles.",
    "Make me a picture-book audiobook in Old-Norse about Nidhogg-the-dragon-at-the-roots, with Norse-tagelharpa-Nidhogg BGM and English subtitles.",
    "Cook up a children's audiobook in Old-Norse about Hugin-and-Munin-Odin's-ravens, with Norse-tagelharpa-ravens BGM and English subtitles.",
    "Produce a narrated children's audiobook in Old-Norse about Sleipnir-the-eight-legged-horse, with Norse-tagelharpa-Sleipnir BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Norse about Mjölnir-Thor's-hammer-forging, with Norse-tagelharpa-Mjölnir BGM and English subtitles.",
    "Build a bedtime audiobook in Old-Norse about Idunn-and-her-apples-of-youth, with Norse-tagelharpa-Idunn BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Old-Norse about Bragi-the-skald-of-the-gods, with Norse-tagelharpa-Bragi BGM and English subtitles.",
    "Make me a picture-book audiobook in Old-Norse about Sif's-golden-hair, with Norse-tagelharpa-Sif BGM and English subtitles.",
    "Cook up a children's audiobook in Old-Norse about Skadi-the-giantess-and-Njord, with Norse-tagelharpa-Skadi BGM and English subtitles.",
    "Produce a narrated children's audiobook in Old-Norse about the-giants-of-Jotunheim, with Norse-tagelharpa-Jotunheim BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Norse about Thor-disguised-as-Freya-at-Thrym's-feast, with Norse-tagelharpa-Thrym BGM and English subtitles.",
    "Build a bedtime audiobook in Old-Norse about Loki-stealing-Thor's-hammer, with Norse-tagelharpa-Loki-2 BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Old-Norse about Loki-and-Sigyn-with-the-serpent's-venom, with Norse-tagelharpa-Sigyn BGM and English subtitles.",
    "Make me a picture-book audiobook in Old-Norse about Fenrir-the-great-wolf, with Norse-tagelharpa-Fenrir BGM and English subtitles.",
    "Cook up a children's audiobook in Old-Norse about Hel-the-queen-of-the-dead, with Norse-tagelharpa-Hel BGM and English subtitles.",
    "Produce a narrated children's audiobook in Old-Norse about Garm-the-hound-of-Hel, with Norse-tagelharpa-Garm BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Norse about Surtr-the-fire-giant, with Norse-tagelharpa-Surtr BGM and English subtitles.",
    "Build a bedtime audiobook in Old-Norse about Ragnarök-the-twilight-of-the-gods, with Norse-tagelharpa-Ragnarok BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Old-Norse about Vidar-avenging-Odin, with Norse-tagelharpa-Vidar BGM and English subtitles.",
    "Make me a picture-book audiobook in Old-Norse about the-rebirth-of-the-world-after-Ragnarok, with Norse-tagelharpa-rebirth BGM and English subtitles.",
    "Cook up a children's audiobook in Old-Norse about Sigurd-and-the-dragon-Fafnir, with Norse-tagelharpa-Sigurd BGM and English subtitles.",
    "Produce a narrated children's audiobook in Old-Norse about Brynhildr-the-Valkyrie, with Norse-tagelharpa-Brynhildr BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Norse about Beowulf-and-Grendel-Anglo-Saxon, with Norse-lyre-Beowulf BGM and English subtitles.",
    "Build a bedtime audiobook in Old-Norse about Beowulf-and-the-dragon, with Norse-lyre-Beowulf-dragon BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Old-Norse about Ragnar-Lodbrok-and-the-pit-of-snakes, with Norse-tagelharpa-Ragnar BGM and English subtitles.",
    "Make me a picture-book audiobook in Old-Norse about Egil-Skallagrimsson-the-skald, with Norse-tagelharpa-Egil BGM and English subtitles.",
    "Cook up a children's audiobook in Old-Norse about Erik-the-Red-discovering-Greenland, with Norse-tagelharpa-Erik BGM and English subtitles.",
    "Produce a narrated children's audiobook in Old-Norse about Leif-Erikson-finding-Vinland, with Norse-tagelharpa-Leif BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Norse about Harald-Hardrada-Stamford-Bridge, with Norse-tagelharpa-Harald BGM and English subtitles.",
    "Build a bedtime audiobook in Old-Norse about Aud-the-Deep-Minded-of-Iceland, with Norse-tagelharpa-Aud BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Old-Norse about Vali-the-avenger-of-Baldur, with Norse-tagelharpa-Vali BGM and English subtitles.",
    "Make me a picture-book audiobook in Old-Norse about Forseti-the-judge-of-the-gods, with Norse-tagelharpa-Forseti BGM and English subtitles.",
    "Cook up a children's audiobook in Old-Norse about Ullr-the-archer-and-skier, with Norse-tagelharpa-Ullr BGM and English subtitles.",
    "Produce a narrated children's audiobook in Old-Norse about Aegir-the-sea-giant-feast, with Norse-tagelharpa-Aegir BGM and English subtitles.",
    "Generate a kids' picture-book audiobook in Old-Norse about Ran-and-her-net, with Norse-tagelharpa-Ran BGM and English subtitles.",
    "Build a bedtime audiobook in Old-Norse about the-Norns-spinning-fate, with Norse-tagelharpa-Norns BGM and English subtitles.",
    "Tell me an illustrated children's audiobook in Old-Norse about Volund-the-smith, with Norse-tagelharpa-Volund BGM and English subtitles.",
    "Make me a picture-book audiobook in Old-Norse about Andvari-the-dwarf-and-the-cursed-ring, with Norse-tagelharpa-Andvari BGM and English subtitles.",
]

assert len(set(USER_GOALS)) == len(USER_GOALS), "duplicate USER_GOALS within file"
